### ISSUE TITLE
PAR - There are no divisions against the 'Triple Alliance' war on Paraguay and there is no 'Fire' icon (conflict) on South America in the world tension GUI

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1000]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591962/game.zip)

Save game: [USA_south_america_conflict.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591963/USA_south_america_conflict.zip)

### Describe the bug

PAR has no entire divisions to defend against the South American Triple Alliance and this leads PAR completely defeated. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. BRA, ARG, and URG declare war on radical PAR.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190862997-02cd4b2c-46d6-40df-a74f-3f386773ad4d.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190862999-c4062bed-a2c4-49ed-a8de-b71250b4e936.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
