### ISSUE TITLE
USA - Odd decision prerequisites of 'Propose A Ceasefire - Stalemate' decision

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1001]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_south_african_war_negotiation.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9592001/USA_south_african_war_negotiation.zip)

### Describe the bug

Despite the prerequisites of the 'Propose A Ceasefire - Stalemate' decision that the three German Reich Commissioners in Africa are required to more than 100% surrender progress, the Propose A Ceasefire - Stalemate' decision is somehow available. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Has the 'The South Africa War Negotiations' decisions.
3. See the 'Propose A Ceasefire - Stalemate' decision requirement.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190864486-7e236320-6d59-4e10-93aa-76451e8cd642.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Ceasefire trigger code has been rewritten, should be fixed in current release
