### ISSUE TITLE
USA - No localize in decision effect of 'Large Scale Arms Agreements' 

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1002]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_new_ports.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9592791/USA_new_ports.zip)

### Describe the bug

I don't know what causes this.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War continues.
3. Completing the 'New Ports' focus.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190880125-63df03b0-c7bc-48c9-b8a2-fbbcd9b097b2.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Event replaced in UB, no longer a issue
