### ISSUE TITLE
SAF - The AI doesn't select any of the 'Strategic Airlift' decisions

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1004]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9592962/game.zip)

Save game: [SAF.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9592964/SAF.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Observe AI SAF.
2. South Africa War triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190883598-95198231-29da-4e1f-ab11-77c84630ba20.png)

### Additional information

I don't have any additional information

**Comment by runelead00** [comment]
Hopefully fixed in Dev Build
