### ISSUE TITLE
FRI - No localize for 'FRI_Malayan_supply_lines' national spirit

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1005]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9593176/USA_play.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. Free Indonesia revolts.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190888535-41e86663-e61f-40b3-82af-3df6055a61c9.png)

### Additional information

I don't have any additional information

**Comment by runelead00** [comment]
fixed in dev build
