### ISSUE TITLE
INS - There are some national spirits have blank description

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1006]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [SAF.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9592964/SAF.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. See and view INS national spirits.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190888783-616fd445-5848-44ce-8115-d1960f311a44.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190888786-e12f807f-9da4-4501-a9d3-bef2c1ebd9a8.png)

### Additional information

I don't have any additional information

**Comment by runelead00** [comment]
No longer an issue on UB
