### ISSUE TITLE
USA - No localize for 'nav_bomber_equipment'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1007]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_NPP_deplomatic_arena.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9593919/USA_NPP_deplomatic_arena.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Complete some NPP's foreign national focuses through the 'Domestic Preparedness' focus.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190901263-44173555-4d29-42b4-9d62-78f1ee48c6ad.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190901267-4f7d44fb-785d-46fd-a337-2478707279e1.png)

### Additional information

I don't have any additional information

**Comment by Stormeagle449** [comment]
Fixed in UB.
