### ISSUE TITLE
USA - Despite taking agency operation decision, some agency operation decisions are still available

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1009]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_agency_decisions.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9594041/USA_agency_decisions.zip)

### Describe the bug

In my game. When I take one agency operation decision, the agency decisions for IRK (Far Eastern Soviet Socialist Republic) and 'Invest in Novosibirsk' agency decisions are still available despite their requirement to not selected another operation. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Take one agency operation decision.
3. See the agency target on other regions. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190904235-e5616ae5-2f92-4fcd-a1dd-ea1eb3a8f01b.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190904238-7842a7ac-d0e4-4736-ae0c-0825f6dea510.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/190904239-6a9cc6de-426a-4e27-a1d3-e7de023aeb36.png)

### Additional information

I don't have any additional information

**Comment by Stormeagle449** [comment]
These are not operations, they're simple decisions that can be done simultaneously.
