### ISSUE TITLE
GER - 'Scorched Earth on the Ground Scale' focus have target GRO instead of MZB and no localize for 'econ_increase_money_reserves_small'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1011]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_German_defeat_in africa.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9595403/USA_German_defeat_in.africa.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. The OFN intervenes.
3. Goring Germany wins the German Civil War ends and GER intervenes to support Afrika-Schild.
4. SAF, OFN, and its allies defeat the Afrika-Schild. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190932002-cd055c63-8885-4a36-86d0-02073121d537.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190932004-9daa24a9-6b96-4649-9028-a49963737793.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
