### ISSUE TITLE
GER - 'Scorched Earth On A Ground Scale' focus has no targeting USC(Central African Republic), only targeting three

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1013]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_mandates.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9595572/USA_mandates.zip)

### Describe the bug

The explanation is stated in the title.

I don't know if there are decisions of sabotage mandates that target USC mandate instead of three mandates.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. OFN and SAF defeat the Afrika-Schild and GER.
3. The Afrika-Schild collapsed.
4. Choosing the single OFN African mandate.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190934862-c6c78771-4a18-43ef-8308-df39a9a2ded3.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190934868-62171319-bd8d-4a8e-977f-b34c50f96c34.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/190934869-232286ad-76a2-409b-a80c-f02dbc3d91a3.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
