### ISSUE TITLE
GSL - No unique GFX icon for Stabilising Regime' national spirit

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1014]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9596000/USA_game.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Goring Germany wins the German Civil War and Goring becomes the new fuhrer. 
2. GER enact War Plan O.
3. GER attacks Slovakia and Slovakia becomes subject to GER. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190945328-d195996e-9f8a-419a-bf73-59577145cbf9.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
