### ISSUE TITLE
USA - Still embargo on former German and Japanese sphere tags despite they are no longer part of

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1016]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9596262/USA_play.zip)

### Describe the bug

The explanation is stated in the title.

Even OFN African mandates are embargoed by USA. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Some tags have been removed from the German and Japanese economic spheres.
3. USA still embargo on former German and Japanese spheres.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190954491-74d0cfff-b05e-482d-923e-c19b53dd2310.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190954495-a8d13726-388e-4830-ba0a-8518fe1ed7e6.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/190954496-7abd9983-74c7-40d9-8941-de9ee7df2ae8.png)

### Additional information

I don't have any additional information.

**Comment by Stormeagle449** [comment]
Fixed for 1.5.0
