### ISSUE TITLE
USA/JAP - The Co-Prosperity Sphere and OFN are still embargoing each other after the US-Japanese Treaty

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1017]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9596422/game.zip)

Save game: [USA_honolulu_accords_success.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9596424/USA_honolulu_accords_success.zip)

### Describe the bug

Despite the Honolulu Accords' success and the US-Japanese Treaty signed, the OFN and Co-Prosperity Sphere and their economic spheres are still embargoing each other. 

### Steps to reproduce / Cause of the issue

1. The Honolulu Accords are successful.
2. The US-Japanese Treaty was signed.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190957139-efd33556-d245-4c70-88bf-d8667e501e3d.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190957140-ccbf7d22-242e-4ce6-a36d-d2d7723bd0bc.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/190957145-638b64ed-167b-4f0b-9d09-c6a3a6773048.png)

![Untitled_4](https://user-images.githubusercontent.com/71108541/190957147-979cc842-463b-47b4-bab9-af271bbc52cf.png)

### Additional information

I don't have any additional information.

**Comment by Stormeagle449** [comment]
Fixed for 1.5.0
