### ISSUE TITLE
USA - Probably change the GFX icon for 'Focusing on Naval Research', 'Focusing on Aerial Research' and 'Oil Concessions' ideas

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1018]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the GFX icon of 'Focusing on Naval Research', 'Focusing on Aerial Research' and '(Low, Moderate or Significant)Oil Concessions' national spirits should be changed.

The 'Focusing on Naval Research' idea has the Tank graphic, so the Tank graphic should be changed to 'Battleship' or 'combat ship' graphic.
The 'Focusing on Aerial Research' idea has the Tank graphic, so the Tank graphic should be changed to 'Fighter Plane' or 'combat plane' graphic.

The '(Low, Moderate or Significant)Oil Concessions' idea should be changed to 'a Japanese flag with the petroleum oil' or 'a handshake between US and Japan flags, and with petroleum oil' GFX icon or something like this.

### Justifications

The 'Focusing on Naval Research' and 'Focusing on Aerial Research' national spirits have the 'Tank' graphic instead of being based on the idea title and its effects because having the 'Tank' icon with the naval or aerial effects and its title is quite weird, to me.

The '(Low, Moderate or Significant)Oil Concessions' national spirit uses the OFN GFX icon is something weird, to me that the idea is represented to fuel concession (buffing fuel effects) to JAP and debuff fuel effects for USA.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190982398-889db82a-aa0b-452b-a90e-0d66fa025fae.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190982403-c5bd8dc8-65bf-43f5-8efa-0b20f739f565.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/190985865-f45b3929-0d3d-40e8-b691-86331843e674.png)

### Additional information

Save game: [USA_some_ideas.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9597636/USA_some_ideas.zip)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
