### ISSUE TITLE
USA - No localize for 'USA_CIA_WEST_RUSSIA_1_tt'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1020]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9598008/USA_play.zip)

### List the loc issues below

No adding loc in agency decision effect of 'Influence the next Grand Marshal of the WRRF'.
![Untitled_1](https://user-images.githubusercontent.com/71108541/190995740-c55ffc91-b75f-4e68-a58f-200fd3de5ad9.png)

### Additional information

I don't know if there is an unfinished event loc and its effect on `USA_CIA_WEST_RUSSIA_1_tt`.

**Comment by runelead00** [comment]
Fixed in Dev Build
