### ISSUE TITLE
Probably all tags - 'The West African War' super event triggers twice

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1021]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_WAW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9598527/USA_WAW.zip)

### Describe the bug

'The West African War' super event triggers when CAO declares war on FFR which leads to war between the West African Alliance and Pan-African Liberation Front, and the 'The West African War' news event pops out.

However, when selecting the 'The West African War' news event, 'The West African War' super event is triggered again. 

### Steps to reproduce / Cause of the issue

1. Formation of West African Alliance by Wolofia.
2. FRR joins the WAA as a member.
3. Pan-African Liberation Front from by CAO.
4. CAO attacks FFR

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191009902-3b1a2318-c2ba-4531-a67a-940b8e1f64a4.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191009908-b3fbea30-c478-400f-b242-bf5b6f6496cb.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/191009911-7981d01e-9766-4f67-9f11-0692d55795c4.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
