### ISSUE TITLE
USA - No localize for 'USA_WAC_harass_convoys_available_tt'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1022]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9598800/USA_play.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. The West African War triggers.
2. See the 'Harass Convoys' decision's prerequisites.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191016732-82e7f856-fbae-45cf-8134-7e5fddf61ef5.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
