### ISSUE TITLE
USC - No localize for 'OFN_CAR_on_a_mission' and a typo of 'compeltly'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1023]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game; [USC.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9599244/USC.zip)

### List the loc issues below

![Untitled_1](https://user-images.githubusercontent.com/71108541/191027430-a9b47496-c290-4878-b187-54229d0d00cc.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191028379-40b5e565-410f-411f-acb3-61bf778f8553.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
