### ISSUE TITLE
All Tags - Someone forgot to code all nations' unique GFX_anti_air_equipment

### ISSUE THREAD

**Issue by KaranDrakken** [TNODevs/TNO-Bug-Tracker#1025]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Basically I noticed that all nations are using the generic GFX for anti-air equipment, I had a hunch on what it could be so tried looking for the files in the interface folder to see what was wrong and noticed that all nations are missing the 

```
	SpriteType = {
		name = "GFX_anti_air_equipment_1_medium"
		texturefile = "gfx/interface/technologies/AntiAir_45.dds"
	}
	SpriteType = {
		name = "GFX_anti_air_equipment_2_medium"
		texturefile = "gfx/interface/technologies/AntiAir_50.dds"
	}
	SpriteType = {
		name = "GFX_anti_air_equipment_3_medium"
		texturefile = "gfx/interface/technologies/AntiAir_70.dds"
	}
	SpriteType = {
		name = "GFX_anti_air_equipment_4_medium"
		texturefile = "gfx/interface/technologies/AntiAir_90.dds"
	}
```
equivalent in their Technologies_Country.gfx file in the Technologies folder, using then the ones from Technologies_Generic_Army.gfx instead.

### Steps to reproduce / Cause of the issue

1. Go to the tech tree and you'll see that (depending of the nation) there is an unique anti-air equipment icon for it.
2. Go to the production screen and you'll notice that the anti-air equipment that can be produced will show the generic icon instead.

### Expected behaviour

The anti-air equipment icon to be the same as the one shown in the tech tree.

### Screenshots

As an example, here we have the USA's Anti-Air tech tree, showing their unique equipment GFX
![image](https://user-images.githubusercontent.com/113949439/191139680-83519485-a72a-4a7d-bd78-aca6dc546c3a.png) ![image](https://user-images.githubusercontent.com/113949439/191139719-12888a13-fbfd-4267-b306-97fe485ac4a4.png)
But when we look for it in the production menu
![image](https://user-images.githubusercontent.com/113949439/191140824-8d54d9b3-6a3a-4d0c-9285-ee8480f79519.png)
It's the generic GFX icons.

So since I was playing the USA, I went to the Technologies_Country_USA.gfx file to find the problem
![image](https://user-images.githubusercontent.com/113949439/191141098-5d7ada94-dc30-4e3a-a73f-30eea3c81ab4.png)
And noticed they're missing the gfx for the equipment itself, here added as an ad-hoc solution
![image](https://user-images.githubusercontent.com/113949439/191141243-5c651c7b-6679-44ca-81fd-f9007154d543.png)
And now the icons are displaying!
![image](https://user-images.githubusercontent.com/113949439/191141948-68b66129-f96b-4a94-a53a-2efcf4053168.png)

I tired using Notepad++ to see if this was an isolated case of some nations
![image](https://user-images.githubusercontent.com/113949439/191143045-db0df5f0-5391-400c-949f-042bf03ca2c3.png)
but apparently all countries are lacking their respective gfx coding.

### Additional information

It isn't a gamebreaking bug, just something I noticed and thought was odd and thus decided to report it for fixing.

**Comment by runelead00** [comment]
Fixed in Dev Buld, think this got messed up when NSB was integrated
