### ISSUE TITLE
USA - Gives a decrease 100 political power, stability, and war support instead of just '0' in the 'Chaos in the CAR' world news event

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1026]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9604300/USA_game.zip)

### Describe the bug

The world news event of 'Chaos in the CAR' give '0' for political power, stability and war support, but instead, it gives a decrease of '100' than changing to '0'. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. SAF and OFN win against the Afrika-Schild and GER.
4. The Afrika-Schild collapsed and switch to OFN mandates.
5. Choosing a single mandate (USC) instead of three.
6. Conference fails in USC.
7. USC chose to war against the rebels.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191173464-c0fb568d-7723-461f-9068-29b70ed5ecd9.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191173478-2a15c443-ff18-4e3a-a5a6-d6332744035e.png)

### Additional information

I don't have any additional information.

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
