### ISSUE TITLE
USA/NOR - Small issues for volunteers to NOR and BLR takes the '94' state

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1027]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9604471/game.zip)

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9604473/USA_play.zip)

### Describe the bug

The 'Military Advisors' idea for NOR is still exists despite GER and NOR are at peace, and BLR has taken control of 'Nordstern' state for an unknown reason, I don't know why.

### Steps to reproduce / Cause of the issue

1. Goring becomes the new Fuhrer of GER after GCW.
2. Goring enacts war plan A and attacks NOR.
3. USA sends support and volunteers to NOR through the 'Aid for Norway?' event.
4. GER and NOR are at peace due to high troubles in Greater German Reich, probably an economic crisis or something like this.
5. Schörner Coup in GER.
6. BLR, EST, and LAT pop out in OST.
7. BLR takes the 'Nordstern' state and cores it.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191178014-0be28040-6b60-4e2b-9678-6ed817922080.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191178021-0a3d6c2f-61ae-40d6-891d-319f4528ca13.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/191178024-8f8f64e8-49a1-4d6d-a32d-e9c9b0313df9.png)

![Untitled_4](https://user-images.githubusercontent.com/71108541/191178025-119b6e18-c5a7-426a-85ea-8aeffab6f6ac.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Hopefully fixed in dev build... we'll see
