### ISSUE TITLE
ITA - The 'Shake the Pact' and 'Last Stand' national spirits have no unique GFX icons

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1028]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_italy_national_spirits.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9611945/USA_italy_national_spirits.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as any feature tags.
2. See ITA's national spirits.

### Expected behaviour

Probably not adding them yet. 

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191386346-a6d0b2f8-d0c7-4a1d-b4c4-186fb86c0282.png)

### Additional information

I don't have any additional information.

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
