### ISSUE TITLE
ALL tags - There is no 'fire' GFX icon on 'East Africa' and 'Middle East' conflict in the 'World Tension Map' GUI when there is conflict on the regions

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1031]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_middle_east_cw.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9613084/USA_middle_east_cw.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Italian East Africa collapsed.
2. ETB and ORM are at war.
3. Oil Crisis triggers.
4. Sudanese Civil War occurs.

### Expected behaviour

Forgot to add them, probably.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191417764-10c97e9c-05b4-4e31-bd6f-5a2118fead4a.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
