### ISSUE TITLE
USA - There is no focus effect of 'The Iranian Civil War'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1032]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_iran_cw.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9616123/USA_iran_cw.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Troubles in Iran.
3. The assignation of Mohammed Reza Pahlavi.
4. Start the Iranian Civil War.

### Expected behaviour

Forgot to add focus effects, maybe?

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191493017-a57dfff7-9057-40fe-a7f0-19f136081bc8.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191493032-0107c962-3f6b-4904-a816-c3aa53bbcbfe.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build, auto bypassed with tooltip
