### ISSUE TITLE
USA - No localize for 'USA_IRCW_sending_loans'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1033]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_iran_cw_decisions.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9616465/USA_iran_cw_decisions.zip)

### List the loc issues below

No loc for prerequisites of 'Approve Loans for the Liberals' decision.

![Untitled_1](https://user-images.githubusercontent.com/71108541/191502649-40662db1-646e-44f3-9a2a-2cb177a400eb.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
