### ISSUE TITLE
USA - Some issues for event's effects of 'Long Term or Short Term?' 

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1034]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game; [USA_long_or_short_term.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9617246/USA_long_or_short_term.zip)

### Describe the bug

No localize for `USA_IRCW_protracted_warfare` and `USA_IRCW_swift_warfare` national spirits, and the protracted warfare idea has `+0.0` for Division Organization instead of 10.0% or something like this.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Iran Civil War has begun.
3. Has the Iran Civil War focus tree.
4. Completing the 'To Free the Oppressed' focus.

### Expected behaviour

Forgot to adding localization or code mistake, maybe, and double check the division organization codes.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191524901-4ec45297-bc13-4a45-87d7-10d4141ef253.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191524915-80e47a02-5053-4cd8-bac3-3eb25bdec617.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/191524916-e9122161-f00e-4ecb-a2f2-fb6c1d511e11.png)

![Untitled_4](https://user-images.githubusercontent.com/71108541/191525429-c4c48da3-9d7e-4132-b5f2-10072e6c529a.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
