### ISSUE TITLE
GER - Schörner Germany doesn't have ability to send support to Ba'athism, Pan-Arabism or Socialist Arabs during the Oil Crisis

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1036]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_towards_oil_crisis.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9617970/USA_towards_oil_crisis.zip)

### Describe the bug

Despite Schörner overthrowing Goering is considered an ending but a bad ending and caused the economy to collapse, GER divisions, political power, and the tag itself are still intact. However, Schörner's GER is not able to support the Arab rebels (i.e. socialist Arab tags).

### Steps to reproduce / Cause of the issue

1. Goering wins the German Civil War.
2. Increases anger of militarists.
3. Schörner coup against Goering.
4. German economy has collapsed.
5. Oil Crisis triggers.
6. GER did nothing to support the Arab rebels.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191542619-799f7267-e084-464e-b543-ea7feb05434a.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191542629-fbd6aa04-6312-4efb-91dc-b6e735d98ea5.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Goering has been skeletonized, no longer an issue in current release
