### ISSUE TITLE
USC - No localize for 'USC_CAR_WAR_establishment_in_progress'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1037]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USC.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9621699/USC.zip)

### List the loc issues below

Some prerequisites of 'Establish Free <African state>' decisions have not yet been localized. 

![Untitled_1](https://user-images.githubusercontent.com/71108541/191644428-1f34c204-f227-482f-a3cd-eeafa1d57f6a.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
