### ISSUE TITLE
USC - 'The Great African Disaster'(path for war) decisions are reappear after taking out the African rebels

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1038]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USC_war_victory.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9621809/USC_war_victory.zip)

### Describe the bug

'The Great African Disaster'(path for war) decisions can appear when completing the 'Stand Our Ground' focus and the decisions will disappear when CAR collapsed. However, after retaking out the rebels, 'The Great African Disaster' appears again. 

### Steps to reproduce / Cause of the issue

1. The Central African Republic is formed.
2. Conference fails (always fails, unfortunately despite the administrations and military stations are high status).
3. USC chooses to warpath focuses.
4. Chaos in CAR.
5. USC managed to defeat the rebels.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191647479-383a8704-89cd-4bc2-8a38-1428b7b4b183.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191647482-2220471b-f36a-4f38-89f0-db8703589e79.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
