### ISSUE TITLE
USA - Some decisions didn't increase its manned preparedness 

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1039]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_space_suit_decision.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9621970/USA_space_suit_decision.zip)

### Describe the bug

Some decisions to increase the manned preparedness mission didn't increase the preparedness of the 'manned' program in the Mission Control decision.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect John Glenn.
3. Have selected a decision to increase the chance of a manned preparedness mission.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191652893-7f50aef7-e4d2-457a-a3c3-b99c34db7723.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191652895-16f88f47-22ea-423f-b048-c41db219db37.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/191652896-2b6a0e25-0d7b-4bad-b3c8-cc1247babef6.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Deprecated Content, getting removed in UB
