### ISSUE TITLE
USA - Some focuses and events' effects show the states have no effect for them, just only see the states

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1040]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save games: 
[USA_with_charity_for_all.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9622318/USA_with_charity_for_all.zip)
[USA_rally_the_progressive_focus.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9622381/USA_rally_the_progressive_focus.zip)
[USA_they're_over_there.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9622385/USA_they.re_over_there.zip)
[USA_dinner_with_king_event.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9622393/USA_dinner_with_king_event.zip)
[USA_don't_rain_on_my_parade.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9622397/USA_don.t_rain_on_my_parade.zip)
[USA_one_angry_elephant.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9623032/USA_one_angry_elephant.zip)

### Describe the bug

The explanation is stated in the title.

Some focuses and events have the same issues instead of just seeing the screenshots. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. See the effects of the focuses and events on the states' effect.

### Expected behaviour

I don't know, unfortunately. 

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191676931-02d3e4bd-99a1-4e61-9d7a-4b6317c7a96d.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191676944-b62bee66-ee79-4ad6-9bfd-ebd0303ade04.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/191676949-136f1b58-eb12-4703-8665-e44bdb139efe.png)

![Untitled_4](https://user-images.githubusercontent.com/71108541/191676953-8dd5cb33-86f7-4b14-bc33-454ecd467c1c.png)

![Untitled_5](https://user-images.githubusercontent.com/71108541/191676954-d06f7326-6cd1-40a1-9443-ae9cdae39421.png)

![Untitled_6](https://user-images.githubusercontent.com/71108541/191676961-fd1cf4be-868b-45a6-955c-37d9a7533b47.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Changed in UB to fit with new election system, no longer an issue
