### ISSUE TITLE
USA - No localize for 'USA_GLN_NASA_Budget_Up_Really_small'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1041]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game; [USA_a_shady_investor.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9623127/USA_a_shady_investor.zip)

### List the loc issues below

The second option of 'A Shady Investor' event has no localize for NASA gain a small budget.

![Untitled_1](https://user-images.githubusercontent.com/71108541/191679594-056ea6e1-aeea-430d-98de-1adbb9de565f.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Deprecated Content, getting removed in UB
