### ISSUE TITLE
USC - Some issues about after completing the 'Farewell Africa' focus when USC winning the war

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1042]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9625874/game.zip)

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9625878/USA_play.zip)

### Describe the bug

When Westmoreland decided to let Africans go to do their own thing after USC wins against the rebels and established free states for Africans through decisions (I don't know if this is meant for a pro-OFN thing), most of the African states are not in OFN economic sphere and OFN observer, and there are some radical African still states exist (fascism and socialism) despite they one of the rebels who declares war on OFN during the Chaos in CAR, their governments should be changed.

And also, there is no unique portrait of 'Marcus Walker;.

### Steps to reproduce / Cause of the issue

1. The Central African Republic is formed.
2. Conference fails (always fails, unfortunately despite the administrations and military stations are high status).
3. USC chooses to warpath focuses.
4. Chaos in CAR.
5. USC managed to defeat the rebels.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191752035-6d4d339b-cbf4-4c42-9c41-15eeb71ff166.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191752044-9e517066-6f31-460d-b59a-da4175836891.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/191752047-64ad0874-54bb-4dae-9c9d-1e6b603e9c5e.png)

![Untitled_4](https://user-images.githubusercontent.com/71108541/191752051-e5d67abb-f14d-4e0f-aa9c-c6ef66385e85.png)

![Untitled_5](https://user-images.githubusercontent.com/71108541/191755627-0c74fe52-4573-4e88-8b96-205f2557b3db.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Correct leader and pop added to Zambia, Katanga will not longer appear in victory, Mozambique changes leader from African Crisis, and all become observers and join the sphere if successful
