### ISSUE TITLE
USA - 'The African Mandates' decision still exists despite the CAR's dissolution after USC wins against the rebels

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1043]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9626193/USA_play.zip)

### Describe the bug

The explanation is stated in the title. 

And also, there is no world news event pops out about the CAR dissolved after USC wins against the rebels or OFN carved CAR (USC crisis diplomatic path) or something like this, and the 'conflict' in Africa is still ongoing on the world tension map despite the African are not fighting.

### Steps to reproduce / Cause of the issue

1. The Central African Republic is formed.
2. Conference fails (always fails, unfortunately despite the administrations and military stations are high status).
3. USC chooses to warpath focuses.
4. Chaos in CAR.
5. USC managed to defeat the rebels.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191758547-64271e53-84ee-411b-b8ef-16d65e14e712.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191758563-0b12a8ee-92f9-4e1d-8b89-e482a289a36f.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/191896074-571cdff0-93b0-4708-92c0-6640ff5ea018.png)

### Additional information

I don't have any additional information.

**Comment by Stormeagle449** [comment]
Fixed in current version.
