### ISSUE TITLE
All tags - The conclusion of Iranian Civil War is not added in Cold War rankings from the cold war view diplomacy tab

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1045]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_end_of_IRCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9626783/USA_end_of_IRCW.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Iranian Civil War starts.
2. The aftermath of the Iranian Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191776239-9df2bb20-2c01-4305-8bc9-4e200ef7ac9f.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
