### ISSUE TITLE
USA - Some issues for 'Sunset in Bahrain' event

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1046]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game; [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9629897/USA_play.zip)

### Describe the bug

The 'Sunset in Bahrain' event describes that JAP is supporting pan-Arabists instead of supporting radical religious Arabists and the event's effect targets pan-Arabist tags instead of radical religious Arabists (like the Egyptian Muslim Brotherhood, Islamic Republic of Iraq, and others) because, during the Oil Crisis, JAP has the decisions to send support to most of highly or radical religious Arabists if ITA is not allied with JAP while GER has the decisions to send support to Ba'athist or pan-Arabists.

So, the event should be targeting 'Muslim Brotherhood, Sudanese Defense Force, Islamic Republic of Iraq, and Imamate of Oman because they are backed by JAP during their struggle. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. ITA goes democratic and joins the OFN after USA successfully persuades ITA. 
3. Oil Crisis triggers.
4. Has the Oil Crisis' Italy focus tree.
5. Complete the 'The Sun Never Rises' focus.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191866186-aaa1d555-768e-4e83-b4ef-80e56c1f92b9.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
