### ISSUE TITLE
USA - Some event have no localize effects for economy decrease money reserves small and large

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1047]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9630066/USA_game.zip)

### List the loc issues below

No localize for `econ_decrease_money_reserves_small` and `econ_decrease_money_reserves_large`.

![Untitled_1](https://user-images.githubusercontent.com/71108541/191870967-c8c3e4c7-deed-4353-9629-14c622ba7ec2.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191872817-f1206f1d-8a77-4d3e-afc6-37de06ed940f.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
