### ISSUE TITLE
USA - 'The Iran Civil War' focus GFX icon uses the in-real-life Iran flag instead of IRL's flag

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1049]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_iran_cw.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9632921/USA_iran_cw.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Oil Crisis triggers.
3. Iran Civil War triggers.
4. Has the Iran Civil War focus tree.

### Expected behaviour

Probably not adding them yet.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191943738-45ff7475-17bb-4eba-98df-01dd8dd38a79.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191943747-95db81ef-ee49-4bee-ba7c-d549aeaf3548.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Cut in Dev Build
