### ISSUE TITLE
USA - No localize prerequisites of the 'Promise More American Equipment' decisions

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1050]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_IRCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9633064/USA_IRCW.zip)

### Describe the bug

No loc for `USA_IRCW_faster_equipment_shipment`s and `USA_IRCW_new_contracts`.

And I don't know whether there is an effect or not on M-I-C contracts decision. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Oil Crisis triggers.
3. Iran Civil War triggers.
4. Complete the 'Promise More American Equipment' focus and the rest.

### Expected behaviour

Forgot to add prerequisites loc, I think.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191948464-61a328c8-1a33-4fc9-afb3-44fbb0969cdc.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
