### ISSUE TITLE
USA - 'The Naples Conference' focus is not unlock after electing second option from 'OIL.500' event

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1051]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_italy_oil_focuses.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9633444/USA_italy_oil_focuses.zip)

### Describe the bug

When after selecting the second option from 'The Oil Must Flow' event, 'The Naples Conference' focus is not unlocked, unfortunately.

While after selecting the first option from 'The Oil Must Flow' event, 'A Company Man' focus is unlocked.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. ITA goes democratic and joins the OFN after USA successfully persuades ITA. 
3. Oil Crisis triggers.
4. Has the Oil Crisis' Italy focus tree.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191957649-af7779f0-c9e4-45a1-b8de-b68469cb555f.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191957653-571f7207-3452-4d9d-a463-2986d99976d7.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/191957658-ba6dd4aa-75c6-408b-8856-d3fc3e8b73a3.png)

![Untitled_4](https://user-images.githubusercontent.com/71108541/191957661-45ca0f81-ac74-4e97-b349-57b520c33a3c.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
