### ISSUE TITLE
USC - Some issues for 'On Our Terms' event

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1052]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USC.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9633670/USC.zip)

### Describe the bug

- The 'On Our Terms' event effect shows that USC can no longer be subject to USA when selecting the option but the formation of USC(Central African Republic) can become independent and not in a faction of OFN, not USC becomes a subject of USA after the formation. 

- The 'Benefits from Logistical Preparations', 'Benefits from our Equipment Stock', and 'Benefits from the Quality from our Troops' ideas are added after taking the event. 

- And also. all divisions are not transferred to the African east coast after taking the 'On Our Terms' event or wait until the decision time fails to trigger the African Crisis that which leads to some divisions being encircled when the war starts. 

### Steps to reproduce / Cause of the issue

1. The Central African Republic is formed.
2. Conference fails (always fails, unfortunately despite the administrations and military stations are high status).
3. USC chooses to warpath focuses.
4. Complete all path to war focuses.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/191977034-1194a58b-faea-4b80-b0fa-4699821f6000.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191979934-5ee15435-9966-4120-ba8b-592e4635adec.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build, except encircled divisions which WAD
