### ISSUE TITLE
USC - William Westmoreland's description is refers to East Africa Mandate instead of Central African Republic after the formation

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1053]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_mandates.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9634446/USA_mandates.zip)

### List the loc issues below

![Untitled_1](https://user-images.githubusercontent.com/71108541/191982890-d2347046-99ec-4285-a464-66fd93ceaf99.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/191982902-0bba43ad-94e9-4e55-86bc-4c51b5a79715.png)

### Additional information

I don't have any additional information.

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
