### ISSUE TITLE
GER/JAP/USA - Slight issue for the global conflict GFX map for Iran CW 

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1055]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_towards_IRCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9637689/USA_towards_IRCW.zip)

### Describe the GFX issue

The global conflict GFX map for Iran CW is slightly different to the current in-game version of the Iran Civil War border fronts. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Oil Crisis triggers.
3. Iran Civil War triggers.

### Expected behaviour

Forgot to changed the global conflict GXC map for IRCW when the Iran CW border fronts are change, maybe.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/192074819-161315c7-113c-4a4d-92f9-a45e3e6debfd.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Not spending resources on new forpol icon until new Iranian setup releases
