### ISSUE TITLE
ITA - Some issues for Goering situation focus tree after 'Mission to Bordeaux' focus

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1056]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [ITA_anti-goering_focus_tree.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9637823/ITA_anti-goering_focus_tree.zip)

### Describe the bug

- The 'Threaten Sanctions Against France' focus has no effect.

- The 'Radia France Libre' focus effect gains negative stability by 5 to FRA instead of positive or buffing. 

- The 'Italian Volunteer Brigades' focus effect gains a national spirit to FRA that gives negative weekly manpower by 500 instead of positive or buffing.

### Steps to reproduce / Cause of the issue

1. ITA chooses the democratic path.
2. Goering wins the German Civil War.
3. ITA has an election and its conclusion.
4. Has the democratic anti-Goering Germany focus tree.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/192077975-6a78f51d-9476-40b3-a3f6-07c3d78d3f5d.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/192077977-59bd4405-2c9b-45f0-a242-75d010fb5932.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/192077978-6e3aa3ad-8acb-4a81-ac34-f256b2f4ad10.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
First one Fixed in Dev Build, Other 2 working as designed
