### ISSUE TITLE
GER - Slight issues for GFX icon for 'War Plan O' and 'War Plan A'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1057]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [GER.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9637928/GER.zip)

### Describe the GFX issue

The GFX icon of 'War Plan O' focus does not include the Netherlands to be the target, which means highlight red on HOL despite this focus can allow attacking HOL. 

The GFX icon of 'War Plan A' does not include the Netherlands to be highlighted as blue because highlighted regions mean conquered.  

### Steps to reproduce / Cause of the issue

1. German Civil War triggers.
2. Goering wins the GCW.

### Expected behaviour

Probably, a oversight. 

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/192079574-29519c7f-eddd-411b-a820-3ddcb0430b03.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Goering has been skeletonized, no longer an issue
