### ISSUE TITLE
USA - Wrong Unit flag

### ISSUE THREAD

**Issue by epicbruhmoment00** [TNODevs/TNO-Bug-Tracker#1058]
### Operating System

macOS Monterey

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Unit flags for some nations (USA, Canada, Japan, Burgundy, and some others) aren't correct. For the US this issue is resolved when the country leader changes, but it comes back when I reload the game. Some countries aren't affected, like Germany.

### Steps to reproduce / Cause of the issue

I just opened the game. It's been like this ever since I got TNO. I've cleared my cache, reinstalled the game & the mod, used -opengl in Steam properties, verified integrity of game files, nothing worked.

### Expected behaviour

Expected the correct flags for the correct country to show up.

### Screenshots

![20220903190722_1](https://user-images.githubusercontent.com/114277978/192082208-1c22b15d-7c43-401d-94d8-ae135931b1c1.jpg)

**Comment by epicbruhmoment00** [comment]
The issue has persisted in TT3 as well. I'm dealing with things like Mexican Slovakia, Puerto Rican Netherlands, Jamaican Generalgouvernement... extremely frustrating bug.
<img width="1440" alt="Screen Shot 2022-10-16 at 12 29 37 PM" src="https://user-images.githubusercontent.com/114277978/196016593-f54b034e-1df1-4f4f-b6a2-e54bc8f8f648.png">

**Comment by runelead00** [comment]
Paradox bug, we can't fix it
