### ISSUE TITLE
BUL - No divisions are added when playing the game

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1060]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [ITA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9638543/ITA.zip)

### Describe the bug

Bulgaria has no divisions when starting the game and BUL can't able to produce weapons due to there are no power grids in BUL lands. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. See BUL's divisions.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/192094326-d7ee8bf3-1703-4a9f-b288-8de99e04e208.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
