### ISSUE TITLE
All feature tags - No unique portraits for operatives

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1061]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [GER.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9640497/GER.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. Has the agency.
3. Operative available.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/192138320-a443b8f6-b091-4404-805e-6dda56ea38b5.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
We currently do not have operative portraits
