### ISSUE TITLE
ITA - Some Malta Conference events have described that Cyprus is controlled by Italian but ITA is not owning Cyprus

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1062]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [ITA_border_conference.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9640900/ITA_border_conference.zip)

### List the loc issues below

The current version of this public mod, Cyprus is controlled by Greece though GRE is subject to ITA but some Triumvirate conference events described that Cyprus is controlled by Italian or referred to ITA is owning Cyprus.  

![Untitled_1](https://user-images.githubusercontent.com/71108541/192147628-f529d1c4-c78f-4838-8148-681cbbafee78.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/192147630-da945c62-231e-4b81-88a7-232d726f7044.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Loc on first event fixed in dev build, World event kept as is.
