### ISSUE TITLE
Zlatoust Peace Deal Crash

### ISSUE THREAD

**Issue by Lazanah** [TNODevs/TNO-Bug-Tracker#1066]
### Operating System

Windows 10

### HOI4 version

1.11.13.886b

### TNO version

1.2.1c

### Do you have other mods in use?

NO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9646788/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9646789/error.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9646790/system.log)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9646816/autosave.zip)

### Describe the crash

While playing as Central Siberian Republic game crashes to desktop around 12th - 16th April

### Steps to reproduce / Cause of the crash

Open save and play as Central Siberian Republic
Unpause the game and run time until 12th - 16th April
Game will crash to desktop

**Comment by runelead00** [comment]
Fixed in Dev Build
