### ISSUE TITLE
COG(ANG & GRO maybe) - No unique GFX icon of 'The Fatherland Arrives' national spirit

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#1067]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [ITA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9653455/ITA_play.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. German Civil War triggers.
2. Afrika-Schild forms.
3. Boers Republic and South Africa are at war.
4. GRO attacks SAF and the Afrika-Schild intervenes.
5. OFN intervenes and helps SAF.
6. Either Speer or Bormann wins the GCW.
7. GER intervenes and helps the Afrika-Schild.

### Expected behaviour

Probably code mistake or forgot to add the unique idea icon.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/192474520-1331e29b-330b-4c70-919d-db0b6b299438.png)

### Additional information

I don't have any additional information.

**Comment by Stormeagle449** [comment]
Fixed for UB.
