### ISSUE TITLE
USA - SAW decision giving way too much money

### ISSUE THREAD

**Issue by mork73** [TNODevs/TNO-Bug-Tracker#1068]
### Operating System

Windows 10 

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

TNO: USA GUI rework

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Usa decision to send over guns to South Africa gives a spirit that gives 15 Billion Dollars income. Making the sale of 750 guns account for a quarter of the Us revenue

### Steps to reproduce / Cause of the issue

1. Play as USA
2. Wait for the SAW to break out
3. Send South Africa guns
4. Profit

### Expected behaviour

Getting less money

### Screenshots

![image](https://user-images.githubusercontent.com/41652769/193124196-a88f5ff0-feba-431d-bfda-30d7f32fd0d1.png)
![image](https://user-images.githubusercontent.com/41652769/193124708-dbbe8f37-3561-4f4e-967a-672480d69657.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
