### ISSUE TITLE
ENG - Various typos for Stirling's England

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1069]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. event FEN_MSA.2 "Those Who Stand With Us"
     In the final sentence of the first paragraph, "She'd be a handful he was sure but" should be "She'd be a handful, he was sure, but".
     In the fourth sentence of the second paragraph, "would get them it would have" should be "would get them, it would have".
     In the second sentence of the third paragraph, "hadn't fallen over the ideas" should be "hadn't fallen for the ideas".
     ![CaptureSTIR](https://user-images.githubusercontent.com/80563255/192709715-551ba0ae-5ced-455a-85f4-089785f0e708.PNG)

2. event FEN_MSA.17 "A Coronation of Arms"
     In the first sentence of the second paragraph, "touch of collaboration she'd been told" should be "touch of collaboration, she'd been told".
     In the third sentence of the second paragraph, "throne even in absence of her presence on British soil had" is a bit clunky and should also have commas for clarification, it could instead be "throne, even in her absence from British soil, had".
     In the final sentence of the second paragraph, "sat about beside those" should be either "sat beside those" or "sat about besides those" depending on the intended meaning.
     In the first sentence of the third paragraph, "Men, and even a few women standing" should be either "Men and even a few women standing" or "Men, and even a few women, standing".
     ![CaptureSTIR2](https://user-images.githubusercontent.com/80563255/192713921-b81e6791-adb7-4ef5-9622-54aa57bf1db5.PNG)

3. event FEN_MSA.6 "The Soldier and the State"
     In the final sentence of the fourth paragraph, "in his cabinet as "advisors" positions that" should be "in his cabinet as "advisors", positions that".
     In the first sentence of the fifth paragraph, "politicization" should probably be "politicisation" since British spellings seem to be the default for the ENG localization.
     In the first sentence of the sixth paragraph, "save the British people from its" should be "save the British people from their".
     ![CaptureSTIR3](https://user-images.githubusercontent.com/80563255/193119672-1d94bcdf-0f54-4cd6-b1df-b19997e3a9d2.PNG)

4. event FEN_MSA.7 "A Small Royal Slight"
     In the first sentence, "David Stirling, and the returned Queen" should be "David Stirling and the returned Queen".
     In the second sentence, "flashes of cameras was dazzling" should be "flashes of cameras were dazzling" or "camera flashes were dazzling".
     In the third sentence of the final paragraph, "leave the Queen now, and perhaps sully" should be "leave the Queen now and perhaps sully".
     ![CaptureSTIR4](https://user-images.githubusercontent.com/80563255/193121211-fda7c431-33d7-4594-b033-4af673eb04f6.PNG)

5. event FEN_MSA.5 "To Defend Democracy"
     In the second sentence of the fifth paragraph, "as the primary mechanism, but one which would not outright destroy the law, but" is a bit awkward with two uses of the word "but" in succession and an excess comma. It could instead be "as the primary mechanism, one which would not outright destroy the law but".
     Also, "democracy" in the second sentence uses quotes while 'oversight' in the first sentence of the final paragraph uses apostrophes, they should probably be consistent with each other.
     ![CaptureSTIR5](https://user-images.githubusercontent.com/80563255/193124221-3f9d2ecb-281f-446d-8c20-24e58403e829.PNG)

6. event FEN_MSA.8 "Bringing Out the Skeletons"
     In the second sentence of the third paragraph, "not many other would" should be "not many others would".
     In the third sentence of the third paragraph, "he thought he had known, and whom he" should be "he thought he had known, whom he" or "he thought he had known and whom he".
     In the third sentence of the final paragraph, "get the message quickly, and not make" should be "get the message quickly and not make"
     ![CaptureSTIR6](https://user-images.githubusercontent.com/80563255/193125832-0a4dd6c7-5006-4dec-b59d-2b846549ef83.PNG)

7. event FEN_MSA.9 "Dulling the Sickle"
     The last sentence of the sixth paragraph is a bit awkward due to the word choice and grammar. It also uses "rumors" instead of the British "rumours". An improved sentence could look like "One coordinated media campaign, highlighting the violence of the trade unionists and rumours about communist infiltration, and the shine over another hero of England would be tarnished".
     ![CaptureSTIR7](https://user-images.githubusercontent.com/80563255/193127549-25c8b967-b6c3-492b-bf0c-2fc615c1207e.PNG)

8. event FEN_MSA.13 "Operational Adjustments"
     The last sentence of the third paragraph has a few grammar errors, it could be corrected to something like "Working with limited resources and with the odds stacked against him was, in a way, coming home, be it in alleys and warehouses or the halls of Parliament."
     In the first sentence of the seventh paragraph, "behind his back, as the moon shone" should be "behind his back as the moon shone".
     ![CaptureSTIR8](https://user-images.githubusercontent.com/80563255/193128683-6d673cc9-18b9-424f-8e37-d4a396afdba4.PNG)

9. event FEN_MSA.14 "Hope for the Best"
     In the third sentence, "was so weak then why was it" should be "was so weak, then why was it".
     ![CaptureSTIR9](https://user-images.githubusercontent.com/80563255/193129346-5ce39f05-6da4-457f-87bc-10267f23ef12.PNG)

10. event FEN_MSA.15 "Lost Time"
     In the final sentence of the fifth paragraph, "required him to go above parliament and destroyed him in the process" sounds a bit awkward. It could instead be "required him to go above parliament and the process destroyed him".
     ![CaptureSTIR10](https://user-images.githubusercontent.com/80563255/193130490-0ef7049f-d92c-4354-9722-63ccc555a16d.PNG)

11. event FEN_MSA.10 "The First Triumph"
     In the second sentence of the third paragraph, "but kept his face still" should be "but he kept his face still".
     In the second sentence of the fifth paragraph, "into ecstatic applause, or shouted" should be "into ecstatic applause or shouted".
     In the last sentence of the fifth paragraph, "realized" should probably be "realised" since that spelling is more common in British English.
     ![CaptureSTIR11](https://user-images.githubusercontent.com/80563255/193132151-c6e95e56-e616-4958-97fe-2c39e108c15c.PNG)

12. event FEN_MSA.11 "A Toast"
     In the final sentence of the fifth paragraph, "free-a" should be "free - a".
     ![CaptureSTIR12](https://user-images.githubusercontent.com/80563255/193132660-43df8773-4dd1-41f8-9fd8-a0f042a3f144.PNG)

13. event FEN_MSA.12 "The Little Things"
     In the third sentence of the third paragraph, "jewish" should be "Jewish".
     In the first sentence of the fourth paragraph, "small minded" should be "small-minded".
     ![CaptureSTIR13](https://user-images.githubusercontent.com/80563255/193133389-8fd9b57d-c6ce-4d94-bdfb-0a8c30a133b4.PNG)

14. event FEN_MSA.4 "A Tense Meal"
     In the first sentence, "was tense; uncomfortable" should be "was tense, uncomfortable" or "was tense and uncomfortable".
     In the fourth sentence of the second paragraph, "who held the power, and was not" should be "who held power and was not".
     In the last sentence of the second paragraph, "he'd accepted, because if" flows better as "he'd accepted because if".
     In the second sentence of the third paragraph, "enough of the awkward silence, and spoke" should be "enough of the awkward silence and spoke".
     ![CaptureSTIR14](https://user-images.githubusercontent.com/80563255/193134611-3b2e9ee1-a7f6-4392-8233-17862b919981.PNG)

15. focus FEN_MSA_hurray_for_msa "Hurray for M, S, and A!"
     In the first sentence, "At long last victory" should be "At long last, victory".
     In the final sentence of the first paragraph, "would have sought to implement" is redundant and should be "sought to implement" or "would have implemented".
     In the last sentence, "defend Britain whatever the cost" should be "defend Britain, whatever the cost".
     ![CaptureSTIR15](https://user-images.githubusercontent.com/80563255/193135468-5fe02381-03eb-4a51-ba7a-acad3a774ba2.PNG)

16. focus FEN_MSA_trust_in_the_people "Trust in the People"
     In the second sentence, "Yes it is" should be "Yes, it is".
     In the second sentence of the second paragraph, "likely as not sick" should be "likely sick" or something similar.
     ![CaptureSTIR16](https://user-images.githubusercontent.com/80563255/193136142-88784d09-836b-488a-b88b-4b83ffdf212c.PNG)

17. focus FEN_MSA_appease_the_ndl "Appease the NDL"
     In the first sentence, "is a drunkard, a womaniser, and man" should be "is a drunkard, womaniser, and man" or "is a drunkard, a womaniser, and a man".
     In the third sentence, "less reasons" should be "fewer reasons" or "less reason".
     ![CaptureSTIR17](https://user-images.githubusercontent.com/80563255/193137004-24832190-5f98-49a0-9465-758bd6a520b6.PNG)

18. focus FEN_MSA_talk_with_wilson "Talk With Wilson"
     In the final sentence, "the law of course, so really we're getting" should be "the law, of course, so we're really getting".
     ![CaptureSTIR18](https://user-images.githubusercontent.com/80563255/193137847-4c7ee5bf-c19b-444e-bf2b-36bed2241659.PNG)

19. focus FEN_MSA_trust_in_the_military "Trust in the Military"
     In the fourth sentence, "didn't in the past, and was" should be "didn't in the past and was" or "didn't in the past, and he was".
     In the first sentence of the second paragraph, "To say nothing of course, of" should be "To say nothing, of course, of". Also, "ill begotten" should be "ill-begotten".
     In the second sentence of the second paragraph, "Our army, and our industry" should be "Our army and our industry" or "Our army and industry".
     In the final sentence, "else Britain" should be "lest Britain" or "or else Britain" or something similar.
     ![CaptureSTIR19](https://user-images.githubusercontent.com/80563255/193139057-50205f52-1224-4ccb-821f-6e083f56c08a.PNG)

20. focus FEN_MSA_invite_military_advisors "Invite Military Advisors"
     In the first sentence of the second paragraph, "to be circumspect of course" should be "to be circumspect, of course".
     In the fourth sentence of the second paragraph, "their goals is" should be "their goals are".
     ![CaptureSTIR20](https://user-images.githubusercontent.com/80563255/193139590-1c7d3ca8-5060-4b55-ae94-ae170a34402e.PNG)

21. focus FEN_MSA_the_queen_and_her_general "The Queen and Her General"
     The second sentence should use a different phrase than "unlike" since that word requires a comma before it, an addition that would make the sentence grammatical but unclear. "in contrast to" would work.
     ![CaptureSTIR21](https://user-images.githubusercontent.com/80563255/193141248-2b49540d-2221-4572-855e-bcdfad08b956.PNG)

22. focus FEN_MSA_shove_the_gunpowder "Shove the Gunpowder"
     In the last sentence of the first paragraph, "cesspits" should be "cesspools".
     ![CaptureSTIR22](https://user-images.githubusercontent.com/80563255/193141896-cbd28819-74b0-4c37-8f82-4716fb260b07.PNG)

23. focus FEN_MSA_light_the_fuse "Light the Fuse"
     In the second sentence, "MP's" should be "MPs".
     In the last sentence of the first paragraph, "never will again" should be replaced since that contradicts the "never have in the past" that precedes it. It could be changed to something like "never will in the future" or "never will hereafter".
     In the second to last sentence, "our cause is just true" should probably be "our cause is just and true".
     In the final sentence, "answer to the people, and the people" should be "answer to the people and the people".
     ![CaptureSTIR23](https://user-images.githubusercontent.com/80563255/193142747-a5b2524b-ac8c-4dcf-8df1-2895796d730d.PNG)

24. focus FEN_MSA_expose_the_auk "Expose the Auk"
     In the second sentence of the second paragraph, "Perhaps even acquire some new MP's" should be something like "Perhaps we will even acquire some MPs" or "Perhaps we can even acquire some MPs".
     ![CaptureSTIR24](https://user-images.githubusercontent.com/80563255/193143139-b92bbe84-c4e0-41fd-928b-65517e1a5b63.PNG)

25. focus FEN_MSA_dig_into_alexander "Dig into Alexander"
     In the second sentence, "Now, one of the primary backers" should be "Now he is one of the primary backers" or "Now, he is one of the primary backers".
     In the first sentence of the second paragraph, "used" should probably be something like "utilised" since the verb use is already present within that same sentence.
     ![CaptureSTIR25](https://user-images.githubusercontent.com/80563255/193143986-b0497716-3f00-4ea9-9069-28612fbb1b5f.PNG)

26. focus FEN_MSA_fire "Fire!"
     In the third sentence, "else" should be "or else" or "otherwise" or something similar.
     In the sixth sentence, "and more than that made history" should be "and, more than that, made history".
     ![CaptureSTIR26](https://user-images.githubusercontent.com/80563255/193144554-8ff34c57-e360-4008-a00b-643733a2d1be.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
