### ISSUE TITLE
ENG - Stirling minister doesn't join the country

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1070]
### Operating System

Linux

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The event "Those Who Stand With Us" (FEN_MSA.2) doesn't add John Woodhouse to the government.

### Steps to reproduce / Cause of the issue

1. Become Stirling's England
2. Complete the given focus in his tree
3. Select the only option for event "Those Who Stand With Us" (FEN_MSA.2)
4. John Woodhouse is not added. I suspect it is because the idea_token for FEN_John_Woodhouse needs to be FEN_John_Woodhouse_eco

### Expected behaviour

All of the ministers listed join the government

### Screenshots

![CaptureSTIR](https://user-images.githubusercontent.com/80563255/193147076-bcd52de4-efa1-4e08-89a7-23f1da1aab7f.PNG)

![CaptureSTIR1](https://user-images.githubusercontent.com/80563255/193147115-94d463fe-6703-43c8-ba62-bf98f502ce16.PNG)

### Additional information

Additionally, as shown in the screenshot above the localization for their names in the event only exists for one person. I'm uncertain whether to count that as part of this bug or to make another issue

**Comment by runelead00** [comment]
Fixed in Dev Build
