### ISSUE TITLE
ENG - Swapped reconstruction regions

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1071]
### Operating System

Linux

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The two devastation regions in Cornwall have their colored map regions switched with each other. The one with >20% devastation is green and the one with <20% devastation is yellow.

### Steps to reproduce / Cause of the issue

1. During English Civil War create circumstances that would give the Cornwall regions different starting devastation
2. Win English Civil War
3. Look at the "A Devastating War" map in the decisions tab

The issue seems to be caused by some typos in the TNO_England_devastation.txt file
1. ENG_Devastation_State1296 has image = GFX_ENG_GUI_Devastation_State123
2. ENG_Devastation_State123 has image = GFX_ENG_GUI_Devastation_State1296

### Expected behaviour

Devastation region color to correspond with actual devastation

### Screenshots

Eastern Cornwall region selected
![CaptureTNO](https://user-images.githubusercontent.com/80563255/193157043-17f86415-1fe7-4032-8601-f39213909576.PNG)

Western Cornwall region selected
![CaptureTNO1](https://user-images.githubusercontent.com/80563255/193157069-0826fd74-a297-4936-811a-4d4142ad10eb.PNG)

**Comment by Stormeagle449** [comment]
Fixed for UB.
