### ISSUE TITLE
All Countries - Crash to Desktop either when December 17th 1969 rolls around or Italian Terrorist Bombing event happens

### ISSUE THREAD

**Issue by ShadHedgie** [TNODevs/TNO-Bug-Tracker#1072]
### Operating System

Windows 10

### HOI4 version

Barbarossa (1.11.13)

### TNO version

1.2.1c (A Toolbox Theory)

### Do you have other mods in use?

None.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA TNO Save Game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9691384/USA.TNO.Save.Game.zip)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9691386/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9691387/error.log)

### Describe the crash

The game closes to desktop a few days after the Italian Terrorist Bombing event & Super-event, without any further explanation. I've used a few debug tools and tested that it's not an USA exclusive crash, any country that you're playing as will crash a few days after the event happens, specifically on moving from the 16th December 1969 to the 17th.

The screenshots provided show the last event and super-event before the game crashes to desktop.

### Steps to reproduce / Cause of the crash

1. Italy triggers the terrorist bombing event / Super-event
2. Game crashes a few days after, seemingly always specifically passing from the 16th to the 17th.

### Screenshots

![Event1](https://user-images.githubusercontent.com/91343943/193432355-69a58aa9-1a8e-49cb-a034-cc4bc9becb4c.png)
![Event2](https://user-images.githubusercontent.com/91343943/193432368-d051df7f-1203-4c2d-af41-86a3299243e7.png)

### Additional information

I genuinely do not know why it's happening; I was _originally_ playing with TMO but then I disabled it and loaded a previous save to make sure it wasn't a TMO issue, as the crash happens on base TNO too.

I also do not know if it's a date-specific crash (always happening on the 16th to 17th) or if it's completely based around the event & super-event.

**Comment by runelead00** [comment]
Your save game can't be opened, What is happening in West Siberia at time of crash

**Comment by ShadHedgie** [comment]
> Your save game can't be opened, What is happening in West Siberia at time of crash

It can't be opened? That's incredibly odd. I'll try to find another way to upload it that might work, then.

As for what's happening in West Siberia, it seems to be a war, although pretty much almost ending. Could it be the peace conference making the game crash, maybe?

![Crash3](https://user-images.githubusercontent.com/91343943/193432629-8a3f4ae4-592b-4c0f-91c4-30f0b6b0e2a8.png)

**Comment by runelead00** [comment]
Yeah, it's the peace conference, Zlatoust has been causing crashes. Fixed in Dev Build
