### ISSUE TITLE
USA - Reuse the 1972 candidates for the 1976 US elections as a stop gap until TNO2

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#1073]
### HOI4 version

1.11.7

### TNO version

1.2.1b

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe your suggestion

The 1976 US elections should be integrated using the 1972 candidates to end the US playthrough run when playing with a 1968 Presidency.

### Justifications

When playing as a 1968 President, the game doesn’t end normally like it would if you played it with the 1964 President. You don’t have any 1976 candidates to run with and it doesn’t end with the “Thanks for Playing” screen popping up either. This makes running a two-term presidency with a 1968 President feels like it doesn’t have a proper end scenario.

That is why I believe you should have the 1972 candidates be reused again for the 1976 elections, as a stop gap for the 1976 election, until TNO2 when you have proper 1976 candidates by then.

You can reuse the 100 days for the 1972 candidates, just now in 1976, with the same the game end when they complete their 100 days followed by the “Thanks for Playing” screen. You can skip doing transition letters since this will be a temporary situation.

Doing this can also incentives people to continue playing their 1968 President to see how the political environment would look like by the time the 1976 election happens, especially for those who want to go down the radical routes.

People who tried to get Hall or Yockey elected in 1972 but failed would now continue to play as their 1968 president (Goldwater or MCS), instead of restarting the game as they now know that they have a second chance to try to get Hall or Yockey elected in 1976, to see their 100 days content and would show how much further they can push the US to elect radicals when they complete two terms as the 1968 President and see what the political environment looks like by 1976.

Overall, I think that reusing the 1972 candidates for 1976 would help to complete a playthrough when going down a 1968 Presidency run.

**Comment by Stormeagle449** [comment]
Don't see the point in implementing this.
