### ISSUE TITLE
United States-Arrows pointing at nothing

### ISSUE THREAD

**Issue by Miniuniverse3** [TNODevs/TNO-Bug-Tracker#1074]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe the GFX issue

Arrows pointing at nothing even after clicking on the GFX for a country, it still reamins.

### Steps to reproduce / Cause of the issue

1. Open freshly installed TNO with no other mods
2. Open United States
3. Start Game

### Expected behaviour

No arrows

### Screenshots

![20221008110939_1](https://user-images.githubusercontent.com/76416436/194714296-72f501b4-ad43-42da-b833-4107e8d19442.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
