### ISSUE TITLE
ENG - State not owned by ENG included in graphics

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1075]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The several graphics in the decisions tab for England include the Isle of Man when it is not owned by England. The state Isle of Mann (id 1566) is present in the "The State of the Nation", "A Devastating War", and "Election Season" graphics even though it is impossible for ENG to own Mann for the first two graphics and only after annexing Scotland for the third.

### Steps to reproduce / Cause of the issue

1. Progress in any England path to the points where each graphic listed ("The State of the Nation", "A Devastating War", "Election Season") would be visible.
2. Look at the graphic

The issue could probably be resolved by tying Isle of Mann to the state Dumfries (id 1321) for election purposes and removing it entirely for the visuals of "The State of the Nation" and "A Devastating War".

### Expected behaviour

Mann is only shown if England controls it

### Screenshots

![CaptureTNO4](https://user-images.githubusercontent.com/80563255/194734918-82142f03-1f06-437c-986a-f5a36496913f.PNG)
![CaptureTNO2](https://user-images.githubusercontent.com/80563255/194734922-ff372837-330e-4ced-b607-0831ed5e08d0.PNG)
![CaptureTNO3](https://user-images.githubusercontent.com/80563255/194734926-833a872d-e082-434c-a18f-13339464b31a.PNG)

**Comment by runelead00** [comment]
Fixed in State of the Nation and Devastating War GUI, still unadjusted in Election Season

**Comment by runelead00** [comment]
oops

**Comment by runelead00** [comment]
Not updating old guis from old england anymore
