### ISSUE TITLE
ENG - Nationwide Devastation not calculating correctly

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1076]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[ENG_1964_05_21_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9740783/ENG_1964_05_21_01.zip)

### Describe the bug

With every state's devastation at 0, the nationwide devastation becomes -0.38%. If it miscalculates the nationwide devastation when all states are at 0 it likely also miscalculates it in other circumstances.

### Steps to reproduce / Cause of the issue

1. Play as ENG
2. Win English Civil War
3. Take decisions such that every state has a devastation of 0.00%
4. Look at Nationwide Devastation

### Expected behaviour

Nationwide Devastation to be at 0 when state devastations are at 0

### Screenshots

![CaptureDevastation](https://user-images.githubusercontent.com/80563255/194739070-9df2d9a5-34ae-4361-a981-9f7341b8f90e.PNG)

**Comment by runelead00** [comment]
Fixed in Current Release
