### ISSUE TITLE
ENG - Event claims 2 separate parties won

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1077]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[ENG_1964_05_17_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9740798/ENG_1964_05_17_01.zip)

### Describe the bug

The event text for "The Choice of Direction" claims that the Royal Party won and that United England won.

### Steps to reproduce / Cause of the issue

I'm not certain why this happened. One guess is that while Royal Party has more seats than any other party, United England as a coalition has a plurality.

### Expected behaviour

The event to definitively say which party won

### Screenshots

![CaptureElection](https://user-images.githubusercontent.com/80563255/194739405-f6689add-0e8b-40e4-8d40-3fa895bb7368.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
