### ISSUE TITLE
ENG - Low National Front support for Chesterton's Act

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1079]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

National Front support for the "The Promotion of British Ideas and Culture" seems to be very low. Regardless of the path taken in Chesterton's tree less than 60% of their MPs support the act, which seems too low to be intended for a fascist party bent on order.

### Steps to reproduce / Cause of the issue

1. Play ENG
2. Ensure Chesterton comes to power
3. Start voting on "The Promotion of British Ideas and Culture Act"
4. Look at the National Front support for the act

### Expected behaviour

A fascist party that is at least somewhat united in support for the act

### Screenshots

![CaptureCHE25](https://user-images.githubusercontent.com/80563255/194948059-d96f5e16-84a9-47b1-8ea6-ade15d584338.PNG)

**Comment by runelead00** [comment]
NF support has been increased somewhat

**Comment by tydane** [comment]
Also, unlike the other English acts there aren't any decisions to increase support for it. Is that intended?
