### ISSUE TITLE
ENG - Communists listed despite 0 support

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1080]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The focus "All the Country's a Stage " splits the National Front into various factions. One of these factions is Communism despite there being 0.00 support for Communism.

### Steps to reproduce / Cause of the issue

1. Play ENG
2. Support Government
3. Ensure National Front wins elections
4. Complete "All the Country's a Stage" focus
5. Look at political factions

### Expected behaviour

Factions to only be present if they have more than 0 support

### Screenshots

![CaptureCHE26](https://user-images.githubusercontent.com/80563255/194949086-5fd15bca-b255-401d-ba3f-49850d114152.PNG)

**Comment by runelead00** [comment]
Issue with how base HoI4 code handles popularity changes, can't fix
