### ISSUE TITLE
All countries - I can't send more than one volunteer 

### ISSUE THREAD

**Issue by LOL-15** [TNODevs/TNO-Bug-Tracker#1081]
### Operating System

Windows 10

### HOI4 version

1.11

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

I can't send more than one volunteer 

### Steps to reproduce / Cause of the issue

Go to the country you want to send volunteer's to 
Click on send volunteer's 
Scroll down and chose your volunteer's and you get the error 

### Expected behaviour

I click on send volunteer button it says I can send two or three volunteer's tho I can't send more than one

**Comment by runelead00** [comment]
merged into #1212
