### ISSUE TITLE
USA - COINTELPRO decsions have no name/text

### ISSUE THREAD

**Issue by Rorschach113** [TNODevs/TNO-Bug-Tracker#1082]
### Operating System

Windows 10 

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

custom country paths

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Text events for Cointelpro decisions for RFK are missing text.

### Steps to reproduce / Cause of the issue

Play RFK as USA, get to Cointelpro, the decsions for fabrications of stories about John Birch society (and others, I believe) have no title or text.

### Expected behaviour

The Cointelpro decisions should have text.

**Comment by runelead00** [comment]
Fixed in Dev Build
