### ISSUE TITLE
ILG - the leader of the Algerian Mandate is generic

### ISSUE THREAD

**Issue by Lorcomax** [TNODevs/TNO-Bug-Tracker#1083]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths Mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Describe the bug

The leader of the Algerian Mandate is a generic One, instead of the actual leader mentioned in the news event

### Steps to reproduce / Cause of the issue

1. Start a game as Italian Algeria
2. Open the console and put in "event ILG.8"
3. Look at the head of state of the country

### Expected behaviour

I expected the correct leader to appear

**Comment by runelead00** [comment]
Fixed in Dev Build
