### ISSUE TITLE
[Bug]: PAL- The capital of Palestine is incorrectly located

### ISSUE THREAD

**Issue by Lorcomax** [TNODevs/TNO-Bug-Tracker#1084]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths Mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Describe the bug

The Capital of Palestine post-partition Is incorrectly located on the map: it's in the State Gaza (n. 1304) , while It should be in the State Caifa (n. 1248) where the actual city of Gaza Is located

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Open the console and put in "event impurita.32"
3. Let the time run for a few seconds.
4. Look at the Capital of Palestine is
The issue Is caused by the fact that the event impurita.32 sets the Capital of Palestine to the wrong State.

### Expected behaviour

I expected the Capital of Palestine to be correctly displayed in Gaza

**Comment by runelead00** [comment]
Fixed in Dev Build
