### ISSUE TITLE
Map Definition Error

### ISSUE THREAD

**Issue by Autistic-Kaiser** [TNODevs/TNO-Bug-Tracker#1085]
### Operating System

Windows 11

### HOI4 version

1.12

### TNO version

1.3.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9789172/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9789174/game.log)

### Describe the crash

dialog box opens up and you get a map definition error.

### Steps to reproduce / Cause of the crash

1. Load the game

**Comment by Stormeagle449** [comment]
Can only recommend the fixes found here: #961
