### ISSUE TITLE
Philippines - Holy Manila

### ISSUE THREAD

**Issue by ZawHawk** [TNODevs/TNO-Bug-Tracker#1086]
### HOI4 version

1.12

### TNO version

1.3.0

### Do you have other mods in use?

Nope

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![image](https://user-images.githubusercontent.com/90123868/195918875-646312e0-e4d8-4822-89d6-415af3b31832.png)

### List the loc issues below

Dakilang Manila translates to Greater Manila
But Greater **Morally**
so it translates to Holy or Noble Manila

It's supposed to be "Kalakhang Maynila" or Greater Manila
Greater being "Metro" or "Greater Area of"

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting.
