### ISSUE TITLE
United States - Carrier Capacity in the hundreds

### ISSUE THREAD

**Issue by davidwang117155** [TNODevs/TNO-Bug-Tracker#1087]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

hanger space modules on carriers have 200/300/400 capacity, which does not make any sense.

### Steps to reproduce / Cause of the issue

boot game, select carrier, view design

### Expected behaviour

Hangar capacities should be 20/30/40

### Screenshots

![20221014150043_1](https://user-images.githubusercontent.com/92734555/195921534-a372ddc3-85b8-4b3b-b7ef-b0d3d8ac481e.jpg)

**Comment by eemilc** [comment]
yeah it seems to be in other nations as well not just america

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by eemilc** [comment]
why do you have my email

ke 19. lokak. 2022 klo 8.59 runelead00 ***@***.***) kirjoitti:
