### ISSUE TITLE
I can't get to the country selection screen

### ISSUE THREAD

**Issue by Shipmanchile1** [TNODevs/TNO-Bug-Tracker#1088]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

The only files I have are the .txt ones

### Describe the crash

When I click on "play", tle loadong screens of vanilla hoi4 appear, it remains stable until the "initializing game", when the game crashes

### Steps to reproduce / Cause of the crash

1. Go to Paradox Launcher
2. Click on Play
3. Wait until "initializing game"
4. Crash

### Screenshots

![20221014_163253](https://user-images.githubusercontent.com/115833857/195927607-583825ef-8f0e-4dcf-97ee-a4d3e982d829.jpg)
Sorry for the low quality

### Additional information

I use the gamepass version

**Comment by Stormeagle449** [comment]
Without a save file or error log file we can't really solve your issue.
