### ISSUE TITLE
United States - Party Support Resets to 50/50 After 1 Month

### ISSUE THREAD

**Issue by Lasaimishan** [TNODevs/TNO-Bug-Tracker#1089]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After playing in the United States for a little while on the newest version, the support for the political parties (RDC and NPP) reset to 50% - 50% in every state after a month of play. This has the effect of essentially rendering the mod unplayable and is way out of line with the given lore. The support for the internal factions within the parties is unaffected. 

### Steps to reproduce / Cause of the issue

1. Play the game in USA for 1 month
2. Check party support by state

### Expected behaviour

Party support behaving like in previous versions of the mod, ie responding to events and decisions, and party popularity stays different across states. 

### Screenshots
Popularity (nationwide) after 1 month:
![image](https://user-images.githubusercontent.com/115836020/195940127-1ad8b5b4-2af9-48a8-9bad-1344882613a9.png)

**Comment by runelead00** [comment]
Fixed in Current Release
