### ISSUE TITLE
USA - LBJ twice the senator from Texas in 1962

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#1090]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3

### Do you have other mods in use?

-

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Lyndon B. Johnson is twice the senator from Texas at the game start.

### Steps to reproduce / Cause of the issue

start the game as USA, look at the elections GUI

### Expected behaviour

One senator LBJ from Texas

### Screenshots

![image](https://user-images.githubusercontent.com/63430051/195933317-59c875ea-7f20-4f06-92c3-0f9685ad51a6.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
