### ISSUE TITLE
USA - two nationalist candidates in '52

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#1091]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In elections GUI for Presidential elections of 1952 when hovering over one of the gray states you can see that their candidate is Albert B. Chandler, but when you hover over 5 faithless electors in VA, you can see that the Nationalist candidate is instead George S. Patton. 

### Steps to reproduce / Cause of the issue

1. Go to USA gov & voting GUI
2. Click on Presidential elections tab and choose 1952.
3. Check what I have described above.

### Expected behaviour

Either Patton, or Chandler alone should be mentioned as the Nationalist candidate when hovering above the gray states and the faithless electors in VA.

### Screenshots

![image](https://user-images.githubusercontent.com/63430051/195934663-93becdef-3b3b-4801-bf7d-2529cf1a81e9.png)
![image](https://user-images.githubusercontent.com/63430051/195934703-6beeb9be-90cd-48e2-95a0-c63ebbea5294.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
