### ISSUE TITLE
USA - 

### ISSUE THREAD

**Issue by UnitBased** [TNODevs/TNO-Bug-Tracker#1092]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR

### Describe the bug

when entering the "research all" command into the console, the game immediately crashes. 

### Steps to reproduce / Cause of the issue

play USA
open console
enter "research all"

### Expected behaviour

all tech becomes researched

**Comment by runelead00** [comment]
don't do actions that are clearly not intended for the player to do, we will not support those issues
