### ISSUE TITLE
Iberia - Remaining Reference to Atlantropa

### ISSUE THREAD

**Issue by mparie** [TNODevs/TNO-Bug-Tracker#1093]
### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB

### List the loc issues below

The "Triumvirate Founder" description for the Iberian Union still references Atlantropa after removal

![image](https://user-images.githubusercontent.com/68326969/195942290-7ed39364-5c55-47d1-b6e9-6b14e19e450f.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
