### ISSUE TITLE
United States - Missing models for F110A Spectre and F105 Thunderchief

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1094]
### Operating System

Windows 10

### HOI4 version

1.11.17

### TNO version

1.3.0

### Do you have other mods in use?

Only music mods and the recall volunteers mod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

As seen on the images, the models for the F110A Specter fighter jet and the F105 Thunderchief CAS for the United States only possess the generic model for U.S. Fighters, as opposed to their pre-made models that existed prior to Toolbox Theory 3's release.

### Steps to reproduce / Cause of the issue

1. Start a United States game.
2. Open the technology tab and go to fighters.
3. Open the F110A and F105 and open their 3d model viewer.

### Expected behaviour

The F110A and F105 should have their expected models that existed prior to TT3.

### Screenshots

![image](https://user-images.githubusercontent.com/25708474/195944341-b6ade0d1-aa86-4957-9242-4a6690d4c171.png)

![image](https://user-images.githubusercontent.com/25708474/195944524-7f3357c8-5076-4b7d-813e-66c21797d262.png)

### Additional information

Interestingly enough, the models for the F-15A Eagle and A-10 Thunderbolt II ae both intact.

I am unsure if the F106 Delta Dart had a unique model in the past, but I am pretty sure it is now using the F110A's model.

The bombers section seems to have no issues.

**Comment by runelead00** [comment]
Fixed in Dev Build - Tdizz
