### ISSUE TITLE
USA - Bug with Presidential Election GUI for 1956

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1095]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the 1956 presidential election GUI on the map Chandler is named as Republican candidate, in the topbar it is (lore-correctly) Dirksen. Additionally, on the map no one is named as the Nationalist candidate.

### Steps to reproduce / Cause of the issue

Open the GUI

### Expected behaviour

Dirksen should be the Republican candidate, Chandler the Nationalist one

### Screenshots

![Screenshot (1274)](https://user-images.githubusercontent.com/33550299/195946944-74df6769-9edc-4183-ade2-901e2c1c9d06.png)
![Screenshot (1275)](https://user-images.githubusercontent.com/33550299/195946965-7b9bf0c5-3d16-46bf-95fb-8fdc78bf2815.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
