### ISSUE TITLE
USA - US intro screens

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1096]
### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Kefauver Presidency:
1. I don't think Wheeler's name is colored correctly since he is not establishment, he should be colored in the progressive color (which he is already in the Eisenhower Presidency screen).
2. Is it intended to use the first name "Estes" instead of "Kefauver" in the second paragraph? Also, his name is never colored democratic despite being mentioned twice.
![Screenshot (1269)](https://user-images.githubusercontent.com/33550299/195949804-eb89db83-c474-401e-a82b-05023e86edae.png)

Eisenhower Presidency:
"Republican Party" and "Republican Robert Taft" should be colored Republican. The first "Ike", the first "Roosevelt" and the second "Wheeler" should also be colored appropriately.
![Screenshot (1268)](https://user-images.githubusercontent.com/33550299/195949779-05d53b6a-aab8-4b28-bafa-aabe6096ec32.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
