### ISSUE TITLE
United States - Missing and incorrect LOC for several Cities.

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1097]
### HOI4 version

1.11.17

### TNO version

1.3.0

### Do you have other mods in use?

Music mods and the recall volunteer mod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. The cities of Richmond, Charleston, Miami, St. Louis, Las Vegas and Portland are all missing their city localisation.

![image](https://user-images.githubusercontent.com/25708474/195950074-5c5a55f9-ea63-4a90-807f-794b2e3eaabf.png)
![image](https://user-images.githubusercontent.com/25708474/195950082-b1aa412b-acca-4d6b-854d-657b8b7b5492.png)
![image](https://user-images.githubusercontent.com/25708474/195950088-bc548c24-c6c8-4a6a-8e74-fdc53a6242c3.png)
![image](https://user-images.githubusercontent.com/25708474/195950100-b22ec999-254d-419f-8043-08b76ea4cd2d.png)
![image](https://user-images.githubusercontent.com/25708474/195950118-2420dd85-7e33-43d8-8a8e-283fc42a4fc0.png)
![image](https://user-images.githubusercontent.com/25708474/195950130-f5bd548a-e5a8-4b6d-9ab6-3502dc6bd1e6.png)

2. The localisation for the Japanese treaty port in San Francisco mentions Paris being split, which is no longer true in TT3.

![image](https://user-images.githubusercontent.com/25708474/195950214-c19abcde-aff0-45b6-b4b9-054e7ebb4622.png)

### Additional information

Not a localisation issue, but the descriptions for San Francisco and Los Angeles proper feel somewhat barren in comparison to the new city descriptions in TT3.

![image](https://user-images.githubusercontent.com/25708474/195950478-3c94796e-370d-4322-83af-d6727f6096e6.png)
![image](https://user-images.githubusercontent.com/25708474/195950488-db122d08-4348-49fa-9aa0-fe1bc1ce6fee.png)

**Comment by ModdingAccount** [comment]
Fixed in dev build
