### ISSUE TITLE
USA Volunteer Supply Bug

### ISSUE THREAD

**Issue by ShinyStaraptor** [TNODevs/TNO-Bug-Tracker#1099]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3bb

### TNO version

1.30.a - Unfinished Business

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

![829f0a85cb953df0c73406fa2c086f49](https://user-images.githubusercontent.com/80494008/195952608-0b563304-ffde-42cf-9021-2dd8b5964b2f.jpg)

### Describe the bug

USA volunteers do not get supply in all proxy wars. Didn't get supply in Malaya, didn't get supply in Madagascar, and now not getting supply in SAW, all due to the reinforcement blocked bug. SAF owns Cape Town and a bunch of other ports, so something has to be broken here. I cheated to give myself 2k convoys, and it's still broken.

### Steps to reproduce / Cause of the issue

1. Play US
2. Send volunteers
3. Have them fight or do a little funni somewhere so they lose strength
4. Check strength bar to see if reinforcements/supplies are incoming
5. Seethe and mald

### Expected behaviour

I expect to get supply if the country I'm supporting in the proxy war has a port.

**Comment by bobw123** [comment]
I had a similar issue - it made pushing in South Africa really difficult

**Comment by AntonosGR** [comment]
Happened to me too after the IJN blockade.

**Comment by JetNebula** [comment]
It's still there for me, even after the IJN Blockade is no more

**Comment by runelead00** [comment]
Fixed in Current Release
