### ISSUE TITLE
USA - Missing Loc

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#1100]
### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB, BBA

### List the loc issues below

- [x] ![Screenshot (167)](https://user-images.githubusercontent.com/84231463/195953541-3557abdb-e4a9-4296-8b8d-78d726c9c011.png)

- [x] ![Screenshot (169)](https://user-images.githubusercontent.com/84231463/195953607-a0151f88-b3b6-4c0e-921d-b9b74a69a5af.png)
- [x] ![Screenshot (170)](https://user-images.githubusercontent.com/84231463/195953624-8781f80a-7c24-40be-b4dc-29c84eca4e0b.png)
- [x] ![Screenshot (171)](https://user-images.githubusercontent.com/84231463/195953639-2903fd1f-f9b5-43ca-8f2f-30f6fa43e9c1.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
