### ISSUE TITLE
USA - Broken Volunteer Cap

### ISSUE THREAD

**Issue by Reshuram** [TNODevs/TNO-Bug-Tracker#1101]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

Last Waltz of Europe Extended, Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Describe the bug

Playing as USA. Volunteer cap 10 divs. Game keeps me from sending more than one volunteer div to SA because of "lack of provinces" even tho they controll a large portion of SA and almost all of Namibia

### Steps to reproduce / Cause of the issue

1. Play USA
2. Get SAW
3. Increase Volunteer cap
4. Try to increase number of volunteers in SA

### Expected behaviour

I expected to be able to send 10 divisions as volunteers

**Comment by runelead00** [comment]
merged into #1212
