### ISSUE TITLE
USA/Japan - Volunteers unable to be resupplied with equipment (besides fuel)

### ISSUE THREAD

**Issue by Pelops27** [TNODevs/TNO-Bug-Tracker#1102]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Volunteer forces are unable to be resupplied with equipment, besides fuel, independant of the actual supply state of the region the unit is in. In screenshot one my units are in the capital of the country they were sent to and have optimal supply. I noticed it with the USA during the Malayan Civil War but only investigated the problem during the South African War. I tried this out with Japan in the Malayan Civil War as well, they have the same problem.

### Steps to reproduce / Cause of the issue

1. Send volunteers in any proxy war
2. Suffer any casualties with those units

### Expected behaviour

I expected units with normal supply to get reenforced

### Screenshots

![grafik](https://user-images.githubusercontent.com/50521496/195959205-89caa404-926b-4ad8-9a99-6bc5bb2dfa7f.png)
![grafik](https://user-images.githubusercontent.com/50521496/195959820-438685b3-a472-4701-9c8f-9ebdb56e89ee.png)

### Additional information

it is possible to circumvent this by using console commands and getting military access to the country you are sending volunteers to

**Comment by ModdingAccount** [comment]
Known issue; Caused by BBA update.
