### ISSUE TITLE
CAN - Extremely high GDP per capita in Northern Ontario and Northern Saskatchewan

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#1103]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Northern Ontario and Northern Saskatchewan both have an extremely high GDP per capita compared to the rest of Canada (500-600% greater than national average), which gives the assumption that this is a bug.

### Steps to reproduce / Cause of the issue

1. Load a new game
2. Open GDP per Capita map mode

### Expected behaviour

Have a GDP per capita closer to their surrounding states

### Screenshots

![Hearts of Iron IV (DirectX 11) 15_10_2022 11_54_01 AM](https://user-images.githubusercontent.com/59920852/195962040-b2f00a35-b862-4bf1-8eb6-89e83b3cd0b4.png)

**Comment by runelead00** [comment]
Fixed in current release
