### ISSUE TITLE
Missing 3D aircraft models

### ISSUE THREAD

**Issue by joublier** [TNODevs/TNO-Bug-Tracker#1104]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

USA, GER, ENG, JAP, ITA, CHI, BRA, IBR using generic/vanilla 3D models for Fighter and CAS aircrafts. (USA uses generic 3D model only for 60s’ aircrafts)

### Steps to reproduce / Cause of the issue

Replace generic/vanilla fighter and CAS 3D models with tags’ unique 3D model.

### Expected behaviour

Correct displacement of 3D aircraft models for tags instead of generic ones

### Screenshots

![987298F6-E41A-4D6E-A6C4-1EC7690F1FBC](https://user-images.githubusercontent.com/115851499/195963280-d33c802e-242d-4889-91c6-af72e96e41e6.png)
![727634EF-80C0-416F-917E-784ADE11048C](https://user-images.githubusercontent.com/115851499/195963282-a403bbb8-22cd-4cbb-a012-d6ba8c5ccfd5.png)
![D2208A7E-39F8-4CCB-8433-F84AF57BD9FA](https://user-images.githubusercontent.com/115851499/195963284-ec9a5047-37e5-45e5-858c-4631a495d48f.png)
![3A582D47-9287-435A-914C-F517CC2828A8](https://user-images.githubusercontent.com/115851499/195963287-b14ec1a8-adfa-4338-8acf-5ff9dd27a71c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build - Tdizz
