### ISSUE TITLE
USA - Missing OST

### ISSUE THREAD

**Issue by GoldenShowa** [TNODevs/TNO-Bug-Tracker#1105]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Most of the TNO OST is missing in game: 
Burgund Erwacht, Einigkeit und Recht und Freiheit, German Anarchy Theme, 
I Will Return Remix. Russian Anarchy Theme, Slave Revolt, The Battle Continues, 
The Final War, The Gun Pointed at the Heart of Africa, Nuke Atmosphere

### Steps to reproduce / Cause of the issue

When opening the music player, one can see that the TNO soundtrack is missing most of the previous soundtracks. I don't believe this was intended as two older soundtracks, "TNO Main Theme" (now known as Toolbox Theory) and "The Great Trial" are present along with the new ones that were added with Unfinished Business. Re-add them NOW pls!! "I Will Return" was a BANGER!!!!

### Expected behaviour

Re-add the missing soundtracks

### Screenshots

![OST issue](https://user-images.githubusercontent.com/94769222/195964915-c18abe00-edc5-4ec3-b0ea-ebb9b03bc92c.png)

![OST issue 2](https://user-images.githubusercontent.com/94769222/195965228-45845fd4-a45c-4c4b-ba40-2a8638cfe6ed.png)

**Comment by runelead00** [comment]
Songs were removed following a break with songs' composer
