### ISSUE TITLE
ENG - Focus doesn't remove claim

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1107]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The NDL focus "Rescind Our Claims" doesn't actually do anything because it rescinds claims on Ascension and Saint Helena despite England having cores on those states.

### Steps to reproduce / Cause of the issue

1. Play as England
2. Win civil war as HMMLR
3. Elect the NDL
4. Complete the focus Rescind Our Claims
5. Look at Saint Helena and Ascension

The reason for this issue is that the focus removes English claims rather than English cores

### Expected behaviour

The focus to remove all English claims to the islands

### Screenshots

![CaptureENG](https://user-images.githubusercontent.com/80563255/195968238-938e8bd5-8867-4391-93d6-09f03c9e7a77.PNG)

**Comment by Stormeagle449** [comment]
Fixed in Silicon Dreams.
