### ISSUE TITLE
DOM/GER/USA - Puerto Plata Invasion does not conclude in Cold War

### ISSUE THREAD

**Issue by Battletank09** [TNODevs/TNO-Bug-Tracker#1108]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Uploading Trujillo Bug.zip…]()

### Describe the bug

The Puerto Plata Invasion did not conclude after Trujillo's Victory in the Cold War Screen

### Steps to reproduce / Cause of the issue

1. (OPTIONAL) Invest in AA research and produce basic related equipment
2. Provide Support to DR as Germany (I was Speer)
3. Have DR Win

### Expected behaviour

German Victory applied after the fact

### Screenshots

![image](https://user-images.githubusercontent.com/53159932/195970133-24c7715f-8944-4b0f-8bb1-6faf22070606.png)

**Comment by runelead00** [comment]
Fixed in Current Release
