### ISSUE TITLE
USA - Colombia Events Bugged

### ISSUE THREAD

**Issue by Legendarybort** [TNODevs/TNO-Bug-Tracker#1109]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe the bug

America's events involving the Colombian Civil War appear not to be displaying correctly. They didn't show the proper event name or text. 

### Steps to reproduce / Cause of the issue

Play as US, progress to Colombian intervention. 

### Expected behaviour

Colombian events did not display text.

**Comment by runelead00** [comment]
Fixed in Dev Build
