### ISSUE TITLE
Omolon  - Omolon Can Still Go To War With Central Siberia After Collapse

### ISSUE THREAD

**Issue by runelead00** [TNODevs/TNO-Bug-Tracker#111]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?  None, I have all expansions

**Longer Description of Issue:**
During a Speer game, the Divine Mandate collapsed and the Sudoplatov's remnant declared war on the SWF and its breakaways in 69. 

**Screenshots:**
![OMO Still War](https://user-images.githubusercontent.com/74165171/131286288-ab111c5b-5962-4c6d-ba2b-d5ded6f5b8b1.jpg)

**Comment by masterbobli** [comment]
Hopefully fixed in dev build
