### ISSUE TITLE
CTD - Free France Reclamation Crash

### ISSUE THREAD

**Issue by Noobjoexe** [TNODevs/TNO-Bug-Tracker#1110]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

Last Waltz of Europe, Last Waltz of Europe Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB, BBA

### Files

[Crash files.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9791337/Crash.files.zip)

### Describe the crash

Game freezes for a while when it reaches June 30 16:00 then it crashes.

### Steps to reproduce / Cause of the crash

1. Load save
2. Wait until June 30 16:00
3. Game freezes then crashes

### Additional information

By looking at the Game log file it looks that it's the French reclamation that causes the crash.

**Comment by runelead00** [comment]
Fixed in Dev Build
