### ISSUE TITLE
There are two "quit" buttons on the exit to menu screen (the one that shows country overview).

### ISSUE THREAD

**Issue by DantheAlligatorMan** [TNODevs/TNO-Bug-Tracker#1111]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3bb

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

There are two quit buttons in the "game overview" screen that appears when one resigns or exits to menu. Only one (the outermost) works. This is likely to BBA changing the game overview section.

### Steps to reproduce / Cause of the issue

1. Load into game as any country.
2. Click on Exit to Menu.
3. Observe that there are two quit buttons.
4. Observe that only the second one works.

### Expected behaviour

I expected there to be only one quit button.

### Screenshots

![Screenshot 2022-10-15 164532](https://user-images.githubusercontent.com/111177827/195973393-6e463af6-694e-4deb-8fc5-efc4815136b4.png)

**Comment by Stormeagle449** [comment]
Fixed in Silicon Dreams.
