### ISSUE TITLE
Speer Germany Crash after Treaty w/Poland

### ISSUE THREAD

**Issue by Enddog** [TNODevs/TNO-Bug-Tracker#1112]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9791524/error.log)

### Describe the crash

When the event for you to sign the treaty pops up the game crashes in about 3 seconds

### Steps to reproduce / Cause of the crash

Go through Speer's focus tree for poland and do the reformist route. When you finish the last focus and get the event fot the treaty the game should crash

**Comment by runelead00** [comment]
Can't reproduce, and the error log doesn't indicate anything that would cause a crash. I'd ask for a save, but after 17 days it's unlikely you would still have a functioning one. I would recommend a reinstall of TNO though, looks like some files have not updated correctly in previous updates
