### ISSUE TITLE
USA Playthrough(Proxy Wars Indonesian Civil War)

### ISSUE THREAD

**Issue by stavrosk97** [TNODevs/TNO-Bug-Tracker#1113]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3bb

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Indonesian civil war ended yet it is still active in global conflicts

### Steps to reproduce / Cause of the issue

1. INS won
2. War still running on Global conflict

### Expected behaviour

The Global Conflict page to dissapear after the end of the civil war

### Screenshots

![Issue](https://user-images.githubusercontent.com/17128162/195979753-ffb62c56-da28-4126-aaac-33871312c6bb.png)

**Comment by runelead00** [comment]
Fixed in Current Release
