### ISSUE TITLE
CTD - Murmansk Peace Deal Crash

### ISSUE THREAD

**Issue by LostSamurai155** [TNODevs/TNO-Bug-Tracker#1114]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9791847/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9791848/game.log)

### Describe the crash

CTD 10.09.1966 or 11.09.1966 (either of those dates, sometimes the first, sometimes the other). As far as I can tell the only thing that could cause a CTD in the error log is missing texture files for the US voting GUI.

### Steps to reproduce / Cause of the crash

1. Launch the attached save file (starts on 05.09.1966)
2. Unpause until 10.09.1966 at which point the game will crash
   a) If you picked another focus once the previous one finishes (doesn't matter which one), the game will go on for one day longer and crash as a event (something about the Mafia, didn't catch the name) appears, on 11.09.1966.

**Comment by runelead00** [comment]
Fixed in Dev Build
