### ISSUE TITLE
KOM - Everyone included while hunting the opposition

### ISSUE THREAD

**Issue by Pumaxt** [TNODevs/TNO-Bug-Tracker#1115]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Played as right-wing komi ,chose to exile the left in previous national focus. Very surprised to see not only the central but also passionariyy themselves on the list of hunting the opposition.

### Steps to reproduce / Cause of the issue

-Playing as komi
-Strengthen the right wing
-Shafarevich elected as president
-chose to exile Suslov
-went to the next focus tree and then this happened

### Expected behaviour

Only left and central are included.

### Screenshots

<img width="397" alt="Screenshot 2022-10-15 133557" src="https://user-images.githubusercontent.com/87628237/195983532-6b839ca5-1772-41f1-9ed5-691499967724.png">

**Comment by runelead00** [comment]
Fixed in Dev Build
