### ISSUE TITLE
USA - Every One Gets A Fair Chance Bill Breaks

### ISSUE THREAD

**Issue by Ordinarycomet** [TNODevs/TNO-Bug-Tracker#1117]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

1.2.1B

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In RFK's right hand tree when you select the "everyone deserves a fair chance" focus no bill comes up in the decision category for you to handle. Thus you automatically fail the bill when the focus expires and this causes an absurd spike in marxist popularity.

### Steps to reproduce / Cause of the issue

1. Go down RFK's right hand tree.
2. Take his Social security focus
3.Go down and do "Everyone deserves a fair chance"
4. Watch to see if the bill pops up

### Expected behaviour

I expected the bill to pop up in the decision category so I could try and get it passed by rallying support.

**Comment by runelead00** [comment]
Fixed in Dev Build
