### ISSUE TITLE
Proxy Wars - Reinforcement Blocked

### ISSUE THREAD

**Issue by JetNebula** [TNODevs/TNO-Bug-Tracker#1118]
### Operating System

Windows 10 Home

### HOI4 version

Avalanche v1.12.3.f3bb (6b16)

### TNO version

TNO v1.3.0a - Unfinished Buisness

### Do you have other mods in use?

radio_tno

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![20221015160446_1](https://user-images.githubusercontent.com/115882710/195990918-3ba0b5f3-d3b4-418e-bad5-70e0e155fd94.jpg)

### Describe the bug

No Supply in the South African War
Description: "Reinforcements blocked: no supply from capital
I have tried to secure the shipping lanes and even tried to airdropp supply, but to no avail

### Steps to reproduce / Cause of the issue

1. fight in any proxywar as the US
2. Send your boys to die in german gunfire
3. Watch as they die instead of lacking boots and food
4. try not to cry as the krauts capture Cape Town

### Expected behaviour

to get supply on the unobstructed frontline

**Comment by runelead00** [comment]
Fixed in Current Release
