### ISSUE TITLE
Burgundy's first focus does not say "STRENG GEIHM"

### ISSUE THREAD

**Issue by MRbushguy** [TNODevs/TNO-Bug-Tracker#1119]
### Operating System

Windows 10

### HOI4 version

By Blood Alone

### TNO version

Tool Box Theory 3

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Currently, I'm playing as Sverdlovsk (Ural Military District), and while clicking on burgundy's focus tree, the first focus (Called "Unter Der Schwarzen Sonne") of Burgundy's focus tree is not marked as STRENG GEHIEM like the other ones. To be clear, I am unsure whether this affects all nations or just Sverdlovsk. I also think it might be related to the fact that they're currently doing the focus but i am unsure.I

### Steps to reproduce / Cause of the issue

1. Play as sverdlovsk
2. Click on burgundy's focus tree after some time has passed ingame (ex. 5 days)
3. The first focus should not say "STRENG GEIHM"

### Expected behaviour

The first focus (Called "Unter Der Schwarzen Sonne") in burgundy's focus tree

### Screenshots

![image](https://user-images.githubusercontent.com/94243600/195991056-1020d6a2-f943-47fd-8209-99f51f692078.png)

### Additional information

If any further info is needed from me, my discord tag is 

bush georges twin brother#2384

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
