### ISSUE TITLE
CTD - Unknown Peace Deal

### ISSUE THREAD

**Issue by 387809109** [TNODevs/TNO-Bug-Tracker#1120]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

CN translation

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792263/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792266/game.log)
[WRS_1969_08_16_05.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792287/WRS_1969_08_16_05.zip)

### Describe the crash

CTD after "Peace Conference Ends, Calculating Results..." pops up around 17 Sep 1969.

### Steps to reproduce / Cause of the crash

1. Launch the save 
2. Unpause. CTD will happen soon

### Screenshots
[Uploading WRS_1969_08_16_05.zip…]()

![image](https://user-images.githubusercontent.com/59388721/195991374-1a4b6943-768b-4ec2-b2fe-baea17a4aa6e.png)

**Comment by runelead00** [comment]
Your save file can't be opened properly, quick question, did Free France win in West Africa

**Comment by 387809109** [comment]
> Your save file can't be opened properly, quick question, did Free France win in West Africa? If not, what are some wars ongoing that are close to finishing?
Free France won the WAW few months ago. The ongoing but nearly ending wars include Serbian CW, Ethiopia-Oromo war, and Indonesia CW. Other ongoing wars include France CW, Iberian Wars, and Rurik-Yagoda war.

**Comment by runelead00** [comment]
Then it's very likely it's another instance of the game crashes when the FF reclamation starts

**Comment by runelead00** [comment]
Fixed in Dev Build
