### ISSUE TITLE
KOM - Stalina coups herself

### ISSUE THREAD

**Issue by CyberCroosh** [TNODevs/TNO-Bug-Tracker#1121]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

LibCon Stalina coups herself (after succesfully electing her) on 1st October and becomes despot.

### Steps to reproduce / Cause of the issue

It happens automatically 

### Expected behaviour

Stalina not couping herself when the stability is high

### Screenshots

![20221015154013_1](https://user-images.githubusercontent.com/115883283/195991584-2c6e6550-450d-469e-9a5c-ee26976e4f90.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
