### ISSUE TITLE
Free French Reclamation Crash

### ISSUE THREAD

**Issue by Ponchow** [TNODevs/TNO-Bug-Tracker#1122]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792323/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792342/game.log)

### Describe the crash

Game freezes on 5th of june 1969

### Steps to reproduce / Cause of the crash

Play a tomsk 
play until june 5 1969 
crash

**Comment by Max200012** [comment]
Damn I thought it was only me, is there a way to fix my savefile? I got the best possible outcome in my USA playthrough and it just got bricked because of some BS

**Comment by runelead00** [comment]
Fixed in Dev Build
