### ISSUE TITLE
OVRI as NatSoc doesn't show on pie chart

### ISSUE THREAD

**Issue by Computer64** [TNODevs/TNO-Bug-Tracker#1123]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[TNO_RUS_komi_scripted_effects.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792341/TNO_RUS_komi_scripted_effects.txt)
[TNO_RUS_komi_scripted_effects (fixed).txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792347/TNO_RUS_komi_scripted_effects.fixed.txt)

### Describe the bug

![image](https://user-images.githubusercontent.com/92990434/195993116-6871208c-c64b-44d8-b096-5a903deab731.png)

I found that every month popularity of OVRI erases and of fascism adds. I dug into the code and found a reason of that.
![image](https://user-images.githubusercontent.com/92990434/195993225-510c01c3-1aa2-484b-a714-bddbe1d23200.png)
Reason is a wrong name of variable of OVRI in scripted_effects file of Komi. KOM_National_Socialism_Wheel_Popularity is wrong name and KOM_NatSoc_Wheel_Popularity is correct name.
![image](https://user-images.githubusercontent.com/92990434/195993368-499b26fc-5697-43d2-b1d4-1063cc32de84.png)

I sent to you two files (first before fixing and second - there this error was fixed by me).

### Steps to reproduce / Cause of the issue

1. Go to common/scripted_effects/TNO_RUS_komi_scripted_effects.txt
2. Scroll to line 83 and find "set_variable = { KOM_National_Socialism_Wheel_Popularity = KOMOVRIPercent }"
3. Change that to "set_variable = { KOM_NatSoc_Wheel_Popularity = KOMOVRIPercent }"
4. Done

### Expected behaviour

Idk what I should write here...

**Comment by runelead00** [comment]
Fixed in Dev Build, Thanks for reporting and even more thanks for isolating the bug
