### ISSUE TITLE
USA- Crash after Malagasy civil war victory

### ISSUE THREAD

**Issue by bruh562** [TNODevs/TNO-Bug-Tracker#1124]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

Last Waltz Expanded, Precise buffs-Cheat Ideas, TNO Nuclear War Gamerule

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log]
[system.log]

### Describe the crash

Won the Malagasy civil war as the USA, and there will be always an event that pops out and said that you won the Malagasy civil war. My game crashed instantly when that event came out.

### Steps to reproduce / Cause of the crash

1. Load save
2. Win the Malagasy civil war
3. The event pops out and the game crashes

### Additional information

When TT1 was released, I encountered the same problem. No matter which superpower nation I play as, the game will crash after winning the Malagasy civil war. This crash ruined my USA and Germany games. Now I can't do the blessed rfk-hart run.😭

**Comment by bruh562** [comment]
error.log

**Comment by brutus624** [comment]
I have the exact same issue with my game. I can’t progress pass the Civil War without crashing. I tried even switching to a different nation having the AI pass the event, then switch back to America even that didn’t fix it. As soon as I switched back to America, my game crashed.

**Comment by brutus624** [comment]
Hey dude I worked out a way to fix it it's just the mods

 

the solution is just turn off all your mods except tno load the save pass the event then save and then reload all mods you had enabled before then load the save that you made
