### ISSUE TITLE
USA - france reclamation crash

### ISSUE THREAD

**Issue by swim251** [TNODevs/TNO-Bug-Tracker#1125]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

DOD

### Files

[Uploading USA_1967_01_05_10.zip…]()

### Describe the crash

After clicking the event of the french reclamation, i unpause and get the notifications of the start of the war, a peace conference triggers, the game freezes and crashes to desktop after that

### Steps to reproduce / Cause of the crash

1. Load save attached
2. Click french reclamation event
3. Unpause
4. Wait for peace conference to trigger

### Screenshots

![HOI crash](https://user-images.githubusercontent.com/115885977/195993666-089eec07-2852-41a2-8e17-8a8360617d43.png)

**Comment by Mvlysebe1992** [comment]
Got the same crash.

**Comment by Bleachhead** [comment]
Same problem, gamebreaking

**Comment by TyphoonWing** [comment]
I have the same issue as well

**Comment by runelead00** [comment]
Fixed in Dev Build
