### ISSUE TITLE
Heydrich's Germany - No Warlord decisions

### ISSUE THREAD

**Issue by googhigg** [TNODevs/TNO-Bug-Tracker#1128]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792406/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792407/error.log)

### Describe the bug

During the Warlord part of Heydrich's germany playthrough, the decision category "Unifying the Vaterland" does not appear no matter what.

### Steps to reproduce / Cause of the issue

1) Pick Heydrich as the new Führer
2) Win the war
3) Reach the warlord stage

### Expected behaviour

Unlocking certain decisions after doing particular focuses

### Screenshots

![1](https://user-images.githubusercontent.com/55514534/195995043-9f576e87-d1cd-4945-b041-423a365c0481.png)
![2](https://user-images.githubusercontent.com/55514534/195995051-6e763e63-3b59-4512-82e4-45cfa481de40.png)

### Additional information

After trying to see myself what the issue is, I found out that the decision category shows only when 3 conditions are met, which are: 
     (tno\common\decisions\categories\TNO_Germay_Heydrich_caregories.txt)
     1) Must complete focus "All Eyes on Heydrich"
     2) global flag "HGR_it_has_begun" is set
     3) the government is Esoteric Nazism
     
Now for some reason I find myself with ruling party NSDAP with the National Socialist ideology and NOT Esoteric Nazism.

Have I missed to do something or is this actually a bug? I am not sure anymore.

**Comment by runelead00** [comment]
Fixed in Dev Build
