### ISSUE TITLE
Free France/Cameroon - West African War bug

### ISSUE THREAD

**Issue by tuttran21x345** [TNODevs/TNO-Bug-Tracker#1130]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[USA_1966_12_16_18.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792576/USA_1966_12_16_18.zip)

### Describe the bug

After West African War (FMA vs WAA vs PALF) peace conference Cameroon getting annexed by Free France.
Cameroon after WAW should be independent and collapse.

### Steps to reproduce / Cause of the issue

1. Play as USA
2. Wait for West Africa War
3. Make Free France wins

### Expected behaviour

I expected to Cameroon don't getting annexed by France, and after WAW ended Cameroon going to collapse

### Screenshots

![image](https://user-images.githubusercontent.com/115889579/195997344-f11fd7d2-4ce9-4f2f-838e-0443177cd0c8.png)

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
