### ISSUE TITLE
KOM - Voznesensky securing nomination

### ISSUE THREAD

**Issue by CyberCroosh** [TNODevs/TNO-Bug-Tracker#1131]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Voznesensky secures nomination even though Stalina had much more influence (51 to 86)

### Steps to reproduce / Cause of the issue

Went through the foci - focused on the center - boosting Stalina and center - cut ties with Zhdanov without ousting Voznesensky - He still took the nomination in the center primaries.

### Expected behaviour

Stalina taking the nomination for center

### Screenshots

![20221015182827_1](https://user-images.githubusercontent.com/115883283/195997787-069bb16e-fb5c-484f-bcff-c201331d3afe.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
