### ISSUE TITLE
Free France - Game freezes on French reclamation final decision. 

### ISSUE THREAD

**Issue by RedStoneIsCooler** [TNODevs/TNO-Bug-Tracker#1132]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792678/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792679/error.log)
[autosave.hoi4](https://www.mediafire.com/file/ns8zfp08be1mwpx/autosave.hoi4/file)

### Describe the bug

The game will freeze the moment the decision is pressed.

### Steps to reproduce / Cause of the issue

1. Load the save
2. Unpause and wait for event
3. Press the event option
4. The game will freeze

### Expected behaviour

The event did not complete its actions and froze instead.

**Comment by runelead00** [comment]
Fixed in Dev Build
