### ISSUE TITLE
Country BRAZIL- Troops without supplies 

### ISSUE THREAD

**Issue by PCANETO** [TNODevs/TNO-Bug-Tracker#1133]
### Operating System

Windows

### HOI4 version

Avalanche 1.12.3 - By Blood Alone - Checksum 6b16

### TNO version

v1.3.0 “Toolbox Theory - Unfinished Business”

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Good afternoon, I was playing as Brazil, and as usual sent volunteers to South Africa during the war, the problem was that my troops were not receiving supplies, even putting them in the port, and I have more than 150 convoys, I used only the base mod without any addition, the game says that the troops have no access to the capital .

### Steps to reproduce / Cause of the issue

Just send the volunteer troops, you should immediately identify that the troops are not being supplied with new equipment, so that they wear out and over time are not supplied even in a port.

### Expected behaviour

Solution

### Screenshots

![Captura de Tela (9)](https://user-images.githubusercontent.com/115892890/196000223-d1f87f0c-03fc-463f-8987-31b5d805f47e.png)
![Captura de Tela (10)](https://user-images.githubusercontent.com/115892890/196000225-f1470077-de94-47f6-9def-0ee204f138b2.png)

**Comment by runelead00** [comment]
Fixed in Current Release
