### ISSUE TITLE
Russian Warlords [The models are broken, more specifically their guns]

### ISSUE THREAD

**Issue by corn58** [TNODevs/TNO-Bug-Tracker#1134]
### Operating System

Windows 11

### HOI4 version

v1.12.3

### TNO version

v1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

The soldier models of the Russian troop are holding a rifle but there's a white blank square covering half the gun.

### Steps to reproduce / Cause of the issue

1, Select a Russian warlord [I was Tomsk]
2. Zoom into a division

### Expected behaviour

I expected to see a regular soldier but I saw a white square

### Screenshots

![20221015004732_1](https://user-images.githubusercontent.com/38385601/196002692-a64e68a0-d4dc-42e6-a05a-43b05e270be9.jpg)

**Comment by runelead00** [comment]
This can depend on renderer, are you using dx9, dx11 or openGL?

**Comment by runelead00** [comment]
Fixed in Dev Build - Tdizz
