### ISSUE TITLE
MPR - Ship with no set variant causes crash

### ISSUE THREAD

**Issue by KlyntarKing** [TNODevs/TNO-Bug-Tracker#1135]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, NSB, BBA

### Files

The save with the crash
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792781/autosave.zip)

Logs from crash by capitulating MPR
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792837/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792780/game.log)

Error from crash by hovering over the ship
[error 2.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792832/error.2.log)

### Describe the crash

Capitulating MPR or hovering over the ship with no variant crashes the game.

### Steps to reproduce / Cause of the crash

Capitulating MPR as FIN will cause a crash because the ship will go into the peace conference, due to BBA changes. Tag switching to MPR and hovering over the ship will also cause the crash.

### Screenshots

![image](https://user-images.githubusercontent.com/78797068/196002300-4188cee7-f301-4188-a5e8-3204426251dc.png)

### Additional information

The cause is event murmansk.2  and load_oob = "MPR_naval_legacy"

**Comment by runelead00** [comment]
Fixed in Dev Build
