### ISSUE TITLE
USA - 1964 Senator not displaying correctly

### ISSUE THREAD

**Issue by Legendarybort** [TNODevs/TNO-Bug-Tracker#1136]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe the bug

1964 Virgina State's Rights senator name displaying as NPP_FR_SENATOR_VIRGINA_1_2

### Steps to reproduce / Cause of the issue

Elect an NPP-Nationalist senator in Virginia in 1964

### Expected behaviour

Senator name displays correctly.

**Comment by runelead00** [comment]
Fixed in Dev Build
