### ISSUE TITLE
HAI - Typo

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1137]
### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Typo in Haiti national spirit The Never-Ending Occupation:

The influence of the occupier --> the influence of the occupier

### Additional information

![Screenshot (1278)](https://user-images.githubusercontent.com/33550299/196004869-a4987e44-9075-4504-ae94-75a73769d7b1.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
