### ISSUE TITLE
KOM - Zhdanov Calls favor despite being dead

### ISSUE THREAD

**Issue by Battletank09** [TNODevs/TNO-Bug-Tracker#1138]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Zhdanov Bug.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792942/Zhdanov.Bug.zip)

### Describe the bug

Despite Zhdanov Being Murdered by Bukharina in a plot to take power, I never cut ties with Zhdanov until then, and then I was surprised to see him cashing in some favors with Voznesky, where i interacted minimally with the system before. he had 3 favors before the mechanic was I thought canned (I did one for party collab at the beginning of the game for pp. This is a Bukharina run.)

### Steps to reproduce / Cause of the issue

1.Attack the left
2.Mitigate favors with Zhdanov as you can
3. Bukharina murders Zhdanov

### Expected behaviour

Event will not fire if Zhdanov is dead

### Screenshots

![image](https://user-images.githubusercontent.com/53159932/196005076-f812d3f7-17cd-4b95-ba08-a72bcc8a9f12.png)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
