### ISSUE TITLE
USA - Extremist Caucus Leadership Events Broken

### ISSUE THREAD

**Issue by Legendarybort** [TNODevs/TNO-Bug-Tracker#1139]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe the bug

Events pertaining to challenges and changes to the Marxist and Sovereign Caucus leadership did not correctly display the name of the character or state. After leadership change the leadership is simply blank. 

### Steps to reproduce / Cause of the issue

1. Play as US, progress to 1966 Midterms
2. Don't raise support in Extremist Caucus
4. Wait for challenges and changes to occur

### Expected behaviour

Names should display correctly.

**Comment by runelead00** [comment]
Fixed in Dev Build by Mango
