### ISSUE TITLE
USA - CTD 1963

### ISSUE THREAD

**Issue by Lorenzo-Putig** [TNODevs/TNO-Bug-Tracker#1140]
### Operating System

Windows 10

### HOI4 version

1.12.2

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792981/error.log)

### Describe the crash

The game immediately crashes to desktop on the 10th December 1963. It seems unrelated to USA content, as even if I tagswitch to another tag the game still crashes on the same date

### Steps to reproduce / Cause of the crash

Just play until the date

**Comment by runelead00** [comment]
Can't reproduce, without out game log and save to go along with error log, not much I can figure determine from this
