### ISSUE TITLE
Omsk-  Can't stop rebellion in 2 cities after Yazov came to power 1963

### ISSUE THREAD

**Issue by Igordack** [TNODevs/TNO-Bug-Tracker#1141]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I noticed that when I complete Minimize Future Liabilities left focus, Health from 4th New Guard member becomes -15  Health and + 50 Command Power when it was +20 Health and + 50 Command Power. Because of that I can't  have 100 Control and 100 Health to stop revolt. I tried 5 hours to complete this mission but just can't because the time is ending. And overall i don't like this gameplay moment when I have to sit 1 year in the decisions menu and make the same things every 5 days - very bad gameplay idea, especially with those toxic font my eyes are sick and tired.  Very hard to supress revolt - I dont know is that supposed to be so or not.

### Steps to reproduce / Cause of the issue

Research Yazov left focuses in 1963

### Expected behaviour

Not so hard suppresing revolts in cities

### Screenshots
Before Focus Minimize Future Liabilities
![tno 2](https://user-images.githubusercontent.com/47941030/196010725-480cd922-e57e-438a-a583-c720703eceba.png)

After Focus
![tno](https://user-images.githubusercontent.com/47941030/196010675-f5f21aeb-f022-41fb-bb3d-362f29d7c3e9.png)

**Comment by Igordack** [comment]
The only way to raise Health remains +15 in random city and it's often just a waste because of the Health Cap and goes for nothing.

**Comment by Igordack** [comment]
Also to raise Health Cap you need a lot of +10 decions and they also go for nothing often when it's 100 in one of the cities. Very annoying

**Comment by Igordack** [comment]
Also Base Health Loss modifiers do not work!

**Comment by Igordack** [comment]
It's cleary a bunch of bugs, especially the thing that it must be 15 to add another 20 Health, not take from me 15, how am I supposed to gain Health in that way????

**Comment by runelead00** [comment]
Fixed in upcoming hotfix
