### ISSUE TITLE
Indonesia - Disbands all factions in the world

### ISSUE THREAD

**Issue by noah-Boah** [TNODevs/TNO-Bug-Tracker#1142]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Playing as DemSoc Komi in 1965, after the Indonesian Civil War ended (OFN victory after Sukharno resigns), every faction in the world disbanded. Would assume its because of a bug relating to the disbanding of the civil war coalition factions. 

### Steps to reproduce / Cause of the issue

1. Let Sukharno resign and the two governments merge.
2. Let the new government win the civil war after capitulating the smaller states.
3. See if anything happens to the global factions.

### Expected behaviour

Only the Indonesian factions should've disbanded.

**Comment by runelead00** [comment]
by any chance, do you have a save from before this triggered, that would very helpful in isolating the bug

**Comment by noah-Boah** [comment]
[indonesiafactionbug.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9793142/indonesiafactionbug.zip)

Also unrelated, but the WAF war peace deal never fired despite all of the FMA countries capitulated

**Comment by runelead00** [comment]
Fixed the Indonesian peace deal bug, also might have given a lead into some issues with WAC as well, but we'll have to keep investigating
