### ISSUE TITLE
Ideology - Marxism-Leninism Missing Desc

### ISSUE THREAD

**Issue by HrafnTheRed** [TNODevs/TNO-Bug-Tracker#1143]
### Operating System

Macintosh

### HOI4 version

I do not know how to find that out that information

### TNO version

I do not know how to find that out that information

### Do you have other mods in use?

FPS Map, TNO Economic cheat

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Apparently “We don’t support that filetype” so here it is as plain text I guess.
[TNO_Ideologies_l_english.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/9793051/TNO_Ideologies_l_english.txt)

### Describe the bug

There is no localisation for Mikhail Suslov’s ideology of Marxism-Leninism/communist_marxism_leninism_subtype

### Steps to reproduce / Cause of the issue

1. Open the file TNO_Ideologies_l_english.yml
2. Cmd-F/whatever it is on windows for “communist_marxism_leninism_subtype"
3. It appears only on line 56, there is no description as is included for all the other communist subideologies on lines 213 through 226.

### Expected behaviour

There ought to be a description of the subideology

### Screenshots

<img width="536" alt="Screenshot 2022-10-15 at 1 48 39 PM" src="https://user-images.githubusercontent.com/92196018/196007020-f2af3fa3-a75f-4ef2-aad6-e5c9f37a0db3.png">
<img width="666" alt="Screenshot 2022-10-15 at 1 48 27 PM" src="https://user-images.githubusercontent.com/92196018/196007022-9bad2633-eb9b-4abd-bcb4-94924f2d935a.png">

### Additional information

Hope this helps. Sorry if I’m not good with the technical stuff.

**Comment by Stormeagle449** [comment]
Fixed in current version.
