### ISSUE TITLE
Research all command - console command crashes the game.

### ISSUE THREAD

**Issue by Fabian5450** [TNODevs/TNO-Bug-Tracker#1144]
### Operating System

Windows 11

### HOI4 version

Avalanche v1.12.3.f3bb (6b16)

### TNO version

v1.3.0a

### Do you have other mods in use?

NO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9793087/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9793089/error.log)

### Describe the bug

When i type in the console command "research all" the game crashes.

### Steps to reproduce / Cause of the issue

1 Start the game and pick a nation.
2. Open the console.
3. Type in "research all".
4. The game wil crash.

### Expected behaviour

I expect to be able to use the "research all" command without crashing the game.

### Screenshots

![Schermopname (1)](https://user-images.githubusercontent.com/115900927/196007764-8334016c-fc04-4b63-8815-2899e4fd790e.png)
![Schermafbeelding 2022-10-15 231424](https://user-images.githubusercontent.com/115900927/196007810-831d07aa-644d-4b25-81d3-d3f8cb4a16c2.png)

**Comment by Culetto** [comment]
+1, even after patch 1.3.0b the bug still persists

**Comment by runelead00** [comment]
Fixed in Dev Build
