### ISSUE TITLE
KOM/WRS - No Option for Komi to assimilate the Front

### ISSUE THREAD

**Issue by Battletank09** [TNODevs/TNO-Bug-Tracker#1145]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Uploading WRS Integration Bug.zip…]()

### Describe the bug

After the WRS agreed to the NAP and then the Front, there is no option for the Komi Soviet Republic to integrate the front, but it is there for the WRS to integrate me. This seems like an oversight

### Steps to reproduce / Cause of the issue

1.Left Wing Komi
2.Front agrees to NAP during the Smuta (very random, seemed to require Suslov not be in command)
3.Front agrees to the Alliance (no alliance seemed to come on map though)
4.Defeat all remaining contenders in the region

### Expected behaviour

A decision is added for Left Komi to integrate the front when they are the only 2 remaining powers and the agreements have been made

### Screenshots

![image](https://user-images.githubusercontent.com/53159932/196008663-a249ac68-08f5-472e-9388-7156a7ebe31b.png)
![image](https://user-images.githubusercontent.com/53159932/196008670-f2b035ff-9e3b-4889-b5b6-9f6d9f26ee3d.png)

### Additional information

This involved a lot of reloading, the WRS was pretty keen to backstab me at all times

**Comment by runelead00** [comment]
Fixed in Dev Build
