### ISSUE TITLE
KOM - Crash after founding COMECON

### ISSUE THREAD

**Issue by Battletank09** [TNODevs/TNO-Bug-Tracker#1146]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Uploading COMECON Crash.zip…]()

### Describe the crash

Crash after founding Comecon as Bukharina

### Steps to reproduce / Cause of the crash

1. Bukharina unites west russia
2. found COMINT
3. Found Comecon Economics

**Comment by runelead00** [comment]
Can't reproduce, plus no save file, closing and considering issue stale, rereport if reoccurs
