### ISSUE TITLE
JAP/GER/USA - Cannot Create Ballistic Missile Wings

### ISSUE THREAD

**Issue by komododad** [TNODevs/TNO-Bug-Tracker#1147]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as a nation that has ballistic missile technology  (GER, JAP, and USA at game start) , I am unable to create new missile wings from my stockpile of equipment.

If I attempt to create missile wings from stockpile, the game will give me a tooltip over the greyed out "ok button" in the air wing creation window saying that I "cannot create empty air wing!"

This happens with all ballistic missile types (SRBM, MRBM, and ICBM) across all countries with ballistic missiles, and even if I have more than enough ballistic missiles to establish a full wing.

### Steps to reproduce / Cause of the issue

1. Start new game
2. Select a country at game start that A.) has ballistic missile technology; and B.) has spare missiles in stockpile (GER and JAP are the best options)
3. Click on any available air base
4. Click the button to create a new air wing at the air base you have chosen
5. Assign any type of ballistic missile (SRBM, MRBM, or ICBM) to the new wing and then attempt to click the "ok" button

### Expected behaviour

I expected to create a new air wing at the air base I chose, equipped with ballistic missiles

### Screenshots

![20221015203927_1](https://user-images.githubusercontent.com/115905809/196012856-a42279be-ee95-406c-838a-ae77e0faf273.jpg)
![20221015203924_1](https://user-images.githubusercontent.com/115905809/196012859-19f705fd-9f15-4efe-ab09-608070f237ee.jpg)
![20221015203922_1](https://user-images.githubusercontent.com/115905809/196012861-a5862c69-4bb9-46ce-8a0c-434fddc72c0b.jpg)
![20221015203753_1](https://user-images.githubusercontent.com/115905809/196012863-3ceb7f49-36c7-4e2c-be0c-39ff4fbd9dda.jpg)
![20221015203750_1](https://user-images.githubusercontent.com/115905809/196012865-0da9a526-5397-4c69-aa3a-d3836f819bad.jpg)
![20221015203740_1](https://user-images.githubusercontent.com/115905809/196012867-88fa44cc-12a2-44c4-8a37-a7fcd4393b85.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
