### ISSUE TITLE
BUL, GER - Wrong Tsar Simeon name in german event

### ISSUE THREAD

**Issue by Simo1819** [TNODevs/TNO-Bug-Tracker#115]
**Questions**

- HOI4 Version: Newest
- TNO Version: Newest
- Any other mods in use: No
No
**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- 
(Screenshot here)
![image](https://user-images.githubusercontent.com/68729958/133891436-d60c2c9c-9bae-4e2f-966b-037d1e98cbbc.png)

-  
(Screenshot here)
It must be „Simeon" not SimeonE.

**Comment by Scarsoftime** [comment]
Fixed in the developer's build, thank you for your report.
