### ISSUE TITLE
Tomsk - Missing loc

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1152]
### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### List the loc issues below

![Screenshot (99)](https://user-images.githubusercontent.com/98137316/196014694-f88fc320-99f4-49b6-822a-795874f215af.png)
The changes from the alteration in pollution regulations are not shown.

**Comment by runelead00** [comment]
There are no changes
