### ISSUE TITLE
Tomsk - Focus has opposite effect of description

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1153]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the bug

The focus "Labor from the Chain Gang" in Likhachyov's tree refers to prison labor being used, however the law change is for prison labor to be outlawed, which is the exact opposite of what's being seen. 

### Steps to reproduce / Cause of the issue

1. Play Tomsk
2. Win the first election as Likhachyov

### Expected behaviour

That the law would change to one that allowed more expanded prison labor, rather than banning it in a contradiction to the focus's text.

### Screenshots

![Screenshot (100)](https://user-images.githubusercontent.com/98137316/196014797-aecd45d5-6cfd-4313-bab0-758cc1488573.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
