### ISSUE TITLE
Dominican Republic GdRN - Wrong ministers

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1154]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the bug

After the Caribbean Legion defeats Trujilo, the new Dominican Republic still maintains Trujilo's ministers.

### Steps to reproduce / Cause of the issue

1. Caribbean Legion wins Dominican Civil War

### Expected behaviour

That there would either be no ministers, as it is when the Caribbean Legion is spawned, or that there would be new ministers to reflect the change in government.

### Screenshots

![Screenshot (101)](https://user-images.githubusercontent.com/98137316/196014853-b3eb1410-802d-4000-af91-7287e5cad480.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
