### ISSUE TITLE
USA - All units encircled in SAW

### ISSUE THREAD

**Issue by oliverabdullahalcombahad** [TNODevs/TNO-Bug-Tracker#1155]
### Operating System

Windows 10

### HOI4 version

1.12.0x

### TNO version

1.3.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

While deploying units in SAW as USA, no matter if they actually are or not all of my units are encircled

### Steps to reproduce / Cause of the issue

1. Play USA
2. Deploy any amt of units in SAW
3. They "don't have a connection to the capital," even on the capital tile itself, they become encircled

### Expected behaviour

Not being encircled even though there's a connection to the capital

### Screenshots

Pretty self expanatory

**Comment by Thomphson20** [comment]
I have this bug as well, this also affects all the ai countries that send volunteers. With this bug SAW is unwinnable on the OFN side.

**Comment by Max200012** [comment]
SAW is winnable, just have to keep disbanding volunteer divisons and keep sending fresh ones, that's how I won it. It is a pain in the ass but at least it's something

**Comment by runelead00** [comment]
Mostly fixed in most recent release version, more consistent fix coming in upcoming hotfix
