### ISSUE TITLE
Mano Campaign Crash

### ISSUE THREAD

**Issue by bosco8179** [TNODevs/TNO-Bug-Tracker#1156]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.30.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9793546/error.log)
https://mega.nz/file/mSZHwCIJ#Rz2u_VyIjqOMecRhKOOa1xYQdiogjaWmAI7xNRPv7xw

### Describe the crash

Game crashed on December 1970,reloading won't help

### Steps to reproduce / Cause of the crash

1. start the game
2. play until december 1970
3. crash

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
