### ISSUE TITLE
Failed to Load Map

### ISSUE THREAD

**Issue by NachoHD123** [TNODevs/TNO-Bug-Tracker#1157]
### Operating System

windows 11

### HOI4 version

1.11.5

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

(sorry may bad english)
I downloaded the TNO mod and when I install it it sends me the error "failed to load the map" and I tried everything to be able to play it, changed the version, deactivated dlc, uninstalled the game, etc...
but no matter what I do the error is always there
![Captura de pantalla 2022-10-16 005528](https://user-images.githubusercontent.com/115906080/196017312-5d20ce61-6c17-48dd-bb0a-c5f4937d7e2a.png)

the vanilla game works fine for me without any problem

### Describe the crash

it starts with the loading screen of the mod, then when the bar reaches the middle the game closes and sends the error "failed to load the map"

### Steps to reproduce / Cause of the crash

1. i open the game
2. wait to the loading screen
3.  the game crash

**Comment by Stormeagle449** [comment]
Can only recommend the fixes found here: #961
