### ISSUE TITLE
USA - Two Eugene McCarthy

### ISSUE THREAD

**Issue by atlas11791** [TNODevs/TNO-Bug-Tracker#1159]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![Gene](https://user-images.githubusercontent.com/115925227/196029788-dd02c452-0f04-4396-80da-c4e84f01b671.png)

### Describe the bug

Gene McCarthy is Senator for both the NPP and DNC

### Steps to reproduce / Cause of the issue

Play it?

### Expected behaviour

Not one man for diffrent Parties

### Screenshots

![Gene](https://user-images.githubusercontent.com/115925227/196029818-ecbf57c2-3490-4f0f-a7be-093bd8ee0cd1.png)

**Comment by runelead00** [comment]
Fixed in release build
