### ISSUE TITLE
BUL - Realistic After War Territories

### ISSUE THREAD

**Issue by Simo1819** [TNODevs/TNO-Bug-Tracker#116]
**Questions**

- Operating System: Win10 pro
- HOI4 Version: Newest
- TNO Version: Newest
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have?
I have every one of them.

**Longer Description of Issue:**
WW2 ended and Yugoslavia and Greece lose the war. Bulgaria had claims for some of the regions in Greece and Yugoslavia because a lot of bulgarians lived there. I suggest to add more territories to Bulgaria - Nis, Thessaloniki and Anatoliki Makedonia Because Bulgaria were member of the Axis powers and they administrate Anatoliki Makedonia in 1941-1944 before USSR invading Bulgaria. Nis and Thessaloniki are Serb and Greek territories and if Greece and Serbia exist these territories must be bulgarian core as a reword of there participation in ww2 and help for Germany. Central Thrace also can be Bulgarian as Bulgaria also administrate the region in ww2.
**Steps to Reproduce/Cause Issue:**

1. Play as Bulgaria

**Screenshots:**
![image](https://user-images.githubusercontent.com/68729958/133891750-c8867b3a-7f0e-49c8-ab16-fa30712e7f9a.png)
![image](https://user-images.githubusercontent.com/68729958/133891785-e33c0000-5613-40fb-a254-99742ed7f678.png)

**Comment by Scarsoftime** [comment]
The collapse of the Axis following the West Russian War caused Turkey and Greece to invade Bulgaria (A member of the Axis) in the hopes of weakening the Pakt's influence in the Mediterranean, losing them Thrace. There is content planned on this in Penelope's Web, I suggest looking up the Second Penelope's Web diary. There is no reason for Bulgaria to own the slice of Serbia shown in the screenshot. Note: Germany doesn't like giving 'rewards' to allies that much after WW2.
