### ISSUE TITLE
Starting superpower world tension

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1160]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![Screenshot (1297)](https://user-images.githubusercontent.com/33550299/196037823-72bfd52e-2aad-4914-b025-5537792891c4.png)

### Describe the bug

Starting tension between GER and USA is 55%, but from the past incidents it should only be 50%. For tensions between GER/JAP and USA/JAP incidents and starting tension do add up.

### Steps to reproduce / Cause of the issue

Play the game

### Expected behaviour

Have a starting USA-GER tension of 50%

**Comment by runelead00** [comment]
Fixed in Dev Build
