### ISSUE TITLE
Tech tree typos

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1161]
### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1.) Basic Infantry Rifle
Sth. is missing in the second sentence, I guess it should read "during the war"

2.) Vacuum Tube Computing
becomes should be either "became" or "have become"

3.) Infantry Weapon Improvements V
that can rectified --> that can be rectified

![Screenshot (1299)](https://user-images.githubusercontent.com/33550299/196038122-58e52683-cf02-44e4-bdf5-61fee84ae329.png)
![Screenshot (1304)](https://user-images.githubusercontent.com/33550299/196038155-92b2b908-ddcb-4fe4-953d-ebee98250615.png)
![Screenshot (1318)](https://user-images.githubusercontent.com/33550299/196038207-d5f63733-11b6-4d1f-9b7d-6b4e1bd146fa.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
