### ISSUE TITLE
News events typos

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1162]
### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1.) Lipetsk Prison Breakout
stages --> staged

2.) Israel Annexes Transjordan
international commentators --> International commentators

3.) Cymru Goch Wins Welsh Elections
his horrific --> this horrific

4.) The Lobster War Ends
Naval Fleets --> naval fleets / Reich affiliated --> Reich-affiliated

![Screenshot (1301)](https://user-images.githubusercontent.com/33550299/196038394-b7ec1dc2-9cc3-458d-a5c7-d941ee7cce47.png)
![Screenshot (1306)](https://user-images.githubusercontent.com/33550299/196038525-9a53d3d5-2ba2-4302-8802-67f42d4eaeab.png)
![Screenshot (1307)](https://user-images.githubusercontent.com/33550299/196038555-8d75f626-419a-4b4c-9b21-93ab2555b160.png)
![Screenshot (1309)](https://user-images.githubusercontent.com/33550299/196038685-d2881f7a-8f54-4579-8a03-7b649e49f79e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
