### ISSUE TITLE
KEM - Spelling mistakes

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1163]
### HOI4 version

1.12.3

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1.) Life Under the King
the Kemerovo's --> Kemerovo's

2.) The Royal Economy
downing it one gulp --> downing it in one gulp

3.) Prince Yuriy's Ideals
the realms --> the realm's

4.) On the Warpath
our internal problems settled with --> our internal problems settled

5.) The Weight of Destiny
his gaze --> her gaze / marcheds --> marched

6.) Favor Lydia's Shieldmaidens
men and woman --> men and women

7.) A Militia of Hope
their reason --> there reason

8.) Together Towards Victory
an pin --> can pin

9.) City Light
style more --> style was more

10.) The Foundries of Novosibirsk
ambition undertaking --> ambitious undertaking / mostly profoundly --> most profoundly

![Screenshot (1302)](https://user-images.githubusercontent.com/33550299/196038826-d51ddaec-bb04-45e3-b424-4c0d6f5ae260.png)
![Screenshot (1303)](https://user-images.githubusercontent.com/33550299/196038950-73a3d330-8502-488c-827e-eb918fb1c83a.png)
![Screenshot (1305)](https://user-images.githubusercontent.com/33550299/196038994-200ecb28-b4de-4ae9-9adb-dbce696475a1.png)
![Screenshot (1310)](https://user-images.githubusercontent.com/33550299/196039110-647cf26d-d9fb-4df6-836f-54371e5aa5fc.png)
![Screenshot (1311)](https://user-images.githubusercontent.com/33550299/196039139-caa7ba9e-5b1c-463d-9781-325aa993abae.png)
![Screenshot (1312)](https://user-images.githubusercontent.com/33550299/196039284-dff8915e-f2f1-443a-8008-1c88e7940df7.png)
![Screenshot (1313)](https://user-images.githubusercontent.com/33550299/196039322-724eea8c-7ca4-45bf-824f-de7d449573c1.png)
![Screenshot (1316)](https://user-images.githubusercontent.com/33550299/196039340-cbf61744-c11c-46ec-aef9-bcd6865b818b.png)
![Screenshot (1317)](https://user-images.githubusercontent.com/33550299/196039381-a280e1bc-6022-4da2-9010-5e9454cdc0d3.png)
![Screenshot (1320)](https://user-images.githubusercontent.com/33550299/196039439-3079d6d8-1464-47b6-b60f-7cfa2c63a70f.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
