### ISSUE TITLE
USA-volunteers not receiving supplies

### ISSUE THREAD

**Issue by mill3104** [TNODevs/TNO-Bug-Tracker#1164]
### Operating System

Mac OS Monterey

### HOI4 version

1.12.3.f3bb

### TNO version

1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

US volunteers sent to the Malaysian Civil War never receive supplies

### Steps to reproduce / Cause of the issue

1.Send US volunteers to the Malaysian Civil War
2. Examine their supply status
3. Note that the supplies are blocked from their capital

### Expected behaviour

The units should receive supplies if they are not encircled,

### Screenshots

<img width="1728" alt="Screen Shot 2022-10-16 at 12 59 12 PM" src="https://user-images.githubusercontent.com/107356989/196050098-2c3602ac-962f-4bfe-a483-d30b1dd25b34.png">

**Comment by runelead00** [comment]
Most robust fix will be implemented in next hotfix, although still a paradox side bug
