### ISSUE TITLE
United States - Missing Patton voters for 1948 election.

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1165]
### HOI4 version

1.11.7

### TNO version

1.3.0b

### Do you have other mods in use?

Music mods and the recall volunteer mod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- For the 1948 U.S. presidential election, Texas has 3 faithless electors for Patton, unfortunately, when one highlights over these electors, it says George S. Patton has 0 voters, and while I'm no expert on U.S. elections, seems a bit impossible to even get those electors with 0 votes.

![image](https://user-images.githubusercontent.com/25708474/196041117-54aa94b6-d1c1-42cb-ac40-6de09b2156af.png)

![image](https://user-images.githubusercontent.com/25708474/196041129-704b9016-af4c-4651-bd5c-82e53d5faac1.png)

**Comment by runelead00** [comment]
Working as Designed, these are faithless electors, Patton wasn't even on the ballot for 1948
