### ISSUE TITLE
Loading Screen Fidel Castro Quote Error

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#1166]
### HOI4 version

1.12.3

### TNO version

1.30b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/94796674/196043062-6077a403-370e-4f25-93a7-c4763780855c.png)

### Additional information

Fidel Castro opened up the sacred roots of Hyperborea to time travel to the year of Perun.

also yes i typed all the latest versions hahahahahaha blehhh

**Comment by runelead00** [comment]
Fixed in Dev build
