### ISSUE TITLE
Heydrich - Decisions Missing

### ISSUE THREAD

**Issue by Khastolik** [TNODevs/TNO-Bug-Tracker#1167]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3

### Do you have other mods in use?

Peace deals and player led peace conferences and no advertisements

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9795012/error.log)

(game.log was too big to upload)

(save game file not supported)

### Describe the bug

When winning the civil war as heydrich, after the SS civil war begins, i dont get any decisions to integrate provinces, the decisions tab is fully empty which renders the game unplayable

### Steps to reproduce / Cause of the issue

Win the german civil war as heydrich (i took the middle heydrich focus tree path if that helps)
wait for the SS civil war to begin
once it begins, go through the focus tree
and you'll notice that the decisions tab is empty

### Expected behaviour

A fix for the decisions to show up

**Comment by runelead00** [comment]
Fixed in Dev Build
