### ISSUE TITLE
Bennett Elected when Wallace won the election by about 20 Electoral Votes

### ISSUE THREAD

**Issue by maarshalker** [TNODevs/TNO-Bug-Tracker#1168]
### Operating System

Windows 10

### HOI4 version

Avalanche 1.12.3

### TNO version

v1.3.0b

### Do you have other mods in use?

Music mods, last waltz of europe

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Wallace was supposed to be president but Bennett was inaugurated instead even though Wallace won by 20 EVs. 

### Steps to reproduce / Cause of the issue

idk

### Expected behaviour

Wallace inauguration

### Screenshots

![image](https://user-images.githubusercontent.com/87913592/196049279-751a9d06-a5ee-4d70-9a7b-7b8b7dcd5a4d.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
