### ISSUE TITLE
South Africa War - Total OFN Victory Bug

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#1169]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.30b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

N/A

### Describe the bug

The conclusion of the South Africa war for when the OFN wins a total victory and sets up the mandates, or at the very least receives a choice to set up said mandates and get party popularity for either the NPP or RDC does not show up. Therefore, South Africa just ends up keeping Angola, Congo, and Mozambique. The South Africa War GUI in decisions also stays.

### Steps to reproduce / Cause of the issue

1. Play USA
2. Wait for SAW
3. Win a total victory as USA
4. You will end up without mandates and a large South Africa, while the GUI for the SAW stays. You will not get party popularity

### Expected behaviour

The OFN is supposed to set up mandates and you receive party popularity for it.

### Screenshots

![image](https://user-images.githubusercontent.com/94796674/196049870-ab1f30e0-5f51-4c4e-946f-ca45a330bece.png)

### Additional information

I won this war fairly fast under JFK (yes, I am a professional gamer) so it may just be for him, however I saw some other TNO users bring up the issue earlier but never brought it up in bug reports.

**Comment by Mvlysebe1992** [comment]
Same problem with bennet

**Comment by Tallerbrute** [comment]
I looked for an event in the files that would solve this, found the victory event SAFWAR.11110, it removed the SAW from the Global Conflict screen, allowed me to do RFK's other foreign policy focuses, although it did not release the mandates. upon winning in west africa, both were gone from the global conflicts screen, although "the african quagmire" kept ticking and applying negative effects despite me having gotten out of both african wars

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
