### ISSUE TITLE
Croatia - Missing Party Localisation

### ISSUE THREAD

**Issue by TymanX3** [TNODevs/TNO-Bug-Tracker#117]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 (Latest)
- TNO Version: 1.1.2 (Latest)
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Croatia is missing localization for its authoritarian democracy party after being puppeted by the Italians via war.

**Steps to Reproduce/Cause Issue:**

1. Have Italy kill Yugoslavia

**Screenshots:**

![20210920135428_1](https://user-images.githubusercontent.com/73478032/134075423-bfcf1b32-149b-462c-9832-fb0f83702ff8.jpg)

**Comment by Scarsoftime** [comment]
Fixed in the developer build, thank you for your report.
