### ISSUE TITLE
Italy - Ascendant Navy Nat. Spirit references Gibraltar Dam

### ISSUE THREAD

**Issue by ZhukovGaming** [TNODevs/TNO-Bug-Tracker#1170]
### HOI4 version

1.12.3

### TNO version

1.30b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/66566166/196051886-289d0e3e-03d8-4dee-b5a5-3d12ca396737.png)

### Additional information

Italian "Ascendant Navy" spirit still references the Gibraltar Dam, which was removed in the latest patch as being unrealistic.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
