### ISSUE TITLE
USA - Nixon tree typos

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1171]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1.) Dixicrats --> Dixiecrats
2.) lets get --> let's get
3,) presidents faction --> president's faction / dillema --> dilemma
4.) is bearing fruit --> are bearing fruit / correspondance --> correspondence
5.) While we know --> We know
6.) Effect tooltip is missing . at the end

![Screenshot (1324)](https://user-images.githubusercontent.com/33550299/196052159-7a57ff87-eb58-42fa-ab54-85f92c2016b1.png)
![Screenshot (1325)](https://user-images.githubusercontent.com/33550299/196052188-23a0d1c5-2736-46cd-a112-abd8db886703.png)
![Screenshot (1326)](https://user-images.githubusercontent.com/33550299/196052273-88604faf-fd5e-4f7b-b203-7f4aea268c4a.png)
![Screenshot (1328)](https://user-images.githubusercontent.com/33550299/196052502-ffc5aefe-24bc-4c53-b5e0-19f71e1028f0.png)
![Screenshot (1331)](https://user-images.githubusercontent.com/33550299/196052747-50f0b0c4-a76d-49df-ae25-1a1ed3953c97.png)
![Screenshot (1332)](https://user-images.githubusercontent.com/33550299/196052929-f9a703b6-91f4-4302-bee0-6064143e2f86.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
