### ISSUE TITLE
USA - LBJ is senator twice

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1172]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

LBJ occupies both Texan senate seats

### Steps to reproduce / Cause of the issue

Load up the Senate GUI

### Expected behaviour

Texas having two different senators

### Screenshots

![Screenshot (1322)](https://user-images.githubusercontent.com/33550299/196053269-006b6e7d-2eff-4622-a18a-13d388d7bd55.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
