### ISSUE TITLE
Omsk - gauntlet mechanic, bug with Pitovranov's decisions

### ISSUE THREAD

**Issue by EpicBoXx** [TNODevs/TNO-Bug-Tracker#1174]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

One decision of the Omsk's Gauntlet mini-game is bugged, with its effects getting reversed as a result of a focus down the focus tree.

### Steps to reproduce / Cause of the issue

Play Omsk until the Gauntlet mechanic becomes available at regional phase. Hire New Guard #4 (Pitrovranov) - his decision "Cut Off the World From Them" adds +20 health too occupied cities. When this decision is modifier further down in the focus tree ("Minimize Future Liabilities" focus, if I'm not mistaken), it switches from adding +20 health to -15 health - a total reversal of the effect.

### Expected behaviour

I believe it should have substracted health and not add it from the beginning

### Screenshots

Sorry for not providing screenshots - as I re-launched the game to try and provide screenshots, whole city of Omsk randomly gets poofed into anarchy at 23 January 1963 along with some other random patches of land. I don't know how that happened so I won't report it, maybe my autosave got corrupted. 

### Additional information

Also, can't confirm, but the whole mechanic seems bugged - health of cities always degrades at 2.6 and 1.3 weekly even if modifiers from decisions and events are applied (such as reduction from "Unified Movement Planning" focus). As such it seems way to hard to succeed.

**Comment by Igordack** [comment]
I have the same here are the screenshots 
![tno](https://user-images.githubusercontent.com/47941030/196191429-3174d13e-8683-4fd4-b772-2e051f3eb326.png)
![tno 2](https://user-images.githubusercontent.com/47941030/196191464-8114ca9e-d0ff-4b37-86c0-6454d70423f7.png)
