### ISSUE TITLE
West African War - Bugged Peace Deal

### ISSUE THREAD

**Issue by vipersniper2001** [TNODevs/TNO-Bug-Tracker#1175]
### Operating System

Win11

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

text and music mods

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the West African War ended, Free France and Wolofia still exist within the FMA and in West Africa. Both countries formed a truce with the PALF. There was no event signifying the end of the war.

### Steps to reproduce / Cause of the issue

1. Free France capitulates but war continues
2. US escalates war but cann't send volunteers because FF is capitulated
3. PALF wins war

### Expected behaviour

WAW ends

### Screenshots

![20221016165431_1](https://user-images.githubusercontent.com/115953733/196058223-2522cdb1-b5f3-40b7-bdf6-2192cc3f13f8.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
