### ISSUE TITLE
While playing Vytka (one of Russian warlords)- window frezzes and stops responding 

### ISSUE THREAD

**Issue by dragogod** [TNODevs/TNO-Bug-Tracker#1176]
### Operating System

Win 11

### HOI4 version

1.12.3

### TNO version

v1.3.0b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[save file.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9795714/save.file.zip)

### Describe the crash

I have united Western Russian provinces and invading west Siberian republic and once 1969:05:21 15:00 comes up game freezes and stops responding. First i thought it might be capitulation of WSR, but when I check surrender progress they are like 15 % away from capitulation  

### Steps to reproduce / Cause of the crash

1. load save file
2. keep playing until date 1969:05:21 15:00
3. Once game freezes click somewhere
4. window freezes and you get windows usual trying to fix error 

### Screenshots

<img width="377" alt="Screenshot_4" src="https://user-images.githubusercontent.com/3165247/196058491-71e9a381-abad-4038-83a2-acd562181f52.png">

**Comment by dragogod** [comment]
Fixed crashing with annexing free France using command.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by dragogod** [comment]
got 2 more crashed 
here are reports 
[crash reports.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9810877/crash.reports.zip)
