### ISSUE TITLE
USA - Superpower GDP Per Capita Not Giving Cold War Score

### ISSUE THREAD

**Issue by Geckonator9** [TNODevs/TNO-Bug-Tracker#1177]
### Operating System

Windows 10

### HOI4 version

1.12.3.f3bb

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

On the Cold War interface, the GDP per Capita element under the Economy section of the overall score is zero for all three superpowers

### Steps to reproduce / Cause of the issue

1. Start the game (I did this as the USA as the primary nation, but I also tested and found the same thing happening as Germany and Brazil, to test this as both a different superpower and a non superpower).
2. The Cold War screen initially has many blank variables,
3. Run the game for one month for features such as sphere share of global GDP to update and other economic score factors.
4. GDP per capita score remains at zero for all three superpowers.

### Expected behaviour

GDP per capita stats should provide economic score in the Cold War mechanic.

### Screenshots

![20221016164902_1](https://user-images.githubusercontent.com/71850842/196058136-e965e7cc-d8d1-467b-b9a6-6e72a2dcf841.jpg)
![20221016170621_1](https://user-images.githubusercontent.com/71850842/196058330-d6a580af-9d3d-47d0-bdaf-1749d3cee64b.jpg)
![20221016171116_1](https://user-images.githubusercontent.com/71850842/196058509-2cbd964b-eb0e-4673-98d4-1c765e431684.jpg)

### Additional information

I tracked down the code that's supposed to calculate these scores to:

\common\scripted_effects\TNO_Cold_War_scripted_effects.txt

However, as far as I can tell nothing is wrong.  I also checked the variables with console commands and in my save file.  All other variables in the array seem to be calculated as expected while Score_Economy^1 remains at 0.  I've copied the code below for reference.

# GDP/Capita
set_variable = { Score_Economy^1 = GDP }
set_temp_variable = { pop = max_manpower_k }
divide_temp_variable = { pop = 100000 }
divide_variable = { Score_Economy^1 = pop }
multiply_variable = { Score_Economy^1 = @score_per_gdpc }

**Comment by runelead00** [comment]
Fixed in Dev Build, issue was a 3 letter var that got turned into a tag
