### ISSUE TITLE
Orenburg - Broken loc for event title

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1178]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![Screenshot (1344)](https://user-images.githubusercontent.com/33550299/196059831-12f403ff-382b-4c39-96c0-f0bf5877b00f.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
