### ISSUE TITLE
Tyumen - Broken loc for national spirit

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1179]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![Screenshot (1343)](https://user-images.githubusercontent.com/33550299/196059940-fe028d70-2208-4969-8cea-15b1a295733b.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
