### ISSUE TITLE
Mengjiang - Missing Focus Icons

### ISSUE THREAD

**Issue by TymanX3** [TNODevs/TNO-Bug-Tracker#118]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 (Latest)
- TNO Version: 1.1.2 (Latest)
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Mengjiang is missing icons for focuses "The Relentless Attack" and "Intensify Japanese Bombing"

**Steps to Reproduce/Cause Issue:**

N/A

**Screenshots:**

![20210920134310_1](https://user-images.githubusercontent.com/73478032/134076239-895ab4e4-7aea-44ad-a7a8-14b122c6e675.jpg)

**Comment by Scarsoftime** [comment]
Fixed in the developer build, thank you for your report.
