### ISSUE TITLE
Missing pic for news event about PAR-BOL war

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1180]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Missing event picture
![Screenshot (1342)](https://user-images.githubusercontent.com/33550299/196060145-1c600cc8-402f-47e8-a8da-8ec69410714e.png)

### Steps to reproduce / Cause of the issue

Get to the oil crisis

### Expected behaviour

Have a picture

**Comment by runelead00** [comment]
Fixed in Dev Build
