### ISSUE TITLE
USA - South African War - Capitulated RKs but no victory event

### ISSUE THREAD

**Issue by InterstellarWar** [TNODevs/TNO-Bug-Tracker#1181]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

(Ironman-compatible mods) Songs of the South African War, Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I won the South Africa War November 22 1964 and I did not get a victory event. South Africa owns all the RKs

### Steps to reproduce / Cause of the issue

1. Win Total Victory in South African War as USA

### Expected behaviour

To get the total victory in south africa event

### Screenshots

https://gyazo.com/3c243b544994aa3556664161fa31a83d

**Comment by mill3104** [comment]
I also got this bug. I tried using the debug command, but the African mandates still wouldn't form.

**Comment by InterstellarWar** [comment]
My temp solution was to release the countries through console and than debug

release COG
release ANG
release GRO

debug

select Total OFN victory decision

**Comment by mill3104** [comment]
> My temp solution was to release the countries through console and than debug
> 
> release COG release ANG release GRO
> 
> debug
> 
> select Total OFN victory decision in major events tab

I'll try that. I never knew what the tags were for the mandates.

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
