### ISSUE TITLE
Event for Increased Healthcare fully without loc

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1183]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The event for the increase of the healthcare level has no text, action button text, pic and no proper title.

![Screenshot (1347)](https://user-images.githubusercontent.com/33550299/196060951-50309b36-9893-4392-8528-7158600319fd.png)

**Comment by Stormeagle449** [comment]
Fixed in dev build.
