### ISSUE TITLE
Carrier capacity in the hundreds

### ISSUE THREAD

**Issue by Ballooney** [TNODevs/TNO-Bug-Tracker#1184]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Hanger space modules on carriers have 200/300/400 capacity, leading to situations where carriers could field over 1000 aircraft.

### Steps to reproduce / Cause of the issue

1. Boot game
2. Select any carrier
3. View design

### Expected behaviour

Hanger capacity should be 20/30/40 respectively.

### Screenshots

![Screenshot 2022-10-16 143749](https://user-images.githubusercontent.com/115955214/196061616-30901b4e-ee1a-4216-8c28-487f7f377d9d.png)
![Screenshot 2022-10-16 143726](https://user-images.githubusercontent.com/115955214/196061622-4a0953dd-83b5-4637-ab3d-ba3f49014eb2.png)
![Screenshot 2022-10-16 143657](https://user-images.githubusercontent.com/115955214/196061629-b329246d-c40b-44d0-bda5-43d5d82e43e8.png)
![Screenshot 2022-10-16 143534](https://user-images.githubusercontent.com/115955214/196061634-e1aea10b-2aec-42d3-b6fb-9484a2190795.png)

### Additional information

The carriers of other nations, like Japan and Germany, also have this issue.

**Comment by SaintPepsi84** [comment]
I'm experiencing the same issue, I hope it gets solved soon.

**Comment by runelead00** [comment]
Fixed in Dev Build
