### ISSUE TITLE
USA Hart - URI bills disappear then fail post oil-crisis

### ISSUE THREAD

**Issue by Looter98** [TNODevs/TNO-Bug-Tracker#1185]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

v1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9796045/error.log)

### Describe the bug

During Hart presidency URI bills mechanic will default back to an empty bill a few days after introducing a new bill. this would cause the bill to fail despite having enough senate backing. This only occurred after the start of the oil crisis.

### Steps to reproduce / Cause of the issue

Wait until Oil crisis with Hart
take a focus to vote on a URI bill
wait 1-2 days

 

### Expected behaviour

The bill interface will reset to empty and at the end of the focus the failure event will fire

### Screenshots

![hart_2](https://user-images.githubusercontent.com/35749173/196066958-05d92164-c0bf-4c91-976e-39f9451fc46f.png)
![hart_3](https://user-images.githubusercontent.com/35749173/196066962-bad839f7-eff8-42f1-8e52-90325a64ec3b.png)
![hart_1](https://user-images.githubusercontent.com/35749173/196066964-b9d83e3f-0b23-4c66-8de0-69a3ea6454d3.png)

**Comment by topgan716** [comment]
same

**Comment by runelead00** [comment]
Fixed in dev build
