### ISSUE TITLE
Iberia / Iberian Union - "Alter the Constitution" focus above the "Nueva División Azul" focus

### ISSUE THREAD

**Issue by Perseus112** [TNODevs/TNO-Bug-Tracker#1186]
### Operating System

Windows 10

### HOI4 version

1.12.3.f3bb

### TNO version

1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

no files

### Describe the GFX issue

Probably badly placed German Civil War focus tree on Iberia, colliding with the Council Focus Tree of 1963 and one of the two focuses cannot be pressed

### Steps to reproduce / Cause of the issue

Just wait until Iberian Council of 1963 and the German Civil War "aid" focus tree pops in.

### Expected behaviour

Spacing between both focus trees of course

### Screenshots

![image_2022-10-17_040051199](https://user-images.githubusercontent.com/85015534/196109958-8dc028e1-ba38-4824-a03a-855df6a27c7f.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
