### ISSUE TITLE
U.S. Carriers with 1000 Planes Capacity

### ISSUE THREAD

**Issue by SaintPepsi84** [TNODevs/TNO-Bug-Tracker#1188]
### Operating System

Windows 11

### HOI4 version

1.12

### TNO version

TT3

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB, BBA

### Describe the bug

I have noticed in several times I played as the U.S. and since the release of TT3 and BBA that all U.S. carriers have 1000 planes capacity -  something I find irrealistic and that probably is a bug.

### Steps to reproduce / Cause of the issue

1. Run HOI4 with the latest version and use the mod TNO.
2. Select the United States of America and choose as the country you will play as.
3. Go to the navy tab and check the capacity of any carrier, you will find it is 1000 planes.

### Expected behaviour

I expected carriers to have between 40 and 60 planes capacity.

### Screenshots

![Hearts of Iron IV Screenshot 2022 10 17 - 18 07 48 50](https://user-images.githubusercontent.com/44471301/196230698-ea8feb5d-e839-4e46-9ea9-b75ab2bf5141.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
