### ISSUE TITLE
USA Hart - No rail progress

### ISSUE THREAD

**Issue by thegomomma** [TNODevs/TNO-Bug-Tracker#1189]
### Operating System

Windows 10

### HOI4 version

12.1.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Describe the bug

When investing in rail as Hart they remain as Electrifying with no visible progress on the Get A Move On screen.

### Steps to reproduce / Cause of the issue

1. Play as Hart and take rail focuses to create Amtrak and invest in rail
2. Take all the decisions to modernize rail
3. Wait for progress

### Expected behaviour

Expected rail to move from electrifying to completed, unsure if other events/decisions are supposed to show up after.

### Screenshots

![20221017182110_1](https://user-images.githubusercontent.com/71211820/196294716-895a8661-a007-4e6c-956c-1c61a897d7dd.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build by Mango
