### ISSUE TITLE
Governatorato del Golfo - Missing Focus Icons

### ISSUE THREAD

**Issue by TymanX3** [TNODevs/TNO-Bug-Tracker#119]
**Questions**

-  Operating System: Windows 10
-   HOI4 Version: 1.10.8 (Latest)
-   TNO Version: 1.1.2 (Latest)
-   Any other mods in use: Radio TNO
-   Were you using Steam? Yes
-   Which expansions do you NOT have? None

**Longer Description of Issue:**

Governatorato del Golfo is missing icons for focuses "Invite Foreign Capital" and "Crackdown on Qatar"

**Steps to Reproduce/Cause Issue:**

1. Wait for Governatorato del Golfo to exist

**Screenshots:**

![20210920144639_1](https://user-images.githubusercontent.com/73478032/134076633-8ced698f-0b64-4247-8167-5299d27076c9.jpg)

**Comment by Scarsoftime** [comment]
Government of the Gulf's content is being removed in the developer build, thank you for your report.
