### ISSUE TITLE
Iberian Federation - Missing Country Name

### ISSUE THREAD

**Issue by InterstellarWar** [TNODevs/TNO-Bug-Tracker#1190]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

(Ironman Compatible mods) Radio TNO, Songs of the South African War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Iberian Federation formed and it had no country name

### Steps to reproduce / Cause of the issue

1. Watch AI form Iberian Federation

### Expected behaviour

Iberian Federation gets a country name

### Screenshots

![image](https://user-images.githubusercontent.com/61920286/196266769-efc4755c-1bf3-4f25-8a7a-27167f3693bf.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
