### ISSUE TITLE
TYM - Agricultural Ticker reset by foci

### ISSUE THREAD

**Issue by Sealeon** [TNODevs/TNO-Bug-Tracker#1191]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The following TYM national foci (in the smuta tree) reset the variable TYMAgriculturalStrainTicker when it is probably supposed to increment it:
TYM_the_hammer
TYM_the_sickle
TYM_casted_off_their_velvet_gloves
TYM_live_among_wolves

### Steps to reproduce / Cause of the issue

1. Complete any of the above stated foci
2. Observe in "The Five Year Plan" GUI that the agricultural strainer ticker has been set to 2 or -2 rather than incremented or decremented

### Expected behaviour

The agricultural strain ticker should have reduced or increased by a value of 2

**Comment by runelead00** [comment]
Fixed in Dev Build
