### ISSUE TITLE
French Reclamation Crash

### ISSUE THREAD

**Issue by hhikon** [TNODevs/TNO-Bug-Tracker#1192]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

State Transfer Tool

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9803997/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9804001/error.log)

### Describe the crash

Playing as Sablin (BRY), game freezes at exactly 18:00 3 Jul 1969, then crashes to desktop a few minutes later

### Steps to reproduce / Cause of the crash

(I'm mostly sure it's the Free French reclamation start that's causing this, the last events in the game log before the crash have to do with the reclamation. Also, annexing/getting rid of the Free French as a country fixes it)

-Pierre Poujade is the leader of the French State
-I made it so the French state collapses in civil war under Poujade using the custom country paths

**Comment by runelead00** [comment]
Fixed in Dev Build
