### ISSUE TITLE
USA - A mcgovern vs kirkpatrick debate event pops up still

### ISSUE THREAD

**Issue by Rorschach113** [TNODevs/TNO-Bug-Tracker#1193]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I’ve seen people mention on both mod feedback and reddit that there’s still an old mcgovern vs kirkpatrick debate event coming up in 1972 election despite mcgovern being removed and kirkpatrick being an RD now. Noticed noone had mentioned it here so I figured I’d make sure you’re aware.

### Steps to reproduce / Cause of the issue

Not sure tbh, I didn’t test it myself yet.

### Expected behaviour

A debate for the correct Presidential candidates would show up.

**Comment by runelead00** [comment]
Fixed in Dev Build
