### ISSUE TITLE
USA - Hart has Inaccurate Tooltips

### ISSUE THREAD

**Issue by Ordinarycomet** [TNODevs/TNO-Bug-Tracker#1194]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

1.2.1B

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Several of Hart's tooltips don't provide accurate Feedback + his poverty mechanic for cities just doesn't work. For example, with his city budget, if you have a good cities budget, the tooltip shifts to saying you're in the red, but if you have a bad city budget, it shifts to saying it's doing well. It's incredibly confusing. The same goes for Homelessness and crime, if crime is high it says it's tamed, if homelessness is high it says it's under control. Furthermore his poverty rate for cities never goes down, which means you're stuck with it always increasing crime at its max rate no matter what you do. 

### Steps to reproduce / Cause of the issue

1. Load up Hart.
2. Read his tooltips
3. Execute console commands for the sake of testing to change the values/change them manually
4. See how the tooltips for Crime, homeless and budget do not match up with the actual state of those things
5. Try and drop the city poverty rate and see how it never changes no matter what happens.

### Expected behaviour

I expected Hart's tooltips to tell me accurately when things are going well and when they are going poorly. Furthermore I expected his poverty rate in cities to actually change based on what I do.

**Comment by runelead00** [comment]
Should be fixed in dev build now according Mango
