### ISSUE TITLE
USA - OC Breaks Hart's Bills

### ISSUE THREAD

**Issue by Ordinarycomet** [TNODevs/TNO-Bug-Tracker#1196]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

1.2.1B

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Hart's bills are automatically removed from the president's desk during the oil crisis and thus they all automatically fail when their focuses time out, even if you have a majority because the game seems to think the bill isn't there, or something. As a result no bills can be passed at this point and if that's intended the game should warn you, but if it's not then well bug.

### Steps to reproduce / Cause of the issue

1. Load up Hart
2. Get to the oil Crisis
3. Try and pass a bill.
4. Look at the president's desk and see how the bill just immediately vanishes after a day

### Expected behaviour

I expected Hart to still be able to pass bills during the Oil Crisis, or at least the game to warn me or block me from passing bills until the oil crisis problems are resolved.

**Comment by runelead00** [comment]
Fixed in dev build
