### ISSUE TITLE
GER - Nerf Goering in GCW, and buff Speer

### ISSUE THREAD

**Issue by Rorschach113** [TNODevs/TNO-Bug-Tracker#1197]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Could you consider nerfing Goering in the GCW? He seems to win over half the time, and still wins a lot when I buff Speer and Bormann’s Germanies in germany’s civil war. His content is consistently highly disruptive for british and sometimes even even russian gameplay, and if he doesn’t get that far, Germany is left with *no* content. I believe he should be fairly long shot winner of GCW- should have worse odds than Bormann or Speer, but better than Heydrich. And for that matter, maybe buff Speer’s odds in civil war while you’re at it? He only wins extremely rarely.

### Justifications

Goering, who needs a rework badly and often is badly disruptive of European, British, and Russian gameplay, wins the gcw far too often. He also has no content whatsoever when he fails his invasions. Until the Goering rework, at least, I think he should be weaker in GCW and Speer should be made stronger.

**Comment by runelead00** [comment]
Balance adjusted by Concommie in dev build
