### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Jedex999** [TNODevs/TNO-Bug-Tracker#1198]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Uploading USA_1969_05_20_18.zip…]()

### Describe the crash

get a peace conference after the reclamation of France event, game crashes 

### Steps to reproduce / Cause of the crash

just happens after reclamation of france event

**Comment by runelead00** [comment]
Fixed in Dev Build
