### ISSUE TITLE
USA - Bennett mechanic parties not updated

### ISSUE THREAD

**Issue by Battletank09** [TNODevs/TNO-Bug-Tracker#1199]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Uploading Bennett Save.zip…]()

### Describe the bug

Bennett when working to pass the Silver Act has to get the Republicans on board, when the lore is now he is a Republican and it should be the democrats he needs to win the favor of, as well as potentially the NPP (not updated with new names either)
EDIT: Rock the boat mechanic is not updated either to be dems he needs to work with rather then reps

### Steps to reproduce / Cause of the issue

1.Elect Bennett
2. Work to the Silver Act

### Expected behaviour

The Party support needed is changed to be democrats and the NPP names are updated

### Screenshots

![image](https://user-images.githubusercontent.com/53159932/196312750-cc274852-5b9a-4a13-81e9-c82cf19c5d55.png)
![image](https://user-images.githubusercontent.com/53159932/196313016-ecfcce0e-4ca5-47d7-9db4-625d36e58797.png)

**Comment by runelead00** [comment]
Fixed in Dev Build by Corn
