### ISSUE TITLE
Free France glitched war

### ISSUE THREAD

**Issue by maarshalker** [TNODevs/TNO-Bug-Tracker#1201]
### Operating System

Windows 10

### HOI4 version

Avalanche 1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

Last Waltz of Europe

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Free France beat both alliances yet is stuck in the war. they are not at war with anyone but they have not released anyone. as the USA I still have the war mechanic and the discontent

### Steps to reproduce / Cause of the issue

Africa war between all 3 alliances (Free France, West Africa, Pan-Africa)

### Expected behaviour

The war to end

### Screenshots

![image](https://user-images.githubusercontent.com/87913592/196324172-b5ee9ace-e17f-4d4b-98b8-b724eb7df161.png)

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
