### ISSUE TITLE
FFR - Game Crashes Upon Declaring Reclamation War

### ISSUE THREAD

**Issue by ShinyStaraptor** [TNODevs/TNO-Bug-Tracker#1203]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3bb

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9806518/error.log)

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9806508/game.log)

I can't upload the save file because it's too big; if y'all really need it, just reply to this thread and I'll find some way to get it to y'all.

### Describe the crash

Game crashes at 6PM on July 1st, 1969, as Free France declares its reclamation war for the mainland. I confirmed this by tag switching to FFR, and clicking on the event crashes the game.

### Steps to reproduce / Cause of the crash

1. Get to a point where FFR is ready to declare their reclamation war
2. Click the event to start the reclamation war
3. mald

### Additional information

this bug ruined my Hart! run so im gonna go vote for yockey now or something idk

**Comment by runelead00** [comment]
Fixed in Dev Build
