### ISSUE TITLE
IBR - Crashes on the 7 July 1969

### ISSUE THREAD

**Issue by Jinetez** [TNODevs/TNO-Bug-Tracker#1204]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0 16/10/2022

### Do you have other mods in use?

TNO Thermonuclear War Switch

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9809744/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9809748/game.log)
[save game link (gofile)](https://gofile.io/d/T4lRgH)

### Describe the crash

Just crashes on the 7 july at 06:00

### Steps to reproduce / Cause of the crash

1. Start the save game
2. Wait
3. Magic crash

**Comment by runelead00** [comment]
Fixed in DevBuild
