### ISSUE TITLE
Free Indonesia - Ideology Icon offcentered

### ISSUE THREAD

**Issue by T3dsch1K1** [TNODevs/TNO-Bug-Tracker#1205]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.2

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The Ideology Icon for Free Indonesia (Republic of Indonesia) looks a bit wierd, offcentered

### Steps to reproduce / Cause of the issue

1.Let Hatta win the civil war

### Expected behaviour

I expected the Icon to be centered

### Screenshots

![WhatsApp Image 2022-10-18 at 17 38 24](https://user-images.githubusercontent.com/94788365/196479933-3c1e636d-9005-4d59-b334-7491b1ee1baa.jpeg)

**Comment by runelead00** [comment]
Fixed in Dev Build
