### ISSUE TITLE
Cameroonian African State - Incorrect annexation after the west aftican war

### ISSUE THREAD

**Issue by T3dsch1K1** [TNODevs/TNO-Bug-Tracker#1206]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.2

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After winning the west african war, the defeated terretories were not made into puppets and the PALF Story did not went on. 

### Steps to reproduce / Cause of the issue

1. French Military Alliance against PALF
2. Let PALF win 

### Expected behaviour

The PALF schould have created puppets and then attacked neighboring countries

### Screenshots

![Screenshot (4)](https://user-images.githubusercontent.com/94788365/196481034-21f8cad1-117c-40cc-b4fc-e128831c3822.png)

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
