### ISSUE TITLE
Heydrich's Germany - Warlord phase No decisions

### ISSUE THREAD

**Issue by LilApple** [TNODevs/TNO-Bug-Tracker#1208]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Describe the bug

As Heydrich Germany, During the warlord phase (SS Civil War) the relevant decisions are not showing (Descions such as managing the SS coalition).
Notes: No cheats were used.

### Steps to reproduce / Cause of the issue

1. Playing normaly as Heydrich's Germany.

### Expected behaviour

Having the decisons available.

### Screenshots

![Capture](https://user-images.githubusercontent.com/42142645/196512690-46232dff-0ab3-4816-bd20-1af52dfb6680.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
