### ISSUE TITLE
Indonesia Still Killing Faction (?)

### ISSUE THREAD

**Issue by MidavNibonzo** [TNODevs/TNO-Bug-Tracker#1209]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0б

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Describe the bug

Immediately after the end of the Indonesian civil war, all alliances fall apart.

### Steps to reproduce / Cause of the issue

regular game

### Expected behaviour

Having the decisons available.

### Screenshots

![image](https://user-images.githubusercontent.com/76819312/196519002-622d41e2-b0ab-4140-b0e0-5aca7a48b970.png)
![image](https://user-images.githubusercontent.com/76819312/196519083-8012830b-64d0-4482-bd0a-0694746a4f81.png)

### Additional information

No response

**Comment by runelead00** [comment]
Could you send a game log, I was certain I had fixed this for the previous hotfix, but now I don't know what's happening? Also are you certain your game has updated properly?

**Comment by MidavNibonzo** [comment]
Where to find the game log)?I have reinstalled the mod several times.

**Comment by runelead00** [comment]
It would in \Documents\Paradox Interactive\Hearts of Iron IV\logs. But it would have to be from playthrough where this occurred immediately, so if you've loaded the mod since then, it has been lost
