### ISSUE TITLE
USA, Magadan and Indonesia - Missing Idea GFX

### ISSUE THREAD

**Issue by TymanX3** [TNODevs/TNO-Bug-Tracker#121]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 (Latest)
- TNO Version: 1.1.2
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Missing GFX for the following ideas:
- [x] Landfall (Indonesia)
- [x] American Advisors (Magadan)
- [x] Air Force on Alert (USA)
- [x] Increased Dockyard Output
- [x] Navy on Alert

**Screenshots:**

![20210922184119_1](https://user-images.githubusercontent.com/73478032/134583212-3ec9d80e-3b46-4384-94bf-df93dab95932.jpg)
![20210922184015_1](https://user-images.githubusercontent.com/73478032/134583226-d0a5be45-c9cb-4cdb-a670-ca51550fbba3.jpg)
![20210922183944_1](https://user-images.githubusercontent.com/73478032/134583240-b08fccbd-d014-4297-8692-66150648782b.jpg)
![20210922183943_1](https://user-images.githubusercontent.com/73478032/134583252-3ea29428-cde8-415e-889d-fa6e23f05d16.jpg)
![20210922183941_1](https://user-images.githubusercontent.com/73478032/134583262-ee6a8f59-8f87-40d1-8830-42220ea69fae.jpg)

**Comment by Scarsoftime** [comment]
Fixed on the developer build, thank you for your report
