### ISSUE TITLE
GER - Schörner coup breaking Germany

### ISSUE THREAD

**Issue by FrieD67** [TNODevs/TNO-Bug-Tracker#1210]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

While Playing as the USA, Göring won the GCW and started attacking Norway, while i was helping Norway to defend Schörner made a coup in Germany, since then nothing happened in Germany and they didnt fight in proxy wars nor conquered the rest of Europe as seen in the screenshot. 

### Steps to reproduce / Cause of the issue

1. Playing as the USA
2. Goering win GCW
3. Defending Norway enough time that Goering stop being supported
4. Schörner make a coup and Germany stop doing anything for the rest of the game

### Expected behaviour

I expected Schörner to be, as said in the coup event, even worse than Goering in conquering all of europe, i know that Schörner doesnt have content but i did think it would have at least continued its expansion and its involvement in proxy wars

### Screenshots

![unknown (1)](https://user-images.githubusercontent.com/93049839/196522656-0b27c538-9c5c-48ad-a36c-feca95cbe6cf.png)

**Comment by runelead00** [comment]
Goering has been skeletonized, no longer an issue in current release
