### ISSUE TITLE
USA. Romney-Schlafly debate event is instead using old Mcnamera-Kirkpatrick loc

### ISSUE THREAD

**Issue by FaeAngst** [TNODevs/TNO-Bug-Tracker#1213]
### Operating System

windows 10

### HOI4 version

1.12.3

### TNO version

v1.3.0b

### Do you have other mods in use?

bi

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Event USA_debate.28. which is supposed to be the romney-schlafly debate. instead uses the loc from the mcnamara-kirkpatrick debate.

### Steps to reproduce / Cause of the issue

Run the event.

### Expected behaviour

Proper loc to be put in place

**Comment by runelead00** [comment]
Fixed in Dev Build
