### ISSUE TITLE
USA - Missing descption for Tanks and Flavor Event

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#1215]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB, BBA

### List the loc issues below

![Screenshot (177)](https://user-images.githubusercontent.com/84231463/196560466-3ffc0373-8111-48e5-adfe-12b63a9b7189.png)
Early Superheavy Tank Desc missing
![Screenshot (176)](https://user-images.githubusercontent.com/84231463/196560486-39cfb422-d40d-4338-9da3-a7da81ad1de5.png)
Basic Superheavy Tank Desc missing

![Screenshot (179)](https://user-images.githubusercontent.com/84231463/196560812-3452842d-b94c-4163-81c7-b0798ac3f8d8.png)
Description missing for end of Philippine war

**Comment by runelead00** [comment]
Fixed in Dev Build
