### ISSUE TITLE
USA - CTD November 4 1968 @ 16:00

### ISSUE THREAD

**Issue by SirStrider** [TNODevs/TNO-Bug-Tracker#1216]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0b

### Do you have other mods in use?

10 support companies for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9816148/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9816150/error.log)

### Describe the crash

Game freezes and then crashes around 4pm on the 4th of November 1968, might have something to do with the us elections or the 200 families war, both those events happen right before.

### Steps to reproduce / Cause of the crash

Not really replicable as don't know the cause sorry

### Additional information

Internet's too slow to upload a save, hopefully the logs have enough info.

**Comment by runelead00** [comment]
Fixed in Dev Build
