### ISSUE TITLE
USA - West Africa Reconstruction

### ISSUE THREAD

**Issue by AHostileDude** [TNODevs/TNO-Bug-Tracker#1217]
### Operating System

Windows 11

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Just a visual bug

### Steps to reproduce / Cause of the issue

Wait for West Africa War Recovery Reconstruction after US victory

### Expected behaviour

Image Bug

### Screenshots

![oght5pb9jmu91](https://user-images.githubusercontent.com/116133155/196580985-2505abd2-fd62-4132-a3c1-35365def522d.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
