### ISSUE TITLE
France Name missing + not in us econ spere(might not be a bug idk)

### ISSUE THREAD

**Issue by PresumedEagle10** [TNODevs/TNO-Bug-Tracker#1218]
### Operating System

win10

### HOI4 version

1.12

### TNO version

1.3.0b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

France is missing its name

### Steps to reproduce / Cause of the issue

have FreeFrance win WAW in the WA alliance, then have them retake them mainland, then get the progressive guy elected

### Expected behaviour

france to have a name

### Screenshots

![sussyfrance](https://user-images.githubusercontent.com/52302725/196612648-6f3d3e8c-e2ee-45f8-9636-a3a255a77c19.png)

**Comment by runelead00** [comment]
Should be fixed in current release
