### ISSUE TITLE
While playing Vytka (Now Russian empire) - game crashes this time generating crash log instead of just freezing 

### ISSUE THREAD

**Issue by dragogod** [TNODevs/TNO-Bug-Tracker#1219]
### Operating System

Win 11

### HOI4 version

1.12.3

### TNO version

v1.3.0b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[crash reports.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9818175/crash.reports.zip)
[Uploading New WinRAR ZIP archive.zip…]() save file

### Describe the crash

The game freezes slightly and then you get a paradox thing to send an error report.
I tried fixing it by annexing some countries America might send volunteers but it doesn't fix it
Yeah is 1972 some kind of date 

### Steps to reproduce / Cause of the crash

Honestly don't know seems to be the way it happens just by playing game

**Comment by dragogod** [comment]
[Save file.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9818203/Save.file.zip)
Save file didn't upload correctly

**Comment by runelead00** [comment]
Fixed in Dev Build, Thanks for reloading the save file it really helped in finding the error!, it was an issue with an invalid template in some volunteers America gave to Italy

**Comment by dragogod** [comment]
would annexing Italy work as a stopgap fix in the current live build ?
