### ISSUE TITLE
USA - Missing capitalization for "Leasing São Tomé" idea

### ISSUE THREAD

**Issue by TymanX3** [TNODevs/TNO-Bug-Tracker#122]
**Questions**

- HOI4 Version: 1.10.8 (Latest)
- TNO Version: 1.1.2 (Latest)
- Any other mods in use: Radio TNO

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

"it's" and "africa" should be capitalized on the national idea "Leasing São Tomé"
![20210922180605_1](https://user-images.githubusercontent.com/73478032/134584839-2c4057a1-0253-4a9c-8fa8-916a9ec13e28.jpg)

**Comment by Scarsoftime** [comment]
Screenshot displays placeholder description, has been change entirely in the developer build. Thank you for your report.
