### ISSUE TITLE
KOM - Shaferevich has Stalina's decision

### ISSUE THREAD

**Issue by Pumaxt** [TNODevs/TNO-Bug-Tracker#1220]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Uploading autosave.hoi4…]()

### Describe the bug

Shafarevich now has PSD's decision and superevent after his rigional unification and superregional unification. His flag also remained regional even after his unification of Russia.

### Steps to reproduce / Cause of the issue

Played Shafarevich's Komi and entered rigional stage. Then decisions that are supposed to belong to Stalina who had already fled from Komi became aviliable.

### Expected behaviour

I expect everyone get and only get their own events and decisions correctly

### Screenshots

<img width="832" alt="Screenshot 2022-10-15 211304" src="https://user-images.githubusercontent.com/87628237/196630579-fd5ec3a8-8f0f-4657-b4e3-80feed7c95d4.png">
![Uploading Screenshot 2022-10-15 211304.png…]()
![Uploading Screenshot 2022-10-15 211443.png…]()

### Additional information

Are these bugs triggered due to the change of ideology?

**Comment by runelead00** [comment]
Fixed in Dev Build
