### ISSUE TITLE
Burgundy Naval OOB

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1223]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. "Krigsmarine von Burgund" should be "Kriegsmarine von Burgund"
2. Englisch-Kanal-Gruppe makes no real sense in German, much better would e.g. be "Ärmelkanalgruppe"
3. Burgundy really shouldn't be using French shipnames, especially not sth. like "Strasbourg" instead of "Straßburg". I guess they could all be translated (Fleuret could be "Florett" etc,)

![Screenshot (1352)](https://user-images.githubusercontent.com/33550299/196772484-bffbe39a-144c-4801-8363-0d141c2ba2b4.png)

**Comment by runelead00** [comment]
Changed in Dev Build, oob is much less French and more accurate in German
