### ISSUE TITLE
BUR - Missing tech pic

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1224]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Burgundy has no techtree pic for 1952 infantry kit 

![Screenshot (1351)](https://user-images.githubusercontent.com/33550299/196774179-311f5b26-05b4-4923-bd13-4b4a66f1ddf5.png)

### Steps to reproduce / Cause of the issue

Load up as Burgundy

### Expected behaviour

Have a picture

**Comment by runelead00** [comment]
Works in Dev Build
