### ISSUE TITLE
BUR - Name of tank model

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1225]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Burgundian tank MBT model is named "Panzerkampfwafen X". Not sure what it's supposed to be, "Panzerkampfwaffe X" or "Panzerkampfwagen X"?
![Screenshot (1354)](https://user-images.githubusercontent.com/33550299/196774901-b5314eb9-49a3-4b52-bafa-e8d49462d3bc.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
