### ISSUE TITLE
BUR - Typos and grammar

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1226]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. Initiaton --> Initiation / Mein Ehre --> Meine Ehre
2. With Hitler's --> With Hitler
3. has been smuggled --> have been smuggled
4. made sure shook --> made sure he shook
5. Lets keep --> Let's keep
6. residance --> residence
7. Walloian --> Wallonian / Belgium people --> Belgian people
8. pointed ignored --> pointedly ignored
9. following order --> following orders / well be called --> will be called

![Screenshot (1355)](https://user-images.githubusercontent.com/33550299/196775460-08cea816-9f0a-490f-8174-770db72da161.png)
![Screenshot (1357)](https://user-images.githubusercontent.com/33550299/196775799-da2ea862-8cde-4290-ac27-8b103b27b01b.png)
![Screenshot (1358)](https://user-images.githubusercontent.com/33550299/196776048-1ab75eec-08eb-4429-a149-25d8d3d776e4.png)
![Screenshot (1359)](https://user-images.githubusercontent.com/33550299/196776328-4517aade-d98d-4e89-88c7-ded7c76ab8ed.png)
![Screenshot (1361)](https://user-images.githubusercontent.com/33550299/196776660-82d07e92-4a98-4c4e-baee-145e065140dc.png)
![Screenshot (1362)](https://user-images.githubusercontent.com/33550299/196776760-80db9b59-688c-4e51-bdd4-72fb656f8748.png)
![Screenshot (1363)](https://user-images.githubusercontent.com/33550299/196776967-f4c9b469-4389-4cdf-8d37-44a441642114.png)
![Screenshot (1364)](https://user-images.githubusercontent.com/33550299/196777189-0e869565-c89b-4686-a25c-969855b9169f.png)
![Screenshot (1365)](https://user-images.githubusercontent.com/33550299/196777652-cbe17ab2-32d6-4388-b73d-f36d8dd3e9ef.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
