### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by kaz1ch** [TNODevs/TNO-Bug-Tracker#1227]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.12.4

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9823688/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9823715/game.log)

### Describe the crash

After the Free French event france_reclamation.2 game freezes for a few minutes and then crashes.

### Steps to reproduce / Cause of the crash

1. French State elects Sidos
2. Sidos aligns with Germany
3. French civil war is triggered
4. French resistance capitulates
5. Wait for the event france_reclamation.2

### Screenshots

![aCQf1smEg19zCA3FCEZlTpv7KnTg7TahNK31TQP4O_mlzz38tW1XqBQgbxBbNvBcCOTO3kUUIC-w_wH0YAD1NeNY](https://user-images.githubusercontent.com/61201257/196787237-d899e712-0655-4103-af43-4b0e68623ab7.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
