### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Hermitcrack** [TNODevs/TNO-Bug-Tracker#1228]
### HOI4 version

1.12.4

### TNO version

v1.3.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![Premier](https://user-images.githubusercontent.com/98195018/196800414-12e66e07-992b-4b2e-a986-ed427ed2755a.png)

It's supposed to be Premier League, no e at the end. 
Also, there is no such thing as "finals" in the majority of European football league systems. All games are worth the same amount of points. But if you want me to be nitpicky here, the Premier League was founded in 1991, replacing the Football League First Division, which existed between 1888 and 1991. Refer to the Football League First Division instead of the Premier League preferably.  If you want to keep the format of "finals" in the event, you should be talking about the later stages of the FA Cup, the oldest football competition in the world, which is organised in a tournament format.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
