### ISSUE TITLE
Komi Republic - Stalina Coup Bug

### ISSUE THREAD

**Issue by Manchesterist** [TNODevs/TNO-Bug-Tracker#1229]
### Operating System

Windows 10

### HOI4 version

 Patch 1.12.4

### TNO version

TNO v1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Describe the bug

I am not sure if this is a bug or not, but the thing is that I am trying to do a liberal run as the Komi Republic, but after the elections of 1963 - when I get Ivan Morozov elected - I get couped by Stalina´s "National Reconstruction Government" (despotic Stalina), even if I have high legitimacy against possible coups. This is preventing me to play a liberal run with Ivan Morozov. Is it a bug or am I missing something?

### Steps to reproduce / Cause of the issue

Play as Komi.
Favour the liberal faction of the SMR party.
Get Ivan Morozov elected.
A few days later, regardless of your legitimacy, you will get couped by Stalina.

### Expected behaviour

...

**Comment by runelead00** [comment]
Fixed in Dev Build
