### ISSUE TITLE
COG - A few Bugs from my playthrough as an OFN Mandate

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#123]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: TNO Radio Mod
- Were you using Steam? Yes
- Which expansions do you NOT have?
I have all expansions
**Longer Description of Issue:**
- [ ]Here is an event that continuously pops up for me - nothing seems to stop it from popping up. The localization is missing too, so I cannot tell if it's deliberate. However, given that I had successfully finished the middle investment tree and kept stability up, I believe it to be a bug. The -50pp and -20% stability is probably why OFN Mandate in the Congo collapses on a regular basis

![Investors Retract Their Support](https://user-images.githubusercontent.com/56777501/134790203-aa6d310d-7d94-4d2d-886c-4b823d2768c9.jpg)

- [ ]Here's another case of missing loc, this time for a focus. 
![Meet Kasa-Vutu](https://user-images.githubusercontent.com/56777501/134790258-865525b7-c5dd-497a-8992-5c4054d30b61.jpg)

- [ ] Another piece of missing loc is for the Congo Rebels
![OFN COG Rebel Attack](https://user-images.githubusercontent.com/56777501/134790273-1128044f-e8ce-4315-9f8b-968f5b5848fc.jpg)

- [ ] Siegfried Muller is a possible FIeld Marshall for OFN Africa
![Siegfried Muller Still a FM for OFN Congo](https://user-images.githubusercontent.com/56777501/134790283-cb257f40-2565-4930-af1a-3827f2f239b1.jpg)

- [ ] Lastly Joseph Illeo has no portrait
![Joseph Illeu no portrait](https://user-images.githubusercontent.com/56777501/134790297-9c6d7747-e778-4c87-8b70-f2490e56dde3.jpg)

**Steps to Reproduce/Cause Issue:**

1. Win SAF war

2. Switch to OFN Mandate of the Congo. Play a run-through with it

If it would be more helpful for me to make separate bug reports for each, I'll be happy to do so. Idk if anyone is actively working on or maintaining OFN Congo so I figure I should put it all under one report for now. 

There were a few small things that I couldn't tell if they were bugs or just part of the gameplay (Congo is the worst OFN Mandate in-Universe so a lot of American efforts not helping makes sense), so I left them out

**Comment by runelead00** [comment]
Fixed in Current Release
