### ISSUE TITLE
FFR - Game Crashes Upon Declaring Reclamation War

### ISSUE THREAD

**Issue by mightymaus1217** [TNODevs/TNO-Bug-Tracker#1231]
### Operating System

Windows 11

### HOI4 version

1.12.4.aefa

### TNO version

1.3.0b

### Do you have other mods in use?

The Operation Thunderstorm

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9825208/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9825212/error.log)

### Describe the crash

Game crashes to desktop at 17:00 on June 30th, 1969 if not playing as Free France (I'm playing Zhukov WRRF). Free France gets the reclamation event and once they start it, the game locks up and crashes. I can play beyond 17:00 if I tag in to FFR and not select anything but when I select the one option for the event it crashes the game. 

### Steps to reproduce / Cause of the crash

Get to a point where FFR is ready to declare their reclamation war
Click the event to start the reclamation war
Be confused

### Screenshots

![unknown](https://user-images.githubusercontent.com/11999109/196829907-b02a93b5-9e88-4f89-95b7-935677b6403c.png)
![unknown](https://user-images.githubusercontent.com/11999109/196829917-ef28f0b7-66a5-42fa-85ac-ef9960d6c806.png)

### Additional information

I realize that someone had this issue before even though the most recent update should have fixed this. Unsure if there are currently other ways to fix this outside of have patience as I'm in the middle of a reunification war as WRRF.

**Comment by runelead00** [comment]
Fixed in Dev Build
