### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by fulgurboj** [TNODevs/TNO-Bug-Tracker#1234]
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

the 16th of October version

### Do you have other mods in use?

last waltz of europe

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Describe the bug

Shafarevich gets flavour stuff from Stalina and in the reunification of Russia, she appears as the unifyer. This is most likely caused due to the changes to Shafarevich's ideology, as he is the same ideology as Stalina. The easiest fix should be to revert his ideology.
![Captura de pantalla (9)](https://user-images.githubusercontent.com/84104058/197048673-e2ffa53c-083e-4039-82e6-403a91437f6b.png)

### Steps to reproduce / Cause of the issue

Elect Shafarevich 
Notice the decisions related to Stalinas party
In the regional stage, there will be a bugged election ui because the election never actually takes place
Finally, once Shafarevich unifyes Russia, the superevent will be Stalina's

### Expected behaviour

Shafarevich superevent

### Screenshots

![Captura de pantalla (9)](https://user-images.githubusercontent.com/84104058/197049768-41ef7c18-3e3a-4fa2-b3f9-4cb5c1cae02c.png)
![Captura de pantalla (10)](https://user-images.githubusercontent.com/84104058/197049782-906af0da-8cd3-4a3c-ae3d-f362435a8e1c.png)

**Comment by runelead00** [comment]
Fixed in Current Release
