### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Qwiksis** [TNODevs/TNO-Bug-Tracker#1235]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0b

### Do you have other mods in use?

TNO Unofficial Soundtrack, Tool Pack 2022

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

https://ufile.io/cvv8e
[peace_conference.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834307/peace_conference.log)
098

[random.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834308/random.log)
[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834309/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834310/sent_commands.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834311/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834312/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834313/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834314/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834315/time.log)
[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834316/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834317/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834318/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834319/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834320/executed_commands.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834322/game.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834323/graphics.log)
[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834324/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834325/message.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9834326/posted_commands.log)

### Describe the crash

The game freezes up entirely.

### Steps to reproduce / Cause of the crash

1. Play up to 17:00, 5 Jun, 1969
2. Crash

### Screenshots

![image](https://user-images.githubusercontent.com/116316629/197070453-7495679b-9052-4b60-9b8e-d1ce92f52d35.png)

### Additional information

I did not use the tool pack mod at any point in the game, I just had it as a backup. The only console commands I used were to give me political power to test the consumer production mechanic.

**Comment by runelead00** [comment]
Fixed in Current Release
