### ISSUE TITLE
USA - Graphics bug regarding showcase of Schlafly's bill natspirit

### ISSUE THREAD

**Issue by delta10210** [TNODevs/TNO-Bug-Tracker#1236]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

The New Order: VT323 Map and Cities Font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![image](https://user-images.githubusercontent.com/116318677/197079062-08238524-4d6f-4af6-b301-ceecf42d28f4.png)

### Describe the GFX issue

The natspirit of Schlafy's bill does not show up and there's an empty space where the bill should be. 

### Steps to reproduce / Cause of the issue

1. Do add_ideas USA_fetal_protection_act
2. Look at the nations natspirits
3.

### Expected behaviour

There should be a GFX that displays the Bill natspirit

### Screenshots

![image](https://user-images.githubusercontent.com/116318677/197079206-f5c2dd45-34ac-4e80-9a00-8f7a270368fe.png)
![image](https://user-images.githubusercontent.com/116318677/197079288-963ce80f-dbbd-4489-b9d1-d9cd63919f87.png)
![image](https://user-images.githubusercontent.com/116318677/197079313-d6ed56b4-aa0b-428a-bef2-5877986330cf.png)

**Comment by runelead00** [comment]
Fixed in dev build
