### ISSUE TITLE
ITA - Multiple national ideas with old Italy having Alantropa

### ISSUE THREAD

**Issue by delta10210** [TNODevs/TNO-Bug-Tracker#1237]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

The New Order: VT323 Map and Cities Font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

These nation_ideas use a GFX of Italy that has Alantropa. This is clearly outdated because TT3 has removed Alantropa. 

### Steps to reproduce / Cause of the issue

1. Use add_ideas to add the ideas to a country and see they contain the Alantropa GFX.

Fix 

1. Updating the GFX of the idea to not contain Alantropa while keeping the name of it so it applies to the previous national_spirits. 

### Expected behaviour

There should be a GFX that displays Italy without Alantropa. 

### Screenshots

Nat spirits that contain the GFX

Path to get here -->\Steam\steamapps\workshop\content\394360\2438003901\common\ideas\tno_italy.txt

![image](https://user-images.githubusercontent.com/116318677/197082960-d19f06e0-ec2a-459c-be64-8d2e4f48daad.png)

![image](https://user-images.githubusercontent.com/116318677/197083198-d46425d9-62b1-4d37-9bff-a784cf8c74b7.png)

![image](https://user-images.githubusercontent.com/116318677/197083313-f78c380a-3e96-4b06-9953-b25868630692.png)

Location of the GFX -->\Steam\steamapps\workshop\content\394360\2438003901\gfx\interface\ideas\

Then I just searched idea_ITA_GenericEconomy.dds

![image](https://user-images.githubusercontent.com/116318677/197083606-85ae4cce-7ad7-4c2b-b348-1eacabce0ac6.png)

Some examples in-game

![image](https://user-images.githubusercontent.com/116318677/197083667-36e5c838-6566-4430-8626-93e8c4025905.png)
![image](https://user-images.githubusercontent.com/116318677/197083673-2aaef894-3a82-4c3b-b1f3-3c7ef65b4717.png)
![image](https://user-images.githubusercontent.com/116318677/197083690-bda1bbe4-72b3-4c00-b95f-721745549de4.png)
![image](https://user-images.githubusercontent.com/116318677/197083703-11de19a7-7ddf-4af2-8a2c-9bdd99dc913f.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
