### ISSUE TITLE
Update Nexus to 1.3.0c

### ISSUE THREAD

**Issue by dawedss** [TNODevs/TNO-Bug-Tracker#1239]
### HOI4 version

1.12.3

### TNO version

1.3.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

You should update the file on Nexusmods to 1.3.0c.

### Justifications

It would help me very much.

**Comment by runelead00** [comment]
The nexus page is finally updated to hotfix 1.3.0c

**Comment by runelead00** [comment]
Sorry, I was lied, hotfix c and now d are still not on nexus, just hotfix b renamed to hotfix c is on nexus
