### ISSUE TITLE
USA - Shift NPP Faction Names around Slightly

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#124]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
Change the NPP faction names around so it's a bit more normalized:

NPP-Far Left for the Communists
NPP-Left for the Soc-Dems
NPP-Right for the Auth-Dems
NPP-Far Right (Yockeys) for the Fascists

OR

NPP-Far Left for the Communists
keep the current naming for NPP-C and NPP-FR and NPP-Y

**Reasoning Behind Suggestion:**
Right now the NPP's faction names are sort of odd, NPP-Far Right can suggest that the Wallace faction is either Far-Right of the NPP Coalition or Far Right of the American political spectrum. The latter seems true, since they initially represent the extreme reactionary elements of America's overton window, before evolving to becoming a more generic extremely warhawkish branch. The former does not appear to be as true, the NPP-Far Right are fairly dominant in the initial NPP set-up and there's no NPP-Right to contrast to their "NPP-Far-Right" branch. 

I think the NPP Far-Right name would be fine though if the Communists under Hall weren't called NPP-Left but instead NPP-Far-Left. The NPP-Left are treated as an American failstate, so far beyond the 1964 overton window, and also not very prominent among the NPP at the start. I feel that the NPP Center is more fitting of the NPP-Left. The name NPP-Center seems to imply that they are either very moderate on the political spectrum or dead center of the NPP political coalition, but I do not think either are particularly true. But if the NPP has its Far-Left Branch as the Communists and the NPP-Far Right are the Wallace supporters, then I think NPP-C could still be a good name to show that the majority of NPP members are more towards the Soc-Dems.

**Additional Information:**

**Comment by runelead00** [comment]
Names being adjusted in TT3/UB USA
