### ISSUE TITLE
I think Found a solution to the Volunteer Resupply Bug

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#1240]
### HOI4 version

1.12.3

### TNO version

1.2.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

The problem seems to be in the defines. After several hours of trial and error today (you can find my chicken scratch notes here: https://docs.google.com/document/d/14i-8HEIT98P4kNYVBBerJDarGVYD2CXpf_UA8REVPTE/edit?usp=sharing) the source of the problem seems to be one line: NDefines.NTrade.BASE_TRADE_FACTOR = 0, which is used twice in TNO_defines.lua

![image](https://user-images.githubusercontent.com/56777501/197112618-b9336829-5bc7-47c7-9d57-5664402e03b2.png)
![image](https://user-images.githubusercontent.com/56777501/197112632-8a01b389-d4b2-45c9-a7b2-4cf12006a279.png)

Commenting it out seems to fix resupply in Malaysia (I haven't tested it elsewhere).

See here:
![image](https://user-images.githubusercontent.com/56777501/197112773-d5f7b3aa-6537-4981-87c5-c66dfc91690d.png)

Down to 86% Supply

![image](https://user-images.githubusercontent.com/56777501/197112837-6775cabb-6016-4022-acf6-27fbbe06c0e3.png)
Resupplying

### Justifications

I don't have time unfortunately tonight to test it out in other proxy wars, but if this is a potential fix to a pretty gamebreaking bug for TNO America I think it's worth investigating.

**Comment by concommie** [comment]
God was it really that fucking simple AAAAAAAAAAA

**Comment by bobw123** [comment]
Played a quick game it seems to work in Madagascar and Philippines - any chance this might be released in a hotfix this weekend?

**Comment by concommie** [comment]
We'll definitely run tests to see if it breaks anything else but this looks to be the solution

apply for contrib we need more

**Comment by concommie** [comment]
Alright after talking with someone very knowledgeable about the econ mechanics, he recommended we keep my workaround because TNO uses a different trade system. Thank you for finding out the source of the issue.

**Comment by bobw123** [comment]
I don't think it's the trade system so much as the fact that the trade value is duplicated (and different for both). Let me try running it with the same TNO values but removing one of the lines. My guess is it was copied initially because the coder wanted a reference for what the value is supposed to be, but forgot to comment it out so it doesn't go active

**Comment by bobw123** [comment]
I did some checking - it's no so much the duplication so much as the value

Eliminating the NDefines.NTrade.BASE_TRADE_FACTOR = 0 allows supply to work
Eliminating the NDefines.NTrade.BASE_TRADE_FACTOR = 50 breaks supply

I played around with some of the values, having it at
 = 0 breaks supply
 = 1 breaks supply
 = 5 breaks supply
 = 10 supply works
 = 30 supply works
 = 50 supply works

The weird thing is regardless of what number I put it at, the base trade factor remains at 50 (For reference this is when I put the define as NDefines.NTrade.BASE_TRADE_FACTOR = 5
![image](https://user-images.githubusercontent.com/56777501/197418648-32805d08-4c86-4b15-a7e2-8e58211dd5d0.png)

Restoring TNO's trade values back to their default (with both the = 0 and =50 active) and it's the same deal
![image](https://user-images.githubusercontent.com/56777501/197418813-f0b1085b-7337-42ca-9ae7-c2ea28750a29.png)

**My guess is TNO sets the base trade value to 50 (for the USA and Germany at least) independently of the defines**. That's why the trade seems unaffected regardless of the BASE_TRADE_FACTOR from the limited testing I've done - TNO basically overrides whatever is set. Testing it again but removing the 50 define altogether and leaving in the 0 gives the same result
![image](https://user-images.githubusercontent.com/56777501/197419634-001d48a1-e4bc-4824-b4b0-f90d6b1e7965.png)

I went to Nexus to download the NSB version of TNO and check on the defines from there.
What's interesting is that in the NSB TT version and the original TT version, the duplicate values were the same (one saying 50 and one saying 0). I used kdiff3 to compare TNO_trade_scripted_effects.txt for all three versions (the current public patch, NSB compatibility, and the OG TT), and its functionally identical. My guess is BBA changed something with regards to how volunteer supply ties with trade, and somehow TNO got affected.

As far as I can tell, removing NDefines.NTrade.BASE_TRADE_FACTOR = 0 and allowing the define to = 50 does not affect the TNO trade system, The embargo system between rival nations remains the same, and the base trade factor seems to be externally set by TNO independent of HOI4's default trade system. If my understanding of the TNO trade system is correct, TNO actually sets up a parallel market system to the base HOI4 trade system. As a result I implore you to remove the define that sets trade factor to 0 - I think it would fix the volunteer system without breaking the trade system.

**Comment by bobw123** [comment]
> Alright after talking with someone very knowledgeable about the econ mechanics, he recommended we keep my workaround because TNO uses a different trade system. Thank you for finding out the source of the issue.

I'm sorry for being a pain in the ass but one though I suddenly had while out doing errands is the top line
![image](https://user-images.githubusercontent.com/56777501/197425318-0537592c-6ca3-46dc-90bb-4f15bd76a0dd.png)

According to the wiki, ALLOW_TRADE_CUT_OFF is normally 0 and if the trade factor is less than that value, no trade will be allowed. So the fact that the value is rather high (200) and far above the base trade value makes me think there is a possibility that TNO has a parallel trade system to the vanilla trade system, and it prevents the vanilla trade system from functioning by setting such a high cutoff that no country can trade with one another. 

Since you have access to someone with expertise in the functioning of the TNO trade system, would you be able to ask them if raising both the base trade factor AND the trade cutoff would allow for TNO to prevent any vanilla trades while still fixing the bug?

**Comment by concommie** [comment]
> Since you have access to someone with expertise in the functioning of the TNO trade system, would you be able to ask them if raising both the base trade factor AND the trade cutoff would allow for TNO to prevent any vanilla trades while still fixing the bug?

That is basically what he told me, that TNO uses a different trade system running parallel to the original. A tester ran a game without the workaround and with the defines fixed and said that AI nations were not using the TNO trade system.

**Comment by bobw123** [comment]
> > Since you have access to someone with expertise in the functioning of the TNO trade system, would you be able to ask them if raising both the base trade factor AND the trade cutoff would allow for TNO to prevent any vanilla trades while still fixing the bug?
> 
> That is basically what he told me, that TNO uses a different trade system running parallel to the original. A tester ran a game without the workaround and with the defines fixed and said that AI nations were not using the TNO trade system.

Does the trade system work with the defines fixed and while keeping workaround? I've been doing my test runs with the workaround still in place and it seems like the trade system works for the player (it takes a couple days though) - I can check to see if it affects the ai

**Comment by runelead00** [comment]
I've implemented it, seems to keep base game trade disabled, helps with supply even without current workaround, although it didn't work fully for Japanese in Madgascar, so the current system will also remain in place for now
