### ISSUE TITLE
USA - Opposite of intended effect in decision

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1241]
### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### List the loc issues below

![Screenshot (106)](https://user-images.githubusercontent.com/98137316/197150952-8a74ce3c-6a4a-4e29-ac31-bbbd52226d6c.png)
I highly doubt that attacking Dominican weapons stores would give them extra guns. This seems to be a case of adding guns when the intention was to remove them

**Comment by runelead00** [comment]
Fixed in Dev Build
