### ISSUE TITLE
FFR - Reclamation Victory Crash

### ISSUE THREAD

**Issue by InterstellarWar** [TNODevs/TNO-Bug-Tracker#1242]
### Operating System

Windows 10

### HOI4 version

1.1.2.4

### TNO version

1.3.0c

### Do you have other mods in use?

(Ironman Compatible Mods) Radio TNO, Songs of the South African War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the crash

The Game crashes when Free France successfully defeats the French State

### Steps to reproduce / Cause of the crash

1. Watch Free France carry out the reclamation
2. Free France wins and game crashes

### Screenshots

![image](https://user-images.githubusercontent.com/61920286/197153226-d6abe681-aaa2-4ace-8141-8eb4b81b1174.png)

**Comment by Uncurlhalo** [comment]
I have also experienced this bug in addition to an endless war Free France is stuck in.

**Comment by runelead00** [comment]
Fixed in Dev Build
