### ISSUE TITLE
OMS multiple bugs

### ISSUE THREAD

**Issue by Pyotr987** [TNODevs/TNO-Bug-Tracker#1243]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Russian warlords after latest Toolbox theory update start with 3 research slots. (I tested on Komi Amur WRRF Magadan Aryan Brotherhood. On the contrary Omsk starts with only 2 research slots.
Moreover Gauntlet mechanic is broken for Omsk because health restoration and removal of health drain decisions do not work.

### Steps to reproduce / Cause of the issue

`1. Go to Omsk.
2. Start Gauntlet.
3. Fill in control cap to 100.
4. Attempt to increase health.

### Expected behaviour

3 research slots and ability to beat Gauntlet minigame.

**Comment by runelead00** [comment]
Hopefully fixed in upcoming hotfix
