### ISSUE TITLE
[Bug]: Finland - Viipuri lore entry in wrong state

### ISSUE THREAD

**Issue by JuniperContos** [TNODevs/TNO-Bug-Tracker#1244]
### Operating System

Linux 6.0.2-arch1-1

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

VT323 Cities and Map Font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Describe the bug

The lore entry for the city of Viipuri is in the state of Käkisalmi, rather than the state of Viipuri.

### Steps to reproduce / Cause of the issue

1. Go to the state of Käkisalmi
2. Click on the state.
3. See error.

### Expected behaviour

The lore entry for the city of Viipuri would be located in the state the city is located in

### Screenshots

![20221021085125_1](https://user-images.githubusercontent.com/116360240/197201106-377878bb-9f40-4d79-915e-10cee231d1cc.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
