### ISSUE TITLE
Playing Speer Germ

### ISSUE THREAD

**Issue by YennOfVengerberg** [TNODevs/TNO-Bug-Tracker#1245]
### Operating System

Win11

### HOI4 version

1.12.4aefa

### TNO version

1.3.0c (14 oct 2022)

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[Uploading New WinRAR archive.zip…]()

### Describe the bug

Um so I loaded my autosave of 1969 1 January. After ~15 days from the start of save I got Bormann  debug event. Then I just deleted it from TNOmod files and played until 7 June 1969, where the Finns lost to CHINA?

### Steps to reproduce / Cause of the issue

1. Start "autosave file"
2. Wait something about 15 days
3. get event
4. play till June I think and get China conquering Finland

### Expected behaviour

Um, not giving debug event and not givin Karelia to China

### Screenshots

![image](https://user-images.githubusercontent.com/63299351/197209679-dc813eb4-681e-437a-aabf-8fd3ce85ee67.png)
![image](https://user-images.githubusercontent.com/63299351/197209753-122dba6c-7280-4d7b-8392-f3b3d96fb824.png)

**Comment by YennOfVengerberg** [comment]
![image](https://user-images.githubusercontent.com/63299351/197216299-02a6f633-3ff9-42da-830c-aab3a9925a9b.png)
and there is also "Middle class investment " not working despite 2 weeks have passed

**Comment by runelead00** [comment]
Likely due to a corrupted save game, caused a secret second hotfix after the last one. Sorry for the inconvenience caused by this
