### ISSUE TITLE
USA - Republicans gain enormous popularity right after election ends

### ISSUE THREAD

**Issue by TheWolfyXZ** [TNODevs/TNO-Bug-Tracker#1246]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Once Wallace is elected, regardless of party popularity, the Republicans gain a MASSIVE slice of the pie chart even when Wallace wins in a complete landslide. 

In the 66 Midterms, this effectively makes Wallace unplayable as every state has “fully secure” RD popularity.

### Steps to reproduce / Cause of the issue

Elect Wallace, wait until the event in late November that announces the end of voting

### Expected behaviour

The republicans not gaining popularity and the NPP Gaining popularity  

### Screenshots

![743F9A2D-C5F5-46A7-90DC-1B0598199014](https://user-images.githubusercontent.com/69799742/197248379-80f17648-c607-439f-9252-3afa37d816fb.png)

**Comment by Stormeagle449** [comment]
Fixed in current build.
