### ISSUE TITLE
WRS - Backstabbed by Komi

### ISSUE THREAD

**Issue by prchad** [TNODevs/TNO-Bug-Tracker#1247]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

WRRF asks Komi Soviet to get intergrated. Komi agrees. Komi asks the same thing back later, depite already being intergrated. Komi then attacked WRRF. None of the later actions make sense.

### Steps to reproduce / Cause of the issue

1. WRRF
2. Ask Left Komi to intergrate them
3. Wait for a while...
4. Komi will ask WRRF to intergrate it. Agree
5. Wait for a while...
6. Komi will still try to attack WRRF

### Expected behaviour

When in the proccess of agreed intergrate, no counter-proposal, and no backstabbing.

**Comment by runelead00** [comment]
Fixed in Dev Build
