### ISSUE TITLE
Bormann's Germany - Stahlecker doesn't join Germany's economic sphere

### ISSUE THREAD

**Issue by garthmatter** [TNODevs/TNO-Bug-Tracker#1248]
### Operating System

Windows 8

### HOI4 version

1.12.3

### TNO version

1.12.3

### Do you have other mods in use?

n

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

If Stahlecker wins the Ostland Civil War or is still a surviving contender and Bormann invites him back into the fold, Stahlecker will only join the Einheitspakt, not the German Economic Sphere. If for whatever reason Stahlecker loses and Bormann is forced to invade Ostland and create a puppet, the puppet will be in the sphere correctly.

### Steps to reproduce / Cause of the issue

The most obvious way would be to look again at the focuses Bormann has for Ostland and making sure that when he invites Ostland back into the Einsheitpakt this also includes putting them in his sphere. 

To reproduce this Bormann needs to have won and Stahlecker must be either victorious or still alive and fighting the OCW. 

### Expected behaviour

Ostland should join Germany's economic sphere.

### Additional information

I joined github to tell you this so please fix. Thank you.

**Comment by runelead00** [comment]
Should be fixed in dev build now
