### ISSUE TITLE
USA - Missing field marshal portrait

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1249]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the GFX issue

Despite being in command, the slot for Creighton Abrams's picture is blank.

### Steps to reproduce / Cause of the issue

1. Create an army as the US
2. Assign it to an army group

### Expected behaviour

That Abrams's picture would show up

### Screenshots

![Screenshot (105)](https://user-images.githubusercontent.com/98137316/197284801-628c0a86-a7fe-44b2-a385-7f01ebb86e1a.png)

**Comment by runelead00** [comment]
Paradox Bug
