### ISSUE TITLE
People's Republic of Zanzibar, Freedom Military Force: Both Countries are lead by John Okello

### ISSUE THREAD

**Issue by Bludakamp** [TNODevs/TNO-Bug-Tracker#125]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: Radio TNO: Music of the New Order, TNO Reskins, TNO: Improved City Lights
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosporus 

**Longer Description of Issue:**
After the African Devastation, John Okello leads both the People's Republic of Zanzibar and the Freedom Military Force. It doesn't seem like both these nations should spawn at the same time. 

**Steps to Reproduce/Cause Issue:**

1. Have the South African War end in stalemate

2. Have the African Devastation occur 

**Screenshots:*
[https://imgur.com/a/MFPEvNr](url)

**Comment by runelead00** [comment]
Fixed in Dev Build
