### ISSUE TITLE
Republic of Laos - Duplicate minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1251]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the GFX issue

Sisouk na Champassk is both security and economic minister

### Steps to reproduce / Cause of the issue

n/a

### Expected behaviour

n/a

### Screenshots

![Screenshot (118)](https://user-images.githubusercontent.com/98137316/197285309-f0acf7b7-6159-4ba8-84a6-92de1445d8ce.png)

**Comment by runelead00** [comment]
Non-issue, working as designed
