### ISSUE TITLE
Kingdom of Afghanistan - Missing economy minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1252]
### Operating System

Windows 11

### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the GFX issue

There is no economy minister for Afghanistan

### Steps to reproduce / Cause of the issue

n/a

### Expected behaviour

n/a

### Screenshots

![Screenshot (119)](https://user-images.githubusercontent.com/98137316/197285517-f9217647-2abc-45ba-a91a-b42db19d05d2.png)

**Comment by runelead00** [comment]
Non-issue, working as designed
