### ISSUE TITLE
RK Moskowien - Portraits not loading

### ISSUE THREAD

**Issue by T3RR5V0N** [TNODevs/TNO-Bug-Tracker#1255]
### Operating System

Ubuntu 22.04

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

TNO Guaranteed Yazov Shades, TNO loading screens / revised and improved, TNO: Loading Screens Redone

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

none of the portraits or descriptions load in the RK moskowien collapse

### Steps to reproduce / Cause of the issue

1. Boot up a game as any country
2. Wait until RK Moskowien collapses
3. Check the leader portraits for the breakaway states

### Expected behaviour

the leader portraits should be normal and not missing

### Screenshots

![20221021180557_1](https://user-images.githubusercontent.com/56271791/197296393-c0e8d296-d789-4326-8a01-a347ad123a0b.jpg)
![20221021180559_1](https://user-images.githubusercontent.com/56271791/197296396-a1e261be-a4c1-4a57-979a-388a289cbfb8.jpg)
![20221021180600_1](https://user-images.githubusercontent.com/56271791/197296398-948fe150-f3c9-4487-ab78-9d5dc40b4f14.jpg)
![20221021180601_1](https://user-images.githubusercontent.com/56271791/197296399-f8ef95f3-6db6-4268-8cd0-a3d95e48b854.jpg)
![20221021180603_1](https://user-images.githubusercontent.com/56271791/197296400-16fabdf6-0c28-425e-8db7-aea1019877cf.jpg)
![20221021180605_1](https://user-images.githubusercontent.com/56271791/197296401-e55d968b-9a9b-4c0a-a286-055d3c3de44c.jpg)
![20221021180611_1](https://user-images.githubusercontent.com/56271791/197296402-de4a5d06-8799-4691-83a2-ba8321e581c5.jpg)

**Comment by runelead00** [comment]
Can't reproduce, possible corrupted save maybe? if it reappears in another run, I'd recommend a reinstall
