### ISSUE TITLE
USA - Morrison and President's Desk when dealing with crises

### ISSUE THREAD

**Issue by TaiKangRW** [TNODevs/TNO-Bug-Tracker#1256]
### Operating System

Windows11

### HOI4 version

1.12.4

### TNO version

1.3.0b

### Do you have other mods in use?

The New Order: Last Days of Europe(CN.Ver)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

1.	If choosing to resign before the mission “Hart's Cancer Worsens” ends, and completing the focuses of Morrison, then when the mission ends, the focus “Morrison Presidency” will be executed again, and lose all the cabinet recover, the members recruited to deal with anti-URI and Chep’s motivation.
2.	If Hart’s administration is dealing with crises, then when bill comes to the President’s desk(for example, Thurgood Marshall bill, or choosing the decisions of Ted Kennedy and Walter Reuther), the bill will appear for a short time, then disappear from the decision tab. A while later, it will fail, even though it was showed to be passed before.

### Steps to reproduce / Cause of the issue

1.	If choosing to resign before the mission “Hart's Cancer Worsens” ends, and completing the focuses of Morrison, then when the mission ends, the focus “Morrison Presidency” will be executed again, and lose all the cabinet recover, the members recruited to deal with anti-URI and Chep’s motivation.
2.	If Hart’s administration is dealing with crises, then when bill comes to the President’s desk(for example, Thurgood Marshall bill, or choosing the decisions of Ted Kennedy and Walter Reuther), the bill will appear for a short time, then disappear from the decision tab. A while later, it will fail, even though it was showed to be passed before.

### Expected behaviour

1. The Chep's stuff shouldn't be reset

**Comment by runelead00** [comment]
Fixed in Dev Build
