### ISSUE TITLE
Frigate category doesn't have the right localization in the tech tree

### ISSUE THREAD

**Issue by Freudensonne** [TNODevs/TNO-Bug-Tracker#1257]
### HOI4 version

1.12.4

### TNO version

1.3.0с

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- Tech category has a description of Battleships not Frigates
![image](https://user-images.githubusercontent.com/59335678/197333282-13da1c45-f2e4-473c-ace0-cce4c99f84c8.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
