### ISSUE TITLE
New Granada - National Spirit without localization

### ISSUE THREAD

**Issue by Freudensonne** [TNODevs/TNO-Bug-Tracker#1258]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0с

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

CLC_Japanese_advisors doesn't have localization

### Steps to reproduce / Cause of the issue

1. Wait until Columbian Civil War resumes
2. Wait until Japan sends advisors to New Granada
3. It's there

### Expected behaviour

To have titles on all national spirits in the mod

### Screenshots

![image](https://user-images.githubusercontent.com/59335678/197334410-6ac515e7-a739-4de0-81cd-a1ed21495137.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
