### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Qwiksis** [TNODevs/TNO-Bug-Tracker#1259]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.30.c

### Do you have other mods in use?

TNO Unofficial Soundtrack, Tool Pack 2022

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844214/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844215/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844216/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844217/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844218/time.log)
[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844219/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844220/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844221/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844222/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844223/executed_commands.log)
https://ufile.io/qflsliew

### Describe the bug

As the MLP April Fools nation, I can softlock myself from reunifying the Far East by winning the civil war as BUR. No option appears to integrate or declare on Sablin, but when testing by annexing states, the flavor text for integration suggests that the civil war was supposed to be still going.

### Steps to reproduce / Cause of the issue

1. Play as the pony nation
2. Go to decisions
3. No decision to unify Far East or get the means to do so
4. D:

### Expected behaviour

I was hoping to reunify the far east and continue with this amazing path

### Screenshots

![image](https://user-images.githubusercontent.com/116316629/197337025-8870719d-7e48-4cb3-a7e0-11216733a379.png)
![image](https://user-images.githubusercontent.com/116316629/197337030-8b797947-80a5-4bf4-9fb8-1012fccff3fe.png)
![image](https://user-images.githubusercontent.com/116316629/197337034-dc761313-5b3d-46dc-ade1-419a03294418.png)

### Additional information

I don't know if April Fools content is supported, no problem if not.

**Comment by runelead00** [comment]
Failsafe implemented
