### ISSUE TITLE
USA - Post-Election Reactions and Transition Flavor Events

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#126]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**

There should be post-election reactions and transition flavor events included for when the new US presidents are elected.

You would have the 64' and 68' elected presidents reacting to them leaving as president in either a positive mood if elected for 2 terms or in a negative mood if voted out in their first term and seeing their opportunities and ideas go unfulfilled. 

Along with their reaction to leaving there should be also be flavor events describing the interactions of the leaving president with the incoming president and how friendly or hostile they would be. 

 e.g. Friendly: RFK welcoming and wishing Henry Jackson well as his term as president begins, while Jackson thanking RFK with what he has done for the country and for the NPP - C.

Hostile: Both Barry Goldwater and Francis Yockey forced to have to meet for a transition press talk (it doesn't go well), 
or Barry calling up all election officials, trying to see if the votes for Yockey were fraudulent, only to be constantly told no, 
that they are all valid and begins having a nervous breakdown when he finally has to accept that Yockey will become president.

**Reasoning Behind Suggestion:**

I always thought post-election there didn't seem much reaction to the incoming president or what the leaving president was thinking/reacting while they were on the way out.

Maybe adding these events could help to enhance the post-election period to see how the changing of the president is being felt during the transition period.

**Comment by runelead00** [comment]
UB will include transition letters, which should fill this niche
