### ISSUE TITLE
WRF - City name appearing as VICTORY_POINTS_6124_COM on map

### ISSUE THREAD

**Issue by tichbou** [TNODevs/TNO-Bug-Tracker#1260]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.30.c

### Do you have other mods in use?

n/a

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[wrf save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9844778/wrf.save.zip)

### Describe the bug

Not sure when it started or what city it should be but I noticed that a city started appearing as VICTORY_POINTS_6124_COM on map

### Steps to reproduce / Cause of the issue

open up the save game and see it on the map, im not sure when it triggered

### Expected behaviour

Should have had a different name (Rykov? Komi? I'm not sure). 

### Screenshots

![rykov](https://user-images.githubusercontent.com/98229246/197349206-f71b7801-b3ca-4952-85ee-4c1ad0dbd68b.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by tichbou** [comment]
Thank you!
