### ISSUE TITLE
Russian communists (Sablin in my case) - Dynamic victory points don't have loc

### ISSUE THREAD

**Issue by Freudensonne** [TNODevs/TNO-Bug-Tracker#1261]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0с

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The screenshot makes the issue obvious

### Steps to reproduce / Cause of the issue

1. Play as Sablin
2. Get hold of Rykov state

### Expected behaviour

To have them localized

### Screenshots

![image](https://user-images.githubusercontent.com/59335678/197355891-7c3409fc-b416-4aa5-a8c5-28b474cb2e56.png)

**Comment by runelead00** [comment]
Fixed in Dev BUild
