### ISSUE TITLE
Omsk is Unplayable because of Unbeatable Gauntlet Mechanic

### ISSUE THREAD

**Issue by AtlasHead5** [TNODevs/TNO-Bug-Tracker#1262]
### HOI4 version

1.12

### TNO version

1.3

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

After Yazov assumes power following Karbyshev's death there is a minigame regarding elimination of the old guard. You recruit new units and fight rebelions in Tara and Isilkul. The problem is that this minigame is unbeatable. It is extremely hard and i tried 3 separate times and always failed.

### Justifications

Unbeatable minigame without using console, It needs massive amounts of PP (decisions are expensive), this minigame is very RNG

**Comment by runelead00** [comment]
Hopefully fixed in upcoming hotfix
