### ISSUE TITLE
BUR - Focuses affect foreign provinces

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1263]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Two of the Burgundian agriculture focuses increase legion support in Cotes du Nord, which is in Brittany.

Also, focus "Penal Repair Battalions" adds a prison in Elsaß-Lothringen, which is part of Germany proper.

![Screenshot (1428)](https://user-images.githubusercontent.com/33550299/197359604-1f81cb12-5f04-4d6c-a954-5f56af407222.png)
![Screenshot (1429)](https://user-images.githubusercontent.com/33550299/197359606-e9c497a2-18e4-4b17-90f2-6e3ddcd473f6.png)
![Screenshot (1424)](https://user-images.githubusercontent.com/33550299/197359766-38f4ded8-1ad0-4799-a5d1-2cddd162b8c7.png)

### Steps to reproduce / Cause of the issue

Play the game

### Expected behaviour

Have results in your territory

**Comment by runelead00** [comment]
Fixed in Dev Build
