### ISSUE TITLE
Anachronistic Dutch leader description

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1264]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The description of Dutch leader van Geelkerken mentions the German Civil War as cause of his rise to power, but it hasn't started yet. 

![Screenshot (1423)](https://user-images.githubusercontent.com/33550299/197359902-3db95d47-665f-4544-921a-c8259efcb8b1.png)

### Steps to reproduce / Cause of the issue

Play the game

### Expected behaviour

Have another Dutch leader (description)

**Comment by runelead00** [comment]
pushed Dutch skeleton event back to start of GCW
