### ISSUE TITLE
BUR - GCW decisions

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1265]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Burgundian decisions to target the various sides in the GCW should have the respective side existing as a prerequisite. Example, Speer is already annexed and the decisions targetting him are still available.

![Screenshot (1426)](https://user-images.githubusercontent.com/33550299/197360409-8d122a30-d464-4f4d-9524-e15bde3f524b.png)

### Steps to reproduce / Cause of the issue

Play the game

### Expected behaviour

Use decisions only against existing targets

**Comment by runelead00** [comment]
Fixed in Dev Build
