### ISSUE TITLE
Komi Republic - Getting the LibDems in Power is Impossible

### ISSUE THREAD

**Issue by Tilli1** [TNODevs/TNO-Bug-Tracker#1266]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In both the first and second election in the Komi Republic, it is imposible to get the LibDems in Power. For Example, the Influence of the Liberal Guy was way higher than Stalina or the SocDem guy and the SocDem guy still won (Center was the strongest faction by far). Inbetween the elections i did everything to get LibDem popularity as high as possible but Stalina always wins the 2nd election unless you campaign for the SocDems. I'm sorry that i didn't state any names but i would have to wait 15mins just to get in the game. 

### Steps to reproduce / Cause of the issue

1. Play Komi and stay democratic (I always chose the middle Route in first Focus tree)
2. Get the LibDems Influence higher than Stalina and SocDem's
3. Result: LibDem guy doesn't win even with higher Influence 
4. For Second Election win 2nd time of troubles
5. Do all possible Foci to get more LibDem popularity
6. Campaign for the LibDems after unifiying West Russia
7. Result: Stalina always wins, by a large or small margin depending on how well you campaigned

### Expected behaviour

LibDems should have won both elections

### Additional information

My only guess for the second election is that, due to conquering radical statelets wich Influences Party Popularity, the Radical Rightists vote for Stalina (and the radical Leftists SocDem).

**Comment by runelead00** [comment]
Should be fixed in current release 1.3.0c
