### ISSUE TITLE
Heydrich germany the decisions arent showing in the ss civil war

### ISSUE THREAD

**Issue by joaobunker** [TNODevs/TNO-Bug-Tracker#1267]
### Operating System

Windows 10

### HOI4 version

v1.12.4

### TNO version

v1.3.0c

### Do you have other mods in use?

No 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The decisions of the ss civil war arent appearing

### Steps to reproduce / Cause of the issue

When germany collapses and the second civil war starts there are no decisions appearing in Heydrich germany 

### Expected behaviour

The decisions appearing

**Comment by runelead00** [comment]
Fixed in Dev Build
