### ISSUE TITLE
USA - Hart senate broken mecanic

### ISSUE THREAD

**Issue by Elprisas71** [TNODevs/TNO-Bug-Tracker#1268]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

NO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

When I start voting a Bill after 2 days dont appears in the senate mecanique and when the time ends it says that failed, that happened after the oil crisis.

### Steps to reproduce / Cause of the issue

1.Do a focus where you vote a bill
2. The will appear just for 2 days
3.And will dissapear

### Expected behaviour

I expected to work well beign a succesfull bill

**Comment by runelead00** [comment]
Fixed in Dev Build
