### ISSUE TITLE
Russian Federative Republic  - Yeltsin Russia's Flag

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#127]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**

Boris Yeltsin's Russia flag should look like the one between 1991-1993, the lighter blue Russian flag.
Here's the flag
![image](https://user-images.githubusercontent.com/84231463/139749905-bb6a3a35-6492-4832-a8bf-bcda6b5e19d8.png)

**Reasoning Behind Suggestion:**

Since the Russian Federative Republic and Novosibirsk/Russian Federation share the same color of Russia, I was thinking that Boris Yeltsin's Russian Flag should look like his flag so as to differentiate the two and gives a nod to the post-Soviet flag Yeltsin ruled under in our OTL.

**Comment by Scarsoftime** [comment]
Upon investigation of this suggestion, I found that the current flag is already the one that you suggested (Even has the same color codes).
