### ISSUE TITLE
Brazil - Infinite Event loading

### ISSUE THREAD

**Issue by Tales-Weaver** [TNODevs/TNO-Bug-Tracker#1270]
### Operating System

macOS Monterey

### HOI4 version

1.12.4

### TNO version

v1.3.0c

### Do you have other mods in use?

The Cold Southern Strings

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9845594/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9845595/error.log)

### Describe the bug

Brazil Joins Andean Pact event fires repetitively. 

### Steps to reproduce / Cause of the issue

1. Play Brazil
2. wait until July 8, 1962
3. the event fires 

### Expected behaviour

a single event firing

### Screenshots

![스크린샷 2022-10-23 오전 11 00 00](https://user-images.githubusercontent.com/86096853/197369859-e8ab69a2-307b-4e29-bf2f-c78656cb5471.png)

**Comment by runelead00** [comment]
Your save corrupted in a hotfix, nothing we can do it to fix it, you just have to restart
