### ISSUE TITLE
USA- No victory events after capitulating all three African RKs

### ISSUE THREAD

**Issue by SherbertHusky** [TNODevs/TNO-Bug-Tracker#1272]
### Operating System

Windows 10

### HOI4 version

v1.12.4aefa (ab47) (D) (S)

### TNO version

1.3.0c

### Do you have other mods in use?

TNO Radio

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[https://drive.google.com/file/d/1RkKswzsO1hTUt47S4B_2KPlZzgK2BZdu/view?usp=sharing](url)
[https://drive.google.com/file/d/1_bewUW-wIvjVpqAkO-oBztv7ywLzccEI/view?usp=sharing](url)

### Describe the bug

After a total victory in the SAW, I do not get the victory event or the event to release the OFN mandate(s). Instead, SA annexes all of the former RKs The debug menu option/event safwar.13 only gives me the victory event but doesn't release the mandate(s). 

### Steps to reproduce / Cause of the issue

1. Play as the USA
2. Wait for RFK to become president.
3. Capitulate all three African RKs
4. Get no victory events

### Expected behaviour

I should receive the victory event and the event to release the mandates.

### Screenshots

![SAW-bugged](https://user-images.githubusercontent.com/116479790/197377008-8c5c429c-3520-4c8e-b9b2-fcf3ba7478a7.PNG)

**Comment by runelead00** [comment]
do you have a save from before the end of the SAW? because one from after is useless to debugging the peace deal

**Comment by SherbertHusky** [comment]
Not one that is super close to when I encountered the bug.
[https://drive.google.com/file/d/1HqaTBlsOA_vyoWmBK2McrQNTciYbmo8C/view?usp=sharing](url)

I tested it on my own and found the bug does not occur if you capitulate the Congo RK last. in that scenario, everything appears to work as intended.

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
