### ISSUE TITLE
[Bug]: Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1273]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0C

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files
The first image is the state that has the description for Viipuri, the second image attached is the actual state of Viipuri.
![image](https://user-images.githubusercontent.com/113797283/197382626-dfa11c92-a544-4eb4-be2b-1a37dbc3d3a9.png)
![image](https://user-images.githubusercontent.com/113797283/197382796-1c1bf4cc-957e-4663-b597-6e500a42783b.png)

### Describe the bug

The Description for Viipuri is not in the same state as Viipuri, most likely a leftover from before it was made into its own state

### Steps to reproduce / Cause of the issue

1 Open Game
2 Look at Finland

### Expected behaviour

The expected behavior is that the description for Viipuri would be in the same state as it

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/197382666-47aadd55-6319-4d26-b05b-0559ab21203c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
