### ISSUE TITLE
USA - Event references outdated lore

### ISSUE THREAD

**Issue by KurtJaensch** [TNODevs/TNO-Bug-Tracker#1275]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

Last Waltz Of Europe 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The event "What Could Have Been" for Bennett is referencing presidents Joseph Kennedy and Truman.

### Steps to reproduce / Cause of the issue

Just trigger event WFB.64.t

### Expected behaviour

Wrong loc

### Screenshots

![image](https://user-images.githubusercontent.com/60235425/197383511-c9184b5c-73f2-46e9-b101-2f8107b62b96.png)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
