### ISSUE TITLE
France - Endless war with Dahomey after repelling FF

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#1276]
### Operating System

Windows 10 

### HOI4 version

1.12.3 (the latest one)

### TNO version

1.3.0c

### Do you have other mods in use?

Nope

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Free France declared war on Vichy France (Poujade no civil war). I deployed volunteers and stomped them as Bormanns Germany + got an event for winning the war aganst them. Despite this France was stuck in an endless war with Dahomey and I couldnt pull back my volunteers. 

Jist of it is: Vichy France was stuck in an endless war with Dahomey being unable to launch a naval invasion after repelling the Free French. 

Also as a sidenote, your missing LOC for the event in which Goldwater rejects Bormanns detente. 

### Steps to reproduce / Cause of the issue

FFA beats PALF 

FF invades Vichy France (Poujade no civil war)

Deployed volunteers and stomped Free France very quickly (a month or so?) 

France stuck in an endless war with Dahmoney after beating them. 

### Expected behaviour

War end normally.

**Comment by Uncurlhalo** [comment]
I've experienced this from the other side as USA. Free france is instead stuck at war with Futa Fulbe and additionally when free france wins eventually there is a CTD as in this bug. https://github.com/TNODevs/TNO-Bug-Tracker/issues/1242
