### ISSUE TITLE
GDP growth modifier for "english good on foreing shelfs" doesn't work in collab Eng tree with UE

### ISSUE THREAD

**Issue by Thicc-Shiba** [TNODevs/TNO-Bug-Tracker#1277]
### Operating System

Windows 11

### HOI4 version

1.12.4.aefa

### TNO version

1.3.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG

### Describe the bug

GDP growth modifier for "english good on foreing shelfs" doesn't work in collab Eng tree with UE, my economy remained consistently with negative growth even after completing the whole economic tree; also after the civil war was over, and even after completing the tree (i choose to remain neutral on trade) all of the OFN remained under an embargo, i guess that's not a feature cuz it wouldn't make any sense

### Steps to reproduce / Cause of the issue

complete focus "english good on foreing shelfs"

### Expected behaviour

the 8.00% GDP growth modifier doesn't work

**Comment by runelead00** [comment]
the GDP modifier affects base GDP growth by 8%, it doesn't give a flat 8% GDP growth boost
