### ISSUE TITLE
USA - Silence the Attorney General not working

### ISSUE THREAD

**Issue by simon2000234** [TNODevs/TNO-Bug-Tracker#1278]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

https://drive.google.com/file/d/1gUSaopG3jnDbm8F1EZ_SUMem0hGcl5Wr/view?usp=sharing

### Describe the bug

Silence the Attorney General under the COINTELPRO Program requires both the event to silence him and RFK to not be president. So you will always get the event "the fall" and never "he who fights monsters"

### Steps to reproduce / Cause of the issue

1. load provided save 
2. click event to sillence the attorney general
3. hover over Silence the Attorney General under the COINTELPRO Program to see its not completed
4. wait until it finishes and get the event "the fall"

### Expected behaviour

You will get the event "he who fights monsters" if you manege to sillence the attorney general

### Screenshots

https://imgur.com/a/oggmnkY

### Additional information

i assume its an "and" that needs to be changed to an "or"

**Comment by runelead00** [comment]
Fixed in Dev Build
