### ISSUE TITLE
Armored Engineer Company No Icon

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1279]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0C

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![image](https://user-images.githubusercontent.com/113797283/197387660-3f297faa-d9f7-4715-8308-65576803aceb.png)

### Describe the GFX issue

The Armored Engineer Company Support Company lacks a functional icon, instead it will copy the icon of the last used gfx piece in the the support company tab.

### Steps to reproduce / Cause of the issue

1 Open the Game
2 Research Engineer Company II
3 Open the Division Designer and look at the Armoured Engineer Company Support company
4 Add it to a division

### Expected behaviour

The expected behavior is that it would have an Icon

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/197387774-cd7b8ef6-9d0a-4447-bf50-685ae26c87ed.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
