### ISSUE TITLE
China - Negative Electricity

### ISSUE THREAD

**Issue by Tilli1** [TNODevs/TNO-Bug-Tracker#1281]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

China has negative Electricity due to Buildings now consuming Electricity. For this reason it is impossible to build or produce anything and no way to increae the Grid (unless Japan builds it for you, but that can only happen in Multiplayer).

### Steps to reproduce / Cause of the issue

1. Play China
2. Try to change the production units --> The Produced Grid Power will change from almost 100 to 38

### Expected behaviour

China should have atleast some Lecricity or a way to get more through Foci

**Comment by Tilli1** [comment]
I just realized you can delete Buildings but this is still a bug. Maybe add the option to prioritize Production Units for Electricity or just update the Electricity. This Whole Issue is also a Problem for other Countries.

**Comment by runelead00** [comment]
Fixed in Current Release
