### ISSUE TITLE
Philippines spirit uses outdated lore

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1282]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

National Spirit for the American-affiliated Philippines refers to Truman, who was never president.

### Steps to reproduce / Cause of the issue

![Screenshot (1462)](https://user-images.githubusercontent.com/33550299/197402368-f480f6b2-c5c3-4c9c-9ac3-aeb12ed2599e.png)

### Expected behaviour

Not mention Truman

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
