### ISSUE TITLE
Ostafrika loc issues

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1283]
### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. Schenck is misspelled twice as Schenk. Also "South-Western RK" should simply be Südwestafrika
2. Otto Förschner minister description is weirdly formatted
3. Ostafrikanischflotte/Ostafrikanischgruppe aren't proper German. Ostafrikaflotte or Ostafrikanische Flotte (+Ostafrikagruppe/Ostafrikanische Gruppe) would be better.

![Screenshot (1431)](https://user-images.githubusercontent.com/33550299/197403368-65016c85-1593-439f-aa87-f4c982494553.png)
![Screenshot (1434)](https://user-images.githubusercontent.com/33550299/197403382-c06c8111-0544-400c-a78e-45e50361e17b.png)
![Screenshot (1436)](https://user-images.githubusercontent.com/33550299/197403429-f7db5b48-a525-44cf-9219-92f3a38d3ecf.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
