### ISSUE TITLE
OFN Mandates - Setting mandates to stable in country paths doesn’t actually make them stable 

### ISSUE THREAD

**Issue by TheWolfyXZ** [TNODevs/TNO-Bug-Tracker#1284]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Setting the mandates in the country paths to be stable doesn’t make them stable, multiple times all 3 mandates went severely unstable despite being set to stable and required intensive investment from me as the U.S to keep them from remaining permanently under the halfway point.

### Steps to reproduce / Cause of the issue

Set all 3 OFN mandates to stable in country paths, release mandates after Total OFN Victory.

### Expected behaviour

The mandates remaining stable throughout their entire lifespan

**Comment by runelead00** [comment]
"These gamerules are programmed to clamp at the very edge of preventing the collapse of each mandate, so there is no problem if the stability is low, as long as it is a value that does not lead to collapse." - CCP Lead 

CCP keeps them above the collapse threshold, it's not meant to be an easy cheat to avoid dealing with the mandate mechanic for the player
