### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Lipad45** [TNODevs/TNO-Bug-Tracker#1285]
### HOI4 version

Avalanche 1.12.4

### TNO version

v1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The West Russian revolutionary front changed Vyatka to Rykov and moved their capital to Rykov and the name of the capital broke and now displays this
![image](https://user-images.githubusercontent.com/88467629/197415502-66487248-0bb8-4a69-b8d8-a9b860f5f5b9.png)

**Comment by runelead00** [comment]
Fixed in dev build
