### ISSUE TITLE
West Russian Revolutionary front- Finland joined the Einheitspakt and Germany annexed WRRF

### ISSUE THREAD

**Issue by Lipad45** [TNODevs/TNO-Bug-Tracker#1286]
### Operating System

Windows 10

### HOI4 version

Avalanche 1.12.4

### TNO version

v1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I can't upload the save file directly. Let me know if you want me to link a Google drive file for it.

### Describe the bug

The Karelian war and Finnish Civil war lasted for a long period of time and in that Finland had an election that put Lauri Torni. Finland then preceded to join the Einheitspakt and called Germany into the fight with WRRF. The Germans defeated the WRRF and then annexed them

### Steps to reproduce / Cause of the issue

1. Have the Karelian War happen
2. Have the Finnish President resign and have the interim government put in place
3. have the Finnish Elections occur and let Lauri Torni win
4. Let Finland join the Einheitspakt
5. Have Germany annex WRRF

### Expected behaviour

Germany annexes WRRF and breaks the Russian Warlord unification

### Screenshots

![image](https://user-images.githubusercontent.com/88467629/197416457-9a93f684-c827-4575-ba73-07572c9af1dd.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
