### ISSUE TITLE
USA-RFK Can't Pass Social Security

### ISSUE THREAD

**Issue by mill3104** [TNODevs/TNO-Bug-Tracker#1287]
### Operating System

Mac OS Monterey

### HOI4 version

1.12.4.aefa

### TNO version

1.3.0c

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Even though I have over 50 votes as Bobby Kennedy to pass Social Security, the act fails to pass. I get the event that the act fails to pass after choosing The World Beings with You focus.

### Steps to reproduce / Cause of the issue

1. Choose The Social Security Act focus as Bobby Kennedy
2. Obtain 50 votes for the act, if necessary
3. Choose The World Begins with You focus
4. Choose Everyone deserves a fair chance

### Expected behaviour

I should get the event that the act passed, not that it failed.

**Comment by runelead00** [comment]
Fixed in Dev Build
