### ISSUE TITLE
Magadan - Wrong Effect For 'Reform the Blackshirts' Focus

### ISSUE THREAD

**Issue by SapphireStorm32** [TNODevs/TNO-Bug-Tracker#1288]
### Operating System

Windows 10

### HOI4 version

1.12.4.aefa

### TNO version

1.3.0c

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The focus 'Reform the Blackshirts,' which is intended to reform the police, increases the harshness of security laws by one, to 'Oppressive Police.' I am reasonably sure this is not intended and the focus is supposed to decrease the harshness of Magadan's security laws as the opposite focus has the same effect and is described as increasing the harshness of the police force.

### Steps to reproduce / Cause of the issue

1. Start a Magadan game
2. Progress to regional stage or load the regional tree through debug
3. Complete the 'Reform the Blackshirts' focus or preview its effects

### Expected behaviour

The security law status should either decrease or remain the same

### Screenshots

![Screenshot (33)](https://user-images.githubusercontent.com/116526539/197424021-79993344-82a5-45a9-9414-e96bb7f6830b.png)
![Screenshot (34)](https://user-images.githubusercontent.com/116526539/197424024-8c259d7b-f574-4272-8bed-e0f2b701a8ca.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
