### ISSUE TITLE
 Loading Tips - Barry Goldwater Quotes

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#129]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
In the Loading Tips part it should include at least one of these three quotes spoken from Barry Goldwater.

“A government big enough to give you everything you want is a government big enough to take from you everything you have.”

“The Conservative approach is nothing more or less than an attempt to apply the wisdom and experience and the revealed truths of the past to the problems of today. The challenge is not to find new or different truths, but to learn how to apply established truths to the problems of the contemporary world.”

“But the framers were not visionaries. They knew that rules of government, however brilliantly calculated to cope with the imperfect nature of man, however carefully designed to avoid the pitfalls of power, would be no match for men who were determined to disregard them.”

**Reasoning Behind Suggestion:**

I think these quotes would be interesting to have in the  Loading Tips screen as they have relevance both domestically and international in terms of politics and government.

**Comment by Scarsoftime** [comment]
The first quote that you suggested has been accepted. The second and third suggestions are not accepted due to concerns about its length. Thank you for your contribution to TNO.
