### ISSUE TITLE
Soviet Komi - War with Germany don't stop

### ISSUE THREAD

**Issue by Morjavick** [TNODevs/TNO-Bug-Tracker#1290]
### Operating System

Windows 11

### HOI4 version

Last

### TNO version

Last

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When at war with Finland as Bukharina, Fascist Finland calls Germany as ally in the war.
After the time event end, a ceasfire automaticly appens with Finland and an event about the result pop.
But I am still at war with Germany and I get crushed.

### Steps to reproduce / Cause of the issue

Go at war with facist Finland who call Germany as ally.
Wait for the time event to come to an end.

### Expected behaviour

After the Ceasfire, the war with Germany stops

**Comment by runelead00** [comment]
Fixed in Dev Build
