### ISSUE TITLE
Komi - Stalina Smuta tree

### ISSUE THREAD

**Issue by AlexKoval21** [TNODevs/TNO-Bug-Tracker#1291]
### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### List the loc issues below

1. 1st focus (The Republic Militant) from Stalina Smuta tree has a code instead of a description.
![image](https://user-images.githubusercontent.com/59415315/197600285-51bce795-de0b-4ae5-af4f-de062da551a6.png)

2. Focus "Suspend Legal Protections" also has a code instead of a description.
![image](https://user-images.githubusercontent.com/59415315/197600493-b2ac932c-8d66-4125-8447-ab8f3ad93b4f.png)

3. Not so important, but in the DEBUG, dem Stalina also has a code instead of localization.
![image](https://user-images.githubusercontent.com/59415315/197601805-22d813f3-eaad-441b-95a0-1b7acdd8f6fd.png)

### Additional information

Just change the localisation code to the correct one.
![image](https://user-images.githubusercontent.com/59415315/197601229-6d42d28d-d182-4b6e-94d1-3c0a72fe69e3.png)

(already done in Russian translation)

**Comment by runelead00** [comment]
Fixed in Dev Build, restoring order desc was moved to the republic militant, devolve judicial power desc was given to restoring order, and arrest sources of information desc was given to suspend legal protections
