### ISSUE TITLE
Shafarevich - effects of focuses of RNP elections

### ISSUE THREAD

**Issue by AlexKoval21** [TNODevs/TNO-Bug-Tracker#1292]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0с

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

I'm not 100% sure, but shouldn't industrialization centralize the economy? And the development of agriculture should be decentralized economy?

### Steps to reproduce / Cause of the issue

1. Click on Komi
2. Print DEBUG in console
3. Click on the RNP election tree
4. Click on the focuses, see the problem

### Expected behaviour

Just swap the effects

### Screenshots

![image](https://user-images.githubusercontent.com/59415315/197606587-605568e9-dcbb-47cf-a3f6-e31441093e2e.png)

![image](https://user-images.githubusercontent.com/59415315/197606727-f402391d-9c20-4ec5-9b1b-cacff2a5c0f6.png)

### Additional information

It seems like an insignificant thing, but still it's still good if you fix it

**Comment by runelead00** [comment]
centralization is not a measure of industrialization, it's a measure of how much control the government has over the economy, so giving the industrial magnates grant power decentralizes the economy while the government stepping in to prioritize agrarian development would centralize the economy
