### ISSUE TITLE
Mossiland Doesn't Surrender

### ISSUE THREAD

**Issue by Kadubrp** [TNODevs/TNO-Bug-Tracker#1293]
### Operating System

Windows 10

### HOI4 version

v1.12.4

### TNO version

v1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I can't send any save files since i'm playing on geforcenow

### Describe the bug

Mossiland for some reason can't don't surrender to france, making it impossible for the west african war to finish

### Steps to reproduce / Cause of the issue

none

### Expected behaviour

Mossiland to surrender

### Screenshots

![Uploading Screenshot (24).png…]()

### Additional information

It's just that, mossiland dosent surrender

**Comment by runelead00** [comment]
Fixed in Dev Build
