### ISSUE TITLE
Vyatka - Leftover references to Brittany

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1294]
### HOI4 version

1.12.4.aefa

### TNO version

1.3.0.c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### List the loc issues below

1. 
![Screenshot (123)](https://user-images.githubusercontent.com/98137316/197894838-8e1c3207-778a-441a-87fd-292af2cde2de.png)
Reference to Brittany should be reference to Niederland.
2.
![Screenshot (124)](https://user-images.githubusercontent.com/98137316/197894906-d85316a4-fc1b-4d8e-bc5a-e5e573a0105d.png)
Since Brittany no longer existed, the reference should be altered or removed.
3. 
![Screenshot (127)](https://user-images.githubusercontent.com/98137316/197895105-93a8a8f3-28b1-42e1-8542-b8aad63063f8.png)
Same as 2.

**Comment by runelead00** [comment]
1 and 3 edited
2 unchanged
