### ISSUE TITLE
Vyatka - Typos and grammatical issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1295]
### HOI4 version

1.12.4.aefa

### TNO version

1.3.0.c

### Do you have other mods in use?

no

### Were you using Steam?

No

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### List the loc issues below

1. 
![Screenshot (129)](https://user-images.githubusercontent.com/98137316/197895349-7a6dca0b-cb8d-4697-b413-6bec8c96ec46.png)
"opposed" should be "opposing"
2. 
![Screenshot (125)](https://user-images.githubusercontent.com/98137316/197895407-0532ab64-27e8-41bf-b06a-f448fa85f6f0.png)
"The Tsar" should be "the Tsar"

**Comment by runelead00** [comment]
Fixed in Dev Build
