### ISSUE TITLE
ctd on startup lol

### ISSUE THREAD

**Issue by PhantomBread225** [TNODevs/TNO-Bug-Tracker#1299]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0c

### Do you have other mods in use?

"Ultimate Soundtrack" music mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9873626/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9873627/error.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9873628/system.log)
[exception.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/9873632/exception.txt)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9873635/game.log)

### Describe the crash

Immediately after starting the game, the game closes without even giving the 'Paradox Crash Reporter' window.

### Steps to reproduce / Cause of the crash

1. Open the HOI4 launcher.
2. Enable TNO.
3. Start the game and wait.

**Comment by runelead00** [comment]
Merged into #961
