### ISSUE TITLE
Reich and West Russia - Reich can join Finland in Karelian war and occupy West Russian warlord

### ISSUE THREAD

**Issue by Afanas42** [TNODevs/TNO-Bug-Tracker#1300]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0C

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9880371/logs.zip)
Can't upload save - too heavy file.

### Describe the bug

If Finland defeats Socialist uprising and joins the Reich, it can call Reich for help, in turn, Reich can simply occupy warlord. This works for Bormann/Speer. 

### Steps to reproduce / Cause of the issue

Add some kind of Finland victory breakpoint. 

### Expected behaviour

Finland victory, demilitarised Onega as usual

### Screenshots

![image](https://user-images.githubusercontent.com/107316734/198316012-679eef5e-a373-4643-a76a-e8db029ed348.png)

### Additional information

Maybe it's "Goring shenaningans" sneaking into another fuhrer path? Eh?

**Comment by runelead00** [comment]
Fixed in Dev Build
