### ISSUE TITLE
Heydrich Germany

### ISSUE THREAD

**Issue by HogansHeroes120** [TNODevs/TNO-Bug-Tracker#1301]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.12.4

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Decision Categorys not showing up after completing focuses in SS Civil War part of the tree,categories

### Steps to reproduce / Cause of the issue

Complete focuses such as "All Eyes on Heydrich".

### Expected behaviour

Decisions would appear after focus is completed.

**Comment by runelead00** [comment]
Fixed in Dev Build
