### ISSUE TITLE
Italy Atlantropa references

### ISSUE THREAD

**Issue by negyit** [TNODevs/TNO-Bug-Tracker#1305]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

.

### Steps to reproduce / Cause of the issue

1. Italy joining the OFN and US got a national spirit
2. Opening the Cold War GUI tab

### Expected behaviour

New borders of italy should be visible

### Screenshots

![Screenshot (26)](https://user-images.githubusercontent.com/116903491/198690192-db5de92d-dc1c-4624-a516-801a668cd6f3.png)
After Italy joins OFN the nat spirit uses the old Italian lore

![Screenshot (27)](https://user-images.githubusercontent.com/116903491/198690405-cae2d843-27c3-4b4e-a8c7-205142be6eda.png)
In the Cold War GUI Italy still have the "Atlantropian lands"

**Comment by runelead00** [comment]
Fixed in Dev Build
