### ISSUE TITLE
US president Bennett event "A Whiff of Popery"

### ISSUE THREAD

**Issue by negyit** [TNODevs/TNO-Bug-Tracker#1308]
### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. None of the two has any effects
![Screenshot (6)](https://user-images.githubusercontent.com/116903491/198698837-07721175-4c10-4abe-b74a-fca7499f8257.png)

**Comment by runelead00** [comment]
I do not know what you are talking about here, both options have effects in the current release build

**Comment by negyit** [comment]
Why I got the event like in the screenshot, strange
