### ISSUE TITLE
US wrong Secretary of Treasury in MCS's cabinet

### ISSUE THREAD

**Issue by negyit** [TNODevs/TNO-Bug-Tracker#1310]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Cabinet of Maragaret Chase Smith having an another character than the planned one

### Steps to reproduce / Cause of the issue

1. Elect MCS

### Expected behaviour

Secretary of Tresaury should be Russell Long stated by an event called "Deliberations"

**Comment by runelead00** [comment]
Fixed in Dev Build
