### ISSUE TITLE
"Crank Up the Draft" focus in MCS's tree uses old lore

### ISSUE THREAD

**Issue by negyit** [TNODevs/TNO-Bug-Tracker#1311]
### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. Focus uses old Joseph Kennedy's lore
![Screenshot (22)](https://user-images.githubusercontent.com/116903491/198703125-8f006986-2410-4d49-bff9-d239d4dd8c16.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
