### ISSUE TITLE
MCS focus flavor events won't fire

### ISSUE THREAD

**Issue by negyit** [TNODevs/TNO-Bug-Tracker#1312]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Focus called "Commission The Carriers" flavour events won't appear

### Steps to reproduce / Cause of the issue

1. Elect MCS, having her tree

### Expected behaviour

The flavor events could fire properly

### Screenshots

![Screenshot (24)](https://user-images.githubusercontent.com/116903491/198704332-344cbdd6-996b-4bf1-b068-c38e1ae4a33c.png)

**Comment by runelead00** [comment]
Working as Designed, just a long wait after focus is done before event occurs, added tooltip to clarify this
