### ISSUE TITLE
Japan - Kaya has been purged

### ISSUE THREAD

**Issue by Laporte12974** [TNODevs/TNO-Bug-Tracker#1313]
### Operating System

Debian 11

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

The Moe Order, radio_tno, TCE: The Community Music, TNO: Last Waltz of Europe, TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9893702/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9893703/game.log)
[Last 3 savefiles.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9893710/Last.3.savefiles.zip)
The last save on January 01 1971 is empty for some reason.
The autosave sets me as the Dai-Nippon Rakuen Teikoku, a focus-less, spirit-less estoeric nazi country that I can't say I remember existing.
The only valid save here is the August 1970 one.

### Describe the bug

A few days ago, I was playing as Japan, led by Kaya, on the technocratic path. Nothing special, nothing major. Today, I open up the game again, and it seems Kaya has been purged. There are still references to Kaya ingame, as in foci, events, and whatnot, but Kaya as a leader is gone and purged.
I am now playing under an Interim government led by Higashikuni Naruhiko.
I have tried through `event jap_interregnum.88` to set Kaya back in position, however, it set another person in his place, one that didn't even have a portrait.
Line 1431 of error.log is as follow.
``[14:44:45][effectimplementation.cpp:667]: events/TNO_Japan_Interregnum.txt:2028: promote_character: Character JAP_kaya_okinori has been retired from country JAP. Can't Update.``
All saves I have that had Kaya as a leader have the same issue.

### Steps to reproduce / Cause of the issue

I wish I knew. I'm sorry I cannot be of help.

### Expected behaviour

I expected to continue my game as Kaya.

**Comment by runelead00** [comment]
It appears was a hotfix between when you started the run and this time or your game didn't updated properly prior to starting the run, which corrupted your save. Can't fix
