### ISSUE TITLE
Liberal Socialism Icon Broke

### ISSUE THREAD

**Issue by leninsinrussia** [TNODevs/TNO-Bug-Tracker#1314]
### Operating System

windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Describe the bug

somebody fucked up naming progressivism_liberal_socialism.dds by forgetting to add _subtype after socialism, which means that when the TNO_ideologies.gfx file tries to find a sprite named "progressivism_liberal_socialism_subtype.dds", it finds nothing, and the icon doesn't show up

### Steps to reproduce / Cause of the issue

just fucking change the name of progressivism_liberal_socialism.dds

### Expected behaviour

the icon should show up in game

**Comment by runelead00** [comment]
Fixed in Dev Build
