### ISSUE TITLE
Vyatka typos

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1315]
### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. when he hid --> when he did
2. Though the efforts --> Through the efforts

![Screenshot (1476)](https://user-images.githubusercontent.com/33550299/198890034-d5be7369-e3dd-4a42-b646-d7471b11489d.png)
![Screenshot (1477)](https://user-images.githubusercontent.com/33550299/198890056-b6dc4313-b7f1-48a2-a222-dfb61cea84a4.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
