### ISSUE TITLE
Yunnan typos

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1316]
### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. Long Yun's knew --> Long Yun knew
2. has shaken him --> have shaken him
3. in throughout Yunnan And beyond -->throughout Yunnan and beyond
4. has seen been times --> has seen better times
5. CCP or CPC?
6. their backs --> their back / their undisputed --> the undisputed
7. a statesmen --> a statesman
8. sanctity of Justice --> sanctity of justice

![Screenshot (1468)](https://user-images.githubusercontent.com/33550299/198890471-94af6fa4-0b87-4070-ac7f-ec643c46ccdd.png)
![Screenshot (1469)](https://user-images.githubusercontent.com/33550299/198890484-12f937bd-7cab-4d6f-82d8-c5c85f09dd92.png)
![Screenshot (1470)](https://user-images.githubusercontent.com/33550299/198890537-03a10b45-fd6a-453f-8a45-c18bd8f4bc55.png)
![Screenshot (1471)](https://user-images.githubusercontent.com/33550299/198890558-0725d3c2-a156-4f21-8f32-e69949393588.png)
![Screenshot (1472)](https://user-images.githubusercontent.com/33550299/198890589-a2367363-15de-4048-bbfc-72dc3c40cdda.png)
![Screenshot (1473)](https://user-images.githubusercontent.com/33550299/198890611-88186e69-ff80-4691-b4e6-40c0a4b91ea1.png)
![Screenshot (1474)](https://user-images.githubusercontent.com/33550299/198890788-c78b960d-e59a-476f-b17c-592469377b1a.png)
![Screenshot (1475)](https://user-images.githubusercontent.com/33550299/198890824-ace48ab2-4142-43c0-94c2-4f69f74692d8.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
