### ISSUE TITLE
Tech tree typos

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1319]
### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. Text is missing . at the end
2. equipmnent --> equipment
3. fill handle all roles --> fill all roles
4. aquiring --> acquiring

![Screenshot (1483)](https://user-images.githubusercontent.com/33550299/198899885-0064089e-d63d-41e8-8370-678aa4da6493.png)
![Screenshot (1486)](https://user-images.githubusercontent.com/33550299/198899905-cb1b56df-302c-4379-9dd1-3d5676cfda37.png)
![Screenshot (1487)](https://user-images.githubusercontent.com/33550299/198899944-197233c1-840c-4f06-94c8-ceed09097d7d.png)
![Screenshot (1488)](https://user-images.githubusercontent.com/33550299/198899971-70da7e26-59f1-48e0-8f01-75d3b1db2faf.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
