### ISSUE TITLE
USA - no debate events for 1968 and 1972 fire

### ISSUE THREAD

**Issue by Malojstoy** [TNODevs/TNO-Bug-Tracker#132]
**Questions**

- Operating System: windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: TNO Reskins, Last Waltz of Europe
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all of them

**Longer Description of Issue:**
No presidential debate events fire for the 1968 and 1972 elections, this happens for all candidates, it wasn't always like this but it's been like that for some time
**Steps to Reproduce/Cause Issue:**

1. Play as the US until the 1968 election

**Screenshots:**
There is nothing to screenshot, the issue is about what isn't there

**Comment by ModdingAccount** [comment]
Fixed in dev build.
