### ISSUE TITLE
USA - Minor spelling mistake in ALP event chain

### ISSUE THREAD

**Issue by C-Kingfish** [TNODevs/TNO-Bug-Tracker#1320]
### HOI4 version

1.12.3

### TNO version

1.3.0c

### Do you have other mods in use?

None relevant

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

During the allen lawrence pope event chain, the event where an SOG team rescues pope, prostrate is misspelled as prostate. I highlighted it because I figured you didn't want to read the whole event to find it.
![nope it's prostrate](https://user-images.githubusercontent.com/117119871/199101487-526414a2-2870-444c-af9e-d8df77571125.png)

### Additional information

I don't actually know what version I'm on. The latest steam build. I don't know fuck about computers. I can barely manage this website.

**Comment by runelead00** [comment]
Fixed in Dev Build
