### ISSUE TITLE
BRG - Somme missing from Domestic Situation Mechanic

### ISSUE THREAD

**Issue by Pixelated1272** [TNODevs/TNO-Bug-Tracker#1321]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

While playing Burgundy Somme is missing from the Domestic Situation Mechanic

### Steps to reproduce / Cause of the issue

1. Play as Burgundy.
2. Play a while
3. Keep getting alerts from the Domestic Situation panel that cant be fixed.
4. Play until you reach the focus: 'Der Industriebezirk Rodomo'
5. Go to decisions and try to build all of the dockyards
6. Somme is grayed out because not enough workers?
7. Realize Somme is missing from the panel.

### Expected behaviour

Add Somme to the Domestic Situation gui

**Comment by runelead00** [comment]
Dockyards mission not longer will appear in Somme
