### ISSUE TITLE
Chita - Typoes

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1322]
### HOI4 version

1.12.4

### TNO version

1.3.0.c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### List the loc issues below

1. 
![Screenshot (136)](https://user-images.githubusercontent.com/98137316/199289788-1b034377-7d69-4e3a-ab81-1621728ed1a6.png)
"not an empty place" makes no sense, and "Possibility of doing so" should be "The possibility of doing so."
2.
![Screenshot (137)](https://user-images.githubusercontent.com/98137316/199289868-a3dde6c9-fe2c-4fd1-89e4-cbeb978756e4.png)
"only a reach away" is grammatically incorrect and should be something like "just within our reach"
3. 
![Screenshot (139)](https://user-images.githubusercontent.com/98137316/199289966-69e28c4e-1b97-4745-8eae-fd557d564d90.png)
"within Loyalists" should be "within the Loyalists"
4. 
![Screenshot (153)](https://user-images.githubusercontent.com/98137316/199290096-32f7eccd-81a9-41ea-940a-a1503760d6a2.png)
"and, yet, I don't" should be "and yet I'm not."

**Comment by Stormeagle449** [comment]
Fixed for the next hotfix.
