### ISSUE TITLE
Romania and Hungary - Identical pie chart bug

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1324]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0.c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, NSB, BBA

### Describe the bug

Both countries had their pie charts glitch to what appears to be the default model for liberalism.

### Steps to reproduce / Cause of the issue

Unknown

### Expected behaviour

That the pie charts would be normal

### Screenshots

1. ![Screenshot (143)](https://user-images.githubusercontent.com/98137316/199291138-34ebeb4a-c1a7-41e0-ab55-e6d5602619f2.png)
2. 
![Screenshot (144)](https://user-images.githubusercontent.com/98137316/199291201-074eb1e3-874e-4034-818d-db7ae6acf086.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
