### ISSUE TITLE
Free Nigerian Republic - Missing capitulation text

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1325]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0.c

### Do you have other mods in use?

no

### Were you using Steam?

No

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the bug

The Free Nigerian Republic has no text where its capitulation message should be.

### Steps to reproduce / Cause of the issue

unknown/none

### Expected behaviour

that "war is hell" would appear

### Screenshots

![Screenshot (148)](https://user-images.githubusercontent.com/98137316/199291621-20cd2cac-d637-43ce-b4c5-15ea5943a3d9.png)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
