### ISSUE TITLE
Imperial State of Iran shouldn't have National Socialist Corporatism 

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1326]
### HOI4 version

1.12.4

### TNO version

1.3.0.c

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe your suggestion

The Imperial State of Iran would have some other form of economy other than National Socialist Corporatism, likely Planned Economy or standard Corporatism.

### Justifications

As a Semi-Constitutional Monarchy(a Paternalism sub-ideology), it makes no sense for Iran's economy to be stated to be organized by National Socialist guidelines.

### Screenshots

![Screenshot (154)](https://user-images.githubusercontent.com/98137316/199292131-de0a0ebc-b7e2-4996-86de-b3f14c91df81.png)

**Comment by Stormeagle449** [comment]
More recent versions of TNO have imperial Iran with dirigisme.
