### ISSUE TITLE
Indonesia - Stagnated civil war

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1327]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0.c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the bug

Indonesia's civil war stagnated for at least three years, with no change in territory.

### Steps to reproduce / Cause of the issue

unknown/none

### Expected behaviour

that the war would end within two years at most

### Screenshots

![Screenshot (156)](https://user-images.githubusercontent.com/98137316/199307439-a38feaae-a9d1-4941-9e7c-ef4453a7d295.png)

**Comment by runelead00** [comment]
War stagnates far less in SD and onwards
