### ISSUE TITLE
Every Country - CTD after 4 seconds

### ISSUE THREAD

**Issue by Vanya-2007** [TNODevs/TNO-Bug-Tracker#1328]
### Operating System

11

### HOI4 version

Avalanche v1.12.4.aefa (a85e) (S)

### TNO version

TT4 v1.3.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9923236/error.log)

### Describe the crash

After about 3 hrs of ingame time, the game crashes.

### Steps to reproduce / Cause of the crash

1. Download the newest patch xd
2. Open game
3. admire megacities
4. play the game for ~4 seconds
5. lol

### Screenshots

N/A

### Additional information

N/A

**Comment by runelead00** [comment]
Already fixed on steam release. Just got to wait for it to update to the hotfixxed hotfix
