### ISSUE TITLE
All - Still CTDing after hotfix for the hotfix

### ISSUE THREAD

**Issue by Vanya-2007** [TNODevs/TNO-Bug-Tracker#1329]
### Operating System

11

### HOI4 version

Avalanche v1.12.4.aefa (a85e) (S)

### TNO version

TT4 v1.3.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9923321/error.log)

### Describe the crash

https://github.com/TNODevs/TNO-Bug-Tracker/issues/1328
still happening even though it says its resolved 
yes I unsubscribed and resubscribed

### Steps to reproduce / Cause of the crash

1. Download the patch for the patch
2. Open game
3. play the game for ~4 seconds
4. lol

### Screenshots

N/A

### Additional information

N/A

**Comment by runelead00** [comment]
Fixed in Dev Build
