### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by PresumedEagle10** [TNODevs/TNO-Bug-Tracker#133]
**Questions**

- Operating System: windows 10
- HOI4 Version: latest 
- TNO Version: latest 
- Any other mods in use: just music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them 

**Longer Description of Issue:**

As the usa you can softlock the cia Becuase your agents will just set to 0 and if your expirence is low enough you can never recruit a new one essentially softlocking the mechanic for the rest of the game

**Steps to Reproduce/Cause Issue:**

1.play as usa and use the cia mechanic, this happend for me around the saw

2.

etc...

**Screenshots:**
I don’t have any but imagine the cia screen but imagine no missions running and the agents are zero aswel as the xp

**Comment by Scarsoftime** [comment]
"Intelligence Analysis" decision gives you free expertise. Please look into it more before reporting an issue, even more so if it is an "imagine" scenario like this one.
