### ISSUE TITLE
Cuba- Wrong government type

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1330]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0.d

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the bug

In the latest patch notes, Cuba is stated to have gone from Social Nationalism to Interim Government, but this was not the case for me.

### Steps to reproduce / Cause of the issue

unknown

### Expected behaviour

That Cuba would have the government stated in the patch notes

### Screenshots

![Screenshot (165)](https://user-images.githubusercontent.com/98137316/199600016-28da4042-79a0-4b51-9674-9cb355701e0d.png)

**Comment by runelead00** [comment]
Hotfix was reverted due to CTD, wait until it is reuploaded
