### ISSUE TITLE
Magadan - 5 out of 4 production units

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1331]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.3.0.d

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the bug

Magadan's power restrictions mean I should only have four production units, but I have five at game start. Subtracting one from either civilian or military will correct this.

### Steps to reproduce / Cause of the issue

1. Start game as Magadan

### Expected behaviour

That I'd only get four production units, as I start with four power.

### Screenshots

![Screenshot (161)](https://user-images.githubusercontent.com/98137316/199600382-a82fc3a5-dba2-45bf-9356-baafb4bd5d7d.png)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
