### ISSUE TITLE
Switzerland - Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1332]
### HOI4 version

1.12.4

### TNO version

1.3.0.d

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### List the loc issues below

1. 
![Screenshot (162)](https://user-images.githubusercontent.com/98137316/199600655-fa8b1cf6-bdc9-4351-adc5-4055ba5d2135.png)
"at ends" should be "at odds"

**Comment by runelead00** [comment]
Fixed in Dev Build
