### ISSUE TITLE
Serbia - Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1333]
### HOI4 version

1.12.4

### TNO version

1.3.0.d

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### List the loc issues below

![Screenshot (163)](https://user-images.githubusercontent.com/98137316/199600802-6f8bb8d4-2460-417c-a32d-fdc5f62c7dbc.png)
"lap dogs" should be "lapdogs"

**Comment by runelead00** [comment]
Fixed in Dev Build
