### ISSUE TITLE
Slovak State - Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1334]
### HOI4 version

1.12.4

### TNO version

1.3.0.d

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### List the loc issues below

![Screenshot (164)](https://user-images.githubusercontent.com/98137316/199601119-cc85d05f-64d1-43a6-90a8-e18d8de018bf.png)
"it's" should be "its"

**Comment by runelead00** [comment]
Fixed in Dev Build
