### ISSUE TITLE
Tooltip typos

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1336]
### HOI4 version

1.12.4

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. to deals --> to deal / Young Republic --> young republic 
2. have not seem --> have not seen
3. decommisioning --> decommissioning

![Screenshot (1526)](https://user-images.githubusercontent.com/33550299/199616434-25399ad2-3b42-4597-8e2d-f6527a1ac4fa.png)
![Screenshot (1525)](https://user-images.githubusercontent.com/33550299/199616585-5294a226-e2f3-4a6e-b3d2-3f56bcdc3135.png)
![Screenshot (1524)](https://user-images.githubusercontent.com/33550299/199618357-d9c9554a-01aa-4424-944c-563b447a1ed6.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
