### ISSUE TITLE
Rykov - No localization

### ISSUE THREAD

**Issue by SirMichaelBlackrose** [TNODevs/TNO-Bug-Tracker#1337]
### HOI4 version

1.12.4

### TNO version

1.3.0d

### Do you have other mods in use?

Last Waltz

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

VICTORY_POINTS_6124_com

VICTORY_POINTS_272_com

**Comment by runelead00** [comment]
Fixed in dev build, coming when hotfix 1.3.0d gets properly released
