### ISSUE TITLE
Medium Flags Broken

### ISSUE THREAD

**Issue by Suetabobra** [TNODevs/TNO-Bug-Tracker#1339]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

TT3 

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9930614/error.log)

### Describe the GFX issue

There`s no small size flags

### Steps to reproduce / Cause of the issue

You can just reload small size flags

### Expected behaviour

i expected to see small size flags((999(((

### Screenshots

![hoi4_awiAM0Do5D](https://user-images.githubusercontent.com/115463789/199765019-96d80368-b4a6-4900-b470-83eb6f33329c.jpg)
![hoi4_LbOaLnjker](https://user-images.githubusercontent.com/115463789/199765030-3a309272-2a4b-4820-b889-da5091a60c40.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
