### ISSUE TITLE
England- Picture for newspaper event of Chesterton being PM

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#134]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**

In case the Devs are still considering what picture to use, for Fascist Britain they should use this picture for the newspaper event that describes A. K Chesterton being elected as Prime Minister.

![image](https://user-images.githubusercontent.com/84231463/141010957-ab3ea145-9e08-4372-802f-af53ae581578.png)

**Reasoning Behind Suggestion:**

This image looks like it would fit well with Chesterton becoming the Prime Minister of England, with Chesterton being de facto leader of the British Union of Fascists in this timeline

**Comment by Scarsoftime** [comment]
BUF symbolism is not used.
