### ISSUE TITLE
Unit icons not appearing when zoomed out slightly

### ISSUE THREAD

**Issue by TheSudoer** [TNODevs/TNO-Bug-Tracker#1340]
### Operating System

Ubuntu Linux 22.10, Unity DE, Xorg, NVIDIA propritary driver

### HOI4 version

1.12.5.b273

### TNO version

1.3.0c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the GFX issue

Unit icons don't show if zoomed out too far with only the division counter still visible.

### Steps to reproduce / Cause of the issue

1. Load game
2. Zoom in till divisions are just visible

### Expected behaviour

Unit icons should remain visible as long as the division is

### Screenshots

![Screenshot from 2022-11-03 12-28-26](https://user-images.githubusercontent.com/29937906/199793726-9bbc5c17-ca58-4658-8686-c0caf456326d.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
