### ISSUE TITLE
All countries - Unit flags don't appear

### ISSUE THREAD

**Issue by 22oroda** [TNODevs/TNO-Bug-Tracker#1341]
### Operating System

Windows 11 Home

### HOI4 version

1.12.5

### TNO version

1.3.0C

### Do you have other mods in use?

TNO Radio

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

When zoomed out flags of units aren't showing up, zoom in and they reappear.

### Steps to reproduce / Cause of the issue

1. Just started the game let time run to see if it would fix and nothing

### Expected behaviour

Flags to show up

### Screenshots

![Screenshot_20221103_030531](https://user-images.githubusercontent.com/110065469/199812222-49be7d12-d9c0-42f6-8145-019abeaf15be.png)
![Screenshot_20221103_030741](https://user-images.githubusercontent.com/110065469/199812272-1e6fc4cc-6dc6-469d-8491-acf7f6505698.png)

**Comment by kaiser3613** [comment]
this is also happening to me

**Comment by runelead00** [comment]
Fixed in upcoming hotfix
