### ISSUE TITLE
Brazil- No 100 days crisis

### ISSUE THREAD

**Issue by DoomedDM** [TNODevs/TNO-Bug-Tracker#1342]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0C

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

I was doing a Brazil run and trying to get the 100 days crisis. After some advice on the TNO discord I kept Quadros and Lott Influence even (contested) and reduced their relationship.

After a time Quadros resigned and things went as expected. Then an event happened where Quadros was allowed back in office and nothing else happened, despite the fact that the relationship between Lott and Quadros remained contested.

Does the 100 days crisis still correctly trigger ?

### Steps to reproduce / Cause of the issue

1. Select brazil
2. Make sure Lott-Quadros influence is contested.
3. Lower Lott-Quadros relationship to non-existent and wait for Quadros resignation

### Expected behaviour

Quadros resigns, only to be accepted back again and for the Lott presidency to continue.

**Comment by runelead00** [comment]
I believe you may have the start of 100 Days confused with a different event. Quadros can resign prior to 100 Days if the relationship gets bad enough after which he will be reinstated. This how ever guarantees he will betray Lott when Lacerda and Adhemar make their play which starts the 100 Days around the start of 1964
