### ISSUE TITLE
USA typos

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1343]
### HOI4 version

1.12.4

### TNO version

1.3.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. with the banking industry retreats --> with the banking industry retreating
2. solution this dilemma --> solution to this dilemma
3. odd couple Coalition --> odd couple coalition / have rapidly become --> has rapidly become / in the smoke filled ? (sth. is missing, offices?)

![Screenshot (1520)](https://user-images.githubusercontent.com/33550299/199928806-dc80a734-4bc8-416e-97d3-ba5a415349fa.png)
![Screenshot (1522)](https://user-images.githubusercontent.com/33550299/199929056-cb3dfcf0-aeea-4577-b904-4502cc122e77.png)
![Screenshot (1521)](https://user-images.githubusercontent.com/33550299/199929152-788560d0-2ec9-46d5-938a-6d52620bb3f0.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
