### ISSUE TITLE
AST&NOR- They should not join the Socintern loc

### ISSUE THREAD

**Issue by YanSGod** [TNODevs/TNO-Bug-Tracker#1344]
### HOI4 version

1.12.5

### TNO version

1.3.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

If NOR & AST have embarked on the road of socialism,they will join the Socintern loc.But one of them is a German ally and the other is an American ally

### Justifications

There was no logic to this, and it was even stranger that the socialist countries could intervene in a German's or American's war by sending the volunteer army.So they should be banned from the Comintern like socialist Britain and Socialist Italy.

### Screenshots

![QQ截图20221105003148](https://user-images.githubusercontent.com/99068464/200030160-3cbc263c-98d5-4ffb-acd7-cf2b86ad17e1.png)
![QQ截图20221105003229](https://user-images.githubusercontent.com/99068464/200030188-b85ebec3-096c-41ca-b2f6-e4f7376d4418.png)

### Additional information

Please!Thanks,Hopefully, the next update will implement this recommendation

**Comment by runelead00** [comment]
Changed in Dev Build, both are now excluded from ComIntern
