### ISSUE TITLE
KOM - Post Taboritsky Crash

### ISSUE THREAD

**Issue by aznfruitboii** [TNODevs/TNO-Bug-Tracker#1345]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9942095/game.log)
[ENG_1972_09_01_02.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9942130/ENG_1972_09_01_02.zip)

### Describe the crash

When Holy Russian Empire gets "Red Rust" event where Orenburg splits, the game ctds. 

### Steps to reproduce / Cause of the crash

1. load save file (or just form HRE)
2. wait until HRE collapses and the event "Red Rust" fires (after Tomsk becomes a thing)
3. Game crashes

### Screenshots

![Hearts of Iron IV Screenshot 2022 11 04 - 17 35 50 97](https://user-images.githubusercontent.com/117486337/200079037-bddb8206-1914-4e6f-b053-b3640a10af06.png)

### Additional information

The game has never crashed due to Taboritsky collapsing until the merging of custom paths into main TNO mod

**Comment by runelead00** [comment]
Fixed in dev build, not at all related to CCP don't know why'd you single that out
