### ISSUE TITLE
Scotland - Focus has no Loc

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#1346]
### HOI4 version

1.12.3

### TNO version

v1.3.0C

### Do you have other mods in use?

Radio TNO: Music of the New Order and Zizek's Ideology Bling

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![20221104210210_1](https://user-images.githubusercontent.com/50662994/200093133-417bb3e1-9442-4483-9a39-7fc795579f5e.jpg)

### Additional information

missing description for Scotland annihilating there support focus counter-coup

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
