### ISSUE TITLE
USA- WHERES NIXON

### ISSUE THREAD

**Issue by Vanya-2007** [TNODevs/TNO-Bug-Tracker#1347]
### Operating System

11

### HOI4 version

Avalanche v1.12.4.aefa (a85e) (S)

### TNO version

TT4 v1.3.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9944482/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9944483/error.log)

### Describe the bug

WHERE IS NIXON
![wtf](https://user-images.githubusercontent.com/94133847/200135347-4d275b16-c193-4632-bcfd-41020ba76412.png)

### Steps to reproduce / Cause of the issue

1. Load into game
2. sleepy nixon stays home
3. wtf

### Expected behaviour

Load into game

**Comment by runelead00** [comment]
Can't reproduce on release copy, best I recommend is reinstall TNO since it looks like some of your files are missing

**Comment by runelead00** [comment]
oh looks like it's fixed looking at discord, a reload might suffice for other people have the same issue
