### ISSUE TITLE
USA - GFX problem for Election GUI

### ISSUE THREAD

**Issue by 22oroda** [TNODevs/TNO-Bug-Tracker#1348]
### Operating System

Windows 11 Home

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

For the integration of TNO GUI I'm still getting 0% on the counters...

### Steps to reproduce / Cause of the issue

Just start game
Hover over pie charts in the election GUI

### Expected behaviour

should list percentages

### Screenshots

![Screenshot_20221105_022345](https://user-images.githubusercontent.com/110065469/200135500-aeeab761-4713-48be-aecc-23c3fd85763b.png)
![image](https://user-images.githubusercontent.com/110065469/200135508-7269ca19-4fde-4ef7-bf2a-fcc5a6078555.png)

**Comment by Stormeagle449** [comment]
Fixed in current version.
