### ISSUE TITLE
Switzerland leader spelling mistake  

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#135]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: 1.1.2 
- Any other mods in use: Radio TNO: Music of the New Order 

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Effrem Cattelan is spell Efrem Cattelan 
- [ ] 1. 
(Screenshot here)
- [ ] 2. 
![20211113201203_1](https://user-images.githubusercontent.com/50662994/141662876-6e258cb3-96b5-4d79-9d70-44a5714a4bd9.jpg)
(Screenshot here)

**Comment by Scarsoftime** [comment]
Fixed
