### ISSUE TITLE
USA - Event w/ Reference to Kennedy Presidency

### ISSUE THREAD

**Issue by 22oroda** [TNODevs/TNO-Bug-Tracker#1351]
### HOI4 version

1.12.5

### TNO version

1.3.0c

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/110065469/200151009-d2550dce-f5c5-4bac-87f2-1d958148b92a.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
