### ISSUE TITLE
USA - Popularity Gains for Proxy Conflicts Switched

### ISSUE THREAD

**Issue by blaze921** [TNODevs/TNO-Bug-Tracker#1352]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Modifier GUI, Player Led Peace Conferences

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9945130/game.log)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9945136/autosave.zip)

### Describe the bug

After electing LBJ, the events for winning proxy conflicts should have switched from providing Republican support to providing Democrat support, however they continue to provide Republican support, I cannot confirm if this occurs with other presidents.

### Steps to reproduce / Cause of the issue

1. Play as the USA
2. Elect LBJ
3. Win a proxy war (examples that I've seen this glitch on so far are SAW, 3 way WAW, Indonesia, Angola, Congo, and Columbia)
4. Check the tooltip of the victory event that comes after winning, it should show that it gives Republican support rather than Democrat

### Expected behaviour

When winning  a proxy war, it would give Democrat support.

### Screenshots

![Screenshot_20221105_052022](https://user-images.githubusercontent.com/105600171/200153927-b868d0d4-3793-4ad3-9565-c6484957727b.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
