### ISSUE TITLE
Siberian Free Territory - Collapse doesn't have portraits

### ISSUE THREAD

**Issue by 22oroda** [TNODevs/TNO-Bug-Tracker#1353]
### Operating System

Windows 11 

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

During collapse of Central Sib Soviet it feels like they should have portraits, like they all have fleshed out descriptions with different names, but I'm getting blank portraits and random names. Never seen it before so if it's incomplete my bad.

### Steps to reproduce / Cause of the issue

Use CCP to cause SBA collapse
Warlords don't have portraits or names

### Expected behaviour

Correct protrait

### Screenshots

![Screenshot_20221106_125903](https://user-images.githubusercontent.com/110065469/200154997-c609b25a-9df7-401d-9891-2b2f9f33bce5.png)
![Screenshot_20221106_125927](https://user-images.githubusercontent.com/110065469/200154998-e89c2a3e-3eba-4a51-8173-93337c655c64.png)
![Screenshot_20221106_125939](https://user-images.githubusercontent.com/110065469/200154999-e453a02e-8721-4028-8be9-abace055edf8.png)

**Comment by runelead00** [comment]
Fixed in Dev Build, wasn't properly integrated in NSB and apparently no one ever saw it occur in testing
