### ISSUE TITLE
SGR - Unit spawning in Indonesia

### ISSUE THREAD

**Issue by TheMobDestroyer** [TNODevs/TNO-Bug-Tracker#1354]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

The Operation Thunderstorm (and other unrelated mods)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Speerite motorised Unit spawning in province 1332 in Indonesia

### Steps to reproduce / Cause of the issue

1. Play Speer
2. Start Civil War
3. ??? 
4. Profit

### Expected behaviour

Unit spawned in Germany

### Screenshots

![20221106155317_1](https://user-images.githubusercontent.com/25604390/200154983-f12fd293-b8f2-436f-9865-78710429f0c4.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
