### ISSUE TITLE
FRA - Misinfomation in the Lore of Brest

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#1355]
### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

localisation/english/TNO_state_lore_l_english.yml

### List the loc issues below

The text of state_lore_desc.21 says "Brest, standing at the easternmost point of the Breton peninsula" which is not true.

Source:
![brest](https://user-images.githubusercontent.com/65211266/200164912-80bf3137-0c10-4cf8-ba82-587f57481c61.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
