### ISSUE TITLE
Goldwater can't negotiate with Japan on Treaty Ports and Hawaii

### ISSUE THREAD

**Issue by negyit** [TNODevs/TNO-Bug-Tracker#1356]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

A

### Steps to reproduce / Cause of the issue

1. Elect Goldwater

### Expected behaviour

Goldwater could negotiate with Japan as every president can except the 72's candidates.

**Comment by runelead00** [comment]
Already Can in Release, moved up to after the 1971 Senate election in Dev Build, rather than saving for 2nd Inaug
