### ISSUE TITLE
USA - USA_sen_bill.404 has no text

### ISSUE THREAD

**Issue by JonathanNordby** [TNODevs/TNO-Bug-Tracker#1357]
### Operating System

Linux Mint 21 Cinnamon

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

USA_sen_bill.404 has no text

### Steps to reproduce / Cause of the issue

Get LBJ elected
Take The Immigration and Nationality Services Act

### Expected behaviour

the event should have text

### Screenshots

![Screenshot from 2022-11-06 09-13-31](https://user-images.githubusercontent.com/70287268/200175799-64c243da-6262-4602-a372-8aa9c9f6f6e6.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
