### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by SaintPepsi84** [TNODevs/TNO-Bug-Tracker#1359]
### Operating System

Windows 11

### HOI4 version

1.12

### TNO version

1.3.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB, BBA

### Describe the bug

When starting the game and playing as any country I realize that when checking the TOP10 Economies of the World, the system is broken because some weird countries appear as the best ones in economical terms while the U.S, Germany or Japan do not when they have the higher GDPs.

### Steps to reproduce / Cause of the issue

1. Start HOI4 and TNO.
2. Go to the main menu and select a country.
3. Check the Economy Tab and click on the Top 10 Economies.
4. Check it and you will see it's broken.

### Expected behaviour

I expected the U.S. or Japan to be in the Top 10 Economies.

### Screenshots

![Captura de pantalla 2022-11-06 214109](https://user-images.githubusercontent.com/44471301/200194240-e852b091-7410-4c14-99ec-365bcf066ad4.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
