### ISSUE TITLE
ostafrika - doing reinige den suden after the war 

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#136]
**Questions** 

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2 
- Any other mods in use:
- Were you using Steam? yes 
- Which expansions do you NOT have? I have then 

**Longer Description of Issue:** this could case a 2nd south south african war  and break the game if usa goes to war 

**Steps to Reproduce/Cause Issue:**

1. time it right 

2.

etc...

**Screenshots:**
![20211113131651_1](https://user-images.githubusercontent.com/50662994/141663140-8567bb1a-5d15-4798-bdbf-ed91ff3a35e2.jpg)
![20211113131822_1](https://user-images.githubusercontent.com/50662994/141663150-c74c7ec1-9c4d-42a6-9804-874bbf4d0258.jpg)

**Comment by ModdingAccount** [comment]
Fixed on dev build
