### ISSUE TITLE
croatia/montenegro  - montenegro is dead and does not come back

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#1360]
### Operating System

windows 10 

### HOI4 version

1.12.3

### TNO version

v1.3.0d

### Do you have other mods in use?

Radio TNO: Music of the New Order and Zizek's Ideology Bling

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Yugoslavia capitulate Montenegro and Montenegro does not come back 

### Steps to reproduce / Cause of the issue

the ai will do it 

### Expected behaviour

Yugoslavia capitulate Montenegro and Montenegro does not come back 

### Screenshots

![20221106164822_1](https://user-images.githubusercontent.com/50662994/200204238-38864d79-c24a-43e5-bff7-59a560cf51f9.jpg)
![20221106164000_1](https://user-images.githubusercontent.com/50662994/200204276-c6384ed9-3e61-43dd-bd98-18dcf2dd2913.jpg)

### Additional information

you guys will probably will fix by pw

**Comment by runelead00** [comment]
Fixed in Dev Build
