### ISSUE TITLE
Ivan Serov's Komi - outdated lore on brittany

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#1361]
### HOI4 version

1.12.3

### TNO version

v1.3.0C

### Do you have other mods in use?

Radio TNO: Music of the New Order and Zizek's Ideology Bling

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![20221102193846_1](https://user-images.githubusercontent.com/50662994/200204797-bf05a2f7-cfb8-4807-ac5b-31e4138176b5.jpg)

### Additional information

I was using debug tho

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
