### ISSUE TITLE
USA Hart - The focus on reducing poverty actually increase it

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#1362]
### Operating System

Windows10

### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I play Hart, complete the focus on reducing the poverty rate, the poverty rate actually increases. By the time I had finished all the focus on reducing the poverty rate, the poverty rate had risen to a frightening level. The terrible consequences of this bug are that, first, poverty is increasing, not decreasing. Second,with the poverty rate rising, my previous efforts to reduce crime were ineffective. Because high poverty rates bring high crime rates, reducing them can't keep up with rising crime rates.

### Steps to reproduce / Cause of the issue

1.play hart
2.complete the focus of reducing the poverty rate
3.And then you see the poverty rate skyrocket

### Expected behaviour

the focus on poverty reduction can reduce poverty rates

### Screenshots

![20221107112036_1](https://user-images.githubusercontent.com/46292981/200219807-6f9ddcd3-f11c-44ac-8901-a340bb7f8c93.jpg)
![20221107112040_1](https://user-images.githubusercontent.com/46292981/200219827-abf44594-d701-4883-b6f0-8a46528fdd0f.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build by Corn
