### ISSUE TITLE
CAO (and others) - Strange West African War victory

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#1365]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error+gamelog+save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9953017/error%2Bgamelog%2Bsave.zip)

### Describe the bug

After the Free French alliance lost the war, all constituent countries just got annexed/liberated as through a normal Paradox peace conference, the global conflicts' page "West African Conflict" was never removed from the US decision category, the war never seems to conclude on Cold War GUI neither.

### Steps to reproduce / Cause of the issue

1. Trigger the West African War
2. Let the Free French alliance lose

For more details please read the attached game log, I have not followed the developments in West Africa very closely.

### Expected behaviour

A TNO peace deal for West African war that would correctly end the war for the US/Japan and assign points in Cold War GUI.

### Screenshots

![image](https://user-images.githubusercontent.com/63430051/200349495-b2cb29cd-4d14-4886-a644-9df70976c0da.png)
![image](https://user-images.githubusercontent.com/63430051/200349639-1c9bce8e-11bd-4f43-889c-24af04290b2f.png)

**Comment by runelead00** [comment]
Should be fixed for SD by Oveja
