### ISSUE TITLE
France - Starting leader not dead in 1965

### ISSUE THREAD

**Issue by 22oroda** [TNODevs/TNO-Bug-Tracker#1366]
### Operating System

Windows 11 Home

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

TNO Radio

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_1965_01_03_18.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9955980/USA_1965_01_03_18.zip)

Here's my save

### Describe the bug

Tixier-Vignancour still in power in France in 1965.

### Steps to reproduce / Cause of the issue

Honestly I have no idea was waiting around clicked France and suddenly realized he was still around. Used CCP to get Pinay...

### Expected behaviour

He is supposed to flee

### Screenshots

![image](https://user-images.githubusercontent.com/110065469/200428096-c504be90-26de-40f6-a222-3b9af87dbf45.png)

**Comment by runelead00** [comment]
Haven't seen reproduce, likely just client side issue due to recent hotfix at time and steam updates
