### ISSUE TITLE
USA - A Manley with a Plan incorrectly refers to Puerto Plata prior to proxy

### ISSUE THREAD

**Issue by vipersniper2001** [TNODevs/TNO-Bug-Tracker#1368]
### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO, Last Waltz, VT323 font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The USA event "A Manley with a Plan" twice refers to the Puerto Plata invasion, however the event fired prior to the proxy starting. Additionally, had the proxy fired by this point and succeeded, it would not make sense to reference locals attempting to take advantage of America's weakness as a basis for the WIF proxy.
![20221105163242_1](https://user-images.githubusercontent.com/115953733/200448932-9511288b-8565-476f-aad7-d8af37a49f6c.jpg)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
