### ISSUE TITLE
Reichsprotektorat Kaukasien missing leader

### ISSUE THREAD

**Issue by vipersniper2001** [TNODevs/TNO-Bug-Tracker#1369]
### Operating System

Win10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO, Last Waltz, VT323 font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9956811/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9956830/game.log)

### Describe the bug

When Speer establishes the Reichslands in the East, the leader for Reichsprotektorat Kaukasien is missing. It remains missing after it is reestablished following the Slave Revolt as well.
![20221106091805_1](https://user-images.githubusercontent.com/115953733/200449411-4bf62059-233f-45bd-a6ec-be2b7e324dbb.jpg)

### Steps to reproduce / Cause of the issue

Have Speer establish Reichlands rather than collab governments

### Expected behaviour

Non-generic leader for Reichsprotektorat Kaukasien

**Comment by runelead00** [comment]
Fixed in Dev Build
