### ISSUE TITLE
World Event for Angolan Civil War refers to Reichkommissariat Sudwestafrika rather than US mandate

### ISSUE THREAD

**Issue by vipersniper2001** [TNODevs/TNO-Bug-Tracker#1370]
### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO, Last Waltz, VT323 font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

When the Angolan Civil War world news event fires, it refers to the collapse of Reichkommissariat Sudwestafrika when really it was the US mandate that collapsed
![20221106101104_1](https://user-images.githubusercontent.com/115953733/200450084-75e5c4fa-ea1c-4fd4-ac68-86c3371c0b18.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
