### ISSUE TITLE
Never ending Cameroon civil war

### ISSUE THREAD

**Issue by vipersniper2001** [TNODevs/TNO-Bug-Tracker#1371]
### Operating System

Win10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO, Last Waltz, VT323 font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9956817/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9956823/game.log)

### Describe the bug

Sokoto has lost all land and capitulated to Nigeria but the war never ends
![20221106153831_1](https://user-images.githubusercontent.com/115953733/200450456-60e2a750-0665-43eb-afcd-14c4817ef530.jpg)

### Steps to reproduce / Cause of the issue

1. Sara Republic victory
2. Republic of Cameroon peaces out with Biafra
3. Biafra peaces out
4. Nigeria remains at war with Sokoto

### Expected behaviour

An end to the war + scripted peace deal

**Comment by runelead00** [comment]
Should be Fixed in Dev Build
