### ISSUE TITLE
USA - Never-ending African Quagmire

### ISSUE THREAD

**Issue by vipersniper2001** [TNODevs/TNO-Bug-Tracker#1372]
### Operating System

Win10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO, Last Waltz, VT323 font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9956819/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9956820/game.log)

### Describe the bug

Following successful US mandates and WAW reconstruction, the African Quagmire modifier/decision continues to tick down and apply debuffs to the US. The description makes it seem that it should not be relevant when the US is absent from Africa.
![20221106145015_1](https://user-images.githubusercontent.com/115953733/200451007-07a5cebd-f25f-4133-814a-fcb82c058779.jpg)

### Steps to reproduce / Cause of the issue

1. Successful mandates
2. Successful WAW reconstruction in WAA vs PALF scenario
3. No more US presence in Africa yet the modifier remains

### Expected behaviour

The African Quagmire stops being a factor

**Comment by bigbadboy78** [comment]
Had the exact same problem.

**Comment by runelead00** [comment]
Fixed in Dev Build
