### ISSUE TITLE
USA RFK - Incorrect GFX for republicans

### ISSUE THREAD

**Issue by 22oroda** [TNODevs/TNO-Bug-Tracker#1374]
### Operating System

Windows 11 

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

RFK mechanic mentions republicans shows democrats donkey..

### Steps to reproduce / Cause of the issue

1. Play RFK

### Expected behaviour

Republican elephant should show up

### Screenshots

![image](https://user-images.githubusercontent.com/110065469/200463554-5a1e3285-d28a-4d6a-a542-188dea66736c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
