### ISSUE TITLE
USA - West African Reconstruction

### ISSUE THREAD

**Issue by 22oroda** [TNODevs/TNO-Bug-Tracker#1375]
### Operating System

Windows 11 

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

West African reconstruciton after three way civil war shows angolan global conflict page

### Steps to reproduce / Cause of the issue

1. trigger three way civil war
2. reconstruction gfx broke

### Expected behaviour

west african gfx

### Screenshots

![image](https://user-images.githubusercontent.com/110065469/200466194-3ada3516-04c2-4cfc-9d70-c11baea81136.png)

**Comment by bigbadboy78** [comment]
Had the same prob

**Comment by runelead00** [comment]
Fixed in Dev Build
