### ISSUE TITLE
USA-Old Lore

### ISSUE THREAD

**Issue by Wolfstorm75** [TNODevs/TNO-Bug-Tracker#1377]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the event "God Bless John F. Kennedy" it still refers to a previous Kennedy presidency

### Steps to reproduce / Cause of the issue

1 Pass the civil rights act
2 wait for the event to fire around Jan 20, 1963

### Expected behaviour

Shouldn't mention a previous Kennedy presidency

### Screenshots

![20221107213801_1](https://user-images.githubusercontent.com/87508501/200486864-2b98fdae-558f-4ced-959d-fb475a2a028a.jpg)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
