### ISSUE TITLE
Panama Canal Zone became leader of the OFN

### ISSUE THREAD

**Issue by Rinz00** [TNODevs/TNO-Bug-Tracker#1379]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

v1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Playing as Germany when i noticed that the Panama Canal Zone became the leader of the OFN, Not seeing any other issues with this but i would think this isnt intended?

### Steps to reproduce / Cause of the issue

i have no idea

### Expected behaviour

USA Leading the OFN

### Screenshots

![20221108163339_1](https://user-images.githubusercontent.com/117752706/200607859-82426b6d-de49-4ad0-a59c-af70ab37efee.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build, Indonesia CW caused issues with factions again
