### ISSUE TITLE
Ostland - Missing Localisation

### ISSUE THREAD

**Issue by SonattaOfTheEclipse** [TNODevs/TNO-Bug-Tracker#138]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: v1.1.2a - Ordem e Progresso
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None; Only missing a few of the Graphical DLCs

**Longer Description of Issue:**

While beginning a playthrough of Reichskommissariat Ostland and coming to the event of the partisans, and after choosing the SS instead of the Belarussians to assist in finding the culprits, this event fired without any localisation.

**Steps to Reproduce/Cause Issue:**

1. Play Ostland

2. Choose the SS after the Partisans damage your Military Factories

**Screenshots:**
![image](https://user-images.githubusercontent.com/94315640/141693956-da48a2fe-249e-4c3a-86a5-4541f206b061.png)

**Comment by runelead00** [comment]
Fixed in current release
