### ISSUE TITLE
Wrong culture of the Isle of Man

### ISSUE THREAD

**Issue by kaz1ch** [TNODevs/TNO-Bug-Tracker#1380]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The culture of the Isle of Man is Jewish-Levantie Arab.

### Steps to reproduce / Cause of the issue

1. Load game
2. Wait for the ECW
3. Select the state 'Isle of Man'

### Expected behaviour

The culture of the Isle of Man is not supposed to be Jewish-Levantie Arab.

### Screenshots

![image](https://user-images.githubusercontent.com/61201257/200637702-7e96c980-1102-4959-8901-7d2f7965c400.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
