### ISSUE TITLE
USA- West African War does not end under Johnson

### ISSUE THREAD

**Issue by mill3104** [TNODevs/TNO-Bug-Tracker#1382]
### Operating System

mac OS Monterey

### HOI4 version

1.12.5.b273

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I win the West African War under Johnson after sending US troops, but the war does not end and the troops remain in Africa. Also, winning proxy wars helps Republican popularity but not Democratic.

### Steps to reproduce / Cause of the issue

1. Send US troops to West Africa
2. Win the West African War under Johnson

### Expected behaviour

The war should end and the Democrats should benefit.

**Comment by runelead00** [comment]
Should be fixed for SD by Oveja
