### ISSUE TITLE
USA - Some Hart bills do not pass, even though they have majority ayes

### ISSUE THREAD

**Issue by Godzillamanror** [TNODevs/TNO-Bug-Tracker#1384]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Describe the bug

I am not able to pass some bills under President Hart while playing USA. For example, the Rebuild the Ghettos Act does not pass even when I have more senators voting aye than nay for the bill.

### Steps to reproduce / Cause of the issue

1. Do a focus tree that requires passing a bill 
2. Bill automatically fails to pass when voting begins, regardless on whether you have majority senators voting aye or not

### Expected behaviour

I expected the Rebuild the Ghettos Act bill to pass successfully

### Screenshots

![20221109093838_1](https://user-images.githubusercontent.com/117790123/200720383-e6809f28-25af-476e-be26-1f9d6f290cc7.jpg)

**Comment by runelead00** [comment]
Should be fixed in dev build now according Mango
