### ISSUE TITLE
Baluchi Liberation Front - Wrong SubID GFX

### ISSUE THREAD

**Issue by 22oroda** [TNODevs/TNO-Bug-Tracker#1385]
### Operating System

Windows 11 

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

islamic conservatism subideology doesn't match icon

### Steps to reproduce / Cause of the issue

1. Iranaian civl war
2. Baluchi liberation front forms
3. leader has islamic conservatism name and description but wrong gfx

### Expected behaviour

correct gfx

### Screenshots

![image](https://user-images.githubusercontent.com/110065469/200742799-fca1c12f-b4c9-43e6-b366-ad5ceb06db14.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
