### ISSUE TITLE
DOM - PUERTO PLATA INVASION did not give score

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#1386]
### Operating System

Windows10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After Trujillo's victory，PUERTO PLATA INVASION did not give score and still showed ONGOING.

In addition, I really hope you can solve the following problem
https://github.com/TNODevs/TNO-Bug-Tracker/issues/1387

### Steps to reproduce / Cause of the issue

1.PUERTO PLATA INVASION
2.Trujillo is locked in a standoff with the Caribbean Legion.Trujillo did not take Puerto Plata.
3.After a period of time,Pop up news of Trujillo's victory.The Caribbean Legion was annexed by Trujillo.
4.PUERTO PLATA INVASION did not give score and still showed ONGOING

### Expected behaviour

PUERTO PLATA INVASION can give score

### Screenshots

![20221109153452_1](https://user-images.githubusercontent.com/46292981/200768087-00f89012-464c-4a83-9b82-6e39f7422f58.jpg)

**Comment by runelead00** [comment]
Should be fixed in current release
