### ISSUE TITLE
USA - Hart UDI mechanics have several broken components and localization problems.

### ISSUE THREAD

**Issue by Helrica** [TNODevs/TNO-Bug-Tracker#1387]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

Unfinished Business Patch D

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The UDI mechanic for Hart, especially relating to, budget, poverty and crime, has problems where events, foci, and the mechanics themselves are confused as to if lower or higher variables are good or bad and a number of pretty bad mechanical bugs that screw with the average playthrough.

For instance, having a city upkeep variable of .25 means you are displayed as doing extremely well, but instead it triggers a bankruptcy crisis. The same is true of the poverty rate, homeless rate and crime rates. 

Also, policing and crime prevention actually displayed backwards. Increasing the police and prevention program variables decreases the crime rate variable. But the crime rate variable is displayed as less crime the higher it is, so it tells you in the focus descriptions that they will become less effective when they become more effective.

In terms of mechanical bugs, a high budget increases the economy when it should decrease it, homelessness increases happiness and too little crime increases racism. Route 69 (yes) never gets started and never has any work done on it for some reason and Amtrak electrification is never displayed as finished. Zsa Zsa also refuses to stop meddling in the last of Chep's interest groups she was in, even when she becomes useful because that flag isn't cleared. Finally the VA event (hart.tree.34) raises poverty and homelessness instead of lowering them.

Probably the most impactful out of all of these is that the Americar does nothing at all whatsoever no matter how solvent it is or is not and the event where it succeeds probably wouldn't help because it sets the solvency at 0.

### Steps to reproduce / Cause of the issue

I'm not good enough a modder to really track down most of these, but a huge budget making the economy better, homelessness making people happy and no crime causing inequality can be fixed by doing the following in TNO_US_scripted_effects. First, crime and inequality:	

# increasing crime - > decreasing equality
	if = {
		limit = {
			# above 0
			check_variable = {
				var = USA_CITY_crime_rate
				value = 0
				compare = greater_than_or_equals
			}
		}
		custom_effect_tooltip = USA_crime_equality_tt
		set_temp_variable = { USA_temp_equality_var = USA_CITY_crime_rate } # 0 to .50
		add_to_temp_variable = { USA_temp_equality_var = 0.5 } # -1 to -.5
		multiply_temp_variable = { USA_temp_equality_var = -0.018 } # 0.03 to 0.015
		USA_equality_adjust = yes
	}

Should be

	# increasing crime - > decreasing equality
	if = {
		limit = {
			# below 0
			check_variable = {
				var = USA_CITY_crime_rate
				value = 0
				compare = less_than_or_equals
			}
		}
		custom_effect_tooltip = USA_crime_equality_tt
		set_temp_variable = { USA_temp_equality_var = USA_CITY_crime_rate } # 0 to .50
		add_to_temp_variable = { USA_temp_equality_var = 0.5 } # -1 to -.5
		multiply_temp_variable = { USA_temp_equality_var = -0.018 } # 0.03 to 0.015
		USA_equality_adjust = yes
	}

As for economy.

	# high budget -> bad economy
	if = {
		limit = {
			# above 0
			check_variable = {
				var = USA_CITY_upkeep_cost
				value = 0
				compare = greater_than_or_equals
			}
		}
		custom_effect_tooltip = USA_budget_economy_tt
		set_temp_variable = { USA_temp_spending_power_var = USA_CITY_upkeep_cost } # 0 to .50
		add_to_temp_variable = { USA_temp_spending_power_var = -.5 } # -1 to -.5
		multiply_temp_variable = { USA_temp_spending_power_var = 0.018 } # 0.03 to 0.015
		USA_spending_power_adjust = yes
	}
should be

	# high budget -> bad economy
	if = {
		limit = {
			# above 0
			check_variable = {
				var = USA_CITY_upkeep_cost
				value = 0
				compare = greater_than_or_equals
			}
		}
		custom_effect_tooltip = USA_budget_economy_tt
		set_temp_variable = { USA_temp_spending_power_var = USA_CITY_upkeep_cost } # 0 to .50
		add_to_temp_variable = { USA_temp_spending_power_var = -.5 } # -1 to -.5
		multiply_temp_variable = { USA_temp_spending_power_var = -0.018 } # 0.03 to 0.015
		USA_spending_power_adjust = yes
	}
Finally homelessness.

	# high homelessness -> decrease happiness
	set_temp_variable = { USA_temp_happy_mix = USA_CITY_homelessness }
	add_to_temp_variable = { USA_temp_happy_mix = USA_CITY_poverty_rate }
	if = {
		limit = {
			# above 0
			check_variable = {
				var = USA_temp_happy_mix
				value = 0
				compare = less_than_or_equals
			}
		}
		set_temp_variable = { USA_temp_happiness_var = USA_temp_happy_mix } # 0 to .50
		multiply_temp_variable = { USA_temp_happiness_var = 0.03 } # 0.06 to 0.03
		if = {
			limit = {
				check_variable = { USA_temp_happiness_var > 0 }
			}
			custom_effect_tooltip = USA_homeless_poverty_happiness_tt
			USA_happiness_adjust = yes
		}
	}

Should probably be:

	# high homelessness -> decrease happiness
	set_temp_variable = { USA_temp_happy_mix = USA_CITY_homelessness }
	add_to_temp_variable = { USA_temp_happy_mix = USA_CITY_poverty_rate }
	if = {
		limit = {
			# above 0
			check_variable = {
				var = USA_temp_happy_mix
				value = 0
				compare = greater_than_or_equals
			}
		}
		set_temp_variable = { USA_temp_happiness_var = USA_temp_happy_mix } # 0 to .50
		multiply_temp_variable = { USA_temp_happiness_var = 0.03 } # 0.06 to 0.03
		if = {
			limit = {
				check_variable = { USA_temp_happiness_var > 0 }
			}
			custom_effect_tooltip = USA_homeless_poverty_happiness_tt
			USA_happiness_adjust = yes
		}
	}

Also the VA event can be fixed by changing this in TNO_America_RDC_D from

	id = hart.tree.34
	immediate = {log = "[GetDateText]: [Root.GetName]: event hart.tree.34"}
	title = hart.tree.34.t
	desc = hart.tree.34.desc
	picture = GFX_report_event_Edward_Lansdale_looking_like_a_bitch

	is_triggered_only = yes

	immediate = {
		hidden_effect = {
		}
	}

	option = { # 
		name = hart.tree.34.a
		
		set_temp_variable = { USA_temp_poverty_rate_var = 0.04 }
		USA_poverty_rate_adjust = yes
		set_temp_variable = { USA_temp_homeless_rate_var = 0.04 }
		USA_homeless_rate_adjust = yes
	}
}

To

	id = hart.tree.34
	immediate = {log = "[GetDateText]: [Root.GetName]: event hart.tree.34"}
	title = hart.tree.34.t
	desc = hart.tree.34.desc
	picture = GFX_report_event_Edward_Lansdale_looking_like_a_bitch

	is_triggered_only = yes

	immediate = {
		hidden_effect = {
		}
	}

	option = { # 
		name = hart.tree.34.a
		
		set_temp_variable = { USA_temp_poverty_rate_var = -0.04 }
		USA_poverty_rate_adjust = yes
		set_temp_variable = { USA_temp_homeless_rate_var = -0.04 }
		USA_homeless_rate_adjust = yes
	}
}

### Expected behaviour

All of these make a Hart playthrough confusing as heck.

**Comment by Helrica** [comment]
Oh, another one. Low poverty increases crime.

# High poverty -> increasing crime
	if = {
		limit = {
			# above 0
			check_variable = {
				var = USA_CITY_poverty_rate
				value = 0
				compare = less_than_or_equals
			}
		}
		custom_effect_tooltip = USA_poverty_crime_tt
		set_temp_variable = { USA_temp_crime_rate_var = USA_CITY_poverty_rate } # 0 to .50
		add_to_temp_variable = { USA_temp_crime_rate_var = -0.5 } # -1 to -.5
		multiply_temp_variable = { USA_temp_crime_rate_var = -0.018 } # 0.03 to 0.015
		USA_crime_rate_adjust = yes
	}
	
	Should be:
	
		# High poverty -> increasing crime
	if = {
		limit = {
			# above 0
			check_variable = {
				var = USA_CITY_poverty_rate
				value = 0
				compare = greater_than_or_equals
			}
		}
		custom_effect_tooltip = USA_poverty_crime_tt
		set_temp_variable = { USA_temp_crime_rate_var = USA_CITY_poverty_rate } # 0 to .50
		add_to_temp_variable = { USA_temp_crime_rate_var = -0.5 } # -1 to -.5
		multiply_temp_variable = { USA_temp_crime_rate_var = -0.018 } # 0.03 to 0.015
		USA_crime_rate_adjust = yes
	}

**Comment by runelead00** [comment]
Should be all fixed in dev build now according Mango
