### ISSUE TITLE
Canada owns Safed and Golan Heights + Canadian culture in both states

### ISSUE THREAD

**Issue by Rinz00** [TNODevs/TNO-Bug-Tracker#1388]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

v1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Noticed Canada became the owner of the states of Safed and Golan Heights in the Levant, BC and western Canada cultures were also in the states.

### Steps to reproduce / Cause of the issue

im not an expert but i would guess some code in the levant bugged

### Expected behaviour

Canada not owning those states

### Screenshots

![20221109112333_1](https://user-images.githubusercontent.com/117752706/200806691-e645a08c-30d7-4682-be8c-65c9b17ff489.jpg)
![20221109112338_1](https://user-images.githubusercontent.com/117752706/200806711-300f7573-6627-4556-b7ca-b1b0f368728f.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
