### ISSUE TITLE
Xinan - Focus tree issues

### ISSUE THREAD

**Issue by Ginger-Reaper** [TNODevs/TNO-Bug-Tracker#139]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 (iirc, whatever the version is as of 15/11/2021 (dd/mm/yyyy))
- TNO Version: v1.1.2 “Ordem e Progresso”
- Any other mods in use: Only music mods
- Were you using Steam?: Yes
- Which expansions do you NOT have?: I don't own any dlc except the Anniversary Pack

**Longer Description of Issue:**

Played Xinan peacefully (a.k.a. I shot Long Yun), and noticed a few issues with their focuses

1) The focuses "Every Inch Surveyed" and "Look the Other Way" have no effects at all, listed or actual.

2) The focuses "Every Grain is Earned with Hardship" and "Heed their Advice" have listed effects of: "Every state: add the following: monthly population: +150%" and "Effect: gets a new cabinet" respectively. These effects are not added.

3) Xinan has no government ministers, nor a head of government for the entire game.

4) The focus "Lay down the Roads" enables missions to build factories, as well as add the modifier "local factories: +25%" to every owned state. The factories are built, but the state modifier is not added.

5) The focus "Revive the Burma Road" enables the "Burma Road Revival Projects" (decisions), however the first decision fires an invalid event in Burma. This locks any future progress without the console command "decision.nochecks".

6) Completing the Burma Road project grants nothing except a flavour event

7) The focuses "Draw Closer to China", "New Friends" and "Economic Ties" mention China gaining influence in Xinan, while Japan loses influence. Yet there is no indication of what "influence" is, what it does and how much China and Japan have in Xinan.

**Comment by Scarsoftime** [comment]
Path no longer exists
