### ISSUE TITLE
YUN - Unique endscreen for KMT Republic of China

### ISSUE THREAD

**Issue by HighMountainGuy** [TNODevs/TNO-Bug-Tracker#1391]
### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Which major expansions do you NOT have?

BBA

### Describe your suggestion

Just like how the US for instance has unique epilogue localisation, I feel like Sun Fo Republic of China should have one aswell

### Justifications

I believe it adds a sort of rewarding and satisfying sense to having played Kuomintang restored Republic of China at the end of its existing content, since the US has this unique feature too.

### Screenshots

![image](https://user-images.githubusercontent.com/71605887/200921400-4c9cea1d-079f-4374-a3a3-6b6591e4897e.png)

### Additional information

X

**Comment by Stormeagle449** [comment]
Added in Dev Build.
