### ISSUE TITLE
SER - Civil War never ends.

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1392]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Music mods and the recall volunteer mod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The civil war that occurs in Serbia has lasted 5 years now, with no movement between either of them in around 3 years.

### Steps to reproduce / Cause of the issue

1. Start a game.
2. Wait until the German Civil War starts.
3. Serbian Civil War will start.

### Expected behaviour

The Civil war most likely isn't supposed to last 5 years, and longer.

### Screenshots

![image](https://user-images.githubusercontent.com/25708474/200931733-2925c748-76c9-4fca-8094-f45a56ef560d.png)

**Comment by runelead00** [comment]
Balanced improved in dev Build
