### ISSUE TITLE
The Isle of Man is Jewish-Levantine Arab

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#1393]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Isle of Man has Jewish-Levantine Arab culture.

### Steps to reproduce / Cause of the issue

Look at it

### Expected behaviour

The Isle of Man is Jewish-Levantine Arab

### Screenshots

![Hearts of Iron IV (DirectX 11) 10_11_2022 9_10_28 PM](https://user-images.githubusercontent.com/59920852/201063695-1b5ade77-fd01-4a48-a2f7-03e0ec6e9dc9.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
