### ISSUE TITLE
USA - West African Reconstruction Military build up is too tight. 

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#1396]
### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

When reconstructing Free France as the USA there are tonnes of decisions for economic reconstruction that are challenging and reasonable but military reconstruction is extremely tight and unforgiving in comparison with only 2 or so options. When your dealing with a tonne of other responsibilities as the USA it can get ridiculously tight too pull off the mil reconstruction with command power when it really shouldnt be. I suggest adding an 2 more or so options to send weapons to the Free French to aid in reconstruction. 

### Justifications

Extremely tight margins to get Free French military reconstruction done compared to economic. Shouldnt be so difficult as America has vast resources to give but cannot due to no decisions. Especially strange as Econ is so well balanced. Mil should be about 20 to 25 percent easier to achieve imo.

**Comment by runelead00** [comment]
Should be fixed in Dev Build
