### ISSUE TITLE
JAP - Missing Loc for Proxy Stuff

### ISSUE THREAD

**Issue by RolandoMagyar** [TNODevs/TNO-Bug-Tracker#1397]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

The Moe Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The start of the Colombian conflict is missing it loc.

### Steps to reproduce / Cause of the issue

Just playing Japan, and this pops in July 1964.

### Expected behaviour

I was expecting to see loc.

### Screenshots

![image](https://user-images.githubusercontent.com/97245647/201162062-0b0d5dc6-edad-4a1b-819b-638027fe5695.png)

**Comment by RolandoMagyar** [comment]
It seems like another missing loc for Japan, about the Christmas Offensive 


![image](https://user-images.githubusercontent.com/97245647/201163385-75444924-e135-4cc7-8683-faf84c41f48e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
