### ISSUE TITLE
China - No Longer in Sphere after Western Insurrection

### ISSUE THREAD

**Issue by karkatthedalek** [TNODevs/TNO-Bug-Tracker#1398]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

While I was playing the US (Wallace to Hart), I noticed that once China had defeated the Western Insurrection, it did not rejoin the Sphere, nor did Mengjiang or the various cliques (Manchuria might have been the same, though I can't recall). This also appeared to severely impact Japan's standing in the Cold War ranking, even discounting all of its losses in the proxy wars.

### Steps to reproduce / Cause of the issue

1. Start the Western Insurrection (while playing USA?)
2. Wait for the Republic of China to put down the National Protection Army (perhaps also us the CIA decision to fund Chinese rebels, if that could somehow affect this)

### Expected behaviour

That China would rejoin the Sphere when the conflict had concluded

**Comment by runelead00** [comment]
Should be fixed in current release
