### ISSUE TITLE
USA - LBJ's NPP Civil Rights Demand Mission is too short

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#140]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?
I have all expansions
**Longer Description of Issue:**
Lyndon B Johnson can strike a deal with the NPP, which gives you a variable called LBJ_NPP_civil_rights_demand = 0 in event LBJ.6

You get a mission to deal with Civil Rights by getting all the way to Fair Housing act at the bottom of his tree. The problem is the timer only gives you 110 days to finish it before you get your first punishment.
![image](https://user-images.githubusercontent.com/56777501/142741809-49f9d216-ad3a-4d38-841a-542481baf9e3.png)

Based off my reading of the decision timer, you get a total of 440 days (4 total failures) to finish the tree before you straight-up fail and lose the deal with the NPP-C (plus around 150pp). There are 15 28-day focuses between Deal with the NPP-C and the Fair Housing Act. 

![image](https://user-images.githubusercontent.com/56777501/142741966-2bc26306-8445-4dcd-bef2-111e6fc009e2.png)

This means you have 420 days to finish Fair Housing Act before you lose the NPP Coalition, and this is only if you went Form Task Forces before you went Deal with the Center, which is pretty unfair because there's no way you would know that without looking at the files first.
![image](https://user-images.githubusercontent.com/56777501/142742018-97b61719-309f-4458-9ca3-98c44b806de3.png)

As LBJ then you end up losing 50 pp for finishing the Civil Rights tree with the NPP-C as your allies since completing the timer only gives you 100pp back while you lost 50pp for each timer you failed. 

To make this path less of a trap path I think the base timer should be 200 days (it takes 168 days to get to the Voting Rights Act and another 56 days if you didn't do the Form Task Forces focuses first). If you pass the Voting Rights Act and it doesn't suck, then you get 150 days added to the timer to get to Immigration Act (another 5 focuses down, or 140 days). If you pass Immigration Act, you get another 120 days added to the timer to finish Fair Housing act. 

This way you are still incentivized to finish Civil Rights tree fast and it's still a net bonus to work with the NPP-C and follow their demands. Otherwise the RD player loses a ton of popularity for not gain if they work with NPP-C to get civil rights done.

**Steps to Reproduce/Cause Issue:**

1. Event LBJ.137 to get the LBJ Presidency tree

2. Look at the Focus tree to measure out the timing. Do the deal with the Center Focus to see what I'm talking about

**Comment by bobw123** [comment]
Rip this submitted early - give me one sec to fix

**Comment by ModdingAccount** [comment]
Suggestion implemented on dev build.
