### ISSUE TITLE
tomsk/oryotia there no peace unification

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#1400]
### HOI4 version

1.12.3

### TNO version

v1.3.0d

### Do you have other mods in use?

Radio TNO: Music of the New Order and Zizek's Ideology Bling

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![20221108125605_1](https://user-images.githubusercontent.com/50662994/201390804-41bb8632-e196-4766-a5b1-6a58e452342e.jpg)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
