### ISSUE TITLE
No fighting in the Indonesian Civil War

### ISSUE THREAD

**Issue by AlexSpuds** [TNODevs/TNO-Bug-Tracker#1401]
### Operating System

Windows 10 

### HOI4 version

1.12.5.b273 

### TNO version

1.3.0d

### Do you have other mods in use?

radio_tno, The New Order: Cheat Mod++, The New Order: VT323 Map and Cities Font, Toolpakt: Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Files

https://www.dropbox.com/s/oq221uh7dtac4lj/USA_1965_03_19_06.hoi4?dl=0

### Describe the bug

The Indonesian Civil War is supposed to fire in March 1965, but while the warring statelets spawn, they do not fight.
Eventually, you will keep receiving events regarding the Indonesian Civil War as if it is going on (USA event "our boys are dying", etc), while the fighting has still not started.

### Steps to reproduce / Cause of the issue

Reach March 1965, doesn't matter which state you reach it with, The Indonesian Civil War superevent will fire and the statelets will spawn, but no fighting will begin.

### Expected behaviour

The Indonesian Civil War is supposed to begin and for fighting to occur.

### Screenshots

![20221111031827_1](https://user-images.githubusercontent.com/6463144/201428566-cd5669b6-87dc-4248-b077-99a854f28d16.jpg)

### Additional information

I use a long specific game rule set on this save, but also tested it once on a USA run with all the game rules on the list except the Indonesian one (in spectator mode), then another USA run without any game rules (also in spectator mode), and then a run with Italy without any extra mods besides TNO, and no game rules (in spectator mode again).

**Comment by runelead00** [comment]
Indonesia needs to escalate before the actual fighting begins
