### ISSUE TITLE
Ponylon (OMO) - Cannot Reunify East Siberia

### ISSUE THREAD

**Issue by Qwiksis** [TNODevs/TNO-Bug-Tracker#1403]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Tool Pack 2022, TNO Unofficial Soundtrack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[peace_conference.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994048/peace_conference.log)
[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994049/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994050/sent_commands.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994051/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994052/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994053/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994054/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994055/time.log)
[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994056/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994057/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994058/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994059/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994060/executed_commands.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994061/game.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994063/graphics.log)
[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994064/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994065/message.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994066/posted_commands.log)
[random.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994067/random.log)
[random_1.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994069/random_1.log)
[random_2.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994070/random_2.log)
[random_3.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994071/random_3.log)
[random_4.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994072/random_4.log)
[random_5.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994073/random_5.log)
[random_6.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994074/random_6.log)
https://ufile.io/tc2bcyz6
https://ufile.io/x6198a4z

### Describe the bug

I cannot Reunify East-Siberia and continue the path.

### Steps to reproduce / Cause of the issue

1. Launch Save
2. Go to decisions
3. Cannot reunify East Siberia
4. D:

### Expected behaviour

A decision to form East Siberia should exist. (Now that I think about it, the decisions to attack warlords weren't under a larger 'Russian Reunification' decision tab, or at least it didn't have the option to reunify)

### Screenshots

![image](https://user-images.githubusercontent.com/116316629/201456482-f6925102-6f1a-4d6e-92ef-40a10e909152.png)
![image](https://user-images.githubusercontent.com/116316629/201456490-31360ffe-1ff6-4f24-ab2e-5838d1638e30.png)
![image](https://user-images.githubusercontent.com/116316629/201456492-cf0c33c8-e9de-4093-b1d0-2e6ff1310336.png)
![image](https://user-images.githubusercontent.com/116316629/201456559-87005069-18a8-4c83-a29b-e17b5598cc77.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
