### ISSUE TITLE
Iberian Union - “Carnation Revolution” country path broken

### ISSUE THREAD

**Issue by itsandyru** [TNODevs/TNO-Bug-Tracker#1405]
### Operating System

macOS Big Sur

### HOI4 version

Avalanche 1.12.5

### TNO version

Unfinished Business 1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Carnation Revolution country path is selected in the game rules, the AI will keep authoritarianism high instead and eventually start the Iberian Wars (when the Iberian Wars started the Federal Government had “State of the Union - Exemplary” so the only way the Iberian Wars could have started is through high authoritarianism, I double-checked this later by tag-switching)

### Steps to reproduce / Cause of the issue

1. Select the “Carnation Revolution” path in the “Country Paths - Other - Triumvirate” subsection along with “The Union Endures” and “A Legislative Council”
2. Wait for the Iberian Union to get to its partial democratisation part of the focus tree
3. After some time tag over and check their authoritarianism level, it should be high
4. Eventually (in my game it happened in around January 1974) the Iberian Wars will start

### Expected behaviour

AI decisions making authoritarianism low and triggering the Carnation Revolution

**Comment by Tarepa** [comment]
This will be fixed in the next patch. Thank you for your report.
