### ISSUE TITLE
Crash on Country Select

### ISSUE THREAD

**Issue by JPIIJMD** [TNODevs/TNO-Bug-Tracker#1406]
### Operating System

Windows 10

### HOI4 version

1.12.5.b273

### TNO version

1.3.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9994990/error.log)

### Describe the crash

in the middle of loading the game (entering a country) it crashes me

### Steps to reproduce / Cause of the crash

1.start the game with TNO
2. select any country 
3. start game (then is crash)

**Comment by runelead00** [comment]
Merged into #962
