### ISSUE TITLE
German Reich After Goring wins - Game freezes when clicking the Doctrine menu

### ISSUE THREAD

**Issue by MrDeepBattle** [TNODevs/TNO-Bug-Tracker#1407]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0e

### Do you have other mods in use?

Cold War iron curtain Music, TNO Cheat mod++

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9995554/error.log)
[exception.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/9995557/exception.txt)

### Describe the bug

During the GCW. You can select and advance land,air,navy doctrines as goring.
Upon winning the GCW though. Whenever you click on the doctrine menu, the games freezes, and will eventually crash.
I have tried it without the music mod and cheat mod. And it still crashes. 

### Steps to reproduce / Cause of the issue

1. Win the GCW as goring
2. Click the doctrine menu.

### Expected behaviour

The game will eventually freeze and crash.

**Comment by runelead00** [comment]
Fixed in Dev Build
