### ISSUE TITLE
USA - Hart’s Amtrak gets stuck on “Electrifying” for eternity, and Interstate 69 is stuck at 0%

### ISSUE THREAD

**Issue by TheWolfyXZ** [TNODevs/TNO-Bug-Tracker#1409]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

None 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Selecting all the options to electrify Amtrak in the decisions menu and finishing the transportation lead to Amtrak staying at “Electrifying” forever, never finishing.

Interstate 69 stays permanently stuck at 0% despite every other interstate at 70% or finished 

### Steps to reproduce / Cause of the issue

Elect hart, do transportation tree and select all options to Electrify Amtrak + options for interstates 

### Expected behaviour

Amtrak completing and Interstate 69 progressing

**Comment by runelead00** [comment]
Amtrak should be fixed in Dev Build

**Comment by runelead00** [comment]
Should be all fixed in dev build now according Mango
