### ISSUE TITLE
All countries - tension tab scrollbars

### ISSUE THREAD

**Issue by mferlandusc** [TNODevs/TNO-Bug-Tracker#141]
In the tensions section of TNO, there is an overall scroll bar, and a scroll bar specifically for "past incidents." Thus, it looks as in the following image:
![ScrollbarsTNOIncidents](https://user-images.githubusercontent.com/46851797/142742473-d0849971-0f0b-4c2d-ac0d-a21fa12c5a71.png)
However, as demonstrated with the image, this is as low as you can scroll with a mouse wheel with the cursor in the center of the page.  To see the bottom incidents, the user has to scroll the left scrollbar down specifically. This makes navigating this page awkward.

The suggestion is simply to merge it into a single bar. Or, alternatively, if this section grows large as the game goes on, to divide it into collapsible subsections which is still all controlled with the main scrollbar.

**Comment by Stormeagle449** [comment]
Fixed in UB.
