### ISSUE TITLE
IRK/BRY/SVR - Artillery and AA GFX 

### ISSUE THREAD

**Issue by ItsRevanAgain** [TNODevs/TNO-Bug-Tracker#1412]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Do you have other mods in use?

Radio TNO, Soviet and Russian Music, Smaller Outlines, RGFX White Map Font.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Not much to say, Irkutsk is suffering from a serious case of generic equipment graphics. 
Teching up makes no difference as the icon remains generic.

### Steps to reproduce / Cause of the issue

1. Play as Irkustk, Buryatia or the Ural District
2. Open the production tab
3. Chances are it's just a localisation issue and the pathing is skewwhiff

### Expected behaviour

Production icons should be the same as in research.

### Screenshots

As they are;
![image](https://user-images.githubusercontent.com/33811430/201549846-1151bea2-59e8-43a6-9648-014d2c34521b.png)
![image](https://user-images.githubusercontent.com/33811430/201549868-6b0d0be9-7377-4475-ad6b-caec4a3b53ec.png)
As they should be;
![image](https://user-images.githubusercontent.com/33811430/201550092-fb89c859-d205-4bab-844a-7b682eb5573a.png)

### Additional information

Are those questions with asterisks really necessary when the simple matter of dodgy graphics are just that, simple?

**Comment by runelead00** [comment]
Fixed artillery and AA equipment for all tags in Russia as well as basic motorized and non-NSB APCs which suffered from the same issue
