### ISSUE TITLE
[Bug]: MISC - Continent mismatches

### ISSUE THREAD

**Issue by Max200012** [TNODevs/TNO-Bug-Tracker#1413]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Certain Continents have different Continents inside them, example being, there's bits of the South American Continent in South Africa

### Steps to reproduce / Cause of the issue

It's a map issue, go to Nudge Tool and fix the continents

### Expected behaviour

continents should be normal

### Screenshots

![20221113031450_1](https://user-images.githubusercontent.com/91160979/201725003-b8cec785-dce0-4c4d-ac66-83562e58feea.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
