### ISSUE TITLE
Speer's Ger - missing loc for Generalgouvernment invasion.

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1415]
### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Music mods and the recall volunteer mod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

If the generalgouvernment win the war in Poland, Speer's Germany has an event to invade it, unfortunately, this event is missing loc, as seen below.

![image](https://user-images.githubusercontent.com/25708474/201752057-6d9879b4-65db-490c-967f-65182408708b.png)

**Comment by turbobounce** [comment]
Okay so the next event is also missing loc, as seen below as well.

![image](https://user-images.githubusercontent.com/25708474/201753071-9b1d0a62-b3f5-41f1-bfd0-c64f1283d775.png)

**Comment by runelead00** [comment]
Both fixed in dev build
