### ISSUE TITLE
USA - Incorrect 1964 RDC Convention Loc

### ISSUE THREAD

**Issue by itsandyru** [TNODevs/TNO-Bug-Tracker#1416]
### HOI4 version

Avalanche 1.12.5

### TNO version

Unfinished Business 1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- Reversed party switch not reflected in 1964 RDC Convention, with LBJ still referred to as a Republican and Wallace Bennett a Democrat
<img width="1440" alt="Screenshot 2022-11-15 at 9 50 33 PM" src="https://user-images.githubusercontent.com/98255313/201873557-69bbd56c-f044-4a00-a3f3-92baa33ee29f.png">
event USA.133

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
