### ISSUE TITLE
USA - JFK-McCormack transition timing

### ISSUE THREAD

**Issue by itsandyru** [TNODevs/TNO-Bug-Tracker#1417]
### HOI4 version

Avalanche 1.12.5

### TNO version

Unfinished Business

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Adjust either focus length for JFK/McCormack/both or the focus description and triggered event for the McCormack focus “Crunching Numbers at Dusk”.

### Justifications

Since JFK now gets shot a lot later on, McCormack now finishes his focus tree some time in Mid-December instead of on the evening before Election Day as intended. This makes the focus description for “Crunching Numbers at Dusk” and subsequent event feel very out-of-place as it talks about McCormack trying to figure out who has the edge in the election, waking up to a new president, etc etc etc when the results were revealed one and a half months ago. Either the focus lengths for McCormack should be shortened to get back to the intended timing or the final focus should be changed to something about preparing for the succession of the next president.

**Comment by runelead00** [comment]
Adjusted in current dev build
