### ISSUE TITLE
KOM - Stablizing against coup starts smuta instantly

### ISSUE THREAD

**Issue by prchad** [TNODevs/TNO-Bug-Tracker#1418]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

When Androbov gets on power from election in minor advantages, he is asked to stablize as well as tracking down a focus tree. When stabilization is complete, a new focus tree (the Smuta one) instantly loads, leaving most of the "revolution" tree unfinished, so names, flags etc are not changed, and some divisions that should be disbanded or unlocked are still locked.

### Steps to reproduce / Cause of the issue

Komi
Left wins marginally
Stablize the situation before finishing the "revolution" tree

### Expected behaviour

The "revolution" tree is kept, and Smuta is started after it is finished.

**Comment by runelead00** [comment]
Fixed in Dev Build
