### ISSUE TITLE
Schild broke & Boers reappeared in middle of SAW

### ISSUE THREAD

**Issue by Rorschach113** [TNODevs/TNO-Bug-Tracker#1419]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.3.0d with addendum

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10018200/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10018201/game.log)
https://www.dropbox.com/s/2btj6qnm3ekhk8c/USA_1966_10_19_12.hoi4?dl=0

### Describe the bug

I was playing USA as RFK, fighting the South African War. It was going well, though speer was doing his best to reinforce the two remaining German colonies in Africa. But then I got some popups saying some Boer cities had been reclaimed by the enemy. This confused me as no enemy units were near there and I was mopping up my foes north of there. When I looked south, the Boers were back! and then I got the Schild Broken event, which I'm pretty sure is only supposed to happen after the war is done. Either way, the Boers popping back up after I beat them while still in middle of war definitely isn't right. 

### Steps to reproduce / Cause of the issue

Not totally sure what caused this but -

1 - Fight SAW as RFK
2 - Beat Boers & Sudwestafrika
3 - Boers are back for some reason?!
4 - Schild Broken

### Expected behaviour

Boers stay dead. Unsure regarding schild breaking, but pretty sure that only ought to happen after SAW.

**Comment by runelead00** [comment]
Fixed in Dev Build
