### ISSUE TITLE
USA - Joseph Kennedy still mentioned as President in some events

### ISSUE THREAD

**Issue by TheWinterCrow** [TNODevs/TNO-Bug-Tracker#1420]
### HOI4 version

1.12.5.b273

### TNO version

1.3.0d

### Describe your suggestion

I've just recently started a Robert Kennedy USA playthrough, and I've noticed a few of the events still mention Joseph Kennedy as a former president of the United States. I think it would be good to comb through some of these events and edit them to suit the new continuity better.

### Justifications

I'm to understand that the previous lore for TNO has been superseded, with Kennedy no longer replacing Roosevelt as the 32nd president of the United States. Having bits of the previous lore littered in a few events is a continuity issue, and could result in confusing newer players.

### Screenshots

![Kennedy leftover 1](https://user-images.githubusercontent.com/118331496/202090653-ff72ad0b-4242-41a3-a558-0236f84f33dd.png)
![Kennedy leftover 2](https://user-images.githubusercontent.com/118331496/202090688-9bef676d-8935-4d62-a888-8f06ac4ec84e.png)
![Kennedy leftover 3](https://user-images.githubusercontent.com/118331496/202090732-60e2ee70-3aca-4c16-afd7-6c9daec0a632.png)

**Comment by Stormeagle449** [comment]
Fixed in dev build.
