### ISSUE TITLE
VYT - National Spirit missing icon

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#1423]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The icon for the 'Liberal Economy' nat spirit is missing.

### Steps to reproduce / Cause of the issue

Complete focus 'Economic Liberalisation'

### Expected behaviour

Should have an icon

### Screenshots

![Hearts of Iron IV (DirectX 11) 17_11_2022 5_45_35 PM](https://user-images.githubusercontent.com/59920852/202375906-ae3e3ce8-cd2c-4504-b108-e6d480733d61.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
