### ISSUE TITLE
VYT - 'A Shackled Okhrana' national spirit duplicated

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#1424]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The 'A Shackled Okhrana' national spirit gets duplicated upon completeing the focus 'Reduce the Okhrana'.

### Steps to reproduce / Cause of the issue

Complete the focus 'Reduce the Okhrana'

### Expected behaviour

No duplicate

### Screenshots

![Hearts of Iron IV (DirectX 11) 17_11_2022 9_29_46 PM](https://user-images.githubusercontent.com/59920852/202422806-271b8434-1c15-49ff-ba6c-96baea704eec.png)
![Hearts of Iron IV (DirectX 11) 17_11_2022 9_29_53 PM](https://user-images.githubusercontent.com/59920852/202422823-5cf69bc1-585c-4dc0-bfc3-3350587200a1.png)

**Comment by runelead00** [comment]
Should be fixed in Dev Build
