### ISSUE TITLE
CAU - Speer's puppet has no leader portrait

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#1425]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The leader of Caucasia imposed by Speer doesn't have a portrait portrait

### Steps to reproduce / Cause of the issue

I dunno man

### Expected behaviour

The guy should have a portrait

### Screenshots

![Hearts of Iron IV (DirectX 11) 17_11_2022 9_31_19 PM](https://user-images.githubusercontent.com/59920852/202423788-a98390e4-093b-4fcd-9c5b-dded8f132841.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
