### ISSUE TITLE
CHI - China not rejoining the Sphere after the Western Insurrection

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#1426]
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

China, as well as its warlord puppets, haven't rejoined the Sphere long after the Western Insurrection

### Steps to reproduce / Cause of the issue

Pretty self explanatory

### Expected behaviour

China rejoins the Sphere

### Screenshots

![Uploading Hearts of Iron IV (DirectX 11) 17_11_2022 9_52_21 PM.png…]()

**Comment by Chewy598** [comment]
![Hearts of Iron IV (DirectX 11) 17_11_2022 9_52_21 PM](https://user-images.githubusercontent.com/59920852/202428053-cfec2238-c4e9-4b0b-9857-3a19a78be9b1.png)

**Comment by runelead00** [comment]
Should be fixed in current release
