### ISSUE TITLE
MAG - Werbell "A Global Reach" Focus Issue

### ISSUE THREAD

**Issue by HighMountainGuy** [TNODevs/TNO-Bug-Tracker#1427]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Do you have other mods in use?

The New Order: VT323 Map and Cities Font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

X

### Describe the bug

After taking "A Global Reach" As Werbell Siberia, ~~you don't have the ability to send volunteers to anyone regardless of what the tooltip implied because of a "We have no reason to get involved" flag [EDIT] Via the mercenary contracts mechanic, which is currently not available for the Colombia War nor the South Africa War~~ you don't have the ability to intervene on either side of the Colombian- and South African Wars

### Steps to reproduce / Cause of the issue

1. Werbell Magadan
2. Take "A Global Reach"
3. Attempt to send volunteers in the South Africa War to the OFN side/any proxy [EDIT] Via the mercenary contracts mechanic, which is currently not available for the Colombia War nor the South Africa War

### Expected behaviour

Sending volunteers to South Africa and Colombia during their wars should be possible

### Screenshots

![image](https://user-images.githubusercontent.com/71605887/202538975-b704ccba-be8a-4cce-8e10-aa9786eb19e2.png)

![image](https://user-images.githubusercontent.com/71605887/202541263-339038a3-1f78-43ec-b29f-9257c67d19d2.png)

![image](https://user-images.githubusercontent.com/71605887/202541513-14018890-c180-4b5a-8894-b74d453cdd84.png)

### Additional information

X

**Comment by runelead00** [comment]
Fixed in Dev Build by Yugo
