### ISSUE TITLE
USA-Crashes after taking Madagascar

### ISSUE THREAD

**Issue by friggityfrag** [TNODevs/TNO-Bug-Tracker#143]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.5
- TNO Version: 1.2.0
- Any other mods in use: Kamchatka submodel, Last Waltz, TNO Landmarks, TNO Ship Names, VT323 map font, Radio TNO, TNO Reskins
- Were you using Steam? yes
- Which expansions do you NOT have? no step back

**Longer Description of Issue:**
Game CTD after capitulating the Republic of Madagascar as Madagascar Government
**Steps to Reproduce/Cause Issue:**

1. Play as normal until Madagascar civil war

2. Capitulate the last remaining enemy

**Comment by runelead00** [comment]
Issue no longer occurs on current builds of TNO, likely fixed in early TT hotfixes
