### ISSUE TITLE
Every country Missile are broken

### ISSUE THREAD

**Issue by Starco77** [TNODevs/TNO-Bug-Tracker#1430]
### Operating System

winsdow 10

### HOI4 version

1.12.4

### TNO version

v1.3.0d "Toolbox Theory - Unfinished Business Patch D

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Missile cant be moved from base to base nor can do anything also there number are capped by the airbase 

### Steps to reproduce / Cause of the issue

1. Select any country with missile
2. Select an airbase
3. Try to create a missile airwing or to do something with present missile airwing

### Expected behaviour

Thats missile can be used as regular airwing like before ![](https://cdn.discordapp.com/attachments/806276324297539586/1043104517354438746/image.png)

### Screenshots

![](https://cdn.discordapp.com/attachments/806276324297539586/1043104517354438746/image.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
