### ISSUE TITLE
Winning proxy war as lbj give republican support instead of democratic support

### ISSUE THREAD

**Issue by Starco77** [TNODevs/TNO-Bug-Tracker#1431]
### Operating System

winsdow 10

### HOI4 version

1.12.4

### TNO version

v1.3.0d "Toolbox Theory - Unfinished Business Patch D

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When you win a proxy war as lbj you gain republican support instead of democratic

### Steps to reproduce / Cause of the issue

1.Play as the usa
2.Get Lbj elected
3.Win a proxy war (SAF, indonésian, colombian, west africa.

### Expected behaviour

I'll expeted that since Jumbo is now a democrat and not a republican the democrat get support for jumbo victory

**Comment by runelead00** [comment]
Fixed in Dev Build
