### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by GRANDMASTUR** [TNODevs/TNO-Bug-Tracker#1432]
### Operating System

Ubuntu 22.10

### HOI4 version

Avalanche v.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10046597/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10046602/game.log)

### Describe the crash

It loads till ~75%, and then crashes.

### Steps to reproduce / Cause of the crash

Use OpenGL, use Ubuntu, use Steam, launch TNO while having modified the GUI scale to either 0.9 or 0.8

**Comment by runelead00** [comment]
Merged into #961
