### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Thebugmen** [TNODevs/TNO-Bug-Tracker#1434]
### Operating System

64-bit operating system, x64-based processor

### HOI4 version

v1.12.5.b273

### TNO version

 Last Days of Europe - v1.3.0d “Toolbox Theory - Unfinished Business”

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, BBA

### Files

I really don't know.

### Describe the crash

Once you select your country and enter the game, the Mod just crashes to desktop, making it unplayable.

### Steps to reproduce / Cause of the crash

I think this is just an individual problem, but heres how it usually goes.
1.Enter the game.
2.Select your nation.
3.Opens for around about 1-3 seconds.
4.Freezes temporarily before crashing.

**Comment by runelead00** [comment]
Merged into #962
