### ISSUE TITLE
Country Affected - Short Description othe entire economy of the game is busted

### ISSUE THREAD

**Issue by frontierplay** [TNODevs/TNO-Bug-Tracker#1435]
### Operating System

windows 11 home

### HOI4 version

v1.12.5.b273

### TNO version

Last Days of Europe - v1.3.0d “Toolbox Theory - Unfinished Business”

### Do you have other mods in use?

the music submod, the text graphic and night graphic

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I have no idea what your talking about

### Describe the bug

1. Canada is literally in the worst state with GDP growth
2. the top 1- shows random nations and not the real ones literally there

### Steps to reproduce / Cause of the issue

literally the second you start the game

### Expected behaviour

with the main 10 there and a normal economy for most nations

### Screenshots

![20221120181915_1](https://user-images.githubusercontent.com/91399590/202932341-dadade5f-e063-48f2-afeb-c61e0f908f28.jpg)
![20221120181827_1](https://user-images.githubusercontent.com/91399590/202932344-86061a79-90cb-4d97-ab98-456fa2c9d381.jpg)

### Additional information

really REALLY need the economy to fixed

**Comment by runelead00** [comment]
Fixed in Dev Build
