### ISSUE TITLE
USA-RFK - Rally the Progressives Democrat break

### ISSUE THREAD

**Issue by J4xx0n** [TNODevs/TNO-Bug-Tracker#1436]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Do you have other mods in use?

Some music mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

RFK, going for Glorious Bill.

Senate is 20R, 27D, 27P, 24N. Taking A Necessary Sacrifice changes it to 20R, 29D, 27P, 24N.

Taking the focus Rally the Progressives after A Necessary Sacrifice will break the temporary coalition and make it impossible to March Straight Forward. Taking A Necessary Sacrifice second allows March Straight Forward.

### Steps to reproduce / Cause of the issue

1. Elect RFK
2. Take Across the Aisle
3. Take Rally the Progressives
4. Take A Necessary Sacrifice
5. Take With Malice Towards None
6. Unable to take March Straight Forward

### Expected behaviour

A coalition of 29 Democrats and 27 Progressives have the majority in the senate to March Straight Forward and pass a radical CRA.

### Additional information

May be because of the senator change from Robert F. Kennedy, Cat Herder, which swaps two N senators into D senators.

Also the senate doesn't update after A Necessary Sacrifice, showing that I still have an NPP majority in the senate despite it being 49RDC-49NPP after two of the Nationalists swapped sides.

Also might have to do with the South Africa War concluding but I doubt it. 

Haven't been able to get the Glorious Bill with The Party Above All path either despite that I should be able to.

**Comment by runelead00** [comment]
Hopefully should be fixed in Dev Build now
