### ISSUE TITLE
All countries - Strange Red Coloring around all the models.

### ISSUE THREAD

**Issue by Bruh431** [TNODevs/TNO-Bug-Tracker#1438]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

Radio of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10078062/error.log)

### Describe the GFX issue

There is a strange, annoying, laser-like coloring around all 3d models that looks like they are heating up or something.

### Steps to reproduce / Cause of the issue

1. Turn on any, some, or all 3d model types
2. You will see a strange red coloring comprised of a bunch of what I believe to be tiny dots.
3. I have no idea what is causing it.

### Expected behaviour

I expected there not to be a strange red coloring around all 3d models

### Screenshots

![Screenshot (16)](https://user-images.githubusercontent.com/106832587/203618714-c20f7aa3-74d0-4aa2-9297-4b10e8b1b02f.png)

**Comment by runelead00** [comment]
I'd recommend trying without all the mods you're using first, because the error log indicates your using more mods than you listed
