### ISSUE TITLE
Puerto Plata invasion

### ISSUE THREAD

**Issue by tuantai50** [TNODevs/TNO-Bug-Tracker#1441]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Germany or USA (player controlled) win Puerto Plata invasion but in the cold war tab still says "ongoing"

### Steps to reproduce / Cause of the issue

- Win the Puerto Plata invasion as Germany or USA
- Check the Cold War tab

### Expected behaviour

Described above

**Comment by runelead00** [comment]
Fixed in Dev Build hopefully
