### ISSUE TITLE
Scotland - Election decisions show the wrong state names

### ISSUE THREAD

**Issue by RustJafar** [TNODevs/TNO-Bug-Tracker#1443]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD

### Describe the bug

In Scotland election decisions, the name of some states do not match the name of states on the map. For the 2 cases in which this applies, the state of "Lanark" in the decision menu matches the state of "Strathclyde" on the map, and the state of "Dumfries" in the decision menu matches the state of "Lanark" on the map. This is especially confusing as the state of "Lanark" in the decision menu does not match the state of "Lanark" on the map.

### Steps to reproduce / Cause of the issue

1. Begin game as Scotland
2. Continue until elections start
3. Compare states names in the election decisions and map

### Expected behaviour

Election decisions would include the states of Strathclyde and Lanark with accurate election statistics.

**Comment by runelead00** [comment]
Fixed in Dev build
