### ISSUE TITLE
USA - Gun Control Act of year is missing in text

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#1445]
### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB, BBA

### List the loc issues below

![Screenshot (194)](https://user-images.githubusercontent.com/84231463/204671460-4cbbd9c8-1258-4f64-84ac-9db55549b4b2.png)

"At the Presidents request, officials in congress today introduced the Gun Control Act of .", should be including the year (1972)
Must be missing code for the year.

**Comment by runelead00** [comment]
Fixed in Dev Build
