### ISSUE TITLE
USA - Goldwater is called a Democrat, not Republican 

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#1446]
### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB, BBA

### List the loc issues below

![Screenshot (199)](https://user-images.githubusercontent.com/84231463/204672640-76638f2f-cfb8-4c8f-b8bd-bc62fbda580c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
