### ISSUE TITLE
South africa -Deploy fighter squadron decision send fighter to the usa 

### ISSUE THREAD

**Issue by Starco77** [TNODevs/TNO-Bug-Tracker#1447]
### Operating System

windows 10

### HOI4 version

1.12.6

### TNO version

v1.3.0d "Toolbox Theory - Unfinished Business Patch D"

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Deploy fighter squadron decision send fighter to the usa 

### Steps to reproduce / Cause of the issue

1.Play south africa 
2.wait until the war
3.do the air and naval support focus
4. Look at the description of Deploy fighter squadron 

### Expected behaviour

I would like to gain those fighter instead yo give them to the us

### Screenshots

![image](https://user-images.githubusercontent.com/96116742/204799728-39e1e096-96e1-4282-a4c2-a764f0d8ace0.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
