### ISSUE TITLE
[Bug]: Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by SamsungSama** [TNODevs/TNO-Bug-Tracker#1448]
### Operating System

Windows 11

### HOI4 version

1.12.5

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Isle of Man has Jewish-Levantine Arab culture, I don't think that's right

### Steps to reproduce / Cause of the issue

1. Click Isle of Man
2. Read the culture

### Expected behaviour

Manx or British

### Screenshots

![6834b321c3aa1c88671834fd4af6f4e3](https://user-images.githubusercontent.com/119552059/204952869-7b666bfa-4b59-48ae-84d2-d5d381bd717a.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
