### ISSUE TITLE
germany/poland - when doing focus "poland lost again?" germanys party ideology will change instead of polands

### ISSUE THREAD

**Issue by cherryninja492** [TNODevs/TNO-Bug-Tracker#1449]
### Operating System

wiindows 11

### HOI4 version

1.12.5

### TNO version

v1.3.0d? I think thats correct

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Germanys ideology will change instead of polands I am assuming this is not meant to be the case

### Steps to reproduce / Cause of the issue

Just play through the path?

### Expected behaviour

I would assume that Poland's ideology is meant to change as to make otto kuhm the leader of the country instead of germany as it results in germany having no leader portrait

### Screenshots

![image](https://user-images.githubusercontent.com/119579211/205008253-761719a5-51df-487a-8c83-8ab48974985e.png)
![image](https://user-images.githubusercontent.com/119579211/205008512-cea9f19a-ab4a-4c63-aaf3-2051e77dfbbb.png)

### Additional information

This is my first time writing something like this so I do not know if this is the correct place to put something like this sorry if its not.

**Comment by runelead00** [comment]
Fixed in Dev Build
