### ISSUE TITLE
Hart USA- Hart senate bill decisions do not work for the Muncipality Housing Act

### ISSUE THREAD

**Issue by Jaggedmallard** [TNODevs/TNO-Bug-Tracker#1450]
### Operating System

Windows 10

### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

The "Chop and Pray" and "Pay the Price" decisions in the Hart mechanics do not change votes in any direction when voting on the Municipality Housing Act. They should increase votes from the relevant party while reducing it for the other. At present the button does not do this.

### Steps to reproduce / Cause of the issue

1. Start a Hart presidency.
2. Advance his focus tree till you vote on the muncipality housing act (Never Too Much) focus
3. Click Chop and Pray or Pay the Price
4. Votes will not change

### Expected behaviour

Votes to go up for one/two parties and decrease for one other.

**Comment by runelead00** [comment]
Should be fixed in dev build now according Mango
