### ISSUE TITLE
Hart USA- Typo in Riding High Event 

### ISSUE THREAD

**Issue by Jaggedmallard** [TNODevs/TNO-Bug-Tracker#1451]
### HOI4 version

1.12.5

### TNO version

1.3.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### List the loc issues below

Missing character from event "Riding High", there should be what I presume is an I at the start of the fourth paragraph.
![image](https://user-images.githubusercontent.com/4210279/205447356-9d408531-37c2-4c22-8dc8-529665c8cca3.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
