### ISSUE TITLE
Vyatka - Missing Quotations

### ISSUE THREAD

**Issue by Kurgis** [TNODevs/TNO-Bug-Tracker#1452]
### HOI4 version

1.12.5

### TNO version

1.3.0b

### Do you have other mods in use?

Last Waltz of Europe

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### List the loc issues below

![TNO_localization_Vyatka](https://user-images.githubusercontent.com/35203040/205483290-232afc82-aa77-4b65-b38c-a34945d409b2.png)

### Additional information

Missing a few quotation marks.

**Comment by runelead00** [comment]
Fixed in Dev Build
