### ISSUE TITLE
Bormann germany - get no event about annexing/tag switching to germania

### ISSUE THREAD

**Issue by Sardinedealer** [TNODevs/TNO-Bug-Tracker#1454]
### Operating System

Windows 10

### HOI4 version

1.12.6

### TNO version

1.3.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[bugged autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10151295/bugged.autosave.zip)

### Describe the bug

When i won the civil war and was going to tag switch/annex germania the game crashed, i started the game up again only to find that whenever i would load the autosave i would get no event about annexing germania

### Steps to reproduce / Cause of the issue

i think it will be replicated by:
1. play as bormann germany
2. win the civil war
3. the moment you win the civil war (when the message pops up that the last contender has capitualted) create a save 
4. continue as usual 
5. during the tag switch after you get the event about germania you close the game (not sure if needed)
6. load save and there will be no event about annexing/tag switching germania

either that or load the save i put in and just continue playing until you are supposed to get the event

### Expected behaviour

for me to get an event about getting germania/becoming the victor of the civil war

### Screenshots

![image](https://user-images.githubusercontent.com/113440974/205570244-19eaf274-3fc6-49f1-ab7c-08a2e8ce9224.png)
![image](https://user-images.githubusercontent.com/113440974/205570427-b359cbee-bbeb-48b9-83ee-e8e59784e40f.png)

### Additional information

screenshot 1 - bormann germany without tag switching to germania
screenshot 2 - how it looks after loading the autosave

**Comment by runelead00** [comment]
Sometimes when you save a game, events meant to trigger almost immediately after will just not appear. Paradox issue, just don't save and reload immediately after GCW before the tag switch
