### ISSUE TITLE
Italy - unable to interact in the proxy wars in Oil crisis

### ISSUE THREAD

**Issue by Jaykey-Soldier** [TNODevs/TNO-Bug-Tracker#1457]
### Operating System

Windows 10

### HOI4 version

v1.12.7.8fc8

### TNO version

V1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, NSB

### Files

I Can't send the save.

### Describe the bug

During Oil crisis, i couldn't send volunteers (Not certain if that is standard). The standard proxy war buttons didn't do anything but the bombing campaign which did work. Buttons to increase volunteer percent did nothing, sending guns or men didn't give them anything and didn't take anything off me. The increase war tier option gave more options that didn't do anything like giving trucks and i couldn't press the send an Italian Division button as it said "egypt needs to control the egypt province." And outlined Cairo, despite egypt owning the whole of its capital it didn't allow me to press it.

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Go with Ciano and become more democratic
3. Win both the levantine war and Algerian War
4. Facists win the 1965 Election
5. Win Both Great Games
6. Conservatives win 1969 Election, side with Facists
7. Finish the Riots after bombing
8. Oil crisis begins

### Expected behaviour

To be able to change what happens in the oil crisis

### Screenshots

![BUGPicture2](https://user-images.githubusercontent.com/120320679/207086773-6e59cdde-0401-414d-a2d2-c4ac26122524.png)
![BUGPicture1](https://user-images.githubusercontent.com/120320679/207086806-b504600c-e33f-417a-804b-cdd0848507e1.png)

### Additional information

I got couped during the oil crisis, so the game ended.

**Comment by Angelblue1852** [comment]
Issue still exists in Patch 1.4.1c.
