### ISSUE TITLE
USA - Progressive and Nationalists never have named leaders

### ISSUE THREAD

**Issue by SiegleJ798** [TNODevs/TNO-Bug-Tracker#1460]
### Operating System

Windows 11

### HOI4 version

1.12.7

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230598/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230599/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230600/code_revisions.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230601/executed_commands.log)
[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230602/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230603/message.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230604/posted_commands.log)
[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230605/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230606/sent_commands.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230607/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230608/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230609/time.log)
[random_2.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230610/random_2.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230611/graphics.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230612/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230613/system.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230614/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230615/game.log)
[Uploading random.log…]()
[random_1.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10230617/random_1.log)

### Describe the bug

In events that describe the progressives and nationalists picking a leader, no leader is chosen. Where the leaders name would be, there is literally nothing, not even empty spaces

### Steps to reproduce / Cause of the issue

Playing up to Bennent, noticed this over election cycles.

NPP was fairly popular, had majority of senate at the last occurence.

### Expected behaviour

I thought some name would be there

**Comment by runelead00** [comment]
Fixed in Dev Build by Mango
