### ISSUE TITLE
Goering's Germany - Crash after civil war

### ISSUE THREAD

**Issue by asdfer-1234** [TNODevs/TNO-Bug-Tracker#1462]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

1.3.0

### Do you have other mods in use?

=none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250497/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250498/sent_commands.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250499/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250500/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250501/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250502/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250503/time.log)
[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250504/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250505/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250506/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250507/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250508/executed_commands.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250509/game.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250511/graphics.log)
[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250512/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250513/message.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250514/posted_commands.log)
[random.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10250515/random.log)

Save File
https://drive.google.com/file/d/1L-3PlNL7yyVUT3RVmwJYQB-q6CDpgO7o/view?usp=sharing

### Describe the crash

Crashes after a short time the german civil war eends

### Steps to reproduce / Cause of the crash

1. Play the savegame

### Additional information

Did two runs, Both crashed

**Comment by runelead00** [comment]
Should be fixed in new hotfix
