### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Dart52000** [TNODevs/TNO-Bug-Tracker#1463]
### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR

### List the loc issues below

The humanist part of the political pie chart for Tomsk is labeled as Gumanistry
![image](https://user-images.githubusercontent.com/57198044/208222170-c5529e81-7706-4a2d-b863-f427cab6758c.png)

**Comment by runelead00** [comment]
It's just in Russian
