### ISSUE TITLE
CAF-Wrong economic model

### ISSUE THREAD

**Issue by YanSGod** [TNODevs/TNO-Bug-Tracker#1469]
### Operating System

Windows11

### HOI4 version

1.12.5

### TNO version

1.3.0c

### Do you have other mods in use?

NO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The socialism Bafrikan Republic still remains free market capitalism

### Steps to reproduce / Cause of the issue

After socialism congo conquered Central African Republic

### Expected behaviour

change it's economic policy to planned economy

### Screenshots

![QQ截图20221223150838](https://user-images.githubusercontent.com/99068464/209289756-2de34ec4-fa34-4f9d-a06b-3045d67aa962.png)

**Comment by YanSGod** [comment]
Also i think the country flag should be changed to be more socialism

**Comment by runelead00** [comment]
Fixed in Dev Build by Yugo
