### ISSUE TITLE
Brazil - south africa war decision to sell apcs instead buys apc

### ISSUE THREAD

**Issue by Ertridj** [TNODevs/TNO-Bug-Tracker#147]
**Questions**

- Operating System:
- HOI4 Version: newest
- TNO Version: newest
- Any other mods in use: none
- Were you using Steam? yes
- Which expansions do you NOT have? Bosphorus

**Longer Description of Issue:**
Brazilian south africa war decision: Sell Armoured Personal Carriers
has the same effects as the buy APC decision

**Steps to Reproduce/Cause Issue:**

1. Play up to south africa war

2. complete all south africa war focuses

3. take decision to "Sell Armoured Personal Carriers"

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
