### ISSUE TITLE
RFI - can't get the finland's core

### ISSUE THREAD

**Issue by YanSGod** [TNODevs/TNO-Bug-Tracker#1470]
### Operating System

Windows11

### HOI4 version

1.12.5

### TNO version

1.3.0c

### Do you have other mods in use?

NO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The red Finns that won the civil war could not get the core of the country

### Steps to reproduce / Cause of the issue

supporting the RFI won the civil war with international column .

### Expected behaviour

RFI should grt finlan's cores

### Screenshots

![QQ截图20221223152416](https://user-images.githubusercontent.com/99068464/209291921-aaa9a8ad-3fc6-460e-b07e-bb4f4f70453e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build by Sonij
