### ISSUE TITLE
Nowa Polska and Kazachstan

### ISSUE THREAD

**Issue by kirbusiland** [TNODevs/TNO-Bug-Tracker#1473]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

Toolbox Theory 3 Update Unfinished Business

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

after unifying Kazakhstan, nowa polska had set up aktobe protectorate and progressive Kazakhstan as intended, however it declared war on the progressive Kazakhstan and it shouldn't

### Steps to reproduce / Cause of the issue

1. Set game rule so Nowa Polska would unify kazakhstan
2. In my game, kyzylorda (now kazakh ssr) unified almost all kazakhstan except nowa polska
3. Nowa Polska has beaten kazakh srr
4. It declared war on progressive kazakhstan which appeared after it unified

### Expected behaviour

Nowa Polska unifying kazakhstan and not declaring war on the progressive kazakhstan

### Screenshots

![image](https://user-images.githubusercontent.com/121460994/209783826-6e5110d4-6a16-4832-86a7-57c45510df3b.png)
that how it looks after it defeated progressive kazakhstan

**Comment by runelead00** [comment]
Should be fixed in dev build now
