### ISSUE TITLE
NOV Wrong event (Event should appear in KOM)

### ISSUE THREAD

**Issue by Iron16** [TNODevs/TNO-Bug-Tracker#1474]
### Operating System

Win10

### HOI4 version

1.12.6

### TNO version

v1.3.0d “Toolbox Theory - Unfinished Business”

### Do you have other mods in use?

Brave New World (New workshop version Hotfix #17)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

DOD, WTT

### Describe the bug

In Avgust 1962 play as NOV shows wrong event what change your focus tree to Komi's libdem tree

### Steps to reproduce / Cause of the issue

I dunno, maybe just find error in event's files (i tried)

### Expected behaviour

event writing error

### Screenshots

![image](https://user-images.githubusercontent.com/59249930/210335861-064a8596-5d1f-404c-9ad3-fae5ac0bbef8.png)
![image](https://user-images.githubusercontent.com/59249930/210335903-83e6a31f-1ce6-4a66-813d-bc3afffa8f05.png)

**Comment by runelead00** [comment]
Issue with BNW, do not report here, Most likely an issue with corruption that happened with their hotfix releasing from the looks of it, a restart should fix any issues
