### ISSUE TITLE
USA - West Africa War doesn't end after Free France and their friends fall

### ISSUE THREAD

**Issue by nimnumoi** [TNODevs/TNO-Bug-Tracker#1475]
### Operating System

Windows 11

### HOI4 version

1.12.8

### TNO version

1.3.0d

### Do you have other mods in use?

TNO but everyone has shades

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10346042/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10346043/error.log)

### Describe the bug

The West Africa War doesn't end after FF and their ally's fall. I was playing as Wallace USA, and only did the left side of 'fighting tyranny since 1776', 'foreign business' and 'abroad' trees. The war ended a while ago, and I still have the West Africa War page on global conflicts.

### Steps to reproduce / Cause of the issue

1. Play as USA
2. Lose all interventions except Philippines
3. Elect Wallace and do the focus tree branches mentioned above
4. Don't do anything in West Africa War
5. Thats what happened to me, I only realized because I got an event about the war not ending after two years.

### Expected behaviour

Once FF falls, get an event saying I failed and remove the page from my decisions.

### Screenshots

![20230104111223_1](https://user-images.githubusercontent.com/121966327/210611432-26734c43-ee49-41d6-a918-e9f13b084251.jpg)

### Additional information

You can see that the West African War page is still there, a year after Free France and their allies collapsed.

**Comment by runelead00** [comment]
Should be fixed for SD by Oveja
