### ISSUE TITLE
NOV - Artillery GFX displaying as generic artillery

### ISSUE THREAD

**Issue by Arthanol** [TNODevs/TNO-Bug-Tracker#1476]
### Operating System

Windows 10

### HOI4 version

1.12.7.8fc8

### TNO version

1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

WTT, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10347759/error.log)

### Describe the GFX issue

In certain Russian tags, artillery related GFX is displaying as generic artillery despite it showing as a D-20 howitzer for example in the tech tree. This seems to apply to all central Siberian warlords, Irkutsk, Sverdlovsk, and Omsk. This also applies to Anti-Air.

### Steps to reproduce / Cause of the issue

1. Play as central siberian warlord
2. go to production screen, assign production units
3. wait for production units to assign
4. Go to infantry/artillery equipment dropdown
5. see the generic gfx

### Expected behaviour

Seeing non-generic tech icons in production screen

### Screenshots

![bugimage](https://user-images.githubusercontent.com/121981502/210657504-60a83c89-ff72-4a43-bdc0-42029d2da2ca.png)

### Additional information

Did initially detect this problem when playing Brave New World codetalker but tried again with only TNO and problem persisted.

**Comment by runelead00** [comment]
Fixed in Dev Build
