### ISSUE TITLE
United States - Irregular ARPA funding

### ISSUE THREAD

**Issue by Take-On-Will** [TNODevs/TNO-Bug-Tracker#1477]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

1.3.0d

### Do you have other mods in use?

Kamchatka Reloaded, Radio TNO: Music of the New Order, The New Order: Last Waltz Expanded, TNO: CIA, TNO: Lullabies Of Europe, ToolPakt: Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Picking the option to give ARPA maximum funding is far more expensive than is stated. (About 15 billion dollars higher).

### Steps to reproduce / Cause of the issue

1. Playing as the USA, elect Lyndon B. Johnson
2. Complete the focus ARPA Funding
3. Pick the option to give ARPA maximum funding
4. Check your economy screen

### Expected behaviour

The event says that giving ARPA maximum funding should add a $0.04B dollars miscellaneous cost to the US economy (Rather than than slightly exorbitant ~$15.00B dollars my economy screen shows)

### Screenshots

![Screenshot (62)](https://user-images.githubusercontent.com/53916048/210659867-45324b4f-eee6-45c1-a0ad-d34a5ad1b4cc.png)
![Screenshot (64)](https://user-images.githubusercontent.com/53916048/210659892-b6eb62ed-b7e2-495d-a63f-bdf8efd31853.png)
![Screenshot (65)](https://user-images.githubusercontent.com/53916048/210659908-73368701-92d6-4c92-99b0-6a5c9bc1c848.png)

### Additional information

Military Spending: $32B
Civilian Spending: $30B
Debt Servicing: $4B
Other: $6B
ARPA FUNDING: $15B

someone good at the economy please help me budget this. my great society is dying

**Comment by runelead00** [comment]
Fixed in Dev Build
