### ISSUE TITLE
Morocco - Core misplacement

### ISSUE THREAD

**Issue by Alae423** [TNODevs/TNO-Bug-Tracker#1479]
### Operating System

10

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

i was playing as italy , as i notice after italian victory in algerian war , both algerian mandate , and republic of algeria gain core over city of oujda , in game files , "1151-MorroccanState2" , i hadn't found anylore related reason for such claim , nor anything base on real life claim of city , furthermore culture of city should be "Moroccain"

### Steps to reproduce / Cause of the issue

1-win algerian war as italy 

### Expected behaviour

core should be own only by Morocco 

### Screenshots

![Capture DS](https://user-images.githubusercontent.com/122237990/211224150-c1c09e34-cae6-4955-8abb-2e253010468d.JPG)

### Additional information

to fix issue , you can simply remove the "add_state_core = 1151" , from event ILG.7 , from file TNO_Italian_Algeria

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
