### ISSUE TITLE
France - STATE_1611 "Poitou Charentes" state name isn't accurate

### ISSUE THREAD

**Issue by Cozvijar** [TNODevs/TNO-Bug-Tracker#148]
**Description of Suggestion:**
The current "Poitou-Charentes" state area in mainland France isn't related at all with its name and should likely be renamed "**Périgord**" (historical province covering the majority of the in-game state) or "**Guyenne**" (another historical province with its western section covering all of the in-game area).

**Reasoning Behind Suggestion:**

"Poitou-Charentes was the name of a french region until 2015, which covered a majority of the current "Poitou" state area. (See maps) 

**Additional Information:**
![wrong name](https://user-images.githubusercontent.com/94767571/142745196-12368d50-f6d2-4c55-998b-928fcc09d26d.png)
![actual poitou charentes](https://user-images.githubusercontent.com/94767571/142745218-82429ac9-3f54-41eb-9b6a-a229cc70e2ff.jpg)
![guyenne](https://user-images.githubusercontent.com/94767571/142745257-66540cb1-9296-4cbd-94c2-c11c76f4a92f.png)

**Comment by Stormeagle449** [comment]
Fixed in UB.
