### ISSUE TITLE
Multiple Nations Affected - After Bug Fix Update, Multiple Cultures Do Not Have Icons

### ISSUE THREAD

**Issue by Dagemelior** [TNODevs/TNO-Bug-Tracker#1481]
### Operating System

Windows 7 Ultimate

### HOI4 version

1.12.5

### TNO version

1.3.0e

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Multiple cultures do have either the crying emoji icon, or a "neon" version. Some states do not display cultures. This is as a result of the update a few minutes ago

### Steps to reproduce / Cause of the issue

1. Open TNO
2. Click some states in Arabia or Europe

### Expected behaviour

I expected to have culture icons for these states

### Screenshots

![IMG-20230113-WA0020](https://user-images.githubusercontent.com/96637002/212426574-b58e51e5-8526-4827-8b15-eee2faa2c950.jpeg)
![IMG-20230113-WA0014](https://user-images.githubusercontent.com/96637002/212426579-c899a819-7240-479c-9310-5e49ab8a7e82.jpeg)
![IMG-20230113-WA0016](https://user-images.githubusercontent.com/96637002/212426585-c03d14cc-f0ee-4c71-b707-ddcc3d7ee762.jpeg)

### Additional information

Here are the ones I have found

**NO CULTURE**
Westmark - Germany
Lothringen - Germany
Magdeburg-Anhalt - Germany
Halle-Merseburg - Germany
Shitomir - Ukraine

**CRYING EMOJI ICON**
JAZIRAN ARAB
Baghdad - Iraq
Ramadi - Iraq
Northern Desert - Iraq
Southern Desert - Iraq

BADAWI ARAB
Gaza - Levant Governorate
Araba - Levant Governorate
Negeb - Levant Governorate
North Sinai - Levant Governorate
South Sinai - Levant Governorate
Al Bahr Al Ahmar - Egypt
Eastern Desert Plateau - Egypt

SA'IDI
Upper Egypt - Egypt
Aswan - Egypt
New Valley - Egypt
Western Desert - Egypt

BAHRAINI ARAB 
Bahrain - Gulf Governorate

DHOFAR ARAB
Dhofar - Oman
Al Mahrah - Yemen

**NEON CRYING EMOJI ICON**
There is only one culture that applies here, and that is Mazandarani, only present in the state of Mazandaran, in Iran. This has been an issue since before the bug fix, perhaps since before Unfinished Business. I have not reported this previously since I did not know how to.

I hope this information is sufficient

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
