### ISSUE TITLE
[Bug]: Governatorato del Levante lives on in Safed

### ISSUE THREAD

**Issue by vipersniper2001** [TNODevs/TNO-Bug-Tracker#1482]
### Operating System

Win11

### HOI4 version

1.12.5

### TNO version

1.3.0e

### Do you have other mods in use?

VT323 font and music submods

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Governorate of the Levant lives on in Safed after a communist uprising in the Levant

### Steps to reproduce / Cause of the issue

Turkish victory in War in the Desert and communist revolution following failed Jerusalem Conference

### Expected behaviour

No more Governorate of the Levant

### Screenshots

![20230113175148_1](https://user-images.githubusercontent.com/115953733/212434107-69f8bc44-523d-48fd-9a33-46cb5d9dcb24.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build by Avata
