### ISSUE TITLE
Missing loc for various German cities

### ISSUE THREAD

**Issue by itsandyru** [TNODevs/TNO-Bug-Tracker#1483]
### HOI4 version

Avalanche 1.12.7

### TNO version

Unfinished Business 1.3.0e

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

When clicking on the state lore for Danzig, Königsberg, Breslau, Litzmannstadt, Leipzig, Dresden, Hannover, Dortmund, Essen, Düsseldorf, Köln, Stuttgart and Wien, none show the proper lore and just have “placeholder text” instead

**Comment by Stormeagle449** [comment]
Fixed in Silicon Dreams.
