### ISSUE TITLE
USA - Opposing party campaigns affect the wrong region

### ISSUE THREAD

**Issue by asbestoseater1963** [TNODevs/TNO-Bug-Tracker#1485]
### Operating System

Windows 10

### HOI4 version

1.12.8

### TNO version

1.12.8

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Opposing party's campaigns affect different regions than they had campaigned in

### Steps to reproduce / Cause of the issue

1. Select USA
2. Choose RDC/NPP when selection is given
3. Run a campaign
4. Your campaign's results will apply to the region you chose, while the other party's will apply to a region other than the one they campaigned in

### Expected behaviour

The opposing party's campaigns will affect the area in which they were previously running it in

### Screenshots

![image](https://user-images.githubusercontent.com/122656930/212447567-19ad7ed8-29c4-47eb-b673-4033e8113580.png)

**Comment by runelead00** [comment]
Just a Loc Issue, fixed in Dev Build. Title is region it's affecting, tooltip is next campaign region
