### ISSUE TITLE
CAO&FFR - Some bugs in the West African war

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#1486]
### Operating System

Windows10

### HOI4 version

1.12.7

### TNO version

v1.3.0e

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

1.Trigger WAA vs FMA vs PALF
When the FMA wins, the US and Japan cannot gain or reduce score
2.Trigger FMA vs PALF
When the PALF wins, could not trigger the PALF victory event

### Steps to reproduce / Cause of the issue

Trigger WAA vs FMA vs PALF,make FMA wins
Trigger FMA vs PALF,make PALF wins

### Expected behaviour

Make West African war normal

### Screenshots

![20230114125755_1](https://user-images.githubusercontent.com/46292981/212457295-bce1b5ce-07d3-4492-9fcc-e6ca016c40df.jpg)
![20230114130242_1](https://user-images.githubusercontent.com/46292981/212457322-585092c0-2555-4eff-a95a-bb689b501380.jpg)
![20230114130307_1](https://user-images.githubusercontent.com/46292981/212457323-e1d52f53-627e-49c3-bb12-6e2563fcc33c.jpg)

**Comment by runelead00** [comment]
Should be fixed for SD by Oveja
