### ISSUE TITLE
GER- Bormann's Germany does not gain cores on all of Denmark

### ISSUE THREAD

**Issue by Lipad45** [TNODevs/TNO-Bug-Tracker#1487]
### Operating System

Windows 10

### HOI4 version

Avalanche 1.12.4

### TNO version

v1.3.0e

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After annexing Denmark as Bormann's Germany the island of Bornholm did not gain any German cores while the rest of Denmark does gain German cores

### Steps to reproduce / Cause of the issue

1. Win the German civil war as Bormann with Denmark in a postion to become a reichskommissariat
2. Set Denmark as a reichskommissariat and fully intergrate it into Grossraum KontinentalEuropa
3. Annex Netherlands and eventually annex Denmark through the event.
4. You have annexed all of Denmark and have cores on all owned regions except for Bornholm

### Expected behaviour

I would get cores on all of German owned Denmark after integrating Denmark

### Screenshots

![image](https://user-images.githubusercontent.com/88467629/212469368-e4c4279e-36c8-4363-9f6c-8b010007259b.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
