### ISSUE TITLE
Iraq - Jaziran Arab culture got No Culture icon 

### ISSUE THREAD

**Issue by kirbusiland** [TNODevs/TNO-Bug-Tracker#1488]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

v1.3.0e

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

When i clicked on Southern Desert, state in Iraq, the culture icon for this, jaziran arab had the No Culture icon, which is the often used in memes image of a crying emoji thing

### Steps to reproduce / Cause of the issue

1. Click on the Southern Desert or any other Jaziran Arab culture states
2. Look at the culture icon

### Expected behaviour

I expected culture icon to be something normal

### Screenshots

![image](https://user-images.githubusercontent.com/121460994/212482897-e74a1277-e97a-4f66-bc79-77be8eb38a2d.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
