### ISSUE TITLE
USA - Hart Budget variable bug + Immediate bankruptcy crisis

### ISSUE THREAD

**Issue by Ordinarycomet** [TNODevs/TNO-Bug-Tracker#1489]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

1.3.0e

### Do you have other mods in use?

No.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Hart's city budget variable is still bugged and from what I can tell is set to get worse when you reduce upkeep, but get better when you increase upkeep. 

Thus when you pass bills and do focuses that reduce upkeep, the mechanic thinks it's actually getting worse, and you also start out with the budget being 'in the red' and thus you immediately get the bankruptcy crisis when you get to Hart. So if you keep reducing the upkeep cost, instead of the loc switching to one of the green options, it switches to the red ones instead. 

And due to the above mentioned issue, you're locked into a negative feedback loop where trying to fix the crisis just makes the issue worse. And since Hart immediately starts out with the bankruptcy crisis, this sets off everything else falling apart. Unless the devs deliberately want you to fail from the start as Hart I'm assuming this is a bug and am reporting it as such.

### Steps to reproduce / Cause of the issue

1. Make Hart president, either via debug or just normally.
2. Immediately look at the URI statistics and at the budget. Trigger events to reduce upkeep and watch as it goes further into the red.
3. View the weekly tick and how it immediately sends you into the bankruptcy crisis with "The Shadow of the wave" event firing after a week.

### Expected behaviour

I expected the Bankruptcy crisis to only be a result of the player failing to manage the city budget, and for reducing the upkeep cost to improve the budget situation, not worsen it. Not for Hart to immediately be thrown into a crisis.

**Comment by runelead00** [comment]
Hart dev couldn't replicate or find a possible cause, Check to make sure if your TNO updated properly for the new hotfix
