### ISSUE TITLE
Every Country: Bizarre red pixels everywhere?

### ISSUE THREAD

**Issue by ThatFuckinGuy** [TNODevs/TNO-Bug-Tracker#149]
**Questions**

- Operating System:
- HOI4 Version: 1.0
- TNO Version:
- Any other mods in use: Just music mods (Youjou Senkai music, Valkyria Chronicles, Last Waltz of Europe, etc.) I had West Russian War on, but I turned it off to see if that was affecting it and upon reentering the game map it still had the same red blob of hell.
- Were you using Steam? Always.
- Which expansions do you NOT have? Only one music mod and one unit model mod (the Eastern front ones). I haven't pre-purchased No Step Back but I don't see how that would induce it.

**Longer Description of Issue:**

Upon entering TNO after TT installed and selecting a country, I was greeted by a fucking nightmare hell of red pixel gore everywhere on the screen. In some countries, all over borders, across the oceans, etc., etc. It's hideous to look at and I can't play like that since it even obscures units.

**Steps to Reproduce/Cause Issue:**

1. Start up TNO

2. Try to select a country, be it one of the ones presented or from the map. It shows up there.

etc...

**Screenshots:**

![what the fuck](https://user-images.githubusercontent.com/94768605/142745292-290bb4a7-fd56-4117-8680-2189da39deec.jpg)

**Comment by ModdingAccount** [comment]
Graphical issue with device; cannot replicate and deduce cause of issue.
