### ISSUE TITLE
CTD on Loading into Game

### ISSUE THREAD

**Issue by LightArcMW** [TNODevs/TNO-Bug-Tracker#1490]
### Operating System

MacOS Monterey

### HOI4 version

1.12.7

### TNO version

v1.3.0e

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Unknown

### Describe the crash

normal launch settings work, I can use everything and then it crashes once I "start" technically, Tried selected scotland/us for example and then it starts, I see the map, then crashes to desktop. I have tried other alternatives such as different countries, still crashes to desktop once setup is done. I checked even without custom setting and just default setting and it still crashes. Im not sure if its a mac specific problem, but have had no issues before with TNO, so I am kind of confused.

### Steps to reproduce / Cause of the crash

1. Start TNO
2. New SinglePlayer Game
3. Default or Custom Setup is fine with crash cause
4. Click Start
5. See welcome note and map
6. Crash to desktop

### Additional information

did download latest DLC as of JAN 14, disabled mod but crashed regardless

**Comment by runelead00** [comment]
Would recommend checking the possible solutions on #962 Cause and proper fix is currently unknown, merging this issue into that one
