### ISSUE TITLE
ANG - Angola still part of Afrika-Schild 

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1491]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

1.3.0e

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10420434/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10420435/error.log)

### Describe the bug

After Angola wins its war for independence (doing the Schenck Angola path), it remains part of the Afrika-Schild faction.

### Steps to reproduce / Cause of the issue

1. Go down free Angola path as Schenck in RK Sudwestafrika.
2. Fight and win the war for independence.

### Expected behaviour

Angola is no longer part of Afrika-Schild after its independence.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/212547098-4dc24a98-d581-4e3d-8cd6-7327ceb5025f.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
