### ISSUE TITLE
Russian Federation - Crash on Startup

### ISSUE THREAD

**Issue by 22goodwinb** [TNODevs/TNO-Bug-Tracker#1492]
### Operating System

Windows 11

### HOI4 version

1.12.7

### TNO version

v1.3.0e

### Do you have other mods in use?

TNO: Brave New World ; Radio TNO 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10421285/error.log)
[TNO_WestAfrica_Crisis_scripted_effects.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/10421292/TNO_WestAfrica_Crisis_scripted_effects.txt)

### Describe the crash

The game crashes about halfway through the loading screen saying that it could not load the map. The error log says that there is an "Invalid scope type for effect set_state_controller in common/scripted_effects/TNO_WestAfrica_Crisis_scripted_effects.txt" on lines 1075, 1525, and 2728.

### Steps to reproduce / Cause of the crash

1. Hit play on steam
2. Activate TNO, TNO: Brave New World. Radio TNO
3. Hit play or resume on HOI4 Launcher
4. Game crashes halfway through loading.

### Screenshots

![Screenshot 2023-01-15 164507](https://user-images.githubusercontent.com/122753777/212568867-4e3f9605-1a1b-47b3-8d78-0edfc00e01d4.png)

**Comment by runelead00** [comment]
BNW is not yet compatible with the most recent hotfix, you cannot play TNO with it enabled currently

**Comment by 22goodwinb** [comment]
> BNW is not yet compatible with the most recent hotfix, you cannot play TNO with it enabled currently

Ah understandable. Any idea when it will be made compatible or is that a separate dev team?

**Comment by runelead00** [comment]
Separate Dev Team, no idea when that will be updated
