### ISSUE TITLE
MAG - Focus to move on to regional tree not locked

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1494]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

1.3.0e

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10427117/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10427120/game.log)

### Describe the bug

Despite not being the only contender left in the Far East, as Magadan I have the ability to advance to the regional tree by selecting the focus that allows me to do so.

### Steps to reproduce / Cause of the issue

1. Play as Magadan and win against the mercenaries in their coup attempt.
2. Look at the new focus tree.

### Expected behaviour

Focus would be locked until I conquered all of the Far East.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/212714119-44315775-33b3-4669-a48b-a4e7fd243056.png)
![image](https://user-images.githubusercontent.com/98370487/212714181-5d0a0a5e-d731-431c-a6fb-14f2c60bca0f.png)

**Comment by runelead00** [comment]
Fixed in Dev Build, that tooltip shouldn't be visible
