### ISSUE TITLE
CAU - Missing portrait

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1495]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

1.3.0e

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10438969/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10438970/game.log)

### Describe the bug

The portrait for Speer's Reichsprotektorat Kaukasien is missing. This is the option for Speer using a firm grip in the East.

### Steps to reproduce / Cause of the issue

1. Be Speer.
2. Go down the option that makes you do a firm grip in the East.

### Expected behaviour

A portrait would show.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/213000546-f5d4fa42-3b22-46fc-aaaf-b9125cd5fca4.png)

**Comment by Stormeagle449** [comment]
This bug should be fixed in current build, did you reload a save from an older version?

**Comment by Blanker389** [comment]
I was definitely on the most recent patch (1.3.0e) and I'm fairly certain I started this game after the patch was released.

> This bug should be fixed in current build, did you reload a save from an older version?

**Comment by runelead00** [comment]
Fixed in Dev Build, code really fucking hated this guy
