### ISSUE TITLE
Samara - CTD on unifying the west

### ISSUE THREAD

**Issue by InEnglishPlease** [TNODevs/TNO-Bug-Tracker#1496]
### Operating System

Windows

### HOI4 version

UB 1.3.0d

### TNO version

Avalanche v1.12.8.fc54

### Do you have other mods in use?

Some music mods and tool pak

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10439722/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10439723/game.log)

### Describe the crash

Samara seems to crash the game a few days after unifying the west. It was despotist so Bunyachenko would have been the successor. I reloaded and ran it a few times, and the crash always occurred less than a week after the unification. Note: this was fairly late into the game, too; second half of 67.

### Steps to reproduce / Cause of the crash

1. Set Bunyachenko as Vlasov's successor.
2. Get him to unify West Russia, possibly hold it off until mid/late 67.

### Additional information

I thought the strangest thing about the run was the three-way West Africa Crisis worked without issue.

**Comment by runelead00** [comment]
Fixed in Dev Build, weird character minister issue that CTDed rather than just giving an error
