### ISSUE TITLE
Italy - Crash at a certain date

### ISSUE THREAD

**Issue by abeaugas** [TNODevs/TNO-Bug-Tracker#1498]
### Operating System

Windows 10 professional

### HOI4 version

1.12.8

### TNO version

1.3.0e

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Error log :
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10449545/error.log)

Game log :
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10449548/game.log)

Save :
[ITA_1966_12_01_02.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10449640/ITA_1966_12_01_02.zip)

### Describe the crash

At 12/06/66, the world event "Samara Unifies West Russia!" fires. At 12/11/66, the game crashes, whatever the player is doing.

### Steps to reproduce / Cause of the crash

1. Load the game
2. Unpause
3. Let the game run / do anything you want
4. Crash

**Comment by runelead00** [comment]
Fixed in Dev Build, weird character minister issue that CTDed rather than just giving an error
