### ISSUE TITLE
Desktop crash as England. 

### ISSUE THREAD

**Issue by IanWigle** [TNODevs/TNO-Bug-Tracker#1499]
### Operating System

Windows 1

### HOI4 version

1.12.8.fc54

### TNO version

1.3.0d

### Do you have other mods in use?

Toolpakt: Toolbox for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10452774/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10452777/game.log)
[ENG_1966_04_09_13.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10452785/ENG_1966_04_09_13.zip)

### Describe the crash

Playing as liberated England, peacefully annexed Wales. Several months later Samara unifies western russia. Several days later game crashes to desktop. 

### Steps to reproduce / Cause of the crash

Load game or play HMMR rebelion. 
Have speer win german civil war.
Peacefully unite with Wales.
Samara unifies western russia.
Crash should occur shortly after.

### Additional information

Although I had the toolbox mod installed, I did not use it at any point.

**Comment by runelead00** [comment]
Fixed in Dev Build
