### ISSUE TITLE
BRG - Issues with new GUI, economy system, investigations, and some localization + misc bugs

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#150]
- Operating System: windows 10
- HOI4 Version: Collie 1.10.8
- TNO Version: TNO v1.2.0
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? own them all

**Issues with the "Domestic Situation" GUI** 

1a. The GUI has issues with displaying the tooltip (circled in image) that let's you know how many more/less police you need in the state, and how much loyalty will be gained/lost. Also, in some cases the tooltip entirely disappears, though this was fixed by saving and reloading. 

The actual map elements appear to function correctly, and will still show up dashed if you have too few police, and solid if you have enough police.

In my example image, I have only 1000 soldiers in Vichy, yet the tooltip does not update and states I will gain 7 Himmler loyalty.

![image](https://user-images.githubusercontent.com/59315866/142744379-ec0d70ff-b3ac-42dd-81c7-bb504478e1f8.png)

2a. Also, upon closing the main GUI, the state-specific GUI will hover, and requires manual closing.

![image](https://user-images.githubusercontent.com/59315866/142744447-bba60239-44fb-460d-9a34-5a07f1ae9881.png)

3a. There appears to be no way to actually check the overall loyalty level of Langemarck, Walloon, and Charlemagne divisions to Himmler, though various events and focuses affect this.

**Issues with economy system** 

1b. Any modifiers you were gaining from your army spending/civilian spending will still be applied to your country policies, even once the economy feature is removed after Pohl is shot. These also affect your stability and war support. There is no way to adjust or remove them. 

![image](https://user-images.githubusercontent.com/59315866/142744463-dbc1f3c2-b93c-4875-8c23-c06b6c36bb80.png)
![image](https://user-images.githubusercontent.com/59315866/142744566-21035713-0a19-4f94-b2d9-f0f7015cfe17.png)

2b. The "X" to close the economy screen no longer functions once Pohl is shot, and hitting ESC also does not work.

3b. Your poverty rate continues to affected by "Negative Real GDP growth.

![image](https://user-images.githubusercontent.com/59315866/142744581-04dbe8b0-3b77-4014-8ee9-b6a735d37e04.png)

4b. States still show the GDP and GDP% change tooltips after Pohl is shot.

![image](https://user-images.githubusercontent.com/59315866/142744660-639d7cdb-2610-4d4e-b315-3ee8b98b1189.png)

**Issues with Investigations**

1c. Some options for investigating (i.e. "Check Medical Records") in the initial Degrelle investigation (Fall Wiesel I think?) are greyed out and unselectable without explanation. I checked, and I had enough enough Intelligence to do these, and I had not done them before.

2c. Upon getting an event about a successful investigation, you will occasionally separately get an event about it being a dead end. This seems a bit strange.

3c. You can raid and destroy the house/bunker, but also later choose the option to plant a mole or search it. You probably shouldn't be able to spy on a house you've demolished.

**Missing localization**

1d. BRG_Econ_Dynamic_Modifier_Hidden2 is not localized or hidden.

![image](https://user-images.githubusercontent.com/59315866/142744849-8026c5ce-6b93-4a33-8d42-4396b888c72e.png)

2d. The loc in the "Domestic Situation" information tooltip is outdated - "security policy" should probably be "security police", and it states you gain 20 police a month base, when it's actually 1000.

![image](https://user-images.githubusercontent.com/59315866/142744916-20941d60-1464-48e9-8df9-55a12692c0e9.png)

3d. The below tooltip is either outdated or incorrect - am I building a dockyard or making a mine?

![image](https://user-images.githubusercontent.com/59315866/142745006-fca5bb20-b667-4b38-918d-9f3b6b027f85.png)

**Miscellaneous bugs**

1e. This tech appears to be unable to be researched even though it is available. Clicking "Research" does nothing. Unknown if this happens with all tags.

![image](https://user-images.githubusercontent.com/59315866/142745073-6761e12d-7f13-4e5f-92d2-147187daa968.png)

2e. Sphere GDP appears to be stuck at 0.

![image](https://user-images.githubusercontent.com/59315866/142745132-0b69aa76-c9ff-4d66-9ded-ccc4b786bf62.png)

3e. An interesting bug with the production units GUI. Not absolutely sure, but I saved and reloaded before this, so possibly that affected it?

![image](https://user-images.githubusercontent.com/59315866/142745321-d383f59d-a96f-40c2-8122-e22c853e100d.png)

**Comment by Drakeme** [comment]
I want to add a screenshot with loc typo: event title says "Inustriebezirk" when it should be "Industriebezirk" (TNO 1.2.0c)
![изображение](https://user-images.githubusercontent.com/71932171/142844086-2e6ed2c9-d5fa-412c-a0cd-d39fbb04aa58.png)

**Comment by runelead00** [comment]
Pretty most if not all issues have been fixed since now
