### ISSUE TITLE
Liberal Sakharov Tomsk - past a certain dates the game crashes / November 26th 1965 / December 4th 1965 13:00 / but the moment of crashing do vary 

### ISSUE THREAD

**Issue by 69thAirborne** [TNODevs/TNO-Bug-Tracker#1500]
### Operating System

Window 10 Pro

### HOI4 version

Avalanche v 1.12.8. fc54

### TNO version

TNO v 1.3.0 d - unfinished business

### Do you have other mods in use?

TNO Last Waltz of Europe Expanded & TNO Radio

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10453205/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10453206/game.log)

### Describe the crash

I move time forward and after a certain amount of time in 1965 in Late November or Early December 1965 my game crashes. Crash dates vary, but usually around that time span. 

### Steps to reproduce / Cause of the crash

Don't understand but perhaps sending a save game as an would work as a reproduction.

### Additional information

 Additional context, I was playing a Magadan game, same version of the game and TNO version, did not encounter any issues during that playthrough.

**Comment by runelead00** [comment]
A save would help, if you put in a zip file you should be able to send it through here easily. Also, are any tags elsewhere in Russia unifying at the same time, we've had 3 other crash reports today relating to Samara unification

**Comment by compute-this** [comment]
I'm having the exact same issue, Only I'm playing that plane-related country below tomsk (I forgot the name) and it's crashing right around early November 1965 for me.

My computer can handle the game pretty well, and was running perfectly fine before the crashes.

I don't have any other mods enabled, I have no DLC, and i'm on Windows 10, Newest version of the game/mod.

I would post my game file, but Github is saying it does not support this file type

**Comment by runelead00** [comment]
> I would post my game file, but Github is saying it does not support this file type

If you compress it into a zip file, you can upload it here. Either that or a game log from immediately after the crash would help

**Comment by runelead00** [comment]
Closing due to lack of additional information, likely one of the solved 1.12.8 crashes
