### ISSUE TITLE
Crash after Samara unifies Western Russia (another one)

### ISSUE THREAD

**Issue by CXCbI4** [TNODevs/TNO-Bug-Tracker#1502]
### Operating System

Windows 10

### HOI4 version

1.12.8

### TNO version

1.3.0e

### Do you have other mods in use?

TNO music, FPS map

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[SVR_1966_09_12_08.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10456176/SVR_1966_09_12_08.zip)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10456239/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10456245/error.log)

### Describe the crash

Samara unified Western Russia, game crashes after a few days at the same time and date. Was playing as Sverdlovsk (Yeltsin). 

### Steps to reproduce / Cause of the crash

1. Start playing as Sverdlovsk (probably could be any other nation)
2. Make Speer win German Civil War
3. Make Samara unify Western Russia (Vlasov in charge)

or just load the save

### Additional information

Last time I played TNO few days ago as Novosibirsk with Brave New World mod and Samara did reunify Western Russia too. But there was Bormann in charge in Germany and Oktan in WR, so such crush did not accure.

**Comment by runelead00** [comment]
Fixed in Dev Build, compatibility issues with 1.12.8
