### ISSUE TITLE
Iberia Union - Sudden crash at exact same date and time.

### ISSUE THREAD

**Issue by ZarkinDrife** [TNODevs/TNO-Bug-Tracker#1503]
### Operating System

MacOS Ventura 13.0.1

### HOI4 version

1.12.8.fc54

### TNO version

1.3.0e

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10467349/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10467352/game.log)
[autosave 101.hoi4.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10467401/autosave.101.hoi4.zip)

### Describe the crash

While playing as Iberia the game seems to crash at the same date every time I played the save. it crashes at 6am on July 2nd 1967.

### Steps to reproduce / Cause of the crash

1. Use MacOS Ventura?
2. Download save
3. Play as Iberia?
4. Unpause until July 2 6am
5. Crash.

### Screenshots

<img width="1440" alt="Screenshot 2023-01-21 at 2 07 06 am" src="https://user-images.githubusercontent.com/120159971/213731394-5ff3de70-e0bf-47bf-9fce-a50651437d02.png">
<img width="1440" alt="Screenshot 2023-01-21 at 2 07 27 am" src="https://user-images.githubusercontent.com/120159971/213731468-4215904c-59a4-4c78-83a1-a8cae9801d4b.png">
<img width="1440" alt="Screenshot 2023-01-21 at 2 08 06 am" src="https://user-images.githubusercontent.com/120159971/213731618-a005e706-a85b-4b7b-980d-b758d166b1a6.png">
<img width="1440" alt="Screenshot 2023-01-21 at 2 08 30 am" src="https://user-images.githubusercontent.com/120159971/213731735-b85a6c3d-fc30-4875-85d3-8fd33af64558.png">

**Comment by runelead00** [comment]
Fixed in Dev Build
