### ISSUE TITLE
USA - Crash on exact date, every time

### ISSUE THREAD

**Issue by Pejsik96** [TNODevs/TNO-Bug-Tracker#1504]
### Operating System

Windows 10

### HOI4 version

Avalanche v1.12.8.fc54 

### TNO version

v1.3.0e

### Do you have other mods in use?

Toolpakt: Toolpack for TNO, No Division Limit

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10469799/logs.zip)
[USA_1971_01_07_06.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10469804/USA_1971_01_07_06.zip)

### Describe the crash

Game crashes exactly on 4:00 8 January 1971

In game log, exactly on that time Republic of Scotland: event sco_up_countercoup.3 happens so i would have guess that this may be the issue. Just a in-game hour before Socialist Republic of Turkmenistan: event central_asia.200 happens so it also may crash the game.

But its only my guess. I know nothing about modding. Hopes it helps and it does not turn out that im just doing something wrong lol

### Steps to reproduce / Cause of the crash

1. Load save USA_1971_01_07_06
2. Wait untill 4:00 8 January 1971

**Comment by runelead00** [comment]
Fixed in Dev Build, issue was with Scottish electing SNP in 1970 (which wasn't logged correctly)

**Comment by Pejsik96** [comment]
Oh okay, may i ask if fix will be save compatible?

**Comment by runelead00** [comment]
No, when the next hotfix is released it won't be compatible because it changes an event file. You could probably continue your game though if you used console to have someone like England annex Scotland before the crash

**Comment by Pejsik96** [comment]
Okay. ill try that. Thanks!
