### ISSUE TITLE
USA - Crash after Oct. 1. 1967

### ISSUE THREAD

**Issue by hands-1973** [TNODevs/TNO-Bug-Tracker#1505]
### Operating System

Windows 8.1

### HOI4 version

Avalanche 1.12.8.fc54

### TNO version

1.3.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Files

https://easyupload.io/m/vvvkml

### Describe the crash

Game crashes after October 1st 1967. No idea what might be causing it.

### Steps to reproduce / Cause of the crash

1. Load provided save
2. Turn time on (save is on Oct. 1.)
3. Game crashes to desktop after a few ingame hours

### Additional information

Using OpenGL for Renderer.
Provided everything that I thought would be relevant for files. Apologies if useless, first time doing something like this.

**Comment by runelead00** [comment]
Fixed in Dev Build, Samara Unification CTD again
