### ISSUE TITLE
USA - West Africa Conflict scren under Global Conflicts menu doesn't go away even after winning the war

### ISSUE THREAD

**Issue by asbestoseater1963** [TNODevs/TNO-Bug-Tracker#1506]
### Operating System

Windows 10

### HOI4 version

1.12.8

### TNO version

1.3.0e

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I won the WAW around half a year before the screenshot, but the decisions menu hasn't gone away, and I didn't get a victory in the Cold War menu

### Steps to reproduce / Cause of the issue

1. Play USA
2. Go LBJ
3. Intervene in WAW
4. thats it

### Expected behaviour

The page would disappear, as it said in the event after the war ended

### Screenshots

![image](https://user-images.githubusercontent.com/122656930/213903036-dd9471c6-792e-418d-a7d0-6f88e9cd19c4.png)

**Comment by runelead00** [comment]
Should be fixed for SD by Oveja
