### ISSUE TITLE
FWA Wales - Midgame CTD

### ISSUE THREAD

**Issue by FruitsPP** [TNODevs/TNO-Bug-Tracker#1507]
### Operating System

Windows 11

### HOI4 version

1.12.8

### TNO version

1.3.0e

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10474160/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10474162/game.log)
[Walia.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10474171/Walia.zip)

### Describe the crash

It crashes when a new hoi4 day is about to start.

### Steps to reproduce / Cause of the crash

1. Load the save
2. Wait for the 16th feb
3. The game crashes

**Comment by runelead00** [comment]
Fixed in Dev Build, crash due to Samara Unification
