### ISSUE TITLE
USA lyndon johnson crashed

### ISSUE THREAD

**Issue by timwar005** [TNODevs/TNO-Bug-Tracker#1508]
### Operating System

Windows 11

### HOI4 version

1.12.8

### TNO version

1.3.0e

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10479831/error.log)

### Describe the crash

just crashes suddenly on exact date 

### Steps to reproduce / Cause of the crash

idk as i dont know why, seems some event is missing

**Comment by runelead00** [comment]
Closing due to lack of additional information, likely one of the solved 1.12.8 crashes
