### ISSUE TITLE
England/HMMLR - Both sides of the English Civil War have no divisions

### ISSUE THREAD

**Issue by Demoburg** [TNODevs/TNO-Bug-Tracker#151]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: v1.2.0
- Any other mods in use: Player-led Peace Conferences, Toolpack
- Were you using Steam?: Yes
- Which expansions do you NOT have?: Battle for the Bosporus 

**Longer Description of Issue:**
Neither the Kingdom of England nor the HMMLR possessed any divisions at the start of the civil war, and when I tag switched to the HMMLR they were not training new divisions despite having the equipment and manpower necessary to do so.

**Steps to Reproduce/Cause Issue:**

1. Play as a country besides England and wait until the start of the English Civil War

2. Tag switch to either the Kingdom or HMMLR

**Comment by Wizard2020** [comment]
I heard of similar issues and the problem for others was they were using outdated submod. It might be toolpack or you forgot a submod.

**Comment by runelead00** [comment]
Haven't heard any other reports or seen in happen since here, concurring with Wizard that's it was most likely a submod conflict
