### ISSUE TITLE
Lyndon B. Johnson - Crash to desktop, Jan 4, 1966.

### ISSUE THREAD

**Issue by gamonkey01** [TNODevs/TNO-Bug-Tracker#1510]
### Operating System

Windows 11

### HOI4 version

1.12.8 

### TNO version

v1.3.0e

### Do you have other mods in use?

Radio_TNO, Last Waltz of Europe, Minecraft Ost, Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10484698/error.log)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10484713/autosave.zip)

### Describe the crash

The game freezes for a few seconds, and crashes to desktop.

### Steps to reproduce / Cause of the crash

Load the autosave, and the game will crash on the 4th of January, 18:00.

### Additional information

Note: The mods I were playing with were turned off, as I was attempting to see if those were causing the issue. That is why, in the error log, there are so many missing sound files. This crash was happening with and without them on, however.

**Comment by gamonkey01** [comment]
Apologies - I was mistaken -  it was Jan 4, 1965.

**Comment by runelead00** [comment]
Fixed in Dev Build, Samara Crash - if you want to keep playing, either revert to 1.12.7, load a previous save and force Samara to lose West Russia, or annex Samara into the West Siberia power early to prevent event from triggering on Jan 4th
