### ISSUE TITLE
China Warlord - Toponymies

### ISSUE THREAD

**Issue by yangjin000** [TNODevs/TNO-Bug-Tracker#1511]
### HOI4 version

Now

### TNO version

Now

### Describe your suggestion

1, The culture of Nanning should be Rau (During ROC, see Rau People in Wikipedia, nowaday Zhuang which was created by CCP) instead of Yue. 2, Victory point San'a in Kainan-to Should be called Gaiken during ROC in Japanese On'yomi, the former one is changed by CCP. 3, Major culture of both of Xikang and Changdu are Tibetan. 4, Please restore the culture name Min from Hokkien (This name just means Fujian in native, means a south branch in English with pronunciation of south branch of Min) which is just a part Min but not all. 5, Culture Sichuanese is a part of Xinan, Integrate them or why not dissolve Xinan futher like Guiliu in Northern Guangxi, Yungui in Yunnan and Guizhou. 6 Major culture in Northern Xijiang should be Uyghur or Uyghur-Xibei, many fleed to Soviet in 1960s because of Ili-Tacheng Incident and CCP-Soviet, People in NX were taken place by more Han settlers. 7, In culture Zhujin, Zhu in pronounced in Mandarin, not Cantonese, It is better to rename as Chuejin (Chue is from the romanisation of Cantonese, see Standard Romanization (Cantonese)) and Guangdong may be better if Japanized as Kanton as well.

And another 2 suggestions about what I found recently while reading history. NI should not be called Ulster which is hated by Irish but prefer but British Unionist because Ulster includes 9 counties, NI is just 6 of Them, still name it Northern Ireland or Six Counties of Ulster may be better. Culture in German Northwest may be better if call Hannoveraner in German, the demonym of Hannover because of duchy of hanover. Niethersachsisch is larger, it includes Westfalen and other parts nearby (maybe). BTW, I am trying to find the toponymies in China in last century many of them changed by CCP after PRC formed, if you want I might promote more in the future.

### Justifications

follow the history of that period if you.want? I don't know...

### Screenshots

n

### Additional information

n

**Comment by tkgitno** [comment]
The current map is outdated and a new one will be come by TSS with new cultures. For other I’ll leave it to ppl in charge of those regions.
