### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Eternal-Shade** [TNODevs/TNO-Bug-Tracker#1512]
### Operating System

Windows 10

### HOI4 version

1.12.8.fc54(e447)(S)

### TNO version

1.3.0d-unfinished business  

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

https://onedrive.live.com/?cid=51e4d0bfdd624718&id=51E4D0BFDD624718%213711&ithint=folder&authkey=%21Ao35hdCVtCBn47Q

https://onedrive.live.com/redir?resid=51E4D0BFDD624718!3684&authkey=!AikLKlNqzqZyowU&e=jY2-CdbOnUCkj86DG7vlNQ&at=9

### Describe the crash

Samara unification Ctd a few days after ever time. I went back to the save multiple times  trying different things and taging over to unify as player exact same result every time. Tried making new save and playing that same issue  

### Steps to reproduce / Cause of the crash

Go to save. Play. Wait a 2 weeks for  Samar to unify or tag and unify yourself. Wait a few days after and it crashes

**Comment by runelead00** [comment]
Fixed in Dev Build, revert to 1.12.7 to avoid the crash until next patch
