### ISSUE TITLE
Game crashing to desktop as soon as I start a new game

### ISSUE THREAD

**Issue by Neopolaria** [TNODevs/TNO-Bug-Tracker#1513]
### Operating System

Windows 10

### HOI4 version

1.12.8

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

WTT, MTG, LAR, NSB, BBA

### Files

None, contact me via discord and I can send it over as this is a different device

### Describe the crash

I had this issue for a while, and I thought it was BNW’s fault, but after loading TNO alone without any other mods, it still crashed whenever I started a new game. I don’t have a crash report but I can try to get one and send via discord dm.

### Steps to reproduce / Cause of the crash

For me, I just started a new game as any country, and the game crashed

### Additional information

While I did say I have other mods, for this occasion specifically I found out it was TNO causing the crash. I am willing to provide my discord for resources as this report is from a different device.

**Comment by runelead00** [comment]
While we don't know the exact cause or fix for this specific issue yet, I would recommend checking the potential solutions listed on issue #962 
Merging this issue in with that one
