### ISSUE TITLE
Nov - West Africa War Peace Deal Crashing

### ISSUE THREAD

**Issue by the-gemperor** [TNODevs/TNO-Bug-Tracker#1514]
### Operating System

Windows 10

### HOI4 version

1.12.8

### TNO version

v1.3.0e

### Do you have other mods in use?

TNO: Brave New World, The Moe Order: Last Days of Anime, Toolpakt: Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[TNO BNW WAW Crash.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10496714/TNO.BNW.WAW.Crash.zip)

### Describe the crash

Playing as Novosibirsk trying to complete all of the base TNO content to move onto the Brave New World content. West African War is about to finish, after I deleted all units from WAA and Cammeroon's Faction (It's the WAA v FMA v Cameroon scenario), All of the WAA appears to be capitulated (all of their land is occupied) and Cameroon is about to surrender. As soon as the peacedeal happens, game crash.

This has happened on different saves with Brave New World off, though it only happened once on my latest Speer Game, with my second try loading in the save working. That did not happen this time.

### Steps to reproduce / Cause of the crash

1. Play as any nation
2. Progress till WAW starts
3. Get Free France to capitulate all countries
4. Peace deal and crash

### Additional information

I don't really have troubles with any other peace deals. It is always the West African War that causes me the most grief, so much so that I dread the conflict happening because it always breaks my game and I can't continue past it.

**Comment by the-gemperor** [comment]
Also happens without Brave New World mod on, every time the WAW crashes my game at the peacedeal

**Comment by runelead00** [comment]
Should be fixed for SD by Oveja
