### ISSUE TITLE
Socialist Italy crashes on around April 11, 1967 not sure the cause. 

### ISSUE THREAD

**Issue by Pinsanity** [TNODevs/TNO-Bug-Tracker#1515]
### Operating System

Windows 11

### HOI4 version

1.12.8

### TNO version

1.12.8

### Do you have other mods in use?

Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10496978/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10496979/error.log)

[ITA_1967_04_07_08.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10497018/ITA_1967_04_07_08.zip)

### Describe the crash

Recently got the event of a Canadian Prime Minister getting relected on April 11, then immediately crashes to desktop.

### Steps to reproduce / Cause of the crash

Unsure of a fix, and unsure the cause or how to replicate other than loading save file and start playing. 

### Screenshots

![italy bug](https://user-images.githubusercontent.com/122412006/214503300-50ac1d72-f0c8-4709-80c5-a91e75fcbd06.png)

Crash will occur about 3 days after this current screenshot.

**Comment by runelead00** [comment]
Fixed in Dev Build, Samara Unification CTD, revert 1.12.7 or annex Samara into another country or load a save to force a different unifier in West Russia
