### ISSUE TITLE
Far Eastern Soviet Republic - Game Crashes on August 3rd 1968

### ISSUE THREAD

**Issue by TheOttoboy** [TNODevs/TNO-Bug-Tracker#1516]
### Operating System

Windows 11 Pro

### HOI4 version

1.12.9

### TNO version

idk

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB, BBA

### Files

[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507697/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507699/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507700/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507701/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507702/executed_commands.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507703/game.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507706/graphics.log)
[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507707/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507708/message.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507710/posted_commands.log)
[random.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507711/random.log)
[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507712/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507713/sent_commands.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507714/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507715/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507717/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507718/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507719/time.log)

[cant upload save game (template doesnt support it)]

Error logs:

[error log 1.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507789/error.log.1.txt)
[error log 2.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/10507794/error.log.2.txt)

### Describe the crash

İ was playing as buryatia on civillian mode and it suddenly crashed on August 3rd 1968

### Steps to reproduce / Cause of the crash

1. Play as Buryatya on DEFCON 5 (and strenghen Buryatya to the max on custom)
2. Reunify the Far east
3. İncrease your army size and play normally until August 3rd 1968

**Comment by runelead00** [comment]
See #1509, you wiped your logs by reloading the game, nothing useless is contained in any of the logs you sent, either replicate the crash again for good logs or send the save game in a zip file. Also check recently closed issues to see if any of the crashes line up with yours

**Comment by runelead00** [comment]
Closing due to lack of additional information, likely one of the solved 1.12.8 crashes
