### ISSUE TITLE
Any Country - Crashing after desktop 

### ISSUE THREAD

**Issue by british105** [TNODevs/TNO-Bug-Tracker#1519]
### Operating System

Windows 10

### HOI4 version

1.12.8

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

DOD, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10516738/error.log)

### Describe the crash

Once I have selected a country and it finishes loading the game crashes to the desktop. I have -opengl in the launch options and I have uninstalled and redownloaded both the game and the mod and done a 'clean install'.

### Steps to reproduce / Cause of the crash

1. Select a country
2. It finishes loading - it then crashes

**Comment by runelead00** [comment]
Merged into #962, recommend trying any of the potential solutions there, cause and proper solution is still unknown
