### ISSUE TITLE
Bormann's Germany - SAW withdrawal decision page remains after winning

### ISSUE THREAD

**Issue by Sebaarebi** [TNODevs/TNO-Bug-Tracker#1520]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.3.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[https://1drv.ms/u/s!AlGdfCRGmfgYihDi6oALN-IDa-th?e=NyHCOr](url)

### Describe the bug

Won the SAW during the 365-day withdrawal period. Withdrawal decisions page never left decisions tab afterwards. Probably caused further issues down the line such as Norway coup decisions never appearing.

### Steps to reproduce / Cause of the issue

1. Win SAW during withdrawal period.

### Expected behaviour

Expected withdrawal decisions to dissapear and Norway coup decisions to appear.

### Screenshots

![image](https://user-images.githubusercontent.com/123741458/215095851-9674dd36-f7c7-4b73-b6a4-21bcef3217cb.png)

**Comment by runelead00** [comment]
Fixed in Dev Build by Yugo
