### ISSUE TITLE
Russian Federative Republic- at 4:00 on January 9th of 1971 the game crashes

### ISSUE THREAD

**Issue by Cart45** [TNODevs/TNO-Bug-Tracker#1521]
### Operating System

Windows 11

### HOI4 version

1.11.7

### TNO version

1.21b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[SVR_1971_01_08_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10522428/SVR_1971_01_08_01.zip)

### Describe the crash

The game crashes as soon as the time hits 4:00 on January 9th of 1971.

### Steps to reproduce / Cause of the crash

1. Open game
2. Wait until 4:00 on January 9th

**Comment by runelead00** [comment]
Scottish election crash fixed in Dev Build, either revert to 1.12.7 or annex SCO into another country to continue playing
