### ISSUE TITLE
Haiti is Uncultured in TNO

### ISSUE THREAD

**Issue by Dagemelior** [TNODevs/TNO-Bug-Tracker#1522]
### Operating System

Windows 7 Ultimate

### HOI4 version

1.12.8

### TNO version

1.3.0e

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

For the states of Grand Ouest, Tiburon, and Nord-Est, the culture icon is replaced with a neon crying emoji. Hovering over it leads to the discovery that these states have no culture

### Steps to reproduce / Cause of the issue

1. Start TNO as any nation
2. Click on Grand Ouest, Tiburon, or Nord-Est
3. Hover over the culture icon

### Expected behaviour

I expected these states to have culture

**Comment by runelead00** [comment]
Fixed in Dev Build for SD
