### ISSUE TITLE
United States - Crash on loading any save

### ISSUE THREAD

**Issue by ezekielraiden** [TNODevs/TNO-Bug-Tracker#1523]
### Operating System

Windows 10

### HOI4 version

1.12.9 "Avalanche"

### TNO version

1.3.0e "Toolbox Theory - Unfinished Business"

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10528964/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10528966/game.log)

### Describe the crash

Every time I load a save game while already playing, the game crashes to desktop. It loads to what appears to be exactly 50%, then the sound cuts out, and then a few seconds later the game crashes to desktop.

I don't have any other mods for HOI4 now that the custom country path mod has been integrated. I have verified the integrity of the game's files and unsubscribed from TNO, launched the game, then resubscribed and attempted it again. This issue has persisted across every save file I have played since the 1.3.0 "Unfinished Business" update.

### Steps to reproduce / Cause of the crash

1. Start or load any file.
2. While already playing, attempt to load any other file, even one you have just saved.
3. Game will load ~50% and then crash to desktop.

### Additional information

Sometimes--rarely--if I quit to menu and then load a file, I can load a saved game without re-launching the program. Sadly, this workaround has mostly stopped working recently, and now sometimes even attempting to bring up a saved game in the ordinary loading menu even when I _haven't_ started playing yet will crash to desktop.

**Comment by ThePikminCaptain** [comment]
This also happens to me when I try to load a new game as usa

**Comment by Stormeagle449** [comment]
I think the problem here is that you're trying to load saves from older versions, load a new game and the issue should be solved.
