### ISSUE TITLE
CHI -  Grammar/Spelling Mistakes

### ISSUE THREAD

**Issue by MisterKrisobg** [TNODevs/TNO-Bug-Tracker#1524]
### HOI4 version

1.12.9

### TNO version

1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### List the loc issues below

- 1. I assume he should be nursing a bear, not a beer.
![beer bear](https://user-images.githubusercontent.com/74677202/215359330-8f2a8c68-e34f-4562-8c09-3efb184e5e4c.png)

- 2. "china" should be capitalised.
![china](https://user-images.githubusercontent.com/74677202/215359586-96d9eb9a-7d4d-494c-b7ca-b4b3e97075e4.png)

- 3. I think that Chinese sanctions should be changed to Japanese unless I'm misunderstanding something.
![chinese sanctions on china](https://user-images.githubusercontent.com/74677202/215359706-e8e679f1-fd4e-4b91-bc1f-f38f6607f102.png)

- 4. "Employee's" should be changed to "employees."
 ![employee's](https://user-images.githubusercontent.com/74677202/215359824-1262183a-cf6f-4c6d-bcda-25330109ab1a.png)

- 5. Is the old man Li's father, grandfather or godfather? I assume he's Li's father and so all of those should be changed to father.
Also, sours should be changed to sores (on the line where it says "sours on his arms").
![father sores comma](https://user-images.githubusercontent.com/74677202/215359921-a6360fd8-b6df-4296-a17b-84bf920f3a86.png)

 - 6. "I'm" should be changed to "I" and the "i" in "i'll" needs to be capitalised.
![I](https://user-images.githubusercontent.com/74677202/215360041-473ffa60-afba-411a-82d2-9646d02f56cb.png)

- 7. "mutitions" should be changed to "munitions"
![mutitions](https://user-images.githubusercontent.com/74677202/215360411-dc7cc903-feff-4db2-a216-2ab6e514b19a.png)

**Comment by runelead00** [comment]
2-7 Fixed in Dev Build
