### ISSUE TITLE
Tyumen/USSR - Game Crash

### ISSUE THREAD

**Issue by averagekaganovichlarper** [TNODevs/TNO-Bug-Tracker#1525]
### Operating System

Windows 11 Home

### HOI4 version

1.11.7?

### TNO version

Pre-silicon Dreams

### Do you have other mods in use?

TNO capitulation messages but funi,  TNO but everybody has shades

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

WTT, MTG, LAR, NSB, BBA

### Files

https://1drv.ms/u/s!Ar2CS43qZyVe6Vv7vobNQPRMSthX?e=WXP0jT

https://1drv.ms/u/s!Ar2CS43qZyVe6Vv7vobNQPRMSthX?e=WXP0jT

Both are the same, this at different dates.

### Describe the crash

Basically, im waiting and preparing for the final war to unify russia. 7th [forgor month] of 1971 hits, and boom crash. 
Yemen Arab republic seems to win right when I hit this date as well. Its a basic random crash, nothing much to describe it besides some small events happening. {I dont know if any other events or territorial changes occured.]

### Steps to reproduce / Cause of the crash

1. Load Save
2. Wait until 7th 1971
3. Yemen Arab Republic wins
4. Crash

### Additional information

I have tried lowering my graphics, turning off other visuals, muting my volume, and loading older saves to see if anything changes. I get the same result, same crash, no matter what.

**Comment by runelead00** [comment]
Likely caused by the Scottish Election crash, try annexing Scotland into England and see if that fixes the issue, or try reverting to 1.12.7 temporarily
