### ISSUE TITLE
game crashes right after you finish selecting your country

### ISSUE THREAD

**Issue by maoouuu** [TNODevs/TNO-Bug-Tracker#1526]
### Operating System

Windows 11

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10532151/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10532153/game.log)

### Describe the crash

basically whenever i get into the game past the loading screen and i when i click on start as the country im playing as i wait for the game to load in and as soon as its done it just crashes. this basically happens everytime i launch the game

### Steps to reproduce / Cause of the crash

open the game
wait for it to load
select the country u wanted to play as
wait for that too load
and then it crashes

### Additional information

this only started happening two days ago up until then it was completely fine

**Comment by runelead00** [comment]
Merged into list #962, all I can recommend is trying the possible solutions listed there, could be something wrong with your installation of TNO since a few of the GUI errors in the log I've never seen before

**Comment by maoouuu** [comment]
i tried yesterday looking at #962 but nothing worked im lost at what to do
