### ISSUE TITLE
Großgermanisches Reich/Russian Republic - CTD After Peace Conference

### ISSUE THREAD

**Issue by neworderbug** [TNODevs/TNO-Bug-Tracker#1527]
### Operating System

Windows 11

### HOI4 version

1.12.8

### TNO version

1.3.0e

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10539263/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10539264/game.log)

### Describe the crash

At 01:00, 25 Jan 1966, Großgermanisches Reich defeats Russian Republic in a war. After the peace conference, at 05:00, the game crashes to desktop. The game can be paused at any time between 01:00 and 05:00 without a crash; it's only at 05:00 that the crash occurs. Earlier, I attempted to tag GER and force annexation of ORL and this prevents the peace conference from occurring, but the crash still occurs (the logs attached are not from this particular crash; I reproduced the crash again as described and attached those logs). I apologize, I'm having trouble uploading the save file but will continue trying.

### Steps to reproduce / Cause of the crash

1. Wait until 05:00, 25 Jan 1966, when the peace conference between Großgermanisches Reich and the Russian Republic resolves.

**Comment by runelead00** [comment]
Fixed in Dev Build, Samara Unification CTD, revert 1.12.7 or annex Samara into another country or load a save to force a different unifier in West Russia

**Comment by neworderbug** [comment]
Was just about to report a revert resolved it - thanks so much for your quick reply, very much appreciated!
