### ISSUE TITLE
Sakharov Tomsk - Crashes after March 15th 1966

### ISSUE THREAD

**Issue by ancavar** [TNODevs/TNO-Bug-Tracker#1528]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.3.0

### Do you have other mods in use?

TNO Russian translation

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10546034/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10546036/game.log)
[TOM_1966_02_04_01_temp_temp_temp.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10546044/TOM_1966_02_04_01_temp_temp_temp.zip)

### Describe the crash

So in the save that I've provided if you wait until the very end of  March 15th 1966 you simply crash.  

### Steps to reproduce / Cause of the crash

Load the save and wait until March 15th

**Comment by runelead00** [comment]
Works in Dev Build, may be a one-off issue or may want to consider a reinstall if it reoccurs, Secret Army wasn't set up for China for some reason

**Comment by ancavar** [comment]
I reinstalled and still persists

**Comment by runelead00** [comment]
even with a reinstall, the same save will continue to broken. A chinese event that fires in the first week of the game just appeared to have not in your version. Dev Build is the most up-to-date version used by the dev and what will be released in the next patch tomorrow
