### ISSUE TITLE
Kingdom of England-Calgary Olympics event fires constantly

### ISSUE THREAD

**Issue by Hhh20212** [TNODevs/TNO-Bug-Tracker#153]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: no
- Were you using Steam? Yes
- Which expansions do you NOT have?

**Longer Description of Issue:**
The Calgary Olympics event has an indefinite amount of pop ups, therefore making the game unplayable
**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by masterbobli** [comment]
Fixed in the latest release. Thanks for reporting
