### ISSUE TITLE
England (Thatcher) - Crashes after 7th January 1967, after firing of Japanese Lighter Hand in the East news

### ISSUE THREAD

**Issue by british105** [TNODevs/TNO-Bug-Tracker#1530]
### Operating System

Windows 10

### HOI4 version

1.12.8

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

DOD, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10566227/error.log)

### Describe the crash

The 'Lighter Hand in the East' on approx. 7 Jan. 1967, and then the game crashes to desktop

### Steps to reproduce / Cause of the crash

1. Play England, take the Thatcher path, get to Jan 1967
2. Be doing the 'Who are you so high that I must bow to you focus'
3. Lighter hand in the east news item fires
4. Crash to desktop

**Comment by runelead00** [comment]
See #1509, none of the information you provided help to diagnose the issue

**Comment by runelead00** [comment]
Lack of response + today's update means cause likely won't be discovered and may already be fixed
