### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by djoah003** [TNODevs/TNO-Bug-Tracker#1531]
### Operating System

Windows 11

### HOI4 version

Avalanche v.1.12.9.d0ab (7c58)

### TNO version

 v1.3.0e

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10572447/game.log)
Error logs under:
[FirstCrash.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10572455/FirstCrash.log) 
[SecondCrash.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10572460/SecondCrash.log)
[ThirdCrash.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10572461/ThirdCrash.log)
autosave days before crash:
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10572497/autosave.zip)

### Describe the crash

As Omsk, I was fighting the insurgents. No one else (I was at peace) . Out of nowhere I got a crash.

### Steps to reproduce / Cause of the crash

1. Load autosave w/ no other mods.
2. Wait a few days
3. Crash.

### Additional information

Annexing every single nation seemed to fix the CTD. Still not sure, which one of the nations is the culprit, but it's one of them.

**Comment by runelead00** [comment]
Samara Unification CTD, fixed in dev build
