### ISSUE TITLE
USA - After first 3 Hart foci, cannot continue focus tree

### ISSUE THREAD

**Issue by Rorschach113** [TNODevs/TNO-Bug-Tracker#1532]
### Operating System

Windows 10

### HOI4 version

1.12.7

### TNO version

1.3.0e

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10573599/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10573625/error.log)

and a save from slightly before I encountered the issue, tested from this save moving forward several times.

https://www.dropbox.com/s/831djaj54ynrpkj/USA_1969_01_24_17.hoi4?dl=0

### Describe the bug

Cannot get past my 3rd focus as Philip Hart.

### Steps to reproduce / Cause of the issue

1 - Do focus "the hart presidency"
2 - do the focus below to the left, and then the one below to the right. (didn't test the other order)
3 - Can't do any more foci.

### Expected behaviour

Let me take foci when by all means it appears I should be able to.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build, Saint of the Senate is now unlocked at equilibrium
