### ISSUE TITLE
TIB/QIN/MEN - Map Suggestions/Issues

### ISSUE THREAD

**Issue by HighMountainGuy** [TNODevs/TNO-Bug-Tracker#1534]
### HOI4 version

1.12.9

### TNO version

1.4.0 "Silicon Dreams"

### Which major expansions do you NOT have?

_BBA_

### Describe your suggestion

The NRA 40th Army Group should (probably) own the Yushu Region (Yul Shul) and Mengjiang should own North Shanxi

### Justifications

The reason for the first point is that Tibet lost Changdu to the NRA 24th Army under Liu Wenhui sometime before the start of the mod's startdate. The 40th Army's invasion of Tibet would be sensible because the loss of the Changdu region to Wenhui would lead to the connection between Tibet and the Yushu region being severed which'd make it vulnerable, alongside how the 24th Army invaded Tibet anyways.
(Yul Shul is State 601)

As for the North Shanxi suggestion, it's basic, the region unified into the Mongol United Autonomous Government and was then maintained through the existence of Mengjiang, in-game it's contradictory to what would've happened.

### Screenshots

To Mengjiang
https://en.wikipedia.org/wiki/North_Shanxi_Autonomous_Government
![image](https://user-images.githubusercontent.com/71605887/216676762-fd71033e-27c4-4b6c-b92e-465e63624a90.png)
![image](https://user-images.githubusercontent.com/71605887/216677014-c2a0fa56-9f1e-4414-a951-e8ffce88db85.png)

To Qinghai (NRA 40th Army)
![image](https://user-images.githubusercontent.com/71605887/216676950-6b2876fd-e309-4b23-8999-1c1e64488354.png)

### Additional information

N/A

**Comment by tkgitno** [comment]
Noted China map isn’t finalised till TSS and is up to changes
