### ISSUE TITLE
CHINA YUNNAN - Crash after JINXI join the unit

### ISSUE THREAD

**Issue by piconasha** [TNODevs/TNO-Bug-Tracker#1535]
### Operating System

Windows 11 22H2 22621.1194

### HOI4 version

1.12.9.d0ab

### TNO version

1.4.0

### Do you have other mods in use?

The New Order: Last Days of Europe(CN.ver)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10582408/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10582420/error.log)

### Describe the crash

I played as YUNNAN and used LONGYUN declared war on reorganized national government.

It works well before invite JINXI warlord to join united front, after that the game crushed,
and popped a window advised me to upload a crush report.

And i tried to load the latest save file without any mod expect for this but it crushed again.

### Steps to reproduce / Cause of the crash

1. Load the save file
2. Invite JINXI to join united front
3. Let time pass about 1 week
4. CTD

### Screenshots

![image](https://user-images.githubusercontent.com/28810462/216702712-a57df03d-dcfc-481b-8a74-61abea892cef.png)

**Comment by runelead00** [comment]
Could you upload a zip file of your save game here please

**Comment by piconasha** [comment]
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10608141/autosave.zip)

**Comment by runelead00** [comment]
Did you start this game before 1.4.0 update, because your error log has a bunch of characters removed in the last update. Incompatibility with the current version is probably causing the crash
