### ISSUE TITLE
Vietnam - Spirits with Conflicting Lore

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1536]
### HOI4 version

1.12.10

### TNO version

1.4.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Two of the descriptions of Vietnam's national modifier icons mention the failure of operation Yon-Go in the early sixties, however, they both conflict on what year exactly.

Icon "The Faltering Establishment" mentions its failure in the year 1961.
![image](https://user-images.githubusercontent.com/25708474/216704465-d870d477-af46-4a8f-8c24-90de1e8a7649.png)

While the icon "A New Phase" mentions the operational failure in 1960.
![image](https://user-images.githubusercontent.com/25708474/216704619-3557d89c-f344-47bd-8614-51dfe2269721.png)

If perhaps, the operation failed over a series of months from 1960 to 1961, then there is no issue, but it does not exactly clarify that and instead sounds like the operation failed on two separate years.

Apologies if this is just a matter of my own misinterpretation.

**Comment by runelead00** [comment]
Fixed in Dev Build
