### ISSUE TITLE
Japan-- Yasuda Crisis Crash

### ISSUE THREAD

**Issue by bosco8179** [TNODevs/TNO-Bug-Tracker#1537]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10608754/error.log)

### Describe the crash

Game Crashed due to Yasuda Crisis

### Steps to reproduce / Cause of the crash

1. Wait Until 1963 April
2. Yasuda Crisis Happened
3. Boom

**Comment by runelead00** [comment]
Could you please share a save, have no other reports of this and nothing in the error log is helpful

**Comment by bosco8179** [comment]
https://mega.nz/file/SKJQSKrA#ZI-4dHGT8eXrBM28RguRj_e7C92OsAtze2s-Od76ijw

**Comment by runelead00** [comment]
Can't reproduce, even with save game
