### ISSUE TITLE
Ethiopia - Division spawning next to Xi'an

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1539]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Ethiopia has a division spawn near Xi'an,  supposed as soon as they gained independence, but I only spotted them in late 1965.

![image](https://user-images.githubusercontent.com/25708474/216779659-7476f736-cb70-4de5-92e4-4e6956056d06.png)

![image](https://user-images.githubusercontent.com/25708474/216779662-cfe21fc5-0991-4536-9b5e-493f256889e6.png)

Now, I'm open to the idea of proud Ethiopian patriots rising up in support of China, but it's more likely that this is just a bug.

### Steps to reproduce / Cause of the issue

1. Play as normal, until the Horn of Africa collapses.

2. Observe Xi'an, a division should be present.

### Expected behaviour

The division is not supposed to be present, maybe.

**Comment by turbobounce** [comment]
It is also not moving, just remaining stationary.

**Comment by runelead00** [comment]
Fixed in Dev Build
