### ISSUE TITLE
BRG - 1964 Winter Olympics event fires ~100 times

### ISSUE THREAD

**Issue by GoldenShowa** [TNODevs/TNO-Bug-Tracker#154]
![TT Winter Olympics bug](https://user-images.githubusercontent.com/94769222/142745805-1f3786d6-20cb-416a-b9a7-3703c2da944d.png)
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: TT Release patch
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
The 1964 Winter Olympics event fires an excessive amount of times leading to the game nearly crashing. FPS slows to 5-15 and the player must click the event close button dozens of times

**Steps to Reproduce/Cause Issue:**

1. Play Burgundy (most likely other nations as well) until the Winter of 1964 

2. The Event will fire x100

etc...

**Screenshots:**

**Comment by ThatOfficially** [comment]
Same problem playing as the USA. Using no other mods, all DLC except for Battle for the Bosporus. All other details same as OP.

**Comment by WikOfTheNorth** [comment]
Same problem playing as Speer's Germany. Playing without Battle for the Bosporus. The game could not progress one hour.

**Comment by WikOfTheNorth** [comment]
Additional information: the bug repeats upon loading the save and makes it impossible to quit the game without using task manager.

Screenshot: ![Olympics](https://user-images.githubusercontent.com/94769702/142746459-cf40ba0c-b047-470f-bc82-04cd9c1df177.png)

**Comment by Flizzyclone** [comment]
This has been fixed in a patch just released. If Steam isn't automatically downloading it for you, try validating your game files.
