### ISSUE TITLE
Japan - Save File Causes Army Function to disappear and crashes game.

### ISSUE THREAD

**Issue by malakite1708** [TNODevs/TNO-Bug-Tracker#1540]
### Operating System

Windows 10 home

### HOI4 version

1.12.10

### TNO version

1.4.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Files

Error Log: 
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10609301/error.log)

Save File: 
[Japan_temp.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10609320/Japan_temp.zip)

### Describe the crash

When the game is saved, an additional piece of text "_temp" is added to the end of the save file. For example, the save file "Japan" becomes "Japan_temp". When you go to load this file, the military UI at the bottom of the screen does not appear. After unpausing the game, a single day will pass and then the game will crash.

### Steps to reproduce / Cause of the crash

1. Start a game
2. Save the game
3. When the game is saved, check if the file name has been changed to "name_temp"
4. load that file

### Screenshots

![2023-02-04 (2)](https://user-images.githubusercontent.com/71910219/216782769-8f3da1b2-3639-4a56-bf5f-f3087ba0aa67.png)
![2023-02-04 (3)](https://user-images.githubusercontent.com/71910219/216782810-0a02d3f5-e356-400c-b1b7-3ea2c8460c6e.png)

### Additional information

The game runs fine, whatever is causing this issue seems to be related to how the game processes save files, because my game was running perfectly fine up until I went to save it.

**Comment by runelead00** [comment]
are you using cloud saves? because those do not work with TNO

**Comment by malakite1708** [comment]
It's not a cloud save as far as I know.

**Comment by runelead00** [comment]
does your autosave work fine? because we can't fix why your game isn't saving properly on your end

**Comment by malakite1708** [comment]
yes and no, though I think I might know what might be causing the problem. I've been messing around with saving the game, and it seems that the save only breaks when I don't have an army formed. I went and saved with one division in an army and the save didn't break, I made three saves without an army and all three broke. I don't know if that helps in identifying the problem or not.

**Comment by malakite1708** [comment]
I've also tested a vanilla game to see if my Hoi4 game was the problem, but I didn't run into this issue, so I'm thinking it has to be connected to TNO.

**Comment by malakite1708** [comment]
I'm gonna close this thread because the issue has resolved itself. I deleted all my files and did a fresh install of Hoi4, and that seems to have fixed whatever was causing the problem.

**Comment by runelead00** [comment]
Note, I'll refer to this if issue occurs for others
