### ISSUE TITLE
Guangdong - (Morita) Focus "Future Fund" does not apply its law

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1541]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

Allegiances Submod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![image](https://user-images.githubusercontent.com/113797283/216786900-9fa021e5-1da0-4f84-a990-34911521ce96.png)
![image](https://user-images.githubusercontent.com/113797283/216786938-bea98cdc-cac6-4433-a7d3-8d2c44ba8c59.png)

### Describe the bug

The Assorted Law for the "Future Fund" is not applies by the focus for it, instead it is applied by a different branch of the focus tree next to it.

### Steps to reproduce / Cause of the issue

1) Play as Guangdong
2) Load Morita's Focus Tree

### Expected behaviour

The Expected behavior is that the misc law would be applied by the branch of the focus that has the Future Fund be created

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/216786961-45f339e5-b843-4624-ab61-c9e01a7f30eb.png)
![image](https://user-images.githubusercontent.com/113797283/216786964-274c6495-49c6-4c04-8110-50f2fc52fc4e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
