### ISSUE TITLE
Guangdong - Springtrap Locks Shut

### ISSUE THREAD

**Issue by J4xx0n** [TNODevs/TNO-Bug-Tracker#1542]
### Operating System

Windows 10

### HOI4 version

I have no idea but this isn't relevant

### TNO version

v1.4.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Springtrap event chain.

Event guangdong_matsushitaspringtrap.5005

Option 5005.b never shows up, even with GNG_Stanley_Ho_Investigated = 1.

### Steps to reproduce / Cause of the issue

To decide whether you get option 5005.b, you need GNG_Yokoi_Hideki_Investigated = 1.
5005 is the event for succesfully investigating Yokoi Hideki. The correct trigger should be checking for GNG_Stanley_Ho_Investigated = 1.

This causes 5005.b to never show up, since it is impossible to get to .5005 with GNG_Yokoi_Hideki_Investigated = 1. Instead, if you have GNG_Stanley_Ho_Investigated = 1, then you get an option with the text "Ok." that has no effect.

### Expected behaviour

With GNG_Stanley_Ho_Investigated = 1 get option 5005.b

**Comment by runelead00** [comment]
Fixed in Dev Build
