### ISSUE TITLE
Guangdong - Springtrap's Missing Assorted Laws Incident

### ISSUE THREAD

**Issue by J4xx0n** [TNODevs/TNO-Bug-Tracker#1543]
### Operating System

Windows 10

### HOI4 version

Still doesn't matter

### TNO version

v1.4.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

guangdong_matsushitaspringtrap.5002

5002.a does not add the assorted law Triad Quiescence. 

### Steps to reproduce / Cause of the issue

Add code at the bottom of 5002.a

set_temp_variable = { v = 36 }
GNG_add_uncategorised_law = yes

### Expected behaviour

Picking 5002.a should give the uncategorised law Triad Quiescence

**Comment by runelead00** [comment]
Fixed in Dev Build
