### ISSUE TITLE
Guangdong Yasuda Crisis and Peace Conference causes Game to Crash to Desktop

### ISSUE THREAD

**Issue by DinoTsar** [TNODevs/TNO-Bug-Tracker#1544]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10610027/error.log)
[AAG_1963_12_24_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10610029/AAG_1963_12_24_01.zip)

### Describe the crash

In the middle of a Guangdong game, with no other mods. Will get to the year 1963 about 14 Days after the Yashuda Crisis. A peace conference will fire which leads to the game crashing onto the desktop

### Steps to reproduce / Cause of the crash

1. Play Guangdong
2. Yasuda Crisis Fires
3. Wait 14ish days
4. Peace Conference Fires
5. Game should crash

### Additional information

I am unsure if a Zip-File works for the save game or what Log-File I should put down

**Comment by runelead00** [comment]
Are you sure the save file is related to the crash? This is an ODF German Antarctica save which wasn't compatible at time of you reporting this issue
