### ISSUE TITLE
Crash - No Other Context

### ISSUE THREAD

**Issue by 387809109** [TNODevs/TNO-Bug-Tracker#1545]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

CN translation

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10610043/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10610044/error.log)

### Describe the crash

Just a sudden CTD. Nothing else are undergoing, e.g., peace conference.

### Steps to reproduce / Cause of the crash

dunno. No fixed time for crashing

**Comment by runelead00** [comment]
#1509, Your logs are wiped and you didn't upload a save, there is nothing helpful or actionable here
