### ISSUE TITLE
Guangdong - Product Cycle bar does not work properly

### ISSUE THREAD

**Issue by joshricatti** [TNODevs/TNO-Bug-Tracker#1546]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Under the "Product Cycle" decision tab, you'll see the product currently in development. Beneath that, you'll see a bar where you can track its progress. By clicking it, you supposedly can toggle between the overview ("launch is expected to be underperforming/middling/etc.) and the effects (in-depth explanation of how the launch will be and the effects of it).
![image](https://user-images.githubusercontent.com/99983601/216797447-2e94ef56-d1c1-4a1a-954a-ac77310b6f7a.png)
The issue is that this does not happen. You can click on the bar as many times as you like but that won't toggle between the two options. The only way to change from 'overview' to 'effects' and vice versa is to click on the bar, then select another decision under the "Product Cycle" tab ('Test the Product Rigorously,' 'Give Freebies to the Chinese,' etc.)  This is of course not how the feature was designed and becomes at least a minor issue for the player.

### Steps to reproduce / Cause of the issue

1. Go to decisions
2. Find the "Product Cycle" tab while a product is being developed
3. Click on the bar

### Expected behaviour

I expected the bar to toggle between views, but this did not happen

**Comment by OPAsian** [comment]
Fixed for next hotfix, thanks for noticing
