### ISSUE TITLE
Guangdong - Emergency Powers Ordinance Does not enter Legco

### ISSUE THREAD

**Issue by Helrica** [TNODevs/TNO-Bug-Tracker#1547]
### Operating System

Windows 10

### HOI4 version

1.12.9 

### TNO version

1.40

### Do you have other mods in use?

No.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as matsushita and the riots hit, taking the right path on his response tree should put an emergency powers ordinance into the legco when the apropriate focus is selected: instead nothing happens. As a result you cannot take the right-hand tree at the bottom and the legco spends 14 days voting on nothing.

### Steps to reproduce / Cause of the issue

1. Play matsushita up until the riots.
2. Take the right path on his focus tree up until the emergency powers ordinance focus.
3. This focus will not work.

### Expected behaviour

The focus should introduce the emergency powers ordinance to the Legco to be voted on in 14 days.

### Screenshots

![image](https://user-images.githubusercontent.com/13255334/216808638-2675c109-3728-494e-aea5-c96392839f84.png)

**Comment by Helrica** [comment]
I fixed it by moving  set_temp_variable = { GNG_temp_legco_id = 75 } from under completion_reward to under select_effect instead: it looks like the problem is that it's wrong placing causes the bill to start _after_ the legco has it's voting session variable ended.

**Comment by OPAsian** [comment]
Fixed for next hotfix, thank you for noticing
