### ISSUE TITLE
The Return/Free France Theme gone in-game

### ISSUE THREAD

**Issue by itsandyru** [TNODevs/TNO-Bug-Tracker#1548]
### Operating System

macOS Big Sur 11.6.2

### HOI4 version

Avalanche v1.12.9

### TNO version

v1.4.0 Silicon Dreams

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Currently there is no define code for The Return/Free France Theme in the tno_soundtrack.asset file so the song does not play in-game

### Steps to reproduce / Cause of the issue

1. Go to music/TNO_songs/tno_soundtrack.asset
2. Ctrl-F and search for "Free France Theme" - no results will pop up

### Expected behaviour

The song should play in-game

### Screenshots

<img width="685" alt="Screenshot 2023-02-05 at 11 17 14 PM" src="https://user-images.githubusercontent.com/98255313/216813354-2b13f67a-5876-4f9f-88ae-e7bd85342d8a.png">

**Comment by runelead00** [comment]
Fixed in Dev Build
