### ISSUE TITLE
Colombia - Missing Portrait for leader Klaus Wilhelm Lehder

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1551]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Missing portrait for Klaus Wilhelm Lehder, leader of the Bolivarian Republic of Colombia.

![image](https://user-images.githubusercontent.com/25708474/216835413-69fa4733-1075-4ca3-9da2-440d96415008.png)

### Steps to reproduce / Cause of the issue

1. Have the fascists win the first Colombian civil war.
2. Have the second civil war begin.
3. portrait should be missing.

### Expected behaviour

A portrait should be present.

**Comment by runelead00** [comment]
Fixed in Dev Build
