### ISSUE TITLE
West African Union-Guinea - Incorrect borders after peace

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1552]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

As seen in the screenshots, The West African union (Formerly PALF) had won against the WAA and FFA, which is how the war was divided, and it started in ~1966-67, after the PALF's victory, the land dedicated for Guinea has instead remained in the possession of the West African Union.

![image](https://user-images.githubusercontent.com/25708474/216835855-734ce002-9adb-4da5-86ce-3f0a815c74df.png)

![image](https://user-images.githubusercontent.com/25708474/216835861-6fa01dca-a65a-45b6-afc7-8a6afa0f1c36.png)

### Steps to reproduce / Cause of the issue

1. The WAA-FFA-PALF war in mid-late 1960s begins.
2. War ends in victory for the PALF.
3. Borders of Guinea should be incorrect, West African Union owns land supposed for them.

### Expected behaviour

Land owned by the West African Union should belong to Guinea

**Comment by runelead00** [comment]
Fixed in Dev Build
