### ISSUE TITLE
USA - Repeating terms

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1553]
### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/98370487/216842775-6b19a9cb-1aa4-401a-b5e4-96d48ada0647.png)

### Additional information

Not an event, but grammar concerning decisions category.

**Comment by runelead00** [comment]
Fixed in Dev Build
