### ISSUE TITLE
New States have No Technology

### ISSUE THREAD

**Issue by Helrica** [TNODevs/TNO-Bug-Tracker#1554]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.40

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

States formed in-game from balkanization effects or similar have no starting technology whatsoever. This means that they can't produce equipment at all and wars turn into them sitting, their units unable to move forwards or do anything due to lack of equipment.

### Steps to reproduce / Cause of the issue

1. Start Game
2. Use debug commands to spawn anything like africa being blown up
3. Check their research - it will be blank.

### Expected behaviour

States should inherit the technology of the state they broke away from.

### Screenshots

![image](https://user-images.githubusercontent.com/13255334/216863030-d9243486-1411-4596-9aac-9cbd6b3e40d0.png)

**Comment by Stormeagle449** [comment]
Fixed for 1.5.0
