### ISSUE TITLE
Columbia - Second Columbian Civil war event repeats 

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#1555]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.40

### Do you have other mods in use?

Nope

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the Nazis win the columbian civil war a new civil war breaks out. The non-orthodox faction alligned with the dems won. Now every now and then the second columbian civil war event fires up and the war breaks out. Both nazi factions will have the orth nat soc guy take charge and then the orth nat soc state will inst capitulate leaving the nazi faction left with a filler stand in blank portrait for a leader. 

### Steps to reproduce / Cause of the issue

nazis win columbian civil war 

Big nazi faction alligned with dems wins 

endless columbian civil war

### Expected behaviour

War end normally.

**Comment by runelead00** [comment]
Fixed in Dev Build
