### ISSUE TITLE
United States - CTD at ~9 am May 1

### ISSUE THREAD

**Issue by Fizzpocalypse** [TNODevs/TNO-Bug-Tracker#1556]
### Operating System

Windows 10

### HOI4 version

v1.12.9.d0ab

### TNO version

(I think) 1.4.0

### Do you have other mods in use?

Player-Led Peace Conferences

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10668831/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10668832/game.log)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10668862/autosave.zip)

### Describe the crash

Hitting play, the timer advances to 9 AM and the game crashes to desktop with no fanfare. PDX crash reporter pops up.

### Steps to reproduce / Cause of the crash

Load in and hit the space bar.

**Comment by runelead00** [comment]
Samara Unification CTD, Fixed in Current Release, your game just wasn't updated properly
