### ISSUE TITLE
USA - Hart focus description error

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#1557]
### HOI4 version

1.12.9

### TNO version

v1.4.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

"Our Crime Combatting programs will lose" is wrong.
This should be change to"Our Crime Combatting programs will gain".
![20230207094348_1](https://user-images.githubusercontent.com/46292981/217128110-fa93096f-fe2b-408d-8fdd-92fbb1fa660c.jpg)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
