### ISSUE TITLE
Wrong name of city - Shostka in Ukraine in the place of Dnipro

### ISSUE THREAD

**Issue by Computer64** [TNODevs/TNO-Bug-Tracker#1559]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

1.4.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

If press endonym/exonym toggle, then Reichenaustadt (Dnipro/Katerynoslav) renames to Schostka (Shostka). However real Shostka in Sumy region, not Krivoi Rog. So, "Schostka" remains in all modes except Ensonyms/English names.

### Steps to reproduce / Cause of the issue

Idk how to fix it. It's necessary to digging in files of victory points.

### Expected behaviour

Non-german name of Reichenaustadt is Katerynoslav/Dniprodrahomyretsk.

### Screenshots

![image](https://user-images.githubusercontent.com/92990434/217358116-490176e2-4873-41a0-8b4f-ce254d069816.png)
![image](https://user-images.githubusercontent.com/92990434/217358191-fbc444cf-493d-4783-8147-aa6b43e507b8.png)
![image](https://user-images.githubusercontent.com/92990434/217359080-0b50b459-8aca-4d9d-964a-1332b7be3be4.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
