### ISSUE TITLE
Guangdong - Sony - Gambling License blocking other motions into Legco

### ISSUE THREAD

**Issue by prchad** [TNODevs/TNO-Bug-Tracker#1562]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

Chinese translation

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, BBA

### Describe the bug

After the Gambling license focus in Sony path, Legco will attempt to review the license. However, before the event fire, player is able to initiate another vote in Legco by selecting another focus. The latter one would not be voted on, and its bargaining events would fire and affect the vote on gambling license.

### Steps to reproduce / Cause of the issue

1.Start as Guangdong
2.Proceed as Sony
3.Finish prerequisites for the policing law focus and the gambling license focus (and suceed in both)
4.Finish the gambling license focus
5.Start the policing law focus
6.Problem is there.

### Expected behaviour

Ongoing voting in Legco prevents/cancels another focus that attempts to be voted on.

**Comment by runelead00** [comment]
Fixed in Dev Build by OP
