### ISSUE TITLE
KOM - Focus icon of Zhdanov's superregional tree is gone

### ISSUE THREAD

**Issue by Computer64** [TNODevs/TNO-Bug-Tracker#1565]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

1.4.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the GFX issue

Focus icon of "The Ultravisionary Method" in Zhdanov's superreg tree is gone when that focus became available (this focus icon was before completing previous focuses).

### Steps to reproduce / Cause of the issue

/interface/... maybe?
or /common/national_focus

### Expected behaviour

Fix that pls.

### Screenshots

![image](https://user-images.githubusercontent.com/92990434/217510905-06473f00-1b73-40f5-8282-3003beaac092.png)
![image](https://user-images.githubusercontent.com/92990434/217511758-954a28f8-5439-4a46-ad23-4023439f8583.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
