### ISSUE TITLE
Brazil - Anti-Trust Laws Missing Icon

### ISSUE THREAD

**Issue by BRUHADDICT4U** [TNODevs/TNO-Bug-Tracker#1566]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The National Spirit Icon 'Anti Trust Laws' for Quadros (Brazil) is missing/doesn't exist

### Steps to reproduce / Cause of the issue

1. have Quadros gain power
2. select the option to aquire the spirit

### Expected behaviour

there to be a non placeholder

### Screenshots

![20230208234430_1](https://user-images.githubusercontent.com/110141473/217678165-29a09323-a75d-497f-b144-8515d9ed813f.jpg)

### Additional information

IK it's just a placeholder so not the end of the world.

**Comment by runelead00** [comment]
Fixed in Dev Build
