### ISSUE TITLE
Guangdong - "Dead To Rights" event option b not firing correctly

### ISSUE THREAD

**Issue by Aggeremid** [TNODevs/TNO-Bug-Tracker#1568]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

Player Led Peace Conferences, Strategic View Adjustment, Toolpack without the errors

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The event with the id "guangdong_matsushitaspringtrap.5005" fired properly. At first the only option was a simple "Ok" that did nothing. After digging around the files I removed the trigger for option b of the event, since I had done the investigation on Stanley too. 

Reloaded the game and the event fired properly.

### Steps to reproduce / Cause of the issue

1. Make Matsushita Chief Executive
2. Go down the security path (Furthest to the right) until you complete the "Spring the Trap" focus
3. Start by investigating Stanley Ho
4. When you fully complete his investigation, start investigating Yokoi Hideki
5. When you fully complete his investigation, choose to confront him
6. When the event "Dead to Rights" fires, the only option should be "Ok"
7. After removing the trigger for option b on the "Dead to Rights" event, load a previous save.
8. Now the event will fire properly and the event chain will continue as usual

### Expected behaviour

There should be an option to continue the "Spring Trap" event chain if you have investigated Stanley Ho instead of a plain "ok"

**Comment by runelead00** [comment]
Fixed in Dev Build
