### ISSUE TITLE
BRG - Cannot select state of Kalen in state interaction GUI

### ISSUE THREAD

**Issue by Helrica** [TNODevs/TNO-Bug-Tracker#157]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: Toolbox Theory
- Any other mods in use: None
- Were you using Steam? Yes.
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Essentially, I just cannot select the state of Kalen in the GUI burgundy uses for "worker" management at all. There's still something there, the decisions to build a port for instance, from the decision tab, works. It's the GUI itself that doesn't seem to work.

**Steps to Reproduce/Cause Issue:**

I'm not sure how this happened, or even when, exactly: I think it was in mid 1963, before the degrelle investigation started. 

**Screenshots:**

![image](https://user-images.githubusercontent.com/13255334/142747062-0f9e1875-36d6-4b21-b0c9-e268b6e716e5.png)

**Comment by Stormeagle449** [comment]
Fixed in dev build.
