### ISSUE TITLE
USA - West African War Doesn't End

### ISSUE THREAD

**Issue by dawedss** [TNODevs/TNO-Bug-Tracker#1570]
### Operating System

Windows 11

### HOI4 version

1.12.8

### TNO version

1.4.0

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

During the three way West African War, when I help the FMA win the war by having Cameroon not control their required region until Cameroon's timer runs out, the war ends. But the global conflicts page for the West African War never disappears and my volunteers are exiled in Free France. No world events announcing FMA victory appears or domestic USA victory events appears. 

### Steps to reproduce / Cause of the issue

1. Have the three way West African War
2. Send volunteers when war escalates
3. Win the war by having Cameroon not control their required region until the timer runs out
4. War event announcing end never occurs, page isn't gone in global conflict

### Expected behaviour

When the FMA wins the 3 way war, the event for FMA victory should fire, and the US event should shortly fire after, removing the global conflicts page.

### Additional information

I looked into the code a little and was able to manually fire the end of the war by going into TNO_West_Africa.txt and using event west_africa_peace_deal.4. The event west_african_crisis.216 fired after I manually fired west_africa_peace_deal.4, but it only influenced voters to the current ruling USA political party. It's missing the removal of the foreign policy (I think TNO_fopo_remove_wac_tab = yes) and volunteers. Not sure what else the event is missing as well. 

I'm not sure if this is a bug, but the Phyllis Schlafly event opposing the WAA fired even after these two events fired.

**Comment by runelead00** [comment]
Should be fixed in release build
