### ISSUE TITLE
USA- RFK Social Security Act is Bugged

### ISSUE THREAD

**Issue by Fukuyamastan** [TNODevs/TNO-Bug-Tracker#1571]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

The Moe Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Files

[USA_1971_12_17_04.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10712066/USA_1971_12_17_04.zip)

### Describe the bug

When I select the Social Security Act Focus it automatically fails but the vote for the act is visible in my decisions. However I cannot do any of the focuses before the original act to negotiate on the act and even when I console command to gain enough support to pass the bill, nothing happens. 

### Steps to reproduce / Cause of the issue

1. Play through RFK Presidency until you reach the Social Security Act Focus.
2. Click on the focus

### Expected behaviour

I expected the focus to be completed so I could go to the other focuses on negotiating about the bill.

**Comment by runelead00** [comment]
Fixed in Dev Build as of today
