### ISSUE TITLE
CTD - Needs More Info

### ISSUE THREAD

**Issue by HuyBinh2004** [TNODevs/TNO-Bug-Tracker#1573]
### Operating System

Windows 11

### HOI4 version

1.12.8

### TNO version

1.3.1

### Do you have other mods in use?

radio_tno, Last Waltz Expanded

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10713893/error.log)

### Describe the crash

CTD after completing "... Of Excellence" focus about 1-2 days

### Steps to reproduce / Cause of the crash

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10713898/error.log)

**Comment by runelead00** [comment]
See #1509, CTD need game logs and save games to properly diagnose the cause of the crash

**Comment by HuyBinh2004** [comment]
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10715384/autosave.zip)
This is my save game file, apologize for not include it yesterday.

**Comment by runelead00** [comment]
Can't reproduce even with save file
