### ISSUE TITLE
IRL, USA, GER, JAP - Short Description of Issue

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1574]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10714468/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10714469/error.log)

### Describe the bug

After winning the Iranian Civil War as the liberals, points are not added to the "victories" tab of the Cold War GUI and is instead still marked as "ongoing." I capitulated the central government before the alliance fractured, if that has anything to do with it.

### Steps to reproduce / Cause of the issue

1. Capitulate the central government of Iran before the rebel alliance fractures.
2. Win the Iranian Civil War as the liberals.
3. See issue.

### Expected behaviour

Points are added to Cold War victories page for the USA and points are subtracted from Germany and Japan.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/218275518-0ef681e5-34a7-4fd3-b34f-c31b3194e221.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
