### ISSUE TITLE
Buryatia - CTD after the western african war peace deal

### ISSUE THREAD

**Issue by ender1324** [TNODevs/TNO-Bug-Tracker#1575]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10714559/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10714560/game.log)
[BRY_1969_01_01_17.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10714563/BRY_1969_01_01_17.zip)

### Describe the crash

On 27 Jan 1969 the game crashes to desktop, presumably after the west african war ends.

### Steps to reproduce / Cause of the crash

1. Load attached savefile
2. Snake around free france some more
3. Wait until ~27 Jan
4. Crash

### Additional information

I did give myself mil access to Cameroon with console commands because the railway was disconnected and it was pain pushing without supply but i have done nothing except that and didnt unpause while allowing diplomatic actions so i dont think its that

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by ender1324** [comment]
> Fixed in Dev Build

Can we download those from anywhere or are they private
