### ISSUE TITLE
State of Guangdong- Decision graphics not loading

### ISSUE THREAD

**Issue by alwod** [TNODevs/TNO-Bug-Tracker#1576]
### Operating System

Linux (Pop_OS!)

### HOI4 version

1.4.0

### TNO version

1.12.9.dOab(ed4b)(S)

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Some images do not appear in the decision tab. For example, during the Guangdong riots the large CCL graphic does not appear, and I can't do any actions against them as a result. Also during product cycles, I assume there is supposed to be an image of the product to the left of the product quality, interest ect. However it is just black empty space.

### Steps to reproduce / Cause of the issue

Issue was there from beginning

### Expected behaviour

Being able to hover over / click on graphic for more decisions

### Screenshots

![image](https://user-images.githubusercontent.com/42940272/218285400-db43b336-c7a9-4459-b740-baf756114159.png)

**Comment by Ovi05** [comment]
I have the same issue on KDE Neon, which makes me think this is a Linux-related issue.

**Comment by runelead00** [comment]
Fixed in Dev Build ^was partially a Linux issue being more sensitive to file capitalization than Windows
