### ISSUE TITLE
All - New Cultures Added Without Icons

### ISSUE THREAD

**Issue by BRUHADDICT4U** [TNODevs/TNO-Bug-Tracker#1577]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

I have noticed a few missing culture icons for the cultures that were presumably added in the hotfix they are as follows Frisian, Russian-Mordvin, Russian Wolgadeutsch, Khowar, Balti, Brahui, Urdu, Pahari, Garwhali, Kumaoni, Seraiki, Haryanvi, Braj, Malvi, Bagheli, Chhattisgarhi, Gondi, Maithili, Magahi-Santali, Sylheti, Tripuri

### Steps to reproduce / Cause of the issue

1. open the game
2. click on any of the provinces with these cultures 
3. notice the missing icons

### Expected behaviour

there to be icons!

### Additional information

again, not really a big issue but I do appreciate the new map work all the same GJ devs!

**Comment by Stormeagle449** [comment]
Fixed for patch 1.4.0b
