### ISSUE TITLE
South African War - Mandates Don't Establish

### ISSUE THREAD

**Issue by AloofGoof** [TNODevs/TNO-Bug-Tracker#1579]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.4.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, BBA

### Describe the bug

Only the OFN mandate of the last protectorate you capitulate creates a mandate.  This bugs the entire US run. 

### Steps to reproduce / Cause of the issue

Finish SAW war by capitulating the congo.

### Expected behaviour

Once SAW ends, only a single mandate is created.

### Screenshots

![congo](https://user-images.githubusercontent.com/98774134/218587129-1e821ce3-a36b-4783-a334-c9817cf4fa0a.png)

**Comment by AloofGoof** [comment]
[USA_1964_07_28_11.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10726821/USA_1964_07_28_11.zip)

**Comment by runelead00** [comment]
Should be fixed in hotfix uploaded a few minutes ago
