### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by thatsocialistgay** [TNODevs/TNO-Bug-Tracker#158]
**Questions**

- Operating System:
- HOI4 Version: Collie v1.10.8 (03e5)
- TNO Version: TNO v1.2.0a- Toolbox Theory
- Any other mods in use: n/a
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
 There is no airborne battalion options
**Steps to Reproduce/Cause Issue:**

1. Edit division template

2. Open all battalion options

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/94770612/142747290-fac7a222-a48d-45f5-9c0c-71bf405fe08f.jpg)
![image](https://user-images.githubusercontent.com/94770612/142747297-557d45ce-7f69-4f75-9d67-6c944c420465.jpg)
![image](https://user-images.githubusercontent.com/94770612/142747301-a3f1bf32-fa19-49dc-b517-4232cb5732c9.jpg)
![Uploading image.jpg…]()

**Comment by masterbobli** [comment]
Air assault battalions have now been moved to support companies.
