### ISSUE TITLE
Flags in DDS format

### ISSUE THREAD

**Issue by Polskers** [TNODevs/TNO-Bug-Tracker#1580]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.4.0a

### Do you have other mods in use?

Music Mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The file format of the following flags: GIB_CIA_paternalism, scorza_ISR are in .DDS format, when every other flag is in .TGA format.

### Steps to reproduce / Cause of the issue

Look in GFX/flags, you'll see.

### Expected behaviour

I am not sure if this prevents images from showing up in game properly due to their formatting.

### Screenshots

![Screenshot 2023-02-13 170716](https://user-images.githubusercontent.com/50228622/218594702-0d8324de-264c-4b58-9dff-2371e9bf90d5.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
