### ISSUE TITLE
All tags - Pollution and Safety do not have an effect in Admin. Expenditures

### ISSUE THREAD

**Issue by cyrilcredo** [TNODevs/TNO-Bug-Tracker#1581]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.9

### TNO version

1.4.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

No file needed.

### Describe the bug

Pollution and Safety do not have an effect when doing spending Admin. Expenditures through the Economy (Macro) mechanic.

### Steps to reproduce / Cause of the issue

1. Play any feature or non-feature tag.
2. Select Economy and go to Macro.
3. See the effect of Pollution and Safety in Admin. Expenditures.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_2](https://user-images.githubusercontent.com/96038418/218703239-dac7893d-18d2-4022-88a9-840eda235f5d.png)

![Untitled_1](https://user-images.githubusercontent.com/96038418/218703285-ab4d73a2-d2ff-496a-a2df-96c2e83b5866.png)

### Additional information

No.

**Comment by runelead00** [comment]
Fixed in UA
