### ISSUE TITLE
Iberia - Sevilla loc. mentioning the Gibraltar Dam

### ISSUE THREAD

**Issue by Vityviktor** [TNODevs/TNO-Bug-Tracker#1582]
### HOI4 version

1.12.9

### TNO version

1.4.0a

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Files

Sevilla localization (cities and landmarks button in Western Andalusia) still mentions the Gibraltar Dam in the text.

### List the loc issues below

![image](https://user-images.githubusercontent.com/95356445/218746176-7b0d3822-114c-4cb1-9a03-f0f6a6410c89.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
