### ISSUE TITLE
SERBIA -  State Name Issues

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1585]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.4.0a

### Do you have other mods in use?

Allegiances Submod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![image](https://user-images.githubusercontent.com/113797283/218812655-6f352b50-1e21-45b2-b2fd-2b6f2b9c35cf.png)

### Describe the bug

This Serbian state features two victory points with the exact same name in all language options

### Steps to reproduce / Cause of the issue

1) Open Game and play as any nation
2) Check the state 

### Expected behaviour

I think it should have a different name

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/218812868-a389ed1e-19d4-4086-84fd-0312fae4a025.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
