### ISSUE TITLE
England - Integration into the Pakt Decision

### ISSUE THREAD

**Issue by ItsRevanAgain** [TNODevs/TNO-Bug-Tracker#1588]
### Operating System

Windows 10

### HOI4 version

1.12.8

### TNO version

1.4.0a "Silicon Dreams"

### Do you have other mods in use?

Radio TNO, Soviet and Russian Music, Smaller Outlines, RGFX White Map Font.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After joining the Pakt (presumably it's the same for the OFN) the looping decision indicates a focus is completed, but there is absolutely no sign of these focuses, nor indication of what their affects are. 

### Steps to reproduce / Cause of the issue

1. Play as England
2. Go through the motions until the 'Atlantic Battleground' decisions appear.
3. Join the Pakt
4. Lose your mind as you wonder where the hell these "focuses" are.

### Expected behaviour

Why is there a focus branch missing?

### Screenshots

![image](https://user-images.githubusercontent.com/33811430/218887831-93aa85cf-4202-49c6-818e-e02d6c8fb176.png)
![image](https://user-images.githubusercontent.com/33811430/218888147-33e51132-883c-4a6b-b3cc-641c11097ee6.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
