### ISSUE TITLE
Gaemany - Hitler Didnt die and now Germany is in the SAW

### ISSUE THREAD

**Issue by jhonasmeili** [TNODevs/TNO-Bug-Tracker#159]
**Questions**

- Operating System: Windows 10
- HOI4 Version: the one that came out on 20/11/2021
- TNO Version: v1.2.0 'Toolbox Theory'
- Any other mods in use: one that disabled nukes, but i dont expect that the nuclear mechanics to be involved in the event that fires to have Hitler die, and the tno radio mod
- Were you using Steam? yes 
- Which expansions do you NOT have? i only lack the cosmetic and radio DLCs

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1. idk but i was playing burgundy and heydrich was named successor

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Haven't seen occur in any test and don't really have enough info. Marking as Stale and closing, might be do to updates/hotfixes that broke a save
