### ISSUE TITLE
Bormann Germany - Withdrawal from Africa and Cabal decisions 

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#1590]
### Operating System

Windows 10 

### HOI4 version

1.12.9

### TNO version

1.40a

### Do you have other mods in use?

Nope

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Won the war as Bormann in SA. Now I have the withdrawal UI pop up despite comitting to the conflict and there is no timer. Anti-Huttig cabal has appeared as well and is missing the strength bar and has no description. 

### Steps to reproduce / Cause of the issue

Bormmann win 

Win SAW and choose the left hand path on the focus tree to commit 

Bug as described above 

### Expected behaviour

No withdrawal and desc and bar for huttig cabal

**Comment by bigbadboy78** [comment]
Withdrew from SA as well and it had zero effect lmao as there was no timer and war was over.

**Comment by runelead00** [comment]
Fixed in Release Build
