### ISSUE TITLE
USA - Many of Wallace's focuses do not effect "Segregation Level" as stated

### ISSUE THREAD

**Issue by Sarhk777** [TNODevs/TNO-Bug-Tracker#1591]
### Operating System

Windows 10

### HOI4 version

1.12.9ab

### TNO version

1.4.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Many of the focuses and events intended to (and saying that they do) increase the "segregation level", used to determine impeachment and Wallace's mechanic, do not raise the level as indicated. This makes playing as Wallace nearly impossible unless you are intending to self-destruct.

### Steps to reproduce / Cause of the issue

1. Play the USA, get George Wallace elected.
2. Complete the focus "Enforce Segregated Funding" with a conservative supreme court.
3. Wait for the related events to fire
4. check segregation level in either Wallace's mechanic or in the save file; it will still be 0, when in previous patches it would be 2.

### Expected behaviour

Certain focuses should raise Wallace's segregation level

### Additional information

It is possible events were effected too, I don't have a way to check which events are _supposed_ to be increasing segregation.
The focuses effected include but are not limited to: "Enforce Segregated Funding", "Segregate the Curricula", "Segregation Belongs to the States", "The Government Shall Maintain Segregation", "Segregate Teacher's Pay", "Segregate State Subsidies", and "Segregated Job Corps."

Note that "Segregate Teacher's Pay" and "Segregate States' Subsidies" both also lower segregation expectation, which is still working.

I believe this is due to the removal of the `USA_TT_WAL_SEG_LOW`, `USA_TT_WAL_SEG_MED`, and `USA_TT_WAL_SEG_HIGH` scripted effects in _Toolbox Theory -- Unfinished Business_. An example of this can be seen by looking at the pre-TT:UB event `wallace.122`, which is when the Supreme Court allows the "Enforce Segregated Funding" Focus. The event previously triggered `USA_TT_WAL_SEG_MED`, raising segregation by 2, while neither the triggered effect nor the event's reference to it exist in the newer versions of TNO.

**Comment by Balkanoid** [comment]
Also the segregation level decreases even if you choose to segregate social security and Medicare

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
