### ISSUE TITLE
Hmmlr is not fireing the win event 

### ISSUE THREAD

**Issue by Memelord058** [TNODevs/TNO-Bug-Tracker#1594]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Hmmlr

### Steps to reproduce / Cause of the issue

I dont know how it happen 

### Expected behaviour

For hmmlr to turn into england

### Additional information

Can I have the event id

**Comment by Stormeagle449** [comment]
Fixed in current build.
