### ISSUE TITLE
Germany/England - Thatcher allignment minigame not working properly 

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#1595]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.40a

### Do you have other mods in use?

None 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Thatcher mini game is not working properly. When I take some decisions they give me no progress and North Sea excercises does literally nothing (No uptick in support over time). Atm I have been stuck on it at 13 or so influence and England is way ahead with 115 (Still hasnt formed its own sphere either). OFN is also not going up in influence so must be having issues on their end as well with decisions. Whole thing is just straight up botched and needs fxing. Also, on a diff note, Colombian intervention event has no Desc just a blank decision which adds it to the GUI. 

### Steps to reproduce / Cause of the issue

Thatcher wins war 

allignment minigame starts 

some decisions have no effect for germany and what seems like OFN (North Sea ecercises and others)

England influence keeps on growing but never gets independent sphere  

### Expected behaviour

Minigame works as previously

**Comment by bigbadboy78** [comment]
England finally went independent. However the minigame window didnt ever go away so im stuck with all the decisons lol

**Comment by AcornSap** [comment]
I've been having this problem too. Have you been able to find a solution to this glitch? or should I wait for the time being?

**Comment by runelead00** [comment]
Fixed in Dev Build
