### ISSUE TITLE
Belarus - Annexation of Germany, Ireland and Madagascar

### ISSUE THREAD

**Issue by LostSamurai155** [TNODevs/TNO-Bug-Tracker#1598]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

1.4.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10769092/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10769093/error.log)
[Save Game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10769119/Save.Game.zip)

### Describe the bug

At the date of the save game I noticed that the Belarusian Council annexed the entirety of Germany, Netherlands, Denmark, Ireland and Madagascar. They also had what seemed to be their army as well. It could have happened earlier in the game but I never noticed.

### Steps to reproduce / Cause of the issue

No clue honestly I only just noticed it, a dev told me it was meant to be fixed in patch 1.4.0a so I'm taking a guess that the cause of the issue has been discovered.

### Expected behaviour

For Germany and the other countries not to be annexed by Belarus

### Screenshots

![image_2023-02-17_180330343](https://user-images.githubusercontent.com/70176382/219717263-c74c004f-3450-406f-a6e6-6496ab140cab.png)

**Comment by runelead00** [comment]
BLR nerfed even more
