### ISSUE TITLE
TNO Issue: Game Crashes When Load In

### ISSUE THREAD

**Issue by HOI4User** [TNODevs/TNO-Bug-Tracker#1599]
### Operating System

Windows 10

### HOI4 version

1.12.9

### TNO version

v1.4.0a

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

error.log https://www.mediafire.com/file/xfq2ckgo8xtv5iy/error.log/file

### Describe the crash

I Started The Game Using The Paradox Launcher When I Put The MOD In. It Goes Normal And It Loads To The Starting Menu. I Click Singleplayer > New Game > TNO.
I decide to play as Germany, and then i click Start.
It loads in and then the problem strikes.
I load into the map and then i get the introduction part.
Then my game starts loading and then it crashes.
And i get the Paradox Crash Report.

### Steps to reproduce / Cause of the crash

1. Look At My Issue.
2. Investigate.
3. Find The Problem.
4. Fix it.

### Additional information

[ No Additional Information ]

**Comment by runelead00** [comment]
See #962 Issue merged there
