### ISSUE TITLE
India - 1972 Election Candidates lack Portraits

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1601]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0a

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![image](https://user-images.githubusercontent.com/113797283/219852593-7c097686-30a8-4c90-bd61-73b2d0056487.png)

### Describe the bug

Character IND_amar_nath_vidyalankar lacks a portrait
Character IND_neelam_sanjiva_reddy lacks a portrait
Character IND_mani_ram_bagri lacks a portrait
Character IND_n_g_ranga lacks a portrait
Character IND_raghu_vira lacks a portrait
Character IND_atal_bihari_vajpayee lacks a portrait

### Steps to reproduce / Cause of the issue

1) Tag into India
2) Type into debug the election events for the year 1972, IND_skeleton.8 and IND_skeleton.9

### Expected behaviour

The expected behavior is that they would have portraits.

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/219852849-4922869e-dabd-4e7d-99f0-53d8ba5b5fc3.png)

**Comment by Stormeagle449** [comment]
Fixed for The Ruin update.
