### ISSUE TITLE
Transbaikal Principality - Name Reversion at unification state

### ISSUE THREAD

**Issue by ItsRevanAgain** [TNODevs/TNO-Bug-Tracker#1602]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.1 "Silicon Dreams"

### Do you have other mods in use?

Radio TNO, Soviet and Russian Music, Smaller Outlines, RGFX White Map Font.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Upon going through each stage of unification, the focus tree and name changes accordingly, but when you finally unify Russia, the name reverts back to Warlord stage name, with the regional focus tree. 

### Steps to reproduce / Cause of the issue

1. Play Transbaikal
2. Go through the unification motions
3. Unify Russia

### Expected behaviour

Name should become Russian Empire?

### Screenshots

![image](https://user-images.githubusercontent.com/33811430/219856289-9b798fe8-f31a-469f-91a2-d56eb119b0c7.png)
![image](https://user-images.githubusercontent.com/33811430/219856311-2805ce5a-0669-433b-906a-a961dc5fce89.png)

**Comment by runelead00** [comment]
Fixed in Dev BUild
