### ISSUE TITLE
GNG - the flag GNG_IJA_full is upside down

### ISSUE THREAD

**Issue by HeHeSkyWolf** [TNODevs/TNO-Bug-Tracker#1604]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The flag GNG_IJA_full is upside down.

### Steps to reproduce / Cause of the issue

1. ~
2. set_cosmetic_tag gng gng_ija_full

### Expected behaviour

Showing the flag correctly.

**Comment by runelead00** [comment]
Fixed in Dev Build
