### ISSUE TITLE
24th NRA Army - Liu Wenhai Localization issue

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1609]
### HOI4 version

1.12.10

### TNO version

1.4.0a

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/220111496-37219ae8-449c-4a27-a9a3-11094295f353.png)

In his leader description's second paragraph, it is mentioned that he took up camp in the small city of Ya'an and has remained in it ever since. As it can be seen in the attached pic, he does NOT control Ya'an and has not since the Sichuan border changes a while back. Instead, his capital is in Xichang.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
