### ISSUE TITLE
Colombia - Colombo-American Negotions Loc issues

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1610]
### HOI4 version

1.12.10

### TNO version

1.4.0a

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/220162512-2ccf0118-a3a4-4466-90b5-2a0a65c8d4ca.png)
The button localization for this event misspells "they" as "they"

![image](https://user-images.githubusercontent.com/113797283/220163052-e17f5672-9453-4d21-b26a-b01e590a8fd7.png)
![image](https://user-images.githubusercontent.com/113797283/220163289-d59fb4f2-a918-4599-b3a7-72c65b0ee1fc.png)
![image](https://user-images.githubusercontent.com/113797283/220163394-25d5bfbf-1f64-4fae-82ad-15b4f246767a.png)
![image](https://user-images.githubusercontent.com/113797283/220163471-794399a6-aa87-419e-92b7-30f4aaf6b50b.png)
![image](https://user-images.githubusercontent.com/113797283/220163551-c129976d-1f98-4bb4-844d-96a3658dd97b.png)

All of the negotiations events lack description loc.

**Comment by runelead00** [comment]
Fixed in Dev Build
