### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by TheYugoslavGuyreal** [TNODevs/TNO-Bug-Tracker#1612]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

19 Feb update

### Do you have other mods in use?

Maximum Construction Slots, 50 Construction slots, player led peace deal, fps map, unit icon revamp, recall Volunteers, colourblindness mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I Cant build any Military nor Civilian Factories

### Steps to reproduce / Cause of the issue

1. Start Game
2. Launch a Singleplayer Campaign
3. pick any Russian warlord
4. go to Construction Tab
5. finding no Civ or Mil Factory Icons

### Expected behaviour

i dont know

### Additional information

Can´t build any Mil or Civ Factories nor see the icons to do so

**Comment by runelead00** [comment]
TNO doesn't use the traditional civ and mil factories of vanilla, you have to assign PUs to each in that specific subtab, there are large, moving red arrows pointing to it when you open the construction or econ tabs
