### ISSUE TITLE
All - Hospital Tooltip Broke

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1613]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/220454631-32d08578-44db-4853-8857-9e2d8af6c45a.png)
The Dynamic coloured text for Hospitals is broken, showing an exclamation mark after the word due to it not being closed properly.

**Comment by runelead00** [comment]
Fixed in Dev Build
