### ISSUE TITLE
USA - RFK Social Security Act Focus Unable to complete normally

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#1614]
### Operating System

Windows10

### HOI4 version

1.12.10

### TNO version

v1.4.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When RFK clicks on the Social Security Act Focus, after a day, the Focus will be canceled. Then the Focus can never be completed.
![image (3)](https://user-images.githubusercontent.com/46292981/220506317-22a542db-ad56-4244-9c92-b2d244c54397.png)

### Steps to reproduce / Cause of the issue

1.Play through RFK Presidency until you reach the Social Security Act Focus.
2.Click on the focus

### Expected behaviour

Social Security Act Focus able to complete normally

### Additional information

In addition, I found some bugs with Hart and gave my own suggestions for Hart.
https://github.com/TNODevs/TNO-Bug-Tracker/issues/1560
https://github.com/TNODevs/TNO-Bug-Tracker/issues/1564
https://github.com/TNODevs/TNO-Bug-Tracker/issues/1561

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
