### ISSUE TITLE
USA - "Escape" Event Loc Issue

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1616]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/220653421-bac41f29-1af0-49bd-935f-fab0414ecfed.png)
In this event, in the last paragraph, I believe the correct phrase would be "When they came FOR him", not "FROM him"

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
