### ISSUE TITLE
USA Oil Crisis Saudi Tree - Broken Loc

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1619]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/220957990-1a6d8c4b-4d87-4be3-993f-8f882ac3842b.png)
As you can see here, the national ideas that the allied OFN nations get have broken localization

**Comment by runelead00** [comment]
Fixed in Dev Build
