### ISSUE TITLE
USA - Crash When Winning the Madagascar War

### ISSUE THREAD

**Issue by armymooseg** [TNODevs/TNO-Bug-Tracker#162]
- Operating System: Windows 10
- HOI4 Version: 2021.9
- TNO Version: Toolbox Theory
- Any other mods in use: State Transfer, Custom Country Paths, Nuclear War Gamerule, Toolpack Updated
- Were you using Steam? Yes
- Which expansions do you NOT have? NSB

**Longer Description of Issue:**
While playing as the US during the Madagascar war, once you achieve victory the event fires then proceeds to crash the game moments later.
**Steps to Reproduce/Cause Issue:**

1. Play as US

2. Win Madagascar

**Comment by masterbobli** [comment]
It is quite possible that the custom country paths submod caused this issue as it hasn't been updated to be compatible with TT yet. Please check whether it still causes the same issue with the submod disabled.

**Comment by armymooseg** [comment]
> It is quite possible that the custom country paths submod caused this issue as it hasn't been updated to be compatible with TT yet. Please check whether it still causes the same issue with the submod disabled.

ive been playing with that mod on. I've heard that it has been causing problems so ill check

**Comment by runelead00** [comment]
Issue no longer occurs on current builds of TNO, might have been a CCP as suggested above

**Comment by armymooseg** [comment]
> 

Yeah once that was suggested and I tried everything was smooth again, thank you guys for helping out
