### ISSUE TITLE
West African War - Three Way Bugs

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1620]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Bug 1) As you can see in the first screenshot, when I beat the West African Alliance, the state held by Fuuta Fulba was given to a resurrected Sokoto
Bug 2) Please disregard the border changes, switched the position of Kayes and Mali so the war would be more equal
Bug 3) When you finish the WAW, the war does not actually end, the Proxy War decision category did not go away, but the African Quagmire mission did and I did not get a reconstruction.

### Steps to reproduce / Cause of the issue

1) Play as the US through the WAW 3 Way Scenario Proxy war
2) Experience the three bugs by winning the war

### Expected behaviour

You would think that the state would be given to the proper nation and the peace conference would properly end the war

### Screenshots

Bug 1

![2023-02-22 23_12_59-Greenshot](https://user-images.githubusercontent.com/113797283/220971347-a0cd0193-6fa3-49f3-8ef4-fa0ba14f4bba.png)

BUG 2 and 3
![2023-02-22 23_17_49-Greenshot](https://user-images.githubusercontent.com/113797283/220971153-5a8bec10-579c-45a2-b6fd-3204060a3b88.png)

### Additional information

Order of capitulation: Guinea - Fuuta Fulba - Wolofia - Jolo - Mali - Niger - Cameroon

**Comment by runelead00** [comment]
Should be Fixed in Dev Build
