### ISSUE TITLE
Germany - No focus tree in Goering’s Germany and German Civil War does not end

### ISSUE THREAD

**Issue by dogeater321** [TNODevs/TNO-Bug-Tracker#1621]
### Operating System

Windows 11

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Goering’s Germany has no focus tree and German civil war does not end after defeating the other 3 factions

### Steps to reproduce / Cause of the issue

1. Play as Germany and select Goering as successor
2. Start the German Civil War as Goering’s Germany 
3. Defeat all 3 opposing factions in the civil war

### Expected behaviour

There should have been a focus tree when playing as Goering’s Germany and the war should have ended after defeating the other factions

**Comment by Jack121Q** [comment]
Goering's content has been removed pal.

**Comment by runelead00** [comment]
Goering has been removed with SD, selecting him as successor is now disabled for next hotfix
