### ISSUE TITLE
JAP - Doesn't get +75 Cold War points for small Malaysian Insurgency victory 

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1624]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10846301/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10846302/error.log)

### Describe the bug

After Japan's small victory in the Malaysian Insurgency (insurgents repelled, territory kept, reduced to rump state) America gets -75 Cold War points for their loss, but Japan doesn't receive +75 for their victory.

### Steps to reproduce / Cause of the issue

1. Have the Malayan Insurgency end in a small victory for Japan.
2. Open Cold War GUI.
3. Observe issue.

### Expected behaviour

Japan would receive +75 Cold War points in their victories tab in the Cold War GUI.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/221747123-af1b8bed-abe8-490c-b03e-e23d0ce46c87.png)
![image](https://user-images.githubusercontent.com/98370487/221747221-88efadde-1278-480a-9a9f-0d91f4283f5c.png)
![image](https://user-images.githubusercontent.com/98370487/221747323-b0a35760-51dc-43fe-a61e-01b373339eff.png)

**Comment by runelead00** [comment]
Fixed
