### ISSUE TITLE
OST - Missing Grammar

### ISSUE THREAD

**Issue by Polskers** [TNODevs/TNO-Bug-Tracker#1625]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0a

### Do you have other mods in use?

Music Mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Ostland is missing a letter (should read "The" instead of 'he') in the decisions screen in first photo.

In second photo, there is overlap between the economy type and the centralisation/decentralisation bar.

### Steps to reproduce / Cause of the issue

Start the game and look at the decisions tab and the economy tab.

### Expected behaviour

The grammar should be fixed and maybe the text somehow fixed on the economy tab but that might require UI rework.

### Screenshots

![Screenshot 2023-02-28 231855](https://user-images.githubusercontent.com/50228622/222052142-d496cc45-9ab6-4483-9841-5d87401774ad.jpg)
![Screenshot 2023-02-28 231827](https://user-images.githubusercontent.com/50228622/222052152-fb93cf3e-10c6-44b6-8024-657f5a0b38c6.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
