### ISSUE TITLE
MAG/AMR - Integrate Commanders

### ISSUE THREAD

**Issue by ItsRevanAgain** [TNODevs/TNO-Bug-Tracker#1627]
### HOI4 version

1.12.10

### TNO version

v1.4.0b "Silicon Dreams"

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Magadan and Amur have a rather woeful roster to start off with, so why not allow either splinter to integrate each other's staff upon defeating each other. 

### Justifications

Before the SMUTA introduction, Magadan and Amur had a couple of focuses whereby after defeating each other and Transbaikal, they would grab a handful of generals to bolster their woeful number.

For Magadan and Amur this also provides another caveat where if you decide to 'purge' Okhotin, and go with Petlin in Magadan you lose Pavlov, bollocking yourself even more to just THREE commanders each. 

I can understand why not allow Amur of all to use the Tsarists, but Matkovsky is far more pragmatic, and couldn't really care less what their previous affiliations were so long as they are talented and loyal.

**Comment by runelead00** [comment]
Implemented on Smuta occupation decisions in Dev Build
