### ISSUE TITLE
Uruguay - Gamerules Loc

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1628]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/222511317-b11e6c7c-2924-4c28-ab71-68663d97c8ca.png)
The requirement for this gamerules is listed as "Marsizt Coup" instead of Marzist.

**Comment by Tarepa** [comment]
fixed in Dev Build
