### ISSUE TITLE
PRC - "Expanding Conscription" focus changes two years draft to one year draft

### ISSUE THREAD

**Issue by helehal** [TNODevs/TNO-Bug-Tracker#163]
**Questions**

- Operating System: window 10
- HOI4 Version: Latest
- TNO Version: 1.20
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have?
All except Death or Dishonor
**Longer Description of Issue:**
The focus "Expanding Conscription" in the Mengjian war tree reduces the draft from two years to one year, reducing conscription by 1%
**Steps to Reproduce/Cause Issue:**

1. Finishing the "Expanding Conscription" Focus

**Screenshots:**
![2021-11-20 (1)](https://user-images.githubusercontent.com/63805017/142749667-4f0b165d-947a-471c-8e86-516cad1db81c.png)

**Comment by runelead00** [comment]
Fixed in Current Release
