### ISSUE TITLE
Zhdanov Gamerules - Loc

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1630]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/222895496-6237e374-6b6c-47f6-af36-c55e2cfebfd3.png)
As you can see here, Chelomey's name is spelled "Chelomey" in the gamerules title and "Chelomei" in the gamerule's description. I believe only one form of his name should be used.

**Comment by Tarepa** [comment]
fixed in Dev build
