### ISSUE TITLE
Samara Gamerules - Loc

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1631]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/222896039-a19d6699-61a4-4cc1-a5b0-a2959e6a311e.png)
As you can see here, this gamerule says that under Zykov, Samara's ideology will be "Military Junta", however that is factually incorrect even before Vlasov dies.

The moment Zykov is selected as Vlasov's successor in the first focus tree, Samara's ideology becomes "Controlled Democracy". Please correct this gamerule's description.

**Comment by Tarepa** [comment]
fixed in Dev build
