### ISSUE TITLE
Goering's Germany during the Civil does not have a focus tree.

### ISSUE THREAD

**Issue by Fougthless** [TNODevs/TNO-Bug-Tracker#1632]
### Operating System

Windows 11

### HOI4 version

the current version as of March 4, 2023

### TNO version

1.4.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

file:///C:/Users/kaema/OneDrive/Documents/Paradox%20Interactive/Hearts%20of%20Iron%20IV/logs/game.log 
file:///C:/Users/kaema/OneDrive/Documents/Paradox%20Interactive/Hearts%20of%20Iron%20IV/logs/error.log

### Describe the bug

The main bug is that when playing as Goring's Germany during the Civil war there is no focus tree for the nation. There are other smaller bugs like Goring breaking away, the event where Goring tries to become Furer but can not does not happen, for the last two focus before Goering invokes Hitlers name do not have a description or effect they just say "This focus currently has no effect", and most the focuses between the focus called the Militarist and Invoke Hitlers Name have this weird peace of text which should not be their which says "Invalid event with id: goering_successor.?" (the question mark just means there is a number there). In general it seems as if the game does not recognize that I am going the Goering route in the German civil war.

### Steps to reproduce / Cause of the issue

As Germany when you are picking the successor pick Goering and then play the game normally and then you will see these glitches.

### Expected behaviour

I expect it to act normally with their not being those weird texts, with the event popping up, with Goering not breaking away, with those focuses doing something, and (most importantly) their being a focus tree for Goering's Germany during the Civil War.

### Screenshots

![Hearts of Iron IV (DirectX 11) 3_3_2023 7_52_12 PM](https://user-images.githubusercontent.com/126918953/222902462-497ab75b-d552-42ad-9986-0a04467fe73b.png)
![Hearts of Iron IV (DirectX 11) 3_3_2023 7_52_01 PM](https://user-images.githubusercontent.com/126918953/222902470-c5ac31ec-b701-4630-adc3-cf3964b31bc8.png)

**Comment by Fougthless** [comment]
I just noticed that Goering breaking away was not a bug.

**Comment by Fougthless** [comment]
Also when or if  you win the civil war you still can not form Germany since the event which makes Goring's Germany into Germany does not appear for some reason.

**Comment by runelead00** [comment]
Goering has been removed with SD, selecting him as successor is now disabled for next hotfix
