### ISSUE TITLE
Jordan - Party lacks name

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1633]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/222915511-f7813c87-b737-41e7-9a79-5ae91e65757a.png)
As you can see in the screenshot attached, the Communist party for Jordan lacks a name, this is relevant since it can take power if the Harakiyyin coup takes place after the Jerusalem Conference fails.

**Comment by Stormeagle449** [comment]
Fixed in current version.
