### ISSUE TITLE
Germany - Colombian Civil War Decision Bug

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1634]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

As you can see in the screenshot attached, this decision increases maximum planning by 1500% instead of...a regular value.

### Steps to reproduce / Cause of the issue

1) Play as Germany until the Colombian Civil War
2) Check the decision

### Expected behaviour

You'd expect the value added to be less than 1500%

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/222923042-7467a20f-c83b-49c0-8b7d-884b28d744df.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
