### ISSUE TITLE
Bulgaria - Wrong Party Name

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1635]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/222952765-95eeb41f-9d4f-45b5-a274-34d2c83a24ca.png)
As you can see in the image attached, the name of the ruling party if King Simeon takes charge following the Macedonian Quiet and the preservation of the Monarchy is "Zveno", this is wrong as Zveno is one of the primary Anti-Regime groups in Bulgaria and can take power, ousting the Tsar in another path. Please rename the ruling party in this case.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
