### ISSUE TITLE
Invasion of Fuuta Fulba - Broken Peace-deal

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1637]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

As you can see in the screenshots shown, following the invasion of Fuuta Fulba, the peace deal did not work, giving the land to Wolofia.

### Steps to reproduce / Cause of the issue

1) Have the French Military Alliance win the FMA vs PALF scenario
2) Wait until Fuuta Fulba is invaded and defeated

### Expected behaviour

The expected behavior is that Mali or Free France would gain the region and have it as a core.

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/222954310-d5576fd1-3e74-472e-a810-a9701f52b3af.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
