### ISSUE TITLE
Free French Invasion - Decision Loc

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1638]
### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/113797283/222954977-de57ae14-2d5d-4153-8f00-ca905fce84a5.png)
As you can see here, this decision has broken loc.

**Comment by runelead00** [comment]
Fixed in Dev Build
