### ISSUE TITLE
Free French Invasion - White Peace not Triggering

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1640]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

As you can see in the screenshot attached, even though Free France and the French Resistance have been capitulated, the French State is still at war, the African members of the French Community not having received a White Peace.

### Steps to reproduce / Cause of the issue

1) Play through the Free French Invasion
2) Have the French State win
3) Check the French State's Diplomacy

### Expected behaviour

You'd expect the West African Staates to have received a White Peace upon the capitulation of Free France.

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/222955623-3cdfee53-a8bb-4fc2-aa79-dd4f95b5fb7c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
