### ISSUE TITLE
Arab Republic of Yemen - Port of Aden remains in Italian Hands after the Civil War

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1643]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The bug is that the Port of Aden is not given to the Arab Democratic Republic of Yemen after they win the Civil War and defeat the Pro-Italy Faction

### Steps to reproduce / Cause of the issue

1)Play until the Oil Crisis
2) Have the Baathists win in Yemen
3) Check the state

### Expected behaviour

You'd expect them to take the Port of Aden after winning the Civil War

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/222958894-dd37a8c5-e3c7-4706-a445-67efd8137fb8.png)

**Comment by runelead00** [comment]
Current WAD, subject to change in PW
