### ISSUE TITLE
Speer's Germany - Slave Revolt not receiving State

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1646]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The issue is that the state of Bergkarabach is not transfered to the Slave Revolt when they take control of Kaukasia. Leaving only it and Baku, which is meant to stay, for Kaukasia

### Steps to reproduce / Cause of the issue

1) Play as Speer all the way to the Slave Revolt
2) Look at Kaukasia after the Slave Revolt takes control of it and before the Freikorps rise up

### Expected behaviour

You'd expect them to also receive this isolated state, thus only keeping Baku

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/223172721-5be79752-8a9d-4319-8d6e-73a70ce57c5a.png)

**Comment by runelead00** [comment]
Fixed in Dev Build by SocijaldemokratTudjman
