### ISSUE TITLE
brazil-Kubitschek  outdated foues tree icon 

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#1647]
### Operating System

windows 11

### HOI4 version

1.12.10

### TNO version

v1.4.0b

### Do you have other mods in use?

Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Kubitschek focus "south American support" icon has a Brittany flag  

### Steps to reproduce / Cause of the issue

icon outdated

### Expected behaviour

Kubitschek focus "south American support" icon has a Brittany flag

**Comment by runelead00** [comment]
Fixed in Dev Build
