### ISSUE TITLE
OFN Congo Spawning Capitulated

### ISSUE THREAD

**Issue by TornadoADV** [TNODevs/TNO-Bug-Tracker#1648]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

OFN Provisional Government Congo cannot start it's focus tree as it's considered capitulated and remains present for an entire playthrough.

### Steps to reproduce / Cause of the issue

1. Click on OFN Congo National Focuses as USA
2. Highlight any National Focus
3. See the error of "Cannot select focus when capitulated"

### Expected behaviour

OFN Congo's National Focuses to work.

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
