### ISSUE TITLE
United States - South Carolina has two of the same senators (Democrats) 

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#1649]
### Operating System

Windows 11

### HOI4 version

1.12.10 (Operation Sabre)

### TNO version

1.40.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

self-evident bug.

### Describe the bug

South Carolina has two of the same senators. (Democrats)

### Steps to reproduce / Cause of the issue

1. Play USA
2. Get Democrats to win both senate seats at South Carolina
3. They're the same senator. 

### Expected behaviour

The senators to be different. 

### Screenshots

![image](https://user-images.githubusercontent.com/94796674/223260448-68a35ed6-a34c-4ed5-93ba-157d0366f560.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
