### ISSUE TITLE
USA - Nearly 50 of the same news event

### ISSUE THREAD

**Issue by GrievingOhio150** [TNODevs/TNO-Bug-Tracker#165]
**Questions**

- Operating System: G5 5500
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use: No
- Were you using Steam? yes
- Which expansions do you NOT have? I have all

**Longer Description of Issue:**
I was playing as America, just getting into the South African War, and when the 1964 Winter Olympics news event appeared, it then lagged my pc, so i paused the game. It then sent the event about 50 different times all at once, and also hurt my ears.

**Steps to Reproduce/Cause Issue:**

1. Play america

2.reach 1964 ~February 6th

etc...

**Screenshots:**
Unfortunately none

**Comment by GrievingOhio150** [comment]
![image](https://user-images.githubusercontent.com/77766898/142750598-08edc8da-1762-4a14-8fa4-82e9a4d5db11.jpeg) heres a screenshot

**Comment by masterbobli** [comment]
Fixed in latest released. Thanks for reporting.
