### ISSUE TITLE
Far as I know every country - when I leave a game something happens and I don't know how to fix it

### ISSUE THREAD

**Issue by Con7484** [TNODevs/TNO-Bug-Tracker#1650]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[hoi4 log.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10915223/hoi4.log.zip)

[USA_1964_08_28_09.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10915259/USA_1964_08_28_09.zip)

### Describe the bug

the game will remove all my divisions that I've made and will let me do stuff but will crash usually 5 -7 mins later for no apparent reason after turning my pc off or leaving the game.

### Steps to reproduce / Cause of the issue

1. Turn off pc or leave game 2. Start game 3. Load save 4. After waiting a few in game days it will slow then crash 5. Divisions are either deleted or the entire bar is gone.

### Expected behaviour

I expected to be able to play my save after school cause it was late at night

### Additional information

If there is a way to fix this on my own, please tell me if your able to

**Comment by Jack121Q** [comment]
Your save-file got corrupted. Try disabling cloud saves and use only local saves. That tends to fix the issue (at least for me). TNO interacts weird with the Cloud.
