### ISSUE TITLE
United States - NPP-N Senator in Virginia has a bugged name. 

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#1651]
### Operating System

Windows 11

### HOI4 version

1.12.10 (Operation Sabre)

### TNO version

1.40.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The senator has a bugged name probably due to a mistype when doing the senator's name code. This happened after the 1972 elections. 

### Steps to reproduce / Cause of the issue

1. 1972 elections in Virginia, have it been won by the NPP-N. (note this might not even be exclusive to 1972)
2. You will see the bug. 

### Expected behaviour

An actual name should be present, not code. 

### Screenshots

![image](https://user-images.githubusercontent.com/94796674/223794861-4e38b9c6-f8be-4ed6-9a0b-2430e915859e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
