### ISSUE TITLE
Guangdong - AI Stuck on Morita's Oil Crisis Focus Tree

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1652]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_1973_06_17_13.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/10945624/GER_1973_06_17_13.zip)
Cheats were used but not on Guangdong. I swear

### Describe the bug

The bug is that almost 3 years later, Guangdong is still stuck on their Oil Crisis tree. They seem to have just...decided not to do the focus shown in the pic.

### Steps to reproduce / Cause of the issue

1) Let the AI play as Guangdong all the way until the Oil Crisis
2) Have them choose Li's plan on the right side of the tree

### Expected behaviour

You'd expect the AI to...do their focus tree?

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/224417396-b6cb25a2-13e5-4ba3-8c83-e34695109529.png)

**Comment by runelead00** [comment]
Should be fixed in Dev Build
