### ISSUE TITLE
SPR - Spanish Republic randomly turns into the Kingdom of Spain during Iberian Wars (or at least still uses Republican flag)

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1653]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10947048/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10947049/game.log)

### Describe the bug

As the Iberian Wars were ongoing, I noticed that randomly the Spanish Republic decided to switch color and name to the Kingdom of Spain. This took place some time after the Iberian government capitulated, if that has anything to do with it. They also have the national spirit of Juan III, so I'm not sure if this is planned, though they still use the Republican flag.

### Steps to reproduce / Cause of the issue

1. Start the Iberian Wars.
2. Iberian government falls.
3. Observe issue.

### Expected behaviour

Spain retains the name Spanish Republic, or if this is planned their flag would switch away from the Republican one.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/224455031-7694d66a-3dcd-49ba-9893-588600e45db9.png)
![image](https://user-images.githubusercontent.com/98370487/224455049-b8f3c724-3a5f-4725-a0c1-fcf0647888bc.png)

**Comment by runelead00** [comment]
Fixed in Dev Build, flag was in the wrong format
