### ISSUE TITLE
Finland - Red Finland Cores Not Removed after Civil War

### ISSUE THREAD

**Issue by Jack121Q** [TNODevs/TNO-Bug-Tracker#1654]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

Allegiances Submod, Toolpakt, State Transfer Tool, Dynamic Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The bug is that Red Finland's cores are not removed from Finnish State after they are defeated in the Civil War.

### Steps to reproduce / Cause of the issue

1)Play through the game and have the Finnish Civil War happen
2) Have National Finland win and defeat Red Finland

### Expected behaviour

You would expect Finland's Civil War to follow the standard and remove the cores of the faction that lost following it's defeat and the end of the Civil War

### Screenshots

![image](https://user-images.githubusercontent.com/113797283/224545926-290f92d7-6fb0-41fe-967b-95a29e0e884c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
