### ISSUE TITLE
IRK - "The Union Triumphant" event fires twice after Far East unification.

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1655]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10951254/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10951255/game.log)

### Describe the bug

After uniting the Far East as Irkutsk and doing the final focus in the Smuta tree, instead of showing the event "The Union Triumphant" only once it shows it twice.

### Steps to reproduce / Cause of the issue

1. Unite Far East as Irkutsk and complete final Smuta focus.
2. Observe issue.

### Expected behaviour

Event appears only once.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/224554217-d2fa888e-f3d8-4f8f-91b8-7d9c931e5fda.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
