### ISSUE TITLE
MOC + SNM - No one lives in Monaco or San Marino.

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1657]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10952047/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10952048/game.log)

### Describe the bug

Both countries have a population of 0.

### Steps to reproduce / Cause of the issue

1. Start game.
2. Observe issue.

### Expected behaviour

Both countries have some sort of population.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/224572491-60061e68-2269-4f72-97a4-5bba1cae9d51.png)
![image](https://user-images.githubusercontent.com/98370487/224572515-f08a6222-e3bd-4797-b892-90c4ada1b3bc.png)

**Comment by Stormeagle449** [comment]
Fixed in dev build.
