### ISSUE TITLE
[Bug]: Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by VicT0r2** [TNODevs/TNO-Bug-Tracker#1658]
### Operating System

Windows 11

### HOI4 version

1.12.11

### TNO version

1.4.0a

### Do you have other mods in use?

TNO: Operation Deep Freeze

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Describe the bug

So during the slave revolt, that war loving German dude commit coup at the Moskowien, and soon after Speer forcesattack from Petersburg and reclaim it. Except, after they destroy war lover and replace him with the older guy (Alexis or smth) some provinces in republic of India and Japanese puppet India are given to the new Moskowien

### Steps to reproduce / Cause of the issue

1. Play as any Russian Warlord state (Not sure if it's necessary but I was playing as Samara)
2. Speer should win the GCW
3. Play the game until Slave revolt
4. Speer is not ousted by the War loving general guy and takes back Moskowien with force
5. After Moskowien is reclaimed some provinces in India is given to Moskowien

### Expected behaviour

Provinces in India should not be given to Moskowien

**Comment by runelead00** [comment]
Fixed in Dev Build
