### ISSUE TITLE
Second Philippine Republic - State Name Typo

### ISSUE THREAD

**Issue by ReetheBro** [TNODevs/TNO-Bug-Tracker#166]
**Questions**

- HOI4 Version: 1.10.8 Collie
- TNO Version: 1.2.0a
- Any other mods in use: None

Loc issues:

- [x] 1. Western Visayas (Kanlurang Bisayas) spelled as "Kanrulang"
![hoi4_3](https://user-images.githubusercontent.com/94774585/142750785-e19f683e-2af3-4dc4-b155-501ba0fe86e4.png)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
