### ISSUE TITLE
Brazil - Che Guevara was held in Chile, not Argentina

### ISSUE THREAD

**Issue by Cataline21** [TNODevs/TNO-Bug-Tracker#1660]
### HOI4 version

1.12.11

### TNO version

1.4.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![BRA Loc Issue](https://user-images.githubusercontent.com/93746733/225797337-3ecd4a8c-af61-4548-947d-e5ffda519328.png)

In the event "The Agitator Issue," which Brazil gets after Che Guevara attends the Marxist conference in Uruguay, General Denys references the Argentinians having him "in their hands." In the current version of TNO Che Guevara is released from Chile, not Argentina, so this line doesn't make sense.

**Comment by runelead00** [comment]
Fixed
