### ISSUE TITLE
Moskowien - Bobriki

### ISSUE THREAD

**Issue by Computer64** [TNODevs/TNO-Bug-Tracker#1662]
### HOI4 version

1.12

### TNO version

1.4.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### List the loc issues below

![image](https://user-images.githubusercontent.com/92990434/226116586-2803a5ea-9f73-4695-88b5-9a6527546edc.png)
![image](https://user-images.githubusercontent.com/92990434/226116683-35603fd7-32d4-4d9c-9fad-cefc36a1d047.png)

### Additional information

Russian name of Bobriki doesn't show (only code).

**Comment by runelead00** [comment]
Fixed in Dev Build
