### ISSUE TITLE
Germany, Gorings path doesnt work 

### ISSUE THREAD

**Issue by Flagstaffery** [TNODevs/TNO-Bug-Tracker#1663]
### Operating System

Windows 11

### HOI4 version

1.12.11

### TNO version

v1.4.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11010819/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11010820/game.log)

### Describe the bug

While looking at the focus during the power struggle for Gorings focus tree the events are loading improperly and after Goring wins the civil war the event for Speidel surrendering and Goring germany annexing germany properly does not fire.  Gorings focus tree during the civil war also does not have a focus tree. 

### Steps to reproduce / Cause of the issue

1. Select goring as Hitlers Successor after the assassination attempt. 
2. Go through the focus tree normally.
3. win the civil war 

### Expected behaviour

Gorings focus tree to have events. Goring's Germany to annex Germany.  

### Screenshots

![20230319063556_1](https://user-images.githubusercontent.com/128293688/226172694-d85a959e-b506-403c-b239-049c67c13031.jpg)
![20230319063557_1](https://user-images.githubusercontent.com/128293688/226172695-cfe9a9b8-862d-48aa-8d3d-4ac89c87e081.jpg)
![20230319063608_1](https://user-images.githubusercontent.com/128293688/226172697-04822446-7f2e-45d2-b5f1-4cd11984400d.jpg)
![20230319063611_1](https://user-images.githubusercontent.com/128293688/226172698-728cb83e-70ee-4aa1-8727-bc1a13c18b24.jpg)
![20230319063551_1](https://user-images.githubusercontent.com/128293688/226172699-3ff2dd95-8b7c-4ee0-892c-b382ec4d8329.jpg)
![20230319063553_1](https://user-images.githubusercontent.com/128293688/226172700-81abeeb1-2ef3-4fbd-ac22-5aaa8432e746.jpg)
![20230319063812_1](https://user-images.githubusercontent.com/128293688/226172767-3832832d-554c-43a8-80ef-2676faf8b0a0.jpg)
![20230319064338_1](https://user-images.githubusercontent.com/128293688/226173028-ea6b0097-f75d-4598-8496-def0871a1802.jpg)

### Additional information

I did use console commands to replicate the bug only for the sake of time. The bug acts the same without the use of console commands.

**Comment by runelead00** [comment]
Goering has been removed with SD, selecting him as successor is now disabled for next hotfix
