### ISSUE TITLE
OFN Mandate of Congo doesn't load its focus tree

### ISSUE THREAD

**Issue by Elucidate1000** [TNODevs/TNO-Bug-Tracker#1665]
### Operating System

Windows 11 x64

### HOI4 version

11.12.11

### TNO version

1.4.0b

### Do you have other mods in use?

Radio TNO, TNO: CIA, New German Voices

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11044630/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11044631/game.log)

### Describe the bug

OFN Mandate of Congo didn't load properly with all DLC enabled and when it did, the focus tree was locked because "It had capitulated"

### Steps to reproduce / Cause of the issue

1. Have a total American victory in SAW after the 1964 election but before the inauguration.

### Expected behaviour

Congo Mandate loads with focus tree working as intended.

### Screenshots

![20230322153930_1](https://user-images.githubusercontent.com/124468584/227033747-f47ff02f-ccef-48d1-af9d-92912478e4b7.jpg)
![20230322153912_1](https://user-images.githubusercontent.com/124468584/227033806-4672e7af-3e6c-435e-bf82-cffac1fb147a.jpg)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
