### ISSUE TITLE
Guangdong (Matsuhita) - Revised Insolvency Ord Stuck

### ISSUE THREAD

**Issue by Kaidyn04** [TNODevs/TNO-Bug-Tracker#1668]
### Operating System

Windows 11

### HOI4 version

1.12.11

### TNO version

1.4.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Took "Resolving Financial Insolvencies" focus as Matsuhita. No voting commenced on focus click as is usual with the Guangdong voting focii.  Upon focus completion, a vote "started" in the Legislative Council but Council says it is not in session. Cannot take any other focii that requires Legislative Council be not in session, completely softlocking run.

### Steps to reproduce / Cause of the issue

1. Click Resolving Financial Insolvencies
2. That's it.

### Expected behaviour

Vote to take place, ability to play the game.

**Comment by runelead00** [comment]
Fixed in Dev Build
