### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by SomeGermanOnline** [TNODevs/TNO-Bug-Tracker#1669]
### Operating System

Windows 10 (though I doubt this matters)

### HOI4 version

1.12.11

### TNO version

1.4.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11069165/game.log)

### Describe the bug

So, I have no Idea how this happened (and I'm very sorry for that) and I also don't know how to upload a save file to GitHub (again, very sorry) so I have here a screenshot and the game log. Maybe it helps. 
So, I was playing a normal Speer democratization Germany and beat Moskowien. I then checked the Einheitspakt because I had nothing else to do and then I saw that I had an ally all over India. When I clicked on it, I was very surprised to see what I've linked bellow.

### Steps to reproduce / Cause of the issue

Like I said, I don't know how it happened.

### Expected behaviour

Anything but Russia making swiss cheese out of India ig

### Screenshots

![Screenshot 2023-03-25 155948](https://user-images.githubusercontent.com/117571405/227725260-2f321c0f-432e-41c2-b96e-b1c7135c00c9.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
