### ISSUE TITLE
Republic of China - Western Insurrection Category does not dissapear

### ISSUE THREAD

**Issue by Flizzyclone** [TNODevs/TNO-Bug-Tracker#167]
**Questions**

- Operating System: Windows 11
- HOI4 Version: 1.10.8
- TNO Version: 1.20a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? All expansions are owned & enabled

**Longer Description of Issue:**
When playing China, once you beat Long Yun, the Western Insurrection decision category doesn't disappear because the "Change in War Momentum" decision keeps repeating over and over. This carried on for at least a year and a half.

**Steps to Reproduce/Cause Issue:**

1. Play China

2. Win the Western Insurrection

**Screenshots:**
![image](https://user-images.githubusercontent.com/42476312/142751833-a8bcd941-3dc5-4c0e-b707-01157c2748bb.png)

**Comment by tkgitno** [comment]
Fixed in Dev Build
