### ISSUE TITLE
Guangdong - PTRG not progressing

### ISSUE THREAD

**Issue by MegaCactus27** [TNODevs/TNO-Bug-Tracker#1670]
### Operating System

Windows 10

### HOI4 version

1.12.10

### TNO version

1.4.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11069631/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11069632/game.log)

### Describe the bug

The objectives during (at least) the first PTRG cycle for Guangdong are not progressing even though the conditions are satisfied.

### Steps to reproduce / Cause of the issue

1. Play as Guangdong (standard difficulty/no custom settings/no difficulty adjustment decisions)
2. Select a PTRG product (both Sony and Matsushita have caused the bug, unsure if there would a difference with the other)
3. Send the PTRG unit to Malaya as a volunteer
4. Try to fight in the conditions listed

### Expected behaviour

PTRG objectives should progress as normal

### Screenshots

![image](https://user-images.githubusercontent.com/59895598/227732092-66d3b508-d519-42d4-a58c-9ac4ba4644bd.png)

### Additional information

I played Guangdong pre-patch and the PTRG worked just fine

**Comment by runelead00** [comment]
Did you have a general assigned?

**Comment by MegaCactus27** [comment]
no

**Comment by MegaCactus27** [comment]
assigning the general fixed it, that explains why it worked before
