### ISSUE TITLE
Goering path not loading

### ISSUE THREAD

**Issue by Jakey19** [TNODevs/TNO-Bug-Tracker#1671]
### Operating System

Windows 11

### HOI4 version

1.12.11

### TNO version

v1.4.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When you go down the Goering path the events don't work for example the, "Smile for the Cameras" Focus doesn't have a event like it used to, it just says, "Invalid event with id: Goering_Successor.(Number)". When the Civil war starts when your the Goering faction you don't have a focus tree while the other three do have their own. After you beat the three other factions there is no event to keep going and become Greater Germany again. Your just there waiting for nothing, the focus tree doesn't change because there is none. In Debug mode the Goering setup isn't there while Speer, Bormann, and Heydrich are all there.

### Steps to reproduce / Cause of the issue

1. Pick Goering for the civil war
 

### Expected behaviour

The events on the Goering tree be shown. And for the civil war to have its focus tree and its winning event

### Screenshots

![image](https://user-images.githubusercontent.com/129008283/227804875-fe3ad9a1-59a9-4461-9a5c-9777673e11bb.png)
![image](https://user-images.githubusercontent.com/129008283/227804966-d275e29b-15b6-45ae-9e62-04198c09b7d2.png)

**Comment by runelead00** [comment]
Removed in SD release, fully disabled in current update
