### ISSUE TITLE
USA - Social security act as RFK self block

### ISSUE THREAD

**Issue by Hugdelgyr** [TNODevs/TNO-Bug-Tracker#1674]
### Operating System

Windows 10 Famille

### HOI4 version

Avalanche v1.12.11.137b(92F5)

### TNO version

v1.4.0b "Silicon Dreams"

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, BBA

### Describe the bug

When picking the social security act focus as RFK during your first term, the focus automatically cancel itself upon picking, and the bill stay on the senate floor forever.

### Steps to reproduce / Cause of the issue

1.get RFK elected as USA 
2.pass all the focus that you need to pass the social security act
3.select the social security act focus.

### Expected behaviour

I expect that in the next bug fixes it would be now possible to pass the social security act as RFK

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Hugdelgyr** [comment]
thanks
