### ISSUE TITLE
TNO Suggestion - Could you Make Your mod playable (no crashes) for Non-Steam Users.

### ISSUE THREAD

**Issue by HOI4User** [TNODevs/TNO-Bug-Tracker#1675]
### HOI4 version

1.12.11

### TNO version

v1.4.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Cause i use HOI4  (Not With Steam) And Whenever i install and play your mod. And it always Crashes. And im very sad cause this mod is very great and all.

### Justifications

This change is necessary cause it would affect the mod very well and a lot of non steam users would play it (without crashes). And the popularity would skyrocket.

**Comment by runelead00** [comment]
If nothing in #961 and #962 helps, not much we can do
