### ISSUE TITLE
Issue with location descriptions

### ISSUE THREAD

**Issue by SCParefornerds** [TNODevs/TNO-Bug-Tracker#1676]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.5.1? Not sure, path is toolbox theory 5?

### Do you have other mods in use?

TNO music mods, Toolpakt

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

No related files.

### Describe the bug

Small bug, but when switching descriptions it does not reset to the top. For a example you can read the Nuuk log, requiring you to scroll down, but if you fail to re-scroll up, it will stay down even in descriptions that dont go as far. Meaning most of the text ends up getting cut off and being unreadable. Thought it should be reported.

### Steps to reproduce / Cause of the issue

1. Go to Nuuk
2. Scroll to bottom of the log
3. Click on a shorter log, like Washington D.C.
4. Ends up getting cut off

### Expected behaviour

It to reset back to the start for each log.

### Screenshots

Cant get a correct file right now, easy to replicate in game.

### Additional information

Nothing.

**Comment by runelead00** [comment]
Issue with Paradox code, can't fix
