### ISSUE TITLE
USA - CTD Upon Dominican Civil War Victory

### ISSUE THREAD

**Issue by ColinFaith** [TNODevs/TNO-Bug-Tracker#1678]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.5.0a

### Do you have other mods in use?

Last Waltz

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11131068/error.log)
[USA_1963_08_19_10.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11131109/USA_1963_08_19_10.zip)

### Describe the crash

Upon the victory of the USA-backed faction in the Dominican Republic, the game CTD's.

### Steps to reproduce / Cause of the crash

1. Play as the USA
2. Win the Dominican Civil War

### Additional information

I was using OBS to record the game, if that helps.

**Comment by runelead00** [comment]
#1509 Please send a save and game log if you are reporting a crash, if you compress the save into a zip file you can send it through github

**Comment by runelead00** [comment]
your save game did not finish uploading before you saved your issue, it cannot be downloaded

**Comment by ColinFaith** [comment]
I think I fixed it now, thanks!

**Comment by runelead00** [comment]
Should be fixed in current hotifx
