### ISSUE TITLE
USA - Volunteer Limit bug

### ISSUE THREAD

**Issue by davidwang117155** [TNODevs/TNO-Bug-Tracker#168]
**Questions**

- Operating System: Win10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: Radio TNO: Music of the New Order
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle of the Bosporus

**Longer Description of Issue:**
Cannot send correct number of volunteers to Indonesia. This issue also occured during South African War, but was fixed on restart. Indonesia issue is persistent.

**Steps to Reproduce/Cause Issue:**

1. Went with Robert Kennedy

2. Established 3 mandates in Africa

3. Indonesian War started

etc...

**Screenshots:*
![20211121014153_1](https://user-images.githubusercontent.com/92734555/142752536-fde909d7-ab55-4b87-9903-6cba697ce02a.jpg)
![20211121014159_1](https://user-images.githubusercontent.com/92734555/142752538-eecdc9f3-80f2-4730-9474-d88857fbf723.jpg)
*

**Comment by AlgisAlphonse** [comment]
I can second this bug's occurance. It happens in every conflict, regardless of the advisor level. I should not that on my end, the send voluteers text tells me that I have send "0 of 1 divisions" (even when I have sent one division and can send more) and does not allow to send any more divisions. If the division already sent dies, you can send more volunteers then.
