### ISSUE TITLE
USA/Dominican Republic - Min Supply in Wrong Position

### ISSUE THREAD

**Issue by TaltosRaven** [TNODevs/TNO-Bug-Tracker#1681]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.11

### TNO version

1.4.1

### Do you have other mods in use?

Player Peace conferences 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Playing as the USA. Doing the "Ousting Trujillo" Global Conflict. 
The little bar with the arrow that shows your current supply level is off the bar and cutting into the decisions.

### Steps to reproduce / Cause of the issue

Unclear... I have Supply of 100/100 and a minimum supply of 100. I have 8 brigades and Operation Strength of 26.

### Expected behaviour

The supply level bar should be at the far right end of the current supply bar instead of overlapping w/ decisions menu.

### Screenshots

![image](https://user-images.githubusercontent.com/83472525/229379059-6b977a66-f53e-4d3e-bf8b-11432bb29c13.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
