### ISSUE TITLE
Trouble with colors in Brazil

### ISSUE THREAD

**Issue by AlexKoval21** [TNODevs/TNO-Bug-Tracker#1682]
### HOI4 version

1.12.11

### TNO version

1.4.1

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/59415315/229380487-cf3fd75f-7404-498a-b452-1ae3999e6196.png)

BRA_lott_act_failed_flag and BRA_lott_act_passed_flag - proper lines

### Additional information

I translated changes in countries, and in the last update, exclamation marks were removed from Brazil and accidentally closing signs for color were removed too. Need fix it.

**Comment by runelead00** [comment]
Fixed for 1.4.1a
