### ISSUE TITLE
CTD from Midwar WAC Peace Conference

### ISSUE THREAD

**Issue by GeneralVonGelre** [TNODevs/TNO-Bug-Tracker#1683]
### Operating System

Windows 11

### HOI4 version

1.12.11.137b

### TNO version

1.4.1b

### Do you have other mods in use?

TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11137407/autosave.zip)

### Describe the crash

Crash happens between a week and a month from this autosave. Seems to be related to the death of the ruler in Thailand. A Peace conference fires at the same day, I've been unable to deduce what war causes it.

### Steps to reproduce / Cause of the crash

Open the save and let the game run.

**Comment by runelead00** [comment]
Fixed in Dev Build
