### ISSUE TITLE
USA - Dominican proxy standstill

### ISSUE THREAD

**Issue by vipersniper2001** [TNODevs/TNO-Bug-Tracker#1684]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

Radio TNO, Last Waltz, VT323 font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the ceasefire fails in the Dominican Republic proxy, both sides will fight for some time before just completely stopping. The rebels usually stop where they were while the government goes to their coast. There's no way to support the rebels as the US during this time so I think it has something to do with their supply, since eventually they simply can't resupply themselves and they won't push forward because of it. This happened before the hotfix and after.

### Steps to reproduce / Cause of the issue

1. Have Dominican ceasefire fail w/ preparation for the rebels around 25
2. Enjoy

### Expected behaviour

An end to the war by one side or the other

**Comment by runelead00** [comment]
Should be less static now, fixed broken AI strat
