### ISSUE TITLE
Various typos/grammar issues

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1685]
### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![Screenshot (1875)](https://user-images.githubusercontent.com/33550299/229614018-8f6f9a5e-80da-4b77-be5b-65069dedeca4.png)
into America --> into American

![Screenshot (1878)](https://user-images.githubusercontent.com/33550299/229614190-df1951aa-8ba2-4388-a1fe-0c92384b800d.png)
technollogies --> technologies

![Screenshot (1879)](https://user-images.githubusercontent.com/33550299/229614328-d2416fa3-76de-4b4a-a9f1-1c622a917cd3.png)
analizing --> analyzing

![Screenshot (1880)](https://user-images.githubusercontent.com/33550299/229614481-d496b71e-249b-4cfb-940b-b01ff0a3c95f.png)
and to centralize --> and proposed to centralize

![Screenshot (1881)](https://user-images.githubusercontent.com/33550299/229614675-b74bfd1d-1b90-4bcd-978a-9b06b7b91c29.png)
Flover class --> Flower class

![Screenshot (1882)](https://user-images.githubusercontent.com/33550299/229615068-2212e672-85c6-4256-b28f-6d5f1ee299dc.png)
Something is wrong with the second sentence of the second paragraph. Maybe "Beach became renowned for this feat as part of his valiant defense against the Japanese in the doomed Pacific theater." ?

![Screenshot (1871)](https://user-images.githubusercontent.com/33550299/229616423-062a2647-1868-42c6-bad5-888cbdf19459.png)
were it is --> where it is

![Screenshot (1872)](https://user-images.githubusercontent.com/33550299/229616499-796ad613-5ac8-4b48-bb79-84515181846c.png)
Weisel --> Wiesel

![Screenshot (1873)](https://user-images.githubusercontent.com/33550299/229616737-756b4f2d-5848-4200-b718-ee7539c071fb.png)
DAS GROßGERMANISCHES REICH --> DAS GROßGERMANISCHE REICH

**Comment by runelead00** [comment]
Fixed in Dev Build
