### ISSUE TITLE
OFN spirits

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1686]
### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![Screenshot (1874)](https://user-images.githubusercontent.com/33550299/229617105-5119514b-307f-48fd-8e87-0e4bbd0712f2.png)
First, should Iceland actually be an independent member (their national spirits suggest otherwise)? If so, the last sentence of this OFN spirit should be updated to include Iceland.

![Screenshot (1876)](https://user-images.githubusercontent.com/33550299/229617364-dfb8e07b-ea93-4919-9366-c1218acf3f36.png)
Last sentence should be updated to include Faroe Islands.

**Comment by runelead00** [comment]
Fixed in Dev Build
