### ISSUE TITLE
Crash - Short Description of Issue

### ISSUE THREAD

**Issue by bmtrs23** [TNODevs/TNO-Bug-Tracker#1691]
### Operating System

Windows 11

### HOI4 version

Latest version 

### TNO version

Latest version 

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Files
[error](https://drive.google.com/file/d/14i9ZfoR-qd1D6TuvoVl85iCEqTkOveHT/view?usp=share_link)
[game](https://drive.google.com/file/d/10wDt98Odha0Kc4yTtuAIW8sDsOnYOKST/view?usp=share_link)

### Describe the crash

Happens only with saved games. I when click unpause, the game crashes. But before crash one hour in game passes. 

### Steps to reproduce / Cause of the crash

Open Hoi4
Click "continue"
After it loads, click space bar to unpause
Crash

### Additional information

Only happens with saved games, i can start a new game normally

**Comment by bmtrs23** [comment]
I can play other mods( and plain hoi4)with no problem. It's just TNO ig

**Comment by runelead00** [comment]
saves from before the update are not compatible and cannot be played
