### ISSUE TITLE
GRE - Wrong digit in year for Athens description

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1694]
### HOI4 version

1.12.10

### TNO version

1.4.1b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/98370487/230208728-8d9fd507-a07a-4614-817f-a32404500e25.png)

### Additional information

The description of Athens says it was chosen as the capital of newly independent Greece in 1932 instead of 1832.

**Comment by runelead00** [comment]
corrected to proper year of 1834
