### ISSUE TITLE
Main menu and map graphics bugged - Subsequent crash

### ISSUE THREAD

**Issue by intheworlditsgone** [TNODevs/TNO-Bug-Tracker#1695]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

1.41b Ugly American

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11163490/error.log)

### Describe the bug

Main menu screen is pitch black with a red bar on the side, when loading the bookmarks screen and trying to load a new game the map is also black then subsequently crashes. 

### Steps to reproduce / Cause of the issue

I'm not sure how you'd be able to do so but I was using DX11 for TNO, using OpenGL and DX9 has the same result just it being completely black instead of that red strip on the side.

### Expected behaviour

I was expecting it to load as usual. 

### Screenshots

![image](https://user-images.githubusercontent.com/65721240/230223801-0648d360-70f2-42bb-8c84-e3bf73b6e820.png)

**Comment by runelead00** [comment]
I've never seen anything like this, best I can recommend right now is trying a reinstall of TNO

**Comment by runelead00** [comment]
Can't reproduce, try the above or disable other mods you have enabled (whatever RSR is in the error log)
