### ISSUE TITLE
Speer's Germany

### ISSUE THREAD

**Issue by Iron-Chancellor2** [TNODevs/TNO-Bug-Tracker#1696]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1-Ugly American

### Do you have other mods in use?

tno radio

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The England minigame between Thatcher's England, Speer's Germany and the U.S. is still bugged. When all three parties gamble for influence over each other, the important decision "North Sea Exercises" does not have any effect for Speer's Germany, just like the counterpart for the U.S.
This means that there is no way of getting monthly influence and that both superpowers have lost any meaningful ability to counter England's take for independence, since this focus is crucial to have. When Thatcher is in power, it is guaranteed that England will go independent. 

### Steps to reproduce / Cause of the issue

1. Win Civil war as Speer
2. Thatcher has to be England's leader
3. England has to finish the focus "Our Biggest Threat" and aquire Cornwall
4. The minigame is initiated once England decides to go on the international stage again
5. The option "North Sea Exercise" for Speer's Germany is correctly diplayed, but has no description and accordingly no effect
6. You wasted 75 influence and 20 (30?) command points
7. Additionally, the decision tab with influence display does not disappear even when the UK is already independent.

### Expected behaviour

England becomes independent (Neither joining the OFN nor the Einheitspakt) without any means of preventing it

**Comment by runelead00** [comment]
Fixed in Dev Build
