### ISSUE TITLE
Speer's Germany - No 2nd Burgundy Mission

### ISSUE THREAD

**Issue by Iron-Chancellor2** [TNODevs/TNO-Bug-Tracker#1697]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1-Ugly American

### Do you have other mods in use?

tno radio

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Even after finishing the RND missions in the U.S. against Burgundy, there is no other mission in Europe than "Tapferkeit", with the last mission apparently being bugged. This caused the Ordensstaat to not collapse in my latest playthrough.

### Steps to reproduce / Cause of the issue

1. Win Civil War as Speer
2. Establish RND
3. Research the reqiured RND techs to conduct "Tapferkeit"
4. The next mission does not show up, despite having finished all other Burgundy-related RND missions.

### Expected behaviour

Ordensstaat is not guaranteed to collapse after successful missions

**Comment by runelead00** [comment]
Removed in purging last references to global plans, Burgundy collapse vars have been adjusted to reflect  this change.
