### ISSUE TITLE
WAC Peace Deal Crash Midway through War

### ISSUE THREAD

**Issue by jaccoc** [TNODevs/TNO-Bug-Tracker#1699]
### Operating System

macOS

### HOI4 version

1.12.11.137b

### TNO version

v1.4.1b “Ugly American”

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[autosave.hoi4 copy.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11178239/autosave.hoi4.copy.zip)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11178244/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11178245/game.log)

### Describe the crash

it says peace confrence in progress.. on 24:00 26th feb 1965 and the event chaos in horn of africa

### Steps to reproduce / Cause of the crash

just leave the game running for a couple days to see the crash

**Comment by runelead00** [comment]
Fixed in Dev Build
