### ISSUE TITLE
Germany (Terra e Liberta) - Cant restore Hegemony of Europe

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#17]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Collie 1.10.7
- TNO Version: 1.1.2B
- Any other mods in use: Terra e Libertà
- Were you using Steam? Yes
- Which expansions do you NOT have? 

**Longer Description of Issue:**

Playing as Speer I can not restore hegemony over Europe. I have tried two playthroughs as him and it is not possible. I believe it is an issue with the Terra e Liberta mod. I have tried going hardline and reformist routes to taking back hegemony and both still dont work. Interestingly enough I did get the world event for restoring hegemony over Europe though. I belive this will probably happen when you play Bormann and Goering as well with the Terra mod on. 

**Steps to Reproduce/Cause Issue:**

1. Play speer with terra e liberta

2. Cant restore hegemony 

(Note on screen shot dates in game, I autocompleted the focuses to get to the final focus to see if the issue was stil present (i did them all organically first playthrough). 

**Screenshots:**
![image](https://user-images.githubusercontent.com/59725197/128107848-4626266d-0974-42bd-987e-edce2e10e224.png)
![image](https://user-images.githubusercontent.com/59725197/128108100-7c5e4110-ee56-47ba-853c-466119077594.png)

**Comment by EddieWasHere** [comment]
Issue fixed in dev build.

**Comment by masterbobli** [comment]
Fixed in dev build.
