### ISSUE TITLE
Income - Costs loc issue

### ISSUE THREAD

**Issue by AlexKoval21** [TNODevs/TNO-Bug-Tracker#1700]
### HOI4 version

1.12.11

### TNO version

v1.4.1b “Ugly American”

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

I'm not sure that's how it should be
![image](https://user-images.githubusercontent.com/59415315/230720607-089f784f-f189-462c-b856-7e78f09430e4.png)

### Additional information

I think you still need to write income as in the code

**Comment by runelead00** [comment]
Fixed in Dev Build
