### ISSUE TITLE
USA - Event missing loc

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#1702]
### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![Screenshot (1918)](https://user-images.githubusercontent.com/33550299/230730945-45a30be1-42b7-4e8e-b2e6-9e4589de6205.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
