### ISSUE TITLE
SG_Politics - Trouble with Effects

### ISSUE THREAD

**Issue by AlexKoval21** [TNODevs/TNO-Bug-Tracker#1705]
### HOI4 version

1.12.11

### TNO version

v1.4.1b “Ugly American”

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

I am 100% sure that this dash breaks the effects in the game
![image](https://user-images.githubusercontent.com/59415315/230795815-747fe669-a4a4-4cf2-b58b-58b0985fa596.png)

### Additional information

Line -  TNO_policy_trend_regulations

**Comment by runelead00** [comment]
Fixed in Dev Build
