### ISSUE TITLE
Angola - Event still references MPLA despite name swap

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1706]
### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://user-images.githubusercontent.com/98370487/230804830-5bff7ab1-992f-4d39-89c5-1461a9073363.png)

### Additional information

I saw that the MPLA was removed and rebranded as a new party, PLUAA. However, the event for the Angolan Civil War still references the old MPLA.

**Comment by ModdingAccount** [comment]
Fixed in dev build.
