### ISSUE TITLE
Tanganyika - Issue with Parties and quotation marks

### ISSUE THREAD

**Issue by AlexKoval21** [TNODevs/TNO-Bug-Tracker#1707]
### HOI4 version

1.12.11

### TNO version

v1.4.1b “Ugly American”

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Just fix it. There are not many words needed here

![image](https://user-images.githubusercontent.com/59415315/230990699-f4835299-9b8f-4aa3-b6e5-c4928cd79247.png)

### Additional information

File - TNO_Tanganyika

**Comment by runelead00** [comment]
Fixed in Dev Build
