### ISSUE TITLE
ITA - Doesn't gain Damascus after winning war

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1708]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[ITA_1962_11_10_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11196043/ITA_1962_11_10_01.zip)

### Describe the bug

After winning the war against Turkey and picking Scorza's peace deal, Italy doesn't gain Damascus despite it being mentioned in the peace event and world event.
Also, I'm not certain if it works as intended with Mosul. Iraq only gains the state of Mosul, the rest of Mosul and Kirkuk remains under Turkish control.

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Send volunteers to the levant during the war with turkey
3. Pick the Scorza peace deal options in every event
4. Win the war

### Expected behaviour

Italy to gain control of Damascus after winning the war

### Screenshots

![Capture27](https://user-images.githubusercontent.com/80563255/231048172-2c2aabfb-3f59-4a6e-a86f-f45599946e7b.PNG)

### Additional information

I needed to pick Scorza's option in three separate events before Turkey accepted defeat

**Comment by runelead00** [comment]
Fixed in Dev Build
