### ISSUE TITLE
ITA - Focus builds new port rather than improving existing one

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1709]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[ITA_1963_02_02_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11196237/ITA_1963_02_02_01.zip)

### Describe the bug

The focus "Build up Sardinia" for Italy builds a new level 5 port directly adjacent to the existing level 3 port in the south. That behavior might be intended, though I suspect the focus is meant to improve the existing port to level 5 rather than build an entirely new one.

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Complete the focus "Build up Sardinia"
3. Look at the ports in Sardinia

### Expected behaviour

The level 3 port is improved to level 5

### Screenshots

![Capture31](https://user-images.githubusercontent.com/80563255/231051367-038e8eba-485b-4f71-ab9a-313a35eaf422.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
