### ISSUE TITLE
USA - News event getting spammed to the point of making the game unplayable.

### ISSUE THREAD

**Issue by SackboyIon** [TNODevs/TNO-Bug-Tracker#171]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosporus, Man The Guns, Walking the Tiger, and Together for Victory.

**Longer Description of Issue:**

I was playing as the United States of America and I was currently fighting the South African War and the game ticked at February 4, 1964 in which the event "1964 Winter Olympics a Success!" popped up so many times within just one tick to the point where my game practically froze and made my entire computer slow down just due to how much information it had to process. I used the Task Manager to exit out of the game before anymore damage could be done. Edit: Also, I started up the game again, started the month I left off, and it happened again.

**Steps to Reproduce/Cause Issue:**

1. Start the game, maybe even play as any country

2. Wait until the game ticks at February 4, 1964

3. You get the spamming event

**Screenshots:**

![hoi4_193](https://user-images.githubusercontent.com/67209873/142756105-113021de-0a87-47f7-9599-3ca1e8f74df5.png)

**Comment by AntonosGR** [comment]
Can Confirm.Played as Communist Komi and the exact isssue occured while I was playing.

**Comment by Katarn1933** [comment]
Same issue. Later in game also couple of spam events from Canada, including 1964 Olympics event in around 1968

**Comment by thashepherd** [comment]
Should be addressed by patch 1.2.0.c
