### ISSUE TITLE
WAC (3 way) peace deal error for Cameroon victory

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1710]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11201264/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11201265/error.log)

### Describe the bug

The peace deal for a 3-way WAC conflict with a Cameroonian victory is bugged, with strange state assignments in places.

### Steps to reproduce / Cause of the issue

1. Win 3-way WAC as Cameroon.
2. Observe issue.

### Expected behaviour

Cameroon and/or Niger don't have random state assignments for the peace deal.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/231186389-a67c3ae9-7511-44c9-a264-baaf2181a0ca.png)

**Comment by runelead00** [comment]
Should be fixed in release build
