### ISSUE TITLE
ITA - Focuses can be completed even if they don't apply

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1712]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

The focus "Meet with Dalla Chiesa" can be completed even though the Jerusalem Conference has happened and the Governatorato del Levante doesn't exist anymore. It should probably be bypassed if it doesn't exist.

Also, the focus "Reinforce the Garrisons" gives manpower to the Governatorato del Levante even if they don't exist. It should probably give manpower to Jerusalem if they exist and have a condition that prevents that part of the focus from being visible unless the Governatorato del Levante or Jerusalem exist.

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Wait until the Jerusalem Conference fires
3. Pick the focus Meet with Dalla Chiesa
4. Pick the focus Reinforce the Garrisons

### Expected behaviour

Bypass the focus and don't display that focus effect if they don't exist

### Screenshots

![Capture42](https://user-images.githubusercontent.com/80563255/231290219-1506fc14-0cb0-4322-985c-22582aa7cef5.PNG)
![Capture43](https://user-images.githubusercontent.com/80563255/231290393-94ae2e03-2fa5-4eac-a03d-3e52dfad9def.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
