### ISSUE TITLE
ITA - Focus builds port in different state

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1713]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

The focus "Reinforce the Horn" builds a level 5 port in Dancalia instead of Bassopiani Eritrei like the focus states. The province is directly below a level 1 port in Bassopiani Eritrei so I think that the focus is meant to improve that level 1 port to level 5 instead.

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Do focus "Reinforce the Horn"

### Expected behaviour

The port to appear in the listed state

### Screenshots

![Capture44](https://user-images.githubusercontent.com/80563255/231291977-ad3a523f-72ca-442f-86d6-dd961bf026a6.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
