### ISSUE TITLE
ITA - Focus "Reinforce the Fourth Shore" doesn't do anything

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1715]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

The focus "Reinforce the Fouth Shore" (ita_reinforce_the_fourth_shore) doesn't add any forts in Bengasi or Calabria. Also, based on the focus description it should probably add forts in Annaba, Constantine, or Kabylie. The focus code seems to point towards Annaba and Touggourt but the prioritize scope doesn't seem to fire

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Complete the focus "Reinforce the Fourth Shore"

### Expected behaviour

Add forts to the listed states

### Screenshots

![Capture46](https://user-images.githubusercontent.com/80563255/231296580-0311af6a-8b6c-462e-aefb-4d676e2837b4.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
