### ISSUE TITLE
ITA - Focus "Modernize The Infrastructures" doesn't actually change railways

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1717]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

The focus "Modernize the Infrastructures" doesn't change any railways from Venice to Tirana. This is likely because the path in the code already has railways and "build_railway" probably doesn't always add a level, only increases the level to 1.

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Complete focus "Modernize the Infrastructures"

### Expected behaviour

The focus to actually modify railways

### Screenshots

![Capture49](https://user-images.githubusercontent.com/80563255/231302806-d9129eae-970b-43df-aab7-b9d6ee9fcf0e.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
