### ISSUE TITLE
ITA - Focus improves Italy's opinions of them, not their opinions of Italy

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1719]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

The focus "Prepare for the Malta Conference" improves Italy's opinion of Iberia and Turkey. Based on the modifier names it should probably be the other way around, opinions of Italy being increased.

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Do focus "Prepare for the Malta Conference"
3. Look at relations with Iberia and Turkey

### Expected behaviour

Opinion modifiers to work properly

### Screenshots

![Capture51](https://user-images.githubusercontent.com/80563255/231306369-55023df7-a3d6-4021-a0ba-f686d226fb0c.PNG)
![Capture52](https://user-images.githubusercontent.com/80563255/231306375-a729c215-ce0d-4f01-bea6-70e4ad0b658d.PNG)

**Comment by runelead00** [comment]
Fixed in Dev Build
