### ISSUE TITLE
ITA - ENI decisions have unexpected behaviors

### ISSUE THREAD

**Issue by tydane** [TNODevs/TNO-Bug-Tracker#1722]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Several of the "Ente Nazionale Idrocarburi" decisions to develop provinces for Italy seem to change what is being built after being selected as shown in the last screenshot. This seems to be due to many decisions picking a random state in Italy to build in and since the rng changes as time progresses, different places get selected. What is being built and where should probably be locked in when you select the decision.

Also, in the code for developing Palestine (and Transjordan, but at the game's start it's already listed as at maximum development despite not having any refineries), for much of the development it only builds in states owned by IME, a tag that usually disappears after the Jerusalem Conference. This effectively locks you out from building those refineries and infrastructure unless you develop before the Jerusalem Conference. If there are any Italian sphere countries in the Levant after the Jerusalem conference they should probably be able to gain the refineries and infrastructure rather than preventing them from being built.

Additionally, the North Sudan and South Sudan decisions don't actually focus on North Sudan or South Sudan, they either build in a random state in EGY or a random state in ITA. This might be intended, but it seems weird that you could fully develop both North and South Sudan and not actually build anything in Sudan at all.

### Steps to reproduce / Cause of the issue

1. Play as Italy
2. Keep an eye on the "Ente Nazionale Idrocarburi" decision effects
3. Often they will change what is being built weeks after selecting the decision
4. There are other quirks with Palestine and Sudan too

### Expected behaviour

Buildings to be locked in when you select the decision and being able to develop the Levant if Italian sphere countries are still there

### Screenshots

Both tooltips are from the "Finish Off Work in the Persian Gulf" decision
![Capture83](https://user-images.githubusercontent.com/80563255/231347293-2920053b-50b9-4782-a115-3ab197d4cca5.PNG)
![Capture85](https://user-images.githubusercontent.com/80563255/231347828-4b0d5d14-e798-4b32-bea3-44994c5fb716.PNG)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
