### ISSUE TITLE
germany-england great game

### ISSUE THREAD

**Issue by Balkanoid** [TNODevs/TNO-Bug-Tracker#1723]
### Operating System

windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

basically in the England great game so to say the naval exercises don't grant you anything

### Steps to reproduce / Cause of the issue

basically play Germany until the great game the collaborator English start and enjoy

### Expected behaviour

.

### Screenshots

.

### Additional information

.

**Comment by runelead00** [comment]
Fixed in Dev Build
