### ISSUE TITLE
Faroe Islands/World events - Trouble with logic?

### ISSUE THREAD

**Issue by AlexKoval21** [TNODevs/TNO-Bug-Tracker#1724]
### HOI4 version

1.12.11

### TNO version

v1.4.1b “Ugly American”

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Not sure if it's actually a mistake, but it confused me. In the Faroe World event, it is written that the Javnaðarflokkurin party is conservative.
![image](https://user-images.githubusercontent.com/59415315/231975537-7732724e-b912-468a-a9bb-ea9e7ed986d4.png)
Whereas in the Faroese file, these are naturally soc-dems/progressivists. 
![image](https://user-images.githubusercontent.com/59415315/231975662-d03c8a6e-2862-44a0-851d-5391954f636d.png)
Maybe remove the word conservative from the event? Idk

### Additional information

File - TNO_WorldEvents

Line - WORLD.17101

**Comment by runelead00** [comment]
Fixed in Dev Build
