### ISSUE TITLE
Game crashes after loading a country

### ISSUE THREAD

**Issue by aviaovrum** [TNODevs/TNO-Bug-Tracker#1728]
### Operating System

Manjaro Linux

### HOI4 version

1.12.12

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Can't find any, probably because when the game crashes my pc freezes and I have to restart

### Describe the crash

The game starts normally, but when I choose a country the game just freezes when the game loads (I can hear the sounds when you load the country) and then it crashes.

### Steps to reproduce / Cause of the crash

1. Open Hoi4 with TNO enabled
2. Choose country
3. Wait
4. The game has now crashed!

**Comment by TheSudoer** [comment]
Same issue here

OS : Artix Linux
HOI4 Ver : 1.12.12
TNO Ver : 1.4.1b "Ugly American"

**Comment by aviaovrum** [comment]
I "solved" the issue. Seems to be some kind of incompatibility with the drivers, still pretty laggy though, but it might be better depending on the drivers you install.
