### ISSUE TITLE
GNG - "And And" Loc Error

### ISSUE THREAD

**Issue by SirJaguar** [TNODevs/TNO-Bug-Tracker#1729]
### HOI4 version

1.12.11

### TNO version

1.2.1b

### Do you have other mods in use?

Zizek's Ideology Bling, More Voicelines for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![hoi4_tDeiRSkrdV](https://user-images.githubusercontent.com/51899758/232253636-77954fc4-b81b-4312-b649-ec9c648c6c36.png)

Repeated "and".

**Comment by runelead00** [comment]
all instances I could find of this error fixed for next hotfix
