### ISSUE TITLE
JAP - doubled "Keiretsu Subsidies" national spirit

### ISSUE THREAD

**Issue by Drakeme** [TNODevs/TNO-Bug-Tracker#173]
- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? None

Longer Description of Issue:
    
   I was playing Takagi Japan until I noticed that there are 2 "Keiretsu Subsidies" national spirits. I did all of National Focuses besides "Moving Forward" and "Corporate Decentralization". I took "Corpotate Decentralization" Focus and after that one of "Keiretsu Subsidies" national spirits got a new modifier while other (having more modifiers in it) stayed as it is.

Steps to Reproduce/Cause Issue:

1. Play Japan
2. Choose Takagi as Prime Minister
3. Complete "Sweeping Contracts" before "Corporate Decentralization"

Screenshots:
![изображение](https://user-images.githubusercontent.com/71932171/142757030-c8545011-332e-4692-90cd-110650c0ab8c.png)

National Spirit that got modified:
![изображение](https://user-images.githubusercontent.com/71932171/142757094-91502c34-807a-46f5-960b-459d78c37738.png)

**Comment by runelead00** [comment]
Fixed in Current Release
