### ISSUE TITLE
IND - Missing portrait for Atal Bihari Vajpayee

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1730]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11240706/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11240707/game.log)

### Describe the GFX issue

Missing portrait for Atal Bihari Vajpayee after his election in India's early 70s election.

### Steps to reproduce / Cause of the issue

1. Have India elect him in the early 70s.
2. Observe issue.

### Expected behaviour

Portrait is present.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/232254033-f6cef601-44d0-4d16-9a43-dd7f02271ff2.png)

**Comment by Stormeagle449** [comment]
Fixed for The Ruin update.
