### ISSUE TITLE
USA - Crash after Free France victory

### ISSUE THREAD

**Issue by Davin4519** [TNODevs/TNO-Bug-Tracker#1731]
### Operating System

Windows 10

### HOI4 version

-

### TNO version

-

### Do you have other mods in use?

music only

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11246528/autosave.zip)

### Describe the crash

Crash on the 3rd of July. Probably because of Niger annexation by Free France.

### Steps to reproduce / Cause of the crash

Just wait for the 3rd of July

**Comment by runelead00** [comment]
Should be fixed in Dev Build (post-war peace code firing mid-war due else_if where it should have been if)
