### ISSUE TITLE
Germany - North Sea Naval Excercises has no effect

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#1734]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

1.4.1b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

North Sea Naval Excercises has no effect. 

### Steps to reproduce / Cause of the issue

Thatchers minigame starts 

Take decision 

### Expected behaviour

Gain incremental support 

### Screenshots

![image](https://user-images.githubusercontent.com/59725197/232929146-7fde16bb-d432-4fbf-903d-fcf64a5aa807.png)

If image doesnt work, the decision just has no description oter than its prereq

**Comment by runelead00** [comment]
Fixed in dev Build
