### ISSUE TITLE
GNG - Missing text for "Joaquín Balaguer Elected Dominican President" 

### ISSUE THREAD

**Issue by SirJaguar** [TNODevs/TNO-Bug-Tracker#1738]
### Operating System

Windows 11

### HOI4 version

1.12.11

### TNO version

1.2.1b

### Do you have other mods in use?

Zizek's Ideology Bling, More Voicelines for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11277593/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11277595/game.log)
https://cdn.discordapp.com/attachments/604335352219566090/1098355314241323150/TNO_-_Guangdong_-_17.hoi4

### Describe the bug

Missing text for "Joaquín Balaguer Elected Dominican President" 
![hoi4_fyblbk2Fve](https://user-images.githubusercontent.com/51899758/233200626-c956bbdb-1d08-466a-8118-17eb5fe8e743.png)

### Steps to reproduce / Cause of the issue

Was not paying attention to this part of the world, sorry.

### Expected behaviour

A news event with text

**Comment by runelead00** [comment]
Disabled in Dev Build, got missed with other DOM election events
