### ISSUE TITLE
All - Loc all appears as ???

### ISSUE THREAD

**Issue by Ranamagica** [TNODevs/TNO-Bug-Tracker#1739]
### Operating System

Windows 11

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, NSB, BBA

### Files

![20230420190824_1](https://user-images.githubusercontent.com/71571170/233439039-d69e9127-6e2d-4fd8-b9f4-a27550fabd74.jpg)

### Describe the bug

Instead of normal letters, there only appears ?

### Steps to reproduce / Cause of the issue

1. Just start the game
![20230420190824_1](https://user-images.githubusercontent.com/71571170/233438812-436e4020-08b8-49c4-8cc8-854adb5a9f1e.jpg)

### Expected behaviour

I was expecting it would work ngl

**Comment by runelead00** [comment]
Are you launching the game in English?, this looks like what happens when you try to load the game in non-English without a proper translation patch
