### ISSUE TITLE
GNG - "an universal" Loc Error

### ISSUE THREAD

**Issue by SirJaguar** [TNODevs/TNO-Bug-Tracker#1740]
### HOI4 version

1.12.12

### TNO version

1.2.1b

### Do you have other mods in use?

Zizek's Ideology Bling, More Voicelines for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Should be "a universal" rather than "an universal" due to "universe" starting with a consonant Y sound rather than a vowel U sound.
![hoi4_hrWAZ51vNz](https://user-images.githubusercontent.com/51899758/233771871-5bdced92-58a7-4c09-8e10-cb8ae3a1ef45.png)
Personally, I think the word "even" should also be added. "but _even_ a universal spirit can be broken down" but that's my opinion. "Universal" is also a weird term to describe "spirit", but I'm sure it has Indonesia-specific connotations that make it appropriate.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
