### ISSUE TITLE
USA - Global Conflicts not resolving, and other bugs

### ISSUE THREAD

**Issue by JiggsPrime** [TNODevs/TNO-Bug-Tracker#1741]
### Operating System

Windows 10 64bit

### HOI4 version

v1.12.12

### TNO version

v1.4.1b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_1972_08_29_18.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11301370/USA_1972_08_29_18.zip)

### Describe the bug

the conflicts in the Dominican Republic, Haiti, and Iberia are all not resolving
Germany has not declared war on its slave uprising
I got the "four more years" event for Michael Harrington but the election UI says some guy named Henry Jackson is the NPP candidate

### Steps to reproduce / Cause of the issue

1. play the game and let the conflicts arise 
2. have Speer win in Germany maybe?
3. elect Michael Harrington in 1968, after Having RFK win and get assassinated, thereby having Stom Thurmond as President during  the 68 election

### Expected behaviour

I expected that the conflicts would eventually have a resolution, even if that resolution is a frozen conflict status. I expected Germany to declare war on its slave uprising. I expected to see Michael Harrington as the NPP candidate in the USA's election UI

### Screenshots

![20230422084548_1](https://user-images.githubusercontent.com/39681939/233785592-db0f8a34-5912-4f09-a494-063ec1dbdf62.jpg)
![20230422084554_1](https://user-images.githubusercontent.com/39681939/233785593-dd23e0e7-697b-4ac8-8e01-122280e9e095.jpg)
![20230422084601_1](https://user-images.githubusercontent.com/39681939/233785594-e1f791bc-1caa-43fa-80d6-6970259ad358.jpg)
![20230422084603_1](https://user-images.githubusercontent.com/39681939/233785595-3e21fb91-8fce-4ffe-b545-1bcdd6e5d7b9.jpg)
![20230422084610_1](https://user-images.githubusercontent.com/39681939/233785596-9dc398fb-df88-4f82-897a-bc2b84ed8f96.jpg)

### Additional information

for the Global conflicts, it occurs to me that these are conflicts that volunteers cannot be sent to. For Haiti and Iberia I have no idea what the end state is supposed to be, but the Dominican Republics uprising/civil war is just in a stalemate. It looks like the AI on both sides are just out of guns and manpower and therefor wont attack each other.

**Comment by ShiftyRail** [comment]
Can confirm it happened to me, but for Haiti (after I won as USA, instantly; see #1847), and the West African War (which Free France won).
Haiti is strange; I got the Victory in the Cold War interface but then the UI page is still there and the communist revolution is at near 100% control in every province, but doesn't pop up. 

As for the Iberian conflicts, they are just frozen in place. The Spanish Republic won the first war and then won't declare on anyone.
