### ISSUE TITLE
USA - Post WFB Bug

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#1742]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

There is an issue with the event “The Ontario Accords” (WFB.response.16). If you choose option a, there is a 60% chance that you will be directed to WFB.response.17, which has no effects and prevents the event chain from continuing.

### Steps to reproduce / Cause of the issue

1. Complete the focus "Fight for our Crops"

### Expected behaviour

WFB.response.17 shouldn't softlock the event chain.

### Screenshots

![1](https://user-images.githubusercontent.com/65211266/233793202-8a41d090-caeb-4ac8-93bf-6e05ccc21e72.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
