### ISSUE TITLE
USA - Harrington - Radical Higher Education Act cannot be triggered

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#1743]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The radical version of The Higher Education Act cannot be triggered.

### Steps to reproduce / Cause of the issue

The option b of harrington.51 should have "set_country_flag = USA_HAR_radical_education_reform".

### Expected behaviour

The radical version of The Higher Education Act should be triggered

### Screenshots

![2](https://user-images.githubusercontent.com/65211266/233793450-f0073508-4252-4315-9d04-a1e189e69493.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
