### ISSUE TITLE
USA - Hart

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#1745]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

TNO_USA_Hart_shared, TNO_America_RDC_D, TNO_USA_decisions, and TNO_US_scripted_effects.

In these files, for set_temp_variable = { USA_temp_upkeep_cost_var = xxx } , the positive and negative signs in front of xxx are all reversed without exception. In fact, only if USA_temp_upkeep_cost_var is negative, it will increase The Budget in the Hart Monitor. Only if USA_temp_upkeep_cost_var is a positive number, it will reduce The Budget i in the Hart Monitor.

it seems that the mechanic was coded with this in mind: a positive number is to increase the budget, and a negative number is to reduce the budget. This isn't true - they did not take into account the code written in the Hart Monitor. This part of TNO_US_scripted_effects must be adjusted accordingly like this
![8](https://user-images.githubusercontent.com/65211266/233793920-e96dac56-1797-44ae-bdcd-7bdb1e6d52b9.PNG)

### Steps to reproduce / Cause of the issue

Play as Hart.

### Expected behaviour

Negative upkeep cost decreases The Budget and vice versa.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
