### ISSUE TITLE
Haiti- cantave coup not working 

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#1746]
### Operating System

windows 11

### HOI4 version

1.12.11

### TNO version

v1.4.1b

### Do you have other mods in use?

Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

when the coup happens it there no cantave and it happens again a few months  

### Steps to reproduce / Cause of the issue

play the game 

### Expected behaviour

I did use Custom Country Paths 

### Screenshots

![20230422121124_1](https://user-images.githubusercontent.com/50662994/233795174-0ec2395b-ad91-46d0-a9d0-7d976f97e248.jpg)
![20230422121448_1](https://user-images.githubusercontent.com/50662994/233795175-0a65f226-5b8c-48b6-b16c-1a82ffafe6ae.jpg)
![20230422121529_1](https://user-images.githubusercontent.com/50662994/233795176-c50f0ace-6cc3-4f6d-9fba-37aaeae5453d.jpg)

### Additional information

not look at the pp

**Comment by runelead00** [comment]
Fixed in Dev Build
