### ISSUE TITLE
United States - Mislabelled Democrat-Republican events

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1747]
### HOI4 version

1.12.11

### TNO version

1.4.1

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Since the Democrats and Republicans were switched. Some events have mistakenly labelled them incorrectly, referring to a Democrat as Republican and vice versa.
This was seen in the event GLD.6, which triggers after the passing of "Reduce Agricultural Subsidies" focus.
![image](https://user-images.githubusercontent.com/25708474/233805967-6865654f-2165-4943-8340-10e873614b8b.png)

There may be others, but this one was seen.

### Additional information

Submitted by Turbobounce on request by the TNO Discord user CEOofChernobyl. Screenshot and description are theirs. They did not wish to create a Discord account and so I volunteered.

**Comment by runelead00** [comment]
Fixed in Dev Build
