### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by SirJaguar** [TNODevs/TNO-Bug-Tracker#1749]
### HOI4 version

1.12.11

### TNO version

1.2.1b

### Do you have other mods in use?

Zizek's Ideology Bling, More Voicelines for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Probably should be "wriggled" instead of "wrigged"
![image](https://user-images.githubusercontent.com/51899758/233864459-533bbbcd-6e73-4bd1-a8d9-dd32a5873878.png)

**Comment by Stormeagle449** [comment]
Fixed for TNO 1.4.1c
