### ISSUE TITLE
Germany - Great game randomly reset after the 5th turn as I was about to win

### ISSUE THREAD

**Issue by Kustogg** [TNODevs/TNO-Bug-Tracker#175]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Current (Pre-NSB)
- TNO Version: TNO-1.2.0a "Toolbox Theory"
- Any other mods in use: CSS flavor and State transfer tool 
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
I had won 3 turns of the great game against Italy so I was guaranteed to win but after the 5th turn, Bulgaria went into isolation and the great game decision just completely reset Germany and Italy's wins to 0 

**Steps to Reproduce/Cause Issue:**

1. Play Germany or Italy

2. Play great game 

etc...

**Screenshots:*
![unknown](https://user-images.githubusercontent.com/38846338/142758051-03c77e58-5912-4a3e-8f9d-cb28ae3806ab.png)
*

**Comment by runelead00** [comment]
getting cut on UB, should no longer be an issue
