### ISSUE TITLE
GNG - missing "to"

### ISSUE THREAD

**Issue by SirJaguar** [TNODevs/TNO-Bug-Tracker#1751]
### HOI4 version

1.12.11

### TNO version

1.2.1b

### Do you have other mods in use?

Zizek's Ideology Bling, More Voicelines for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

"able to rest" rather than "able rest"
![hoi4_dBxKWfpHFQ](https://user-images.githubusercontent.com/51899758/233993222-4c90492f-426d-47d7-b1e2-bab27391a00e.png)

**Comment by Stormeagle449** [comment]
Fixed for TNO 1.4.1c
