### ISSUE TITLE
ALL - Fulbe War Not Ending

### ISSUE THREAD

**Issue by SirJaguar** [TNODevs/TNO-Bug-Tracker#1752]
### Operating System

Windows 11

### HOI4 version

1.12.11

### TNO version

1.2.1b

### Do you have other mods in use?

Zizek's Ideology Bling, More Voicelines for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11310464/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11310465/game.log)
[TNO - Guangdong - 28.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11310471/TNO.-.Guangdong.-.28.zip)

### Describe the bug

Fuuta Fulbe has not capitulated.

### Steps to reproduce / Cause of the issue

1. West African War with two factions. The French won, I think.
2. There was another war later on where the French faction invaded Fuuta Fulbe but I guess that never ended.
3. France won the mainland back and joined the OFN, although, I don't know if that's super relevant.

### Expected behaviour

I assume that war should be over and Free France should not perpetually own that sliver of land.

### Screenshots

![hoi4_msoatbm17I](https://user-images.githubusercontent.com/51899758/233996186-a68076e0-0546-479a-9b3b-380149e52d3f.png)
![hoi4_8m7GIXhqyh](https://user-images.githubusercontent.com/51899758/233996312-991a66fe-0d04-40df-aa41-ef7113c57a8b.png)
![hoi4_m119MJ4eRa](https://user-images.githubusercontent.com/51899758/233996524-08a1e1dc-3654-4895-94fc-9c89be3255b0.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
