### ISSUE TITLE
GER - Full operation strength bar shown in the Puerto Plata Invasion decisions after selecting the event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1755]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.11

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11328343/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11328344/game.zip)

### Describe the bug

After selecting the 'Status of the Dominican Republic' event, the 'Operational Strength' bar in the Puerto Plata Invasion decisions shows fully but the numbers of the 'Operational Strength' is not completely maximum to full. 
 
And also, there is no 'blue' Operational Strength shown in the bar.  

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. 'Status of the Dominican Republic' event pops out and select the event.
3. See the 'Operational Strength' bar in the global conflicts' Puerto Plata Invasion decisions.

### Expected behaviour

I don't know what causes this. 

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/234449263-6acbf314-108e-407e-baab-9a019020c065.png)
![Image_02](https://user-images.githubusercontent.com/131833099/234449280-40475610-98f9-4c2b-822d-eb8c4cd86e58.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
