### ISSUE TITLE
GER - Can receive research bonus of Anti-Air instead of giving to Dominican Republic

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1756]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.11

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

The decision effects of 'Send Prototype AA Weaponry' shows that GER will receive the Anti-Air research bonus when selecting the decision instead of giving the Anti-Air research bonus to Dominican Republic. 

And also, because of the word "Send".

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. 'Status of the Dominican Republic' event pops out and select the event.
3. See the decision effects of 'Send Prototype AA Weaponry'. 

### Expected behaviour

Forgot to add Dominican Republic in the decision effect, probably.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/234467029-2d07a5d3-435d-4408-85c9-76a35d11ed3a.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Intended, Germany gets to test their prototype AA in the Domincan Republic and get a research boost for it, while they get reduced bombing effects in the PPI
