### ISSUE TITLE
GER - No loc for GER_MADCW_america_do_less_tt

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1757]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.11

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

No needed.

### Describe the bug

`GER_MADCW_america_do_less_tt` has no loc in the decision effect of 'Target Rebel Leaders'.

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. Has Second Malagasy Uprising proxy war.
3. Set stage 2 for Second Malagasy Uprising.
4. See the decision effects of 'Target Rebel Leaders'.

### Expected behaviour

Forgot to adding loc, probably.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/234471860-0e8cfc89-4a4e-4c8c-a37a-9cb87d9b7e6a.png)

### Additional information

I have no other info about this issue.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
