### ISSUE TITLE
GER - Disconnected Settlements is somehow added a target in 'Transfer Military Aircraft' decision effect

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1758]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.11

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

No need.

### Describe the bug

The 'Transfer Military Aircraft' decision effect has also targeted Disconnected Settlements but those anarchy states have no divisions, so this decision should target Malagasy Rebellion only.

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. Has Second Malagasy Uprising proxy war.
3. Set stage 2 for Second Malagasy Uprising.
4. See the decision effects of 'Transfer Military Aircraft'.

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/234472997-58db1021-b4ef-4508-a0a6-f9e0795389a0.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
