### ISSUE TITLE
GER - The nodes do not go increase its strength when selecting some 2MU decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1759]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.11

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11330453/error.zip)
[error_2.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11330454/error_2.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11330455/game.zip)
[game_2.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11330456/game_2.zip)

### Describe the bug

When selecting some decisions that have increasing node strength except the 'Provide Local Reconnaissance' decision in the 2nd Malagasy Uprising, the selected node doesn't go increase. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. Has Second Malagasy Uprising proxy war.
3. Select some decisions that have increased node strength except the 'Provide Local Reconnaissance' decision.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/234508376-a003f1f3-98f0-4d11-8632-bee54a399adf.png)
![Image_02](https://user-images.githubusercontent.com/131833099/234508391-d63fe887-a91d-4ce6-ba94-f3929f0aa11d.png)
![Image_03](https://user-images.githubusercontent.com/131833099/234508398-b367a59d-d41d-43d8-bdf3-0d79c3740f37.png)
![Image_04](https://user-images.githubusercontent.com/131833099/234508404-0abde6ac-3025-4dad-af75-ef13ecd3490a.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
