### ISSUE TITLE
MDG - Madagascar becomes a puppet of Germania /  that one tile is still an ocean

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#176]
![Hearts of Iron IV 21_11_2021 9_38_44 PM](https://user-images.githubusercontent.com/59920852/142758617-de94852d-bc97-4926-8eaf-7bfacc6ef8b9.png)
Names all weird and the tile on Madagascar's east coast is still underwater

**Comment by Scarsoftime** [comment]
Fixed. Please properly follow the bug reporting scheme next time.
