### ISSUE TITLE
GER - Missing targeted states in some Second Malagasy Uprising decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1760]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11331490/GER_game.zip)

### Describe the bug

In the 'Undermine Rebel Control' and 'Run Localized Terror Operations' decisions effect, there are states that have no effect. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. Has Second Malagasy Uprising proxy war.
3. Select some decisions that have targeted states in the Second Malagasy Uprising global conflict.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/234540550-79e3b49b-1581-448c-a51c-6d658e6f78d5.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235347467-e476d20d-c788-4774-b661-61f57640fcd1.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
