### ISSUE TITLE
GER - Despite Trujillo wins the PPI, there is a word "Santo Domingo" instead of "Cuidad Trujillo"

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1761]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11331674/game.zip)

### List the loc issues below

![Image_1](https://user-images.githubusercontent.com/131833099/234547884-244ee62b-88fe-4a9d-bffe-8d5355f4735a.png)
![Image_2](https://user-images.githubusercontent.com/131833099/234547896-c064cb68-1f6d-4612-9bf2-243b0ce0170b.png)
![Image_3](https://user-images.githubusercontent.com/131833099/234549166-c3070262-c3c1-4460-85fd-6dd254934d18.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Non-issue, state lore says it itself, most people still refer to the city as Santo Domingo, even it's name has formally changed
