### ISSUE TITLE
GER - The Rova Coup event triggers despite after winning the 2nd Malagasy Uprising before Hitler's Death

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1762]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11333392/GER_game.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11333397/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11333398/game.zip)

### Describe the bug

After winning the Second Malagasy Uprising before Hitler's death and Hitler's death event triggers, the 'Rova Coup' event, however, is triggered and Madagaskar has taken over by Milch, and the event and Milch's description say about the ongoing uprising but the Second Malagasy Uprising is over and the rebels are beaten. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. Has Second Malagasy Uprising proxy war.
3. Win the Second Malagasy Uprising against the Malagasy rebels before Adolf Hitler's death.
4. Paktkommission is in charge of Madagaskar.
5. Death of Adolf Hitler triggers.
6. 'Rova Coup' event triggers.

### Expected behaviour

I don't know if this is intended or what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/234591134-64dbc778-4056-4c3b-92f3-07df5436c01e.png)
![Image_2](https://user-images.githubusercontent.com/131833099/234591147-e8075627-d898-488a-9f88-29ec37f8797a.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
