### ISSUE TITLE
USA - Philippine Conflict doesn't end after FRP defeats Japanese 14th Army and Communists

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1764]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11333979/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11333980/game.zip)

### Describe the bug

After FRP defeats both the Japanese 14th Army and its former ally, the Communists, the Philippine Conflict doesn't end. 

And in the Cold War Achievements, the Philippine Landing declares 'Victory' for USA but not 'Total Victory' because of the three-way war and FRP defeats them both. 

Probably cause when the Communists or Free Filipinos defeated the 14th Army first.

### Steps to reproduce / Cause of the issue

1. Coup in the FRP succeeds.
2. Balintawak Blintz success and FRP taking Manila.
3. Philippine Landing starts.
4. Communists defeat the 14th Japanese Army.
5. FRP defeats Communists.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/234606835-0b99dd7f-e7bc-4770-8ae8-82e803ef7f60.png)
![Image_2](https://user-images.githubusercontent.com/131833099/234606848-a62fdad8-7618-4649-bda6-b23b6f6970ff.png)
![Image_3](https://user-images.githubusercontent.com/131833099/234606852-3b29f4fc-72f5-4d9e-b2cd-652db5585020.png)
![Image_4](https://user-images.githubusercontent.com/131833099/234606857-d287f479-a2a7-4513-9f88-0e1e62695216.png)
![Image_5](https://user-images.githubusercontent.com/131833099/234607403-7499871b-efd6-4063-93bd-2550ec92a442.png)
![Image_01](https://user-images.githubusercontent.com/131833099/234779686-2fb04c54-a2f4-4453-a565-19471acdbc18.png)

### Additional information

I have no other info about this issue.

**Comment by the-gemperor** [comment]
Have the same issue. I actually reloaded an earlier save and redid the landing, and it was still the same

**Comment by runelead00** [comment]
Fixed in Dev Build
