### ISSUE TITLE
USA - First CRA passage description doesn't reflect year it was passed

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1766]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11338698/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11338699/game.log)

### List the loc issues below

![image](https://user-images.githubusercontent.com/98370487/234737277-5ee0840e-4b18-4488-8df8-87baec6d7155.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
