### ISSUE TITLE
GER - 'Heydrich Dead' event gives increase NS popularity instead of Fascism as Speer

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1767]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.11

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11338957/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11338958/game.zip)

### Describe the bug

After Speer wins the German Civil War, the 'Reinhard Heydrich Found Dead' event gives increase National Socialism party popularity instead of Fascism.

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. Choose Albert Speer as a successor.
3. German Civil War triggers.
4. Speer's Germany wins the Civil War.
5. 'Heydrich Dead' event triggers.

### Expected behaviour

Forgot to add Fascism increase in 'Reinhard Heydrich Found Dead' event when Speer is victorious, probably.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/234743439-5d15a8d5-9f5f-48c0-8e30-32258857c360.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
