### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Welp-there** [TNODevs/TNO-Bug-Tracker#1768]
### Operating System

windows 11

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

Brave New Wolrd

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11339174/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11339175/game.log)

### Describe the crash

I tried to start the game and about 35-40 ercent though the start up the game just gives a 

### Steps to reproduce / Cause of the crash

have these mods activated
TNO
Brave new world
TNO: economic cheat
Toolpakt for TNO
Then click start then you will get a map loading error.

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/131302040/234749048-6e9506f3-bb64-42f9-89e3-b49651eecb0f.png)

**Comment by runelead00** [comment]
BNW isn't updated to newest hotfix yet
