### ISSUE TITLE
GER - 'The Northern Question' national focus can bypass without getting focus effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1769]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11339357/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11339359/game.zip)

### Describe the bug

After selecting 'The Fortress Up North' decision as Speer's German Reich, 'The Northern Question' national focus is able to bypass without getting the national focus effects. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich (GER).
2. Choose Albert Speer as a successor.
3. Speer's Germany wins the Civil War.
4. Select 'The Fortress Up North' decision.
5. 'The Northern Question' national focus is able to bypass. 

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/234755030-b459fd60-c2c5-4e5d-b8ef-53dcc0999fe7.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
