### ISSUE TITLE
WRRF - Power struggle decisions not available

### ISSUE THREAD

**Issue by comradejuju** [TNODevs/TNO-Bug-Tracker#177]
**Questions**

- Operating System: MacOS Mojave
- HOI4 Version: v1.10.8
- TNO Version: v1.2.0
- Any other mods in use: TNO music mods, bigger counter for TNO, TNO loading screen redone, TNO custom country paths
- Were you using Steam? Yep
- Which expansions do you NOT have? None

**Longer Description of Issue:**
I was playing as WRRF and after I chose the option to support Tukhachevsky, I briefly saw the power struggle UI, but it no longer shows. Completed another two focuses to give Tukh influence but it is still hidden from the decisions tab.

**Steps to Reproduce/Cause Issue:**

1. Play WRRF up to focus "Pertinent Matters"

2. Select Tukhachevsky (Presumably this also works if choosing Zhukov, but I don't know 100%)

3. The power struggle UI may be visible for a day or two, but the decisions are not available.

4. UI should then disappear. Won't reappear after completing more Tukhachevsky focusses. 

**Screenshots:**
<img width="1440" alt="Screenshot 2021-11-21 at 10 36 59 pm" src="https://user-images.githubusercontent.com/90958045/142760236-7e197304-1d4e-4107-a863-9daad556ead2.png">

<img width="1440" alt="Screenshot 2021-11-21 at 10 36 48 pm" src="https://user-images.githubusercontent.com/90958045/142760239-b236ef2b-1962-4326-96fd-b03c85acd9ab.png">

**Comment by Wizard2020** [comment]
I am pretty sure your problem is using the custom country paths submod. It hasn't been updated to be compatible with TT and using it will cause problems. You should wait for its TT compatibility update before using it again.
