### ISSUE TITLE
GER - 'Operation Armbanduhr' intelligence decision is not unlock despite the requirements are met

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1770]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11342671/GER_game.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11342674/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11342675/game.zip)

### Describe the bug

Despite the intelligence requirements being met, the 'Operation Armbanduhr' intelligence decision is not unlocked.

And also, there are some intelligence decisions USA and Germany are not unlocked despite their requirements being ok.

### Steps to reproduce / Cause of the issue

1. Play as Speer's Greater German Reich (GER).
2. Have the Intelligence Agency.
3. Emil Maurice Escape event triggers.
4. See Special Mission in the African Region from Intelligence Agency.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/234843930-10ac1b31-ab35-463a-bc0d-5252915a006f.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
