### ISSUE TITLE
PAR - Still has 'The Shadow Province' idea despite being communist and at war with Argentina

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1771]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11343338/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11343339/game.zip)

### Describe the bug

Despite Paraguay turning communist and being at war with the Triple Alliance, 'The Shadow Province' national spirit still exists. 

### Steps to reproduce / Cause of the issue

1. Paraguay becomes a communist nation.
2. Argentina, Brazil, and Uruguay declare war on Paraguay.
3. See Paraguay's national spirits.

### Expected behaviour

Forgot to remove it when Paraguay goes communist or at war with Argentina, probably.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/234858837-cc18ccc2-bef9-42cf-bc38-0fa7609bf01e.png)

### Additional information

I have no other info about this issue.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
