### ISSUE TITLE
GER/USA/ENG - 'An Atlantic Battleground' global conflict image is somehow change and it's not suitable

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1772]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11343605/GER_game.zip)

### Describe the GFX issue

The image of 'An Atlantic Battleground' in global conflict is somehow changing when selecting other proxy conflicts or switching feature tags.

And the image of 'An Atlantic Battleground' for GER, USA and ENG should be changed to an image of English Parliament Building or the previous image before transferring to the global conflict decision tab. 

### Steps to reproduce / Cause of the issue

1. Collab England wins the English Civil War.
2. England enters the world stage.
3. The Battle for England triggers.
4. See the 'An Atlantic Battleground' global conflict image.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/234865301-097cdb86-8f14-4624-bb01-ddb033582d14.png)
![Image_2](https://user-images.githubusercontent.com/131833099/234865314-ffe060ff-4695-4139-aedf-b1db4a6d290c.png)
![Image_3](https://user-images.githubusercontent.com/131833099/234865320-fd98b8f2-af7e-4cff-ae80-72998bbbdf77.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
