### ISSUE TITLE
USA - Bennett's inaguration isn't updated to the new lore

### ISSUE THREAD

**Issue by Crazyita** [TNODevs/TNO-Bug-Tracker#1773]
### HOI4 version

1.12.11

### TNO version

1.4.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Bennett's inaguration event says that he's the first republican since WW2. This was true in the old lore but is not the case in the new lore.
![image](https://user-images.githubusercontent.com/93662386/234911494-06caa2bc-e941-46b8-a17f-29e9897b0bea.png)

**Comment by Stormeagle449** [comment]
The event is correct, the last republican president was Dewey and he was elected in '44.

**Comment by Crazyita** [comment]
Im confused; I thought that Nixon was a Republican in the "new" lore (as opposed to Democratic as was in the release version, I believe), shouldnt Nixon count as a Republican president?
