### ISSUE TITLE
TNO keeps crashing

### ISSUE THREAD

**Issue by Athar1140** [TNODevs/TNO-Bug-Tracker#1774]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11347342/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11347344/error.log)

### Describe the crash

the game crashes on the startup

### Steps to reproduce / Cause of the crash

Open HOI4
Wait 
crash

### Additional information

Idk

**Comment by Athar1140** [comment]
how to fix it dude. its been a week

**Comment by NhanTNTOfficial** [comment]
it's been 6 months

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/961, can only recommend possible fixes listed there
