### ISSUE TITLE
GER - Reichskommissariat Ukraine makes peace with the rebels after taking 'Retake Ukraine' decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1776]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_ukraine.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11352390/GER_ukraine.zip)

### Describe the bug

When the Ukrainian Civil War is still ongoing and after selecting the 'Retake Ukraine' decision as Speer or Bormann Germany and Reichskommissariat Ukraine become subject again, Reichskommissariat Ukraine is suddenly making peace with the rebels and while Germany declares war on the rebel.

### Steps to reproduce / Cause of the issue

1. Win the German Civil War as Speer or Bormann.
2. Ukrainian Civil War is still ongoing.
3. Germany begins to reclaim lost conquest in Eastern Europe.

### Expected behaviour

Forgot to add Reichskommissariat Ukraine to declare war on the rebels in 'Retake Ukraine' decision.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235118636-fa6de38f-38ad-4f5a-8842-29ab08a26a3e.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235118644-5749458d-db83-4fb2-a273-0c3138f26704.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
