### ISSUE TITLE
All Countries - Armored car tech localization issues

### ISSUE THREAD

**Issue by hagamablabla** [TNODevs/TNO-Bug-Tracker#1779]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- Inconsistent spelling of "Armored Car". The column on the tech tree is spelled "Armored Car", but the techs are labeled as "X Armoured Car Chassis".
![image](https://user-images.githubusercontent.com/1676710/235151654-fa527d3d-0df9-41a3-bb7b-5b8076bbff93.png)

- Incorrect labeling for final armored car tech. Vehicle techs are supposed go early -> basic -> improved -> advanced -> semi-modern -> modern. However, for armored cars the final tech is also labeled as "Advanced Armoured Car Chassis" rather than "Modern Armoured Car Chassis".
![image](https://user-images.githubusercontent.com/1676710/235151873-af2154be-a16a-402d-81c1-540bf89481bd.png)
![image](https://user-images.githubusercontent.com/1676710/235151997-33e23371-118a-4d75-a97e-89a7735df843.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
