### ISSUE TITLE
Novosibirsk - Feniks Factories in America bug

### ISSUE THREAD

**Issue by RealHumppi** [TNODevs/TNO-Bug-Tracker#178]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0 (Toolbox Theory)
- Any other mods in use: Radio TNO: Music of The New Order
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosporus

**Longer Description of Issue:**
When selecting the "Build Feniks Military factories in America" decision as Novosibirsk in Regional stage, it causes Southern California's GDP to plummet by 98% (written in decision description)
**Steps to Reproduce/Cause Issue:**

1. Select Novosib geopolitical tree's first focus in Regional, starting the "A Tale of Two Megacorps" mechanic.

2. Select "Build Feniks Military factories in America" from the "OFN" tab in the menu

3. Watch as California's GDP sinks to third-world levels

Sorry for possibly poor report, I'm not an expert in these things

**Screenshots:**
![novosibruh1](https://user-images.githubusercontent.com/94785861/142760317-451039d8-92f9-4275-80a1-d52260553df4.png)
![novosibruh2](https://user-images.githubusercontent.com/94785861/142760319-4912c05d-202e-4a17-bed6-48639ab7c505.png)

**Comment by Scarsoftime** [comment]
Fixed
