### ISSUE TITLE
GER/NOR - Norway has Bündnispartner despite being subject (Collaborator) as Speer's Germany

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1780]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11353605/GER_game.zip)

### Describe the bug

When Norway rejoins the Pakt and becomes subject again through Speer's Germany foreign focus tress, Norway has Bündnispartner despite being a puppet.

While other independent Pakt members have the Bündnispartner due to this.

### Steps to reproduce / Cause of the issue

1. Won the German Civil War as Speer's Germany.
2. Retake Norway.
3. Complete all of Speer's Norway focus trees.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235141044-d647fa46-822f-4ef2-b825-8495b4867ec4.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235141053-e0353758-06a2-4fa1-9166-795a9e5f080b.png)
![Image_3](https://user-images.githubusercontent.com/131833099/235141055-73c5a29b-67f1-4cae-8403-14588f16a867.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
