### ISSUE TITLE
All tags - 'alt_MBT' has no loc and AFV icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1781]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11353880/GER_game.zip)

### Describe the bug

When I edited the division template to change the armored battalion, I saw no loc for 'alt_MBT' and has the icon the same as AFV icon. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tags.
2. See Armored Battalions in the division template.

### Expected behaviour

Forgot to added loc and the icon, I think

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235159827-fe1170bc-d16b-4b8b-9d13-98fb613ef8f5.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
