### ISSUE TITLE
UKR - 'Not Their War' national spirit doesn't get removed after German Ukraine wins the CW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1782]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11354088/autosave.zip)

### Describe the bug

When Reichskommissariat Ukraine wins the Ukrainian Civil War, the 'Not Their War' national spirit still exists and doesn't get removed.  

### Steps to reproduce / Cause of the issue

1. German Civil War starts.
2. Einheitspakt collapses.
3. Ukrainian Civil War triggers.
4. Either Speer or Bormann wins the CW.
5. Germany intervenes in UCW due to ongoing.
6. Reichskommissariat Ukraine wins the CW.

### Expected behaviour

Probably forgot the national spirit once the Reichskommissariat Ukraine wins the CW.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235165686-83ba13d9-7404-4969-a55c-f75b148afec3.png)

### Additional information

I have no other info about this issue.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
