### ISSUE TITLE
Guangdong - WAC Peace conference causes crash

### ISSUE THREAD

**Issue by Artelectual** [TNODevs/TNO-Bug-Tracker#1783]
### Operating System

Windows 10

### HOI4 version

1.12.12.456f Avalanche

### TNO version

1.4.1c - Ugly American

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11356649/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11356650/game.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11356652/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11356655/system.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11356659/code_revisions.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11356662/graphics.log)
[Save file]https://drive.google.com/file/d/1gVyBBbXhQfp6WRrSyH2aAib6EsygsRKz/view?usp=sharing

### Describe the crash

Game crashes when the peace conference for WAC pops up

all I see is "Peace Conference is over" "Calculating effects..." and the game crashes
It seems to happen on either 5 or 6 June 1964

### Steps to reproduce / Cause of the crash

1. Load up save
2. wait until June 5th or 6th
3. peace conference message pops up and game crashes

**Comment by runelead00** [comment]
Fixed in Dev Build
