### ISSUE TITLE
CAU - King Josias Portrait Missing

### ISSUE THREAD

**Issue by TheShinrog** [TNODevs/TNO-Bug-Tracker#1784]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11357991/error.log)

### Describe the GFX issue

Josias's king picture isn't there.

### Steps to reproduce / Cause of the issue

Basically, there is an extra ".dds" in the event file for CAU. "portrait = "gfx/leaders/GER/Portrait_Caucasus_Josias_Kaiser.dds.dds""

EDIT: also, it says GER when instead it should say CAU, he also doesn't have any description and is assigned random leader traits.

### Expected behaviour

I expected a portrait. Nothing much else to add

### Screenshots

![20230428203230_1](https://user-images.githubusercontent.com/132112899/235273668-3753b647-e409-4ce6-bd99-deed0d24f8d4.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
