### ISSUE TITLE
GER/CAU - Germany has no resource rights on Kaukasien after Kaukasien brings into the fold as Speer

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1785]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11358350/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11358351/game.zip)
[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11358352/GER_game.zip)

### Describe the bug

When Kaukasien becomes subject again to Germany after Germany brings Kaukasien into the fold either peace or war, there are no German resource rights on Kaukasien. 

I don't know if this issue is affected when Speer reforms Eastern Europe governments. 

### Steps to reproduce / Cause of the issue

1. Speer's Germany wins the German Civil War.
2. Paul Pleiger successfully overthrows Josias or Josias secures his position in Kaukasien.
3. Germany retakes Kaukasien.

### Expected behaviour

Probably forgot to add resource rights on Kaukasien for Speer's Germany once Kaukasien rejoins the Pakt.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235283606-1f955b21-8f19-4ab5-a8ca-7cb1daf9a4cc.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
