### ISSUE TITLE
USA/HAITI - Cantave anti-Communist Coup Constantly occurs

### ISSUE THREAD

**Issue by TheShinrog** [TNODevs/TNO-Bug-Tracker#1786]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The coup that Cantave launches constantly happens. It will kill him and then a random leader will take over, and then it will happen again, and again.

### Steps to reproduce / Cause of the issue

From what I could tell, is that there is nothing to prevent it from happening over and over again.  Perhaps adding a flag that would prevent it from triggering again would help.

### Expected behaviour

Should only happen once

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Angelblue1852** [comment]
Does this also cover the Constitutional Referendum?
