### ISSUE TITLE
All tags - 'alt_APC' has no loc

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1787]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11358421/GER_game.zip)

### Describe the bug

When I edited the division template to change the mobile battalion, I saw no loc for 'alt_APC.

### Steps to reproduce / Cause of the issue

1. Play as any feature tags.
2. See Mobile Battalions in the division template

### Expected behaviour

Forgot to added loc, I think

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235284492-3060aa1b-25ce-4cf4-9cd7-f6b35c8f88ce.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
