### ISSUE TITLE
SHO - Add world news event about the Japanese wins against UMAJF 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1790]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest adding the world news event about Shonan-Marai Gunseibu victory against UMAJF during the Malayan Emergency.  

### Justifications

While there is a world news event about UMAJF victory, the Japanese victory against the UMAJF has no world news event. 

### Screenshots

Not needed.

### Additional information

I have no other info about this issue.

**Comment by FMGIV** [comment]
Yo, good work reporting issues over the last few days. Whats your discord username, might hit you up to be a tester if your interested.

**Comment by Ikidikid** [comment]
> Yo, good work reporting issues over the last few days. Whats your discord username, might hit you up to be a tester if your interested.

Hello. Thanks for the offer but I'm going to stay as is.

**Comment by runelead00** [comment]
Fixed in Dev Build, already was there, just only triggered for JAP
