### ISSUE TITLE
West Russia/West Siberia - Make completion of regional focus tree prerequisite for advancing to superregional tree

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1791]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Add a prerequisite to the decision "Russian Reunification" for having completed the regional tree before clicking the decision.

### Justifications

As West Russia or West Siberia, you have the ability to go to war with your neighbor in the Race for the Urals. In this, if you don't go for a ceasefire, you have the ability to destroy your opponent and unite early. However, the decision "Russian Unification" when clicked brings you to the superregional tree even if you haven't completed your regional tree, missing out on a lot of content if you weren't paying attention. I would suggest adding the prerequisite of having completed your regional tree first before taking the decision, since it could really mess up your game if you take it without saving first.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/235310494-f0d8d13f-424f-49f8-a90d-d1d6d33faca1.png)

### Additional information

I took the decision earlier in my game and this is how I found it out. The screenshot shows me after reloading to before the decision.

**Comment by runelead00** [comment]
We will not as some players would prefer to jump over the last bits of their regional tree near the end of the game and adding a hundred focus checks for the decision across all warlords is tedious and not worth the return
