### ISSUE TITLE
IBR - Command Power doesn't decrease when clicking 'Patrol the Coast' decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1792]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[IBR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11360581/IBR.zip)

### Describe the bug

When selecting the 'Patrol the Coast' decision in the global conflict, the command power doesn't decrease and the decision requires 25 CP. 

I don't know if the rest of Iberia's Puerto Plata Invasion decisions have the same issue as this one. 

### Steps to reproduce / Cause of the issue

1. Triumvirate collapses.
2. America, Cuba, and Mexico prepare to oust Trujillo's regime in the Dominican Republic by supporting Carribean Legion. 
3. Iberia and Germany backed Trujillo.
4. Select any of Iberia's Puerto Plata Invasion intelligence decisions.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235335275-527a4a52-6ee4-4554-bdeb-a23be98228e1.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235335277-b97ba505-72a6-4ba3-bf92-ce997d41819f.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
