### ISSUE TITLE
GER - Command Power doesn't decrease when clicking 'Coordinate with Dominican Intelligence' decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1793]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_PPI.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11360614/GER_PPI.zip)

### Describe the bug

After selecting the 'Coordinate with Dominican Intelligence' decision in the global conflict, the command power doesn't decrease, however.

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Triumvirate collapses.
3. America, Cuba, and Mexico prepare to oust Trujillo's regime in the Dominican Republic by supporting Carribean Legion.
4. Iberia and Germany backed Trujillo.
5. Select the 'Coordinate with Dominican Intelligence' decision and see Command Power.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235336564-6b1ef22a-254c-420e-a742-64538c0c8585.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235336565-f15de23a-9826-4d8d-bccb-cd7ccc43bbb4.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
