### ISSUE TITLE
MAD - Rebel divisions do not transfer to rebel hold states when the uprising starts

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1794]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11360661/GER_game.zip)

### Describe the bug

When the Second Malagasy Uprising triggers, the Malagasy Rebellion's divisions do not transfer to rebel-holding states.

### Steps to reproduce / Cause of the issue

1. French Madagascar situation becomes critical.
2. Second Malagasy Uprising occurs.
3. French administration in Madagascar collapsed and the Germans took control.
4. See Malagasy Rebellion's division.

### Expected behaviour

Forgot to transfer the rebel divisions to rebel territories, probably.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235338168-484fcab2-8aeb-449a-9c6a-d3ca7ec5cb49.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235338169-19946b03-bd6e-4aec-8324-5239eecfb419.png)
![Image_3](https://user-images.githubusercontent.com/131833099/235338173-4f9920bc-f469-43aa-9875-578570bc49c5.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Not something were can do
