### ISSUE TITLE
MDG - Some states do not have 'Base of Operations' state modifiers

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1795]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11360891/GER_game.zip)

### Describe the bug

When the Second Malagasy Uprising starts, some of the Militärverwaltung Madagaskar holdings do not have the 'Base of Operations' state modifier.

### Steps to reproduce / Cause of the issue

1. French Madagascar situation becomes critical.
2. Second Malagasy Uprising occurs.
3. French Madagascar collapses.
4. German garrisons took control of remaining colonial holdings.

### Expected behaviour

Forgot to add them, maybe.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235344712-b37942a9-61c3-4edc-b687-157edfeea082.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235344713-92a23276-2905-4528-b27b-9480c8dc4f21.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
