### ISSUE TITLE
GER - Slight no line break in prerequisites of 'Restore Order' decision 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1797]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11361063/GER_game.zip)

### List the loc issues below

1. In the 'Restore Order' decision, I saw a slight line break after not having the base of operations state modifier from prerequisites.
![Image_1](https://user-images.githubusercontent.com/131833099/235347719-6736313c-4bb9-4e6d-b75f-838258867974.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
