### ISSUE TITLE
GER - Two decisions that requires 10 German Factionalism goes decrease by 18% instead of 10% during stage 3 of SMU

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1802]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11363495/GER_play.zip)

### Describe the bug

After selecting the 'Tear Up Old Infrastructure' and 'Undemine Rebel Control' decisions that require 10 German factionalism during stage 3 of the 2nd Malagasy Uprising, the factionalism for Germany ended up decreasing by 18% instead of 10%. 

### Steps to reproduce / Cause of the issue

1. Second Malagasy Uprising occurs.
2. German garrisons fight the rebels.
3. Second Malagasy Uprising proceeds to stage 3.
4. Select the 'Organize Police Harassment' decision.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235409207-db18fc50-3252-4d90-a44d-0c756f7f7373.png)
![Image_02](https://user-images.githubusercontent.com/131833099/235409209-865aa160-a5c9-4703-8b9e-c6442b7b4896.png)
![Image_03](https://user-images.githubusercontent.com/131833099/235409211-955b8e6a-5d22-439a-abde-c12071fd2094.png)

### Additional information

I have no additional info.

**Comment by runelead00** [comment]
Fixed in Dev Build
