### ISSUE TITLE
GER - Factionalism doesn't reach 100% after increasing either German or French favor

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1803]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11363613/GER_play.zip)

### Describe the bug

I play as Germany. After selecting the decisions that have increased German favor for factionalism, 'The Reich' favor doesn't reach 100%. 

### Steps to reproduce / Cause of the issue

1. Second Malagasy Uprising occurs.
2. German garrisons fight the rebels.
3. Second Malagasy Uprising proceeds to stage 3.
4. Select the decision that has an effect to increase Gemrna factionalism.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235410172-cbbd662c-72bb-4e76-9fe5-5b13ebf793d6.png)
![Image_02](https://user-images.githubusercontent.com/131833099/235410177-302c5ce6-86ba-4ef2-b886-bc7eecfa135d.png)
![Image_03](https://user-images.githubusercontent.com/131833099/235410181-9e6aee01-603f-4afc-a082-affc051273aa.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Intended, factionalism caps at 99% to prevent an issue where the shader breaks
