### ISSUE TITLE
MDG/MAD - Militärverwaltung Madagaskar is defeated itself in the diplomatic alert after the SMU

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1804]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11363689/GER_play.zip)

### Describe the bug

After Militärverwaltung Madagaskar defeats the Malagasy Rebellion, the 'Diplomatic Alert' shows "Militärverwaltung Madagaskar has defeated Militärverwaltung Madagaskar in a war". 

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Second Malagasy Uprising triggers.
3. German garrisons have crushed the rebels. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235411885-1035ae9a-59aa-4b4d-b8ce-ea0a4a8b5778.png)

### Additional information

I have no other info about this issue.

**Comment by Stormeagle449** [comment]
Should be fixed in current release.
