### ISSUE TITLE
MAD - Militärverwaltung Madagaskar and Disconnected Settlements do not remove in 'Foreign Claims' states after the SMU

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1805]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_2MU.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11363849/GER_2MU.zip)

### Describe the bug

After the German garrisons defeat the rebels, Militärverwaltung Madagaskar and Disconnected Settlements still have claims on most of the Madagaskar states and doesn't remove them. 

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Second Malagasy Uprising triggers.
3. German garrisons have crushed the rebels.
4. See details for Madagaskar states.

### Expected behaviour

Forgot to remove them, probably.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235416734-0a86ffcf-df32-4fd5-98c7-faad1bdd840e.png)
![Image_02](https://user-images.githubusercontent.com/131833099/235416739-55d1c2ae-505d-45f6-83de-e9cc6c66e050.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
