### ISSUE TITLE
MAD - No description about the state modifiers in Madagascar due to blank during the SMU

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1807]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When the Second Malagasy Uprising starts, the state modifiers in Madagascar have no or blank descriptions. 

### Steps to reproduce / Cause of the issue

1. Second Malagasy Uprising triggers.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235442530-3db86ffa-a244-45be-b1e4-c49b17c5c10d.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235442536-4b3f9a9c-008c-43a5-9919-32916840c3f1.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build, no descs were intended, but HoI4 displays the blank placeholder "" desc for some reason
