### ISSUE TITLE
MAD/MDG - All impassable states have state modifiers except the Tsaratanana Massif state

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1808]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_SMU.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11365046/GER_SMU.zip)

### Describe the bug

When the Second Malagasy Uprising starts, there are state modifiers on all impassable states except one, Tsaratanana Massif.

I think the state modifiers should be removed on impassable states because those impassable states are not allowed division there.  

### Steps to reproduce / Cause of the issue

1. French Madagascar situation going critical.
2. Second Malagasy Uprising triggers.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235444754-f99c3d8f-b181-41c4-a8bd-851e60f24618.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235444757-d8e8452e-7cda-4495-afeb-17587727bac9.png)
![Image_3](https://user-images.githubusercontent.com/131833099/235444759-318bd441-efa4-4e5d-8541-3bd5483e3389.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
