### ISSUE TITLE
GER - A slight space after the second paragraph in the Brandenburger Combat Strength description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1809]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_PPI_ceasefire.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11365368/GER_PPI_ceasefire.zip)

### List the loc issues below

1. In the Brandenburger Combat Strength description, there is a very slight space after the second paragraph of the description. 
![Image_1](https://user-images.githubusercontent.com/131833099/235452664-0c69b1c6-3546-401c-819a-ecdb77584182.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
