### ISSUE TITLE
SPH/UPH - There is a word "USFIP" instead of "FRP" in Co-Founder of the United Filipino Front

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1810]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_philippine_war.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11365461/GER_philippine_war.zip)

### List the loc issues below

1. In the Co-Founder of the United Filipino Front description, there is the word "USFIP" instead of "FRP" because of changing from USFIP to FRP(Free Philippine Republic).
![Image_1](https://user-images.githubusercontent.com/131833099/235456132-a80c8053-0b14-49bc-9336-9724c891755a.png)

### Additional information

I have no other info about this issue.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
