### ISSUE TITLE
SPH - Doesn't rename to "Republic of the Philippines" but instead rename to pre-war "Free Philippine Republic" after Marcos coup

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1813]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11368885/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11368887/game.zip)

### Describe the bug

After the communists win the Philippine conflict and then Marcos coup the communist government, SPH changed to the pre-war "Free Philippine Republic" instead of changing to the "Republic of the Philippines" or "Philippines".

This issue is also affected UPH which stays the name "Free Philippine Republic" instead of "Republic of the Philippines" or "Philippines" after Free Philippine Republic wins the Philippine conflict.

### Steps to reproduce / Cause of the issue

1. Balintawak Blintz triggers.
2. FRP takes Manila and the SPR dissolves.
3. End of alliance between communists and FRP.
4. 4th Japanese Army invade the Philippines to retake the Islands.
5. The Communists win the Philippine three-way war.
6. Marcos coup the communist government.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235556922-f00c0e4b-0f35-4a83-9d39-7894096c226b.png)

### Additional information

I have no other info about this issue.

**Comment by runelead00** [comment]
Fixed in Dev Build
