### ISSUE TITLE
ENG - Add world news event about the Battle for England

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1814]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest adding the world news event about the Battle for England and the image should be the Palace of Westminster and its surroundings.
 

### Justifications

Well, just like the Battle for Italy has the world news event. So, the Battle for England should have. 

### Screenshots

Not needed.

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Not adding content to old england in any way
