### ISSUE TITLE
Haiti - Despite capitulation, Haitian Civil War never stops

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1815]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Uploading error.log…]()
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11369093/game.log)

### Describe the bug

The Haitian Civil War essentially never ends. Despite the revolutionaries capitulating the central government, they are still shown to be at war with them.

### Steps to reproduce / Cause of the issue

1. Have revolutionaries defeat central government in Haitian Civil War.
2. Observe issue.

### Expected behaviour

Revolutionaries would be at peace.

### Screenshots

![image](https://user-images.githubusercontent.com/98370487/235562228-0a36ce7e-64c3-4d16-a59b-33c3140b4e61.png)
![image](https://user-images.githubusercontent.com/98370487/235562274-204e0708-f6ce-4433-a4d5-e511c3aa876a.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
