### ISSUE TITLE
GER - Suddenly crash to desktop after FMA capitulation to PALF during WAC scenario 3 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1816]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11370046/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11370047/game.zip)
[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11370054/GER_play.zip)

### Describe the crash

Play as Germany and I see Fuuta Fulbe has 100% capitulation during the West African War. During the peace effect, the game suddenly crashes. 

### Steps to reproduce / Cause of the crash

1. Scenario 3 West African War triggers.
2. Free France capitulated, FMA is losing ground.
3. Fuuta Fulbe capitulated. 
4. Peace effect triggers.

### Screenshots

Not needed.

### Additional information

I have no other info.

**Comment by MadTaco** [comment]
I have this same problem playing as Japan. The attached save has Fuuta Fulbe capitulate a day or two after loading, and the crash takes place when the "Peace Conference" text appears.
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11416302/error.zip)
[game.zip](h
[Save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11416311/Save.zip)
ttps://github.com/TNODevs/TNO-Bug-Tracker/files/11416303/game.zip)

**Comment by runelead00** [comment]
Fixed in Dev Build
