### ISSUE TITLE
GER - Unternehmen Wurgegriff operation decision appeared despite Villasboa is not in charge of Paraguay

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1817]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11370366/GER_play.zip)

### Describe the bug

When the Paraguay situation critical and Morínigo is deposed by conservative Colorados, the Unternehmen Wurgegriff operation decision is somewhat appeared despite Villasboa is not in charge of Paraguay. 

### Steps to reproduce / Cause of the issue

1. German Civil War triggers.
2. Morínigo is overthrown. 
3. Federico Chaves takes power in Paraguay.
4. FULNA attacks the government.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235597733-e34733e1-6b0e-450e-b5fd-146392d228a1.png)
![Image_02](https://user-images.githubusercontent.com/131833099/235597741-5d4b1cd0-fa5d-4b88-abf5-5e9b7d79c1e6.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
