### ISSUE TITLE
USA - Focus "USA_wfb_64_on_radio" doesn't show its effects

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#1821]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

![3](https://user-images.githubusercontent.com/65211266/235656749-7cf9eeb5-bfa9-4ccb-a44b-a8242c5210ce.png)
Add custom_effect_tooltip = USA_urban_rep_shift here, the same goes to other shifts

### Steps to reproduce / Cause of the issue

Play as WFB

### Expected behaviour

Focus "USA_wfb_64_on_radio" should show its effects

**Comment by runelead00** [comment]
Fixed in Dev Build
