### ISSUE TITLE
GER - Operation Armbanduhr in Caribbean America region is appeared despite has murder of Maurice cold war achievement 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1822]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_operation_decision.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11372908/GER_operation_decision.zip)

### Describe the bug

After the success of murdering Emil Maurice in Africa through Operation Armbanduhr decision, the same decision appeared in Caribbean America region in agency decisions despite Germany having the "Murder of Emil Maurice" cold war achievement. 

### Steps to reproduce / Cause of the issue

1. Emil Maurice has escaped.
2. Germany sent an agent to eliminate him in Africa.
3. Success eliminates Maurice.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235663081-db66730b-1241-49e1-b8cd-0c5346a49795.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235663090-4a97f768-bdaf-48e2-a3db-d221f7e5894e.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
