### ISSUE TITLE
USA - Esponige is locked after starting Operation Thermidor

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#1823]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

![4](https://user-images.githubusercontent.com/65211266/235672042-108cf42f-9463-42b1-ac62-0b44fb22f870.PNG)
This line of code is needed or esponige will be locked after starting Operation Thermidor.

### Steps to reproduce / Cause of the issue

Take the decision "Operation Thermidor"

### Expected behaviour

Esponige won't be locked after starting Operation Thermidor.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
