### ISSUE TITLE
USA - Achievement "Oh! Darling" cannot be unlocked

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#1824]
### Operating System

Windows 10

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Ditto. Get rid of this "always=no" please.
![5](https://user-images.githubusercontent.com/65211266/235673064-8a0dc5a0-821e-4b0e-93ef-00d77c8df0e0.PNG)

### Steps to reproduce / Cause of the issue

mhm.

### Expected behaviour

Achievement "Oh! Darling" can be unlocked.

**Comment by runelead00** [comment]
Fixed in Dev Build
