### ISSUE TITLE
ZAR - Zarmaland is still exists despite being capitulated by PALF

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1825]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11373326/GER_game.zip)

### Describe the bug

After Zarmaland was defeated and capitulated by PALF, Zarmaland still exists and PALF is not able to create socialist Niger. 

### Steps to reproduce / Cause of the issue

1. PALF wins the West Africa War against the FMA.
2. PALF attacks Zarmaland.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235673184-505418b2-bd79-4a56-944e-87019c805ed6.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235673191-e6004232-2d07-4b86-a2c5-1f6e8b49f8d4.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Should be fixed in Dev Build
