### ISSUE TITLE
IRE/ULS - They haven't got the 'Member of the Zollverein' idea after they rejoin the Pakt when the Brigadiers coup

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1827]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11374049/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11374050/game.zip)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11374130/autosave.zip)

### Describe the bug

After the Brigadiers coup in Ireland and rejoining the Pakt under Speer's Germany due to Ireland was leave the Pakt before, Ireland and Ulster haven't received the 'Member of the Zollverein' national spirit. 

### Steps to reproduce / Cause of the issue

1. Speer wins the German Civil War.
2. Ireland and Ulster join the Pakt.
3. Ireland leave the Pakt due to a crisis.
4. Brigadiers coup the government and Ulster become with Ireland again and then they rejoin the Pakt.

### Expected behaviour

Forgot to add them, probably if Speer is charge of Germany.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235693183-892258ae-7426-4e1d-8222-58e41c4b1566.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235693195-e175f379-e3f4-47e8-85fb-5c009a13b24c.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Takes 3 months for integration into the Zollv
