### ISSUE TITLE
USA - Arizona Graphic shows Arkansas for senate and electoral map

### ISSUE THREAD

**Issue by Zlepp** [TNODevs/TNO-Bug-Tracker#1828]
### Operating System

Windows 11

### HOI4 version

1.12.12.456f

### TNO version

1.4.1c

### Do you have other mods in use?

fps map

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

In the electoral map when you click on arizona , it shows arkansas

### Steps to reproduce / Cause of the issue

1. Play USA
2. Go to electoral tab
3. click on arizona and arkansas will appear

### Expected behaviour

i expected to see arizona

### Screenshots

![Screenshot (31)](https://user-images.githubusercontent.com/121841187/235736343-bcb2f871-529c-4055-82ba-e84e725f662e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
