### ISSUE TITLE
GER - 'Looming Failure' decision time still appears and disappears despite having SAW withdrawal decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1829]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11378208/GER_game.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11378216/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11378217/game.zip)

### Describe the bug

After doing the SAW withdrawal decisions due to higher war protest without selecting the withdrawal decision, the 'Looming Failure' decision time still appears and disappears.

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. Either Speer or Bormann wins the German Civil War.
3. Germany supports the Afrika-Schild.
4. Has higher war protest and force to withdraw without taking withdrawal decision.
5. 'Looming Failure' decision time still appears and disappears, and so on and so forth.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/235803195-4581eb1e-b339-44c5-b2ba-e834b6315b5c.png)
![Image_2](https://user-images.githubusercontent.com/131833099/235803201-b9a9798a-53d9-4b7d-9204-6bac00679099.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
