### ISSUE TITLE
HMMLR - "Lose game screen" and pre-war Loyalist focus tree after winning civil war

### ISSUE THREAD

**Issue by dv15** [TNODevs/TNO-Bug-Tracker#183]
- Operating System: Win11
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: TNO Nuclear War gamerule (gamerule not enabled, so theoretically nothing changed), Radio TNO, TNO reskins
- Were you using Steam: Yes
- Which expansions do you NOT have: None, I have all

I played as HMMLR and won the civil war in a week or so due to the Loyalists only having London at war start. After I won, I got the "game over" screen you get when you capitulate, and then after a few (paused) seconds it went away, my color changed to a darker red, and my focus tree became the prewar loyalist focus tree, with the first two focuses and then the first one on the right (the "without Germany we are nothing" one) already taken.

To reproduce:

1. Play as England

2. Select all focuses that put you on the HMMLR path

3. Win civil war

Screenshots:

<img width="960" alt="english_civil_war_bug" src="https://user-images.githubusercontent.com/33880784/142762550-85ad46f3-aaae-44c0-ba09-fa5964819ea0.png">

**Comment by JberkofRivia** [comment]
Can confirm, got the same bug.
![20211204011714_1](https://user-images.githubusercontent.com/95519142/144699977-4def284b-6021-43ed-9f4b-3d8b9617b309.jpg)

**Comment by runelead00** [comment]
The load screen we can't fix due to how tag switching works, winning ECW now loads blank focus tree before the event to load reconstruction appears
