### ISSUE TITLE
All tags - Not localized yet for APC module slot

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1831]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

`APC_designation_slot` and `APC_armament_slot` are not localized yet.

### Steps to reproduce / Cause of the issue

1. Play as any feature tags.
2. Create a variant for APC.
3. See loc for designation and armament.

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235829571-bd003b73-3954-4b61-8934-35ce1e8e67d6.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
