### ISSUE TITLE
CLD - 'German Advisors' has no GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1834]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_CW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11379476/GER_CW.zip)

### Describe the GFX issue

When Germany selects the 'Send Advisors' decision and SPA has the national spirit, 'German Advisors' has no GFX icon.

### Steps to reproduce / Cause of the issue

1. Border war in Colombia.
2. The second Patriotic Army appears.
3. Colombian Civil War resumes.
4. Germany sends advisors to SPA.

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/235837942-b57d0a3f-cee0-4b98-bd68-cbdbf2ab62e2.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
