### ISSUE TITLE
All tags - There is an overlap "Nuclear Reactor" name with the selectable engine module

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1838]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### List the loc issues below

1. All ships' variants have an overlap "Nuclear Reactor" name in the ship's engine module. 
![Image_1](https://user-images.githubusercontent.com/131833099/235904919-7bd60e4d-e504-4c05-84a6-5f999249a40d.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
