### ISSUE TITLE
USA - SAW spirit missing loc

### ISSUE THREAD

**Issue by YaBoiRox** [TNODevs/TNO-Bug-Tracker#184]
**Questions**

- Operating System:
- HOI4 Version: Last before NSB
- TNO Version: TT
- Any other mods in use: No
- Were you using Steam? : Yes
- Which expansions do you NOT have? : La resistance not active

**Longer Description of Issue:** SAW Bombing spirit missing loc

**Steps to Reproduce/Cause Issue:**

1. Hover over the decision or the spirit panel

2.

etc...

**Screenshots:**

![image](https://user-images.githubusercontent.com/78772243/142762584-1501622b-00eb-4179-9782-d9eb16ec16e8.png)

**Comment by Stormeagle449** [comment]
Fixed for UB.
