### ISSUE TITLE
USA/HAI - Haitian Proxy War Instantly Ends

### ISSUE THREAD

**Issue by DinoTsar** [TNODevs/TNO-Bug-Tracker#1847]
### Operating System

Windows 11

### HOI4 version

1.12.9

### TNO version

1.4

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Haitian Proxy Conflict for the USA ends BEFORE the Proxy Conflict even starts

### Steps to reproduce / Cause of the issue

1. Play as the USA
2. Play the game normally
3. A week before the Haitian Proxy War starts the Insurgency should be crushed and the Ugly American Success Event occurs.
4. A week later the Haitian Proxy War starts.

### Expected behaviour

The Haitian Proxy War shouldn't end BEFORE it began

### Screenshots

![image](https://user-images.githubusercontent.com/73443055/236084335-d04add48-8ade-4250-aa55-67d1fd46217d.png)

### Additional information

Sometimes the Proxy War works normally, but most of the time it doesn't work properly.

Also, Github will not allow me to send over my save that causes this issue because it is too large (instead of being 25 mb it is 34 mb) as a Zip so if you need my autosave be sure to DM me at TheDinoTsar#9571

**Comment by runelead00** [comment]
Should be fixed in Dev Build
