### ISSUE TITLE
GER - Double gaining negative stability by 10% in the 'Conference of Global Security and Co-Operation' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1848]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11392609/GER_play.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11392610/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11392611/game.zip)

### Describe the bug

There is a double 'Gain Base Stability: -10.00%' in the first option from the 'Conference of Global Security and Co-Operation' event. I don't know what are these for. 

### Steps to reproduce / Cause of the issue

1. Speer choose to thaw relations with the Americans during GER's phase 1 focus tree.
2. Choosing a reformist side from the GER's America foreign focus tree.
3. The Americans say yes to the conference with the Germans.

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236104594-3dc97eb6-e6c3-446e-ada1-631c261eac42.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
