### ISSUE TITLE
GER - Zukunftsmusik and other focuses are available despite 'Siemens' and other companies are waning, not vulnerable

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1849]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11392712/GER_play.zip)

### Describe the bug

When 'Siemens' influence is waning, the Zukunftsmusik focus is somehow available despite this focus requirement tells 'Siemens company must be vulnerable'.

This issue also includes; 'Fuhrererlass', Past is Past', and 'Buyout' national focuses that their requirements are needed their companies' influence are vulnerable. But when one of the four powerful companies' influence is waning, not vulnerable, the national focus is somehow unlocked.

### Steps to reproduce / Cause of the issue

1. Play as Speer's Germany.
2. Actions against the corporations are activated.
3. One of the powerful companies begins the fade. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236107941-cd3f1f11-2486-4c33-a8f4-54646ee25e3d.png)
![Image_02](https://user-images.githubusercontent.com/131833099/236107948-5903a7a7-e6f7-4fbf-93d6-65bcb8fbe027.png)
![Image_03](https://user-images.githubusercontent.com/131833099/236109780-393efef4-69a0-404f-9616-bf28f5458194.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
