### ISSUE TITLE
GER - Unable to dismantle the company power when the power is 0% except reload the save game and the bar cannot go empty

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1850]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11392906/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11392908/game.zip)
[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11392970/GER_play.zip)

### Describe the bug

When the company's power reaches 0% after taking action, the 'Dismantle' button is locked and the bar cannot go empty. 

However, when reloading the save game, the 'Dismantle' button is unlocked except for the bar that is still not empty.

### Steps to reproduce / Cause of the issue

1. Play as Speer's Germany.
2. Proceed to Phase 2.
3. Take action against four powerful companies in Econ GUI.
4. One of the big four has zero percent power.
5. Dismantle still locks.
6. Reload the save game.
7. Dismantle unlock.
8. Company's power bar cannot go empty.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236113367-88c7a3f3-6df8-4e70-991d-88313a42e813.png)
![Image_02](https://user-images.githubusercontent.com/131833099/236113372-a1a20587-68d4-453c-8e6c-35687deca70c.png)
![Image_03](https://user-images.githubusercontent.com/131833099/236113929-7f52fe08-443b-405e-8741-798b4e2f918f.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Read the 2nd half of the tooltip, in the save you sent you hadn't completed that focus
