### ISSUE TITLE
HAI - Long world news event description about the Communist PPLN victory in Haitian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1852]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11393148/GER_play.zip)

### List the loc issues below

![Image_01](https://user-images.githubusercontent.com/131833099/236119182-be184828-1488-4be2-9096-b7026ae25842.png)

### Additional information

I don't know what causes this.

**Comment by runelead00** [comment]
Fixed in Dev BUild
