### ISSUE TITLE
USA-Pie Chart doesn't change 

### ISSUE THREAD

**Issue by Dillyhere** [TNODevs/TNO-Bug-Tracker#186]
**Questions**

- Operating System:
- HOI4 Version: 1.10.5 Collie
- TNO Version: Toolbox Theory
- Any other mods in use: Custom Paths, Toolpack, Hybrid map, State Transfer
- Were you using Steam? yes
- Which expansions do you NOT have? i don't have all of them except the basic packs

**Longer Description of Issue:**
USA's pie chart doesn't change even though several events indicates an increase of socdem popularity but even with closing and opening it again is still the same

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/94790120/142764289-c8f7cc03-261b-43f8-b8b0-4ceda9548369.png)

**Comment by Scarsoftime** [comment]
Custom country paths submod is causing the issue, this is out of our hands.
