### ISSUE TITLE
ITA - Some national spirits have the same GFX icon as 'Declining Trade' idea icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1860]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11404381/GER_play.zip)

### Describe the GFX issue

When I look at Italy's national spirits, I saw some national spirits have the same GFX icon as the 'Declining Trade' national spirit GFX icon and no unique different GFX icons related to the national spirit's title. 

### Steps to reproduce / Cause of the issue

1. Galeazzo Ciano secures his position.
2. Italy becomes a democracy.
3. Taking the national focuses

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236409329-0b0992e0-58fd-4fa3-8dfe-163c70882e74.png)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed for 1.5.0
