### ISSUE TITLE
GER/BRG - AI Burgundy can't highly collapse in Jan 1970 after successful operations against Burgundian elements in Europe and North America

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1862]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11406520/GER.zip)

### Describe the bug

Despite successful operations against Burgundy elements in Europe and North America through the agency and the increased chance of AI Burgundy collapse, AI Burgundy is not highly collapse in Jan 1970, and even after many reloading the save game BRG doesn't collapse. 

### Steps to reproduce / Cause of the issue

1. Not using the custom country paths for Burgundy.
2. Play as Speer's Germany.
3. Select agency operations against Burgundy elements in Europe and North America.
4. The operation against Burgundy was successful.
5. Reach Jan. 1, 1970.

### Expected behaviour

I don't know what causes this.

### Screenshots

Not needed.

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Even with all missions, it's not certain Burgundy will collapse, just makes it more likely. Also RNG is set on game start, reloading changes nothing
