### ISSUE TITLE
CAO/PALF - 'Transitioning Guerrilla Tactics' and other Japanese support national spirits do not remove after WAC ended

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1863]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11411421/GER_play.zip)

### Describe the bug

After the PALF victory against FMA due to Japanese support, some of the Japanese support national spirits do not remove. 

### Steps to reproduce / Cause of the issue

1. The West Africa War triggers.
2. No blockade on the Gulf of Guinea.
3. PALF victory. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236602095-a88139fc-9f26-45db-af9c-adf3e5dd5ac1.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236602099-90a674bb-a427-44a9-ae1d-6fada93cca51.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
