### ISSUE TITLE
GER - 'Technical Support for the Ba'aths' and 'Authorize Luftwaffe Operations' do not include other factions before they pop out

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1864]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_oil_crisis.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11411661/GER_oil_crisis.zip)

### Describe the bug

During the Yemeni Civil War, I select the 'Technical Support for the Ba'aths' decision targeted only pan-Arab Yemen but when there are another pan-Arab rebels, this includes them too, But, after 'Technical Support for the Ba'aths' decision, and Pan-Arab Egypt and Sudan pop out, Pan-Arab Egypt and Sudan have not received 'German Industrial Support' idea due to the decision only targets when there is exists. 

This issue includes the 'Authorize Luftwaffe Operations' decision that Muslim Brotherhood has no 'German Bombing Runs' idea due to late pops out.

So, 'Technical Support for the Ba'aths' and 'Authorize Luftwaffe Operations' decisions should include targeting them before they pop out. 

### Steps to reproduce / Cause of the issue

1. Play as Speer or Bormann's Germany.
2. Crisis in the Middle East.
3. The Oil Crisis triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236608712-ba74fd49-276a-4085-8dfe-0d6cbd808ab5.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236608717-db8c1128-3351-4570-99b8-9378ce3deaa7.png)
![Image_3](https://user-images.githubusercontent.com/131833099/236608718-6e1a2589-3581-4c13-9db2-601fab4f7834.png)
![Image_4](https://user-images.githubusercontent.com/131833099/236608719-7a896702-6eae-4224-8c71-94eaa44d8169.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Germany is not sending industrial support to factions that do not yet exist
