### ISSUE TITLE
GER/USA/JAP - Not updated the GFX map of 'The Middle East in Flames' global conflict

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1865]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11412153/GER_play.zip)

### Describe the GFX issue

The GFX map of 'The Middle East in Flames' global conflict is not updated because the rebels' positions during the conflict changing in Egypt and Iraq, and uses the old version of 'The Middle East in Flames' GFX map

### Steps to reproduce / Cause of the issue

1. Crisis in the Middle East.
2. The Oil Crisis triggers.
3. See the GFX map of 'The Middle East in Flames' proxy war in global conflict.

### Expected behaviour

Forgot to update them, maybe.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236619962-1845bd74-00fe-4db2-b76c-8ba68823f6e3.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236619964-dceb9587-b67c-4f99-826b-1c2d7528fe98.png)
![Image_3](https://user-images.githubusercontent.com/131833099/236619966-17cfabd8-4ecd-43c0-86e0-29369f739933.png)
![Image_4](https://user-images.githubusercontent.com/131833099/236619968-78fd4c9d-371f-4dee-984f-e1020fd4de46.png)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
