### ISSUE TITLE
Oman/Egypt/Iraq/Kurdistan/Sudan - Add some grid powers

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1867]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest adding some grid powers in Oman, Egypt, Sudan, and Iraq. And also their factions' position states because of their civil wars during the Oil Crisis.

### Justifications

Iraq has 0 power grids while others have some power grids. However, during the Middle Eastern civil wars, some of the civil war factions have 0 power grids due to their spawning states' position. Because, if the civil war factions have industrial support national spirits that gain construction speed and factory output, their national spirits are kinda useless.  

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236626544-ae63f3be-22c2-4cff-bd4c-8693e856712c.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236627387-7d6f92a2-65ce-4b2b-815f-289f8fd0f88b.png)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
