### ISSUE TITLE
UTL/TAJ - Add some grid powers on them

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1868]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest adding some grid power to Turkistan Legion and Tajikistan.  

### Justifications

While Turkmenistan, Kyrgyzstan, and Uzbekistan have the power grids, Turkistan Legion and Tajikistan do not. 

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236628018-4e087aad-6e73-42f4-9757-71b87f95b48a.png)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
