### ISSUE TITLE
USA/JAP - The Mano Campaign global conflict has no GFX map

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1869]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[USA_global_conflict.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413807/USA_global_conflict.zip)

### Describe the GFX issue

When the Mano Campaign starts, the Mano Campaign in global conflict for USA and Japan has no GFX map of West Africa. 

### Steps to reproduce / Cause of the issue

1. PALF wins the West Africa War.
2. Oil Crisis triggers.
3. PALF invades Liberia and Mendi.

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236655530-d3fa683e-c07b-4bbf-8b0d-825eaef69de1.png)
![Image_02](https://user-images.githubusercontent.com/131833099/236655533-ae25a3f4-f1dd-48e6-8f1b-dac1642dbeb3.png)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
