### ISSUE TITLE
GER/MAD - German national spirits still exist after the communist AREMA seize control of Madagaskar during the Oil Crisis

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1871]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413894/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413896/game.zip)
[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413906/GER_play.zip)

### Describe the bug

When the resurgent rebels (AREMA) successfully seize control of Madagascar from the Germans, communist Madagascar still has the German national spirits and doesn't remove them. 

### Steps to reproduce / Cause of the issue

1. Militärverwaltung Madagaskar wins the Second Malagasy Rebellion.
2. German Madagaskar rejoins the Pakt.
3. Oil Crisis triggers.
4. Madagaskar situation critical.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236657423-874b2f4d-6ca8-45e0-909f-beeae788f294.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236657424-d3898ab1-1186-4bac-8f8e-385334283a0d.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
