### ISSUE TITLE
GER - 'Welcome Heroes From Madagaskar' decision is appear despite the native rebels remove the German from Madagascar during the Oil Crisis

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1872]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413931/GER_play.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413932/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413933/game.zip)

### Describe the bug

After the leftist native rebels succesful overthrowing the Germans from the Madagascar during the Oil Crisis, 'Welcome Heroes From Madagaskar' decision is somehow appear. When I click it, 'Democratic Republic of Madagascar' rejoins the Pakt and Milch is in charge again. 

### Steps to reproduce / Cause of the issue

1. Militärverwaltung Madagaskar wins the Second Malagasy Rebellion.
2. German Madagaskar rejoins the Pakt.
3. The Oil Crisis triggers.
4. Madagaskar situation critical.
5. Resurgent rebels (AREMA) successful remove the Germans from the Madagaskar.
6. 'Welcome Heroes From Madagaskar' decision appear. 
7. Select the decision.
8. AREMA change their mind and they join the Pakt again.
9. Milch becomes in charge of 'Democratic Republic of Madagascar' and allow its communist flag to stay. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236657857-8712c299-6f4f-43fa-9bf7-3b60be30637b.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236657859-d114f114-9521-455f-bd7e-c8d062f4d66d.png)
![Image_3](https://user-images.githubusercontent.com/131833099/236657860-f04f751b-5abd-46e1-a229-29c688fe0242.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
