### ISSUE TITLE
USA - AI USA doesn't select any of the agency researches and operations

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1873]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When reaches 1970s and switches to USA tag to see, it seems AI USA doesn't select any of the agency researches and operations.

### Steps to reproduce / Cause of the issue

1. Play as any feature tags except USA.
2. Reach 1970.
3. Switch to USA tag through the console.
4. See the Intelligence decision tab. 

### Expected behaviour

I don't know what causes this.

### Screenshots

Not needed.

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Should be fixed in Dev Build
