### ISSUE TITLE
MDI/SUS(PALF) - Sierra Leone is occupied by Guinea that doesn't let them go despite the country exists after PALF defeats Mano River Pact

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1874]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413990/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413991/game.zip)
[USA_mano_campaign.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11413992/USA_mano_campaign.zip)

### Describe the bug

After PALF defeats the Mano River Pact during the Oil Crisis, Sierra Leone is occupied by Guinea despite Sierra Leone's existence.  

### Steps to reproduce / Cause of the issue

1. PALF wins the West Africa War.
2. The Oil Crisis triggers.
3. PALF invades Liberia and Mendi.
4. PALF defeats the Mano River Pact.

### Expected behaviour

I don't know exactly. Possibly due to bug of Zarmaland. 

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236659449-1ae79583-e691-45cb-9370-316342deb98d.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236659452-a0d42360-0fe2-4f7b-a5e3-d73e06ab1928.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
