### ISSUE TITLE
USA - Some issues for the Mano Campaign global conflict

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1875]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11414018/USA.zip)

### Describe the bug

The 'Increase Troops Allocation' decision effect gives sending **0** instead of **1** volunteers to Mendi and Liberia.

After selecting the 'Promote Scorched Earth' decision, there is an overlap to the left in the state modifier of Mendi and Liberi states. 

### Steps to reproduce / Cause of the issue

1. PALF wins the West Africa War.
2. The Oil Crisis triggers.
3. PALF invades Liberia and Mendi.
4. OFN supports the Mano River Pact.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236660214-60ba8dc4-b89f-4010-b1f5-18440be5856c.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236660217-fd44f520-e941-41cd-bfb4-2b46529d5c84.png)
![Image_3](https://user-images.githubusercontent.com/131833099/236660218-3d2fe8d1-731e-4e1e-97e9-8348d5bc082c.png)
![Image_4](https://user-images.githubusercontent.com/131833099/236660219-7b980623-b127-4e69-9822-0655c4da4675.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
