### ISSUE TITLE
Burgundy - Calgary Olympic news event fires a billion times

### ISSUE THREAD

**Issue by astickyheresy** [TNODevs/TNO-Bug-Tracker#188]
**Questions**

- Operating System:
- HOI4 Version: latest
- TNO Version: 1.2
- Any other mods in use: Radio TNO
- Were you using Steam? Y
- Which expansions do you NOT have?

**Longer Description of Issue:**

I'm not sure what happened exactly, but while playing Burgundy, with volunteers in the German Civil War, the Calgary Winter Olympics superevent fired about a hundred times, grinding everything down to a halt and requiring me to manually click through them. Perhaps it's firing once from every country in the game?

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by Scarsoftime** [comment]
Fixed.
