### ISSUE TITLE
YEM/NYM - 'Yemeni Civil War' national spirit still exist despite the civil war ended

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1885]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11417154/GER_play.zip)

### Describe the bug

After either the Monarchists or Socialists win the Yemeni Civil War, the 'Yemeni Civil War' national spirit still exists.

### Steps to reproduce / Cause of the issue

1. Yemeni Civil War triggers.
2. Conflicts in the Middle East.
3. Oil Crisis triggers.
4. Yemeni Civil War ended.

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236718967-76c701e6-8647-45d8-a3f7-8dbf6e919a6e.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
