### ISSUE TITLE
GER/USA - 'ICEPROX_exposed_cleared' has no loc

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1886]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_iceland.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11418263/GER_iceland.zip)

### Describe the bug

When I see the 'Opposition Campaign Investigates Leakers' decision effect, there is a lack of localization of 'ICEPROX_exposed_cleared'.

### Steps to reproduce / Cause of the issue

1. 1971 Iceland Election starts.
2. Leak the opposition base.
3. See 'Opposition Campaign Investigates Leakers' decision effect.

### Expected behaviour

Forgot to adding loc, probably.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236746420-ee2a91f4-e8df-4b68-bfb0-356dfc981eaf.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
