### ISSUE TITLE
GER/UTL - Turkestan Legion is not border war with Kyrgyzstan again after click again the 'Send the Legion after Ishkoshim' decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1887]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_turkes_kenes.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11418332/GER_turkes_kenes.zip)

### Describe the bug

After selecting again the 'Send the Legion after Ishkoshim' decision due to the Turkestan Legion fails the border war, Turkestan Legion is not doing the border war with Kyrgyzstan (Talas) again. 

I don't know if the 'Send the Legion after Tashkent' decision has the same issue as this one when selecting it again. 

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. The Reunification of Turkestan triggers.
3. Turkestan Legion has a border war with Talas (Kyrgyzstan) through GER's 'Send the Legion after Ishkoshim' decision.
4. Turkestan Legion fails to take Ishkoshim from Talas aftermath of the border war. 
5. Germany select again the 'Send the Legion after Ishkoshim' decision.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236748993-9c4ceb16-0778-4f4f-ab2f-5a6a12719ea6.png)
![Image_02](https://user-images.githubusercontent.com/131833099/236749007-0787d9c6-1d5d-4d28-b11a-8e8db097dd0c.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
