### ISSUE TITLE
GER - Command power doesn't go decrease after taking the 'Industrial Aid' decision during the IRC

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1888]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_iran_civil_war.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11425777/GER_iran_civil_war.zip)

### Describe the bug

After taking the 'Industrial Aid' decision during the Iranian Civil War, the command power doesn't decrease because this decision required command power.

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. The Oil Crisis triggers.
3. Shah of Iran was assassinated.
4. Iranian Civil War triggers. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236955814-1e52ec8f-2d59-4528-bd17-927661a1262d.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236955843-22d0e804-a9b2-476f-94bc-491076f435f0.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
