### ISSUE TITLE
GER/USA/JAP - The Iranian Civil War GFX map is not updated in global conflict despite the changes of Iran

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1889]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_iran_civil_war.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11425833/GER_iran_civil_war.zip)

### Describe the GFX issue

When the Iranian Civil War starts, the Iranian Civil War GFX map for Germany, USA and JAP is not yet updated due to Iran changes and uses the old version.

### Steps to reproduce / Cause of the issue

1. The Oil Crisis triggers.
2. The Shah of Iran was assassinated.
3. The Iranian Civil War triggers.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://user-images.githubusercontent.com/131833099/236958896-7b57ce1e-bb59-45b9-9f23-075192a435b6.png)
![Image_2](https://user-images.githubusercontent.com/131833099/236958900-084730bd-3ea8-4252-a756-67ce868580b8.png)
![Image_3](https://user-images.githubusercontent.com/131833099/236958904-1343bec2-6105-415f-a93c-329d27222fba.png)
![Image_4](https://user-images.githubusercontent.com/131833099/236958908-5be727b7-dfcb-461b-b7d1-71eb553e7a2a.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Not spending resources on new forpol icon until new Iranian setup releases
