### ISSUE TITLE
Middlesbrough misspelled literally unplayable

### ISSUE THREAD

**Issue by Dissatisfaction** [TNODevs/TNO-Bug-Tracker#189]
**Questions**

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**
![52CD2B4F-CC97-493F-A09C-C77AB489398D_4_5005_c](https://user-images.githubusercontent.com/83587467/142766972-e8db3f44-a1b9-4a85-b2a2-b8abab307076.jpeg)

apologies if I don't fill in all the other questions, but literally the only issue is that "Middelsbrough" should be spelt "Middlesbrough". Not that much of a biggie.

**Comment by Scarsoftime** [comment]
Fixed
