### ISSUE TITLE
GER - Pro-OFN wins the Iceland 1971 election despite the OFN reputation is bad and anti-OFN is higher

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1890]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11426154/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11426155/game.zip)
[GER_final_media_cycle.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11426166/GER_final_media_cycle.zip)
[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11427962/GER_game.zip)

### Describe the bug

Despite the Pro-OFN being very low and anti-OFN having a higher bar than pro-OFN, the outcome of the election is pro-OFN-Independent coalition wins. 

### Steps to reproduce / Cause of the issue

1. Oil Crisis triggers.
2. Iceland's situation deteriorates. 
3. Iceland's 1971 election triggers.
4. Doing negative leaks to Pro-OFN decision to decrease their reputation. 
5. Pro-OFN reputation is bad and anti-OFN is higher.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236965262-437b5db1-d09b-453a-89a1-0f6eb90ad8cc.png)
![Image_02](https://user-images.githubusercontent.com/131833099/237010071-0c05473b-93ee-4fa5-9a07-7b21d82ed40f.png)
![Image_02](https://user-images.githubusercontent.com/131833099/236965271-1f4042d3-872c-400b-b2a6-3aab5d7d9bd5.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
