### ISSUE TITLE
GER - 'Wehrmacht Over the Division Limit' event is triggered after making division more than 50 despite finishing all Speer's military reforms focus tree

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1891]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11426685/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11426686/game.zip)
[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11426687/GER_game.zip)

### Describe the bug

Despite finishing all military reform focus trees, the 'Wehrmacht Over the Division Limit' event is triggered somehow after making divisions of more than 50. 

### Steps to reproduce / Cause of the issue

1. Play as Speer's Germany.
2. Proceed to the phase 2 focus tree.
3. Deleting the rest of the divisions to limit 50. 
4. Complete all military reform focus trees.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236979429-f1e777aa-9c32-4f5d-844b-e12075154bcc.png)
![Image_02](https://user-images.githubusercontent.com/131833099/236979437-e3d472d8-9acc-49eb-bcb8-3530eeec6ab8.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Army division limit is a permanent, not just for during reform tree
