### ISSUE TITLE
GER - Faction members have no effect shown in 'Victory in Iran' event effect

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1892]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_Iran_civil_war_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11426992/GER_Iran_civil_war_ends.zip)

### Describe the bug

After the pro-German Monarchists win the ICW, in the 'Victory in Iran' event effect there are no effects for faction members. 

I don't know what is this for. 

### Steps to reproduce / Cause of the issue

1. Iranian Civil War starts.
2. Monarchists win the civil war.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_01](https://user-images.githubusercontent.com/131833099/236987755-234c9a00-e9db-44d8-b0da-a158a48cbcda.png)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
