### ISSUE TITLE
MAD - Didn't change to Paktkommission Madagaskar and Erhard Milch is not in charge after Speer won the German Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1893]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the German Garrisons won the Second Malagasy Uprising after Speer won the German Civil War a few weeks later, Militärverwaltung Madagaskar didn't change to Paktkommission Madagaskar and Erhard Milch is not in charge.

### Steps to reproduce / Cause of the issue

1. Start of the Second Malagasy Uprising.
2. Speer won the German Civil War.
3. The second Malagasy Uprising is still ongoing.
4. German Garrisons won the Second Malagasy Uprising.

### Expected behaviour

Forgot to remove them after the CW, maybe.

**Comment by runelead00** [comment]
Fixed in Dev Build
