### ISSUE TITLE
Ultravisionary komi - Game crashes after some random peace conference

### ISSUE THREAD

**Issue by soundbolt47** [TNODevs/TNO-Bug-Tracker#1894]
### Operating System

Windows 11

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11427385/error.log)
[metropolitan russia.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11427386/metropolitan.russia.zip)

### Describe the crash

At the end of December 7th, a peace conference occurs and the game crashes.

### Steps to reproduce / Cause of the crash

1. The game starts at the 6th of december, goes fine until the end of 7th December, when a peace conference occurs and crashes the game

### Screenshots

![Screenshot 2023-05-08 215343](https://user-images.githubusercontent.com/70601884/236997699-db077cd8-7c05-4a86-b88e-299edbce6b62.png)
This happens right before

**Comment by soundbolt47** [comment]
I also want to say the peace conference (which i believe happens in west africa) crashes the game no matter when it happens, even after replaying the game to January 18th, the game will still crash, so i think its just west africa crashing the game

**Comment by runelead00** [comment]
Fixed in Dev Build
