### ISSUE TITLE
ICE - There are still in-OFN faction related national spirits despite leaving OFN through 1971 election

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1895]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error1.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11436878/error1.zip)
[error2.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11436879/error2.zip)
[game1.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11436880/game1.zip)
[game2.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11436881/game2.zip)
[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11436885/GER_game.zip)

### Describe the bug

After the anti-OFN wins the 1971 Icelandic election due to German support and Iceland leaves the OFN, the national spirits (except the oil crisis) related to in faction with OFN are still there instead of removing or modifying them. 

### Steps to reproduce / Cause of the issue

1. Oil Crisis triggers.
2. Incident happens in Iceland.
3. 1971 election in Iceland triggers.
4. Total Anti-OFN wins the election.
5. Iceland leaves the OFN.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_01](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9bc8eeed-607d-4c25-a16a-80b8cfc772ba)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
