### ISSUE TITLE
FAR - The description of 'Greenland Home Rule' event says about Faroe Islands questioning their place in OFN but Faroe Islands is already leaves OFN

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1896]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11437687/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11437688/game.zip)
[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11437690/GER_play.zip)

### Describe the bug

When Greenland secures its home rule due to the impact of Iceland leaving the OFN, the description event of 'Greendland Secures Home Rule' says about Faroe Island is beginning to question their place in the OFN but Faroe Island already leaves the OFN before Greenland's home rule. 

### Steps to reproduce / Cause of the issue

1. Iceland leaves OFN.
2. Faroe Islands leave the OFN.
3. Greendland granted home rule. 

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_01](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f3c1056d-4d70-489d-90a3-f7fc506fdb17)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Slight edit made to loc, meant to serve both situations Faroes become an independent OFN member + out of the OFN
