### ISSUE TITLE
ANL - Long news event's description about 'Union of African Socialist States Joins PACMEA'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1898]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[GER_angola_joins_palf.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11437914/GER_angola_joins_palf.zip)

### List the loc issues below

1. There is a long description of the 'Union of African Socialist States Joins PACMEA' event.
![Image_01](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8b149265-7e5b-408b-b040-00b18af3e86f)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev BUild
