### ISSUE TITLE
IBR - Iberian War is triggered somehow despite the Iberia status is moderately stable

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1899]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11442680/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11442681/game.zip)
[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11442770/GER_play.zip)

### Describe the bug

Play as Germany. When Iberia collapsed happening and descent into war, I see Iberia's 'Status of the Union' is moderately stable.

The Iberian wars can be triggered if the status of the union collapsed or some extremely unstable. I don't know what is this happening. 

### Steps to reproduce / Cause of the issue

1. Iberia going legislative council.
2. Iberia is stable.
3. Terrorists attack in Iberia.
4. Status-quo economic policy.
5. Iberia sticks with the legislative council.
6. Uniao National is in power. 
7. Iberia became a civilian dictatorship.
8. The Iberian Wars triggered. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9ed119c3-da00-44ac-ade1-636a8e08a466)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Stability is not the only factor that determines the start of the Iberian Wars
