### ISSUE TITLE
Kingdom of England Sphere cumulative GDP not showing

### ISSUE THREAD

**Issue by Dissatisfaction** [TNODevs/TNO-Bug-Tracker#190]
**Questions**

- Operating System:
- HOI4 Version: Collie v.1.10.8 (O3e5) [the pre-NSB version]
- TNO Version: Toolbox Theory v1.2.0a
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? Any of them

**Longer Description of Issue:**
The "total sphere GDP" for the pre-GCW German economic sphere just shows 0.

**Steps to Reproduce/Cause Issue:**

1. n/a

2. n/a

etc...

**Screenshots:**
![82B53601-3954-4770-B9DC-03BF89F72998_4_5005_c](https://user-images.githubusercontent.com/83587467/142767456-90a986bb-da67-4ef7-8dc0-6a9c89c3e4ce.jpeg)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
