### ISSUE TITLE
USA - CTD on Aryan Brotherhood Victory in West Russia

### ISSUE THREAD

**Issue by bug-reporter-tno** [TNODevs/TNO-Bug-Tracker#1900]
### Operating System

Windows 10, build 19045.2251

### HOI4 version

Avalanche v1.12.12.456f

### TNO version

v1.4.1c "Ugly American"

### Do you have other mods in use?

More Voicelines for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Files

Save file and relevant logs:
https://drive.google.com/drive/folders/1rjCujJOdaIBD6vCxCcdvT-JHHymRBCDT?usp=share_link

### Describe the crash

I was playing an ironman game as the USA and, during the South African War, an AI-controlled Aryan Brotherhood defeated Vyatka, shortly after which the game crashed. On further loading of the save, the game consistently crashed to desktop immediately after the Aryan Brotherhood victory notification.

### Steps to reproduce / Cause of the crash

1. Load the attached save.
2. Let the game run until Aryan Brotherhood defeats Vyatka.
3. Game immediately crashes to desktop.

**Comment by runelead00** [comment]
Fuuta Fulbe Capitulation CTD, Fixed in Dev Build
