### ISSUE TITLE
IBR - 'A New Iberian Nationalism' national focus has no GFX icon when selecting it

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1902]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.12.12

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[IBR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11447809/IBR.zip)

### Describe the GFX issue

After clicking the 'A New Iberian Nationalism' national focus, the Iberia Union tag details show the 'A New Iberian Nationalism' national focus has no GFX icon while there is a national focus GFX icon in the focus tree.

### Steps to reproduce / Cause of the issue

1. Iberia going legislative council.
2. Terrorists attack in Iberia.
3. Status-quo economic policy.
4. Iberia sticks with the legislative council.
5. Uniao National is in power.

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_01](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/867070f0-3b96-4f62-9ab9-a28f09e86586)
![Image_02](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e305f7a4-3714-4a98-81b8-c7527a6bef99)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Shine fixed in Dev Build
