### ISSUE TITLE
USA/JAP - Add Mano Campaign in the cold war achievement if USA choose to supports Mendi and Liberia

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1904]
### HOI4 version

1.12.12

### TNO version

1.4.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest add the Mano Campaign in the cold war achievement for USA and JAP. 

### Justifications

Because if the superpowers nations have the global conflict, it should be adding in the cold war achievement once the proxy conflict ended. 

### Screenshots

Not needed.

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Added in Dev Build
