### ISSUE TITLE
Komi - Lenin Body decisions not updated to Serov ideology change

### ISSUE THREAD

**Issue by vivecism** [TNODevs/TNO-Bug-Tracker#1905]
### Operating System

windows 11

### HOI4 version

latest

### TNO version

latest

### Do you have other mods in use?

TNO toolpack and TNO cheat mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

ordosocialists got changed to fascism but the unique lenin body decisions for komi still need natsoc ruling party

### Steps to reproduce / Cause of the issue

1. play serov
2. get lenin body

### Expected behaviour

lenin body decision has an unique case where fascist (ordosoc) komi can preserve it

### Screenshots

![20230515130316_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/133650316/454d1714-63ba-425c-bec4-93816d7fcea5)

**Comment by runelead00** [comment]
Fixed in Dev Build
