### ISSUE TITLE
England (Collaborator, post GCW)- faction requirement issue

### ISSUE THREAD

**Issue by jetflare2256** [TNODevs/TNO-Bug-Tracker#1907]
### Operating System

windows 11

### HOI4 version

latest (1.12.13)

### TNO version

latest (v1.4.1c)

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I saw a requirement for foci only being allowed when not in a faction for most of the foci for England (collaborators), which is fine on its own but this does not seem normal. Also, because me as Germany influenced them into eihenspakt england is now softlocked without a cheat

### Steps to reproduce / Cause of the issue

Just win over England in the influence game as Germany

### Expected behaviour

To be able to complete any selected national focus without cheating 

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/130992867/2da68cc5-271b-445c-a293-58ddc441038f)

### Additional information

The focus for American advisors does not face this same problem so it probably isn't intentional

**Comment by runelead00** [comment]
Fixed in Dev Build
