### ISSUE TITLE
Ordensstaat Burgun missing focus text

### ISSUE THREAD

**Issue by ThePowerOfTheSun** [TNODevs/TNO-Bug-Tracker#1909]
### Operating System

Windows 10

### HOI4 version

1.12.13

### TNO version

1.4.1c "Ugly American"

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

2 focuses have debug text and debug description.

### Steps to reproduce / Cause of the issue

1. Do enough focuses until you start removing the collaborators.

### Expected behaviour

The 2 focuses not have a name or description.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/134122966/871ccb24-7876-40a7-a55c-5a8e50571364)

**Comment by runelead00** [comment]
Fixed in Dev Build
