### ISSUE TITLE
USA - Received an event from Tomsk which changed the ruling party and focus tree

### ISSUE THREAD

**Issue by Demoburg** [TNODevs/TNO-Bug-Tracker#191]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: 1.2.0
- Any other mods in use: Player-lead peace conferences
- Were you using Steam?: Yes
- Which expansions do you NOT have?: Battle for the Bosporous

**Longer Description of Issue:**
Received a Tomsk event as the USA on the 1st of May 1964, which caused the ruling party of the USA to change to Socialism and caused the focus tree to change to Tomsk's regional focus tree, despite the fact Tomsk had not yet united Central Siberia.

**Steps to Reproduce/Cause Issue:**

1. Play as the US until May 1st 1964

**Screenshots:**
![unknown](https://user-images.githubusercontent.com/76626433/142767788-bde1a25d-8fdf-4687-a411-98a9b6fb5b52.png)
![unknown](https://user-images.githubusercontent.com/76626433/142767797-4c3e84f5-3ba8-43d0-8fe1-3f6bd7b183f8.png)
![unknown](https://user-images.githubusercontent.com/76626433/142767855-b1883005-e46b-4b6a-aca1-f8a27154516b.png)

**Comment by Demoburg** [comment]
I'm also now receiving events as if I were Tomsk:
![unknown](https://user-images.githubusercontent.com/76626433/142768006-d8e43a0c-af1c-469d-86f4-c7345613aaa3.png)

**Comment by runelead00** [comment]
Issue caused by hotfix around the time of report
