### ISSUE TITLE
Ordensstaat Burgun - Grammar Mistake in the "Breach..." event

### ISSUE THREAD

**Issue by ThePowerOfTheSun** [TNODevs/TNO-Bug-Tracker#1910]
### HOI4 version

1.12.13

### TNO version

1.4.1c "Ugly American"

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/134122966/062df737-cd76-4bac-889c-e9d343155577)

### Additional information

Its supposed to be cyanide pill and not cyanide bill.

**Comment by runelead00** [comment]
Fixed in Dev Build
