### ISSUE TITLE
Soviet Komi(suslov 's way) Factories do not produce products

### ISSUE THREAD

**Issue by Psix0L0g** [TNODevs/TNO-Bug-Tracker#1912]
### Operating System

Windows 10

### HOI4 version

1.12.11

### TNO version

v1.4.1c

### Do you have other mods in use?

yes, Brave new world

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[KOM_1965_11_22_01_save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11537282/KOM_1965_11_22_01_save.zip)

### Describe the bug

After the unification of the western part of Russia (+ Murmansk), the efficiency of production factory drops to 0.000%. There's nothing wrong with the economy.

### Steps to reproduce / Cause of the issue

1. Suslov unites Western Russia
2. Returns Murmansk
3. Literally before the race for the Urals (possibly during it), factories stop production

### Expected behaviour

Bug solution (resumption of production efficiency) and what was the reason for the bug

### Screenshots

![изображение](https://github.com/TNODevs/TNO-Bug-Tracker/assets/134336318/3c7c90e1-c368-4bb1-93c1-c2353632a7d3)
![изображение](https://github.com/TNODevs/TNO-Bug-Tracker/assets/134336318/89e4c821-66ff-49ae-9c73-a9560fc39c1c)

**Comment by Stormeagle449** [comment]
Submod interaction issue, closing this issue.
