### ISSUE TITLE
Crash after FMA vs PALF victory

### ISSUE THREAD

**Issue by Tallman310** [TNODevs/TNO-Bug-Tracker#1913]
### Operating System

Windows 11 x64

### HOI4 version

1.12.13

### TNO version

1.4.1c

### Do you have other mods in use?

Radio TNO, TNO: CIA, New German Voices, BNW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11548702/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11548703/game.log)

### Describe the crash

The peace deal in the PALF vs FMA WAW scenario crashes the game. This occurs regardless in and outside of the BNW submod.

### Steps to reproduce / Cause of the crash

1. Go to Custom Country Paths
2. Enable FMA vs PALF and Guarantee FMA victory
3. The crash usually occurs in mid-1964.

**Comment by runelead00** [comment]
Fixed in Dev Build
