### ISSUE TITLE
Crash the game after a peace deal notification appear

### ISSUE THREAD

**Issue by hunter1523** [TNODevs/TNO-Bug-Tracker#1914]
### Operating System

Windows 10 steam

### HOI4 version

Avalanche v1.12.14.50e7 (5555)

### TNO version

TNO v1.4.1c

### Do you have other mods in use?

"State Transfer Tool" and the mod "Strategic View Adjustments"

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585704/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585705/executed_commands.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585706/game.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585707/graphics.log)
[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585708/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585709/message.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585710/posted_commands.log)
[random.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585711/random.log)
[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585712/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585713/sent_commands.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585714/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585715/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585716/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585717/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585718/time.log)
[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585719/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585720/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585721/code_revisions.log)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11585726/autosave.zip)

### Describe the crash

after a while a peace deal appear causing the game crash

### Steps to reproduce / Cause of the crash

just play normal until the peace deal message appears

**Comment by runelead00** [comment]
Fixed in Dev Build, try annexing Fuuta Fulbe into a different West African tag to prevent the crash
