### ISSUE TITLE
MLY- Division Spawns Off The Coast Of Italy

### ISSUE THREAD

**Issue by ChasePE** [TNODevs/TNO-Bug-Tracker#1915]
### Operating System

Windows 11 

### HOI4 version

"Avalanche" v1.12.14.50e7 (1751) (S)

### TNO version

v1.4.1c - Ugly American

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Upon starting the game as UMAJF, the "3rd MPAJA Independent Regiment" will spawn in the central Mediterranean sea instead of a location you could reasonably expect a division to spawn at. 

### Steps to reproduce / Cause of the issue

1. launch the game as the "UMAJF" 
2. Pan to the central Mediterranean sea 

### Expected behaviour

the division not to be there 

### Screenshots

![Screenshot (98)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/135076243/b226de41-0b0a-4646-8593-02e6fa72e70f)

**Comment by runelead00** [comment]
Fixed in Dev Build
