### ISSUE TITLE
Amur - Crashes after unrelated peace deal

### ISSUE THREAD

**Issue by kairosjct** [TNODevs/TNO-Bug-Tracker#1916]
### Operating System

macOS monterey

### HOI4 version

1.12.14.50e7

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11641900/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11641901/error.log)
[AMR_bruh3.hoi4.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11641902/AMR_bruh3.hoi4.zip)

### Describe the crash

Was just playing Amur normally, fighting the Divine Mandate and not doing anything else. The game suddenly crashes because of an unknown and most likely unrelated peace deal. Repeated the save several times and it always happens. Apologies in advance if this is repetitive to some other report - I have no way to see what actually broke the game. 

### Steps to reproduce / Cause of the crash

Continue playing the attached save, and the crash will happen by itself soon (around 2 weeks in game). 

### Additional information

thanks for making tno, such a good mod, love it

**Comment by runelead00** [comment]
Fixed in Dev Build, Fuuta Fulbe capitulation bug, annex Fuuta Fulbe into a different country to fix the issue
