### ISSUE TITLE
USA - No loc for 'USA_voting_state_florida' in voting states GUI 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1917]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When selecting Florida state in USA's voting GUI, there is no localization for the "Florida" state name.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Either a senate or presidential election occurs.
3. Select the voting GUI.
4. Select Florida state. 

### Expected behaviour

Forgot to adding loc, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/95277540-e46b-4a98-bad6-6abb5c36e689)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
