### ISSUE TITLE
USA - Few graphic issues in Voting GUI

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1918]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the GFX issue

Some graphic map states in Voting GUI when selecting any states have slight graphic issues on the bottom left. I have no explanation for this but I saw there is a small issue.

The Alaska state map in Voting GUI shows the US doesn't own the islands near Alaska except for Atsuta-to but in the game, USA does own the islands near Alaska which are now part of Alaska state. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Either a senate or presidential election occurs.
3. Select the voting GUI.
4. See the graphic state map.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f310a837-56fc-42d7-bdaf-a1bb4abd3295)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/cfc13afd-1c7f-4e8e-8f89-cab0bb0ab2d3)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0cda1722-fdc2-4e1c-8232-4ae3fcb125fa)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/686917c0-f1b9-495e-afe6-2ae30b5ac4fe)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
