### ISSUE TITLE
All tags - Division effects in Division Template's Division Designer have overlap with scroll bar

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1919]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When selecting division edit through the division template and seeing the division effect status, there is an overlap between the effect and the scroll bar. 

### Steps to reproduce / Cause of the issue

1. Play as any tags.
2. Have divisions that have many designs.
3. See the division's stats and equipment cost. 

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c3f2e7dd-ed26-4a8f-a403-bcf7f67b1c01)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
