### ISSUE TITLE
Omsk - National Focus not takeable

### ISSUE THREAD

**Issue by Imlitterallyhereforjustonemod** [TNODevs/TNO-Bug-Tracker#192]
**Questions**

- Operating System: Laptop
- 1.10.[Current bug patch]
- 1.2
- No
- Yes
- I have all expansions

**Longer Description of Issue:**
As you will see, I can't take a focus for Omsk, despite all requirements being met.

**Steps to Reproduce/Cause Issue:**

1. ????????????????

2.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/71610183/142768100-65d8cc8f-1baf-4e73-8ced-0dcbb668b64e.png)

**Comment by runelead00** [comment]
Prereq now made visible, fixed in Dev Build
