### ISSUE TITLE
All tags - Overlap operative name with rectangular box and slight doesn't fit the flag box with nationality flag

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1920]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When selecting a recruit operative, there is an overlap between the operative name and the rectangular box. And there is a slight issue with the operative nationality flag because the nationality flag doesn't fit the flag box and slight overlaps if zooming in on the image.

### Steps to reproduce / Cause of the issue

1. Play as any tags.
2. Has the intelligence agency.
3. Recruitment for operatives available.
4. Select available operative.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6eec5d2d-2eb6-48e3-843c-0d17ad9f06e5)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Paradox issue that displays the wrong background at times
