### ISSUE TITLE
Crash - Indeterminate Cause

### ISSUE THREAD

**Issue by Falconinglasses** [TNODevs/TNO-Bug-Tracker#1922]
### Operating System

Win10

### HOI4 version

12.13

### TNO version

1.4.1c

### Do you have other mods in use?

rusification und community expansion

### Were you using Steam?

No

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11646215/error.log)

### Describe the crash

Randomly happens when some event comes up on screen, or sometimes just on its own, practically always at the end of the mouth, but sometimes not(for example when reasearch notification shows up)

### Steps to reproduce / Cause of the crash

Play
Get f*cked randomly

**Comment by runelead00** [comment]
See #1509, an error log alone is not enough to determine what is causing the crash and if it is even related to TNO and not just a submod issue

**Comment by Falconinglasses** [comment]
Well, ehen i downgraded to pre ugly american, there is no crashes so far for 8 years

**Comment by runelead00** [comment]
again that doesn't help with figure out the actually causes or if it was a submod conflict
