### ISSUE TITLE
USA - Most of the PPI decisions have space after decision name when viewing their effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1923]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11652730/USA.zip)

### Describe the bug

When Puerto Plata Invasion starts and moves the mouse cursor to PPi decisions to see their effects, most of the decisions have space after their name. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Puerto Plata Invasion global conflict triggers.
3. Move the mouse to the Puerto Plata Invasion decisions. 

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/698b00d4-bf20-4476-be22-a7f6947c2524)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a6de4fa7-acdc-4d2a-8f17-1c96cc5cfc1a)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e81b8fd3-0302-44cf-bb10-cbb66a39f7a0)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
The spaces are to make the indentation work, working as designed
