### ISSUE TITLE
USA - Command power decreases 5 instead of expected decision requirement from some of the PPI intelligence decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1925]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11658494/USA.zip)

### Describe the bug

Some of the PPI intelligence decisions have required command power but when selecting those, the command power decreases less than the expected decision requirement. 

Like the 'Establish Sleeper Cells' decision required 15 cp but when selecting this, the cp decreased by 5 instead of 15. The same goes for the 'Organise Dissidents' decision. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Puerto Plata Invasion proxy war triggers.
3. Select the 'Establish Sleeper Cells' and 'Organise Dissidents' decisions.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7f4b6ede-6a06-4648-abb8-ab5c968f1325)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f450bbec-459d-4a5d-a91d-9c118cff70df)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e2b3348d-9c40-4785-9b64-b553d3b7b833)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/253a51f4-91f3-47b7-8379-9b8908b9f140)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
