### ISSUE TITLE
USA - GFX focus icon of 'The Fighting Filipinos' is not update when USFIP is changed to Free Philippine Republic

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1927]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the GFX issue

'The Fighting Filipinos' GFX focus icon uses the USFIP logo hat on the right side instead of Free Philippine Republic's coat at arms or logo because the USFIP was changed to Free Philippine Republic during the 1.4.1 version update. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. See the changes of 'blue' Philippine faction from USFIP to Free Philippine Repuiblic.
3. See 'The Fighting Filipinos' GFX focus icon.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6baa85e5-cfaa-44eb-898e-40acd5139351)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6d89b812-3cc9-4673-a9df-bce3ae75c871)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
We will not be updating the icon, given the the FPR and 2nd PR have the same flag, this is a more identifiable image + USFIP/USA still being a major presence in the FPR
