### ISSUE TITLE
SPH/UPH - The 'AFRSR Takes Manila' news event mention about the USFIP 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1928]
### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### List the loc issues below

1. The 'AFRSR Takes Manila' news event talks about the Americans in the South which refers to USFIP but USFIP was changed to Free Philippine Republic and is run by Filipinos who opposed pro-Japanese and potentially, communists. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a337ddcc-a4c8-4e48-81ed-309afbde9694)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/98f85666-4ba8-4e48-8dde-6b4f837cbff7)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
The Americans are still a major prescence in the South and the FPR is heavily influenced by them (see Fertig coup in-game for an example)
