### ISSUE TITLE
BRG - Superevent The Burgundian Spring does not play its unique audio

### ISSUE THREAD

**Issue by glowingone** [TNODevs/TNO-Bug-Tracker#193]
**Questions**

- Operating System: Win 10
- HOI4 Version: Latest
- TNO Version: 1.2.0
- Any other mods in use: OWB Radio
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all expansions

**Longer Description of Issue:**
Super event The Burgundian Spring does not play its unique audio, it plays audio for The African Crisis instead.

**Comment by Scarsoftime** [comment]
Fixed
