### ISSUE TITLE
USA - A small issues for 'Sit Down With Iberia' decision effect

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1931]
### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

1.2.1c

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11663503/USA_Play.zip)

### List the loc issues below

1. In the 'Sit Down With Iberia' decision effect, there is a "W" before effect loc and no line break for "Get event".
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c09479a7-d3a6-4edd-8b1a-3caa37704076)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
