### ISSUE TITLE
USA - Some decisions of Balaguer's Dominican Ceasefire have space between decision icon and name

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1932]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11663644/USA_Play.zip)

### Describe the bug

When I choose Balaguer during the Dominican ceasefire, there are some decisions have space between decision icon and name. Or do not have the '-' negative sign before the decision icon and name.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Puerto Plata Invasion triggers.
3. Caribbean Legion succeeded in defeating Trujillo forces.
4. Trujillo is overthrown and triggers a ceasefire.
5. Choose to side with Balaguer. 

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/81162101-479e-4131-94c7-0fdb2e35bc89)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/decabf54-09e8-4481-ae1d-db8b3f11e852)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
