### ISSUE TITLE
USA - Two intelligence decisions of Dominican ceasefire have unnecessary effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1933]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11676183/USA_Play.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11676971/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11676972/game.zip)

### Describe the bug

In the Dominican ceasefire decisions, two intelligence decisions: Counteract Foreign Agents and Send Intelligence Agents decisions effect have shown operation strength only without some description or effect about these. Because when selecting those and running the game, it doesn't happen. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Puerto Plata Invasion triggers.
3. Caribbean Legion succeeded in defeating Trujillo forces.
4. Trujillo is overthrown and triggers a ceasefire.
5. Choose to side with Balaguer.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/eb8b4ad2-adee-4438-aa8a-294c4976a822)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/78da8743-ed77-475e-a629-2d142468e441)

### Additional information

I have no other info.

**Comment by ModdingAccount** [comment]
Worked as intended; Try interacting more with the interface.
