### ISSUE TITLE
UPH - Doesn't rename to "Republic of the Philippines" after Free Philippine Republic wins the three-way Philippine war

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1934]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_UPH_wins.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11678600/USA_UPH_wins.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11678609/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11678610/game.zip)

### Describe the bug

After FRP wins against the communists and the 14th Army, Free Philippine Republic doesn't rename to "Republic of the Philippines".

### Steps to reproduce / Cause of the issue

1. Balintawak Blintz triggers.
2. AFRSR takes Manila.
3. USA refuses to make an alliance between FRP and AFRSR.
4. End of alliance between communists and FRP.
5. 14th Japanese Army invade the Philippines to retake the Islands.
6. FRP defeats the communists and the 14th Army.
7. FRP wins the Philippine war.

### Expected behaviour

Forgot to rename the country, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c01f2319-f764-4b5e-8f56-0d12a74fbb20)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1a1043ff-0615-4c29-800c-04aa7d576787)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Working as Designed
