### ISSUE TITLE
USA/DOM/CAL - DRF still has the 'American Military Advisors' national spirit after choosing the side with Balaguer

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1936]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Trujillo_defeated.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11682629/USA_Trujillo_defeated.zip)

### Describe the bug

After Trujillo was overthrown, succeeded by Balaguer and chose to side with Balaguer instead of the Revolutionaries, Dominican Revolutionary Front still has the 'American Military Advisors' national spirit. 

The 'American Military Advisors' national spirit should move to Balaguer's Dominican Republic if USA chooses to side with Balaguer and encase of Civil War happens. 

### Steps to reproduce / Cause of the issue

1. Puerto Plata Invasion starts.
2. Caribbean Legion invades the Dominican Republic.
3. Caribbean Legion successfully defeated Trujillo forces.
4. Trujillo has been overthrown.
5. Choose to side with Balaguer over the revolutionary.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/eb5f0283-1e56-4dd7-ba64-23487743aa82)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/69921a8c-0809-48e0-ba6e-b1a9afaf85df)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
