### ISSUE TITLE
GER - 'The Ceasefire' event about the Balaguer's diplomatic solution with US pops out despite USA chose to side with the revolutionaries

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1937]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Trujillo_defeated.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11688746/USA_Trujillo_defeated.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11688896/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11688897/game.zip)

### Describe the bug

When USA chose to side with the revolutionaries after Trujillo was overthrown in the Dominican Republic, Germany received the event about the Dominican ceasefire, and potential diplomatic solution and cooperation with US instead of receiving the event about USA choosing to support the revolutionaries and Germany will receive support to Balaguer's Dominican Republic. 

### Steps to reproduce / Cause of the issue

1. Puerto Plata Invasion starts.
2. Caribbean Legion invades the Dominican Republic.
3. Caribbean Legion successfully defeated Trujillo forces.
4. Trujillo has been overthrown.
5. USA chose to side with Balaguer than the revolutionary.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/021cc87c-01ba-4e25-a14e-390f1099b215)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4a343045-264d-49ca-9f7e-eb2a555d5e8c)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2167fdeb-cfff-4cbc-ba5e-9474d0012f07)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
there is a reason why it's "unconfirmed rumors", the event is for both scenarios
