### ISSUE TITLE
USA - Societial Breakdown Still Present After Proxy Wars

### ISSUE THREAD

**Issue by PresumedEagle10** [TNODevs/TNO-Bug-Tracker#194]
**Questions**

- Operating System: windows 10
- HOI4 Version: latest 
- TNO Version: TT
- Any other mods in use: no
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Usa rioting doesn’t end even when at peace 
**Steps to Reproduce/Cause Issue:**

1.play as usa and enter proxy wars

2. End the wars and it will still be social breakdown at least for bennett

etc...

**Screenshots:**

**Comment by Stormeagle449** [comment]
Fixed for UB.
