### ISSUE TITLE
USA - Active Agent Training is stuck at 100%

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1940]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11704887/USA_Play.zip)

### Describe the bug

Despite the agent training is 100%, the training progress is somehow stuck and doesn't get additional agents.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Train the Agent in the Intelligence tab once and got the additional agent.
3. Train the Agent again.
4. Active Agent Training is stuck at 100%.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aa21690b-8fc3-4313-837e-348f42f0750f)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Should be fixed in Dev Build
