### ISSUE TITLE
USA - Not possible to unlock the 'Formalize Control' decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1944]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11711631/USA_game.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11711633/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11711634/game.zip)

### Describe the bug

When proceeding the stage 3 of the Second Malagasy Uprising, there is no way to unlock the 'Formalize Control' decision due to it requiring German Madagaskar to control any node. And when selecting the German-controlled node, the 'Formalize Control' decision doesn't appear. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Second Malagasy Uprising triggers.
3. Proceed to stage 3.
4. See the 'Formalize Control' decision requirement.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1c094615-b0d9-498e-8761-4fee043ff1bd)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0dd39adc-261b-479c-a4cb-320c0909c5d4)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
