### ISSUE TITLE
USA - Some glitches in the global conflict tab

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1945]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11712237/USA_game.zip)

### Describe the bug

When running the game through almost 1964, there is a glitch image of the Haitian Civil War and there is no description of the Reconstruction of the Philippine global conflicts. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Run the game through December 1963.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8db642af-3650-495d-a071-ecc17e711e09)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7ea32ca2-9950-4ab3-be9c-bf2562a8b0cc)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
