### ISSUE TITLE
USA/FFR/CAO - CTD(crash to desktop) occurs when FFR(Free France) is defeated by CAO

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#1947]
### Operating System

Windows 11

### HOI4 version

1.12.13

### TNO version

1.4.1c

### Do you have other mods in use?

Chinese Localization 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11714765/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11714766/error.log)
[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11714769/USA.zip)

### Describe the crash

When FFR is defeated by PALF during the war(PALF vs. FMA, other conditions untested),crash occurs after the peace conference.

### Steps to reproduce / Cause of the crash

1.Go to Custom Country Paths
2.Set FMA vs PALF and PALF victory
3.Start a game,wait until the war outbreaks
4.When FFR's imperialists are overthrown by PALF,crush occurs.

**Comment by runelead00** [comment]
You wiped your gamelog #1509 and I can't open your the file you send, just gives an error trying to open it, can't determine cause of crash

**Comment by runelead00** [comment]
Fixed in Dev Build
