### ISSUE TITLE
IBR/GER - AI doesn't do anything with the Puerto Plata Invasion

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1948]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

AI GER and IBR are not selecting or interacting with the PPI and Dominican ceasefire decisions when I switch tags to them through the console to see what happens to them. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI triggers.
3. Run the game.
4. Switch the tag to GER and then IBR to see what AI can do with PPI.
5. AI GER and IBR do not select any of the PPI decisions.

### Expected behaviour

Lack of AI interaction with PPI proxy war, probably.

### Screenshots

Not needed.

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
