### ISSUE TITLE
USA - Missing Loc for Indonesian War

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#195]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?
I have all expansions
**Longer Description of Issue:**
The Indonesian War Appears to be missing some loc (from events 1-5). One example: 

![20211120224845_1](https://user-images.githubusercontent.com/56777501/142769225-a24833f9-ae96-40a8-b7c2-b1d471a0bc47.jpg)

**Steps to Reproduce/Cause Issue:**

1. Play the USA

2. Fire the event usaindoflavor.1 via console

**Screenshots:**

**Comment by Scarsoftime** [comment]
Fixed.
