### ISSUE TITLE
GER/FRA - AI can't able to send volunteers again to Militärverwaltung Madagaskar

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1950]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[JAP.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11718038/JAP.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11718039/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11718040/game.zip)

### Describe the bug

After the French State and Greater German Reich (before declaring war for retaking the sphere of influence in Europe) end their wars, they (AI) can't able to send volunteers again to Militärverwaltung Madagaskar. 

### Steps to reproduce / Cause of the issue

1. Second Malagasy Triggers.
2. AI Germany and France send volunteers.
3. German Civil War triggers.
4. Franco-Burgundian War triggers. 
5. End of Franco-Burgundian War.
6. Either Speer or Bormann wins the Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/df86cd47-dbed-450c-b3cb-28b58d370004)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bd8ea1b2-ea2f-4b99-9a6b-98f47e6a22ba)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3515d89a-da05-4d27-b576-f5379c34c008)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
base game issue, if the ai doesn't want to send volunteers, there is absolutely nothing we can do, best you can hope is the ai reevaluates on a reload
