### ISSUE TITLE
USA/HAI - Haitian Civil War goes endless

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#1951]
### Operating System

Windows 11

### HOI4 version

1.12.13

### TNO version

1.4.1c

### Do you have other mods in use?

Chinese Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11718370/USA.zip)

### Describe the bug

Haitian Civil War can't meet an end even if PPLN nearly controls the whole country.(a copy of my game save is enclosed in this issue's "Files" section)

### Steps to reproduce / Cause of the issue

1.Go to Custom Country Paths
2.Set "PPLN crashes the government"
3.Start a game,wait
4.Haitian Civil War goes endless 

### Expected behaviour

PPLN crashes the Haitian government and builds a communist Haitian government 

### Screenshots

![HC1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/956700df-edde-453a-acde-18cb0b8b0cb4)
![HC2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/26e052ac-f66e-46a5-8dec-59de5874de84)
![HC3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/f804c853-5c58-4f9e-8c9c-adf853cfe0d4)
![HC4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/a8bdff19-d86d-492c-9658-373f6944404a)

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
