### ISSUE TITLE
N/A - Game freezes my pc

### ISSUE THREAD

**Issue by brunothedev** [TNODevs/TNO-Bug-Tracker#1953]
### Operating System

Debian Linux sid

### HOI4 version

Avalanche v1.12.14.50e7

### TNO version

v1.4.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

At the end of loading my country, it just freezes my pc, after i added "-opengl -debug_smooth" to launch options, the only thing that changed is that the music continued and sometime my mouse would update

### Steps to reproduce / Cause of the issue

1. Select a country
2. Wait until the end of the loading screen
3. Crash!

### Expected behaviour

It would load the country

**Comment by TheSudoer** [comment]
Experiencing the same on my computer running Linux Mint 21.1

**Comment by runelead00** [comment]
Merged into #962
