### ISSUE TITLE
Iberia - Various bugs, localisation and balance issues from playthrough.

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#1954]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

Music mods and the recall volunteer mod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

1. After already defeating Algeria after Salazar died, the decision timer continued to tick down.
![Iberia1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/9dee004d-5593-46e7-a72e-d7423e60061e)

2. Event says the Iberian council was created almost seven years ago, which would have been around 1961. It would be more appropriate to say it was created almost 5 years ago, around 1963 which is when the focus tree is available.
![Iberia2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/a1b616e4-b9af-4e81-b6f0-2eb097264b27)

3. The "State of the Union" focus, which is the first focus for whether Iberia becomes a democracy or remains under the caudillo mentions the Triumvate despite it being years since it collapsed. Not entirely sure if it is a repeated description.
![Iberia3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/811c17e0-8088-4273-b85d-b8102ed13257)

4. The town of Nuuk's description is missing a picture for it, instead reverting to whatever was previously selected, like Germania or Reykjavik.
![Iberia4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/70e7acd7-6286-4a7c-ab69-3e22a22492b9)
![Iberia5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/664cc25a-95a4-4b66-920d-0ed467259229)

5. The Ovamboland-Namibia war has been going for years with no noticeable change in years either, stuck in permanent stalemate.
![Iberia6](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/0c2e2a0c-166a-40cd-a867-ace6833851d0)

6. The Iraq civil war is also stuck in permanent stalemate despite it being years.
![Iberia7](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/99a1a971-510a-4c46-be15-5e8a71adaba1)

7. The Haitian civil war is currently still ongoing for years despite the original government already being capitulated, No other OFN members have been called in but the war has not ended.
![Iberia8](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/95e3d7b8-80f2-4e31-a695-74f3aa13892c)

8. This is a suggestion as opposed to a bug, but being able to avoid the militarist coup as liberal Iberia shouldn't be RNG based, or at least the RNG mechanics should be more visible.
![Iberia9](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/4738df81-08e4-45c4-9f26-14329e05489b)

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

**Comment by runelead00** [comment]
Iberia bugs fixed in Dev Build, please refrain from grouping a whole bunch of mostly unrelated issues together in the future
Also the Iberia Coup isn't RNG based
