### ISSUE TITLE
USA - State modifier in Madagascar node doesn't improve after select some SMU decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1955]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11733486/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11733487/game.zip)
[USA_smu_stage_3.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11733599/USA_smu_stage_3.zip)

### Describe the bug

When selecting the node that has a negative state modifier and selecting the 'Import Topographers', the state modifier that has been controlled by the Rebels doesn't improve its state modifier. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Second Malagasy Uprising triggers.
3. Reach stage 3 of the SMU.
4. Select the 'Import Topographers' decision. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/239d0cbf-9cc9-4336-b389-f4c0859d8dc3)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6c22b8bb-306d-42ad-b30e-d55ad3f2fca1)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a944273c-9eb8-4f7e-95ea-ae71455ca991)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e34f8c9c-093f-43cf-9953-29d58ae7d84e)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
