### ISSUE TITLE
USA - Double effects shown in 'Import Topographers' decision about state modifier will improve

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1956]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_smu_stage_3.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11733682/USA_smu_stage_3.zip)

### Describe the bug

In the 'Import Topographers' decision effect, there is a double "Local Territory controlled by our faction will improve its state modifier to be better fit for stationing our troops" shown.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Second Malagasy Uprising triggers.
3. Reach stage 3 of the SMU.
4. See the 'Import Topographers' decision effect.

### Expected behaviour

I don't know if this is an oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/139eba2b-dbc4-45de-a5b3-87e3cc3beaca)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev BUild
