### ISSUE TITLE
UPH - Diosdado is somehow in charge of FRP despite the Philippine Reconstruction is not complete or reaching deadline

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1958]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11744486/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11744487/game.zip)
[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11744495/USA_game.zip)

### Describe the bug

After reaching 1964 by running the game, Diosdado Pangan Macapagal Sr. (Liberal Conservatism) is somehow in charge of the Free Philippine Republic despite FRP being previously no election and the USA's Philippine Reconstruction not complete or reaching a deadline. 

### Steps to reproduce / Cause of the issue

1. Philippine conflict triggers.
2. Rebels victory.
3. Ending the alliance between FRP and AFRSR.
4. Free Philippine Republic wins the Philippine war.
5. Select the 'Delegitimize the Leyte Proclamation' decision. 
6. Reach Jan. 1964.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b08cbb88-f5ad-4a22-9b41-f0bf38734083)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8fe7b369-ef62-4613-a69d-537a253414e5)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e3b6b65d-de2b-4c97-9250-e29087d8bfe0)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Should be Fixed in Dev Build
