### ISSUE TITLE
USA/HAI - Glitch in government and PPLN control in Haitian Civil War 

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#1960]
### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

During the Haitian Civil War,the control of the government,the PPLN,and the contested part should add up to 100%,but they add up to nunbers larger than 100%
![Control](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/02ad43ea-2ed3-41a5-b0c9-22c8584ce450)

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
