### ISSUE TITLE
USA - 'HCW_transfered' and 'HCW_locked' are not localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1962]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_HCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11770665/USA_HCW.zip)

### Describe the bug

In the 'Expand the Cap-Haitian Harbor' decision requirement, there are some not localized yet. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Puerto Plata Invasion launch in DOM.
3. Insurrection In Haiti triggers.
4. Haitian Civil War triggers.
5. Proceeds to Phase: Building.

### Expected behaviour

Forgot to added loc, I think

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1593484e-94c4-4238-a842-0e3d19dec031)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
