### ISSUE TITLE
USA - 'Turkmenistan's Ambitions' event triggers in Sept 1964 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1963]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778178/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778179/game.zip)
[USA_gameplay.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778189/USA_gameplay.zip)

### Describe the bug

The 'Turkmenistan's Ambitions' event is somehow triggered in 1964 and it describes the wake of the Oil Crisis despite it not starting yet. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Choose to hear the CIA agent about Turkmenistan in the event.
3. Choose to know about the Turkmen candidates in the event.
4. Choose any of the Turkmen candidates in the event.
5. Event triggers about the newly elected Turkmenistan president.
6. 'Turkmenistan's Ambitions' event triggers.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c073523b-62ef-4efc-8423-06e15efee408)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
