### ISSUE TITLE
KAY - Got the 'West African Protectorate' faction icon after FMA wins the PALF-FMA war

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1964]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_WAW_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778550/USA_WAW_ends.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778551/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778552/game.zip)

### Describe the bug

After FMA wins the West Africa Crisis between PALF and FMA, Mali under Traore (KAY) got the 'West African Protectorate' faction icon instead of 'Signatory of the French Military Alliance'. 

Even if FMA wins without Kayes existing, the issue is still the same as this one.

### Steps to reproduce / Cause of the issue

1. FMA and PALF faction form.
2. West African War triggers.
3. FMA wins the WAW. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0117bd6e-5132-4af1-9926-17951b7ca694)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
