### ISSUE TITLE
All tags - 'French Victory in West Africa' news event pops out twice

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1965]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_WAW_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778586/USA_WAW_ends.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778587/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11778588/game.zip)

### Describe the bug

After FMA wins the West Africa Crisis between PALF and FMA, there are double 'French Victory in West Africa' news events.  

### Steps to reproduce / Cause of the issue

1. FMA and PALF faction form.
2. West African War triggers.
3. FMA wins the WAW.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8d2b3b84-efe9-45f1-b9ea-3c0d500bc346)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
