### ISSUE TITLE
FFR - It should be "Free French" in the FMA victory against PALF news event title

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1966]
### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### List the loc issues below

1. In the FMA victory against the PALF news event, there is the word "French" instead of "Free French" because the FMA is led by "Free" France and there is another French in mainland France. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f183b9ea-7b7c-4547-85ac-2015d59821ce)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4776ba4d-b03f-45bb-a2cf-8fd3f0d10da2)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed for 1.4.1d
