### ISSUE TITLE
Italy - Peace deal calculation crash after National Protection Army war declaration (5th of May, 1966)

### ISSUE THREAD

**Issue by Zakara** [TNODevs/TNO-Bug-Tracker#1968]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[tno_crash.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11779333/tno_crash.zip)

### Describe the crash

National Protection Army declares war on Republic of China (5th of May, 1966) in my game as Italy. Shortly after (within the same in-game day but not immediately when the NPA war declaration event fires), a Peace Deal Conference is being calculated, which immediately crashes my game.

### Steps to reproduce / Cause of the crash

1. Load savegame
2. Un-pause and keep game running on 3-speed
3. Wait for "National Protection Army declares war on Republic of China" event on 5th of May, 1966
4. Click the button associated with the event (just the general confirmation to close the event window)
5. Wait for a few seconds
6. You will see the "Peace Deal Conference" calculation text, which is followed by an immediate crash

### Additional information

- Playing as Italy through the Democratic path
- At the tail-end of the Influence game between Japan and America regarding Italy

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Zakara** [comment]
> Fixed in Dev Build

No manual workaround for my current save? I also have a manual save from like an in-game year before.
