### ISSUE TITLE
USA Savefile. Game crashes on June of 1964 because of a pop-up regarding Vyatka. 

### ISSUE THREAD

**Issue by BaronVonBork** [TNODevs/TNO-Bug-Tracker#1969]
### Operating System

Windows 11

### HOI4 version

Avalanche v1.12.14.50e7

### TNO version

v1.4.1c - Ugly American

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[South African Adventure_temp.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11780092/South.African.Adventure_temp.zip)

### Describe the crash

3 pop ups come up around the same time. Right around a peace deal regarding the West African War. One of them a news event, can be closed with no issue. The second one is a declaration of war, can be closed with no issue. The third one involes Vyatka (I'm sorry I'm new to the mod and don't know or have the the time to throughly read the pop-up) and the moment it appears the game freezes for a second and them crashes to desktop.

### Steps to reproduce / Cause of the crash

Play until June of 1964, preferably after June 15th.

Somebody either declares war on Vyatka or capitulates Vyatka

That specific pop-up causes the game to crash

### Additional information

I had to send it as a zip file otherwise it would be too big. I hope it isn't too much of an inconvinience

**Comment by runelead00** [comment]
The save file you send is corrupted and can not be opened in game

**Comment by runelead00** [comment]
Probably fixed in dev build
