### ISSUE TITLE
USA - Missing Loc for West African War

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#197]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?
I have all expansions
**Longer Description of Issue:**
I was playing as the US and during the West African War and got a few events without localisation
![West Africa Bugged](https://user-images.githubusercontent.com/56777501/142769592-19fb22c5-81cb-4e10-bed1-c7d225f8d7ea.png)

**Steps to Reproduce/Cause Issue:**

1. Boot up the USA

2. Console in west_african_crisis.212

**Comment by bobw123** [comment]
Also west_african_crisis.213 is broken

**Comment by runelead00** [comment]
Both Fixed in Current Release
