### ISSUE TITLE
USA - No increase current election political party or opposition parties effect given in Malagasy rebels victory event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1970]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When PADESM takes control over Madagascar after Malagasy rebels win the second Malagasy uprising, there is no increase current party election effect in the 'Rebellion's End' event.

Even when TAFAMA takes control over Madagascar, there is no increase opposition parties election effect in the 'TAFAMA's New Framework' event. And also for AFKM when takes control over Madagascar.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Second Malagasy Uprising triggers.
3. Malagasy Rebels win the Second Malagasy Uprising.
4. Either PADESM, AKFM or TAFAMA wins. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e0bd8484-2da4-4ba9-a63d-85edf678131f)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/90075f12-d527-4352-bad0-93a46b3a4d80)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
