### ISSUE TITLE
CAO/CPR/ANL/PALF - Red Congo and red Angola never joins PALF

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#1971]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

Chinese Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11780669/USA.zip)

### Describe the bug

If The West African War outbreaks later than Congo and Angola civil war(only possible if the west africa crisis scenario is "WAA vs FMA vs PALF"),red Congo and red Angola won't join PALF after PALF wins the war.

### Steps to reproduce / Cause of the issue

1.Go to Custom Country Paths
2.Set WAA vs FMA vs PALF,and PALF victory
3.Set red Congo and red Angola wins their civil war
4.start a game,wait

### Expected behaviour

red Congo and Angola join PALF

### Screenshots

![RedCongo3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/f5c12dc0-9cd5-4f90-af78-14b736b09d3f)
![RedCongo1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/846f62f3-c039-431f-94e1-729429996774)
![RedCongo2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/68048c5b-3409-435c-8faa-58d326b93b55)

**Comment by runelead00** [comment]
Fixed in Dev Build
