### ISSUE TITLE
PAC - No divisions when a tag created

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1972]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11780715/USA_Play.zip)

### Describe the bug

When the First Paraguayan Corps (PAC) was formed, the tag has no divisions and PAC has unable to defend itself against Bolivia due to no divisions. 

### Steps to reproduce / Cause of the issue

1. Paraguay falls into crisis.
2. FULNA seize control of Paraguay
3. First Paraguayan Corps (PAC) formed in the northwest.
4. Paraguay becomes a communist state.
5. Triple Alliance declares war on Paraguay.
6. Bolivia declares war on Santa Cruz and First Paraguayan Corps.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d128be97-ab97-443e-b8b1-da8cd03465ab)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/593014f5-2180-4f3a-875e-07348a49571c)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
