### ISSUE TITLE
USA - Unable to unlock the 'Public Demands Disengagement' decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1974]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11788161/USA_Play.zip)

### Describe the bug

When proceeding to phase intervention for the Haitian Civil War, the 'Public Demands Disengagement' decision is somehow locked and there are no requirements for unlocking it.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Haitian Civil War triggers.
3. Proceeds to phase intervention. 
4. See the 'Public Demands Disengagement' decision. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/87c4f8e9-7f2a-45a5-ac98-2ec3911f80ed)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed for 1.4.1d
