### ISSUE TITLE
USA - There is a word "Disengament" instead of "Disengagement" in HCW decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1975]
### HOI4 version

1.12.14

### TNO version

1.4.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11788243/USA_Play.zip)

### List the loc issues below

1. In the Haitian Civil War decision, I saw misspelled "Disengament". 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/024e673b-475e-4d65-9ac2-c1e6389e3b98)

### Additional information

I have no additional info.

**Comment by Stormeagle449** [comment]
Fixed for 1.4.1d
