### ISSUE TITLE
Scotland, focus tree event continuation

### ISSUE THREAD

**Issue by SlySlyBreadAndPi** [TNODevs/TNO-Bug-Tracker#1977]
### Operating System

windows

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

was playing through attempting to do a SNP run off scotland.  Chose to deny the first bill(whether to attempt the first bill) and agreed to increased military spending bill. Continued to play on. All normal although not sure if it had anything to do with it but when it came to focuses i pivoted and chose to go down the reunification path. in about late 63 i failed to prevent the military junta coup during the military police event chain. The event did stay on around after the coup and resulted in a 'nothing happeneing dialogue'. Decided to go with and go through the focus tree rolling with the punches. during this time the civil in england fired and was lost, keeping Marget thatcher in power. 
After getting to the end of the focus i stopped getting events and no new focus tree appeared i have let the game run for another 2 years and nothing more has occured. 

### Steps to reproduce / Cause of the issue

1. go snp
2. go down unification focus path
3. fail to prevent coup
4. england civil war uprising is lost
5

### Expected behaviour

More to happen. after a few hours of game play and no war kind of hit a dead end. Not sure if i just got unlucky and went down the one path that goes nowhere. thought at least id be attacked.

**Comment by runelead00** [comment]
Nope, that's pretty much all the content for Scotland, unless you want to wait years to get invaded
