### ISSUE TITLE
Communist Haiti's Ruling Party Bug

### ISSUE THREAD

**Issue by TheDinoTsar** [TNODevs/TNO-Bug-Tracker#1978]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I do not think the files are necessary for this bug

### Describe the bug

So after the Haitian Communists win the Haitian Civil War, after a certain point the country will switch from a named leader, with a portrait and all the things we come to expect from skeleton content to around the later 1960s (like 1968ish) the country's ruling party changes to generic socialism and the country leader changes from a named, known historical figure to some generic dude with generic leader traits.

### Steps to reproduce / Cause of the issue

1. Play the new TNO update
2. Have the Haitian Communists win the Civil War
3. Wait until 1966ish
4. Change occurs automatically

### Expected behaviour

I don't know what the expected behavior's should be but it seems to me that this is just a flaw with skeleton content

### Screenshots

![20230620152958_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/137230847/97799988-d396-4fee-b291-511a3b32542b)

### Additional information

I also find it a little strange that with the latest TNO update (1.4.1d) that the ruling party of the initial Haitian Communist leader has changed from Marxist-Leninist too Stalinism. This too me doesn't make much sense especially since the economy of Haiti is "worker-directed" and Stalinism advocates a Planned Economy. Also I don't think the Haitian Communist Leader even was a Stalinist and shouldn't Stalinism be dead expect outside the Soviet Union. Sorry if this is not approriate for the Bug Report thing you guys have going but it bugged me a lot especially since it wasn't in the recent changelog

PS: IGNORE THE FACT I AM PLAYING CAMEROON, this happens even outside of playing a nation with no content

**Comment by TheDinoTsar** [comment]
An Addendum to this bug report is that this seems to only occur when the PALF win the West African War and Communist Haiti joins the Pan-African Sphere

**Comment by runelead00** [comment]
Fixed in dev build, issue with effect scoping for PALF victory in all scenarios + Amazonism in the DR
