### ISSUE TITLE
Country Affected - Short Description of Suggestion

### ISSUE THREAD

**Issue by TheDinoTsar** [TNODevs/TNO-Bug-Tracker#1980]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

After the Iberian Collapse, Guinea-Bissau should join the PALF and Pan-African Sphere if the PALF/Cameroon wins the West African War

### Justifications

It kind of makes sense if the PALF has already won the WAW and then for the Iberian Collapse to occur for the newly freed _Pan-African_ rebels of Guinea-Bissau to join the Cameroon Sphere and PALF Faction for protection from Iberia.

### Screenshots

![20230620173110_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/137230847/b2f598cc-2ad5-4d81-ac1f-a28b4ca63fea)

### Additional information

Didn't know if I should put this as a bug or a suggestion and decided to settle on this being a suggestion

**Comment by Stormeagle449** [comment]
Guinea-Bissau does join the PALF, but only after Cameroon successfully invades Liberia and Mendi.
