### ISSUE TITLE
England Proxy description broken

### ISSUE THREAD

**Issue by GoldenShowa** [TNODevs/TNO-Bug-Tracker#1982]
### Operating System

Windows 10

### HOI4 version

Avalanche 1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

On the Global Conflicts tab, the description of "An Atlantic Battleground" (US v Germany proxy for control of England) is missing

### Steps to reproduce / Cause of the issue

1. Play USA
2. Play until the England proxy event in 1964
3. Check the ForPol tab and find the description missing

### Expected behaviour

The proper description of the "An Atlantic Battleground" to appear

### Screenshots

![tnobug](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94769222/5cf0fb80-f86b-405e-88c2-219d568ec202)

**Comment by runelead00** [comment]
Fixed in Dev Build
