### ISSUE TITLE
USA - Foreign Policy Lag issue persists

### ISSUE THREAD

**Issue by Calisniper91** [TNODevs/TNO-Bug-Tracker#1983]
### Operating System

Windows 10 home 

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, NSB, BBA

### Describe the bug

When playing as the USA, during the lead up to the Madagascar Proxy conlifct and afterwards, the game will lag significatly when you have the foreign policy tab open. The game will breifly freeze before resuming again and lag quite a bit. closing said menu results in the lag residing. this was supposedly fixed in the recent hotfix. 

### Steps to reproduce / Cause of the issue

1. select as the USA
2. Play until the madagascar rebellion decisions become avaliable.

### Expected behaviour

the game to run at normal speed as it was prior

**Comment by Ikidikid** [comment]
I think the TNO devs should try CKShrek321's fixing new proxy war GUI lag methods.
