### ISSUE TITLE
Canadian Skeleton Content Bug

### ISSUE THREAD

**Issue by TheDinoTsar** [TNODevs/TNO-Bug-Tracker#1984]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

During any game of TNO Canada where Diefenbaker wins the first Canadian Election and then the Cooperative Commonwealth Federation wins the next election, a world event where Diefenbaker is still PM occurs in 1970-ish despite the CCF being in power.

### Steps to reproduce / Cause of the issue

1. Play any country in TNO (besides maybe Canada I guess)
2. Have Diefenbaker win the first Canadian PM Election
3. Have him lose Re-Election too the CCF (or maybe any other party but the CCF is when it has occurred in both of my games)
4. Wait until February 1970 for the skeleton content world event too pop up.

### Expected behaviour

I assume some other skeleton content event occurring for Canada

### Screenshots

![Screenshot 2023-06-21 170227](https://github.com/TNODevs/TNO-Bug-Tracker/assets/137230847/fd6ed337-22ce-4c90-84d8-0e098cd66048)
![Screenshot 2023-06-21 170348](https://github.com/TNODevs/TNO-Bug-Tracker/assets/137230847/397247d0-65c8-43a5-83d4-c37050d0ef34)
![Screenshot 2023-06-21 170930](https://github.com/TNODevs/TNO-Bug-Tracker/assets/137230847/5b291b8b-8b0c-46aa-9b3c-18bd62407bb9)

### Additional information

Some notes:
1. I used the Custom Country Paths to make Diefenbaker win and then for him to lose to the CCF
2. Besides the event I posted, another event where Diefenbaker loses this referndum has also occurred in a previous game in the same circumstance (Diefenbaker winning, then losing, but still being PM when another party is in power)
3. It seems like the Skeleton Content is broken because nothing seems to happen in terms of a National Spirit, a change on the map, or anything like that. I don't know if this is supposed to occur, if this is something this specific bug is causing, or even this is an entirely separate bug

**Comment by runelead00** [comment]
Fixed in Dev Build
