### ISSUE TITLE
All tags - Not localized for APC module slot again

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1985]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

APC_designation_slot and APC_armament_slot are not localized again.

### Steps to reproduce / Cause of the issue

1. Play as any feature tags.
2. Create a variant for APC.
3. See loc for designation and armament.

### Expected behaviour

Oversight again.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c8e8691c-7484-43a6-b757-d4e5a71d5956)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bed70fae-e421-46b7-9174-f81ac1689d29)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
