### ISSUE TITLE
[Bug]: Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by kaz1ch** [TNODevs/TNO-Bug-Tracker#1988]
### Operating System

Win 10

### HOI4 version

1.12.11 (latest)

### TNO version

1.4.1d (latest)

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The culture of South Georgia is Japanese.

### Steps to reproduce / Cause of the issue

1. Boot up the mod
2. Press on the South Georgia

### Expected behaviour

The culture of South Georgia should be Falklander or something.

### Screenshots

![JSG](https://github.com/TNODevs/TNO-Bug-Tracker/assets/61201257/dd5e2b8e-0cc9-44b2-9de0-726b96364a0d)

### Additional information

The great Co-Prosperity Sphere knows no boundaries! Glory to Nippon and Dai Tōa Kyōeiken!

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
