### ISSUE TITLE
ARM - Missing Leader for Armenian Revolt (Communist)

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1989]
### Operating System

Windows 10

### HOI4 version

1.12.13

### TNO version

1.4.1d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11834443/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11834445/game.log)

### Describe the bug

The leader for the communist Armenian Revolt is missing both name and portrait.

### Steps to reproduce / Cause of the issue

1. Have the Armenian Revolt launch, headed by the communists.
2. Observe issue.

### Expected behaviour

Leader portrait and name shows.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/e0a420b0-cf65-40ae-8831-7a18cb58d5fd)

**Comment by runelead00** [comment]
Fixed in Dev Build
