### ISSUE TITLE
USA/JAP - There is a word "TANAFA" instead of "TAFAMA" in 'The End of French Madagascar' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1991]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### List the loc issues below

1. In 'The End of French Madagascar' event description, there is the word "TANAFA" instead of "TAFAMA"
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/44963961-5686-4111-a401-e7916c8afd9e)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
