### ISSUE TITLE
USA/DOM - Dominican Republic's Enemy Bombing Runs national spirit effect doesn't remove negative effects after selecting Icarus event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1992]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11847370/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11847371/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11847374/USA_play.zip)

### Describe the bug

When selecting the 'Begin Close-Air Sorties' decision before or after selecting USA's 'Icarus' event, DOM's 'Enemy Bombing Runs' national spirit effect doesn't increase positive or remove some negative effects.

I don't know if the DOM's 'USAF Bombings' national spirit will remove some of its negative effects.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI triggers.
3. Germany selects decrease air bombings in DOM decisions.
4. PPI landing triggers. 
5. Select 'Begin Close-Air Sorties' decision before or after selecting 'Icarus' event. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/059409f3-b71d-4da5-81f7-ca2affcdc8e1)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/074b6728-775a-4756-a43e-7b2a60f44e64)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2b031c13-77cc-4231-84b2-82a5ce95e9be)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
