### ISSUE TITLE
MEX - Ordaz has "Red Eminence" leader trait instead of "Americophile"

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#1993]
### Operating System

Windows 10

### HOI4 version

1.12.13

### TNO version

1.4.1d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11849332/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11849334/game.log)

### Describe the bug

Ordaz has the incorrect leader trait. If I'm correct he should have the trait "Americophile" instead of "Red Eminence," which is reserved for a different president of Mexico.

### Steps to reproduce / Cause of the issue

1. Have Mexico elect Ordaz.
2. Observe issue.

### Expected behaviour

Ordaz has leader trait "Americophile."

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/272abd83-181a-4692-a30e-ce22b24b9d2b)

**Comment by runelead00** [comment]
Replaced Ordaz's trait, removed Madrazo's, Red Eminence is only for Suslov, Fixed in Dev Build
