### ISSUE TITLE
Playing as the SBA, the game crashes at 4:00 on August 2, 1972

### ISSUE THREAD

**Issue by Tibbers1312** [TNODevs/TNO-Bug-Tracker#1996]
### Operating System

Windows 10

### HOI4 version

Avalanche v1.12.14.50e7 (273b) (S)

### TNO version

TNO v1.4.1d - Ugly American

### Do you have other mods in use?

Leftist Radio, Songs of The Anarchists, Radio TNO, The New Order: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11853953/executed_commands.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11853954/error.log)
[SBA_1972_08_02_01 Unification TIme.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11853965/SBA_1972_08_02_01.Unification.TIme.zip)

### Describe the crash

The game crashes consistently at 4:00 on August 2, 1972.

### Steps to reproduce / Cause of the crash

Unpause the game and wait until 4:00 on August 2, 1972. The game will consistently crash at that exact day and time.

**Comment by runelead00** [comment]
Save was start on UB version C and mod updated to version D midway though, issue that lead to crash is client-side
