### ISSUE TITLE
USA - Goldwater Presidency - Fight Fascism decision has wrong success parameters

### ISSUE THREAD

**Issue by br54** [TNODevs/TNO-Bug-Tracker#1997]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

The file that needs fixed is "common/decisions/TNO_USA_decisions.txt"

### Describe the bug

The success conditions for Goldwaters fighting fascism decision use the success conditions for fighting socialism, making it impossible to complete.

### Steps to reproduce / Cause of the issue

1. Click fighting fascism
2. Cry because it's impossible to complete

### Expected behaviour

When the correct conditions are met sovereigntists support should drop

### Screenshots

![Desktop Screenshot 2023 06 23 - 22 35 43 96](https://github.com/TNODevs/TNO-Bug-Tracker/assets/7267500/b62cf9ff-f92d-4f73-a0d5-63789f91fd25)

### Additional information

Hope you're having a good day, thanks for making an awesome mod. <3

**Comment by runelead00** [comment]
Fixed in Dev Build
