### ISSUE TITLE
USA - Budgets do not decrease when selecting some intelligence decisions 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1998]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_intelligence_decisions.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11854400/USA_intelligence_decisions.zip)

### Describe the bug

When selecting some intelligence decisions that have required budgets, the budgets for intelligence do not decrease. 

### Steps to reproduce / Cause of the issue

1. Play as USA. 
2. See intelligence budgets.
3. Select some agency intelligence decisions.
4. See intelligence budgets again.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/69eaeac9-a15e-4c18-b349-40234ee24ed3)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7b4dfefa-b41d-49e9-a79c-4657cb48ae9a)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c8120b78-af95-4268-9588-8573f7519163)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0131367e-202d-4ea7-b299-68c025e9546c)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
