### ISSUE TITLE
USA - Finalize a Peace Agreement PPI ceasefire's decision shows remove some ideas but DOM and CAL do not have these ideas

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#1999]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11854431/USA_play.zip)

### Describe the bug

When I looked at the Finalize a Peace Agreement decision effect, it shows that will remove DOM's USAF bombings modifications and Significant Revolts, and DOM and CAL's Military Preparation national spirits. But these national spirits do not exist in DOM and CAL's national spirits.   

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI triggers.
3. PPI ceasefire triggers.
4. USA chooses Balaguer.
5. Tension is relaxed.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/840fbace-1681-42b4-b8a9-e9e9bd2eeb83)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fca2202a-bc9f-4e4b-b82a-91d11664a90f)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
