### ISSUE TITLE
USA - Invest In Novisbirsk bugged

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#200]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?
I have all expansions

**Longer Description of Issue:**
The CIA decision for Invest in Novisbirsk wouldn't go away for a little bit. It did eventually leave but it would linger on the CIA tab regardless of what region you were focusing. In the case below, the CIA's focus is clearly outside of Russia but the aggressive Novisbirsk investors keep trying to pitch another venture.

![Invest in Novsibirsk](https://user-images.githubusercontent.com/56777501/142769876-870487ef-ce5e-435d-a352-4b75a6bd1894.png)

I think they even kept doing so after it was dead.

I think I see the problem. Comparing these two focuses, the Novisbirsk one doesn't have an avaliability condition that requires the CIA window to be on Russia
![image](https://user-images.githubusercontent.com/56777501/142770010-5a78d0e5-9595-4c99-b312-a4969d64472e.png)

![image](https://user-images.githubusercontent.com/56777501/142770021-cac8e03c-43c6-408f-a969-92c690b7cb72.png)

**Comment by Scarsoftime** [comment]
Fixed in the dev version, thank you for your report.
