### ISSUE TITLE
DOM - Tags' opinions issue after diplomatic success in Dominican Republic during the ceasefire

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2000]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

1.2.1c

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11854606/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11854607/game.zip)
[USA_dominican_ceasefire_peace.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11855972/USA_dominican_ceasefire_peace.zip)

### Describe the bug

After taking the Finalize a Peace Agreement decision and The Santo Domingo Agreement news event triggers, there are some opinion relations issues of Balaguer's Dominican Republic with the rest of the Caribbean nations. 

The opinion between Mexico and Cuba, and Balaguer's Dominican Republic should rename their opinion to "Hostile" instead of remaining "Caribbean Tensions" because Trujillo is gone. 

The opinion between West Indies Federation and Balaguer's Dominican Republic does not remove "Caribbean Tensions" because under Balaguer, relations between the Dominican Republic and USA are now ok, and West Indies is in OFN.

The opinion between New Granada and Balaguer's Dominican Republic does not remove "Fascist Comrades" because the Dominican Republic is no longer a fascist and Trujillo is gone

I don't know about Venezuela's relationship with the Balaguer's Dominican Republic. Should they keep the "Caribbean Tensions" negative opinions and remove "Caribbean Tensions" due to VEN being an OFN partner? 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI triggers.
3. PPI ceasefire triggers.
4. USA chooses Balaguer.
5. Tension is relaxed.
6. Finalize a Peace Agreement decision finish. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d26651ee-6ca1-4626-ab85-fe7c07cbe865)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f94bb7a1-d4f0-4c32-afa7-68f74c612209)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4a9bdeb5-70df-44de-bb55-c5c3ec2503bb)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7201fb77-7b2b-49fc-a9bc-17259e1ba0d2)
![Image_5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/734b5b54-cf04-43a7-a170-ddf20b966d25)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
