### ISSUE TITLE
Localization error

### ISSUE THREAD

**Issue by Dwffffffcccccc** [TNODevs/TNO-Bug-Tracker#2001]
### Operating System

Windows 11.

### HOI4 version

the latest version of hoi4

### TNO version

the latest version of tno

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The mistake is most likely due to the fact that the authors forgot to translate the description of the global conflict in the Battle of Britain, if Maximilian had ruled there.

### Steps to reproduce / Cause of the issue

1) Go to the user rules and make sure that Trevor comes to power.
2) Wait until the civil war in Germany is over (It is desirable that Bormann wins it)
3)We are waiting for the start of the global conflict about the "Battle of Britain"
Ready.

### Expected behaviour

I expected that the interface would be clearly visible, where the number of the influence of the USA, Britain and Germany in glasses would be displayed.

### Screenshots

![Screenshot_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/87900842/2d1d1dfa-6bb0-4655-9d4e-3031cb89edb8)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
