### ISSUE TITLE
USA - Haitian government victory in HCW instantly triggers when the HCW starts

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2002]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_HCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11856663/USA_HCW.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11856665/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11856666/game.zip)

### Describe the bug

When the Haitian Civil War triggers, the 'Insurgency Eradicated in Haiti' world news, and 'The Ugly Americans' events are somehow instantly triggered. 

When I selected 'The Ugly American' and then 'The Ugly Americans' events, I got Total Victory for the Haitian Civil War despite the HCW still ongoing in global conflict. And Haiti got a 'Renewed Haitian Sovereignty' national spirit somehow. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. USA supports Balaguer in the PPI ceasefire.
3. Successful negotiation between the Balaguer's government and the Legion.
4. The Dominican Republic peacefully annexed the Dominican Revolutionary Front without the Civil War.
5. Haitian Civil War triggers. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/23b07d36-e460-4ab9-ad09-80add5ff0a18)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aee324a1-54a2-4dc8-962b-5e087cad85ba)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2dd7c67d-b238-4791-a490-e2b7eadee85f)
![Image_5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/305a276a-1b12-46dd-abf9-1f8828e15c3c)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
