### ISSUE TITLE
DOM - Odd second paragraph in 'Insurgency Eradicated in Haiti' world news despite DOM is anti-socialist and ok with the USA

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2004]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_HCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11858397/USA_HCW.zip)

### List the loc issues below

1. The second paragraph in 'Insurgency Eradicated in Haiti' world news says about the Dominican Republic has been the PPLN's greatest supporter - though not always. But in my game, Balaguer is in charge of DOM, the relationship between USA and Dominican Republic is normalized (due to USA choosing Balaguer during the PPI ceasefire), and Balaguer is anti-far left.
This also includes liberal or progressive DOM if the alliance between socialists and non-socialists breaks down. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7372c3bc-7c8a-4862-b207-c937dde96ac5)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
normalized relations with the USA  doesn't necessary mean the Haiti-DR relations are going to suddenly be good, also she the "not always intentionally line"
