### ISSUE TITLE
USA - Legitimacy is somewhat 0 after selecting 'The Ugly American' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2005]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_HCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11858433/USA_HCW.zip)

### Describe the bug

After selecting 'The Ugly American' event to start the Haitian Civil War global conflict, the legitimacy is somewhat 0.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Dominican conflict triggers.
3. Haitian Civil War triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2b4c091d-f827-4a4f-b8a1-5344ac96db6c)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5023dce8-1ad5-4192-b341-001567c2fbb3)

### Additional information

I don't know what causes this.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
