### ISSUE TITLE
"Maximizing Growth" national spirit as Japan is not removed upon Yasuda Crisis event

### ISSUE THREAD

**Issue by MadTaco** [TNODevs/TNO-Bug-Tracker#2006]
### Operating System

Windows 10

### HOI4 version

Avalanche v1.12.14.50e7 (5555)

### TNO version

v1.4.1d "Ugly American"

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Yasuda Crisis event shows on its event tooltip that the "Maximizing Growth" national spirit should be removed, but it isn't removed. It does correctly remove the "Sense of Security" national spirit.

### Steps to reproduce / Cause of the issue

Seems to be a consistent bug regardless of conditions and throughout past versions as well.

### Expected behaviour

"Maximizing Growth" national spirit should be removed.

**Comment by runelead00** [comment]
Fixed in Dev Build
