### ISSUE TITLE
USA/UPH - Free Philippine Republic is not joining the OFN after completing the Philippine reconstruction

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2007]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11861136/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11861137/game.zip)
[USA_uph_reconstruction.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11861140/USA_uph_reconstruction.zip)

### Describe the bug

After selecting the 'Delegitimize the Leyte Proclamation' decision and 'Declare Reconstruction Complete' in The Reconstruction of the Philippines, Free Philippine Republic is not joining the OFN.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Philippine Conflict triggers.
3. the Free Philippine Republic wins against the Japanese 14th Army and the communists.
4. Complete the reconstruction of the Philippines.

### Expected behaviour

Oversight again, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/33c9efdf-8835-48c9-bf4f-2bbf5323e979)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5b362f92-f91c-4495-b64b-bbd8fad1018f)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fd8361f3-64f3-4c51-8da2-6288b1a79fd8)

### Additional information

I don't know what causes this.

**Comment by runelead00** [comment]
Working as Designed, Philippines can no longer join the OFN as a member
