### ISSUE TITLE
USA - Still no add voters effect again in the aftermath of the Second Malagasy Uprising event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2009]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11861190/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11861191/game.zip)
[USA_PADESM_victory.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11861192/USA_PADESM_victory.zip)
[USA_madagascar_will_join_ofn.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11861203/USA_madagascar_will_join_ofn.zip)

### Describe the bug

This issue is the same as this one. #1970

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Second Malagasy Uprising triggers.
3. Malagasy Rebels win the Second Malagasy Uprising.
4. Either PADESM, AKFM or TAFAMA wins.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/eaaf5c59-0853-4e09-91d7-26d90f89adff)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
