### ISSUE TITLE
USA - Discontent grows even when at peace.

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#201]
**Questions**

- Operating System: Windows 10 Home
- HOI4 Version: 1.10.8 Collie
- TNO Version: 1.2.0a Toolbox Theory
- Any other mods in use: Spot Optimization Mod
- Were you using Steam? Yes.
- Which expansions do you NOT have? I have every expansion. 

**Longer Description of Issue:**
Essentially my issue is that discontent for the United States never disappears, and progressively gets worse despite being at peace, not having mandates, and not having volunteers of any conflicts I could intervene in. I suspect the reason why is that I let the mandates decolonize themselves, but I personally do not know. The ticking decrease to your discontent every 2 months did nothing either it seems. The President was Wallace F. Bennett just to clarify. The discontent went all the way to Societal Breakdown.
**Steps to Reproduce/Cause Issue:**

1. Play as the United States. Win all conflicts that cause discontent, and let the mandates decolonize themselves successfully. 

2. Wait from there, as your discontent will raise even when at peace time. 

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/94796674/142770048-6055c14a-6ebd-457a-a23d-237f3b74e606.png)
![image](https://user-images.githubusercontent.com/94796674/142770065-786302b3-529f-4143-9b47-93b6f01978b6.png)
![image](https://user-images.githubusercontent.com/94796674/142770165-54d0b43f-f779-4b09-9c08-eddd39247357.png)

**Comment by runelead00** [comment]
No longer an issue in UB
