### ISSUE TITLE
USA-Changing Armor or Engine during MBT design causes it to claim design too expensive despite having enough xp

### ISSUE THREAD

**Issue by Godsofchicken** [TNODevs/TNO-Bug-Tracker#2010]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Preventing me from creating a new MBT design by stating my design is too expensive when modify engine and armor values. 

### Steps to reproduce / Cause of the issue

1. Start a Game
2. Go into production and select a new MBT design
3. Modify engine and armor values
4. Will claim design to expensive

### Expected behaviour

Should allow me to save and create the design once I increase engine and armor values

### Screenshots

![Hearts of Iron IV 2023 06 25 - 20 00 17 04](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98362386/a45b215d-ed6a-4e8f-92ed-457435d18d46)
![Hearts of Iron IV 2023 06 25 - 20 00 20 05](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98362386/8bf61d0e-c817-4cf0-88ac-f0f0a22d99e6)

**Comment by runelead00** [comment]
??? you have 5 xp, saving costs 6, Working as Intended in provided screenshots

**Comment by Godsofchicken** [comment]
Shit misread army xp for navy xp, my bad
