### ISSUE TITLE
Atlantropa doesn't appear

### ISSUE THREAD

**Issue by Unaliare** [TNODevs/TNO-Bug-Tracker#2011]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.4.1

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11866223/error.log)
No save game

### Describe the bug

The Mediterranean is at his pre-Atlantropa level

### Steps to reproduce / Cause of the issue

1) Launch the game
2) See

### Expected behaviour

I expected to see the Mediterranean drier

### Screenshots

![Capture](https://github.com/TNODevs/TNO-Bug-Tracker/assets/70194852/982d4709-cf51-4487-a652-249273155c88)

**Comment by Stormeagle449** [comment]
WAD since 1.2.0

**Comment by Unaliare** [comment]
So it's normal that is don't appear ?
