### ISSUE TITLE
HAI - Haiti's ideology and it's head of state glitches after PALF wins The West African War

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2013]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Chinese Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Red Haiti's ideology should be Pan-Africanism after PALF wins The West African War,and it's head of state should be Jacques-Stephen Alexis,rather than "ordinary" socialism and a random leader.

### Steps to reproduce / Cause of the issue

1.Go to custom paths
2.Set "PPLN crashes the government",PALF vs. FMA and PALF wins The West Africa War
3.Start a game,wait

### Expected behaviour

The Red Haiti's ideology should be Pan-Africanism after PALF wins The West African War,and it's head of state should be Jacques-Stephen Alexis

### Screenshots

![Red Haiti1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/e7b9d247-44fc-4be2-bcaa-8d604fa12a22)
![Red Haiti2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/fb8f32aa-70c8-4287-9529-bdc5427ed8f6)

**Comment by runelead00** [comment]
Fixed in Dev Build
