### ISSUE TITLE
Gabonese Union - He is blue

### ISSUE THREAD

**Issue by T3dsch1K1** [TNODevs/TNO-Bug-Tracker#2016]
### Operating System

Windows 11

### HOI4 version

1.12.14 

### TNO version

1.4.1

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The leader of the Gabonese Union is blue 

### Steps to reproduce / Cause of the issue

1. Let PALF win
2. African devastation at stage 2
3. PALF attacks Gabon and puppets it

### Expected behaviour

He should not be blue

### Screenshots

![grafik](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94788365/c0ecd191-d42a-4bdd-a4b6-d2724deeb0b2)

**Comment by runelead00** [comment]
Fixed in Dev Build
