### ISSUE TITLE
CAN - Get Diefenbaker event despite Socreds being in power

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#2017]
### Operating System

Windows 10

### HOI4 version

1.12.13

### TNO version

1.4.1d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11875206/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11875207/game.log)
[TNO.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11875211/TNO.zip)

### Describe the bug

Despite the Socreds being elected into power in the previous election, the world news event about Canada's patriation for when the Tories are in power under Diefenbaker still fires.

### Steps to reproduce / Cause of the issue

1. Have Socreds be elected for the first time.
2. Wait for ~ Feb 1970.
3. Observe issue.

### Expected behaviour

Event only fires for Diefenbaker if he's in power in 1970.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/712124e4-25ef-4106-9cdb-3b6756d073ac)

**Comment by runelead00** [comment]
Fixed in Dev Build
