### ISSUE TITLE
USA - There is a word "woth" in intelligence decision loc effect of 'Invest in Novosibirsk'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2018]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11875254/USA_play.zip)

### List the loc issues below

1. In the 'Invest in Novosibirsk' intelligence decision effect, there is the word "woth".
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7fd86497-d335-4976-8491-2dc189fc701c)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
