### ISSUE TITLE
GER/SLO - Slovakia doesn't increase its current party popularity after Germany defeats Slovak Republic

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2019]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11875311/USA_play.zip)

### Describe the bug

After Germany defeats the Slovak Republic due to Slovakia's refusal, the Slovak State doesn't increase its current party popularity (either National Socialism or Fascism).  

### Steps to reproduce / Cause of the issue

1. Either Bormann or Speer wins the German Civil War.
2. Slovak Republic refuses to submit to Greater German Reich. 
3. Greater German Reich attacks the Slovak Republic.
4. Slovak State becomes subjugated again by Greater German Reich.   

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/505f3969-fe4a-4e3f-8d10-38ffd99c8d25)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
