### ISSUE TITLE
Problems with Chinas response of Long Yun tree

### ISSUE THREAD

**Issue by WhyDoesCheeseExist** [TNODevs/TNO-Bug-Tracker#202]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.10.8
- TNO Version: Toolbox theory
- Any other mods in use: TNO, The Last Waltz of Europe expanded, Toolpack, universal coloured puppets
- Were you using Steam? Yes
- Which expansions do you NOT have? Eastern front planes pack, eastern music pack, axis armour pack, radio pack, both sabaton music packs, allied armour pack, allied speeches music pack.

**Longer Description of Issue:**
In china's initial response tree to Long Yun (before the war) the "one last ultimatum" focus doesn't have an effect, and I never received an event. Also, "Put down the mad dog" tooltip is broken, showing the unlocalized version
**Steps to Reproduce/Cause Issue:**

1. Play as Long Yun and look at Chinas response tree

2. Play as China and look at your response tree

etc...

**Screenshots:**
![image_2021-11-21_163143](https://user-images.githubusercontent.com/63547428/142770542-108e8259-5329-46f8-98a6-ef4540bebd4e.png)
![image_2021-11-21_163204](https://user-images.githubusercontent.com/63547428/142770564-3c4831e6-a1fe-401a-bb7b-c050a4b38a31.png)

**Comment by tkgitno** [comment]
Fixed in Dev Build
