### ISSUE TITLE
GRO/BOR/ANG/COG/URL/ORE - Their faction icons should slightly decrease their size

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2020]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the Afrika-Schild and Ural Alliance faction icons should slightly decrease their size. Similar to major alliances and the West African alliances (WAA, PALF and FMA).   

### Justifications

Because their faction icon sizes are different, which are slightly bigger compared to other faction icon sizes. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a4db3b83-771a-4a33-8e26-a196ddb14b7c)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0f310ba8-7758-488c-9645-516d439849c5)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
