### ISSUE TITLE
USA/HAI - Some of the Haitian state doesn't become demilitarized when the PPLN almost reaches 50% 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2021]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_HCW_phase_buildup.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11882767/USA_HCW_phase_buildup.zip)

### Describe the bug

During the Haitian Civil War, some of the Haitian states doesn't become demilitarized when the PPLN almost reaches 50% to control one of the Haitian states. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. HCW triggers.
3. At least one Haitian state is almost 50% controlled by PPLN. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/274afbc6-ad40-42f6-ba9d-4567298d7dce)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7d17d1bf-f998-4f62-9654-69b5030a513e)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
