### ISSUE TITLE
USA/HAI - PPLN tag doesn't pops up when some of the Haitian state has more than 50% of PPLN supporters

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2023]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11887820/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11887822/game.log)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11887824/USA_play.zip)

### Describe the bug

When some of the Haitian states reached more than 50% of PPLN supporters during the Haitian Civil War, PPLN (socialist Haiti) tag doesn't pops up. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Haitian Civil War triggers.
3. At least one Haitian state has PPLN supporters of more than 50%.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/53b84a8a-cfc1-449d-bd02-f4d28747950a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5b2c0bfe-4373-4f75-9c01-69150701c0f4)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
