### ISSUE TITLE
BRA - No news event about the Adhemar is elected as the president of Brazil after hundred days

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2024]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11888026/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11888027/game.zip)
[NEP.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11888033/NEP.zip) (Run the game to see what happens)

### Describe the bug

When Adhemar is elected as the new president of Brazil after hundred days, there is no news event about the Adhemar becoming the new Brazilian president. 

### Steps to reproduce / Cause of the issue

1. Hundred days triggers in Brazil.
2. Adhemar is elected as the new president of Brazil.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8a03dc49-8498-459b-9d33-2018b6038dc6)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
There are no news events for the end of Hundred Days
