### ISSUE TITLE
WIN - WIF(The West Indies Federation) can't collapse even if the custom option "The Federation Collapses" was chosen in custom paths

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2025]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Chinese Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11892754/save.zip)

### Describe the bug

WIF can't collapse even if the custom choice "The Federation Collaspes" was chosen in custom paths,(The event will fire but the WIF will still be a nation)

### Steps to reproduce / Cause of the issue

1.Go to custom paths
2.Set "The USA allow Jamaica Independence Referendum", "Jamaica Leaves", "Trinidad Leaves", and "The Federation Collapses"
3.Start a game,wait

### Expected behaviour

The Federation collapses immediately after the event fires

### Screenshots

![WIF1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/1d1ff918-2429-4caf-b24f-fdcd308f2eb1)
![WIF2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/27ff2cd9-ac37-44be-a43c-e1bc333d552e)

**Comment by runelead00** [comment]
Fixed in Dev Build
