### ISSUE TITLE
ITA/IBR - They still have the sending volunteers national spirits after the Algeria War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2026]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11893256/USA_play.zip)

### Describe the bug

After the Algeria War, Italy and Iberia still have the 'sending volunteers to their Algerian territories' national spirits. 

### Steps to reproduce / Cause of the issue

1. The triumvirate collapsed.
2. Algeria War between Italy and Iberia.
3. Algeria War ends. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bc84ceca-8fac-4f2e-a135-7b11f81583ec)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/46c1f2df-3fc8-4dbb-a9c4-567e1524f49c)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8d9e4650-d0ef-4bbc-9d86-4a307d911eaa)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
