### ISSUE TITLE
USA - 'Public Demands Disengagement!' decision is not appeared

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2027]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11895562/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11895563/game.zip)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11895723/autosave.zip)

### Describe the bug

After reaching Phase: Intervention and having the '100/100' during the Haitian Civil War as USA, there is no 'Public Demands Disengagement!' decision to appear. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Haitian Civil War triggers.
3. Reach Phase Intervention (100/100)

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/beb09cea-8f54-4a65-a296-207b146fe205)

### Additional information

No response

**Comment by runelead00** [comment]
Public Demand Disengagement does not depend on phase or violence, it depends on weariness, WAD as far as I can tell
