### ISSUE TITLE
GER - Second Malagasy Uprising doesn't show in cold war achievements for Germany

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2029]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_SMU_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11900603/USA_SMU_ends.zip)

### Describe the bug

After the Second Malagasy Uprising ends before the German Civil War ends, the Second Malagasy Uprising doesn't show in the cold war achievements for Germany after the German Civil War ended. 

### Steps to reproduce / Cause of the issue

1. Second Malagasy Uprising triggers. 
2. German Civil War triggers.
3. Second Malagasy Uprising ends (possibly rebels' victory due to the Germans and French unable to support the garrisons).
4. German Civil War ends. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a629d30f-85ef-4cf0-b477-526a70622353)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ca72ef56-6a9a-4940-8251-3eb1279ef4f2)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
