### ISSUE TITLE
USA - Change the Loc for Race Riots Focus if LBJ passes Strongest CRA

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#203]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
Right now no matter what, once you pass the Voting Rights Act as LBJ, you get an event (LBJ.16) called Race Riots. 
![This is BS](https://user-images.githubusercontent.com/56777501/142770200-7c2acd1d-0dd2-4af4-9d79-8f97eedb3e2b.png)

This event loc makes it sound like the President didn't do anything for the Black community and it looks like it was probably originally meant for if LBJ made a weak bill as a punishment before it became integrated into the "main" storyline. I recommend the loc be changed depending on the bill LBJ made - the events you get if you go strong or medium already suggest the pro-Wallace population is mad so maybe they can be the instigator instead.

**Reasoning Behind Suggestion:**
Make the story a bit more congruous with the decision you made

**Additional Information:**
Maybe something like this? It keeps most of the wording intact but shifts the mood of the African-American community towards being defensive of the new bill rather than hating it

LBJ.16.desc:0 "In at least half a dozen cities across the nation, most notably Birmingham, New York, and Los Angeles, African American communities are in jubilation, their inhabitants taking to the streets to celebrate the passing of president Lyndon Johnson's landmark Civil Rights bill. The bill, which saw a fierce vote in the Senate between the Progressives and the Far Right and Republicans, has widely been criticized by the latter for its deep protections for African Americans and their disadvantaged communities. In response to the bill, leaders like Wallace and Thurmond have mobilized thousands of supporters into the streets in a vicious backlash in the South.\n\nAfrican Americans hardly share that sentiment, as tens of thousands began demonstrating early this morning, calling the President a "hero", and preparing to fight to defend their newly won gains. In many cities however, notably Los Angeles and Birmingham, state governors sent in police and National Guard elements to disperse the protestors. Things became violent quickly, however, with the protestors using improvised weapons to fight back, as well as makeshift shields made from hubcaps and trash can covers to block the fire hoses the police attempted to disperse them with. By the end of the day, hundreds of shops, cars, and public buildings had been vandalized or burned.\n\nFighting appears to have been worst in Birmingham, where it appears that the local chapter of the Klu Klux Klan involved themselves when the demonstrations became violent. The Klansmen formed a temporary alliance with the police chief in charge of the operation, and soon came down upon the protestors with clubs and other weapons. Now, with most of the Birmingham riot concluded, at least 19 people, 12 of them African American, are confirmed dead."

**Comment by ModdingAccount** [comment]
Fixed in dev build.
