### ISSUE TITLE
France/Iberia

### ISSUE THREAD

**Issue by choclatemilk123** [TNODevs/TNO-Bug-Tracker#2030]
### Operating System

Windows 11

### HOI4 version

1.12.13

### TNO version

v1.4.1d

### Do you have other mods in use?

Radio TNO, second west russian war (pretty sure thats not the problem)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

France does not leave Iberia econmic union after iberia dies. Look at screenshot.

### Steps to reproduce / Cause of the issue

1. Have Iberia collapse
2. Before Iberia collapses have france and iberia sign agreement
3. before iberia collapses have free france france reconcile with french state.
4.

### Expected behaviour

I thought free france would leave. 

### Screenshots

<img width="1920" alt="Screenshot 2023-06-28 185339" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/138082408/262f0c71-c2b1-422f-b312-ce9d4efc9588">

### Additional information

I know this is not really a big deal but its kinda anoyning lol.

**Comment by runelead00** [comment]
Fixed in Dev Build, change also means France is more likely join the OFN if Iberia fucking dies
