### ISSUE TITLE
CAN/ENG - The culture of South Georgia is Japanese 

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2031]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![SG-JP](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/bec6528e-142d-4f78-8d04-faf803b8471e)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
