### ISSUE TITLE
PAR/STC/CLC/DOM - Communist Paraguay is still has the 'very good relationship with the fascist nations in the Americas'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2032]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[PAR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11906281/PAR.zip)

### Describe the bug

After the communists seized control of Paraguay, Paraguay still has the 'Fascist Comrades' positive opinion on New Granada, Santa Cruz, and the Dominican Republic with each other despite Paraguay being communist.  Although, the Dominican Republic under Balaguer is no longer a fascist state.  

### Steps to reproduce / Cause of the issue

1. Paraguay falls into crisis.
2. FULNA seize control of Paraguay
3. Paraguay becomes a communist state.
4. Hugo Banzer seizes control of Santa Cruz. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/021f84c0-62b8-4969-b119-8f89b875e996)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/13d07a1f-a8c1-4980-8fbd-e9b44ae9493e)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1d04fb13-6e08-4c9f-8728-4cae21293b87)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3a43e6b8-1ddf-485f-8ff6-1af1a63e0c44)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
