### ISSUE TITLE
ITA - Some of Scorza's national focuses have no effects shown

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2033]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11906405/USA_play.zip)

### Describe the bug

When playing the game, I saw some of the Scorza national focuses have no show of their effects. 

### Steps to reproduce / Cause of the issue

1. Scorza becomes the new Duce of Italy.
2. Scorza's phase 2 focus trees triggers. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/83b83256-3d69-4ad8-8562-8e9e4a867a92)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/418c5b2c-21d8-4c24-9ec3-f32fd3a1ca9f)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/43396e5a-9509-4504-9d4c-59b528449fcd)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed for 1.5.0
