### ISSUE TITLE
SCO - Minor Mistake in King's Speech Event Description

### ISSUE THREAD

**Issue by KeetnaWilson** [TNODevs/TNO-Bug-Tracker#2034]
### HOI4 version

1.12.14

### TNO version

1.4.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

WTT, MTG, LAR, NSB, BBA

### List the loc issues below

Event ID = SCO.2708: Event 'The "King's" Speech' description, one of Scotland's starting events, misidentifies Robert McIntyre as the President when he is in fact the Prime Minister. It states, from the perspective of the actual President, John MacCormick, "As he had his papers in his hand, he looked for his President and friend, Robert McIntyre who had smiled at him and gave him a thumbs up." A correct version of this sentence would read "As he had his papers in his hand, he looked for his Prime Minister and friend, Robert McIntyre, who smiled at him and gave him a thumbs up."
![Screenshot 2023-06-29 231419](https://github.com/TNODevs/TNO-Bug-Tracker/assets/37520104/fd629213-8ae9-4fda-a03c-890e401c5a4d)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
