### ISSUE TITLE
HAI/DOM(CAL)/USA - (Sometimes) Red Dominican causes the USA wins the HCW(Haitian Civil War) instantly.

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2035]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

If Maximo Antonio Lopez putsches the Caribbean Legion's DOM government and founds a red DOM(before the HCW outbreakes),The USA will win the HCW immediately even before the HCW outbreaks(the event that The US wins will fire BEFORE the event of HCW),thus causing the HCW page and decisions can NEVER be removed from the global conflict decisions,which will cause much more glitches.
PS.2 pictures are enclosed in this issue's "Screenshots" section,which show that the winning event fires before the HCW event

### Steps to reproduce / Cause of the issue

1.Go to custom paths,make sure the CL(Caribbean Legion) wins the Puerto Plata Invasion
2.Set the socialists coups the CL government,and make sure the coup d'etat succeed before the HCW
3.Wait until the HCW and "enjoy" the consequent bugs and glitches

### Expected behaviour

I just want a "normal" HCW......

### Screenshots

![Win BEFORE the HC outbreaks](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/20c51d3b-8701-4f49-a699-814ddccf661b)
![Win BEFORE the HC outbreaks2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/4455bdf8-54d0-49b1-864f-0d67f8568468)

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
