### ISSUE TITLE
ENG-Global conflict of Thatcher's foreign politics has a desc_error and doesn't work properly

### ISSUE THREAD

**Issue by Iron-Chancellor2** [TNODevs/TNO-Bug-Tracker#2036]
### Operating System

Windows 10

### HOI4 version

1.12.13

### TNO version

v1.4.1d "Ugly American"

### Do you have other mods in use?

radio_tno

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Thatcher comes to power in England, a global conflict page opens for USA and Speer's Germany to vie power over England. Playing as Germany AND the U.S., the decisions have a described effect for them (e.g. North Sea Exercise as Germany lowers OFN's and England's influence and give Germany +1 influence each month).
But these decision do not actually HAVE an effect, and the conflict will never resolve, since an desc_error exists for it. When taking a decision, you pay the PP/CP costs, but it for nothing. No events fire for it, no changes happen, and there is no screen displaying the progress.
Therefore, some form of desc_error needs to be fixed in this global conflict.

### Steps to reproduce / Cause of the issue

1. Thatcher has to be in power
2. Speer's Germany has to exist
3. Thatcher's gamble that lets the superpowers vie over England has to start
4. The global conflict display shows a desc_error once the gamble started

### Expected behaviour

Expected outcome of this global conflict would be that England either stays independent, or joins OFN/Pakt spheres

**Comment by runelead00** [comment]
Fixed in Dev Build
