### ISSUE TITLE
USA/HAI - 'Crushing the PPLN' decision fails despite the Haitian state is controlled by the government more than 90%

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2037]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11915465/USA_game.zip)

### Describe the bug

When some of the Haitian states reaches more than 90% controlled by the Haitian government during the Haitian Civil War, the 'Crushing the PPLN' decision still fails due to its requirement fail if the PPLN reaches more than 10 controlled the state but it is not. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Haitian Civil War triggers.
3. At least one of the Haitian states is controlled by the Haitian government more than 90%.
4. Crushing the PPLN decision appears.
5. Weird Crushing the PPLN decision requirement. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d0ff4f62-43ab-46e5-926f-5ee79fb92a7f)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fdfc8b31-f62f-4c98-85ed-d329addecc0f)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fdf53a96-4aef-4ac2-9df7-d9c34f766552)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
