### ISSUE TITLE
USA - Confuse percentage in control breakdown during Haitian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2038]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11915550/USA_game.zip)

### Describe the bug

In my game as USA, I saw a weird percentage about controlling the Haitian state that didn't match with the 100%. Like, PPLN controls 6.37% while the government controls 98.62% in Artibonite et Nord. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Haitian Civil War triggers.
3. At least one of the Haitian states is controlled by the Haitian government more than 90%.
4. See the pie chart about the struggling control over the Haitian state percentage. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/86a32760-66bd-4a5a-8620-8163210696b5)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
