### ISSUE TITLE
USA - There are no decisions about giving increase 'Weariness' after reaching Phase Intervention (100/100) of HCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2039]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11915460/USA_game.zip)

### Describe the bug

Despite reaching Phase Intervention (100/100) in the Haitian Civil War and March 1965, there are no decisions about the increasing 'Weariness' effects. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Haitian Civil War triggers.
3. Reach Phase Intervention (100/100).

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/42dccc84-82a8-49a7-8b1a-1376dbe55366)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
