### ISSUE TITLE
USA - Game crashes when zoom in on South Africa during SAW

### ISSUE THREAD

**Issue by Bearbeer1** [TNODevs/TNO-Bug-Tracker#204]
**Questions**

- Operating System: Win 10
- HOI4 Version: Collie v1.10.8 (0aab)
- TNO Version: v1.2.0a “Toolbox Theory”
- Any other mods in use: The New Order: Last Waltz Expanded
- Were you using Steam? Yes
- Which expansions do you NOT have?
N/A
**Longer Description of Issue:**
When SAW first pop up, I send 200 CAS and 80 Fighters to the airport in South Africa, at the border of the Boer Republic. Then I send 3 divs, 2 of the Armored Division template, and one air cav template that is available from the start as the US. When the 3 units get there I zoomed in on them and the game just crashes each time. This happens around December 7 or 8 1963 as Nixon still.
**Steps to Reproduce/Cause Issue:**

1. Send 200 Improved CAS I and 80 Improved Fighter I

2. Send three divisions 

3. When the units get there, assign a frontline where the airport is at the border of the Boer Republic.

4. Zoom in on the units where the airport is at.

5. Game crashes

**Screenshots:**
Couldn't get a screenshot of this since it crashes before I could get a chance of that.
**Game Saves and Log Files, if possible:**

**Comment by runelead00** [comment]
A crash like this was discovered and fixed internally around this same time, so I assume it has been fixed. If this is still causing issues for you and others, I recommend a reinstall of the mod and see if that fixes it
