### ISSUE TITLE
USA - Slight issue for Haitian state control pie chart in Haitian Civil War global conflict

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2040]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11916641/USA_game.zip)

### Describe the GFX issue

After selecting and waiting to finish the 'Increase Haitian government control' operation decision on the selected Haitian state in HCW proxy war tab, there is an empty gap in the selected state pie chart. But when selecting again on the selected state, the pie chart is back to normal, probably.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Haitian Civil War triggers.
3. Select the 'Increase Haitian government control' operation decision.
4. Wait to finish the 'Increase Haitian government control' operation decision.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aaefb380-bcf5-44f7-b282-5ab1a1c13290)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8e73d0e0-2ac2-4348-81f0-22f38167ea01)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9947a07c-66a4-4edb-b624-360ee17f52d4)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
