### ISSUE TITLE
URP - Uruguayan Occupation Zone is not in the economic sphere while Uruguay has

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2042]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11923833/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11923834/game.zip)

### Describe the bug

After the triple alliance defeated communist Paraguay, the Uruguayan Occupation Zone is not a member of the economic sphere while Uruguay has. 

### Steps to reproduce / Cause of the issue

1. Paraguay becomes a communist nation.
2. The triple alliance invades Paraguay. 
3. Paraguay was defeated. 

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/85af5d5b-1897-4492-b71e-909c27f81ba9)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/880d213f-426f-4f11-adf0-a727e5cafaa5)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
