### ISSUE TITLE
USA - COL_civil_war_preparations is not localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2043]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11924602/USA_play.zip)

### Describe the bug

`COL_civil_war_preparations` is not localized in the Supply URC Forces decision requirements. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Colombian Civil War resumes.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fccc5a7e-af31-4090-9809-2397363d1268)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
