### ISSUE TITLE
IBR/COL - Benevolent Motherland opinion is not removed when Pinilla wins the election

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2044]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[IBR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11924669/IBR.zip)

### Describe the bug

When Pinilla wins the election due to his previous coup in Colombia, the Colombian opinion of Iberian Union's Benevolent Motherland is not removed because Iberian will support New Granada if Pinilla stays in power. 

### Steps to reproduce / Cause of the issue

1. Pinilla coup in Colombia.
2. Pinilla wins the election.
3. Colombian Civil War resumes.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2f67b87f-f926-48d6-ae09-d852f5013d58)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5168402b-fc44-4b79-befa-6cf4319ba513)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
