### ISSUE TITLE
CLC - It should be "OFN" not "Sphere" due to Japan supports New Granada

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2045]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11924786/USA_play.zip)

### List the loc issues below

1. In 'Japanese Support' national spirit description says to include isolating "Sphere" instead of "OFN". 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f448308d-1822-4dd1-96d2-0b80225389a9)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
