### ISSUE TITLE
USA - "American Military Advisers" can cause CP(Command Power) and Army Experience decrease 

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2046]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

"American Military Advisers" can cause CP(Command Power) and Army Experience decrease

### Steps to reproduce / Cause of the issue

1.Start a game
2.(I don't know)
3.CP and Army Experience decrease

### Expected behaviour

CP and Army Experience should grow

### Screenshots

![cp -](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/7285e772-72c5-4439-9e76-114dd8380f5b)
![xp -](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/99c2684a-68d4-4f1d-8acd-8d62e281a377)

**Comment by runelead00** [comment]
Fixed in Dev Build
