### ISSUE TITLE
USA/OMS - There are supporting Black League intelligence operations pop out despite US is not recognize Black League yet

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2049]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11929802/USA_play.zip)

### Describe the bug

After Black League(Omsk) takes control over West Siberia, USA has the supporting the Black League intelligence operations despite US is not recognize Black League or the Black League is not taking the 'Appeal for Recognition' national focus. 

### Steps to reproduce / Cause of the issue

1. Luftwaffe Bombings ended in West Russia and Siberia.
2. Unification War of West Siberia.
3. Black League(Omsk) takes control over West Siberia. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/45af54b1-6365-4696-b53e-13aa55050e2e)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/69efc59b-d885-4ece-814e-1f7eb77ad928)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Not recognizing a country never stopped US covert support before, WAD
