### ISSUE TITLE
USA - Slight issues for The African Mandates proxy war after choosing to form CAR

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2051]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_saw_victory.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11931676/USA_saw_victory.zip)

### Describe the bug

There are OFN East Africa decisions after choosing to form CAR instead of choosing to remain three African mandates.

There is no 'Expand Peacekeeping Mission in Central Africa' decision but instead, there are three 'Expand Peacekeeping Mission' decisions despite choosing to form CAR. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. Total Victory for South Africa and the OFN in South Africa War.
4. Chooses to form the Central African Republic.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9d717e8c-84e7-4f42-b72f-c3b2243ce192)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/950e8939-255e-4444-8bd0-c5fc2d522b87)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
First part, fixed in dev build, expand peacekeeping however is WAD
