### ISSUE TITLE
USA - NPP's foreign policy focus trees and George Wallace's civil rights focus trees slightly overlap with each other after OFN wins the SAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2052]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_saw_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11934830/USA_saw_ends.zip)

### Describe the bug

After the OFN wins the South Africa War, NPP's foreign policy focus trees and George Wallace's civil rights focus trees slightly overlap with each other. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. Elect George Wallace as the new US president.
4. Win the South Africa War. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d465de5c-a16a-4d0a-809a-5a87b403ec68)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/330b5a49-5ecb-4815-9f18-c8a2553127fc)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/01425f9f-7735-49dc-a379-6606f61f0258)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
