### ISSUE TITLE
SAF - Some SAW national spirits do not get removed after the South Africa War ended

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2053]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_saw_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11935424/USA_saw_ends.zip)

### Describe the bug

After South Africa War ended with South Africa exists, some of the SAF's SAW national spirits do not get removed. 

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. South Africa War ends. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/47b92bb7-bba9-4d85-b763-aee434fecf3f)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3ab74615-dd34-4337-8d08-98dd0a2cf75a)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
