### ISSUE TITLE
USC - AI doesn't select any of the OFN Interim Command decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2057]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USC.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11941746/USC.zip)

### Describe the bug

It seems that AI Central African Republic is not doing anything with the pre and post-CAR collapse decisions. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. Total Victory for South Africa and the OFN in South Africa War.
4. Chooses to form the Central African Republic.
5. Run the game.
6. Switch to tag USC to observe what USC is doing.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/181f7e35-e323-4875-945a-29450c8d9894)

### Additional information

I have no other info.

**Comment by Marok132** [comment]
I hope it will fix soon.

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
