### ISSUE TITLE
All tags - Intelligence research is somehow appeared when doing observe and it cannot be closed

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2058]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When entering observe through the console, the 'Directorate of Research and Technology' is somewhat appeared and unable to close this. 

### Steps to reproduce / Cause of the issue

1. Play as any tag.
2. Observe by doing the console command.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aff8e780-4178-40f2-8010-ad76ddc73767)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Working as Designed to allow AI to work properly
