### ISSUE TITLE
USA - There is less than 50% stability negative effects in 'The African Quagmire' despite the mandate stability is more than 50%

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2059]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_africa_mandate.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11941847/USA_africa_mandate.zip)

### Describe the bug

Despite the Mandate has stability of more than 50% and there is only one Mandate, in 'The African Quagmire' decision time effects, there is an additional negative effect due to stability is less than 50% in one of those Mandates.

### Steps to reproduce / Cause of the issue

1. Total Victory for South Africa and the OFN in South Africa War.
2. Chooses to form the Central African Republic.
3. Has the Mandate stability of more than 50%.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d8d1d9b4-3f53-498f-8bb3-2f07dd348343)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/86a6ea8e-a00c-4e02-8f64-d4dd2186a9cd)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
