### ISSUE TITLE
USA - Missing UI Icon for Increased Civil Rights Enforcements

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#206]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use:
A music mod
- Were you using Steam?
yes
- Which expansions do you NOT have?
I have all expansions
**Longer Description of Issue:**
There is a missing focus icon for USA_LBJ_voting_rights_enforcement_boost
![Civil Rights Bug](https://user-images.githubusercontent.com/56777501/142770841-285ac5d9-c864-4182-bacd-1575a80d785e.png)

It might be caused by the focus icon having the wrong name
![image](https://user-images.githubusercontent.com/56777501/142770899-c3e2c7c1-57a5-40c4-a953-9dc03d969383.png)

![image](https://user-images.githubusercontent.com/56777501/142770948-5b742d51-7df5-482a-b700-b7191514f772.png)

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by Stormeagle449** [comment]
Fixed for UB.
