### ISSUE TITLE
USA - Operation CONCORD is appeared despite the South Africa War was over

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2061]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11943903/USA_game.zip)

### Describe the bug

After the South Africa War ended, the 'Operation CONCORD' is somewhat appeared. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers before completing the South Africa Secured focus.
3. Finishing the South Africa Secured focus.
4. End of the South Africa War. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fa3fe8b6-0fad-4a6a-914b-753728237eaf)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/afc64b0e-9fd9-465d-874b-c6dbd16366aa)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
