### ISSUE TITLE
USA - There are no 'Sabotage Second Patriotic Army Supply Lines' decision and 'Light American Bombing' idea for SPA

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2062]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11944388/USA_play.zip)

### Describe the bug

When the Colombian Civil War escalates, there is no 'Sabotage Second Patriotic Army Supply Lines' decision, and in the Light Bombing Campaign decision effect, there is no 'Light American Bombing' targeting SPA despite the Second Patriotic Army exists. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Colombian Civil War resumes.
3. Colombian Civil War escalates. 

### Expected behaviour

Forgot to add target on SPA during the CCW. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3d63524c-3074-4acf-984d-eb5239207f2e)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1168abf2-ec33-472b-82f0-882ee00553b6)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Added decision in Dev Build.
