### ISSUE TITLE
CLD - There is no mention about the Second Patriotic Army in the Colombian Civil War Resumes news event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2063]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11944431/USA_play.zip)

### List the loc issues below

1. In the 'Colombian Civil War Resumes' news event, there is no mention of the Second Patriotic Army despite the SPA's existence and at war with the three.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b1fc34a3-9fa7-4ac8-abee-f41600877c4c)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build x2
