### ISSUE TITLE
OMS - Nameless tag after Black League collapsed due to death of Dmitry Yazov

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2065]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_black_league_collapse.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11944669/USA_black_league_collapse.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11944787/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11944788/game.zip)

### Describe the bug

After the death of Dmitry Yazov and the Black League collapses, Omsk becomes a nameless tag. 

### Steps to reproduce / Cause of the issue

1. Black League wins the West Siberia smuta.
2. Black League collapses. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4e9a415d-5625-4344-95f2-466e24ca8932)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Working as Designed
