### ISSUE TITLE
USA/USC - Ending screen pops out when selecting the first option of the 'Reflect, then Decide' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2070]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11949756/USA_game.zip)

### Describe the bug

When the 'Reflect, then Decide' event pops out due to the dissolution of the Central Africa Republic and selects the first option of this event, the ending screen pops out.

I think this event is meant for the Central Africa Republic but this event is popping out for USA. Or the first option of the 'Reflect, then Decide' event should be removed.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Total Victory for South Africa in SAW.
3. Chooses to form the Central African Republic instead of three mandates. 
4. USC chose the diplomatic path due to the Africa Crisis.
5. USC manages to prevent the Africa Crisis from escalating.
6. Dissolution of the Central Africa Republic. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/16e2a8d9-f961-44af-aa90-792cca9eef01)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/68e78c41-bfa4-483f-9a8c-e6eb743ceb9a)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
