### ISSUE TITLE
SUS/EWE - Guinea and Ghana do not join the WAA after WAA defeats PALF during the West Africa War(WAA vs PALF)

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2074]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_WAC_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11952658/USA_WAC_ends.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11952659/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11952660/game.zip)

### Describe the bug

When the West African Alliance defeats the PALF(Pan-African Liberation Front) during the West Africa War(WAA vs PALF), Guinea and Ghana are not joining the WAA due to their previous alliance with the PALF(Cameroonian African State). 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. West Africa Alliance from and Free France joins the WAA.
3. The West Africa War was triggered in 1967.
4. WAA wins the war against PALF.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d69d11c3-eaec-46ff-875b-a6ca648c4c30)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bb8267a2-349a-4a25-a998-649504458675)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/165ee01b-a398-4df2-9ab8-496ce8ea6fb7)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
