### ISSUE TITLE
ITA/Italian subjects - ita_lira_zone national spirit is not lozalized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2075]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11962507/USA_game.zip)

### Describe the bug

When I looked one of the Italian subjects, I saw a not localized `ita_lira_zone` national spirit.

### Steps to reproduce / Cause of the issue

1. Scorza becomes the new Duce of Italy.
2. Italy taking the 'The New School' focus.
3. Italy going to Rome Pact path.

### Expected behaviour

Forgot to add loc, I think. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e9656910-224d-481e-94c4-2970a27cec41)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
