### ISSUE TITLE
USA/JAP - 'Rumblings' and INS' 'Rise of the Duumvirate' events do not trigger after selecting any ICW decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2076]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11972889/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11972890/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11973002/USA_play.zip)

### Describe the bug

After selecting any Indonesian Civil War decisions as USA or JAP when the Duumvirate triggered. the 'Rumblings' and INS' 'Rise of the Duumvirate' events do not trigger and after running the game through months, the events still somehow do not appear. 

### Steps to reproduce / Cause of the issue

1. Indonesian Civil War triggers.
2. Indonesian Civil War takes too long. 
3. Lubis takes control of the Indonesian government along with Suharto. 
4. Select any Indonesian Civil War decisions as USA or JAP. 
5. Duumvirate in Indonesia.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d5a971b7-ae08-45c0-bbac-734881ad3077)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/635c574c-7a0e-4fa1-a386-379219d18526)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/175086a8-70e2-41e6-804a-f7c1e8903d64)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
