### ISSUE TITLE
USA - There is still Military Advisor sending volunteers to Free Indonesia despite Free Indonesia and PRIM are gone due to duumvirate

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2077]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11972999/USA_play.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11973003/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11973004/game.zip)

### Describe the bug

After the duumvirate triggers in Indonesia due to the civil war taking too long and Lubis taking the lead, USA still has the sending volunteers to Free Indonesia military advisor despite the PRIM no longer exists. 

### Steps to reproduce / Cause of the issue

1. Indonesian Civil War triggers.
2. Indonesian Civil War takes too long.
3. Lubis takes control of the Indonesian government along with Suharto.
4. Duumvirate in Indonesia.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a17c8444-e248-456e-9d7c-4dfc8dbb8beb)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/03fb6f4c-7b58-45d2-b370-4dbab13d1172)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Volunteer effect for Lubis fixed in Dev Build
