### ISSUE TITLE
FFR - The Reclamation of France news event doesn't trigger when the French Reclamation starts

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2078]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11973085/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11973086/game.zip)
[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11973144/USA_game.zip)

### Describe the bug

When the French Reclamation triggered, there is no news event popped out about 'The Reclamation of France'.

### Steps to reproduce / Cause of the issue

1. Free France wins the West Africa War.
2. French Reclamation commences.
3. French Reclamation War triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

Not needed.

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
