### ISSUE TITLE
USA - Give small notifications every time the discontent level rises

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#208]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
Add an event every time the US sees its discontent rise.

**Reasoning Behind Suggestion:**
It's weird that you can have a total Societal Breakdown and yet you wouldn't know it as the player because the UI is fairly full of ideas and you don't really get notified as people get madder and madder.

**Additional Information:**

**Comment by runelead00** [comment]
No longer relevant for UB
