### ISSUE TITLE
USA - 'Some Lip Service' national focus is not unlocked despite the requirement is met

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2085]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11982767/USA_play.zip)

### Describe the bug

After completing either the 'Old Friends, New Dynamic' or 'Cuffed to the Chair' focus or both, the 'Some Lip Service' national focus is somehow not unlocked despite the 'Some Lip Service' focus requirement is met. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect NPP in the 1964 presidential election.
3. Elect Philip Hart (RDC-D) as the president in 1968.
4. Completing former NPP president focus tree.
5. Complete either 'Old Friends, New Dynamic' or 'Cuffed to the Chair' focus.  

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e432938d-da1f-44df-b0fe-ee21b34ead5b)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0785389e-44cf-4b40-98c7-8760e30236e0)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build, Requirements on Some Lip Service and Saint of the Senate are now tooltipped (control of the Senate vs not)
