### ISSUE TITLE
Some GFX files dont show up on Linux

### ISSUE THREAD

**Issue by intheworlditsgone** [TNODevs/TNO-Bug-Tracker#2087]
### Operating System

Linux (Pop_OS!)

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Files on Linux are case-sensitive meaning if an interface or character file points to a gfx portrait file in gfx/leaders/moskowien, (Notice how the M in moskowien is undercased) but the actual name of the directory is gfx/leaders/Moskowien/, the portrait won't show up. This causes portraits in Moskowien to not show up correctly on Linux, as well as some tech icons, and other portraits such as Adolf Heusinger. There was a submod a while back to fix some of these issues, but its outdated. https://steamcommunity.com/sharedfiles/filedetails/?id=2365818068&searchtext= 

### Steps to reproduce / Cause of the issue

Use any Linux distribution, open TNO and  check the tech tree and Moskowien dissolution portraits.
Check if interface and character files are case-consistent. 

### Expected behaviour

I'd expect the GFX files to show up correctly

### Screenshots

![Screenshot from 2023-07-06 18-32-34](https://github.com/TNODevs/TNO-Bug-Tracker/assets/65721240/7bc7248c-e137-48cf-9daa-91893d0d5bd2)

**Comment by Sebastianroczz** [comment]
i dont think you should be playing this on linux skul

**Comment by intheworlditsgone** [comment]
Why not?

**Comment by runelead00** [comment]
The portraits are fixed, for any other broken GFX, you're going to have to be more specific about which ones

**Comment by grevyarlesp** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=3001814375 

I made an updated version for that, to fix the tech tree and the Guangdong GUI.

**Comment by runelead00** [comment]
> https://steamcommunity.com/sharedfiles/filedetails/?id=3001814375
> 
> I made an updated version for that mod, to fix the tech tree and the Guangdong GUI.

All fixes in the submod should be implemented, please report any similar issues that crop up in the future
