### ISSUE TITLE
Communist Komi - misstype "g" in focus "For Revolution Everlasting"

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2089]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

As shown below:
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/65ac0360-4038-4d33-970d-094e78331622)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
