### ISSUE TITLE
Philippines - Wrong spelling and stuff

### ISSUE THREAD

**Issue by ZawHawk** [TNODevs/TNO-Bug-Tracker#209]
**Questions**

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**
Wrong Spelling in Philippines
**Steps to Reproduce/Cause Issue:**

1. Go to Philippines

2. Read

Olongapo not Olangapo
Sorsogon not Sorsogen
(Sidenote, the city was called Bacon until the 2000s im not joking https://www.sorsogon.gov.ph/cool_timeline/bacon-the-oldest-municipality/)
Kanlurang not Kanrulan 

**Screenshots:**
![image](https://user-images.githubusercontent.com/90123868/142771136-b2e8eafa-18d3-4627-9727-e83ec61a80ed.png)

**Comment by Stormeagle449** [comment]
Fixed in dev build.
