### ISSUE TITLE
Communist Komi - Misstype in event "Concerning Nikolai Bukharin"

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2090]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Misstype of "he" before "We" in the middle paragraph of the event.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/01140e4d-3f53-4578-9304-c9b600c45282)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/341e5246-cb16-46da-86a7-7103a83dca0d)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
