### ISSUE TITLE
Suslov's Komi - Misspelled word "drafter"

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2091]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

In the focus "Revive the Economy" in Suslov's regional tree, the word "drafted" is misspelled as "drafter" in the last paragraph of the focus' description.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/4d89ac2c-89a0-4cde-85ce-0c42fe30da72)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/e708dc5c-5ebb-4677-b75e-08f802e4cd8c)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
