### ISSUE TITLE
USA - 'Our Dictator Wins' event gives proxy war lose voters effects instead of victory after pro-OFN Lubis wins the ICW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2095]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992570/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992571/game.zip)
[USA_icw_duumvirate_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992572/USA_icw_duumvirate_ends.zip)

### Describe the bug

After Lubis' duumvirate defeats the rest of the rebels during the Indonesian Civil War, the 'Our Dictator Wins' event pops out and the event gives a 'losing proxy war voters effects' instead of 'victory voters effects' because if Lubis wins, Indonesia joins the American sphere and OFN partner. And USA has an Indonesian Civil War victory cold war achievement. 

### Steps to reproduce / Cause of the issue

1. Indonesian Civil War triggers.
2. Indonesian Civil War takes too long.
3. Duumvirate in Indonesia.
4. Lubis takes control of the Indonesian government along with Suharto.
5. Lubis' duumvirate wins the Indonesian Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/99ee36e6-e6c5-4123-9324-a4faef925490)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c73ef5d3-a996-4263-85da-41b0cc62d864)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/faea9ddd-f8a7-4c31-99e2-5ff404543f47)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
