### ISSUE TITLE
USA - There is a placeholder event when Zulkifli Lubis' duumvirate wins the Indonesian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2096]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_icw_duumvirate_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992613/USA_icw_duumvirate_ends.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992614/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992615/game.zip)

### Describe the bug

After Lubis' duumvirate wins the Indonesian Civil War, there is a placeholder event about pro-OFN Indonesia victory and it has not been localized.

### Steps to reproduce / Cause of the issue

1. Indonesian Civil War triggers.
2. Indonesian Civil War takes too long.
3. Duumvirate in Indonesia.
4. Lubis takes control of the Indonesian government along with Suharto.
5. Lubis' duumvirate wins the Indonesian Civil War.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0252dd90-c686-430a-af97-ea4c1cf01c05)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
