### ISSUE TITLE
INS - "Zulfikli" instead of "Zulkifli" in the 'Peace in Indonesia' (Lubis' duumvirate victory) news event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2097]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_icw_duumvirate_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992623/USA_icw_duumvirate_ends.zip)

### List the loc issues below

1. There is the word "Zulfikli" in the 'Peace in Indonesia' news event instead of "Zulkifli". 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5fba64da-cb85-4948-894c-139ace063df9)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
