### ISSUE TITLE
INS - Doesn't rename to "Republic of Indonesia" after Duumvirate wins the Indonesian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2098]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992635/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992636/game.zip)
[USA_icw_duumvirate_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11992637/USA_icw_duumvirate_ends.zip)

### Describe the bug

When either Lubis or Suharto's Duumvirate wins the Indonesian Civil War, the INS tag doesn't change to "The Republic of Indonesia" just remains the 'Indonesian Government for National Salvation and Unity' tag name. 

### Steps to reproduce / Cause of the issue

1. Indonesian Civil War triggers.
2. Indonesian Civil War takes too long.
3. Duumvirate triggers in Indonesia.
4. Either Lubis or Suharto is in charge of Duumvirate Indonesia. 
5. Duumvirate wins the Indonesian Civil War.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6a038621-4a52-4cc5-9e0f-a4cc0cd2c43a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2de83c33-8f41-49dc-9b6a-e014539c9cac)

### Additional information

I have no other info.

**Comment by Marok132** [comment]
By the way it was fixed so you can close the issue.
