### ISSUE TITLE
USA - There is just 'Remove .' loc effect in 'Idealism Lost' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2099]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11994121/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11994122/game.zip)
[USA_cities_bankrupt.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11994126/USA_cities_bankrupt.zip)

### Describe the bug

When the 'Idealism Lost' event pops out, the event effect shows that there is a 'Remove .' loc, I don't know what that is. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Philip Hart.
3. Bankruptcy Crisis triggers.
4. Do not do anything with solving Bankruptcy Crisis. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/72ba4738-f29c-47cd-b44d-70b86329ece3)

### Additional information

I have no other info.

**Comment by Fortune801** [comment]
Fixed

**Comment by Stormeagle449** [comment]
Fixed for version 1.5.0
