### ISSUE TITLE
USA - Domestic Discontent 

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#210]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use:
Music Mod
- Were you using Steam?
Yes
- Which expansions do you NOT have?
I have all expansions

**Longer Description of Issue:**
My SAF Discontent doesn't seem to be going down even after I've finished pulling out of Africa
![image](https://user-images.githubusercontent.com/56777501/142771185-2783a109-ee42-4ae0-ba30-ff65928f2fd2.png)

The "Scars Health" timer doesn't seem to have much impact  
![image](https://user-images.githubusercontent.com/56777501/142771204-731427d6-0555-4825-9ae0-4febd2be68ce.png)

I think it's because by 1972 I have 700+ Discontent when the scale is really only supposed to go up to 100.
![image](https://user-images.githubusercontent.com/56777501/142771380-850baff5-4a74-40f9-a313-52a7e4ef75d3.png)

I know staying the Mandates too long is supposed to damage your society, but the Mandates only last tops 3 years. The US was in Vietnam far longer and in any case recovered from the worst of the protesting relatively quickly.

**Comment by thashepherd** [comment]
This happened to me as well. `remove_ideas USA_saf_war_insurgency_domestic_discontent_10` can help you ameliorate the effects for this playthrough.

**Comment by thashepherd** [comment]
Note that the above fix doesn't prevent "The Scars Heal..." from continuing to cycle.

**Comment by Stormeagle449** [comment]
Fixed for UB.
