### ISSUE TITLE
INS - There are still Japanese resource rights in Indonesia Borneo after pro-OFN Indonesia wins the civil war

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2100]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11994178/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11994179/game.zip)
[USA_icw_duumvirate_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11994180/USA_icw_duumvirate_ends.zip)

### Describe the bug

When the pro-OFN Indonesian faction wins the Indonesian Civil War, there are still Japanese resource rights in Indonesia Borneo remaining. 

### Steps to reproduce / Cause of the issue

1. Indonesian Civil War triggers.
2. The Indonesian Civil War takes too long.
3. Pro-OFN Indonesian faction wins the Indonesian Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6325da6b-fff4-4e63-854c-21c56f12e9ba)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
