### ISSUE TITLE
USA - 'USA_unlocked_Freshly_Paved_Road' is not localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2101]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11996522/USA_game.zip)

### Describe the bug

In the 'Driver Clubs' focus effect, there is a country_flag that has not been localized. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect NPP in the 1964 presidential election.
3. Elect Philip Hart (RDC-D) as the president in 1968.
4. See the 'Driver Clubs' focus effect. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f3c2f398-5117-4f04-b3cf-ae4a395a3605)

### Additional information

I have no other info.

**Comment by runelead00** [comment]
Fixed in Dev Build
