### ISSUE TITLE
RPS - Doesn't receive the OFN Partner after Republic of Sudan wins the Sudanese Civil War.

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2103]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14/1.13.5

### TNO version

1.4.1d/1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12002166/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12002169/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13307983/USA_play.zip)

### Describe the bug

When the Republic of Sudan won the Sudanese Civil War with the aid from USA, the Republic of Sudan didn't receive the OFN Partner while the Iraqi Republic had the OFN Partner due to USA supporting them. 

### Steps to reproduce / Cause of the issue

1. Italy remains independent.
2. The Oil Crisis triggers.
3. Middle Eastern conflict triggers.
4. Sudanese Civil War triggers.
5. the Republic of Sudan wins the civil war. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f9986f95-2d4a-4582-b364-861ff78c3724)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/01dd07e6-0b6a-4871-825f-c9239d590418)

### Additional information

I have no other info.

**Comment by Marok132** [comment]
It works intended because for getting a OFN partner you need USA_OC_participation should be equal 79 or more.
![image](https://github.com/user-attachments/assets/642717d2-f01d-49b3-95dc-5bf749f192ba)

**Comment by Ikidikid** [comment]
Oh, I didn't see that. I will play as USA again, do increase participation in OC and RPS wins the CW. Thanks for the tips.👍

**Comment by Marok132** [comment]
> Oh, I didn't see that. I will play as USA again, do increase participation in OC and RPS wins the CW. Thanks for the tips.👍

You're welcome. You can close this issue.

**Comment by Ikidikid** [comment]
Close this issue because RPS can join OFN observer if USA OC participation reached more than 79.
