### ISSUE TITLE
USA (Hart) - Starting focuses are blocked

### ISSUE THREAD

**Issue by Computer64** [TNODevs/TNO-Bug-Tracker#2105]
### Operating System

Windows 10

### HOI4 version

1.12

### TNO version

TNO v1.4.1d - Ugly American

### Do you have other mods in use?

Russian localisation, The Second West Russian War and Next Frontier

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[TNO_USA_Hart_shared.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/12008466/TNO_USA_Hart_shared.txt)
Fix this file.

### Describe the bug

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/92990434/87c6cb85-ebbd-488b-b2fe-40b60b870593)
First Hart focuses ("Some Lip Service" and "Saint of The Senate" are blocked because I have equal equal ratio of senators from the RDC and NPP.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/92990434/45fecfeb-d617-4a53-a0d4-1d080bfd9a60)
I looked code of focus tree and found that.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/92990434/abf0d508-b296-4e6e-b8ed-bf8831178939)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/92990434/24726a83-0b19-4dd4-816e-810c71490c39)
For this reason, I can't play normally without using the console until the next election in 1970 to shift the balance in the Senate.

This is a rather rare phenomenon - the equillibrium of parties in the Senate and perhaps you, the developers, did not take it into account. Ideally, in this case, there should be some third focus between the two mentioned above, or both of these focuses should be unlocked and the player will decide which one to take (in the second case, you need to write a condition - greater/less than or equal to, and not just greater/less than).

### Steps to reproduce / Cause of the issue

1. You need to get equillibrium in the Senate (49 senators from RDC and 49 senators from NPP). To do this without a console is very difficult and should be very lucky - you should get it in elections in 1968.
2. Go through Hart focus tree to "Some Lip Service" and "Saint of The Senate" and you will find that you can't go any further.

### Expected behaviour

I can't play further!!!

### Additional information

FIX THAT NOW!!!!

**Comment by runelead00** [comment]
Fixed in Dev Build, Saint of the Senate is now unlocked at equilibrium
