### ISSUE TITLE
WRRF - ComIntern stops working on founder annexation

### ISSUE THREAD

**Issue by ashbjohnson** [TNODevs/TNO-Bug-Tracker#2107]
### Operating System

Windows 11

### HOI4 version

1.12.14.50e7

### TNO version

1.4.1d

### Do you have other mods in use?

FPS Map

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

ComIntern interactions are unable to progress if its founder is annexed

### Steps to reproduce / Cause of the issue

1. As Irkutsk, unify Far East and establish the ComIntern.
2. As WRRF, unify West Russia and join the ComIntern through focus tree.
3. Far East loses war to Central Siberia and is annexed.
4. After the conclusion of the next vote in the ComIntern, no further actions can be taken and the ComIntern is essentially useless.

### Expected behaviour

Either another country can take helm of ComIntern or votes can continue without founder

### Additional information

ComIntern UI is still visible in decisions tab, but voting never ends for the measure on the table. This prevents any ComIntern votes from being started, including COMECON integration votes and military aid

**Comment by runelead00** [comment]
Fixed in Dev Build
