### ISSUE TITLE
USA Under Bennett - CTD when WAA wins over Cameroon

### ISSUE THREAD

**Issue by DaNmarkK** [TNODevs/TNO-Bug-Tracker#2108]
### Operating System

Fedora Linux 38

### HOI4 version

Avalanche v1.12.14.50e7

### TNO version

TNO v1.4.1d - Ugly American

### Do you have other mods in use?

Modifier Icons (https://steamcommunity.com/sharedfiles/filedetails/?id=2668048070)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12022634/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12022635/error.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12022636/system.log)
[https://drive.google.com/file/d/1lwrEcOkX3W2sKMAukox8D3-gjo4bpDcT/view?usp=sharing](https://drive.google.com/file/d/1lwrEcOkX3W2sKMAukox8D3-gjo4bpDcT/view?usp=sharing) I couldnt get the save to upload, so heres a google drive link

### Describe the crash

If i click the event about it OFN reforms it crashes, if i dont it still crashes.

### Steps to reproduce / Cause of the crash

Unpause and wait 2-3 ingame hours.

### Additional information

# Crash Information
AppName: HOI4 
AppVersion: Avalanche v1.12.14.50e7 
SCMBranch: stable 
SCMCommit: 50e7729985301286b1724fa42c5607723da2f37a 
SCMTimeStamp: "2023-05-17 10:33:13 +0000" 
DateTime: "2023-07-11 01:47:24 +0200" 
BuildType: Release 
Platform: Linux 
Architecture: 64-bit 
OperatingSystem: Linux 6.3.11-200.fc38.x86_64 x86_64 
SystemLanguage: unknown 
CPUModel: AMD Ryzen 5 5600X 6-Core Processor 
CPUSpeed: 4650 
CPUPhysicalCores: 6 
CPULogicalCores: 12 
SystemMemory: 31991 
LaunchArguments: --crash_data_log 
debug: 1 
DataChecksum: c7220105f428b57927d4475eabd3273b
AppChecksum: d41d8cd98f00b204e9800998ecf8427e
HasMods: true
Mods: Modifier Icons The New Order: Last Days of Europe
IsOldSave: false
LastRead: order_delete_command (1)
LastScript: common/scripted_effects/TNO_WestAfrica_Crisis_scripted_effects.txt:1080: clear_array

**Comment by runelead00** [comment]
Fixed in Dev Build
