### ISSUE TITLE
USA - LBJ Fractures the Party - Allow him or others to repair it

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#211]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use:
Music Mod
- Were you using Steam?
Yes
- Which expansions do you NOT have?
I have all expansions

**Longer Description of Issue:**
In LBJ.105 (caused by having 11 Exhaustion or basically finishing the top part of the Great Society tree) causes the Democrats to totally split from the RDs, which is meant to add to the challenge of playing R-Ds
![image](https://user-images.githubusercontent.com/56777501/142771674-d96974a1-3790-4479-bc1d-edc6aa35fd78.png)

![image](https://user-images.githubusercontent.com/56777501/142771738-b5b20379-ea1d-46fa-8e2e-d22762222edf.png)

The problem is this persists regardless how united the party is - I was 30 (the max) unity by the end of 1971. Also I backstabbed the NPP-Cs during the drafting of the Social Security Act, which creates further dissonance about how the R-Ds are supposed to shatter. Moreover, there's no way for the 1972 R-D presidents to fix this split, despite the fact that they are supposedly still voting together at least enough to share a party convention. 

The game loc sort of implies the Republican-NPP-C is meant to last longer than LBJ, but the gameplay does not support this. Robert McNamara is a democrat in-game and even after LBJ suffers from the Democrat break off he stays on LBJ's cabinet. Moreover the NPP-Cs will generally still be counted towards the NPP coalition.

To fix this I think one of 2 solutions could be implemented

Solution 1: 
1.) Have the event not removing the Ds and Rs voting together unless you previously chose to Break with the Democrats while drafting Social Security (the entire point of Unite the Party is to avoid this outcome)

Solution 2:
1.) LBJ should have a decision to coax the Democrats back into the R-D camp if he has sufficient party Unity (maybe 25)?
2.) Upon the election of the 1972 candidate, the R-Ds should reform and start voting together again

**Steps to Reproduce/Cause Issue:**

1. Fire LBJ.105 in console

**Screenshots:**

**Comment by ModdingAccount** [comment]
Changed in dev build.
