### ISSUE TITLE
niger - no leader portrait 

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#2110]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

v1.4.1d

### Do you have other mods in use?

Zizek's Ideology Bling and Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

after FMA wins the waw against PALF they invades Zarmaland  and put a no portrait leader guy

### Steps to reproduce / Cause of the issue

play the game 

### Expected behaviour

no leader portrait for france's niger 

### Screenshots

![20230713142244_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/b96cdfe3-a028-4bb2-8cc4-9dc74398fe29)

**Comment by runelead00** [comment]
Fixed in DevBuild
