### ISSUE TITLE
EGY - Two insurgents national spirits still exist despite the Egyptian government wins the civil war

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2117]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12080863/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12080864/game.zip)
[USA_middle_east_conflicts.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12080875/USA_middle_east_conflicts.zip)

### Describe the bug

When the Egyptian government(pro-Italian) wins the Egyptian Civil War, 'The Arab Socialist Union' and 'The Muslim Brotherhood' national spirits still existed despite pro-Italy Egypt defeating both Pan-Arabists and Islamists. 

### Steps to reproduce / Cause of the issue

1. Conflicts in the Middle East.
2. Egyptian Civil War triggers.
3. The Oil Crisis triggers.
4. Egyptian government(pro-Italy) victory.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bd148685-8b8c-461e-b564-0472bc4ede38)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2cc1d92b-1290-47c8-8342-bd3d9938fe62)

### Additional information

I have no other info.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
