### ISSUE TITLE
USA - 'Send Advisors to the 'supporting faction' Army' decisions appeared despite the supporting factions have the 'US Army Advisors' idea

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2118]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12080968/USA_game.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12080971/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12080972/game.zip)

### Describe the bug

When the 'supporting factions' have the 'US Army Advisors' national spirits during the Middle East conflicts after selecting the 'Send Advisors to the 'supporting faction' Army' decisions, the 'Send Advisors to the 'supporting faction' Army' decisions still appeared despite still having the 'US Army Advisors' national spirits. 

### Steps to reproduce / Cause of the issue

1. Middle East crisis triggers.
2. Iraqi Civil War triggers.
3. The Oil Crisis triggers.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/885eb31c-4345-41e5-929b-1f46d229014c)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d7ed1406-eec7-45f8-aab3-cb4916299234)

### Additional information

I have no other context about this.

**Comment by runelead00** [comment]
Fixed in Dev Build
