### ISSUE TITLE
USA - 'The Honolulu Accords' events have the NPP logo image instead of RDC logo due to RDC is in power of USA

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2121]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12094940/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12094941/game.zip)
[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12094950/USA_game.zip)

### Describe the GFX issue

When 'The Honolulu Accords' events are triggered, these events have the NPP logo in the event's image instead of RDC one because the RDC is in charge of USA. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. RDC becomes the current ruling party in the USA.
3. Doing the Treaty Port events.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7270c66b-ecf3-4866-b1c1-629579d08715)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d7f7b8e9-2d50-42ac-a7df-68372d7ce184)

### Additional information

I have no other context about this.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
