### ISSUE TITLE
SAF - Bugged scripted effect makes winning the referendum impossible

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2124]
### Operating System

Windows 10 Home

### HOI4 version

Avalanche 1.12.14

### TNO version

Ugly American 1.4.1d

### Do you have other mods in use?

Modifier Icons (TNO Version)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

The scripted effect for South Africa’s referendum campaigning (SAF_monarchy_support_change) is bugged. Whenever the player completes decisions and focuses that are supposed to improve monarchy support, they have no effect. Because of this, it is impossible to win South Africa’s referendum without either the country options menu or console commands.

### Steps to reproduce / Cause of the issue

How to fix:

1.  Open “TNO_SAF_scripted_effects.txt”
2. Scroll down to “SAF_monarchy_support_change” (line 165) 
3. At line 167, delete the IF function so that the relevant effect works when increasing referendum support.

### Expected behaviour

Decisions, focuses, and events should be able to actually improve referendum support.

### Screenshots

![SAF_referendum_bug](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/efeca175-800e-4b70-843f-12ddffed3225)

**Comment by runelead00** [comment]
Fixed in Dev Build
