### ISSUE TITLE
GER/JAP - Add 'Turkes Kenes' or 'Turkestan Reunification' in the cold war achievements

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2127]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest adding the 'Turkes Kenes' or 'Turkestan Reunification' in the cold war achievements for Germany and JAP when the aftermath of the Turkes Kenes. 

### Justifications

Because Germany and Japan have the proxy wars about the fate of Central Asia. So, that is why I suggest this. 

### Screenshots

Not needed.

### Additional information

I have no other context about this.

**Comment by runelead00** [comment]
Fixed in Dev Build
