### ISSUE TITLE
TRK - Anarchy 'Turkmen and Uzbek Territories' still has the economic 'Turkish Sphere'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2128]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12104673/USA_play.zip)

### Describe the bug

After the Turkestan Conference was disrupted and the governments of Turkmenistan and Uzbekistan collapsed, the 'Turkmen and Uzbek Territories' still has the economic 'Turkish Sphere' because the Turkmen Republic joined the Turkish Sphere before the conference. 

### Steps to reproduce / Cause of the issue

1. Sarry Karryev coups the communist government in Turkmenistan.
2. Turkmen Republic joins the Turkish Sphere. 
3. Turkes Kenes triggers.
4. Japan and Afghanistan have succeeded to disrupt the conference.
5. Turkmenistan and Uzbekistan governments collapsed. 

### Expected behaviour

Forgot to remove it, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/44d37ce9-23ec-4204-b4a0-bb4a71284080)

### Additional information

I have no other context about this.

**Comment by runelead00** [comment]
Fixed in Dev Build
