### ISSUE TITLE
International (I think) - Unable to Invest or pay debt

### ISSUE THREAD

**Issue by Imlitterallyhereforjustonemod** [TNODevs/TNO-Bug-Tracker#213]
**Questions**

- Operating System: Laptop
- HOI4 Version: 1.10
- TNO Version: TT (Patches not on)
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all expansions

**Longer Description of Issue:**
I was unable to interact with my debt or investments, even though I had money to spare to invest.

EDIT: I CAN PAY DEBT, I DIDNT HAVE DEBT AT TIME AND WAS ASSUMING I COULDNT PAY DEBT AS WELL

**Steps to Reproduce/Cause Issue:**
N/A

**Screenshots:**
![image](https://user-images.githubusercontent.com/71610183/142772779-10423603-20c9-45cb-bb93-7ee0aff254c0.png)

**Comment by Scarsoftime** [comment]
You can only invest into your GDP once a year.
