### ISSUE TITLE
USA - USA_active_police_activity is not localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2131]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12114602/USA_game.zip)

### Describe the bug

When I looked at the 'Topple the Planters' Empire' decision requirement, there is country_flag is not been localized. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Hart as the new president.
3. Doing 'Shining Megalopolis On A Hill' national focuses.

### Expected behaviour

Forgot to adding loc, I think

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/25fb272a-7931-4b2d-aa68-4955f7b984c5)

### Additional information

I have no other context about this.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
