### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Nasa-Space-Fanatic** [TNODevs/TNO-Bug-Tracker#2132]
### Operating System

Windows 11

### HOI4 version

Avalanche 1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

The Moe Order, Modifier GUI, The Moe Order: Waifu Himmler, The New Order: Cheat Mod++, TNO: Economic Cheat, TNO: Second West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

All Major Expansions EXCEPT WTT.

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12114581/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12114584/error.log)

### Describe the crash

I loaded my autosave to find an icon with a question mark labeled "Transitioning to Guerilla Tactics." and pressed play, I've done this multiple times so I know when the hour hits exactly 1968, December 1st, **04:00**, it crashes. It doesn't crash upon loading or playing by itself, but by the hour.

### Steps to reproduce / Cause of the crash

Unsure of how this can be reproduced outside of my situation, will try to give best steps.
1. Have Steam Hoi4 encounter a syncing error
2. Enter the game despite that to delete old saves, I used an autosave that saved on 1968, December 1st, 02:00
3. Press play, first crash occurs.
4. Hoi4 no longer shows syncing error after a period of time, reload game
5. Should encounter the question mark icon with "Transitioning to Guerilla Tactics"
6. Press Play and wait for clock to reach 04:00
7. Game will crash upon reaching the hour.

### Screenshots

![image_2023-07-20_155130627](https://github.com/TNODevs/TNO-Bug-Tracker/assets/140122238/a4955fa9-2c34-4af3-b11f-29c85b27949f)
![image_2023-07-20_155140456](https://github.com/TNODevs/TNO-Bug-Tracker/assets/140122238/bbcccd8c-db2b-4b66-8506-7f594bb678a4)
![image_2023-07-20_155548942](https://github.com/TNODevs/TNO-Bug-Tracker/assets/140122238/72351722-65ce-4e8d-b4de-abcd86e470ef)

### Additional information

Note: An error like this has not occurred using the same mods as I've used aside from Second West Russian War and The Moe Order: Waifu Himmler, for which this is my first time using them. My best guess is it has to do with something regarding the WAW that is occurring. Thank you for any help you may provide.

![image_2023-07-20_155813864](https://github.com/TNODevs/TNO-Bug-Tracker/assets/140122238/de6daecd-4154-402e-a070-846fb317ba01)

**Comment by runelead00** [comment]
Did you enable any mods mid-game cause any change/addition to certain files causes this issue

**Comment by Nasa-Space-Fanatic** [comment]
> Collaborator

No, nothing comes to mind, I didn't add any other mods to my library nor activate any of the ones already downloaded.

**Comment by Nasa-Space-Fanatic** [comment]
Just noticed I closed this on accident, my apologies.
