### ISSUE TITLE
USA - Missing Culture Icons

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#2133]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

v1.4.1d

### Do you have other mods in use?

Zizek's Ideology Bling and Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

tennessee, kentucky and florida has missing culture 

### Steps to reproduce / Cause of the issue

look at tennessee, kentucky and florida cultures

### Expected behaviour

missing cultures

### Screenshots

![20230721211635_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/abc640f5-a8e7-443f-ab59-383056fd8e48)
![20230721211633_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/456e8ea2-f5a5-4af0-bf99-0f201db6e1e7)
![20230721222519_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/90670338-3b8f-4310-b0bb-b5c92ff2ca2a)

**Comment by unluckychip** [comment]
sorry if someone have report all ready I did look

**Comment by runelead00** [comment]
Fixed in Dev Build
