### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by AAAAZZZXDE** [TNODevs/TNO-Bug-Tracker#2135]
### Operating System

Windows 11

### HOI4 version

1.12.4

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I observe a country this thing pops up and it's pretty annoying

### Steps to reproduce / Cause of the issue

So I observe any country and that pops up

### Expected behaviour

I expect for me to just observe and not that thing popping up

### Screenshots

![thing](https://github.com/TNODevs/TNO-Bug-Tracker/assets/140222359/084f715c-2468-46b8-ab0a-5bb1a2e9e2c6)

**Comment by runelead00** [comment]
Appearance of tab more limited but still needed for AI to work properly
