### ISSUE TITLE
guangdong - ai does not send experimental division 

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#2136]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

v1.4.1d

### Do you have other mods in use?

Zizek's Ideology Bling and Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

 ai does not send experimental division 

### Steps to reproduce / Cause of the issue

 ai does not send experimental division 

### Expected behaviour

 ai does not send experimental division 

### Screenshots

![20230722145730_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/63649e23-0de2-407d-9816-63f14ddd8f7a)
![20230722145733_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/a79b9f6d-b696-4555-bbf3-92c74ebe5e28)
![20230722150107_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/d0a3190c-5e29-41df-bbb2-9a69b30859fd)

**Comment by runelead00** [comment]
Can't adjust ai to only send the right division
