### ISSUE TITLE
ITA - Short Description of Issue

### ISSUE THREAD

**Issue by RyanLoil** [TNODevs/TNO-Bug-Tracker#2137]
### Operating System

Windows 11

### HOI4 version

1.12.14.50e7

### TNO version

1.4.1d

### Do you have other mods in use?

TNO(CN ver.), Chinese translation mod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12138534/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12138535/game.log)

### Describe the bug

In Decisions - Ente Nationale Idrocarburi, some decisions are empty with description text and not funtioning at all. It looks like they were generated by the regions which had status changing from "Unknown Reserve" to "Small Reserve Discovered" but not sure .

### Steps to reproduce / Cause of the issue

1. Go to Decisions  - Ente Nationale Idrocarburi
2. Try click all the decisions which is avaliable
3. Some of them may generate these empty decision.

It could also have a condition that the effected countries were not belong to ITA or its colony anymore.

### Expected behaviour

Close Ente Nationale Idrocarburi when all the decisions are done

### Screenshots

<img width="396" alt="image" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/50242494/24d77a35-5042-4382-9c0a-5ee7bfba7e38">

**Comment by runelead00** [comment]
Fixed in Dev Build, decisions are now fire_only_once
