### ISSUE TITLE
Console commands when typed in the console aren't showing up, but they are working

### ISSUE THREAD

**Issue by LtRomanov** [TNODevs/TNO-Bug-Tracker#2138]
### Operating System

Windows 10

### HOI4 version

Latest version

### TNO version

Latest version 

### Do you have other mods in use?

Radio TNO and Second West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I open console in game and try to type commands the letters aren't showing so I need to memorize what I typed. The commands are working, but even when the Enter is clicked and the command is enabled console is not showing that command is enabled or what command is used. It's just blank.

### Steps to reproduce / Cause of the issue

1. Open console
2. Type any command
3. If the letters of the command are showing then the bug isn't there

### Expected behaviour

The console commands should show when typed in console

**Comment by runelead00** [comment]
2WRW Issue
