### ISSUE TITLE
United States - Losing West African War causes Societal Breakdown

### ISSUE THREAD

**Issue by captainrex75** [TNODevs/TNO-Bug-Tracker#214]
**Questions**

- Operating System: macOS Monterey
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use: Music mods
- Were you using Steam? Yes
- Which expansions do you NOT have?
Death or Dishonor, Together for Victory, Battle for Bosphorous
**Longer Description of Issue:**
I did not take many decisions to intervene in the West African Crisis as I wanted to save up political power for LBJ's Great Society. I had withdrawn from the OFN mandates as well. However, when the Cameroonian African state won, not only did I lose 20% stability and 200 political power, but I got slammed with the "Domestic Discontent-Societal Breakdown" national spirit and it's absolutely crippling my LBJ run.
**Steps to Reproduce/Cause Issue:**

1. Play as LBJ's America

2. Win South African War completely and set up mandates

3. Completely stay in mandates, causing extremely high domestic discontent (is there a way to withdraw early? It's kind of frustrating to be sucked into this)

4. Withdraw from mandates when mandates decolonize; national discontent goes away

5. Take only a few decisions that escalate the West African war, but nothing really comes from it.

6. Lose West African war and get hit with crippling domestic discontent national spirit again. 

![20211121130206_1](https://user-images.githubusercontent.com/51009600/142773701-fe9ee722-788a-4835-8e3d-8fc2ba4216de.jpg)

**Comment by runelead00** [comment]
No longer an issue in UB
