### ISSUE TITLE
Italy - Atlantatropa still mentioned in focus

### ISSUE THREAD

**Issue by x1ce** [TNODevs/TNO-Bug-Tracker#2142]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Focus "Right's for Refugees" still mentions Atlantropa despite its removal.

### Steps to reproduce / Cause of the issue

1. Click "New Game"
2. Choose "Italian Empire"
3. Click "Start"
4. Go to focuses
5. Click focus "Rights for Refugees"
6.  Read description

### Expected behaviour

No Atlantropa 

### Screenshots

![Screenshot 2023-07-26 180010](https://github.com/TNODevs/TNO-Bug-Tracker/assets/64276473/ee2cf9c7-6b78-4469-8f6c-8020cd9ff161)

**Comment by x1ce** [comment]
Mentioning of "reclaimed adriatic lands" also included in event attached to focus

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
