### ISSUE TITLE
USA - No Command Power

### ISSUE THREAD

**Issue by AnarchoNerd** [TNODevs/TNO-Bug-Tracker#2144]
### Operating System

Windows 11

### HOI4 version

1.12.14.50e7

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After clicking the "Send American Military Advisors" decision for the Haitian Civil War, I was afflicted with -1.75 command power gain, one which persisted after the end of the Haitian Civil War and which prevented me from gaining any command power throughout the rest of the game.

### Steps to reproduce / Cause of the issue

1. Play as America
2. Click the "Send American Military Advisors" button in the Haitian Civil War 
3. Hover over command power gain to see

### Expected behaviour

I expected the malus to disappear after the end of the conflict.

### Screenshots

![Screenshot 2023-07-29 105406](https://github.com/TNODevs/TNO-Bug-Tracker/assets/140903130/4f80d803-7236-44be-b1c0-2a65aaf95b50)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/140903130/5c2f9c68-204f-4d2d-811b-0c5bf5812a0a)

**Comment by runelead00** [comment]
Fixed in Dev Build
