### ISSUE TITLE
USA - AI Hart never uses Oil Crisis decisions

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2146]
### Operating System

Windows 10 Home

### HOI4 version

Avalanche v.1.12.14

### TNO version

Ugly American 1.4.1d

### Do you have other mods in use?

Modifier Icons (TNO Version), Zizek’s Ideology Bling, TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

When the Oil Crisis hits for an AI-controlled Hart presidency, the computer never uses any of its Oil Crisis decisions. Given that Hart is the only president that doesn’t use focuses to tackle the Oil Crisis, this bug leaves him much weaker than other American presidents.

### Steps to reproduce / Cause of the issue

How to fix:
    1. Open “TNO_USA_decisions.txt”
    2. Scroll down to “USA_HART_OIL_CRISIS_CAT” (line 1472) 
    3. From lines 1484 to 1690, note that each decision doesn’t have any `ai_will_do` values attached.
    4. Add a high `ai_will_do` value so the AI will prioritize these decisions first.

### Expected behaviour

Philip Hart, if played by the AI, should at least make an effort to tackle the Oil Crisis, especially since one of the decisions costs no Political Power.

### Screenshots

![HartOilCrisisBug](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/dc005055-4a2e-4302-a812-6e90f40fe896)
![HartOilCrisisBug2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/f29535a7-c2a1-46e3-94c5-6a6db0d3e59c)

### Additional information

In addition, the Amtrak decisions do not have any `ai_will_do` variables either, despite costing only 25 PP each. This ends up debilitating an AI-run USA, since these Amtrak decisions would have lowered the starting Oil Crisis modifier if they were taken beforehand.

**Comment by Stormeagle449** [comment]
Fixed for 1.5.0
