### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by CursedAuroran** [TNODevs/TNO-Bug-Tracker#2147]
### Operating System

Manjaro Linux

### HOI4 version

1.12.4

### TNO version

v1.4.1d

### Do you have other mods in use?

The New Order: Operation Deep Freeze, TNO: Next Frontier

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The define for the song Backroom Deal is broken due to wrong capitalization in tno_soundtrack.asset resulting in it not being played, and breaking the ingame music until you skip it.

### Steps to reproduce / Cause of the issue

1. Enter a game
2. Let the music play until it stops
3. Check music player for which song it says its on

### Expected behaviour

The song should play ingame and not break the music player

### Screenshots

![Screenshot_20230804_204101](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/298d18ec-6c95-4938-858a-86720e59e6bd)
![Screenshot_20230804_204055](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/b9dde5b7-adf1-416a-95b4-7037038444dc)

**Comment by CursedAuroran** [comment]
I realised I screenshotted the wrong define, here is the correct one
![Screenshot_20230804_204239](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/cbae7ca7-db2c-463d-8a28-fec76b14462f)

**Comment by CursedAuroran** [comment]
The OFN main theme also appears  to be missing entirely from the defines, even tho the music file is present in the mod
![Screenshot_20230804_210210](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/df77b56b-28e1-4714-8201-2cfbca25e505)
![Screenshot_20230804_210024](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/a16e53f7-1713-4a6a-98dc-84a6706502d7)

**Comment by runelead00** [comment]
Fixed Backroom Deal, OFN main theme is already properly in-game, just not in that file because of base-game code reasons
