### ISSUE TITLE
All countrys - Short Description of Issue

### ISSUE THREAD

**Issue by ToxicEP** [TNODevs/TNO-Bug-Tracker#2148]
### Operating System

Windows 10

### HOI4 version

1.12.14.50e7

### TNO version

1.4.1d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

https://drive.google.com/file/d/1lq9qUPZuwWBXCoJqkl42nkyXg5mhL2tl/view?usp=drive_link

### Describe the crash

when starting the game with any country crashes

### Steps to reproduce / Cause of the crash

starting the game with any country crashes

**Comment by ToxicEP** [comment]
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12313694/error.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12313696/system.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12313698/code_revisions.log)

**Comment by runelead00** [comment]
Merged into #962
