### ISSUE TITLE
All Countries - Ghosts Of The Street song breaks music player

### ISSUE THREAD

**Issue by CursedAuroran** [TNODevs/TNO-Bug-Tracker#2149]
### Operating System

Manjaro Linux

### HOI4 version

1.12.4

### TNO version

v1.4.1d

### Do you have other mods in use?

The New Order: Operation Deep Freeze, TNO: Next Frontier

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The song Ghosts In The Streets is broken due to wrong capitalization in the music define for it

### Steps to reproduce / Cause of the issue

1. Go into a game
2. Allow the music player to play until it suddenly stops
3. Check which song should be playing

### Expected behaviour

The song should play ingame and not break the music player

### Screenshots

![Screenshot_20230806_021427](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/11985691-02ae-41a9-9fa1-5f5215ca2821)
![Screenshot_20230806_021420](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/881c8c9e-8ae5-47b6-b7a2-f134894e3c64)

**Comment by runelead00** [comment]
Fixed in Dev Build
