### ISSUE TITLE
Haiti and Domincan Republic - Custom Game Rules bugged

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#2150]
### Operating System

Windows 11

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

2WRW, Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12287397/game.log)

### Describe the bug

Custom Game Rules supposed to set for Cantave to coup Haiti after Communist Putsch succeeds in DR, then Anti-Radical coup would occur in DR and Magloire would counter-coup Cantave.

However, Lopez didn't get deposed instead after Cultural Revolution, Lopez reverted his ideology from Amazonism to Guevarism, and the Domincan Cultural Revolution national spirit was reverted into Domincan People's Revolution. Also, no coup occurred in Haiti and Dejole remained in power.

### Steps to reproduce / Cause of the issue

1. Set Custom Game rules to be set for Cantave coupling Dejole in Haiti and Magloire counter-couping Cantave.
2. Set Custom Game rules to be set for Communist Putsch to succeed after Revolutionary Front wins, and Tavarez to launch anti-radical coup against Lopez.
3. Wait till 1965.

### Expected behaviour

Magloire leads Haiti in the end and Tavarez to coup Lopez in DR.

### Screenshots

![Screenshot (1765)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/96382658/4cedfc6b-05f7-4b1e-ac4b-70a090a3adfc)
![Screenshot (1766)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/96382658/71644b04-b419-4ba3-ab03-c44eb9230925)
![Screenshot (1799)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/96382658/687308e5-09ad-47ba-8398-31609f70a25f)

**Comment by runelead00** [comment]
DR's anti-radical coup fixed. Please read the name of the Magloire counter-coup gamerule
