### ISSUE TITLE
United States of America - Broken Command Power after the end of the WAC

### ISSUE THREAD

**Issue by CursedAuroran** [TNODevs/TNO-Bug-Tracker#2151]
### Operating System

Manjaro Linux

### HOI4 version

1.12.4

### TNO version

v1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Following the end of the WAC the United States of America will have negative command power production if the US provided any military advisors to the US aligned faction during the WAC

### Steps to reproduce / Cause of the issue

1. Start a game as the USA
2. Open console and enter debug
3. Start the WAC, any scenario works
4. When possible send military advisors
5. Once the decision ends and the military advisors are actually sent, end the WAC, for the clearest picture I would recommend doing this after the second military advisors decision
6. Check your Command Power gain

### Expected behaviour

Positive Command Power production after the WAC

### Screenshots

![Screenshot_20230808_162421](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/3053a9dd-399c-49a8-8752-2340678cd47d)

**Comment by runelead00** [comment]
Fixed in Dev Build
