### ISSUE TITLE
CTD on game startup

### ISSUE THREAD

**Issue by Nomad6553** [TNODevs/TNO-Bug-Tracker#2153]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12306124/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12306125/game.log)

### Describe the crash

regular load until 'creating resentment' then an instant CTD without a 'not responding' popup or even a crash reporter afterward.

### Steps to reproduce / Cause of the crash

no system, hoi4, or steam updates to speak of, the discord mentions no problems so i have no idea how to replicate this crash.

### Additional information

Mod was working fine yesterday but today it has begun crashing for n discernable reason, none of the error logs or the exception folder display any type of fatal error.
the only thing displayed within the exception folder is: Unhandled Exception E06D7363 (UNKNOWN EXCEPTION) at address 0x00007FFE65824C3C

Stack Trace: 
and nothing else

**Comment by Nomad6553** [comment]
after keeping task manager open while loading the game ive found that cpu usage and memory spike at a certain point in the startup, the cpu goes to 100% usage which may cause the crash.
however this doesnt explain why this is suddenly happening today,

**Comment by runelead00** [comment]
Meged into #961, all I can recommend is trying some of things there, or potentially do a clean reinstall of Hoi4 and TNO
