### ISSUE TITLE
Jamaica - Remaind in Federation after Coup

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#2154]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12318764/game.log)

### Describe the bug

After US AI rejects Jamaican Independence Referendum few in-game years ago, news event showed "Bloodless Coup in Jamaica" but Jamaica still isn't independent and remained in West Indies.

### Steps to reproduce / Cause of the issue

1. US AI to reject Jamaican independence bid
2. Wait till 1970.

### Expected behaviour

Jamaica to be independent, Social Nationalism ideology, not part of OFN.

### Screenshots

![Screenshot (1848)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/96382658/38fedcec-922f-4bee-9ebf-51c5849e1a2e)

**Comment by runelead00** [comment]
Fixed in Dev Build
