### ISSUE TITLE
HAI - Duvalier "wins" the Haitian 1964 "election" even if PPLN already has turned Haiti red

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2155]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Chinese Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Duvalier sometimes may "win" the Haitian 1964 "election" after PPLN crashed the government, and this will grant red Haiti 2 Duvalier's national spirits.

### Steps to reproduce / Cause of the issue

1.Go to custom paths
2.Set "PPLN crashes the government"
3.Wait

### Expected behaviour

Duvalier DO NOT win the RED HAITI'S election

### Screenshots

![Duvalier](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/8fd1f664-9714-4dbb-a04a-9c29f9339ae4)

**Comment by runelead00** [comment]
Fixed in Dev Build
