### ISSUE TITLE
BRA - Compilation of Brazil typos

### ISSUE THREAD

**Issue by SirJaguar** [TNODevs/TNO-Bug-Tracker#2158]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

https://imgur.com/a/2kVWQHs

**Comment by runelead00** [comment]
Fixed in Dev Build
