### ISSUE TITLE
Germany - "An Atlantic Battleground" Description and numbers missing

### ISSUE THREAD

**Issue by Guslaff** [TNODevs/TNO-Bug-Tracker#2159]
### Operating System

Windows 10 Home

### HOI4 version

1.12.14

### TNO version

1.4.1

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The entire description section of the "An Atlantic Battleground"-Tab in the "Global Conflicts"-Tab is replaced by the placeholder GER_IBC_desc. This includes the numbers and statistics. All decisions are visible and can be taken. 

### Steps to reproduce / Cause of the issue

1. As Speer-Germany, go to Foreign Policy 
2. Select the "Global Conflicts"-Tab 
3. Select the "An Atlantic Battleground"-Tab 
4. See issue

### Expected behaviour

The descriptions and stats/numbers should be there.

### Screenshots

![MissingDescription](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142436065/9ce84cb1-3432-4e69-879f-016c65482e9c)

### Additional information

This problem occured twice now. I started a new game after it occured for the first time, but it occured again. I also reinstalled the Mod once. I continued playing the game in the second try. (I also took some of the decisions in the affected tab.)
I don't know if this issue can be reproduced. As far as I'm concerned, I didn't do anything special that could have led to the issue. 
I don't know if this issue also appears when playing the US. 
I don't know if the other german paths have the same problem.

**Comment by runelead00** [comment]
Fixed in Dev Build
