### ISSUE TITLE
Omsk - Random crashing due to AI doing an "invalid command"

### ISSUE THREAD

**Issue by VibeChecker5** [TNODevs/TNO-Bug-Tracker#2160]
### Operating System

macOs

### HOI4 version

1.12.14

### TNO version

1.4.1

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12362312/error.log)

### Describe the crash

The game freezes for around ten seconds before crashing. 

### Steps to reproduce / Cause of the crash

I am not entirely sure how to reproduce/fix this crash, as this has happened several times before on entirely random dates, but it seems it has something to do with the AI. 

### Screenshots

N/A

### Additional information

N/A

**Comment by runelead00** [comment]
That happens all the time and it's not the cause of a crash. See #1509 , mid-game crash reports are useless with game.log or save files prior to the crash
