### ISSUE TITLE
An Atlantic Battleground - England Proxy Description Bugged.

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#2161]
### HOI4 version

1.12.13

### TNO version

1.4.1d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/be6c52bc-cb8d-40c0-960e-8cc94b8c8366)

**Comment by runelead00** [comment]
Fixed in Dev Build
