### ISSUE TITLE
game crashes after it loads

### ISSUE THREAD

**Issue by Ryan-marcus** [TNODevs/TNO-Bug-Tracker#2162]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

v1.4.1d

### Do you have other mods in use?

no i dont have others mods

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

N/A

### Describe the crash

when i press play and the game load, it immediately crashes

### Steps to reproduce / Cause of the crash

game loads
i press play single player
the game loads then it crashes

### Screenshots

![Screenshot 2023-08-17 160911](https://github.com/TNODevs/TNO-Bug-Tracker/assets/104573558/fe85600c-6cc8-4ba8-bfa2-1642ab29b089)

**Comment by runelead00** [comment]
Merged onto #962
