### ISSUE TITLE
French State - Ultranationalist France uses base version of the flag.

### ISSUE THREAD

**Issue by Lorcomax** [TNODevs/TNO-Bug-Tracker#2164]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

the flag used for the French State with Ultranationalist ideology, such as the OAS coup path for Pinay uses, is the IRL modern French flag, instead of using the correct. historical Vichy France flag. Since all other versions use it, I assume it is a bug.

### Steps to reproduce / Cause of the issue

1. starta game as the French State.
2. use debug options
3. select the debug decisions "Post-FWB Setup", "Pinay Debug", and "OAS Coup"
4. Look at the flag

### Expected behaviour

The flag to appear to be the correct one.

**Comment by runelead00** [comment]
Fixed in Dev Build
