### ISSUE TITLE
USA - CIA can't send military aid to Russian unifiers except Omsk and Magadan

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2165]
### Operating System

Windows 10 Home

### HOI4 version

Avalanche v.1.12.14

### TNO version

Ugly American 1.4.1d

### Do you have other mods in use?

Modifier Icons (TNO Version), TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

This bug has been around since Toolbox Theory. Prior to that update, a player-led USA was able to send military aid and equipment to regional unifiers in Russia, and even choose which side to support once the Russian regional and superregional wars begin. Right now, there is a flaw in the scripted triggers that prevent the CIA from sending military aid to any Russian nation, except the Black League and Magadan.

### Steps to reproduce / Cause of the issue

Cause of the issue:
    1. Activate debug mode
    2. As an example, tag to Tomsk and Magadan, and use the Region Unification debug decision.
    3. Tag to USA, wait a few in-game days, and look at the CIA tab. Notice that you only have the option to send covert aid to Magadan.
    4. Trigger event ‘USA_RUS_CIA.13’, and notice that there’s no option to support Tomsk instead of Magadan.

How to fix:
    1. Open “TNO_RUS_scripted_triggers.txt” in the scripted_triggers folder
    2. Scroll down to ‘RUS_is_CIA_sponsored’ (line 1244)
    3. From lines 1286 to 1315, change the code so that, for example, if the player wants to support Central Siberia, it requires `NOT = { has_country_flag = RUS_CIA_backing_FST }` instead of `has_country_flag = RUS_CIA_backing_CSB`.

### Expected behaviour

The player should be able to give covert military aid to Russian unifiers that are not ultra-militaristic death cults nor fascist dictatorships pretending to be a democracy.

### Screenshots

![20230820081721_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/05ae592e-7659-48cd-ba5e-aa370af1f394)
![20230820081737_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/70571794-e85e-43a3-a258-26d0e1bbca12)
![CIA_Critical_support_Fix](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/00b00120-a829-41bd-80f8-439a884dc7da)

### Additional information

Prior to Toolbox Theory, the ‘RUS_is_CIA_sponsored’ scripted trigger didn’t require the country flags that designate which faction the CIA supports. The update was likely done to cut down on extra decisions in the Intelligence category.

The problem is that there is no way to add the relevant country flags in order to support the countries in question. The event options that are supposed to add the country flags don’t show up, since the buggy trigger `RUS_is_CIA_sponsored` is also part of the event choices.

**Comment by runelead00** [comment]
Fixed in Dev Build
