### ISSUE TITLE
Lemberg Province Culture status

### ISSUE THREAD

**Issue by ItsLeoneq** [TNODevs/TNO-Bug-Tracker#2166]
### HOI4 version

Avalanche v.1.12.14

### TNO version

Ugly American 1.4.1d

### Describe your suggestion

Lemberg was mainly Polish city with only 15% of its population being Ukrainian so I suggest changing Lemberg (Lwów) province culture from Polish-Ukrainian into Polish with slightlyUkrainian minority

### Justifications

Historical accurancy

**Comment by runelead00** [comment]
Intended, the city is significantly more Ukrainian than 1931 in TNOTL due to German occupation policy in the region, was going to be elaborated on in original Poland plans

**Comment by ItsLeoneq** [comment]
https://upload.wikimedia.org/wikipedia/commons/e/ea/1931_Census_of_Poland%2C_Miasto_Lwow_%2C_table_10_Ludnosc-Population-pg.11.jpg
In 1931 the amount of Ukrainians in Lvov was 25k
And amount of Poles was almost 200k
So you're saying that Ukrainians multiplied by 10 times magically in pure culturally Polish city?
