### ISSUE TITLE
Democratic Italy (Nenni) - Infinite "Battle for Italy"

### ISSUE THREAD

**Issue by Iron-Chancellor2** [TNODevs/TNO-Bug-Tracker#2167]
### Operating System

Windows 10

### HOI4 version

1.12.13

### TNO version

v1.4.1d "Ugly American"

### Do you have other mods in use?

radio_tno

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When becoming Nenni (with Liberal Coalition), the Battle for Italy first starts normally, but once every issue was chosen and set, the event simply keeps going and substracts independence score every time, though no new issue can be chosen (since all are already decided on), and so far, it does not seem to end.

### Steps to reproduce / Cause of the issue

See above.

### Expected behaviour

Once every issue was settled, the decision of Italy's international fate will be decided (Join OFN/Sphere or stay independent) WITH all effects from the issues

**Comment by runelead00** [comment]
Without log data and a save game prior to things breaking, we can't do much to fix this, we haven't had any reports other than yours, both internally and externally

**Comment by VoyteckGit** [comment]
I had a similar problem, unfortunately I don't have any logs (I gave up on the game). I also noticed that the US AI does not have the option to release Ciano's diaries, even if they have more influence than Japan.

**Comment by Speederzzz** [comment]
Save File:
[ITA Broken BFI.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12910660/ITA.Broken.BFI.zip)
Logs:
[logs ITA broken BFI.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12910669/logs.ITA.broken.BFI.zip)

Happy to send more if needed

**Comment by runelead00** [comment]
Believe this is fixed in dev build now
