### ISSUE TITLE
Government of National Salvation lacking content, requires bug fixes

### ISSUE THREAD

**Issue by Clickaholic0081** [TNODevs/TNO-Bug-Tracker#2168]
### Operating System

Windows 11

### HOI4 version

Avalanche v1.12.14.50e7

### TNO version

1.4.1d

### Do you have other mods in use?

Ayden George Remix Radio, ENA Jams, Radio TNO: Music of the New Order, The Full Minecraft Soundtrack, TNO: Last Waltz Expanded, TNO Lullabies of Europe, 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, BBA

### Files

[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12438829/autosave.zip)

### Describe the bug

I was playing as West Alaska/ United States of Siberia/ United States of Russia, sending mercenaries to the Government of National Salvation, helping them conquer Iberia when after the war was won I noticed that their puppets had generic leaders and no content, not even a unique puppet status. The worst of all of the puppets was the Spanish puppet, which didn't even have a country name.

### Steps to reproduce / Cause of the issue

1. Iberian War starts
2. GNS wins the war

### Expected behaviour

A functioning peace deal

### Screenshots

![Hearts of Iron IV (DirectX 11) 8_24_2023 5_15_17 AM](https://github.com/TNODevs/TNO-Bug-Tracker/assets/112770738/f9a136cd-3f88-4100-a9f7-810a4d9d452e)

**Comment by runelead00** [comment]
Fixed in Dev Build
