### ISSUE TITLE
"Expo 67 Opens in Montreal" and "Canadian Centurium" happens multiple times in different times

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#217]
Operating System: Windows 10
HOI4 Version: latest one
TNO Version: latest one
Any other mods in use: no
Were you using Steam?: Yes
Which expansions do you NOT have?: Only have Waking the Tiger DLC

**Screenshots:**
Note the date at the top right, that's when all of these popped up. Also was going down the LBJ path if that makes any difference.

![Screenshot (68)](https://user-images.githubusercontent.com/84231463/142774431-23a14237-8829-4c51-97b4-dc2397eaf72e.png)
![Screenshot (73)](https://user-images.githubusercontent.com/84231463/142774455-d61be498-a662-49b7-93b8-5d2b024c5173.png)
![Screenshot (74)](https://user-images.githubusercontent.com/84231463/142774492-2d5462e2-133d-4060-9a2c-7001231a89c6.png)
![Screenshot (79)](https://user-images.githubusercontent.com/84231463/142774506-f355d6df-744d-44be-92c8-2599cf66e6e6.png)
![Screenshot (82)](https://user-images.githubusercontent.com/84231463/142774515-d901d46e-fa7c-43c9-8c3a-3a772fb54b21.png)

![Screenshot (70)](https://user-images.githubusercontent.com/84231463/142774588-47ba122b-b587-4b46-84b1-75e42b1d30f6.png)
![Screenshot (77)](https://user-images.githubusercontent.com/84231463/142774606-0e3e2d7c-4ddf-453b-b79f-903478ed137a.png)
![Screenshot (78)](https://user-images.githubusercontent.com/84231463/142774612-10fef053-55d3-456b-abf8-9613b10322b2.png)
![Screenshot (80)](https://user-images.githubusercontent.com/84231463/142774622-83dacd9d-1033-4871-9522-fb63ade4a0dd.png)
![Screenshot (81)](https://user-images.githubusercontent.com/84231463/142774634-71d6cf80-4479-4b85-bf70-6b0b172a2b13.png)
![Screenshot (83)](https://user-images.githubusercontent.com/84231463/142774642-8fc02ff6-b97f-4518-9405-6ef2ea176784.png)

**Comment by runelead00** [comment]
Fixed in Current Release
