### ISSUE TITLE
ITA - No bio description and sub-ideology alignment for starting government advisers

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2172]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When I looked at the starting Italian government advisers' bio description, I saw none, and three government advisers have no sub-ideology alignment.  

### Steps to reproduce / Cause of the issue

1. Play as ITA.
2. See the political advisers' bio description.

### Expected behaviour

Forgot to add them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/002dcfda-da81-47e6-9630-296bdd8a87ba)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in dev Build
