### ISSUE TITLE
BRG - Double "his" in 'Operation Bodyguard' description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2173]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[BRG.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12554069/BRG.zip)

### List the loc issues below

1. There is a double "his" in the 'Operation Bodyguard' description from the Investigation GUI about Degrelle. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5c108027-2034-4535-bc1e-017d22a31196)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
