### ISSUE TITLE
Magadan - Purchase American Tanks does nothing

### ISSUE THREAD

**Issue by dlabrique** [TNODevs/TNO-Bug-Tracker#2176]
### Operating System

Mac Big Sur

### HOI4 version

1.12

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the Werbell path for Magadan, you can buy equipment from the USA using political power. All of the other equipment decisions work, but buying tanks results in getting nothing.

### Steps to reproduce / Cause of the issue

1. Pick Magadan
2. Go down Werbell path and pro-america subpath
3. Get american support for your regime to very high, unlocking the ability to buy Jets and Tanks (jets works fine)
4. Try to buy tanks, you spend 100 PP but receive nothing

### Expected behaviour

It should give me tanks.

### Screenshots

<img width="1440" alt="Screen Shot 2023-09-14 at 2 31 56 AM" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/102992137/b09cf036-2391-4647-bf3b-cb5445a1f15d">

**Comment by runelead00** [comment]
Fixed in Dev Build
