### ISSUE TITLE
Belize getting Calling Lotts Bluff event causing crash to desktop

### ISSUE THREAD

**Issue by attardw** [TNODevs/TNO-Bug-Tracker#2180]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

N/A

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I currently do not have the log files as I'm posting this for a friend (unimportant but I'm a software engineer and he asked for help), however, they shouldn't be needed, I believe, because we were able to deduce the issue, we're just unsure why it was happening and what files to look in.

I will post the log files, in an edit, at a later date, or have my friend post them if they are required, for now, I'll type the last thing in the logs that gave us our start from memory.

"Character indexed with BRA_Quadros_hog when not associated with BLZ"

or something of the like.

### Describe the crash

After starting the launcher and clicking resume, or starting the game and going to saves, we get into the game. The last save is 7 days from the crash date Dec 10, it happens, every time, at 2:00 a.m. on Dec 17 (unfortunately I can't remember the year but I think it was 1984??? (If needed I can ask and edit)).

So to make a long story short, after looking through the files and finding nothing, we decided to test switching to Brazil and waiting for the crash, then switching to Belize and waiting for the crash. My friend is playing as the United States. 

As the United States and Brazil, we get to 2:00 am on Dec 17 (1980 something I believe) and the game just immediately crashes. As Belize though, at 2:00 am on Dec 17, they get the _**Brazilian**_ event Calling Lotts Bluff, and the game _**does not crash**_ as long as we don't "accept" the event (click whatever block of text that closes the event). As soon as we do, the game crashes in the same manner. Hence the error log output.

Belize has already finished almost all of its event chains we believe, it has no head of government and only one minister (cant remember his name, if it helps I'll ask). As well as, Calling Lotts Bluff already happening for Brazil. We found that either removing the event Calling Lotts Bluff or removing the events file for Belize fixes the issue and allows for continued play, for how long I have no idea. As I have the feeling doing either will cause issues in the future.

I don't think the issue lies with the Brazilian Calling Lotts Bluff event and instead lies inside of the events file for Belize. We had looked in both event files for Brazil and Belize and found no mention of a _**direct**_ call to the Calling Lotts Bluff event in Belize's event file. My best guess is that since Belize is calling some sort of skeleton function, the issue lies there. Granted I have no idea, as we have no file for any skeleton functions for Belize, like there is with Brazil. _**Again, It shouldn't be an issue with Calling Lotts Bluff itself, but the fact that its being called a second time by a country that it shouldn't be.**_

My friend has no issues with just removing either and continuing play but as a fellow developer, I thought at the least you'd like to know about the issue as well as what we've tried and found. Just trying to pass the word along, give a heads-up, and try to help as best I can. Love modding communities as they prolong the life of a game indefinitely.

### Steps to reproduce / Cause of the crash

1. Somehow manage to get Belize to finish up to event number 7 we think in the event files, where they have no head of government and only 1 minister.
2. Brazil should already have done the Calling Lotts Bluff event.
3. Wait??? until Belize randomly gets the event.... We have no idea what is calling the "Calling Lotts Bluff event" for Belize. unless it has something to do with the BLZ_Skeleton_7.t call, which is the event (off the top of my head), that procs when belize has no head of government, 1 minister, and a few other preReqs.

### Screenshots

N/A until I get on his Pc again, if needed let me know.

### Additional information

I know the stereotype of an issue with no logs but try not to get hung up on that fact, please. The logs were short compared to most others that I've seen, and from the looks of it, nothing seemed to be out of order besides the last message mentioned above.

If more information is needed, anything in the paranthesis above or the logs, let me know and ill go ahead and get them.

Thank you for reading, keep up the good work, I'm not a HOI4 player but have been recently interested in trying it because of my friend.

**Comment by runelead00** [comment]
Sound like a file getting corrupted/updated on your end mid-game on your end, error on user end
