### ISSUE TITLE
USA - 'Begin Close-Air Sorties' and other commencing PPI decisions are not shown

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2181]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12640695/USA.zip)

### Describe the bug

When the Caribbean Legion commenced the invasion, the 'Begin Close-Air Sorties', sending American advisors and other decisions are not visible due to selecting only the Prepare Close-Air Sorties decision and not including the Prepare USN Naval Support decision to be selected.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Puerto Plata Invasion triggers.
3. Select the Prepare Close-Air Sorties decision in PPI before it commences its invasion.
4. PPI begins. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/492effe3-c0d3-427f-909e-3815eaed0ff5)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dcd23ebf-4e34-48e7-bffd-3addac019ffc)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Adjusted several decisions, otherwise mostly WAD
