### ISSUE TITLE
USA - There is an "observer" word instead of "partner" or "OFN partner" in Razak wins in Malayan election event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2182]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12641772/USA_play.zip)

### List the loc issues below

- [ ] 1. In the 'Out of the Japanese, In Comes the OFN' event description, there is an "observer" word instead of "partner" or "OFN partner" because the OFN Observer is renamed to OFN Partner in the Ugly American update.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/536efa29-a915-4336-8f0a-22cd3c7082f0)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
