### ISSUE TITLE
USA - 'Dominican Assistance Increases' decision appeared despite the Haitian Civil War is not yet trigger

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2184]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12641973/USA.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12641974/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12641975/game.zip)

### Describe the bug

When the Red Revolution in the Dominican Republic happened after the revolutionaries won the civil war, the 'Dominican Assistance Increases' decision appeared despite the Haitian Civil War not yet triggered and this decision can appear again after the decision time out. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI triggers.
3. The Caribbean Legion defeats Trujillo.
4. Dominican Revolutionaries won the Civil War.
5. Red Revolution in the Dominican Republic success.
6. López seize control.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aa2cea50-dd67-48f8-8b4c-ed77e7068007)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7745c1fa-75ce-4188-bf04-65dbea0e4792)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
