### ISSUE TITLE
USA - 'Helping Out a Friend' and 'Break Open the Caches' national focuses should be bypassed when the English(British) Civil War triggers

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2185]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Describe your suggestion

I would like to suggest that the 'Helping Out a Freind' and 'Break Open the Caches' national focuses should be bypassed if the English(British) Civil War triggers or ends. 

### Justifications

Because these operation decisions after completing the 'Helping Out a Freind' and 'Break Open the Caches' national focuses can appear if the English(British) Civil War is not triggered. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e32497c5-04ec-4701-84af-7d24ecd18139)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a0ba13d0-d9bc-44a9-a64d-f43fa9e79411)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
