### ISSUE TITLE
Guangdong - CCL Logo Not Appearing

### ISSUE THREAD

**Issue by T3RR5V0N** [TNODevs/TNO-Bug-Tracker#2188]
### Operating System

CachyOS Linux

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

2nd West Russian War, Next Frontier, Loading Screens Redone, Loading Screens Revised and Improved

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the GFX issue

The CCL logo is not visible, and I can't interact with it

### Steps to reproduce / Cause of the issue

1. Play Guangdong
2. Wait until the Guangdong Riots happen, and you can interact with the GFT and the CCL
3. Check Decisions

### Expected behaviour

Both the GFT and CCL logos should be visible

### Screenshots

![20230917134043_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/56271791/fb433a91-ae89-41fa-8a3b-e604710a0ba4)

**Comment by T3RR5V0N** [comment]
I forgot to mention, I was playing as Morita's Guangdong, but I don't think this bug is exclusive to Morita

**Comment by runelead00** [comment]
Fixed in Dev Build, would recommend downloading https://steamcommunity.com/sharedfiles/filedetails/?id=3001814375 until next update
