### ISSUE TITLE
DOM - There is a word "Spain" instead of "Iberian Union" in the Balaguer Victory in the Dominican Civil War event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2189]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### List the loc issues below

- [ ] 1. The 'Balaguer Victorious in the Dominican Civil War' event says about "Spain" word instead of "Iberian Union" or "Iberia" because the Iberian Union is not yet dissolved. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c51acc3d-492b-4829-8b7b-611de9d2d039)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4c66d97b-5980-49c1-ab32-c07f905d461c)

### Additional information

Not needed.

**Comment by Stormeagle449** [comment]
Fixed for version 1.5.0
