### ISSUE TITLE
AI Speer's Germany - AI Speer will not annex Bohemia

### ISSUE THREAD

**Issue by reginaldtheI** [TNODevs/TNO-Bug-Tracker#219]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Lastest
- TNO Version: Latest
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Playing as Buryatia, AI Speer has puppeted, but not annexed Bohemia, locking it out of the rest of the decisions to restore order in Europe

**Comment by runelead00** [comment]
Fixed in Current Release
