### ISSUE TITLE
CZE - Wehrkreis XIX is not in German economic sphere despite being puppet of Germany

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2191]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12672753/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12672754/game.zip)

### Describe the bug

When either Bormann, Speer or Heydrich wins the German Civil War and Bohemia survives due to siding with either of the German faction, Bohemia is not in the German economic sphere. 

### Steps to reproduce / Cause of the issue

1. Adolf Hitler appoints Bormann as the successor.
2. Bormann convinces Bohemia to join his side.
3. German Civil War triggers.
4. Bohemia sided with Bormann.
5. Bormann wins the German Civil War with Bohemia survives.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/67e24c31-9ff1-4585-9bb1-4416f8357e15)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/684dc4f5-5b74-4b5d-ae90-1f056f462a19)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
