### ISSUE TITLE
USA - 'Integrate the Support' national focus should be bypassed if the German Civil War triggers

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2192]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest the 'Integrate the Support' national focus should be bypassed if the German Civil War triggers.

### Justifications

Because the decision after completing the 'Integrate the Support' national focus would not have been available if the German Civil War started.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4a1318bd-2270-4cc4-b34a-5d2df975ef02)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Added in Dev Build
