### ISSUE TITLE
BRA - AI doesn't doing the South Africa War decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2193]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12673621/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12673623/game.zip)
[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12673626/USA.zip)

### Describe the bug

AI Brazil didn't do anything with the South Africa War decisions during the South Africa War and didn't move its ships to the Gulf of Guinea and Angola Basin which means unable to unlock the 'Operation Curtain Call' decision. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tag except Brazil.
2. Play through mid-1964.
3. The South Africa War triggers.
4. Switch to Brazil through the console.

### Expected behaviour

Probably forgot to add AI interaction with the South Africa War decisions, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/495ce35c-d989-4f6c-9ee7-4d6984dff3dc)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/481dc339-9bb5-4487-ba29-0d7f95d5f3b2)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build, Curtain Call now has a ai bypass for trigger since we can't modify AI like that
