### ISSUE TITLE
USA - 'Support Political Reform' decision is somehow unlocked despite the violence is above 0

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2194]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678119/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678120/game.zip)
[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678131/USA.zip)

### Describe the bug

When the Haitian Civil War is ongoing, the 'Support Political Reform' decision is somehow unlocked despite the violence is above 0 or more than 0 because the decision is required to have violence is below 0.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Lavaud coups in Haiti.
4. Select the second option from the Lavaud event as USA.
5. Haitian Civil War triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/28351531-992b-4a43-9d53-2e088d321716)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
