### ISSUE TITLE
USA - The (second) PPLN Activity Rises decision time is always available then complete and so on until the violence is above 33%

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2195]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678291/USA.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678301/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678302/game.zip)

### Describe the bug

The (second) PPLN Activity Rises decision time is always available then complete, and so on and so forth until the violence is above 33% in the Haitian Civil War global conflict.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Lavaud coups in Haiti.
4. Select the second option from the Lavaud event as USA.
5. Haitian Civil War triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3712cc5f-5404-4f07-af4f-a4850969ba0e)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Haiti overhauled for the Ruin, issue not longer relevant
