### ISSUE TITLE
USA - I receive 'Victory' event after Dominican Revolutionary Front wins the Civil War despite previously supporting Balaguer

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2196]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678741/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678742/game.zip)
[USA_support_Balaguer_lost.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12678745/USA_support_Balaguer_lost.zip)

### Describe the bug

Despite USA support for Balaguer during the start of the PPI ceasefire and Balaguer's loss to the Dominican Revolutionary Front, I received a 'Victory' event instead of a losing event due to siding with Balaguer. The event should be like this `HIS_PP_ceasefire.3` event to be popped out. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI triggers.
3. PPI ceasefire triggers.
4. USA chose to support Balaguer.
5. PPI ceasefire tension critical.
6. The Dominican Civil War triggers. 
7. Dominican Revolutionary Front wins the Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/798405b9-b860-4303-b7ef-39ff04ddeced)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5f16e854-3e89-4f65-b095-c1785364d26c)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
