### ISSUE TITLE
USA - There is no number before the percentage about anti-Trujillo insurgency in PPI's operational strength

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2197]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_PPI_started.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12679838/USA_PPI_started.zip)

### Describe the bug

When the Puerto Plata Invasion landing started, there is no number before the percentage of anti-Trujillo insurgency in PPI's operational strength from the PPI global conflict. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI triggers.
3. PPI landing.

### Expected behaviour

Probably forgot to add it.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ca4bf0fb-c0b2-4ac2-a7ce-caa77aa0a1fd)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
