### ISSUE TITLE
USA - I receive the pre-UA update 'Victory' event instead of USA supported Legion victory(UA update) event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2198]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

When USA continued to support the Legion during the beginning of the PPI ceasefire and the Legion(Dominican Revolutionary Front) victory in the Dominican Civil War, I received the pre-UA 'Victory' event instead of the `HIS_PP_ceasefire.6`(Smoke Receiver) event.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI triggers.
3. PPI ceasefire triggers.
4. USA chose to support the Dominican Revolutionaries.
5. PPI ceasefire tension critical.
6. The Dominican Civil War triggers.
7. Dominican Revolutionary Front wins the Civil War.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f515ab3a-1693-4672-8df4-df6d5c3041bf)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
