### ISSUE TITLE
N/A - Custom Game Rules Still Has "Strengthen Omolon" Slider

### ISSUE THREAD

**Issue by Ngp-3** [TNODevs/TNO-Bug-Tracker#220]
**Questions**

- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: Terra e Libertà

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [ ] 1. On the `Major Nation Buffs` section of the Custom Game Rules tab on the startup screen, there is a slider named `Strengthen Omolon` at the very bottom, even though it and the other four Siberian wasteland tags were removed with the release of Toolbox Theory.
![image](https://user-images.githubusercontent.com/78689657/142776885-0e4d60da-d627-4456-a8fe-b35a3d4719f3.png)

**Comment by runelead00** [comment]
Updated to make it more clear it affects the Father
