### ISSUE TITLE
USA - 'Breaking the Pariah State' national focus should be bypass if the PPI ceasefire triggers

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2200]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest the 'Breaking the Pariah State' national focus should be bypassed if the PPI ceasefire triggers.

### Justifications

Well, the 'Breaking the Pariah State' national focus effect gives increased intelligence strength and dissidents. However, these effects are only targeting Trujillo but when the ceasefire happens, this national focus effect is somehow useless against Balaguer. So, that is why I suggest this. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/537598f3-d289-4ceb-b6b2-ed3e109ef04d)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7fb3c1b1-11e1-4a86-a5e1-0c869c9fea86)

### Additional information

Game and error logs:
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12680387/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12680388/game.zip)
Save game: 
[USA_PPI_started.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12680390/USA_PPI_started.zip)

**Comment by runelead00** [comment]
Fixed in Dev Build
