### ISSUE TITLE
DOM - 'Accelerated Training' national spirit has no unique GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2201]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[IBR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12683068/IBR.zip)

### Describe the GFX issue

The 'Accelerated Training' national spirit has no unique GFX icon for the Dominican Republic.

### Steps to reproduce / Cause of the issue

1. PPI triggers.
2. Trujillo is ousted and the PPI ceasefire triggers.
3. USA continues to support the Legion.
4. Iberian Union selects Balaguer's decisions.

### Expected behaviour

Forgot to add GFX icon, i think. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c8af7f3a-6fa3-4081-af87-198ff32ac44c)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
