### ISSUE TITLE
USA/DOM - 'Balaguer Victorious in the Dominican Civil War' says about navigate its relationship with USA despite USA supports the Legion previously and lost

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2203]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_support_legion_lost.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12683429/USA_support_legion_lost.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12683437/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12683439/game.zip)

### List the loc issues below

- [ ] 1.  After USA supported the Legion have lost the Dominican Civil War, the description of the 'Balaguer Victorious in the Dominican Civil War' says about navigating its relationship with USA despite USA and DOM are still hostile with each other.  
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b9a1d715-3591-4a0a-9deb-d17d98249221)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/33bd7312-9464-490f-a807-49c0900bc5f9)

### Additional information

Not needed.

**Comment by runelead00** [comment]
WAD, Dominican Republic will still need to navigate its very negative relationship with USA, they can't just ignore the superpower on their doorstep
