### ISSUE TITLE
YUN/JAP - NPA's "new" ROC doesn't have claims on Taiwan regions except Taipei

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2205]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

Chinese Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

NPA's ROC should claim the whole Taiwan,but it only has a claim on Taipei

### Steps to reproduce / Cause of the issue

1.Play as Yunnan
2.Play as NPA and win The Great Asian War
3.Wait until Sun Fo establishes a "new" ROC
4.ROC has no claims on most of the Taiwan regions

### Expected behaviour

ROC claims the whole Taiwan Island

### Screenshots

![UI](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/0ecb779e-388b-4a12-ae35-37a4475c157c)
![taipei](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/0a0b454d-e765-4453-a35a-e8276b489478)
![Hearts of Iron IV (DirectX 9) 2023_9_22 15_05_37](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/656945f8-5b37-4ee7-81e1-4bad2b37f805)
![Hearts of Iron IV (DirectX 9) 2023_9_22 15_05_41](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/cbface79-e5d1-4791-9049-b9c24e3f3350)
![Hearts of Iron IV (DirectX 9) 2023_9_22 15_05_46](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/d74ff1a8-7945-41bc-98b6-fc363ad9f77b)
![Hearts of Iron IV (DirectX 9) 2023_9_22 15_05_54](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/0313f82c-eb76-41aa-b6b5-239e1a629d5e)
![Hearts of Iron IV (DirectX 9) 2023_9_22 15_05_59](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/f2f700ee-bf8e-4a3f-b787-adb783810552)
![Hearts of Iron IV (DirectX 9) 2023_9_22 15_06_05](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/76a4a09a-dec9-4285-8259-c4f2b0db6f2c)

**Comment by Stormeagle449** [comment]
Fixed for The Ruin update.
