### ISSUE TITLE
SAF/BOR/GRO/ANG/COG - 'Unconventional Tactics' national spirit still exist despite the SAW is over

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2207]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12699318/GER.zip)

### Describe the bug

Despite the South Africa War ending, the participants of the SAW still have the 'Unconventional Tactics' national spirit and didn't remove it.  

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. SAF taking the Unconventional Tactics focus.
3. South Africa War ended.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/19bb5cd3-a846-48a6-bf62-6ef7e22f298b)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/09333687-5ee6-4994-bd81-fa0aaeda264a)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
