### ISSUE TITLE
GER/GRO - No Hassel's fascism party popularity increased in Großafrikanischer Reichsstaat after GCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2208]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[HGR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12699478/HGR.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12699482/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12699483/game.zip)

### Describe the bug

When the German Civil War ended after the Großafrikanischer Reichsstaat and the Afrika Cabal formed, there is no increase Hassel's fascism party popularity in Großafrikanischer Reichsstaat. Even after selecting the GER's Afrika Cabal's decisions to increase strength (fascism) in Hüttig's Afrika, it doesn't increase the fascism party popularity in Großafrikanischer Reichsstaat.

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Chose Heydrich.
3. South Africa War triggers.
4. South Africa War ended, Afrika-Schild survived.
5. Großafrikanischer Reichsstaat is formed.
6. Win the Garman Civil War as Heydrich.
7. Cabal against Hüttig global conflict appears.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/db39f362-76c2-4c24-846b-caea984907df)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0c4099cc-0537-4bf7-a010-594bf175b266)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Updated GRO piechart to have von hassel's party displayed
