### ISSUE TITLE
Brazil - Reduce buffs for the economy

### ISSUE THREAD

**Issue by betletel** [TNODevs/TNO-Bug-Tracker#221]
**Description of Suggestion:**
Try to reduce "gdp growth" and "inflation reduction" in the Brazilian focus tree. 

**Reasoning Behind Suggestion:**
Brazil reached a point where in 1966 had a real gdp growth of 25.8 % (and the avarage for the other years was 23%). Not even OTL China ever obtained such a high gdp growth rate.

**Additional Information:**
I did Lacerda path (I don't know if this is the reason), but I think that Brazil is generally unbalanced when talking about economics.
![20211121214726_1](https://user-images.githubusercontent.com/94806378/142779172-499c4456-181e-4fea-adeb-0454129914b5.jpg)

**Comment by Stormeagle449** [comment]
This is gonna change in future updates.
