### ISSUE TITLE
GER - Karl Dönitz, Johannes Steinhoff and Karl Hanke portraits are not shown in the Nuclear Struggle GUI

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2211]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_ss_cw.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12705409/GER_ss_cw.zip)

### Describe the GFX issue

In the Nuclear Struggle GUI, the portraits of Karl Dönitz, Johannes Steinhoff, and Karl Hanke do not appear. 

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Chose Heydrich as the Fuhrer successor.
3. Heydrich won the German Civil War.
4. SS Civil War(2nd GCW) triggers.
5. See the Nuclear Struggle GUI. 

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b6c59bc3-3f69-46a2-a016-923709e5fe27)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/55ab1e9c-c0d3-4f41-8d97-9338d8c2f0bf)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8a5cf475-03c6-483f-9093-c69c85fd98bd)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
