### ISSUE TITLE
USA - 'Public Demands Disengagement!' decision is not unlocked despite the requirements are met

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2212]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12707376/USA.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12707379/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12707380/game.zip)

### Describe the bug

The 'Public Demands Disengagement!' decision is not able to be unlocked despite the requirements are involvement and weariness are 100.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Haitian Civil War triggers.
4. Have the involvement and weariness are 100 or above in HCW.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f1a6305f-bf96-4a86-8309-68925d5252a0)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/251c5488-fea9-474a-8bda-b7ddcac104c7)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/519a2b3a-5818-467e-95db-fff913550fd9)

### Additional information

Not needed.

**Comment by runelead00** [comment]
No longer relevant with Haiti changes for UB
