### ISSUE TITLE
USA/SAF/BRA/CAN/AST/NZL - 'Control the Sky' national spirit doesn't get removed after the SAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2213]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_saw_ceasefire.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12707971/USA_saw_ceasefire.zip)

### Describe the bug

When the South Africa War ended, the OFN and OFN-aligned members who participated in the SAW still had the 'Control the Sky' national spirit and hadn't gotten removed. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. Elect any of the 1964 presidents.
4. Has the South Africa War tree.
5. Choose the Escalate the Air War focus.
6. End of the South Africa War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/cbc91ce9-18ad-4535-92ce-fae923858aa5)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/90d01778-d0fe-4dae-890d-54868ef28a0f)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c7288be1-0ab2-4464-8651-6b9828941179)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/822f1322-6208-4b25-8388-132db0459ebd)
![Image_5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e1096c25-2948-46ce-87e7-120ecaf185cc)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
