### ISSUE TITLE
USA/DOM - 'Heavy American Bombing' and 'Heavy American Naval Bombardment' national spirits do not their unique GFX icons

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2214]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12708610/USA_game.zip)

### Describe the GFX issue

When the Haitian Blitz triggers, Dominican Republic has no unique GFX icons for 'Heavy American Bombing' and 'Heavy American Naval Bombardment' national spirits. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Haitian Civil War triggers.
4. Border tension between Haiti and the Dominican Republic triggers.
5. Haitian Blitz triggers.

### Expected behaviour

Forgot to add GFX idea icon, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5bcfb9f0-044f-4d91-b531-b96b783f8380)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f864c711-7b6d-479b-b2e5-c8d07bb5e9d2)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dc69ca76-9ca9-445d-9277-8d630f4e49f4)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
