### ISSUE TITLE
DOM - Trujillo doesn't include to declare war on PPLN when the Blitz starts

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2217]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_trujillo_blitz.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12709809/USA_trujillo_blitz.zip) Recommend to run the game

### Describe the bug

When the Haitian Blitz started, Trujillo's Dominican Republic only declared war on Haiti, not including to declare on PPLN. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Haitian Civil War triggers.
4. Border tension between Haiti and the Dominican Republic triggers.
5. Haitian Blitz triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a73a02dc-6980-4324-9fe6-9a55381d3642)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e8aa9e17-c80e-4723-9964-bb756685dd89)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
