### ISSUE TITLE
USA - The Haitian Blitz doesn't switch back to the Haitian Civil War global conflict after the Ceasefire in Hispaniola

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2218]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12709899/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12709900/game.zip)
[USA_blitz_haiti_holds.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12709904/USA_blitz_haiti_holds.zip)

### Describe the bug

When the Haitian Blitz occurred, and then the Ceasefire in Hispaniola was triggered due to Haiti still holding and either Haiti reoccupying Hinche or the Dominican Republic holding in Hinche, the Haitian Blitz didn't switch back to the Haitian Civil War global conflict.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Haitian Civil War triggers.
4. Border tension between Haiti and the Dominican Republic triggers.
5. Haitian Blitz triggers.
6. Haiti reoccupies Hinche.
7. DOM is unable to push through and the Ceasefire in Hispaniola triggers. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5b6b5e65-f7f3-46a6-9a33-b8e854e537c0)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/36ad063f-7968-45bf-99be-6aaa595ca55c)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
