### ISSUE TITLE
USA - Operation budget doesn't decrease when selecting the 'Increased Presence in the Siberian National Republic' decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2219]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12712944/USA_game.zip)

### Describe the bug

When selecting the 'Increased Presence in the Siberian National Republic' operation decision, the operation budget doesn't decrease. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Magadan wins against the contenders during the Smuta in East Siberia.
3. 'Increased Presence in the Siberian National Republic' operation decision available.
4. Select operation decision. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2d3275cc-17fa-4090-b606-d2f58f9be199)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2b43e9b5-e705-4e19-b9cb-7a849a8bb28a)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
