### ISSUE TITLE
DOM - Doesn't rename its capital to 'Santo Domingo' after Haiti defeats Trujillo in the Haitian Blitz

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2220]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12713329/USA_game.zip)

### Describe the bug

After Haiti defeats the Dominican Republic and the Trujillo regime is overthrown in the Haitian Blitz, 'Ciudad Trujillo' is not renamed to 'Santo Domingo'. 

### Steps to reproduce / Cause of the issue

1. Trujillo wins the PPI.
2. Haitian Civil War triggers.
3. Border tension between Haiti and the Dominican Republic triggers.
4. Haitian Blitz triggers.
5. Haiti wins against the Dominican Republic and Trujillo is overthrown. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b48cbd24-a6d0-4000-b0f5-a9c774f3d07b)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
