### ISSUE TITLE
DOM - Inter-American Peace Force still has the negative opinion from other Carribean countries despite Trujillo overthrown

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2221]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12713781/USA_game.zip)

### Describe the bug

After Trujillo was defeated by Haiti in the Haitian Blitz, Trujillo's regime was overthrown and establishing the Inter-American Peace Force in DOM, DOM has still a negative opinion of DOM from other Caribbean nations like USA, Haiti, West Indies Federation, Cuba and Venezuela. 

### Steps to reproduce / Cause of the issue

1. Trujillo wins the PPI.
2. Haitian Civil War triggers.
3. Border tension between Haiti and the Dominican Republic triggers.
4. Haitian Blitz triggers.
5. Haiti wins against the Dominican Republic and Trujillo is overthrown.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/da1f36cb-0562-4364-87f7-2db44047c035)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/341bad60-2d17-4de5-a30a-c0346366c492)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c123a8c8-db52-4aec-b7a3-5fb5c0f34edc)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
