### ISSUE TITLE
DOM - Trujillo's political advisers didn't remove or replace after Haiti defeats Dominican Republic in Haitian Blitz

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2222]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12713991/USA_game.zip)

### Describe the bug

After Trujillo and his regime were defeated in the Haitian Blitz and replaced by the Inter-American Peace Force, Trujillo's political advisers are still there and didn't get removed or replaced. 

### Steps to reproduce / Cause of the issue

1. Trujillo wins the PPI.
2. Haitian Civil War triggers.
3. Border tension between Haiti and the Dominican Republic triggers.
4. Haitian Blitz triggers.
5. Haiti wins against the Dominican Republic and Trujillo is overthrown.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/23d81db6-1452-44db-9cf7-7efa990b2a10)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a2b2be20-f128-487b-90eb-c231570cb467)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
