### ISSUE TITLE
DOM/HAI - 'Ceasefire in Hispaniola' news event triggers despite Trujillo is beaten and overthrown after the Haitian Blitz

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2223]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12720304/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12720305/game.zip)
[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12720306/USA_game.zip)

### Describe the bug

After Trujillo is defeated and overthrown by Haitian and American forces during the Haitian Blitz, the 'Ceasefire in Hispaniola' news event is somehow triggered.

### Steps to reproduce / Cause of the issue

1. Trujillo wins the PPI.
2. Haitian Civil War triggers.
3. Border tension between Haiti and the Dominican Republic triggers.
4. Haitian Blitz triggers.
5. Haiti wins against the Dominican Republic and Trujillo is overthrown.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/59c49761-9cc7-4901-ac4c-496e763ba207)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
