### ISSUE TITLE
USA - There is a [USA.GetLeader] in Joseph Raseta's description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2224]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_left_madagascar.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12721411/USA_left_madagascar.zip)

### Describe the bug

In the bio description of Joseph Raseta, there is an unlocalized `[USA.GetLeader]`.

### Steps to reproduce / Cause of the issue

1. Second Malagasy Uprising triggers.
2. Malagasy Rebels wins.
3. PADESM wins in Madagascar.
4. FIPIMA takes control in Madagascar.
5. See bio description of Joseph Raseta.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/27a9fe4d-b825-4f9f-a94f-ac20f256b4ba)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
