### ISSUE TITLE
USA/DOM/HAI - Some bugs after Trujillo wins the Haitian Blitz

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2225]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_haiti_fall.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12722469/USA_haiti_fall.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12722429/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12722430/game.zip)

### Describe the bug

- After the Dominican Republic defeated Haiti and annexed it during the Haitian Blitz, The Haitian Civil War in the Cold War achievement for USA is still ongoing instead of going 'Total Defeat'.
- Despite the Dominican Republic's total victory and the end of Haiti in the Haitian Blitz, the 'Ugly American' flavor events are still there.
- When running the game after the outcome of the Haitian Blitz of favoring the Dominican Republic, Haiti tag pops out, rejoins the OFN, declares the Haitian government won the Haitian Civil War events, and the 'Ceasefire in Hispaniola' news event triggers.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Haitian Civil War triggers.
4. Border tension between Haiti and the Dominican Republic triggers.
5. Haitian Blitz triggers.
6. Trujillo wins the Haitian Blitz.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7b7868c4-1c52-465b-ad39-165a92978df6)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2afd05fc-315a-4f9b-8b4a-1eae5009ce05)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8707fd3c-0511-4adf-a982-19ea22457e65)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8e76126f-d39b-44a5-8d08-25ba16fe7932)
![Image_5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ac9fbefe-7d66-4893-a0aa-651376f6fb75)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
