### ISSUE TITLE
SAF - 'Iberian Counterinsurgency Units' national spirit is still existing despite the end of the SAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2226]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_saw_ceasefire.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12724946/USA_saw_ceasefire.zip)

### Describe the bug

After the South Africa War, South Africa still has the 'Iberian Counterinsurgency Units' national spirit. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. The Iberian Union supports South Africa.
4. End of the South Africa War.
5. South Africa exists.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/411ad71d-b308-4b1d-bd39-2c2e7e0ff02f)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
