### ISSUE TITLE
USA/HAI - There is no Haitian Government Victory in Haitian Civil War event after Haiti defeats PPLN

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2227]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12726015/USA_game.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12726021/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12726022/game.zip)

### Describe the bug

After Haiti defeated the Haitian Revolutionary Front due to the PPLN-organized uprising triggered, there are no events popped out about the Haitian Government's Victory in the Haitian Civil War, and the Haitian Civil War in USA's Cold War achievement is still marked as an 'Ongoing'.  

However, during the PPLN-Haitian Government war, the Haitian Revolutionary Front was suddenly annexed by the Haitian government without a capitulation event.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Haitian Civil War triggers.
4. Trujillo invades Haiti and the Haitian Blitz triggers.
5. Haiti defeats the Dominican Republic and Trujillo is overthrown.
6. The Haitian Revolutionary Front declares war on the Haitian government.
7. Haitian government defeats PPLN.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/09349cb2-00af-4a09-ab4d-9db499e5cd63)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/de4ae1f6-5e16-43d4-960a-35717f4aa2ac)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
