### ISSUE TITLE
USA - Change the GFX icon of 'States' Militia' national spirit

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2228]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Describe your suggestion

I would like to suggest changing the GFX icon of the 'States' Militia' national spirit to something military conscription icon instead of using a downward military industry icon.

### Justifications

Well, because using the downward military industry icon GFX icon for the 'States' Militia' national spirit is kind of confusing.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d110b452-43f2-4c84-8083-de013576684e)

### Additional information

Savegame:
[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12726700/USA_game.zip)

**Comment by runelead00** [comment]
Fixed in Dev Build
