### ISSUE TITLE
DOM - The 'Trujillo Assassinated!' triggers despite Dominican Republic under control of OFN-OAS Peace Force

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2229]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12727354/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12727355/game.zip)

### Describe the bug

The 'Trujillo Assassinated!' is somehow triggered and DOM has got the 'Rafael Trujillo' national spirit when running the game through 1966 despite the Dominican Republic is still under the OFN-OAS Peace Force and Trujillo was removed.

### Steps to reproduce / Cause of the issue

1. Trujillo wins the PPI.
2. Haitian Civil War triggers.
3. Border tension between Haiti and the Dominican Republic triggers.
4. Haitian Blitz triggers.
5. Haiti wins against the Dominican Republic and Trujillo is overthrown.
6. Trujillo Assassinated news event triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/38ad8f79-8f9a-4299-9109-4e09a8e17e01)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
