### ISSUE TITLE
Norway - Not present on country select screen

### ISSUE THREAD

**Issue by rivalnator** [TNODevs/TNO-Bug-Tracker#223]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
The patch notes stated that Norway and Scotland had been added to the country select screen. While Scotland has been added, Norway does not appear to be present. 
**Steps to Reproduce/Cause Issue:**

1. Enter country select screen

2. Observe the shocking lack of the best Scandinavian content currently in the mod

**Screenshots:**
![image](https://user-images.githubusercontent.com/41270788/142780063-2ab1c36e-f6ea-4663-9861-bb9e246a4da6.png)

**Comment by Scarsoftime** [comment]
There was a time where it was decided to add norway into the country select screen, at that time, the patch log was updated. However, this decision was reverted, but the patch log was not.
