### ISSUE TITLE
ANG - The division 3D model uses the Reichskommissariat Südwestafrika(German Afrika) division model instead of 'Black' African model

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2234]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12734755/USA_play.zip)

### Describe the GFX issue

Angola's division 3D model uses the Reichskommissariat Südwestafrika division model instead of the African 3D division model.

### Steps to reproduce / Cause of the issue

1. Angolan Civil War starts.
2. See UNITA 3D division model. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/652834dd-14ed-417d-81c2-e26bb5ab6bc4)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
