### ISSUE TITLE
USA - Change the event picture of 'The Motherland Beckons'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2235]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest changing the event picture of 'The Motherland Beckons' to the Siberian National Republic flag, Eastern Siberia, Russian people migrating picture instead of using the Paratroopers picture.

### Justifications

Because it is a little bit confusing to show a picture of Paratroopers picture in 'The Motherland Beckons' event that talks about the Russian communities in USA. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/002ea1b6-953b-4550-a921-73f21d02d1a8)

### Additional information

Not needed.

**Comment by Stormeagle449** [comment]
Fixed for The Ruin update.
