### ISSUE TITLE
USA - There is no event about Suharto wins the Indonesian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2236]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12737586/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12737587/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12737601/USA_play.zip)

### Describe the bug

After Suharto's duumvirate won the Indonesian Civil War, there was no trigger event about Suharto winning the Indonesian Civil War and USA losing the Indonesian War Cold War.

### Steps to reproduce / Cause of the issue

1. Indonesian Civil War triggers.
2. Sukarno gains an advantage against the Rebels.
3. The Indonesian Civil War took too long.
4. Duumvirate triggers and Suharto is in charge. 
5. Suharto won the Indonesian Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/48b168e0-4523-4e2c-8910-3aedabd35902)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/db82ecd9-f419-4a33-ae93-812294c49f9f)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
