### ISSUE TITLE
GER - Change the GFX icon of 'Breitspurbahn' national spirit

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2237]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest changing the GFX icon of 'Breitspurbahn' national spirit from combat planes to railways icon. 

### Justifications

Because the 'Breitspurbahn' national spirit is about the construction and expansion of railways in Einheitspakt Europe, and using the Luftwaffe with a Europe background GFX icon is somewhat confusing. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f980ad43-7fa5-41ae-93d2-bdccf4fa44ca)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
