### ISSUE TITLE
USA - Some bugs after Congolese government wins the Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2238]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12744967/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12744968/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12744988/USA_play.zip)

### Describe the bug

- In the 'Back to Africa' event, there are no mentions of the current Congolese government like 'Victor Lundula' and his 'ARC' political party due to Reichsstaat in devastation 2 but instead chose to mention the 'Congolese National Movement' and 'Patrice Lumumba' but he is not in power in Congo. 
- In the 'Back to Africa' event effect, there is political change. I don't this is for USA or Congolese Republic/State.
- In the 'Congo joins the OFN' news event, there is the word "Congolese Republic" instead of "Congo State" because of Congo's current government. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Großafrikanischer Reichsstaat formed.
3. Großafrikanischer Reichsstaat collapsed in devastation 2.
4. Congolese Civil War triggers.
5. Congo State victory.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/512be010-0751-4fe8-99a5-2ad13693fe25)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/075a0819-25ab-4529-8b05-85890bb8bf4a)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
