### ISSUE TITLE
USA - URI crisis decisions didn't remove or disappear after failing to solve the crisis

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2239]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12747040/USA_play.zip)

### Describe the bug

When the URI crisis fails to be solved, the URI crisis decisions are not removed. Like failing to solve the bankruptcy crisis and the bankruptcy crisis decisions are still there despite the damage that has already been done (in the city mechanics). The same goes for rural revolt, race riots and whiteflight.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Hart as the new president.
3. Fail to solve the URI crises. 

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5e4efb7a-ec02-4613-8094-7fe02c2bdead)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/be5fc74f-db2c-4dc9-af64-32cb412da41b)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
