### ISSUE TITLE
MZB - No trigger for Mozambican Civil War in 1970 despite the Reichstaat collapsed in stage 2 devastation

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2240]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

After either the South Africa War ceasefire stalemate, the ceasefire victory for Afrika-Schild or the total victory for Afrika-Schild and Großafrikanischer Reichsstaat collapsed in devastation 2, the Mozambican Civil War is not trigger in 1970.

### Steps to reproduce / Cause of the issue

1. South Africa War starts.
2. Either South Africa War ceasefire stalemate, ceasefire victory for Afrika-Schild or total victory for Afrika-Schild.
3. Großafrikanischer Reichsstaat collapsed in devastation 2.
4. Reach 1970.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/96125bc6-8de3-42b8-b8a4-5a31cd6749bd)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/893518d4-8a95-474f-9ce9-a59f3dd8222b)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Working as designed, Civil War in Mozambique is not at a set date
