### ISSUE TITLE
OMI - Unable to join the American economic sphere and OFN partner due to USA support after the ME conflicts

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2242]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12754375/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12754376/game.zip)
[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12754381/USA_game.zip)

### Describe the bug

After the Middle Eastern conflicts, the Imamate of Oman is not in the American economic sphere and OFN partner or OFN faction because USA supported the Imamate during the Omani Civil War while other USA-supported factions in the ME during their civil wars joined. 

### Steps to reproduce / Cause of the issue

1. Italy turned into a democracy.
2. Japan won the Battle for Italy.
3. Italy joined the Kyōeiken.
4. Omani Civil War triggers.
5. Oil Crisis triggers.
6. Imamate wins the Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e2ee1c54-b314-4c86-bb7a-6f7b2d2e1fb9)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/61ed1cc9-a5f2-4fdd-9b45-3ad1106f5d88)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/da7976e3-efe4-4bcc-bb09-88635f17bb44)

### Additional information

Not needed.

**Comment by Marok132** [comment]
How did you get Israel in your economic sphere??

**Comment by Ikidikid** [comment]
To get Israel to join the OFN economic sphere: the USA's intelligence operation to support Irgun is successful, Jurusalem Conference fails, and Israeli's Irgun takes over.

If the operation to support Irgun fails and the Irgun takes over after Jerusalem Conference fails, Israel cannot join the OFN economic sphere.

**Comment by runelead00** [comment]
Added in Dev Build
