### ISSUE TITLE
USA - Some bugs for the beginning of the 'Mozambican Civil War' 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2243]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12754845/USA_game.zip)

### Describe the bug

- In the 'CIA REPORT: Mozambique' event's first option effect, there is a text that says "aid The Popular Republic of Mozambique in their against Japan" but Samora Machel a pro-Japanese is in charge of the Popular Republic of Mozambique. "The Popular Republic of Mozambique" should be changed to "The People's Liberation Army of Mozambique" because Mondlane Mondlane is there.
- The flag is not "The People's Liberation Army of Mozambique" but instead uses the Popular Republic of Mozambique flag in the 'CIA REPORT: Mozambique' event's first option effect.
- After selecting either of the options from the 'CIA REPORT: Mozambique' event, the 'Mozambique Civil War' proxy war image will change when selecting another proxy war and then back to the 'Mozambique Civil War' proxy war.  This issue is the same goes for Japan. 

### Steps to reproduce / Cause of the issue

1. South Africa War starts.
2. Either South Africa War ceasefire stalemate, ceasefire victory for Afrika-Schild or total victory for Afrika-Schild.
3. Großafrikanischer Reichsstaat collapsed in devastation 1 or 2.
4. Mozambican Civil War triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a1418b25-a941-4f28-a07c-dbc8da9763c3)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f5825ce8-6c2e-4416-8d0a-65b07de8a777)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6b6cdc89-ab74-46d4-a1de-68d3c34758c0)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
