### ISSUE TITLE
USA - There are no operation decisions to support friendly Russian warlord when choosing to support them

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2244]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_russian_reunification_war.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12755209/USA_russian_reunification_war.zip) Run the game to see the event

### Describe the bug

After choosing to support a friendly Russian warlord in the CIA Battle for Russia event, there are no available operations in the Russia region to support the friendly Russian warlord. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. A Russian warlord has a friendly relationship with USA.
3. A Russian warlord has the regional or super-regional states.
4. The Russian reunification wars.
5. USA chose to support the friendly Russian warlord in the event through operation decisions.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5e0f5cdf-96d3-413c-bd9f-5cf65e1489df)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e34a8a30-d00e-4767-8822-a090c2287f63)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
