### ISSUE TITLE
USA - Slight confusing text in 'We're Here Now' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2245]
### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12755940/USA_game.zip) Run the game to see the event

### List the loc issues below

- [ ] 1. The text in the 'We're Here Now' event says that Zambia is a socialist nation that neighbors Mozambique but Mozambique is not neighboring Zambia but instead with Nyasaland and Zambia is not a socialist nation because Reichstaat collapsed or Zambia declares independence in devastation 2. 
Zambia could become a socialist if Reichstaat collapsed or Zambia declared independence in devastation 1. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ee925ce5-7b72-455e-90fc-d933a301401b)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
