### ISSUE TITLE
USA - US states have no given effects shown in the 'An Ocean Pacified' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2247]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_an_ocean_pacified.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12764150/USA_an_ocean_pacified.zip)

### Describe the bug

In the 'An Ocean Pacified' event's effects show that there are no effects given to USA states and there are two double for US states shown. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. 'The Honolulu Accords' triggers.
3. Japan returns some Pacific territories to USA.
4. 'An Ocean Pacified' event triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4fa2a80d-1fca-431b-82a1-e64817746a73)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
