### ISSUE TITLE
SBA - Missing Assembly Resolutions

### ISSUE THREAD

**Issue by ScreenWatcherRO** [TNODevs/TNO-Bug-Tracker#225]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0b?
- Any other mods in use: Opaque map, State transfer tool.
- Were you using Steam? Yes.
- Which expansions do you NOT have? None.

**Longer Description of Issue:**
When i won the power struggle as anarchists against Stepanov it became impossible to suggest resolutions in the General Assembly.

**Steps to Reproduce/Cause Issue:**

1. Finish power struggle tree in SBA

2. Check General Assembly

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Current Build
