### ISSUE TITLE
FUK ( + other factions?) - Inherit SS Template from RKU

### ISSUE THREAD

**Issue by RandomPandaCake** [TNODevs/TNO-Bug-Tracker#2250]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

In the Republic of Ukraine, you Can Train SS Units

<img width="1023" alt="Screenshot 2023-09-30 at 10 38 28 am" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/146496682/490fa269-c1ff-40c2-b202-128ec8313c47">

**Comment by runelead00** [comment]
Fixed in Dev Build
