### ISSUE TITLE
UKR - Loads up UNRA tree after Koch bombing

### ISSUE THREAD

**Issue by ThiFiuza** [TNODevs/TNO-Bug-Tracker#2251]
### Operating System

Windows 10

### HOI4 version

The recent one.

### TNO version

The Ruin

### Do you have other mods in use?

Fuck The Moe Order (Not using any submods)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I can't upload because the save game is too big.

### Describe the bug

After the event that fucking bombs Koch (funny) it directly goes to the Ukrainian Republic (maybe the rebellion?) focus tree for some reason. Also the localization files there seems to be missing I guess?

### Steps to reproduce / Cause of the issue

1-Play the game normally

2-I did all of the GeneralPlan Ost part first.

3-Messed a little bit with the breadbasket adding producion and stomping on rebels.

4- Go with the mechanized plan on breadbasket part of the focus tree.

5-End the focus tree making Koch getting banged.

6-Bug appears.

### Expected behaviour

Probably the Leibbrandt focus tree after Koch got bombed.

### Screenshots

[https://imgur.com/a/ooqLs0P](url) link to the screenshot

### Additional information

This maybe "Ruin"ed my gameplay HA GOTTEM (jk devs yall are doing an awesome job can't wait for more content to the other RKs and HMMLR Britain! Keep up the good work!)

**Comment by runelead00** [comment]
Did you pick UNRA in destiny category or did you just forget to select your path?

**Comment by ThiFiuza** [comment]
> Did you pick UNRA in destiny category or did you just forget to select your path?

I didn't selected any path, maybe was randomly chosen for me as now I noticed when replaying. Thank you runelead!

**Comment by runelead00** [comment]
Yeah, there is an mission  that randomly selects a path if you're ai or forgetful, so that's almost certainly what happened
