### ISSUE TITLE
ENG - Event Domvile.71 does not have option localization

### ISSUE THREAD

**Issue by ZhukovGaming** [TNODevs/TNO-Bug-Tracker#2252]
### Operating System

Win 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

NONE

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/66566166/77756743-27c5-485b-bdb6-e1347b0c0fe1)

### Describe the bug

Event "Domvile.71" is missing localization for the option "Domvile.71.a" -- Seems to be a case of either the localization either not being written, or for some reason incorrectly coded.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/66566166/deec8947-c3b4-4135-b1ce-ded539796ea9)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/66566166/2d46916b-86e1-4a5d-b339-f2541e60900e)

### Steps to reproduce / Cause of the issue

1. Play Britain
2. It's a focus event I kinda forget which focus does it but I was in the Lords subtree and the code says it's connected to a nat focus

### Expected behaviour

I expected there to be localization

**Comment by runelead00** [comment]
Fixed in Dev Build
