### ISSUE TITLE
Japan - Kido takes power after Takagi

### ISSUE THREAD

**Issue by richardnixon2** [TNODevs/TNO-Bug-Tracker#2253]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

The Moe Order (forgive me for my sins)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Kido takes power after Tagaki, this may have been intentional but it still says the reformists are in control in Japanese government UI so it doesn't look that way, I noticed this around January 1964 and unless I missed it I didn't see any event for the change. paternalism is the ruling party, and also the ministers for Tagaki are still there. 

### Steps to reproduce / Cause of the issue

1. Go through and start a Tagaki game, only specifics I had were winning and recounstructing the Phillipines, winning Malaya and Madagascar, but I doubt they have much relevance. 

### Expected behaviour

I expect that Tagaki would remain in power, and even if the switch to kido was intentional the ministers still need to be swapped and so does the Japanese government UI unless im missing something

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146497987/f6a3e677-d626-4198-9493-171b02c6f6aa)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146497987/cda09324-bd67-4252-a4a9-07dfbdf46f05)

screenshots show that Kido holds two roles which shouldn't be happening.

**Comment by runelead00** [comment]
Do you have a save from around when this happened/right before it happened

**Comment by runelead00** [comment]
Nevermind, found the cause, was completing Philippines reconstruction
