### ISSUE TITLE
Australia - Ewatt's Party missing

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#2254]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.5.0

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12773490/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12773491/error.log)

### Describe the bug

After Beazley resigns from PM. Ewatt comes in as the caretaker but missing his ALP(L) or ALP (R) party name, instead showing the name "Socialism" instead.

### Steps to reproduce / Cause of the issue

1. Wait till Feb 1962.
2. Ewatt shows up, but no ALP.

### Expected behaviour

It should show Ewatt representing ALP(L)/(R)

### Screenshots

![Screenshot (2307)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/96382658/73b6619c-c704-4405-8b71-8e6e50679dbb)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
