### ISSUE TITLE
UKR - Leibbrandt Wrong Focus Tree

### ISSUE THREAD

**Issue by InterstellarWar** [TNODevs/TNO-Bug-Tracker#2255]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Only Ironman Music Mods (Radio TNO, Songs of the South African War, Wolfenstein Music)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Koch gets attacked and Leibbrandt takes power, he gets the Insurgent Army Focus Tree and the ukraine map actions are all changed to sabotage.

### Steps to reproduce / Cause of the issue

1. Wait for Erich Koch to die
2. Leibbrandt becomes leader

### Expected behaviour

I get the Leibbrandt focus tree and map actions

### Screenshots
https://gyazo.com/917b865ad88f520c3b2823fbf66ba9cb
https://gyazo.com/335e1bda52769bf8ef807098fe538e7b
https://gyazo.com/0575e459f7cc3558958cb1bbb28c2b0b

**Comment by runelead00** [comment]
Did you select RK path when the destiny decisions came up after taking the first focus

**Comment by InterstellarWar** [comment]
oh my bad i didnt notice that i didnt choose a path
