### ISSUE TITLE
Ukraine- Option to "Assult Nazi Stronghold" not working on communist path

### ISSUE THREAD

**Issue by kylebentl** [TNODevs/TNO-Bug-Tracker#2256]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

when playing Ukraine on the communist path, the option to "Assault Nazi Stronghold" in the Resistance tab of The Breadbasket Of The Reich menu cannot be activated, regardless of cooldown, command power, guns, or manpower. there is also no icon for it.

### Steps to reproduce / Cause of the issue

1. complete "Terror against the Occupier" focus. The option mentioned was dead from the get go.

### Expected behaviour

The opption to be selected when i clicked on it with the needed rescorses

### Screenshots

tno isnt letting me add my screenshot while game is open rip

**Comment by runelead00** [comment]
Fixed in Dev Build
