### ISSUE TITLE
Economy system - Spending limits not effective

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2257]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

If you press the bar to select spending, it can ignore max and min limit 
like you can set 100% or 0% social expenditures with 20-80% limit
This bug only happens on Expenses on homepage(except nuclear expenditures), doesn't happen on expense of detailed page(such as Procurement funding)

### Steps to reproduce / Cause of the issue

This bug was not happening in 1.4.1d, I dont know about this

### Expected behaviour

Spending limits can work correctly

**Comment by runelead00** [comment]
Fixed in Dev build
