### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by 10195097** [TNODevs/TNO-Bug-Tracker#2258]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0 The Ruin

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12774142/error.log)

### Describe the crash

Whenever I load into the game and select a country, I load into the game and the country guide menu pops up and immediately crashes.

### Steps to reproduce / Cause of the crash

1. launch game
2. pick country
3. start loading
4. crashes

**Comment by Jack121Q** [comment]
A possible fix I can recommend is to try loading the game with openGL, had reports of this possibly fixing the game.

Guide for doing that:
In steam, right click HOI 4, click properties->set launch options, type -opengl, press ok.

**Comment by 10195097** [comment]
Thanks for the recommendation but unfortunately it did not work nor did changing the launcher itself to opengl.

**Comment by runelead00** [comment]
Merged into #962, can only recommend possible fixes listed there
