### ISSUE TITLE
RK Ukrain - doesn't change cost of actions for partisans

### ISSUE THREAD

**Issue by ErichvonLudendorff** [TNODevs/TNO-Bug-Tracker#2259]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After death of Koch cost of actions in Breadbasket menu doesn't change for partisans

### Steps to reproduce / Cause of the issue

1. Start game as RK Ukraine
2. Choose as beloved of destiny any partisan movement (I chose UPA)
3. Play until Koch's death
4. Open Breadbasket menu
5. Move your coursor on any action in window of development

### Expected behaviour

Real cost of actions will be the same as it is written on pictures

### Screenshots

![1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/103324819/36a4e7fc-e7ee-427d-b6bd-e90d8cd97021)

**Comment by runelead00** [comment]
Fixed in Dev Build
