### ISSUE TITLE
JAP - PHI_blitz.6 event occurred in Japan

### ISSUE THREAD

**Issue by ibonopo** [TNODevs/TNO-Bug-Tracker#2260]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Describe the bug

Japan experiences event PHI_blitz.6 post reconstruction instead of the Phi tag intended, so Japan switches leaders instead.

### Steps to reproduce / Cause of the issue

1. Win Balintawak Blitz 2. Complete Reconstruction successfully, 3. Click any option (all of them are paternalists, and change party leader to paternalist)

### Expected behaviour

Leader of the Second Philippine Republic to change from national assembly to chosen leader from event. Also to not have Japan's leader changed

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/118903028/6db21dff-991d-49e7-bae2-e7a85021b7d9)

### Additional information

I got it as Takagi, and based on last Ukraine game something similar happened as well.

**Comment by runelead00** [comment]
Fixed in Dev Build
