### ISSUE TITLE
Ukraine - Partisan Development Actions GFX gone

### ISSUE THREAD

**Issue by SunnyFlower00** [TNODevs/TNO-Bug-Tracker#2261]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

FPS Map

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12774477/error.log)

### Describe the GFX issue

After loading my Ukrainian save I noticed that breadbasket menu doesn't have GFX buttons for partisan development actions, so I couldn't use them.

### Steps to reproduce / Cause of the issue

1. Save the game
2. Exit the game
3. Load the save file
4. Open the breadbasket menu

### Expected behaviour

Have GFX buttons.

### Screenshots

![the bug](https://github.com/TNODevs/TNO-Bug-Tracker/assets/117448123/fe16800b-72f8-4a89-82ed-fe7c11d0e70b)

**Comment by runelead00** [comment]
Fixed in Dev Build
