### ISSUE TITLE
Great Britain - Economy slider not limited

### ISSUE THREAD

**Issue by SeveralSpeciesOfSmallFurryAnimals** [TNODevs/TNO-Bug-Tracker#2262]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When selecting the expenditures sliders in the economy tab you can set spending above the cap. For example you can set Britain's social spending, which is supposed to be capped at 75%, to any value you want by simply clicking on the slider.

### Steps to reproduce / Cause of the issue

1. Go to the economy tab 2. click on any of the expenditure sliders at the bottom of the tab

### Expected behaviour

the bars show a limit between 25% and 75%. Clicking past these threshold i expected expenditures to be set to either 25 or 75%, not something past these values.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146538964/3b040ca1-1cdd-4183-80e1-e351179604a9)    
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146538964/5df583f9-69e0-4b2e-b4ba-e35c1d022a6a)    Visually it shows 75% but in reality spending is close to 100%

**Comment by runelead00** [comment]
Fixed in Dev Build
