### ISSUE TITLE
USA/GER - Add 'Channel Crisis' in the Cold War achievements

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2263]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Describe your suggestion

I would like to suggest adding the 'Channel Crisis' to the Cold War achievements for USA and Germany. 

### Justifications

Because USA and Germany have a 'Channel Crisis' in the global conflicts. So, that is why I suggest this.

### Screenshots

Not needed.

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
