### ISSUE TITLE
Ireland - ending event chain broken

### ISSUE THREAD

**Issue by An-Sealgaire** [TNODevs/TNO-Bug-Tracker#2265]
### Operating System

Windows 10

### HOI4 version

Avalanche v.1.12.14.50e7

### TNO version

TNO v1.5.0 - "The Ruin"

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The event  "Garret the Good and the Nice Fellow" doesn't trigger the next Irish event "Labour's Love Lost", as a result the ending is broken unless the latter event is triggered manually through console commands.

### Steps to reproduce / Cause of the issue

1. Play TNO Ireland up to "Garret the Good and the Nice Fellow" (aka IRE_postcrisis.3)
2. To fix go to TNO_BRI_Ireland in events and add  country_event = { id = IRE_postcrisis.4 days = 7 } to IRE_postcrisis.3

### Expected behaviour

The events after "Garret the Good and the Nice Fellow" should trigger, but currently don't

**Comment by runelead00** [comment]
Fixed in Dev Build
