### ISSUE TITLE
FUK - No loc for FUK_post_war.0 event

### ISSUE THREAD

**Issue by johnsnoa** [TNODevs/TNO-Bug-Tracker#2266]
### Operating System

Windows 11

### HOI4 version

1.12.14.50e7

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

No localization for event

### Steps to reproduce / Cause of the issue

1. Win as Republic of Ukraine

### Expected behaviour

Localization be there

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/61244971/ad416eb5-2941-4a98-a3f5-ad398b39502c)

**Comment by runelead00** [comment]
Fixed in Dev Build
