### ISSUE TITLE
Uks - breadbasket not work after civil war 

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#2267]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

v1.5

### Do you have other mods in use?

no 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

the breadbasket and resistance mechanic is not showing up for the socialist. 

### Steps to reproduce / Cause of the issue

win the war 
get the mechanic  

### Expected behaviour

can't click on anything 

### Screenshots

![20230930142828_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/6f36b696-b4b0-418f-85b4-0850b1e02a4c)
![20230930141207_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/5ea81c77-5163-4ef2-846b-861947ac29b2)

**Comment by runelead00** [comment]
Fixed in Dev Build
