### ISSUE TITLE
Japan - Text showing up where it shouldn't?

### ISSUE THREAD

**Issue by richardnixon2** [TNODevs/TNO-Bug-Tracker#2268]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

It shows the text when responding to the event jap_ar.4
"JAP_army_reforms_started_tt"

### Steps to reproduce / Cause of the issue

1. Should be  able just to trigger the event via console, but I've just played a Tagaki game, went through strength and totality, and a coalition of equals and I'm just about to finish the easing nationalization part of the focus tree. 

### Expected behaviour

probably give me something that does not use _ consistently as I think that it's a bug

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146497987/28ad0e25-05a0-4b44-92cf-2a5aeaeb7f13)

message you get when responding to the event (besides the debug stuff which I used to find the event id for this report)

**Comment by runelead00** [comment]
Fixed in Dev Build
