### ISSUE TITLE
FUK - Unable to use "Acquire Collaborator Weapons" decision

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2269]
### Operating System

Windows 10 Home

### HOI4 version

Avalanche v.1.12.14

### TNO version

The Ruin 1.5.0

### Do you have other mods in use?

Modifier Icons (TNO Version), TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[savegame.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12775429/savegame.zip)

### Describe the bug

When playing as Free Ukraine, the “Acquire Collaborator Weapons” decision is unavailable for use, despite having Collaborator Support being above 50%, which is supposed to fulfill the decision requirements.

### Steps to reproduce / Cause of the issue

1. Play as Free Ukraine.
2. Use decisions and focuses to get Collaborator Support to at least 50%
3. Notice that the relevant decision is unusable

### Expected behaviour

“Acquire Collaborator Weapons” decision, as well as "Mobilize Collaborator Forces", should be usable.

### Screenshots

![20230930115326_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/9c5fba6c-3a86-4f09-a62a-4d1c27ea3b31)
![Picture](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/07f0af22-b30c-4142-8550-7d2477d8ca65)
![Picture2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/84742a81-02c8-46ce-87c0-3bd94aaeb76c)

**Comment by runelead00** [comment]
Fixed in Dev Build
