### ISSUE TITLE
USA - Misc. USA Bugs

### ISSUE THREAD

**Issue by biasface** [TNODevs/TNO-Bug-Tracker#227]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

1. I had no ability to intervene in the West African War. It was the PALF vs FF only scenario. The victory event (I deleted all of the PALF's troops in the console) had no localization.
2. Even after a successful decolonization of Africa, I still had the societal discontent modifier, and it never went away.

**Comment by runelead00** [comment]
Fixed in Dev Build
