### ISSUE TITLE
USA - Regarding Global Conflicts Decisions

### ISSUE THREAD

**Issue by DaZeebo** [TNODevs/TNO-Bug-Tracker#2270]
### Operating System

Windows 11

### HOI4 version

1.11.7

### TNO version

1.5.0

### Do you have other mods in use?

Not ones affecting my issue

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, MTG, LAR, NSB, BBA

### Describe the bug

In the Global Conflicts decisions, there is a countdown for something regarding that conflict, but it ends up covering the top decision, making it a hassle to select

### Steps to reproduce / Cause of the issue

1. Play as USA 2. Click on Foreign Policy 3. Go to Global Conflicts 4. For conflicts like Puerto Plata, there is a countdown that remains at the top of the decision bar, and it sometimes covers up decisions at the very top, making them h ard to click

### Expected behaviour

being able to click the decision 

### Screenshots

n/a

### Additional information

n/a

**Comment by runelead00** [comment]
Fixed in Dev Build
