### ISSUE TITLE
Ukraine- Text for Ukraine ruling party under Speer's collab gov is UKR_collab_paternalism.

### ISSUE THREAD

**Issue by N3cron4** [TNODevs/TNO-Bug-Tracker#2272]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![Screenshot 2023-10-01 002807](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146596656/ed3e06cf-58fa-46a7-98dd-6e1092fc0b83)

**Comment by runelead00** [comment]
Fixed in Dev Build
