### ISSUE TITLE
Ideology descriptions are contradictory and based on old lore

### ISSUE THREAD

**Issue by D4ntheM4n** [TNODevs/TNO-Bug-Tracker#2273]
### HOI4 version

v.1.12.14

### TNO version

The Ruin 1.5.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

The description for Marxism Leninism still mentions that Stalin dies during an industrial accident while the Bolshevism ideology description mentions the Stalin coup of Bukharin that occurs in 1942. The Marxism Leninism description, and probably the Tyumen unification events, should be changed to adjust for the new lore in which Stalin overthrows the Bukharin government and forms the WSPR. 

### Justifications

Aside from the fact that the two different ideologies have conflicting descriptions of events, the Marxism Leninism sub ideology is based on outdated lore where Stalin was killed in an industrial accident instead of the new lore where Stalin coups the government. 

### Screenshots

![Screenshot (32)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107819293/70080644-4e5c-4d47-a1dd-0da9f5496dc8)
![Screenshot (33)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107819293/ec21d38a-a6dc-4d3b-b34c-e16306859bc5)

**Comment by runelead00** [comment]
Fixed in Dev Build
