### ISSUE TITLE
HAI - Incorrect Tooltip Used in Haiti Civil War

### ISSUE THREAD

**Issue by CKShrek321** [TNODevs/TNO-Bug-Tracker#2274]
### HOI4 version

1.12.14

### TNO version

The New Order: Last Days of Europe - v1.5.0 "The Ruin"

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [x] 1. For the TNO_HCW_increase_control_small effect the government uses the correct tooltips but the communists use "large" meaning even when they are supposed to be only making minor gains it appears like they are constantly winning 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/56777501/c68ae9fc-7ed6-4fc0-86ea-f6502c8bdfad)
- [x] 2. Ditto for medium 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/56777501/bdddafe7-5c02-46f5-8bfe-ff9987ef37d2)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
