### ISSUE TITLE
Japan - Broken Philippine reconstruction event

### ISSUE THREAD

**Issue by APerson626** [TNODevs/TNO-Bug-Tracker#2275]
### Operating System

Windows 11

### HOI4 version

1.12.13

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12776508/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12776509/game.log)
[JAP_1963_12_10_13.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12776511/JAP_1963_12_10_13.zip)

### Describe the bug

After finishing the Philippine reconstruction, Japan gets an event to choose Yulo's successor. The event sets Kido's party as the ruling party of Japan in all cases.

### Steps to reproduce / Cause of the issue

1. Finish Philippine reconstruction
2. Event to choose Yulo's successor launches
3. YSK-Kido-ha set as Japan's ruling party in all 3 options

### Expected behaviour

Chosen leader (for example, Osmena) supposed to become leader of 

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146614812/1c11f2df-121f-43bd-a6e0-89a5c99da614)

**Comment by runelead00** [comment]
Fixed in Dev Build
