### ISSUE TITLE
UNRA Ukraine - CCP Issue with Election

### ISSUE THREAD

**Issue by ECWWCWWWF** [TNODevs/TNO-Bug-Tracker#2276]
### Operating System

Windows 11

### HOI4 version

latest 

### TNO version

latest Ruin

### Do you have other mods in use?

FPS mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

I choose Ohloblyn in customs but in game it chooses Dziuba

### Steps to reproduce / Cause of the issue

1. Select Collabs in Dem Ukraine customs

### Expected behaviour

Ohloblyn becoming the leader duh

**Comment by runelead00** [comment]
Fixed in Dev Build
