### ISSUE TITLE
USA - RFK Social Security Act multiplies unemployment expenses by 10x

### ISSUE THREAD

**Issue by borbytar** [TNODevs/TNO-Bug-Tracker#228]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0c
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

RFK's Social Security Act costs vastly more than it reasonably should (making me think it's a bug), dooming the USA to a massive debt crisis once it is passed. Prior to passing the act, my unemployment expenses were roughly ~$10 billion at max, while they were $163 billion at max expenditure after passing the act.

**Steps to Reproduce/Cause Issue:**

1. Pass RFK's Social Security act doing any prerequisite foci or things that modify the act.

**Screenshots:**
![image](https://user-images.githubusercontent.com/94809252/142782662-1979638a-4587-44b5-b8f5-1b2fc9c3a746.png)

**Comment by runelead00** [comment]
Assuming caused by accidently getting UBI, which RFK has since been prevented from getting, so fixed in current release
