### ISSUE TITLE
UKR - No unique icon for 'Government Control is low!' warning attention

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2280]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12777221/UKR.zip)

### Describe the GFX issue

Playing as German Ukraine and the 'Government Control is low!' warning attention pops out, there is no unique icon for 'Government Control is low!' instead uses of generic icon (probably a question mark icon). 

However, the icon of 'Government Control is low!' warning attention is somewhat changed to a production icon or something else. 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Run the game.
3. 'Government Control is low!' warning pops out.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/390475d2-7449-4547-b39d-b85be6c4b727)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c0cb6981-7e7c-4965-a291-362ce3c6da2b)

### Additional information

Not needed.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
