### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by ekenny3** [TNODevs/TNO-Bug-Tracker#2281]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

As Japan, winning the "Balintawak Blitz" proxy conflict and completing the reconstruction mechanic afterwards if a successor has not been endorsed in the decisions then an event appears where you can choose the successor from a list of three. But any of the choices doesn't change the filipino government but, instead, changes Japans one.
In my run specifically I played as Takagis Japan and when that event fired it changed my ruler to Kido instead of putting industrialists in charge of the Philippines.

### Steps to reproduce / Cause of the issue

1. Win the Balintawak blitz (first filipino civil war) as the Japanese side
2. Complete the reconstruction event without endorsing anyone
3. Choose any successor on the event that fires immediatly after completing the reconstruction
4. Done, now Japans ruler changed and the filipino one is still a building

### Expected behaviour

Japans ruler shouldn't change and the Philippines would be ruled by the chosen faction in the event

**Comment by runelead00** [comment]
Fixed in Dev Build
