### ISSUE TITLE
UKR - 'Government Control is low!' warning attention suddenly pops out 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2283]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

Playing as Reichskommissariat Ukraine and running the game, the 'Government Control is low!' warning attention suddenly pops out despite the rebels not fully controlling either of the Ukraine regions and Erich Koch is not yet severe injured. 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Run the game.
3. 'Government Control is low!' warning pops out.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/de92d540-3043-4f44-bcb2-cd017b493697)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9f967f07-db82-48b1-81d6-de3e6ee71892)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
