### ISSUE TITLE
HAI - Cantave can coup the Red Haiti's PPLN government 

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2284]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Chinese Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After PPLN win's the HCW and communists putsches the DR after the PPI,Cantave will coup the PPLN government 

### Steps to reproduce / Cause of the issue

1.Go to custom paths
2.Set"PPLN crashes the government" in HCW option and "communists putsches" after the PPI
3.Wait until PPLN wins the HCW and DR turns red
4.Contave coups the PPLN government 

### Expected behaviour

Cantave can't coup the PPLN government 

### Screenshots

![Haiti](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/fd4e0d05-4648-488c-94c3-8df67c01c732)

**Comment by runelead00** [comment]
Fixed in Dev Build
