### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Something-Fun** [TNODevs/TNO-Bug-Tracker#2285]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

The New Order: Last Waltz Expanded, The New Order: VT323 Map and Cities Font, Toolpakt: Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12777637/game.log)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12777644/autosave.zip)

### Describe the bug

Upon completing reconstruction for the Philippines I received an event asking me to choose the nation's leader.
"Who to lead after Yulo's assassination (unnecessary loc)"
- "Quentin Paredes"
- "Claro M. Recto"
- "Osmena"

This is event the further breaks in which instead of affecting the Philippines it makes the Kidoites lead Japan.

### Steps to reproduce / Cause of the issue

I dunno what exactly caused it but my guess would be deciding to support Osmena (I think) in the Philippine Reconstruction decisions

### Expected behaviour

For Osmena to simply seize power

### Screenshots

![Screenshot (2)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146658439/5d47cda3-cfbb-4daa-9e30-137b25bc0c59)
![Screenshot (3)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146658439/72155eda-68df-44c3-9a04-fb4128ecfc8b)

**Comment by runelead00** [comment]
Fixed in Dev Build
