### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by HerrnChaos** [TNODevs/TNO-Bug-Tracker#2286]
### Operating System

Windows 10

### HOI4 version

1.12.14.50e7

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12777913/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12777914/game.log)

### Describe the bug

So i go to Steam and open the paradox launcher, activate TNO and see a Red Warning sign besides "Play" saying some active mods arent installed and when i load in the game is just vanilla.
Im having those problems since yesterday the 30th September.
All other mods besides Calm before the Storm (the one WW1 mod) and Red Flood are working.

The Bug is basically the mod isnt loading.

### Steps to reproduce / Cause of the issue

I am not experienced with such skills but i have already reinstalled all mods i got, cleared the cache multiple times and reloaded the mods.
i would be just happy if you guys can solve my problem

### Expected behaviour

that everything goes good.

### Additional information

if you want to talk directly to me go on Discord and text HerrnChaos#2341

**Comment by Stormeagle449** [comment]
If the launcher is saying some active mods aren't installed then there's probably an issue on your end. Check your playset and all the subscribed mods on the launcher, if there are uninstalled mods then delete them from your launcher. If the problem persists then check your mod folder (C:\Program Files (x86)\Steam\steamapps\workshop\content\394360\2438003901) and see if TNO is installed correctly.

**Comment by HerrnChaos** [comment]
question: how do i check that TNO is installed correctly?

**Comment by HerrnChaos** [comment]
its still not working, i even redownloaded the paradox launcher

**Comment by HerrnChaos** [comment]
nope its still not working, i unsubcribed to the mod and now it just shows me still "some active mods arent installed" and the game still is vanilla
