### ISSUE TITLE
Germany -speer isn´t the leader even after winning the civil war

### ISSUE THREAD

**Issue by EvoDevco** [TNODevs/TNO-Bug-Tracker#2288]
### Operating System

Windows 10

### HOI4 version

latest version until today

### TNO version

1.5.0

### Do you have other mods in use?

TNO:Second West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Describe the bug

So I was playing as novobrins and when the civil war begun  speer wasn´t the leader. What is worse is that they won and then speer wasn´t still the leader. it says that the leader is someone called: Willi brandner.

### Steps to reproduce / Cause of the issue

i don´t know. I didint even play as germany

### Expected behaviour

seeing speer being the lader of germany after the civil war

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146676062/f7245897-bcc7-4c16-be52-3c7c9d1573b3)

**Comment by runelead00** [comment]
2WRW issue, report it them (assuming it's even compatible yet, which I don't think it is)
