### ISSUE TITLE
Britain - Invalid event id for the "Scavenge all we can" focus

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2292]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

There is an event in the "Scavenge all we can" focus during the British civil war with an invalid id, no event fires after finishing the focus.

### Steps to reproduce / Cause of the issue

Look at focus after the British civil war starts.

### Expected behaviour

An event should be there.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/f204ffa2-195d-4c9b-a77b-f3ac7be4b4e7)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
