### ISSUE TITLE
UKR - No unique icon for 'A Breadbasket Action is Available!' warning attention

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2293]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12778376/UKR.zip)

### Describe the GFX issue

Playing as German Ukraine and the 'A Breadbasket Action is Available!' warning attention pops out, there is no unique icon for 'A Breadbasket Action is Available!' instead uses of generic icon.

However, the icon of 'A Breadbasket Action is Available!' warning attention is somewhat changed to a production icon or something else.

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Run the game.
3. 'A Breadbasket Action is Available!' warning pops out.

### Expected behaviour

Forgot to add unique icon. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/11cf692d-8da6-4cd8-9d01-10e62136ecf7)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ea12a8a9-fd6d-46fe-a492-38274d6b9ae1)

### Additional information

Not needed.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
