### ISSUE TITLE
Britain - Event showing Domville still alive despite being dead

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2294]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The event "Fountaine's Petition", which outlines falling behind in the 1963 economy mentions Domville very much alive despite him being blown up a number of months earlier.

### Steps to reproduce / Cause of the issue

Occurs around early 1964, a number of months after Domville's death and during the British civil war.

### Expected behaviour

No event, or Nall-Cain or mention of the civil war affecting the economy.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/2d924f6f-3582-45ea-800d-c9066002f141)

**Comment by runelead00** [comment]
Fixed in Dev Build
