### ISSUE TITLE
UKR - No unique icon for 'The Consumption Cycle is nearing its end!' warning attention

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2295]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12778442/UKR.zip)

### Describe the GFX issue

Playing as German Ukraine and the 'The Consumption Cycle is nearing its end!' warning attention pops out, there is no unique icon for 'The Consumption Cycle is nearing its end!'.

However, the icon of 'The Consumption Cycle is nearing its end!' warning attention is somewhat changed to a production icon or something else.

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Run the game.
3. 'The Consumption Cycle is nearing its end!' warning pops out.

### Expected behaviour

Forgot to add unique icon. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1d25b0c9-c558-47d5-8564-992d6d0b5580)

### Additional information

Not needed.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
