### ISSUE TITLE
UKR - 'The Consumption Cycle is nearing its end!' warning suddenly pops out despite the consumption cycle is not nearly end

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2296]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12778456/UKR.zip)

### Describe the bug

Playing as German Ukraine, 'The Consumption Cycle is nearing its end!' warning suddenly pops out despite the consumption cycle is not nearly end.

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Run the game.
3. 'The Consumption Cycle is nearing its end!' warning pops out.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f109f2fc-bab0-4e37-a732-1058fe6f1971)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
