### ISSUE TITLE
UKR - The Actions from 'The Breadbasket of the Reich' GUI are not unlocked despite the requirements are met

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2297]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12778492/UKR.zip)

### Describe the bug

Despite having enough PP requirements for the Action from the 'The Breadbasket of the Reich' GUI, the actions are not unlocked despite the requirements are met. But when PP is more than the requirement, the actions are somehow unlocked.  

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Has enough PP to get the action through 'The Breadbasket of the Reich' GUI.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7b53d11a-e573-47fc-919a-80249e2b513a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/72f04d30-30c4-4ef4-8118-14b7ad546116)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
