### ISSUE TITLE
UKR - One-Time Development Tax and Paradise Undone national spirits have the same GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2298]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12778525/UKR.zip)

### Describe the GFX issue

'One-Time Development Tax' has the same GFX icon as the 'Paradise Undone' national spirit, and One-Time Development Tax should have a different national spirit icon. 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Complete the 'Blood from Stone' focus.
3. Has the 'One-Time Development Tax' national spirit.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/77eaaedb-a82b-4f40-ad1f-64538cdfbf51)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e4aba4ae-a7bf-4ec7-a9fc-b9959032f7b8)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
