### ISSUE TITLE
UKR - 'UKR_power_struggle_active' is not localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2299]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12778597/UKR.zip)

### Describe the bug

'UKR_power_struggle_active' is not localized yet in the 'An Empty Throne' decision prerequisites. 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Choose Reichskommissariat Ukraine destiny.
3. Koch has a severe injury.
4. Power struggle between AOdNSDAP factions triggers. 

### Expected behaviour

Forgot to adding loc, I think

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4e91ec36-0a22-4da7-8ab7-7d433e669129)

### Additional information

Not needed.

**Comment by Fortune801** [comment]
Fixed on Dev Build
