### ISSUE TITLE
USA- Philippines reconstruction bugged

### ISSUE THREAD

**Issue by SarFed** [TNODevs/TNO-Bug-Tracker#230]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 
- TNO Version: 1.2.0
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? The unit model/music packs

**Longer Description of Issue:**
After completing Filipino reconstruction to 100%, the mission still fails.
**Steps to Reproduce/Cause Issue:**

1. Win as the USA in the Philippines while going to war with the socialists
2. Get progress on reconstruction to 100%
3. Wait for the timer to run out

**Screenshots:**
![image](https://user-images.githubusercontent.com/94810018/142783941-42604cc9-3b5b-45d5-b5f5-bdfe234b8c5f.png)
![image](https://user-images.githubusercontent.com/94810018/142784010-58d046dd-a7ef-4668-8746-edc2a2ec549e.png)

**Comment by runelead00** [comment]
You need to press the button next to the progress bar to finish reconstruction
