### ISSUE TITLE
United Kingdom - Missing Domvile choice name

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#2300]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.5.0

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12779152/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12779153/error.log)

### Describe the bug

In the "I Know Fairer Fair" event from the "Shining Forth Upon Our Clouded Hills" focus, it shows "domvile_focus.27.b" instead of regular text.

### Steps to reproduce / Cause of the issue

1. Play as Domvile's UK in 1962
2. Get to "Shining Forth Upon Our Clouded Hills" focus.
3. Get the "I Know Fairer Fair" event.

### Expected behaviour

Shows regular text instead of code name.

### Screenshots

![7e65909659fe542df92ac1e4e6e107f4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/96382658/0cf7b5d2-1d7e-46b2-bc79-bec37e6b2732)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
