### ISSUE TITLE
UKR - There is a placeholder in 'The Consumption Cycle' idea description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2301]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12779187/UKR.zip)

### List the loc issues below

- [x] 1. There is a placeholder "guangdong reference?????" in the national spirit description of 'The Consumption Cycle'.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/513d262a-c69e-445c-a6dd-d54713cb0a44)

### Additional information

Not needed.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
