### ISSUE TITLE
Choose Philippines President as Japan - Faction leader of Japan changes from Kaya Okinori to Kido Kōichi

### ISSUE THREAD

**Issue by rmor13** [TNODevs/TNO-Bug-Tracker#2302]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Just soundtrack mods

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I am playing as Japan and put Kaya Okinori (Technocrats) in power. I ensured that the Second Philippine Republic won the civil war. 
After that war, I went through the "Reconstruction of the Philippines" process in the "Global Conflicts" tab and reached 100% in that process. As I "Declare Reconstruction Complete" I get the event pop up to decide who the next President of the Philippines will be. No matter which candidate I choose, a bug appears that affects Japan. The new faction leader of Japan becomes Kido Kōichi and it shows his political party in power. Oddly enough, Kaya Okinori's focus tree is still in place, and on the "Japanese Government Overview GUI" it still shows that I am playing as the Technocrats. Everything else appears that I am still playing as Okinori and the Technocrats as well. It is just what you see in the screenshot that makes it appear I am playing as Kido Kōichi 

### Steps to reproduce / Cause of the issue

1. "Declare Reconstruction Complete" after reaching 100% in the "Reconstruction of the Philippines" tab on "Global Conflicts"
2.  Pick whichever candidate in the "Our successor" pop-up.
3. What I described in the bug will happen.

### Expected behaviour

I would pick the successor and the game would proceed as normal with Kaya Okinori still the leader of Japan.

### Screenshots

![Screenshot (11)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146687289/9c46b27c-9878-4da3-86a4-e313edd36f02)
![Screenshot (12)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146687289/e9f07964-13cc-4bc0-b793-315ec54c5916)

### Additional information

I am not super tech. savvy and don't really need how to attach a save file. I am going to try to go back to a recent save and not go through the Philippines event to see what happens if I don't do reconstruction.

**Comment by runelead00** [comment]
Fixed in Dev Build, just put set_ruling_party = despotism to fix it on your end for this playthrough

**Comment by rmor13** [comment]
> Fixed in Dev Build, just put set_ruling_party = despotism in the console to fix it on your end for this playthrough

I tried this and it then says "Invalid number of arguments". Sorry if I am missing something. I've never messed with console commands. Any help is appreciated. Thank you!

**Comment by runelead00** [comment]
oh sorry that's on me, I meant set_ruling_party despotism, w/o the =

**Comment by rmor13** [comment]
Thank you very much runelead00, that worked! Appreciate all of the help!
