### ISSUE TITLE
JAP - Indonesian Civil War not triggering

### ISSUE THREAD

**Issue by MsChoo1** [TNODevs/TNO-Bug-Tracker#2303]
### Operating System

Window 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Last Waltz of Europe Extended, Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Describe the bug

Sukarno is not declaring war on the free independent front. I've played out for about a month since the borders broke, and it hasn't triggered.

### Steps to reproduce / Cause of the issue

Takagi, and play to the Indonesian civil war.

### Expected behaviour

Both sides to declare war on each other

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107003909/84c59a7b-2c8f-4e2a-b8e2-f2ae4d5ca842)

**Comment by runelead00** [comment]
How much has the war escalated in the forpol menu?

**Comment by MsChoo1** [comment]
> How much has the war escalated in the forpol menu?

Second phase to escalation. It says it'll let me send one more volunteer to indonesia, but the war hasn't even started. I get the super event, too.
