### ISSUE TITLE
USA - 'Helping Out a Freind' and 'Break Open the Caches' national focuses are not bypassed when the British Civil War triggers

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2305]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12780647/USA_play.zip)

### Describe the bug

After the start and end of the British Civil War, 'Helping Out a Freind' and 'Break Open the Caches' national focuses are not bypassed.

Note: The image shows the 'Helping Out a Freind' focus was completed before the German and British civil wars. So, this focus has the bypass same as the 'Break Open the Caches' focus.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. German Civil War triggers.
3. Start of the British Civil War.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4057fa9d-b724-4b44-84f9-1c65159e2018)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/52ea7f67-7260-4df9-90ad-b469b1539302)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
