### ISSUE TITLE
FUK - No localization for power struggle factions' national spirits during the UCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2307]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12781247/UKR_play.zip)

### List the loc issues below

- [ ] 1. There are no localization for `FUK_power_struggle_partisan_dynamod`, `FUK_power_struggle_populist_dynamod` and `FUK_power_struggle_collaborator_dynamod`.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d96dd25b-8a8e-4af7-8d0b-3a59f17f76eb)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/15167b1c-a8f1-4eaf-b9b4-a5d1160b8a18)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/45e7bb34-fd1c-4178-8843-7eb4b04e0089)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
