### ISSUE TITLE
UKR - 'Sicherungs-Division' and 'SS Grenadier-Division' division template bugs

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2308]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12781480/UKR_play.zip)

### Describe the bug

- Before the UCW and UKR's division templates are unlocked, in template view, 'Sicherungs-Division' division template has blank four support template icons and localizations, and 'SS Grenadier-Division' division template has blank two support template icons and localizations. 
- When the division templates are unlocked, 'Sicherungs-Division' and 'SS Grenadier-Division' division templates have no loner blank support template icons and become plus sign icons when moving the cursor to them but the localizations are still blank. Yet, those become plus sign icons when moving the cursor to them already have support template added because it says "Click to change". not "Click to add".

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. See view or edit for the division template of 'Sicherungs-Division' and 'SS Grenadier-Division' before and during the UCW.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9d8e33b3-5bae-466e-8166-fd6bd3f2f43e)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9cd24a5e-ebdf-4ba2-9993-8c905c6783d6)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bd8a5813-e6be-4876-b1b5-006a2d01cebe)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/abd20f18-2cbc-4d9c-83f4-edfd36a6fad0)

### Additional information

Not needed.

**Comment by Fortune801** [comment]
Fixed on Dev Build
