### ISSUE TITLE
USA - Can't send more Vounteers to South Africa

### ISSUE THREAD

**Issue by Zakar505** [TNODevs/TNO-Bug-Tracker#231]
**Questions**

- Operating System: Windows 10
- HOI4 Version:
- TNO Version: 1.2.0
- Any other mods in use: None
- Were you using Steam: Yes
- Which expansions do you NOT have?

After I do the decisions to expand ground operations, I can’t send any more volunteers.

**Steps to Reproduce/Cause Issue:**

1. I sent my first volunteer

2. Increase Max volunteers sent to two

3.  I click on send volunteers and it says the maximum amount of volunteers has been sent

**Screenshots:**
![20211121181214_1](https://user-images.githubusercontent.com/83110300/142785130-1c34d683-555e-4e5b-8a75-97efebcdde63.jpg)
![20211121181210_1](https://user-images.githubusercontent.com/83110300/142785158-86c20bc2-bc68-488c-a8b6-2520c245355a.jpg)

**Comment by AlgisAlphonse** [comment]
I can second this bug's occurance. It happens in every conflict, regardless of the advisor level. I should not that on my end, the send voluteers text tells me that I have send "0 of 1 divisions" (even when I have sent one division and can send more) and does not allow to send any more divisions. If the division already sent dies, you can send more volunteers then.

**Comment by AlgisAlphonse** [comment]
![20211123001053_1](https://user-images.githubusercontent.com/94876543/142953445-fad79f0e-396a-4b8c-8316-a9087fdb77ad.jpg)
Screenshot of the issue on my end.
