### ISSUE TITLE
UKR - 'Intel Based Partisan Warfare' national spirit has no GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2310]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_civil_war.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12781828/UKR_civil_war.zip)

### Describe the GFX issue

The 'Intel Based Partisan Warfare' national spirit has no GFX icon when selecting the 'Squeeze the Informants' decision. 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Start of the German Civil War.
3. Start of the Ukrainian Civil War.
4. Select the 'Squeeze the Informants' decision. 

### Expected behaviour

Forgot to add GFX icon.  

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/325abc90-f019-4d73-ac77-656ec9306d88)

### Additional information

Not needed.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
