### ISSUE TITLE
GER/HUN/ROM - Hungary and Romania suddenly rejoined the Pakt after either of the German factions wins the CW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2311]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12782171/GER.zip)

### Describe the bug

After either of the German factions won the German Civil War, Hungary and Romania suddenly rejoined the Pakt without any event about their rejoining the Einheitspakt. 

### Steps to reproduce / Cause of the issue

1. The German Civil War starts.
2. Either of the German factions wins the GCW.
3. Hungary and Romania rejoin the Pakt after Speidel Surrenders Germania! event.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/89a6577c-3e13-4232-b7da-f42e528649d4)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1bb6dd8c-b0d6-4f1b-8a5f-0d8751f03f66)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6052c30d-dd77-49fa-8e5e-e77c265450ef)

### Additional information

Not needed.

**Comment by runelead00** [comment]
WAD, Hungary and Romania (and also collab Serbia + England) never leave the Pakt in any official manner so they immediately rejoin when it reforms after the GCW, unlike states like Bulgaria who use the opportunity to distance themselves
