### ISSUE TITLE
MAD - Malagasy Republic changed its color instead of remain Malagasy Rebellion's color after TAFAMA wins 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2312]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the bug

After the Malagasy rebels won and TAFAMA won due to Japanese factionalism is greater, Malagasy Republic changed its color instead of to remained Malagasy Rebellion's color. Because Malagasy Rebellion is also supported by the Japanese and so the tag color of the Malagasy Rebellion should not be changed when TAFAMA takes over. 

### Steps to reproduce / Cause of the issue

1. Second Malagasy Uprising starts.
2. Japanese factionalism is higher.
3. Malagasy rebels win.
4. TAFAMA wins.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/73696ab2-c557-40e8-9f66-535e1b7e1c24)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/30111885-2154-4f85-80ec-3d2f56f95dd1)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Madagascar's color changes regardless of which faction wins
