### ISSUE TITLE
GER - There is a Göring content reference in the 'German Intervention in Africa' news event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2313]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### List the loc issues below

- [x] 1. The description of the 'German Intervention in Africa' news event refers to Göring content and "and his militarist staff" text should be removed because Bormann wanted to remove militarist influence anyway and Speer has no militarist faction.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4b3fba82-761a-4c29-b2a0-a634df4c6cee)

### Additional information

Not needed.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
