### ISSUE TITLE
Global - Missing localization for no training

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#2314]
### Operating System

win11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The no training policy is missing localization.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/59315866/ccf0e286-c44b-4eb1-84fb-bff107792b4f)

### Steps to reproduce / Cause of the issue

n/a

### Expected behaviour

n/a

**Comment by runelead00** [comment]
Fixed in Dev Build
