### ISSUE TITLE
UKR/UKS/FUK/BOV - 'The Ukrainian Civil War' national spirit has no GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2315]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12782923/UKR_play.zip)

### Describe the GFX issue

'The Ukrainian Civil War' national spirit has no GFX icon for all Ukrainian factions during the UCW.

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Start of the German Civil War.
3. Start of the Ukrainian Civil War.

### Expected behaviour

Forgot to add GFX icon.  

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/95f316fa-4df4-44a1-ba00-d662e079e2f9)

### Additional information

Not needed.

**Comment by Fortune801** [comment]
Fixed on Dev Build
