### ISSUE TITLE
UKR/UKS/FUK/BOV - 'The Ukrainian Civil War' national spirit appears in the late Civil War instead of starting

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2316]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12782994/UKR_play.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12783061/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12783064/game.zip)

### Describe the bug

When the Ukrainian Civil War was triggered, 'The Ukrainian Civil War' national spirit didn't appear for all Ukrainian factions at the start of the civil war but instead, the national spirit appeared in the late civil war. 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Start of the German Civil War.
3. Start of the Ukrainian Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/87e18df2-7829-459d-b9a1-574a1de5e010)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/72e7eeba-2099-4a65-a799-52fcbf35038a)

### Additional information

Not needed.

**Comment by Fortune801** [comment]
Fixed on Dev Build
