### ISSUE TITLE
UKR - 'Panacea' national spirit doesn't remove after Reichskommissariat wins the Ukrainian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2319]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12786856/UKR_play.zip)

### Describe the bug

After Reichskommissariat Ukraine won the Ukrainian Civil War, the 'Panacea' national spirit didn't get removed. 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Ukrainian Civil War triggers.
3. Complete all Reichskommissariat Ukraine's civil war focus trees.
4. Has the 'Panacea' national spirit. 
5. Reichskommissariat Ukraine wins the civil war.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/47a055bb-2375-44b5-9ab7-35f3203937f3)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5836950e-0181-41f5-a71e-379f83e57ad8)

### Additional information

Not needed.

**Comment by Fortune801** [comment]
Fixed on Dev Build
