### ISSUE TITLE
SBA - Unchoseable Reform 7

### ISSUE THREAD

**Issue by carys-the-weed-cloud** [TNODevs/TNO-Bug-Tracker#232]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0c
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Reform 7, Checks on Assembly Authority, is not pickable after completing focus "We Will Stand Shoulder to Shoulder" at super regional stage of libertarian socialist path. May be related to issue with the SBA_debate_ongoing flag not being cleared when entering/leaving the power struggle decision category.

**Steps to Reproduce/Cause Issue:**

1. Go 'libsoc' path during power struggle at end of regional stage.

2. Complete focus "We Will Stand Shoulder to Shoulder" at super-regional stage

3. Attempt to click on reform.

**Screenshots:**

Not easily representable in screenshot format.

**Comment by runelead00** [comment]
Fixed in Current Build
