### ISSUE TITLE
UKR - 'UKR_something_is_broken_tt' has no localization

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2320]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12786965/UKR.zip)

### Describe the bug

In the 'Something is Broken' national focus effect, `UKR_something_is_broken_tt` has not yet been localized.

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Ukrainian Civil War triggers.
3. Reichskommissariat Ukraine wins the civil war.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a7adaec4-1450-472b-9dae-65de7aea3c9a)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
