### ISSUE TITLE
UKR - 'Factionalism Intensifies' decision time doesn't remove after Reichskommissariat wins the Ukrainian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2321]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12787028/UKR_play.zip)

### Describe the bug

After Reichskommissariat Ukraine won the Ukrainian Civil War, the 'Factionalism Intensifies' decision time didn't get removed because this decision has an effect on increasing or reducing resistance groups just before the civil war.

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Ukrainian Civil War triggers.
3. Reichskommissariat Ukraine wins the civil war.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c9863385-b0cd-4a2a-a8ec-790b34c8d5e7)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
