### ISSUE TITLE
UKR - The Final Hours event has generic picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2322]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Not needed.

### Describe the GFX issue

'The Final Hours' event has the generic picture(paratroopers picture) after completing the 'A Nation Without Kings...' focus

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Ukrainian Civil War triggers.
3. Reichskommissariat Ukraine wins the civil war.
4. Complete the 'A Nation Without Kings...' focus. 

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8b9f5451-5ae4-47bb-9438-72cf126484e4)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build, issue was person who assigned event pic spelled Melnyk's name correct, when file name was spelled wrong
