### ISSUE TITLE
UKR - Erwin Weinmann has no GFX portrait

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2326]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_ohlendorf_takes_over.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12787782/UKR_ohlendorf_takes_over.zip)

### Describe the GFX issue

When Otto Ohlendorf takes power, Erwin Weinmann has no GFX portrait. 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Ukrainian Civil War triggers.
3. Reichskommissariat Ukraine wins the civil war.
4. Complete '...Grinding to a Halt' focus.
5. Ohlendorf wins the power struggle.

### Expected behaviour

Forgot to add portrait.  

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/88ae2c8b-7b15-4f4f-a7af-1f7702ea4f76)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c6e4f6c4-ddd8-4c3f-ab0f-5faa63e867ad)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
