### ISSUE TITLE
USA - LBJ's Winning the African American Vote Chain Broken

### ISSUE THREAD

**Issue by CKShrek321** [TNODevs/TNO-Bug-Tracker#2327]
### Operating System

Windows 12

### HOI4 version

1.12.14

### TNO version

The New Order: Last Days of Europe - v1.5.0 "The Ruin"

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

LBJ is supposed to have an event chain (LBJ.136-139) about gaining the African American vote as he progresses through the civil rights part of his tree. This is also needed for the final LBJ "victory" event LBJ.144.

The problem is the chain does not go on beyond the first event, and it's because of one effect accidently being deleted at this event.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/56777501/aca93408-c993-44d1-95fc-59d976f0b9de)
The effect that should be in the missing line is akin to this (clearing the LBJ_winning_the_aa_vote_1 flag and adding LBJ_winning_the_aa_vote_2 flag)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/56777501/ab6786af-10ee-4b89-8b13-ef48a1855750)

Since it's missing, the trigger does not go beyond the first event.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/56777501/cbeaba95-22c1-4107-a4df-fb2583a03928)

### Steps to reproduce / Cause of the issue

1. Play LBJ
2. Keep going down the LBJ tree with a particular focus on civil rights
3. Etc

### Expected behaviour

LBJ.137-139 and LBJ.144 should appear in campaigns.

**Comment by runelead00** [comment]
Fixed in Dev Build
