### ISSUE TITLE
UKR - Some bugs for Ohlendorf's ending screen

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2328]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[UKR_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12787967/UKR_play.zip)

### Describe the bug

- There is no scroll bar in the ending screen's epilogue because the description is too long.
- When scrolling down to the last in the Credits of current members (1) and former members (2), there is no text about special thanks in (3). 

### Steps to reproduce / Cause of the issue

1. Play as Reichskommissariat Ukraine.
2. Ukrainian Civil War triggers.
3. Reichskommissariat Ukraine wins the civil war.
4. Complete '...Grinding to a Halt' focus.
5. Ohlendorf wins the power struggle.
6. End of the story of Ohlendorf's Reichskommissariat Ukraine.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3cf565a6-77bf-4c80-865f-dda684f62ee2)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ed3fa2c3-bada-42a9-82a1-9b8cc73dc5c9)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8fcd9cb0-e961-4f9e-a670-78c2ab9e65cf)

### Additional information

Not needed.

**Comment by runelead00** [comment]
1. Endscreen adjusted to better fit descs of the length
2.  2nd issue is a base Paradox bug, can't fix
