### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Aur3Ilan** [TNODevs/TNO-Bug-Tracker#233]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have?
None
**Longer Description of Issue:**
as USA in 1964, at 1:00 on February 4th 1964, the game just completely freezes and crashes, presumably due to the 2 events popping up, the Olympics event and the 
**Steps to Reproduce/Cause Issue:**

1. It's pretty much due to the random pop-ups i think so idk how to "recreate" it directly

2.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/94817643/142799567-7892d17a-aaeb-4d6a-9c94-9677ebbd4dc1.png) 
 
![image](https://user-images.githubusercontent.com/94817643/142799639-de9185a9-7636-4019-aa7e-a6c3d9d5f3e5.png)

**Game Saves and Log Files, if possible:**

**Comment by runelead00** [comment]
Fixed in Current Release
