### ISSUE TITLE
USA - No 'Operation LIMESTONE' appears in intelligence in Europe region after completing the 'Break Open the Caches' focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2332]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12792289/USA_play.zip)

### Describe the bug

After completing the 'Break Open the Caches' national focus, 'Operation LIMESTONE' is not appearing in the intelligence in Europe region. 

However, 'Operation LIMESTONE' somehow appears 'late'. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Completes the 'Break Open the Caches' national focus.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/30d9071f-3e7f-46cd-a5cf-f163f9993e14)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f5a820c6-ca34-445f-96cf-3f756d1d694a)

### Additional information

Not needed.

**Comment by Fortune801** [comment]
Fixed on Dev Build
