### ISSUE TITLE
Japan- Japanese political party and prime minister changed

### ISSUE THREAD

**Issue by piyokichi123** [TNODevs/TNO-Bug-Tracker#2333]
### Operating System

Windows 10

### HOI4 version

latest

### TNO version

latest

### Do you have other mods in use?

+JP The New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After completing reconstruction after the end of the Philippine War, the Japanese political parties somehow become Kido as they proceed with the event to choose the Philippine president.

### Steps to reproduce / Cause of the issue

1, Finish Philippine War
2, Select some  decision about reconstruction.
3, The event of select President
4, Japanese political party and prime minister changed.(And Philippine President doesn't any change)

### Expected behaviour

Some Country IDs were mistake?

**Comment by runelead00** [comment]
Fixed in Dev Build
