### ISSUE TITLE
USA - 'An Opportunity' event gives a +100.0 command power

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2335]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12792689/USA_play.zip)

### Describe the bug

The 'An Opportunity' event gives a '+100.0' command power, which is too much. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. The triumvirate collapsed.
3. 'An Opportunity' event triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8cb06cee-869b-4ecf-a28e-735bc52fc2a2)

### Additional information

Not needed.

**Comment by Fortune801** [comment]
This is WAD
