### ISSUE TITLE
USA - Add the 'new' decision timers in the decision tab's 'Events or Decisions Timeout'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2336]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest adding the 'new' decision timers in the decision tab's 'Events or Decisions Timeout' to warn the player that there are decision timers that are about to end. 

### Justifications

Because before The Ruin update, there were decision timers that appeared in the decision tabs 'Events or Decisions Timeout' to warn the player that the decision timers were about to end. Just like the HOI4 decision timers' system.    

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b4edd722-12cc-40d4-93f8-3e4665583e4c)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Not a part a code we can adjust, Paradox doesn't allow us to adjust that part of code
