### ISSUE TITLE
Haiti - Lavaud's elections never happen

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#2338]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After Lavaud's coup happens when the Puerto Plata invasion fails, the elections never happen and the interim government stays.

### Steps to reproduce / Cause of the issue

1. Have the game rules set where the Puerto Plata invasion fails, Lavaud's coup happens and any of the potential candidates in his elections wins (and to avoid any chance of the PPLN taking over, make it so the government wins). 
2. Wait

### Expected behaviour

One of the three candidates in Lavaud's elections should be elected.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by PhoneythePhoneSaver** [comment]
Wait so the next patch update will fix it?
