### ISSUE TITLE
USA - Command Power is somehow drops to zero when the 'Landfall' event pops out

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2339]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12797438/USA_play.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12797509/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12797510/game.zip)

### Describe the bug

When the 'Landfall' event pops out, the command power somehow drops to zero which means it takes many months to receive additional CP in order to take the proxy war decisions. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Triumvirate faction collapsed.
3. Start of the PPI.
4. 'Landfall' event triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/06c6e987-bdd5-46a3-ae2c-b9ed2eb0a479)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9f18eaec-8808-4153-902d-54ebeb0fdedb)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
