### ISSUE TITLE
Speer Germany - Reorganize Moskowien decision has no effect, no puppet established you keep the land directly 

### ISSUE THREAD

**Issue by Senkaimon** [TNODevs/TNO-Bug-Tracker#234]
**Questions**

- Operating System:
- HOI4 Version: Latest before NSB
- TNO Version: TT initial release
- Any other mods in use:Terra et Liberta
- Were you using Steam? Y
- Which expansions do you NOT have? La Resistance

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
