### ISSUE TITLE
USA/IBR/GER - Change the 'The Ceasefire Expires...' and 'Tensions Increase...' decision timers to 'new' (update) ones

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2341]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the PPI ceasefire's decision timers, 'The Ceasefire Expires...' and 'Tensions Increase...' for USA, Iberia and Germany should be changed to the 'new' decision timers. Just like USA has one. 

### Justifications

Well, most of the USA's proxy wars have changed their decision timers. So that is why I suggest this to include 'The Ceasefire Expires...' and 'Tensions Increase...' decision timers to 'new' ones. Including changing the decision timers to the 'new' ones for Germany and Iberia. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/37f9c52c-184f-40ed-a8f9-742723232135)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/809ef18e-bd83-47a8-85f3-b3b2289be0ad)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d29e9884-01f1-4226-9479-dfc09654087c)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Working as Designed
