### ISSUE TITLE
GER - PPI defeat declares 'Stalemate' -5 instead of 'Total Defeat' in the Germany's Cold War achievements

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2344]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12799067/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12799068/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12799113/USA_play.zip)

### Describe the bug

After USA backed the Legion(Dominican Revolutionary Front) won the Dominican Civil War, Germany declared a 'Stalemate' -5 instead of 'Total Defeat' -100 or so in Germany's Cold War achievements. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the PPI.
3. Trujillo overthrown.
4. USA continues to support the Legion.
5. Dominican Revolutionaries won the Dominican Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8f41ac56-ceb8-42fd-850a-e015d2b44dd0)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/61bd2dd6-7dc1-455d-b73e-30a4b8ff9b7d)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
