### ISSUE TITLE
DOM - Still has good relationship with the fascist nations in the Latin America despite Trujillo was overthrown

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2345]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12799224/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12799225/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12799229/USA_play.zip)

### Describe the bug

Despite Trujillo and Balaguer removed and ending the fascist era in Dominican Republic, Dominican Republic still has a good relationship with the fascist nations in the Latin America(New Granada, Paraguay and Santa Cruz) and the rest of the fascist nations in the Latin America still have good relationship with Dominican Republic.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the PPI.
3. Trujillo overthrown.
4. USA continues to support the Legion.
5. Dominican Revolutionaries won the Dominican Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ff44000e-18b3-4d15-ba2a-89d90fbfba90)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6d7bc783-4300-4b4e-8231-9fc56ef801e9)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
