### ISSUE TITLE
USA - 'Rebellion's End' event gives increased opposition voters instead of increase current political party

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2350]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12804254/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12804256/game.zip)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12804269/autosave.zip)

### Describe the bug

After PADESM won in Madagascar, the 'Rebellion's End' event gave increased opposition voters instead of increasing current political party voters. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Second Malagasy Uprising starts.
3. American factionalism is higher.
4. Malagasy Rebels wins.
5. PADESM wins.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/98fabae6-184d-4cca-84e1-2209c29b4345)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ffef1be8-c1a9-4069-8436-46639140a9e5)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
