### ISSUE TITLE
USA - Operation JEWEL still appears despite South Africa becomes republic

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2351]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12804353/USA.zip)

### Describe the bug

When the Union of South Africa becomes the Republic of South Africa, Operation JEWEL still appears. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa chooses the status quo.
3. Pro-Monarchy in SAF decreases.
4. South Africa War starts.
5. South Africa becomes a republic.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/249ecf8f-2f53-4f76-b836-71cd772f94ea)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
