### ISSUE TITLE
All Countries - States Population bug

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2352]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

At some point, the population of any random states may drop significantly or even go 0
This bug has been here since 1.4.1, perhaps longer
I can't find laws of it, the states where this bug occurs are all over the world, it happens on Deserts, villages, islands and enclaves, but they all fall to -$1 per capita in map when this bug occurs

### Steps to reproduce / Cause of the issue

TNO - common - scripted_effects - TNO_population_scripted_effects, edit here
idk why it heppens, here are some suggestions of mine
1.set a min-population for states. at least 100 population per state, this is for worst situation if bug already happened, at least this min-population won't make states completely broken
2.If it can, set a state min monthly population growth, minimum monthly grow -1% people, that means that even if Holy Russian Empire came, it would only kill 1% people per month

### Expected behaviour

There will no longer be a sudden and rapid decline in population

**Comment by runelead00** [comment]
This scripted effect has nothing to do with population breaking, this affects only Iberia under very certain circumstances
