### ISSUE TITLE
Britain - Mission icon for focus "A Purge Long Overdue"

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2353]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/31eb3a33-3ad0-45ab-a6f9-4e302477eac8)

However the icon returns after you click on the icon.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/dbaab21d-69ec-4b72-80c1-4f8b9bc09b14)

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

**Comment by runelead00** [comment]
Fixed in Dev Build
