### ISSUE TITLE
USA - There are 'Sending support to Central Siberian Federation' operation decisions despite Central Siberian Federation is not in the American eco sphere yet

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2354]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12810164/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12810165/game.zip)
[USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12810169/USA.zip)

### Describe the bug

When Novosibirsk united Central Siberia, the 'Sending support to Central Siberian Federation' operation decisions appeared despite Central Siberian Federation is not in the American economic sphere yet. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Smuta in Central Siberia.
3. Novosibirsk unites Central Siberia.

### Expected behaviour

Not needed.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e3ffc43c-722e-472b-b0b4-c6a980124ac6)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c42dd8b0-23a6-4a23-a72b-7486445b556e)

### Additional information

Not needed.

**Comment by runelead00** [comment]
CIA decisions to help in Russia do not and have never depended on econ spheres
