### ISSUE TITLE
Collab Britain - Civil War Objectives Failing

### ISSUE THREAD

**Issue by astickyheresy** [TNODevs/TNO-Bug-Tracker#2356]
### Operating System

Windows 11

### HOI4 version

Avalanche v1.12.14.50e7

### TNO version

v 1.5.0 The Ruin

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I seem to be getting little objectives to do, like "Hold York" and "Hold Norfolk" and then immediately failing them, which is tanking my military confidence. Should this be happening? It seems like a fairly rough civil war, all told, and this certainly isn't helping.

### Steps to reproduce / Cause of the issue

Play out the British Civil war as normal.

### Expected behaviour

I expected to be able to actually do the objectives, but actually holding the objectives seemed to do nothing and fail it anyway.

**Comment by Fortune801** [comment]
This is already fixed on Dev Build, thank you for the report
