### ISSUE TITLE
USA - Graphical Haiti map bug in the Haitian Civil War global conflict

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2357]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12810991/USA_play.zip)

### Describe the bug

The GFX Haiti map in the Haitian Civil War global conflict shows the Artibonite et Nord has been controlled by the government at least but in-game, it shows that Artibonite et Nord is controlled by the Haitian Revolutionary Front. 

This issue is the same for the rest of the Haitian states in the GFX Haiti map in the Haitian Civil War global conflict. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the Haitian Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5ad5f47d-39f7-4a76-9670-140243a9c00b)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a9f8a2dd-2670-410c-93da-bcbc1b008435)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
