### ISSUE TITLE
JAP- Kido as head of state and Hirohito national spirit bugs 

### ISSUE THREAD

**Issue by Sploosh233** [TNODevs/TNO-Bug-Tracker#2358]
### Operating System

Window 11

### HOI4 version

1.11.5

### TNO version

V1.5.0- “The Ruin”

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Kido will become the head of state after new prime minister inauguration, it does not affect gameplay. Political pie chart will show Kaya’s faction with much more power. This usually happens in September 1963. Hirohito spirit can disappear when it is supposed to be modified, but when a focus is completed that modifies the spirit again, it will reappear. 

### Steps to reproduce / Cause of the issue

Quickest way to get Kido glitch (as observed)
1. Government forces win Philippine civil war
2. Complete reconstruction
3. Pick any leader for Philippines from event pop up
4. Kido will show as head of state

### Expected behaviour

Kido as head of state and Hirohito spirit not present(temporarily)

**Comment by runelead00** [comment]
Fixed in Dev Build
