### ISSUE TITLE
England - Cant pass Act, decision appears twice 

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#236]
**Questions**

- Operating System: 10
- HOI4 Version: latest
- TNO Version: latest
- Any other mods in use: no
- Were you using Steam? Yes
- Which expansions do you NOT have? All 

**Longer Description of Issue:**
I have 300 seats in parliament as NF a nnd still can't pass the Act. Also, the entire last two NF focuses seem bugged concerning the bill (able to take focus saying bill has passed despite bill having just entered parliament). No decisions that seemingly should be there to help pass the bill dont appear as well. 

Seperate: I got two versions of the event which allows you to pick who to kill in HMMLR. One had no effects and a dead end, another one allowed me to lower HMMLR influence in the north, middle or south of England depending on who I killed. I assume this is the new one and the old one was supposed to be removed.

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by brmusch** [comment]
Not a bug, part of the narrative
