### ISSUE TITLE
USA - No 'Secure the Gulf of Guinea' decision timer appeared in West African Conflict global conflict

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2360]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12811602/USA_play.zip)

### Describe the bug

After the West African War started, there is no 'Secure the Gulf of Guinea' decision timer that appeared in the West African Conflict global conflict for USA while Japan has the 'Secure the Gulf of Guinea' decision timer. 

However, the 'Secure the Gulf of Guinea' and 'Frontline Solidify' decision timers are in 'The Home Front' decision instead of in the West African Conflict global conflict.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. The West Africa War starts.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6464250a-3602-4de6-b61c-e596fdcad4b1)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d4a8f625-9527-4b7f-bddc-3880e5f41787)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/db367e34-c0c2-4610-aaf2-e7ca433041d3)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Working as Designed
