### ISSUE TITLE
ROM/TNS - Slight bugs after they rejoined the Pakt

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2361]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_speer_victorious.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12811715/GER_speer_victorious.zip)

### Describe the bug

Romania doesn't have the Zollverein national spirit and Transnistria is not in the German economic sphere and doesn't have the Zollverein national spirit after they rejoined the Pakt when the GCW ends. 

### Steps to reproduce / Cause of the issue

1. Start of the German Civil War.
2. Speer won the German Civil War.
3. Romania and Transnistria rejoined the Pakt. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/71b72280-becd-47d7-8662-7a5c6631ae18)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
