### ISSUE TITLE
USA/MZB - East African Mandate doesn't dissolve

### ISSUE THREAD

**Issue by Angelblue1852** [TNODevs/TNO-Bug-Tracker#2362]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The East African Mandate doesn't work properly, as when it finishes the last focus, the event chain only does the first event before stopping.

### Steps to reproduce / Cause of the issue

1. Play as USA
2. Win the SAW with Total OFN Victory
3. Make the 3 Mandates
4. Tell East African Mandate to go Liberal
5. Keep East African Mandate alive long enough for it to finish it's focus tree
6. Events never fire so Mandate never decolonizes.

### Expected behaviour

East African Mandate decolonizes

### Additional information

Apparently according to a friend of mine, the issue is that there's an extra if block in the first decolonization event that's breaking it. (See Bold if block)

hidden_effect = {
			if = {
				limit = {
					has_country_flag = OFN_MZB_DECOL_socialist
				}
				country_event = {
					id = OFN_AFR_DECOL_MZB.2
					days = 1
				}
			}
			else_if = {
				_**if = {**_
					limit = {
						has_country_flag = OFN_MZB_DECOL_federation
					}
					country_event = {
						id = OFN_AFR_DECOL_MZB.6
						days = 1
					}
				**_}_**
			}
			else = {
				if = {
					limit = {
						has_completed_focus = OFN_MZB_cooperate_with_the_anglos
					}
					country_event = {
						id = OFN_AFR_DECOL_MZB.6
						days = 1
					}
				}
				else = {
					country_event = {
						id = OFN_AFR_DECOL_MZB.3
						days = 1
					}
				}
			}
		}

Try removing that possibly?

**Comment by runelead00** [comment]
Fixed in Dev Build
