### ISSUE TITLE
USA - The Channel Crisis suddenly appeared before clicking the 'A Victory and a Burden' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2363]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12812928/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12812929/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12812994/USA_play.zip)

### Describe the bug

The Channel Crisis somewhat appeared in the global conflict before clicking the 'A Victory and a Burden' event. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the German Civil War.
3. Start of the British Civil War.
4. Free Britain won the Civil War.
5. 'A Victory and a Burden' event triggers.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/20b3b6ac-bbf4-4cb9-b6bf-3c7a8eeef5c1)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
