### ISSUE TITLE
USA - 'Direct International Pressure' decision has no effects shown

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2364]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12814082/USA_play.zip)

### Describe the bug

In The Channel Crisis global conflict, the 'Direct International Pressure' decision has no effects shown. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the British Civil War.
3. Free Britain won the Civil War.
4. Start of The Channel Crisis.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/78397c94-0dc3-4b9c-b31c-1f2518961f0b)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
