### ISSUE TITLE
HUN/ROM - Hungary and Romania are somehow removed from the German economic sphere after run the game

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2366]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12814239/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12814242/game.zip)
[GER_speer_victorious.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12814244/GER_speer_victorious.zip)

### Describe the bug

Hungary and Romania were suddenly removed from the German economic sphere after running the game that Hungary and Romania joined the German economic sphere after the GCW.  

### Steps to reproduce / Cause of the issue

1. Start of the German Civil War.
2. Speer won the German Civil War.
3. Hungary and Romania joined the Pakt and the German economic sphere.
4. Hungary and Romania are removed from the German economic sphere.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e34556d2-1c25-4e68-926e-48e09a0cb16c)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1f94a141-f523-4d9d-bca4-f6c800a3aa81)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
