### ISSUE TITLE
SER - Republic of Serbia joins the economic sphere and has Zollverein (if Speer wins) after the GCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2367]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12815130/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12815135/game.zip)
[GER_speer_victorious.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12815170/GER_speer_victorious.zip)

### Describe the bug

The Republic of Serbia has somehow joined the German economic sphere and has the Zollverein national spirit (if Speer wins) after the German Civil War.  

If this is intended, then Republic of Serbia is suddenly removed from the German economic sphere after running the game. 

### Steps to reproduce / Cause of the issue

1. Serbian Civil War triggers.
2. The Serbian National Liberation Front won the civil war.
3. Declaration of 'Republic of Serbia'.
4. Republic of Serbia joins the economic sphere and has Zollverein (if Speer wins).

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fd3b57e7-bcac-4ce9-9b92-47dbe7fd2790)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/70f3127d-3255-40b2-801e-6a487ac69265)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/278d2a01-d4a3-470c-95bf-8b46489e38f7)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
