### ISSUE TITLE
USA - 'Gain Base Stability: -1.00%' has no line break in 'The Staus of the War'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2368]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12816531/USA_play.zip)

### Describe the bug

'Gain Base Stability: -1.00%' after 'The Government's Response' has no line break in 'The Staus of the War' decision timer.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the Haitian Civil War.
3. The Involvement reaches 100.
4. Select any of the 'One-Time Decision' decisions.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0922c6d9-e0ed-4d31-b172-c9cdea928cae)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
