### ISSUE TITLE
ENG (Thatcher) - An Atlantic Battleground influence doesn't tick up monthly for ENG, also credit rating doesn't tick up for ENG

### ISSUE THREAD

**Issue by austrianemperor** [TNODevs/TNO-Bug-Tracker#237]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Whatever is up-to-date
- TNO Version: 1.2.0 (no patches)
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have?
None
**Longer Description of Issue:**
First issue: Despite stating that I will gain three influence a month as ENG, I do not. However, GER does (not sure if USA does because they never took the decision). This means it is a literally impossibility for me to win the Atlantic Battleground as ENG. 
Second issue: My credit rating progress bar is much more than maxed out yet I do not receive a credit rating improvement. See screenshot.
**Steps to Reproduce/Cause Issue:**

1. Play ENG as Thatcher and take the foreign policy branch of the focus tree. 

2a. Play the Atlantic Battleground and Denounce the Superpowers in Parliament. Then wait to see that you have no monthly tick despite it saying you do. 

2b. Have a budget surplus and wait a long time. Your credit rating doesn't increase. 

**Screenshots:**
![2021-11-22](https://user-images.githubusercontent.com/18901210/142826351-7e0fd9e6-e229-41be-9d7f-ce0d8b68081b.png)
![2021-11-22 (1)](https://user-images.githubusercontent.com/18901210/142826354-fe8ccbd3-2980-49d1-9532-f2079cde5e3e.png)

**Comment by masterbobli** [comment]
Fixed 2A in dev build

**Comment by runelead00** [comment]
Fixed 2b in Dev Build
