### ISSUE TITLE
ffr -waw 3 is broken

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#2370]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

v1.5

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GNG_1966_08_10_07.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12817400/GNG_1966_08_10_07.zip)

[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12817408/logs.zip)

### Describe the bug

waa defeat France and this happen 

### Steps to reproduce / Cause of the issue

play the game 

### Expected behaviour

waw 3 is broken

### Screenshots

![20231004225851_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/c1c1a6c4-7e9f-4cbe-8755-12f7b1c5bcc8)
![20231004230017_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/e99ba86e-713e-4dd9-b23c-5e9e15d0e581)

**Comment by runelead00** [comment]
#1509, Can't do very little w/o save PRIOR to a peace deal breaking

**Comment by runelead00** [comment]
Fixed in Dev Build probably
