### ISSUE TITLE
ukrainian state - useless attack buff

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#2371]
### HOI4 version

1.12.14

### TNO version

v1.5

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

idk remove it or move it or something

### Justifications

the attack buff on UNRA is useless because you need it not to exist to complete the past focus 

### Screenshots

![20231004212051_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/58d50f7b-5e34-4583-86e2-256512841454)
![20231004212053_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/e0baa528-cf7a-4a62-bbc4-9785c34cbae2)

**Comment by runelead00** [comment]
Already moved in dev build + it's not a attack buff, it's removing the attack buff + combat malus
