### ISSUE TITLE
ENG - Unable to join the OFN after USA wins The Channel Crisis

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2372]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12817416/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12817417/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12817429/USA_play.zip)

### Describe the bug

After USA wins The Channel Crisis and Free Britain either become the 'free' United Kingdom or the Commonwealth of Britain, Free Britain is unable to join the OFN and American economic sphere because Free Britain is actually a pro-OFN. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Free Britain won the British Civil War.
3. The Channel Crisis triggers.
4. USA won The Channel Crisis.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3a9bbcf2-abe7-4168-94b3-99172fb276d3)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9c0d7b47-b784-492e-86e9-df26a56f8e16)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
