### ISSUE TITLE
USA - Malagasy rebellion wrong victory

### ISSUE THREAD

**Issue by vonSarow** [TNODevs/TNO-Bug-Tracker#2373]
### Operating System

windows 11

### HOI4 version

1.12.14

### TNO version

v1.5

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I won the Malagasy rebellion as Nixon. The "win" event adds popularity to NPP and tanks my RDC unity

### Steps to reproduce / Cause of the issue

1)play the game
2)win madagaskar

### Expected behaviour

I expected to get RDC popularity and unity because I won Madagaskar as a RDC president Richard Nixon

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/130732579/f6c1fa20-b3f9-4410-a3f1-0ef1616ddb3f)

### Additional information

I campaigned as NPP in 1962 and 1964. No idea whether this affects the issue or not

**Comment by runelead00** [comment]
Fixed in Dev Build
