### ISSUE TITLE
USA - 'HCW_communists_crushed_tt' has no localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2374]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12818232/USA_play.zip)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12818249/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12818250/game.zip)

### Describe the bug

`HCW_communists_crushed_tt` has no localized yet in 'The Staus of the War' decision effect. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the Haitian Civil War.
3. The Haitian government almost fully controls on one state.
4. See 'The Staus of the War' decision effect.

### Expected behaviour

Forgot to adding loc, I think

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/162a7153-420e-42d2-8434-e145b43216ec)

### Additional information

Not needed.

**Comment by Fortune801** [comment]
Fixed on Dev Build
