### ISSUE TITLE
USA - 'The Staus of the War' decision effect bug when one of the Haitian states fully controlled by the government

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2375]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12818377/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12818378/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12818380/USA_play.zip)

### Describe the bug

'The Status of the War' decision timer effect shows that one of the Haitian states will be fully controlled by the government and crush the rebels due to controlled by above 90% but the control breakdown pie chart shows that one of the Haitian states is controlled by the government less than 90% or above. 

Just like the images below. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the Haitian Civil War.
3. The Haitian government almost fully controls on one state.
4. See 'The Status of the War' decision effect.
5. See info about 'Control breakdown' in the pie chart.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dca9407b-7923-44bb-8db9-478b6f3a6a2f)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/caeb2510-b754-4a32-bbc2-1be5a9e3dc93)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
