### ISSUE TITLE
ENG - Wrong current country name in 'The Young, Old Democracy' national spirit description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2376]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12819102/USA_play.zip)

### List the loc issues below

- [ ] 1. In 'The Young, Old Democracy' national spirit description says "United Kingdom" for a current country name but Free Britain is now a Commonwealth of Britain, not United Kingdom. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dbf7974f-6b3c-4dc9-b0f6-50679c138076)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
