### ISSUE TITLE
USA - No effects shown for some of the Haitian states in 'The Status of the War' decision timer effect

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2377]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12819165/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12819166/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12819168/USA_play.zip)

### Describe the bug

In 'The Status of the War' decision timer effect, it shows that there are no effects shown for some of the Haitian states. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the Haitian Civil War.
3. One of the Haitian states is fully controlled by the government and the rebels are crushed.
4. See 'The Status of the War' decision timer effect.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a3a9d3be-886a-4657-a524-10fd6ecee1c7)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
