### ISSUE TITLE
SAF - Missing Icon for "A Plan for the Future"

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2378]
### Operating System

Windows 10 Home

### HOI4 version

Avalanche v.1.12.14

### TNO version

The Ruin 1.5.0

### Do you have other mods in use?

Modifier Icons (TNO Version), TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the GFX issue

After The Ruin update, the icon for South Africa’s “A Plan for the Future” focus is now missing. If you click on the focus, it’s missing in the expanded description as well.

### Steps to reproduce / Cause of the issue

Cause of the issue:
    1. Open "goals2.gfx” under the Interface folder
    2. Scroll down to “GFX_SAF_A_Plan_for_the_Future” (line 28483)
    3. Cause of the bug is a duplicate `SouthAfrica` in the GFX path

### Expected behaviour

The focus should show an icon of a burning South African flag, with Boers on one side and ANC members on the other.

### Screenshots

![20231005112220_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/2eb2c68d-cfc9-4361-9034-a30503ac4354)
![Causes](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/50a01f15-23b1-4a62-a7ad-2b2db3622e26)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
