### ISSUE TITLE
USA - Random Madagascar Strikes

### ISSUE THREAD

**Issue by profabeckner** [TNODevs/TNO-Bug-Tracker#2379]
### Operating System

Windows 11

### HOI4 version

1.5.idk

### TNO version

The Ruin Sept 29th version

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

Getting strikes at random in the Madagascar proxy. Happened three campaigns in a row. This most recent time I got one random strike in phase 2, then I skipped straight to three strikes a couple of weeks after phase 3 started. I did not get the second strike event at all. I always seem to get at least one strike in phase 3. Yes, I am absolutely sure I have an action in loadout before taking a decision.

### Steps to reproduce / Cause of the issue

Play Madagascar proxy as USA. Do decisions as normal. Wait for events to start firing about things you didn't do.

### Expected behaviour

Get strike three.

**Comment by runelead00** [comment]
Fixed in Dev Build
