### ISSUE TITLE
USA - Contested has increased after 'The Status of the War' decision but after reloading the game, it didn't

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2380]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12824939/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12824940/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12824942/USA_play.zip)

### Describe the bug

In 'The Status of the War' decision timer shows that Tiburon will get government increase considerably and then after the decision times out, Tiburon has contested increased instead of the government.

But after reloading the same save game and running the game to finish the decision timer, the issue didn't occur. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the Haitian Civil War.
3. One of the Haitian states is fully controlled by the government and the rebels are crushed.
4. Increase government control over Tiburon.
5. Select Tiburon state in HCW global conflict.
6. Wait to finish the 'The Status of the War' decision timer.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/970a08d0-e8b4-42be-b902-c76a46349922)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/99e46118-98e7-4af6-9ef8-f561d4ec3c3e)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Working as Designed
