### ISSUE TITLE
USA/MAD - Bugs after Ramanantsoa coup in Madagascar

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2382]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12826327/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12826328/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12826349/USA_play.zip) (Run the game to see what is happening)

### Describe the bug

When Republic of Madagascar became 'Malagasy Republic' due to FIPIMA taking over, changing its flag and tag color and then Ramanantsoa coup due to late selecting the 'Operation THERMIDOR' before FIPIMA changed the country, Ramanantsoa's Madagascar doesn't change to 'Republic of Madagascar' and its original tag color and flag and is not in the American economic sphere. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Malagasy Rebels wins the SMU.
3. PADESM wins
4. FIPIMA wins the election.
5. Select 'Operation THERMIDOR' a little late.
6. Republic of Madagascar becomes 'Malagasy Republic'.
7. FIPIMA switched to National Communism.
8. 'Operation THERMIDOR' success.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9cd5bb43-3431-4d20-9c58-686f22eb63ca)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8fcbfba9-70ba-48a9-ab64-245b1036633e)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Fixed in Dev Build
