### ISSUE TITLE
USA - Government or PPLN control in the Haitian states will increase is still appeared in 'The Status of the War' decision timer effect

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2383]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_HCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12827436/USA_HCW.zip)

### Describe the bug

In 'The Status of the War' decision timer effect shows that the Government or PPLN control in the Haitian states will increase is still appeared despite one of the Haitian states is fully controlled by the government or the PPLN.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the Haitian Civil War.
3. One of the Haitian states is fully controlled by the government and the rebels are crushed.
4. See 'The Status of the War' decision timer effect.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3b8a186d-331d-467f-8c2b-472659947068)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5cfcda85-c162-40f8-a3ef-d701f1f14321)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0f9013ed-be1a-4a4c-8ce8-15995e9d39f2)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d3f3d55b-61c8-4006-8827-3ddb41e2aa7a)

### Additional information

Not needed.

**Comment by runelead00** [comment]
Working as Designed
