### ISSUE TITLE
USA - There is a reference about the old Guyana skeleton content in 'Watching Too Much Television' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2384]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12828408/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12828409/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12828428/USA_play.zip)

### Describe the bug

After the PALF won the West African War scenario 3, the 'Watching Too Much Television' event description talks about the old Guyana skeleton content instead of talking about the PALF's dominant West Africa. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. West African War scenario 3 triggers.
3. The PALF wins the West African War scenario 3. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/92d74899-e969-4f0e-8240-e86abc2ecb23)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/306c9eba-9ffd-46fe-9205-7b91f11f4959)

**Comment by runelead00** [comment]
Fixed in Dev Build
