### ISSUE TITLE
USA/JAP - Move 'The Battle for Italy' proxy war to 'Global Conflicts' GUI

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2385]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest moving 'The Battle for Italy' proxy war from the decision tab to the 'Foreign Policy' GUI in the 'Global Conflicts' tab. 

### Justifications

Because I believe that 'The Battle for Italy' is the only proxy war that doesn't integrate with the new 'Foreign Policy' GUI while 'The Battle for England' has already moved to the 'Foreign Policy' GUI in the 'Global Conflicts' tab (if switching the old Britain content in the game rules before playing). So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2ede2f91-d145-4897-ab15-75a6e1fa8dd5)

**Comment by runelead00** [comment]
We are not moving and rebuilding a relatively complex gui to fopo menu that will be removed in a near future update
