### ISSUE TITLE
JAP - Philippine Reconstruction causes Japanese change in government instead of Filipino

### ISSUE THREAD

**Issue by Sherlock429008** [TNODevs/TNO-Bug-Tracker#2386]
### Operating System

macOS Ventura

### HOI4 version

1.12.14

### TNO version

1.5

### Do you have other mods in use?

Linear XP Gain, Mini-Mod Game Speed Boost, Radio TNO, Last Waltz Expanded, Toolpakt - Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

DOD, NSB, BBA

### Describe the bug

After winning the Balintawak Blitz as Japan, and finishing reconstruction, the event for Japan to pick a new Filipino President causes Japan to change ideologies and party popularity instead of the Philippines. 

### Steps to reproduce / Cause of the issue

1. Win Balintawak Blitz as Japan
2. Finish reconstruction decisions

### Expected behaviour

Expect a government change for the Philippines

**Comment by runelead00** [comment]
Fixed in Dev Build
