### ISSUE TITLE
USA - 'New Way Forward' achievement is not unlocked after selecting 'Initiate Troop Surge' and wins the HCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2387]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12829035/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12829036/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12829041/USA_play.zip) After committing troops surge
[USA_HCW.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12829081/USA_HCW.zip) Before committing troops surge

### Describe the bug

After the 'Initiate Troop Surge' decision is selected and the Haitian government wins the Haitian Civil War by either increasing control of all Haitian states or winning the battle against Haitian Revolutionary Front, the 'New Way Forward' achievement is not able to unlock despite the achievement requirements are met.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Start of the Haitian Civil War.
3. Start Withdrawal.
4. Select the 'Initiate Troop Surge' decision.
5. Win the Haitian Civil War by total government control of all Haitian states.

### Expected behaviour

I don't know what causes this and probably the `country_flag` has changed due to HCW revamped.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4a677f9a-b738-4d7a-92cb-b4c8d81794b8)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c6262017-7065-4c0f-babe-a9d7803b0302)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3b6c9375-2dbd-4860-8568-3fc9e0725876)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b1f76abe-7d23-43dd-8d92-71d1ceca1af3)

**Comment by runelead00** [comment]
Fixed in Dev Build
