### ISSUE TITLE
USA - 'Sabotagage Eastern Repatriation Infrastructure' operation requirement bug

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2388]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12831631/USA_play.zip)

### Describe the bug

The 'Sabotagage Eastern Repatriation Infrastructure' operation shows the requirement is $25M but the prerequisites in the hover box is $50M. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Speer won the German Civil War.
3. Speer's Germany proceeds to phase 2.
4. See 'Sabotagage Eastern Repatriation Infrastructure' operation requirement.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9c09ffc9-27e7-42cd-8cfc-b5a45691164b)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
