### ISSUE TITLE
USA - 'Sabotagage Eastern Repatriation Infrastructure' operation typo

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2389]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12831829/USA_play.zip)

### List the loc issues below

- [x] There is a misspelled word of 'Sabotagage' instead of 'Sabotage' word. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/09a4d223-ed32-4a82-9748-8066a060d47f)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
