### ISSUE TITLE
Ukraine - Event detailing the attack on Koch too early

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2390]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The event "The Old Commissar" mentions Koch's bombing several weeks early, where Koch is actually very much alive.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/6923590d-a116-4a7b-b8d3-bb8399786c06)

**Comment by runelead00** [comment]
Fixed in Dev Build
