### ISSUE TITLE
Ukraine - Missing name for FUK_power__struggle_RK_manpower_dynmod

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2391]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Missing name for the national spirit "FUK_power__struggle_RK_manpower_dynmod" which is acquired in "The New Hruchevsky" focus.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/7c170e5b-edc8-47f9-9980-804fe974234d)

**Comment by runelead00** [comment]
Fixed in Dev Build
