### ISSUE TITLE
Ukraine - Misspell in event "The Aftermath"

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2392]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Misspell of what I believe to be state as star on the line "cannot be considered to be under star control."
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/a1c04068-ab54-4173-a89f-9c5596f968ee)

**Comment by runelead00** [comment]
Fixed in Dev Build
