### ISSUE TITLE
Ukraine - Paternalism Ideology Unnamed

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2393]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Paternalism ideology is unnamed for Ukraine prior to the civil war.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/be3d064c-3faa-48fe-95da-b4c248dce26d)

**Comment by runelead00** [comment]
Fixed in Dev Build
