### ISSUE TITLE
Ukraine - Legacy of One Hundred missing icon.

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2395]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The National spirit "Legacy of the One Hundred" is missing it's icon.

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/1a939743-af5e-46ba-ba91-e14885772ad2)

**Comment by runelead00** [comment]
Fixed in Dev Build
