### ISSUE TITLE
USA - There are words "Australasia" and "Australasian" instead of using the current one

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2396]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12835940/USA_play.zip)

### List the loc issues below

- [ ] 1. In USA national focus, there are words "Australasia" and "Australasian" instead of "Australia" and "Australian" words. Because this national focus effect gives an event about "Australia", not "Australasia" and the use of old Oceania skeleton content reference. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5adb5cdd-4ffc-4187-b4c5-7aa8a95221e6)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7edd211e-a3a8-4ae5-9d71-f156373bd3d4)

**Comment by runelead00** [comment]
Working as Designed, Australasia is a geographic term, Australasia has never been a political entity in TNO
