### ISSUE TITLE
Ukraine - Event FUK_post_war.0.t incomplete

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2397]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The event FUK_post_war.0.t is missing essentially everything, name, description, options, photo.

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/73069c36-6555-4301-bf93-c1244510cb0a)

**Comment by runelead00** [comment]
Fixed in Dev Build
