### ISSUE TITLE
GRO/BOR - Afrika-Schild faction icon is replaced by generic faction icon after taking the 'Brudermord' focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2398]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836012/error.zip)
[game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836013/game.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836014/USA_play.zip)

### Describe the bug

After Reichskommissariat Ostafrika took the 'Brudermord' focus, Großafrikanischer Reichsstaat and Afrikaner Volkstaat's Afrika-Schild faction icon has changed to generic faction icon. 

### Steps to reproduce / Cause of the issue

1. South Africa War starts.
2. SAW is still ongoing.
3. Reichskommissariat Ostafrika selects 'Brudermord' focus.
4. Afrikaner Volkstaat becomes a puppet of Reichsstaat.
5. Two Reichskommissariats in Africa annexed by Hüttig.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fc33ccf5-606c-40fc-a760-32c2e5cb421a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e53846a1-d9f1-40c5-8330-eb6fdc090cd0)

**Comment by runelead00** [comment]
Fixed in Dev Build
