### ISSUE TITLE
Ukrainian Republic - Capital in Uman

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2399]
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

For some reason, the capital of the Ukrainian Republic is in Uman, as opposed to Kyiv.

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/1db41580-23e5-4329-9beb-14a006b5d49b)

**Comment by runelead00** [comment]
Fixed in Dev Build
