### ISSUE TITLE
CHI - "Change in war momentum" decision not removed after defeating Long Yun

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#240]
- Operating System: windows 10
- HOI4 Version: Collie 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? i own them all

The repeating "Change in war momentum" decision is not removed after defearting Long Yun as China, and hangs out forever

**Comment by tkgitno** [comment]
Fixed in Dev Build
