### ISSUE TITLE
Ukrainian Republic - Connections from the Collaborators missing description

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2400]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The Ukrainian Republic Focus "Connections from the Collaborators" has no description.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/ee47e221-b6b5-4269-8a1e-0d68313beda3)

**Comment by runelead00** [comment]
Fixed in Dev Build
