### ISSUE TITLE
Ukrainian Republic - Duplicate "Have" in focus dscription

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2402]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

For the Focus "The Graves We Dug" their is a duplicate "have" shortly after records are demanded.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/d0369766-8dea-4322-a961-756d1938c023)

**Comment by runelead00** [comment]
Fixed in Dev Build
