### ISSUE TITLE
USA - German intelligence network strength doesn't decrease after successful operation

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2403]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836341/USA_play.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836350/Logs.zip)

### Describe the bug

After selecting one of the 'Operations' to reduce German intelligence network strength in each region of the world, German intelligence network strength doesn't decrease somehow.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Either Bormann or Speer won the German Civil War.
3. Germany has the intelligence tab.
4. Select one of the 'Operations' to reduce German intelligence network strength in each world region. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/03fa0883-77af-4e3c-b1f0-13ee0687c64b)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d9c14d97-3982-4ac7-abde-cf3a06e84b03)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2c55b459-af98-4a29-a447-cdf3a39c1bc4)

**Comment by runelead00** [comment]
Fixed in Dev Build
