### ISSUE TITLE
USA - 'Safehouses in the <regional Russian warlord>' operation is impossible to unlock

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2404]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836367/USA_play.zip)

### Describe the bug

The 'Safehouses in the <regional Russian warlord>' operation requirement is impossible to unlock due to its prerequisites to have over 25 regional obfuscation but there are no operations to have an increased number of regional obfuscations. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. One of the Russian warlords who disliked Germany and Japan had a regional takeover.
3. Has the 'Safehouses in the <regional Russian warlord>' operation.
4. See the 'Safehouses in the <regional Russian warlord>' operation requirement.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/564648ef-8cc5-4f95-b477-b87ed7ca7257)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/67e0018b-2188-4baf-a095-7625ce7adbef)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7a157eec-8a88-47d6-b1b4-7405c8e2c91d)

**Comment by runelead00** [comment]
Fixed in Dev Build
