### ISSUE TITLE
GER/CAU - Some bugs after Speer's Germany reconquers Kaukasien

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2405]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836673/USA_play.zip)

### Describe the bug

- Kaukasische Militärregierung is not a 'Military Authority' faction status and 'Military Government' puppet status after Speer reconquers Kaukasien because the word "Militärregierung" meaning "Military government". So, Kaukasische Militärregierung should be a 'Military Authority' faction status and 'Military Government', not Autonomous Reichskommissariat. 
- Germany doesn't have resource rights on Kaukasische Militärregierung resources like oil and other resources after Germany takes all Kaukasien policy focus trees and reconquers Kaukasien. 

### Steps to reproduce / Cause of the issue

1. Speer wins the German Civil War.
2. Germany retakes former territories in Europe except the few.
3. Germany attacks Reichskommissariat Kaukasien 
4. Kaukasien becomes Kaukasische Militärregierung under Pleiger after Germany reconquers it.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/33ea0684-8d81-41b7-b1ef-7476c8e2bece)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/868ff7bd-7437-46f3-b389-e2f0ee1d29b7)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bc474d7b-575b-43ae-aee9-f2110e9b7e04)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2b1c7a7e-90d7-4b51-9aee-c340e4eb6a2b)

**Comment by runelead00** [comment]
Fixed in Dev Build
