### ISSUE TITLE
CHI - Missing GFX icon for 'Economic Integration of the Yun-Gui Region' national spirit

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2406]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836728/USA_play.zip)

### Describe the GFX issue

The 'Economic Integration of the Yun-Gui Region' national spirit has no unique GFX icon. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tag except Collab China.
2. Collab China has the 'Economic Integration of the Yun-Gui Region' national spirit

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/34d4db56-4d1d-4137-a069-b4e178388d4d)

**Comment by runelead00** [comment]
Fixed in Dev Build
