### ISSUE TITLE
All tags - 'Improved Armor-Piercing Medium Shell' takes less research time compared to others

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2408]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12836803/USA_play.zip)

### Describe the bug

The 'Improved Armor-Piercing Medium Shell' takes less research time compared to the 'Improved Armor-Piercing Light Shell' and 'Improved Armor-Piercing Heavy Shell' research time. 

### Steps to reproduce / Cause of the issue

1. Play as any content tags.
2. Select 'Naval Support' from the research tab.
3. See all 'Improved Armor-Piercing' research time.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3dcf83d5-9a35-4bb7-992e-eeb866797a98)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3e21523f-beb5-4106-93cd-760edf6a3732)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/532a879c-0d33-428a-bb46-af33c7e01ab8)

**Comment by runelead00** [comment]
Fixed in Dev Build
