### ISSUE TITLE
ENG (Thatcher) - English economic sphere from winning the influence battle for Britain is called No Sphere

### ISSUE THREAD

**Issue by austrianemperor** [TNODevs/TNO-Bug-Tracker#241]
**Questions**

Operating System: Windows 10
HOI4 Version: Whatever is up-to-date
TNO Version: 1.2.0 (no patches)
Any other mods in use: No
Were you using Steam? Yes
Which expansions do you NOT have?
None

**Longer Description of Issue:**
Self-explanatory
**Steps to Reproduce/Cause Issue:**

1. Win the race for influence as UK under Thatcher.

**Screenshots:*
![2021-11-22 (2)](https://user-images.githubusercontent.com/18901210/142833791-4210884b-ae33-4749-97c2-969b33f15e6d.png)
*

**Comment by runelead00** [comment]
Fixed in Current Release
