### ISSUE TITLE
ITA - Missing GFX icons for 'Fully Controlled Businesses' and 'Moderately Controlled Businesses' national spirits

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2412]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12837753/USA_play.zip)

### Describe the GFX issue

'Fully Controlled Businesses' and 'Moderately Controlled Businesses' national spirits have no GFX icons.

### Steps to reproduce / Cause of the issue

1. Ciano won the power struggle against Scorza.
2. Italy became a democracy.
3. Nenni wins the election.
4. Nenni towards the path to socialism.
5. A military coup (Lorenzo coup) occurred in Italy.

### Expected behaviour

Forgot to add GFX icon.  

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/89b936f6-f0ce-4b37-a378-ecfd6d9dce34)

**Comment by runelead00** [comment]
Fixed in Dev Build
