### ISSUE TITLE
ITA - 'Moderately Controlled Businesses' national spirit is not removed when 'Fully Controlled Businesses' national spirit appears

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2413]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12837771/USA_play.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12837772/Logs.zip)

### Describe the bug

The 'Moderately Controlled Businesses' national spirit is not removed when 'Fully Controlled Businesses' national spirit appears or merges with 'Fully Controlled Businesses' national spirit. 

### Steps to reproduce / Cause of the issue

1. Ciano won the power struggle against Scorza.
2. Italy became a democracy.
3. Nenni wins the election.
4. Nenni towards the path to socialism.
5. A military coup (Lorenzo coup) occurred in Italy.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d2ed21a4-2a37-483b-b006-566e4c07d64e)

**Comment by runelead00** [comment]
Fixed in Dev Build
