### ISSUE TITLE
ITA - There is a "placeholder" word in some national spirits' description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2414]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12837918/USA_play.zip)

### List the loc issues below

- [ ] 1. 'Fully Controlled Businesses' and 'Moderately Controlled Businesses' national spirits.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6ec23bd8-8e4b-4603-946f-73aa8026faa3)
- [ ] 2. 'Disordine' and 'Operative Connections' national spirits.
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/03b92b68-6b01-46da-a586-f42abe7eeb5a)

**Comment by runelead00** [comment]
Replaced w/ blank descs
