### ISSUE TITLE
Spain - GNS peace deal broken

### ISSUE THREAD

**Issue by ds-xiaoyi** [TNODevs/TNO-Bug-Tracker#2415]
### Operating System

windows11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Iberian War, the Blue Front fought Portugal, and only signed an armistice and did not puppet the failure to enter the unity agreement，Version 1.4.1.d does not have this bug, it can be puppeted normally, version 1.5.0 I tried twice but could not puppet and only signed an armistice

### Steps to reproduce / Cause of the issue

Presuppose the collapse of Iberia, the collapse of the Falange, and the victory of the Spanish Civil War by the Blue Front

### Expected behaviour

I'm making the maximum extent of the solidarity agreement, please fix it as soon as possible, thanks

### Screenshots

![2023-10-07](https://github.com/TNODevs/TNO-Bug-Tracker/assets/102014915/ea0c8971-8933-43e3-9799-3e0c2f426e63)

**Comment by runelead00** [comment]
#1509 We need saves prior to broken peace deal to actually properly fix them

**Comment by ds-xiaoyi** [comment]
> #1509我们需要在和平协议破裂之前进行保存，以实际正确修复它们

The game does not crash, you can try to set the Iberian collapse in advance, the Falangist collapse, jump to the blue front to play, can't puppet Portugal, I have provided as much information as I can

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by ds-xiaoyi** [comment]
> 已在 Dev Build 中修复
But it's not fix in 1.5.0.b,the bug still exists...
