### ISSUE TITLE
USA - Political Power suddenly decreases to 300 when the new or re-elect president event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2417]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12839674/USA_play.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12839718/Logs.zip)

### Describe the bug

USA's political power shrunk to 300 when the new or re-elected president event triggered because USA had lots of PP carrying before the event. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Have lots of Political Powers.
3. New or re-elected president event triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d664d72e-e33c-4ee7-8d5d-233b95031758)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c159a730-14e9-4d41-bcc9-61f11ec3a1fb)

**Comment by runelead00** [comment]
Working as Desinged
