### ISSUE TITLE
USA - Hubert Humphrey is not leader of the Labor Democrat after 'Season's Greetings' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2419]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12841944/USA_play.zip)

### Describe the bug

After selecting the 'Season's Greetings' event that Hubert Humphrey will become the leader of the Labor Democrat in 'Smoke and Mirrors' decisions according to this event, Hubert Humphrey is not the leader of the Labor Democrat but instead, James G. O'Hara becomes the leader of the Labor Democrat.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Hart as the new president.
3. Complete 'The Hart Presidency' national focus.
4. Select the 'Season's Greetings' event.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c9da89d1-e6f2-4a88-a154-b2bad498e6d1)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2109e4da-9288-46cb-a456-752fbd81ef8b)

**Comment by runelead00** [comment]
Fixed in Dev Build
