### ISSUE TITLE
ENG (Thatcher) - Trade law disappears relatively early in the game

### ISSUE THREAD

**Issue by austrianemperor** [TNODevs/TNO-Bug-Tracker#242]
**Questions**

Operating System: Windows 10
HOI4 Version: Whatever is up-to-date
TNO Version: 1.2.0 (no patches)
Any other mods in use: No
Were you using Steam? Yes
Which expansions do you NOT have?
None

**Longer Description of Issue:**
The trade law under economic policies disappears; there is simply no trade law. 
**Steps to Reproduce/Cause Issue:**

1. Play as England under Thatcher and go for full-scale economic reform, not heeding elite worries.

I'm not sure when it exactly happened but it happened pretty early into Thatcher's premiership. There've been many many law changes boosting trade that have showed up as not doing anything in her focus tree.

**Screenshots:*
![2021-11-22 (3)](https://user-images.githubusercontent.com/18901210/142834720-90b34bdf-8ca3-4f8d-9575-6dd2a54ee58c.png)
*

**Comment by runelead00** [comment]
Fixed in Current Release
