### ISSUE TITLE
TNZ/ZZB - Republic of Tanganyika and People's Republic of Zanzibar are at war without border between them

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2420]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12842109/Logs.zip)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12842110/autosave.zip) Run the game to see what is happening

### Describe the bug

When the Republic of Tanganyika declares on People's Republic of Zanzibar, they are not border with each other because the People's Republic of Zanzibar has a border only with is Zanzibari Socialist Republic to the left.  

I think the People's Republic of Zanzibar and Zanzibari Socialist Republic should be at war with each other because they are both Zanzibar and border with each other. 

### Steps to reproduce / Cause of the issue

1. Afrika-Schild survives after the SAW.
2. Republic of Tanganyika revolts and success against Reichstaat in devastation stage 1.
3. Reichstaat collapsed in devastation stage 3.
4. Republic of Tanganyika declares on People's Republic of Zanzibar. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e7cc05f5-5889-4587-a801-dd6ee011e9da)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6b41b7a8-5371-43d5-8a4e-53f40b1bc644)

**Comment by runelead00** [comment]
Fixed in Dev Build
