### ISSUE TITLE
JAP - Galician Republic and Gibraltar Protectorate are not included in The Iberian Wars decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2422]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[JAP.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12842645/JAP.zip)

### Describe the bug

Galician Republic and Gibraltar Protectorate are not included in the sending volunteers' national spirit after selecting the 'Intervention in Iberia' decision, 'sending equipment decisions' and 'Supply Regional Merchant Marine' decision effect despite The Iberian Wars GFX maps show that the Galician Republic and Gibraltar Protectorate are marked green. 

### Steps to reproduce / Cause of the issue

1. Iberia stability is critically unstable.
2. Iberian Wars triggers.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/cb857b20-cac8-422d-8eb9-e5a50b5b3999)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/cd1d8b43-8fca-42be-88fe-b76a2cd84c7f)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/30928cf6-1508-497f-a703-c10a1d29906d)

**Comment by runelead00** [comment]
Fixed in Dev Build
