### ISSUE TITLE
DOM - Trujillo's Dominican Republic should join the German economic sphere and probably join the Pakt observer if Iberian Federal Government doesn't exist

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2424]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Describe your suggestion

I would like to suggest that Trujillo's Dominican Republic should join the German economic sphere and probably join the Pakt observer if Iberian Federal Government no longer exists which means defeated during the Iberian Wars.

### Justifications

Because Germany previously supported Trujillo during the PPI and has influence in the Dominican Republic (practically in intelligence service), Trujillo's Dominican Republic should join the German economic sphere and probably join the Pakt observer in order to safeguard Trujillo's Dominican Republic from another invasion that Iberian Union is no longer provide support due to Iberian collapsed.

**Comment by runelead00** [comment]
Rejected
The main economic power in a country vanishing does not mean that all that power immediately falls into hands of another foreign power, especially when that power is far less directly involved
