### ISSUE TITLE
DOM - Some bugs after López deposed

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2425]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12844130/USA_play.zip)

### Describe the bug

There are some of López's national spirits that weren't removed and the Economy type didn't change from 'Worker Directed' after López deposed.  

### Steps to reproduce / Cause of the issue

1. PPI starts.
2. Caribbean Legion/Dominican Revolutionary Front wins the Dominican Civil War. 
3. López taking control.
4. Dominican Cultural Revolution triggers.
5. Tavárez coup success.
6. Juan Bosch takes power.
7. Rafael Bonnelly takes power. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/64253f02-a5ec-4f25-b505-6c8c39654006)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fc1ffe9c-5e83-4b37-93a4-a714e8139c9a)

**Comment by runelead00** [comment]
Fixed in Dev Build
