### ISSUE TITLE
USA - Gain power projection on Mediterranean if Spanish Republic/Kingdom of Spain wins the Iberian Wars

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2426]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest adding power projection on the Mediterranean for USA if the Spanish Republic/Kingdom of Spain wins the Iberian Wars because Spain has the coasts on the Mediterranean. 

### Justifications

Because if the Spanish Republic/Kingdom of Spain wins the Iberian Wars, Japan would have a power projection on the North Atlantic due to Galicia and Basque are Sphere observers and have Japanese economic sphere and Spanish Republic/Kingdom of Spain is unable to take the separatists. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/43e44ca0-0481-49dc-b718-20b526625555)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e0a18335-8824-4c0d-b5c6-f2930296d82c)

**Comment by runelead00** [comment]
Japan should not being getting sea zone access from the Iberian Wars, removed in dev build
