### ISSUE TITLE
RIF - Rif Republic joins the Co-Prosperity Sphere and Sphere Observer after Iberian Wars despite still at war with Morocco

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2427]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12844705/USA_play.zip)

### Describe the bug

When the Spanish Republic/Kingdom of Spain defeated both the Iberian Federal Government and Falangist Spain, the Rif Republic somehow joined the Co-Prosperity Sphere and Sphere Observer despite still at war with Morocco. 

### Steps to reproduce / Cause of the issue

1. The Iberian Wars triggers.
2. Northwest African war triggers.
3. The Spanish Republic/Kingdom of Spain won the Iberian Wars.
4. Rif Republic joins the Co-Prosperity Sphere and Sphere Observer despite being at war with Morocco.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/318e0eda-84ea-44d3-9dab-8375e26924a4)

**Comment by runelead00** [comment]
Fixed in Dev Build
