### ISSUE TITLE
USA - There is no voter effects in 'Iberian Cascade' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2428]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12844876/USA_play.zip)

### Describe the bug

After the Spanish Republic/Kingdom of Spain won the Iberian Wars, there is no voter effects in the 'Iberian Cascade' event and including the defeat in the Iberian Wars event. 

### Steps to reproduce / Cause of the issue

1. The Iberian Wars triggers.
2. The Spanish Republic/Kingdom of Spain won the Iberian Wars.

### Expected behaviour

Forgot to add effects.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bef7aa70-4416-44a2-9f6d-4d52e94aab8b)

**Comment by runelead00** [comment]
Fixed in Dev Build
