### ISSUE TITLE
USA - No "TOP" word before "SECRET" word in 'Iberian Cascade' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2429]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In the 'Iberian Cascade' event, there is no "TOP" word before the "SECRET" word.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3c85be70-6d81-4194-86ab-49df96e369a7)

**Comment by runelead00** [comment]
Working as Designed
