### ISSUE TITLE
USA/OFN Mandates/Bosnia - Generic portraits instead of intended leaders

### ISSUE THREAD

**Issue by kolebaby12** [TNODevs/TNO-Bug-Tracker#243]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: State transfer tool
- Were you using Steam?: Yes
- Which expansions do you NOT have?: None

**Longer Description of Issue:**
Following Nixon's resignation and the assassination of JFK, all leaders afterwards showed up as generic, faceless placeholder portraits with randomly generated names. This continued throughout the rest of the game, with leaders being changed through elections but not to any actual intended president. This affected the Mandate(s) in Africa, as well.
This also happened in Bosnia when Italy invaded Croatia. Curiously, Croatia and Serbia were fine - It was just Bosnia having this issue.
**Steps to Reproduce/Cause Issue:**

Unfortunately, I'm unsure how you would go about recreating this. From what I can tell, it started right after JFK was assassinated, when McCormack took office(though obviously, the leader wasn't McCormack)

**Screenshots:*
![20211121141223_1](https://user-images.githubusercontent.com/94831964/142835319-69de486b-a482-4cd1-a61d-6d8022146ed9.jpg)
![20211121150919_1](https://user-images.githubusercontent.com/94831964/142835355-69d0d898-4227-4bc8-89ae-3031eed90d5f.jpg)
![20211121153658_1](https://user-images.githubusercontent.com/94831964/142835412-3e5aa754-b126-46d1-a768-f2c5ebf166c5.jpg)
![20211121090003_1](https://user-images.githubusercontent.com/94831964/142835653-8f03ed23-e591-4e4f-9983-83abc5268e39.jpg)

**Comment by runelead00** [comment]
Fixed in Current Release
