### ISSUE TITLE
GNS - Bugs after Spanish Republic defeats Government of National Salvation

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2430]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12846678/Logs.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12846686/USA_play.zip)

### Describe the bug

Portugal uses the Government of National Salvation flag instead of the Portuguese Republic flag, has a generic leader, no portrait and generic traits, has generic puppet party ideologies pie chart shown, and still has the National Socialist advisers instead of removing them.

### Steps to reproduce / Cause of the issue

1. The Iberian Collapsed.
2. The Iberian Wars triggers.
3. Spanish Republic wins the Iberian Wars.
4. Government of National Salvation wins the Portuguese Civil War.
5. Government of National Salvation attacked Spanish Republic.
6. Spanish Republic defeats Government of National Salvation.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9e2ffd4a-7837-4222-96d2-f93bcc28b0db)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9c379690-cb2e-4bb4-ad20-18edf7e819c3)

**Comment by runelead00** [comment]
Fixed in Dev Build
