### ISSUE TITLE
Free France - Portrait of Charles De Gaulle is missing

### ISSUE THREAD

**Issue by VoyteckGit** [TNODevs/TNO-Bug-Tracker#2431]
### Operating System

Fedora 38

### HOI4 version

1.12.14

### TNO version

1.50

### Do you have other mods in use?

nonw

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Charles de Gaulle has no portrait as a leader of Free France, it is replaced by a generic one

### Steps to reproduce / Cause of the issue

1. Go to the diplomatic menu, and choose Free France
2. See that the Free French leader is absent
3. Go trough an existential crisis

### Expected behaviour

De Gaulle has a portrait, like before 1.50

### Screenshots

![Screenshot from 2023-10-09 19-34-09](https://github.com/TNODevs/TNO-Bug-Tracker/assets/127428612/c993d0b0-ea5b-46c0-b831-53c8e6d51a82)

**Comment by runelead00** [comment]
Can't Reproduce, portrait appears properly on release build, would recommend reinstall to see if that fixes it
