### ISSUE TITLE
GNA - Portugal declares war on three Iberian separatists despite being puppet

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2432]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12851025/Logs.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12851035/USA_play.zip) Ryn the game to see what is happening

### Describe the bug

Spanish Republic's puppet Portugal can declare war on three Iberian separatists, Galicia, Basque and Catalonia. Puppet Portugal shouldn't do this. 

Probably the Iberian wars/Exhausted Nation national spirit caused this because the national spirit still existed after Spanish Republic defeated GNS. 

### Steps to reproduce / Cause of the issue

1. The Iberian Collapsed.
2. The Iberian Wars triggers.
3. Spanish Republic wins the Iberian Wars.
4. Government of National Salvation won the Portuguese Civil War.
5. Government of National Salvation attacked Spanish Republic.
6. Spanish Republic defeats Government of National Salvation.
7. Puppet Portugal(GNS) declares war on three Iberian separatists.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/04b72eb0-c982-4f20-9f90-a118ae86a447)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4c798686-ed78-4058-a026-6cb51121f58c)

**Comment by runelead00** [comment]
Fixed in Dev Build
