### ISSUE TITLE
ITA - 'The Extremist's Handprint' national spirit still has no GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2434]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12851252/USA_play.zip)

### Describe the GFX issue

'The Extremist's Handprint' national spirit and its modifiers still have no GFX icon. 

### Steps to reproduce / Cause of the issue

1. Galeazzo Ciano secures his position.
2. Italy became a democracy.

### Expected behaviour

Forgot to add GFX icon.  

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b49bb18a-54f0-4faf-aebf-c1c302b89fb7)

**Comment by runelead00** [comment]
Fixed in Dev Build
