### ISSUE TITLE
USA - 'The Industrial Arm' national spirit somehow appeared and without its effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2437]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12855925/Logs.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12855998/USA_play.zip)
[USA_Hart_2.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12856000/USA_Hart_2.zip)

### Describe the bug

Playing as Hart's USA, there is 'The Industrial Arm' national spirit appeared and without its effects after doing some transportation national focuses. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Hard as the new president.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2a2751a8-cb42-4d67-8e9f-a444a87879d2)

**Comment by runelead00** [comment]
Fixed in Dev Build
