### ISSUE TITLE
USA - Sending volunteers to Mendi still exists in 'Military Advisor' national spirit after the Mano Campaign

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2441]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12858128/USA_play.zip)

### Describe the bug

After the OFN declared support for the Mano Pact and the Mano Campaign ended, sending volunteers to Mendi still exists in the 'Military Advisor' national spirit. 

### Steps to reproduce / Cause of the issue

1. The PALF victory in the West African War.
2. The Oil Crisis triggers.
3. PALF invades Liberia and Mendi State, and triggers the Mano Campaign.
4. USA and OFN intervened.
5. OFN mobilization in West Africa is completed.
6. The Mano Pact was held, and PALF and OFN ceasefire. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/789c2721-c417-4f92-a865-87370f787d65)

**Comment by runelead00** [comment]
Fixed in Dev Build
