### ISSUE TITLE
USA - Add voters' effects in the aftermath of the Channel Crisis event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2442]
### HOI4 version

1.12.14

### TNO version

1.5.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest adding the voters' effects in the aftermath of the Channel Crisis event. 

### Justifications

Because most USA's proxy wars have the voters' effects in the aftermath of the proxy war events. So, that is why I suggest this.

**Comment by runelead00** [comment]
Added in Dev Build
