### ISSUE TITLE
Japan - Can't Send Volunteers to Malaya (Shonan-Marai Gunseibu)

### ISSUE THREAD

**Issue by hhikon** [TNODevs/TNO-Bug-Tracker#2444]
### Operating System

Windows 10

### HOI4 version

1.13.0

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

As Japan, I can't send volunteers to Malaya (Military Governorate of Shonan-Marai) to fight the insurgents. The volunteer screen is blank where my divisions would be.

I was playing Japan right before this new update and I could send volunteers fine.

### Steps to reproduce / Cause of the issue

1. Play Japan
2. Select the Military Governorate of Shonan-Marai, your puppet
3. Click "Send volunteers" in the diplomacy screen 

### Expected behaviour

My divisions should be appearing in their armies with their generals

### Screenshots

https://cdn.discordapp.com/attachments/806276324297539586/1161364836547051670/20231010140754_1.jpg?ex=6538084a&is=6525934a&hm=c9e25471ef079a48c1fc837514bf0294f4758fb72440d0f24a1d8832c34ae90f&

![20231010140754_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/79466618/9286d320-fb79-497f-a584-b804a1e5dbdc)

### Additional information

I don't have Arms Against Tyranny, the newest expansion

**Comment by runelead00** [comment]
Fixed in Current Release Build
