### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Fafafafafafafafaffafa** [TNODevs/TNO-Bug-Tracker#2445]
### Operating System

Win10

### HOI4 version

1.13

### TNO version

The Ruin

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When trying to send volunteers, armies are not shown

### Steps to reproduce / Cause of the issue

Just play as Japan and wait for the proxy in Malaya

### Expected behaviour

 Just bring back the army

### Screenshots

![Снимок экрана (234)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/147547613/86eb7555-4b0f-4706-8b68-d62df4394401)

**Comment by runelead00** [comment]
Fixed in Current Release Build
