### ISSUE TITLE
USA (all?) - CTD on selecting traits for generals

### ISSUE THREAD

**Issue by kendallizer** [TNODevs/TNO-Bug-Tracker#2446]
### Operating System

Windows 10

### HOI4 version

Stella Polaris v1.13.1.0fd4

### TNO version

TNO v1.5.0a - "The Ruin" October 10th, 2023

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

[CTD traits.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12860840/CTD.traits.zip)

### Describe the crash

Pressing the "Click to assign a new Trait to this Unit Leader", either in the top left, or the bottom of the screen where the cards are, CTDs. 

### Steps to reproduce / Cause of the crash

1. Assign divisions to a group
2. Assign a general to those divisions
3. Select "Click to assign a new Trait to this Unit Leader"

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/144939338/554ab7b3-da6a-4b3a-81f8-35013cae3aa5)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/144939338/7d7eebc6-8f46-4293-8e03-e8d11e035560)

**Comment by kendallizer** [comment]
Here's a log, sorry, forgot to add it! 
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12860888/error.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12860890/error.log)

**Comment by runelead00** [comment]
Fixed in Current Release Build

**Comment by kendallizer** [comment]
> Fixed in Current Release Build

Thank you so much!!!
