### ISSUE TITLE
i was playing as guangdong and when i was ready to send volunteers to malysia, i couldnt because none of my armies showed up meaning i couldnt send any volunteers (sorry if i spelt anything wrong)

### ISSUE THREAD

**Issue by ripple0428** [TNODevs/TNO-Bug-Tracker#2447]
### Operating System

windows 11

### HOI4 version

1.13.1

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

when i went to send volunteers to Malaysia i couldn't send any because the option to select what army you want to send didn't appear and it was just a blank box i could still send air volunteers though.

### Steps to reproduce / Cause of the issue

I don't know how it happened.

### Expected behaviour

when i click "send volunteers" it should pop up with an option to select which army to send.

### Screenshots

![Screenshot 2023-10-10 204906](https://github.com/TNODevs/TNO-Bug-Tracker/assets/147574309/c300513d-c706-4a70-b7fb-22469c2ea38d)

**Comment by runelead00** [comment]
You need to wait for steam to download the next hotfix/force update the mod. Fixed in Current Release

**Comment by ripple0428** [comment]
ok cool thanks
