### ISSUE TITLE
ENG - Rename the 'South Yorkshire' state to be 'West and South Yorkshire' or 'South and West Yorkshire'

### ISSUE THREAD

**Issue by BRUHADDICT4U** [TNODevs/TNO-Bug-Tracker#2448]
### HOI4 version

1.13.1

### TNO version

v1.5.0a 'the ruin'

### Describe your suggestion

Rename 'South Yorkshire' to be 'West and South Yorkshire' as the rest of the county names for in game states seem to use those provided by the Local Government act 1972, if you are however using a source from pre divergence to name the Counties then that's completely fine.

### Justifications

Making a 2 tile state would be completely impractical so simply adding the distinction would make more sense, this has already been done with both Dorset and Somerset being merged into a single state.

**Comment by runelead00** [comment]
Updated for a future patch
