### ISSUE TITLE
Germany - focus tree disappearing

### ISSUE THREAD

**Issue by JanKazimierz** [TNODevs/TNO-Bug-Tracker#2449]
### Operating System

Windows 10

### HOI4 version

1.13.2

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Describe the bug

When playing as Germany (Speer, didn't test as Bormann) after taking the decision to restore Ukraine (collabs won) to the Pakt, focus tree goes blank after the decison takes effect. If you then take decision about Kaukasia, focuses are restored but they're all uncompleted.

### Steps to reproduce / Cause of the issue

1. Play Speer as usual
2. Try restoring RK Ukraine to the Pakt

### Expected behaviour

Obviously, I expected that focus that focus tree doesn't disappear

**Comment by runelead00** [comment]
Fixed in Dev Build
