### ISSUE TITLE
ENG (Thatcher) - Wrong law put in Parliament from focus

### ISSUE THREAD

**Issue by austrianemperor** [TNODevs/TNO-Bug-Tracker#245]
**Questions**

Operating System: Windows 10
HOI4 Version: Whatever is up-to-date
TNO Version: 1.2.0 (no patches)
Any other mods in use: No
Were you using Steam? Yes
Which expansions do you NOT have?
None

**Longer Description of Issue:**
Indirect Taxation Act focus instead brings Fair Employment Act in Parliament. 
**Steps to Reproduce/Cause Issue:**

1. Take Indirect Taxation Act focus.

**Screenshots:**
![2021-11-22 (5)](https://user-images.githubusercontent.com/18901210/142837820-bc19e842-6e5d-49fb-a6cc-4e279edd3249.png)
![2021-11-22 (4)](https://user-images.githubusercontent.com/18901210/142837822-2494a4e6-092e-4584-ac3a-92394cd5aeb4.png
![2021-11-22 (7)](https://user-images.githubusercontent.com/18901210/142838010-4739532a-0ff9-4eaa-b0af-8578337af191.png)
)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
