### ISSUE TITLE
UK & Ireland - Belfast and London share same image

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2451]
### Operating System

Windows 10

### HOI4 version

1.13.2

### TNO version

1.5.0a

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Belfast and London share the same picture.

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/13d94586-cbf0-4656-a930-24ceca1886cd) 

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/13d28684-c39a-4135-a032-f66282136f95)

### Additional information

It appears that Belfast uses the same picture as London, as opposed to it having no picture and just pulling from other cities.

**Comment by runelead00** [comment]
Fixed in Dev Build
