### ISSUE TITLE
All Countries - population disappear because of irk's decision

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2452]
### Operating System

Windows 11

### HOI4 version

1.13.1

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

At some point, the population of any states may drop significantly or even go 0
This bug has been here since 1.4.1, perhaps longer
the states where this bug occurs are all over the world, but it's not completely random, always happens on Deserts, villages, islands and enclaves, but they all fall to -$1 per capita in map when this bug occurs
Also, population disappear is not happening at the end of the month when population counts, it happens in the middle of the month
the time when bug happens is not random either, it has a fixed time, across 1968-1970
I even tried to delete all files in tno -common- scripted_effects (pretty sure i deleted them all) and I saw the gdp per capita map stopped working
but the population bug still HAPPENED

if you disable AI at all times, this bug won't happen
As mentioned above, deleting all of tno's scripted effects files can't fix it, so this is most likely fault of original hoi4
please don't close this issue report, i'll post them if i find something more useful

### Steps to reproduce / Cause of the issue

TNO-common-decisions-TNO_RUS_Irkutsk_decisions
in decision IRK_party_reform_4, this decision will add city population and reduce village and islands population
but it used "every_state" not "every_controlled_state", that means it will influence whole world...
who wrote this part should be killed

### Expected behaviour

this bug never, never happens anymore

**Comment by MrStraws114514** [comment]
No, the effect of reducing population must be completely removed
even use "every_controlled_state", it will still cause the population of parts of Irkutsk to 0

**Comment by runelead00** [comment]
honestly the effect doesn't make much sense at all for the decision itself,
effect adjusted and fixed in dev build
