### ISSUE TITLE
West Africa - State flags don't remove when WAC ends

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2453]
### Operating System

Windows 11

### HOI4 version

1.13.1

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

if Cameroon vs Free French allience and war ends, state flag "soild frontline" won't be removed, no matter who wins
This also makes cameroon collapse war endless

### Steps to reproduce / Cause of the issue

TNO - common - scripted_effects - TNO_WestAfrica_Crisis_scripted_effects
in WAC_2_PALF_VICTORY and WAC_2_PALF_BEATEN, add this:
						every_state = {
			remove_province_modifier = {
				static_modifiers = { soild_frontline }
				province = { all_provinces = yes }
			}
		}

### Expected behaviour

province modifier disappears after war

**Comment by MrStraws114514** [comment]
solid, not soild

**Comment by runelead00** [comment]
Do you have a save where this occurred, this should never happen outside of Scenario 3

**Comment by runelead00** [comment]
Fixed in Dev Build? I think you were misunderstanding the code and your suggested fix is the wrong block of code
