### ISSUE TITLE
South Africa - When SAW ends in total South African victory, mandates don't form

### ISSUE THREAD

**Issue by DRMkid** [TNODevs/TNO-Bug-Tracker#2455]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.2

### TNO version

1.5.0a

### Do you have other mods in use?

150 dockyards, No division limit, Resource rights GUI, Toolpakt

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the South African war ends in total OFN victory, the mandates don't form and South Africa ends up just occupying all the territory of the African RKs. There's also no news event for the SAW ending. I've noticed this while playing South Africa, but also while playing Guangdong, Japan, and Ireland. In my latest game where this occurred, Speer intervened in the war, but I'm not sure if German intervention changes anything. Also, Huttig reached the end of his tree and formed the bigger RK by absorbing the other two during the war, but I've also observed the bug even when he has not absorbed the other two RKs.

### Steps to reproduce / Cause of the issue

1. Play TNO as any country
2. Have the South African war occur
3. OFN wins a total victory
4. Observe as mandates are not created and no news event pops up

### Expected behaviour

I expected for the African OFN mandates to form and for the news event for total OFN victory to pop up.

### Screenshots

![20231012131312_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146794384/e7dde9cf-5559-4001-8f03-b05be5666d34)

**Comment by runelead00** [comment]
Saves before a peace deal are needed to actually fix them #1509
