### ISSUE TITLE
GER/CRI - Germany doesn't get back Crimea after hegemony reestablished

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#2456]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Files

[Uploading error.log…]()
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12887017/game.log)

### Describe the bug

Even after getting the news event about Germany hegemony being restored and Germany having all of its other prior possessions back, they never touched Crimea.

### Steps to reproduce / Cause of the issue

1. Go forward in time until Germany gets all other possessions.
2. Note that Crimea remains untouched.

### Expected behaviour

Germany would annex Crimea before this happens.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/7cb0f8b0-2dac-4ad1-8113-e718c1642712)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/f184b94a-9d8c-4c0b-86a6-92df12e9d6b4)

### Additional information

Note: Onega still existing in one of the screenshots is just on part for West Russia unifying late (year of the screenshot is 1968).

**Comment by runelead00** [comment]
Fixed in Dev Build
