### ISSUE TITLE
GER - Focus Tree disappears after Ukraine rejoins Pakt

### ISSUE THREAD

**Issue by RedStarIsDead** [TNODevs/TNO-Bug-Tracker#2457]
### Operating System

Windows 10

### HOI4 version

1.13.2

### TNO version

v1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

Playing as Bormann's Germany, when the selected 'The Ukrainian Problem' decision was removed, so is the entire focus tree. I've been able to consistently replicate this bug, and whilst I haven't tested it out myself around a dozen other people in the discord server have experienced the same bug as Speer's Germany.

### Steps to reproduce / Cause of the issue

1. Play as Germany (Bormann or Speer, but I've only tested with Bormann)
2. Once you get access to the 'Reclaiming the Pakt' decisions, click the decision to deal with 'The Ukrainian Problem'
3. After 20 days, the entire German focus tree should be gone/reloaded

### Expected behaviour

Game continues as normally/no focus tree reload

### Screenshots

https://github.com/TNODevs/TNO-Bug-Tracker/assets/44728396/f16c4b99-47bf-4c1f-9ece-e5c456248cb6

**Comment by runelead00** [comment]
Fixed in Dev Build
