### ISSUE TITLE
Ireland- Parents instead of grandpartens

### ISSUE THREAD

**Issue by Butterspekulatius** [TNODevs/TNO-Bug-Tracker#246]
**Questions**

- HOI4 Version: current
- TNO Version: 1.2.0b Toolbox Theory
- Any other mods in use: Terra e Libertá

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

Event:  A Famlily Evening

A really small one in the first sentence.

Eoin and Maggie Ward had been staying with their parents for the weekend as their parents went on a business trip.

It should be grandparents instead of parents, when parents is first used.

[20211122110023_1](https://user-images.githubusercontent.com/38876624/142841740-689a350e-257a-4169-bf76-3c5e7f077121.jpg)

**Comment by runelead00** [comment]
Fixed in Current Release
