### ISSUE TITLE
Irkutsk and potentially all Far East unifiers - Yakutia instantly annexes warlords that declare war on them

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#2461]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

Yakutia just instantly annexes any Far Eastern warlord that declares on them

### Steps to reproduce / Cause of the issue

1. Just wait until a Far Eastern unifier declares on Yakutia

### Expected behaviour

Whoever declares war on Yakutia should eventually defeat them

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/143363540/56b8c379-ba59-4281-9ed6-1b2391aec294)

**Comment by runelead00** [comment]
#1509 Do you have a save before the peace deal

**Comment by runelead00** [comment]
Nvm figured it out, PDX changed how every_enemy_country is treated, fixed in Dev Build
