### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by kylebentl** [TNODevs/TNO-Bug-Tracker#2462]
### Operating System

Windows 11

### HOI4 version

1.13.1

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA, AAT

### Describe the bug

Unites States Of America Foreign Policy is blank if RFK is president if reloading a save after total OFN victory in South African War

### Steps to reproduce / Cause of the issue

1. Have RFK be president
2. Have a total OFN victory in South African War
3. quit game
4. reload save

### Expected behaviour

able to see the american foreign policy screen as normal

### Screenshots

![Screenshot 2023-10-14 023231](https://github.com/TNODevs/TNO-Bug-Tracker/assets/141360327/5131400a-bc88-434c-b3fe-788a5a8080f8)

### Additional information

not entirely sure what the cause was. only my best guess

**Comment by runelead00** [comment]
Was likely caused by a HoI4 hotifx, not an issue we can fix (we had a few others report similar issues after last hotfix)
