### ISSUE TITLE
IRQ - IQR_italian_interference_desc

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2463]
### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/9717fe98-c26d-4945-ac05-9952f875121d)

**Comment by runelead00** [comment]
Fixed in Dev Build
