### ISSUE TITLE
YEM - Ahmad Bin Yahya desc

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2464]
### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The ruler of Yemen is named Ahmad Bin Yahya, but in his bio a different spelling is used - Yaha instead of Yahya.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/9faf7bf3-869b-4c4c-b873-a81305597cc1)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
