### ISSUE TITLE
Buryatia (Recently formed Far Eastern Soviet Republic) - Crashing to Desktop on specific date.

### ISSUE THREAD

**Issue by Jerjudo10** [TNODevs/TNO-Bug-Tracker#2465]
### Operating System

Windows 10

### HOI4 version

Stella Polaris v1.13.3.f717 (e134) (S)

### TNO version

TNO v1.5.0a - ''The Ruin''

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12904580/error.log)

[Ironman Buryatia 1.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12904589/Ironman.Buryatia.1.zip)

### Describe the crash

Before the crash date, the game runs normally as expected. At exactly 01:00, 25 November 1963 the crash happens. The game freezes, but then quickly closes itself and opens a Paradox crash report.

### Steps to reproduce / Cause of the crash

1. Download the save file.
2. Start the game with said game file. (Should start on 12:00, 24 November 1963 if i'm not mistaken)
3. Unpause the game and wait for the crash to happen on 01:00, 25 November 1963.

Otherwise i have no clue on how to reproduce this in a new game besides playing as buryatia and waiting untill the crash date.

### Additional information

I haven't the slightest clue what causes this.

**Comment by runelead00** [comment]
Game was started before the 1.5.0a hotfix, incompatible with current version
