### ISSUE TITLE
Game doesn't load past start screen

### ISSUE THREAD

**Issue by Gamingnoepic** [TNODevs/TNO-Bug-Tracker#2466]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12908257/error.log)

### Describe the crash

The game will reach the loading screen and maybe get to 3/4ths of the way. Then it will suddenly stutter for 3-4 seconds, come back for another 2, and promptly crash to desktop.

### Steps to reproduce / Cause of the crash

1. Open HOI4
2. Enable TNO mod
3. Start game
4. Watch game load and then crash as the bar has a quarter left to load

### Additional information

Vanilla works fine for me.

**Comment by runelead00** [comment]
Looks like you're trying to play with incorrect versions of something or with an incompatible submod, you have a ton of vanilla AAT errors
