### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Speederzzz** [TNODevs/TNO-Bug-Tracker#2468]
### Operating System

Windows 10

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT

### Files

[Jap broken foreign policy save file.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12909007/Jap.broken.foreign.policy.save.file.zip)

### Describe the bug

When opening the foreign policy screen, the left screen is blank. The tab is called "despised by the elite". The right screen does work.

### Steps to reproduce / Cause of the issue

1. Go to foreign policy screen
2. that's it, you'll see it's broken.

### Expected behaviour

you see the foreign policy screen as I s

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/38327445/1e224361-e4c9-48e0-8e35-a313da87d73b)

### Additional information

Savefile was made before the patch, therefor kido leads my reformist japan. I am unsure when this started, but my guess is when the patch got added.

**Comment by runelead00** [comment]
Saves from before the hotfix are not compatible
