### ISSUE TITLE
ITA - Consequences of Atlantropa mentioned

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2469]
### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Focus description for ita_build_up_sardinia mentions Sardinia being united with Corsica into a single island, but that is no longer the case ever since Atalntropa was removed.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/42a55948-7a7a-493b-914e-4bb949edecea)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
