### ISSUE TITLE
Germany - The focus tree disappers

### ISSUE THREAD

**Issue by AdriWookie** [TNODevs/TNO-Bug-Tracker#2470]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The german focus tree disappers one the second of may 1965. I think this is because of the reintegration of ukraine because it happend in a speer run and also in a bormann run.

### Steps to reproduce / Cause of the issue

1. Play germany
2. go though the civil war, it is not important who you choose
3. Play the game normally, reintegrate ostland etc. when you reintegarte ukraine you will see that the focus tree disappers

### Expected behaviour

expected to integrate ukraine, it is my puppet but I cant play the game without the focus tree.

**Comment by runelead00** [comment]
Fixed in Dev Build
