### ISSUE TITLE
ANY - no text for second level of computer hacking in intel agency

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2471]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

No loc for level 2 of computer hacking upgrade in intelligence agency upgrades

### Steps to reproduce / Cause of the issue

research level 1 of computer hacking

### Expected behaviour

actual text

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/6e11a3d1-5ec5-462a-b007-e5a5e2d11ed5)

**Comment by runelead00** [comment]
Fixed in Dev Build
