### ISSUE TITLE
GRE/ITA - Greece doesn't rejoin Italy after Papadopoulos coup

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2472]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12910440/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12910441/error.log)

### Describe the bug

After completing an event chain of negotiations with Greek partisans as ITA I got no concluding event. GRE's leader was changed to Papadopoulos, but ITA could neither invade, nor accept GRE back into its economic sphere/puppet status.

### Steps to reproduce / Cause of the issue

1. After GRE's collab government is couped, pick the most lenient/moderate options in negotiations with the partisans.
2. Choose IDEA for investigations into Greek communists
3. Have Papadopoulos coup the government?

### Expected behaviour

Either Greece should've rejoined my faction, or ITA should be able to reinvade it. After Switzerland, East Africa and Egypt Greece is the most important country in the Italian sphere, it shouldn't be allowed to just leave.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/4880b283-6501-463c-91b4-0ca2c3824160)

**Comment by runelead00** [comment]
Working as Designed, and we don't plan to make any major change to Italy or Greece before either of their releases
