### ISSUE TITLE
ITA - unclear length of temporary idea in ita_dissolve_the_blackshirts

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2475]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The prompt that is supposed to show how many days a temporary idea lasts does not show that number.

### Steps to reproduce / Cause of the issue

Go to Ciano's post-Verona focus tree.

### Expected behaviour

To see how many days an idea lasts

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/24896803-4e86-4d23-ba9f-4311cc47bf7d)

**Comment by runelead00** [comment]
Fixed in Dev Build
