### ISSUE TITLE
ITA - Double activation of the Battle for Italy decision cat

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2476]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Uploading ITA_1965_12_12_01.zip…]()

### Describe the bug

The decision category for Battle for Italy has activated 5 days before it was supposed to be activated by WORLD.930 event. If you didn't select an issue before this event, everything works as normal. However, if you select an issue and investment level before that event, the new issue raised clears the previous one without attributing any of the influence to America, Japan, or Italy, so I'm assuming the effects are completely cleared. The issue cannot be selected again.

### Steps to reproduce / Cause of the issue

1. Get a democratic Italy
2. Wait till activation of Battle for Italy decision cat

### Expected behaviour

The decision category and mission for selecting an issue should only activate once.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/9643a112-5436-4a3e-80be-d5877b3b8b66)

**Comment by Daru1914** [comment]
added save game if it helps

**Comment by runelead00** [comment]
Fixed in Dev Build
