### ISSUE TITLE
ITA - ita_environmental_protection idea has no icon

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2478]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

ita_environmental_protection idea has no icon

### Steps to reproduce / Cause of the issue

1. Get socialist path in ITA
2. Complete focus ita_terra_e_liberta

### Expected behaviour

An icon for the idea

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/e1bca320-a48b-4f3f-a7d5-bf886caaf72f)

**Comment by runelead00** [comment]
Fixed in Dev Build
