### ISSUE TITLE
ITA - FD.19 minor name spelling error

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2479]
### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Matteo is spelled with a single "t" once in this event
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/6c77b6fb-ba80-405e-b1a5-35992816db53)

**Comment by runelead00** [comment]
Fixed in Dev Build
