### ISSUE TITLE
Goring’s Germany- Iberia not being released

### ISSUE THREAD

**Issue by thatsocialistgay** [TNODevs/TNO-Bug-Tracker#248]
**Questions**

- Operating System:
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use:
- Were you using Steam? Yes
- Which expansions do you NOT have?
None
**Longer Description of Issue:**
During Goring run, In War Plan B, after winning against Spain & Portugal (Iberia split apart), mod does not automatically release puppet and keeps land occupied.

**Steps to Reproduce/Cause Issue:**

1. Win GCW as goring

2. Split up Iberia 
3. Get to War plan B
4. Start war against Portugal and Spain
5. Win
6. The issue should be visible

etc...

**Screenshots:**

![08AAF092-5325-4FD7-B394-71EFFA464B39](https://user-images.githubusercontent.com/94770612/142855161-5161278e-5fc9-4991-99dc-ab21ae0597b7.jpeg)
![5468A320-BD1D-4ADF-8765-B4CE5A75B569](https://user-images.githubusercontent.com/94770612/142855163-fd097435-fffd-49be-b086-ac4f01c1e5ce.jpeg)
![CB0FD3CF-6EDE-4165-A071-DE8194C90E0F](https://user-images.githubusercontent.com/94770612/142855166-c5b29c67-b823-465f-bcec-38c9f906d224.jpeg)

**Comment by masterbobli** [comment]
Could you send me the save game?

**Comment by thatsocialistgay** [comment]
> Could you send me the save game?

Sure. How would I send it? Github does not accept .hoi4. files
