### ISSUE TITLE
ITA - ita_stready_radicals idea has no icon

### ISSUE THREAD

**Issue by Daru1914** [TNODevs/TNO-Bug-Tracker#2481]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0.a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

It doesn't exist

### Steps to reproduce / Cause of the issue

Elect socialists in Italy, complete ita_the_steady_pace_of_change focus

### Expected behaviour

An idea with an icon

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/63430051/4d51839c-e0a3-41f2-b8df-db7a8bb9c748)

**Comment by runelead00** [comment]
Fixed in Dev Build
