### ISSUE TITLE
My gaungding playthrough again and this time my volunteer just got deleted

### ISSUE THREAD

**Issue by ripple0428** [TNODevs/TNO-Bug-Tracker#2482]
### Operating System

windows 11

### HOI4 version

1.13

### TNO version

1.13

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

i sent the volunteers to malysia and while they were fighting and all of a suddenn the division just stopped fucking existing (and no i wasn't finished testing)

### Steps to reproduce / Cause of the issue

i dont know i sent the volunteers to malysia and then it dissapeared

### Expected behaviour

the volunteer to not just dissapear

**Comment by runelead00** [comment]
You probably just lost all the strength and the unit got destroyed, not much we can do based on the information provided
