### ISSUE TITLE
All Countries - Crash when i try to open game options

### ISSUE THREAD

**Issue by ThePikminCaptain** [TNODevs/TNO-Bug-Tracker#2483]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12910796/error.log)

### Describe the crash

Press game options, then it crashes

### Steps to reproduce / Cause of the crash

1. Pick A Country
2. Press Game Options
3. The Game will crash quickly depending on how many other mods you use

**Comment by ThePikminCaptain** [comment]
custom difficulty to be exact

**Comment by runelead00** [comment]
Can't reproduce, like an issue with all of the other mods you are using not being compatible or updated to the most recent versions of TNO or HOI4
