### ISSUE TITLE
Komi - Stalina unable to be elected post reunification

### ISSUE THREAD

**Issue by Stirling181** [TNODevs/TNO-Bug-Tracker#2484]
### Operating System

Windows 10

### HOI4 version

v1.13.3.f717 (e134) (S)

### TNO version

v1.5.0.a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Describe the bug

Playing democratic Komi (KOM) doing a Svetlana playthrough. Regional stage elections start, game informs me that due to a bug the faction I chose would automatically win, before electing the Democratic Socialists.

### Steps to reproduce / Cause of the issue

1. Play centrist Komi
2. Elect Stalina
3. Unify West Russia
4. Chose to run as her in West Russian Election
5. Have someone else elected

### Expected behaviour

Svetlana to be elected.

### Screenshots

![Screenshot (99)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148020320/0a42304a-1c31-4cdf-8be0-9c9e50705be9)
![Screenshot (101)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148020320/b08ee630-f2cd-41f0-b06b-f6fab64c5696)

**Comment by runelead00** [comment]
Did you campaign for the PSD in the starting event, or did you just do the PSD tree

**Comment by Stirling181** [comment]
Campaigned as well, winning the around 1000 seats for the PSD

**Comment by runelead00** [comment]
And no gamerules as well?

**Comment by Stirling181** [comment]
Ahhhhh, I goofed. My bad, I loaded up a preset I had made without realising it had DSNP victory checked. Thanks for your help though

**Comment by runelead00** [comment]
okay good to hear, I was afraid it was something extremely esoteric if it wasn't a gamerule or a goof with campaigning
