### ISSUE TITLE
USA - Still not able to get the 'New Way Forward' achievement after selecting 'Initiate Troop Surge' and wins the HCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2485]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12911480/USA_play.zip)

### Describe the bug

The 'New Way Forward' achievement is still locked after the 'Initiate Troop Surge' decision is selected and the Haitian government wins the HCW. Probably the `TNO_HAI_civil_war_government_victory` set global flag is not added to USA victory in the HCW event, the Haitian government won the HCW news event or peace on action when I look at the requirement codes.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Haitian Civil War triggers.
3. 'Initiate Troop Surge' decision selected.
4. PPLN declares war on the Haitian government.
5. The Haitian government defeats PPLN.
6. USA won the Haitian Civil War.

### Expected behaviour

I don't know. Probably the set global flag `TNO_HAI_civil_war_government_victory` is not added.

**Comment by runelead00** [comment]
Fixed in Dev Build
