### ISSUE TITLE
USA - has_country_flag = USA_HCW_did_troop_surge somehow removed or cleared when Haitian Blitz starts

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2486]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_haitian_blitz_inevitable.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12914628/USA_haitian_blitz_inevitable.zip)
[USA_HCW_disengagement.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12914629/USA_HCW_disengagement.zip)
[USA_trujillo_fall.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12914630/USA_trujillo_fall.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/12914632/Logs.zip)

### Describe the bug

When the 'Initiate Troop Surge' decision is selected and the Haitian Blitz triggers, `has_country_flag = USA_HCW_did_troop_surge` is somehow removed or cleared. I don't know. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo wins the PPI.
3. Haitian Civil War triggers.
4. Select 'Withdrawal' decision.
5. Select 'Initiate Troop Surge' decision.
6. Haitian Blitz triggers.
7. Trujillo is defeated and ousted in the Haitian Blitz.
8. Haitian Civil War resumes.

### Expected behaviour

I don't know.

**Comment by runelead00** [comment]
Fixed in Dev Build
