### ISSUE TITLE
Britain - Workshop of the world GDP not tied to actual GDP

### ISSUE THREAD

**Issue by oppressedSVTFOEfan** [TNODevs/TNO-Bug-Tracker#2487]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

radio tno, last waltz of europe

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Describe the bug

the GDP in Workshop of the world GUI is not tied to your actual GDP making it impossible to fulfil the Chancellor`s promises

### Steps to reproduce / Cause of the issue

1. click on the economy screen
2. open the macro tab
3. observe your GDP growth
4. open the Workshop of the world GUI
5. Notice that the GDP section in Workshop of the world GUI is stuck at 3.1%

### Expected behaviour

the GDP in workshop of the world GUI should reflect your actual (or nominal) GDP

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148009499/00f3e2e2-658e-4493-8148-19fdb8754605)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148009499/9ecef4a7-cc0f-4d10-8b45-557c3fb623d6)

**Comment by runelead00** [comment]
Fixed in Dev Build
