### ISSUE TITLE
Germany - no super event German Civil War/German Focus Trees are gone

### ISSUE THREAD

**Issue by Sindan1203** [TNODevs/TNO-Bug-Tracker#2488]
### Operating System

Window 11

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I play as Germany (Speer's Germany to be exact), all Focus Trees are gone since March 13, 1965.
There is also no super event at the start of the German Civil War.

(My native language is Korean, and this article is written with a translator, so there may be some errors. I'm sorry.)

### Steps to reproduce / Cause of the issue

1. Start the game and choose Speer as Hitler's successor.
2. Start the German Civil War (at this point, the civil war normally happens, but there's no super event)
3. Win the German Civil War and continue to play.
4. As soon as the game goes past March 13, 1965, all Focus Trees disappear. The focus that was going on also disappears.

### Expected behaviour

Normal game progression.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148056569/f987a741-32b0-4000-839a-0807a002deeb)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148056569/fabfd79b-db53-4adb-b575-ee691aaeeef0)

https://github.com/TNODevs/TNO-Bug-Tracker/assets/148056569/4d69bad7-2e6d-43dc-8b35-b3c381815759

**Comment by Luzzot** [comment]
My Focus tree disappears when the option of Dealing with Ukraine is complete and the event of the return of Crimea does not happen

**Comment by runelead00** [comment]
Fixed in Dev Build
