### ISSUE TITLE
Ireland - Game says Ireland's next elections are in May of 1968

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#2489]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

Despite Ireland's next elections meaning to happen in 1965, the game says they happen in 1968, but even then, they don't

### Steps to reproduce / Cause of the issue

This shouldn't be hard to reproduce

### Expected behaviour

Ireland's elections should happen in 1965, with either FF or the NC winning

### Additional information

I know, this might seem irrelevant.

**Comment by runelead00** [comment]
The election is scheduled for 1968 at game start, Working as Designed

**Comment by PhoneythePhoneSaver** [comment]
Wait why did it say 1965 in the gamerule then?

**Comment by runelead00** [comment]
because the aftermath of the arms crisis and Lemass's resignation leads to snap election being called before the scheduled 1968 elections
