### ISSUE TITLE
Northern Ireland - Bugged GDP in the 100s of Billions

### ISSUE THREAD

**Issue by Senkaimon** [TNODevs/TNO-Bug-Tracker#249]
**Questions**

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by Stormeagle449** [comment]
This was fixed several versions ago.
