### ISSUE TITLE
Speerite Germany - Focus tree disappeared randomly

### ISSUE THREAD

**Issue by Scare17** [TNODevs/TNO-Bug-Tracker#2491]
### Operating System

Windows 10

### HOI4 version

it tells me not to write latest version but it was the latest version.

### TNO version

it tells me not to write latest version but it was the latest version.

### Do you have other mods in use?

No.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Was just playing a ironman mode speer germany, invaded moskowvien and then my focus tree disappeared. it re-appered when i took the Kaukasia decision but the focus tree had nothing done on it. 

### Steps to reproduce / Cause of the issue

I have no idea.

### Expected behaviour

For my focus tree to not disappear

**Comment by Sindan1203** [comment]
Me too

**Comment by runelead00** [comment]
Fixed in Dev Build
