### ISSUE TITLE
Germany - German Focus Trees disappear again

### ISSUE THREAD

**Issue by Sindan1203** [TNODevs/TNO-Bug-Tracker#2492]
### Operating System

Window 11

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I play as Germany (Speer's Germany to be exact), all Focus Trees are gone since June 10, 1965.

### Steps to reproduce / Cause of the issue

1. Start the game and choose Speer as Hitler's successor.
2. Win the German Civil War and continue to play.
3. As soon as the game goes past June 10, 1965, all Focus Trees disappear. The focus that was going on also disappears.

### Expected behaviour

Focus Trees must not disappear.

### Screenshots

https://github.com/TNODevs/TNO-Bug-Tracker/assets/148056569/63d3232f-7541-4771-bfed-d67abebe79aa

**Comment by runelead00** [comment]
If don't provide any saves or logs we can't do much, a video isn't very helpful

**Comment by Xfirez2012** [comment]
Ah man, I also have the same bug. I honestly think it might have something to do with Serbia.

**Comment by Luzzot** [comment]
[Savrs Tree focus dissapear.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13035384/Savrs.Tree.focus.dissapear.zip)

Here is mine

**Comment by runelead00** [comment]
Not the same issue, that's just the Ukraine focus tree issue again

**Comment by nzamtnv** [comment]
[GER_1965_04_16_15_temp.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13196491/GER_1965_04_16_15_temp.zip) I have the same problem, here is my save if needed

**Comment by runelead00** [comment]
Again, not the same issue, that's just the Ukraine focus tree issue which has been confirmed to be fixed for hotfix a dozen times already
