### ISSUE TITLE
TYM - Smuta ends before reunion of West Siberia 

### ISSUE THREAD

**Issue by IHateFMA** [TNODevs/TNO-Bug-Tracker#2495]
### Operating System

windows11

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

Chinese Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

If Ural Military District successfully integrated The Free Aviators just before being defeated by TYM,then Ural Military District will instantly "revive" on Surgut.

### Steps to reproduce / Cause of the issue

1.Go to custom paths
2.Set TYM wins the Smuta in West Siberia
3.Start a game,and wait

### Expected behaviour

TYM can reunite West Siberia successfully 

### Screenshots

![TYM1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/b516c0a9-62ef-4444-ae85-698a48ca4820)
![TYM2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/d7f6ccfe-ce6f-42a5-95f0-a9e75b0bb6ae)
![TYM3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/33b81597-6f36-4b1f-bec5-21f1153af9cf)
![TYM4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/136247382/c03ac8a4-d9bf-4623-a3a3-5e818a427ad6)

**Comment by runelead00** [comment]
Fixed in Dev Build
