### ISSUE TITLE
ENG - Focus Cost Is Absurdly High

### ISSUE THREAD

**Issue by Zecats** [TNODevs/TNO-Bug-Tracker#2496]
### Operating System

Windows 10

### HOI4 version

1.13.x

### TNO version

Not sure exactly I'm afraid, but I am playing 'The Ruin'

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

Collaborator focus "Lothian Must Survive The Winter" takes five billion dollars to do, which is presumably not the intention, rather meant to be either half a billion or even just fifty million

### Steps to reproduce / Cause of the issue

Play Britain until the civil war, then hover over the named focus. The tooltip describes the logic error.

### Expected behaviour

I expected protecting Lothian to not practically bankrupt me, 5B is a bit steep surely?

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/87282378/0d113975-f463-4849-8c96-f9b4b0e11cd9)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
