### ISSUE TITLE
KOM - Szhatie Laser SPAA Missing Unit Portrait Since Toolbox Theory

### ISSUE THREAD

**Issue by WesternFailMox** [TNODevs/TNO-Bug-Tracker#2497]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The Szhatie Laser SPAA, an equipment that you can get from from Ultravisionary Komi's Experimental Weapons mechanic, has been missing its unit portrait for as long as the initial release of Toolbox Theory, perhaps even further back, I know this is a bug because it used to have its own unique equipment icon in the production menu, and I am pretty sure the icon is still in the game files. 

### Steps to reproduce / Cause of the issue

1. Play as Komi
2. Progress down the Zhdanov path
3. Complete the Experimental Weapons Focus and complete the Decision for the Szhatie
4. Check production to see that it doesn't have a equipment icon

### Expected behaviour

Szhatie should have an equipment icon

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107778652/fad8e4c4-22f9-4a75-adfb-fa723e9425b4)
![jq3thjjy6sz51](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107778652/04501ff0-c706-4674-b981-eb8165c221b2)

The first image is a screenshot I have taken from my most recent game just today, as you can see, it is missing an equipment icon, despite the equipment icon existing and was originally not bugged, as shown in the second image.

**Comment by runelead00** [comment]
Fixed in Dev Build
