### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#2498]
### Operating System

Windows 10

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

After invading Poland as Yaroslav Stetsko, a peace deal occuredf after sometime that resulted in Poland annexing nearly all of Ukraine. I imagine that this issue is probably replicated in other path with the Ukranian State. This disallows an epilogue and the Ukraine has no events after this peace deal. Also there is no ministers except for yaroslavs wife. Sucks I cant wrap up my playthrough :(

### Steps to reproduce / Cause of the issue

Play Ukranian state 

declare on poland in final Yaraolsav focus. 

Push into Poland 

Peace deal activates and Poland annexes most of Ukraine. 

### Expected behaviour

Poland gives up territopry or is annexed. Not sure. 

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/59725197/5c9cf0a0-8b99-4c42-946e-988d475e0145)

**Comment by runelead00** [comment]
Fixed in Dev Build
