### ISSUE TITLE
Speer Germany- Reorganize Moskowien, no effect. Invalid Event Speer.moskowien53

### ISSUE THREAD

**Issue by Senkaimon** [TNODevs/TNO-Bug-Tracker#250]
**Questions**

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in current dev build
