### ISSUE TITLE
USA - NPP's Northern Nationalists have more senators than Dixiecrat Nationalists senators

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2502]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13042505/USA_play.zip)

### Describe the bug

Playing as Wallace's USA. After I doing to increased more NPP's nationalist voters, NPP's Northern Nationalists are somewhat more senators than Dixiecrat Nationalists senators in the 'Cutting a Deal' decision despite Wallace is in charge of USA because Wallace is pro-Dixie and Southerners and always likely to fail the Healthcare Reform and Social Security bills if chosen the 'Wallace Shall Lead the Way!' focus and doing segregate focuses because the Dixiecrat Nationalists senators are less compared to Northern Nationalist senators.

So, the NPP Dixiecrat Nationalists should have more senators than NPP Northern Nationalist senators before and during Wallace's presidency when increasing NPP nationalist voters.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Increase NPP voters.
3. Elect Wallace.
4. Win the proxy wars to gain more NPP voters.
5. Successful passing of segregation bills.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/74d86ee0-7a7c-4fb8-bb58-fd320cfc9271)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/651a2a46-15f0-4398-bdfd-86a88c538af4)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dd5a9190-713a-4326-9e9c-705d9f1cc5bd)

**Comment by runelead00** [comment]
Fixed in Dev Build
