### ISSUE TITLE
USA - Some issue in 'Encourage the Donkeys' focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2503]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_wallace_donkey.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13043152/USA_wallace_donkey.zip)

### Describe the bug

- In the 'Encourage the Donkeys' focus effect, the second word "Southerner" is colored red instead of blue because Lyndon is a Democrat, not a Republican.
- In 'Lyndon accepts support' and 'Lyndon refuses support' events' effects say that Democrats will support or refuse to support the bill but after clicking the event, the effect straight to Republicans instead of Democrats in the 'Cutting a Deal' decision for Healthcare Reform.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Wallace.
3. See the focus effect of 'Encourage the Donkeys'.
4. Complete the 'Encourage the Donkeys' focus.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dfdb336f-18f3-4ede-ae45-e6b80393f8e6)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fd860ea6-e965-42e3-8b85-537942acbc40)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7e659bea-ded9-4541-af9a-c116f04ed409)

**Comment by runelead00** [comment]
Fixed in Dev Build
