### ISSUE TITLE
USA - Strom Thurmond anger events gives Nativists support Democratic Party instead of Republican Party

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2504]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.3

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the 'Strom Thurmond anger' events, the effect shows that the Nativist Voters support the Democratic Party instead of the Republican Party.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Wallace.
3. Doing Social Security and Healthcare Reform focuses.
4. Choose not to be too segregation.
5. Strom Thurmond angers.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6f365215-fb8a-4936-8520-b4f93d4a48b8)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f98b1a19-e551-47a4-ac12-62e2a9b25b31)

**Comment by runelead00** [comment]
Fixed on Dev Build
