### ISSUE TITLE
USA - 'A Concern, Voiced' event gives Urban voters support the Democratic Party instead of Republican Party

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2505]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the 'A Concern, Voiced' event, the effect gives the Urban voters support the Democratic Party instead of the Republican Party because the big business is conservative, I think.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Wallace.
3. Doing Social Security focuses.
4. 'Our Northern Adjacents' focus is completed.
5. 'Spend! Spend! Spend!' focus is completed.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/793547e3-0811-4349-8953-cef7ff788ca0)

**Comment by runelead00** [comment]
Fixed in Dev Build
