### ISSUE TITLE
I was playing as Tomsk and formed the Central Siberian Republic. It was 1969 January and i was getting ready to go to war with the far eastern republic with the decisions when it crashed on the 16th of January 1969.

### ISSUE THREAD

**Issue by IDunnono** [TNODevs/TNO-Bug-Tracker#2507]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

Core with compliance++, Player led Peace Confrences, TNO: Second West Russian War, Toolpack 2023 Edition

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA, AAT

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13061246/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13061247/game.log)

### Describe the crash

It was 1969 and it was January 16th and it froze for around half a second and just crashed and completely exited hoi4.

### Steps to reproduce / Cause of the crash

1.Play as tomsk and form the Central Siberian Republic.
2. As soon as possible, go to war with whoever united far eastern siberia. 
3. Start the decisions to gian war prepartion to go to war.
4. In 1969 January 16th it will crash.

**Comment by runelead00** [comment]
You're playing with a submod not updated for The Ruin or AAT, it's a miracle you didn't crash before 1969, Can't Fix

**Comment by IDunnono** [comment]
Oh alright

**Comment by IDunnono** [comment]
So i cant use west russian war mod?
