### ISSUE TITLE
Germany(Speer) - Focus tree dissapears after dealing with Reichskommisariat Ukraine

### ISSUE THREAD

**Issue by Dudegamer1** [TNODevs/TNO-Bug-Tracker#2508]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.50.a

### Do you have other mods in use?

State Transfer Tool, Player Led Peace Conferences 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, BBA, AAT

### Files

https://1drv.ms/u/s!As7c41RBJLyWjG1KABbCJ73bg0uZ?e=VUbJ8X

### Describe the bug

After selecting Deal with Ukraine the german focus tree will vanish, and sometime after show up with none of the focuses completed.  

### Steps to reproduce / Cause of the issue

1. Select Dealing with Ukraine
2. Focus tree vanishes
3. bruh
4. Focus tree shows up with nothing completed after some time.

### Expected behaviour

Focus tree doesnt vanish

**Comment by runelead00** [comment]
Fixed in Dev Build
