### ISSUE TITLE
Germany - Disappearance of focus tree

### ISSUE THREAD

**Issue by Lenzo2001** [TNODevs/TNO-Bug-Tracker#2509]
### Operating System

macOS

### HOI4 version

1.13

### TNO version

1.5.0&

### Do you have other mods in use?

TNO: Toolpakt, TNO economic cheat, TNO release nations mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

none to give 

### Describe the bug

After reclaiming RK Ukraine as Bormann, the German focus tree disappeared.

### Steps to reproduce / Cause of the issue

none to give.

### Expected behaviour

This bug did also occur the last time I played TNO as Bormann, so I thought to try again, yet the bug did happen once more.

### Screenshots

none

### Additional information

none

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Lenzo2001** [comment]
If it is fixed, why does it still happen?

**Comment by runelead00** [comment]
Because it hasn't been added to the public release yet

**Comment by Lenzo2001** [comment]
Two question:

When do you think it will be released to the public?

If it is, do you have to restart the campaign all over again?

**Comment by Lenzo2001** [comment]
For now I'll use the Toolpakt to puppet Ukraine and when the focus "Autumn in Germany" for Bormann pops up, i'll do the Ukraine decision to fully puppet the country and make sure Bormann doesn't get cancer.
