### ISSUE TITLE
IRK/CHT- Irkutsk is annexed by Chita if they win during the SMUTA

### ISSUE THREAD

**Issue by Angelblue1852** [TNODevs/TNO-Bug-Tracker#2510]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0.a The Ruin

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[New folder (17).zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13062139/New.folder.17.zip)

### Describe the bug

For some odd reason, Irkutsk is getting annexed by Chita during the SMUTA if they managed to make Chita capitulate, as though they are losing.

### Steps to reproduce / Cause of the issue

1. Play as Irkutsk
2. Defeat Sablin and reach the SMUTA
3. Defeat Chita
4. Get annexed by Chita

### Expected behaviour

Irkutsk annexs Chinta

### Screenshots

![20231021205905_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/38672184/0940b977-0fdb-4036-81bb-632e9fa62218)
![20231021205908_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/38672184/38dedec6-20cc-4340-ac47-d6328915ffe0)

### Additional information

For some odd reason, the game is setting Chita as FROM and Irkutsk as ROOT when it should be the other way around.
Problem seems to be exclusive to Irkutsk as far as the Far East goes, though I could be wrong.

**Comment by runelead00** [comment]
Fixed in Dev Build
