### ISSUE TITLE
Germanys focus tree disappears half way through. 

### ISSUE THREAD

**Issue by LuciusKornelius** [TNODevs/TNO-Bug-Tracker#2512]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

Ruin (22 of october)

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Describe the bug

When playing both Bormann or Speer Germany the focus tree will disappear when the decision to intergrate the Ukraine Colony finishes. Its the same for both Speer and Bormann, i tried reloading the saves the same happens each time.

### Steps to reproduce / Cause of the issue

1 Play Bormann or Speer.  Wait for the decision to intergrate Ukraine Colony finishes. 

### Expected behaviour

Germany's Focus tree will disappear.

### Additional information

This didn't happen before the Ukraine update.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
