### ISSUE TITLE
I can't research technology, the button doesn't work

### ISSUE THREAD

**Issue by Farron38** [TNODevs/TNO-Bug-Tracker#2513]
### Operating System

windows 10 

### HOI4 version

1.12.14 avalanche

### TNO version

The Ruin Patch

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The button of research don't work and there is a message with it 

### Steps to reproduce / Cause of the issue

1.launch the game
2.go to research slot 
3.try to research a tech

### Expected behaviour

research technology

### Screenshots

![dddsd](https://github.com/TNODevs/TNO-Bug-Tracker/assets/111241974/37201813-1229-4547-91c2-a808a25421c0)

**Comment by runelead00** [comment]
Update to the most recent hotfix and make sure you're using the most recent version of HOI4, it doesn't look like you updated properly
