### ISSUE TITLE
GER - Germany has no resource rights on Kaukasien after Pleiger's Kaukasien rejoins the Pakt

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2514]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Pleiger's Reichskommissariat Kaukasien rejoins the Pakt without battle through Speer's Kaukasien focus tree, Germany has still no resource rights (mainly oil and other resources) on Kaukasien. 

### Steps to reproduce / Cause of the issue

1. German Civil War starts.
2. Paul Pleiger and his technocrats overthrow Josias in Kaukasien.
3. Speer won the German Civil War.
4. Reichskommissariat Kaukasien rejoins the Pakt without war. 

### Expected behaviour

Oversight, maybe.

**Comment by runelead00** [comment]
Fixed in Dev Build
