### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Crazycrafter0o** [TNODevs/TNO-Bug-Tracker#2516]
### Operating System

Windows 10

### HOI4 version

Stella Polaris v1.13.4.0735 (15a3)

### TNO version

TNO v1.5.0a The Ruin

### Do you have other mods in use?

Modifier Icons, Radio Berlin, Show Speed in Construction View

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

as soon as i hit the decision to dea with the RK Kaukasien as Speer germany the entire Focus tree resets

### Steps to reproduce / Cause of the issue

1. play a standard game until the subjugation of Rk Ostland and reintegrate Ukraine
2. Click the descision to activate the focus to deal with Kaukasien
3. as soon as the Kaukasien descision is activated the entire focus tree resets, setting it back to right after the end of the civil war

### Expected behaviour

the kaukasien tree appers and the rest of the focus tree stays as it is

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/33728103/f55bd7cc-b39b-47bd-8442-2ddc145a6b4e)

**Comment by runelead00** [comment]
Fixed in Dev Build
