### ISSUE TITLE
All economic sphere leader tags - Navy Satisfaction Status for Cruisers doesn't affect when producing light cruisers

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2517]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[IBR_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13079678/IBR_play.zip)

### Describe the bug

When producing light cruisers, the Navy Satisfaction Status for Cruisers doesn't affect to increase percentage.  

### Steps to reproduce / Cause of the issue

1. Play as any feature tag that has an economic sphere leader.
2. Produce light cruisers.
3. See Navy Satisfaction Status from the Cold War tab.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/92c0f68c-b9bc-4af3-a7ce-02bc5c90fb13)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5cd9865c-dc70-41d9-8881-695a206eb899)

**Comment by runelead00** [comment]
Fixed in Dev Build
