### ISSUE TITLE
USA-Alabama/Arkansas name mixup. Hovering over Alabama in the United States Government and Voting GUI when camping in the Deep South has it labeled as Arkansas and visa versa 

### ISSUE THREAD

**Issue by kylebentl** [TNODevs/TNO-Bug-Tracker#2518]
### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA, AAT

### List the loc issues below

1.
![16981349610371452594364670230127](https://github.com/TNODevs/TNO-Bug-Tracker/assets/141360327/d9260330-4910-4ab1-a327-8675180ec7ca)
2.
![16981349904578483615711870440896](https://github.com/TNODevs/TNO-Bug-Tracker/assets/141360327/72d6b123-f6aa-475e-bd0c-cf986cefdcb7)

**Comment by runelead00** [comment]
Fixed in Dev Build
