### ISSUE TITLE
IBR - 'Stalemate in South Africa' event triggers despite the South Africa and OFN have the total victory in SAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2520]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[IBR_saw_ofn_total_victory.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13114187/IBR_saw_ofn_total_victory.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13115132/Logs.zip)

### Describe the bug

After South Africa and OFN won the South Africa War in total victory, Iberia received the 'Stalemate in South Africa' event instead of the 'Total Victory in South Africa' event or something like that

I don't know if this issue could occur when South Africa and OFN won in the South Africa War in a 'partial' victory or defeat in the South Africa War in a partial or total defeat. 

### Steps to reproduce / Cause of the issue

1. Play as Iberian Union.
2. South Africa War triggers.
3. Iberia supports South Africa.
4. Total victory for South Africa in SAW.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/085f6add-131d-4fa1-af45-c8026dc7c67f)

**Comment by runelead00** [comment]
Fixed in Dev Build
