### ISSUE TITLE
WRRF - Unit Model All Black

### ISSUE THREAD

**Issue by Vperedsmotryashchij** [TNODevs/TNO-Bug-Tracker#2522]
### Operating System

Windows 10

### HOI4 version

1.13.4.0735 (7a0e) (S)

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13121095/graphics.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13121096/error.log)

### Describe the GFX issue

The black model of the WRRF soldier instead of the normal one that was before the DLC

### Steps to reproduce / Cause of the issue

The problem may stem from the fact that in the latest update, Paradox replaced the Soviet models of units with others.At least there is a connection with this.

   1. Log in to the game.
    2. To see an error when entering/in the template.
    Occurs even after the game is fully installed
P.S
Also, the error has a connection with the change of the Paradox model of the Soviet unit lying in the game files. Now the main one is another model.

### Expected behaviour

Not a completely black model of the soldier WRRF/ the model that was on the Ruin before the DLC

### Screenshots

![277663186-d1070497-e1c9-4aaa-aec8-99a59503b4b5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/86300859/c606bd25-4b99-418e-87f2-b17ae0766674)

**Comment by runelead00** [comment]
Fixed in Dev Build
