### ISSUE TITLE
GER - Second Malagasy Uprising still doesn't show in cold war achievements for Germany after German Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2523]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Similar issue with this one #2029.

### Steps to reproduce / Cause of the issue

1. Second Malagasy Uprising triggers.
2. German Civil War triggers.
3. Malagasy Rebels win the Second Malagasy Uprising event.
4. End of the German Civil War.

### Expected behaviour

Oversight, maybe.

**Comment by runelead00** [comment]
Fixed in Dev Build
