### ISSUE TITLE
COG - Congo can buy resources from Germany even in OFN

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2525]
### Operating System

Windows 11

### HOI4 version

1.13.1

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

At the beginning of game, Central Afrika (COG) can buy resources and guns from Germany
If it has been defeated in south africa war and captured by USA, but after this government collapse, then congo civil war will start
but **here's the problem**
if congo government win congo civil war and join OFN, it can still buy resources from germany, just like beginning of game
because of it's COG tag

### Steps to reproduce / Cause of the issue

add a limit for buying resource decisions, COG must be in faction with GER

### Expected behaviour

COG can't buy resources from GER after this

**Comment by runelead00** [comment]
Do you have evidence of this happening? because the decisions are already locked behind Siegfried Muller ruling the country.

**Comment by MrStraws114514** [comment]
well sry, someone updated a fixed bug...
