### ISSUE TITLE
JAP - End of interregnum incorrectly removes "The Showa Emperor" modifier when electing Kaya or Ikeda

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#2526]
### Operating System

win11

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Hi! I know this was marked as fixed, but the bug is still present in version 1.5.0a. The edited scripted effect JAP_remove_all_showa_ideas_INT, which is supposed to avoid removing the PM specific Showa ideas when the new PM takes power, does not function correctly.

While the bug does not occur when putting Takagi in power, it still removes the Showa idea if Ikeda or Kaya takes power. This is because the jap_showa_emperor_ikeda and jap_showa_emperor_kaya ideas are removed before the checks on whether they _should_ be removed takes place.

### Steps to reproduce / Cause of the issue

You can easily recreate this bug by triggering event jap_interregnum.1 (Yasuda Crisis event) and then triggering either Ikeda's election (jap_interregnum.70) or Kaya's election (jap_interregnum.78).

To fix this, the two lines I've marked in the screenshot below should be removed from JAP_remove_all_showa_ideas_INT:
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/59315866/85b3f4a3-8529-413f-af22-e9dc49db4fc7)

### Expected behaviour

The Showa idea should be modified and not removed

**Comment by Jack121Q** [comment]
Fixed, this time hopefully properly.
