### ISSUE TITLE
USA - Unable to lower German Spy Network strength in central america area using CIA

### ISSUE THREAD

**Issue by WhtDoWeWnt** [TNODevs/TNO-Bug-Tracker#2527]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Describe the bug

When I select the counterintelligence (using CIA) to reduce   network strength in Caribean America (yellow coloured on the CIA map), it doesn't lower that region's German intelligence network, it lowers the South American area's network strength for the Germans

### Steps to reproduce / Cause of the issue

Only one step needed
1. Use CIA to counter German network strength in Caribbean America in foreign policy screen

### Expected behaviour

Choose foreign policy, select Caribbean America region, choose AJFICTION task

### Additional information

all versions of this task work in all other regions, just not in that region.

**Comment by runelead00** [comment]
Can't reproduce on dev build, and w/o logs or saves can't confirm issue
