### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by yunghobe** [TNODevs/TNO-Bug-Tracker#2529]
### Operating System

windows 11

### HOI4 version

1.13.4 

### TNO version

v1.5.0a "The Ruin"

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA, AAT

### Describe the GFX issue

Playing as UK, in the workshop of the world mechanic, all the regions are showing up with the shape of Scotland, the regions don't have names, and hovering over the tick boxes for the projects don't give any information

### Steps to reproduce / Cause of the issue

1. Play as UK
2. Click on Workshop of the world tab
3. See visual errors

### Expected behaviour

Regions should load as their normal shape

### Screenshots

https://imgur.com/a/fBodP4U

**Comment by Stormeagle449** [comment]
Fixed in TNO's current version.
