### ISSUE TITLE
The Leopoldville Verwaltung - Does not recapture whole Congo

### ISSUE THREAD

**Issue by YakovMatvienko** [TNODevs/TNO-Bug-Tracker#253]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use: Last Waltz
- Were you using Steam?  +
- Which expansions do you NOT have? have all current major expansions

While german remnants retake Congo, Pakts allies send their troops. 

1. Huttig's collapse
2. Congo civil war.
3. Have Pakt allies occupy Congo states and capitulate them.
4. Now Pakt ally has its own Congo.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/22596145/142861959-8e44073e-a8de-42fd-bd50-c1ccf950cf62.png)

**Comment by masterbobli** [comment]
Should be fixed in the latest release: German Congo will leave the Pakt after the Congo Crisis begins
