### ISSUE TITLE
All country - Civs producing consumer goods

### ISSUE THREAD

**Issue by averagetomskenjoyer** [TNODevs/TNO-Bug-Tracker#2530]
### Operating System

Windows 10

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

When I start playing with any country, the game takes away a portion of the civilian factories to produce consumer goods, which shouldn't really happen, as they are produced separately with production units.

### Steps to reproduce / Cause of the issue

Playing any country

### Expected behaviour

Civilian factories should not produce consumer goods

### Screenshots

![20231024211813_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148972379/5add717d-170e-47b5-8989-da22e063f514)

**Comment by runelead00** [comment]
Fixed in Dev Build
