### ISSUE TITLE
WRRF or West Russian unifiers - peace conference pops up for invading ural republic (zlatoust)

### ISSUE THREAD

**Issue by silverbugreporter** [TNODevs/TNO-Bug-Tracker#2531]
### Operating System

windows 11

### HOI4 version

v.1.13.4.0735 (7a0e) (S)

### TNO version

v1.5.0a "The Ruin"

### Do you have other mods in use?

Loaded 2WRW for 2 in-game years, then turned it off. (because it hadn't updated yet)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, WTT, MTG, NSB, BBA, AAT

### Describe the bug

Once Zlatoust and their client states capitulate, a peace conference pops up instead of simply annexing west Siberia automatically.

### Steps to reproduce / Cause of the issue

Play as the WRRF (or, most likely any west russian unifier) and unite West Russia. Then have Zlatoust (somehow) unify west Siberia. Invade and capitulate the Ural Republic, and the peace conference will pop up

### Expected behaviour

West Siberia to be annexed.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/59fc4711-6c04-46fb-b9a3-53126c68ace2)

**Comment by runelead00** [comment]
Should be fixed in current release
