### ISSUE TITLE
Amur and Manchuria - Blagoveshchensk returns to Manchuria if Amur is capitulated

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#2532]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

If Amur is defeated by another far eastern warlord, when it unifies the far east Blagoveshchensk is given back to Manchuria

### Steps to reproduce / Cause of the issue

1. Make sure Amur isn't the one who unifies the far east

### Expected behaviour

The unifier of the far east keeps Blagoveshchensk

**Comment by runelead00** [comment]
Working as Designed, AI Far East lost the border war
