### ISSUE TITLE
Bormann Germany - Eastern expansion stuck

### ISSUE THREAD

**Issue by Fanatismus** [TNODevs/TNO-Bug-Tracker#2533]
### Operating System

Win 10

### HOI4 version

1.13.4

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

WTT, BBA, AAT

### Describe the bug

Bormann Germany couldn't reclaim its eastern colonies because "Reichgau Gotenland" needs not to exist as they can't do the decision to declare war or interact with the eastern parts. It occurred probably because no events fired for crimea as of the new update. It is probably a bug unsolved by the recent update "The Ruin." I played as the US and I had to use console command to annex crimea to germany.

### Steps to reproduce / Cause of the issue

AI Germany - Played as USA
- Eastern

### Expected behaviour

Remove the requirement for Germany to own gotenland before reclaiming ukraine etc

**Comment by runelead00** [comment]
Fixed in Dev Build
