### ISSUE TITLE
Shukhevych Ukraine - Poland annexes Ukraine

### ISSUE THREAD

**Issue by Dagemelior** [TNODevs/TNO-Bug-Tracker#2534]
### Operating System

Windows 7 Ultimate

### HOI4 version

1.13.1

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Describe the bug

After winning the Galician Conflict as Shukhevych's Ukraine, Poland annexed large swathes of my territory.

### Steps to reproduce / Cause of the issue

1. Get Shukhevych in charge of OUN Ukraine
2. Win the Galician War by taking Lwów

### Expected behaviour

I expected Ukraine to take Galicia

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/96637002/8b41134a-24ce-47fa-89cb-2929c32c2ced)

### Additional information

Also, Shukhevych kills Stetsko to take power, yet Stetsko is alive in the description for the focus "Excise Extremist Excess" and is to be executed in the description for "Subdue the Supreme Serpents"

Also, when declaring the Galician War, the event just says "todo" in both the main text file and the option button

**Comment by runelead00** [comment]
Fixed in Dev Build
