### ISSUE TITLE
MAD - Militärverwaltung Madagaskar and Disconnected Settlements still do not remove in 'Foreign Claims' states after the SMU

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2535]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Similar issue of this one #1805.

### Steps to reproduce / Cause of the issue

1. The second Malagasy Uprising starts.
2. Either German/French Madagascar or Malagasy Rebels won the Second Malagasy Uprising.

### Expected behaviour

Oversight, maybe.

**Comment by runelead00** [comment]
Fixed in Dev Build
