### ISSUE TITLE
German Reich (Speer) 1964 - my Focus tree just disappeared

### ISSUE THREAD

**Issue by Joserkp** [TNODevs/TNO-Bug-Tracker#2539]
### Operating System

Win 10

### HOI4 version

1.13.4

### TNO version

v1.5.0a “The Ruin”

### Do you have other mods in use?

Only radio mods (Phonk Radio, etc.), Player Led Peace conferences and the spot optimization

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13198626/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13198627/error.log)

### Describe the bug

just fighting in the South African war, I was doing the focus "Deny our participation" or something like that, I don't remember now and then suddenly the focus tree disappeared, before that I couldn't continue my decision to expand the faction after the civil war because the event of Norway didn't load and they hadn't joined my faction

### Steps to reproduce / Cause of the issue

?

### Expected behaviour

my focus tree doesn't disappear

### Screenshots

![Tno Bug](https://github.com/TNODevs/TNO-Bug-Tracker/assets/147947685/a746a5ef-bd01-471a-8049-5c077558153a)
![tno bug2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/147947685/5e000caa-9c82-479c-8009-8e6923f4e42c)

**Comment by runelead00** [comment]
Pretty sure this another instance of the Ukraine focus tree bug, fixed in Dev Build
