### ISSUE TITLE
USA/Japan/Italy - Battle for italy issue bonuses are not updated to toolbox

### ISSUE THREAD

**Issue by Beletor** [TNODevs/TNO-Bug-Tracker#254]
**Questions**

- Operating System:Win10
- HOI4 Version:Current up to date
- TNO Version:Toolbox
- Any other mods in use:Gibraltar fix
- Were you using Steam? Yes
- Which expansions do you NOT have? Have all of them

**Longer Description of Issue:**
Battle For Italy mechanics effects are not updated to the new Toolbox Theory system - Agricultural subsidizes issue gives -0.50 poverty reduction which vaporises it out of existense for US
I guess it is not the only problematic issue inside BFI, so i suggest to check all of the scripted effects for BFI

**Steps to Reproduce/Cause Issue:**

1. Win BFI
2. For example win Agricurtural issue
3. Poverty is gone, We saved America boyz

etc...

**Screenshots:**
[image](https://user-images.githubusercontent.com/75991671/142872892-3e871fd4-62fb-4dde-bce9-6353bdf88b68.png)

**Comment by runelead00** [comment]
Fixed for UB
