### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Dwffffffcccccc** [TNODevs/TNO-Bug-Tracker#2540]
### Operating System

Windows 11.

### HOI4 version

the latest version of hoi4

### TNO version

the latest version of tno

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![Screenshot_6](https://github.com/TNODevs/TNO-Bug-Tracker/assets/87900842/802af253-97d8-42ef-b1e4-7c5ae3a053c6)

### Describe the bug

When playing for the Reich, when you maintain your regime in Madagascar, a sign appears that should originally belong to the United States (the number of days after the last action). It blocks the decision to supply rifles to certain cities in Madagascar

### Steps to reproduce / Cause of the issue

1. Choose Borman(i choosed him in this bag)
2. Wait Civil war in Madagascar.
3. We are waiting for the second stage of the conflict.

### Expected behaviour

The plate relating to the US interface should be cut out of the global conflict of the Reich, thereby restoring an adequate opportunity to supply weapons to the cities of Madagascar

### Screenshots

The plate relating to the US interface should be cut out of the global conflict of the Reich, thereby restoring an adequate opportunity to supply weapons to the cities of Madagascar

**Comment by runelead00** [comment]
Fixed in Dev Build
