### ISSUE TITLE
bug with the Reichskommissariat of Ostland

### ISSUE THREAD

**Issue by Dwffffffcccccc** [TNODevs/TNO-Bug-Tracker#2541]
### Operating System

Windows 11.

### HOI4 version

the latest version of hoi4

### TNO version

the latest version of tno

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

As a result of the civil war, the Reichskommissariat won, but the game believes that the civil war is still going on.

### Steps to reproduce / Cause of the issue

1. Play as Bormann and win the German Civil War.
2. Give a guaranteed opportunity to defeat Stalker's Reiskommissariat
3. Wait for the end of the civil war.

### Expected behaviour

There should be an event about Stalker's victory in the war, as well as a focus option aimed at reuniting with peaceful Ostland.

### Screenshots

![Screenshot_8](https://github.com/TNODevs/TNO-Bug-Tracker/assets/87900842/bb79b591-6634-4836-9910-44ff6245437d)
![20231029222713_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/87900842/bd4b1dee-bb5b-4a09-ad92-ab7c43b8b164)

**Comment by runelead00** [comment]
Fixed in Dev Build
