### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Gabigoulos** [TNODevs/TNO-Bug-Tracker#2542]
### Operating System

Windows 10

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13199353/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13199362/game.log)

### Describe the crash

It simply crashes in the end of the loading process

### Steps to reproduce / Cause of the crash

1. Use the "opengl" as option for initialization (written exactly as that)
2. Run the game with all DLCs and no other mods
3. The game crashes mid into loading

### Additional information

I've tried desistaling and reinstaling the mod and using the "opengl" and "-opengl" ( the latter intializantion option gave a liter crash report, about 16 MB and the other gave one with 18 MB)

**Comment by runelead00** [comment]
Looks like you're trying to play with incorrect versions of something or with an incompatible submod, you have a ton of vanilla AAT errors
