### ISSUE TITLE
RUS - Nations getting randomly annexed

### ISSUE THREAD

**Issue by Angelblue1852** [TNODevs/TNO-Bug-Tracker#2543]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0.a The Ruin

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[New folder (19).zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13199543/New.folder.19.zip)

### Describe the bug

I don't know for sure if this is a bug, but the Russian Warlords are getting annexed by nations they're at war with for no reason, they've not lost any victory points. I'm not sure if there's a bug causing this or if it's a mechanic to keep wars from going too long due to AI stupidity.

### Steps to reproduce / Cause of the issue

I haven't figured out how to reproduce the error. I just know that randomly, Russian Warlords at war will suddenly have one of them annex the other without any explanation.

### Expected behaviour

Russian Warlords to annex each other via fighting

### Additional information

Again, don't know if this is an issue or a mechanic.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Angelblue1852** [comment]
Thanks. That was a big annoynace.
