### ISSUE TITLE
Amur- Getting annexed w/o losing V.Ps

### ISSUE THREAD

**Issue by Virolac414** [TNODevs/TNO-Bug-Tracker#2544]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0a "The Ruin"

### Do you have other mods in use?

State Transfer Tool & Precise Buffs

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13199620/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13199621/game.log)

### Describe the bug

Im playing as Amur and i am at war with the Divine Mandate of Siberia and in early January 1964 i get a peace treaty calculating effects pop up and then my game ends as i am annexed by the Divine Mandate even though i havent lost any land and i am currently winning, i was also preparing for war and randomly the entire nation of Irkutsk was given to me without war or any events

### Steps to reproduce / Cause of the issue

Download same mods
Play as Amur
complete first focus tree
begin second tree
complete might makes right, those who have helped us and silent killers focuses
begin war on Divine Mandate

### Expected behaviour

For the war to end with me winning and annexing the Divine Mandate

**Comment by runelead00** [comment]
Fixed in Dev Build
