### ISSUE TITLE
Speer's Germany - Focus tree disappearing 

### ISSUE THREAD

**Issue by Cragytop** [TNODevs/TNO-Bug-Tracker#2546]
### Operating System

Windows 11

### HOI4 version

1.13.4.0735

### TNO version

1.5.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Bugged Germany - Copy.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13207804/Bugged.Germany.-.Copy.zip)

### Describe the bug

Focus tree disappear when decision to conquer Moscow is clicked and reappear when decision to invite the Caucuses but non of them are completed 

### Steps to reproduce / Cause of the issue

1. Chose Speer
2. Go as normal until you can retake Moscow and the Caucuses (I went down fully reformist, but I don't know if that will affect anything)
3. When you click the decisions you should get what was described previously if you click the Moscow one first then the Caucuses on after

### Expected behaviour

The focus tree should end up being removed then reset to none compleated 

### Screenshots

![Screenshot 2023-10-30 164340](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149414306/214ee33a-63bc-4b84-bbb0-85c6dff86983)
![Screenshot 2023-10-30 164406](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149414306/302e8a4f-5d42-4587-b7a3-b9a97387614f)

**Comment by runelead00** [comment]
Fixed in Dev Build
