### ISSUE TITLE
USA - The Home Front Decagon

### ISSUE THREAD

**Issue by Dagemelior** [TNODevs/TNO-Bug-Tracker#2547]
### Operating System

Windows 7 Ultimate

### HOI4 version

1.13.1

### TNO version

1.5.0a

### Do you have other mods in use?

Operation Deep Freeze

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Describe the GFX issue

The pentagonal bars in the Home Front mechanic are upside down

### Steps to reproduce / Cause of the issue

Play until the South African War and wait for the Home Front mechanic to appear

### Expected behaviour

I expected the bars to be the right way up

### Screenshots

![IMG-20231030-WA0006](https://github.com/TNODevs/TNO-Bug-Tracker/assets/96637002/cfc24479-5b66-46ec-bf27-3bf5daacf3b0)

**Comment by Ikidikid** [comment]
Probably an Operation Deep Freeze submod issue, I think. Try to disable the Operation Deep Freeze submod.
