### ISSUE TITLE
USA/SAF/BRA/CAN/AST/NZL - 'Breaking Front' national spirit is not removed after the South Africa War.

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2548]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the South Africa War, the OFN and OFN-aligned members who participated in the South Africa War still have the 'Breaking Front' national spirit instead of removing the SAW national spirit.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. Elect any of the 1964 presidents.
4. Has the continuation of the South Africa War tree.
5. Choose the Land War bonuses focus.
6. End of the South Africa War.

### Expected behaviour

Oversight, maybe.

**Comment by runelead00** [comment]
Fixed in Dev Build
