### ISSUE TITLE
ITA - Missing loc

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#255]
- Operating System: windows 10
- HOI4 Version: Collie 1.10.8
- TNO Version: 1.2.0c
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? i own them all

After the decision "Improve Tunisia", this decision appeard which has no localization.

![image](https://user-images.githubusercontent.com/59315866/142900535-ba6f87ea-c9d8-4a55-a6be-0cf049747bff.png)

**Comment by jink47787** [comment]
Also, this event option does not have a description.
![image](https://user-images.githubusercontent.com/59315866/142904957-a7087357-edb7-498e-b69f-50bd0649f8c3.png)

**Comment by runelead00** [comment]
Fixed on UB
