### ISSUE TITLE
[Bug]: Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by TFAltHist** [TNODevs/TNO-Bug-Tracker#2551]
### Operating System

Windows 11

### HOI4 version

1.13

### TNO version

1.5.0a

### Do you have other mods in use?

TNO Radio, Player-Led Peace Conferences, The Second West Russian War, Operation Deep Freeze

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT

### Files

Non-applicable here, as this has been happening in pretty much all my games for some time, and I don't know where the save game is on my desktop anyway.

### Describe the bug

For some reason, the states of Moghilau, Balta, Dealurile Nistrului, and Berezovca are not owned by anyone, not even as an anarchic region. The Diplomacy tab doesn't work on this strange null-zone, and attempting to use console-commands to annex those states ends in the game crashing.

### Steps to reproduce / Cause of the issue

Non-applicable, as the null-zone is there when you enter the game.

### Expected behaviour

As you probably know, those states should be part of Romania in TNO.

**Comment by Vladislavia** [comment]
I've witnessed the same issue in my game. I'm quite surprised there are other people, who has it,

**Comment by Vladislavia** [comment]
> ### Operating System
> Windows 11
> 
> ### HOI4 version
> 1.13
> 
> ### TNO version
> 1.5.0a
> 
> ### Do you have other mods in use?
> TNO Radio, Player-Led Peace Conferences, The Second West Russian War, Operation Deep Freeze
> 
> ### Were you using Steam?
> Yes
> 
> ### Which major expansions do you NOT have?
> MTG, LAR, NSB, BBA, AAT
> 
> ### Files
> Non-applicable here, as this has been happening in pretty much all my games for some time, and I don't know where the save game is on my desktop anyway.
> 
> ### Describe the bug
> For some reason, the states of Moghilau, Balta, Dealurile Nistrului, and Berezovca are not owned by anyone, not even as an anarchic region. The Diplomacy tab doesn't work on this strange null-zone, and attempting to use console-commands to annex those states ends in the game crashing.
> 
> ### Steps to reproduce / Cause of the issue
> Non-applicable, as the null-zone is there when you enter the game.
> 
> ### Expected behaviour
> As you probably know, those states should be part of Romania in TNO.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Disable 2WRW. The submod hasn't updated yet

**Comment by runelead00** [comment]
^see above, disable 2WRW
