### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Vladislavia** [TNODevs/TNO-Bug-Tracker#2552]
### Operating System

Windows 10 Professional

### HOI4 version

1.13.4

### TNO version

1.5.0a

### Do you have other mods in use?

FPS Map (No strategic view adjustments), TNO: Second West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13216292/error.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13216954/setup.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13216969/game.log)

### Describe the crash

The game I saved starts up in January 15 1969, and after a day, in the exact date of 1:00 Jan 16 1969, the game crashes.
 The music stops for a sec, and the game later freezes, just like any crash starts with.

### Steps to reproduce / Cause of the crash

I can't truly explain the cause of the crash. But the only thing I was thinking the problem is there are some countries, whose names (and the leader portraits) are not showing, and the "Ideological pie" is freaking out when constantly clicking on it with a right mouse click. These countries/warlords are: "Speer's Germany" (which was later taken by Bormann afterwards), Kazakh warlords after Kazakhstan collapsed (Pavlodar, Aktobe, Nova Polska) - are the only spotted issues during my gameplay.

**Comment by Vladislavia** [comment]
P.S. I've been playing as Novosibirsk

**Comment by runelead00** [comment]
Likely a 2WRW related issue, wait until submod updates to play it
