### ISSUE TITLE
UKR, CAU, and CRI - RK Ukraine and Kaukasien declare war on Gotenland

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#2555]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

After the GCW begins and before the UCW starts, RK Ukraine and Kaukasien declare war on Gotenland, with the latter annexing it after they surrender.

### Steps to reproduce / Cause of the issue

1. Just wait until the GCW begins

### Expected behaviour

Only the Ukrainian State, Republic of Ukraine, and Ukrainian SSR should be able to declare war on Gotenland

### Screenshots

![image (25)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/143363540/9c2f0626-8969-4992-8fed-6c7bb1b17cab)

**Comment by Sebastianroczz** [comment]
can confirm this also affects affects every nation in the game 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/132775390/ab4bea76-062b-4c57-871f-f6531889d1a1)

**Comment by Sebastianroczz** [comment]
image above is from my iberia game

**Comment by runelead00** [comment]
Fixed in Dev Build
