### ISSUE TITLE
Global Base Stability randomly declining weekly. 

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#2556]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Global stability declined for all nations globally (except mine for some strange reason) by -5, and it continues to keep varying. It's not in reference either to their economies and their sub-stability effects. It's quite literally the base stability itself. 

### Steps to reproduce / Cause of the issue

1. Play TNO
2. Watch the base stability weekly (or just in general it's not consistent which is weird.)
3. If you haven't seen it at the start, you'll notice it around 1963-1964 (I personally did)
4. If this matters at all, I was playing Japan. 

### Expected behaviour

I expected global base stability to not collapse/decline.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/d7f14a2b-af0b-4746-8c67-21a2857445e2)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/18adbf3a-9832-47dc-9a44-73f5361655ea)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/15205229-011d-4f30-b7af-46cf346b0a12)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/bcf83877-2718-443d-87c8-79b9fe3518b3)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/e9812260-0e8e-43ef-962f-cd0729d79129)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/c09e26b3-7914-49ac-bb4c-1222b2c1c3eb)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/41a641ab-fa47-4912-8ab3-d1de1ed90d95)

### Additional information

If you want more screenshots let me know. However, I provided enough to display how weird and strange this is. Some of these nations shouldn't be this low at all, and I personally, although didn't record, watch every nation's base stability decline by 5.

**Comment by BoneSteelTNO** [comment]
I just found out that this is linked to another bug "We rise across the Dnieper" being present for each and every nation throughout TNO. I have this decision even as Japan. Although I am pretty sure you know about this bug already. 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/f6552693-c50a-410f-9b35-5dfae9abf11b)

**Comment by runelead00** [comment]
Fixed in Dev Build
