### ISSUE TITLE
FRS - France State still can't build army even after Burgundy war

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2557]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

France State has all armys locked at the beginning of round, to make itself weaken and impossible to beat burgundy
but after 1963 burgundy war, FRS still can't build army, this will make it very easy to die in civil war
even Free France returns peacefully, FRS still get armys locked, this is unreasonable

### Steps to reproduce / Cause of the issue

Here's the way to fix
Add a immediately effect for 1964 elections, no matter who becomes country leader, France will unlock divisions

### Expected behaviour

FRS can unlock armys after burgundy war

**Comment by runelead00** [comment]
Working as Designed, France gets new sets of troops loaded at the start of the civil war and old set removed, removing lock when make them very overpowered in civil war scenarios

**Comment by MrStraws114514** [comment]
> Working as Designed, France gets new sets of troops loaded at the start of the civil war and old set removed, removing lock when make them very overpowered in civil war scenarios

but if Pinay or king made reconciliation with Free France, France Republic is still not able to build army, i think this might belongs to bug
