### ISSUE TITLE
USA - Mission "The German Remnants"

### ISSUE THREAD

**Issue by eruaeru** [TNODevs/TNO-Bug-Tracker#2558]
### Operating System

Windows 10

### HOI4 version

1.13.4

### TNO version

1.5.0b

### Do you have other mods in use?

1.5.0.b

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

WTT, MTG, LAR, NSB, BBA, AAT

### Describe the bug

The mission "The German Remnants" popped up in my USA game. The mission is impossible to complete, so I'm losing 5 % base stability every month.

### Steps to reproduce / Cause of the issue

I don't know. The mission popped up before the start of the Ukrainian Civil War.

### Expected behaviour

The mission not popping up

### Screenshots

![wat](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131889210/8bffc60a-3c4e-4478-9505-aee343bd9c11)

**Comment by runelead00** [comment]
Fixed in Current Release
