### ISSUE TITLE
UKS - The attack on Poland cannot be triggered correctly

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#2559]
### Operating System

Windows 10

### HOI4 version

V1.13.4

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Red Ukraine united Ukraine, the attack on Poland could not be triggered properly.After checking, I found that the TAG was written incorrectly, and this event should change the TAG to UKS.
![捕获294](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/1dfc5e5b-80ea-49c7-b2cc-99d030c1e212)

### Steps to reproduce / Cause of the issue

Change TAG from UKR to UKS

### Expected behaviour

Let the Red Ukraine attack Poland correctly

**Comment by runelead00** [comment]
Fixed in Dev Build
