### ISSUE TITLE
Japan - Shiina becomes PM even if he isn't supposed to

### ISSUE THREAD

**Issue by Voltz12h** [TNODevs/TNO-Bug-Tracker#256]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10
- TNO Version: 1.2.0c
- Any other mods in use: Terra e Libertà/Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all of them except No Step Back (which hasn't come out yet)

**Longer Description of Issue:**
Shiina becomes PM instead of Fukuda after destroying his political career as Kaya
**Steps to Reproduce/Cause Issue:**

1.Play Kaya
2. Chooes the middle path toeing the line between the hardliners and the opposition groups
3. Choose the New Old Bureaucrats path
4. Confirm Fukuda as Kaya's successor
5.  Shiina becomes PM even if his political life is basically non existant

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Current Release
