### ISSUE TITLE
Omsk (West Russian provincial authority) tries to liberate Ukraine from behind the Urals

### ISSUE THREAD

**Issue by Thatrandomguyontheweb** [TNODevs/TNO-Bug-Tracker#2560]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.50a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

As Omsk you get the event to liberate Southern Ukraine however it is 1967 and only Western Siberia is under the league's control.
This bug breaks your stability and even after the reichskommisariats annex it you still get the event.

### Steps to reproduce / Cause of the issue

1. play Omsk and make sure Yazov survives
2. Have RK Ukraine and Caucusus invade Gotenland
3. profit from -5% stability every month

### Expected behaviour

that I get the event to liberate Crimea after I reunified Russia

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/143511581/0954f56b-2e62-4678-aebc-2079f319bd74)

### Additional information

It might have a corrolation with the reichskommisaraits invading Crimea as then the event first appeared.
The scramble for the urals also didn't appear event after the focus and I had to debug its start.

**Comment by runelead00** [comment]
Fixed in Dev Build, waiting on someone to push an emergency non-save breaking hotfix
