### ISSUE TITLE
BRY (Buryatia after forming Far Eastern Soviet Republic) - The description that showed "Planned Economy" was switched "Burn the fanatics" and a Coca-Cola symbol

### ISSUE THREAD

**Issue by mrTVD** [TNODevs/TNO-Bug-Tracker#2561]
### Operating System

macOS

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA, AAT

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13233183/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13233200/game.log)

### Describe the bug

Basically I loaded up my saved game and when I clicked on the economy tab to check up on my debt, I saw that the planned economy and its title was replaced with burn the fanatics (I'm guessing its one of the other nations economies) with no description present and a Coca Cola symbol (which I think is used for American Capitalism). I have no idea what happened but I just accidentally found this minor bug which I will report just in case.

### Steps to reproduce / Cause of the issue

1. Open Hoi4 through steam.
2. Launch Hoi4 with only the TNO mod (no add ons or anything) and its version history as of November 1st.
3. Load up a saved game of Far Eastern Soviet Republic.
4. Click the economy tab as you load in.
5. The bug is just there. I don't think the steps are that important considering I think it might just be something relating to the update that was done on October 31st for the main TNO mod.

### Expected behaviour

Expected it to show me the usual "planned economy" title and description as well as the usual Communist economy symbol

### Screenshots

<img width="279" alt="Burn the Fanatics" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/149638667/1cd82e26-5d08-4514-b8ea-31ff67a4e7a2">

### Additional information

If my explanation of what the bug is then I hope the screenshot should at least explain enough of it.

**Comment by runelead00** [comment]
You started this save on 1.5.0a, which is not compatible with the most recent version of TNO

**Comment by mrTVD** [comment]
> You started this save on 1.5.0a, which is not compatible with the most recent version of TNO

Ok, thanks. That makes so much more sense. I'll be sure to know about this in the future.
