### ISSUE TITLE
United kingdom - The economy map is glitched

### ISSUE THREAD

**Issue by Zombiemancz** [TNODevs/TNO-Bug-Tracker#2564]
### Operating System

Windows 10

### HOI4 version

Latest version

### TNO version

Latest version

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT

### Files

Apparently i cant sent saved games here. Not even, if i zip them, that sucks

### Describe the GFX issue

The map is glitched into trillion Leadings. You can still see the other provinces with a cursor, but it looks really bad.

### Steps to reproduce / Cause of the issue

Win as collaboration Britain
Do the pragmatist path
Do focus Rectyfing Lloyd-George's Mistakes
Open the economy map

### Expected behaviour

For map to appear as before the civil war

### Screenshots

![20231102_210341](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98554353/b18acdb3-b1eb-4bc5-9a39-61c716fb5c2c)

**Comment by Stormeagle449** [comment]
Fixed in TNO's current version.
