### ISSUE TITLE
USA - Foreign Policy Button Disappeared 

### ISSUE THREAD

**Issue by frozonion** [TNODevs/TNO-Bug-Tracker#2565]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13246426/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13246427/error.log)

### Describe the bug

Playing as USA, bug deletes the foreign policy tab entirely.

Moments before foreign policy deletion: there was a tab that said "south american cold war", clicked on it and it removed the foreign policy tab.

Reloading and restarting the game does not fix the bug.

### Steps to reproduce / Cause of the issue

Foreign policy open during war in South Africa and Japan's invasion of Philippines
New side tab "south american cold war" seen
clicking on it deletes the foreign policy tab

### Expected behaviour

Expected more foreign policy options

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149748420/d24f1b17-39f2-482e-908f-4e6617c5dd46)

### Additional information

clicking on foreign policy notification does nothing

**Comment by MrStraws114514** [comment]
when did you create this file?
TNo just had a hotfix today, if you start game before that update, file will be destroyed and some random bugs will happen

**Comment by frozonion** [comment]
Started Yesterday

**Comment by runelead00** [comment]
Likely broken by hotfix, all you can do is restart
