### ISSUE TITLE
All tags - OUTDATED sign in equipment doesn't show when selecting minimize production line

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2567]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13249527/USA_play.zip)

### Describe the GFX issue

The OUTDATED sign in equipment doesn't show when selecting minimize production line and it shows less transparency brown bar. 

### Steps to reproduce / Cause of the issue

1. Play any tag.
2. Upgrade some ships or tanks in the production lines.
3. Selecting minimize production line.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/146d00b8-a287-488e-a6d7-5af6a0d2b3d2)

**Comment by runelead00** [comment]
Fixed in Dev Build
