### ISSUE TITLE
ITA - Military Advisors national spirit not working correctly

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#257]
- Operating System: Windows 10
- HOI4 Version: Collie 1.10.8
- TNO Version: 1.2.0c
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? i own them all

The military advisors national spirit, which is supposed to let me send 4 more volunteers to Algeria, does not actually work. I was only able to send one division.

![image](https://user-images.githubusercontent.com/59315866/142901172-f0981adc-8654-4a7b-805d-655c9edc6dc4.png)
![image](https://user-images.githubusercontent.com/59315866/142901302-40859c3a-a049-4c6c-9c90-27177c4f235c.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
