### ISSUE TITLE
Zombie mode - country sometimes don't get firethrower buff

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2571]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

when country researches Assault weapon during zombie mode enables, system will give it a buff
but it only works when zombie enables, that means this country will have no chance to get buff if it finishs tech before zombie enables

### Steps to reproduce / Cause of the issue

add this into spook_temp.4
		option = {
			if = {
				limit = {
					OR = {
						has_tech = assault_weapons_1
					}
				}
				add_ideas = Anti_Zombie_Weaponry_1
			}
			if = {
				limit = {
					OR = {
						has_tech = assault_weapons_2
					}
				}
				add_ideas = Anti_Zombie_Weaponry_2
			}
			if = {
				limit = {
					OR = {
						has_tech = assault_weapons_3
					}
				}
				add_ideas = Anti_Zombie_Weaponry_3
			}
			if = {
				limit = {
					OR = {
						has_tech = assault_weapons_4
					}
				}
				add_ideas = Anti_Zombie_Weaponry_4
			}
			if = {
				limit = {
					OR = {
						has_tech = assault_weapons_5
					}
				}
				add_ideas = Anti_Zombie_Weaponry_5
			}
		}

well..ik i shouldnt report this here, but but I've done the code, and it works in my tests, just upload it then it will fix
thanks a lot if you can help me to do it

### Expected behaviour

Countries can get firethrower buff correctly

**Comment by MrStraws114514** [comment]
sorry, add "every_country = limit not =  ZOM" before this code, or this will only works on ZOM itself

**Comment by runelead00** [comment]
Fixed in Dev Build
