### ISSUE TITLE
GER - Josias breaks Germany's content

### ISSUE THREAD

**Issue by averagetomskenjoyer** [TNODevs/TNO-Bug-Tracker#2572]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

In my recent game, when Germany reconquered RK Kaukasien led by it's starting leader Josias, instead of reestablishing the RK, Germany annexed it's entire territory, which broke Germany's content (Germany was led by Speer).

### Steps to reproduce / Cause of the issue

1. Play as Germany (Speer or Bormann)
2. Make sure Josias stays in power in Kaukasien
3. Defeat Josias
4. Germany should annex Kaukasien

### Expected behaviour

Germany should reestablish Kaukasien instead of annexing it.

### Screenshots

![20231103135026_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148972379/b05dfd4f-78eb-4048-9664-047cb05df280)
![20231103223259_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148972379/6af3c293-4964-47a9-bd77-873fd55bf29f)

**Comment by runelead00** [comment]
Fixed in Dev Build
