### ISSUE TITLE
Japan - Misspell "Thorough" as "Through" in Takagi Focus

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2574]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The word Thorough has been misspelled as Through in the "Solidify Our Practices" focus in Takagi's First tree.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/c8d4c8bd-685e-4beb-a55e-6a5c73858448)

**Comment by runelead00** [comment]
Fixed in Dev Build
