### ISSUE TITLE
RUS, CAO, CZE, TYR - countries can't get core issues

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2575]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

This is 3 different bugs about core, i dont wanna spam reports so i put them together hete
1.in event **cao.101**, cameroon takes state 1207 after collapse war, but cao doesn't get core of it
2.in decision **RUS_coring_integrate_kola**, it doesn't add core for state 1724, that means if West Russia beat Finland but got beaten by siberia countries, they have no way to get core of 1724 by coring
3.in scripted_effects **GER_GCW_begin**, CZE controls state 9 and 75 transitory, but doesn't get core of it

### Steps to reproduce / Cause of the issue

1. in tno-event file
2. in tno-common-decisions file
3. in tno-common-scripted_effects file(also pls don't forget to remove core for it after Germany annex it)

### Expected behaviour

These 3 places can get core correctly

**Comment by MrStraws114514** [comment]
also, if Turkey win in central asia, TRK can't get core of TAJ, UTL and KYR after unite central asia

**Comment by Fortune801** [comment]
Fixed on dev build, Turkey not getting cores is WAD
