### ISSUE TITLE
USA - Support Magadan operations in progress are downward in some regions and upward in some regions in the Intelligence tab

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2576]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_operation_decisions.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13255953/USA_operation_decisions.zip)

### Describe the bug

In the Intelligence tab, the Support Magadan operations in progress are downward in Russia, East Asia, Southeast Asia and Oceana regions while the Support Magadan operations in progress are upward in Middle East, Africa, Europe, South America, Central America and North America regions. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Select support Magadan operations in the intelligence tab.
3. Select some other regions in the intelligence tab.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d1be05b1-d340-413c-9f28-ffb34bf6aa44)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bcd72c76-a980-4c9a-9f62-996177590ea8)

**Comment by runelead00** [comment]
Fixed in Dev Build
