### ISSUE TITLE
USA - Some issues for second option from 'Nixon's Dilemma' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2577]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_nixon's_dilemma.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13256065/USA_nixon.s_dilemma.zip)

### Describe the bug

In the second option from the 'Nixon's Dilemma' event, there is a double 'The Progressives in the coalition will not be happy' and Nativist Voters have support Democratic Party instead of Republican Party due to nativists are conservatives, I think.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Do not take any civil rights issues focuses.
3. Bloody Wednesday event triggers.
4. 'Nixon's Dilemma' event triggers.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e623e8f7-58b8-4cfe-a5b9-214a7ffbef3b)

**Comment by runelead00** [comment]
Fixed in Dev Build
