### ISSUE TITLE
USA - No space after sentence loc in the 'Icarus' event effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2578]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Icarus.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13256104/USA_Icarus.zip)

### List the loc issues below

- [ ] 1. No space before "The 100 Command Power loaned....." in the 'Icarus' event effects.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ae469076-a8c3-43c8-beec-fdcfbf5516d0)

**Comment by runelead00** [comment]
Fixed in Dev Build
