### ISSUE TITLE
West Siberian People's Republic (Probably every soviet remnant state), "We rise across the Dnieper, and into history." mission triggering even after Gotenland no longer exists.

### ISSUE THREAD

**Issue by beanbakerguy** [TNODevs/TNO-Bug-Tracker#2579]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as soviet remnant states, Reichsgau gotenland (I'm pretty sure) existing causes the "We rise across the Dnieper, and into history." mission, which gives a -5% stability debuff every 20 days it is not completed. To complete it, a player must be neighbouring gotenland with at least 1 division in a state neighbouring gotland, and select the option to declare war on it. The issue is, this mission continues to trigger even when gotenland no longer exists, meaning that you will get a -5% debuff to stability every 20 days, permanently.

### Steps to reproduce / Cause of the issue

This could be fixed very simply, by adding an additional condition that if gotenland no longer exists, this mission completes automatically.

### Expected behaviour

The mission to cancel if gotenland no longer exists, or no longer controls crimea and kherson.

**Comment by runelead00** [comment]
Make sure you TNO is updated to the most recent version and restart your game, fixed in current release
