### ISSUE TITLE
Bennet USA, the public discontent can't be removed

### ISSUE THREAD

**Issue by marko606** [TNODevs/TNO-Bug-Tracker#258]
**Questions**

- Windows 10:
- 1.10.4:
- 1.2.0:
- No:
- yes?
- None

**Longer Description of Issue:**
after I won the SAW the public discontent spirit doesn't deescalate and it stays on "societal breakdown"

**Steps to Reproduce/Cause Issue:**

1. win the SAW

2. set up the mandates

3. I was also in Indonesia but I don't remember if it was before or after SAW

**Screenshots:**
https://user-images.githubusercontent.com/61092515/142901446-5238fa3b-9c58-496e-a33a-78ea95a49b12.png
https://user-images.githubusercontent.com/61092515/142901536-1b2c1cfe-0a14-4ff5-b3cb-d5f048fa1d72.png

**Comment by thashepherd** [comment]
This occurred for me as both RFK and Glenn as well. I shared a fix in https://github.com/TNODevs/TNO-Bug-Tracker/issues/210 (which is the same bug) which will allow you to continue your playthrough normally.

Note that the timed decision which is supposed to (but doesn't) reduce discontent still continues to fire even after this console fix.

**Comment by runelead00** [comment]
No longer an issue in UB
