### ISSUE TITLE
USA - Some issues in the 'Coordinated Local Uprising' decision effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2581]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_second_malagasy_uprising.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13256268/USA_second_malagasy_uprising.zip)

### List the loc issues below

- [ ] 1. In the 'Coordinated Local Uprising' decision effects, there are spaces of effects for 'Ambatondrazaka', no line break for 'Remove No Authority which granted: and there is a space for 'Add Isolated Authority which grants:'. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fd2718dc-f65d-4d14-8121-8792341d4d32)

**Comment by runelead00** [comment]
Fixed issue with no line break after create unit effect
