### ISSUE TITLE
USA - There are some spaces in the 'Formalize Control' decision effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2582]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13256354/USA_play.zip)

### List the loc issues below

- [ ] 1. In the 'Formalize Control' decision effects, there are spaces before 'Remove Tamed Territory which granted:' and 'Add Base of Operations which grants:'.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/49e166b9-b934-47b8-b7cf-d1ab4317fcce)

**Comment by runelead00** [comment]
Can't fix, that's how the base game displays state scoped effects, it's not a thing we can change
