### ISSUE TITLE
UKR INVADE DICISION CAUSE ALL COUNTRY -5% ST PER WEEK

### ISSUE THREAD

**Issue by XiaoCXXX** [TNODevs/TNO-Bug-Tracker#2583]
### Operating System

WIN11

### HOI4 version

1.13.4

### TNO version

1.5.0b

### Do you have other mods in use?

FPS map

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

ukr invade decision will send to all the country. We can't finish the dicision which make st of all nation -5% every week

### Steps to reproduce / Cause of the issue

fix the dicision. Let it not send to all the nation

### Expected behaviour

solve the bug

**Comment by MrStraws114514** [comment]
Fixed in recent update, you can download fixed version in nexusmod if you dont have steam

**Comment by runelead00** [comment]
Make sure you TNO is updated to the most recent version and restart your game, fixed in current release
