### ISSUE TITLE
Nation ideas - Unhelpful reducing factor ideas that should be removed

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2584]
### HOI4 version

1.13.3

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

here are some ideas i feel unhelpful and should be removed
EGY_idea_colonial_government
IEA_idea_colonial_government
GER_BOR_dont_join_wars_please
MEN_mengjiang_conflict_dont_join
GAW_cta_block

### Justifications

These ideas are outdated and have no meaning in the game, only to prevent players from inviting them in ww3 or zombie mode
mengjiang might used for yun vs chi before, but now men will be auto autonomy by japan
GAW cta block is only used for Gao zongwu's CHI gaw, but there is no CHI gaw in game

**Comment by runelead00** [comment]
Remove the last two, but the other are very much in the game for a reason and have meaning
