### ISSUE TITLE
Usa and Germany  - When gotenland declares war i always get that decision named "The german Remnants" i can't get it away

### ISSUE THREAD

**Issue by Zanocchia** [TNODevs/TNO-Bug-Tracker#2585]
### Operating System

Windows 11

### HOI4 version

1.13.5

### TNO version

1.5 The Ruin

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the german civil war appears, gotenland will declare war to ukraine and caucasus. Me, playing as the USA i just got that decision "The German Remnants". I can't get it away

### Steps to reproduce / Cause of the issue

After the german civil war appears, gotenland will declare war to ukraine and caucasus. Me, playing as the USA i just got that decision "The German Remnants". I can't get it away

### Expected behaviour

In think is not supposed to appear for usa

**Comment by runelead00** [comment]
Make sure you TNO is updated to the most recent version and restart your game, fixed in current release
