### ISSUE TITLE
WRS - Unit model completely dark exept guns (also i think i may have been banned from your discord but idk why. (username is LuccaVG))

### ISSUE THREAD

**Issue by LuccaVG** [TNODevs/TNO-Bug-Tracker#2586]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

NO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT

### Files

![Captura de tela 2023-11-04 153448](https://github.com/TNODevs/TNO-Bug-Tracker/assets/112782142/7dc9b15e-ceb9-41b9-a2a4-b390474e2f26)

### Describe the bug

Units 3d models show up simply black. the helmets, the uniforms all black

### Steps to reproduce / Cause of the issue

1.start game
2.select wrs as playing nation
3.look at the units

### Expected behaviour

unit models not looking like a black hole

### Additional information

i would like to know why was i banned from the discord.

**Comment by Vperedsmotryashchij** [comment]
Thank God someone else wrote about this!

**Comment by runelead00** [comment]
#2519 Duplicate issue
