### ISSUE TITLE
SAM - No national focus icon for 'A Renewed Spirit'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2587]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13258053/USA_play.zip)

### Describe the GFX issue

'A Renewed Spirit' national focus has no GFX icon.

### Steps to reproduce / Cause of the issue

1. Miletiy Zykov's influence is greater in Samara.

### Expected behaviour

Forgot to add GFX focus icon.  

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/752bfe0c-a2f4-4056-b34d-f4dece963210)

**Comment by runelead00** [comment]
Fixed in Dev Build
