### ISSUE TITLE
USA - Some prerequisites suggestion for increases volunteers to SAF decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2588]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I suggest that the prerequisites of the 'Expand Ground Operations' decision should be changed to 'Max volunteers less than **+6**' instead of '**+7**' and the 'Greatly Expand Ground Operations' decision should be changed to 'Max volunteers less than **+7**' instead of '**+6**'.

### Justifications

Because, it is weird that the 'Greatly Expand Ground Operations' decision required to have 'Max volunteers less than +6', and its decision effect and decision requirement are much greater than the 'Expand Ground Operations' decision that it required to have 'Max volunteers less than +7'

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9a2d46f6-a900-4858-a893-f7dbb9452b25)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c1799732-6954-42c4-b69f-3423a56eff5b)

### Additional information

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13258120/USA_play.zip)

**Comment by runelead00** [comment]
They have different caps because they give different amounts of units
