### ISSUE TITLE
VOR/YGR - 'Pechora War' national spirit doesn't get removed after either of them won the war

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2589]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After either Vorkuta or Yugra wins the Pechora War, the 'Pechora War' national spirit doesn't get removed.

### Steps to reproduce / Cause of the issue

1. Vorkuta and Yugra are at war.
2. Either Vorkuta or Yugra wins the war.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9b72c00e-2181-47e1-acaf-e74b236c2f60)

**Comment by runelead00** [comment]
Fixed in Dev Build
