### ISSUE TITLE
Magadan - clicking on the event 'A typical meeting' to overthrow Matkovsky crashes the game

### ISSUE THREAD

**Issue by ThatSecondLuke** [TNODevs/TNO-Bug-Tracker#259]
**Questions**

- Operating System: Not sure
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0c
- Any other mods in use: Yes, TNO Custom Paths and Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all the expansions

**Longer Description of Issue:**
I was playing Magadan, and whilst playing, I tried to go reformist Petlin, and so I build up Reformist power and click the decision Overthrow the Tyrant. The event 'A typical meeting' fires and I read it, and click it. The game crashed to desktop immediately. To double check, I reloaded the game and did the same thing, and it crashed to desktop once more.

**Steps to Reproduce/Cause Issue:**

1. Play Magadan up until you can overthrow Matkovsky

2. Click on the decision to overthrow him

3. Click the event

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**

**Comment by Wizard2020** [comment]
I think there's a good chance your problem is using the custom country paths submod. It hasn't been updated to be compatible with TT and using it will cause problems. You should wait for its TT compatibility update before using it again.

**Comment by runelead00** [comment]
Assumed issue is due above reason, closing
