### ISSUE TITLE
SER - Nationalist Serbia has the Worker Directed economy typed

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2590]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Serbian National Liberation Front proclaimed the Republic of Serbia, Nationalist Serbia has the Worker Directed economy type instead of changing one. 

### Steps to reproduce / Cause of the issue

1. Serbian Civil War triggers.
2. Serbian National Liberation Front won the Civil War.
3. Serbian National Liberation Front became the 'Republic of Serbia'.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ae95db45-6502-462d-bf62-51cb3623e7f1)

**Comment by runelead00** [comment]
Fixed in Dev Build
