### ISSUE TITLE
CZE - Wehrkreis XIX uses the Czech flag in the state hover box instead of Wehrkreis XIX flag

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2591]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13258634/USA_play.zip)

### Describe the bug

Wehrkreis XIX uses the Czech flag in the state hover box instead of Wehrkreis XIX flag. 

### Steps to reproduce / Cause of the issue

1. The German Civil War starts.
2. Wehrkreis XIX remains neutral.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6c61ff6c-d422-44e8-9410-ee9e6fe700b5)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d7a5c3a7-9906-4879-82ec-a2b29fc063b3)

**Comment by runelead00** [comment]
Fixed in Current Release, you have to reinstall TNO
