### ISSUE TITLE
USA - There is no 'Northern Fury' national spirit appear after selecting the 'Cooling Down' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2594]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13259103/USA_play.zip)

### Describe the bug

USA has the 'Northern Riots' national spirit and after selecting the 'Cooling Down' event, the 'Northern Fury' national spirit didn't appear. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Veto Civil Rights Act.
3. Robert F. Kennedy won the election.
4. 'Cooling Down' event triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/668365c5-ea73-4fce-b9c4-860775ad201d)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3788bf18-a09c-46b2-bcfb-db69d1e13e1e)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/eae47f78-abda-43c2-b664-7f958cb139b7)

**Comment by runelead00** [comment]
Fixed in Dev Build
