### ISSUE TITLE
GER - AI doesn't sent Air Fighters and Bombers. and taking air mission after sending volunteers during the SAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2595]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Greater German Reich intervened in the South Africa War by sending volunteers to the Afrika-Schild, AI Germany is not able to send Aircraft Fighters and Bombers(Close Air Supports and Tactical Bombers) and taking air missions. 

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. Either Bormann or Speer wins the German Civil War.
3. Germans intervened in the South Africa War.

### Expected behaviour

I don't know what causes this.

**Comment by runelead00** [comment]
We can't touch how the AI uses air units as far as know, if it's an issue it's on paradox's side
