### ISSUE TITLE
USA - Extending an Olive Branch decisions are disappeared after the NPP president inauguration

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2596]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13259274/USA_game.zip)

### Describe the bug

After the NPP president's inauguration, 'Extending an Olive Branch' decisions are somehow disappeared. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Has the Extending an Olive Branch decisions.
3. Elect the NPP president.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5a822d65-ae9a-4d26-a485-13f33151c3ab)

**Comment by runelead00** [comment]
Fixed in Dev Build, Deccat is now disabled when Nixon is no longer in power rather than waiting till inauguration
