### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by modpathisinvalid** [TNODevs/TNO-Bug-Tracker#2597]
### Operating System

Windows 11

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Foriegn Policy tab is blank, it has no text on the left but decisions are still visible on the left.

### Steps to reproduce / Cause of the issue

1. Scale gui scaling to 0.9 (Possible cause)
2. Load a prexisting save
3. Go to politics tab
4. Observe lack of text

### Expected behaviour

The text of the left part of the Tab should appear along with other images

### Screenshots

<img width="960" alt="Screenshot 2023-11-04 223048" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/130386920/c4beee19-cdfa-4129-9c0b-3799e3a12e97">

### Additional information

I changed the gui scaling from 1.0 to 0.9 because tno would crash if I had it at 1.0

**Comment by runelead00** [comment]
I look like you loaded a save from before the most recent update, or enabled a submod mid-game, seems unrelated to gui scaling

**Comment by modpathisinvalid** [comment]
> It looks like you loaded a save from before the most recent update, or enabled a submod mid-game, seems unrelated to gui scaling

Yeah, No I've only just started this save 3 days ago.
