### ISSUE TITLE
USA - German Intelligence Network doesn't decrease in Caribbean America region after successful operation

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2599]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b (emergency update version)

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13262221/USA_play.zip)

### Describe the bug

After Operation AJFICTION success, the German Intelligence Network doesn't decrease in the Caribbean America region from the intelligence tab.

### Steps to reproduce / Cause of the issue

1. German Civil War ends.
2. Germany has the intelligence tab.
3. Operation AJFICTION selected.
4. Operation AJFICTION success.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/13419694-f242-447a-8bed-464f458294aa)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/09c77a77-b00a-4318-bca7-e8de000878ae)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5c588ae1-4bab-440f-9a54-5ca8feacd2ca)

**Comment by runelead00** [comment]
Fixed in Dev Build
