### ISSUE TITLE
Kaminski's Tver Republic - Core on Herat?

### ISSUE THREAD

**Issue by brmusch** [TNODevs/TNO-Bug-Tracker#260]
**Questions**

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**
Kaminski has a core on Herat
**Steps to Reproduce/Cause Issue:**

1. Launch TNO

2. Look at Herat

etc...

**Screenshots:**
https://gyazo.com/ab0318fac3333986db8c0ab65741748e

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
