### ISSUE TITLE
USA - 'Discontent Towards African Interventions' national spirit is not removed after the WAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2602]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13265621/Logs.zip)
[USA_palf_defeated.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13265990/USA_palf_defeated.zip) Run the game to see what happen

### Describe the bug

'Discontent Towards African Interventions' national spirit doesn't remove after the West Africa War.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Scenario 3 West Africa War triggers. 
3. Select WAW decisions to decreasing discontent.
4. Not to select decisions that increasing discontent.
5. The West Africa War ends.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3428f42b-de95-43ea-9943-5ed3099f58bc)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/33b32630-7ce5-4c18-85f0-56b0953ab802)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
