### ISSUE TITLE
USA - bobby.justice.51.b is not localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2603]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_the_noise_of_thunder.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13266131/USA_the_noise_of_thunder.zip)

### Describe the bug

bobby.justice.51.b is not yet localized in The Noise of Thunder event.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Select option 2 from dealing with KKK event.
3. The Noise of Thunder event triggers.

### Expected behaviour

Forgot to adding loc, I think

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/47a5bb50-6684-4e34-9ee4-d08c8a5e2387)

**Comment by runelead00** [comment]
Fixed in Dev Build
