### ISSUE TITLE
NGR - Economic Reconstruction national spirit appeared 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2604]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_fma_takes_niger.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13266299/USA_fma_takes_niger.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13266300/Logs.zip)

### Describe the bug

After Free France defeated Zarmaland, and Niger emerged and joined the FMA, Niger has 'Economic Reconstruction' national spirit appeared.

### Steps to reproduce / Cause of the issue

1. FMA wins the scenario 3 West Africa Crisis.
2. FMA invades Zarmaland.
3. Zarmaland is defeated and reactionary Niger joins FMA.

### Expected behaviour

I don't know exactly.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e36808a0-ac22-45fd-9719-167b772fe935)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a34d47e1-a632-4d07-aa7c-b9b96e06d09b)

**Comment by runelead00** [comment]
Fixed in Dev Build
