### ISSUE TITLE
USA - There is "Remove ." in 'The Death of Hope' event effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2605]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13267066/USA_play.zip)

### List the loc issues below

- [ ] 1. In The Death of Hope' event effects, there is a "Remove ." shown and a dot (".") has space after "Remove" word.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f5edbf83-4f42-4266-8604-e7da290ae13a)

**Comment by runelead00** [comment]
Fixed in Dev Build
