### ISSUE TITLE
USA - 'Silence the Attorney General' decision timer reappeared and reset after the assassination of RJK

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2606]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_RFK_assassinated.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13267245/USA_RFK_assassinated.zip)

### Describe the bug

After selecting 'The Death of Hope' event, the 'Silence the Attorney General' decision timer suddenly reappeared and reset. This decision should be removed if Robert F. Kennedy is no longer a president. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect NPP Robert F. Kennedy as the new president.
3. Make right-wingers lots of anger towards RFK.
4. Complete the 'Betting the Southern Bullies' focus.
5. Has the 'Silence the Attorney General' decision timer.
6. Robert F. Kennedy and William Guy were assassinated.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/58504d13-6765-4608-9fd4-7b1fbd039531)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0377235f-ca54-4212-b714-6b50e64247ec)

**Comment by runelead00** [comment]
Fixed in Dev Build
