### ISSUE TITLE
USA - There is a word "center" instead of "progressive" about NPP left

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2608]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. "The Center Should Not Hold" focus should be "The Progressive Should Not Hold" because to NPP center and far-right have changed. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0709b620-f63c-4127-93a6-dc629aed6ddd)

**Comment by runelead00** [comment]
It's a common turn of phrase, were not changing it
