### ISSUE TITLE
ITA - 'Thermobaric Technological Advantage' national spirit has no GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2609]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13273457/USA_play.zip)

### Describe the GFX issue

'Thermobaric Technological Advantage' national spirit has no unique GFX icon.

### Steps to reproduce / Cause of the issue

1. Scorza wins the power struggle against Ciano.
2. Scorza begins phase 2 of his focus trees.
3. Italy has the 'Thermobaric Technological Advantage' national spirit.

### Expected behaviour

Forgot to add the GFX icon.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/125ba2f6-7104-4fd3-83f7-762e5d7a5920)

**Comment by runelead00** [comment]
Fixed in Dev Build
