### ISSUE TITLE
GRO/BOR - South Africa War national spirits didn't get removed after the SAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2610]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13273499/USA_play.zip)

### Describe the bug

After either partial or total victory for the Afrika-Schild in the South Africa War, South Africa War national spirits for Großafrikanischer Reichsstaat and Afrikaner Volkstaat are not removed. 

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. Either partial or total victory for the Afrika-Schild.

### Expected behaviour

Forgot to remove them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b410d9c6-6b21-4d5d-b1f4-861b3a5e3a08)

**Comment by runelead00** [comment]
Fixed in Dev Build, I've removed the two ideas you've listed here, you took pictures of here. idk if the other one you circled is also supposed to be removed, but I'm not spending 10 minutes loading a save to find out

**Comment by Ikidikid** [comment]
@runelead00, here is other one that I circled.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aea871f3-21cb-4aeb-b69a-b466b8fff7c1)

**Comment by runelead00** [comment]
Fixed in Dev Build
