### ISSUE TITLE
ITA - The 'National Corporations' focus GFX icon has Italy Atlantropa

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2611]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13273540/USA_play.zip)

### Describe the GFX issue

The 'National Corporations' focus GFX icon still has the Atlantropa remnant. 

### Steps to reproduce / Cause of the issue

1. Scorza wins the power struggle against Ciano.
2. Scorza begins phase 2 of his focus trees.
3. See the focus GFX icon of 'National Corporations'.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f721e723-0478-4ec3-a2d3-ad8230cf1fe1)

**Comment by runelead00** [comment]
Fixed in Dev Build
