### ISSUE TITLE
USA - German Intelligence Network doesn't decrease in South America region after successful operation

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2612]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13276141/USA_play.zip)

### Describe the bug

After Operation BTSTART success, the German Intelligence Network didn't decrease in the South America region from the intelligence tab.

### Steps to reproduce / Cause of the issue

1. The German Civil War ends.
2. Germany has the intelligence tab.
3. Operation BTSTART selected.
4. Operation BTSTART success.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ed6bf9cc-97bf-4288-9a5e-3c6a7bf55787)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bc51570f-2c80-4a64-bd20-1ceb4c5238d6)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fb23d0c9-b41a-4540-b49c-a431e8f2d8ce)

**Comment by runelead00** [comment]
Fixed in Dev Build, CA and SA were swapped in effects
