### ISSUE TITLE
USA - Berry Goldwater is still the leader of Hardline Republicans instead of replacing him when Goldwater inauguration 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2613]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13279806/USA_play_game.zip)

### Describe the bug

At the Berry Goldwater inauguration, Berry Goldwater is still the leader of Hardline Republicans instead of replacing him in the Smokes and Mirrors' decisions.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect NPP President in 1964.
3. Choose Goldwater RDC primary.
4. Elect Berry Goldwater as the new president.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/18af6445-9efd-4667-acc1-79f3825b4c4f)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4fca35b3-6bff-45b6-b810-206ab3630853)

**Comment by runelead00** [comment]
Fixed in Dev Build
