### ISSUE TITLE
GBE - Hubert Maga (Paternalistic Conservatism) is not become the leader of Dahomey after FMA victory in scenario 3 WAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2614]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_palf_defeated.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13280615/USA_palf_defeated.zip)

### Describe the bug

After FMA's victory in scenario 3 West Africa War and Dahomey became the subject of Free France, Hubert Maga (Paternalistic Conservatist) did not become the leader of Dahomey and Paternalistic Conservatism is not the ruling party in Dahomey. Because Hubert Maga is a pro-French.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Scenario 3 West Africa War triggers.
3. FMA won the West Africa War.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/338d172c-9ab5-4b09-abae-cef46bce3022)

**Comment by runelead00** [comment]
Both Maga and Soglo are pro-French
