### ISSUE TITLE
YOR - 'The Shield Against Socialism' national spirit is not removed after PALF defeated

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2615]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_palf_defeated.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13281154/USA_palf_defeated.zip)

### Describe the bug

When the PALF was defeated, Yorubaland still had the 'The Shield Against Socialism' national spirit and didn't remove it.

### Steps to reproduce / Cause of the issue

1. West Africa War triggers.
2. The West Africa War ends.
3. The PALF has fallen. 

### Expected behaviour

Forgot to remove it, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b1ae0804-9c76-494c-9dbe-fbff9db84eb2)

**Comment by runelead00** [comment]
Now removed when collapse begins
