### ISSUE TITLE
FFR's West African Subjects - Free France's West African subjects are not able to join the war against the French State

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2617]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13290379/Logs.zip)
[USA_france_recalmation.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13290411/USA_france_recalmation.zip)

### Describe the bug

Free France's West African subjects are not able to join the war against the French State during the reclamation of France while the independent Free France's West African allies are able to join the war. 

### Steps to reproduce / Cause of the issue

1. Free France wins the West Africa War.
2. Reclamation of France triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/28e36c22-719e-4479-a6ae-8bdfea05b505)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/330a364a-f16c-4a5c-971b-d696432bf37e)

**Comment by runelead00** [comment]
Fixed in Dev Build
