### ISSUE TITLE
FRD - Free France's French Republic doesn't set capital to South Paris after the reclamation victory

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2618]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13290635/Logs.zip)
[USA_reclamation_victory.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13290705/USA_reclamation_victory.zip)

### Describe the bug

After the victory of the Free French Reclamation of France, the French Republic didn't set its capital to South Paris. 

### Steps to reproduce / Cause of the issue

1. Free France wins the West Africa War.
2. Reclamation of France triggers.
3. French Resistance and Free France win the Reclamation of France.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/76c4e10b-b501-49c2-9de2-7f5b5debfe89)

**Comment by runelead00** [comment]
Fixed in Dev Build
