### ISSUE TITLE
HAI - USA is not embargo on Socialist Republic of Haiti after PPLN won the Haitian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2619]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the PPLN won the Haitian Civil War, USA and the rest of the OFN are not embargo on the Socialist Republic of Haiti despite the description in The Fall of Port-au-Prince event.

### Steps to reproduce / Cause of the issue

1. Haitian Civil War triggers.
2. PPLN won the Haitian Civil War.
3. USA and the Haitian government lost the HCW.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/666e3a1a-18ba-44e9-afc8-9a16f59c2f87)

**Comment by runelead00** [comment]
Fixed in Dev Build
