### ISSUE TITLE
HAI - Haitian Revolutionary Front doesn't remove in 'Foreign Claims' states after the Haitian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2620]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the Haitian Civil War, the Haitian Revolutionary Front is still appearing in 'Foreign Claims' states in all Haitian states.

### Steps to reproduce / Cause of the issue

1. Haitian Civil War triggers.
2. Either the Haitian Government or PPLN won the Haitian Civil War.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/091b6f0d-3c6a-4de3-9483-3a20ceb1c368)

**Comment by runelead00** [comment]
Fixed in Dev Build
