### ISSUE TITLE
GRO - Afrikaner-Abwehrfront doesn't remove in 'Foreign Claims' states in the most Central and South Africa after defeated in Congolese Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2621]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13292694/USA_play.zip)

### Describe the bug

After the Afrikaner-Abwehrfront was defeated in the Congolese Civil War and Afrikaner-Abwehrfront was removed in 'Foreign Claims' states in all Congo states, most of the Central and South African states still have Afrikaner-Abwehrfront in 'Foreign Claims' states

### Steps to reproduce / Cause of the issue

1. Großafrikanischer Reichsstaat collapses.
2. Afrikaner-Abwehrfront relocates to Leopoldville.
3. Congolese Civil War triggers.
4. Afrikaner-Abwehrfront defeated.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/523eb63b-b5ca-409a-bf68-fca69f582cb5)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9e594ae1-21e6-4222-9ebf-7f57bdbc6202)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f143083e-cb26-4716-a478-cdcc865da239)

**Comment by runelead00** [comment]
Fixed in Dev Build
