### ISSUE TITLE
GER - Militärverwaltung der Britischen Inseln is exists in the overview for German war 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2622]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13292786/GER.zip)

### Describe the bug

After viewing the war overview for Germany, there is a Militärverwaltung der Britischen Inseln exists despite the old Britain content is disabled (default). 

### Steps to reproduce / Cause of the issue

1. The German Civil War ends.
2. Germany retakes its hegemony through war.
3. See the German war overview.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1b20163d-a611-4287-9330-3cd07c68a9dc)

**Comment by runelead00** [comment]
Fixed in Dev Build
