### ISSUE TITLE
USA - USA_urban_black_shift is not localized and double Urban Voters in some of Goldwater's cutting welfare events

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2624]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13294075/USA_play.zip)

### Describe the bug

SA_urban_black_shift is not been localized and there are double Urban Voters in some of Goldwater's cutting welfare events.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Berry Goldwater as the new president in 1968.
3. Complete the 'Cut Wasteful Welfare' focus.

### Expected behaviour

Oversight, maybe.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2857ee86-d436-4cb7-b608-e93ca83d7e0d)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0345e9d3-8614-487c-8674-f86d582d145e)

**Comment by runelead00** [comment]
Fixed in Dev Build in both event issue is present
