### ISSUE TITLE
USA - FR_NPP_comprimise_desc_30 is not localized in 'A Metting with Russel' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2625]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13294424/USA_play.zip)

### Describe the bug

After selecting the 'Talk with the NPP's Nationalists' decision in 'Goldwater's New Budget!' bill decision and 'A Metting with Russel' event pops out, FR_NPP_comprimise_desc_30 is not localized. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Berry Goldwater as the new president in 1968.
3. Select the 'Budget Balanced' focus.
4. Select 'Talk with the NPP's Nationalists' decision.

### Expected behaviour

Forgot to adding loc, I think

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1cc5e76b-02b0-4e30-82d8-519256073c1c)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d167c1db-0cda-4ddc-aa99-a88986a26e45)

**Comment by runelead00** [comment]
Fixed in Dev Build
