### ISSUE TITLE
USA - 'Conservative Finance' national focus GFX icon uses Donkey instead of an Elephant

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2626]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The 'Conservative Finance' national focus GFX icon uses a Donkey (a democratic party icon) instead of an Elephant (a republican party icon) because of RDC-Republican is in charge of USA.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Berry Goldwater as the new president in 1968.
3. See the 'Conservative Finance' national focus GFX icon.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0846da3c-d6b3-42b5-8e48-3fee5c66d41e)

**Comment by runelead00** [comment]
Fixed in Dev Build
