### ISSUE TITLE
SER - Republic of Serbia still embargoed by other nations despite Serbia is no longer aligned with Einheitspakt

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2627]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the Serbian National Liberation Front became the 'Republic of Serbia' and the Germans are no longer invaded Serbia due to Serbia is not a communist nation, the Republic of Serbia still embargoed by other nations. 

### Steps to reproduce / Cause of the issue

1. Serbian Civil War triggers.
2. Serbian National Liberation Front won the Civil War.
3. Serbian National Liberation Front became the 'Republic of Serbia'.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2199d264-558f-42c7-acc4-40e2def30df2)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d3e698a8-64f4-40b5-8006-a2023038ca89)

**Comment by runelead00** [comment]
Fixed in Dev Build
