### ISSUE TITLE
USA - Navy Satisfaction Status turns all ships satisfaction to 0.00% when reaching 1967

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2628]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13296382/Logs.zip)
[USA_navy_satisfaction_bug.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13296463/USA_navy_satisfaction_bug.zip) Recommend to run the game to see what happen

### Describe the bug

After reaching 1967, all ship satisfaction turned 0.00% and could not increase in Navy Satisfaction Status through gameplay for USA while other tags that have sphere leader didn't affect them, only USA affected. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Play through 1967s.
3. See the Navy Satisfaction Status.

### Expected behaviour

I don't know what causes this. Probably some of the TNO team screwing over USA codes.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2a6cf7c9-c403-4f34-9b71-0e5d5f0fea97)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d9d2624b-b48e-4090-9df8-873d833b00b0)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b0d70d77-4c0a-4cd9-b580-094dbb083285)

**Comment by runelead00** [comment]
Fixed in Dev Build, just annex GAX and wait to fix it for yourself
