### ISSUE TITLE
UKR - Reichsland Ukriane has no Reichsland faction icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2629]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

While most of the eastern Europe controlled by Germany became Reichsland and have the Reichsland faction icon, Reichsland Ukraine, however, does not have the Reichsland faction icon.

### Steps to reproduce / Cause of the issue

1. Speer won the German Civil War.
2. Germany retakes Ukraine through war.
3. Germany chose 'Under the Boot' focus.
4. Most of the eastern Europe controlled by Germany became Reichsland.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/45634b08-7662-40fa-87e9-ccf3ee8e7b9a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ef5dd69d-f26f-4985-81ef-8a70ba20dfae)

**Comment by runelead00** [comment]
Fixed in Dev Build
