### ISSUE TITLE
COL - Post-CCW elections are no set ruling party and party popularity change

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2631]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Colombian election in 1970 was triggered after the NF Colombian government won the CCW, Colombia still had a current leader instead of changing its leadership.

In the post-COL CCW election in the code file, I see there are no `set_ruling_party` and changing party popularities like set ruling party should have more popularity than other parties for `COL_post_war.1` and `COL_post_war.2` options

### Steps to reproduce / Cause of the issue

1. National Front successfully deposed Pinilla.
2. Colombian government victory in the Colombian Civil War.
3. Colombian election in 1970 triggers.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/54f9f909-e253-4df7-979b-7bd0a204b51f)

**Comment by runelead00** [comment]
Fixed in Dev Build
