### ISSUE TITLE
OMA/IRQ - They used generic faction icon instead of unique Scorza's Italy faction member icon after their civil wars

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2632]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_italy_victory_in_middle_east.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13303033/USA_italy_victory_in_middle_east.zip)

### Describe the bug

After Pro-Italian Oman and Iraq won their Civil Wars, their faction icon used generic icon instead of Italy's own faction member icon because previously Scorza selected the new school foreign focus to create its own faction. 

### Steps to reproduce / Cause of the issue

1. Scorza is in charge of Italy.
2. Scorza creates Italy its own faction.
3. Middle East in flames.
4. Oil Crisis triggers.
5. Pro-Italian Oman and Iraq won their Civil Wars.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7d40e2cc-d93e-42e9-bff1-40dd4ce886b1)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aef69e12-8ce6-4b35-aee4-55152bb3a4c3)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/247c8e3a-9afa-4098-9e2c-544d666a4e0d)

**Comment by runelead00** [comment]
Fixed in Dev Build
