### ISSUE TITLE
IRQ - Iraq became Heavily Associated State instead of Colonial Government puppet status 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2634]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_italy_victory_in_middle_east.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13303592/USA_italy_victory_in_middle_east.zip)

### Describe the bug

After pro-Italian Iraq won the Iraqi Civil War, Iraq became a Heavily Associated State instead of a Colonial Government puppet status because the current Iraqi government is a Colonial Government under Italian. 

### Steps to reproduce / Cause of the issue

1. Middle East conflicts trigger.
2. The Oil Crisis starts.
3. Pro-Italian Iraq won the Iraqi Civil War.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/70a4aee2-2d89-4f4e-8917-570386116fe3)

**Comment by runelead00** [comment]
Fixed in Dev Build
