### ISSUE TITLE
USA - Colombo-American Negotiation beginning and endings events' effect have news event shown

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2636]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_america_colombia_relationship.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13305363/USA_america_colombia_relationship.zip)

### Describe the bug

The Colombo-American Negotiation's beginning and ending events effects have news events shown instead of adding hidden news events.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. National Front Colombian government won the La Violencia.
3. Either Borrero or Restrepo elects in post-Colombian government victory in La Violencia.
4. Re-establish a relationship between USA and Colombia.

### Expected behaviour

Forgot to add them hidden.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/cdf97f37-a093-4cad-8c41-35008ed04433)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a02ac830-58de-4a99-ad1a-27fb7673fec4)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5709b04a-8d38-4459-b1b3-989542432ed9)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4f6c5819-4704-4ccd-aaf0-6eaf2fdc7760)
![Image_5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0d8c0a65-f82c-45dc-b140-1e263744d897)

**Comment by runelead00** [comment]
Fixed in Dev Build
