### ISSUE TITLE
USA - GLD.301.t is not localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2637]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

GLD.301.t event is not been localized.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Choose Berry Goldwater as the new president.

### Expected behaviour

Forgot to add loc.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4ced6315-e994-453f-8bef-856e116419db)

**Comment by runelead00** [comment]
Fixed in Dev Build
