### ISSUE TITLE
All tags - Placeholder description news events of The Renewed Spirit of Mallarino-Bidlack and Colombia and the United States Agree on the Fundamentals

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2638]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_america_colombia_relationship.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13306304/USA_america_colombia_relationship.zip)

### Describe the bug

There are placeholder descriptions in The Renewed Spirit of Mallarino-Bidlack and Colombia and the United States Agree on the Fundamentals news events. 

### Steps to reproduce / Cause of the issue

1. National Front Colombian government won the La Violencia.
2. Either Borrero or Restrepo elects in post-Colombian government victory in La Violencia.
3. Re-establish a relationship between USA and Colombia.
4. Ok and good Colombo-American Negotiation news events trigger. 

### Expected behaviour

Forgot to add localization.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4eaecdc9-1dfd-4cf1-8e4b-1a5f9a4e7642)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/44ac8ee4-f081-4c39-8338-58c27d2ba744)

**Comment by runelead00** [comment]
Fixed in Dev Build
