### ISSUE TITLE
COL - No GFX portraits for post-National Front Colombia victory in CCW leaders

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2639]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Misael Eduardo Pastrana Borrero, Manuel Mosquera Garcés, Carlos Alberto Lleras Restrepo and Hernando Durán Dussán do have their GFX portraits when I looked at the TNO GFX leader folder for COL. 

### Steps to reproduce / Cause of the issue

1. National Front deposed Pinilla.
2. La Violencia resumes.
3. National Front Colombian government won the La Violencia.

### Expected behaviour

Forgot to add GFX post-CCW National Front Colombian leaders.

**Comment by runelead00** [comment]
Fixed in Dev Build
