### ISSUE TITLE
HMMLR England - Combatting Fiscal Crisis National Spirit never ends

### ISSUE THREAD

**Issue by originalperson0** [TNODevs/TNO-Bug-Tracker#264]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: No
- Were you using Steam? Yea
- Which expansions do you NOT have? i have all the major ones

**Longer Description of Issue:**
you get a fiscal crisis and when you try to fix it it gives you a permanent spirit called combatting fiscal crisis which gives you like -7% weekly stability and other stuff like 4935758375% inflation and -522% interest rate 
**Steps to Reproduce/Cause Issue:**

1. play HMMLR england and try to stall for a while to get radicalization up

2. win war

3. get fiscal crisis

4.  try to fix it but you get bad national spirit and gdp goes insane

etc...

**Screenshots:**

**Comment by originalperson0** [comment]
also some parts of the the repealing YDL bill thing as stirling has no loc

**Comment by runelead00** [comment]
Fiscal crises should be fixed in current release
