### ISSUE TITLE
USA - Bugs in Colombia Agrees to Intelligence Sharing event effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2640]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_america_colombia_relationship.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13306761/USA_america_colombia_relationship.zip)

### Describe the bug

- Despite three rounds of Colombo-American negotiation success, in the 'Colombia Agrees to Intelligence Sharing' event effects shows the 'No Success in Colombian Talks' event and the 'Minimal Success with Colombia' event for COL which is meant for USA.
- After selecting the 'Colombia Agrees to Intelligence Sharing' event, the 'Colombia and the United States Agree on the Fundamentals' news event suddenly triggers.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. National Front Colombian government won the La Violencia.
3. Either Borrero or Restrepo elects in post-Colombian government victory in La Violencia.
4. Re-establish a relationship between USA and Colombia.
5. All rounds success.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/750383ee-5165-4986-970a-9571dfc3a409)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1092e4f0-f057-477b-bc2d-0c109f2b6778)

**Comment by runelead00** [comment]
Fixed in Dev Build
