### ISSUE TITLE
USA - Some bugs about conclusions of Colombo-American Negotiation

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2641]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_america_colombia_relationship.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13306896/USA_america_colombia_relationship.zip)

### Describe the bug

- After 2 rounds succeed and 1 round fail, the 'Minimal Success with Colombia' event triggers instead of 'Partial Success with Colombia' event should be triggered. 
- 'Complete Success with Colombia' event gives 30 Political Power while the 'Partial Success with Colombia' event gives 100 Political Power. Complete Success with Colombia' event should be given 100 Political Power because of success all rounds and 'Partial Success with Colombia' event should be given 50 Political Power because of 1 fail round.
- After 2 rounds fails and 1 round succeed, the 'Partial Success with Colombia' event triggers instead of 'Minimal Success with Colombia' event should be triggered. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. National Front Colombian government won the La Violencia.
3. Either Borrero or Restrepo elects in post-Colombian government victory in La Violencia.
4. Re-establish a relationship between USA and Colombia.
5. Endings of Colombo-American Negotiation trigger.

### Expected behaviour

I don't know what causes this.

**Comment by runelead00** [comment]
Fixed in Dev Build
