### ISSUE TITLE
ITA - 'Servizio Informazioni Militare' national spirit has no GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2642]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13307105/USA_game.zip)

### Describe the GFX issue

The 'Servizio Informazioni Militare' national spirit has no GFX icon. 

### Steps to reproduce / Cause of the issue

1. Scorza won the power struggle against Ciano.
2. The Oil Crisis hits Scorza's Italy.

### Expected behaviour

Forgot to add GFX icon.  

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0b176f92-c7d5-4190-bbbd-d9ba8689dc03)

**Comment by runelead00** [comment]
Fixed in Dev Build
