### ISSUE TITLE
ILG - Algerian Union became Heavily Associated State instead of Colonial Government puppet status

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2643]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13307225/USA_game.zip)

### Describe the bug

After Italian Algeria won the Algeria War and became the Algerian Union, the Algerian Union became a Heavily Associated State instead of a Colonial Government puppet status because the current Algerian Union government is a Colonial Government. 

### Steps to reproduce / Cause of the issue

1. Algeria War triggers.
2. Italy won the Algeria War.
3. Forming the Algerian Union.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b517935e-487a-4f94-9a6e-f4bc452ac26c)

**Comment by runelead00** [comment]
Fixed in Dev Build
