### ISSUE TITLE
OMAN/YEMEN - Defeated factions are still in the 'Foreign Claims' and didn't remove them after Yemeni and Omani Civil Wars

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2644]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13307516/USA_game.zip)

### Describe the bug

After the Yemeni and Omani Civil Wars, the defeated factions are still in the 'Foreign Claims' and didn't remove them. 

### Steps to reproduce / Cause of the issue

1. Middle East conflicts trigger.
2. The Oil Crisis triggers.
3. Yemini and Omani civil wars ended.

### Expected behaviour

Forgot to remove them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aa0343d1-957b-4d7f-b219-33812fc24999)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5a3ec1a9-afab-462d-aa11-c92bcbfe9340)

**Comment by runelead00** [comment]
Removed Oman, not removing Yemen's cores until the Saudis are dealt with though
