### ISSUE TITLE
SAU - Saudi Arabia doesn't release monarchist Yemen to become subject of Saudis after defeated Socialist Yemen

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2645]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13307977/USA_play.zip)

### Describe the bug

After Saudi Arabia defeated the Yemeni Arab Democratic Republic, Saudi Arabia didn't release monarchist Yemen.

### Steps to reproduce / Cause of the issue

1. Middle East conflicts trigger.
2. The Oil Crisis started.
3. Yemeni Arab Democratic Republic won the Yemeni Civil War.
4. Yemeni Arab Democratic Republic declares war on Saudi Arabia.
5. Saudi Arabia defeats Yemeni Arab Democratic Republic.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a5c41c85-e48a-4c42-b98f-b6d450e4964c)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7782d8fd-5c03-426b-8039-065e916e0790)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6cefcb51-7493-47e0-b3a2-3ffac5ed6746)

**Comment by runelead00** [comment]
Fixed in Dev Build
