### ISSUE TITLE
GUL - League of Arab Sheikdoms doesn't change its economy type after become Saudi's subject

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2646]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13308073/USA_play.zip)

### Describe the bug

After Saudi Arabia defeated the Yemeni Arab Democratic Republic and the People's Republic of the Arab Gulf became the League of Arab Sheikdoms, the League of Arab Sheikdoms still has the Worker Directed economy type and didn't change it. 

### Steps to reproduce / Cause of the issue

1. Arab Gulf became the People's Republic of the Arab Gulf under socialist(syndicalist).
2. Middle East conflicts trigger.
3. The Oil Crisis started.
4. Yemeni Arab Democratic Republic won the Yemeni Civil War.
5. Yemeni Arab Democratic Republic declares war on Saudi Arabia.
6. Saudi Arabia defeats the Yemeni Arab Democratic Republic.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/954f199f-e378-437a-9e1f-04457329ed26)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/827c56d0-6d8f-4c01-8545-ab33c4f8be75)

**Comment by runelead00** [comment]
Fixed in Dev Build, isn't suppose to happen in the first place
