### ISSUE TITLE
GUL - League of Arab Sheikdoms doesn't join the Italian economic sphere after become Saudi's subject

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2647]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13308903/USA_play.zip)

### Describe the bug

After Saudi Arabia defeated the Yemeni Arab Democratic Republic and the People's Republic of the Arab Gulf became the League of Arab Sheikdoms, the League of Arab Sheikdoms doesn't join the Italian economic sphere while Saudi Arabia has.

### Steps to reproduce / Cause of the issue

1. Arab Gulf became the People's Republic of the Arab Gulf under socialist(syndicalist).
2. Middle East conflicts trigger.
3. The Oil Crisis started.
4. Yemeni Arab Democratic Republic won the Yemeni Civil War.
5. Yemeni Arab Democratic Republic declares war on Saudi Arabia.
6. Saudi Arabia defeats the Yemeni Arab Democratic Republic.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/59de679b-41f3-40c0-951f-6c0f155a8891)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ceb5fafb-6a4c-4377-b96a-7298c2dfcba6)

**Comment by runelead00** [comment]
Fixed in Dev Build, isn't suppose to happen in the first place
