### ISSUE TITLE
USA - Confuse options in 'The Carrot and The Stick' and 'Diplomacy, the Stepford Method' events

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2648]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13308658/USA_play.zip)

### List the loc issues below

- [x] 1. In 'The Carrot and The Stick' event, the first option says about carrot but when selecting the first option it ends up threatening or doing the stick method. The second option says about hitting with the stick but when selecting the second option it ends up playing nice or doing the carrot method.
So, the first option loc should be named "Hit them with the stick!" and the second option loc should be named "Feed them the carrot."
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/00dd148b-3d89-47d0-8dd4-a05866cfc75e)

- [x] 2. In the 'Diplomacy, the Stepford Method' event, the first option says about smiling and waving but when selecting the first option it ends up giving some weapons to Saudis which is presents. The second option says get presents ready but when selecting the second option it ends up disappointing the relationship with the Saudi King.
So, the first option loc should be named "Get the presents ready and don't bother with the gift wrap." and the second option loc should be named "Smile and wave, boys, smile and wave."
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3252d87e-7c15-498c-977d-e28199af5818)

**Comment by runelead00** [comment]
Fixed in Dev Build
