### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by DieuMivas** [TNODevs/TNO-Bug-Tracker#265]
**Questions**
Wrong name of the river in the description of Brussels (should be Senne and not Seine)

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**
In the description of Brussels, the name given for the river flowing there is the Seine even though it should be the Senne. The Seine is in Paris. The name are close but it's not the same. 

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

![1ACDB815-B877-4ED4-86EF-E12A349D7672](https://user-images.githubusercontent.com/94872152/142940422-077a1cf5-3532-4ed7-b7f3-a4794bb5c352.jpeg)

**Comment by runelead00** [comment]
Fixed on UB
