### ISSUE TITLE
IRI/IRL/IRA/IRC - Allow them to retake Baluchestan after Iranian Civil War in a few months

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2653]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest these Shite former Iranian Revolutionary Front members should be retaking Baluchestan by declaring war after the Iranian Civil War in a few months. 

### Justifications

Because Baluchestan is considered part of Iran despite Baluchestan has majority of Sunni Muslims and not to mention about collapse of the Iranian Revolutionary Front faction. So, that is why I suggest this.

**Comment by runelead00** [comment]
We are not making any content additions to the current Iranian Civil War
