### ISSUE TITLE
USA - 'The Ghost Squadron' national spirit's effect is not updated to BBA version

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2654]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13314196/USA_play.zip)

### Describe the bug

'The Ghost Squadron' national spirit's effect is not updated to the By Blood Alone version about increasing air volunteers wing limit.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Has the supporting Saudi Arabia focus tree.
3. Choose the 'An Unsavory bargain' focuses.
4. Complete the 'Send in the Spooks' focus.
5. Has 'The Ghost Squadron' national spirit. 

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d91eb3f5-be8b-4a76-a659-0c8094493102)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6bdadb75-0b7f-4e09-b4a4-ae336d0db620)

**Comment by runelead00** [comment]
Fixed in Dev Build
