### ISSUE TITLE
IRAN - Defeated factions are still in the 'Foreign Claims' and didn't remove them after Iranian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2655]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13314369/USA_play.zip)

### Describe the bug

After the Iranian Civil War, the defeated factions are still in the 'Foreign Claims' and didn't remove them.

### Steps to reproduce / Cause of the issue

1. Iranian Civil War triggers.
2. End of the Iranian Civil War.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/080b64c2-6c0c-45e4-839f-5608a27cde0e)

**Comment by runelead00** [comment]
Fixed in Dev Build
