### ISSUE TITLE
USA - Operation Successful or Fail event doesn't pop out after finishing the 'Organizing Troops in [supporting Russian faction]' operation

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2656]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_last_battle_for_russia.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13323563/USA_last_battle_for_russia.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13323566/Logs.zip)

### Describe the bug

When choosing to support either of the Russian factions during their Regional and Superregional wars and selecting 'Organizing Troops in [supporting Russian faction]' operation, the Operation Successful or Fail event doesn't pop up after finishing the 'Organizing Troops in [supporting Russian faction]' operation which means the agent doesn't return because the operation requires to have at least one agent available. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Choose to support either of the Russian factions during their Regional and Superregional wars.
3. Select 'Organizing Troops in [supporting Russian faction]' operation. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/72c0037f-7026-4c9b-a4a9-023b0f3c7e47)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5836d515-8910-4b2c-a2ed-66725ba6d6c0)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b395d883-d341-48f9-88c0-712e5f28b7a9)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f640dcfa-3bc7-4888-9054-e7bc54803bc6)

**Comment by runelead00** [comment]
Fixed in Dev Build, always successful which is why it gives that one event for affected tag at the end, will just add the agent back once it times out
