### ISSUE TITLE
SAU - Change the national spirit's name of 'American Advisor'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2657]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I suggest the 'American Advisor' national spirit should be renamed 'CIA Support' or something like this.

### Justifications

Because this national spirit gives political power gain and increases decryption. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1a5489b9-f840-4c40-a7aa-dfa0e76fbe90)

**Comment by Stormeagle449** [comment]
Accepted, renamed idea to "American Intelligence Support"
