### ISSUE TITLE
RK Kaukasien - Speer Doesn't release it as a puppet after invading

### ISSUE THREAD

**Issue by Reshuram** [TNODevs/TNO-Bug-Tracker#2659]
### Operating System

Windows 11

### HOI4 version

1.13.5.7

### TNO version

1.5.0b

### Do you have other mods in use?

Last Waltz of Europe Extended, Radio TNO, Second West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

When Speer Invaded RK Kaukasien as part of re-establishing german hegemony over Europe, Instead of creating a new RK in it's place like intended, Germany Annexed the nation and thus was unable to progress further in the focus Tree.

### Steps to reproduce / Cause of the issue

1. Play russian warlord
2. Have Speer win GCW
3. Wait for invasion of Kaukasien
4. Watch Germany annex it

### Expected behaviour

I expected RK kaukasien to be created as a puppet of germany

**Comment by runelead00** [comment]
Fixed in Dev Build
