### ISSUE TITLE
USA - Ghost Brigade within Infantry Division

### ISSUE THREAD

**Issue by Kurgis** [TNODevs/TNO-Bug-Tracker#266]
**Questions**

- Operating System: Win 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: Last Waltz
- Were you using Steam? Yes.
- Which expansions do you NOT have?
    Death or Dishonor
    Waking the Tiger
    Man the Guns
    La Resistance
    Battle for Bosporus

**Longer Description of Issue:**
Infantry divisions have a "ghost" brigade within their designer, this actually costs 5 exp to remove despite not requiring any equipment or manpower.

**Steps to Reproduce/Cause Issue:**

1. Open Division Designer

2. Select Infantry Division

**Screenshots:**
![image](https://user-images.githubusercontent.com/35203040/142950416-1fe2deb4-3c22-42b0-b331-0934ce38f71e.png)

**Comment by thashepherd** [comment]
This occurred in my USA game as well. Can confirm that it required 5 Army XP to remove the blank spot (or to move the motorized battalion underneath it into that spot)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
