### ISSUE TITLE
USA - There is no debate event in presidential election in 1972

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2661]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.12

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13320141/Logs.zip)

### Describe the bug

After choosing Gus Hall, Henry M. Jackson or Phyllis Schlafly as the new NPP primary and RDC choosing Goldwater for the second term during the 1972 presidential election, there is no debate event popped out.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Goldwater in 1968.
3. Presidential election 1972.
4. Choose NPP primary.

### Expected behaviour

I don't know what causes this.

**Comment by runelead00** [comment]
Fixed in Dev Build
