### ISSUE TITLE
Black League - Unlockable decision not showing up

### ISSUE THREAD

**Issue by Noovsky** [TNODevs/TNO-Bug-Tracker#2663]
### Operating System

Windows 11

### HOI4 version

1.13.5.7

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When selecting the focus "A quiet rage" on the "West Siberian Provisional Authority" stage, a decision is supposed to be unlocked to exert influence in the Southern Urals. The decision did not appear after the focus has been completed. 

### Steps to reproduce / Cause of the issue

Go to Black League as nation
Complete focuses
Defeat Batov's insurgency
Complete the rest of the focuses in that tree
Do the last focus in the focus tree (A quiet rage)

### Expected behaviour

The decision shows up on the decision board

### Screenshots

![image_2023-11-10_222912363](https://github.com/TNODevs/TNO-Bug-Tracker/assets/87027153/dd3ca950-d666-405b-950a-7bf52ee3ddc5)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/87027153/a36d8b31-4686-44b4-8cea-ca374204ee3c)

**Comment by runelead00** [comment]
Are the South Urals still independent?

**Comment by Noovsky** [comment]
If you are talking about Kazahstan, then yes, but Kazahstan had a
marxist-leninist coup which failed and national communists remained in
power.

**Comment by Noovsky** [comment]
[image: image.png]
decided to start a new game, and still no decision

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

сб, 11 нояб. 2023 г. в 03:26, runelead00 ***@***.***>:

**Comment by runelead00** [comment]
Given you can't even identify the South Urals on the map, likely already annexed by the time you finished off Batov

**Comment by runelead00** [comment]
Actual issue has been fixed in dev build
