### ISSUE TITLE
USA - Peacetime decisions doesn't triggered when all major proxy wars ended

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2664]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13323905/USA_play.zip)

### Describe the bug

When all major proxy wars that related to USA's home front effects have ended, the Peacetime decisions doesn't triggered. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Has the Home Front decisions.
3. All major proxy war conflicts ended.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/94c9f5f5-d227-4aec-8abd-b9b3dddbf9f3)

**Comment by runelead00** [comment]
Fixed in Dev Build
