### ISSUE TITLE
MCW - Bugs after Schorner's Russland succeed crushing slave rebels

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2667]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_Schorner_invades_rebel_slaves.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13324403/USA_Schorner_invades_rebel_slaves.zip)

### Describe the bug

When Schorner's Russland succeeds in crushing slave rebels and rejoins the Pakt, Schorner's Russland has no Zollverein national spirit, does not join the German economic sphere, and is not subject to Greater German Reich due to the 'Militarverwaltung' faction status.

### Steps to reproduce / Cause of the issue

1. Speer won the German Civil War.
2. Oil Crisis triggers.
3. Slave Revolt triggers.
4. Schorner's Russia attacks rebellion slaves.
5. Schorner successfully crushed the slave rebels. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d2085f7a-9e5b-4d3e-b21a-fff62f49ba12)

**Comment by runelead00** [comment]
Fixed in Dev Build
