### ISSUE TITLE
USA - [Supporting Russian faction] operations should not be available when Russia is reunited

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2668]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I suggest that the [Supporting Russian faction] operations should not be available in the intelligence tab for the Russia region when Russia is reunited under one banner.

### Justifications

Because when the Russian faction reunites Russia, the [Supporting Russian faction] operations still exist. So, that is why I suggest this. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4acb8bbc-7ada-47d0-ac3b-b6605fd3ed12)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c4eccf0a-ca43-4556-80bf-1b2ce81dc6d1)

**Comment by runelead00** [comment]
Fixed in Dev Build
