### ISSUE TITLE
USA - 'Conservatism Reigns' national spirit GFX icon uses Donkey instead of an Elephant

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2669]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_conservative_reigns.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13324501/USA_conservative_reigns.zip)

### Describe the GFX issue

The 'Conservatism Reigns' national spirit GFX icon uses a Donkey (a democratic party icon) instead of an Elephant (a republican party icon).

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Berry Goldwater as the new president in 1968.
3. Complete the 'Conservatism Reigns Supreme' national focus.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ea4023af-96bc-49f6-8fee-e0353f05a707)

**Comment by runelead00** [comment]
Fixed in Dev Build
