### ISSUE TITLE
USA - Enable CIA decision visibility during ongoing operations

### ISSUE THREAD

**Issue by Kurgis** [TNODevs/TNO-Bug-Tracker#267]
**Description of Suggestion:**
Allow CIA decisions to be visible during agent operations.

**Reasoning Behind Suggestion:**
It will allow the US player to continue to plan future operations without needing to memorize everything. I honestly thought this was a bug at first, operations already have a requirement check preventing you from selecting them if an operation is already ongoing, so why also turn them invisible?

**Additional Information:**
https://github.com/TNODevs/TNO-Bug-Tracker/issues/169

**Comment by Stormeagle449** [comment]
Already implemented, stale suggestion
