### ISSUE TITLE
USA - The URSA bill description says about opposition from Republicans instead of Democrats

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2671]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [x] 1. The URSA bill description in the decision says about opposition from Progressives and **Republicans** instead of **Democrats** because Goldwater's current party is Republican. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/27923704-f3cd-4a18-9b90-68e98c3afd40)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
