### ISSUE TITLE
USA - Pieces of evidence against AFL are not decrease after completing 'The AFL-CIO' focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2672]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_afl_cio.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13325243/USA_afl_cio.zip)

### Describe the bug

When at least have 3 pieces of evidence against the AFL and complete 'The AFL-CIO' focus, the pieces of evidence against AFL are not decreased while the 'The War Against the Unions' decisions that have required pieces of evidence are able to decrease pieces of evidence when completing them. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. At least have 3 pieces of evidence against the AFL.
3. Complete 'The AFL-CIO' focus.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a6b9dbb7-496e-4fe8-bd1f-365e6af91f43)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8df7b206-8cf4-48a9-856f-470f09661f68)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
