### ISSUE TITLE
USA - If discovered the consequences status doesn't appear after increasing consequences in 'The War Against the Unions' decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2673]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13325446/Logs.zip)
[USA_afl_cio.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13325447/USA_afl_cio.zip)

### Describe the bug

In 'The War Against the Unions' decision, if discovered the consequences status doesn't appear after increasing more consequences.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Goldwater in 1968 as the new president.
3. Doing against the Labor Union's focus tree.
4. Increase consequences. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/74d9baed-178b-4298-b50b-c4bdea37f5bb)

**Comment by runelead00** [comment]
Fixed in Dev Build
