### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by INCDI** [TNODevs/TNO-Bug-Tracker#2674]
### Operating System

Windows 11 Home

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13325678/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13325679/game.log)

### Describe the crash

Whenever I load the mod it crashes midway through loading before reaching the main menu.

### Steps to reproduce / Cause of the crash

1. Launch game
2. Wait
3. Crash

### Additional information

I am using the Nexus version of the mod. The base game and other mods load fine. From the error log it appears to be something with the GUI/Interface.

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/961, can only recommend possible fixes listed there
