### ISSUE TITLE
BHU - Bhutan doesn't get annexed by Azad Hind after Jan. 1, 1974

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2678]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_to_1974.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13326767/USA_to_1974.zip)

### Describe the bug

After reaching January 1st, 1974 in the game, Bhutan didn't get annexed by Azad Hind because according to Bhutan's 'Transitional Military Occupation' national spirit. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. Play through 1974s.
3. See Bhutan.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/920b796c-6e6d-4424-8757-5745b751f543)

**Comment by runelead00** [comment]
Tentative means it isn't guaranteed to happen on that date, also we aren't touching any part of old India skeleton until it's properly developed
