### ISSUE TITLE
USA - Rafuko and Kuwako are not renamed after the Treaty Ports succeed

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2679]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_treaty_ports_success.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13326795/USA_treaty_ports_success.zip)

### Describe the bug

When the Treaty Port success and two Japanese concessions in USA's California coasts returned to their rightful owner in exchange for Oil, Rafuko and Kuwako are not renamed to American one. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. The Honolulu Accords triggers.
3. The Treaty Ports' success.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aa2b6628-fa3b-4a46-8cd6-bbf2ec700c6d)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4c7567f3-a799-4af9-8577-1504693470e7)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c7278b43-8aa7-4634-92e3-466b320e1938)

**Comment by runelead00** [comment]
Fixed in Dev Build
