### ISSUE TITLE
Suggestions about Game Balance and Value

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2680]
### HOI4 version

1.13.3

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

1. America's Civil Rights Act was supposed to reduce poverty
2. For industrial regulation, higher regulation should improve industrial equipment, and higher regulation can lead to higher production caps
3. Tax cuts can increase the poverty rate by 0.01 base change
4. remove Canada's Nixon shock idea on gdp growth

### Justifications

1. America has a lot of stability from begin of game, in other words, stability rarely falls below 100%, in this case, the Civil Rights Act's effect did more harm than good
2. Regulation is too weak, productivity was sacrificed in exchange for population growth that was negligible and had little effect over the 10 years
3. Tax cuts is too useless, It simply reduces revenue to create a deficit, which players can do by adding a few more armys, also "tax cuts" help to eradicate poverty to some extent
4. Canada's growth rate is not high, Nixon shock will make it decrease forever

**Comment by MrStraws114514** [comment]
> ### HOI4 version
> 1.13.3
> 
> ### TNO version
> 1.5.0b
> 
> ### Which major expansions do you NOT have?
> I have all
> 
> ### Describe your suggestion
> 1. America's Civil Rights Act is supposed to reduce poverty
> 2. For industrial regulation, higher regulation should improve industrial equipment and lead to higher production ceiling
> 3. Tax cuts can increase the poverty rate by 0.01 base change
> 4. Increase Canada's basic gdp growth, at least don't let gdp decrease forever
> 5. In peace_action, when a country got destroyed and annexed, system will clear the debt of it
> 
> ### Justifications
> 1. America has a lot of stability from begin of game, in other words, stability rarely falls below 100%, in this case, the Civil Rights Act's effect did more harm than good
> 2. Regulation is too weak, productivity was sacrificed in exchange for population growth that was negligible and had little effect over the 10 years
> 3. Tax cuts is too useless, It simply reduces revenue to create a deficit, and gives a small multiplier, which players can do by adding a few more armys, also "tax cuts" help to eradicate poverty to some extent
> 4. Canada's basic growth rate is not high, and Nixon shock will make it decrease forever in game
> 5. when a country collapses, some dead tags will revive, such as 2nd Colombia war and 2nd South africa war, But these resurrected tags still inherited debts they had before they died, and this will nuke lands they control
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

**Comment by MrStraws114514** [comment]
5. In peace_action, when a country got destroyed and annexed, system will clear the debt of it
reason: when a country collapses, some dead tags will revive, such as 2nd Colombia war and 2nd South africa war, But these resurrected tags still inherited debts they had before they died, and this will nuke lands they control

**Comment by runelead00** [comment]
1. I have no idea what you are trying to say here, your suggestion and justification are unrelated
2. We are not adding any further effects to current set of laws
3. They already actively increase GDP growth when taken, also tax cuts do not inherently cause less poverty
4. No, we are not changing Canada until Canada content releases as repeatedly stated previously
5. Debt clearing is handled on a situational basis, countries do not suddenly not to pay creditors because they lost a war
