### ISSUE TITLE
YEM/OMI/EGQ/SNI - About the 'Pro-Saudi Volunteers' national spirit and its effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2681]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I suggest that the 'Pro-Saudi Volunteers' national spirit's effects on Yemen, Imamate of Oman, Muslim Brotherhood and Islamic Republic of Iraq should be changed to 'Max volunteers to Saudi Arabia +5' instead of vanilla effects.

### Justifications

Yemen, Imamate of Oman, Muslim Brotherhood and Islamic Republic of Iraq's 'Pro-Saudi Volunteers' national spirit's effects have vanilla effects because the sending volunteers is unlocked in TNO unless the national spirit's effect has sent volunteers on target specific tags. 

And also, I don't know what 'Pro-Saudi Volunteers' national spirit is for. Probably, this national spirit's purpose is to send volunteers to Saudi Arabia if Saudi Arabia is attacked by Scorza's Italy or Yemeni Arab Democratic Republic?

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fffe6319-3857-4437-8962-7eecec999d12)

**Comment by runelead00** [comment]
Removed in Dev Build
