### ISSUE TITLE
USA - Eric Williams is not in charge of West Indies Federation after selecting either of the options from 'Return to the Port' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2682]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_jamaica_blackpower_leaves.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13327510/USA_jamaica_blackpower_leaves.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13327599/Logs.zip)

### Describe the bug

After selecting either of the options from the 'Return to the Port' event and running the game through many months, Eric Williams is not in charge of the West Indies Federation and WIF has not changed its national spirits and its tag name. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. West Indies Crisis triggers.
3. Jamaican leaves and becomes independent.
4. Black Power Revolution succeeded in Trinidad and Tobago.
5. Select either of the options from the 'Return to the Port' event.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/54220d87-95dd-45a8-bfd2-8ba017b08d05)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/09627b5a-ab7b-42fd-8c88-b636c29968b0)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/99970f5d-3324-44ea-ad38-82e64cdbf3cf)

**Comment by runelead00** [comment]
Working as Designed, it take 300 days before the actual reforms are implemented, also nothing in the world event suggests Eric Williams has become leader of the WIF at time of event
