### ISSUE TITLE
USA - 'American Target' national spirit gives target to wrong tag and it didn't remove once the ME conflicts ended

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2683]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13327610/Logs.zip)

### Describe the bug

The United Arab Kingdom and the People's Republic of the Arab Gulf have the 'American Target' national spirit despite PAL tag is not communist/socialist which is pan-Arabist and GUL tag is non-pan-Arabist socialist it does not align with the Pan-Arabist movement. 

And the 'American Target' national spirit for other tags that have it wasn't removed when the Middle East conflicts ended. 

### Steps to reproduce / Cause of the issue

1. Italy remains independent.
2. PAL tag is not communist/socialist.
3. GUL tag is a non-pan Arab socialist.
4. Middle East conflict triggers.
5. The Oil Crisis triggers.
6. USA completes 'Securing Our Interest' focus trees.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6a3b3d1c-da74-40ba-aa85-3ee1de49e391)

**Comment by runelead00** [comment]
Fixed in Dev Build
