### ISSUE TITLE
USA - 1971 Icelandic General Elections decision are not disappear after the all Medica Cycles are done

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2685]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13327749/Logs.zip)
[USA_pro-ofn_iceland_stays.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13327751/USA_pro-ofn_iceland_stays.zip)

### Describe the bug

After all five Media Cycle decision timers were done, the 1971 Icelandic General Elections decision did not disappear. 

### Steps to reproduce / Cause of the issue

1. Iceland Crisis triggers.
2. Icelandic 1971 General Election triggers.
3. All five Media Cycle decision timers are done.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/362b9ed3-e067-4571-abc9-920e08926fe7)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5d60fe9e-3c7c-4687-8d2f-bd887cb29236)

**Comment by runelead00** [comment]
Fixed in Dev Build
