### ISSUE TITLE
All tags - Allocated is not decrease despite has the military advisers when start of beginning of the game

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2686]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing the game at the start of beginning as with any feature tag, there is no allocated decrease appeared in CP effects despite the military advisers being in. But, after reloading the save game, the allocated decrease is somehow appears in CP effects. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tags that have military advisers.
2. See Command Power's effect gain.
3. Reload the save game.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/90abfa7e-8f07-46d0-8834-a1f58aa3d04a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7ebfb3c3-2db7-4eae-9520-b6a82dc75fc1)

**Comment by runelead00** [comment]
Paradox Issue, can't fix
