### ISSUE TITLE
All tags - A slight issue in the 'Rojas Pinilla Deposes Colombian Government' news event description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2688]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [x] 1. At the end of the second paragraph in the 'Rojas Pinilla Deposes Colombian Government' news event description, it says that "autocratic third position path of national development inspired by Casto's Cuba", it should be "inspired by Mexico" because Cuba has able to change its ruling party.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5475cea2-ad34-431d-865b-09b61cd28df4)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
