### ISSUE TITLE
GER - 'A Retroactive Understanding' event uses Erhard Milch's picture instead of Emil Maurice

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2690]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The 'A Retroactive Understanding' event uses Erhard Milch's picture instead of Emil Maurice's picture because the event talks about Maurice's situation in Madagascar. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich.
2. Second Malagasy Uprising triggers.
3. 'A Retroactive Understanding' event triggers.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9b6ec49d-aaed-4ac1-9865-754ee3ab0d00)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
