### ISSUE TITLE
All countries

### ISSUE THREAD

**Issue by gamerweeb623** [TNODevs/TNO-Bug-Tracker#2692]
### Operating System

Windows 11

### HOI4 version

1.13.2

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

 Loading any save horribly corrupts the map and game, leaving many countries with bugged focus trees, missing names and missing leaders.

### Steps to reproduce / Cause of the issue

Load any savegame.

### Expected behaviour

I expected my save to load as normal.

### Additional information

This seems to happen consistently.

**Comment by Stormeagle449** [comment]
We need your save file, the game log, and the error log to solve this issue otherwise we can't address it properly.

**Comment by gamerweeb623** [comment]
It actually seems like the issue has been resolved since my bug report. Thank you!
