### ISSUE TITLE
CAL - Add few fighters and CAS planes when the PPI landing starts

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2693]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the Caribbean Legion should have a few fighters and CAS planes when the PPI landing starts.

### Justifications

Because during the PPI, the Germans supported the Dominican Republic by giving them Anti-Air Equipment and Anti-Air Weapons. But when the PPI landing started, the Caribbean Legion had no combat planes.  So, that is why I suggest this that the Dominican Republic should use its Anti-Air weapons against the Caribbean Legion's combat planes. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3e3d3467-88eb-4548-b86a-83a7e99b9fe1)

**Comment by runelead00** [comment]
The Caribbean Legion is a small force that has to rely on the USA for air and navy and Cuba for armor support, they would not have an airforce. the anti-air is repeatedly mentioned in-game to be against the US in events and decisions and actively affects the spirits the DR gets
