### ISSUE TITLE
DOM - AI doesn't move its divisions to create a front line against Caribbean Legion

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2694]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13343992/Logs.zip)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13343995/autosave.zip)

### Describe the bug

When the Caribbean Legion landed on Puerto Plata during the PPI, AI Dominican Republic is not able to create a front line towards the Caribbean Legion and attacked them but instead focused on the Area Defense plan. This could be Trujillo's Dominican Republic's inevitable defeat. 

### Steps to reproduce / Cause of the issue

1. Puerto Plata Invasion starts.
2. Caribbean Legion landing on Puerto Plata.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2972ed65-993f-4b4f-8ae3-cff98f134549)

**Comment by runelead00** [comment]
Fixed in Dev Build
