### ISSUE TITLE
GER - 'Run Localized Terror Operations' decision still has no effects for targeted states

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2695]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_smu.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13343892/GER_smu.zip)

### Describe the bug

In the 'Run Localized Terror Operations' decision, I see the effect for targeted states inside on parenthesis have no effects for. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich.
2. Has Second Malagasy Uprising proxy war.
3. Proceed to stage 2 of SMU.
4. See 'Run Localized Terror Operations' decision effects.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2ca38e22-078d-4d5a-aa52-735393b361fb)

**Comment by runelead00** [comment]
Fixed in dev build
