### ISSUE TITLE
Various GDP Bugs in new update

### ISSUE THREAD

**Issue by D4ntheM4n** [TNODevs/TNO-Bug-Tracker#2698]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

1.5.0.b The Ruin

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Small countries like Vorkuta or Kanem get an insane GDP increase for no reason. 

### Steps to reproduce / Cause of the issue

Play the game on any difficulty

### Expected behaviour

Fix the GDP bug

### Screenshots

![Screenshot (35)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107819293/9c8cf73d-58e8-467b-810c-497c5eed1a31)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
