### ISSUE TITLE
GER - 'Undermine Rebel Control' decision not appear until Moramanga is taken by the German garrisons

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2699]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13344908/GER_play.zip)

### Describe the bug

When stage 3 happens in the second Malagasy uprising, the 'Undermine Rebel Control' decision does not appear but when the Moramanga is taken by the German garrisons, the 'Undermine Rebel Control' decision somehow appears. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich.
2. Second Malagasy Uprising triggers.
3. Proceed to stage 3 of SMU.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/39d17562-9913-434a-b0f7-ff4223bfd53d)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aaba7336-b3c0-42b7-a763-3931a36bdb7a)

**Comment by runelead00** [comment]
Fixed in Dev Build
