### ISSUE TITLE
USA - Populace demand negative debt to gdp

### ISSUE THREAD

**Issue by Pandox231** [TNODevs/TNO-Bug-Tracker#270]
**Questions**

- Operating System: **Windows 10 build 19042.1348**
- HOI4 Version: **1.10.8**
- TNO Version: **1.2.0c**
- Any other mods in use: **Last Waltz of Europe (extended), State Transfer Tool, Radio TNO, and TNO Loading Screens Redone**
- Were you using Steam? **Yes**
- Which expansions do you NOT have? **Battle for the Bosporus**

**Longer Description of Issue:**
**When playing as Bennett for the United States, the people's expectation of debt to GDP and total GDP between 1962-1964 were easily met by our growing economy. However when it came time for the people to make their second "demands" for GDP growth and debt ratio, they demanded a debt to GDP ratio of less than 0, an impossibility. The total GDP request was unaffected by the bug however. This bug was resolved for the 1966-1968 demands however due to the lost support I lost the 1968 election to Harrington and the run was ended.**
**Steps to Reproduce/Cause Issue:**

1. **I have not played multiple US TNO games with TT so far, so my only suggestion is keep running as R-D also electing Bennett, perform higher than expected for the 1962-1964 requests by the public, and that's how I got the bug.**

**Screenshots:**
![20211121160553_1](https://user-images.githubusercontent.com/94878927/142962960-4c3fc47e-4a51-4dd0-b815-356ed28a45da.jpg)
![20211121162418_1](https://user-images.githubusercontent.com/94878927/142963008-4aaad4ec-d451-4868-a486-f10a665ce39e.jpg)

**Comment by fedacking** [comment]
Fixed in Dev Build. The tooltip has been updated to reflect that it's no more debt than that percentage. Thank you for reporting.
