### ISSUE TITLE
GER - Slight confuse description in the 'Undermine Rebel Control' decision effect

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2700]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. The description in the 'Undermine Rebel Control' decision effect after the "state modifiers" is quite confusing. So, it should be "to be worse fit for stationing our enemy troops" or something like that after the "state modifiers" loc. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1d78da31-00b5-4fe3-aca1-da8d92955409)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9ed7306b-7bb9-4f43-b2ee-4af108b52b98)

**Comment by runelead00** [comment]
Fixed in Dev Build
