### ISSUE TITLE
DOM - Three generals have anti-Fascist traits and a guerilla veteran trait in fascist Dominican Republic

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2701]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I switch to the Dominican Republic tag, there are three generals who have anti-fascist traits and a general has a guerilla veteran trait despite the Dominican Republic is still a fascist. They shouldn't be available until the Dominican Republic is no longer controlled by Trujillo and Balaguer. 

### Steps to reproduce / Cause of the issue

1. Switch to the Dominican Republic tag.
2. See the Dominican generals. 

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bb97bd81-75e7-43c7-b581-a0786ab557b6)

**Comment by runelead00** [comment]
Fixed in Dev Build, were suppose to be transferred to CAL at PPI start
