### ISSUE TITLE
GER - Slight description issue in the 'REPORT: DOMINICAN SITUATION' events

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2704]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In all of the 'REPORT: DOMINICAN SITUATION' events' description, there is the word 'SANTO DOMINGO' which is the capital of Dominican Republic but in the game, the capital of Dominican Republic under Trujillo regime is Ciudad Trujillo. It should be "CIUDAD TRUJILLO as the capital of Dominican Republic in the description events of 'REPORT: DOMINICAN SITUATION'. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/94476b96-b33e-4ea4-a948-245e716defcf)

**Comment by runelead00** [comment]
Fixed in Dev Build
