### ISSUE TITLE
All tags - There is the word "Santo Domingo" instead of "Ciudad Trujillo" in reaction to 'Trujillo Defeat the Caribbean Legion' news event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2706]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In the reaction to 'Trujillo Defeat the Caribbean Legion' news event, there is the word "Santo Domingo" instead of "Ciudad Trujillo" because the current capital of the Dominican Republic under Trujillo regime is 'Ciudad Trujillo'. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a8b0fc9f-6b65-4054-abe9-843d99b71135)

**Comment by runelead00** [comment]
#1761

**Comment by Ikidikid** [comment]
Oh, I didn't expect there was a report that was in before this. Thanks for letting me know.
