### ISSUE TITLE
GER - Some issues on description of 'A Call to the Reichskommissar' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2707]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In the 'A Call to the Reichskommissar' event description, the "Koch" word should be replaced with "Leibbrandt" due to Koch has an injury, "and Madagaskar" words should be removed due to Madagaskar is not Reichskommissariat at the game start, "Veesenmayer" word should be replaced with "England" due to old content of Veesenmayer and "garrison" should add "s" like "garrisons". 
I don't know why this event's description didn't include Niederlande and Norwegen despite they are Reichskommissariats. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/63886d8f-4651-42a0-b47a-3ca04efb6e52)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dc1f0062-1c86-461b-bf01-7cc130ad6a59)

**Comment by runelead00** [comment]
Koch fixed in dev build
Madagaskar is unchanged, there is a large German prescence which is massive part of the 2MU
Veesenmayer is unchanged as it isnt old content, its the current content
