### ISSUE TITLE
MAD - Last paragraph in city description of Antananarivo didn't change when the German garrisons won the war

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2708]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Militärverwaltung Madagaskar won the second Malagasy Uprising, the last paragraph in the city description of Antananarivo didn't change to something that Germans retook control over Madagascar. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich.
2. Second Malagasy Uprising triggers.
3. German garrisons won the SMU.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ab83173b-0a9b-45ac-a421-05f94674aea0)

**Comment by runelead00** [comment]
Fixed in Dev Build
