### ISSUE TITLE
MAD - Second Malagasy Uprising state modifiers are not removed after German garrisons won the war

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2709]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13348000/Logs.zip)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13348159/autosave.zip)

### Describe the bug

When the Militärverwaltung Madagaskar won the Second Malagasy Uprising, all Madagascar states still have the Second Malagasy Uprising state modifiers and didn't remove them.

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich.
2. Second Malagasy Uprising triggers.
3. German garrisons won the SMU.

### Expected behaviour

Forgot to remove them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e1ef55c3-2ec5-45b6-b2ab-09a7bd422cf5)

**Comment by runelead00** [comment]
Fixed in Dev Build
