### ISSUE TITLE
IRK- Wrong Superregional Army Flag

### ISSUE THREAD

**Issue by Dreamfoot** [TNODevs/TNO-Bug-Tracker#271]
Irkutsk switches to warlord flag during superregional unification

![Uploading Screenshot (23).png…]()

**Comment by Dreamfoot** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/54084244/142981281-b4f63828-c525-4ca1-891c-fda332db24dc.png)

**Comment by runelead00** [comment]
Fixed on UB
