### ISSUE TITLE
GER - Change the event's picture for 'Heydrich Rises Up!', 'Speerians Rise Up!', 'Goring Rises Up!' and 'Bormann Breaks Away!' 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2710]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the event's picture for 'Heydrich Rises Up!', 'Speerians Rise Up!', 'Goring Rises Up!' and 'Bormann Breaks Away!' should be changed to something German mobilization picture.

### Justifications

These events are using pictures of the German soldiers checking on the people with their hands up. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b16f1cdc-e21c-42c6-a8ac-1b94b734b624)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c9d27b2b-17e3-41b8-855e-716adc441b3f)

**Comment by runelead00** [comment]
Changed in Dev Build
