### ISSUE TITLE
BGR - Change the 'Rally the Old Guard' decision effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2712]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I suggest that the 'Rally the Old Guard' decision effects should change like removing 'Change national Socialism popularity: +2.50%', and Army and Air Experiences should increase +25. 

### Justifications

because when the German Civil War started, Bormann's Germany has a 100% National Socialism current party. So, the 'Change national Socialism popularity: +2.50%' should be removed from the 'Rally the Old Guard' decision effects and Army and Air Experiences should increase +25.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b5410080-0c57-4335-aa85-8e8802e1fa5c)

### Additional information

Save game: [GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13349512/GER_play.zip)

**Comment by Stormeagle449** [comment]
We're not making any changes to GCW code for future patches.
