### ISSUE TITLE
BGR/SGR/HGR/GGR - Change the event picture for 'The Gotenland Emergency' and 'The Kriegsmarine Leaves for Crimea'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2714]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the event's picture for 'The Gotenland Emergency' and 'The Kriegsmarine Leaves for Crimea' should be changed to something Crimea is shown on the map including Taurien for 'The Gotenland Emergency' and a German navy for 'The Kriegsmarine Leaves for Crimea'.

### Justifications

'The Gotenland Emergency' and 'The Kriegsmarine Leaves for Crimea' events picture use the German soldiers checking on the people with their hands up. So, that is why I suggest this to something different from this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/acc55365-ffa6-4e54-bf8c-6036bdf978d5)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e1333e0b-96ac-46e1-a91d-b98e2e733e14)

**Comment by runelead00** [comment]
Changed in Dev Build
