### ISSUE TITLE
MST - 'For a Free Osland' national focus has no GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2715]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[BGR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13357907/BGR.zip)

### Describe the GFX issue

The 'For a Free Osland' national focus has no GFX icon added. 

### Steps to reproduce / Cause of the issue

1. The German Civil War starts.
2. The Ostland Civil War starts.

### Expected behaviour

Forgot to add GFX icon.  

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/77d9907c-4182-4b7d-8eed-55e25a3982bb)

**Comment by runelead00** [comment]
Fixed in Dev Build
