### ISSUE TITLE
GER - Civilian and Military factories are increased compared PU allocated to after the German Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2717]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[BGR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13359267/BGR.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13359268/Logs.zip)

### Describe the bug

When Bormann won the German Civil War, Civilian and Military factories somehow increased more than the Production Units given. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich.
2. Choose Bormann as a successor.
3. German Civil War triggers.
4. Bormann won the German Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f3525e4a-be09-44e3-b08c-6190a106d226)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/724d081e-e1c0-41ab-aff1-1be6af68a2db)

**Comment by runelead00** [comment]
Likely fixed in Dev Build
