### ISSUE TITLE
GER - Greater German Reich is not in the Top 10 Economies and the German contenders are still there after the GCW until runs the game

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2718]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13359360/Logs.zip)
[BGR.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13359362/BGR.zip)

### Describe the bug

After Speidel surrendered to either Speer or Bormann after either of them defeated the remaining contenders and ended the German Civil War, the Greater German Reich did not appear in the Top 10 Economies and the German contenders still appeared. But when running the game, the Greater German Reich now appeared in the Top 10 Economies lists. 

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich.
2. German Civil War triggers.
3. Either Bormann or Speer won the German Civil War.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8f8dc9fb-7f21-496d-9053-486bf077168d)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a125ee22-9e1e-44f6-a949-0f235c85b762)

**Comment by runelead00** [comment]
Fixed in Dev Build
