### ISSUE TITLE
IRK-9th 5 Year Plan

### ISSUE THREAD

**Issue by Dreamfoot** [TNODevs/TNO-Bug-Tracker#272]
Final decision requires that you take all other ones, even though Japanese cooperation is mutually exclusive with the OFN one so it become impossible to finish

![Screenshot (24)](https://user-images.githubusercontent.com/54084244/142981559-aa545a70-3683-4c79-9ea2-c8d43bb7290e.png)

**Comment by runelead00** [comment]
Fixed on UB
