### ISSUE TITLE
GER - 'The Takeover' event has generic picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2720]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13360759/Logs.zip)

### Describe the GFX issue

'The Takeover' event uses a generic picture instead of a Bohemian administrative city picture or something like that.

### Steps to reproduce / Cause of the issue

1. The German Civil War started.
2. Wehrkreis XIX remains neutral.
3. Bormann won the Civil War.
4. Germans retake Wehrkreis XIX.
5. Choose either keep or remove von Krosigk.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d9c66821-d82f-4298-ab9a-4d3ea637bb7a)

**Comment by runelead00** [comment]
Fixed in Dev Build
