### ISSUE TITLE
HOL - National Socialism party popularity didn't increase after the Germans reconquered Netherlands

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2721]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13360953/Logs.zip)

### Describe the bug

After the Germans reconquered the Netherlands, Reichskommissariat Niederlande's National Socialism party popularity didn't increase.  

### Steps to reproduce / Cause of the issue

1. German Civil War triggers.
2. Cornelis van Geelkerken takes over the Netherlands.
3. Bormann won the German Civil War.
4. Bormann sent ultimatum to van Geelkerken.
5. van Geelkerken refused.
6. Germans invade Dietsland and Netherlands becomes Reichskommissariat again.

### Expected behaviour

Forgot to add increased current party popularity after reconquered.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/61448abe-9f66-47c8-8dee-520aa2d1bf9d)

**Comment by runelead00** [comment]
Working as Designed, literally wait 4 more days
