### ISSUE TITLE
SLO - Some Ján Golian's national spirits didn't removed after the German reconquered Slovakia

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2722]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13361321/Logs.zip)

### Describe the bug

After the Germans reconquered Slovakia and deposed Ján Golian, 'The Slovak Voice' and 'A Free Slovakia?' national spirits didn't removed. 

### Steps to reproduce / Cause of the issue

1. German Civil War triggers.
2. Ján Golian overthrew the pro-German government in Slovakia.
3. Either Bormann or Speer won the GCW.
4. Ján Golian refused to submit.
5. Germans invaded Slovakia and reinstalled the pro-German government in Slovakia.

### Expected behaviour

Forgot to remove them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/cf7d0dfd-d332-405c-bdd1-e84e300c061b)

**Comment by runelead00** [comment]
Removed all 3 of Golian's spirits
