### ISSUE TITLE
GER - Change the event picture for 'Unterwanderung'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2723]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I suggest that the 'Unterwanderung' event picture should be changed to Generalgouvernement (General Government) map picture or something like that.

### Justifications

'Unterwanderung' event picture uses the German soldiers checking on the people with their hands up. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e718ec12-fc7c-4077-8420-6db1b5040089)

**Comment by runelead00** [comment]
Fixed in Dev Build
