### ISSUE TITLE
POL - Generalgouvernement's Interimregierung uses the Reichstag building instead Sejm building

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2726]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13363242/GER_play.zip)

### Describe the GFX issue

After Bormann successfully defeated the Polish Republic and reestablished of Generalgouvernement in Poland, Generalgouvernement's Interimregierung uses the Reichstag building portrait instead of the Sejm building portrait. 

### Steps to reproduce / Cause of the issue

1. Bormann won the German Civil War.
2. The Germans re-invades Poland.
3. Greater German Reich defeated independent Poland.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a34c6cf8-5c58-4327-af03-7a01a40f20b8)

**Comment by runelead00** [comment]
We're not wasting team resources for a minor temp leader portrait for content that will be cut when Poland is released
