### ISSUE TITLE
GER/GGN - Eduard Wagner has no trait effects and bio description after choosing a new director for Generalgouvernement

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2728]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13364196/GER_play.zip)

### Describe the bug

After Eduard Wagner as the new Reichskommissar for Generalgouvernement, Eduard Wagner had no trait effects and bio description compared to other candidates. 

### Steps to reproduce / Cause of the issue

1. Bormann won the German Civil War.
2. The Germans re-invades Poland.
3. Greater German Reich defeated independent Poland.
4. Generalgouvernement reestablished.
5. Choose Eduard Wagner as the new Reichskommissar for Generalgouvernement.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c1442b72-421e-49bf-8546-d5e3854b3eea)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/627169c3-6fb4-4c1d-9fc8-273f4a51aa75)

**Comment by runelead00** [comment]
Fixed in Dev Build
