### ISSUE TITLE
OST - Franz Walter Stahlecker is replaced by Friedrich Karl Vialon and removed all OCW national spirits after at least one contender is defeated

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2729]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13364319/GER_play.zip)

### Describe the bug

When the Germans intervened in the Ostland Civil War to support Stahlecker and at least one Ostland contender was defeated, Franz Walter Stahlecker was replaced by Friedrich Karl Vialon and removed all OCW national spirits despite the civil war is still ongoing. 

Franz Walter Stahlecker shouldn't be replaced by Friedrich Karl Vialon if the Germans intervene in the OCW and Stahlecker's Ostland exists, and if Stahlecker's Ostland wins the OCW due to the Germans intervene, Stahlecker should stay as Reichskommissariat Ostland leader instead of replacing him. 

If Stahlecker is defeated in the Ostland Civil War before the Germans intervene, Friedrich Karl Vialon should be in charge of Reichskommissariat Ostland. 

### Steps to reproduce / Cause of the issue

1. German Civil War starts.
2. Ostland Civil War starts.
3. Bormann won the German Civil War.
4. Stahlecker's Ostland hold.
5. The Germans intervened in Ostland Civil War to support Stahlecker.
6. At least Ostland contender is defeated. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f2a9b06f-5c10-4df1-a912-cbc99ebf8f77)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c89ebcff-b2b4-4062-87af-2ccf494625f5)

**Comment by runelead00** [comment]
Fixed in Dev Build
