### ISSUE TITLE
GERMAN and US - Crash when winning madagascar war

### ISSUE THREAD

**Issue by baraghiffari** [TNODevs/TNO-Bug-Tracker#273]
**Questions**

- HOI4 Version: Collie 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: TNO Nuclear wargame rule (didn't turn it on), Precise buff - cheat ideas, TNO Toolpakt, tno cheat
- Were you using Steam? Yes
- Which expansions do you NOT have? Armor pack, Radio pack, Allies speech pack, Planes pack, Music pack

The game crashes when I won the war in Madagascar as US or Germany, not sure about Japan since I don't play it. I don't think it's other mod problem since when i interfere Indochina conflict as US the crash doesn't happen

**Steps to Reproduce/Cause Issue:**

1. Play as Germany or US

2. Win the Madagascar conflict

Error logs :
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7586342/error.log)

**Comment by nielskoster2000** [comment]
I also suffered from this. 

- HOI4 Version: Collie 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: TNO Nuclear wargame rule, Toolpakt: Toolpack for TNO, Better Air Wing Deployment and the Radio TNO mod
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back 

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7803498/error.log)

**Comment by runelead00** [comment]
Duplicate of #143
