### ISSUE TITLE
GER - No pictures for inevitable war with communist Serbia and its outcome events

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2730]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

There are no images or pictures of the 'inevitable war with communist Serbia and communist Serbia defeated' events.

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Either Bormann or Speer won the GCW
3. Serbian National Liberation Front won the Civil War.
4. Serbian National Liberation Front became the People's Republic of Serbia.
5. Serbia remains communist. 

### Expected behaviour

Forgot to add picture, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/cdd9a21e-a634-431c-a663-5ceb8d7f52f4)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e07ff13c-02cf-4e95-b68e-fae82360782b)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dcf50d89-f28a-411d-9315-6baf948b9aca)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
