### ISSUE TITLE
SER - Independent State of Serbia has no German economic sphere after the Germans reconquered Serbia

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2731]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13365440/Logs.zip)

### Describe the bug

After the Germans reconquered Serbia from the communists, the Independent State of Serbia was not in the German economic sphere. 

### Steps to reproduce / Cause of the issue

1. Play as Germany
2. Either Bormann or Speer won the German Civil War.
3. Serbian National Liberation Front won the Civil War.
4. Serbia remains communist.
5. German reinvades Serbia.
6. Serbia becomes a collaborator again.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0ca40fad-ca43-4321-bbc0-1dfdf2089b7e)

**Comment by runelead00** [comment]
Fixed in Dev Build
