### ISSUE TITLE
GER - Slight suggestion changes effect for The Political Rodeo'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2733]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that in 'The Political Rodeo' national spirit's effects, the 'Bureaucracy' should give Political Power Gain instead of Party Popularity Stability and the 'People' should give Party Popularity Stability instead of Political Power Gain.

### Justifications

Well, because it is confusing to me that the 'Bureaucracy' gives Party Popularity Stability that 'Bureaucracy' is about government decisions and also political and 'People' gives Political Power Gain that 'People' is about the society and status of well being for the people which is stability, I think. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b35f391e-a7e3-4ae3-98dd-675df230f31e)

**Comment by runelead00** [comment]
Rejected, not making any significant change to before Bormann facelift
