### ISSUE TITLE
TOM - Can't research nuclear reactors at superregional

### ISSUE THREAD

**Issue by averagetomskenjoyer** [TNODevs/TNO-Bug-Tracker#2734]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

At superregional level, upon completing the "Into the Atomic Age" focus as Tomsk, I expected that I can research nuclear reactors, which gets enabled for every russian unifier, but as Tomsk, it doesn't get enabled.

### Steps to reproduce / Cause of the issue

1. Play as Tomsk
2. Reach superregional
3. Complete the aformentioned focus

### Expected behaviour

Tomsk should be able to research nuclear reactors at superregional

### Screenshots

![20231115155425_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148972379/c5ebaa6f-0af8-4162-99f7-2683b75b2fb0)
![20231115155448_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148972379/2863124f-0fa3-463f-aa5b-002bd7ecbabd)

**Comment by runelead00** [comment]
Fixed in Dev Build
