### ISSUE TITLE
GER - There is a tag word "SAF" in 'The Rodent' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2735]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In 'The Rodent' event, there is a tag word "SAF". It should be placed in the current South Africa name like Republic of South Africa or Union of South Africa.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/423caf48-c3f8-4c69-acf2-f990f71a9e3f)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8d7d827b-6b75-43e7-b595-43e6cc2f2685)

**Comment by runelead00** [comment]
Fixed in Dev Build
