### ISSUE TITLE
GER - Change the event picture of 'Terboven's Fate'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2736]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I suggest that the 'Terboven's Fate' event picture should be changed to Josef Terboven image.

### Justifications

Well, the 'Terboven's Fate' event is about what to do with Josef Terboven after he was arrested for abandonment of Norway and this event uses the picture of two men viewing the mountains from Northern Europe. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7c995670-dcbc-4121-a8ee-9c0561a2142b)

**Comment by runelead00** [comment]
Changed in Dev Build
