### ISSUE TITLE
Italy - Nukes made through Progetto Alfa don't display

### ISSUE THREAD

**Issue by Dutchman1217** [TNODevs/TNO-Bug-Tracker#2737]
### Operating System

Windows 10

### HOI4 version

1.13

### TNO version

1.5.0b

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

For Italy, nukes produced through using Progetto Alfa do not display on the world nukes list in the cold war interface, or on your own nukes interface in the social tab in the economy tab.

### Steps to reproduce / Cause of the issue

Use progetto alfa to produce nukes

### Expected behaviour

I expected for the nukes produced to be displayed, as well as a way to produce more than  one at a time

### Screenshots

![Screenshot (40)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149511437/bdbaae42-6281-4816-82e9-355a34fd9bcc)
![Screenshot (39)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149511437/52431647-5ee9-473f-b8c3-8548533eda2c)

**Comment by runelead00** [comment]
Fixed in Dev Build
