### ISSUE TITLE
Speers Germany- Speer post civil war doesnt get an event that allow it to advance to phase 2 speers germany locking me out of the rest of the game

### ISSUE THREAD

**Issue by Kaiserspeer** [TNODevs/TNO-Bug-Tracker#2739]
### Operating System

Windows 11

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

The Moe Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

neither the AI or I are able to advance to the second phase of speers germany post civil war because according to the focus that allows germany to progress Germany has not reclaimed hegemony over europe which locks me out of most of the story for speers germany wether the AI is playing or I am playing

### Steps to reproduce / Cause of the issue

1. Play any normal game of TNO
2. Have Speer win Germanys civil war
3. Wait until germany takes over europe
4. nothing else will happen in germany for the entire game

### Expected behaviour

I was expecting speers germany to be able to be played 

### Additional information

this doesnt lock germany out of the slave revolt just their entire focus tree

**Comment by runelead00** [comment]
Could you provide a zip file of a save with the issue present

**Comment by Kaiserspeer** [comment]
[CHT_1967_06_02_03.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13401780/CHT_1967_06_02_03.zip)
 sorry for the wait the device that i was using was unable to send save games

**Comment by runelead00** [comment]
Fixed in Dev Build
