### ISSUE TITLE
USA - Events spam about anti-war movements that destroys stability when im not at war

### ISSUE THREAD

**Issue by rywiannd** [TNODevs/TNO-Bug-Tracker#274]
**Questions**

- Operating System:
   Windows 10
- HOI4 Version: 
  Collie v1.10.8
- TNO Version:
   TNO v1.2.0 - Toolbox Theory
- Any other mods in use:
  Only TNO and TNO radio
- Were you using Steam?
  Yes
- Which expansions do you NOT have?
   La Resistance and Battle for the Bosphorus
   
**Longer Description of Issue:**
The events first fired around 1969 when i was playing as Bennett, during the port negotiations. It was the event "A Nation Defiant" that first fired which caused the disunity of the American society and stability debuffs. After that, it soon kept firing every 2 months or so even though for a majority of that time, I wasnt even at war, except for the Iberian wars which took about 3 months to beat. Then it kept going worse as another event "Last Resorts" followed suit and soon they both started firing every 2 months until America's stability fell into the negative and the L-NPP gained a sizeable popularity.

**Steps to Reproduce/Cause Issue:**

1. Play the USA

2. Win the West African War in a very short time (a year's time or less) 
    NOTE: I don't have definitive proof that this was the cause but I have my suspiciouns
    
3. Wait until 1969 (around port negotiations)

4. Voila! Let it begin
  

**Screenshots:**

![20211123141357_1](https://user-images.githubusercontent.com/94892913/142987695-3133e0b1-6b78-4911-a386-c5d8ab670642.jpg)

**Comment by runelead00** [comment]
Should be fixed in Current Release
