### ISSUE TITLE
BOR - One division spawn in province 3151

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2740]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

South African Civil War started before the Afrika-Schild intervened, there is one division spawned in province 3151.

### Steps to reproduce / Cause of the issue

1. Boers Rebellion triggered.
2. South African Civil War starts.
3. One division somehow spawned in province 3151.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1b77d1d5-805b-47c5-81a8-957c9a8f17b1)

**Comment by runelead00** [comment]
fixed in dev build
