### ISSUE TITLE
GER - Some confusing 'The Barons' Kaukasia focus tree's descriptions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2741]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13372698/GER_play.zip)

### List the loc issues below

- [ ] 1. When playing as Bormann's Germany during the GCW, I received the 'A Letter from Katharinastadt' event about Paul Pleiger and his industrialist declaring support for Bormann after Paul Pleiger coup against Josias. Then when Bormann won the GCW, retook almost all of Eastern Europe, and took the Kaukasia focus tree, some of the Kaukasia national foci's descriptions talk about 'The Barons' were supporting Goring during the GCW instead of supporting Bormann during the GCW.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/391d510c-dfd8-4041-ba6c-03e753c61e79)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/088efad7-656d-471a-a115-3b8fdb5eadab)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1b76f97d-6aff-4fce-b843-ae706ac68a37)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/51e3d25c-d062-4924-b664-ec430480c0d7)

**Comment by runelead00** [comment]
Fixed in Dev Build, flag not being checked correctly
