### ISSUE TITLE
GER - Slight issue of 'The Reich's War Down in Afrika' focus description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2742]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13372932/GER_play.zip)

### List the loc issues below

- [ ] 1. In the text of 'The Reich's War Down in Afrika' focus talks about the "Union of South Africa" and "American-aligned union" but the current name of South Africa is the Republic of South Africa because the monarchy in South Africa is abolished. So, it should be replaced "Union of South Africa" word with South Africa tag name code and "American-aligned union" should be replaced with "American-aligned South Africa" or something like that.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9eeedf98-e154-4102-b683-4a0491de0d02)

**Comment by runelead00** [comment]
Fixed in Dev Build
