### ISSUE TITLE
GER - The 'Fastung Johannesburg' decision has no effects to give Afrikaner Volkstaat something

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2743]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_south_africa_war.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13373436/GER_south_africa_war.zip)

### Describe the bug

In the 'Fastung Johannesburg' decision effects, there is no effect for giving Afrikaner Volkstaat something compared to the other three decisions that have to give three Afrikan Reichskommissariats.

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. Bormann won the German Civil War.
3. The Germans intervened in the South Africa War.

### Expected behaviour

Forgot to add them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/86d181e1-4c0f-4592-8b0b-2fd318bcb74d)

**Comment by runelead00** [comment]
Fixed in Dev Build
