### ISSUE TITLE
GRO/ANG/COG - Change the GFX icon of 'Schock-Methode' national spirit

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2751]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest changing the GFX icon of 'Schock-Methode' national spirit to something land army forward GFX icon or something like that.

### Justifications

The 'Schock-Methode' national spirit GFX icon uses the 'bombing runs in the Africa' GFX icon that the national effects give division buffs instead of air buffs.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5e97dc5f-2bde-4d50-b04c-0581246c9e73)

**Comment by runelead00** [comment]
Not changing the icon, but adding some air effects. The huge part of Shock and Awe is the bombing
