### ISSUE TITLE
BOR - Conservative party popularity is removed when the Großafrikanischer Reichsstaat formed

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2752]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_afrikaner.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13384687/GER_afrikaner.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13384689/Logs.zip)

### Describe the bug

When the Afrika-Schild achieved total victory in the South Africa War, Afrikaner Volkstaat had conservative party popularity and Großafrikanischer Reichsstaat formed, Afrikaner Volkstaat somewhat had conservative party popularity removed.

### Steps to reproduce / Cause of the issue

1. Total victory for Afrika-Schild in the South Africa War.
2. Afrikaner Volkstaat changed its ruling party to fascist corporatism.
3. Afrikaner Volkstaat has conservative party popularity.
4. Großafrikanischer Reichsstaat is formed.
5. Afrikaner Volkstaat removes conservatism party popularity.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fb9b5c47-6cae-46cc-af8a-f107a17d86d9)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ca406a8c-04c9-4fdb-a3a9-172eda6ded4a)

**Comment by runelead00** [comment]
Fixed in Dev Build
