### ISSUE TITLE
MCW - Moskowien still has an 'Autonomous Reichskommissariat' faction icon instead of 'Military Authority' faction icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2754]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13386352/GER_play.zip)

### Describe the bug

Similar to #2233. 

### Steps to reproduce / Cause of the issue

1. Bormann won the German Civil War.
2. Greater German Reich retakes Eastern Europe.
3. Germany reconquers Moskowien.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b85fbb90-49bc-457d-b2c1-1e3115179983)

**Comment by runelead00** [comment]
Fixed in Dev Build (think I only actually fixed Speer's Mosk the last time this was reported)
