### ISSUE TITLE
GGN - Generalgouvernement has Reichsprotektorat puppet status instead of Integrated Reichskommissariat puppet status

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2755]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13386370/GER_play.zip)

### Describe the bug

After the Germans defeated Poland and reestablished the Generalgouvernement, Generalgouvernement became Reichsprotektorat puppet status of Germany instead of the Integrated Reichskommissariat puppet status. Because Generalgouvernement will get annexed by Germany during the Oil Crisis and Crisis in the Reich. 

### Steps to reproduce / Cause of the issue

1. Bormann won the German Civil War.
2. The Germans decided to go to war with Poland to reestablish the Generalgouvernement.
3. Polish defeated and Generalgouvernement was reestablished.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f7efe3af-e731-461d-b2f3-95dca3ac77e5)

**Comment by runelead00** [comment]
Fixed in Dev Build
