### ISSUE TITLE
USA - African Mandates conflict tab doesn't remove if Congo collapses at last

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2756]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

As title
If Central Africa Mandate(congo) collapses after angola and east africa finishes, system won't wipe out conflict tab, manpower damage is still counting

### Steps to reproduce / Cause of the issue

in event OFN_COG.16 (mandate collapse event), add this code
		USA = {
			if = {
				limit = {
					Angola_is_independent = yes
					Mozambique_is_independent = yes
				}
				TNO_fopo_remove_saf_reconstruction_conflict_tab = yes
			}
		}

### Expected behaviour

tab can be removed after congo collapse

**Comment by runelead00** [comment]
Fixed in Dev Build
