### ISSUE TITLE
GER - The "inn" word should be "in" in the 'Negotiation with Parliament' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2757]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. There is a slight typo word of "inn", it should be "in".
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/50ff70c5-c511-47cc-9d93-273a68b580f8)

**Comment by runelead00** [comment]
Fixed in Dev Build
