### ISSUE TITLE
HAI - Generic Character Leads Haiti

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2758]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13388749/autosave.zip)

### Describe the GFX issue

When Michael Roumain is in power in Haiti, there is no GFX portrait of Michael Roumain. 

### Steps to reproduce / Cause of the issue

1. Trujillo won the PPI.
2. Haitian Civil War triggers.
3. Cantave coup in Haiti.
4. Port-au-Prince was surrounded by communists controlled in Haiti.
5. Haitian Blitz triggers.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/366bf12d-af09-45a6-aa10-3807a91ae467)

**Comment by runelead00** [comment]
Fixed in dev build
