### ISSUE TITLE
HAI/USA - Bugs after Haitian Blitz ceasefire

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2759]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13388859/Logs.zip)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13388864/autosave.zip)

### Describe the bug

- When the Haitian Blitz ceasefire was triggered, the Haitian Revolutionary Front (HAC) was somehow gone and annexed by the Haitian government instead of retaining its previously controlled states before the Blitz.
- Despite the PPLN no longer exist, the PPLN lunches general uprising triggered. And for USA, there are still 'The Status of the War' decision timer and other HCW decisions appear instead of replacing them with an actual war of HCW decisions that can able to send weapons and volunteers to the Haitian Government. Without the HAC (Haitian Revolutionary Front) tag, the Haitian Civil War proxy war still remains for USA and in the USA's Cold War achievements without end, and USA stuck with the Haitian Civil War and its stability and war support would decrease forever. 

### Steps to reproduce / Cause of the issue

1. Trujillo won the PPI.
2. Haitian Civil War triggers.
3. Cantave coup in Haiti.
4. Port-au-Prince was surrounded by communists controlled in Haiti.
5. Haitian Blitz triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8ffa7184-7a65-4a1a-8bb2-1b225e76a1b4)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2fa0686d-c79b-408a-a2bb-d890e30284b2)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bed6c0a7-acd7-422c-bc34-a6259cb08c2d)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4b989da8-0103-42d6-9093-aa08d38968b0)
![Image_5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5aa94ee9-e119-48e6-9b27-ed0b7432757b)
![Image_6](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/de4b229d-4da0-4afc-a62b-fd71a1fa3f0b)

**Comment by runelead00** [comment]
Hinche working as designed, pro-Dominican ceasefire keeps the Hinche

**Comment by Ikidikid** [comment]
Um, this issue is not about Hinche.

**Comment by runelead00** [comment]
it's too late, I read part of the first issue as being about the Hinche

**Comment by runelead00** [comment]
should be fixed in dev build
