### ISSUE TITLE
Bormann Germany - cant dismantle factions 

### ISSUE THREAD

**Issue by bigbadboy78** [TNODevs/TNO-Bug-Tracker#276]
**Questions**

- Operating System:
- HOI4 Version: latest (collie)
- TNO Version: 1.20 c
- Any other mods in use: Terra Liberta
- Were you using Steam? Yes
- Which expansions do you NOT have? All 

**Longer Description of Issue:**
Can't dismantle any factions despite 71 percent superiority. 
*
*Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by bigbadboy78** [comment]
Version was 1.20 D sorry, last patch before NSB. I could press the dismantle button but simply couldn't do the execute button despite years of waiting

**Comment by Stormeagle449** [comment]
Fixed in current release.
