### ISSUE TITLE
DOM - AI doesn't sent air wings to air mission during the PPI and Haitian Blitz

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2760]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In my game run, AI (fascist) Dominican Republic doesn't seem to use its air wings during the Puerto Plata Invasion and the Haitian Blitz.

### Steps to reproduce / Cause of the issue

1. The Puerto Plata invasion starts.
2. The Haitian Blitz starts.

### Expected behaviour

I don't know.

**Comment by runelead00** [comment]
We can't touch how the AI uses air units as far as know, if it's an issue it's on paradox's side
