### ISSUE TITLE
GER - "Suspect D" sentence has no line break and space in the 'Eyes and Ears Everywhere' event description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2761]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In the 'Eyes and Ears Everywhere' event description, there is no line break and space for "Suspect D".
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/40a723a4-5233-4d13-9821-ce5b5d0fec3e)

**Comment by runelead00** [comment]
There is no reason to have a line break there
