### ISSUE TITLE
GER - There are double "that" words in the 'Find the Dirt' focus description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2763]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In the 'Find the Dirt' focus description, I saw double "that" words. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/311204f9-8023-4390-a409-53cfcd2fcb6f)

**Comment by runelead00** [comment]
Fixed in Dev Build
