### ISSUE TITLE
GER - A typo word "fro" in the decision description of 'The Krakau Railway Junction'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2765]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. There is a typo word "fro" in the decision description of 'The Krakau Railway Junction'. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/622e36d9-2ac3-4486-ab01-e02ac02795ff)

**Comment by runelead00** [comment]
Working as Designed
