### ISSUE TITLE
GER - German agent doesn't return after the 'Unternehmen Schild' operation finished

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2766]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13392643/Logs.zip)
[GER_west_russia_attacks_finland.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13392879/GER_west_russia_attacks_finland.zip)

### Describe the bug

After the 'Unternehmen Schild' operation finished, the operative didn't return. 

### Steps to reproduce / Cause of the issue

1. Either Bormann or Speer won the German Civil War.
2. Germany created its intelligence.
3. Select 'Unternehmen Schild' operation.
4. 'Unternehmen Schild' operation finished.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ad5066d5-30c6-4e2f-abbf-dc933ad6267e)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/29416445-d356-4443-87eb-0fce77811c5e)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/30b0db61-3d3b-4bb1-ae38-2affcce60af1)

**Comment by runelead00** [comment]
Fixed in Dev Build
