### ISSUE TITLE
GRO - Zaire and Uige are not demilitarized when the Angolans starting to revolt

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2767]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13398311/GER_play.zip)

### Describe the bug

When the Angola region sparked the rebellion and Angola became demilitarized, Zaire and Uige are included to be demilitarized because these two states could become part of Angola when Angola tag is created. 

### Steps to reproduce / Cause of the issue

1. South Africa War ended and the Afrika-Schild survived.
2. Großafrikanischer Reichstaat formed.
3. Angolans began to rebel. 

### Expected behaviour

Forgot to include them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7de0d5e1-999b-483c-991d-7d9bafb1eb13)

**Comment by runelead00** [comment]
Fixed in Dev Build
