### ISSUE TITLE
GER - A slightly small space before "TOP SECRET INFORMATION" sentence in 'Reichsbanner' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2768]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. There is a slightly small space before "TOP SECRET INFORMATION" sentence in 'Reichsbanner' event description. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0c3481c8-8ce4-45fd-8967-a03a2ae31e8c)

**Comment by runelead00** [comment]
Fixed in Dev Build
