### ISSUE TITLE
All tags - No Intelligence Agency Insignia placed in the Foreign Operative event despite having the Agency Insignia

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2769]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13398424/GER_play.zip)

### Describe the bug

When the (hoi4 vanilla) Foreign Operative event pops out, there is no intelligence agency insignia placed despite having the Agency Insignia. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. Has Intelligence Agency Insignia.
3. The Operative event popped out.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fba2a610-089b-4024-931a-caa30bbb458d)

**Comment by runelead00** [comment]
Not included because it looks CRT on paper looks terrible
