### ISSUE TITLE
Japan - No cold war victory points awarded due to victory in Philippines

### ISSUE THREAD

**Issue by DraconicAspirant** [TNODevs/TNO-Bug-Tracker#277]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Collie v1.10.8.
- TNO Version: 1.2.0.c
- Any other mods in use: Only Radio TNO
- Were you using Steam? - Yes
- Which expansions do you NOT have? - LR,BoB,NSB

**Steps to Reproduce/Cause Issue:**

1. Defeat both insurgent groups in the Philippines as Japan. No second landing in my game.
2. Succeed at the reconstruction of the country. Reconstruction process declared complete at 100% in my game.
3. Wait until the new president is inaugurated and the country joins the sphere, at which point, cold war victory points were probably meant to be awarded. Screenshots below were taken 3-4 in-game months after this.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/50157156/143016322-b7a39d05-4f58-4413-b531-d0badac20aaf.png)
![image](https://user-images.githubusercontent.com/50157156/143016369-65469548-97b0-4b03-811f-c031209df408.png)

**Comment by Scarsoftime** [comment]
Fixed
