### ISSUE TITLE
GER - Some Unternehmen operations are not appear in intelligence tab after unlock them through focuses and events

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2771]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13399274/GER_play.zip)

### Describe the bug

The 'Unternehmen Nordlich't and 'Unternehmen Vier' operations do not appear or are available in the intelligence tab after taking the Milorg's Norway focus to take a coup and 'A Gang Remnant' event. 

I don't know if some Unternehmen operations have bugs that same as this. 

### Steps to reproduce / Cause of the issue

1. Bormann won the Civil War.
2. Has the Intelligence tab.
3. Milorg controls Norway.
4. Two members of Gang of Four located in Switzerland. 

### Expected behaviour

I don't know what causes this.

**Comment by runelead00** [comment]
Fixed in Dev Build
