### ISSUE TITLE
GRO - Léopoldville Verwaltung is not become a puppet of Germany due to Marionettenstaat after selecting 'The Cabal Victorious' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2773]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13399637/GER_play.zip)

### Describe the bug

Léopoldville Verwaltung does not become a puppet of Greater German Reich after selecting 'The Cabal Victorious' event because Léopoldville Verwaltung has Marionettenstaat faction icon.

### Steps to reproduce / Cause of the issue

1. South Africa War ended and Afrika-Schild existed.
2. Großafrikanischer Reichsstaat formed.
3. Kai-Uwe von Hassel overthrow Hüttig.
4. Léopoldville Verwaltung form.
5. Léopoldville Verwaltung joins the Pakt.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c1b72cb4-4cdf-4fe4-883c-f36b508efb4c)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aa21f15e-d9bc-4405-a7fe-21c0c805ca9d)

**Comment by runelead00** [comment]
Fixed in Dev Build
