### ISSUE TITLE
BOR - The Afrikaner Volkstaat joins the Pakt talks about the Afrikaner Volkstaat "rejoins" the Pakt but Afrikaner Volkstaat wasn't joining the Pakt in the first place

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2775]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. The Afrikaner Volkstaat joins the Pakt news event talks about the Afrikaner Volkstaat "rejoins" the Pakt but Afrikaner Volkstaat wasn't joining the Pakt after the South Africa War because Afrikaner Volkstaat was a puppet of Reichskommissariat Ostafrika and Reichskommissariat Ostafrika wasn't join either. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d64a712c-1969-4711-8806-4ffe3ab1c24d)

**Comment by runelead00** [comment]
Fixed in Dev Build
