### ISSUE TITLE
BOR - Afrikaner Volkstaat changes its ruling party to fascist (Corporatism) when the SAW ended

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2776]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_saw_ends.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13400201/GER_saw_ends.zip)

### Describe the bug

After the South Africa War in favor of partial or total victory for Afrika-Schild, Afrikaner Volkstaat suddenly changed its ruling party to fascist (Corporatism).  

Because, according to the event text from MEMORANDUM ON THE Afrikaner Volkstaat, The Afrikaner Volkstaat rejoins the Pakt and other Afrikaner Volkstaat aftermath of Reichsstaat collapsed events mentions that Albert Hertzog resigned because he aligned with Hüttig's Greater Afrika but Albert Hertzog was no longer leader of Afrikaner Volkstaat when the SAW ended.

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. Either partial or total victory for Afrika-Schild in the SAW.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/ebd6aa38-3d07-4a11-9fcc-aaaaf15bd2e9)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/57e1badb-51fe-4166-ad75-eba1e941debb)

**Comment by runelead00** [comment]
Fixed in Dev Build
