### ISSUE TITLE
GER - 'Integrate Denmark' decision does not appear or available after completing the 'A Modern Wunderwaffe' or 'Removing the Weeds...' focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2778]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_railway_to_denmark.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13400602/GER_railway_to_denmark.zip)

### Describe the bug

The 'Integrate Denmark' decision does not appear or is available when completing the 'A Modern Wunderwaffe' or 'Removing the Weeds...' focus.

However, when I looked at the codes, the 'Integrate Denmark' decision required Denmark's ruling party to be Despotism only instead of including Paternalism because Werner Best also wanted Denmark to be integrated with the Greater German Reich. So, the 'Integrate Denmark' decision should be available if Denmark is **either** Paternalism or Despotism. 

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Bormann won the German Civil War.
3. Werner Best secures his position in Denmark.
4. GroBraum Kontinentaleuropa created.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c0dbc66a-baa9-4bb5-af69-d5ab5fce732a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b616ec06-7b90-49d2-a55c-9171229286d5)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d5c8476e-a63a-455b-8154-18ce47d77758)

**Comment by runelead00** [comment]
Denmark does not always get integrated into Germany, only if an RK under Hanneken gets set up
