### ISSUE TITLE
Every countries - Impossible to unlock the 5th slot for divisions in doctrine

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2779]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

![280239435-0beb7cc4-0389-41ca-b9b4-38853bb05f64](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/89258d50-123c-4394-9c74-64a66b27aec1)
![MY)3A S1Q1OCLS($IXX UEF](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/d3eddde8-b280-4c3d-b3d1-bc84b67dae7e)
![C(Z`C8LMY}{{1{H41`JLKRS](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/d0180ddd-4eb3-4f99-8a7a-f3f80b82672d)
![4U}YD_ 4ZFIU67M76 T0_UH](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/a30f1aa6-927e-4118-b300-38328670b959)

### Describe the bug

such as title

### Steps to reproduce / Cause of the issue

add "additional_brigade_column_size = 1" for every land doctrine lines
i suggest to put it at start, this can avoid some bugs for AI and make game more reality (they were supposed to unlock slot 5 in 40s for HOI4 timeline hehe)

### Expected behaviour

Slot 5 can be unlocked properly, at least in normal game

**Comment by MrStraws114514** [comment]
in file TNO - common - technologies - **land_doctrine**

**Comment by MrStraws114514** [comment]
with a small bug that has strange grammar here, i dont think this is enough to create a new report
![9PKC00 Q{$L87J}POD)G)XF(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/ae8835f6-6b3d-486b-a10c-8925496a7c63)

**Comment by runelead00** [comment]
Fixed in Dev Build
