### ISSUE TITLE
Effects of Good Hope Resolution don't work 

### ISSUE THREAD

**Issue by Warszawer** [TNODevs/TNO-Bug-Tracker#278]
**Questions**

- Operating System: Windows 10
- HOI4 Version: latest (collie)
- TNO Version: 1.20 c
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? BoB, NSB

**Longer Description of Issue:**
When I passes Good Hope Resolution as Bennett (after the Advisors No More focus), I can't send more volunteers to South Africa (whereas it should be 8).
I checked the code .../events/TNO_America_RD.txt
where in `id = RD_SAF.19` I found:

```
set_temp_variable = { target = ITA }
    set_temp_variable = { number = 8 }
    TNO_set_num_volunteers = yes
    custom_effect_tooltip = "TNO_advisors_no_more_increase"
```
By this way, I can send 8 volunteers to Italy, and not to South Africa...
Then I change the tag from `ITA` to `SAF`, and effects of Good Hope Resolution are working now.

I hope you will have no trouble fixing this problem for other players.

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting.
