### ISSUE TITLE
GER - Some bugs after Léopoldville Verwaltung won the Congo War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2780]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13402057/GER_play.zip)

### Describe the bug

- After Léopoldville Verwaltung won the Congo War, rejoined the Pakt and became a subject of Germany, Léopoldville Verwaltung has the Marionettenstaat faction icon instead of the Autonomous Reichskommissariat faction icon because Marionettenstaat talks about the pan-European ideal and some sort and Léopoldville Verwaltung is not in Europe.
- After Léopoldville Verwaltung won the Congo War and Paktkommission was formed, Paktkommission Kongo became an Autonomous Reichskommissariat puppet status instead of becoming a Military Government puppet status because the word "Paktkommission" and Paktkommission Kongo is under military government.  

### Steps to reproduce / Cause of the issue

1. South Africa War ended and Afrika-Schild existed.
2. Großafrikanischer Reichsstaat formed.
3. Kai-Uwe von Hassel overthrow Hüttig.
4. Großafrikanischer Reichsstaat collpased in devastation 1 or 2.
5. Léopoldville Verwaltung form.
6. Congo Civil War triggers.
7. Léopoldville Verwaltung won the Congo War.

### Expected behaviour

Forgot to check them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/40897e67-a8cf-4e67-b4ff-2d611be739d3)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dcad0eda-e981-41c6-949f-7300aa18e7a0)

**Comment by runelead00** [comment]
Fixed in Dev Build
