### ISSUE TITLE
GRO - Some suggestions about Léopoldville Verwaltung

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2781]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that after the Großafrikanischer Reichsstaat collapsed, Léopoldville Verwaltung formed and Léopoldville Verwaltung joined the Pakt, Léopoldville Verwaltung should have the Autonomous Reichskommissariat faction icon instead of have Marionettenstaat. And Léopoldville Verwaltung should become Autonomous Reichskommissariat puppet status of Germany.

### Justifications

The Marionettenstaat description talks about the members of the Pakt that are close together with the Reich, supporting the pan-European ideal led by the Reich and some sort. Léopoldville Verwaltung has the Marionettenstaat faction icon is confusing to me because Léopoldville Verwaltung is in Africa, not in Europe. So, that is why I suggest Léopoldville Verwaltung should become an Autonomous Reichskommissariat when joining the Pakt.

**Comment by runelead00** [comment]
Fixed in Dev Build
