### ISSUE TITLE
GER - Unternehmen Tapferkeit operation is not appear in the Europe region in the intelligence tab after selecting 1st option from 'Facing the Night' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2783]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13402388/GER_play.zip)

### Describe the bug

When selecting the first option from the 'Facing the Night' event, the Unternehmen Tapferkeit operation does not appear in the Europe region in the intelligence tab.

### Steps to reproduce / Cause of the issue

1. Bormann won the German Civil War.
2. Germany proceeds to phase 2 of Bormann's focus tree.
3. Taking the anti-Burgundy focus tree.
4. Select the first option from the 'Facing the Night' event.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a7dc52d5-4448-4e6b-92aa-6cb84b725e16)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fcc3b5f3-83a8-42a9-844e-092bf5e2535e)

**Comment by runelead00** [comment]
Fixed in Dev Build
