### ISSUE TITLE
GER - Decreasing intelligence budget and expertise are different than operation requirements met

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2784]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13402697/GER_play.zip)

### Describe the bug

When selecting the operation, subtracting budget and expertise are different than operation requirements met. Like, after selecting Unternehmen Architekt shows the required 20% expertise and 50M budget, expertise and budget are decreased differently which means that instead of subtracting 20%, it subtracts 50% and instead of subtracting 50M budget, it subtracts 20M budget. 

Here are some of the German operations that have issues like this one:
- Unternehmen Architekt
- Unternehmen Vier
- Unternehmen Schwarzes Gold
- Unternehmen Unsterblich
- Bug Political Enemies
- 'Disappear' Reactionaries

I don't know if there are some German operations that have similar issues as this one because I barely look at the German espionage codes. 

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Either Bormann or Speer won the German Civil War.
3. Has the intelligence tab.
4. Select some Unternehmen operations.

### Expected behaviour

Decreasing differently than requirement met. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/49d98018-4795-461e-89b5-dfcd076a6c15)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/abbcc508-6df2-47e7-9b05-6dadb4167475)

**Comment by runelead00** [comment]
Fixed in Dev Build
