### ISSUE TITLE
DOM - 'The Puppet of Caudillo' national spirit didn't remove after Balaguer taking over

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2785]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13402879/GER_play.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13402882/Logs.zip)

### Describe the bug

When Balaguer defeated Ramfis Trujillo during the power struggle and end of Caudillato in Santo Domingo, 'The Puppet of Caudillo' national spirit still exists and didn't remove. 

### Steps to reproduce / Cause of the issue

1. Trujillo won the PPI.
2. Trujillo won the Haitian Blitz.
3. Death of Trujillo, Ramfis takes over but is under puppet by the Military Intelligence Service.
4. Balaguer won the power struggle against Ramfis.
5. End of Caudillato in Santo Domingo.

### Expected behaviour

Forgot to remove it, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6bac1047-a882-45bb-a9eb-b9b2ce71af07)

**Comment by runelead00** [comment]
Fixed in Dev Build
