### ISSUE TITLE
The puppet Portuguese leader of the Blue Front has the wrong avatar

### ISSUE THREAD

**Issue by ds-xiaoyi** [TNODevs/TNO-Bug-Tracker#2787]
### Operating System

windows11

### HOI4 version

1.13

### TNO version

1.5.0.b

### Do you have other mods in use?

chinese translate

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Blue Front of the Spanish Civil War could not pass the war normal puppet Portugal, and the leader of the command puppet was the portrait of the original Salvation Government instead of the occupation authorities, and there was also the icon of the Organization of Free Nations in the upper right corner

### Steps to reproduce / Cause of the issue

1.Presuppose the Falangist collapses
2.The Blue Front won the Spanish Civil War
3.Since it is not possible to pass the war puppet Portugal properly, use the command: event iberiawars.29
4.Look at Portugal

### Expected behaviour

Please fix it as soon as possible, you can leave the icon in the upper right corner unfixed, but please be sure to fix the bug that the leader is not the occupation authority

### Screenshots

![20231119195229_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/102014915/8fd47ad9-279a-43f7-aff1-1d7bd30f729f)

**Comment by runelead00** [comment]
Fixed in Dev Build
