### ISSUE TITLE
USA - Has no power project on Indian Ocean despite there is an Australia has cost to Indian Ocean after total defeat in SAW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2788]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13402975/GER_play.zip)

### Describe the bug

After the total defeat for South Africa in the South Africa War and the dissolution of South Africa, USA had no power projection on the Indian Ocean despite that there is Australia has a coastline through the Indian Ocean and also an OFN member. 

### Steps to reproduce / Cause of the issue

1. South Africa War triggers.
2. Total victory for Afrika-Schild.
3. End of South Africa.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b3cc729e-c958-4e6b-aceb-5f57b19005a3)

**Comment by runelead00** [comment]
Fixed in Dev Build
