### ISSUE TITLE
USA - Manpower Reserves (under decisions, not vanilla manpower) keeps decreasing for no aparrent reason

### ISSUE THREAD

**Issue by Arminius-de** [TNODevs/TNO-Bug-Tracker#2789]
### Operating System

Windows 11

### HOI4 version

Stella Polaris v1.13.5.7c31 (8f25) (S)

### TNO version

TNO v1.5.0b - "The Ruin"

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13403115/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13403116/error.log)
Save game is too big for github upload, you can download it here: https://wormhole.app/Q1dYL#5sQ3fju7f28_HWpJDyuENg

### Describe the bug

For some reason my manpower reserves keep decreasing even though I am not involved in an active war anymore. I suspect it is related to me using the send more volunteer option (at foreign politics) during the South Africa against German African colonies war. I lost it and regained my divisions from the evacuate capetown "decision" and i think the manpower depletion should have stopped there but it seems it didn't.

### Steps to reproduce / Cause of the issue

Not sure, but its probably:
1. Become friendly with South Africa as USA
2. Support South Africa during African Civil War / War against German colonies that triggers shortly after Hitler dies
3. Use the send more volunteers option under Foreign policy (I did it multiple times)
4. Lose the war, but evacuate your troops by not losing capetown after 14 days

### Expected behaviour

manpower reserves drain should stop after troops are evacuated

**Comment by runelead00** [comment]
Fixed in Dev Build
