### ISSUE TITLE
USA - 'No More Free Launches' focus has shown that "Effect:" and 'All voters:' are separated from each other compared to other focuses

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2790]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13403305/GER_play.zip)

### Describe the bug

The 'No More Free Launches' focus has shown that "Effect:" and 'All voters:' are separated from each other or have a slightly bigger line space between them compared to other focuses. 

### Steps to reproduce / Cause of the issue

1. Robert F. Kennedy won the 1964 election.
2. RFK is safe from assassination.
3. Either Hart or Goldwater won the election in 1968 election.

### Expected behaviour

Forgot to check them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/188b0e49-aee9-4613-89ae-3585961aff7d)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2bd66e12-ab52-4bd1-a316-55451e776e45)

**Comment by runelead00** [comment]
Fixed in Dev Build
