### ISSUE TITLE
FIN - The Second Crisis of Democracy national spirit didn't remove or modify when the news triggers about 'The End of Finnish Democracy'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2791]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13404869/GER_play.zip)

### Describe the bug

When 'The End of Finnish Democracy' news event triggered due to both the president and prime minister are fascists, The Second Crisis of Democracy national spirit didn't removed or modified.  

### Steps to reproduce / Cause of the issue

1. Communist Russian warlord reunites West Russia region.
2. Murmansk Peoples Republic rebels against Finland.
3. Second Finnish Civil War triggered.
4. Lauri Törni takes over Finland.
5. Elias Simojoki takes over FInland.
6. End of Democracy in Finland.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2019e275-fcc6-48ac-9815-7f2c206e1eba)

**Comment by runelead00** [comment]
Fixed in Dev Build
