### ISSUE TITLE
FIN - 'An Unsatisfactory Answer' national spirit didn't modify when changing policy toward Murmansk

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2792]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13404905/GER_play.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13404907/Logs.zip)

### Describe the bug

When the news event triggered about the changing policy toward Murmansk after Finland defeated them, the 'An Unsatisfactory Answer' national spirit didn't modify. 

### Steps to reproduce / Cause of the issue

1. Murmansk Peoples Republic was crushed by Finnish forces.
2. Finland defeated West Russia.
3. Greater Finland endures.
4. Changing policy toward Murmansk. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2701a235-202e-4c4e-9cf2-4e3da20cec8a)

**Comment by runelead00** [comment]
Fixed in Dev Build
