### ISSUE TITLE
GER - German agent doesn't return after the 'Unternehmen Geld - Send Supplies' and 'Send Aid to the Spanish Fascists' operations done

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2794]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13405896/Logs.zip)
[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13405898/GER_play.zip)

### Describe the bug

After the 'Unternehmen Geld - Send Supplies' and 'Send Aid to the Spanish Fascists' operations finished, the German agent didn't return. 

### Steps to reproduce / Cause of the issue

1. Either Bormann or Speer won the German Civil War.
2. Germany has the intelligence tab.
3. Oktan is a leader of Samara.
4. Iberian War triggers.

### Expected behaviour

Forgot to add code to return agent when the operation is complete.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/1bd90a12-5344-493f-912d-f8091b394a21)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3e7278c0-709c-4d7a-9414-c0058f9ed32d)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c3f8a6ce-fa34-465a-b6aa-9421e10fb57c)

**Comment by runelead00** [comment]
Fixed in Dev Build
