### ISSUE TITLE
GNS - Falangist Portugal is not at war with Portuguese Republic after Falangists take over Government of National Salvation

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2795]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13405954/Logs.zip)
[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13405955/GER_play.zip)

### Describe the bug

When the Falangists took over the Government of National Salvation and became Falangist Spain's puppet, Falangist Portugal and Portuguese Republic somehow ended up in white peace with each other instead of continuing to war with each other. 

### Steps to reproduce / Cause of the issue

1. Iberian War triggers.
2. Asturian Workers revolt in Falangist Spain.
3. Asturian Workers were crushed.
4. Falangists take over the Government of National Salvation and become Falangist Spain's puppet.
5. Falangist Portugal and Salazarist Portugal are not at war.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2d1582cc-bfd0-4fb3-a502-c53b02c7e87a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d1d286ff-c934-4afe-b7cf-e96d94b61cc9)

**Comment by runelead00** [comment]
Fixed in Dev Build
