### ISSUE TITLE
GER - Placeholder in option text of 'A Closed Curtain' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2797]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. There is a placeholder in the option text of the 'A Closed Curtain' event, " #'kill me.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/76fad58f-da2d-4457-b770-8f542443b745)

**Comment by runelead00** [comment]
Fixed in Dev Build
