### ISSUE TITLE
YUN/NPA - Problems with North Expedition GUI

### ISSUE THREAD

**Issue by TaiKangRW** [TNODevs/TNO-Bug-Tracker#280]
**Questions**

- Operating System: Win10
- HOI4 Version: Latest
- TNO Version: 1.20c
- Any other mods in use: None
- Were you using Steam?: Yes
- Which expansions do you NOT have?: None

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1. States which were under  NPA's control before North Expedition War, such as Kunming and Chongqing, only have the option of MIL, and can not find ADM options.
Screenshots:
  
![20211123215724_1](https://user-images.githubusercontent.com/42321702/143038955-e6a40986-7d83-4df4-8908-eaf1ba2d4f8a.jpg)
![20211123215730_1](https://user-images.githubusercontent.com/42321702/143038998-b7f0823d-772e-4b93-a774-b04fba0fff9e.jpg)

2. The states' Reintegration Process may be stopped when the war with the North Expedition GUI disappears.
Screenshots:

![20211123220033_1](https://user-images.githubusercontent.com/42321702/143039208-899a4517-cd57-488d-aaf3-7a5351c843ec.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build
