### ISSUE TITLE
GER - 'Icelandic Campaign Season Begins' event has option effect unlocking proxy war text in the event description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2800]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13415204/GER_play.zip)

### Describe the bug

In the 'Icelandic Campaign Season Begins' event, the last paragraph from the event shows the loc of the event's option effects.

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Either Bormann or Speer won the German Civil War.
3. Icelandic 1971 election triggers.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e1195a9b-7ecf-4414-a136-af8d241cefcc)

**Comment by runelead00** [comment]
Fixed in Dev Build
