### ISSUE TITLE
Humanist Tomsk - Focus description has incorrect information

### ISSUE THREAD

**Issue by averagetomskenjoyer** [TNODevs/TNO-Bug-Tracker#2801]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

The very last focus description ("For the Commonwealth!") before regional for Humanist Tomsk has incorrect information.  The very last paragraph incorrectly implies that the secessionist warlords, such as Novosibirsk or Kemerovo, still exist, when you can only complete this focus once you are the last contender in Central Siberia.

### Steps to reproduce / Cause of the issue

1. Play as Tomsk
2. Elect the Humanists
3. Reach the last focus

### Expected behaviour

The aformentioned focus should not have this incorrect information

### Screenshots

![20231104212719_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148972379/fe5ebd46-eb2b-4997-8ad6-348b7cb1749e)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
