### ISSUE TITLE
TUR - Change the news event image from the 'TIP Victory in Turkey!' 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2802]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the 'TIP Victory in Turkey!' news event image should be changed to a picture or photo of Behice Boran.

### Justifications

When the 'TIP Victory in Turkey!' news event, I saw the image was not Behice Boran. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/613add46-c242-416e-92e1-aa7027385725)

**Comment by Marok132** [comment]
It shouldn't? The world event says about TIP victory in general, not only Behice Boran.

**Comment by Stormeagle449** [comment]
Turkey, and by extension its news events, will be overhauled for patch 1.7.0 and have new election events.
