### ISSUE TITLE
LIB/MDI - Liberia and Sierra Leone are not released as puppets after the PALF defeats the Mano Pact

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2805]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13422016/Logs.zip)
[GER_mano_campaign.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13422383/GER_mano_campaign.zip)

### Describe the bug

When the PALF defeated the Mano Pact during the Mano Campaign and the Oil Crisis, Liberia and Sierra Leone were somewhat not released as puppets.

### Steps to reproduce / Cause of the issue

1. The PALF won the West Africa War.
2. The Oil Crisis began.
3. The PALF invades the Mano Pact.
4. The OFN does not intervene.
5. The PALF defeated the Mano Pact.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4e7e3f45-2874-475c-b49b-86929acb6089)

**Comment by runelead00** [comment]
Fixed in dev Build
