### ISSUE TITLE
GER - Slight confuse description in the 'Iceland Leaves the OFN' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2809]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_playthrough.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13432045/GER_playthrough.zip)

### List the loc issues below

- [ ] 1. In the 'Iceland Leaves the OFN' event description says that the Conservative government's victory in the 1971 Icelandic election when the anti-OFN won but Iceland's current ruling party is Democratic Socialism after the anti-OFN won. So, the "Conservative" word should be replaced with "Socialist" because when the anti-OFN wins, the Democratic Socialist or Socialist will take over Iceland. 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/02553e45-d802-4c04-b6fc-8cc278100207)

**Comment by runelead00** [comment]
Fixed in Dev Build
