### ISSUE TITLE
SPR - Some bugs when the Republic of Andalusia spawned

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2810]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13432464/Logs.zip)
[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13432566/USA_game.zip) run the game to see what happens

### Describe the bug

When the Republic of Andalusia spawned due to SPR's war exhaustion is higher during the Iberian Wars, SPR tag is somehow gone without getting conquered event and USA still had the Iberian Wars proxy war to support SPR despite SPR no longer exists. 

### Steps to reproduce / Cause of the issue

1. The Iberian Wars triggers.
2. The Spanish Republic turned into the Kingdom of Spain after reaching more war exhaustion.
3. The Iberian Wars took too long.
4. The Republic of Andalusia tag spawned and declared neutrality.
5. The Kingdom of Spain tag is suddenly gone without getting conquered.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/675a076f-01c3-4958-9a99-3b82aad4fabc)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a7bcffcd-13c1-41a7-8fa4-32023cec465e)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bc06a8db-279c-424d-873a-87e954888d29)

**Comment by runelead00** [comment]
Working as Designed, SPR lose all their states and thus died. Also we don't remove the Iberian Wars tab until the entirety of the war is over for any power as it has always worked
