### ISSUE TITLE
GER - Hermann Josef Abs is removed from political minister when selecting 'The Final Cabinet Meeting' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2811]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13432669/Logs.zip)
[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13432699/GER_play.zip) Run the game to see what happens
[GER_playthrough.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13432750/GER_playthrough.zip)

### Describe the bug

When Reichsminister Lange was replaced by Hermann Josef Abs became the new Reichsminister in 'The New Reichsminister' event, Hermann Josef Abs was somewhat removed from Reichsminister when selecting 'The Final Cabinet Meeting' event. 'The New Reichsminister' event is triggered before the 'The Final Cabinet Meeting' event pops out in my game but after reloading the save game and running the game, 'The New Reichsminister' event is somehow triggered **after** selecting the 'The Final Cabinet Meeting' event.

So, 'The New Reichsminister' event should be triggered **after** the 'The Final Cabinet Meeting' event is selected. 

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Bormann won the German Civil War.
3. The Oil Crisis.
4. Conspiracy against Fuhrer Bormann triggers.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a085ca0f-af18-47b9-86b9-feaf29166fc4)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7cb20d3d-562c-44bb-a164-2c210374c0f0)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c554235b-25e2-4a03-ab53-f9709f2c6966)

**Comment by runelead00** [comment]
Fixed in Dev Build
