### ISSUE TITLE
Sudan - Defeated pro-Italian Egypt still appeared in the 'Foreign Claims' and didn't remove them after Egyptian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2812]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_playthrough.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13432928/GER_playthrough.zip)

### Describe the bug

After the Egyptian Civil War, the defeated pro-Italian Egypt still appeared in the 'Foreign Claims' in all of Sudan (North and South Sudan) and didn't remove them.

### Steps to reproduce / Cause of the issue

1. Civil Wars in the Middle East triggers.
2. Pro-Italian Egypt was defeated by Pan-Arabist Egypt and Islamist Egypt.

### Expected behaviour

Forgot to remove them, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9c28bf58-3707-42c1-9008-ac5c92710faf)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e406ee94-35ca-4a49-a700-15c873879fc7)

**Comment by runelead00** [comment]
Fixed in Dev Build
