### ISSUE TITLE
ITA - Still has the 'Military Advisors' national spirit to sent volunteers to Italian interests in the Middle East despite the Middle Eastern Civil Wars is over

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2813]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_playthrough.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13433102/GER_playthrough.zip)

### Describe the bug

After the Middle Eastern Civil Wars, Italy still had the 'Military Advisors' national spirit to send volunteers to pro-Italian Middle Eastern and didn't remove it. 

### Steps to reproduce / Cause of the issue

1. The Civil Wars in the Middle East triggers.
2. Italy has sent volunteers national spirit to support pro-Italian Middle Easterns.
3. End of the Civil Wars in the Middle East.
4. Italy still has the 'Military Advisors' national spirit.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4abcd26c-afc6-4e3a-adf7-cea2b9dee4ab)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/77dde7d1-4e67-4b97-a64d-0d3f1d664d52)

**Comment by runelead00** [comment]
Fixed in Dev Build
