### ISSUE TITLE
USA - Sending volunteers to Democratic Republic of Iran in Military Advisors national spirit didn't remove after the end of the Iranian Civil War

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2815]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_playthrough.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13433177/GER_playthrough.zip)

### Describe the bug

After the Imperial State of Iran defeated and capitulated the leader of the Iranian Revolutionary Front, the Islamic Republic of Iran and the rest are annexed by pro-German Iran without capitulating, and end of the Iranian Civil War, USA still has a sending volunteers to Democratic Republic of Iran in Military Advisors national spirit and didn't remove. 

### Steps to reproduce / Cause of the issue

1. The Iranian Civil War triggers.
2. Imperial State of Iran defeated and capitulated the leader of the Iranian Revolutionary Front, the Islamic Republic of Iran.
3. Democratic Republic of Iran, Shadom of Iran, and Baluchi Liberation Front are also annexed by Imperial State of Iran.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/5f90adbb-0b1f-4802-a170-ff0a9beee415)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/35bcf2a6-04a4-4656-aae1-7cc2d7686dc1)

**Comment by runelead00** [comment]
Fixed in Dev Build
