### ISSUE TITLE
GER - 'The Attempted Coup' event shows to remove the 'Schorner's OKW' national spirit but the 'Schorner's OKW' national spirit is already removed

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2816]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_the_attempt_coup.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13434208/GER_the_attempt_coup.zip)

### Describe the bug

'The Attempted Coup' event shows that the 'Schorner's OKW' national spirit will be removed when clicking the event but the 'Schorner's OKW' national spirit was already removed before the Oil Crisis. So, 'The Attempted Coup' event should have `if` code that if 'Schorner's OKW' national spirit is exists, it should be removed.

### Steps to reproduce / Cause of the issue

1. Play as Germany.
2. Bormann won the German Civil War.
3. Choose Schorner as the OKW.
4. Proceed to phase 2.
5. Complete the 'Sweeping the Dregs' focus trees.
6. The 'Schorner's OKW' national spirit was removed.
7. The Oil Crisis triggers.
8. Conspiracy against Bormann triggers.
9. 'The Attempted Coup' event triggers.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/20991094-421b-432d-8d5f-d7cc1713d140)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/197f2961-ea7f-4a97-8b27-c08a2dc02129)

**Comment by runelead00** [comment]
Fixed in Dev Build
