### ISSUE TITLE
GER - Missing "m" for "militarist" word in 'The Calm After the Storm' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2817]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. There is a missing "m" for the "militarist" word in 'The Calm After the Storm' event.
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/36e7a968-fa8e-4885-b6d1-2e1122a2ad25)

**Comment by runelead00** [comment]
Fixed in Dev Build
