### ISSUE TITLE
ICE/FAR - Goldwater's OFN 'Military Spending Focus' and 'OFN Tariffs Abolished' national spirits are still exist and didn't remove

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2819]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13435750/GER_play.zip)

### Describe the bug

After Iceland and Faroe Islands left the OFN faction, they still had the Goldwater's OFN 'Military Spending Focus' and 'OFN Tariffs Abolished' national spirits and didn't remove them.

### Steps to reproduce / Cause of the issue

1. Barry Goldwater won the 1968 election.
2. USA choose Morton's Plan.
3. Icelandic Crisis triggers.
4. 1971 Icelandic general election.
5. Anti-OFN won.
6. Iceland and Faroe Islands

### Expected behaviour

Forgot to remove them when not in faction, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a5a53928-ecb8-41c9-9f7f-2ab3a0c87e19)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fd848956-6a4f-48c1-8421-451267838e7b)

**Comment by runelead00** [comment]
Fixed in Dev Build
