### ISSUE TITLE
Amur cannot take a repopulation decision in the third phase

### ISSUE THREAD

**Issue by spermenk** [TNODevs/TNO-Bug-Tracker#282]
![obrázok](https://user-images.githubusercontent.com/44478254/143067380-a2b6ab83-d629-42a0-8a05-049e36796248.png)
Amur's "All-Russian Repatriation Program" decision requires a focus from the second phase of the game, which, even if completed, makes the decision impossible to take in the third phase after switching to the final focus tree.

**Comment by runelead00** [comment]
Fixed on UB
