### ISSUE TITLE
USA/OFN - Potentially OFN members should have gain 'Military Spending Focus' and 'OFN Tariffs Abolished' national spirits

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2820]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the potential OFN members should gain Goldwater's 'Military Spending Focus' and 'OFN Tariffs Abolished' national spirits.

### Justifications

When a potential tag joins the OFN, a tag doesn't receive Goldwater's 'Military Spending Focus' and 'OFN Tariffs Abolished' national spirits while other OFN members have. Because, only current OFN members will receive the 'Military Spending Focus' and 'OFN Tariffs Abolished' national spirits, not including the potential members when Goldwater completes 'The OFN System' and 'Tariff-Free OFN' focuses. So, that is why I suggest this that the potential OFN members should receive the Goldwater's OFN national spirits.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6a4dae6a-0a66-452c-a357-5ff9dfdae692)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/28e47920-a973-47f9-9931-e0218ddc3ba0)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/214da160-f42d-4d4e-9a39-aadf8c733bac)

**Comment by runelead00** [comment]
We're not going through all code to add checks to add couple of ideas every time a new faction member joins the OFN
