### ISSUE TITLE
GNA - Puppet Portugal still able to declare war on three Iberian separatists despite being puppet

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2821]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13438032/Logs.zip)
[GER_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13438035/GER_game.zip) Run the game to what happens

### Describe the bug

Puppet GNA (Portugal) still declares war on the separatists and remaining Spanish factions despite being a puppet.

Puppet GNA shouldn't declares war on Spanish states. 

### Steps to reproduce / Cause of the issue

1. The Iberian Wars triggers.
2. GNA becomes a puppet of the Spain faction.
3. GNA defeated Portugal and won the Portuguese Civil War.
4. GNA declared war on Spanish factions and separatists.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0a11ebe8-b6aa-446c-aac4-81176bad8d4f)

**Comment by runelead00** [comment]
Fixed in Dev Build
