### ISSUE TITLE
GER - 'Completion of the Breitspurbahn' event doesn't include Dagestan and add level 3 railway from Kuban to Baku

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2822]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13438506/GER_play.zip)

### Describe the bug

After selecting the 'Completion of the Breitspurbahn' event, the event doesn't include Dagestan to gain maximum infrastructure and the railways from Kuban to Baku are not gaining or adding level 3.

### Steps to reproduce / Cause of the issue

1. Play as Bormann's Germany.
2. GroBraum Kontinentaleuropa created.
3. Begin the Breitspurbahn.
4. 'Completion of the Breitspurbahn' event.

### Expected behaviour

Forgot to add something, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e55be983-6b81-4056-9c81-d5d981f813ec)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/51ba1d1d-0a55-4746-bc20-80a2bc61b190)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6b74912a-6170-4fea-9c30-a6934848621a)
![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6bbf8847-ae97-45d6-af50-77514aeec1f2)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
