### ISSUE TITLE
GER - 'The Breitspurbahn: Inauguration of the Rostow-Paulusburg Line' event didn't include Paulusburg state to gain max infrastructure

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2823]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13438838/GER_play.zip)

### Describe the bug

When selecting the 'The Breitspurbahn: Inauguration of the Rostow-Paulusburg Line' event, the event didn't include Paulusburg state to gain max infrastructure while the Paulusbur-Stadt state has max infrastructure. 

### Steps to reproduce / Cause of the issue

1. Play as Bormann's Germany.
2. GroBraum Kontinentaleuropa created.
3. Begin the Breitspurbahn.
4. 'The Breitspurbahn: Inauguration of the Rostow-Paulusburg Line' event.

### Expected behaviour

Forgot to add something, I think.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a5de2221-ea4e-41b2-937a-80620bec9a1c)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b00807a7-6d96-4050-962b-5b80c75e93d3)
![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a971d036-cdca-4a23-8561-358ec6a63469)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
