### ISSUE TITLE
UTL - Hayit or Korşirmat's Turkestan Legion change its flag to Kayyum's flag when reunites Turkestan under the Legion control

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2824]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13439150/GER_play.zip)

### Describe the GFX issue

When either Hayit or Korşirmat's Turkestan Legion reunites the Turkestan nation due to the German victory in Turkes Kenes, UTL flag somehow changes its flag to Kayyum's flag instead of Hayit or Korşirmat's flag to remain. 

### Steps to reproduce / Cause of the issue

1. Turkes Kenes triggers.
2. German won the Turkes Kenes.
3. The Legions invaded the rest of the Central Asia nations (except Kazakhstan).
4. The Legion reunites Turkestan.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a5d42a38-c5eb-46e2-a327-f639b107296a)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8658f729-a43f-4d4f-865d-289b33fb01ae)

**Comment by runelead00** [comment]
Fixed in Dev Build
