### ISSUE TITLE
SPS/GNS/POR - They're not receive the Pakt Observer faction status when the Iberian Wars ended in Spain

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2828]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_playthrough.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13444799/GER_playthrough.zip)
[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13444800/logs.zip)

### Describe the bug

When the Falangist Spain won the Iberian Wars in Spain, the Spanish State and its puppet, Portugal didn't receive the Pakt Observer faction status. 

### Steps to reproduce / Cause of the issue

1. The Iberian Wars triggered.
2. Portugal became a puppet of Falangist Spain.
3. Falangist Spain won the Iberian Wars in Spain (Second Spanish Civil War).

### Expected behaviour

Forgot to add faction observer.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6e60b8e7-2392-484f-a9b4-580be2c72be1)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d38ee435-f4b1-47b8-9306-51485f21d6b8)

**Comment by runelead00** [comment]
Fixed in Dev Build
