### ISSUE TITLE
IBR/SPS/FSR - Allow them to retake Gibraltar by declaring war on Gibraltar Protectorate through decision or event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2829]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest the Iberian Federal Government, Falangist Spain and National Redemption Front should be able to declare war on the Gibraltar Protectorate through decision or event after dealing with other Spanish factions and separatists in order to retake Gibraltar.

### Justifications

Becuase, Gibraltar Protectorate is part of Spain or the Iberian Federation and it has claimed territories by IBR, SPS and FSR. So, that is why  suggest this.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d22c72ce-4d2e-4f70-9c9d-93c93cf9ac74)

**Comment by runelead00** [comment]
We aaren't adding new content to the Iberian Wars till their facelift is finished
