### ISSUE TITLE
UTL - They receive the Mitstreiter faction status instead of Bündnispartner faction status when Turkestan joins the Pakt

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2831]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Turkestan Legion joins the Pakt after defeating the remaining Central Asia nations (except for Kazakhstan), Turkestan receives the Mitstreiter faction status instead of Bündnispartner because the Mitstreiter talks about the European unity and prosperity under the Einheitspakt while Turkestan is not in Europe. 

### Steps to reproduce / Cause of the issue

1. Turkes Kenes triggers.
2. German won the Turkes Kenes.
3. The Legions invaded the rest of the Central Asia nations (except Kazakhstan).
4. The Legion reunites Turkestan.
5. Turkestan joins the Pakt.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/25ddb093-22c8-42dc-977f-77fbc682823c)

**Comment by Fortune801** [comment]
WAD - Bundnispartner makes less sense than Mistreiter
