### ISSUE TITLE
USA - Wallace epilogue events out of order

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2834]
### Operating System

Windows 10 Home

### HOI4 version

Stella Polaris v.1.13.5

### TNO version

The Ruin 1.5.0b

### Do you have other mods in use?

TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Describe the bug

The epilogue event chain for George Wallace (for both impeachment and lost election endings) is out of order. For the former, it actually triggers an event that’s supposed to be for the “lost election” epilogue. Both chains are also missing a second event and end up skipping to their last chapter.

### Steps to reproduce / Cause of the issue

Cause of the issue:
    1. Open “TNO_America.txt” under Events
    2. Scroll down to `USA.epilogue.1` (line 22281) and `USA.epilogue.4` (line 22332)
    3. Change the effects of the event to fire the epilogues in proper order

### Expected behaviour

George Wallace's epilogue should have triggered three events as with other president, not only two events.

### Screenshots

![Screen_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/ff0ebd5e-8c41-4e7e-8151-e123414b3f45)
![Screen_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/7a72fcc7-41a2-4965-9eef-099c05c2a93b)

**Comment by runelead00** [comment]
Fixed in Dev Build
