### ISSUE TITLE
USA - There are no Enrichment Plants in place when starting at the beginning of the game

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2836]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as USA at the start of the game, USA has no at least one or few Enrichment Plants while Japan has 2 and Germany has many Enrichment Plants despite USA having 2nd largest warheads. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. USA has no at least one or few Enrichment Plants.
3. Japan has 2 and Germany has many Enrichment Plants.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8a42c591-b8f0-449c-bbaf-b2d57528261f)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/575d3c48-3148-497d-a5a7-b6a6b90d2f17)

**Comment by runelead00** [comment]
Fixed in Dev Build
