### ISSUE TITLE
USA - The description of North America from the intelligence tab says to including influence in Mexico but Mexico is not marked blue for North America

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2837]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In the description of North America from the intelligence tab says to include influence in Mexico. Still, Mexico is not marked blue for North America or part of North America but instead part of Central America in the intelligence GFX map.
[ ] ![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/12d0c1ec-45f3-4803-849b-5f0414d8e97f)

**Comment by Fortune801** [comment]
Fixed on dev build
