### ISSUE TITLE
NOR/GER - Germany always keep Port of Norway even Heydrich wins German Civil war, collapses and becomes wasteland finally

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2838]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

![G{BE$_Q6AHTENGHS0JG1~{5](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/e62e72a8-5c0d-4cdb-bf48-6dfe7ae83042)

### Describe the bug

such as title

### Steps to reproduce / Cause of the issue

Here's way to fix
just add a effect in event HGR.204 (Heydrich Germany collapses officially), transfer state 94(Norway's port state) to NOR
This is very easy to solve

### Expected behaviour

The port will be free, and no longer go wasteland with Heydrich

**Comment by Fortune801** [comment]
Fixed on Dev Build
