### ISSUE TITLE
Bormann's Germany - Focus not increasing credit rating

### ISSUE THREAD

**Issue by originalperson0** [TNODevs/TNO-Bug-Tracker#284]
**Questions**

- Operating System: win 10
- HOI4 Version: latest
- TNO Version: latest
- Any other mods in use: no
- Were you using Steam? yea
- Which expansions do you NOT have? i have all of them

**Longer Description of Issue:**
the focus "let the money flow" says it increases your credit rating when it doesnt do anything
**Steps to Reproduce/Cause Issue:**

1.
play bormann and win
2.
complete focus 
3. no increase to credit rating

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Current Release
