### ISSUE TITLE
USA - AI doesn't select most of the intelligence operations

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2840]
### Operating System

Windows 10 Pro

### HOI4 version

1.12.14

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

AI USA doesn't seem to select most of the intelligence operations like supporting Polish and Serbian rebels before Hitler's death, Strengthening the pro-American sentiment and Increasing Trade Relationships in Central and South America, some operations in Southeast Asia, Africa and Europe and other operations. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tags except USA.
2. Play through 1970.
3. Switch to USA tag through the console.

### Expected behaviour

I don't know. Forgot to add AI variables.

**Comment by runelead00** [comment]
Working as Designed, AI for CIA missions the AI will do is decided at game start
