### ISSUE TITLE
USA/Fiscal Crisis/Mex - Some small code mistakes from file

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2842]
### Operating System

1.13.4

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

1.
![F5X40S0{LA%{(NIY`CEMG@P(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/fbfb749e-e1de-4237-9b77-61dcb470ddcd)
2.
![9PKC00 Q{$L87J}POD)G)XF(2)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/81b30766-fb11-4c67-924c-fb065f0eab90)
3.Mexico just copy and paste code from USA, ik Mexico is unplayable, but shouldn't we fix title and desc to Mex.[number] for better program in future...?
![Q5IK3OD%VQJ`T EDANM(T92(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/667a1022-04c9-45dc-a168-b29bf953cf2a)

### Steps to reproduce / Cause of the issue

Here's location of file
1. TNO - common - decisions - **Fiscal_Crisis_decisions**
2. TNO - events - **TNO_America_RDC**
3. TNO - events - **TNO_Mexico_sleletons**

### Expected behaviour

F1x

**Comment by MrStraws114514** [comment]
2. 
![9PKC00 Q{$L87J}POD)G)XF(2)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/c1363ccf-43e9-4c09-9052-b3a56f870894)

**Comment by MrStraws114514** [comment]
3.
![Q5IK3OD%VQJ`T EDANM(T92(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/667d9cab-9ba2-46b3-bbb5-170c3d3e07d4)

**Comment by runelead00** [comment]
None of these affect the actual function of the code
