### ISSUE TITLE
USA - Operation Homestead is required 'Break Open the Caches' focus to be completed instead of 'Helping Out a Friend' focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2843]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I looked at the `USA_CIA_Increase_OFN_England_Relations` operation requirement, it required to have the 'Break Open the Caches' focus to be completed instead of the 'Helping Out a Friend' focus because 'Helping Out a Friend' is about improved relationships with the HMMLR and the `USA_Break_Open_The_Caches` should be replaced with `USA_Helping_Out_A_Friend` operation requirement.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Enable the old Britian content.
3. See the code requirements for Operation Homestead.

### Expected behaviour

Oversight, maybe. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3c38c180-9746-492f-b22a-8ffbca2e43e9)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/eb0ae266-b8b0-42f1-a99e-f4f92bb1560c)

**Comment by runelead00** [comment]
Fixed in Dev Build
