### ISSUE TITLE
ZOM - Some text is not displayed due to code errors and only exists in localisation files 

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2844]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![M %V(}JH4{VPT`QYP4@US19](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/33469eab-236b-4f14-bbcf-5963ebc10088)

![BO@`IID6YMO) IWKVN{B6DO](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/1dadb698-ce54-4adf-9693-46f2b7dcc4df)

![TW2${62`1 IU2 SBWP517I0](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/6ac19d18-af02-4167-81ef-74110e65aaec)

### Describe the bug

The screenshots i updated are texts only show in localization because of bugs

### Steps to reproduce / Cause of the issue

1.There is no buff named BRG_Rodomo_Virus in game, only ZOM_Romodo_Virus, please rename localization file
2. same reason like 1
3.There is no Anti_Zombie_Weaponry_6 buff in game, it stops at level 5

### Expected behaviour

F1x pls

### Additional information

By the way, i think zombie Gorbbels is more like national socialism or ultranationalism in ideology..

**Comment by runelead00** [comment]
Fixed in Dev Build
