### ISSUE TITLE
USA - Change the focus effects of 'Helping Out a Friend' for the new Britain content

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2845]
### HOI4 version

1.13.5

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the 'Helping Out a Friend' focus' effects should be changed when the old Britain content is disabled.

### Justifications

When the old Britain content is turned off and playing with the new Britain content, the 'Helping Out a Friend' focus still has the old Britian content effects. So, that is why I suggest about the changing focus effect of 'Helping Out a Friend' for the new Britain content. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/27266d03-c0c9-443b-a3a8-f7afe5f2ade4)

**Comment by Fortune801** [comment]
addressed on dev build
