### ISSUE TITLE
DOM - No political party name added for Liberal Conservatism

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#2849]
### Operating System

Windows 10 Pro

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13466891/Logs.zip)

### Describe the bug

When Bonnelly took over in the Dominican Republic after the Legion's victory in the Dominican Civil War, Liberal Conservatism had no political party name.

### Steps to reproduce / Cause of the issue

1. Trujillo was overthrown in the Dominican Republic during PPI.
2. The Legion won the Dominican Civil War.
3. The Legion unity collapsed.
4. Purge of the Legion's Socialists.
5. Bonnelly takes over in the Dominican Republic.

### Expected behaviour

Forgot to adding loc, I think

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/557d3821-7c21-4ee9-9a9e-d0a783dbaa39)

**Comment by runelead00** [comment]
Fixed in Dev Build
