### ISSUE TITLE
PHI - The values of the national spirit are seriously wrong

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#2850]
### Operating System

Windows 10

### HOI4 version

V1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The value of the national spirit is wrong, the normal is 0.75
![4ff74b821b9c54af8c9edd7e6218b1e1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/e87d5c90-8b33-4240-a8a8-6bc007d59419)

### Steps to reproduce / Cause of the issue

See picture above

### Expected behaviour

Become 0.75

**Comment by Fortune801** [comment]
Fixed on dev build
