### ISSUE TITLE
As Burgundy i cannot do focus 'Our Germanic Heritage' it says i dont meet requirements (there arent any)

### ISSUE THREAD

**Issue by DaweCZ09** [TNODevs/TNO-Bug-Tracker#2851]
### Operating System

Windows 11

### HOI4 version

1.13

### TNO version

idk

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

I'm in 1967 has burgundy, i went through the focus tree, until i wanted to do focus 'Our Germanic Heritage'. I cannot do the focus, it says i dont meet requirements, but there arent any requirements. i even tried using console 'focus.nochecks' but that didnt help.

### Steps to reproduce / Cause of the issue

1. Go to burgundian focus tree in early 1967
2. do all the focuses and then try to do 'our germanic heritage'

### Expected behaviour

i expected i will do the focus without any issues

**Comment by Fortune801** [comment]
Can you give me any more information?

**Comment by DaweCZ09** [comment]
> Can you give me any more information?

The problem somehow solved by disappearing of that focus and pop-up of new branch of focus tree, but thank you for reaction.

**Comment by runelead00** [comment]
Probably just a matter of focus tree updating while you had focus menu up, added effect to force reload tree, which might help
