### ISSUE TITLE
Guangdong - Product Cycle Not Ticking

### ISSUE THREAD

**Issue by MsChoo1** [TNODevs/TNO-Bug-Tracker#2852]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

1.2.1b

### Do you have other mods in use?

Last Waltz

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT

### Files

[GNG_1965_03_01_03.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13483149/GNG_1965_03_01_03.zip)

### Describe the bug

Product cycle timer not ticking down for whatever reason; been stuck on 26 days for the past six months

### Steps to reproduce / Cause of the issue

This is a pretty standard Morita Aoki Sony game for Guangdong, so all you should need to do is play through normally?

### Expected behaviour

The timer should just be ticking down.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107003909/c158d07d-1423-4f01-ac9e-d181c9b672a0)

**Comment by MsChoo1** [comment]
And now America is lead by a despotist generic portrait called "Gideon Gordon" with the economic status of "Iberian Bombing Campaign"? What the fuck happened?

**Comment by MsChoo1** [comment]
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107003909/d6683580-e996-4539-925a-1533eed2fb0e)

**Comment by Fortune801** [comment]
Did you start this game before the update and continued it after?

**Comment by MsChoo1** [comment]
No. This game was started within the past week.

**Comment by runelead00** [comment]
Issue on player end, save either corrupted or something updated mid-campaign
