### ISSUE TITLE
USA - The CIA Network Strength will not improve

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#2854]
### Operating System

Windows10

### HOI4 version

V1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The CIA Network Strength will not increase in the event, which will not reduce the success rate of German operations against the United States.
![20231128222402_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/2e2a7be4-22b6-41f8-9f9c-209f875c88a5)

### Steps to reproduce / Cause of the issue

1.Play USA
2.Use CIA operations to conduct counterintelligence operations for the region

### Expected behaviour

The CIA Network Strength will improve，reduce the success rate of German operations against the United States

**Comment by Fortune801** [comment]
WAD, this operation is meant to damage Germany's ability to operate in the region and that's what it's doing, it even states as much in the Intelligence Operation
