### ISSUE TITLE
FGB - Wrong number for national ideas "vengeance for dead"

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2856]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

![Image_1701224500505](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/cc561b84-2c7d-4f82-807b-0fd2afc2a4c6)

this code gives 75 defense against, that means it will gives FGB 7500%

### Steps to reproduce / Cause of the issue

change 75 to 0.75, then it will fix

### Expected behaviour

f1x

**Comment by runelead00** [comment]
Fixed in Dev Build
