### ISSUE TITLE
BOV(Ukrainian State) - The Country Closing Screen of Roman Shukhevych and Yaroslav Stetsko are not show

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#2858]
### Operating System

Windows10

### HOI4 version

V1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Ukrainian State defeated Poland, the Country Closing Screen of Roman Shukhevych and Yaroslav Stetsko are not show.
![20231129194027_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/d98dbff5-998d-42e9-b99b-ec2ba732722b)
![20231129195151_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/87889cff-0c75-464e-9b28-6052f25a220b)

### Steps to reproduce / Cause of the issue

1.Play Ukrainian State
2.Play Roman Shukhevych and Yaroslav Stetsko
3.Complete defeat of Poland

### Expected behaviour

The Country Closing Screen of Roman Shukhevych and Yaroslav Stetsko are show

**Comment by Fortune801** [comment]
Fixed on dev build
