### ISSUE TITLE
FFR/All nation - France Reclaimed news displays an error

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#2859]
### Operating System

Windows10

### HOI4 version

V1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

France Reclaimed news displays an error
When it comes to other non- Pakt countries such as the United States, it is not "Those magnificent bastards!" that should be shown, but one of the remaining few
![20231129204747_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/383463fa-c909-4cd6-b6b5-5c5001925eca)
![捕获40](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/7207e691-66a5-42cf-ba25-eb7a219fd726)

### Steps to reproduce / Cause of the issue

1. Play non- Pakt countries such as the United States
2. The news that triggered France Reclaimed (see above)

### Expected behaviour

France Reclaimed news displays not have an error

**Comment by runelead00** [comment]
??? have no idea what you are reporting, loc appears as it should, working as deigned

**Comment by otherside02** [comment]
> ??? have no idea what you are reporting, loc appears as it should, working as deigned

I mean, from an American perspective, this news should not end with "Those magnificent bastards!"
Should it be "The flame of French resistance could not be extinguished" or something else

**Comment by runelead00** [comment]
Those magnificent bastards! is the intended loc
