### ISSUE TITLE
Takagi Japan - wrong army reform requirements

### ISSUE THREAD

**Issue by JanKazimierz** [TNODevs/TNO-Bug-Tracker#2868]
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I got to the end of army reform as Takagi, the event said that I failed to improve military supervision even though the policy was at "watchdog groups". I believe this is because the successful reform event (jap_ar.7) doesn't account for policies other than "rules of engagement". I didn't check if the same happens for other PMs.

### Steps to reproduce / Cause of the issue

1. Play as Takagi
2. Improve military supervision policy two times (Army Rationalisation Act + military focuses)
3. Wait for Rentokuen 43

### Expected behaviour

That the event would account for more advanced policies

**Comment by runelead00** [comment]
Fixed in Dev Build
