### ISSUE TITLE
Germany, USA, Japan-global conflicts

### ISSUE THREAD

**Issue by idk90978** [TNODevs/TNO-Bug-Tracker#2871]
### Operating System

windows 10

### HOI4 version

1.13.5

### TNO version

1.5.0

### Do you have other mods in use?

Korean Language, Korean Language TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Cannot use global conflicts
If I use Korean Translation mod on TNO, I cannot use global conflicts tab. The maker of the Translation mod said that the bug is related to the main mod.
I hope it get fixed soon.

### Steps to reproduce / Cause of the issue

1. Turn on the Korean Translation mod and Korean Translation mod TNO.
2. Select the major countries(Germany, USA, Japan).
3. Go to the global conflicts tap.
4. See the bug.

### Expected behaviour

The description of global conflicts conceals the decisions so that I cannot use the decisions.

**Comment by runelead00** [comment]
could you provide a screenshot of what you mean? this seems like it's a translation issue since it isn't reported by any other foreign community, but I'm unsure of the actual issue

**Comment by runelead00** [comment]
Confirmed on my end as being caused by Korean Translation submod
