### ISSUE TITLE
Germany - Bohemia never gets annexed after the civil war ends

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#2873]
### Operating System

Windows 11

### HOI4 version

1.13.5

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13573685/game.log) (note: this is the same file I sent for the Haiti bug, but this bug happened during that run-through as well)

### Describe the bug

After the German civil war ends, Germany puppets Bohemia, but never annexes them (in this case, it happened when Bormann was chosen as Hitler's successor, and Wehrkreis XIX sided with him in the civil war, but Speer won the civil war, though after defeating Bormann, Wehrkreis XIX became a puppet of Germany and never was annexed)

### Steps to reproduce / Cause of the issue

1. Set game rules for where Bormann is chosen as Hitler's successor (since he'll almost always get Wehrkreis XIX to side with him) but Speer wins the civil war
2. Wait

### Expected behaviour

Whoever won the German civil war should annex Wehrkreis XIX after defeating whoever the latter sided with

**Comment by runelead00** [comment]
Fixed in Dev Build
