### ISSUE TITLE
Komi Suslov path - Mispelled a word

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2875]
### HOI4 version

1.13.5

### TNO version

1.5.0

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![TNO bug reporte](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/1adcf839-b4f7-4529-af55-a3d1290c7685)

The word is marked under with red

### Additional information

It should be saying explaining instead of exlaining.

**Comment by runelead00** [comment]
Fixed in Dev Build
