### ISSUE TITLE
KOM (Suslov) - Mispelled the word "fundings

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2876]
### HOI4 version

1.13.5

### TNO version

1.5.0

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![TNO bug report e](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/58877546-7f68-4568-aa04-5afe00297c45)

Mispelled word marked with red

### Additional information

The word "fundings" seems to have been mispelled as "foundings".

**Comment by runelead00** [comment]
Fixed in Dev Build
