### ISSUE TITLE
Guangdong-PTRG not working

### ISSUE THREAD

**Issue by Avemap** [TNODevs/TNO-Bug-Tracker#2879]
### Operating System

windows 10

### HOI4 version

1.13.5.7

### TNO version

1.5.0b

### Do you have other mods in use?

tno radio

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA, AAT

### Describe the bug

When playing as guangdong I am unable to progress the ptrg points, only the initial rifle testing worked, the MBT and SPA, and the helicopter are unable to progress on their testing goals

### Steps to reproduce / Cause of the issue

1. Play Guangdong
2. get involved in japanese proxy wars (colombia and indonesia at this point)
3. Send ptrg units
4. See if they progress on the tests

### Expected behaviour

For the points to complete/progress when they are followed

**Comment by runelead00** [comment]
Did you assign the unit to an army

**Comment by Avemap** [comment]
> Did you assign the unit to an army

Yes, the was sent as volunteers in an army with a general
