### ISSUE TITLE
KLT / MFP - As the puppets of AFG, they don't join AFG's economic sphere (With solution)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2880]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Afghanistan has 2 puppets, KLT and MFP
At the end of game, The coup event **AFG.12** will lead AFG to join someone's economic sphere, Turkey, Germany or Japan
However, when AFG joins, the puppets of it doesnt follow to join

### Steps to reproduce / Cause of the issue

in event AFG.12, add KLT and MFP's econ_join_sphere_XXX effect

### Expected behaviour

These 2 puppets can follow its leader to join sphere

**Comment by MrStraws114514** [comment]
The "steps to reproduce" is the way to fix, forgot to mark

**Comment by runelead00** [comment]
Fixed in Dev Build
