### ISSUE TITLE
ALL Country - a bug in the code for “contentless AI fiscal crisis prevention”(There is a solution)

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#2881]
### Operating System

Windows10

### HOI4 version

V1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

There is a bug in the code for “contentless AI fiscal crisis prevention”.This bug caused the code to never fire properly.
Original bug code：
![ae2f3447a185954be253cb8657466c8a](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/c15774c6-85ca-445a-aade-129afb790750)

### Steps to reproduce / Cause of the issue

New code after resolution：
![76b67e9b7670757ba7b008f4994e263a](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/1e176150-b5ed-4ef0-9846-99f4cf1124d2)

### Expected behaviour

The contentless AI fiscal crisis prevention code is working properly.

**Comment by MrStraws114514** [comment]
add: The event ID is Fiscal_crisis.0

**Comment by MrStraws114514** [comment]
improved version?
fix the resolution above sometimes doesnt work, and no content country will gonna have a weaken version fiscal crisis(for cosmetic)
[11.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/13617548/11.txt)

**Comment by runelead00** [comment]
the code fires perfectly fine, you don't understand how the code works

**Comment by MrStraws114514** [comment]
> the code fires perfectly fine, you don't understand how the code works

pardon, I just realized a small problem
the 1st option "is_ai=no and TNO_has_content=yes"I
this probably asks both of them, but I saw a lot of times that AI fires fiscal crisis(only for playable countries), I am sure the 1st option's limit is correctly working
the 2nd option is supposed to use for AI, but it has no ai_factor, this might lead ai to 1st option
i think 2nd option needs a ai_factor, this can fix
