### ISSUE TITLE
UKS - "The Revolutionary Will"GUI is disappear

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#2883]
### Operating System

Windows10

### HOI4 version

V1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

"The Revolutionary Will"GUI is disappear. I remember in the v1.5.0a, this GUI existed
![20231212203914_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/5b29381a-77d3-436c-aea2-33e4c698261b)

This is what the GUI looks like
![捕获58](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/558cb5f7-b780-47ce-8879-a4ebc77ca56e)

### Steps to reproduce / Cause of the issue

1.Play UkrainianSSR
2.View the decision,"The Revolutionary Will"GUI is disappear

### Expected behaviour

"The Revolutionary Will"GUI is appear

### Additional information

Also, I want you to deal with these bugs. A lot of players have been asking questions about this and want you to deal with it.

1.https://github.com/TNODevs/TNO-Bug-Tracker/issues/2607
2.https://github.com/TNODevs/TNO-Bug-Tracker/issues/2857
3.https://github.com/TNODevs/TNO-Bug-Tracker/issues/2865
4.https://github.com/TNODevs/TNO-Bug-Tracker/issues/2867
5.https://github.com/TNODevs/TNO-Bug-Tracker/issues/2869

**Comment by runelead00** [comment]
Fixed in Dev Build
