### ISSUE TITLE
Any Country That Can Lead an Economic Sphere - GAW Rework

### ISSUE THREAD

**Issue by ThePikminCaptain** [TNODevs/TNO-Bug-Tracker#2885]
### HOI4 version

1.13

### TNO version

1.50b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Add a game rule for who wins the WI + GAW and one to force the legitimacy of Long Yun if he wins
Make it so when Yun coups his brother, the US and Germany can send aid with a strike system, getting caught results in superpower tensions increasing slightly, when the GAW starts, Other Sphere leaders (Brazil Argentina Turkey Iberia Italy) can send support to one side, Russian Unifers can send aid to the NPA. If the NPA wins and has high legitimacy, a Battle for China starts where the Us and Germany attempt to woo China into their faction, whoever had more factionalism in their support start with an advantage. Meanwhile japan will attempt to keep them neutral, if the WRRF is doing well, they can join the fun as well, whoever wins has China join their faction and economic sphere, otherwise China becomes neutral, also speaking of, make an option to force who could win in this Battle for China

### Justifications

It gives the USA and Germany a reason to support the NPA besides effectively removing japan’s superpower status

**Comment by runelead00** [comment]
No, as we have repeatably stated, we are not turning NPA into a proxy for a variety of reason and the other superpowers have no way to supply the NPA. We also do not add gamerules for player only outcomes
