### ISSUE TITLE
West India and East India - Renewed Indian Civil War

### ISSUE THREAD

**Issue by ThePikminCaptain** [TNODevs/TNO-Bug-Tracker#2886]
### HOI4 version

1.13.5

### TNO version

1.50b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

USA Japan Proxy Conflict
To Start, Have west India be able to join the ofn when Nixon improves relations with them, when chaos enters both India’s, both can either peacefully work a solution (Battle for India) or go to war, 

### Justifications

Because India is boring as of now

**Comment by ThePikminCaptain** [comment]
To Add, whoever reunites India can go to war with Afghanistan, if they win they puppet Afghanistan and retake lost land

**Comment by runelead00** [comment]
We're not going to a proxy based on a suggestion, India will get skeleton content when it has a skeleton content designed.
