### ISSUE TITLE
GER - Militärverwaltung der Britischen Inseln still exists

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2887]
### Operating System

Windows 11

### HOI4 version

1.13.5

### TNO version

1.5.0 "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Militärverwaltung der Britischen Inseln starts as Germany's puppet, even though it doesn't own any land. And it continues to be your puppet after the civil war. (Probably because you tag switch back to Germany, and it doesn't stop being a German puppet)

### Steps to reproduce / Cause of the issue

To reproduce the issue
1. Play Germany
2. Click on "Manage Subjects"

### Expected behaviour

Militärverwaltung der Britischen Inseln won't exist

### Screenshots

![tno bugger reporter](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/292ddd53-73fd-43e7-93a7-a7ca66a45074)

![tnio burg report](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/53aa0a91-14b6-4491-8b8d-7d9200835882)

**Comment by runelead00** [comment]
Fixed in Dev Build
