### ISSUE TITLE
GER - Mispelled word

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2888]
### HOI4 version

1.13.5

### TNO version

1.5.0 "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Word is underlined with red.

![tno bugger reppoort](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/a5e38320-8e0d-4e8e-acf0-fc7e6d7a6dd7)

You get the event from the following two focusses:

![tno bug reporter](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/ad447234-d035-4d5e-a553-a30c2f5a9d11)

### Additional information

It should be saying "of" instead of "if".

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
