### ISSUE TITLE
GER (Speer) - Small typo in event

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2889]
### HOI4 version

1.13.5

### TNO version

1.5.0 "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Word marked with red.

![tno bug rpot](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/790edcb2-d3bc-4988-8472-ed3975f3c91d)

### Additional information

It should be saying "men" instead of "man", as it references to the men who were slain in World War 2 or the 1. West Russian War.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
