### ISSUE TITLE
Japan - Can sabotage their own allies in Angola

### ISSUE THREAD

**Issue by indexoquarto** [TNODevs/TNO-Bug-Tracker#289]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest before NSB
- TNO Version: 1.2.0c
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? All

**Longer Description of Issue:**
In the Angolan Civil war, Japan can take a decision that gives negative modifiers for its own allies

**Steps to Reproduce/Cause Issue:**

1. In the Angolan Civil War, take the decision "Japanese Sabotage Effort" as Japan

**Screenshots:**

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
