### ISSUE TITLE
Economy System - AI states GDP overflow when reach 32-bit limit(with solution)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2890]
### Operating System

Windows 11

### HOI4 version

1.13.4

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

when any countries controlled by AI, the state GDP reaches the 32-bit integer limit(214.7483647B), it will go bug in the  monthly counting and then become minimum state GDP - $25 per capita
![QG@HW@IWR_Y`}N8LOWI WO5_edit_7766315399855](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/032cc25b-b927-4e92-be04-36c396af562c)

![{~@S}QH`~X98E9{L1{K8GGD_edit_7770503911312](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/363857cc-948b-48f8-897d-379446bf492a)

### Steps to reproduce / Cause of the issue

Add a state GDP ceiling of 214,748
That would stop the state's GDP from growing once it reaches 214B, but at least better than getting nuked
![K%@Z2$EOJ`C@XVEV(7)EZ}S](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/1988693f-2e59-4535-bc16-061e5d364da2)

### Expected behaviour

AI states GDP no longer get nuked when reaches 214B

### Additional information

**The limit code must be in front of the economic calculation part!!**
some events and decisions in-game directly increases state GDP, that'll make GDP operate beyond the 32-bit integer limit, this means that state GDP would be calculated at a rate higher than 214b
To solve the situation like this, the state GDP limit must work before the economic code is calculated, or it'll still go overflow

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
