### ISSUE TITLE
Central Asia - Code bugs collection

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2891]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

1.
![EXG _S`FS%(J` MTA{B0K7Q(1)_edit_6422373089123](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/40790956-527e-4392-9cfa-d4c0be92217c)

In this event, Turkestan wins and TRK just start solving other nations in central asia
but at the same time, it **immediately** check if KYR and TAJ and exists?
that means if TRK declare war on either of them, it needs to defeat them in 0 hours
also, TRK doesnt get core from TAJ, KYR and UTL

2.when Japan wins and bomb TRK and UZB, TRK's cosmetic tag will be wasteland and UZB get annexed by TRK, but TRK doesnt get UZB's core

### Steps to reproduce / Cause of the issue

Here's location of event
1.CA_TK_skeleton.33
2.CA_TK_skeleton.28

### Expected behaviour

These 2 bugs can be fixed

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
