### ISSUE TITLE
BRG - When RPY wins Burgundy Civil war and get annexed by France, state culture is still Burgundy(With Solution)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2892]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Such as title
![8P``}J97T2Z07_K~WUI L{P](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/2b1e7a55-6f1c-4ff6-88f7-1f56459ef451)

### Steps to reproduce / Cause of the issue

Here's way to fix
![FVJJC7~OYW5_J6%M)SA3%VV](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/f7e31ca6-3309-4432-9c7b-fa760c937e26)

add this part of code, it changes state culture and remove Nord-Paris victory point

### Expected behaviour

Culture can change correctly

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
