### ISSUE TITLE
GER/JAP/USA - Strange and not united ports mode

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2893]
### Operating System

Windows 11

### HOI4 version

1.5.0b

### TNO version

None

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Here's JAP's port mode
It has 6 ports, 2 from CHI, 2 from MAN, 2 from USA, all of them are Occupied states(has resistance and compliance)

![741Q385%M O{@HFT8P`ZNF1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/4255dc34-daa4-40c3-9e42-7954d97a4f28)

![O0I2%V7 UR9` W86 06AL_J](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/73b23032-e5d4-4116-ae08-a4ce9fdbdcf4)
Here's USA's ports mode
![WIB8R6APU H OP( 8{ J8K](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/8a842102-ba74-4b0d-9faf-d47d3612593d)

![B88YQ @ XXC@@VR2R4MV`OK](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/d80800c0-846d-4d1f-a9e5-efecc839c2a9)

![4QX@%TOE(~B5NY(3MV)X U](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/2f456dbd-d4a7-4489-91b3-6001bb4f5d5d)

USA has a port from CUB, a channel from PAN, captures Puerto Rico and Greenlands
But strangely, PAN channel is colony states(no resistance and compliance) so does Puerto Rico
but in fact no states are usually defined as "colony states" in game, except those that are small islands that are uninhabited, but Puerto Rico has 2.5M population in 1962,i dont think its uninhabited

Here's GER's port

![4OI~BPOGC_@EOJ0U(XO0TI](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/fc1e193d-1ca2-4d2e-ad6b-608bc0aa9846)
%A2KV`_46Q])

![J92_%MLN{_SAS@XU9~BXJ0O](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/23ef1568-4250-4e19-8beb-5ef5e12a89c1)
It captures 2 islands from DEN and ENG, they are Occupied states, but it also got port from NOR, and **this is core?**
I dont think this makes sense, core means legal territory and mainland, yes, this port becomes German mainland
Even if the port had no resistance, I don't think it could be defined as a core, because different with Crimea, Germany didn't intend to make it part of the Reich

### Steps to reproduce / Cause of the issue

in history/states
It's code has no problem, but looks weird, i think this is a logical bug

### Expected behaviour

Unite these port states to be a same mode

**Comment by Marok132** [comment]
As far as I know Nordstern is not just a port. It's a colonized land like Crimea and it's a legal part of Reich. Check the culture in this state.

**Comment by runelead00** [comment]
Some of these are being changed with map-rework but most of intentional
