### ISSUE TITLE
CHI - AI Economy protection system not working correctly (with solution)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2894]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

in event CHI.3, system will test if China is controlled by AI
If yes, then fire event **CHI.10001** to protect AI's economy, and this event keeps firing itself to run
![A)D6YT4G63K}BJIWB5HCT3H](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/62f9f8ae-4c6a-4e5b-b5d0-bfbd1c879190)
However, this code has a problem
It created 2 options, 1st has effect, 2nd no, and it didnt add any AI_factor
that means, AI gonna see 2 options, and once it choose the 2nd one at any time, THIS PROTECTION SYSTEM GONNA STOP WORKING FOREVER

### Steps to reproduce / Cause of the issue

Here's way to fix
remove the 2nd option, it doesnt even needs to exist

### Expected behaviour

None

### Additional information

In fact, I personally recommend add a "date < 1970.1.1" limit, let it auto stop in 1970s
CHI's decisions are already too powerful, if we let this system work forever, this might make AI to be god of world

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
