### ISSUE TITLE
About your official Twitter (X)

### ISSUE THREAD

**Issue by sat0510** [TNODevs/TNO-Bug-Tracker#2895]
### HOI4 version

Not in game

### TNO version

Not in game

### Describe your suggestion

Why your official Twitter's Japanese moderator uses it for private use? He or she sent reply to the Japanese musician and this is like to scream. Please do not use the account for private use.

### Justifications

Official account should not be used for private use.

### Screenshots

![IMG_6885](https://github.com/TNODevs/TNO-Bug-Tracker/assets/91327260/bcf43785-be02-4472-b6e1-bbc0356eb339)

**Comment by runelead00** [comment]
This is not the proper channel to complain about the TNO twitter account
