### ISSUE TITLE
GER Speer - Small typo

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2898]
### HOI4 version

1.13.5

### TNO version

1.5.0 "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Typo marked with red

![tno buuug report](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/1c29dd8f-cc38-4562-825b-6b1a7cd62417)

### Additional information

Should be saying "a" instead of "an".

**Comment by runelead00** [comment]
Fixed in Dev Build
