### ISSUE TITLE
GER Speer (Go4) - Repeats word "our" in focus

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2899]
### HOI4 version

1.13.6

### TNO version

1.5.0 "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Issue underlined with red

![tno burg report](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/dde0b239-aff1-439f-9fde-4f271b760b74)

### Additional information

Should probably just be saying "our" one time.

**Comment by runelead00** [comment]
Fixed in Dev Build
