### ISSUE TITLE
unemployment value inaccurate ~ Policy cost per Capita inaccurate for Universal Basic Income

### ISSUE THREAD

**Issue by TrueRedBaron** [TNODevs/TNO-Bug-Tracker#290]
Policy cost per Capita for unemployment is 1000$ for Universal Basic Income, which means unemployment becomes incredibly large. Suggest lowering it to 150$ or 100$ to be in line with other unemployment policies.

**Comment by fedacking** [comment]
This is by design, as Universal Basic Income is represented as it was in real life proposed by mc govern.
