### ISSUE TITLE
Chinese Culture - Sichuanese and Xinan cultures have the same logo

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2900]
### HOI4 version

1.13.6

### TNO version

1.5.0 "The Ruin"

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I suggest the two cultures not having the same logo.

### Justifications

I believe this to be an oversight from the developers, though maybe theres a reason for this. However with all other cultures, logos aren't duplicates.

### Screenshots

Xinan cultured province:

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/8713f80c-228b-4ba3-8570-7094470ed34d)

Sichuanese cultured province:
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/0cb54c79-93d1-42c9-b22c-f0ef90c95fc6)

**Comment by runelead00** [comment]
Fixed for future Chinese state overhaul
