### ISSUE TITLE
USA - Typos in LBJ event

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#2901]
### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/569eba55-30bc-45cd-904a-30eb9abd1ddf)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/727e4de3-ea71-4fb8-883a-e0eb418d7694)

**Comment by runelead00** [comment]
Fixed habe typo in dev build
