### ISSUE TITLE
IRK - Typo in national spirit

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2903]
### HOI4 version

1.13.6

### TNO version

1.5.0b "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Typo underlined with red

![tno boog repooot](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/300db8c0-cf84-4e23-b782-cf34f9f6b0f6)

You get the national spirit from this focus (marked with red)

![tnio boog repooot](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/ddaa033d-dcca-4bae-aa25-68d1dcef58de)

### Additional information

It should be saying "campaign" instead of "campaigna".

**Comment by runelead00** [comment]
Fixed in Dev Build
