### ISSUE TITLE
All Countries - 3 kinds of Missiles not working(with solution!)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2904]
### Operating System

windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

SRBM, MRBM, ICBM
These 3 Missiles cant be displayed, can't work in war, can't be removed from air base

### Steps to reproduce / Cause of the issue

here's way to fix
In file TNO/common/units/equipment/guided_missiles

![QXJ_PEWA CTUZ9}BH14`GR](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/7e928f9e-af50-44b1-84ce-ad208d2f24f0)

add "manpower = 1" for 3 kinds of missiles, then everything will be fine

![P%@J 20~OPJN$@0}~ `G3M2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/df84fd6b-8df1-497f-94b5-2f98709c7870)

can bomb enemies correctly in game, and one use only

### Expected behaviour

3 kinds of missiles can work correctly

**Comment by runelead00** [comment]
Can't Reproduce, work correctly in dev build
