### ISSUE TITLE
ENG/USA/All russian countries - Non-existing country's tag 

### ISSUE THREAD

**Issue by SablArt** [TNODevs/TNO-Bug-Tracker#2906]
### Operating System

Windows 10

### HOI4 version

Latest

### TNO version

Latest

### Do you have other mods in use?

Russian localisation of TNO, state transfer tool (though, I noticed bug directly in TNO mod root folder, so these mods won't affect the bug)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[TNO_RUS.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/13760197/TNO_RUS.txt)

### Describe the bug

I was exploring the code of Steve Smit's events and noticed, that option from event RUS_tourist.91 leads to country event in Scotland (SCO), but Scotland does not exist in current version of TNO, which makes all events after 91st impossible to happen

### Steps to reproduce / Cause of the issue

Just write ENG = {country_event = {...}} instead of SCO (string 3992 of RUS_events.txt)

### Expected behaviour

Working chain of events

**Comment by runelead00** [comment]
Fixed in Dev Build
