### ISSUE TITLE
TOM - Missing idea swaps for Cynicism Crisis

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2907]
### Operating System

Windows 10 Home

### HOI4 version

Stella Polaris v.1.13.6

### TNO version

The Ruin 1.5.0b

### Do you have other mods in use?

TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Files

[Tomsk Bugfix.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13762777/Tomsk.Bugfix.zip)

### Describe the bug

One of the scripted effects used for Tomsk has a bug that prevents it from swapping ideas whenever its idealism or political integration changes. Because of this, despite the importance in-story of managing the Cynicism Crisis, there are no in-game benefits nor downsides from this mechanic.

### Steps to reproduce / Cause of the issue

Cause of the issue:
    1. Open “TNO_RUS_Tomsk_Mechanics_scripted_effects.txt” under scripted_effects folder
    2. Scroll to line 625 (TOM_set_idea_variable`)
    3. For each sub-function, modify it so it adds the relevant idea as a failsafe

### Expected behaviour

There would be national spirits that indicate how much idealism and integration Tomsk has, and what the in-game benefits are.

### Screenshots

![Bugfix](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/ef145e2f-1342-46fa-b894-760a7db71475)
![integration](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/5005018b-e710-44c9-a6de-0d77b8f5bcb8)

**Comment by runelead00** [comment]
Fixed in Dev Build
