### ISSUE TITLE
TOM - AI overuses Cynicism Crisis decisions to cause massive instability

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2909]
### Operating System

Windows 10 Home

### HOI4 version

Stella Polaris v.1.13.6

### TNO version

The Ruin 1.5.0b

### Do you have other mods in use?

TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT

### Files

[Tomsk_stabilityfix.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13790546/Tomsk_stabilityfix.zip)

### Describe the bug

Often, when an AI Tomsk manages to unify Central Siberia, its base Stability will gradually decline until it reaches -100%. The AI doesn’t know how to properly use the Cynicism Crisis decisions, which not only results in massive instability, but also a ruling party with its popularity measured in single digits.

### Steps to reproduce / Cause of the issue

Cause of the issue:
    1. Open “TNO_RUS_Tomsk_decisions.txt” under decisions folder
    2. Scroll to `TOM_Political_Situation` (line 1371)
    3. For each decision under this category, add a modifier that keeps the AI from taking them when idealism or integration is high.

### Expected behaviour

The AI should know when to stop using the Cynicism Crisis decisions.

### Screenshots

![code](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/9e98a739-bd23-411a-8333-501ab0515545)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
