### ISSUE TITLE
USA- War Taxes Never End

### ISSUE THREAD

**Issue by Weatherboy1102** [TNODevs/TNO-Bug-Tracker#291]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? La Resistance, No Step Back

**Longer Description of Issue:**
I enacted war taxes at the beginning of the Guyana war, and in 1965 they are still applying. 

**Steps to Reproduce/Cause Issue:**

1. Play game normally until Guyana War
2. Enact War Taxes
3. After the war, income should still be massive

**Screenshots:**
![Uploading Screenshot (1583).png…]()

**Comment by runelead00** [comment]
Fixed in Dev Build
