### ISSUE TITLE
cant allocate my PU

### ISSUE THREAD

**Issue by bijesyna123** [TNODevs/TNO-Bug-Tracker#2910]
### Operating System

windows 10

### HOI4 version

1.13.6

### TNO version

v1.5.0b

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA, AAT

### Files

link to save

https://drive.google.com/drive/folders/1cqyLac3ggekppEW6Gq1qNy4OoH0ez4aE?usp=sharing

### Describe the bug

my production units jumped from 57 to 64 because i get PU from trade but i can only allocate 47 of them. Rest of PU wont allocate. I've waited couple in game days and still nothing, it stays on 47

### Steps to reproduce / Cause of the issue

i dont know

### Expected behaviour

nothing 

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/155130279/b1c9c153-0505-4d0b-a372-e8442def6522)

**Comment by runelead00** [comment]
Fixed in Dev Build
