### ISSUE TITLE
ITA - "A Wise Investment" And Other Egyptian Administration Events Options Don't Show Properly

### ISSUE THREAD

**Issue by Sebastianroczz** [TNODevs/TNO-Bug-Tracker#2915]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b "The Ruin"

### Do you have other mods in use?

Toolpack without the errors

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The event choices on "A Wise Investment" Do not show correctly

### Steps to reproduce / Cause of the issue

1. Play As Italy
2. Play Until you get the event named "A Wise Investment"
3. See the options text are just empiremanagment_7.a b c

### Expected behaviour

Show a proper text of the options

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/132775390/7b70fc0b-5c24-4cb0-9b16-774565f5d80a)

**Comment by Sebastianroczz** [comment]
This seems to happen on multiple egyptian related events for Italian colonial managment

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
