### ISSUE TITLE
Germanic Reich - Hitler won't die

### ISSUE THREAD

**Issue by TarrySix3** [TNODevs/TNO-Bug-Tracker#2916]
### Operating System

Windows 11

### HOI4 version

1.11.6

### TNO version

1.2.0

### Do you have other mods in use?

TNO ai disable nukes

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Whenever 1963 is about to end Hitler is supposed to die in October or November, but even if I play as the Reich or any other country he will not die unless I full restart the game. Sometimes I have to verify the files for HOI4 or reinstall the mod entierlly.

### Steps to reproduce / Cause of the issue

Just play as any country up till October or November of 1963 and if the South Africa War kicks off without Hitler dying theres the bug.

### Expected behaviour

I expect Hitler to die whenever I restart the game to see if it fixes it and it does not fix it.

**Comment by Sebastianroczz** [comment]
try disabling the mod and see if it works? I think that mod is outdated

**Comment by runelead00** [comment]
Can't Reproduce, have seen similar issues happen in the past with saving too near certain events but unclear if actually happening here nor would be able to fix that
