### ISSUE TITLE
Matsushita's party name is Yasuda

### ISSUE THREAD

**Issue by KingParrot99** [TNODevs/TNO-Bug-Tracker#2917]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all, TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

Matsushita's party on the popularity chart is called Rippoukai - Zaikaiha (Yasuda) when it should be Rippoukai - Zaihaika (Matsushita). This occurred during a Hitachi game.

### Steps to reproduce / Cause of the issue

1. Play as Sony Guangdong
2. Get couped by Hitachi
3. Observe Matsushita party name

### Expected behaviour

Matsushita's party should be called Matsushita, not Yasuda.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/97854462/77edd134-cd6f-4101-88af-222e46309765)

### Additional information

Maybe this is deliberate, but Hitachi's popularity refused to rise above 36% to match its legco seats.

**Comment by runelead00** [comment]
Fixed in Dev Build
