### ISSUE TITLE
Haiti - Cantave still coups in Haiti even if Trujillo wins in the Dominican Republic

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#2918]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

When Trujillo defeats the Legion, after Lavaud coups in Haiti and the PPLN uprising begins, Cantave coups Lavaud 

### Steps to reproduce / Cause of the issue

1. Set the rules where Trujillo defeats the Legion, then when the PPLN uprising happens to civil war with the Haitian government victorious

### Expected behaviour

Cantave should only coup if the Communist putsch succeeds after the Legion wins in the DR

**Comment by runelead00** [comment]
Should be fixed in dev build
