### ISSUE TITLE
ZOM - some small bugs collection (with solution)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2919]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

1.if BRG goes die in 1970, then player go fire spook_temp.1, ZOM will immediately declare war to all neighbors without killing BRG
this gonna cause problems, ZOM should kill BRG to start firing event lines and get Goebbel leader
2.If ZOM has been defeated or annexed in half way, the events gonna stop running

### Steps to reproduce / Cause of the issue

Here's way to fix
1.in event spook_temp.1, add this part of code
			BRG = {
				transfer_state = 16
				transfer_state = 1626
				transfer_state = 1625
				transfer_state = 788
				transfer_state = 1635
				annex_country = {
					target = GLC
					transfer_troops = yes
				}
			}
this means if BRG already dies in 1970, then let it annex GLC and revive
also let BRG get Nord-Paris territories when ZOM spawns
2.

![L3REE}K T)6Z} 3P449%_TT(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/62459b63-bd7a-4a96-8a1a-30f6715a8ae7)

all these events are letting ZOM fire event to spawn Army, if ZOM not exists, it'll stop working
Replace these circles with ZZZ can fix, all these events' effect are already target to ZOM, so it won't wrongly give armys to ZZZ

### Expected behaviour

ZOM events can run correctly at any time

**Comment by runelead00** [comment]
Fixed 2, Not doing 1: Errors caused by players using console are unsupported
