### ISSUE TITLE
OMO(Aprilfool) - 1962 Pony Rifles even weaker than 1958 Normal rifles(with solution)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2920]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

such as title
the left side is normal 1958 rifle's data, the right side is pony 1962 rifle's data

![IMG_20240105_201407](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/391ee8fa-9318-42a0-b70a-fe18799952ce)

### Steps to reproduce / Cause of the issue

Here's location of pony's file location
tno - common - units - equipments - horse

### Expected behaviour

Pony rifle's data can be better than normal rifles, at least don't be weaker

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
