### ISSUE TITLE
WW3 - JAP can still gain resources from CHI even in war with it (with solution)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2921]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0B

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

![)0~)~6KP$R2AQ_ZZB8QS{O4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/36e14d53-e386-4072-9175-759966392ca3)
when arcade mode ww3 is started with CHI's GAW, it doesnt remove resource right, JAP can still take resource from China even it's in war with it

### Steps to reproduce / Cause of the issue

Here's way to fix
in event arcademode.1
1. add this part of code for gaw options
	CHI = {
		every_owned_state = {
			JAP = {
				remove_resource_rights = PREV
			}
		}
	}

### Expected behaviour

JAP no longer gains resource when CHI starts GAW

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
