### ISSUE TITLE
USA - When 1972 president takes power, retain the focus tree of port negotiations

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2923]
### HOI4 version

1.13.6

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

When a 1972 president(like Kirkpatrick)takes power, don't wipe out the port negotiation focus tree, keep it and allow USA to finish it if it didnt finish in 1968

### Justifications

In the 1968 election, the majority of players choose to get a new 1968 president, and in the 1972 election, the majority of players voted to reelect the 1968 president
this is because the 1972 president is too weak
1972 presidents not only have a short focus tree, but they remove the focus tree for port negotiations when they took office
It also means that players in the 1968 president's term had to spend a year negotiate for port, plus a few focus trees appointing government officials and dealing with the legacy of the previous president, they only had 2 years to act
if they gonna get out of office in 1972, we can even say they have no chance to do anything
because of this, value of choosing a 1968 president for a second term is far greater than a 1972 president
Keeping this focus tree would not only increase the value of the 1972 president, but also avoid someone(both players and AI) ignore port negotiations and have no chance to finish it forever after 1972

**Comment by runelead00** [comment]
We're not adding this, 72 presidents are designed to be short conclusion, not 2 extra year working through a generic tree to deal with the ports. This also would require designing these trees for RDC candidates as well which isn't worth the dev time
