### ISSUE TITLE
Ukraine - Missing "Revolutionary Will" tab for Communists

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2925]
### Operating System

Windows 10

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

Music mods, the recall volunteer mod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Missing tab/gui for the Communists Ukrainians after winning the civil war.

### Steps to reproduce / Cause of the issue

Play as Communist Ukraine.
Win the civil war.

### Expected behaviour

A gui or tab should appear.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/93f39c0e-c57c-4c12-b782-dc3a44e18d36)

**Comment by runelead00** [comment]
Fixed in Dev Build
