### ISSUE TITLE
Norway has the vanilla Germany flag

### ISSUE THREAD

**Issue by Assassin2003** [TNODevs/TNO-Bug-Tracker#2926]
### Operating System

Windows 10

### HOI4 version

1.13.6

### TNO version

1.5.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Norway flag

### Steps to reproduce / Cause of the issue

Sorry, I don’t know

### Expected behaviour

I expected a normal RK Norway flag

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/156140000/7257575e-b6fa-47b6-8bfb-d0df77835722)

### Additional information

This issue started when the latest The New Order version dropped

**Comment by runelead00** [comment]
Fixed in Dev Build
