### ISSUE TITLE
IRK - Typo

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2927]
### HOI4 version

1.13.6

### TNO version

1.5.0b "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Typo marked under with red

![bug report tno](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/4c20f680-93e5-4c9b-89b5-2a305bb1d4e4)

### Additional information

Should be saying "greatly" instead of "great"

**Comment by runelead00** [comment]
Fixed in Dev Build
