### ISSUE TITLE
IRK - Typo "skys"

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2928]
### HOI4 version

1.13.6

### TNO version

1.5.0b "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Typo marked under with red:

![bugger report tno](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/89b58b40-77b1-4fbf-b883-1f3b2557deec)

### Additional information

Should be saying "skies" instead of "skys", as that is the correct form of sky in plural.

**Comment by runelead00** [comment]
Fixed in Dev Build
