### ISSUE TITLE
Collab England - "Towards the North" not working

### ISSUE THREAD

**Issue by YaBoiNuke** [TNODevs/TNO-Bug-Tracker#293]
**Questions**

- Operating System: Win10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Nope
- Were you using Steam? Yeah
- Which expansions do you NOT have? Just NSB

**Longer Description of Issue:**

Pretty simple, the special actions for Lancashire and Newcastle don't show up. Took a look at the files and they use the HMMLR flags instead of the Collab flags for those particular decisions.
**Steps to Reproduce/Cause Issue:**

1. Play collabs

2. Choose Chesterton's subtree in the pre-ECW

3. No special decisions show up in Lancashire or Newcastle on the GUI

**Comment by runelead00** [comment]
Fixed in Dev Build
