### ISSUE TITLE
GER - Heydrich Germany can ignore Nuke_disabled effect to fire nuclear war(small and easy to fix, with solution)

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2931]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

when Heydrich let BRG get enough nukes, system will fire event HGR.666 to start nuclear war
and it can ignore arcade mode's disable nuke effect

### Steps to reproduce / Cause of the issue

here's way to fix
trigger = { NOT = { has_global_flag = nukes_disabled } }
add it for event hgr.666, that's it

### Expected behaviour

bug fixed

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
