### ISSUE TITLE
Britain - Focus "Discuss the Garrison's Situation" had no effect

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2932]
### Operating System

Windows 10

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

Music mods, the recall volunteer mod and toolpakt.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In Britain, after Adolf Hitler dies the focus in the sort focus tree "Discuss the Garrison's Situation" is supposed to reduce chaos by 5%, assuming this means the party chaos in the decision tab.
However, when this focus complete, there was no decrease in the percentage of chaos.

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/ffe908c6-037b-418c-baef-6296a0f8afc8)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/13cf065b-98ed-469f-a83a-e18c65b7928c)

**Comment by runelead00** [comment]
Working as Designed, Chaos can't be lowered a threshold once you pass it as it listed in tooltip
