### ISSUE TITLE
CHI - Grammar mistake in Chongqing lore description

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#2933]
### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

In Chongqing's lore description, "cities" should be written as "city's" (possessive).
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/c8eecfd2-427d-47b9-837d-85a075748ff4)

**Comment by runelead00** [comment]
Fixed in Dev Build
