### ISSUE TITLE
West Africa - Bugged peace process

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2935]
### Operating System

Windows 10

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

Music mods, the recall volunteer mod and toolpakt.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

West Africa experienced the early 1964 war between FMA and PALF over the Ghana civil war. The PALF were very quick, and won in December of 1964. However, in the peace conference, Senegal got split in half by the PALF taking control of the Dakar state and Mali taking control of the Ballou state.

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/0bddb0c7-f535-417f-b583-c6c0c96aae54)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/9c260eb7-0961-48a1-bf43-418f80bec838)

**Comment by runelead00** [comment]
Should be fixed in Dev Build
