### ISSUE TITLE
BRY - Event BRY.90 fires during English Civil War

### ISSUE THREAD

**Issue by Totalen** [TNODevs/TNO-Bug-Tracker#2936]
### HOI4 version

.

### TNO version

.

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT

### List the loc issues below

![obraz](https://github.com/TNODevs/TNO-Bug-Tracker/assets/92178816/20933d39-80c3-48a3-a023-c56ec8e36d0a)

### Additional information

I got an event talking about Socialist Labour Party winning in the UK, while ignoring the Civil War ongoing. Also, i'm pretty sure the TFL team removed the old HMMLR content.

**Comment by Sebastianroczz** [comment]
fix your format or the devs are going to fix

**Comment by Stormeagle449** [comment]
Fixed wrong instance of party name, will fix the firing issue later.

**Comment by Marok132** [comment]
> Fixed wrong instance of party name, will fix the firing issue later.

Was it fixed?

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
