### ISSUE TITLE
cant even play it

### ISSUE THREAD

**Issue by ProundRhodesian** [TNODevs/TNO-Bug-Tracker#2937]
### Operating System

windows idk

### HOI4 version

lastest version

### TNO version

lastest version

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, BBA, AAT

### Files

cant have a save games if it crash every time I try to play any nations.

### Describe the crash

The game load. The nation load. When the bar finish, the game crash automatically.

### Steps to reproduce / Cause of the crash

Idfk

### Screenshots

![20240119215457_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/157188811/51eb84eb-f8aa-4d9c-873f-619d4bd1cd20)

### Additional information

I reloaded the game. Uninstalled it than instal it again both the game and the mod. try multiple nations. clean all the other mods. restarded my pc.

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/962, can only recommend possible fixes listed there
