### ISSUE TITLE
IRK - Localization error

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2938]
### HOI4 version

1.13.6

### TNO version

1.5.0b "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Error marked under with red.

![bug report](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/81f68938-e645-44d4-8950-dfad9358ea40)

### Additional information

Should be saying "We've got little choice..." or something, because something isn't right.

**Comment by runelead00** [comment]
This is correct English, we've and we've got have the same meaning other than the formality of the writing
