### ISSUE TITLE
BGR - Receiving 250 billion/year in free income

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#294]
- Operating System: windows 10
- HOI4 Version: Collie 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? own them all

I believe this modifier is over-inflated, as it's at 250 billion a year in income (probably should be 250 million). My reserves are ridiculously high now.

![image](https://user-images.githubusercontent.com/59315866/143229397-7256c93c-26ac-4798-9cda-be0abceb8931.png)

**Comment by runelead00** [comment]
Fixed in Current Dev Build
