### ISSUE TITLE
YUN - 2 Partial Victory bugs

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2940]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

1.in event yun_wi.42
AI has 10% chance to choose Partial Victory, and this will ruin JAP players' feeling
YUN can fire this event without JAP's action, and if AI agrees, It will make JAP lose 700 scores in cold war - even JAP player never asked for this ending
also if player YUN choose this way, YUN wont get closing screen
2.
this is YUN's Partial Victory effect
![T6PEKZ8A_ 2PL~@F09W0URM](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/28ea41b8-3109-4ff1-ba43-08b134535c5f)
it asks GUX SHX is in faction with JAP, So it can be annexed
but what if they are in faction with YUN? they wont get annexed
also, QIN and XIK is not annexed, even they supposed to be

### Steps to reproduce / Cause of the issue

here's way to fix
1.make 1st option's factor to be 0
also, add TNO_Country_Closing_Screen_Show = yes
for yun_wi.43
2.remove GUX's and SHX's limits, they dont need to exist
add annex QIN and XIK effects

### Expected behaviour

both of them can be fixed

**Comment by runelead00** [comment]
1. Adjusted so chance for peace is 0 if Japan is a player, also that's not where the closing screen goes at all since that event triggers more events
2. already fixed in dev build
