### ISSUE TITLE
Hart USA - 'Cars' misspelt to 'Care' for description of paved roads in Anytown.

### ISSUE THREAD

**Issue by KingParrot99** [TNODevs/TNO-Bug-Tracker#2941]
### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/97854462/c17208c1-122b-4ac7-83f1-42d7273d26ad)

**Comment by runelead00** [comment]
Fixed in Dev Build
