### ISSUE TITLE
Germany - Dönitz refuses to move to Crimea and disappear during the GCW

### ISSUE THREAD

**Issue by Interesting2752** [TNODevs/TNO-Bug-Tracker#2944]
### Operating System

Windows 10

### HOI4 version

1.13.6.7bda

### TNO version

1.5.0b

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT

### Describe the bug

While I was playing as Speer in Germany, I noticed that after Germany annexed my side, I still had Admiral Dönitz on my character list, despite the fact that he and his navy was supposed to have fled to Crimea at this point. This led to some weird narrative problems as despite forcibly striping his admiral rank and sentencing him to 30 years in prison, he could still command my submarine fleet.

### Steps to reproduce / Cause of the issue

1. Play Germany
2. Pick successor, I went with Speer for my run.
3. Make sure to win
4. Look at the admiral's list, Dönitz should still be an admiral in Germany
5. For extra ludonarrative dissonance, make sure to proceed across the focus tree until you get to reform the navy and deal with Dönitz
6. Wonder at how Dönitz can still command your U-boats despite being in jail.

### Expected behaviour

I expected Dönitz to disappear to Crimea and not be on my Admirals list anymore, or failing that, for him to be retired when I did a Speer event for him.

### Additional information

I think the problem is that the event that triggers Dönitz's defection to Crimea doesn't actually transfers the character, causing him to stay in Germany.

**Comment by Marok132** [comment]
His lore was changed in Ruin update and now he'll be always in Germania when the GCW starts.
