### ISSUE TITLE
The Onega Peace Accord is not progressing.

### ISSUE THREAD

**Issue by backstepsoviet** [TNODevs/TNO-Bug-Tracker#2945]
### Operating System

windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0

### Do you have other mods in use?

korean Translation 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I played Onega and won the Murmansk War, but then the Peace Accords became like this and no victory events popped up.
Just to be sure, I played it again, but the Peace Accord is still there.
This caused a major disruption to Onega's play. We've temporarily fixed it with a debug fix, but it looks like it needs to be officially fixed. ㅠㅠㅠㅠㅠ

### Steps to reproduce / Cause of the issue

It seems to be an issue of peace agreements, so why don't we look at the part of the peace agreement between Onegawa and West Russia?

### Expected behaviour

i dont know

### Screenshots

![20240131190700_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/151175745/f96acdd1-20d4-4cb6-bfe4-b5a7b0a34c69)

**Comment by runelead00** [comment]
Fixed in Dev Build
