### ISSUE TITLE
ITA - A Focus completely blocked by another focus

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2946]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Fascism path, the right side of military focus tree
![Image_1706781098387](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/857cd1cf-1f9c-454d-8591-78577643092c)
![Image_1706781015678](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/4aae554f-9d0c-44ec-9226-6b7fbb5f725d)

### Steps to reproduce / Cause of the issue

Go ITA Fascism path and it'll happen

### Expected behaviour

Focus no longer get blocked

**Comment by runelead00** [comment]
Fixed in Dev Build
