### ISSUE TITLE
United States - LBJ still in Texas despite being president

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2948]
### Operating System

Windows 10

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

Music mods, the recall volunteer mod, toolpakt and Zizek's Ideology Bling.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Despite LBJ being president, he is still acting as a senator from Texas. Perhaps I have my politics of the US wrong but shouldn't he not occupy both positions at once?

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/2078e51c-5155-4b7d-be37-653352954dfb)

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

**Comment by runelead00** [comment]
Fixed in Dev Build
