### ISSUE TITLE
Germany (Speer): Madagaskar and Bulgaria not joining Zollverein

### ISSUE THREAD

**Issue by RPSbluekirby** [TNODevs/TNO-Bug-Tracker#295]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 
- Any other mods in use: 1.2.0.d
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back

**Longer Description of Issue:**

After the German Civil War Bulgaria and Madagaskar did not rejoin the Zollverein. 

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed for UB
