### ISSUE TITLE
United States/Colombia - Missing loc for "The Renewed Spirit of Mallarino-Bidlack" news event

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2951]
### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

Music mods, the recall volunteer mod, toolpakt and Zizek's Ideology Bling.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

As the title says:
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/5e4c87a3-b51f-47d0-b385-4cf8158f2a53)

**Comment by runelead00** [comment]
Fixed in Dev Build
