### ISSUE TITLE
United States - Two opposing events about outcome of Colombia negotiations.

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2952]
### Operating System

Windows 10

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

Music mods, the recall volunteer mod, toolpakt and Zizek's Ideology Bling.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

During the negotiations to repair Colombian-US relations the conclusion somehow resulted in me acquiring to events, indicating two entirely different outcomes to the negotiations.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/55504bac-a6a4-4146-8551-856add309dbe)

I am not sure which event is the genuine one, although only the failure event also yielded a news event, and nothing visibly changed in relations between the two countries.

### Steps to reproduce / Cause of the issue

1. Have the republic of Colombia win the civil war.
2. Wait until the elect the pro-American candidate, begin negotiations.
3. In the second round, ask they expel all foreign actors, have them accept this offer.
4. Wait until the negotiations come to an end.

### Expected behaviour

Only one of these two events should fire.

**Comment by runelead00** [comment]
Fixed in Dev Build
