### ISSUE TITLE
Faroe Islands - Period Missing on Peter Mohr Dam's death event

### ISSUE THREAD

**Issue by Interesting2752** [TNODevs/TNO-Bug-Tracker#2953]
### HOI4 version

1.13.6.7bda

### TNO version

1.5.0b

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT

### List the loc issues below

1. On the event for Peter Mohr Dam's death (WORLD.17102), there's no period or other punctuation ending the second paragraph of the news event.
![20240202180913_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/86580638/4643ca89-760e-4793-9183-6a94be1648e8)

**Comment by runelead00** [comment]
Fixed in Dev Build
