### ISSUE TITLE
United States - Missing focus Icon for LBJ focus tree

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#2954]
### Operating System

Windows 10

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

Music mods, the recall volunteer mod, toolpakt and Zizek's Ideology Bling.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

For the "But Our Virtues are Great!" focus, the icon is missing.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/d457ccbe-b923-4fb3-b6ba-73aebd58e2b7)

### Steps to reproduce / Cause of the issue

N/A

### Expected behaviour

N/A

**Comment by turbobounce** [comment]
Note, when the focus is completed the icon returns.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/9b416b04-a314-42d3-8f15-103bee08d13b)

**Comment by turbobounce** [comment]
Okay, and even later it again changed back to an unknown icon.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/25708474/d46a28cf-005d-41a7-a8b0-20f4175732fb)

**Comment by runelead00** [comment]
Fixed in Dev Build
