### ISSUE TITLE
USA - If Hart loses 1972 election, Cancer events and 500 days timer are still running even Hart's no longer prisedent, then Chep will wrongly takes power when timer ends

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2955]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

If Hart loses 1972 election, the timer "USA_Hart_Cancer" is still running
and 500 days later, even if 1972 president already took office, Hart cancer events are still running, and after Hart die from cancer
Chep gonna have a coup to take power, get rid of 1972 presidents

### Steps to reproduce / Cause of the issue

here's a personal suggestion to fix
coup comes from USA_Hart_Cancer timer, and this timer comes from cancer events
Hart cancer events start from USA_elec_prim.11, I hope it can be moved to event USA_elec_prim.15
this means Hart will find cancer only after he won 1972 election
if he loses, then let new president takes power normally, no cancer event will happen

### Expected behaviour

if Hart loses 1972 election, system transfers things correctly

**Comment by runelead00** [comment]
Fixed in Dev Build
