### ISSUE TITLE
ZZZ/CME/ADN/PKT - As Anarchy tag, they can sometimes get troops wrongly

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2956]
### Operating System

Wndows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

If player can sometimes make something stupid and fire nuclearwar, it will be tagged to tag ZZZ - and sometimes can even see it got some troops
this bug sounds strange, but exists, and I have no idea how it got troops - it has no start division, no tech, no factory, even no core
I guess It is likely that the GCW transferred some guns to ZZZ, and then other countries gave the divisions to him
This situation also possible for 3 other anarchy tags - CME/ADN/PKT

### Steps to reproduce / Cause of the issue

here's possible way to fix
in file tno-history-countries
add this for CME/ADN/PKT/ZZZ:
country_lock_all_division_template = yes

### Expected behaviour

These tags can no longer to build army

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
