### ISSUE TITLE
IBR - Wrong Brazil Capital in diplomacy event

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2957]
### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

in event IBR.264
"With business in Argentina concluded, it is time for Franco to go to Brazil and visit the capital city of **Rio de Janeiro.**"
However Brazil capital should be Brasilia

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
