### ISSUE TITLE
AM Warlords - debt still retain after midnight that make state GDP nuked

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2958]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

After midnight, holy russian empire(KOM) lost a lot of lands, but debt doesnt get removed, this will make debt-to-GDP fly to a scary number and make state GDP nuked
this situation also happen on other warlords, they will also lose some land in the process of splitting at midnight, and debt kept

### Steps to reproduce / Cause of the issue

here's personal way to fix
in file TNO_RUS_AfterMidnight_effects
add this for TNO_AM_country_setup
![ZP33({A2PY3TKH9TR~ RXJ](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/55832fa5-240b-4a1e-8d52-0e99dbe8b77b)

### Expected behaviour

atfer midnight, debt would be cleared to make state GDP not getting nuked

**Comment by runelead00** [comment]
added to national debt wipe for KOM. Not adding anywhere else because it would have zero effect
