### ISSUE TITLE
Mozambique Civil war - If South African War ends with SAF advantage, Mozambique Civil war will not able to start correctly

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2959]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

if civil war starts, it'll be like this
![KRU71KXGYH) NQ4W ~{D ~F](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/73df3e0f-3d60-4710-a275-7a0619872ac2)
however, if South african war ends with SAF advantage, the south Mozambique will be taken, and civil war will not able to start correctly, the south part of warlord won't spawn

### Steps to reproduce / Cause of the issue

here's way to fix
in file TNO_Mozambique_scripted_effects, add this for TNO_start_mozambique_civil_war
![EP1R}SUQ{5M @_{4@EXS556](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/0ca234bd-1fed-4d98-87a9-6c09cf0d351e)
then civil war will be like this
(to make sure of balance, i give GZO 2 more lands)
![ZH 9GNRSV0ROZKLA12QALPW](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/e2e3ff7c-0cef-4558-b334-8d1796498748)
even if SAF advantage, civil war can still run
![LS}1 GRX8_D(ZBK}8E97TO](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/416ea078-02ef-4eee-96dc-59ac3106340e)

### Expected behaviour

Mozambique civil war can start correctly

**Comment by runelead00** [comment]
Fixed in Dev Build
