### ISSUE TITLE
Iberia : starting Iberia focus reduce GDP instead of increasing it

### ISSUE THREAD

**Issue by vtmt2000** [TNODevs/TNO-Bug-Tracker#2960]
### Operating System

Windows 11

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

like in the title the Iberian starting focus that "increase Guinea/Morroco/Algeria GDP by 2%" actually decrease the GDP in those regions ... by a lot.
The only saving grace is that after 1 month it self corrects to 25$ GDP per capita as I suppose a minimum number 

### Steps to reproduce / Cause of the issue

1. Play Iberia
2. do the "2% increase in GDP focus"
3. look at the affected states
4. wait a month for the number to self correct to the minimum of 25$ per capita

### Expected behaviour

For the GDP to increase by 2% maybe for a 2% growth state modifier

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/123703832/bb5801d5-5e8f-48a7-97d3-9ff3154e4d2c)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/123703832/ee4f5894-e277-428b-8360-69c9a6353d4e)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/123703832/a9fa00e8-20a5-4edc-83b3-b3b0d7d66c1d)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/123703832/b02ef22f-c320-4cee-a0ad-71260a2bfc45)

**Comment by runelead00** [comment]
Fixed in Dev Build
