### ISSUE TITLE
Ireland - Typo of name

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#2962]
### HOI4 version

1.13.6

### TNO version

1.5.0b "The Ruin"

### Do you have other mods in use?

Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Marked under with red
![aaaaa report](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/b1771a54-b483-4516-af8e-b79ae973cf1d)

### Additional information

It's saying "Flangan" instead of "Flanagan"

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
