### ISSUE TITLE
Speer germany post gcw, intelligence and foreign policy bug and economic icons bugged

### ISSUE THREAD

**Issue by wzrd9** [TNODevs/TNO-Bug-Tracker#2963]
### Operating System

windows 11

### HOI4 version

latest

### TNO version

latest

### Do you have other mods in use?

Modifier Gui, easybuff tno, radio tno, strategic view,  player led conference

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

DOD, MTG, BBA, AAT

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14231358/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14231359/error.log)

### Describe the bug

sometimes the tab is disappearing and never returned, global conflict only show decision and intelligence is bugged too. also economy icons also bugged

### Steps to reproduce / Cause of the issue

1.go to politics tab
2.press foreign policy tab
3.global conflict only showed decision
4.intelligence tab

### Expected behaviour

nothing and it goes like what it use to

### Screenshots

![Screenshot (4)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/73803795/4f816b46-9e35-45b6-8f79-389fbd3178e8)
![Screenshot (5)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/73803795/2d424221-7d2a-4c41-9b53-3d301d491f97)

### Additional information

i think either other mods or something

**Comment by Posidon88** [comment]
did u ever find a fix for this?
