### ISSUE TITLE
Iran Civil War - if Iran Government defeats IRB then get defeated by other countries, civil war can't end correctly

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2965]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

after Iran resistance faction dissolve, Baloch(IRB) will fight with Iran Empire Government itself
and if it has been killed by Government, and then Government get killed by other powers, war will can't end correctly(winner can't get core, can't join OFN or sphere)

### Steps to reproduce / Cause of the issue

Steps to reproduce has been said in Description
can't give way to fix

### Expected behaviour

Iran civil war can end correctly even if IRB died

**Comment by runelead00** [comment]
We can't properly fix peace deal issues without a save prior to a peace deal #1509

**Comment by runelead00** [comment]
Can't Reproduce
