### ISSUE TITLE
After Midnight - Coring decisions not able to get Stability and other effects

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2966]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Before midnight, every coring decisions can get effects like this:
![I`RU $)IU1CE4FXEFLG@P0C](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/d85ef37c-4c3d-410d-934c-35041d4e317d)
But none after midnight
![J9HDT8K4$P3TYZBV7J)CS0K](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/8e2d753e-17fe-4818-8bda-ecbb3e8e38c0)
It deducts the player's stability and does not grant after completing coring, nor does GDP growth and admin effiency
![Image_1707833339291](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/8d96ab00-2c4b-4816-90f9-6052f492e4fc)
also, "every_state" is wasting players' CPU, It can be completely replaced by every_owned_state

### Steps to reproduce / Cause of the issue

here's way to fix
1.in file **TNO_After_Midnight_decisions**
add this code for all decisions **in RUS_AM_coring_category**:
add_stability = 0.025
set_temp_variable = { gdp_growth_temp = 0.01 }
econ_gdp_growth_change = yes
TNO_improve_admin_efficiency_really_low = yes
2.replace every_state with every_owned_state

### Expected behaviour

Coring can get bonus correctly

**Comment by runelead00** [comment]
AM coring decisions do not need to be identical to regular coring decisions and it doesn't make much sense for them to be either
