### ISSUE TITLE
[Bug]: Ethiopia - Capital city (Addis Ababa) duplicated in the same spot

### ISSUE THREAD

**Issue by silverbugreporter** [TNODevs/TNO-Bug-Tracker#2967]
### Operating System

windows 11

### HOI4 version

Stella Polaris v1.13.7.1e05 (6100) (S)

### TNO version

v1.5.0b "The Ruin"

### Do you have other mods in use?

2WRW v1.5.0b - Global Conficts: World In Flames

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, AAT

### Files

I have no files.

### Describe the bug

It's simply when Addis Ababa duplicated itself as both a capital and major city.

### Steps to reproduce / Cause of the issue

For me, this seems unnecessary, but here:
1. Play Novosibirsk (or, possibly any country)
2. Look at Ethiopa's capital (if it isn't there, wait until Italy reclaims the horn of Africa)
3. Look at it again

### Expected behaviour

Addis Ababa to be a singular city, as a capital city.

### Screenshots

https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/bc52ad60-3768-401e-a40d-195cee93049f

### Additional information

A minor issue.

**Comment by runelead00** [comment]
Fixed for ODF integration
