### ISSUE TITLE
[Bug]: French Republic - Capital is still "La Rochelle" despite France reclaimed

### ISSUE THREAD

**Issue by silverbugreporter** [TNODevs/TNO-Bug-Tracker#2968]
### Operating System

windows 11

### HOI4 version

Stella Polaris v1.13.7.1e05 (6100) (S)

### TNO version

v1.5.0b "The Ruin"

### Do you have other mods in use?

2WRW v1.5.0b - Global Conficts: World In Flames

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, AAT

### Files

No error logs. Map-based issue.

### Describe the bug

The capital city is still "La Rochelle" despite the French Reclamation war already over. Minor issue.

### Steps to reproduce / Cause of the issue

1. With custom game rules, ensure Poujade is in office and have him lose the War Against the 200 Families
2. Free France **must** win the West African War with custom game rules (again)
3. Once Poujade loses the War Against the 200 Families, Free France must reclaim the French State with the French Resistance.
4. Once the French Resistance defeats the French State (there shouldn't be any other contenders), the capital does not move for some reason (If it's due to Burgundy occupying North Paris, do the optional route)
 --- ONLY DO THE BELOW IF BURGUNDY IS CONSIDERED "AN ISSUE" TO MOVING THE CAPITAL ---
5. Collapse Burgundy in 1970
6. Have Red Poppy win, with the French Republic annexing them
7. Check if the capital has moved

This is either not coded in or simply a bug.

### Expected behaviour

After the civil war, the capital is moved to South Paris.

### Screenshots

https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/6f9abd23-0ded-4fe3-9e4c-a0a149995c14
https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/65b8b441-0e9e-4c64-9859-6e8f0fbbbc12

**Comment by runelead00** [comment]
Fixed in Dev Build
