### ISSUE TITLE
NGA - can't get core of several lands it controls after Cameroon civil war

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2969]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

![Image_1707989936599](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/a71a3a42-dfd5-4f96-9f43-123643118623)

![Image_1707989935117](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/f7cfde17-d92d-4a79-920e-955b8c9dfafa)

![Image_1707989933747](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/02468cf6-dc46-4953-b594-468a84d3cd34)

### Describe the bug

after Cameroon civil war, NGA will take 625, 1187, 1188 these 3 states if all other Nigeria warlords died
but NGA didn't get core of them
I guess this is becuase system only gives core when NGA get these lands from CAO
if it takes from other countries, then system won't add core

### Steps to reproduce / Cause of the issue

here's possible way to fix
in event CAO.102
remove limit of these 3 states core code, geographically, they should be claimed as native by the NGA, there's no need to add limit

### Expected behaviour

NGA(and other warlords) can get core correctly

**Comment by runelead00** [comment]
Fixed in Dev Build
