### ISSUE TITLE
SBA - General Assembly broken after power struggle

### ISSUE THREAD

**Issue by Camkufyss** [TNODevs/TNO-Bug-Tracker#297]
Operating System: MacOs catalina
    HOI4 Version: Collie 1.10.8
    TNO Version: 1.2.0d
    Any other mods in use: TWR music mod
    Were you using Steam? yes
    Which expansions do you NOT have? No step back, man the guns

After winning the power struggle on superregional, I got events for the power struggle for over six months still. Button to pass resolutions never appeared again. Was trying to pass a resolution when the power struggle erupted.
![20211124125254_1](https://user-images.githubusercontent.com/69312208/143262653-01c58cbd-bf21-4faa-b55f-0c2d2fe8aed9.jpg)

**Comment by runelead00** [comment]
Fixed in Current Build
