### ISSUE TITLE
All countries - Achievements list broken

### ISSUE THREAD

**Issue by silverbugreporter** [TNODevs/TNO-Bug-Tracker#2970]
### Operating System

windows 11

### HOI4 version

Stella Polaris v1.13.7.1e05 (6100) (S)

### TNO version

v1.5.0b "The Ruin"

### Do you have other mods in use?

2WRW v1.5.0b - Global Conficts: World In Flames

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, AAT

### Files

Applies to **all** my playthroughs.

### Describe the GFX issue

Achievements score exists, however, the list of such achievements is broken, and the scroll slider is bugged and displaced.

### Steps to reproduce / Cause of the issue

1. Play any country
2. Go to the Cold War GUI, and see if the Achievements list is there.
3. If it isn't broken, then it might be a compatibility issue on my end.

### Expected behaviour

The achievements would be displayed correctly.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/7b7c6196-ece6-4764-928b-8c20d2da553a)

### Additional information

For you, the developers, this may not be possible to reproduce.
If you need more info, ask me.

**Comment by runelead00** [comment]
Can't Reproduce
