### ISSUE TITLE
GER - Speer's Economy Unfucker destroys Economy

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2971]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

![Image_1708060689362](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/6086ad5a-cd3a-4d1d-a82b-be88902ba1b8)
when content ends, system gonna have a event to save economy
![Image_1708060592398](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/4c85f8bf-f1ba-414d-aac1-25459e465688)
but all it does just fucks economy with another way
![Image_1708060896916](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/d5d628f0-febd-43b0-8ed8-6e7fb47535c6)

**First and Most importantly, this event does not have any additional triggers, meaning that any players can trigger this event after 90 days and have it destroy their own economy**
the idea it added gives 100b misc income, I think it doesnt even need to exist
if it needs to clear debt, we already had divide_var above, this income only creates spillover reserves, when all the debt is paid off, the reserves destroy GDP growth too
also, it sets basic GDP growth to 1.5%, for even the worst players, they should all be able to make more than 1.5% basic growth at the end of content
even for AI, 1.5% is too low, maybe it really saved economy for AI skill
but in tno, 1.5% is the same as stagnation, floundering on the edge of negative growth
Germany should not have such stagnation, whether it GOF or Speer, or even reactionaries won at the end

### Steps to reproduce / Cause of the issue

here's personal suggestion about this
in reich.9999
add trigger = { is_ai = yes } , players dont need this unfucker
add a var check to the section that sets the growth rate, let It only work if GDP_growth < 2%
also, i think the growth it sets should be higher

### Expected behaviour

Economy unfucker no longer fucks economy

**Comment by runelead00** [comment]
will reduce misc income effect + add trigger (although it's not really necessary because no one should be playing after all the content is over)
Not increasing growth. The economy is set to stagnation level because the economy is stagnating
