### ISSUE TITLE
GAX/TDF - can make horrible debt from void

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2972]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Tierra del Fuego and the Galapagos - These 2 tags have unnatural trade system
their trade system can bring negative customs revenue, nuke their economy
![Image_1708095571817](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/1fbc6e52-b4aa-4ca8-928a-0f950a40fb4e)
![Image_1708095983410](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/aeea62b0-5c15-4bf2-90e7-cf0958384bd6)
and this is what it caused, 700b debt
i tried to annex Brazil, then the value goes correct immediately, so this is not tags' problem

### Steps to reproduce / Cause of the issue

when these 2 tags has been spawned, tag to them and check their trade system
can't give stable way to fix, perhaps because these two states are too poor, the value of goods cannot be calculated normally

### Expected behaviour

GAX and TDF can no longer find debt from void

**Comment by MrStraws114514** [comment]
perhaps can add a value max limit in scripted effects

**Comment by runelead00** [comment]
Fixed potential issue with GAX economy previously, also TDF is being removed in the future so this is a non-issue
