### ISSUE TITLE
Some unplayable countries have "tno_playable_country" flag and some unused tags

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2973]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

1. FRI, GUL, UAE, GRE
these are unplayable countries wrongly get playable flags, tno has some extra operations for playable countries, these might waste performance
 
2. UKR FUK BOV UKS
these 4 ukrainian tags are playable, but didnt getting flag

3. NPL, UYG, EST, LAT, PAV, KOK, DER, ARL, AKT, WSM, ESM, MAL, BRM, QUE, MAU, MOM, AFR, TOO
these tags exists in file, but seems completely unused and can be removed(idk if dev build gonna use them, pls check carefully

4. BRT Britanny has been dead for long time, but still in file with tno_playable_country flag

### Steps to reproduce / Cause of the issue

in file
tno - history - countries

### Expected behaviour

playable flag can be correct

### Additional information

dont forget to add flag for Mexico next version

**Comment by runelead00** [comment]
Performance and gameplay impact is extremely minimum, also we know about all the unused tags, they are kept for a purpose/can't be removed easily right now. (plus one of them is used completely normally in game + used for core purposes)
