### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Alfrenep** [TNODevs/TNO-Bug-Tracker#2975]
### Operating System

Windows 10

### HOI4 version

1.13.6

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When i take the colonial budget focuses as iberia (the ones that give a small bonus to the GDP of the colonies) the economy goes crazy

### Steps to reproduce / Cause of the issue

1.Play as iberia
2.Just do any focus

### Expected behaviour

the gdp of the aforementioned territories becomes completely irrational

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98240555/7a3e1fc5-60cb-44b7-896b-aa47e9fd2465)

**Comment by runelead00** [comment]
Fixed in Dev Build
