### ISSUE TITLE
eng - Domvile is back from the dead and mad about the economy

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#2976]
### Operating System

windows 11

### HOI4 version

1.13.6 

### TNO version

v1.5.0b

### Do you have other mods in use?

Radio TNO: Music of the New Order,Zizek's Ideology Bling 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I think the workshop mechanic is still running 

### Steps to reproduce / Cause of the issue

play the game idk. the event id is britain_budget.6

### Expected behaviour

event about workshop mechanic is pop up 

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/e8fe0f8a-fd07-4127-ade8-79464e5f4f40)

**Comment by runelead00** [comment]
fixed in dev build
