### ISSUE TITLE
eng - britain finds oil in the Frontier Provinces in the middle of the civil war

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#2977]
### Operating System

windows 11

### HOI4 version

1.13.6

### TNO version

v1.5.0b

### Do you have other mods in use?

Radio TNO: Music of the New Order,Zizek's Ideology Bling

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

the focus call "the oil, depleting", spawns oil in chitral state 

### Steps to reproduce / Cause of the issue

play the game 

### Expected behaviour

idk

### Screenshots

![20240219134637_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/65fcc489-80f0-4abf-b00c-9f632d761f04)
![20240219134641_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/b8595170-be6f-4ad6-97a0-89fe249f2704)

**Comment by runelead00** [comment]
Fixed in Dev Build
