### ISSUE TITLE
USA - Revolt of the Generals Event Series is broken

### ISSUE THREAD

**Issue by Angelblue1852** [TNODevs/TNO-Bug-Tracker#2978]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0 The Ruin

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I noticed this one on an older patch, but the files that caused it are unchanged.
The Revolt of the Generals event series is borked. It starts with Event 5, but it never fires. According to a friend of mine, the trigger line that requires the revolt_of_the_generals_active country_flag, has made it so the event will never fire under any circumstances. I won't swear it's replicatable, but it sure looks like the files haven't been altered enough to remove the underlying issue. There are similar issues with chase.rog.8, which should trigger chase.rog.9, but doesn't due to the trigger being messed up, and events 12 and 30, which never fire as there are no blocks or triggers in the files that trigger them.

### Steps to reproduce / Cause of the issue

1.Play as USA
2.Get MCS elected in 68.
3.Do the Military Tree and tick off the generals.
4.The Revolt event never triggers due to the trigger line not being fulfilled.
5.Even if manually triggered, event 9 never fires as the trigger for it in event 8 tries to trigger 8 again.
6. EVEN IF THAT WORKS, Events 12 and 30 never trigger as there is nothing that calls them up.

### Expected behaviour

The Revolt of the Generals Event to fire after the focuses are taken and the timer runs out, as well as for the event chain to work properly and fire all its events.

### Additional information

For chase.rog.5, Removing the Trigger line should fix it.
A Similar issue exists for chase.rog.8, as it should trigger event chase.rog.9, but instead it tries to trigger itself again, but can't due to the fire_only_once block.
option = {
		name = chase.rog.8.b
		custom_effect_tooltip = USA_subtract_NPP_unity
		custom_effect_tooltip = usa_mcs_68_rog_lose_face
		hidden_effect = {
			country_event = {
				id = **chase.rog.8**
				days = 33
			}
			set_temp_variable = { USA_week_change_rural_rep = 2 }
			add_to_variable = { Demographic_Shift_rural_rep_Weeks = USA_week_change_rural_rep }
			add_to_variable = { Demographic_Shift_urban_rep_Weeks = USA_week_change_rural_rep }
			add_to_variable = { Demographic_Shift_black_rep_Weeks = USA_week_change_rural_rep }
			add_to_variable = { Demographic_Shift_hispanic_rep_Weeks = USA_week_change_rural_rep }
			add_to_variable = { Demographic_Shift_minority_rep_Weeks = USA_week_change_rural_rep }
			add_to_variable = { Demographic_Shift_union_rep_Weeks = USA_week_change_rural_rep }
			add_to_variable = { Demographic_Shift_nativists_rep_Weeks = USA_week_change_rural_rep }
			set_temp_variable = { USA_week_change_rural_dem = 2 }
			add_to_variable = { Demographic_Shift_rural_dem_Weeks = USA_week_change_rural_dem }
			add_to_variable = { Demographic_Shift_urban_dem_Weeks = USA_week_change_rural_dem }
			add_to_variable = { Demographic_Shift_black_dem_Weeks = USA_week_change_rural_dem }
			add_to_variable = { Demographic_Shift_hispanic_dem_Weeks = USA_week_change_rural_dem }
			add_to_variable = { Demographic_Shift_minority_dem_Weeks = USA_week_change_rural_dem }
			add_to_variable = { Demographic_Shift_union_dem_Weeks = USA_week_change_rural_dem }
			add_to_variable = { Demographic_Shift_nativists_dem_Weeks = USA_week_change_rural_dem }
		}
	}
As for chase.rog.12 and chase.rog.30, those two just need something to actually trigger them.

**Comment by runelead00** [comment]
Fixed in Dev Build, also 30 is intended to be skipped because no one requested properly loc for it
