### ISSUE TITLE
USA - Revolt of the Generals Decision Bug

### ISSUE THREAD

**Issue by Angelblue1852** [TNODevs/TNO-Bug-Tracker#2980]
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.5.0 The Ruin

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The event for MCS to Enforce her will on the Revolt of the Generals is bugged, as the event never calls up the follow up event.
This is due to the event trying to call up event rog.29 instead of chase.rog.29

### Steps to reproduce / Cause of the issue

1.Play as USA
2.Elect MCS in 68
3.Tick off the generals and get the revolt of the generals.
4.Finish the Military tree and unlock the decision.
5. Take the decision, the 2nd event doesn't fire.

### Expected behaviour

The event chase.rog.29 to fire when the 1st event's call is done.

### Additional information

country_event = { #Enforce control by force
	id = chase.rog.43
	immediate = { log = "[GetDateText]: [Root.GetName]: event chase.rog.43" }
	title = chase.rog.43.t
	desc = chase.rog.43.desc
	is_triggered_only = yes
	fire_only_once = yes
	option = { #Fuck yeah
		name = chase.rog.44.a
		add_political_power = 75
		hidden_effect = {
			country_event = { id = **rog.29** days = 1 }
		}
	}
}
Error is here. Didn't spot this till I tested it.

**Comment by runelead00** [comment]
Fixed in Dev Build
