### ISSUE TITLE
NGA/BFR/NNG/CHD/CHF - As Cameroon civil war powers, they don't inherit CAO's technologies

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2982]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

NGA,BFR,NNG,CHD,CHF
as powers of civil war, these tags supposed to inherit CAO's technologies, but they didn't - in fact, they dont even have any basic technologies, even no 1936 rifles
that's probably why Cameroon civil war always stuck

### Steps to reproduce / Cause of the issue

Here's way to fix
in event cao.100
add"**inherit_technology = CAO**" for NGA/BFR/NNG/CHD/CHF

### Expected behaviour

These tags can share techs correctly

**Comment by runelead00** [comment]
Fixed in Dev Build
