### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by stopmakingmemakeaccounts** [TNODevs/TNO-Bug-Tracker#2984]
### Operating System

Windows 11

### HOI4 version

1.13.7.1

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT

### Describe the bug

Every playthrough, even when non-socialists win in the Dominican Republic, Cantave coups the Haitian government, eventually his portrait turns into the default soldier lineart.

### Steps to reproduce / Cause of the issue

1. Start as the US
2. Win the Puerto Plata invasion
3. Set the united front to defeat the communists
4. wait for the cantave coup event to fire

### Expected behaviour

Haitian elections to continue as normal, since the communist putsch did not happen

**Comment by runelead00** [comment]
Fixed in Dev Build
