### ISSUE TITLE
Economy system - A logic bug for law "Count Our Pennies"

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2986]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

the cosmetic effect of "Count Our Pennies", is directly reduce inflation rate, if someone has 6% inflation, it will go 4.8% after enable, and return to 6% after disable
but this gonna make a problem, it just directly decrease inflation, if the country has gained extra inflation during this time, this extra inflation will increase together if disable Count Our Pennies
for example, this country i just mentioned now has 4.8% inflation
but get 1% more inflation because of focus or event, the inflation become 5.8%
and when disable Count Our Pennies, inflation will be 5.8 / 0.8 = 7.25% - and it supposed to be 7%
this also work when event reduces inflation

### Steps to reproduce / Cause of the issue

here's suggestion to fix
change the principle of "Count Our Pennies", when enabled, create a var same with basic inflation, and make it divided by -5
then use clamp_var to limit it to a range of 0 to -3, multiply it by the activity rate, finally add it to final inflation rate

### Expected behaviour

Count Our Pennies no longer influence late added inflation

**Comment by runelead00** [comment]
Do you have any evidence of this issue actually happening? That's not how the central bank code works.

**Comment by MrStraws114514** [comment]
> Do you have any evidence of this issue actually happening? That's not how the central bank code works.

can't reproduce anymore, i remember it just happen in 1.5.0 or 1.5.0a, sorry
