### ISSUE TITLE
USA - Chep still becomes president even if Hart wasn't reelected in 1972

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#2989]
### Operating System

Windows 11

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14380957/game.log)

### Describe the bug

In this runthrough, Hart was elected in 1968 then Schlafly was elected in 1972. However, the event for Hart's death still fires and Chep becomes president

### Steps to reproduce / Cause of the issue

1. Set the game rules where an NPP candidate wins in 1964, Hart wins in 1968, and an NPP candidate wins in 1972.
2. Wait

### Expected behaviour

The Hart death event should not fire if Hart wasn't reelected in 1972

**Comment by runelead00** [comment]
Fixed in Dev Build
