### ISSUE TITLE
Kaya Japan - Typo in the event 'Cutting Out the Disease'

### ISSUE THREAD

**Issue by kolebaby12** [TNODevs/TNO-Bug-Tracker#299]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: Latest
- Any other mods in use: No

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
In the event, on the third row, it says "Japanfor" instead of (presumably) "Japan for".
this is minute but i have nothing better to do and i figure why not report it.
- [ ] 1. 
(Screenshot here)

![20211124164216_1](https://user-images.githubusercontent.com/94831964/143269725-b136fe9b-7973-4e0b-ba23-dbe18dea4af0.jpg)

**Comment by runelead00** [comment]
Fixed in Current Release
