### ISSUE TITLE
NOR - The aftermath of German Civil War and coup didn't happen

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2993]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

the year is 1973, Boreman won civil war, but nothing happened on Norway, it still keeps situation in 1962, and Germany didn't invite it back to faction
![Screenshot_20240225_210835_com idreamsky buff](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/7c0e1380-59c3-4424-8be1-f68b5aafb970)

![b46886b96815857f7f197d3d423294e0](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/dd676059-92bf-40be-b421-ab7b02277123)

### Steps to reproduce / Cause of the issue

if Germany civil war ends too fast(even faster than 29 days),  the final focus of NOR "nor_for_an_efficient_future" will be not able to finish, because german_civil_war global flag will be cleared when civil war ends, and focus will be canceled due to preconditions are not met
the possible way to fix is remove this auto-cancel limit or shorter the focus time

### Expected behaviour

NOR's final focus will be able to finish

**Comment by runelead00** [comment]
Fixed in Dev Build, although the only possible way I believe the GCW can end in under a month is some amount of cheating which we obviously don't support issues that arise from use of console
