### ISSUE TITLE
State of Guangdong - Typo

### ISSUE THREAD

**Issue by silverbugreporter** [TNODevs/TNO-Bug-Tracker#2994]
### HOI4 version

Stella Polaris v1.13.7.1e05 (6100) (S)

### TNO version

v1.5.0b "The Ruin"

### Do you have other mods in use?

2WRW v1.5.0b - Global Conficts: World In Flames

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, AAT

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/8c7e88ae-0bc4-4c83-ad47-a45376b481ce)
"The" is written twice

### Additional information

Minor issue

**Comment by runelead00** [comment]
Fixed in Dev Build
