### ISSUE TITLE
West African countries - Former Free French puppets and territories remain blue

### ISSUE THREAD

**Issue by silverbugreporter** [TNODevs/TNO-Bug-Tracker#2996]
### Operating System

Windows 11

### HOI4 version

Stella Polaris v1.13.7.1e05 (6100) (S)

### TNO version

v1.5.0b "The Ruin"

### Do you have other mods in use?

2WRW v1.5.0b - Global Conficts: World In Flames

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, AAT

### Describe the bug

Former Free French puppets and territories are still blue even after the French Reconciliation and the formation of the West African Federation.

### Steps to reproduce / Cause of the issue

1. The French State should go the "Clerical Fascist" path, join Einheitspakt, then collapse into a civil war
2. The French Community, The West African Alliance, and the Pan-African Liberation Front should be formed in West Africa.
3. Free France should win the West African War, and make all of West Africa (excluding Cameroon) to be its puppets.
4. The French Resistance should win the French Civil War, and the Free French exiles should return.
5. After the French reconciliation, the West African Federation (an alliance) should be formed. Check if the country colours have changed

### Expected behaviour

West African countries should have its own colour instead of France's color.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/c1b35b8b-807f-472b-9d7b-25ba66c6b142)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/f03db56e-dac7-4210-85cb-c9adb05dfa6b)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149180500/3f9de115-9535-4a38-bea0-cacb7f7f8ba8)
(Successor to Gaulle after his death)

**Comment by runelead00** [comment]
Fixed in Dev Build
