### ISSUE TITLE
Germany (Bormann) Danish island of Bornholm is not cored after integrating Denmark

### ISSUE THREAD

**Issue by Lipad45** [TNODevs/TNO-Bug-Tracker#30]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.7
- TNO Version: 1.1.2a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
After using the Grossraum Kontinentaleuropa decisions to intergrate and annex Denmark the Danish island of Bornholm is not German cored while the rest of Denmark is. 

**Steps to Reproduce/Cause Issue:**

1. Win the German civil war as Bormann and when retaking Denmark make sure to establish Denmark either as a reichskommissariat or something along those lines to ensure integration into the Reich
2. get past the first dismantlement (either militarist or reformist.)
3. complete "The Modern Wunderwaffe" focus and use the Grossraum Kontinentaleuropa decisions to integrate Denmark into the Reich until its integration status is "complete"
4. continue down the "The Modern Wunderwaffe" and complete the focus "Our Eternal Hegemony" which will give Germany the decision to integrate Denmark among the Grossraum Kontinentaleuropa decisions.
5. select the 'Integrate Denmark" decision and wait 30 days.
6. after the decision ends all of Denmark will be annexed and cored except for the island of Bornholm which is only annexed as seen in the screenshot where it is still treated as an occupied territory.

**Screenshots:**
![tno bornholm](https://user-images.githubusercontent.com/88467629/128279683-1979700c-833a-4be9-ae35-0cb0d076336f.png)

**Comment by ModdingAccount** [comment]
Issue fixed in dev build.
