### ISSUE TITLE
USA - Move "Eastern Gibraltar" Political Demographic Effects to Affected Tags

### ISSUE THREAD

**Issue by Kurgis** [TNODevs/TNO-Bug-Tracker#300]
**Description of Suggestion:**

Can all of these political restructurings happen inside of an event within their own country instead? Just two new events for Malaya and Shonan that do those things themselves, I'd like to instead know what this means politically for the tag I'm playing as, but information is lost. Even some text like "this will give democratic movements more influence", something I'd actually like to know, gives way more information to the player than the current mess of statistical change.
![Eastern Gibraltar](https://user-images.githubusercontent.com/35203040/143333306-5a1e4297-8825-4213-ab34-ac22d6415df1.png)

**Reasoning Behind Suggestion:**
I have zero clue if this event is effecting me well politically or not, I know there's a later event which gives political effects afterwards, but important details such as nations getting events gets lost in the details.

**Additional Information:**
Game ver: 1.2.0d

**Comment by runelead00** [comment]
I've hidden most of the tooltip to be less of a mess for UB
