### ISSUE TITLE
São Tomé and Príncipe thing

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3000]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Add cores for Iberia to São Tomé and Príncipe.

### Justifications

Both Cabo Verde and São Tomé and Príncipe have the same pop (Mestiço) but Cabo Verde is the only one what cored. If Mestiço is intended to be a colonization term, so then São Tomé and Príncipe must be cored as well. But if it's a mistake, so both ones mustn't have cores at all.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/05db0346-cd2e-4826-8b93-549124c92b1b)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/bf2ade95-333f-4741-957c-06d064277982)

**Comment by runelead00** [comment]
Fixed in dev build, cabo verde is no longer a core
