### ISSUE TITLE
USA -  Power project on the North Sea

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3001]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

The US should have a power project on the North Sea when HMMLR joins the OFN.

### Justifications

The Shetland islands and East British coasts cover the North Sea and it's enough to have a power project on it.

**Comment by runelead00** [comment]
Fixed in Dev Build
