### ISSUE TITLE
DEN - Claims/Cores on the Faroe, Greenland and Iceland islands

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3002]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

To add claims/cores on  the Greenland, Faroe and perhaps Iceland islands for Denmark.

### Justifications

Denmark should consider them as its own territories because it wouldn't recognize American proxy states and an occupation of Greenland by the US. If it recognizes as independent ones so no questions.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/1171728e-4075-48f4-8c0c-a7882f78ae32)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/b303dfb7-7ec3-4af8-9342-62719003aa93)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/d8ffeb6c-2561-409f-9f64-2650e79dad14)

**Comment by runelead00** [comment]
Rejected. Doesn't make any sense in lore and the danes have pretty much accepted that they're never getting those islands back 15 years on from the war
