### ISSUE TITLE
ROM - Dealurile Nistrului issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3006]
### Operating System

Windows 10

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

If Romania gets Dealurile Nistrului, Pridnestrovia (both the Administration between the Dniester and Bug and Pridnestrovian Republic) still has core on this region.

### Steps to reproduce / Cause of the issue

1. Penescu must retire for the Pridnestrovian Republic. Otherwise keep him in charge.
2. Choose Rațiu or Zane for the Pridnestrovian Republic OR choose Penescu or Fărcășanu for the Administration between the Dniester and Bug.
3. Wait until 1969.

### Expected behaviour

Pridnestrovia should lose core on Dealurile Nistrului no?

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/70fe67f5-5d2c-4b6f-af0f-f2baaa2d704e)

**Comment by runelead00** [comment]
Fixed in Dev Build
