### ISSUE TITLE
OST - Incorrect long name for Balticher Bund

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3007]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Balticher Bund's long name is the Baltic Federation instead Balticher Bund. I think its short name should be the Baltic Federation as well. 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/8afd33e9-a2e4-4354-b799-34320b5b453a)

**Comment by runelead00** [comment]
Fixed in Dev Build
