### ISSUE TITLE
IRE - Post-Lemass elections bug

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3008]
### Operating System

Windows 10

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Lynch or other democratic elected Taoiseaches wins, it sets No Elections for Ireland.

### Steps to reproduce / Cause of the issue

1. Investigation failure - Negotiation successful
2. Lemass retires.
3. Fianna Fáil or National Coalition wins the elections.

### Expected behaviour

It should not set No Election, just move election dates to another time.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/2a0cd819-044a-486a-8401-219d1fc4c021)

**Comment by runelead00** [comment]
Fixed in Dev Build
