### ISSUE TITLE
CAN - Elizabeth in Exile bug

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3009]
### Operating System

Windows 10

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Despite pro-Elizabeth party wins the elections in the United Kingdom, Canada still has the Elizabeth in Exile national spirit.

### Steps to reproduce / Cause of the issue

1. HMMLR victory.
2. The US wins in the Channel Crisis.
3. Any party but socialist one comes to power.

### Expected behaviour

Canada should lose the Elizabeth in Exile national spirit.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/380fc021-0dd5-42d2-bd82-2ab0c394c691)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a7689dbd-680e-4136-8324-335885c320c0)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thank you
