### ISSUE TITLE
Kanem (KNM) - Ridiculously High State GDP 

### ISSUE THREAD

**Issue by usacaesar** [TNODevs/TNO-Bug-Tracker#301]
- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: TNO Radio
- Were you using Steam? Yes
- Which expansions do you NOT have? MTG, La Resistance, Battle for Bosphorous, No Steps Back

**Longer Description of Issue:**

Around 1969-1970, KNM gets a ridiculously high GDP in one of its states, Mousorro.

**Steps to Reproduce/Cause Issue:**

1. Play TNO until 1970

![image](https://user-images.githubusercontent.com/88407654/143366983-51ac1461-be83-4c94-92b7-a776ad2df72b.png)
![image](https://user-images.githubusercontent.com/88407654/143367010-10ba0662-c22e-42c9-9952-9bdffeb82874.png)
![image](https://user-images.githubusercontent.com/88407654/143367046-785efad6-953f-4bd9-a197-f12f4b357ec6.png)
![image](https://user-images.githubusercontent.com/88407654/143367055-9a62a937-4406-4750-ad4a-c06d67d225f9.png)

**Comment by Stormeagle449** [comment]
Fixed a long time ago.
