### ISSUE TITLE
Italosphere - Weird extra spaces between effects and titles

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3010]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

There are extra spaces between the titles and effects in both Italosphere in the OFN and Italy in the OFN (both Italian and American variants) national spirits.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e252184a-9a7f-48e9-95fa-78d816afac0c)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/667ad9fa-54b5-4d71-b197-5f047f080ba7)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/82d2515b-5156-427b-983f-1695ea9f0b4c)

**Comment by runelead00** [comment]
Base Game issue with dynmods
