### ISSUE TITLE
ITA - Oil crisis tree pops up in 1969

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3011]
### Operating System

Windows 10

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

For some unknown reasons Italy gets the OC tree in 1969.

### Steps to reproduce / Cause of the issue

Wait until late-1969.

### Expected behaviour

Italy should get it when the Oil Crisis begins.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/c7f3e700-8d7c-47c6-9eb5-8534c6440a2a)

**Comment by runelead00** [comment]
We are not currently supporting old Italy content
