### ISSUE TITLE
ITA - 1970 Elections bug

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3019]
### Operating System

Windows 10

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The game says the elections must be held  in June 1970 but they do in August 1969 actually.

### Steps to reproduce / Cause of the issue

Italy must be democratized and not be overthrown.

### Expected behaviour

The elections must be held as it's intended in June 1970.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a2c168a1-ac9c-47b9-b231-b434fb44ba9b)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/5febc0d8-8df9-42ea-9d91-fa9bc64a220a)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/490c24e2-2072-4e1a-bb7b-e722a8fc26ab)

**Comment by runelead00** [comment]
We are not supporting old italy content
