### ISSUE TITLE
USA - Toolbux Localization Issues

### ISSUE THREAD

**Issue by Kurgis** [TNODevs/TNO-Bug-Tracker#302]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use:
    Death or Dishonor
    Waking the Tiger
    Man the Guns
    La Resistance
    Battle for Bosporus

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [x] 1. I believe this is meant to be "occurred", rather than "occuied".
![occuied](https://user-images.githubusercontent.com/35203040/143370292-dd9c71ef-1607-4893-bb8b-0832c0c53007.png)

- [x] 2. This should be "a healthy society". `USA_lbj_64_national_humanities`
![helth](https://user-images.githubusercontent.com/35203040/143764252-89498021-f986-416c-b2ad-efebb63f9e72.png)

- [x] 3. 1980 Battleship tech, "tried" into "tries".
![tries](https://user-images.githubusercontent.com/35203040/144233284-ff2caf64-dc78-4b9b-9293-2fbaec2a160e.png)

**Comment by runelead00** [comment]
Fixed on UB
