### ISSUE TITLE
GRO - Wrongly show closing screen when annexs COG and ANG

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#3024]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

both SAFWAR.38 and SAFWAR.39 have this code problem
this is event SAFWAR.38, it is fired by COG and let it get annexed by GRO
![8CI56Y$R}HV H(CR{YNQ $6(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/f2fb444a-3a76-4cd5-b109-4ac60d49519d)
the 2nd option transfer players to GRO and show closing screen for GRO, and this option with full AI factor
that means GRO players will wrongly get closing screen when annexs COG and ANG

### Steps to reproduce / Cause of the issue

simply remove these 2 events' effect will let ANG and COG have no way to get ending screen to tell players all content ended
I personally suggest to move closing screen showing effect to event SAFWAR.23, this event is Huttig independence trigger

### Expected behaviour

GRO no longer get closing screen when annexs COG and ANG

**Comment by runelead00** [comment]
Fixed in Dev Build
