### ISSUE TITLE
Iceland - No Long Country Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3026]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

TNOwiki points out Iceland has a long country name but it is not displayed in game itself.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/6facd5e1-bbc2-48e4-8323-d803cd928432)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/48df4902-5fa4-45d4-8e7a-ba2be69b2435)

**Comment by runelead00** [comment]
This wiki is incorrect, Iceland's official legal name is just Iceland
