### ISSUE TITLE
Canada - No Long Country Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3027]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Canada is supposed to be named as the Dominion of Canada according to official wiki.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/38c5fd59-1c72-4850-87a5-3e3caa6052ee)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/f1b4920f-1393-4bc9-abb4-2ff74cc5579f)

**Comment by runelead00** [comment]
The Wiki is wrong, the full legal name of Canada is Canada
