### ISSUE TITLE
Azandeland/Zaire-An issue about capital city 

### ISSUE THREAD

**Issue by 1umtu** [TNODevs/TNO-Bug-Tracker#3029]
### Operating System

Win 11

### HOI4 version

1.13.6

### TNO version

1.15.0

### Do you have other mods in use?

No other mods 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA, AAT

### Describe the bug

Azandeland's capital not moving to Leopoldville after Congo wins civil war

### Steps to reproduce / Cause of the issue

Play with Japan/Continue to play with Japan/Congolese Civil War happened/send volunteers to Azandeland /Help to azandeland win this civil war/ wait for the forms of Zaire 

### Expected behaviour

Analyzing and fixibg that issue 

### Screenshots

![Screenshot_20231127_161121_com nvidia geforcenow_edit_7850496948800](https://github.com/TNODevs/TNO-Bug-Tracker/assets/149859259/5dd7abc7-566d-4f33-9e16-952064545667)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
