### ISSUE TITLE
Yunnan - Admin options unavailable

### ISSUE THREAD

**Issue by CreativeGrey** [TNODevs/TNO-Bug-Tracker#303]
**Questions**

- Operating System: Linux Mint 19.3
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Player led peace conferences, EAW music mod, State transfer tool
- Were you using Steam?: Yes
- Which expansions do you NOT have?

**Longer Description of Issue:**

When playing Yunnan, during the war against China, the tab to view Admin options on the China map is greyed out.
No other method to make admin decisions for states found.

EDIT: Upon further playing, it seems the real issue is that upon the start of the war, the core states you begin with are stuck at 0% admin efficiency and give the large debuffs. Admin options are not available for these states but became available for states conquered in the course of the war.

**Steps to Reproduce/Cause Issue:**

1. Play Yunnan on Long Yun path until war with China starts

2. Pull up China map and Select state, only military tab will be available, not Admin

**Screenshots:**
When selecting a State
https://steamcommunity.com/sharedfiles/filedetails/?id=2663426220

When Selecting a state on the Map of China, the Admin tab is greyed out in the bottom right
https://steamcommunity.com/sharedfiles/filedetails/?id=2663426147

**Comment by tkgitno** [comment]
Fixed in Dev Build
