### ISSUE TITLE
Speer's Germany in 1973 get's massive boost in revenue

### ISSUE THREAD

**Issue by Tallman310** [TNODevs/TNO-Bug-Tracker#3032]
### Operating System

Windows 11 x64

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

Radio TNO, TNO:CIA, New German Voices

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14475390/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14475391/game.log)

### Describe the bug

At some point in 1973, Germany gains a massive boost in revenue.

### Steps to reproduce / Cause of the issue

1. Have Speer win the GCW
2. Go through the Oil Crisis tree
3. At some point in 1973, I'm not entirely sure what causes it, the economy gains a massive boost in revenue at the expense of GDP growth.

### Expected behaviour

Germany should recover pre-Oil Crisis GDP growth

### Screenshots

![20240303185958_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/124468584/36af4c73-d87b-4f44-9699-d2d98b9e4cd7)
![20240303190037_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/124468584/af4a6246-b292-4d9c-93ec-13b2a4a3a3dd)

**Comment by runelead00** [comment]
Working as Designed, to prevent German economy from breaking after it finishes its content for countries that go longer than 1973
