### ISSUE TITLE
SLO - Incorrect Used Flag

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3033]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Change the current Slovak flag to this one below.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/19327f0c-8214-4c3a-87db-c7b0512762a6)

### Justifications

The current flag was designed in 1992 because of similarity to Russian and Slovene ones. The historical flag of Slovakia was just a tricolor with no coat of arms and used by the Autonomous Land of Slovakia, First Slovak Republic, Slovak Socialist Republic and Slovak Republic from 1990 to 1992 when it was consisting of Czechoslovakia. So I can't see any reasons why Slovakia would change her historical flag in TNO.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/f9b53045-7075-4eca-978b-e5608463b4ec)

**Comment by runelead00** [comment]
Already Fixed in Dev Build
