### ISSUE TITLE
Any Tags - Missing Long Country Names

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3034]
### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

A list of missing long country names taking by me from Offical TNO wiki.

- [ ] 1. Mendi's long country name is the Mendi state. 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/d56cb33b-98b8-4b3d-9d80-14cff19dc175)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/4011a867-8992-446b-8a98-1e3202456c10)

- [ ] 2. Trarza's long country name is either the Islamic State of Mauritania or Islamic State of Trarza (idk why wiki uses different country names for Trarza).
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/44824af8-2671-40b0-833e-4ece011e3105)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/08dbdff8-5d49-4bdc-8c9d-af1d2cb5e949)

- [ ] 3. Orenburg's long country name is the Orenburg Communes.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/f3f54b3b-f8ac-419a-ba07-ef06c83f595d)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/dc9c4775-3d1d-41ef-9221-d36dc5329519)

- [ ] 4. Guyana's true name is British Guyana.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/91f9fd10-5d07-4a4b-8437-13a52a363e83)

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/23b8f581-c5a9-4e06-9890-9aedca996ae0)

- [ ] 5. Yemen's long country name is the Mutawakkilite Kingdom of Yemen.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/99b3feee-6858-40a5-bf39-e05ad5de01a4)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e1f033d3-b87a-49ac-8680-8db96cc1b57b)

Here's list of countries don't have long country names but I didn't find anything about them in wiki.

- [ ] 1. Burba's Orenburg
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/4f77a597-27cd-4697-9a67-4b9deaae59ee)

- [ ] 2. Eritrea
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/48b05790-4cdb-42ec-a1b9-273eae94966d)

- [ ] 3. Somalia
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/c2a87e20-ff7a-4f8a-9e77-4568adaa69cc)

- [ ] 4. Kenya
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/4f15008b-613b-4a7c-a412-d93491d96a2d)

- [ ] 5. Ethiopia

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/8c44cacb-8c9a-41f7-b855-54b082fca17e)

**Comment by runelead00** [comment]
The wiki should not be treated as an absolute source of knowledge that that precedence over the actual mod it's a wiki for
