### ISSUE TITLE
Brazil - Only Vargas Jr succeeds Adhemar in the 1970 elections

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#3036]
### Operating System

Windows 11

### HOI4 version

1.13.3

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

If Adhemar was elected in 1965, only Vargas Jr gets elected in 1970, even if the game rule isn't set to him winning

### Steps to reproduce / Cause of the issue

1. Set game rules to where Adhemar wins in 1965 and anyone other than Vargas Jr wins in 1970

### Expected behaviour

Other candidates besides Vargas Jr should be able to succeed Adhemar

**Comment by runelead00** [comment]
Cant Reproduced

**Comment by PhoneythePhoneSaver** [comment]
I think this was fixed in that hotfix from last month actually
