### ISSUE TITLE
Argentine Occupational Zone in Paraguay and Gobernación de Tierra del Fuego - Both nations still change their flags and color even if Anchorena doesn't lead Argentina

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#3037]
### Operating System

Windows 11

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

Argentine Occupational Zone in Paraguay and Gobernación de Tierra del Fuego both change their color to dark blue and change their flags even if Anchorena didn't take power in Argentina

### Steps to reproduce / Cause of the issue

1. Recommended to set it where Argentina becomes Peronist as this is when I've seen it happen, and set it where Anchorena doesn't succeed Peron. 
2. (optional) Make it so Paraguay goes communist
3. Wait

### Expected behaviour

The Argentine Occupational Zone in Paraguay and Gobernación de Tierra del Fuego should remain light blue if Anchorena hasn't become leader of Argentina

**Comment by runelead00** [comment]
Fixed in Dev Build
