### ISSUE TITLE
CLC/CLL/SAF/CHI/YUN - When tags have been reused after death, their debts are not cleared

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#3038]
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

1. In 2nd colombia war, CLC and CLL these 2 tags will be revived, and declare war to CLD, but they still keep debt in 1st Colombia war
2. In 2nd South African war, SAF will be revived and declare war to BOR and some other warlords, but debts are kept
3. if YUN beaten RGOC(CHI), but soon got beaten by JAP, JAP will release CHI and puppet YUN, without clearing debt

All of these tags will lose a lot of lands when they revive, make debt-to-GDP very high and nuke their state GDP, their debt must be cleared

### Steps to reproduce / Cause of the issue

Add set_variable = { national_debt = 0 } for countries
1.in scripted_effects CCW_Partisans
2.didn't find 2nd SAW's code file, perhaps can add In event file TNO_second_south_africa_war
3.in event japchiinteraction.3

### Expected behaviour

These tags' debt will be removed when they revive

**Comment by Marok132** [comment]
It's a general issue for other tags by the way.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build for those nations.
