### ISSUE TITLE
[Bug]: Black Map

### ISSUE THREAD

**Issue by JR1216** [TNODevs/TNO-Bug-Tracker#3040]
### Operating System

Windows 11

### HOI4 version

1.14.1

### TNO version

1.5.0

### Do you have other mods in use?

Deep Freeze, 2WRW, Last walt of europe, radio tno

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When I loaded up TNO today the map was all black.

### Steps to reproduce / Cause of the issue

1. Launch TNO with the mods I have mentioned

### Expected behaviour

I expected TNO map to load normally

### Screenshots

![20240308102847_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/162726343/ff252eca-e6dd-4923-96e0-76e910bacd20)
![20240308111142_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/162726343/26b8df5a-f6a7-40b0-ad24-62ac786c04aa)

**Comment by silverbugreporter** [comment]
I also have this problem since i relaunched the Paradox Launcher.

**Comment by JR1216** [comment]
Okay I think a mixture of cache cleaning and switching to and from directx11 fixed it. at least for me.

**Comment by runelead00** [comment]
Fixed in Hotfix, TNO was not compatible with latest version
