### ISSUE TITLE
[Bug]: Map is Black not just the See

### ISSUE THREAD

**Issue by LUCA5325** [TNODevs/TNO-Bug-Tracker#3041]
### Operating System

Windows 10

### HOI4 version

1.14.1

### TNO version

1.5.0bb

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA, AAT

### Files

![20240308211420_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/162748953/38a2fbd5-e1ae-4eb7-9308-3abe68806628)

### Describe the bug

the map is black not just the see

### Steps to reproduce / Cause of the issue

IDK i m not in modding stuff

### Expected behaviour

That it gets fix as it wourld be imbosiblie to mico

### Screenshots

![20240308211420_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/162748953/dca75328-9440-4654-b31e-23388887c1de)

### Additional information

i just wantet to play TNO and then dis

**Comment by runelead00** [comment]
Update the mod to 1.5.0c

**Comment by LUCA5325** [comment]
> Update the mod to 1.5.0c

okay works again thanks
