### ISSUE TITLE
USA - 'CIA Begins Training New Operative' event uses the wrong picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3043]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14544774/Logs.zip)

### Describe the bug

When selecting the 'Recruit' button from the foreign policy's Intelligence tab, the 'CIA Begins Training New Operative' event uses the German intel picture instead of the American one. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Select 'Recruit' button to train more agents from the foreign policy's Intelligence tab.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/23f37258-a797-4ac3-9a52-0e3eb41d5535)

**Comment by Stormeagle449** [comment]
Stale issue, we don't use that event anymore.
