### ISSUE TITLE
USA - 'CIA Operative Reports for Duty' event uses the wrong event picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3044]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14544932/Logs.zip)

### Describe the bug

After USA's agent done its training, the 'CIA Operative Reports for Duty' event uses the wrong event picture.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Select 'Recruit' button to train more agents from the foreign policy's Intelligence tab.
3. Agent training complete.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b222100a-925a-41ac-874e-ccb8ccb78b24)

**Comment by Stormeagle449** [comment]
Stale issue, we don't use that event anymore.
