### ISSUE TITLE
USA - 'Begin Close-Air Sorties' decision is not removed after the 'Icarus' event selected

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3047]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_PPI_commence.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14545884/USA_PPI_commence.zip)

### Describe the bug

After selecting the 'Icarus' event and the 'Begin Close-Air Sorties' decision is not selected, the 'Begin Close-Air Sorties' decision is still appear and not able to get removed, which means that DOM will get debuff national spirit despite the 'Icarus' event selected. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. The PPI triggers.
3. 'Prepare USN Naval Support' and 'Authorize Air Support' decisions selected.
4. PPI landing.
5. 'Begin Close-Air Sorties' decision is not selected.
6. The Icarus event triggers.

### Expected behaviour

Forgot to remove the decision that it should not supposed to. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/57a20ab7-7a6c-4f17-8461-e13a3023859c)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4da932e9-0acf-49de-9c20-eaaaa2e307e1)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/12625db7-e732-44c5-bbcc-0381f0349248)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
