### ISSUE TITLE
ROM - ROM_michael_the_brave national spirit name is not localize

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3048]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

`ROM_michael_the_brave` national spirit name is somewhat not localize. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. See ROM's national spirits.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/40b76735-e447-4e91-bfa3-d5e0d67bd47b)

**Comment by runelead00** [comment]
Fixed in Dev Build
