### ISSUE TITLE
USA/HAI - The 'Renewed Haitian Sovereignty' national spirit appear when the HCW starts

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3049]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14548286/Logs.zip)

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14548285/USA_play.zip)

### Describe the bug

The 'Renewed Haitian Sovereignty' national spirit suddenly appears for Haiti when the HCW triggers.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI starts.
3. Trujillo overthrown.
4. USA continues to support the Legion.
5. The Caribbean Legion victory in DCW.
6. Socialist/Communist Revolution in the Dominican Republic.
7. The HCW starts.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/beba7cd8-88c8-43cd-8f89-460b97f05845)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/600512e4-7264-485c-9dc6-d4346091f3e0)

**Comment by runelead00** [comment]
Issue with war ending immediately, already reported
