### ISSUE TITLE
USA - Capitulating the West African Union in the Mano Campaign Crashes the game

### ISSUE THREAD

**Issue by Objclaro** [TNODevs/TNO-Bug-Tracker#305]
**Questions** Is the Mano campagin supposed to be unwinnable for the USA or is there some sort of scripted peace deal that never fired?

**- Operating System:** Windows 11 Home Single Language (Version 21H2)
**- HOI4 Version:** 1.10.8
**- TNO Version:** 1.2.0.c
**- Any other mods in use:** Radio TNO: Music of the New Order, The Spot Optimization Mod, Music no Sekai, The Moe Order: Last Episodes of Anime, Wolfenstein Music
**- Were you using Steam?** Yes
**- Which expansions do you NOT have?** Battle of the Bosphorus, No Step Back

**Longer Description of Issue:**
During my LBJ-MCS USA game Cameroon came out on top of the 3 way west african war. During the oil crisis they decided to invade Liberia, so I sent 3 divisions to go and win the war. Mendi fell pretty quickly so it ended up being my 3 voluntieers and the Liberia VS the rest of West Africa. I just waited for the Pan-Africanists to waste all of their supplies attacking my troops so I could go in encircile their troops and then snake the vp's of the vrious pan african nations. But when I got over to Cameroon and capitualte it's a garanteed crash.

**Steps to Reproduce/Cause Issue:**

1. Intervene in the Mano Campaign as the USA

2. Let Mendi fall

3. Capitualte all West African nations except Cameroon

4. Capitulate Cameroon

5. Game should crash

**Screenshots:**

![2021-11-24 (8)](https://user-images.githubusercontent.com/75542088/143379939-b6c43822-2095-488b-a89d-3b7ffbfc8fc2.png)

![2021-11-24 (9)](https://user-images.githubusercontent.com/75542088/143379959-3a064eee-c358-41ff-8b64-2e5201b61333.png)

**Game Saves and Log Files, if possible:** Zip file of an autosave I used to get the screenshots shown
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7600219/autosave.zip)

**Comment by Fenneru** [comment]
Same issue here and I'm not using the anime submod or anything else like that.

**Comment by Ceyboard** [comment]
Same issue here. No other mods or submods, just TNO. Near-Identical to OP. 
I wonder if there's even a set outcome or if it's just an error thing.

**Comment by ArHaefs** [comment]
Same Issue here.
Only Radio TNO submod
Mendi fell
I slowly capitulated West African union allies one by one
Game Crash everytime they capitulate

**Comment by ArHaefs** [comment]
Tag switching to Liberia shows that it triggers a peace conference. Probably not intended for Liberia to win this war, so TNO crashes because of that?

**Comment by Stormeagle449** [comment]
Fixed in current build.
