### ISSUE TITLE
CCP - A list of possible gamerules.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3051]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Add next gamerules, please:

- [ ] 3. The Republic of Nigeria - Economic Sphere (A_SPRING.22)
- [ ] 8. Iberia - Legionary Uprising Outcome
- [ ] 9. Free France - Reclamation
- [ ] 11. Lavaud's Haiti - Fate of Democratization (check TNO_HAI_civil_war_HAI_victory_crushed)
- [ ] 16. Armenian Revolt - Victors.
- [ ] 17. COMECON - Founder
- [ ] 18. Russia - Peaceful Superregional Unification (Russia/Siberia)

### Justifications

3. It lets  Nnamdi Azikiwe's Nigeria to join the West African Zone's economic sphere or stays neutral.
7. It lets Tanganyika and Zanzibar to create Tanzania (triggers only if the OFN East African Mandate collapses).
8. Either Iberia wins and restore control Algeria or Legionary Algeria fends off and stays independent (it happens when Salazar dies)
9. It lets to choose who will win in the Reclamation; either it'll be Free or Vichy France.
10. 
11. 16. It's two-side war between Armenian revolutionaries and Turkey with several outcomes.
17. The gamerule lets to choose which communist Russian warlord will found the COMECON; The Far Eastern, West Russian or West Siberian one.
18. There is a gamerule for peaceful regional unification between West Russian and West Siberia/Central Siberia and Far East but there isn't a similar gamerule for Russia/Siberia.

**Comment by ThePikminCaptain** [comment]
There is a game rule for peaceful unification at the super regional stage, it’s the national unification rule
