### ISSUE TITLE
WRS - CTD in 1965

### ISSUE THREAD

**Issue by IosifSilinov** [TNODevs/TNO-Bug-Tracker#3052]
### Operating System

Windows 10

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

{"game":"hoi4","name":"TNO","mods":[{"displayName":"Radio TNO : Music of The Radio Peking","enabled":false,"position":0,"steamId":"2455684260"},{"displayName":"The New Order: Cheat Mod+","enabled":false,"position":1,"steamId":"2388101337"},{"displayName":"The New Order: Cheat Mod++","enabled":false,"position":2,"steamId":"2606510574"},{"displayName":"新秩序：欧洲末日","enabled":true,"position":3,"steamId":"2438003901"},{"displayName":"The New Order: Last Days of Europe(CN.Ver)","enabled":true,"position":4,"steamId":"2243912940"},{"displayName":"TNO - Brave New World [OUTDATED]","enabled":false,"position":5,"steamId":"2514593219"},{"displayName":"TNO Disable Nukewar","enabled":true,"position":6,"steamId":"2185416592"},{"displayName":"tno社会发展作弊mod","enabled":true,"position":7,"steamId":"2309654066"},{"displayName":"Kamchatka:The Pacific Fleet for TNO(CN.Ver)","enabled":false,"position":8,"steamId":"2464424847"},{"displayName":"TNO The New Order: Mr Göring's Wild Ride","enabled":false,"position":9,"steamId":"2251001951"},{"displayName":"TNO: Custom Country Paths","enabled":false,"position":10,"steamId":"2738949889"},{"displayName":"Radio TNO : Music of the Liberal China 自由中国电台","enabled":false,"position":11,"steamId":"2452574680"},{"displayName":"新秩序：东方红 The New Order:The East is Red","enabled":false,"position":12,"steamId":"2781363716"},{"displayName":"TNO: ECONOMIC CHEAT","enabled":false,"position":13,"steamId":"2687000267"},{"displayName":"Toolpakt: Toolpack for TNO","enabled":true,"position":14,"steamId":"2700327893"},{"displayName":"TNO Air Assault","enabled":true,"position":15,"steamId":"2718912113"},{"displayName":"bigger counter for TNO","enabled":true,"position":16,"steamId":"2513520989"},{"displayName":"可以发送更多的志愿军","enabled":true,"position":17,"steamId":"2890823448"},{"displayName":"TNO坦克设计拓展","enabled":true,"position":18,"steamId":"2840691184"},{"displayName":"TNO More Tank Slots + Tank Module","enabled":false,"position":19,"steamId":"2842324948"},{"displayName":"The New Order: Roter Morgen","enabled":false,"position":20,"steamId":"2909300709"},{"displayName":"Historical Tank gun name","enabled":false,"position":21,"steamId":"3003498172"},{"displayName":"Light from Lake Baikal","enabled":false,"position":22,"steamId":"2833083239"},{"displayName":"新秩序：大雷雨行动","enabled":true,"position":23,"steamId":"2863215782"},{"displayName":"TNO: Second West Russian War","enabled":false,"position":24,"steamId":"2980739000"},{"displayName":"The New Order: Operation Deep Freeze","enabled":false,"position":25,"steamId":"2719053325"},{"displayName":"新秩序：深冻行动简体中文汉化","enabled":false,"position":26,"steamId":"2948065390"},{"displayName":"新秩序：鹿鸣河","enabled":false,"position":27,"steamId":"3013237827"},{"displayName":"[OUTDATED] The New Order: Last Days of Europe","enabled":false,"position":28,"steamId":"2173766180"},{"displayName":"TNO Italy Submod","enabled":false,"position":29,"steamId":"2350267172"},{"displayName":"TNO经济修改","enabled":true,"position":30,"steamId":"2739151728"},{"displayName":"更多建筑槽位（TNO适用）","enabled":true,"position":31,"steamId":"2846027552"},{"displayName":"TNO修改器&作弊菜单  By  Crys7aL_L1nE","enabled":true,"position":32,"steamId":"2847981333"},{"displayName":"Toolpakt: Toolpack for TNO(CN.Ver)","enabled":true,"position":33,"steamId":"2997152402"},{"displayName":"tno经济作弊","enabled":false,"position":34,"steamId":"2706079012"},{"displayName":"TNO Achievements","enabled":false,"position":35,"steamId":"2895075046"},{"displayName":"TNO: Allegiances Submod","enabled":true,"position":36,"steamId":"2897376278"},{"displayName":"10 Support Companies for TNO","enabled":true,"position":37,"steamId":"2816263161"},{"displayName":"Supply hub cost 3000 - Tno Version","enabled":true,"position":38,"steamId":"2844022903"},{"displayName":"TNO：军火贩卖 & 经济扩展","enabled":true,"position":39,"steamId":"2990602166"},{"displayName":"+++Easybuff - The New Order","enabled":true,"position":40,"steamId":"3015271507"},{"displayName":"[OLD]The New Order: Last Days of Europe (TT2, 1.11)","enabled":false,"position":41,"steamId":"2969900850"},{"displayName":"TNO：第二次西俄战争 GPT汉化 TNO: Second West Russian War CN.Ver","enabled":false,"position":42,"steamId":"2989705802"},{"displayName":"[OLD] TNO: Brave New World","enabled":false,"position":43,"steamId":"3053939042"},{"displayName":"TNO Cheat Decisions","enabled":false,"position":44,"steamId":"2787480450"},{"displayName":"TNO: 允许建造工厂","enabled":false,"position":45,"steamId":"3028064671"},{"displayName":"10 Dockyards for capital ships","enabled":false,"position":46,"steamId":"2872909333"},{"displayName":"TNO支援连不减组织度","enabled":true,"position":47,"steamId":"3008272202"},{"displayName":"The New Order允许西俄革释放傀儡","enabled":false,"position":48,"steamId":"3013331235"},{"displayName":"TNO Generals 24 Divisions Limit","enabled":true,"position":49,"steamId":"3012599902"},{"displayName":"The New Order - 戈林扩展","enabled":false,"position":50,"steamId":"3023597061"},{"displayName":"TNO - Goering Expanded(MOVED!)","enabled":false,"position":51,"steamId":"3019781125"},{"displayName":"TNO-集结红军指战员","enabled":true,"position":52,"steamId":"2529394054"},{"displayName":"TNO法令政策修改","enabled":true,"position":53,"steamId":"2740537368"},{"displayName":"TNO USA Election super cheat","enabled":false,"position":54,"steamId":"2879375481"},{"displayName":"TNO 召回德国退役/已寄将领","enabled":true,"position":55,"steamId":"3044043908"},{"displayName":"TNO More Unit CN","enabled":false,"position":56,"steamId":"2776179007"},{"displayName":"将领修改器","enabled":true,"position":57,"steamId":"2904967963"},{"displayName":"【新秩序：欧洲末日】冰儿の作弊与汉化模组合集","enabled":true,"position":58,"steamId":"3111563097"},{"displayName":"The New Order: Unfinished Businesses (BACKUP)","enabled":false,"position":59,"steamId":"3075337768"},{"displayName":"铁路无需转化","enabled":false,"position":60,"steamId":"3050718147"}]}

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[hoi4_20240310_220943.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14550513/hoi4_20240310_220943.zip)
[WRS_1965_04_01_02.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14550518/WRS_1965_04_01_02.zip)

### Describe the crash

The game crashes at 1:00 am, April 6, 1965, when I play WRS and goes back to the desktop.

### Steps to reproduce / Cause of the crash

1. Go to the "logs" file in hoi4_20240310_220943.zip.
2. Click error.log.
3. Scroll down to the last lines with [22:09:43][1965.04.06.01].
4. See error.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by IosifSilinov** [comment]
So when can the Dev Build be released?

runelead00 ***@***.***> 于2024年3月11日周一 09:06写道：
