### ISSUE TITLE
Any Tags - QoL Proposals.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3054]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

- [ ] 3. Give An economy for Germany extra effects that transfer some PUs and GPD growth to Germany.
- [x] 4. Serbia should be named as the Kingdom of Serbia if Peter 2 returns. 
- [ ] 5. Make Davao as a capital of the Free Philippine Republic when ceasefire happens and it remains Southern Philippines only.
- [x] 6. Change a country color from dark gray to dark green for Ireland.
### Justifications

3. According to the An economy for Germany national spirit the Dutch economy is fully used by Germany. I think it's reasonable to add those effects to show that Germany gets benefits from it actually.

4. Serbia declares as a kingdom itself and invites Peter 2 to return. It's reasonable if they return old country name as well.

5. Cagayan de Oro looks like a random-picked capital by a game. I guess the Philippines' capital should be Davao because it's the largest city in the Philippines and I can't see any reasons why they could ignore the city.

6. Ireland's country color is too gray and it's similar to ones that are used by German RKs. Previous dark green colors looked better.

### Screenshots

3. 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/61b5409d-406b-4c82-86ed-ddc273e21602)|

5. 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/f52f14ad-3a72-49fb-84f1-7698ba75d9d0)

6. 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/ecfafe9f-082d-42ed-9fee-21550a9ab4b1)

**Comment by runelead00** [comment]
Fixed 4, rejected 6,
