### ISSUE TITLE
MST - No Cored States.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3056]
### Operating System

Windows 10

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Vereinigte Ostlandliga wins in Ostland, it doesn't core states.

### Steps to reproduce / Cause of the issue

Vereinigte Ostlandliga must win.

### Expected behaviour

Vereinigte Ostlandliga should core the states.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e9412cb0-0419-4649-99b3-d9f81842bbe2)

**Comment by runelead00** [comment]
Fixed in Dev Build
