### ISSUE TITLE
Haiti/USA - Lavaud choice event option effects flipped

### ISSUE THREAD

**Issue by CursedAuroran** [TNODevs/TNO-Bug-Tracker#3059]
### Operating System

Endeavour OS

### HOI4 version

1.14.1

### TNO version

v1.5.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The options following the Lavaud coup in haiti are swapped, with the decision opening up political reforms being labeled as supporting the coup in the code and blocking fignole from coming to power, and the decision opening up stronger military support and letting lavaud do his thing being labeled as pressuring for civilian government in code and enabling fignole coming to power

### Steps to reproduce / Cause of the issue

1. let the DR win in the peurto plata invasion
2. wait for lavaud to coup

### Expected behaviour

Pressuring Lavaud for civilian government and political reform shouldn't lock out a reformist candidate and the opposite shouldn't enable a reformist candidate

### Screenshots

![Screenshot_20240311_173921](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/280e3394-4320-436a-9695-851e877d5716)
![Screenshot_20240311_173854](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/409a3072-d9a5-45da-bfc1-b5ce70798183)
![Screenshot_20240311_173848](https://github.com/TNODevs/TNO-Bug-Tracker/assets/84097469/1797c796-e57e-4e1b-a7bc-468531b7296a)

**Comment by runelead00** [comment]
Fixed in Dev Build
