### ISSUE TITLE
Guangdong- not storying achievements

### ISSUE THREAD

**Issue by megaloloriginal** [TNODevs/TNO-Bug-Tracker#3060]
### Operating System

windoes 11

### HOI4 version

1.11.7

### TNO version

the one with the birtish guy in front page

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

The game is not storing my achievements

### Steps to reproduce / Cause of the issue

1. play a game2. get an achievement 3. exit game 4. return to see your achievement is not stored

### Expected behaviour

I expect for my achievements to the stored

**Comment by runelead00** [comment]
If your achievements aren't saving, that's on your end. We have nothing to do with storing achievements on our end, entirely  base game code.
