### ISSUE TITLE
GER - Reactionary Crackdown Loc Issue

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#3064]
### HOI4 version

1.14.1 "Bolivar"

### TNO version

1.5.0c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

N/A

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/a4290e88-ef74-4266-9f42-b481658abf55)

**Comment by Stormeagle449** [comment]
Duplicate of #2365
