### ISSUE TITLE
Any Tags - A Collection Of Bugs

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3066]
### Operating System

Windows 10

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files
17. [PAN_1968_07_05_15.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14623240/PAN_1968_07_05_15.zip)

_No response_

### Describe the bug

- [x] 2. Either SS-Oberabschnitt Ostland or Fareynikte Partizaner Organizatsye does not get cores on Ostland when one of them wins.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/b5f80431-a75e-4a44-a4b2-c12ac0e64385)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/85a339e7-9755-4f78-bdbf-c21e1717cc86)

- [ ] 3. Iberia is at an eternal war with Morocco since the start of the Iberian Wars.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/93311d51-93ba-4b4f-8965-1c98e21da206)

- [ ] 5. When Trarza defeats Morocco, the Rif Republic doesn't get Melilla.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/2b65cbf8-4144-4f50-be07-dc5a38a05226)

- [x] 7. Omani loser tags has cores on Khasab despite they have lost on other Omani states.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/26955afb-27fe-4c03-a8c1-db84906f9242)

- [x] 15. Einar Gerhardsen loses his subideology in the new version. In the previous one he was a social democrat.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/5dcd2e6d-079c-4633-92df-fea1d8058cec)

- [x] 17. Nothing happens when Zimbabwe defeats Botswana. No regime change, occupation, not renaming even.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/f32b986e-e4f8-4ac3-af92-f90a5c4f0714)

### Steps to reproduce / Cause of the issue

2:
1. Should Either SS-Oberabschnitt Ostland or Fareynikte Partizaner Organizatsye wins in the OCW.

3: 
1. To trigger the Iberian Wars.

5:
1. To trigger the Iberian Wars.
2. Let Mauritania or the Rif Republic to defeat Morocco.

7: 
1. To trigger the Oil Crisis
2. Should one of the Omani tags win.

15:
1. Milorg overthrows the collabs.
2. Norway holds the election.
3. Einar Gerhardsen wins.

17:
1. Should Großafrikanischer Reichstaat collapses at the first/second stage.
2. It must control Botswana and Zimbabwe (no pro-OFN ceasefire)
3. Wait some time and the war starts.

### Expected behaviour

There are too little spaces to write anything here.

**Comment by runelead00** [comment]
Report bugs individually, not in one giant list, unless they are very closely related

**Comment by runelead00** [comment]
15 His subid was lasted changed over 2 years ago when socdem became progressivism

**Comment by runelead00** [comment]
17 working as designed

**Comment by Marok132** [comment]
> Report bugs individually, not in one giant list, unless they are very closely related

Should I close this issue and make the bugs individually?
