### ISSUE TITLE
Finland - Relocate after_midnight.63.desc

### ISSUE THREAD

**Issue by Kviiri** [TNODevs/TNO-Bug-Tracker#307]
**Description of Suggestion:**
`after_midnight.63`.desc describes Dr. Hemilä as having heard of Taborite at the Department of Chemistry in Kumpula. A more logical place would be one of:
- Unioninkatu 35 (the Dept. of Chemistry's radio- and biochemistry lab)
- Hallituskatu 5 (the period-accurate location of the Dept. of Chemistry)
- Meilahti (the hospital and medical science district of Helsinki, built from the 1960's on)

**Reasoning Behind Suggestion:**
The Kumpula campus was only built from the 1980's on and the Dept. of Chemistry moved there in the 1990's. Before that the area was very light residental/recreational district with allotment gardens, a maternity ward and public swimming pool. Use one of the suggested locations for period-accuracy.

**Additional Information:**

**Comment by Stormeagle449** [comment]
Fixed in UB.
