### ISSUE TITLE
CAN - change name of Ferdrickston to Fredericton 

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#3071]
### HOI4 version

1.14.2

### TNO version

v1.5.0c

### Do you have other mods in use?

Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![20240318132107_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/ce89c04b-d628-4249-8709-34af86d56162)

### Additional information

look like you guys put the pronunciation of the city instead of the name idk 

say hi to king of liberals for me

**Comment by runelead00** [comment]
Fixed in Dev Build
