### ISSUE TITLE
USA - Romney focus position wrong

### ISSUE THREAD

**Issue by lostthingss** [TNODevs/TNO-Bug-Tracker#3072]
### Operating System

Win 11

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Chinese localisation

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_1973_03_08_18.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14641689/USA_1973_03_08_18.zip)

### Describe the bug

The position of 'Uniting the Party' seems to be misplaced, as it's directly below another focus 'America's Future' but 2 can be done at the same time.

### Steps to reproduce / Cause of the issue

open the focus tree

### Expected behaviour

you can jump through a focus

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/125246097/a0ebbcbc-5fe8-4d5e-b16a-894d6f3053ab)

**Comment by runelead00** [comment]
Fixed in Dev Build
