### ISSUE TITLE
USA/HAI - Haitian Civil War - Legitimacy mechanic is broken

### ISSUE THREAD

**Issue by Barometr2137** [TNODevs/TNO-Bug-Tracker#3075]
### Operating System

Windows 11

### HOI4 version

1.14.2

### TNO version

v1.5.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

game.log, error.log, save file: https://file.io/qoRHOclI4oP1

### Describe the bug

The legitimacy of the the haitian government is stuck at 0, making the civil war unwinnable without the use of commands, as government doesn't get passive increase of control, decision don't affect the legitimacy.

### Steps to reproduce / Cause of the issue

Happens every time, regardless of Puerto Plata invasion outcome, or the use of debug menu

### Expected behaviour

Legitimacy working as intended

### Screenshots

![20240320181557_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/164221578/ac0bf844-e786-4a17-97ed-77897d4caca5)
![20240320181611_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/164221578/7ffdbedc-87aa-4c90-9051-40fee37af04a)

**Comment by runelead00** [comment]
Fixed in Dev Build
