### ISSUE TITLE
Haiti - Bug where Cantave coups even if the communist putsch hadn't happened is back

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#3076]
### Operating System

Windows 11

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Goering Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT, TOA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14677058/game.log)

### Describe the bug

The bug where Trujillo defeats the Legion, and Cantave coups in Haiti after Lavaud coups and the PPLN uprising begins is back

### Steps to reproduce / Cause of the issue

1. Set the rules where Trujillo defeats the Legion, then when the PPLN uprising happens to civil war with the Haitian government victorious

### Expected behaviour

As mentioned before, Cantave should only coup if the Communist putsch succeeds after the Legion wins in the DR.

**Comment by runelead00** [comment]
Fixed in Dev Build
