### ISSUE TITLE
FRS - When FRS has been defeated in civil war, system directly shows "TNO_PEACE_POPUP_FLAVOR_FRA_CW" on peace popup, localisation lost

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#3077]
### Operating System

Windows 11

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

as the title

### Steps to reproduce / Cause of the issue

this bug doesnt exists in last version, perhaps localization ID has been changed, made text lost
localization file's ID needs to be changed

### Expected behaviour

popup's localisation can show correctly

**Comment by runelead00** [comment]
This bug does not exist in the version of TNO you reported
