### ISSUE TITLE
japan - outdated lore on japan's starting information screen

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#3079]
### HOI4 version

1.14.3

### TNO version

v1.5.0c

### Do you have other mods in use?

Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![20240327175543_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/ae74197d-06c2-49a7-9dd9-49f20b6d432d)

### Additional information

old lore about MacArthur death in ww2

**Comment by runelead00** [comment]
Fixed in Dev Build
