### ISSUE TITLE
USA - Outdated party-swap lore in Civil Rights loc

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#3080]
### HOI4 version

Bolivar v1.14.3

### TNO version

The Ruin 1.5.0c

### Do you have other mods in use?

TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT, TOA

### List the loc issues below

- [x] 1. Loc for `USA_civil_rights_5` references outdated lore where Democrats are conservative and Republicans are liberal. Nationalists lack the relevant loc coloring and text symbol.
![Issue1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/5cb85f7b-b2a0-4ae9-95f3-15c9020227d1)

- [x] 2. Loc for `USA_civil_rights_6` has redundant use of “mandate”. Civil Rights Act is also not properly capitalized. 
![Issue2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/7c59b1fc-c11d-4d45-b02c-d2365cee44cc)

- [x] 3. Under “Smoke and Mirrors” decision category, the loc for the Marxist and Sovereignist Caucuses lacks a linebreak after the caucus subtitles.
![Issue3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/4323f57e-75ec-40a2-b945-c49881236319)![Issue3_error_location](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/4fa6a153-9d8f-4cdd-aabf-fbc3a2c1a55b)

- [x] 4. Harrington’s events still assumes that Jeane Kirkpatrick, not Phyllis Schlafly, is part of the NPP.
![Issue4a](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/acd0bec3-46c4-448a-a455-d829bae035eb)
![Issue4b](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/ce4ca28f-4c7b-413c-93ea-a8f23858208b)

- [x] 5. “Lansdale” is sometimes misspelled as “Landsdale” in Hart’s events and focus tree. 
![Issue5a](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/3bbfafa5-0bf9-4b70-8fdd-43171682bf25)
![Issue5b](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/4efd6d22-08d6-400a-9ccf-93b030e58f69)
![Issue5c](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/93a683f6-2165-49cb-b607-52ec8f4e7422)

**Comment by runelead00** [comment]
Fixed coloring on 1, party remain the same, Dixiecrats are still a major component of the Democratic Party
