### ISSUE TITLE
INS - Rejoining issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3081]
### Operating System

Windows 10

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Despite Suharto victory counts as the Japanese victory, Indonesia doesn't rejoin the Sphere.

### Steps to reproduce / Cause of the issue

1. To set Suharto victory in the gamerule.
2. The Indonesian War starts.
3. To wait 1968.

### Expected behaviour

Suharto's Indonesia must join the Sphere when it wins.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/71781e82-1351-4e9d-a9eb-b56d69897ca2)

**Comment by runelead00** [comment]
Fixed In Dev Build
