### ISSUE TITLE
IBR - Missing focus icon

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3083]
### Operating System

Windows 10

### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The focus "Our Loyal Advisors" does not have an icon.

### Steps to reproduce / Cause of the issue

Play Iberia to 1969.

### Expected behaviour

No reasons to explain.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/d8df07eb-a9fe-460d-a8fb-971216d7458d)

**Comment by runelead00** [comment]
Fixed in Dev Build
