### ISSUE TITLE
HAI - 'La Mulatocratie' national spirit or its modifier doesn't get remove when Cantave's coup in Haiti

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3085]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14805429/Logs.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14805432/USA_play.zip)

### Describe the bug

When Cantave's coup in Haiti triggers, HAI's 'La Mulatocratie' national spirit and its modifier didn't remove. 

### Steps to reproduce / Cause of the issue

1. Play as any feature tag.
2. Haitian Civil War triggers.
3. HAI's 'La Mulatocratie' national spirit modified or stays.
4. Cantave's coup in Haiti.

### Expected behaviour

Forgot to remove the 'La Mulatocratie' national spirit and it's modifers when Cantave coup in HAI happens.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/46b05c4e-ed1e-4fac-a5a2-453689a885c9)
![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6465f44c-9e61-437a-ae1c-3987bf6f6bd6)

**Comment by runelead00** [comment]
Fixed in Dev Build
