### ISSUE TITLE
USA - issue on news event reaction of 'The Schild Broken'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3087]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14810179/autosave.zip)

### Describe the bug

When the SAW ended and the Afrika-Schild dissolves through Huttig taking over, the reaction of 'The Schild Broken' news event says "Just keep fighting!" despite the SAW is over.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. South Africa War end.
4. The Afrika-Schild survives.
5. The Afrika-Schild dissolve.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/96278781-8b4e-40d9-8146-df427bc699e4)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
