### ISSUE TITLE
USA - No event about Trujillo defeat the Haitians after the Blitz

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3088]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14810635/autosave.zip)
[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14810637/Logs.zip)

### Describe the bug

When Trujillo defeated both Haitian government and communists during the Haitian Blitz, there is no event pops out about Haiti lost to Trujillo's Dominican Republic and no voters effect. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Trujillo victory in PPI.
3. Haitian Civil War starts.
4. The Haitian Blitz starts.
5. Trujillo victory in the Haitian Blitz start.

### Expected behaviour

Probably, oversight.

**Comment by runelead00** [comment]
I did, i can see it in the log hispaniola_news.23
