### ISSUE TITLE
China - Focus Tree Resources Do Not Appear

### ISSUE THREAD

**Issue by GreenerAlien** [TNODevs/TNO-Bug-Tracker#309]
**Questions**

Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Last Waltz of Europe (music mod)
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**

Finishing focuses that should give oil and rubber does not provide oil or rubber

**Steps to Reproduce/Cause Issue:**

1. Play China

2. Finish Oil of Shengi 

3. Have no Oil

**Screenshots:**

![oil](https://user-images.githubusercontent.com/95036880/143457448-753f8b5f-97c0-4708-8643-3b6f99014464.PNG)
![oil2](https://user-images.githubusercontent.com/95036880/143457509-e28cd852-3425-4c5d-8a3b-0193eb2cb600.PNG)

**Comment by Scarsoftime** [comment]
Look at the resources on the map. TNO uses a new trade and resource system and it won't get displayed here.
