### ISSUE TITLE
UKR - Borderlands Mention in Info Screen

### ISSUE THREAD

**Issue by Karab0k** [TNODevs/TNO-Bug-Tracker#3091]
### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT

### List the loc issues below

![изображение_2024-03-30_141542323](https://github.com/TNODevs/TNO-Bug-Tracker/assets/165471804/7a040a2e-1121-4d8c-9bd0-ad571c8a57c6)

### Additional information

This start screen has mistake "from the old slavic language, it means "Borderlands"". It's fake "Ukraine" means "In land". "Країна" translate like land, country. When traveler was man years ago on this land and asking civilian "where are you live?" they answer "in our land/ in land". On ruthenian-ukranian language it's "В країні/ У країні". So please don't spread fake. I hope you understand. Ukraine on slavic languages means what mean EngLAND on English language or DeutschLAND on German language. Just logic, how border can be so giant? In past border was (ukrainian) "околиця". Ukraine meets in old documents where saying about death of ruler. Where saids "all ukraine cry about him". So why only border was sad. Other people don't like him.
I hope you understand and this wasn't difficult to change two sentences. Ukraine or Ruthenia (old name of Ukraine) always called like Gates of Europe. I think this explanation be much better. For example "Ukraine it's "Gates of Europe", so thats why caught between the forces of Berlin in west or Moscow in the east".
Thanks for reading my text, sorry for grammar.

**Comment by runelead00** [comment]
Both are long-standing etymological theories and the borderland theory is more widely accpeted of the two, even by many Ukrainian academics, we're not changing it.
