### ISSUE TITLE
guangdong - no icon for Matsushita's 1963 prodduct cycle

### ISSUE THREAD

**Issue by unluckychip** [TNODevs/TNO-Bug-Tracker#3093]
### Operating System

windows 11

### HOI4 version

1.14.3

### TNO version

v1.5.0c

### Do you have other mods in use?

Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

no icon for prodduct cycle 

### Steps to reproduce / Cause of the issue

play Matsushita path and chose his prodduct cycle in 63

### Expected behaviour

no icon for prodduct cycle 

### Screenshots

![20240329203706_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/50662994/de501a6a-aa92-4cc7-9379-783cd787b746)

**Comment by runelead00** [comment]
Fixed in Dev Build
