### ISSUE TITLE
USA - All 1964 RDC military national focuses do not give national spirits after completion

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3095]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14813571/USA_game.zip)

### Describe the bug

After completing all 1964 RDC military national focuses, the 1964 RDC military national focuses' national spirits didn't appear and give buffs. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect RDC 1964 president.
3. Taking the military focus trees.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/4c454abe-1f69-48b0-bc40-e59ed38e33aa)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/57709266-5506-44ea-829b-fb0bbb1b91b0)

**Comment by runelead00** [comment]
Spirits are added and giving effects, just not visible to not clog spirits with dozens of generic military effects
