### ISSUE TITLE
USA - 'M60 Enhancement Project' focus icon change when the 'XM16 Acquisition Program' focus completes

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3096]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14813596/USA_game.zip)

### Describe the bug

After completing the 'XM16 Acquisition Program' national focus, the national focus GFX icon of 'M60 Enhancement Project' is somewhat changes. However, after completing the 'M60 Enhancement Project' focus, the focus icon is somehow changes back. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect 1964 RDC president.
3. Taking some of the 1964 RDC military foci.
4. 'XM16 Acquisition Program' focus completes.
5. Focus icon of 'M60 Enhancement Project' focus changes.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/df189bbd-5306-40dc-89e8-e82fdbb16def)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/aae43fe2-4c02-420e-bb24-2afca0a4a7bd)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/84ae3f3f-67f6-42b1-8ba6-d80a420c346b)

**Comment by runelead00** [comment]
Fixed in Dev Build
