### ISSUE TITLE
USA - Some suggestions for 1964 RDC military foci

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3097]
### HOI4 version

1.14.3

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

- I would like to suggest that the focus effect for 'XM16 Acquisition Program' should be added another. Like adding 'Infantry Weapon Improvements VII' to 'Semi-Modern Infantry Rifle' researches.
- I would like to suggest that the focus effect for 'M60 Enhancement Project' and 'M113 Enhancement Project' national focuses should be changed to current version. Like bonus research for main battle tank in 'M60 Enhancement Project' and bonus research for APC in 'M113 Enhancement Project'.

### Justifications

- Because some of the players decide to research the infantry weapon first before the taking the 'XM16 Acquisition Program' focus if electing the 1964 RDC president in order to win the proxy war through HOI4 volunteers. And M16A2(Semi-Modern Infantry Rifle) is also another variant of M16 because that is what 'XM16 Acquisition Program' focus description said. 
- 'M60 Enhancement Project' and 'M113 Enhancement Project' national focuses have bonus research effects that do not exist in the current public version because when I looked at the vehicle research tab, I didn't see the modules on what 'M113 Enhancement Project' national focuses' effects describe for. And I think it is a bug or something.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/eb77d838-619c-4278-aebd-51c82d8aee64)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/65ebf1f9-2082-49ec-852c-17ded5c521c7)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/863e0f05-6cf2-4784-94b9-d2e315c0ee9a)

**Comment by runelead00** [comment]
Changed in Dev Build
