### ISSUE TITLE
NOV - Peaceful Unifications Replaces My Tech With Partner's

### ISSUE THREAD

**Issue by MelonHeadzzz** [TNODevs/TNO-Bug-Tracker#310]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Second West Russian War, TNO: Loading Screens Redone, TNO: Improved City Lights, Last Waltz Expanded, State Transfer Tool, Recall Volunteers, Radio_TNO, Player-Led
- Were you using Steam? Yes
- Which expansions do you NOT have? La Resistance, No Step Back, Battle For The Bosporus, 

**Longer Description of Issue:**

After a peaceful unification of Novosibirsk (Shukshin) with Zykov Samara, I was hit with a massive wave of notifications and found out that *all* of my technology had been replaced with Samara's. I am unsure if this is the intent when peacefully unifying.

**Steps to Reproduce/Cause Issue:**

1. Play Novosibirsk

2. **Make sure you're researching along the way**

3. Unify Central Siberia

4. Peacefully unify with a democratic nation

5. Watch your research get completely screwed up

**Screenshots:**
![image_2021-11-25_205830](https://user-images.githubusercontent.com/92616897/143515535-8e0b0eae-f78e-4cf0-95ec-15e228d6387a.png)

As you can see, the research menu *demands* I research the previous motorized equipment, but the graphics say that I already have researched it.

**Comment by Scarsoftime** [comment]
Dealt with in dev build, tech will no longer be transfered in peaceful unification until a better solution is found.
