### ISSUE TITLE
USA - Caspar Weinberger has no position name, political align and his bio description in the political minister

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3100]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_smith.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14815542/USA_smith.zip)

### Describe the bug

After the Margaret Smith's 'Inauguration Day' event, Caspar Weinberger has no position name, political align and his bio description appeared in the political minister. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Smith (NPP-N) in 1968 presidential election.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/d1ec2ea7-efc3-449d-a9e3-2ae30d22775c)

**Comment by runelead00** [comment]
Fixed in Dev Build
