### ISSUE TITLE
BOR - Missing party name 

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3101]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

There is not a despotic party name in Afrikaner Volkstaat
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a7fd3671-0597-4d45-8968-c40767448d95)

**Comment by runelead00** [comment]
Fixed in Dev Build
