### ISSUE TITLE
Siberian Black Army- I crash at 6am June 8th, 1967

### ISSUE THREAD

**Issue by GreaseNeverDries** [TNODevs/TNO-Bug-Tracker#3102]
### Operating System

Windows 10

### HOI4 version

1.14.3.6de2

### TNO version

1.5.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT, TOA

### Files

[
[crash.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14817278/crash.zip)
](url)
[error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14817287/error.zip)

### Describe the crash

It just goes right to desktop if you progress from my save file ahead one hour. Not much to say

### Steps to reproduce / Cause of the crash

Unpause for one hour

**Comment by runelead00** [comment]
This was started on a previous version of TNO, not 1.5.0c which is likely why it is crashing, that or an unlisted submod is affecting stuff
