### ISSUE TITLE
After the country selection menu, the game crashes to desktop

### ISSUE THREAD

**Issue by DarkEtoile** [TNODevs/TNO-Bug-Tracker#3103]
### Operating System

Windows 10

### HOI4 version

1.14.3.6de2

### TNO version

1.5.0c "The Ruin"

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14817557/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14817558/game.log)

### Describe the crash

I installed TNO, enabled it then I selected the black league. After that the game freezes for a moment while showing the national spirit window and then it crashes to desktop. I have deleted the mod and reinstalled it but it still does the same thing.

### Steps to reproduce / Cause of the crash

1.turn on the mod
2.select a country

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/962, can only recommend possible fixes listed there
