### ISSUE TITLE
All nations - Only 1st and 2nd focus trees appearing

### ISSUE THREAD

**Issue by Xeanathan** [TNODevs/TNO-Bug-Tracker#3104]
### Operating System

Windows 11

### HOI4 version

1.14.3.6de2

### TNO version

1.5.0c

### Do you have other mods in use?

Ayden George Remix Radio, Former USSR flags reworked for TNO, Taco Bell Start Sound Ultra Deluxe Supreme Fries Edition,  The New Order: VT323 Map and Cities Font, TNO Achievemnets

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Files

[error.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/14833699/error.txt)

### Describe the GFX issue

After the second focus tree for any nation that has more than 2 focus trees (so far observed in United States, RK Ukraine, Italy, Tomsk and some others) the third focus tree will not load, and i will have the old completed focus trees.

### Steps to reproduce / Cause of the issue

1. Begin game with any nation that has more than 2 focus trees
2. Complete at least 2 focus trees

### Expected behaviour

The third (and so on) focus trees were expected to load in.

### Screenshots

![Screenshot 2024-03-31 183746](https://github.com/TNODevs/TNO-Bug-Tracker/assets/123459092/b6b4da30-0eb6-40ce-b4f6-173ca23d7e25)

### Additional information

I don't know if Ukraine has more than 2 focus trees, but i definitely know that Italy and USA do. I might try and recreate the glitch without any submods installed. Also, in the screenshot, the Algerian war had just finished, and i had none of the usual focuses to prepare

**Comment by runelead00** [comment]
Can't Reproduce

**Comment by Xeanathan** [comment]
Ok
