### ISSUE TITLE
GER - AI doesn't select the 'Unternehmen Nordlicht' in the intelligence tab

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3106]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14835550/USA_play.zip) Switch to GER tag through console to see what happen

### Describe the bug

When playing as any feature tag (except GER) and almost reaches 1970, AI Bormann GER doesn't select the 'Unternehmen Nordlicht' in the intelligence tab to initiate coup against the Milorg's Norway, leading unable to take the rest of the phase 2 focus trees. This is a huge bug.

### Steps to reproduce / Cause of the issue

1. German Civil War triggered.
2. Milord taking control of Norway.
3. Bormann won the German Civil War.
4. Bormann's Germany choose to overthrow the Kingdom of Norway instead of negotiation.
5. AI GER unable to select the 'Unternehmen Nordlicht' in the intelligence tab.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/131502cb-4a41-4035-981d-435d2c2ce437)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/641825e4-902e-4944-8b3a-5faee4d21b00)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fdce6e59-e7a7-465d-8dd0-a610421d6375)

**Comment by runelead00** [comment]
Fixed in Dev Build
