### ISSUE TITLE
Several Tags - Missing Long Country Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3107]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Guinea-Bissau, Palestine and Jerusalem don't have long country names.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/4660f4d7-cdaf-4d31-b3f3-1380c656c3d7)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/80a606fd-68ae-4eae-bec0-f04fc005ad86)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/1da6b6a3-82d1-4e94-b22b-b52d4e162333)

**Comment by runelead00** [comment]
Fixed in Dev Build, although missing long names are not by default an issue (doing these because both Jerusalem and Palestine are referred to by a name in several pieces of loc and GNB was discussed previously and never implemented
