### ISSUE TITLE
USA, 1969 feb 1 crash

### ISSUE THREAD

**Issue by LBJalltheway** [TNODevs/TNO-Bug-Tracker#3108]
### Operating System

Windows 10

### HOI4 version

1.13.7

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/TNODevs/TN
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14833769/game.log)
O-Bug-Tracker/files/14833768/error.log)
[USA TREATY NEGOTIATE.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14847441/USA.TREATY.NEGOTIATE.zip)
[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14847472/autosave.zip)

### Describe the crash

I was saving the game after the second inauguration of lbj on 29/1/1969, and when the game went to 1 am, feb 1 1969, the game froze without reaching the autosaving screen, and then it quited to the window. I tried to restart repeatedly, but all times they failed

### Steps to reproduce / Cause of the crash

Click on the USA TREATY NEGOTIATE.zip file, extract its save file to Documents\Paradox Interactive\Hearts of Iron IV\save games
Repeat above for the autosave.zip file
Open hoi4 from explorer, no steam or paradox launcher
First load the first save game in hoi4, let it run to 1 feb 1969
then load the second save, see if it loads at all

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/165771469/c80b7bdb-a349-4b2d-a654-05c70bce8e12)

**Comment by runelead00** [comment]
We are not investigating issues that exist on outdated version of TNO
