### ISSUE TITLE
State of Guangdong- The game automatically crashes at the end of July

### ISSUE THREAD

**Issue by felixtsang2** [TNODevs/TNO-Bug-Tracker#3109]
### Operating System

Windows 10

### HOI4 version

1.14.1

### TNO version

v1.5.0c

### Do you have other mods in use?

TNO CN translation

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, BBA, AAT, TOA

### Files

[GNG_1969_07_01_01_temp.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14848356/GNG_1969_07_01_01_temp.zip)

### Describe the crash

the game automatically crashes no matter what policy is chosen and there is no event occuring at that moment at the end of july 1969

### Steps to reproduce / Cause of the crash

Keep Playing Until the end of july,1969

**Comment by runelead00** [comment]
Your save is corrupted and firing random events for tags that can't happen them. Usually _temp saves are corrupted and irreparably broken
