### ISSUE TITLE
USA - Hidden event of 'west_africa_crisis_19.t' suddenly triggered after the mobilization is complete

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3110]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14851306/Logs.zip)
[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14851342/USA_play.zip)

### Describe the bug

When the mobilization is complete to help the Mano Pact during the Mano Campaign, the `west_africa_crisis_19.t` hidden event suddenly triggered. It shouldn't be appeared to USA or JAP. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PALF won the West Africa War.
3. Oil Crisis triggers.
4. PALF invade the Mano Pact.
5. OFN choose to support the Mano Pact.
6. OFN manage to hold the PALF forces.
7. OFN and PALF ceasefire.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/af908ff3-ebec-45d9-8140-52b4cf31774c)

**Comment by runelead00** [comment]
Fixed in Dev Build
