### ISSUE TITLE
EGY - Losing Long Country Name in Sadat's Path

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3112]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

When Sadat takes power, Egypt loses its long country name despite it's still counted as the Kingdom of Egypt.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/64ee2a79-78e4-43e9-b2ab-f00749ac8a58)

**Comment by runelead00** [comment]
Fixed in Dev Build
