### ISSUE TITLE
GRO - Missing Party Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3113]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

There is a missing party name for ultranationalist party in Großafrikanischer Reichstaat.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/6f77cddc-5b38-462b-ae60-a4eacef32505)

**Comment by runelead00** [comment]
How did Hüttig even get any ultranationalism popularity

**Comment by Marok132** [comment]
> How did Hüttig even get any ultranationalism popularity

Idk. I just noticed it during playing.
