### ISSUE TITLE
UKR/UKS/FUK/BOV - Defeated factions still exist in the 'Foreign Claims' on Ukraine states after the UCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3115]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the Ukrainian Civil War, the defeated factions still appeared in the 'Foreign Claims' and still have cores on Ukraine states. 

When the Germans reconquers Ukraine from the Rebels, the defeated Ukrainian rebel faction still also appeared in the 'Foreign Claims' and still have cores on Ukraine states.

### Steps to reproduce / Cause of the issue

1. German Civil War triggers.
2. Ukrainian Civil War triggers.
3. End of the Ukrainian Civil War.
4. Germans retake Ukraine if the Rebels won the Ukrainian Civil War.

### Expected behaviour

Forgot to remove the defeated civil war factions in the 'Foreign Claims' on Ukraine states.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/75dedeb8-855b-4df4-81bc-12532f08c96f)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a
