### ISSUE TITLE
USA - 'Look to the Arabian or Italian' event pops out after finishing the Oil Crisis focus tree, despite the Middle East conflicts ended

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3119]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14866108/autosave.zip)

### Describe the bug

After finishing the Oil Crisis focus tree, the 'Look to the Arabian or Italian' event suddenly triggered despite the Middle East conflicts have ended before the 'Crisis Averted?' national focus complete.

According to #2650 that the issue was fixed before the new update. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Middle East Conflicts start.
3. Oil Crisis triggers.
4. Middle East Conflicts end, except Iran.
5. Finish the Oil Crisis focus tree.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c0e6e632-2a53-44bd-ba21-56230d60a6da)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/77d63f0b-423d-44dc-a216-6dc13d33cbe0)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/7ccbc20c-75da-4cca-9ec9-5e6f7391cc7b)

**Comment by runelead00** [comment]
Fixed in Dev Build
