### ISSUE TITLE
Nations with the Comintern Associate/Member spirits get both if the Associate becomes a full member

### ISSUE THREAD

**Issue by GrannTNO** [TNODevs/TNO-Bug-Tracker#312]
**Questions**

Operating System: Windows
HOI4 Version: 1.10.8
TNO Version: 1.2.0d
Any other mods in use: TNO Radio
Were you using Steam? Yes
Which expansions do you NOT have? No Step back

**Longer Description of Issue:**
Nations that become a Associate, but after some time get voted in as a full member have the national spirit of both Associate and Member, which is doubling the effects.

**Screenshots:**
![](https://cdn.discordapp.com/attachments/671023787952570392/913499328717389834/Comintern.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
