### ISSUE TITLE
SLO - Alexander Mach's subideology

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3120]
### HOI4 version

1.14.3

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Make Alexander Mach (he's a guy who can take power if Germany goes brrr to Slovakia) a clerical fascist.

### Justifications

He is part of the Hlinka's Slovak People's Party which main ideology is clerical fascism. Plus all Slovak national socialist leaders are clerical fascists as well so I think he can be one, too.

**Comment by runelead00** [comment]
Rejected, just because other members of this party are clerical fascist doesn't mean he is, especially since they were in a different wing of the party
