### ISSUE TITLE
USA - 'A Greased Palm' and 'Hands Off the South' national focuses are not unlocked after finishing the 'Sit Them Down' focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3126]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14892182/USA_play.zip)

### Describe the bug

After completing the 'Sit Them Down' national focus, the 'A Greased Palm' and 'Hands Off the South' national focuses are somehow not unlocked despite their focus requirements say "Requires one of the following:". 

I don't know if this bug occurs when finishing the 'Cut Wallace Loose' or 'Harangue Harrington' focus.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 presidential election.
3. Complete the 'Sit Them Down' national focus.
4. 'A Greased Palm' and 'Hands Off the South' national focuses are not unlocked.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0b0ee1b0-eca8-40ff-a358-7b52701803f4)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a18f7cee-159f-4fd4-b4c9-4c60f798678b)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/03dd196b-0d62-4a14-8e49-353b33673f62)

**Comment by runelead00** [comment]
read immediately under the things you circled

**Comment by Ikidikid** [comment]
Arrggh, I didn't see the other focus requirements for those two focuses. Thanks by the way. I gonna re-edit this when I found some issue.

**Comment by Ikidikid** [comment]
@runelead00 Will you reopen this? I re-edit this issue.
