### ISSUE TITLE
USA - 'Suppress the Marxists' decision is not unlock

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3127]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_smith.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14892644/USA_smith.zip)

### Describe the bug

When Margaret Chase Smith's inauguration in January 1969, the 'Suppress the Marxists' decision is not unlocked, while the 'Suppress the Sovereignists' decision is unlocked. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 presidential election.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/47559531-5eb9-4bf9-a0ad-caf8db6ece45)

**Comment by runelead00** [comment]
Working as Designed, the Marxists have zero influence on the part to suppress them
