### ISSUE TITLE
USA - Edwin Walker has no bio description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3129]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_smith.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14892897/USA_smith.zip)

### Describe the bug

When Smith inauguration, Edwin Walker has no bio description while other Smith's ministers have their bio descriptions.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 presidential election.

### Expected behaviour

Forgot to add his bio.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/500be18c-66cf-4ae4-9572-1088c7b3504b)

**Comment by runelead00** [comment]
Fixed in Dev Build
