### ISSUE TITLE
MAG - AuthDem Magadan, crash to desktop late game

### ISSUE THREAD

**Issue by eccolus** [TNODevs/TNO-Bug-Tracker#313]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: v1.2.0d “Toolbox Theory”
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? all expansions enabled

**Longer Description of Issue:**
Game crashes May 16/17/18/18th 1972. No apparent reason. War with western super-regional "unificator" WRRF ongoing. I tried rushing VPs to end the war before the previously mentioned date and even when I succeed the crash still occurs. Thing to note, I forgot to do super-regional unification before I was attacked by WRRF. 

No console commands were used and no alterations to the safe file were made during the play-through, 

A common error I found in each crash log (as I reloaded the save and tried to do decisions/foci to try and stop the crash from happening) is as follows:
[15:22:54][trigger.cpp:379]: common/scripted_triggers/TNO_Russia_scripted_triggers.txt:618: SIB: Invalid Scope
[15:22:55][trigger.cpp:379]: common/decisions/TNO_Germany_Espionage_decisions.txt:221: WSB: Invalid Scope

**Game Saves and Log Files, if possible:**
[hoi4_20211126_152311.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7609283/hoi4_20211126_152311.zip)
[MAG_1972_05_01_10.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7609284/MAG_1972_05_01_10.zip)

**Comment by eccolus** [comment]
Found the root cause I think. The game crashes the very moment Scorza's Italy takes out the last faction member of the United Arab States, during the Italy's oil crisis middle east war.

I tag switched to Italy, and it turns out that the vanilla HOI 4 peace conference starts upon the capitulation of the above faction's faction leader. This crashes the game.

Temporary workaround would be to tag switch and manually annex the Syria/Lebanon.

**Comment by eccolus** [comment]
The issue might have something to do with the fact that there are still several potential members of this faction who still have not joined it and couple of weird occurrences. 

1. Egypt somehow formed UAR (United Arab Republic) by itself without joining the "United Arab States" faction first. 
2. Iraq and Oman still have not finished their own civil wars. 
3. United Arab Emirates turned into People's Republic of Arabian Gulf (United Arab Emirates) and did not join this faction. Maybe "Syndicalists" are not supposed to? Don't know.
 
I think this is just a ridiculous edge case... Sadly I do not have older saves to check how this situation came to be.

**Comment by ModdingAccount** [comment]
Fixed in dev build.
