### ISSUE TITLE
USA - 'A Greased Palm' and 'Hands Off the South' national focuses are locked, despite doing favor Progressives or Dixiecrats

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3130]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14893200/Logs.zip)
[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14893216/USA_game.zip)
[USA_game_1.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14893230/USA_game_1.zip)

### Describe the bug

When finishing the 'For the General Welfare' or 'For Domestic Tranquility' focus, the Progressives or Segregationists are the most influential wing is checked in focus requirement of 'A Greased Palm' or 'Hands Off the South' focus. 

But, when finishing the 'Power of the States' or 'Compromise on Welfare' focus, 'A Greased Palm' and 'Hands Off the South' national focuses are locked again even doing favor for Progressives or Dixiecrats through 'The State of the Pact' decisions, the focus requirement's 'the Progressives or Segregationists are the most influential wing' is still not checked.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 presidential election.
3. Doing favor Progressives or Dixiecrats in 'The State of the Pact' decisions.
4. Doing 'Power of the States' or 'Compromise on Welfare' focus.
5. The Progressives or Segregationists are the most influential wing is not checked.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f42446f5-70be-4ac7-a5a1-1311b7367175)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/72ba65aa-0d42-46d6-ab26-bfb72f4a9027)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/00b739ee-7850-40b3-8d59-34dda6de712b)

![Image_4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/30d63120-403b-4d98-9bbb-6dc991c179ee)

**Comment by runelead00** [comment]
Adjusted tooltip to reflect the actual trigger, not giving any concessions to the other side
