### ISSUE TITLE
USA - The Nationalists are increases positive when selecting two support Dixiecrats decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3131]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_smith.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14893251/USA_smith.zip)

### Describe the bug

When selecting the 'Publicly Support the Dixiecrats' and 'Divert Funding to Southern States' decisions from 'The State of the Pact', The Nationalists are somehow increase positive instead of favoring Dixiecrats despite the decisions focus on increasing favor of Dixiecrats (segregationists).

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 presidential election.
3. Select 'Publicly Support the Dixiecrats' and 'Divert Funding to Southern States' decisions.
4. The Nationalists are happy.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/c9d8fb6f-d46a-4389-bfe4-5abb945007a6)

**Comment by runelead00** [comment]
First one intentional, second one fixed
