### ISSUE TITLE
USA - Progressives and Nationalists are decreasing favor when selecting to satisfy left-wing of the pact than segregationists

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3133]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14895304/USA_game.zip)

### Describe the bug

When selecting the effect about 'satisfying the left wing of the pact but Wallace and southerners may object' though events and national focuses, the progressives and nationalists in the State of the Pact decision are somehow unhappy instead of increases happy. 

I don't know if this issue appears when selecting effect 'satisfying the right wing of the pact but Harrington and activists may object' though events and national focuses. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 presidential election.
3. Select favoring left-wing of the pact than Dixiecrats (Wallace and Southerners) though events and focuses.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6626a8c0-ed2c-4c74-a2c4-540d2bff6045)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/70457944-c0c8-4e22-b8c7-6b366488256c)

**Comment by runelead00** [comment]
Fixed in Dev Build
