### ISSUE TITLE
USA - 'Deliberations' event has no description text

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3136]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14895762/USA_play.zip)

### Describe the bug

After 'The Right to Unionize' national focus finish, the 'Deliberations' event has no description text appear. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 and 1972 presidential elections.
3. Finish the national focus of 'The Right to Unionize'. 
4. 'Deliberations' event pops out.

### Expected behaviour

Forgot to add event's description.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/10e1406b-bfbe-49e2-85ef-15061677938f)

**Comment by runelead00** [comment]
Fixed in Dev Build
