### ISSUE TITLE
USA - Some issues in 'The Communication Act of 1973 Passes!' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3137]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14895853/USA_game.zip)

### Describe the bug

In the event's effects of 'The Communication Act of 1973 Passes!', it says "This will please the right-wingers and moderates in our pact, but bother the left-wingers." but this event is about helping the unions and workers. The effect should be, "This will please the left-wingers and moderates in our pact, but bother the right-wingers."

And effects for the Southern States didn't show on what effects on these states. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 and 1972 presidential elections.
3. The Communication Act passes.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a92822c8-f37b-480b-bcc6-d786e1815e3b)

**Comment by runelead00** [comment]
Fixed in Dev Build
