### ISSUE TITLE
KOM - Bukharina's Komi can't peacefully reunify with anyone at the superregional stage.

### ISSUE THREAD

**Issue by letheanlight** [TNODevs/TNO-Bug-Tracker#314]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: TNO: Terra e Liberta
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosphorus, No Step Back

**Longer Description of Issue:**
Currently, of Komi's far-left, the game allows Zhdanov to reunify with IRK and PRC, and Suslov to reunify with IRK, BRY, and PRC, but Bukharina isn't considered compatible with anyone. 

This is because RWS_SIB_is_compatible flag in TNO_russia_scripted_triggers.txt only checks for a socialist Komi, which only Zhdanov fits now, and a communist Komi under Suslov specifically, meaning Bukharina's Komi doesn't meet any of the requirements.

**Steps to Reproduce/Cause Issue:**

1. Reunify West Russia and West Siberia as Bukharina.

2. Have any of the Soviet splinter states reunify Siberia.

3. Cry because you have to conquer a country you have +100 relations and a non-aggression pact with, and that you helped reunify with Comintern volunteer divisions.

**Comment by runelead00** [comment]
Fix in Dev Build
