### ISSUE TITLE
USA - Compile the monthly HCW mission with a scripted effect

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#3140]
### HOI4 version

Bolivar v1.14.4

### TNO version

The Ruin 1.5.0c

### Which major expansions do you NOT have?
BBA, AAT, TOA

### Describe your suggestion

For the Haitian Civil War mission `ZZZ_USA_Haiti_Updates` that fires every month, and its corresponding dummy decision `USA_HCW_empty_space`, have the timeout effects compiled with a scripted effect. 

### Justifications

Compiling the mission effects into a scripted effect would make it easier for the HCW developers to rebalance and bugfix, since they would only need to change the variables in one place, rather than two decisions scattered inside a massive file. Having a scripted effect would also decrease the file size of “TNO_forpol_USA.txt” (from 608kb to ~570kb).

### Screenshots

![HCW_scriptedeffect_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/6d451a51-2c98-4a57-8295-f367d690a9fd)
![HCW_scriptedeffect_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/bef42a70-05c6-45a5-92c4-5728072948ae)
![HCW_scriptedeffect_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/c6fd117f-52a0-4e59-9219-fcd360aef4df)

### Additional information

This is what the scripted effect would look like, as an example:

	TNO_HCW_fire_monthly_effect = {
		318 = {
			set_variable = { HCW_Communist_Control = 0 }
			set_variable = { HCW_Government_Control = 0 }
			clr_state_flag = HCW_locked
		}

		if = {
			limit = {
				HAI = {
					any_controlled_state = {
						AND = {
							check_variable = { HCW_Government_Control > 89.99 }
							NOT = { has_state_flag = HCW_communists_crushed }
						}
					}
				}
			}
			custom_effect_tooltip = USA_HCW_Haiti_Eradicating_Communists_tt
			if = {
				limit = {
					1728 = {
						check_variable = { HCW_Government_Control > 89 }
						NOT = { has_state_flag = HCW_communists_crushed }
					}
				}
				1728 = {
					hidden_effect = {
						set_temp_variable = { control_winner = 1 }
						TNO_HCW_increase_control_large = yes
					}
					set_state_flag = HCW_communists_crushed
					custom_effect_tooltip = TNO_HCW_increase_control_large_govt_tt_no_target
					custom_effect_tooltip = HCW_communists_crushed_tt
				}
			}
			if = {
				limit = {
					1881 = {
						check_variable = { HCW_Government_Control > 89 }
						NOT = { has_state_flag = HCW_communists_crushed }
					}
				}
				1881 = {
					hidden_effect = {
						set_temp_variable = { control_winner = 1 }
						TNO_HCW_increase_control_large = yes
					}
					set_state_flag = HCW_communists_crushed
					custom_effect_tooltip = TNO_HCW_increase_control_large_govt_tt_no_target
					custom_effect_tooltip = HCW_communists_crushed_tt
				}
			}
			if = {
				limit = {
					1880 = {
						check_variable = { HCW_Government_Control > 89 }
						NOT = { has_state_flag = HCW_communists_crushed }
					}
				}
				1880 = {
					hidden_effect = {
						set_temp_variable = { control_winner = 1 }
						TNO_HCW_increase_control_large = yes
					}
					set_state_flag = HCW_communists_crushed
					custom_effect_tooltip = TNO_HCW_increase_control_large_govt_tt_no_target
					custom_effect_tooltip = HCW_communists_crushed_tt
				}
			}
			if = {
				limit = {
					1882 = {
						check_variable = { HCW_Government_Control > 89 }
						NOT = { has_state_flag = HCW_communists_crushed }
					}
				}
				1882 = {
					hidden_effect = {
						set_temp_variable = { control_winner = 1 }
						TNO_HCW_increase_control_large = yes
					}
					set_state_flag = HCW_communists_crushed
					custom_effect_tooltip = TNO_HCW_increase_control_large_govt_tt_no_target
					custom_effect_tooltip = HCW_communists_crushed_tt
				}
			}

			USA = { hidden_effect = { TNO_HAI_crush_check = yes } }
		}

		USA = {
			if = { # stage 1
				limit = {
					has_country_flag = TNO_HCW_base_phase
				}
				TNO_HCW_increase_radicalism_small = yes
				TNO_HCW_increase_involvement_small = yes

				HAI = {
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control < HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip < 3 } }
							TNO_HCW_increase_control_small = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
						else = {
							set_variable = { HAI_state_flip = 0 }
							# TNO_HCW_increase_control_small = yes
						}
					}
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip < 3 } }
							TNO_HCW_increase_control_small = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
						else = {
							set_variable = { HAI_state_flip = 0 }
							TNO_HCW_increase_control_medium = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
					}
				}
				HAC = {
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control < HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip < 3 } }
							TNO_HCW_increase_control_small = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
						else = {
							set_variable = { HAI_state_flip = 0 }
							# TNO_HCW_increase_control_small = yes
						}
					}
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip < 3 } }
							TNO_HCW_increase_control_small = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
						else = {
							set_variable = { HAI_state_flip = 0 }
							TNO_HCW_increase_control_medium = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
					}
				}
			}
			else_if = { # stage 2
				limit = {
					has_country_flag = TNO_HCW_buildup_phase
				}
				TNO_HCW_increase_radicalism_medium = yes
				TNO_HCW_increase_involvement_small = yes
				if = {
					limit = {
						check_variable = { USA.HAI_radicalism > 69 }
					}
					if = {
						limit = { check_variable = { HAI_weary_flip < 3 } }
						add_to_variable = { HAI_weary_flip = 1 }
					}
					else = {
						TNO_HCW_increase_weariness_small = yes
						set_variable = { HAI_weary_flip = 0 }
					}
				}
				HAI = {
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control < HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip_com < 3 } }
							TNO_HCW_increase_control_small = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
						else = {
							limit = { check_variable = { HAI_state_flip = 1 } }
							TNO_HCW_increase_control_medium = yes
							set_variable = { HAI_state_flip_com = 0 }
						}
					}
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip_com < 3 } }
							TNO_HCW_increase_control_medium = yes
							add_to_variable = { HAI_state_flip_com = 1 }
						}
						else = {
							set_variable = { HAI_state_flip_com = 0 }
							TNO_HCW_increase_control_large = yes
						}
					}
				}
				HAC = {
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control < HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip_com < 3 } }
							TNO_HCW_increase_control_small = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
						else = {
							limit = { check_variable = { HAI_state_flip = 1 } }
							TNO_HCW_increase_control_medium = yes
							set_variable = { HAI_state_flip_com = 0 }
						}
					}
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip_com < 3 } }
							TNO_HCW_increase_control_medium = yes
							add_to_variable = { HAI_state_flip_com = 1 }
						}
						else = {
							set_variable = { HAI_state_flip_com = 0 }
							TNO_HCW_increase_control_large = yes
						}
					}
				}
			}
			else_if = { # stage 3
				limit = {
					has_country_flag = TNO_HCW_interventionism_phase
				}
				TNO_HCW_increase_radicalism_large = yes
				TNO_HCW_increase_involvement_small = yes
				if = {
					limit = {
						check_variable = { USA.HAI_radicalism > 69 }
					}
					if = {
						limit = { check_variable = { HAI_weary_flip = 0 } }
						add_to_variable = { HAI_weary_flip = 1 }
					}
					else = {
						TNO_HCW_increase_weariness_small = yes
						set_variable = { HAI_weary_flip = 0 }
					}
				}

				HAI = {
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control < HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip < 3 } }
							TNO_HCW_increase_control_medium = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
						else = {
							set_variable = { HAI_state_flip = 0 }
							TNO_HCW_increase_control_large = yes
						}
					}
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip_com < 4 } }
							TNO_HCW_increase_control_large = yes 
							add_to_variable = { HAI_state_flip_com = 1 }
						}
						else = { 
							set_variable = { HAI_state_flip_com = 0 }
							TNO_HCW_increase_control_medium = yes
						}
					}
					if = {
						limit = { has_country_flag = HAICW_bunker_down }
						every_owned_state = {
							limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
							TNO_HCW_increase_control_large = yes
							hidden_effect = { # really fucking fast
								TNO_HCW_increase_control_medium = yes
							}
						}
					}
				}
				HAC = {
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control < HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip < 3 } }
							TNO_HCW_increase_control_medium = yes
							add_to_variable = { HAI_state_flip = 1 }
						}
						else = {
							set_variable = { HAI_state_flip = 0 }
							TNO_HCW_increase_control_large = yes
						}
					}
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						if = {
							limit = { check_variable = { HAI_state_flip_com < 4 } }
							TNO_HCW_increase_control_large = yes 
							add_to_variable = { HAI_state_flip_com = 1 }
						}
						else = { 
							set_variable = { HAI_state_flip_com = 0 }
							TNO_HCW_increase_control_medium = yes
						}
					}
					if = {
						limit = { has_country_flag = HAICW_bunker_down }
						every_owned_state = {
							limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
							TNO_HCW_increase_control_large = yes
							hidden_effect = { # really fucking fast
								TNO_HCW_increase_control_medium = yes
							}
						}
					}
				}
			}

			if = { # stage fuck
				limit = {
					has_country_flag = TNO_HCW_disengagement_phase
				}
				TNO_HCW_decrease_weariness_small = yes
				TNO_HCW_decrease_involvement_medium = yes

				HAI = {
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control < HCW_Government_Control } }
						TNO_HCW_increase_control_small = yes
					}
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						TNO_HCW_increase_control_large = yes
					}
				}
				HAC = {
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control < HCW_Government_Control } }
						TNO_HCW_increase_control_small = yes
					}
					every_owned_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						TNO_HCW_increase_control_large = yes
					}
				}
			}

			if = {
				limit = {
					USA = {
						has_country_flag = USA_HCW_bombing_runs
						check_variable = { HAI_bomb_flip = 0 }
					}
					HAI = {
						any_core_state = {
							check_variable = { HCW_Communist_Control > HCW_Government_Control }
						}
					}
				}
				custom_effect_tooltip = USA_HCW_effects_from_bombing_runs_tt
				HAI = {
					set_temp_variable = { control_winner = 1 }
					every_core_state = {
						limit = { check_variable = { HCW_Communist_Control > HCW_Government_Control } }
						TNO_HCW_increase_control_medium = yes
					}
				}
				USA = {
					add_to_variable = { HAI_weary_flip = 1 }
					add_to_variable = { HAI_bomb_flip = 1 }
				}
			}
			else = {
				USA = { set_variable = { HAI_bomb_flip = 0 } }
				custom_effect_tooltip = USA_NO_BOMB_RUNS_tt
			}

			if = {
				limit = {
					DOM = {
						OR = {
							has_government = fascism
							has_government = socialist
						}
					}
					has_global_flag = HIS_trujillo_blitz_preparing
				}
				custom_effect_tooltip = USA_HCW_tensions_DR_tt
				if = {
					limit = {
						has_country_flag = TNO_HCW_interventionism_phase
					}
					TNO_HCW_increase_tensions_medium = yes
				}
				else = {
					TNO_HCW_increase_tensions_small = yes
				}
			}

			## Security Force
			TNO_HCW_increase_HAI_professionalism_check = yes
			custom_effect_tooltip = USA_HCW_linebreak
			TNO_HCW_check_haiti_status = yes
			TNO_HCW_Calculate_Frame = yes

			if = {
				limit = {
					check_variable = { global.HCW_locked_states > 0 }
					USA = { NOT = { has_country_flag = HIS_HAI_cantave_coup } }
				}
				custom_effect_tooltip = USA_HCW_incoming_coup_tt
				set_country_flag = HIS_HAI_cantave_coup
				hidden_effect = { HAI = { country_event = { id = HIS_HAI.3 days = 14 } } }
			}

			if = {
				limit = {
					check_variable = { USA.HAI_involvement < USA.USA_HCW_disengagement_target_needed_check }
					USA = { has_country_flag = TNO_HCW_disengagement_phase }
				}
				custom_effect_tooltip = USA_HCW_effects_from_hitting_target_tt
				add_political_power = 20
				TNO_HCW_decrease_weariness_small = yes

				set_variable = { USA_HCW_disengagement_target_needed = HAI_involvement }
				subtract_from_variable = { USA_HCW_disengagement_target_needed = 10 }
				clamp_variable = { var = USA_HCW_disengagement_target_needed min = 15 }
				set_variable = { USA_HCW_disengagement_target_needed_check = USA_HCW_disengagement_target_needed }
				subtract_from_variable = { USA_HCW_disengagement_target_needed_check = 0.01 }
			}
			else_if = {
				limit = { USA = { has_country_flag = TNO_HCW_disengagement_phase } }
				custom_effect_tooltip = USA_HCW_effects_from_missing_target_tt
				add_to_variable = { USA_HCW_missed_disengagement_targets = 1 }

				add_stability = -0.01
				add_war_support = -0.02

				set_temp_variable = { protest_weeks = 2 }
				custom_effect_tooltip = USA_all_voters_header_tt

				set_variable = { USA_HCW_disengagement_target_needed = HAI_involvement }
				subtract_from_variable = { USA_HCW_disengagement_target_needed = 10 }
				clamp_variable = { var = USA_HCW_disengagement_target_needed min = 15 }
				set_variable = { USA_HCW_disengagement_target_needed_check = USA_HCW_disengagement_target_needed }
				subtract_from_variable = { USA_HCW_disengagement_target_needed_check = 0.01 }

				if = { # NPP
					limit = {
						OR = {
							has_government = progressivism
							has_government = paternalism
						}
					}

					set_temp_variable = { USA_week_change_rural_dem = protest_weeks }
					set_temp_variable = { USA_week_change_rural_rep = protest_weeks }

					add_to_variable = { Demographic_Shift_black_dem_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_hispanic_dem_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_minority_dem_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_nativists_dem_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_urban_dem_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_rural_dem_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_union_dem_Weeks = protest_weeks }

					add_to_variable = { Demographic_Shift_black_rep_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_hispanic_rep_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_minority_rep_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_nativists_rep_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_urban_rep_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_rural_rep_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_union_rep_Weeks = protest_weeks }

					custom_effect_tooltip = USA_rural_dem_shift
					custom_effect_tooltip = USA_rural_rep_shift
				}

				if = { # RDC
					limit = {
						OR = {
							has_government = conservatism
							has_government = liberalism
						}
					}

					set_temp_variable = { USA_week_change_rural_pro = protest_weeks }
					set_temp_variable = { USA_week_change_rural_nat = protest_weeks }

					add_to_variable = { Demographic_Shift_black_pro_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_hispanic_pro_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_minority_pro_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_nativists_pro_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_urban_pro_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_rural_pro_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_union_pro_Weeks = protest_weeks }

					add_to_variable = { Demographic_Shift_black_nat_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_hispanic_nat_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_minority_nat_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_nativists_nat_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_urban_nat_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_rural_nat_Weeks = protest_weeks }
					add_to_variable = { Demographic_Shift_union_nat_Weeks = protest_weeks }

					custom_effect_tooltip = USA_rural_pro_shift
					custom_effect_tooltip = USA_rural_nat_shift
				}

				set_temp_variable = { USA_week_change_black_foreign_policy_con = protest_weeks }
				add_to_variable = { Policy_Shift_black_foreign_policy_con_Weeks = protest_weeks }
				add_to_variable = { Policy_Shift_hispanic_foreign_policy_con_Weeks = protest_weeks }
				add_to_variable = { Policy_Shift_minority_foreign_policy_con_Weeks = protest_weeks }
				add_to_variable = { Policy_Shift_nativists_foreign_policy_con_Weeks = protest_weeks }
				add_to_variable = { Policy_Shift_urban_foreign_policy_con_Weeks = protest_weeks }
				add_to_variable = { Policy_Shift_rural_foreign_policy_con_Weeks = protest_weeks }
				add_to_variable = { Policy_Shift_union_foreign_policy_con_Weeks = protest_weeks }
				custom_effect_tooltip = USA_black_foreign_policy_con
			}
			if = {
				limit = {
					check_variable = { USA.HAI_involvement < 6 }
					USA = { has_country_flag = TNO_HCW_disengagement_phase }
				}
				USA = { TNO_HCW_withdrawal = yes }
			}

			clr_country_flag = HAICW_single_month_decision_used
		}
		hidden_effect = { ZZZ = { activate_mission = ZZZ_USA_Haiti_Updates } }
	}

**Comment by ModdingAccount** [comment]
Added in Dev Build
