### ISSUE TITLE
USA - Slight issue for the 'Eyes in the Sky' focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3142]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14911744/USA_play.zip)

### Describe the bug

The 'Eyes in the Sky' focus shows its effect to give 'Research Decryption Technology' but there is no about decryption technology in research tabs when LaR dlc is on. However, this focus gives bonus time for computing research, so this focus effect should be renamed to "Computing" instead of Decryption to avoid confusion. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 and 1972 presidential elections.
3. See the effects of 'Eyes in the Sky' focus.
4. Complete the 'Eyes in the Sky' focus.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f7bef1c8-35df-40f4-b9cc-fe44d5cae250)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/82fed9bc-d505-4e2e-8392-658d64379896)

**Comment by runelead00** [comment]
Fixed in Dev Build
