### ISSUE TITLE
USA - 'Submission of the Admirals' national spirit has no GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3144]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14912281/USA_game.zip)

### Describe the GFX issue

The 'Submission of the Admirals' national spirit has no unique GFX icon.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Margaret Chase Smith in the 1968 and 1972 presidential elections.
3. The Army is displeased.
4. The Army protest.
5. Give in to the Army.

### Expected behaviour

Forgot to add unique GFX national spirit icon.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2c89bd6a-dbfa-4d53-aead-596aa207f969)

**Comment by runelead00** [comment]
Fixed in Dev Build
