### ISSUE TITLE
komi russia - after the country has loaded the game crashed

### ISSUE THREAD

**Issue by helldivers1** [TNODevs/TNO-Bug-Tracker#3146]
### Operating System

windows 11

### HOI4 version

1.14.3.6de2

### TNO version

1.5.0c "The Ruin"

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14914855/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14914857/error.log)

### Describe the crash

when i picked a country after a few minutes of waiting the entire damn thing crashed, its been happening since i've downloaded the mod. and i have tried everything, from -opengl to uninstalling and re-installing it. it has honestly been frustrating. 

### Steps to reproduce / Cause of the crash

1. open hoi4
2. wait for the game to load
3. pick any nation
4. wait a few minutes for country to load
5. game crashes

### Additional information

when i look throught the error it says it cant find the music among other things. if you can respond it would be great, thank you

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/962, can only recommend possible fixes listed there (I'm sure the music is not the problem).
