### ISSUE TITLE
USA - asw_tech_research and speacial_forces_tech_research effects are no localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3148]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.4

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/14915295/USA_game.zip)

### Describe the bug

`asw_tech_research` is not yet localized in the 'Navy Focused Research' national spirit and `speacial_forces_tech_research` is not yet localized in the 'Army Focused Research' speacial_forces_tech_research.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect any NPP leader in 1964 and 1968 presidential election.
3. Doing NPP's foreign focuses.
4. Doing 'Domestic Preparedness' focuses.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/356fbb22-72b5-40e0-baed-1e9c273e0a94)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/8a68e10a-38aa-4dae-8731-49ab0e00121b)

**Comment by runelead00** [comment]
Fixed in Dev Build
