### ISSUE TITLE
USA - Game crashes to desk after loading upm occurs after I choose country

### ISSUE THREAD

**Issue by Get-GoodPowershellProgrammer** [TNODevs/TNO-Bug-Tracker#3149]
### Operating System

Windows 11 22H2

### HOI4 version

Bolivar v1.14.4.d429

### TNO version

1.5.0c

### Do you have other mods in use?

Nope

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[exception.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/14924245/exception.txt)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/14924247/error.log)

### Describe the crash

After booting up the game, I choose a country normally, then the game loads for a while and it crashes me to desktop, For some reason, it also crashed Google Chrome and when I opened it back, it causes a weird effect to be shown instead of the taskbar, which goes away when I open the Screen Capture tool.

### Steps to reproduce / Cause of the crash

1. Boot up the game.
2. Choose a country in singleplayer.
3. Wait until it crashes.
4. On the weird chance it loads, click the voting UI and it will crash

**Comment by Get-GoodPowershellProgrammer** [comment]
The Chrome issue subsided after I killed and reopened explorer.exe (Resetting didn't fix it.)

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/962, can only recommend possible fixes listed there
