### ISSUE TITLE
COMECON Centralization Bug

### ISSUE THREAD

**Issue by WalkehTalkeh** [TNODevs/TNO-Bug-Tracker#315]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Collie 1.10.8
- TNO Version: v1.2.0d
- Any other mods in use: none
- Were you using Steam? yes
- Which expansions do you NOT have? I have all expansions 

**Longer Description of Issue:**

Once comecon has been centralized and now becomes an actual sphere, any nations added to comecon afterwards do not join the sphere. They are shown within the COMECON  gui but don't add to the power of the econ sphere. Additionally, there sometimes are issues with new members joining the assembly, as they do not always appear

**Steps to Reproduce/Cause Issue:**

1. Any nation that can form the COMECON can cause this

2. Once you centralize comecon so it can become an actual economic sphere and you try to add nations afterwords it occurs

![20211126135548_1](https://user-images.githubusercontent.com/94952493/143625917-0cc33f38-3851-455b-94f0-bcb1afda6aa1.jpg)

List of members in econ sphere only 8

![20211126140139_1](https://user-images.githubusercontent.com/94952493/143625922-d0bc0782-5f4f-4e35-98b1-96db6b9d2da5.jpg)

Assembly shows many more including countries like Iran

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
