### ISSUE TITLE
Levant - Effects for the Levantine Union ideas.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3152]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Make effects for the Levantine Union Member and Levantine Union Mandate faction ideas.

### Justifications

Flavors + some economic boosts for Italy because the Levant countries are economically dependent by Italy . Let's say the effects will be GDP Growth Boost: 4.5% and GDP to Sphere Leader Modifier: 2.5% for Levantine Union Member and  GDP Growth Boost: 2.5% and GDP to Sphere Leader Modifier: 1% for Levantine Union Mandate.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/3568d57c-e86f-407a-9023-6f0488586c4b)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a7b7f9ca-e4cd-4646-bfc5-8a9f0f9c6a48)

**Comment by ThePikminCaptain** [comment]
I believe the union should still be associate states of Italy, the member/mandate should be a spirit

**Comment by Marok132** [comment]
> I believe the union should still be associate states of Italy, the member/mandate should be a spirit

Well... I wouldn't mind it if the devs do it.

**Comment by runelead00** [comment]
Not changing stuff changing subject to change in near future
