### ISSUE TITLE
Levant - Give Acre Palestine

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3153]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Give Palestine Acre when the Italian Levant Partition occurs.

### Justifications

If I understand it right, the partition occurs along ethnic lines. Despite Acre is inhabited by Arabs completely, Israel holds it. It's better to give it Palestine. If the borders are made along beautiful borders, Safed should be transferred to Israel because of gore borders.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e129597d-0060-4052-8086-a7ce8d9dbd2b)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/8d993c33-9bf6-4530-96bb-03aa4faa8ef9)

**Comment by runelead00** [comment]
Not changing stuff changing subject to change in near future
