### ISSUE TITLE
FRA - Faction Idea Issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3159]
### HOI4 version

1.14.1

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Give Mitstreiter for both Pierre Sidos and François Duprat's France instead of Bündnispartner.

### Justifications

Sidos isn't fully independent actually. He's a German buttlicker who wishes to be in a very close ties to Germany. It can be understood if you read Back to the Pakt and Learning from the Reich national spirit descriptions. Durpart is almost literally as Sidos but less independent even. Plus all countries who have Mitstreiter at start will receive it again, so I don't think France is an exception.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/70a460b0-0d71-4458-8758-753400ded3fb)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/f6eb5bc4-db0e-41d1-9120-b10a5ca82631)

**Comment by Stormeagle449** [comment]
Rejected, we're currently reviewing France's paths and Pakt's faction ideas and the final result will be different from current state. There's no point in changing content that will be overhauled in future updates.

**Comment by Marok132** [comment]
> Rejected, we're currently reviewing France's paths and Pakt's faction ideas and the final result will be different from current state. There's no point in changing content that will be overhauled in future updates.

It's understandable. Thanks for your answer!
