### ISSUE TITLE
"Buisness" -> "Business" in several LoC files

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#317]
**Questions**

- HOI4 Version: Beta set to 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

I noticed this misspelling while playing Glenn USA; looks like there's an opportunity for a quick search-and-replace.

The misspelling `buisness` occurs in several localization files:

- `TNO_Burgundy_I_english.yml`
- `TNO_China_I_english.yml`
- `TNO_Congo_I_english.yml`
- `TNO_Italy_loc_I_english.yml`
- `TNO_Latin_America_I_english.yml`
- `TNO_USA_RD_R_I_english.yml`

**Comment by Scarsoftime** [comment]
Fixed
