### ISSUE TITLE
DEN - Wrong Puppet Status

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3170]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Denmark has a reichsprotektorat status despite it isn't part of Reich and it's a marionettenstaat like Slovakia or Serbia which have Collaborator Puppet State.

### Steps to reproduce / Cause of the issue

Just start a new game.

### Expected behaviour

Denmark is supposed to have Collaborator Puppet State

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a3a9c1a7-159c-4ca8-988c-0f7a961e537b)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/64735c50-6aa1-4d30-8f84-a45182851a61)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/7d128160-b990-48a8-b03b-7466c2f643c9)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build (we made Denmark into a Reichsprotektorat).

**Comment by Marok132** [comment]
> Fixed in Dev Build (we made Denmark into a Reichsprotektorat).

Why? How will it look?
