### ISSUE TITLE
YEM and SAU - Incorrect Installed Leader

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3176]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Saudi Arabia defeats Yemen, the world event mentions the Saudis install Muhammad al-Badr as a new Imam of Yemen. It isn't actually. Ahmad bin Yahya is still in charge of Yemen.

### Steps to reproduce / Cause of the issue

1. The Oil Crisis starts.
2. Socialist Yemen defeats Monarchist one.
3. Socialist Yemen invades Saudi Arabia.
4. Saudi Arabia defeats Yemen.

### Expected behaviour

Muhammad al-Badr is supposed to be a new Imam of Yemen.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/6897a589-7b7e-4b6c-812d-441582da73a7)

**Comment by runelead00** [comment]
Fixed in Dev Build
