### ISSUE TITLE
GER Bormann - Wrong name

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#3178]
### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

marked with red
![bbbug report](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/b8464740-bc7f-44f7-a619-9bf173d7583a)

### Additional information

I'm playing bormann and i got the event from a focus called "The new leader"
![Skærmbillede 2024-04-22 201949](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/a1000d12-02d0-4447-b6ad-db6b04e664a7)
however im unsure if Heydrich is the right person, because this is bormann not reinhard heydrich.

**Comment by Stormeagle449** [comment]
In that paragraph the protagonist is reminiscing the times before the German civil war when Heydrich was leading the SS, and thus Heydrich is correct.
