### ISSUE TITLE
USA West African Intervention

### ISSUE THREAD

**Issue by orane63** [TNODevs/TNO-Bug-Tracker#318]
**Questions**

- Operating System: Mac OS 11.2.3
- HOI4 Version: 1.10.8 Collie
- TNO Version: 1.2.0d
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have?
No Step Back (which I'm not using anyways)
**Longer Description of Issue:**
When USA wins Gulf of Guinea Campaign, it is still unable to send volunteers after 60 days. This was in the WAA vs PALF version of the West African Crisis.
**Steps to Reproduce/Cause Issue:**

1. Win Gulf of Guinea, but receive no event to actually send volunteers in the West African Crisis

**Screenshots:**
Judging from the files, it seems like USA should send be able to send volunteers after 60 days. However, it did not occur.
<img width="592" alt="Screen Shot 2021-11-26 at 3 37 41 PM" src="https://user-images.githubusercontent.com/41270689/143661199-25e6451b-0dc3-4cca-8335-12b99d2c5e7f.png">
.

**Comment by runelead00** [comment]
Fixed in Dev Build
