### ISSUE TITLE
GER - typo

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#3180]
### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![bbbbug report](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/41135e6b-c76c-4541-8761-f81d857c6a0b)
marked with red

### Additional information

im playing bormann germany and oktan is in power in west russia so i get decision in intelligence thing to do something and boom this event fires but theres a typo

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
