### ISSUE TITLE
SPH - Coalition Government is Renamed after Reconstruction 

### ISSUE THREAD

**Issue by ThePikminCaptain** [TNODevs/TNO-Bug-Tracker#3181]
### HOI4 version

1.14

### TNO version

1.50c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

If the coalition government forms after the Philippine war, it should rename itself to ”The United Republic of The Philippines”

### Justifications

The Coalition Government would eventually hold elections

**Comment by Stormeagle449** [comment]
We decided to change the country's name to "Third Philippine Republic" instead.
