### ISSUE TITLE
GER Bormann - Typo

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#3183]
### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/2c6ca2eb-98c6-4cc5-9da7-772039ae384e)

### Additional information

Should be saying "weeks" instead of "week"

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
