### ISSUE TITLE
SRK and BRU - Faction Idea issue (code issue)

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3184]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The JAP_north_borneo_release_tags_into_sphere script effect is supposed to give for both SRK and BRU the Sphere_Economic_Dependent idea but it doesn't work actually because SRK - Sarawak and BRU - Brunei are used the Sphere_Imp_Protectorate line.

### Steps to reproduce / Cause of the issue

Just remove Sphere_Imp_Protectorate in SRK - Sarawak and BRU - Brunei files so both tags will get right faction ideas in the JAP_north_borneo_release_tags_into_sphere script effect.

### Expected behaviour

SRK and BRU is supposed to get Sphere_Economic_Dependent, not Sphere_Imp_Protectorate. 

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/592b8d4a-0b1d-4d0a-adce-55b080deceff)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/6610c6ed-a5b7-4f3d-83dd-c46f14895ffe)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Marok132** [comment]
> Fixed in Dev Build.

Thank you!
