### ISSUE TITLE
Orsk (Dirlewanger) missing national spirit icon

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#319]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Orsk has an empty spot where a national idea should be, which I *believe* means that one of their national spirits is missing an icon.

Noticed this while playing as Tomsk in early '65. Orsk has recently completed the focus "The Second Phase".

**Screenshots:**

![image](https://user-images.githubusercontent.com/711467/143661268-47e08906-a5c3-4a78-9e5d-48e6e354162d.png)

**Comment by runelead00** [comment]
I believe the affected national spirit has now been fixed
