### ISSUE TITLE
GER bormann - typo

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#3190]
### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/dda1c0c7-b025-47f3-9208-85ace1f71e76)
marked with red

### Additional information

should be saying "against" instead of "again"

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
