### ISSUE TITLE
SLF - Missing Party Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3191]
### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/54ed93d7-0ff6-4df4-984d-19f09c873925)

### Additional information

Most of the sides in the Second South African Civil War don't have party names.

**Comment by runelead00** [comment]
Fixed in Dev Build
