### ISSUE TITLE
BZZ - Wrong Long Country Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3192]
### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e02acaa1-1229-4aa0-b822-d32e482e491a)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/8b575831-7f01-453a-9b94-d85110391c93)

**Comment by runelead00** [comment]
Fixed in Dev Build
