### ISSUE TITLE
YEM - Incorrect Mentioned Character in the World Event

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3193]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Despite Ahmad bin Yahya is in charge of Yemen, Muhammad al-Badr is mentioned in the Royalist Victory in Yemen world event. 

### Steps to reproduce / Cause of the issue

1. To trigger the Oil Crisis.
2. The Yemeni civil war starts.
3. The royalists should win in the civil war.

### Expected behaviour

Muhammad al-Badr is supposed to be a new king of Yemen.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/01d7154f-1c9a-4f32-b463-17549a7ff79f)

**Comment by runelead00** [comment]
Fixed in Dev Build
