### ISSUE TITLE
Germany Bormann - different type of spellings

### ISSUE THREAD

**Issue by Luckerducker123** [TNODevs/TNO-Bug-Tracker#3196]
### HOI4 version

1.14.3

### TNO version

1.5.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/152777320/c4ce631a-8656-4a35-9fc0-7081e722d6ab)
both words marked with red

### Additional information

Defense is spelled "Defense" in american english
However it is spelled "Defence" in british english.
But in the focus, there is spelling of both the british english and american english.
Sure, technically it might still be correct english, but yeah.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
