### ISSUE TITLE
SAU - Send Volunteers During the Oli Crisis

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3198]
### HOI4 version

1.14.2

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Add Saudi Arabia an opportunity send volunteers to allied countries during the Oil Crisis.

### Justifications

When the Oil Crisis starts, almost all the starting civil war world events emphasize Saudi Arabia's participation in the civil wars and helping their allies. However, it doesn't show in game so Saudi can't help anyhow them actually, I think it would make sense to add Saudi to send volunteers because they have enough divisions to do it.

**Comment by runelead00** [comment]
We're not adding this for skeleton that's changing in the near future, not to mention how completely that would destroy balance
