### ISSUE TITLE
USA - McNamara described as Secretary of Defense for Bennet even though he's not

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#320]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use:
Music Mod

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [ ] 1.  McNamara is described as secretary of defense in this event for one of the Community of Free Nations focuses, but Clark Giffords is the in-game Secretary of Defense
![McNamara not Sec Defense](https://user-images.githubusercontent.com/56777501/143663848-9ab897e0-e8a4-40f5-912b-7ed6d8039ce0.png)

**Comment by fedacking** [comment]
Fixed in dev build, thanks for report.
