### ISSUE TITLE
EGY - Incorrect Country Names after the civil war.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3200]
### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

When Italian Egypt wins in the civil war, it gets the Kingdom of Egypt/the Republic of Egypt instead of Regno d'Egitto/Repubblica d'Egitto. They should get it because they have them before + all direct colonies of Italy have Italianized names.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/74e1fe3b-afe3-4c83-80eb-1ad9a37201ba)

**Comment by Stormeagle449** [comment]
Italianized names for Egypt have been removed for patch 1.7.0

**Comment by Marok132** [comment]
> Italianized names for Egypt have been removed for patch 1.7.0

Alright. Thank you!

**Comment by Marok132** [comment]
> Italianized names for Egypt have been removed for patch 1.7.0

May I ask you to check #3412, #2999, #3262 and #3647, please? Thanks in advance.
