### ISSUE TITLE
Algerian Union (ILG), Republic of Iraq (IRQ) - Name Proposal

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3201]
### HOI4 version

1.14.2

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Give Italianized names for the Republic of Iraq (if it wins in the civil war) and Algerian Union if it's created.

### Justifications

Other Italian colonies have italianized names, and it would make sense to do the same for them. I also suggest to change their colours close to Italian ones such other colonies do.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/ba1a630d-44b0-4fa2-b43b-52ae883ac525)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/7e47e42e-e372-4796-a8e3-bfbe77d997b4)

**Comment by runelead00** [comment]
We're not implementing changes to skeleton that's changing in PW
