### ISSUE TITLE
Some Ostland Tags - Missing Focus Icons

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3207]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

There are not focus icons in these two focuses.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/c1f95abc-181e-404d-8990-af4438a97dd5)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/519f25ee-8937-478a-846e-a20e263874e1)

### Steps to reproduce / Cause of the issue

No need to explain.

### Expected behaviour

No need to explain.

**Comment by runelead00** [comment]
Fixed in Dev Build
