### ISSUE TITLE
IBR - Missing Focus Icons

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3209]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Two these focuses don't have focus icons.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e089808b-1a0a-4e52-b51c-60887448da9c)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a308a979-8d87-437b-9d44-cfebd396ab37)

### Steps to reproduce / Cause of the issue

Go to Paternalist Franco Path and wait to 1969.

### Expected behaviour

No need to explain.

**Comment by runelead00** [comment]
Fixed in Dev Build
