### ISSUE TITLE
USA - Domestic Discontent - None still gives you some debuffs

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#321]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use:

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [ ] 1. Domestic Discontent - None still gives you some pp, stability and war support debuffs. Maybe rename it to "Domestic Discontent - Budding" or "Domestic Discontent - Minimal" since no discontent would probably be just not having the national spirit

**Comment by Stormeagle449** [comment]
Fixed for UB
