### ISSUE TITLE
GER - Missing Focus Icon for The Reich's OKW focus.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3210]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

No focus icon for this focus.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/9b367b46-fad6-4f9b-8fee-ca7c26fbc276)

### Steps to reproduce / Cause of the issue

No need to explain.

### Expected behaviour

No need to explain.

**Comment by runelead00** [comment]
Fixed in Dev Build
