### ISSUE TITLE
SUR - No Elections 

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3211]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When any guys are elected in any elections, the game set no elections for Suriname.

### Steps to reproduce / Cause of the issue

Use this type of code and put them in each Suriname's election event so it will always have the election
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/675b09a5-2ba3-49e6-8929-102b18aa219c)

### Expected behaviour

The game should not set No Elections for Suriname elected guys.

### Screenshots

Here's an example of No Elections.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/0b08f7c9-c6b2-47ab-b07d-b54d6c383423)

**Comment by Stormeagle449** [comment]
Fixed for 1.6.0 release.
