### ISSUE TITLE
USA - Supporting Saudi Arabia focus tree lets you send volunteers to Italy but not Saudi Arabia

### ISSUE THREAD

**Issue by bobw123** [TNODevs/TNO-Bug-Tracker#322]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use:
Music Mod
- Were you using Steam?
Yes
- Which expansions do you NOT have?
I have all expansions

**Longer Description of Issue:**
Saudi Arabia seems like it's in a weird spot in the Oil Crisis, where the US can't support them with volunteers but apparently can support them in their focus tree. I ended up doing so because Nationalist Yemen won their civil war (I had no side to back there) and then proceeded to invade Saudi Arabia. I had no ability to intervene on their behalf, and the one focus that might've been able to change that says it lets the US help send more volunteers to Italy (who, if I'm not correct, do not directly fight in the oil crisis). 
![Reach out to Ridyah doesn't help](https://user-images.githubusercontent.com/56777501/143664156-747f01a0-2cac-4b69-ab39-f098ec8a3269.png)

I think this is a bit unbalanced too because the Germans send volunteers to Yemen but Saudi Arabia gets nothing
![Yemen gets support](https://user-images.githubusercontent.com/56777501/143664171-8e7346b8-ed66-4bc3-9552-502f4b00a7cf.png)
![Saudis Get Jack](https://user-images.githubusercontent.com/56777501/143664172-76c553c7-d339-4b39-97e4-55c1612ad311.png)

Ideally the US can support the Saudis with volunteers, and the focus branch allows them to send more volunteers.

**Steps to Reproduce/Cause Issue:**

1. Wait till oil crisis as USA

2. back Saudis and go down the tree

**Comment by runelead00** [comment]
Fixed in Dev Build
