### ISSUE TITLE
synthetic refinery 4 and 5 isnt working

### ISSUE THREAD

**Issue by mo0ncake0** [TNODevs/TNO-Bug-Tracker#3220]
### Operating System

Win10

### HOI4 version

1.14.5.01917 (d40a)

### TNO version

1.5.0c "The Ruin"

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

Synthetic refinery can only be build up to 3 levels and you cant build level 4 and 5 

### Steps to reproduce / Cause of the issue

You can research synthetic refinery lvl 4 and 5 but you will be only be able to build up to lvl 3.

### Expected behaviour

Expected to be able to build lvl4 and 5 synthetic refinery

**Comment by runelead00** [comment]
Fixed in Dev Build
