### ISSUE TITLE
Game crash - Select country

### ISSUE THREAD

**Issue by Hrutes** [TNODevs/TNO-Bug-Tracker#3221]
### Operating System

Windowns 10

### HOI4 version

1.14.5.0917 (d40a)

### TNO version

v1.5.0c “The Ruin”

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I dont have any, because the bug reporter does not work

### Describe the crash

When i select a country and click "play", the games loads ( Like in normal game ) and iwhen it finnaly loaded, it immediatly crash

### Steps to reproduce / Cause of the crash

1. Go to select a country
2. Select and hit play
3. Wait to load
4. When it loads, it crashes and appears the crash reporter

### Screenshots

I dont have any

### Additional information

I tried to solucianate it by using opengl as a launch option, but it didn't work

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/962, can only recommend possible fixes listed there
