### ISSUE TITLE
AWB - Missing Type of Economy

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3225]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Afrikaner Weerstandsbeweging does not have a type of economy.

### Steps to reproduce / Cause of the issue

1. African Schild competley wins in the SAW.
2. The Second South African Civil War starts.
3. Oberkommando Südafrika wins.
4. Oberkommando Südafrika collapses.

### Expected behaviour

Afrikaner Weerstandsbeweging should have a type of economy

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/1dc07fd6-8054-417c-bb49-dfcb678c3d19)

**Comment by runelead00** [comment]
Fixed in Dev Build
