### ISSUE TITLE
UFK - Mateus Mattoka Loses his subideology.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3227]
### Operating System

Windows 10

### HOI4 version

1.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

Toolpakt

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

For some reasons Mateus Mattoka loses his subideology in the current version. His sub was military junta.

### Steps to reproduce / Cause of the issue

1, African Schild competley wins in the SAW.
2. The Second South African Civil War starts.
3. Oberkommando Südafrika wins.
4. Oberkommando Südafrika collapses.

### Expected behaviour

Mateus Mattoka is supposed to have Military Junta like he has in the previous versions.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/162a922b-20ef-47ca-8d4a-7333f320eb34)

**Comment by runelead00** [comment]
He never was Military Junta
