### ISSUE TITLE
Omsk stuck in war with Tyumen for years

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#323]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

I'm playing Ironman Tomsk.

Omsk, to the west of me, has been at war with Tyumen (and now Sverdlovsk) for around 3 years. Neither nation appears to actually be attacking, which means that this war will likely continue indefinitely. Although it's hard to tell, I believe this behavior is locking me (Tomsk) out of westwards expansion.

I've been monitoring the casualties in the war and none (save for attrition) have occurred on any side for years.

(As Tomsk, I ran out of national focii in mid-1967 - as far as I can tell, I'll be unable to progress until 01JAN1969 when siberian unification opens up. Is this intended behavior?)

**Screenshots:**

![image](https://user-images.githubusercontent.com/711467/143664163-3a73b7b2-0fb7-4179-ba4a-d3186baca10f.png)
![image](https://user-images.githubusercontent.com/711467/143664170-d1098e99-f180-47d3-bea3-be05d17b4d52.png)

**Comment by runelead00** [comment]
should be fixed in current version, as well as fixed better for UB
