### ISSUE TITLE
England (Old, may be applicable to every country)

### ISSUE THREAD

**Issue by Hoohoohuey** [TNODevs/TNO-Bug-Tracker#3233]
### Operating System

Windows 11

### HOI4 version

latest version

### TNO version

latest version

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

so basically i tagged over to germany to check out what they were doing and then i unpaused as england and then my deficit rate went up to like 50% instantly from a surplus and then it didn't fix after two months.

### Steps to reproduce / Cause of the issue

1. play as some country with a decent military
2. let the ai take over for one day
3. check deficit rates

### Expected behaviour

the eonomy system to not bug out

### Screenshots

![Screenshot 2024-05-02 211349](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146782573/58cf9450-7679-4aed-88ec-8dfe2868bcb5)

**Comment by runelead00** [comment]
Letting the ai take over your country will break stuff, don't do that, we're not covering issues caused by use of console
