### ISSUE TITLE
COG - Reference to old Britain lore in event

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#3235]
### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/15214797/error.log)
[TNO.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/15214800/TNO.zip)

### List the loc issues below

<img width="487" alt="image" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/e5fff0df-10fc-418d-bafa-d6f774a147c8">

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
