### ISSUE TITLE
On non -ronman, save always gets corrupted.

### ISSUE THREAD

**Issue by BopoHex** [TNODevs/TNO-Bug-Tracker#3237]
### Operating System

macOS Ventura

### HOI4 version

1.14.5

### TNO version

1.5.0

### Do you have other mods in use?

2 West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

<img width="1440" alt="Screenshot 2024-05-08 at 17 29 39" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/169318523/146d45ca-2c8f-4a4e-a282-608798f3edfe">

### Describe the bug

On Non -Ironman, even without 2WRW, save always gets corrupted (cloud save), and it always fails to show correct GUI for all Russian warlords, as well as some other countries such as Afrikan RK's, and some Japanese puppets

### Steps to reproduce / Cause of the issue

1. Start the game in non-ironman 2. Save on cloud 3. Turn off tno (use other mod or no mod) but do not open the save 3. reopen tno along with 2WRW and the save gets cirrupted

### Expected behaviour

I expected for the ideology, leaders, and advisiors to load properly

### Screenshots

<img width="1440" alt="Screenshot 2024-05-08 at 17 29 39" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/169318523/34b41b71-ab2d-475c-86d8-c9361a7c9797">

### Additional information

I already looked, but could't find similar issues.

**Comment by runelead00** [comment]
Cloud Saves do not work with TNO
