### ISSUE TITLE
ENG - Poverty glitch

### ISSUE THREAD

**Issue by jonteboi0707** [TNODevs/TNO-Bug-Tracker#3238]
### Operating System

Windows 11

### HOI4 version

11.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Poverty turned from 40ish% to 30ish% after the civil war.

### Steps to reproduce / Cause of the issue

1 Play Collab Britian
2 Have the civil war.
3 Done

### Expected behaviour

The poverty to stay 40ish% or more after the war.

### Screenshots

![20240510151057_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146529932/826ed097-81b9-4433-b3a9-9253c0af0f4c)

![20240510163952_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146529932/d29b32fb-5f37-4811-a4fb-5f9dfa11f5cf)

**Comment by runelead00** [comment]
Fixed in Dev Build
