### ISSUE TITLE
ENG - Change the effect on a focus.

### ISSUE THREAD

**Issue by jonteboi0707** [TNODevs/TNO-Bug-Tracker#3239]
### HOI4 version

11.14.2

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

In the focus "Dousing England In Oil" make so that it also decreases the popularity in the pragmatic factions, ie mauldings and wilsons factions.

### Justifications

1 It looks better.
2 It would be strange if it decreased some pragmatics but not all of them.

### Screenshots

![20240511173134_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146529932/2cb75fc5-ac9e-49ce-9c8c-215a91691ccf)

**Comment by Stormeagle449** [comment]
Accepted.
