### ISSUE TITLE
Floating intelligence agency operation counter

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#324]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

This is a small graphical glitch probably related to how the 'New PUs available' gear icon is implemented.

**Steps to Reproduce/Cause Issue:**

1. Have no dismissible icons in that top row
2. Have some intelligence networks permitting operations
2. Grow GDP such that the 'New PUs' icon shows up (the green gear)
3. Dismiss the 'New PUs' icon
4. Floating number showing number of available operations appears to the right of the spy agency icon (see screenshot)

etc...

**Screenshots:**

![image](https://user-images.githubusercontent.com/711467/143664435-2bb5db41-4552-4449-8b23-d0dd8975c927.png)

**Comment by runelead00** [comment]
Fixed in Current release
