### ISSUE TITLE
Komi - In the event "Memories of Home" it says "Then the way with the Soviets began", when it should be "war", not "way"

### ISSUE THREAD

**Issue by Bigweevil** [TNODevs/TNO-Bug-Tracker#3240]
### HOI4 version

1.14.5

### TNO version

v1.5.0c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![LocalizationIssueKomiTNO](https://github.com/TNODevs/TNO-Bug-Tracker/assets/76667940/9f6a25be-2100-43e8-8979-56b2b35e217b)

**Comment by runelead00** [comment]
Fixed in Dev Build
