### ISSUE TITLE
GRE - Missing Long Party Description for Poulos' Bande in the Hellenic National State

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#3241]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[TNOsave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/15369844/TNOsave.zip)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/15369848/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/15369849/error.log)

### Describe the bug

Missing long description when hovering over party for Poulos' Bande (ultramilitarism).

### Steps to reproduce / Cause of the issue

1. Go fascist path for Italy.
2. Have Greek communist revolution.
3. Invade and capitulate Greece as Italy.
4. Hover over party and observe issue.

### Expected behaviour

Long description is present.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/77221733-6dcb-4878-89cd-2b614122bd4e)

**Comment by runelead00** [comment]
Fixed in Dev Build
