### ISSUE TITLE
Game crashes on startup when loading TNO

### ISSUE THREAD

**Issue by tommy3330** [TNODevs/TNO-Bug-Tracker#3242]
### Operating System

Windows 11

### HOI4 version

1.14.5.0917(d40a)

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/15372005/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/15372007/game.log)

### Describe the crash

Game begins to load before eventually crashing straight to desktop, not even giving a crash report to send to paradox.

### Steps to reproduce / Cause of the crash

1. Add TNO to playset and enable
2. Launch game

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/961, can only recommend possible fixes listed there
