### ISSUE TITLE
CAN - Constant Negative GPD Growth

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3249]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

At start, Canadian GDP growth is decreased all the game withiout any reasons, so the Canada's economy always ruins.

### Steps to reproduce / Cause of the issue

To set Canadian GDP growth on 1% at least.

### Expected behaviour

GDP growth must not ruin all the game.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/310b6629-18eb-41fd-85e3-1f0bf878b9bc)

**Comment by runelead00** [comment]
Working as Designed, not changing until Canada content
