### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Meatball23** [TNODevs/TNO-Bug-Tracker#3255]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT, TOA

### Files

[error.log](https://github.com/user-attachments/files/15522401/error.log)
[game.log](https://github.com/user-attachments/files/15522403/game.log)

### Describe the crash

When i selected country (Komi) and the game started to load (as usual), the game crasched (when it was almost loaded). A black screen appeared (for about a second) and then i was at the desktop.

### Steps to reproduce / Cause of the crash

I don´t know, I was just trying to load a country.

### Additional information

It is the first time I am trying to play the mod but it just keeps crashing.

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/962, can only recommend possible fixes listed there
