### ISSUE TITLE
CCP - Henry VII's France - Prime Minister bug

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3256]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod, TNO: Second West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Despite I set Pujo victory in the Henry VII's France - Prime Minister gamerule, Guichard still comes.

### Steps to reproduce / Cause of the issue

FRA_MONARCHIST_ELECTION_OUTCOME_PUJO is set in the FRA_SKELETON.40.c (Pujo option), so if you choose this option, you will never get him. There should be FRA_MONARCHIST_ELECTION_OUTCOME_ORMESSON instead of FRA_MONARCHIST_ELECTION_OUTCOME_PUJO in this event option.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/08b99f12-5bec-4149-8982-f02014bf301a)

### Expected behaviour

Pujo should take power by the gamerule.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/c06608c8-935e-4dff-a18b-e2192db54487)

**Comment by Stormeagle449** [comment]
Fixed for 1.6.0 release.

**Comment by Marok132** [comment]
> Fixed for 1.6.0 release.

Thank you.
