### ISSUE TITLE
Passive Borman

### ISSUE THREAD

**Issue by NifRon** [TNODevs/TNO-Bug-Tracker#3258]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO: Second West Russian War, The New Order: Last Days Of Europe (RUSSIAN)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Bormann came to power. He stops at central Europe. He refuses to attack other Reich commissariats. (The photo shows that it is already 1972, and Bormann has not yet attacked Ukraine, Ostland, the Caucasus and Muscovy)

### Steps to reproduce / Cause of the issue

1. Wait for Bormann's AI to win 2. Bormann captures Central Europe 3. Bormann stopped

### Expected behaviour

Bormann will continue to return the Reich commissariats to Reich control

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/171451529/d85e0bfa-9ae8-4ba7-a29f-c8ed9a8ded13)

**Comment by Marok132** [comment]
I'm not a dev. However, I would not recommend you to play the 2WRW at the moment because it breaks many scripts of vanila TNO.

**Comment by Stormeagle449** [comment]
Most likely the base mod is conflicting with the Second West Russian War submod.
