### ISSUE TITLE
Development of Russian nuclear weapons

### ISSUE THREAD

**Issue by NifRon** [TNODevs/TNO-Bug-Tracker#3259]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO: Second West Russian War, The New Order: Last Days Of Europe (RUSSIAN)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When reaching 100% in the development of nuclear weapons for any Russian warlord, development freezes at the last stage

### Steps to reproduce / Cause of the issue

1. Start developing nuclear weapons ... 2. Get to the last stage of development ... 3. When 100% is reached, the development freezes

### Expected behaviour

The development should be completed

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/171451529/ff47cf0c-0a4a-46a7-b7a1-65cbcca10cad)

**Comment by runelead00** [comment]
2WRW, not our issue
