### ISSUE TITLE
AST - No rename when it becomes a republic

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3261]
### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod, TNO: Second West Russian War

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

When Australia becomes a republic, it doesn't rename. 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/51e84fec-f8bf-4e8b-82ad-0663e76de6f9)

Upd: It happens only if a despotic guy comes to power.

**Comment by runelead00** [comment]
Fixed for next update

**Comment by Marok132** [comment]
> Fixed for next update

Thank you.
