### ISSUE TITLE
IBR - No loc for one tooltip 

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3263]
### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod, TNO: Second West Russian War

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/1d0e6707-6af7-4be0-8742-1622e8e82255)

**Comment by runelead00** [comment]
Fixed in Dev Build
