### ISSUE TITLE
ITA - Remove a core of the Ionian islands

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3264]
### HOI4 version

1.14.5

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Remove core of the Ionian islands for Italy.

### Justifications

The Ionian islands aren't integrated as part of Italy. It's just an occupied territory of Greece Italy received as a military base. I think it makes sense to remove an Italian core of this region.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/7ecc60e7-8a0c-4770-9177-9e5214297c84)

**Comment by runelead00** [comment]
Rejected, that's not how Italy handled the Ionian islands at all, they directly replaced Greek civilian government with their own and the region had been a target for annexation by the Italian irredentists even before the war
