### ISSUE TITLE
NYM - No Party names.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3266]
### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod, TNO: Second West Russian War

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The paternalist, despotic and communist parties don't have names.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/eb0128b7-a691-4378-87e3-fd785ecffc92)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e08e60a3-606d-456d-9f1c-33b92d28b873)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/896461cf-0e8a-4c3a-8efa-683147548bfb)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thanks!
