### ISSUE TITLE
CCP - Cantave's coup happens even if it's disabled (Haiti)

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3268]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod, TNO: Second West Russian War

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Despite I disabled any coups, Cantave's one still triggers.

### Steps to reproduce / Cause of the issue

The gamerules I used.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/aaab32c2-bbb6-4c6c-8508-1c127be99a2b)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/747f4699-f817-43fa-a070-09c8c4783531)

### Expected behaviour

The No Coup option in the Haiti - Anti-government coup should work correctly and prevent any coups.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/b2acb7b3-0cb2-4ec0-b9ed-dccb10e803aa)

**Comment by runelead00** [comment]
Should be fixed in current release
