### ISSUE TITLE
Communist Russias - Expanding COMECON 

### ISSUE THREAD

**Issue by optimisticdude** [TNODevs/TNO-Bug-Tracker#327]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**

When the COMECON economic sphere is made, it should be able to integrate new members of the COMECON organization for those who join the COMINTERN and are not in a different sphere.

**Reasoning Behind Suggestion:**

Allows for COMECON to be able to expand, allowing for the sphere to logically expand to aiding other socialist movements and countries as more socialist nations appear on the map due to events + unrest. 

**Additional Information:**

**Comment by ModdingAccount** [comment]
Added in Dev Build
