### ISSUE TITLE
EGY - Missing name when the civil war starts.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3271]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Egyptian civil war starts, the Kingdom of Egypt loses its long country name.

### Steps to reproduce / Cause of the issue

To trigger the Oil Crisis.

### Expected behaviour

Egypt must not lose its long country name.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/5a0738d7-d0f2-47e7-8e2e-86b3de956a96)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thank you!
