### ISSUE TITLE
CPP - Two missing party names.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3272]
### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

There are not party names for communist and proggresivist parties in Ghana.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/40dd5829-701b-4acc-94dc-b9f67896a44b)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/ab17c5d8-b4e4-4735-8a6f-3a2f49158f9d)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
