### ISSUE TITLE
GNB - Two missing party names.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3273]
### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

There are not party names for liberal and progressivist parties in Guinea-Bissau
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/b65438b0-1115-4a31-991e-2d0f3870165f)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/4249f81b-3e76-4666-a361-a3de19d15ac4)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
