### ISSUE TITLE
THA - No cores on some states.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3277]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Thailand does not have cores on Kalantan and Trangkanu, and Syburi and Palit. I've paid attention on them because some occupied regions in Camdodia (Phibunsongkhram), Laos (Lan Chang) and Saharat Thai Doem (Burma) are cored for Thailand. I think it should be done  for Malayan regions as well.

### Steps to reproduce / Cause of the issue

It's said above.

### Expected behaviour

Thailand should have cores on Kalantan and Trangkanu, and Syburi and Palit states.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/228e721d-1866-4c53-a84d-dccc830ad6f3)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/52ad1941-6d13-4465-9109-f024d60a6960)

### Additional information

If someone tells me it's intended, why are other occupied regions cored but not these two ones? What's the reason?

**Comment by Stormeagle449** [comment]
This is intended for now, but it's going to change in future updates.
