### ISSUE TITLE
JOR - Not joining the Levant Union.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3278]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Levant Union is formed, Jordan does not enter the faction for some reasons tho it has always done before.

### Steps to reproduce / Cause of the issue

1. The Second Italo-Turkish war starts.
2. Italy wins.
3. The Levant partition happens.

### Expected behaviour

Jordan should join the Levant Union as well.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/0ec2a93f-51d1-4387-95ba-40c6beaa1ae4)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/3b398126-81f6-4005-836d-40cbcca59ee7)

**Comment by Stormeagle449** [comment]
Fixed for version 1.5.0e
