### ISSUE TITLE
Siberian Free Territory - Can't do motions

### ISSUE THREAD

**Issue by SwynwrYDrwg** [TNODevs/TNO-Bug-Tracker#328]
**Questions**

- Operating System: windows 11
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? battle of bosporous 

**Longer Description of Issue:**
After completing the power struggle against stepanov and winning as pyotr, I can no longer access motions even if I unlock them in the focus tree. the box to select them is gone.
**Steps to Reproduce/Cause Issue:**

1. win power struggle as pyotr
2. open decisions
3. unable to access motions

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/94949348/143676443-289befec-8cb0-45a7-9ae2-0d36da323fa4.png)

**Comment by EnderTender** [comment]
I would like to add- reloading a save does not help or fix it.
