### ISSUE TITLE
ISR - Wrong names after independence

### ISSUE THREAD

**Issue by Taalul** [TNODevs/TNO-Bug-Tracker#3280]
### HOI4 version

1.14.5.0917

### TNO version

1.5.0c

### Do you have other mods in use?

Player Led Peace Confrences

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1. Safed should be called "Tzfat" post-independence. 
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/154693466/3f848116-0bff-421a-9bae-11202ef0eba4)

2. Acre should be called "Akko" post-independence.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/154693466/dab781a2-5d1d-45e8-9890-66302106455a)

3. Nablus should be called "Shkhem" or any other romanisation of "שכם" post-independence.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/154693466/f0c4f4b9-b55a-473f-9ab5-d43a0aa3e94f)

4. Araba should be called "Arava" post-independence.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/154693466/bcf58f59-9213-4924-af01-4d6b41d1a759)

5. Elath (state)'s name does not match the city after which it's named. (Also wrong location, will be opening a map issue)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/154693466/9554024f-617e-4b00-b35d-c66c788d4b33)

6. Beit Givrin didn't exist during the 60s and should be called "Beit Shemesh" after the larger, nearby, city.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/154693466/51e68c38-10f9-42a9-9df2-4fc4c71eca36)

### Additional information

Using the Endonyms/Native names mode.

**Comment by Taalul** [comment]
See also https://github.com/TNODevs/TNO-Bug-Tracker/issues/3281

**Comment by Taalul** [comment]
Gaza (State) stays Gaza post-independence instead of changing to Azzah
Araba (state) stays Araba post-independence despite that not being the Hebrew pronounciation, the actual pronounciation would be "Aravah" or "Arava'.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
