### ISSUE TITLE
[Bug]: ISR & JOR - Wrong location for Eilat.

### ISSUE THREAD

**Issue by Taalul** [TNODevs/TNO-Bug-Tracker#3281]
### Operating System

Windows 11

### HOI4 version

1.14.5.0917

### TNO version

1.5.0c

### Do you have other mods in use?

Player Led Peace Confrences

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Aqaba post-independence of Israel is renamed Eilat even though it's in Jordan.

### Steps to reproduce / Cause of the issue

1. Wait for the split up of the Levant.
2. Go to Jordan
3. Click on "Eilat"

### Expected behaviour

State and city stays "Aqaba"

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/154693466/e7a094ba-0f9c-4296-bdad-a359515c6a31)

**Comment by Taalul** [comment]
See also https://github.com/TNODevs/TNO-Bug-Tracker/issues/3280

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
