### ISSUE TITLE
CENTRAL ASIA - Cities are not visible on the map

### ISSUE THREAD

**Issue by D4ntheM4n** [TNODevs/TNO-Bug-Tracker#3283]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Despite having some large cities with a substantial population, central Asia has almost no cities or victory points listen on the map. This makes it look bizarre compared to the surrounding countries, 

### Steps to reproduce / Cause of the issue

Appears throughout the game 

### Expected behaviour

Add more victory points or make the cities more visible in Central Asia

### Screenshots

![hoi4_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107819293/37d769a5-e07a-4822-8b4d-ccc5d29a2150)

**Comment by Stormeagle449** [comment]
Try reloading the game without the 2WRW mod on and tell me if the issue still persists.

**Comment by D4ntheM4n** [comment]
> Try reloading the game without the 2WRW mod on and tell me if the issue still persists.

It does. It seems that cities in Central Asia all have very low victory points which means that they are barely visible on the map compared to surrounding cities.

**Comment by Marok132** [comment]
> > Try reloading the game without the 2WRW mod on and tell me if the issue still persists.
> 
> It does. It seems that cities in Central Asia all have very low victory points which means that they are barely visible on the map compared to surrounding cities.

I hope TNO devs add more VPs for Central Asian cities.

**Comment by Stormeagle449** [comment]
I see, closing this issue since it's WAD.
