### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by TNOBird1998** [TNODevs/TNO-Bug-Tracker#3285]
### Operating System

Windows 11

### HOI4 version

Bolivar v1.14.6.49ff (5a08)

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/user-attachments/files/15781175/error.log)
[game.log](https://github.com/user-attachments/files/15781177/game.log)

### Describe the bug

Went to different save files and every one of them wont allow me to see the foreign policies screen.

Only by starting a new game does it let me see the screen normally. There are also two notification boxes that appear in the top. One that says "consumer goods are empty" and the other that says "Pan African Liberation". Neither do a thing and can be dismissed without any effect.

### Steps to reproduce / Cause of the issue

1. Open saved game as USA
2. Open foreign policy tab
3. Nothing

### Expected behaviour

Expect it to be blank without any graphics and minimal choices.

### Screenshots

![20240610205639_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/172343267/1081ac77-2c61-4dc1-a09e-7189ceaf781d)

**Comment by Stormeagle449** [comment]
Don't reload old saves after mod updates cause they never work properly.
