### ISSUE TITLE
受影响的国家-问题简要描述

### ISSUE THREAD

**Issue by wangmingjun29281** [TNODevs/TNO-Bug-Tracker#3286]
### Operating System

evevccevec

### HOI4 version

c s c

### TNO version

ce ce c

### Do you have other mods in use?

jjkk

### Were you using Steam?

No

### Which major expansions do you NOT have?

LAR

### Describe the bug

你劝架劝架丝了不知道几年就剩你🐴天天出去卖养你，记得拿你🐴用b养你的钱买个股汇盒装你🐴剩下的股汇，操死你妈的漂客都不敢件你🐴的尸体，还不火亻匕你🐴是想把你🐴肿胀的逸体当充气娃娃租出去骗别人操你🐴逼？你件你🐴湿体害得你🐴b湿度过大，火亻匕你🐴怎么烧都烧不起来，还不紫砂给你天上的亲人赔罪。你🐴b被扩得能同时塞下好几根漂客的吊怎么生你的时候还能给你夹成大脑发育不全的恼谈啊？还是说你🐴是刚交后用刚门把你拉出来的？给后入你🐴漂嫖客磕头，要不是有人给你🐴刚门扩大点让你不至于被夹成智力障碍，不然你现在火亻匕你🐴能不顺便把你自己烧了去陪你劝架都是祖分冒烟，纱闭你🐴b水太多被火亻匕得半生不熟有没有你一份功劳，去口你🐴残留的湿体把你🐴水吸干吧丝🐴dinner

### Steps to reproduce / Cause of the issue

你劝架劝架丝了不知道几年就剩你🐴天天出去卖养你，记得拿你🐴用b养你的钱买个股汇盒装你🐴剩下的股汇，操死你妈的漂客都不敢件你🐴的尸体，还不火亻匕你🐴是想把你🐴肿胀的逸体当充气娃娃租出去骗别人操你🐴逼？你件你🐴湿体害得你🐴b湿度过大，火亻匕你🐴怎么烧都烧不起来，还不紫砂给你天上的亲人赔罪。你🐴b被扩得能同时塞下好几根漂客的吊怎么生你的时候还能给你夹成大脑发育不全的恼谈啊？还是说你🐴是刚交后用刚门把你拉出来的？给后入你🐴漂嫖客磕头，要不是有人给你🐴刚门扩大点让你不至于被夹成智力障碍，不然你现在火亻匕你🐴能不顺便把你自己烧了去陪你劝架都是祖分冒烟，纱闭你🐴b水太多被火亻匕得半生不熟有没有你一份功劳，去口你🐴残留的湿体把你🐴水吸干吧丝🐴dinner

### Expected behaviour

你屁眼里漏史漏到脑子了害得你脑子里塞满史和你🐴骨灰了？轮件你🐴的人太多了给你这瑙谈件出幻觉来了以为人人都是你跌到处认亲？放心你全家人都丝光了就剩你这没跌没🐴的榨种，脑子没你🐴私体匹眼大的洛制，我只能说你就这智力小心哪天出门被车碾丝去陪你劝架，还好你浮木双王得早，他们看你这b样不得被气丝？可惜你🐴刚门脱出你的时候让你沾了太多史导致你🐴不敢弄死你这脑贪了

**Comment by Marok132** [comment]
Wtf

**Comment by MrStraws114514** [comment]
Somebody's crazy and come here spamming useless things to show himself
pls close this issue and ban this guy if can
