### ISSUE TITLE
AFG - Islamist Portrait is Zahir Shah

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#3288]
### Operating System

Windows 11

### HOI4 version

1.14.6

### TNO version

1.5.0c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the GFX issue

Zahir Shah still has his portrait when Islamists take over.

### Steps to reproduce / Cause of the issue

Have Islamists coup as the skeleton content intends (either do this manually through console, or railroad it.), and voila. 

### Expected behaviour

Should not be Zahir Shah's portrait. 

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/94796674/8be784cf-0a6b-4a69-b62d-02905cc06daa)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
