### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Dankku08** [TNODevs/TNO-Bug-Tracker#3289]
### Operating System

windows 10

### HOI4 version

Well latest one

### TNO version

Again Latest One

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, BBA, AAT, TOA

### Files

Well when ever there is a popup about a war or decipher when i press enter or click the continue button nothing seems to happen its stuck on my screen and i can NOT Get rid of it whitout relaunching my game

### Describe the GFX issue

Well when ever there is a popup about a war or decipher when i press enter or click the continue button nothing seems to happen its stuck on my screen and i can NOT Get rid of it whitout relaunching my game

### Steps to reproduce / Cause of the issue

Just wait for a war decleration popup or any other diplomatic popup

### Expected behaviour

I expected the popup to be gone but it stayed and did not disapier

### Screenshots

![dfdffg](https://github.com/TNODevs/TNO-Bug-Tracker/assets/172467099/ef6c2a79-75e9-45da-b933-93c26aadc5c3)

### Additional information

I was not able to put any screenshots here but basically i cant get rid of popups like war declerations and such becouse it does not let me click the continue button on screen

**Comment by Dankku08** [comment]
Nevermind the screenshot came up but still its there and cant get rid of it

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
