### ISSUE TITLE
Omsk - Siberian Black Army - Tomsk war ending, leading to crash

### ISSUE THREAD

**Issue by heckbell** [TNODevs/TNO-Bug-Tracker#3290]
### Operating System

Windows 11

### HOI4 version

v1.14.6.49ff

### TNO version

v1.5.0c

### Do you have other mods in use?

five nights at hoi4

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Files

[game.log](https://github.com/user-attachments/files/15804151/game.log)
[error.log](https://github.com/user-attachments/files/15804202/error.log)

### Describe the crash

The game freezes, and paradox crash reporter opens up asking me what happened before the crash

### Steps to reproduce / Cause of the crash

1. Open up TNO
2. Play as Omsk
3. Do all focus trees until tara and isilkul pacifying
4. Use decision.nochecks in commands (without disabling)
5. Complete the pacification
6.  Siberian Black Army / Tomsk war is (hopefully) going on
7. War ends
8. Crashes

**Comment by runelead00** [comment]
Crashes need saves to properly troubleshoot
