### ISSUE TITLE
Reichskommissariat Ukraine

### ISSUE THREAD

**Issue by KieronKelk** [TNODevs/TNO-Bug-Tracker#3291]
### Operating System

Windows 11

### HOI4 version

1.14.6.49ff

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT

### Files

[error.log](https://github.com/user-attachments/files/15822651/error.log)
[game.log](https://github.com/user-attachments/files/15822653/game.log)

### Describe the crash

Game just crashes straight away as soon as hitting 1963 October 25th 01:00. Only occurred as playing as Reichskommissariat Ukraine not any other nation.

### Steps to reproduce / Cause of the crash

- Play as Reichskommissariat Ukraine
- Go Ukrainian National Revolution Army Path
- Play till 1963 October 24th at 24:00
- Next hour the game crashes even at 1 speed or pausing as soon as it turns to the next hour

**Comment by runelead00** [comment]
Crashes need saves to properly troubleshoot
