### ISSUE TITLE
USA - Blank Foreign Policy Tab

### ISSUE THREAD

**Issue by UncleFunke** [TNODevs/TNO-Bug-Tracker#3292]
### Operating System

Windows 11

### HOI4 version

1.14.6.49ff 

### TNO version

v1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Files

[game.log](https://github.com/user-attachments/files/15853173/game.log)
[error.log](https://github.com/user-attachments/files/15853214/error.log)
(I am unable to upload my save file, github says it does not support the .hoi4 file type.)

### Describe the bug

The U.S.A foreign policy tab is blank, No buttons or previews for anything. Even clicking the 2 options tabs at the top do nothing. It simply broke one day after booting the game. I have updated the mod, the June 15th 2024 patch, and it didn't fix it.

### Steps to reproduce / Cause of the issue

1: Load into game
2: Click on foreign policy tab

### Expected behaviour

I should be able to see the Iceland election, the middle east oil war options, alongside the spy choices. 

### Screenshots

![20240615122352_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/172932859/7c5768b6-e017-4e2f-a943-3a6add3f8bb5)

### Additional information

reclosing, waiting for an event popup, or waiting in general does not fix it

**Comment by Stormeagle449** [comment]
Try starting a new game as the USA and tell me if the issue still persists.

**Comment by UncleFunke** [comment]
> Try starting a new game as the USA and tell me if the issue still persists.

I started a new game and it works fine, seems to be only that save file.

**Comment by Stormeagle449** [comment]
I'm closing this issue then.
