### ISSUE TITLE
Most countries of the world have a white color 

### ISSUE THREAD

**Issue by Lenzo2001** [TNODevs/TNO-Bug-Tracker#3293]
### Operating System

macOS

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool mod, Second West Russian War, TNO - Göring expanded, Precise Buffs - cheat ideas, add building slot fixed, 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

none

### Describe the bug

Earlier this day, everything was fine, but after the recent update today I noticed a HEAVY bug in the game. Almost all the countries of the world now had a flashing white colour. The only few countries not affected by it, were Germany, Ostland, Moskowien, Kazachstan, Turkmenistan, China and a few others. Even when trying to start a new campaign the same bug appeared. I tried to play the game without the Second West Russian War submod, but then the game crashed on its own. 

Can you fix this problem? I placed a screenshot down below to make you see what I mean.

### Steps to reproduce / Cause of the issue

none

### Expected behaviour

none

### Screenshots

<img width="1485" alt="TNO Bug picture" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/147545608/fdf3cdfc-7a94-40f9-916f-1d509acaeaa9">

### Additional information

None

**Comment by Lenzo2001** [comment]
On top of that, I also just noticed that when playing as the USA and Germany , you get the option to select the elections of Brazil. For Brazil, a Russian unifier, Burgundy, the UK, Ireland, China and the Iberian Union you get the option for the elections in the USA. And for Japan I get the option to select both the elections of the USA and Brazil.

**Comment by runelead00** [comment]
As with every update, dont play submod until they are compatible
