### ISSUE TITLE
The Peace_on_action issue.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3295]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

For some unknown reasons but when a Russian faction wins in Kazakhstan it triggers white_finland.2 event in 420 days for Finland despite this event is tied with the Finnish civil war.

### Steps to reproduce / Cause of the issue

Remove this line from the TNO_peace_on_actions.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/bc3bdece-1c59-45ae-947e-30dd99c78b53)

### Expected behaviour

The white_finland.2  should not trigger when the Russian faction wins in Kazakhstan.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/67bd4333-fe41-4d5f-adaf-eaae03de52c6)

**Comment by runelead00** [comment]
Fixed in Dev Build
