### ISSUE TITLE
ENG - Core issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3296]
### Operating System

Windows 10

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Free Britannia gets lots of Atlantic islands, it doesn't have cores on most of them besides Ascension, Saint Helena the Falkland islands.

### Steps to reproduce / Cause of the issue

1. Free Britannia wins in the civil war.
2. The Sealion II doesn't happen.
3. The socialist revolution does not happen.

### Expected behaviour

They should be either all cored or not cored.

### Screenshots

The states that have no cores.

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/028a1e7d-bb7c-4a30-af0d-41e18b5c892a)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/b181688b-d39d-41d6-842b-70c2cb00ec4e)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a1e0be59-19c5-409e-8b12-b721f29dac4e)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/4493985d-ef6b-47e9-8c99-11d2fcadb3fa)

The states that have cores.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/940fe3e0-4c97-44a2-aa27-52d0be75b4eb)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/c2cb1ec3-346c-474e-bc50-004afa6e5282)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/291d781f-f652-4f92-81a5-5ed688718d39)

**Comment by Stormeagle449** [comment]
WAD, the islands in the Atlantic Ocean are technically not considered part of Britain proper, but are still part of its sovereign territory. This status is represented in game by having those states as colony rather than fully cored by Britain.

https://en.wikipedia.org/wiki/British_Overseas_Territories

**Comment by Marok132** [comment]
> WAD, the islands in the Atlantic Ocean are technically not considered part of Britain proper, but are still part of its sovereign territory. This status is represented in game by having those states as colony rather than fully cored by Britain.
> 
> https://en.wikipedia.org/wiki/British_Overseas_Territories

Then why do those three states (Ascension, Saint Helena the Falkland islands)  have cores? They are the British Overseas Territories as well.

**Comment by Stormeagle449** [comment]
> Then why do those three states (Ascension, Saint Helena the Falkland islands) have cores? They are the British Overseas Territories as well.

These states have also had their cores removed and been turned into colony states.
