### ISSUE TITLE
USA - USA_HCW_PPLN_Uprising_tt has no localization in The Status of the War decision timer

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3299]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.6

### TNO version

1,5,0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/user-attachments/files/15860236/USA_game.zip)

### Describe the bug

The Status of the War decision timer effect has shown the `USA_HCW_PPLN_Uprising_tt` has not yet localize.

And the Legitimacy for the HCW is still broken by the way.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI starts.
3. Trujillo overthrown.
4. USA continues to support the Legion.
5. The Caribbean Legion victory in the DCW.
6. Socialist/Communist Revolution in the Dominican Republic.
7. The HCW starts.
8. At least two Haitian states have suppressed the PPLN.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/a6646bd4-fbf5-436c-956b-e99a2e3ea5e1)

**Comment by ModdingAccount** [comment]
Fixed in Dev build
