### ISSUE TITLE
Free Indonesia - Missing Focus Icon for "Help From India"

### ISSUE THREAD

**Issue by runelead00** [TNODevs/TNO-Bug-Tracker#33]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?  None

**Longer Description of Issue:**
Icon from Free Indonesian focus Help From India is missing.

**Screenshots:**
![gfx1](https://user-images.githubusercontent.com/74165171/128481907-88fe2732-cae4-488b-b116-ae2c6cb59049.jpg)

**Comment by ModdingAccount** [comment]
Issue fixed in dev build.
