### ISSUE TITLE
speer germany, von landhut's ostland - ostland doesn't join the zolverein, doesn't become a puppet, doesn't join the war against moskowien

### ISSUE THREAD

**Issue by demanvanwezel** [TNODevs/TNO-Bug-Tracker#330]
**Questions**

- Operating System: windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0.d
- Any other mods in use: non
- Were you using Steam? yes
- Which expansions do you NOT have? no step back

**Longer Description of Issue:**
if you finish the german civil war as speer prior to the ostland civil war ending and you intervene in favour of von landshut's ostland then they join the einhietspakt but not the zolverein, they also don't want to join against moskowien because of "dangerous borders"

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed for UB
