### ISSUE TITLE
USA - PPLN declares war on Haiti after one day, despite The Status of the War decision timer to wait until 35 days

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3300]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.6

### TNO version

1,5,0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/user-attachments/files/15860468/USA_game.zip)

### Describe the bug

The Status of the War decision timer effects shows the PPLN will start the uprising in 35 days but after running the game in one day, the PPLN suddenly declares war on Haiti rather than to wait for 35 days to start the uprising. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI starts.
3. Trujillo overthrown.
4. USA continues to support the Legion.
5. The Caribbean Legion victory in the DCW.
6. Socialist/Communist Revolution in the Dominican Republic.
7. The HCW starts.
8. At least two Haitian states have suppressed the PPLN.
9. PPLN declares war on Haiti.

### Expected behaviour

I don't know.

### Screenshots

![Image_one](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/9e80637f-bf90-4838-b9c0-b0f7fa35d2b2)

![Image_two](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3e263b99-fb9c-4eed-8b45-c9fe64322089)

**Comment by ModdingAccount** [comment]
Clarified in Dev Build
