### ISSUE TITLE
USA - Authorize Air and Navy Support Operations are not including target on socialist Dominican Republic

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3302]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/user-attachments/files/15861325/USA_game.zip)

### Describe the bug

When the PPLN and Socialist/Communist Dominican Republic declare war on Haiti, the 'Authorize Air-Support and Navy-Support Operations' decisions are not including socialist Dominican Republic to have negative national spirits.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. PPI starts.
3. Trujillo overthrown.
4. USA continues to support the Legion.
5. The Caribbean Legion victory in the DCW.
6. Socialist/Communist Revolution in the Dominican Republic.
7. The HCW starts.
8. At least two Haitian states have suppressed the PPLN.
9. PPLN and Socialist/Communist Dominican Republic declare war on Haiti.

### Expected behaviour

Forgot to include Socialist/Communist Dominican Republic to have negative effects.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/071f3f0b-3a38-4185-9f46-23ba7dce872f)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f9c50d32-75fb-4c86-9427-03716efd7ad8)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
