### ISSUE TITLE
USA The foreign policy tab is empty

### ISSUE THREAD

**Issue by manueldavidoj** [TNODevs/TNO-Bug-Tracker#3303]
### Operating System

Windows 11 

### HOI4 version

v.1.14.6.49ff (7c52) (s)

### TNO version

v.1.5.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I had saved a game and i loaded it again when i noticed some weird notifications on the game notifications which said "breadbasket action available" i clicked on it  various times and nothing happened so I dismissed and continued playing until I tried to open the foreign policy tab to manage the intelligence agency and there was nothing I couldn't interact with the global conflicts tab also.  

### Steps to reproduce / Cause of the issue

save the game as the US
load it from the menu

### Expected behaviour

i expected to be able to open and interact with the intelligence agency and global conflicts tab

### Screenshots

<img width="960" alt="Screenshot 2024-06-17 023833" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/29528049/17b17c12-4723-4ba0-a112-8bc60d54af3a">

<img width="960" alt="image" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/29528049/4303cac6-aad7-4041-b6e4-31a49cc2bb3a">

### Additional information

i saved the game the day after I won the Iranian Civil War the event about me winning had appeared and when I clicked the game froze for 1 minute. also,

**Comment by runelead00** [comment]
Standard Post-Update Jank
