### ISSUE TITLE
FIN - News Event Incorrectly Fires

### ISSUE THREAD

**Issue by averagetomskenjoyer** [TNODevs/TNO-Bug-Tracker#3306]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

In July 1969, "The End of Finnish Democracy" event incorrectly fires for some reason when Fagerholm is president. It might be because Finland has a fascist prime minister at the same time.

### Steps to reproduce / Cause of the issue

1. Play as any country
2. Wait until the aformentioned time
3. Presumably have Fagerholm and a fascist pm at the same time

### Expected behaviour

The event should not fire when Finland's democracy is perfectly fine.

### Screenshots

![20240616222144_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/148972379/a714b700-7c39-4286-9979-b87716b6fd84)

**Comment by runelead00** [comment]
Fixed in Dev Build
