### ISSUE TITLE
Russian Far East - Brotherhood Fragment State capitulates but does not become annexed, leading to a state of endless war

### ISSUE THREAD

**Issue by Bowieno** [TNODevs/TNO-Bug-Tracker#331]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: Toolbox Theory 
- Any other mods in use: Only TNO music submods, state transfer tool (four mods total).
- Were you using Steam? Yes
- Which expansions do you NOT have? Bosphorus DLC

**Longer Description of Issue:**

Vyatka unifies Western Russia after defeating Black League splinter states. Battle to unify the east is between Rurik and the remnants of Men's Brotherhood, which has collapsed. I am playing as Iberia.

a. Rurik fails to declare war on all of the fragment states. Most of the ones he declares war on he isn't even bordering.
b. Vyatka conquers Rurik, declares war on all successor states apart from the actual 'Brotherhood' ; conquers them all. But there is no capitulation event for the Partisan Republic of Buryatia. Instead they appear on the war screen as capitulated but the war drags on. Vyatka cannot declare war on the Brotherhood and unite Russia

**Steps to Reproduce/Cause Issue:**

1. Ensure the collapse of Alexander Men's Brotherhood.

2. See what happens when Rurik (or any other unifier) attempts to declare war on the fragment states and if any get left out.

3. In addition, see if the rump states capitulate properly.

etc...

**Screenshots:*
![tno bug](https://user-images.githubusercontent.com/82480840/143690413-7434772f-4296-43db-9e97-1f712d962ad0.PNG)
*

**Comment by runelead00** [comment]
No longer an issue on UB
