### ISSUE TITLE
USA - Change the event picture for Bennett's 'Inauguration Day'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3311]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

1. I would like to suggest the event picture of Bennett's 'Inauguration Day' should be changed to Bennett's election post picture.

### Justifications

The event picture for Bennett's 'Inauguration Day', however, uses the generic RDC voting picture instead of uses the Bennett's voting post or any Bennett's voting image. 

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/bd8b272d-58b8-4f1a-a2db-1793fa20d69e)

**Comment by Stormeagle449** [comment]
Accepted.
