### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Meta-typhy** [TNODevs/TNO-Bug-Tracker#3312]
### Operating System

macOS Monterey

### HOI4 version

Bolivar v1.14.6.49ff (5a08)

### TNO version

(can't find it sorry, subscribed 6/15/2024)

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Describe the bug

When the Divine Mandate appeared in Siberia, some of the descriptions for the event were not present. This was true for Madagascar (and potentially other countries I didn't play as). The Divine Mandate also was missing a focus tree throughout the play through, this and some other countries I also played (Madagascar, Free Indonesia, Switzerland... I don't know if these even have focus trees but just in case, I wanted to point it out).

When the Divine Mandate was doomed to collapse, the collapse event did not have a fleshed out description compared to the other events. This was an oddity that I noticed both when the Divine Mandate was being founded, the Malagasy elections or Madagascar's final alliance decision.

### Steps to reproduce / Cause of the issue

I'm not sure how to reproduce it as it may be on my end only but this is what I did:
1. Subscribe to TNO 6/15/2024
2. Play without other mods (and without DLC)
3. Choose Far Eastern Siberia
4. Wait for Alexander Men to materialize
5. Notice that some event popups lack descriptions
6. Notice that the Focus Tree is still missing

### Expected behaviour

I expected a description for most event popups in the countries that I was playing (Madagascar/Divine Mandate). And I was expecting a focus tree for the Divine Mandate.

### Screenshots

![Screen Shot 2024-06-20 at 21 21 11](https://github.com/TNODevs/TNO-Bug-Tracker/assets/173377534/7f38bfda-d426-47ac-b6a8-0b658727f7d2)
![Screen Shot 2024-06-20 at 21 23 18](https://github.com/TNODevs/TNO-Bug-Tracker/assets/173377534/7c6b7b6a-9485-4ad5-b9f6-da95b8fb78c1)
(Same thing for Madagascar)

### Additional information

This is an issue I noticed because in other playthroughs, the Divine Mandate had a focus tree. And also the fact that some national event pop ups are missing descriptions.

**Comment by Marok132** [comment]
Men and the Divine Mandate  was removed in TT3

**Comment by runelead00** [comment]
^this plus Madagascar and Indonesia were removed when their respective civil wars were overhaul well over a year ago now, and Switzerland never had any focus tree to begin with
