### ISSUE TITLE
TNO broken

### ISSUE THREAD

**Issue by Issacdurden** [TNODevs/TNO-Bug-Tracker#3313]
### Operating System

Windows 10 Pro

### HOI4 version

None (Not using any betas just regular)

### TNO version

https://steamcommunity.com/sharedfiles/filedetails/?id=2438003901&searchtext=+The+new+order (i dont know how to fill this im sorry)

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

No save available

### Describe the bug

I was trying to boot up TNO as usual i had Second West Russian,everyone with shades,fps maps,etc it was going well until the next day it was all bugged the map was white and i didnt know what was wrong, i turned off all the mods including Second West Russian, and try to load up but it failed and it crashed i do not know why

### Steps to reproduce / Cause of the issue

-

### Expected behaviour

-

### Screenshots

![bug](https://github.com/TNODevs/TNO-Bug-Tracker/assets/173391757/231e85dd-9228-41c3-a9bd-e3a4f9ba9f5a)
![bug](https://github.com/TNODevs/TNO-Bug-Tracker/assets/173391757/8cd73d18-3ec4-4828-a031-66a09a70d030)

### Additional information

There's also me trying to boot up regular TNO but it just crashed without explanation

**Comment by Stormeagle449** [comment]
It's most likely a 2WRW submod integration problem, my only advice here is either to play TNO without that submod active or wait until the 2WRW devs release an updated version.
