### ISSUE TITLE
[Bug]:  Map coloring

### ISSUE THREAD

**Issue by jimbo0810** [TNODevs/TNO-Bug-Tracker#3314]
### Operating System

windows 11 home

### HOI4 version

current version

### TNO version

current version

### Do you have other mods in use?

instant naval invasion, instant paratrooper drop, 2wrw mod, alantropia

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/user-attachments/files/15919375/error.log)

### Describe the bug

most countries on the map are colored white while a few such as germany, the african colonies and japan are colored in 

### Steps to reproduce / Cause of the issue

problem appears at country selection menu and during game play

### Expected behaviour

I expected the map to be colored in 

### Screenshots

![Screenshot 2024-06-20 122837](https://github.com/TNODevs/TNO-Bug-Tracker/assets/138622718/6f5cce55-ee70-4cec-b39c-3e7efd470d9a)
![Screenshot 2024-06-20 122847](https://github.com/TNODevs/TNO-Bug-Tracker/assets/138622718/ac008f65-a38a-4180-bc6d-0e13be866f89)
![Screenshot 2024-06-20 123322](https://github.com/TNODevs/TNO-Bug-Tracker/assets/138622718/089efb80-248c-4d23-9b91-1214ddbba569)
![Screenshot 2024-06-20 122713](https://github.com/TNODevs/TNO-Bug-Tracker/assets/138622718/ebc5e498-ac67-427f-b28b-7c9ba826eb54)
![Screenshot 2024-06-20 122818](https://github.com/TNODevs/TNO-Bug-Tracker/assets/138622718/6fb0cfa6-05f3-4bbc-ae05-754ce7a4b734)

### Additional information

game appears to still be playable, topographical features and other visual graphics are still there

**Comment by Marok132** [comment]
As TNO devs say many times, do not use submods until they are updated.

**Comment by jimbo0810** [comment]
All mods and submods are up to date

**Comment by runelead00** [comment]
No they are not

**Comment by Issacdurden** [comment]
i turned off the 2WRW but i still crashed i turn off all of my submobs idk where i did wrong
