### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by Issacdurden** [TNODevs/TNO-Bug-Tracker#3316]
### Operating System

Windows 10 Pro

### HOI4 version

Current

### TNO version

Current

### Do you have other mods in use?

FPS map,player led conference,automatic city name changer,10 support companiest tno,goering expanded,shades,eco cheat

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

None

### Describe the crash

i was trying to boot up TNO but when it fully loads aswell me trying to play it crashed for unknown reason

### Steps to reproduce / Cause of the crash

1.load up the game
2.wait for it to load
3.sucessfully load
4.crash

### Screenshots

![bug 2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/173391757/8dc74c5d-12d4-4059-8f84-f7869ead5b6c)

### Additional information

😭😭

**Comment by Marok132** [comment]
Try to disable ALL mods and submods besides TNO

Also why do you use a player led conference mod in TNO where the ones are disabled

**Comment by Stormeagle449** [comment]
Merged into https://github.com/TNODevs/TNO-Bug-Tracker/issues/962, can only recommend possible fixes listed there

**Comment by Issacdurden** [comment]
> Merged into #961, can only recommend possible fixes listed there

Thanks, i'll try them soon

**Comment by Issacdurden** [comment]
> Try to disable ALL mods and submods besides TNO
> 
> Also why do you use a player led conference mod in TNO where the ones are disabled

i forgot i enabled them

**Comment by Marok132** [comment]
> > Try to disable ALL mods and submods besides TNO
> > Also why do you use a player led conference mod in TNO where the ones are disabled
> 
> i did disable everything it works but i wanna use the submobs

Wait when the submods are up to date.

**Comment by Issacdurden** [comment]
> > > Try to disable ALL mods and submods besides TNO
> > > Also why do you use a player led conference mod in TNO where the ones are disabled
> > 
> > 
> > i did disable everything it works but i wanna use the submobs
> 
> Wait when the submods are up to date.

How do i check the submods are up to date i forgot

**Comment by Marok132** [comment]
> > > > Try to disable ALL mods and submods besides TNO
> > > > Also why do you use a player led conference mod in TNO where the ones are disabled
> > > 
> > > 
> > > i did disable everything it works but i wanna use the submobs
> > 
> > 
> > Wait when the submods are up to date.
> 
> How do i check the submods are up to date i forgot

Check their workshop pages and look the latest date update

**Comment by Issacdurden** [comment]
> Merged into #961, can only recommend possible fixes listed there

Excuse me, i follow all the tutorials, i even deleted and tried booting it up it works regular on TNO but i wanted to try to submods, the submods i use was only Dont Surf, but it kept crashing before i got to the main menu,the HOI4 for me did not automatically re-install itself after i tried many attempts loading and signing off but it wont work, until i eventually go to the files and repair it but it still didnt work, the submod Dont Surf, its up to date but when i try other submods it didnt work even though it was up to date
was i missing something wrong? Because when i look at the tutorial and the pictures it didnt load it dissapeared for some reason
any help is appreciated🙏

**Comment by runelead00** [comment]
>  the submod Dont Surf, its up to date 

Is there a submod also named Don't Surf I don't know about or are you trying to use the 4 year old, extremely outdated TNO demo on-top of modern TNO and expecting it work?
