### ISSUE TITLE
Basically all saves - Foreign Policy broken and notifications that shouldn't be there

### ISSUE THREAD

**Issue by JP2208wasntavailable** [TNODevs/TNO-Bug-Tracker#3318]
### Operating System

Linux Mint

### HOI4 version

Bolivar v1.14.6.49ff 

### TNO version

The Ruin v1.5.0d

### Do you have other mods in use?

technically a self developed one and The Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT, TOA

### Files

[Savegame.zip](https://github.com/user-attachments/files/15929067/Savegame.zip)

### Describe the bug

For some reason all my savefiles have been corrupted in some way that the Foreign Policy UI is completely blank (and the text on top of it reads "Brazil-Zentralafrika Settlement" instead of Foreign Policy and I notifications for RKUs Breadbasket Decisions and the American presidential campaign, even though Im not playing either of them. Also Icons and descriptions for economic systems are broken, instead they show question marks and the names of intellieance agencies 

This has basically broken my current Japan playthrough, since Indonesia just collapsed but now i cant do anything about it.

Also while i cant check the FP on there, the RKU and US notifacations now also appear I if load my old Burytia save, which has been completed for a few weeks now.

### Steps to reproduce / Cause of the issue

What happened before the bug showed up:
1. Was playing normally and had even already reached Indonesia Collapse, UI still worked there
2. Wanted to quickly speed through events as spectator to view Croatian Spring, so started new game as Iceland, but did nothing in there
3. This set me back a bit as the progress with Japan had been on the autosave, didnt notice at the time
4. Got about trying to translate a bit of the mod myself, so locally created a mod to that end
5. Worked on it for a bit, but DID NOT change anything about tno itself
6. The wrong notifications an wonky eco icon started appearing when testing the translation
7. Today wanted to continue playing after a week of diy translation
8. Also installed the last Waltz, as i found the addional music interesting
9. Disabled diy translation in launcher, set language back to english
10. Noticed the f***ed up UI
11. Disabled everything which wasnt tno itself, even reinstalled it
12. Still didnt fix the issue
13. Save probably corrupted by me meddling with TL

### Expected behaviour

Didnt expect those bugs to still be there after disabling TL

### Screenshots

https://steamcommunity.com/sharedfiles/filedetails/?id=3272228567

### Additional information

I know i basically screwed up, since this is very likely the result of testing my diy translation, but is there any way to still save the file? I dont really want to start from scratch

**Comment by JP2208wasntavailable** [comment]
P.S. the indonesian global conflict hadnt fired when i wrote this, heres what the page looks like with it active

https://steamcommunity.com/sharedfiles/filedetails/?id=3272246824

**Comment by Stormeagle449** [comment]
If you modified your game with submods of your own making then we can't help you. We suggest playing the mod without it.
