### ISSUE TITLE
JAP - I400 submarine cannot be deployed

### ISSUE THREAD

**Issue by Zhuravlik-Z80** [TNODevs/TNO-Bug-Tracker#3319]
### Operating System

Windows11

### HOI4 version

1.14.6

### TNO version

v1.5.0d

### Do you have other mods in use?

Japanese Localization

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The I400 submarine can be built when Japan plays but cannot be deployed.

### Steps to reproduce / Cause of the issue

in ship_hull_submarine.txt
in ship_hull_submarine_japan_special
		type = {
			submarine
		}
		type = {
			submarine
			carrier
		}
and it is now deployed.
Perhaps that will solve the problem.

### Expected behaviour

It will be deployable.

**Comment by Stormeagle449** [comment]
This unit doesn't exist anymore.
