### ISSUE TITLE
ZIM - The leader game rules' effect got wrongly reversed

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#3323]
### Operating System

Windows 11

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

there's a game rule setting to set who will take power in ZIM after GRO collapses, ultranationalism or socialism
but the effect of it got upside down
if u set socialism to take power, system will spawn ultranationalism leader, if u set ultranationalism, system will spawn socialism

### Steps to reproduce / Cause of the issue

as the title
In the relevant code, when player set socialism leader, code will make the chance of socialism taking power to be 0%, lead to ultranationalism
and same to ultranationalism

### Expected behaviour

ZIM's leader can works as the game rule describes

**Comment by runelead00** [comment]
Fixed in Dev Build
