### ISSUE TITLE
The mod is cracking on the loading screen

### ISSUE THREAD

**Issue by knigthhhh** [TNODevs/TNO-Bug-Tracker#3328]
### Operating System

Windows 10 pro 22H2

### HOI4 version

Bolivar v1.14.6.49ff (50a8)

### TNO version

Bolivar v1.14.6.49ff (50a8) Last version of mod 

### Do you have other mods in use?

Radio TNO: Music of New Order. TNO Tradução PT-BR. Immersive music mod - Axis.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[code_revisions.log](https://github.com/user-attachments/files/15942192/code_revisions.log)
[error.log](https://github.com/user-attachments/files/15942193/error.log)
[system.log](https://github.com/user-attachments/files/15942196/system.log)
[dlc_load.json](https://github.com/user-attachments/files/15942197/dlc_load.json)
[exception.txt](https://github.com/user-attachments/files/15942198/exception.txt)
[gameplaysettings.txt](https://github.com/user-attachments/files/15942199/gameplaysettings.txt)
[mods_registry.json](https://github.com/user-attachments/files/15942200/mods_registry.json)
[pdx_settings.txt](https://github.com/user-attachments/files/15942202/pdx_settings.txt)
[settings.txt](https://github.com/user-attachments/files/15942203/settings.txt)

### Describe the crash

When starting the game, the mod maintains the default loading for a few minutes, almost finished or already a little more than halfway through the music crashes and the game crashes. This issue has occurred twice

### Steps to reproduce / Cause of the crash

1. Start the game
2. Wait for the game to load
3. the game badge while at the end while it was finishing loading

**Comment by Marok132** [comment]
Try to disable other mods but TNO.

**Comment by Stormeagle449** [comment]
Try to follow the solutions listed here: #961, and if it doesn't work reopen the issue. 

I doubt it's the music mods, but disable mods that are not updated to the current HOI4 version just in case.
