### ISSUE TITLE
MPLA/Angola - Leaves Comecon after the Civil War.

### ISSUE THREAD

**Issue by christianzk** [TNODevs/TNO-Bug-Tracker#333]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: TT Release Version
- Any other mods in use: TNO Radio, TNO Music Mod
- Were you using Steam? Yes
- Which expansions do you NOT have? N/A

**Longer Description of Issue:**

I was playing as Zhukov in the West Russian Revolutionary Front—I had unified West Russia and joined the COMINTERN (Which the PRC founded). We had created COMECON and the International Brigades, which we invited the MPLA to following the beginning of the Angolan Civil War. They joined, but after they won the war and formed the Union of African Socialist Republics they left COMECON and joined the Japanese economic sphere. I was told by Sino on the discord that their leaving the COMECON sphere was an unintentional outcome and that I should write about it here.

**Steps to Reproduce/Cause Issue:**

1. Begin the Angolan Civil War. 

2. Invite the MPLA to the Comintern, integrating them into the Comecon economic sphere.

3. Support them until their victory in the civil war.

4. They should form the UASR and join the Japanese economic sphere, leaving Comecon but remaining in the Comintern.

**Screenshots:**

I don’t have a save which can display both. Just imagine the MPLA being in COMECON during the civil war and leaving/joining the Japanese sphere afterward.

**Comment by Stormeagle449** [comment]
Should be fixed in latest version.
