### ISSUE TITLE
GER/CAU - Kaukasische Militärregierung is not set to 'Military Government' puppet status after Speer reconquers Kaukasien

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3331]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_kaukasien.zip](https://github.com/user-attachments/files/15944300/GER_kaukasien.zip)

### Describe the bug

When Speer's Germanic Reich reconquers Reichskommissariat Kaukasien through war, Kaukasische Militärregierung is not set to 'Military Government' puppet status instead becoming an Autonomous Reichskommissariat despite the Kaukasische Militärregierung is under military control. 

### Steps to reproduce / Cause of the issue

1. Speer wins the German Civil War.
2. Germany retakes former territories in Europe.
3. Germany attacks Reichskommissariat Kaukasien 
4. Kaukasien becomes Kaukasische Militärregierung under Pleiger.

### Expected behaviour

Probably, oversight again.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/e91aa083-7c87-41d4-ab76-6102c0362efe)

**Comment by Marok132** [comment]
Add my notes; all eastern European Militärregierungs have incorrect puppet or faction status.

**Comment by runelead00** [comment]
Fixed in Dev Build
