### ISSUE TITLE
BLZ - Philip Goldson's controversial ideology

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3334]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Philip Goldson from Belize is elected in 1965, his leader ideology is liberal conservatism (big tent). However his minister ideology is liberalism (national liberalism). I'm not certain sure it's fine.

### Steps to reproduce / Cause of the issue

1. The HMMLR wins in the ECW and survives during the Channel Crisis.
2. Non-socialist faction wins in the British elections.
3. Philip Goldson should win in the 1965 election.

### Expected behaviour

Philip Goldson's minister ideology should coincide with the leader one.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/2aedfc30-bd89-4f95-9d74-5a19a6abf6b7)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/91338361-d91b-40e1-9e39-e214385eb566)

**Comment by runelead00** [comment]
Non-issue
