### ISSUE TITLE
Ostland / Germany- Andreas gets replaced with generic leader upon getting puppeted by Speer

### ISSUE THREAD

**Issue by JamesNicod** [TNODevs/TNO-Bug-Tracker#334]
Just as stated, Andreas Meyer-Landrut gets replaced with a generic leader if Speer diplomatically puppets him
![unknown](https://user-images.githubusercontent.com/95150440/143723215-78d9bd60-b1f0-407c-a4be-ef53460fa7f9.png)

**Comment by runelead00** [comment]
Fixed in Current Release
