### ISSUE TITLE
ENG - Collab Britain core issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3340]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Britain has no cores on Tyrone and Fermanagh despite it has the same on Ulster. This state is also included in the workshop of the world mech.

### Steps to reproduce / Cause of the issue

To add core on Tyrone and Fermanagh for the Collab Britain.

### Expected behaviour

It's said above.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a6b0c727-41a6-46ce-a618-71ebbfa1b89d)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e0bfea90-8beb-45d4-8b43-7a266a790a89)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0, but we added claims not cores due to lore.

Thanks!
