### ISSUE TITLE
TYM - Old Kazakh lore issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3341]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The Contact the Remaining SSRs and Support Central Asia focuses mentions old Kazakh lore when there was a warlord era.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/6e029d7c-2aea-4caf-a088-c2b902455969)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/16d4bed2-dba3-47c2-941f-165335cc8695)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
