### ISSUE TITLE
NOV - Old Kazakh Lore

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3342]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The focus "a Kazakh Consulate" mentions old Kazakh lore with warlords.
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/76e4d3aa-89d2-49f9-bea2-27fc872fc41f)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
