### ISSUE TITLE
German Reich Speer's war against Burgundy

### ISSUE THREAD

**Issue by Wulfric28** [TNODevs/TNO-Bug-Tracker#3349]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

 v1.5.0d “The Ruin”

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/user-attachments/files/15957796/error.log)
[game.log](https://github.com/user-attachments/files/15957797/game.log)

### Describe the crash

In 1970 when I'm as Speer's Germany starting a war against Burgundy and other countries on the west, game crashed after 5-7 days right before capitulation I suppose...

### Steps to reproduce / Cause of the crash

I don't know how you can fix this crash, I suppose its have nothing to do with mod, but patch of the game. I played few starts with TNO before and finished without problem.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Wulfric28** [comment]
> Fixed in Dev Build

Thank you very much, I'll try tomorrow!
