### ISSUE TITLE
Jellicoe's United Kingdom - Game crashes at precisely Nov 7th, 1971 at 24:00

### ISSUE THREAD

**Issue by NibbledPots** [TNODevs/TNO-Bug-Tracker#335]
- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version:  v1.2.0d “Toolbox Theory”
- Any other mods in use: Radio TNO
- Were you using Steam? yes
- Which expansions do you NOT have? No Step Back, Battle for the Bosporus, La Resistance, Man the Guns, Waking the Tiger, Death or Dishonor, Together for victory

**Longer Description of Issue:**
Pretty straightforward issue, I was using max speed, but I've tried it on other speeds and the same thing happens. At 24:00 Nov 7th, 1971, the game crashes to the desktop almost immediately. Maybe a half-second freeze, and then it crashes. 

**Steps to Reproduce/Cause Issue:**
I don't know what I'm doing to cause the issue, so I'll just write up what going on right now
1. Got all focuses for Jellicoe's first term, and some for the second (Fig. 1)

2. Large military buildup in southern England (Fig. 2)

3. I was passing the investigations act through parliament
4. Large Navy in the English Channel and north sea (Fig. 3)

**Screenshots:**
Fig. 1 
![focustree](https://user-images.githubusercontent.com/74081242/143721675-9f0b9bdf-23cf-4f61-85fc-17559ce93c39.png)

Fig. 2 
![army](https://user-images.githubusercontent.com/74081242/143721678-2d799000-e31e-48e4-bae7-289622f9913e.png)

Fig. 3
![navy](https://user-images.githubusercontent.com/74081242/143721679-a83f421e-93c1-40a3-af53-e9d9dd512fa0.png)

**Game Save:**
Game save from a little before Nov 7th
[ENG_1971_06_16_23 (2).zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7612456/ENG_1971_06_16_23.2.zip)

**Comment by seby154** [comment]
Hm i have this problem too, but as Speer's Germany and in the same year
