### ISSUE TITLE
KEM - The old kazakh lore in the focus "Friends in the Steppe"

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3351]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/dcf6cc7c-cae2-4f72-bd7a-4e5d0e875247)

### Additional information

You should also make this focus to bypassed if Kazakhstan is communist.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
