### ISSUE TITLE
DRL - Mentioned of the Kazakh Warlords in the country overview

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3352]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/9f12e7ec-e5d2-4dd7-882a-0de6fd0d6db9)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
