### ISSUE TITLE
USA - Slight issue in focus effect of 'The Financial and Monetary Conference'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3353]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/user-attachments/files/15969539/GER_play.zip)

### Describe the bug

In 'The Financial and Monetary Conference' focus effects, I see `double ` OFN members who already invited the CFN that do not show what effects on them. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Bennett as the new president.
3. See the national focus effects of 'The Financial and Monetary Conference'.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/6ab77a6d-6660-4914-882e-b8abf218042c)

**Comment by Marok132** [comment]
It does. It refers to USA_WFB_CFN_voting. However yeah there should be a tooltip. I hope devs add it.

**Comment by runelead00** [comment]
Fixed in Dev Build
