### ISSUE TITLE
USA - No adding USA to declare war on Burgundy and SS legions in the 'France Requests Support for Burgundy Intervention' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3354]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/user-attachments/files/15969994/GER_play.zip)

### Describe the bug

In the 'France Requests Support for Burgundy Intervention' event effects, there is no adding USA to declare war on Burgundy and SS native legions, despite the texts from the event and news event saying that USA has intervened in the Burgundy collapse. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Free France won the West Africa War.
3. Free France reclaimed France. 
4. French Republic and its West African allies join the OFN.
5. Burgundy collapsed.

### Expected behaviour

Probably forgot to add USA to declares war on SS legions.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/288f709c-89c2-480d-b6d5-7cdced4a4e47)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/55c064cc-46a2-4cae-ad1d-61d75af4edf5)

**Comment by Marok132** [comment]
The US will declare war later. Just wait  for one day lol.

**Comment by runelead00** [comment]
Fixed in Dev Build
