### ISSUE TITLE
Undefined GUI_TYPE: confirmation_popup_window cause the game to crash

### ISSUE THREAD

**Issue by TommyCantCode** [TNODevs/TNO-Bug-Tracker#3355]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

a few music mods and other things, i'll get into details later

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/user-attachments/files/16006486/game.log)
[error.log](https://github.com/user-attachments/files/16006490/error.log)

Save game cannot be uploaded here apparently, GitHub does not accept .hoi4 files but I could be contacted to sent one if needed be

### Describe the crash

Game crashes when I unpause after a while. There aren't that many details except for the logs file I've sent. At first the game crashed at seemingly random intervals going from days to months, but after a certain period it became more consistent and crashed before the 10th of May, 1968.

### Steps to reproduce / Cause of the crash

There are no steps to this. Playing the game with TNO on my save cause this crash. I would send a save game here if it was possible but GitHub does not seem to support .hoi4 files unless there is a way that I haven't figured out yet.

### Additional information

I've launched the game with two different presets, one with all the submods installed, which includes Radio TNO; Radio TNO Thai; Radio TNO Thai 80s-90s; Release Nations; and a modified version of Night 24/7. The other was with the bare mod, TNO itself. In both circumstances the results were crashing as described. The only cheat used while I was playing Yunnan is to boost maximum military spending as fighting the GAW with a subpar budget is a pain in the ass.

**Comment by TommyCantCode** [comment]
Tried it before, no luck. Tried it again, still no luck. Guess that means this is a save game problem. Makes sense too considering all my other playthroughs didn't get the same error despite enabling the same mods. Guess this is case closed then.

**Comment by runelead00** [comment]
Fixed in Dev Build, not a save game issue
