### ISSUE TITLE
BRY - BRY.90 event issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3357]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The event "A visit to London" uses old English lore (England, English, etc).
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/9e119040-f022-4f11-a414-0bc7ff323d1b)

**Comment by Stormeagle449** [comment]
WAD, "England" and "English" are totally valid synonyms for "United Kingdom" and "British".
