### ISSUE TITLE
KOM - England mentions in some Komi events.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3358]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [x] 1. komi_dem_generic.15
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/33e620fe-ea85-4afc-b410-10699a15fb16)
- [x] 2. komi_dem_generic.22
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/21c18327-08dd-4be7-b54a-e407c58f1075)
- [x] 3. komi_dem_generic.23
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a39a63d4-4033-4302-abee-2981ff11e6dd)

**Comment by Stormeagle449** [comment]
Fixed for 1.6.0 release.
