### ISSUE TITLE
KOM - The focus Appeal for Recognition mentions England instead of Britain.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3359]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/00bd2c8f-f349-4874-8734-b3efc5b9bb70)

**Comment by runelead00** [comment]
Fixed in Dev Build
