### ISSUE TITLE
USA - West African Conflict Silent Sitatunga Lacking Pre-requisite

### ISSUE THREAD

**Issue by Kurgis** [TNODevs/TNO-Bug-Tracker#336]
**Questions**

- Operating System: Win 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: Last Waltz
- Were you using Steam? Yes.
- Which expansions do you NOT have?
    Death or Dishonor
    Waking the Tiger
    Man the Guns
    La Resistance
    Battle for Bosporus

**Longer Description of Issue:**
The AI may have issues being able to take this decision repeatedly, it should check whether or not Cameroon has the National Spirit already, or have a cooldown timer applied.

**Steps to Reproduce/Cause Issue:**

1. Enact Operation Silent Sitatunga.

2. Cameroonians get "Egyption Snooping".

3. Enact Operation Silent Sitatunga.

4. Cameroonians already snooped.

**Screenshots:**
![oss](https://user-images.githubusercontent.com/35203040/143729114-273d9972-1648-4d15-9667-e13f1c93125a.png)

**Comment by Kurgis** [comment]
I'd like to just leave the off-hand comment that I really enjoy small details like these, it brings the geopolitical situation together in a cool way, as if you're actually affecting the Earth rather than isolated statelets.

**Comment by runelead00** [comment]
Current Dev Build has restricts visibility for Cameroon to not have the spirit
