### ISSUE TITLE
GER - a mention of England in bormann.1504

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3360]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/5c6ca2b6-31a6-4eca-b5fb-7365b7b77ce3)

**Comment by runelead00** [comment]
Fixed in Dev Build
