### ISSUE TITLE
USA - 'The Accords Are Signed' event didn't appear after selecting the détente with Germany event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3361]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_GER_detente.zip](https://github.com/user-attachments/files/16015413/USA_GER_detente.zip)
[Logs.zip](https://github.com/user-attachments/files/16028569/Logs.zip)

### Describe the bug

After selecting the at least one, two or all German agree in Speer's detente with USA event, the 'The Accords Are Signed' event is not pop out. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Speer won the German Civil War.
3. USA has RDC in charge of the country.
4. Speer chooses the détente with USA.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/f82c5093-cdef-4fc1-aaf4-e86b9924511c)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/3d211d7f-76c0-4ae3-937e-419c13299014)

**Comment by runelead00** [comment]
Fixed in Dev Build
