### ISSUE TITLE
BUR - Game Crash after I start WW3

### ISSUE THREAD

**Issue by gmd1999** [TNODevs/TNO-Bug-Tracker#3362]
### Operating System

Win 11

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

NONE

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[code_revisions.log](https://github.com/user-attachments/files/16037306/code_revisions.log)
[error.log](https://github.com/user-attachments/files/16037307/error.log)
[system.log](https://github.com/user-attachments/files/16037308/system.log)
[game.log](https://github.com/user-attachments/files/16037325/game.log)
[dlc_load.json](https://github.com/user-attachments/files/16037328/dlc_load.json)
[exception.txt](https://github.com/user-attachments/files/16037329/exception.txt)
[gameplaysettings.txt](https://github.com/user-attachments/files/16037330/gameplaysettings.txt)
[mods_registry.json](https://github.com/user-attachments/files/16037331/mods_registry.json)
[pdx_settings.txt](https://github.com/user-attachments/files/16037332/pdx_settings.txt)
[settings.txt](https://github.com/user-attachments/files/16037333/settings.txt)

### Describe the crash

After I start WW3 (Buryatia fight against Germany), the game will crash very frequently. Hard to tell what caused the crash. 

### Steps to reproduce / Cause of the crash

[16:52:13][1979.12.29.23][gui.cpp:931]: Undefined GUI_TYPE: confirmation_popup_window - This will most likely crash the game
This is the last line I found in "error.log" file. Not sure if it is helpful or not

**Comment by runelead00** [comment]
Fixed in Dev Build
