### ISSUE TITLE
GER - Second and third options have no decreasing tension between USA and GER from the 'Conference of Global Security and Co-Cooperation' part 1 event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3363]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_detente_with_usa.zip](https://github.com/user-attachments/files/16038522/GER_detente_with_usa.zip)

### Describe the bug

In the 'Conference of Global Security and Co-Cooperation' part 1 event, the second and third options have no decreasing tension between USA and GER while other options have the decrease tension. 

### Steps to reproduce / Cause of the issue

1. Speer won the German Civil War.
2. USA has RDC in charge of the country.
3. Speer chooses to détente with USA.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/054bd63c-c1fe-4dea-9047-ff971b86926f)

**Comment by runelead00** [comment]
Fixed in Dev Build
