### ISSUE TITLE
USA/GER - No adding 'The Toronto Accords' in Past Incidents from the Cold War tension tab 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3364]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_detente_with_usa.zip](https://github.com/user-attachments/files/16038833/GER_detente_with_usa.zip)

### Describe the bug

When détente between RDC's USA and Speer’s Germany succeed, there in no 'The Toronto Accords' appeared in Past Incidents from the Cold War tension tab after selecting some agree option in the 'Conference of Global Security and Co-Cooperation' event and completing the 'Toronto Accords' focus. 

### Steps to reproduce / Cause of the issue

1. Speer won the German Civil War.
2. USA has RDC in charge of the country.
3. Speer chooses to détente with USA.
4. Détente between USA and Germany success.

### Expected behaviour

Forgot to add to the Past Incidents from the Cold War tension tab.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/73a865c6-cb1c-499a-b34f-b78c6cea5985)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fe8a308e-1e0d-481c-818b-27cfa1ae7e76)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/dabf9828-876d-4b4d-8abd-b1a6aee67ef1)

**Comment by runelead00** [comment]
Fixed in Dev Build
