### ISSUE TITLE
USA/JAP - Misspelled "Shooutout" in Past Incidents from the Cold War tension about the Indonesian crisis

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3365]
### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/user-attachments/files/16039038/USA_play.zip)

### List the loc issues below

- [x] 1. There is a misspelled "Shooutout" in Past Incidents from the Cold War tension about the Indonesian crisis. It should be "Shootout". 
![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/db24f6b3-efd2-4b6d-8958-0f2159b17513)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
