### ISSUE TITLE
USA - The 'Northern Fury' national spirit doesn't get removed when the liberal or conservative Civil Rights Act passed

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3366]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_bennett_cr.zip](https://github.com/user-attachments/files/16039166/USA_bennett_cr.zip)

### Describe the bug

When the liberal or conservative Civil Rights Act passed during Bennett presidency, the 'Northern Fury' national spirit doesn't get removed and when reaches to 1970s, the 'Northern Fury' national spirit still exists. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Nixon vetoed the Civil Rights Act.
3. Have the Northern Fury national spirit.
4. Buffing Northern Fury national spirit in the event.
5. Bennett elected as the new president.
6. Either liberal or conservative civil right act passed. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/2004c749-ab8a-4241-a5a1-b7c71a19852d)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/199672d8-d268-437e-a5fc-8bc143aefb19)

![Image_3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/fd3be762-1d11-4873-8423-119e25b62f35)

**Comment by runelead00** [comment]
Fixed in Dev Build
