### ISSUE TITLE
DEFCON 1 Difficulty - Some countries are not able to build any equipments with it

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#3373]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

DEFCON 1 gives player a very powerful debuff
![}9YCTL746P8P QXN{OTI6(E](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/aadab9dd-b6c4-4923-8043-1fc801234721)
and if player is SAF, that will directly make factories dead
-4% cap
![Y R2LIE}WMLKJ204RT@F)U9(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/2921c4b0-c469-45e6-b1e3-a13779abb284)
Not able to make anything
![MNLWC 1S7OV~KJ56~8X68YF(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/68838991-dfaf-4eb0-ba4f-a1da3c9b2c43)
also happen on WRS
![}YN~WCHM8UYCDV({EKJ0GFK](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/9671890d-055a-4154-b319-7a531458ac94)
CHI
![4EWJXB`D~VI2LS1I ~TJULT(1)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/432c4bb6-4653-4d3e-b5a8-223f63196773)

### Steps to reproduce / Cause of the issue

cause of the issue has been explained above
my suggestion is to increase defcon 1 debuff to be -20% cap from -30%, or increase base cap to 60% from 50%

### Expected behaviour

These countries are able to make equipments with defcon 1

**Comment by runelead00** [comment]
Reduced debuff
