### ISSUE TITLE
A couple of design errors.

### ISSUE THREAD

**Issue by OCPD86** [TNODevs/TNO-Bug-Tracker#3374]
### Operating System

Windows 11

### HOI4 version

1.14.5.0917 (c4ff) (S)

### TNO version

1.5.0d

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Look at the screenshots.

### Steps to reproduce / Cause of the issue

Look at the screenshots.

### Expected behaviour

Just fix it.

### Screenshots

![Screenshot 2024-07-01 165443](https://github.com/TNODevs/TNO-Bug-Tracker/assets/174353026/b8c8560a-530e-461e-a482-725ce31cd6e5)
![Screenshot 2024-07-01 170146](https://github.com/TNODevs/TNO-Bug-Tracker/assets/174353026/3d39380a-341b-40c8-8271-a4404e2b8b27)

**Comment by runelead00** [comment]
1, Paradox Issue, Can't Fix
2. Fixed in Dev Build

**Comment by OCPD86** [comment]
> 1, Paradox Issue, Can't Fix
In such cases, in my country they say: “You either take off your pectoral cross or put on your panties.”

Is this solution not suitable? Of course with rebalancing.
![Screenshot 2024-07-02 173632](https://github.com/TNODevs/TNO-Bug-Tracker/assets/174353026/4aeb6308-7045-4054-b558-a2229f3b6472)

**Comment by runelead00** [comment]
we're not redesigning one of the doctrine trees because of a minor graphical issue
