### ISSUE TITLE
USA - There is 'Add .' appear in 'The Essential Ambassador' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3378]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_rdc.zip](https://github.com/user-attachments/files/16082623/USA_rdc.zip)

### Describe the bug

When 'The Essential Ambassador' event appeared and showed the event's effect, there is an 'Add .' appeared without showing related effects to it.

Probably this event is intended to add a political minister named "Donald Rumsfeld" but he was already added in the political minister when the Romney inauguration triggered.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect George Romney as the new president.
3. Romney inauguration. 

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/0bc0ad7d-b744-420d-bbe9-12bcef1c8f96)

![Image_2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/b9323018-aa37-443a-b7c6-cb3a4b1ed463)

**Comment by runelead00** [comment]
Fixed in Dev Build
