### ISSUE TITLE
National Protection army (yunnan) - The game just crashes everytime i play for a few days.

### ISSUE THREAD

**Issue by Ilay191** [TNODevs/TNO-Bug-Tracker#3379]
### Operating System

Windows 11

### HOI4 version

1.14.6

### TNO version

v1.5.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[YUN_1967_06_02_21.zip](https://github.com/user-attachments/files/16083009/YUN_1967_06_02_21.zip)

### Describe the crash

it just crashes for no reason. i have no mods im at the latest version of hoi4 and this mod. i didnt use any commands. and it happens after i started the war of liberation against japan but i dont think they are related.

### Steps to reproduce / Cause of the crash

Go to the save  i sent. Play for a few days. and it crashes. 

### Screenshots

none

### Additional information

no additional information

**Comment by runelead00** [comment]
Fixed in Dev Build, if you want to patch it yourself in the meantime, swap out this file in the interface folder of the mod

**Comment by runelead00** [comment]
oops didn't attach the first time because github doesn't like .gui files
[tno_peace_popup.zip](https://github.com/user-attachments/files/16088744/tno_peace_popup.zip)

**Comment by runelead00** [comment]
and that was wrong file, sorry
[popupwindow.zip](https://github.com/user-attachments/files/16104812/popupwindow.zip)
