### ISSUE TITLE
USA - Glenn Will Start World War Three If He Doesn't Get The 1968 Nomination

### ISSUE THREAD

**Issue by Kurgis** [TNODevs/TNO-Bug-Tracker#338]
**Questions**

- Operating System: Win 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: Last Waltz
- Were you using Steam? Yes.
- Which expansions do you NOT have?
    Death or Dishonor
    Waking the Tiger
    Man the Guns
    La Resistance
    Battle for Bosporus

**Longer Description of Issue:**
_Glenn takes over the Ohio Missile Center, in utter horror the world watches on as his Socialist goons televise the impending Nuclear Armageddon he shall soon bring down upon the Fascist orders of the world._

The event triggered around the 21 of January, 1969, before the inauguration events even fired.

**Steps to Reproduce/Cause Issue:**

1. Continue The Great Society as Lyndon B. Johnson after winning the 1968 Elections.

2. Glenn breaks into the Ohio Missile Center.

3. He cannot be stopped.

Note: In sincerity, I have zero clue how this occurred, though I took a save of the game immediately once the event appeared.

**Screenshots:**
![Glenn_Cannot_Be_Stopped](https://user-images.githubusercontent.com/35203040/143732326-d7d9cef7-ca52-47bb-9152-4b7679037401.png)

**Comment by Kurgis** [comment]
If any details are needed I have the save, so feel free to question about this, I assume another Glenn event reacting to the LBJ administration was meant to fire instead perhaps.

**Comment by Stormeagle449** [comment]
Not relevant anymore since Glenn is getting cut for UB.
