### ISSUE TITLE
COL - No Bios for several leaders.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3380]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Misael Eduardo Pastrana Borrero, Manuel Mosquera Garcés, Carlos Alberto Lleras Restrepo, Hernando Durán Dussán and Roberto Urdaneta Arbeláez don't have bios.

**Comment by runelead00** [comment]
Non-Issue, if something doesn't have a desc, it doesn't have a desc
