### ISSUE TITLE
AFG - Has a weird claim on Jammu

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3381]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files
A fix of this bug.
[1318-Jammu.txt](https://github.com/user-attachments/files/16234226/1318-Jammu.txt)

### Describe the bug

AFG has a claim of Jammu for no reasons and I think it's weird because...

1. AFG does not have common borders with this state and it's far away from AFG.
2. This state is the only one in India where AFG has a claim that looks weird. I should say this claim looks like the random set one and AFG wasn't supposed to have it.

### Steps to reproduce / Cause of the issue

Remove a claim for AFG.

### Expected behaviour

AFG should not have a claim of Jammu.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/a63bf7ba-e285-4023-8e64-f5514cd6ba04)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Marok132** [comment]
> Fixed in Dev Build.

Thank you!!
