### ISSUE TITLE
CHI - Tao Xisheng does not have effects as minister.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3384]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Tao Xisheng does not have a minister trait.

### Steps to reproduce / Cause of the issue

To give him some trait.

### Expected behaviour

Tao Xisheng should have a trait.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/d8eb72c8-9dd8-4677-8196-9414fdcb45e9)

**Comment by Fortune801** [comment]
Fixed, thank you

**Comment by Marok132** [comment]
> Fixed, thank you

You're welcome.
