### ISSUE TITLE
National Protection Army(Yunnan) - Game always crashes on the eighth of April, 1967 and I have no clue what causes it other than a GUI issue according to the error logs 

### ISSUE THREAD

**Issue by Colbai10** [TNODevs/TNO-Bug-Tracker#3385]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

Logs: https://1drv.ms/u/s!AnlNuQS_LQMChf9KHecgNVD-_zRTGQ?e=bGnc02
Save: https://1drv.ms/u/s!AnlNuQS_LQMCkO1_J3NF9CYjWOJZZw?e=XAnnpX

### Describe the crash

Before the game would systemically crash on the 8th, it used to crash normally every month.  I have no clue what causes the crash besides a GUI error according to the last error code: [02:02:23][1967.04.08.05][gui.cpp:931]: Undefined GUI_TYPE: confirmation_popup_window - This will most likely crash the game

### Steps to reproduce / Cause of the crash

Wait until the eighth 

### Additional information

As mentioned before, it used to crash once every few months or so but now it always crashes on this date.

**Comment by runelead00** [comment]
Fixed in Dev Build, to continue your playthrough, you can swap out this file in the interface folder of the mod
[tno_peace_popup.zip](https://github.com/user-attachments/files/16103251/tno_peace_popup.zip)

**Comment by Colbai10** [comment]
> Fixed in Dev Build, to continue your playthrough, you can swap out this file in the interface folder of the mod [tno_peace_popup.zip](https://github.com/user-attachments/files/16103251/tno_peace_popup.zip)

Do I have to download the nexus version in order to replace this file or can I just find it in its folder in the steam workshop?

**Comment by runelead00** [comment]
yes you can just swap this out in the steam version

**Comment by runelead00** [comment]
somehow included the wrong version of the file, sorry, should work on steam
[popupwindow.zip](https://github.com/user-attachments/files/16104809/popupwindow.zip)
