### ISSUE TITLE
SER - No Effects for the natspirit "Zealots, Conservatives, and Comformists

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3386]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

There aren't effects for the natspirit "Zealots, Conservatives, and Comformists".

### Steps to reproduce / Cause of the issue

1. Should Serbian partisans win.
2. Communists take power.
3. Germany invades.
4. Jonic's government is set.

### Expected behaviour

It should have some effects.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/b30ac6fb-4ff1-4c2c-90bc-04aeb895a3e1)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Marok132** [comment]
> Fixed in Dev Build.

Thank you!
