### ISSUE TITLE
SAF - No traits for a foreing minister.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3387]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The South African foreing minister does not have a trait.

### Steps to reproduce / Cause of the issue

To add some trait.

### Expected behaviour

He should have some trait.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/65997f3c-1708-46df-93b6-56088a01bb5e)

### Additional information

Many of foreing ministers don't have traits. Idk why.

**Comment by runelead00** [comment]
Stop reporting the same bug about foreign ministers he has a trait that is missing effects, fixed in dev build
