### ISSUE TITLE
ROM - all the natspirits use the name Romania and Romanian instead of Rumania and Rumanian (Also check the Additional information group)

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3388]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/58cf545c-1f6b-4c9d-b89d-b3793eef455c)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/314228f1-c5a5-4cd1-bb74-1bd5c7e16587)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/bd4f55d5-00ec-4dc7-8fa1-320a23e2516f)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/9be080fc-fa9c-4379-870c-1e02c8b14322)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/3bb24eb1-2d6a-4827-bc18-59bfe8dfb515)

### Additional information

There are plenty of states, events, gamerules use Romania instead of Rumania. I should say there should be unification for one name if Rumania is the only legal name for pronunciation and spelling this country.

**Comment by runelead00** [comment]
Non-Issue

**Comment by Marok132** [comment]
> Non-Issue

Why?
