### ISSUE TITLE
MLY - Post-war national spirits don't have descriptions

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3390]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the UMAJF victory, Malaya gets national spirits which do not have descs.

### Steps to reproduce / Cause of the issue

Should the UMAJF win in the Malayan uprising.

### Expected behaviour

The national spirits should have descs.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/93e58e3b-6af4-4dab-b389-4ec3edb23c1e)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/ba34d12e-327d-4df6-a0bb-3a4365e45453)

**Comment by runelead00** [comment]
Non-Issue, if something doesn't have a desc, it doesn't have a desc
