### ISSUE TITLE
SNI (maybe other Iraqi tags, too) - not getting cores on Iraq after the end of the civil war

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3393]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When SNI (or other Iraqi tags. I haven't checked it yet) wins in the Iraqi civil war, it does not get cores on Iraq.

### Steps to reproduce / Cause of the issue

To add cores in the IraqCW.9, IraqCW.11, IraqCW.12, and IraqCW.13 events for certain tags.

### Expected behaviour

Iraqi tags should have cores on the states after ending the civil war.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/12190ed1-6f2f-42ea-9322-009579a25c69)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
