### ISSUE TITLE
EGY - Has cores on Sudan after Sudan breakaways

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3394]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Kingdom of Egypt still has cores on Sudan despite it breakaways

### Steps to reproduce / Cause of the issue

Should the OC starts and Sudan is independent.

### Expected behaviour

I guess Egypt should lose cores on Sudan.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/42f14bd4-06f2-44a3-b9ed-efecbb99305d)

**Comment by runelead00** [comment]
Intended Design, Sudan literally broke away a year prior why would Egypt stop caring about the half of the country it just lost
