### ISSUE TITLE
typo in division names group

### ISSUE THREAD

**Issue by stocazz0o** [TNODevs/TNO-Bug-Tracker#3395]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### List the loc issues below

https://i.imgur.com/jt1olgk.png
Unit name group "Mountain Rifle Division" has the word mountain misspelled

**Comment by runelead00** [comment]
Fixed in Dev Build
