### ISSUE TITLE
HGR and GRO - Misspelled Oberkommando, Ultramilitarism ideology remnants

### ISSUE THREAD

**Issue by VoyteckGit** [TNODevs/TNO-Bug-Tracker#3397]
### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT, TOA

### List the loc issues below

- [x] 1. ![1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/127428612/27db270a-edba-444c-9700-1423379eaf21)
- [x] 2. ![2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/127428612/3f222cbe-da98-4354-b61c-769d56a5896c)
- [x] 3. ![3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/127428612/f85d04a0-14dd-4337-b488-a51e83844240)

**Comment by runelead00** [comment]
Fixed in Dev Build
