### ISSUE TITLE
INS - Suharto (probably other Indonesian leaders, too) loses his bio

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3398]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Suharto wins in the ICW, he does not get his post war bio despite there is one in the file (POLITICS_SUHARTO_POSTWAR_DESC).

### Steps to reproduce / Cause of the issue

Should Suharto take power in 1968 (use a gamerule Indonesian victor outcome).

### Expected behaviour

He should use his bio from the file.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/9a2d016c-de11-4f90-ad0f-b9ba81edb628)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/3bd8cfbb-07a2-4959-bd57-8cff1b664bc7)

**Comment by runelead00** [comment]
Fixed in Dev Build
