### ISSUE TITLE
Japan - Swapped options in a Dai Li event

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#340]
**Questions**

- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

```
japdlc.510.a:0 "Arrest them immediately!"
japdlc.510.b:0 "We need evidence of a crime taking place."
```
^ Above need to be swapped in `localisation\TNO_Japan_DLC_l_english.yml`

![image](https://user-images.githubusercontent.com/711467/143781613-8ca8a9c9-12f4-455f-a169-b1fc38553157.png)

**Comment by Stormeagle449** [comment]
Fixed in a previous build.
