### ISSUE TITLE
HOL - Incorrect Faction Idea after rejoining Speer's Einheitspakt

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3402]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Rochemont rejoins Speer's Germany, it has Mitstreiter despite his country name is Reichskommissariat Niederlande and it's supposed to have Integrated Reichskommissariat instead.

### Steps to reproduce / Cause of the issue

1. Speer wins in the GCW.
2. H. A. Sinclair de Rochemont should take power in the Netherlands and rejoin Speer's faction.

### Expected behaviour

Its country faction status should match with the country name.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/fb63c69d-d755-4fc9-9bcd-ec96fbefdba1)

**Comment by runelead00** [comment]
Fixed in Dev Build
