### ISSUE TITLE
JOR - No Party names for Paternalist and Conservative ones

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3403]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/3159e5a8-3ab5-4f2a-9ea9-d07c7ff2b0fa)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/21ae78bb-9572-4426-97b0-2e7d10ade9d8)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
