### ISSUE TITLE
ZLT - Post-unification issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3404]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Zlatoust unites West Siberia, it creates several puppet states. These ones have national spirits from previous regimes and I don't think it's supposed to because they don't match to the new regimes (a.k.a Five year plan in the Tyumen protectorat).

### Steps to reproduce / Cause of the issue

Should Zlatoust unites West Siberia.

### Expected behaviour

These puppet states should not have national spirits from the previous regimes.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/bf86d4e7-4873-4861-aacb-47e09c184d0a)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/e8b13f78-8dad-435e-a9a0-44e3256d84e0)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/0be0ef96-0dc1-48b9-91eb-cc97109d9adb)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/d431c02c-93c8-482c-8204-4ee641b728ed)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/1b5bb254-eefe-4dbf-9c6d-e66bc6c202ed)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/7a41218d-b474-41e6-86ea-c61af10c5520)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/cae20bcc-d7d5-43fb-8045-63955c55a506)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/aa0e0f3c-8080-42de-9362-83480cdf12c3)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/d32a5d6f-ef06-475f-b7a4-88750731dfdf)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/acd19ba9-c574-4f79-91c4-992ff82c8d8d)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/018a6f80-8e09-45cb-8d6e-f279a1507160)

**Comment by runelead00** [comment]
Fixed in Dev Build
