### ISSUE TITLE
CLC - Mariano Ospina Pérez uses an incorrect portrait

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3405]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Mariano Ospina Pérez takes power, he uses CLC_Alberto_Uribe_Sierra portarit instead of his own one.

### Steps to reproduce / Cause of the issue

New Granada wins and Mariano Ospina Pérez takes power.

### Expected behaviour

He should not use CLC_Alberto_Uribe_Sierra portrait for obvious reasons.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/075ab741-2818-4dd5-ac37-1d9520e18469)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/db868779-4fad-45bf-8488-b5ab49bf210c)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks.
