### ISSUE TITLE
MCW - Missing Paternalist Party Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3408]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

When Speer's Germany bring backs Moskowien, a paternalist party is the only one does not have a party name.

![image](https://github.com/user-attachments/assets/d20f826f-349b-496b-adc6-5326cf98e242)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
