### ISSUE TITLE
Regno D'Italia - Imperial Committe Scorza Loc

### ISSUE THREAD

**Issue by Chocotwo** [TNODevs/TNO-Bug-Tracker#3418]
### HOI4 version

1.14.7

### TNO version

v1.5.0d “The Ruin”

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/91c708f9-4d6a-465c-8d72-38e66cd6921e)

**Comment by runelead00** [comment]
Fixed in Dev Build
