### ISSUE TITLE
Regno D'Italia - Missing Scorza Loc

### ISSUE THREAD

**Issue by Chocotwo** [TNODevs/TNO-Bug-Tracker#3419]
### HOI4 version

1.14.7

### TNO version

v1.5.0d “The Ruin”

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/0d893e49-2148-4e20-bfbd-10ba6dfb2f57)

### Additional information

Appears after the focus "Towards a Common Currency?" with Scorza as the current leader

**Comment by runelead00** [comment]
Fixed in Dev Build
