### ISSUE TITLE
Japan (Takeda) - National Eugenics Law Reform never taken to Diet

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#342]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

This pertains to Takeda's 'Secure The Final Votes' focus. It looks like the preceding focuses are supposed to unlock it via event but that was never hooked up.

Specifically, it looks like `japtakagirecon.78` (The Moderate Law) and `japtakagirecon.86` (The Act On The Floor) should have `complete_national_focus = JAP_TakagiRecon_Secure_Final_Vote` added as a completion award (or something like that).

**Steps to Reproduce/Cause Issue:**

1. Be Takeda, take either branch of the Kokumin Yuseiho branch
2. Have ample popularity, party strength, etc
2. Take either 'A Conditional Acceptance' or 'The State And The Child' and wait for the event chains to run out
3. 'Secure The Final Votes' remains unavailable and the bill never goes to the Diet

**Screenshots:**
![image](https://user-images.githubusercontent.com/711467/143783341-08349dff-5e52-41e6-9806-312de0ca40dc.png)

**Comment by thashepherd** [comment]
![image](https://user-images.githubusercontent.com/711467/143783932-b9ba2705-6165-4b26-a622-34675f7daa4f.png)
^ Results when focus triggered using focus.nochecks when taking the left path

**Comment by runelead00** [comment]
Fixed in Dev Build
