### ISSUE TITLE
Jordan - Nation isn't in the Levantine Union

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#3421]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

Jordan isn't a member of the Levantine union after Italy partitions the Levant. I'm not sure if Shimon Peres becoming leader of Israel had anything to do with this

### Steps to reproduce / Cause of the issue

1. Set the game rules to where Italy wins the 2ITW, the Jerusalem Conference is successful and the Levant is partitioned
2. Wait

### Expected behaviour

Jordan should be in the Levantine Union with Israel, Palestine, Jerusalem, and Lebanon

### Screenshots

![image](https://github.com/user-attachments/assets/58818be7-654e-4a84-acbd-68f87398f0c5)

**Comment by runelead00** [comment]
Fixed in Dev Build
