### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3422]
### Operating System

Windows

### HOI4 version

the newest

### TNO version

the newest

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Bug collections:
1. Ronne's tag OKB ruling Sankt Petersburg during slavery riots use Russian toponymy instead of German. And OKB controlling states GDP will heavily decrease in while.
2.  RFI controlling states GDP will decrease to 0
3. South Georgia has no core of ENG, and I tried to add it in history-state files but nothing happened, then I find that is because this islands ID is miss in a event of event-Britain txt but others 3 islands have had, so add it to fix please.
4. when paraguay defeated, the 3 occupation tag controlling states' GDP will decrease to 0.
5. speer German controlling nordsten (in Norway), UK channels isles, reunion and mauritus (in Madagascar)'s personal GDP will heavily increase higher than many states in German home, I don't know is it a bug but I think its unreasonable.
6. RK Ukraine has no core in central states when Germany defeat Ukraine rebellion and rebuild RK.
7. When Yemen take back the port in civi war it still use italian name.
8. when Saudi Join ofn but is able to change the faction member statue to Sphere when still in OFN
9. when USA take back the port, hawaii and attu, they still use japanese names.
10. Canada GDP growth in decreasing at the beganing of the game i am not sure is it a bug.
Suggest:
When BRG was defeated, would you make every_state = remove_core_of = BRG, the tag and flag has cores make players feel unfit.

### Steps to reproduce / Cause of the issue

in game

### Expected behaviour

fix them please

**Comment by runelead00** [comment]
Don't report unrelated issues in a single massive block + half of these are duplicates of existing issues
