### ISSUE TITLE
USA - McCormack final event issue

### ISSUE THREAD

**Issue by Interesting2752** [TNODevs/TNO-Bug-Tracker#3424]
### HOI4 version

1.14.7.f4d3

### TNO version

1.5.0d

### Do you have other mods in use?

Radio TNO, TNO: Second West Russia War, Zizek's Ideology Bling, Fallout Music Reborn, Increased Volunteer Limit + Recall Volunteers (UPDATED)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT, TOA

### List the loc issues below

1. In "Crunching Numbers at Dusk" (McCormack's final event in the focus tree), there are mentions in the second paragraph of the event about odds for R-D Senators in Illinois and Louisiana. However, the Senate GUI shows that there are no Senate elections in Illinois and Louisiana in 1964. (I didn't get the picture for Louisiana because I am a dummy)
![20240722183122_1](https://github.com/user-attachments/assets/0fec0b27-8168-4180-83ff-989c3153ab51)
![20240722183127_1](https://github.com/user-attachments/assets/57167b95-7853-419c-898e-e0b043e24847)

**Comment by Fortune801** [comment]
Fixed, thank you
