### ISSUE TITLE
Dahomey - Chaotic Fronts spirit not removed after war

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#343]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

'Chaotic Fronts' is removed from other West African nations, but not Dahomey, after the war ends.

**Steps to Reproduce/Cause Issue:**

This game had a 3-way West African War. Free France died first, then the West African Federation beat Cameroon. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/711467/143784714-71865592-ffbc-4088-8d54-9909281e6cf4.png)

**Comment by ModdingAccount** [comment]
Fixed in dev build.
