### ISSUE TITLE
Japan - Hirohito nat spirit not appearing for Kaya

### ISSUE THREAD

**Issue by Nick74u** [TNODevs/TNO-Bug-Tracker#3432]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

1.5.0D

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Kaya Okinori, the technocratic PM for Japan, doesn't get the Hirohito nat spirit whenever he gets elected for some reason

### Steps to reproduce / Cause of the issue

Get Kaya elected as PM

### Expected behaviour

Kaya gets hirohito nat spirit

**Comment by runelead00** [comment]
Without game logs we can't address this issue
