### ISSUE TITLE
WRRF - Repeated "too" on "The New Economic Policy" focus

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#3433]
### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/678b65b3-32c0-4445-8036-98ea285b07cc)

![image](https://github.com/user-attachments/assets/a5e583ee-8269-49dd-8abe-b7a598a0e510)

In the focus "The New Economic Policy" towards the end the phrase "and so too will it be our policy too" decides to put the "too" at the start and end of the sentence.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
