### ISSUE TITLE
[Bug]: All countries

### ISSUE THREAD

**Issue by BopoHex** [TNODevs/TNO-Bug-Tracker#3435]
### Operating System

macOS Ventura

### HOI4 version

1.14.7

### TNO version

1.5.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The entire map is white apart from Egypt and African RK's and some other small countries. Germany is unplayable, is fully black and it doesn't even appear as anarchy. Country selection is also glitched out, all major countries are misplaced, America shows up twice, antarctic anarchy is one of the countries. Main menu is fine.

### Steps to reproduce / Cause of the issue

Just open the game with/without any other mods

### Expected behaviour

Map and country selection expected to be normal

### Screenshots

<img width="1440" alt="Screenshot 2024-07-30 at 13 57 15" src="https://github.com/user-attachments/assets/0c20b36b-1ab8-457d-855f-985a3df85281">
<img width="1440" alt="Screenshot 2024-07-30 at 13 57 24" src="https://github.com/user-attachments/assets/a37807fe-97fd-4a25-9c50-a051cf6bc509">

### Additional information

I tried this with and without 2WRW and some other music mods

**Comment by Marok132** [comment]
Try to reinstall TNO and update to 1.5.0d.

**Comment by runelead00** [comment]
Can't reproduce, only can recommend a fresh reinstall
