### ISSUE TITLE
Japan - Completed Dai Li investigation and the menu disappeared, months later get the Unannounced Army Maneuvers anyway

### ISSUE THREAD

**Issue by noelle71** [TNODevs/TNO-Bug-Tracker#344]
**Questions**

- Operating System: macOS 12.0.1
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0c
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosporus

**Longer Description of Issue:**
Bug has been experienced with both Takagi and Kaya's paths. The Dai Li investigation begins, it progresses mostly normally, aside from one event that doesn't seem to properly fill in the evidence it says you've gathered. This was bypassed with set_var, and the investigation was completed normally, removing the decisions and national spirit for it by the end of 1968.

**Steps to Reproduce/Cause Issue:**

1. Complete the Dai Li investigation, removing the decisions and national spirit
2. Wait around 10-12 months
3. Get the "Unannounced Army Maneuvers" event, starting the Tokyo standoff, implying it is because of the failure of the investigation.

**Screenshots:**
<img width="290" alt="Screen Shot 2021-11-28 at 4 08 46 PM" src="https://user-images.githubusercontent.com/44420082/143786037-96ac32b4-db24-4da9-8298-7e6fd91adcd6.png"> <img width="361" alt="Screen Shot 2021-11-28 at 3 31 27 PM" src="https://user-images.githubusercontent.com/44420082/143786042-66013329-0a57-4491-b63b-f612fee09b38.png"> 

The orange evidence that is not properly checked off

<img width="1440" alt="Screen Shot 2021-11-28 at 3 37 24 PM" src="https://user-images.githubusercontent.com/44420082/143786120-3b02ae96-b938-46b1-bca2-d0a3646b8f42.png">
The completed evidence and final event of the investigation which removes the national spirit and decisions.

<img width="1440" alt="Screen Shot 2021-11-28 at 4 05 14 PM" src="https://user-images.githubusercontent.com/44420082/143786141-de31266f-a136-473a-be57-794219fdc3a0.png">
10 months later, the event signalling the failure of the investigation.

**Comment by noelle71** [comment]
> I just ran into the orange evidence bug as well. What is the set_var command you used to bypass it?

I believe it was set_var JAP_Orange_Card 1

**Comment by Tarepa** [comment]
already fixed in v1.2.1
