### ISSUE TITLE
SNS - Party name not updated

### ISSUE THREAD

**Issue by M4nuun** [TNODevs/TNO-Bug-Tracker#3442]
### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT, TOA

### List the loc issues below

- SNS ruling party name stays in Turkish even after Scorza's peacedeal in 2ITW. Name should be changed to Italian or Arabic

**Comment by runelead00** [comment]
Fixed in Dev Build
