### ISSUE TITLE
Xinan Culture GFX Wrong Character

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3444]
### Operating System

newst

### HOI4 version

newst

### TNO version

newst

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

incorrect Culture picture for Xinan in China, the Chinese character in the culture picture is gui(桂) which means Guangxi Province only, you should change to xinan(西南). BTW I remember the picture was right in the long old version of TNO but lately it became wrong.

### Steps to reproduce / Cause of the issue

-

### Expected behaviour

to make the culture picture correct.

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
