### ISSUE TITLE
Culture Name Reset - Zhujin

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3445]
### HOI4 version

newst

### TNO version

newst

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Change the culture name from Zhujin to Zyujin. 

### Justifications

Zyu(珠 pronunced in Cantonese) + Jin(人 pronunced in Japanese). Zhu is from the pronunciation of Mandarin instead of Zyu from Cantonese.

**Comment by runelead00** [comment]
The name uses Mandarin because it was it was made by Japanese bureaucrats who didn't really care about Cantonese as explained in content,
we're also not renaming the thousands of references to it
