### ISSUE TITLE
Promote New Culture - Raeuz

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3446]
### HOI4 version

Newst

### TNO version

Newst

### Describe your suggestion

Raeuz, the major culture used in state Nanning (Guangxi), this culture is of modern Zhuang (name created by PRC). They were named Raeuz (in Chinese: 獠 Liao) during and before ROC period.

### Justifications

Yue is not the major culture in Nanning. you could simple describe the culture is Raeuz or add more details like : major culture in the state is Raeuz, with minor Cantonese-speaking Han ethnic group in urban area.

**Comment by Stormeagle449** [comment]
Cultural makeup of China has been completely overhauled for patch 1.7.0
