### ISSUE TITLE
Incorrect Culture Name - Hokkien

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3447]
### Operating System

newst

### HOI4 version

newst

### TNO version

newst

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Change the culture name from Hokkien to Min. It is right that the name Hokkien means Min, but the pronunciation is from South Min and is understood as South Min only, Min is more neutral name for all instead of Hokkien which only means part of Min. I remember its Min in long old version of TNO but lately became Hokkien

### Steps to reproduce / Cause of the issue

-

### Expected behaviour

Change culture name from Hokkien to Min.

**Comment by runelead00** [comment]
Fixed for map rework

**Comment by MacGeeham** [comment]
BTW, culture Sichuanese should be renamed as Shu (This is how the picture of Chinese character pronunoce, and will be more accurate to describe Chinese culture in TNO culture system. But actually Shu is definted as a subgroup of Xinan. So you can try to replace it by Xinan, or just change the name to Shu.)

**Comment by MacGeeham** [comment]
And, I still remember the major culture in Xinjiang's north state was Khazak in old version of TNO, that was correct but then was change to Xibei and I don't know why. According to history data Khazak was major in the north, but Soviet aroused the Khazak and Uyghur in the north to rebel and escape to Soviet from north Xinjiang after PRC and Soviet Union turned their relationship badly in the later 1950s to 1960s. After that, PRC gathered Han Chinese people from the whole nation to develop the territory deserted by the rebellion, that was when and how the major culture in north of Xinjiang turned to Xibei (a subgroup of Han).
