### ISSUE TITLE
Promote New Culture - Hainan

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3448]
### HOI4 version

newst

### TNO version

newst

### Describe your suggestion

Hainan (海南), the culture used in Hainan(kainan, core state of Guangdong and controlled by Japan). Culture description: major culture in the state is Hainan, contains Min varieties-speaking Han ethnic group in maritime area and Hlai people in central mountain area and hinterland.

### Justifications

to make it more correct

**Comment by Stormeagle449** [comment]
Rejected, for future updates to the map Hainan will have Min and Li cultures instead of one that represents only the island.
