### ISSUE TITLE
Change Culture Description - Ulster

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3449]
### HOI4 version

newst

### TNO version

newst

### Describe your suggestion

change the culture description from now to Ulster,  contains Irish, Ulster Scots and Anglo-Irish peoples.

### Justifications

I think the culture description should focus more on ethnic groups or identities instead religion. Base on like Flanders and Dutch share the same culture but they have different major religions and finnish.

**Comment by Stormeagle449** [comment]
Accepted.
