### ISSUE TITLE
National Protection Army/Chinese Cliques/Japan/The Rest Of Japan Sphere

### ISSUE THREAD

**Issue by NoThymeToulouse** [TNODevs/TNO-Bug-Tracker#345]
**Questions**

- Operating System: Windows 10 Home, Version 21H1, Build 19043.1348
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back, Battle of Bosporus, La Resistance, Death or Dishonor, Together For Victory

**Longer Description of Issue:**
During the national protection war AI Long Yun allies with several cliques and take Nanjing causing a rump Republic of China to form as normal. However as soon as he capitulates the rump RoC Long Yun immediately forms a peace with the entirety of the Co-Prosperity Sphere, but the cliques which were allied with him remain at war with the Sphere. This causes Japan to be marked as losing the Great Asian War and have a -700 score applied to it.

However, when any one of the remaining cliques still at war (I observed it happening with both the Guanxi Clique and the Shanxi Clique) are capitulated by the Co-Prosperity Sphere, it immediately marks Japan as having won the Great Asian War, as well as splinters the National Protection Army into multiple separate countries.

**Steps to Reproduce/Cause Issue:**

1. Unknown. I observed this happening twice while playing different countries (Modernist Tomsk and Bennett US), so it may be an AI issue.

**Screenshots:**
![image](https://user-images.githubusercontent.com/95224461/143869368-f97330de-aa11-4f10-92f3-7eda2b1f251c.png)
![image](https://user-images.githubusercontent.com/95224461/143869410-6853f732-4c9f-40fe-a0df-8ace7f32ef0a.png)

**Comment by tkgitno** [comment]
Fixed in Dev Build
