### ISSUE TITLE
Promote New Culture - Germanisch

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3450]
### HOI4 version

Newst

### TNO version

Newst

### Describe your suggestion

Germanisch (Germanic in English), the amalgamation of German, Dutch, Flemish, Nordic and minor Germanized Czechs and Walloons settlers who are settling in east occupation.

### Justifications

I saw some event that describes dutch settlers in Ukraine so I think of  this culture. It could be used in any state of east RK

**Comment by runelead00** [comment]
We already have cultures to represent Germanics settling in the east

**Comment by MacGeeham** [comment]
yeah I know, Ostdeutsch. But it doesn't represent people of all Germanic and only describe from Reichs

**Comment by runelead00** [comment]
the vast majority of people settling in the east are German, the amount that don't fall under and would not integrate with the general German settler community that is insignificant and are not worth showing

**Comment by MacGeeham** [comment]
OK.

**Comment by MacGeeham** [comment]
And BTW, would you guys plan to edit a culture to represent Japanese settlers in new occupation Pacific islands like "Kaidakudan" (開拓団, literally "settlers group") or something like that?
