### ISSUE TITLE
Culture description Change - Karelian

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3451]
### HOI4 version

Newst

### TNO version

Newst

### Describe your suggestion

Karelian (Karjalaiset in Finnish), the native Finnic-speaking Karelian live together with new residents of Finns and resettlers of Ingrian Finns and Estonian who have replaced ethnic Russian.

### Justifications

Finland have received Ingrian refugees from the persecution of soviet and have plan to receive the refugees from Estonia after Reich establish RK Ostland. I think Finland will place them in Karelia to replace Russian.

**Comment by runelead00** [comment]
Plans to rework Finland culture maps are planned in the near future, likely with future map rework, although i don't believe Estonians are a significant enough minority to be represented nor would Finland use them to colonize land they want for Finns
