### ISSUE TITLE
state name change - Thrace

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3454]
### Operating System

Newst

### HOI4 version

Newst

### TNO version

Newst

### Do you have other mods in use?

Newst

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Thrace has no dynamic names, it won't change during the border conflict between Greece and Turkey. It keeps the same name all the time no matter who controlls them (in Turkish or Greek and I don't know but they don't seem like English to show the neutral). BTW, Dodecanese is the same if control by Turkey during the Italian-Turkey border conflict.

### Steps to reproduce / Cause of the issue

-

### Expected behaviour

give those states dynamic names in Greek Romanization and Turkish, or use English all the time to be neutral

**Comment by ModdingAccount** [comment]
Resolved
