### ISSUE TITLE
All States Cores

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3455]
### HOI4 version

Newst

### TNO version

Newst

### Describe your suggestion

I suggest you guys should pay more attention to states cores, which should represent native people's attitude to the regimes. Like cleaning the cores of no exist country but exclude some Tags that represent native resistance. For example cleaning GGN's cores after Poland defeats GGN (who will miss a colonial government to adminitrate themselves and have no resistance) and you could readd GGN's cores after Bormann re-established GGN. And clean GGN, UKR, MCW and OST cores after Bormann or Speer Germany integrate RK (why the Tags that representing colonial governments would resist home's rule?). Same with BRG, IME, Italian East Africa, GRO's collapse, UAE after Italian Gulf recreat UEA (UAE has another UAE cores it seems like hilarious, same with ILG and ALG), Reunion and Mauritius with Paktkomission MAD's cores under German administration. And Ostland civil war end (UPO and BLR representing native resistances is OK, but MST,  JST and DST have no the most of native people to represent, same with after Speer and Bormann re-establish MCW). Seems like cores are so exclusively used in TNO.

### Justifications

As I mentioned above. I know it will be a huge work and I am not sure would you guys will do it but it is just from my opinion that state cores should not be used too excessive.

**Comment by runelead00** [comment]
We're not going to be done this because it is a lot of work for very little gain and would only serve to annoy the player, especially since the ai is terrible with managing resistance
