### ISSUE TITLE
Establish Countries Post-Burgandy

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3456]
### HOI4 version

Newst

### TNO version

Newst

### Describe your suggestion

Just a small imagination to fill the content, it depends on you guys. Germany can hold 2 referendums in Walloonia and Flanders (if GER doesn't annex them), they could decide like join France(or Netherlands), independence or re establish Belgium. Germany, France, Netherlands are able to intervene the referendums by decisions. But I saw leak that Himmler will come back Reich in further version. I don't know if Burgandy still exists but the referendums can still be held in RK Belgium-North France. Like if Walloonia decides independence, it can choose De-Frenchized and make Walloon Language and culture rebirth because they regard France as the loser of WW2 or something like that bla bla etc.

### Justifications

fill the content.

**Comment by runelead00** [comment]
We're not doing and neither would the Nazis

**Comment by MacGeeham** [comment]
Actually, all I said is based on Reich choose not to annex them. Because I think its more economy extractable for nazi to establish puppet states here compared with handing them to Netherlands and France who have been Pakt members. But all of that depend on you, just a idea from me.
