### ISSUE TITLE
please fill more content of Serbian Banat

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3457]
### HOI4 version

Newst

### TNO version

Newst

### Describe your suggestion

Serbian Banat German enjoy a significant political priority and Reich in the history have planed to rebuild the place with significant German elements, event Serbian collaboration Government is not able to administrate there. I think this state should use German name, and native German militia will keep neutral until Reich come back instead of supporting the Collaboration Government. The native people should prefer to be intergrated into Reich Home or separate from Serbia and establish a native German dominating autonomy.  And even Germany will not invade non-communism Serbia but I think they wouldn't accept such a place with so many ethnic German controlled by a enemy (or non-pakt) country, they will try to take this place back(or native militia uprising to unify with Reich ). I think Germany shouldn't lost this place in any route, just like Germany wouldn't lose RK no matter who are fuhrer based on the game rule setting.

### Justifications

As what I said above.

**Comment by runelead00** [comment]
We're not changing our skeleton for Serbia again

**Comment by MacGeeham** [comment]
OK, But I still hope you would still sell this ideas to mod team. Because it seems like more realist after I read nazis history plan in Serbian Banat, they seemed like would keep and develop this place in any case.

**Comment by runelead00** [comment]
We already messed around with Germans in Serbia in previous skeleton and discard it because it wasn't the direction Serbia team wanted to take the content
