### ISSUE TITLE
victory point in Hainan

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3458]
### Operating System

Newst

### HOI4 version

Newst

### TNO version

Newst

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

incorrect victory point in Hainan(Kainan, core of Guangdong and controlled by Japan), Sanya (San'a in Japanese) was named by PRC in 1980s. Before that it was called Yaxian(Gaiken in Japanese).

### Steps to reproduce / Cause of the issue

-

### Expected behaviour

please restore the historic name.

**Comment by runelead00** [comment]
Fixed for map rework
