### ISSUE TITLE
Capital of Guangxi

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3459]
### Operating System

Newest

### HOI4 version

Newest

### TNO version

Newest

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

the Capital of Guangxi Should be in Guilin instead of Nanning. Capital was move to Nanning was when PRC established and they planed to balance the political power of New Guangxi Clique to ethnic minorities- dominating city Nanning, because Guilin is the home of NGC who insists a strong sentiment of anti-CCP

### Steps to reproduce / Cause of the issue

-

### Expected behaviour

restore the Capital of Guangxi based on history

**Comment by runelead00** [comment]
Fixed for map rework
