### ISSUE TITLE
Japna - incorrect victory point

### ISSUE THREAD

**Issue by yangjin000** [TNODevs/TNO-Bug-Tracker#346]
Hokkai(state) -
 Japanese Occupied state of Guangdong includes a incorrect victory point(city) "sūsa" which is a part of Guangxi province, not Guangdong. This place should be named Fangcheng(in Mandarin, is named Fangchenggang Today now) at that time, and Sūsa(Mandarin name: Chongzuo is administrated by Guangxi) is the city near by Fangcheng and is not coastal.

**Comment by tkgitno** [comment]
Fixed in Dev Build
