### ISSUE TITLE
DOM - Keep a claim on Hinche after the defeat

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3460]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Haiti defeats socialists and takes Hinche, the Dominican Republic still has a claim on it.

### Steps to reproduce / Cause of the issue

Use the gamerules in screenshot to reproduce it.

### Expected behaviour

The Dominican Republic should not have a claim on Hinche after the defeat.

### Screenshots

![image](https://github.com/user-attachments/assets/238421a0-5da1-4c10-918d-0205242208b2)
![image](https://github.com/user-attachments/assets/77e00f53-1307-402f-be9b-e78e6edf0253)
![image](https://github.com/user-attachments/assets/0bea04a9-04bc-4c78-9cf9-92c4b634ddf7)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thank you.
