### ISSUE TITLE
Scotland Shetland's culture

### ISSUE THREAD

**Issue by MacGeeham** [TNODevs/TNO-Bug-Tracker#3461]
### Operating System

Newest

### HOI4 version

Newest

### TNO version

Newest

### Do you have other mods in use?

Ni

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Highlander means Geals areas in Gaelic language but actually the major language spoken in Shetland is Scots(Lowland Scots) instead of Gaelic, so is it more accurate the change the culture from Highlander to Lowlander in Shetland state?

### Steps to reproduce / Cause of the issue

-

### Expected behaviour

change the culture in the state.

**Comment by runelead00** [comment]
That's not what Highlander means in the Scottish context unless you want to get really granular Shetlanders are 1000% "Highlanders"  - from a Britain dev
