### ISSUE TITLE
DOM - Missing party name for García Godoy being elected president of the DR

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#3462]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[game.log](https://github.com/user-attachments/files/16534554/game.log)
[error.log](https://github.com/user-attachments/files/16534555/error.log)

### Describe the bug

García Godoy is missing his party name.

### Steps to reproduce / Cause of the issue

1. Have Trujillo expel Puerto Plata.
2. Trujillo assassinated.
3. Emergency junta takes over from Ramfis.
4. Godoy elected president.

### Expected behaviour

Shows party name.

### Screenshots

![image](https://github.com/user-attachments/assets/46b405b0-f934-4507-a4fa-c1f986b25a65)

### Additional information

The missing localization for the event is said to have been fixed by a team member. This only left the party name to be fixed.

**Comment by runelead00** [comment]
Fixed in Dev Build
