### ISSUE TITLE
IRE - Missing adjective in "opinion of" section for despotic Ireland.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3463]
### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/bd75ca01-2392-4eed-88d9-452fecdddf49)
![image](https://github.com/user-attachments/assets/5d21fc54-b5e8-410f-bb0a-925a87b2e66a)

**Comment by Stormeagle449** [comment]
Fixed for 1.6.0 release.

**Comment by Marok132** [comment]
> Fixed for 1.6.0 release.

Thank you.
