### ISSUE TITLE
ITA - No Icon for the Natspirit "Freefall in Popularity"

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3464]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title said everything.

### Steps to reproduce / Cause of the issue

Should neofascists take power in Italy.

### Expected behaviour

The national spirits should have an icon.

### Screenshots

![image](https://github.com/user-attachments/assets/c342f9cb-2eaf-4dc0-a23c-4dfc0ea6a699)

**Comment by Stormeagle449** [comment]
Fixed for 1.6.0 release.
