### ISSUE TITLE
UPH - Missing Effects For the "Cacique Democracy" Natspirit

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3465]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title said everything.

### Steps to reproduce / Cause of the issue

To start to play.

### Expected behaviour

The national spirits should have effects.

### Screenshots

![image](https://github.com/user-attachments/assets/3e0e4b19-7fa9-4bd2-a18f-3fbdf8e4a6a5)

**Comment by Stormeagle449** [comment]
Fixed for 1.6.0 release.
