### ISSUE TITLE
All Countries - GUI Issue crashing the game

### ISSUE THREAD

**Issue by SomeGermanOnline** [TNODevs/TNO-Bug-Tracker#3468]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/user-attachments/files/16553402/error.log)

### Describe the crash

Crash is sudden and without player input as it's caused by a UI error

### Steps to reproduce / Cause of the crash

I got no clue

**Comment by runelead00** [comment]
Fixed for next update
