### ISSUE TITLE
HOL - Rochemont's Netherlands does not join the German Economic Sphere

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3469]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Rochemont takes power in the Netherlands and backs to Speer's Germany, it doesn't join a German economic sphere.

### Steps to reproduce / Cause of the issue

1. Rochemont takes power in the Netherlands.
2. Speer wins in Germany.
3. The Netherlands return to Pakt.

### Expected behaviour

The Netherlands should join a German Economic Sphere.

### Screenshots

![image](https://github.com/user-attachments/assets/c4dce499-4176-47a1-aee7-c4772954f112)

**Comment by runelead00** [comment]
Can't reproduce and without logs we will not be investigating
