### ISSUE TITLE
Schmidt Slave Revolt Negotiations - Minor typo

### ISSUE THREAD

**Issue by intzequals0** [TNODevs/TNO-Bug-Tracker#347]
**Questions**

- HOI4 Version: Most recent
- TNO Version: most recent
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [ ] 1.  "with our without eyes" should be "with or without eyes" when Schmidt meets Brandt
(Screenshot here)
- [ ] 2. 
(Screenshot here)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting.
