### ISSUE TITLE
SAM - Broken leader and focus tree

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3471]
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Samara unites West Russia, a leader is not changed (Disorganized Cliques are still in charge after the Karelian war).  Also its focus tree is broken (check the screenshot below).

### Steps to reproduce / Cause of the issue

Samara unites West Russia.

### Expected behaviour

It should work right.

### Screenshots

![image](https://github.com/user-attachments/assets/82909b59-e54a-4400-9f72-8ef452e1f560)
![image](https://github.com/user-attachments/assets/e9f61989-0a52-42f8-a168-b0db3b748ed5)

**Comment by runelead00** [comment]
Without proper logs, we're not considering issues this near to an update
