### ISSUE TITLE
MEX - Zacatecas Typo

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#3473]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### List the loc issues below

![image](https://github.com/user-attachments/assets/df618401-6a40-4a41-9fdf-6098ae4ce0d7)

### Additional information

horrifying

**Comment by runelead00** [comment]
Fixed in Dev Build
