### ISSUE TITLE
Samara - Missing loc on focus

### ISSUE THREAD

**Issue by maxrightgame** [TNODevs/TNO-Bug-Tracker#348]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0.d
- Any other mods in use: none
- Were you using Steam? : Yes
- Which expansions do you NOT have? : All DLC 

**Longer Description of Issue:** Samara focus "Saborage their tanks" have Gorky modifier with missing loc 

**Steps to Reproduce/Cause Issue:** pick Zykov as Samara leader

**Screenshots:**
![image](https://user-images.githubusercontent.com/18327176/143899868-f917da59-6bfc-48aa-a290-cf551fe8c049.png)

**Comment by runelead00** [comment]
Changed in UB
