### ISSUE TITLE
GER - Cabal doesn't show if SAW ended before GCW and Huttig annexed the others as well

### ISSUE THREAD

**Issue by cheeems02** [TNODevs/TNO-Bug-Tracker#3480]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

v1.6.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

As the title says. If the South African war (somehow) ends in total Schild victory and Huttig eats the other reichkommissariats before the end of German civil war, when the war is over you don't get any way to influence Cabal at all, to get the German remnants in the Pakt

### Steps to reproduce / Cause of the issue

1. Play as Germany, Speer or Bormann
2. Stall German civil war enough for schild to win without your help and Huttig to eat other reichkommissariats
3. No matter how long you play you won't get event for Cabal

### Expected behaviour

You should get event for Cabal

**Comment by runelead00** [comment]
Working as Designed, if Germany doesn't or can't invest support into Africa, a network of loyalists within Huttig's government cannot form
