### ISSUE TITLE
USA - "inveshtigation" typo in the 'Hail Mary' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3481]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. There is a typo word "inveshtigation" in the 'Hail Mary' event, and this word should be "investigation". 
![Image_1](https://github.com/user-attachments/assets/4e4a4b59-07df-474c-9d4d-0a8cb1904dfa)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by runelead00** [comment]
Update: Working as Designed, reverted previous fix
