### ISSUE TITLE
MEX - AI doesn't select some of the PPI proxy war decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3483]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[MEX.zip](https://github.com/user-attachments/files/16573714/MEX.zip)

### Describe the bug

When the PPI triggered. AI MEX doesn't select some of the PPI decisions and even doesn't select any of the PPI Operational decisions despite MEX has plenty of political powers. 

### Steps to reproduce / Cause of the issue

1. The Puerto Plata Invasion proxy war starts.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/55df55ee-0e3c-4b4d-b9b0-762357ed896e)

![Image_2](https://github.com/user-attachments/assets/fdba1f44-fe4d-4eb4-9b4b-89d2456b160b)

**Comment by Fortune801** [comment]
Fixed on Dev, thank you for reporting
