### ISSUE TITLE
SAO - A Country Name Issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3484]
### HOI4 version

1.14.6

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The offical TNO wiki mentions the "Democratic Republic of São Tomé and Príncipe" name is a offical long country name for São Tomé. In game, however, its long country name is the Republic of São Tomé. I guess the long name from game should be the same in wiki as well.
![image](https://github.com/user-attachments/assets/f797304e-196d-454f-9a75-30cad9023349)
![image](https://github.com/user-attachments/assets/ba79be49-7f0a-409f-bf98-c2fbe0d92c55)

**Comment by runelead00** [comment]
Wiki Issue
