### ISSUE TITLE
The Carribean Countries are coloured white instead of normal colours

### ISSUE THREAD

**Issue by martman911** [TNODevs/TNO-Bug-Tracker#3486]
### Operating System

Windows 11

### HOI4 version

the latest

### TNO version

So Far From God

### Do you have other mods in use?

FPS Map

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Describe the bug

The Carribean Countries are coloured white instead of normal colours

### Steps to reproduce / Cause of the issue

Change back the colours

### Expected behaviour

colours normal colours

**Comment by runelead00** [comment]
All i can recommend is an reinstall of the mod and double check to make sure you're not using any outdated submod, can't reproduce on dev or public builds
