### ISSUE TITLE
USA - "Pashific" typo in the 'Hail Mary' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3487]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. There is a typo word "Pashific" in the 'Hail Mary' event, and this word should be "Pacific".
![Image_1](https://github.com/user-attachments/assets/7f8207ff-a093-4acf-b8c9-5d11aa2503e0)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by runelead00** [comment]
Update: Working as Designed, reverted previous fix
