### ISSUE TITLE
Mexico - CDMX Metro Blocked for Lozano

### ISSUE THREAD

**Issue by BigComp** [TNODevs/TNO-Bug-Tracker#3490]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

The CDMX Metro Megaproject in the Mexican Miracle GUI is blocked because the mayor Uruchurtu doesn't want to build it. Lozano gets an event where he appoints Uruchurtu to be his infrastructure minister, upon which Uruchurtu will no longer be able to block the Metro construction. The event tells the player that when Lozano becomes president, the Metro will become available to build. When Lozano becomes president, however, the Metro is still blocked and the game says that Uruchurtu has not been dealt with.

### Steps to reproduce / Cause of the issue

1. Play Mexico
2. Select Lozano as the successor
3. Get the event about Uruchurtu
4. Get Lozano's tree

### Expected behaviour

The CDMX Metro Megaproject should be available

**Comment by runelead00** [comment]
Fixed in Dev Build
