### ISSUE TITLE
CUB - Doesn't join the OFN faction after the Quisqueya Agreement

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3491]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/user-attachments/files/16599137/Logs.zip)
[USA_play.zip](https://github.com/user-attachments/files/16599291/USA_play.zip)

### Describe the bug

After the Quisqueya Agreement between two anti-fascist Dominican factions, Cuba doesn't join the OFN faction despite the Quisqueya Agreement world news event says. Because, if USA continues to side with the revolutionaries and Dominican revolutionaries wins and the Dominican Civil War, Cuba can join the OFN faction. 

### Steps to reproduce / Cause of the issue

1. PPI started and landed in the Dominican Republic.
2. Trujillo's overthrown and assassinated by Pupo Roman during the PPI.
3. Ceasefire between revolutionaries and Pupo Roman's government.
4. Negotiation successful without the Dominican Civil War.
5. The Quisqueya Agreement. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/0a66f769-35a1-409a-9db0-bb22e7a47910)

![Image_2](https://github.com/user-attachments/assets/65e26127-d503-427b-a86c-664e52a58e6e)

**Comment by Fortune801** [comment]
WAD, thank you for reporting
