### ISSUE TITLE
MEX - CDMX Metro not unlocking

### ISSUE THREAD

**Issue by Wextra** [TNODevs/TNO-Bug-Tracker#3493]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[OrdazDone.zip](https://github.com/user-attachments/files/16602175/OrdazDone.zip) (save game)
[game.log](https://github.com/user-attachments/files/16602177/game.log)
[error.log](https://github.com/user-attachments/files/16602176/error.log)

### Describe the bug

Uruchurtu seems to be very firm in his opposition to the Mexico City Metro. So much that even after he has been removed, it is still not possible to build the metro. 

### Steps to reproduce / Cause of the issue

1. Play normally as Gustavo Díaz Ordaz OR execute event MEX_Ordaz.87
2. Expect Uruchurtu to be dealt with, allowing the Metro to be built
3. Nothing happens

### Expected behaviour

It is expected that after firing event MEX_Ordaz.87, the Mexico City Metro project will be unlocked.

### Additional information

Can not find effect MEX_ordaz_metro_projects_unlocked_tt when executing command 'effect MEX_ordaz_metro_projects_unlocked_tt'. Don't know if this is intended or not.

**Comment by runelead00** [comment]
#3490 Duplicate issue, fixed in dev build
