### ISSUE TITLE
HAI - Missing leader

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#3494]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/user-attachments/files/16604817/error.log)
[game.log](https://github.com/user-attachments/files/16604819/game.log)
[tno.zip](https://github.com/user-attachments/files/16604822/tno.zip)

### Describe the bug

Absent leader for communist Haiti. This occurred some time after the Amazonist guy was in power.

### Steps to reproduce / Cause of the issue

1. Communists win Haitian Civil War.
2. Amazonists take power.
3. Wait until Amazonist leader goes away.

### Expected behaviour

Leader shows up in country box.

### Screenshots

![image](https://github.com/user-attachments/assets/32e6fc33-c93f-48e1-84d1-c4a533b0b7b2)

**Comment by runelead00** [comment]
Fixed in Dev Build, skeleton event for Hudicourt was firing when the Amazonist came to power
