### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Luris2003** [TNODevs/TNO-Bug-Tracker#350]
**Questions**

- Operating System: Intel core I5 9th gen
- HOI4 Version: 1.10.8
- TNO Version: TT
- Any other mods in use: none
- Were you using Steam? yes
- Which expansions do you NOT have? No step back

**Longer Description of Issue:** the credit rating isnt improving even if i fullfill the requirements as the Uk doing a Margaret Tatcher run it got stuck in "poor"

**Steps to Reproduce/Cause Issue:**

1. nothing really happened outside of the usual 

2.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/95248850/143931902-0881d528-c833-4725-84a4-b9c95e803ee4.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
