### ISSUE TITLE
MEX/ENG - Negative opinions toward each other still exist after Free Britain won the BCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3503]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[MEX.zip](https://github.com/user-attachments/files/16637406/MEX.zip)

### Describe the bug

After Free Britain wins the British Civil War, Free Britain(ENG) and MEX are still negative with each other. 

MEX's 'Illegitimate Government' negative opinion of ENG and ENG's 'Refused to Recognize Us' negative opinion of MEX are should be removed when Free Britain won the BCW.

However, if German reconquers Britain and reinstalled pro-German puppet regime in Britain, MEX's 'Illegitimate Government' negative opinion of ENG and ENG's 'Refused to Recognize Us' negative opinion of MEX should trigger again. 

### Steps to reproduce / Cause of the issue

1. British Civil War triggered.
2. HMMLR(Free Britain) won the Civil War.
3. FGB switch to ENG.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/7f544c34-7256-464d-b6de-9d6e9d1c18d9)

![Image_2](https://github.com/user-attachments/assets/bc042bc9-9177-4b8e-91d6-75fdfa70c1b2)

**Comment by runelead00** [comment]
Fixed in Dev Build
