### ISSUE TITLE
General - Communism has strange alts

### ISSUE THREAD

**Issue by VoyteckGit** [TNODevs/TNO-Bug-Tracker#3505]
### Operating System

Fedora 40

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT, TOA

### Describe the bug

Ideology alts are displayed next to the main ideology on **both sides** of the pie chart. Oddly enough, all communist alts are above the main ideology. This is slightly annoying when making a submod.

### Steps to reproduce / Cause of the issue

None, no countries in the public build use more than two communist alts

### Expected behaviour

communist_3 and communist_4 should be below communist

### Screenshots

NatSoc alts
![image](https://github.com/user-attachments/assets/6ea54cf2-cea8-4adb-ab87-795f7fe8f5e5)

Communist alts
![image](https://github.com/user-attachments/assets/031ef67b-5b3c-4b75-89ab-0c60c4ff7e73)

**Comment by runelead00** [comment]
Working as Designed, due to bug with base game hoi4, last ideology list will sometimes appear with 0% pop on wheel and base communist ideology is the only one with loc + set leader in 99% of cases
