### ISSUE TITLE
URL/ORE - Southern Ural United Defense League faction icon uses the generic faction icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3507]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[ORE.zip](https://github.com/user-attachments/files/16642941/ORE.zip)

### Describe the GFX issue

The Southern Ural United Defense League faction icon uses the generic faction icon instead of using the unique Southern Ural United Defense League faction icon.

### Steps to reproduce / Cause of the issue

1. Southern Ural United Defense League faction formed.
2. See the faction icon of the Southern Ural United Defense League. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/ecc319f4-8972-46a8-add5-3fa1489241c8)

**Comment by runelead00** [comment]
Fixed in Dev  Build
