### ISSUE TITLE
USA - Slight effect loc issue in the 'Robert F. Kennedy, Cat Herder' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3508]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. In the 'Robert F. Kennedy, Cat Herder' (after taking 'Across the Aisle' focus) event effect, it says 'Some of our southern senators might defect to the **Democrats**' instead of **Republicans** because the Republicans have more conservatives.  
![Image_1](https://github.com/user-attachments/assets/9fcea210-fd79-4e32-84f6-6b90ad52aac5)

**Comment by runelead00** [comment]
Fixed in Dev Build, effect now favors Democrats
