### ISSUE TITLE
JAP - Lose the Indonesian War event has no negative effects

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3510]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[JAP.zip](https://github.com/user-attachments/files/16643886/JAP.zip)

### Describe the bug

After the Japan lost the Indonesian War, the 'Strategic Redeployment' event has no negative effects. 

### Steps to reproduce / Cause of the issue

1. Indonesian Civil War triggered.
2. Front Indonesia Merdeka won the ICW.
3. Japan lost the Indonesian War. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/8a06ff60-9d20-45c3-8a9c-612bf68ae653)

**Comment by Fortune801** [comment]
Addressed, thank you
