### ISSUE TITLE
USA - Slight issue loc of Radical Civil Rights Legislation national spirit

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3511]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [ ] 1. The last paragraph of the Radical Civil Rights Legislation national spirit descriptions says "some **Democrats**". It should be "some Republicans" instead.
![Image_1](https://github.com/user-attachments/assets/e9c9ca27-c69a-49da-851a-d37075ae243a)

**Comment by runelead00** [comment]
Working as Designed
