### ISSUE TITLE
Any tag - CtD when I click the economic sphere map mode

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3512]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[hoi4_20240817_201042.zip](https://github.com/user-attachments/files/16645697/hoi4_20240817_201042.zip)
[Error.zip](https://github.com/user-attachments/files/16645698/Error.zip)

### Describe the crash

When I sometimes click a economic sphere map mode, my game crashes. It is not connected to a save because it happens randomy in both random time and versions. I have been noticing this crash since TT3 is released.  It happens in almost each my playthrough but only one time. After it does not crash. and my save is not corrupted.

### Steps to reproduce / Cause of the crash

IDK.

**Comment by Fortune801** [comment]
Have you tried uninstalling and then resubscribing to the mod? Your files may have been corrupted during the update

**Comment by Marok132** [comment]
> Have you tried uninstalling and then resubscribing to the mod? Your files may have been corrupted during the update

As I said, it wasn't related to certain updates. Also it rarely happens (only one time in each playthrough, and not always).
