### ISSUE TITLE
USA - Aftermath of South Africa War events' show double 'The focus tree will change...'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3514]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/user-attachments/files/16648059/Logs.zip)
[USA_saw_end.zip](https://github.com/user-attachments/files/16648075/USA_saw_end.zip)

### Describe the bug

When the South Africa War ended, the two aftermath of South Africa War events' show the double 'The focus tree will change...'

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggered.
3. South Africa War ended.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/356ac0e9-4182-49db-a684-8deea1558d7d)

**Comment by runelead00** [comment]
Fixed in Dev Build
