### ISSUE TITLE
Foreign Policy Tab Breaks For me around 1972

### ISSUE THREAD

**Issue by ToastyBob** [TNODevs/TNO-Bug-Tracker#3516]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

v1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/user-attachments/files/16648924/game.log)

[error.log](https://github.com/user-attachments/files/16648925/error.log)

### Describe the bug

This is my second RFK run where this has happened. With mods and now without and to my shock it happened again. I have no idea what's causing this. It worked the night before I saved and got off woke up the next day to play and its broken! Loading all the previous saves and it now does the same for all of them. If i start a new game its fixed. I have also reinstalled the TNO mod and no result. I have the ability to fix anything in the save file but i don't know what to look for as I've tried searching economic measures, tactic_breakthrough_preferred_weight_factor and found nothing in the save information. Looking online I seem to be the only one that has this reoccurring issue. I'm about to use second PC thats perpetually on the game and offline so i don't lose my progress. Please help if you can it will be much appreciated.

### Steps to reproduce / Cause of the issue

View Foreign Policy tab and its blank and says nonsense for tab names. It also had two notification boxes on main map screen.

### Expected behaviour

Up to 1972 the Foreign Policy Tab/intelligence tab was working. Was able to do operations in Iran and give aid to Siberian federation

### Screenshots

![20240817095445_1](https://github.com/user-attachments/assets/80a454c9-31dd-43d3-90b9-c0060757d647)
![20240817095434_1](https://github.com/user-attachments/assets/5a1e3c0b-7c08-4190-b462-32bf8e5818c4)
![20240817095504_1](https://github.com/user-attachments/assets/c96100ea-c30d-40c5-9e02-83354a2e075c)

**Comment by runelead00** [comment]
You may need to do a proper clean reinstall (KR's guide: https://kaiserreich.fandom.com/wiki/How_to_do_a_Clean_Install), there are errors present in your files that should not exist in base TNO (like portraits errors for TDF which were removed and do not appear in fully functional versions of current TNO).

**Comment by ToastyBob** [comment]
> You may need to do a proper clean reinstall (KR's guide: https://kaiserreich.fandom.com/wiki/How_to_do_a_Clean_Install), there are errors present in your files that should not exist in base TNO (like portraits errors for TDF which were removed and do not appear in fully functional versions of current TNO).
Hello thanks for looking into this. I have done a complete reinstall of the game and mod. But im still getting the issue.
Does it have something to do with this below? But i went and deleted everything but the save file itself.
![image](https://github.com/user-attachments/assets/e8488ef9-6499-4e87-b46e-c6fcd5f64fae)

[error.log](https://github.com/user-attachments/files/16691140/error.log)

**Comment by Stormeagle449** [comment]
> Hello thanks for looking into this. I have done a complete reinstall of the game and mod. But im still getting the issue.
> Does it have something to do with this below? But i went and deleted everything but the save file itself.

You also need to start a new game, whatever save you made before the clean reinstall is also broken.
