### ISSUE TITLE
ITA - No GFX for the "No Trooper like the Paratrooper" focus

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3526]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title is already said.

### Steps to reproduce / Cause of the issue

To make Italy democratized.

### Expected behaviour

The focus should have its GFX.

### Screenshots

![image](https://github.com/user-attachments/assets/de9cce7f-9d82-4980-810e-d606a69f5c7b)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks.
