### ISSUE TITLE
CHL - Skeleton content doesn't seem to be working

### ISSUE THREAD

**Issue by JoshuaFromVietnam** [TNODevs/TNO-Bug-Tracker#3527]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Skeleton for Chile does not seem to happen in the latest update. I have the custom country paths set up for Allende to get elected, but instead Alessandri stays in power in Chile until the end of the game.

### Steps to reproduce / Cause of the issue

1. Set up the custom country paths as follows
2. Chile - Alessandri's Term: Alessandri Resigns
3. Chile - Philippi's Term: The Crisis Intensifies
4. Chile - The October Crisis: Allende Elected
5. Chile - Viaux's Coup: Coup Fails
6. Let game run until end

### Expected behaviour

Chile's skeleton content should occur with Alessandri resigning to Philippi, and then Allende taking over. Instead

**Comment by Marok132** [comment]
Does it happen in every game?

**Comment by JoshuaFromVietnam** [comment]
Yes I have played 3 test games observing as the Vatican, and this occurred every time.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by DuceMewtwo** [comment]
They haven't fixed it yet

**Comment by Marok132** [comment]
> They haven't fixed it yet

They said they fixed it in DEV BUILD, not the public one.
