### ISSUE TITLE
Healthcare Law Listed Effects Not Matching Actual Effects

### ISSUE THREAD

**Issue by Balkanoid** [TNODevs/TNO-Bug-Tracker#3528]
### Operating System

windows 10

### HOI4 version

1.14.7

### TNO version

v1.6.0 

### Do you have other mods in use?

second west russian war

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[VYT_1965_06_20_02.zip](https://github.com/user-attachments/files/16673232/VYT_1965_06_20_02.zip)

### Describe the bug

The healthcare policy is bugged. The bug is also present in vanilla tno.
The different types of stances on the policy have the same described effect for total coverage and universal and besides that the current policy (emergency support) does not have the emergency support effect.

### Steps to reproduce / Cause of the issue

1.open the game
2.load in a nation
3.click healthcare policy
4.see the differences between stated policy and effect

### Expected behaviour

The healthcare policy matching the effects of it

### Screenshots

![image](https://github.com/user-attachments/assets/6c2845fd-0ec4-41d7-8703-617b0ea440c3)

**Comment by runelead00** [comment]
Fixed in Dev Build
