### ISSUE TITLE
USA - National Ethics Committee national spirit has no unique GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3531]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/user-attachments/files/16675349/USA_game.zip)

### Describe the GFX issue

The 'National Ethics Committee' national spirit has no unique GFX icon. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Vetoed the JFK's Civil Rights Act.
3. Elect RJK (NPP - Progressive).
4. Complete the National Ethics Commission focus. 

### Expected behaviour

Forgot to add unique GFX national spirit icon.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/255e5ba0-6671-45eb-aadc-0c344fcf9b45)

**Comment by runelead00** [comment]
Fixed in Dev Build
