### ISSUE TITLE
CCL - Still Keeps pre-war and war national spirits after the end of the war.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3534]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Unión Revolucionaria de Colombia wins in the Colombian civil war, they still have pre-war and war national spirits.

### Steps to reproduce / Cause of the issue

Should Unión Revolucionaria de Colombia wins in the Colombian civil war.

### Expected behaviour

The pre-war and war national spirits should be removed when the civil war is ended.

### Screenshots

![image](https://github.com/user-attachments/assets/a7b56a73-2ffa-4b81-b9da-20ffd528aeb7)
![image](https://github.com/user-attachments/assets/34e2ab2d-6d36-40c4-a2ab-90121a79db13)
![image](https://github.com/user-attachments/assets/fffb191a-fba0-45ad-b057-ed330493a83a)
![image](https://github.com/user-attachments/assets/df75cece-f27d-4c65-b515-52aa094ced38)
![image](https://github.com/user-attachments/assets/6a2d8fb1-fb74-44c0-951a-f6ed0520dd15)

### Additional information

This issue, I guess, is connected to other sides of the civil war, not only the Unión Revolucionaria de Colombia.

**Comment by Jack121Q** [comment]
Fixed. Thank you for reporting

**Comment by Marok132** [comment]
> Fixed. Thank you for reporting

You're welcome. You can close this issue then.
