### ISSUE TITLE
DOM - The national spirit "The Pan-American Force" is not removed after transferring the authority to civils.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3535]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

After Haiti victory over the Dominican Republic, there was set up an interim authority. After it ended, the civil one was established. However the national spirit "The Pan-American Force" is still here.

### Steps to reproduce / Cause of the issue

1. Trujillo defeats the Legion.
2. Trujillo invades Haiti.
3. Haiti defeats the Dominican Republic.
4. To wait when the civil authority takes power.

### Expected behaviour

The national spirits The Pan-American Force should have removed after the civils take power.

### Screenshots

![image](https://github.com/user-attachments/assets/e03ce0e5-7a82-4418-add2-d6fd194290c3)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thank you.
