### ISSUE TITLE
USA - Slight issue focus requirement of 'The Bitterest of the Bitter' 

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3536]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_npp_rfk.zip](https://github.com/user-attachments/files/16677464/USA_npp_rfk.zip)

### Describe the bug

The 'The Bitterest of the Bitter' focus requires the 'Build A Safety Net' and 'The Power of a Handshake' focuses to be completed but the 'The Bitterest of the Bitter' focus is not align with the 'Build A Safety Net' focus. 

So, the 'Build A Safety Net' focus should require to have 'The Power of a Handshake' focus to completed because of the national focus line and 'The Power of a Handshake' focus should require to have 'Build A Safety Net' and 'Testimony From The People' focuses to complete. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Vetoed the JFK's Civil Rights Act.
3. Elect RJK (NPP - Progressive).
4. See the Bitterest of the Bitter focus requirement.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/7d813616-a6e8-4e0f-89db-ae03690ec21b)

![Image_2](https://github.com/user-attachments/assets/c0589484-2fe2-4ab4-85d2-e11dbc026e41)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
