### ISSUE TITLE
USA - The Operational Success or Failure intelligence events are using the CIA picture instead of FBI in the Americas region

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3540]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After selecting any of the intelligence operations in the North, Central and South America regions and the Operational Success or Failure intelligence event pops out, the outcome of the intelligence operation events in the Americas are using the CIA picture instead of using the FBI picture. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Select any intelligence missions in the North, Central and South America regions. 
3. The outcome of the intelligence event. 

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/4810f57d-e749-4a27-805a-c31e4960cc06)

![Image_2](https://github.com/user-attachments/assets/c0543b62-5f74-469e-bdfe-99d1b7adef59)

**Comment by runelead00** [comment]
Fixed in Dev Build
