### ISSUE TITLE
USA - All the intelligence events outside the Americas are didn't change their event picture to old one

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3541]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

All or most of the intelligence events outside the Americas are using the new CIA event picture instead of the old CIA event picture. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Intelligence events outside the Americas triggered.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/b0e3bf91-f2b5-4cb6-9987-a6becae9626f)

![Image_2](https://github.com/user-attachments/assets/15c6a92a-d097-4abb-ae71-10beebff47a0)

**Comment by runelead00** [comment]
Non-issue
