### ISSUE TITLE
VIC - Trường Chinh does not use his existing bio .

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3543]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Trường Chinh's bio is not shown in the game although there is in the file TNO_Vietnam_l_english. Also his name is spelled as Trường Chinh, not Truong Chinh.

### Steps to reproduce / Cause of the issue

To put this bio below for him.

POLITICS_TRUONG_CHINH_DESC: "The man who now calls himself Truong Chinh was born as Dang Xuân Khu in the Red River Delta not far from Hà Noi in 1907. After twenty-nine years spent on a life journey that led him first towards socialism and later towards the communism of Ho Chí Minh, he took his current name - "Long March" in Vietnamese - to honor the Long March undertaken by Mao Zedong, who was later to be martyred fighting the Japanese imperialists.\n\nNow Ho Chí Minh is dead, and an at least temporary victory against the Japanese has been assured. His successor is the man who the Vietnamese communists were proud to refer to as the 'excellent student of Bác (Uncle) Ho' - Truong Chinh. His revolutionary credentials are impeccable, and his loyalty to Vietnam and the Communist Party never in doubt: he took pride in his devotion to Ho's ideals even though he did not always agree with them.\n\nWith control now fully in Truong's hands, and the loyalty of his party and nation more or less assured, Truong is freed to move forward with a somewhat changed ideological program: the main plans will be predicated upon a land reform inspired by Mao Zedong's writings combined with a Bolshevist interpretation of the anti-colonial movement.\n\nRegardless of his plans, Truong will give his predecessor every reason to be proud of him. This he swears on his honor and loyalty to the Revolution and to Vietnam."

### Expected behaviour

His bio should be put.

### Screenshots

![image](https://github.com/user-attachments/assets/ef55f6d6-b521-4038-8133-4940dd1707ed)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thank you!
