### ISSUE TITLE
MEX - Icon-text conflict

### ISSUE THREAD

**Issue by DSDHX** [TNODevs/TNO-Bug-Tracker#3544]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### List the loc issues below

There are two places in the Mexican tech tree where the text does not match the icon. _(It should be sort of a mix of localization and GFX issue, but I didn't find out how to add two Labels...)_
1. Infantry equipment 1988
- MEX_infantry_equipment_5:0 "DGIM FX-88" in "TNO_Mexico_l_english.yml" (line 94) (...2438003901\localisation\english)
- "DGIM FX-87" shown in "MEX_Infantry_88.dds" (...2438003901\gfx\interface\technologies)
![屏幕截图 2024-08-22 025550](https://github.com/user-attachments/assets/efb0cc86-fcc9-43ae-b392-d505d2c66223)
2. MBT equipment 1980
- MEX_MBT_equipment_4:0 "DN-30A1" in "TNO_Mexico_l_english.yml" (line 198) (...2438003901\localisation\english)
- "DN-37" shown in "MEX_MBT_80.dds" (...2438003901\gfx\interface\technologies)
![屏幕截图 2024-08-22 025625](https://github.com/user-attachments/assets/c07f96da-e123-42ae-bb6d-c19d5e01be04)

**Comment by runelead00** [comment]
Fixed in Dev Build
