### ISSUE TITLE
Helicopters

### ISSUE THREAD

**Issue by zulmietek** [TNODevs/TNO-Bug-Tracker#3545]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

?

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, BBA, TOA

### Describe the bug

When i Research a attack helicopter i cant add it to template

### Steps to reproduce / Cause of the issue

.

### Expected behaviour

Work

**Comment by runelead00** [comment]
did you research the support company

**Comment by runelead00** [comment]
User error assumed
