### ISSUE TITLE
USA - A no line break in the event's effect of 'An Ocean Pacified'

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3549]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_hawaii_return.zip](https://github.com/user-attachments/files/16724170/USA_hawaii_return.zip)

### List the loc issues below

- [ ] 1. In the 'An Ocean Pacified' event, there is a no line break of "Toko is renamed to Honolulu" loc.
![Image_1](https://github.com/user-attachments/assets/070c8bb0-81b3-41a0-b98a-33922eb7ddb8)

**Comment by runelead00** [comment]
Fixed in Dev Build
