### ISSUE TITLE
USA/GER - The Hamburg Invitation events have no event picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3550]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Most or all of the Hamburg invitation events have no event picture. 

### Steps to reproduce / Cause of the issue

1. Speer won the German Civil War.
2. NPP won the election in the USA.
3. Speer's Germany chose to favor USA.
4. Germany chooses the 'Lying, Congressional Style' focus.

### Expected behaviour

Forgot to add event pictures. 

### Screenshots

![Image_1](https://github.com/user-attachments/assets/4e8406e6-fc75-48a4-bd3d-64d4ec58a78f)

![Image_2](https://github.com/user-attachments/assets/b94a2791-ea4d-44fe-866f-8bb35ef399e7)

![Image_3](https://github.com/user-attachments/assets/899b4db3-5820-4a9f-a208-8869d4a0db11)

![Image_4](https://github.com/user-attachments/assets/b3301e50-eead-4048-9599-79f84c0f4dd5)

![Image_5](https://github.com/user-attachments/assets/85d5a576-b60a-494c-83a0-810deb821bf8)

![Image_6](https://github.com/user-attachments/assets/446afde1-a4d9-4e5a-b2e5-693fdfc097b0)

![Image_7](https://github.com/user-attachments/assets/3e9b4cc1-8159-4125-b80d-3118fb28a021)

![Image_8](https://github.com/user-attachments/assets/368dba8d-bc29-4a76-b463-5184ecc8aa1f)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
