### ISSUE TITLE
GER - USA's French Reclamation victory event appeared after Free France victory

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3551]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/user-attachments/files/16727337/GER_game.zip)

### Describe the bug

After Free France wins the Reclamation of France, the USA's French Reclamation victory event somewhat appeared instead of the French Reclamation defeat for Germany event appear. 

### Steps to reproduce / Cause of the issue

1. Free France won the West Africa War.
2. Reclamation War started.
3. Free France and French Resistance won the Reclamation War.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/c403407b-18c5-434b-ab44-8ccea465205a)

**Comment by runelead00** [comment]
Working as Designed
