### ISSUE TITLE
GER - Unable to take the 'A Night in Wonderful Hamburg' focus, just bypass the focus

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3552]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/user-attachments/files/16727560/GER_game.zip)

### Describe the bug

When successful with the American delegation, the 'A Night in Wonderful Hamburg' focus is suddenly bypassed without taking this focus and its effects. And the focus requirement 'The affair with the American delegation has been resolved successfully' is not marking check despite the success. 

This focus shouldn't have bypass because for to take the focus effects. 

### Steps to reproduce / Cause of the issue

1. Speer won the German Civil War.
2. NPP won the election in the USA.
3. Speer's Germany chose to favor USA.
4. Germany chooses the 'Lying, Congressional Style' focus.
5. Germany success détente with USA. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/b32c40d9-18d5-4e10-bd11-89c2d822c8dd)

**Comment by runelead00** [comment]
Fixed in Dev Build
