### ISSUE TITLE
SPR - Has negative political power gain during the Iberian Wars

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3553]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[SPR.zip](https://github.com/user-attachments/files/16727810/SPR.zip)

### Describe the bug

During the Iberian Wars, SPR (Spanish Republic) has negative political power gain and unable to take most of the Iberian Wars decisions even for AI. 

### Steps to reproduce / Cause of the issue

1. The Iberian Wars triggered.
2. Switch to SPR (Spanish Republic) tag.
3. Check the political power gain. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/77724086-4c03-48e1-8ac9-1dfcf70ec6df)

**Comment by runelead00** [comment]
Will be fixed for Iberian facelift
