### ISSUE TITLE
USA - Some of the decisions have changed their icons into US political parties icon after select any of the Smoke and Mirrors decisions

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3554]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_gameplay.zip](https://github.com/user-attachments/files/16728229/USA_gameplay.zip)

### Describe the bug

After select any of the Smoke and Mirrors decisions, some or most of the decisions are somewhat changed their icon into US political parties icon like NPP and its Caucuses and RDC.

### Steps to reproduce / Cause of the issue

Play as USA.
Elect the 1964 president.
Has the president's agenda decisions.
Select any of the Smoke and Mirrors decisions.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/ba5dacd6-6abe-43be-85f9-8f6f46436f32)

**Comment by runelead00** [comment]
Fixed these two specific categories in Dev Build
