### ISSUE TITLE
USA - Democrat senators support does not increase after selecting the decision in the bill decision

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3558]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_rfk.zip](https://github.com/user-attachments/files/16736294/USA_rfk.zip)

### Describe the bug

After the 'Talk with the Democrats' decision is finished in the bill decision, the Democrat senators support does not increase its numbers despite the bill decision description says that the Democrat senators have **plenty of** room for further compromise. Because the word "plenty of" which means that there will be more support for this bill if wanting to compromise with them. 

There are some bills have issue with this one about gaining one senator support after selecting the 'Talk with the (Political Party senators)' despite it says **plenty of** room for further compromise.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect RFK as the new president.
3. Select the 'The National Labor Relations Act' focus.
4. The Democrat senators have plenty of room for compromise in the bill decision. 
5. Finish the Talk with the Democrats decision. 

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/6407ff5e-ba68-48e1-9bb1-902dcdb5c888)

**Comment by runelead00** [comment]
Fixed in Dev Build
