### ISSUE TITLE
Turkey  - APC model for Turkey

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#356]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
I found this article about APC design that is based in Turkey and is 60's design.
https://www.oryxspioenkop.com/2021/11/forgotten-designs-turkish-cemal-tural.html
![image](https://user-images.githubusercontent.com/84231463/143970911-050343a7-ea15-4582-8152-84e7048d4704.png)

**Reasoning Behind Suggestion:**
This might be a good design for Turkish APC designs for the PW Patch.

**Comment by runelead00** [comment]
Our tech team have already decided on the Turkish tech tree
