### ISSUE TITLE
USA - Generous Subsidies is not matching with its icon in the economic policies

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3560]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_rfk.zip](https://github.com/user-attachments/files/16736640/USA_rfk.zip)

### Describe the bug

When the Moderate Subsidies changed to Generous Subsidies for Unemployment in the economic policies through event or national focus, the Moderate Subsidies icon is not changed into Generous Subsidies icon in the economic policies.

However, after reloading the save game, the Generous Subsidies have no icon and it remains blank which is unable to select the status of Unemployment in the economic policies because only the icon has able to see the policy status through viewing and selecting it.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Change to Generous Subsidies for Unemployment in the economic policies through event or national focus.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/e80a3151-bc47-4b66-843d-f95adff1c6d5)

![Image_2](https://github.com/user-attachments/assets/3358c6c4-8e44-403c-9055-81a41a0f59b5)

**Comment by runelead00** [comment]
Fixed in Dev Build
