### ISSUE TITLE
USA - Issue of The Social Security Act national focus' effect loc

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3561]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_rfk.zip](https://github.com/user-attachments/files/16738272/USA_rfk.zip)

### Describe the bug

The effect loc from The Social Security Act national focus says that "Taking this focus will prevent you from taking non-Social Security Act focuses until the Social Security has been sent through Congress" but after taking this national focus, the non-Social Security Act focuses are still available, and instead it disables the four 'The Road Towards Justice' decisions.

If this intended that The Social Security Act national focus is taken and disable the four 'The Road Towards Justice' decisions, the effect loc should be changed to avoid confusion. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect RFK as the new president.
3. See the national focus effect of The Social Security Act.
4. Complete The Social Security Act national focus.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/0860a255-9607-4fd7-9e65-6b767962f8a1)

![Image_2](https://github.com/user-attachments/assets/dc3c6934-7ab9-42e1-9b1b-b205e407ec4d)

**Comment by runelead00** [comment]
Adjusted tooltip in dev build
