### ISSUE TITLE
USA - March of Suriname intel event has the CIA picture instead of putting the FBI picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3562]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the 'March of Suriname' intel event appeared, this event uses the CIA picture instead of using the FBI picture.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Play through 1970's.
3. The 'March of Suriname' intelligence event appeared.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/5411e828-2227-4dac-a8fd-6e8f15f74c80)

**Comment by runelead00** [comment]
Fixed in Dev Build, including references to FBI in event loc
