### ISSUE TITLE
JAP - Turkes Kenes in Cold War ranking is marked Defeat instead of Victory due to points are marked green

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3564]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Logs.zip](https://github.com/user-attachments/files/16740328/Logs.zip)
[USA_game.zip](https://github.com/user-attachments/files/16740332/USA_game.zip)

### Describe the bug

When the aftermath of the Turkes Kenes in favor of Afghanistan and Japan, and Talas, Tajikistan and Turkestan are become puppets of Afghanistan, in the Cold War ranking is marked Defeat for Japan instead of Victory due to points are marked green. 

### Steps to reproduce / Cause of the issue

1. Play through 1972's.
2. Turkes Kenes triggered.
3. Aftermath of the Turkes Kenes.
4. Afghanistan won in the Turkes Kenes.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/c19f85a3-2e6d-4bd5-bab4-d842fe7674db)

![Image_2](https://github.com/user-attachments/assets/a5d33df8-c352-45bd-bc67-64c8585f1603)

**Comment by runelead00** [comment]
Fixed in Dev Build
