### ISSUE TITLE
Almost Every Country has no Colour

### ISSUE THREAD

**Issue by DoctorWhoGaming** [TNODevs/TNO-Bug-Tracker#3566]
### Operating System

Windows 10

### HOI4 version

Bolivar v1.14.7.f4d3 (25df) (S)

### TNO version

TNO v1.5.0a - "The Ruin"

### Do you have other mods in use?

The New Order: Operation Deep Freeze

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

A lot of countries look white when using the mod Operation Deep Freeze, exept for a few.

### Steps to reproduce / Cause of the issue

1.(Obiusly) Activate TNO and TNO Deep Freeze at the same time and boot the game.               2. Start a new game.

### Expected behaviour

I expect the right colours of each country

**Comment by runelead00** [comment]
ODF is not compatible with current TNO
