### ISSUE TITLE
Turkestan tags - CA_Turkes_Kenes_Apathy national spirit is not localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3567]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/user-attachments/files/16742279/USA_play.zip)

### Describe the bug

The `CA_Turkes_Kenes_Apathy` national spirit is not localized for Turkestan tags. 

### Steps to reproduce / Cause of the issue

1. Play through 1972's.
2. Turkes Kenes triggered.
3. Aftermath of the Turkes Kenes.
4. Afghanistan and Japan won in the Turkes Kenes.

### Expected behaviour

Forgot to add localization for national spirit.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/97809e09-79d6-4c88-8fca-3827b45c3e60)

**Comment by runelead00** [comment]
Fixed in Dev Build
