### ISSUE TITLE
USA - No Foreign Minister added when the inauguration of Henry M. Jackson triggered

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3569]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/user-attachments/files/16743248/USA_game.zip)

### Describe the bug

When the inauguration of Henry M. Jackson triggered, there is no Foreign Minister added. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Henry M. Jackson (NPP-P) in the 1972 election.
3. Henry M. Jackson inauguration. 

### Expected behaviour

Forgot to add political minister.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/188c9fb9-ec49-43dc-bc0c-d058ec39013c)

**Comment by runelead00** [comment]
Fixed in Dev Build
