### ISSUE TITLE
Mod Launcher crashes at "Turning the Key"

### ISSUE THREAD

**Issue by MonarchistReactionary** [TNODevs/TNO-Bug-Tracker#357]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.9
- TNO Version: Toolbox Theory
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all expansions

**Longer Description of Issue:** So whenever I start up the mod it loads and then always seems to crash at "Turning the Key"

**Steps to Reproduce/Cause Issue:**

1. I have tried -opengl but that doesn't seems to work

2.

etc...

**Screenshots:** None it just crashes

**Game Saves and Log Files, if possible:**

**Comment by masterbobli** [comment]
Toolbox theory should only be compatible with HOI4 version of 1.10. Please update your game and check if the issue persists.
