### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Starco77** [TNODevs/TNO-Bug-Tracker#3572]
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

1.6.0 - So Far From God

### Do you have other mods in use?

French translation for tno

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

Third south african war dont fire the country spawn when oberkommando sudafrika collapse but the war never happen

### Steps to reproduce / Cause of the issue

1. Play huttig
2. Make the second south african war happen
3. Make oberkommando sudafrika win (somehow)
4. No third south african war

### Expected behaviour

I expected the third south african war to fire

### Screenshots

![image](https://github.com/user-attachments/assets/4c64d579-aa95-49c1-8b51-1263c7f74ccc)

**Comment by runelead00** [comment]
Working as Designed, 3rd SAW is just the collapse
