### ISSUE TITLE
Two naval issues with the mod when not running the naval MtG DLC

### ISSUE THREAD

**Issue by Lewa263** [TNODevs/TNO-Bug-Tracker#3573]
### Operating System

Windows 

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The naval satisfaction mechanic for economic sphere leaders checks for certain types of ships (corvette, frigate, destroyer, etc.) and gives modifiers based on whether the navy has enough of that type of ship. However, the corvette type ship is only available with the Man the Guns DLC active. So without the DLC, it is impossible to get rid of the penalty from your unsatisfactory navy.

Additionally, Japan and the USA (maybe other countries too?) only begin with frigate type ships when the Man the Guns DLC is active, even though they are still available in this mod without the DLC. Some of the ships are destroyers without the DLC, while others simply don't exist.

### Steps to reproduce / Cause of the issue

1. Run TNO with and without the Man the Guns DLC active.
2. Look at the naval satisfaction tooltip and the starting navies of Japan and the USA.

### Expected behaviour

I expected the mod to function essentially the same for players without this DLC.

### Screenshots

Here is the naval satisfaction tooltip for Japan in the first month **with** the Man the Guns DLC active:
![Screenshot 2024-08-28 161523](https://github.com/user-attachments/assets/5619365e-00be-49f8-a67c-aa1d63cbc264)

And here is the same naval satisfaction tooltip **without** the DLC active:
![Screenshot 2024-08-28 162158](https://github.com/user-attachments/assets/f01bcf8b-2c6c-4976-9ab5-6d6793971496)

**Comment by Lewa263** [comment]
I found that it is possible to disable the naval superiority thing entirely when MtG isn't active by putting `has_dlc = "Man the Guns"` in the limit block 3666 in the `TNO_economy_backend_scripted_effects.txt` file. The game seems to still be functioning with that change, but it may still be causing problems that I can't see. Hopefully you devs can figure out a more elegant solution that would still allow the other ship types to count for something.

**Comment by runelead00** [comment]
Fixed in Dev Build
