### ISSUE TITLE
GER - GER_provide_local_recon decision has no localized

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3577]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_mad.zip](https://github.com/user-attachments/files/16828797/GER_mad.zip)

### Describe the bug

The `GER_provide_local_recon` decision has no localized. 

### Steps to reproduce / Cause of the issue

1. Play as GER.
2. Second Malagasy Uprising triggered.
3. See Second Malagasy Uprising proxy war decisions.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/7a278690-9521-4d5c-a0c6-2b4268fb32ac)

**Comment by runelead00** [comment]
Fixed in Dev Build
