### ISSUE TITLE
GER - Some outcome events of the PPI have no picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3578]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Some of the PPI outcome events for Germany have no event pictures.

### Steps to reproduce / Cause of the issue

1. Play as GER.
2. The PPI triggered.
3. Flavor events of PPI for GER.

### Expected behaviour

Forgot to add event picture.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/e48b4667-93ee-47ff-99c7-934d51835af2)

![Image_2](https://github.com/user-attachments/assets/2719df2b-1ac0-4523-a2ff-0476d7229923)

**Comment by Fortune801** [comment]
Fixed on Dev Build
