### ISSUE TITLE
USA - PPI ceasefire breakdown events have no event picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3579]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the PPI ceasefire is breaking down and the events appeared, the PPI ceasefire breakdown events have no event picture.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. The PPI triggered.
3. The PPI ceasefire triggered.
4. The PPI ceasefire breakdown.

### Expected behaviour

Forgot to add event pictures.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/d0e503e4-e229-4e0b-a7aa-12a150cb84b2)

**Comment by Fortune801** [comment]
Fixed on Dev Build
