### ISSUE TITLE
PRC - Empower Civilian Faction decision decreases Civilian Loyalty

### ISSUE THREAD

**Issue by Corgilover** [TNODevs/TNO-Bug-Tracker#358]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? BfB, NsB

**Longer Description of Issue:**
This specific decision decreases civilian loyalty even though i'm pretty sure it should decrease military loyalty, as the Empower Military Faction decision decreases civilian loyalty.
**Steps to Reproduce/Cause Issue:**

1. Start game as PRC
2. Select Empower Civilian Faction decision

etc...

**Screenshots:**
https://i.imgur.com/GuWFroo.jpg

**Comment by runelead00** [comment]
Changed in UB
