### ISSUE TITLE
[Bug]:  Italy - Victory point bugged for italian levant

### ISSUE THREAD

**Issue by BaveMavick64** [TNODevs/TNO-Bug-Tracker#3580]
### Operating System

windows 11

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

victory point for the capital of Lebenon is bugged when under control of Governatorato del Levante. 

### Steps to reproduce / Cause of the issue

when you turn on endonyms the vicotry name gets bugged

### Expected behaviour

the name would change or if no name was added nothin at all

### Screenshots

![Screenshot (204)](https://github.com/user-attachments/assets/6a97c1a9-d24b-42e2-baf9-69a97df2b8e5)

**Comment by runelead00** [comment]
Fixed in Dev Build
