### ISSUE TITLE
ITA/JER/ISR/PAL/JOR/LEB - Levantine Union should be Associate States of Italy with the said countries having Military Access and Guarantees on each other 

### ISSUE THREAD

**Issue by ThePikminCaptain** [TNODevs/TNO-Bug-Tracker#3584]
### HOI4 version

1.14

### TNO version

1.60

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

The countries in the Levantine union should be associates of Jerusalem which is an associate of Italy, or they are all direct associates with Italy (the latter change should happen if Bulgaria aligns with Italy and puppets Macedonia as Italy can’t move troops in it)

### Justifications

I feel like this should happen as people would stop going for the kingdom path to still hold the Levant as the new countries would remain allied with you.

**Comment by runelead00** [comment]
We're not throwing out most of one of the current skeleton paths that already been slated to replaced with different skeleton
