### ISSUE TITLE
GER/OST - Ostland didn't join the Zollverein economic sphere and didn't receive the Member of the Zollverein national spirit after Osland folded without war

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3585]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/user-attachments/files/16869123/GER_play.zip)

### Describe the bug

When Reichskommissariat Ostland under Stahlecker rejoin the Einheitspakt though Speer's Ostland negotiation events, Reichskommissariat Ostland is somewhat didn't join the Zollverein economic sphere and didn't receive the Member of the Zollverein national spirit. 

### Steps to reproduce / Cause of the issue

1. Play as GER.
2. Speer's Germany won the German Civil War.
3. Reichskommissariat Ostland won the Ostland Civil War.

### Expected behaviour

Forgot to check these Ostland(after civil war) events.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/d0094e51-90c8-474e-b0e7-022744f5f210)

![Image_2](https://github.com/user-attachments/assets/78c002c1-a6a2-4854-9d5a-2cd8105b3824)

![Image_3](https://github.com/user-attachments/assets/9e10403e-d224-4b4c-830d-f5a9686f4153)

**Comment by runelead00** [comment]
Fixed in Dev Build
