### ISSUE TITLE
GER - 'Reorganize the Second Patriotic Army' decision gives -0.00% of Max Planning Breakthrough Factor

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3586]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_play.zip](https://github.com/user-attachments/files/16871938/GER_play.zip)

### Describe the bug

The 'Reorganize the Second Patriotic Army' decision effect shows that it gives -0.00% of Max Planning Breakthrough Factor instead of increasing them.

### Steps to reproduce / Cause of the issue

1. Play as GER.
2. Continuation of the Colombian Civil War triggered.
3. The Second Patriotic Army appeared.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/921d7882-1a65-4e28-a036-e6b75e19dbbd)

**Comment by runelead00** [comment]
Fixed in Dev Build
