### ISSUE TITLE
GER - Some of the Speer's Architecture events have generic event picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3589]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_speer_architect_events.zip](https://github.com/user-attachments/files/16894631/GER_speer_architect_events.zip)

### Describe the GFX issue

Some of the Speer's Architecture events use the generic event picture instead of different or unique pictures based on the event's description.

### Steps to reproduce / Cause of the issue

1. Play as GER.
2. Speer's Germany won the German Civil War.
3. End of Phase 1 focus trees.
4. Begin the Phase 2 focus trees.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/477fa535-d38b-42eb-981a-fc20cbfe2770)

**Comment by runelead00** [comment]
Fixed in Dev Build
