### ISSUE TITLE
(Tested with West Alaska) - CTD in Trading Partners

### ISSUE THREAD

**Issue by ReetheBro** [TNODevs/TNO-Bug-Tracker#359]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**
The game crashes when you click on a country that does not exist in the Trade tab under Economy
**Steps to Reproduce/Cause Issue:**

1. Go to Economy 

2. Click Trade

3. Click on country that doesn't exist in the game (save shows Ural League, who is already owned by the West Siberian Republic)
**Screenshots:**
![hoi4_4](https://user-images.githubusercontent.com/94774585/144011733-3dfa53b7-5c1c-4f30-bf96-397544d4e9fc.png)

**Game Saves and Log Files, if possible:**
Game Save:
[MAG_1968_07_01_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7624116/MAG_1968_07_01_01.zip)

Log Files:
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7624119/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7624120/error.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7624121/system.log)

**Comment by runelead00** [comment]
Fixed in Dev Build
