### ISSUE TITLE
GER - The 'Relocate the Protestors' event has no event picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3595]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The 'Relocate the Protestors' event has no event picture added.

### Steps to reproduce / Cause of the issue

1. Speer won the German Civil War.
2. NPP won the election in the USA.
3. Speer's Germany chose to favor USA.
4. Germany chooses the 'Lying, Congressional Style' focus.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/38f15c28-c252-476d-89dd-a5416d50f43e)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
