### ISSUE TITLE
GER - Fuhrererlass, Zukunftsmusik, Past is Past, and Buyout national focuses requirement issue

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3596]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/user-attachments/files/16917010/GER_game.zip)

### Describe the bug

When the Wehrwirtschaftsführers' power influence are 'middling'(25.00%) in the Economic GUI, the Fuhrererlass, Zukunftsmusik, Past is Past, and Buyout national focuses are somehow available despite the focus requirement says that the 'company' must be 'waning' for us to take action.

The national focus requirement of Fuhrererlass, Zukunftsmusik, Past is Past, and Buyout should be 20.00% influence power of the company because 20.00% is 'waning' status.

### Steps to reproduce / Cause of the issue

1. Play as GER.
2. Speer won the German Civil War.
3. Finishing phase 1 focus trees.
4. Begin phase 2 focus trees.
5. Decreasing great companies' power in the Economic GUI.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/e099d18d-98f6-4fa7-8adf-1b9571a8d26c)

![Image_2](https://github.com/user-attachments/assets/c97dbe1b-b286-4f74-8777-48ae3bc16a86)

**Comment by Fortune801** [comment]
Fixed on Dev Build
