### ISSUE TITLE
CLC - State lore of Bogotá refers to New Granada victory in La Violencia instead of National Socialist League victory lore

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3597]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/user-attachments/files/16917780/GER_game.zip)

### Describe the bug

After the National Socialist League wins the Second Colombian Civil War, the state lore of Bogotá in the last paragraph talks about the New Granada victory in La Violencia instead of National Socialist League victory lore.

### Steps to reproduce / Cause of the issue

1. Continuation of Colombian Civil War triggered.
2. Second Patriotic Army spawned.
3. The SPA won the Colombian Civil War.
4. Second Colombian Civil War triggered.
5. National Socialist League won the Second Colombian Civil War.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/8675958d-b501-43bb-a4a0-58ee22e73427)

**Comment by runelead00** [comment]
Fixed in Dev Build
