### ISSUE TITLE
[Bug]: Amur - Hailanpao not transferred

### ISSUE THREAD

**Issue by taxevader6217** [TNODevs/TNO-Bug-Tracker#3599]
### Operating System

Windows 11

### HOI4 version

Latest

### TNO version

Latest

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[AMR_1962_02_04_08.zip](https://github.com/user-attachments/files/16918881/AMR_1962_02_04_08.zip)

### Describe the bug

Hailanpao cannot be transferred to Amur for some reason. I used console commands to switch to Machuria to see if I could click the event to transferrer but that didn't work.

### Steps to reproduce / Cause of the issue

1. Go to Amur 2. Do the "Contact the Japanese" focus 3. Click the event to request Hailanpao 4. Watch as Hailanpao is not transferred and nothing happens

### Expected behaviour

I expected Hailanpao to be transferred to Amur

### Screenshots

![Amur glitch](https://github.com/user-attachments/assets/0cdc3f6b-6167-4bd8-b129-1215d20914da)

### Additional information

:(

**Comment by runelead00** [comment]
Cant Reproduce
