### ISSUE TITLE
Terra e Libertà Map Issues

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#36]
Bialystok needs to be rounded off more
![Hearts of Iron IV 6_08_2021 7_52_27 PM](https://user-images.githubusercontent.com/59920852/128492804-2e782a38-80b4-46d7-a30d-e9f807901536.png)
![image](https://user-images.githubusercontent.com/59920852/128492983-92883373-e8d4-46bf-82b4-4b69dc5239b4.png)

Wrong/missing cultures
![Hearts of Iron IV 6_08_2021 7_54_58 PM](https://user-images.githubusercontent.com/59920852/128493541-fef49da3-dd70-455f-b663-8d715494116e.png)
![Hearts of Iron IV 6_08_2021 7_55_02 PM](https://user-images.githubusercontent.com/59920852/128493556-77292ea9-7838-4221-b368-6291c9e9fc02.png)
![Hearts of Iron IV 6_08_2021 7_55_07 PM](https://user-images.githubusercontent.com/59920852/128493561-7e250003-7d58-47ba-9e4a-5c406c769c7c.png)
![Hearts of Iron IV 6_08_2021 7_55_15 PM](https://user-images.githubusercontent.com/59920852/128493565-e128d166-ccf9-475b-bfa1-6b047b4b0501.png)
![Hearts of Iron IV 6_08_2021 7_55_24 PM](https://user-images.githubusercontent.com/59920852/128493572-3de7d133-8494-43fe-9b4a-edd824c5e4f4.png)
![Hearts of Iron IV 6_08_2021 7_55_42 PM](https://user-images.githubusercontent.com/59920852/128493576-ddec31c6-a51b-4406-a3d7-ade02b395a66.png)
![Hearts of Iron IV 6_08_2021 7_56_11 PM](https://user-images.githubusercontent.com/59920852/128493578-620d3e7e-cac1-4a72-9b34-f69f1d5f19e5.png)
![Hearts of Iron IV 6_08_2021 7_56_14 PM](https://user-images.githubusercontent.com/59920852/128493583-15d382c4-92d9-41ec-9486-f6cdce200a46.png)
![Hearts of Iron IV 6_08_2021 7_56_26 PM](https://user-images.githubusercontent.com/59920852/128493589-833df8bf-8137-49e0-91c2-c3cbd0eb29d5.png)
![Hearts of Iron IV 6_08_2021 7_56_33 PM](https://user-images.githubusercontent.com/59920852/128493593-8adacff5-e96a-443a-901d-e27b1aa2fb42.png)
![Hearts of Iron IV 6_08_2021 7_56_44 PM](https://user-images.githubusercontent.com/59920852/128493599-6d32f777-023b-4246-9936-1f9def39845e.png)
![Hearts of Iron IV 6_08_2021 8_00_56 PM](https://user-images.githubusercontent.com/59920852/128493926-2f644b24-2bff-4f27-924a-311fdb4eed03.png)

Lake out of place
![Hearts of Iron IV 6_08_2021 7_58_40 PM](https://user-images.githubusercontent.com/59920852/128493633-e15280db-d50d-4ab0-882c-0eb140590b44.png)

Incorrect border/coastline
![Hearts of Iron IV 6_08_2021 8_00_00 PM](https://user-images.githubusercontent.com/59920852/128493837-5128e10c-8b4c-4301-90a6-7feaa88dd02e.png)
![image](https://user-images.githubusercontent.com/59920852/128493869-087927e2-549c-491c-8f6d-ef79ae3a7a41.png)

Missing lake
![Hearts of Iron IV 6_08_2021 8_01_41 PM](https://user-images.githubusercontent.com/59920852/128494022-830456fd-51e0-4a54-a33a-9e624dca9f80.png)

Macedonian border should be fixed
![Hearts of Iron IV 6_08_2021 8_02_16 PM](https://user-images.githubusercontent.com/59920852/128494225-a4fc699a-dfeb-4874-8dd2-3d2b5d504660.png)
![image](https://user-images.githubusercontent.com/59920852/128494230-fe3138ff-965f-4d32-89bb-199d005327e3.png)

Missing land
![Hearts of Iron IV 6_08_2021 8_05_11 PM](https://user-images.githubusercontent.com/59920852/128494445-b4de0313-0eca-452b-b146-db95c380a15e.png)

**Comment by Chewy598** [comment]
I probably should have made this text instead of screenshots

**Comment by runelead00** [comment]
All seems to be fixed in current Dev Build
