### ISSUE TITLE
Sverdlovsk- broken bio on startup menu

### ISSUE THREAD

**Issue by dym4201984** [TNODevs/TNO-Bug-Tracker#360]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?

**Longer Description of Issue:** On the starting screen, Konstantin Rokossovsky's bio has the sentence "Rokossovsky would quickly gather his 3rd Army in the city of [Get_RUS_Yekaterinburg_Or_Sverdlovsk]"

**Steps to Reproduce/Cause Issue:**

1. Go to the Country Select Screen

2. Mouse over Sverdlovsk

**Screenshots:**

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting.
