### ISSUE TITLE
[Bug] Novosibrisk Takeover Bar not filling up to 100%

### ISSUE THREAD

**Issue by MasonBaldass** [TNODevs/TNO-Bug-Tracker#3600]
### Operating System

Windows 10

### HOI4 version

1.14.8

### TNO version

1.3.2c

### Do you have other mods in use?

Second West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Novosibrisk Takeover Bar not filling up to 100%

### Steps to reproduce / Cause of the issue

After Using enough mission decisions on a nation a certain amount of times the bar stops filling up

### Expected behaviour

The Takeover bar Not fill up to 100%

### Screenshots

![Screenshot (156)](https://github.com/user-attachments/assets/bd658324-d7d6-457e-be5c-2edc625a3569)

**Comment by runelead00** [comment]
Fixed in Dev Build
