### ISSUE TITLE
GER - Einheitspakt and Kyōeiken are still embargoing each other after completing Ending Japan Embargo focus tree

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3601]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[GER_game.zip](https://github.com/user-attachments/files/16920247/GER_game.zip) (before taking all end Japan embargo focus tree)
[GER_play.zip](https://github.com/user-attachments/files/16920248/GER_play.zip) (After taking all end Japan embargo focus tree)

### Describe the bug

After finishing 'The Land of the Rising Sun' focus tree, the Einheitspakt, Kyōeiken and their alignments are still embargoing each other despite the national focuses say that the embargo will end if taking these national focuses. 

### Steps to reproduce / Cause of the issue

Speer's Germany won the German Civil War.
Speer chose to favor rapprochement with USA instead of Japan.
Finishing all Ending Japan Embargo focus tree.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/2b079744-cc2f-46e0-b95b-956196687beb)

![Image_2](https://github.com/user-attachments/assets/e9ef8978-02bc-4b12-9867-2bfe61e5a964)

**Comment by runelead00** [comment]
Fixed in Dev Build
