### ISSUE TITLE
GER - Secrets Wide Open event has no event picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3603]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The 'Secrets Wide Open' event has no event picture added.

### Steps to reproduce / Cause of the issue

1. Speer's Germany won the German Civil War.
2. RND flavor event.

### Expected behaviour

Forgot to add event picture.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/324c303c-8bfa-43cb-a2bc-91e6f8bb4ca2)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
