### ISSUE TITLE
GER - Message from the Aryan Brotherhood event has no event picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3604]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The 'Message from the Aryan Brotherhood' event has no event picture added.

### Steps to reproduce / Cause of the issue

1. Aryan Brotherhood reunites West Russia.
2. Hyperborea influence is higher in Aryan Brotherhood.

### Expected behaviour

Forgot to add event picture.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/fd861355-ac27-4e6d-a3bd-9e77dba8b879)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
