### ISSUE TITLE
levant leader name typo

### ISSUE THREAD

**Issue by stocazz0o** [TNODevs/TNO-Bug-Tracker#3606]
### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### List the loc issues below

The Gov. of the Levant leader's last name is misspelled as it reads Carlo Alberta dalla Chiesa instead of Carlo Alberto dalla Chiesa.
![Immagine 2024-09-11 200753](https://github.com/user-attachments/assets/017c0d27-3ed9-4862-bb0c-fce0a56371e3)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
