### ISSUE TITLE
PHI Tags - United Republic of The Philippines

### ISSUE THREAD

**Issue by ThePikminCaptain** [TNODevs/TNO-Bug-Tracker#3607]
### HOI4 version

1.14.8

### TNO version

1.6.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

After the Reconstuction, have the coalition government of the Philippines be renamed to United Republic of the Philippines

### Justifications

Coalition Government of the Philippines is a stupid name to have after the reconstruction

**Comment by Marok132** [comment]
Didn't you suggest it before?
