### ISSUE TITLE
IME - Beirut Localization bug

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#3608]
### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### List the loc issues below

![image](https://github.com/user-attachments/assets/61593130-193b-4e21-8f5b-54b53ba6d2a2)

### Additional information

i will continue writing the full versions of hoi4 and tno
it makes my brain feel good
you cannot stop me

**Comment by runelead00** [comment]
Fixed in Dev Build
