### ISSUE TITLE
State GDP question

### ISSUE THREAD

**Issue by MarkGCom** [TNODevs/TNO-Bug-Tracker#3609]
### HOI4 version

yes

### TNO version

yes

### Describe your suggestion

Hello, I would like to ask you guys a question. Would you guys tell me in which file to set regional state GDP Proportionality. For example like a country GDP is set 10M, where do I achieve that like  state 206 is set 7M and state 208 is set 3M. I need help and will thanks so m

### Justifications

really need a help please.

**Comment by runelead00** [comment]
Not the place to ask questions, ask on the discord or reddit. But it's based off the generate_state_gdps effect based off state_category and buildings on game start

**Comment by MarkGCom** [comment]
sorry I can't find out. I mean, Speer Germany ruling Reunion, Mauritius, Channel Isles and 94 state in Norway's GDP grows too high and much GDP growth are distributed to those states and I try to fix but I done know In which file. Like the way canada ruling oversea territories states GDP are distributed so low, would you tell me where I can fix?
