### ISSUE TITLE
WRRF- wrong focus tooltip

### ISSUE THREAD

**Issue by dym4201984** [TNODevs/TNO-Bug-Tracker#361]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?

**Longer Description of Issue:**
In Tukh's regional military tree: Set an Example has the wrong tooltip and Make an Example has a broken one

**Steps to Reproduce/Cause Issue:**

1. Can be found in Tukhachevsky's military tree

**Comment by runelead00** [comment]
Fixed in Dev Build
