### ISSUE TITLE
Brazil - Custom Country Path Setting not Working

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#3610]
### Operating System

Windows 10

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

For the custom country paths for Brazil, one of them is about whether the Hardliners or Sorbonnes are able to take control and determine Brazil's direction after the 100 days crisis coup. As seen in the first image, the prerequisites state that only the coup path needed to happen for this path setting to matter.
I had set the path for the coup to occur, and for the hardliners to take control. However, as seen in the second image, this did not happen, either because the custom country path no longer works, or there is a hidden factor or prerequisite that is not indicated on the setting.

### Steps to reproduce / Cause of the issue

1. Set the setting for "Brazil - The Junta's Future" in the custom country path setting to "Hardliners Triumph."
2. Play through a game normally, until May of 1965.
3. The event indicating the hardliners lost will appear.

### Expected behaviour

The hardliners should succeed.

### Screenshots

![image](https://github.com/user-attachments/assets/d6a38c05-d954-4d64-8e65-cacf6449a9b7)
First image, the custom country path for the hardliners.

![image](https://github.com/user-attachments/assets/7a1683e4-9626-47ee-bd76-0b23297a5199)
Second image, indicating the opposite from the chosen setting.

### Additional information

If it is a hidden prerequisite that was not met, then it is not clear, and should be added to setting when you hover over it, like for other setting in the custom country path tab.

**Comment by runelead00** [comment]
Fixed in Dev Build
