### ISSUE TITLE
GER- Sending volonteers to the UK if their civil war takes too long.

### ISSUE THREAD

**Issue by timtimou** [TNODevs/TNO-Bug-Tracker#3612]
### HOI4 version

1.14.8

### TNO version

v.1.5.0d

### Which major expansions do you NOT have?

MTG, AAT

### Describe your suggestion

Germany should be able to send volonteers to the United Kingdom if the British Civil war outlast the German civil war.

### Justifications

Because Germany can reclaim Reichkommisariats in a ongoing civil war (Ostland, Ukraine), it should be able to help Britain at least on a limited scale.

### Screenshots

![20240922151736_1](https://github.com/user-attachments/assets/eeb3f1be-1f7e-4554-94d1-d166de948f00)

**Comment by runelead00** [comment]
We're not adding this, volunteers would completely imbalance the conflict and make the Channel Crisis proxy almost entirely irrelevant, and from a lore-prespective Germany is going to focus its forces to reclaiming and protecting the RKs in Europe and Africa
