### ISSUE TITLE
CLL - No Flag Change  After Communists prevails during Deadlock (CLL_post_war.3)

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3614]
### Operating System

Windows 10

### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Deadlock happens and communists overthrow gaitanistas, they conitinue to use a pre-civil war flag. I'm not certain sure it's intened.

### Steps to reproduce / Cause of the issue

1. The Colombian Civil War is triggered.
2.  Unión Revolucionaria de Colombia prevails.
3. The Deadlock happens.
4. Communists overthrow gaitanistas.

### Expected behaviour

Idk.

### Screenshots

![image](https://github.com/user-attachments/assets/e90e8146-296d-41c0-ad9e-f39c54f2cd20)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thank you.
