### ISSUE TITLE
EQG - Missing Long Country Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3615]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/6ac43c46-1f5a-4aee-b9ab-053f0a9539be)

**Comment by runelead00** [comment]
Not all countries are going to have a different long name from their short name, do not assume the short and long names being the same is a bug
However, this one wass an actual issue and was intended to get a proper long name for Iberia facelift
