### ISSUE TITLE
FUK - Missing Communist Party Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3619]
### HOI4 version

1.14.7

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

There is not a name for the communist party in FUK tag.
![image](https://github.com/user-attachments/assets/100e97d2-ad8b-4872-b54a-4595f195482c)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thank you.
