### ISSUE TITLE
Goering gives Ksyanevich a random city in Norway

### ISSUE THREAD

**Issue by dym4201984** [TNODevs/TNO-Bug-Tracker#362]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?

**Longer Description of Issue:**
When Goering conquers Ostland, he gives some of it to Belarus and Estonia. Belarus receives the city of Nordstern for no discernable reason. (Perhaps this is explained in game, I wasn't playing Goering)

The states given out also look a little funky, but maybe that's intended.

**Steps to Reproduce/Cause Issue:**

1. Play Goering and annex Ostland.

2. Give the collaborators land.

**Screenshots:**
![image](https://user-images.githubusercontent.com/95279781/144020918-45216f92-a3e0-4aa8-9649-6939a0aae719.png)
![image](https://user-images.githubusercontent.com/95279781/144021153-83823ea9-f85f-4417-b52f-5b95c8d2459a.png)

**Comment by runelead00** [comment]
Fixed on Dev Build
