### ISSUE TITLE
Ukraine - Breadbasket gives too much development

### ISSUE THREAD

**Issue by BigComp** [TNODevs/TNO-Bug-Tracker#3620]
### Operating System

Windows 11

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Two of the decisions in the Development Tab from the perspective of the RK, Mechanize Farms and Invest in Industrial Development, claim to give 5 and 10 development respectively. In reality, they give 3 times that amount, being 15 and 30 development.

### Steps to reproduce / Cause of the issue

1. Play Reichskommissariat Ukraine
2. Open up the Breadbasket GUI
3. Click one of two decisions in the development tab (Mechanize Farms/Invest in Industrial Development)

### Expected behaviour

The decisions should give 5 and 10 development respectively

**Comment by runelead00** [comment]
Fixed in Dev Build
