### ISSUE TITLE
FRD can't be defeated

### ISSUE THREAD

**Issue by MarkGCom** [TNODevs/TNO-Bug-Tracker#3622]
### Operating System

1

### HOI4 version

1

### TNO version

1

### Do you have other mods in use?

0

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

during FRA civil war, the war still going after FFR's faction member FRD capitulate while leads FRA is unable to end the civil war by defeating FRD.

### Steps to reproduce / Cause of the issue

checks on action white peace file FRD can't be defeated when in a faction 

### Expected behaviour

FFR lose when FRD capitulate

**Comment by runelead00** [comment]
No save file for peace deal issue, closed for lack of testable material
