### ISSUE TITLE
RFI, BRP, URP, URP, OKB, economy bug

### ISSUE THREAD

**Issue by MarkGCom** [TNODevs/TNO-Bug-Tracker#3623]
### Operating System

0

### HOI4 version

0

### TNO version

0

### Do you have other mods in use?

0

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

when those tag appears, their controlled state's GDP will down to 0. Fix it please

### Steps to reproduce / Cause of the issue

0

### Expected behaviour

checks those tag's file in history/country and adds TNO_startup_nation

**Comment by MarkGCom** [comment]
by the way, MAC I miss above

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by MarkGCom** [comment]
> Fixed in Dev Build.

ARP yet.
