### ISSUE TITLE
OKB's controlled state and victory points error

### ISSUE THREAD

**Issue by MarkGCom** [TNODevs/TNO-Bug-Tracker#3624]
### Operating System

1

### HOI4 version

1

### TNO version

1

### Do you have other mods in use?

0

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

OKB's controlled state and victory points still use Russian name instead of German name. fix please

### Steps to reproduce / Cause of the issue

0

### Expected behaviour

checks and fix in common/script_effect britian and pakt state control file

**Comment by Stormeagle449** [comment]
Which state and victory points are you talking about? Please clarify.

**Comment by MarkGCom** [comment]
> Which state and victory points are you talking about? Please clarify.

OKB appear to controll 195, during speer slave riot. and control ingria and a state near by ingria which i forgot by decision, all should use german name.

**Comment by Stormeagle449** [comment]
I have fixed state 195 but I can't help you for the other state unless you can give me the exact info.

**Comment by MarkGCom** [comment]
> I have fixed state 195 but I can't help you for the other state unless you can give me the exact info.

I mean there are 2 states neighboring 195 controlled by MCW on startup might be controlled by OKB should use German name which I forget their number but maybe you checks in game.
