### ISSUE TITLE
Spanish civil war never end.

### ISSUE THREAD

**Issue by MarkGCom** [TNODevs/TNO-Bug-Tracker#3626]
### Operating System

0

### HOI4 version

0

### TNO version

1

### Do you have other mods in use?

0

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Spanish civil war never end because it will be white peace after Spanish country(like FZL and so on) tags beat Portugese Country tags and then Spanish tags declare Portuguese tags in a while, repeat and repeat.

### Steps to reproduce / Cause of the issue

1

### Expected behaviour

checks common/on_action peace file and fix

**Comment by runelead00** [comment]
No save file for peace deal issue, closed for lack of testable material
