### ISSUE TITLE
SLG GDP is out of normal

### ISSUE THREAD

**Issue by MarkGCom** [TNODevs/TNO-Bug-Tracker#3627]
### Operating System

1

### HOI4 version

1

### TNO version

1

### Do you have other mods in use?

0

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

SLG gdp is so low event out of normal

### Steps to reproduce / Cause of the issue

0

### Expected behaviour

checks on_action set startup country'gdp, SLG is missed

**Comment by Stormeagle449** [comment]
TNO_startup_nation script is already applied to the country, the only reason I can think for why Iberian Algeria's GDP is so low is that its states' GDP isn't high to begin with. If you believe it's abnormally low post a screenshot of Iberian Algeria's GDP and its states.
