### ISSUE TITLE
Pacific state didn't show in Japanese name

### ISSUE THREAD

**Issue by MarkGCom** [TNODevs/TNO-Bug-Tracker#3631]
### Operating System

1

### HOI4 version

1

### TNO version

1

### Do you have other mods in use?

1

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I find a lots of Japanese name of Pacific states in location file, it works in old version but now don't. 

### Steps to reproduce / Cause of the issue

0``

### Expected behaviour

I don't know if whether you guys make it show in English name on purpose but it works in old version.

**Comment by runelead00** [comment]
Pacific is being changed with map rework
