### ISSUE TITLE
Turkmenistan & Bukharan People's Republic - Missing loc for "CA_Turkes_Kenes_Apathy"

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#3632]
### HOI4 version

1.14.9

### TNO version

1.6.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version, custom train research icon submod.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

For the nations of Bukharan Peoples' Soviet Republic and Socialist Republic of Turkemenistan. Both nations are missing loc for the national spirit "CA_Turkes_Kenes_Apathy."
![image](https://github.com/user-attachments/assets/fe5e42fd-31bc-40dd-870d-00586d2f8894)

![image](https://github.com/user-attachments/assets/5b4fab47-7b10-45b9-85b6-bcd0bd0b7790)

### Additional information

While I'm not sure if it is related, the two nations of the Islamic Republic of Talas and the Islamic State of Tajikistan don't have this national spirit whatsoever. Although I am not sure if they are also supposed to be assigned it.
![image](https://github.com/user-attachments/assets/4f54d2ae-6373-4b1d-ac48-e9d2c2853907)

![image](https://github.com/user-attachments/assets/c5ec5991-ea59-49c0-a894-75bea2b6f6ae)

**Comment by runelead00** [comment]
Fixed in Dev Build
