### ISSUE TITLE
KOM - Event "A Friend on the Left" fires after Shafarevich wins elections

### ISSUE THREAD

**Issue by Jackopumpking** [TNODevs/TNO-Bug-Tracker#3633]
### Operating System

windows 11

### HOI4 version

1.14

### TNO version

1.6.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Playing komi, Shafarevich wins the elecetion. A month later, due to the "a friend on the left" events, Vosnezensky is ousted, and Stalina becomes president. This makes Stalina the national leader, and makes one of the advisor slots unfilled. The game fixes itself after completing the first Shafarevich focus tree

### Steps to reproduce / Cause of the issue

play komi
go down the "eyes to the left" path
do the election and relevant events
make the right win
make sure stalina has more influence than mozorov
make sure you start the "a friend on the left" events late enough, by not activating any of the decisions until very close to the election
Choose to call yuri after discovering Zhdanov's spy 
Stalina should take over after the centre ousts Voznesensky, and  she will become the nation's leader

### Expected behaviour

I expected Stalina not to take power, since Shafarevich won the election by a large margin

**Comment by runelead00** [comment]
Fixed in Dev Build
