### ISSUE TITLE
MEX - Add Mexico in Major Nation Buffs 

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3634]
### HOI4 version

1.14.8

### TNO version

1.6.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

To add Mexico in the Major Nation Buffs section.

### Justifications

There are all the playable countries. I do not see any reasons not to add Mexico as well

### Screenshots

![image](https://github.com/user-attachments/assets/8c86f1b4-39d3-4161-9883-8ce4c085c59c)

**Comment by runelead00** [comment]
It's already in the game what

**Comment by Marok132** [comment]
> It's already in the game what

Not in the current version.

**Comment by runelead00** [comment]
oh god you're right, i did it 2 months ago right after the update and didn't realize we hadn't updated since then

**Comment by Marok132** [comment]
> oh god you're right, i did it 2 months ago right after the update and didn't realize we hadn't updated since then

That's okay. Thanks in advance for adding this.
