### ISSUE TITLE
PRC - Mentions western Mongolia in Vasilevsky's Bio

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3635]
### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

In Vasilevsky's Bio still mentions the PRC controls western Mongolia despite it doesn't.
![image](https://github.com/user-attachments/assets/366fcaae-09d2-4a1f-ba1e-855c5b3df836)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Marok132** [comment]
> Fixed in Dev Build.

Thank you.
