### ISSUE TITLE
Map definition error- General

### ISSUE THREAD

**Issue by Basilatari** [TNODevs/TNO-Bug-Tracker#364]
**Questions**

- Operating System: Windows 
- HOI4 Version: 1.11.3 b175
- TNO Version: 1.2.0d (Toolbox Theory) 
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? All (only have base game) 

**Longer Description of Issue:**
The game works fine on others mod like KR and by itself, i only receive this error with tno where after I launch the game, it crashes right before fully loading on startup. I receive an error which says "Some errors are present in the map defition (with typo) and have been logged on to error.log"
**Steps to Reproduce/Cause Issue:**

1. Open Game 

2. Wait and the game crashes with an error 

etc...

**Screenshots:**
![IMG_20211130_145741](https://user-images.githubusercontent.com/95284559/144037401-7479d433-1ce1-442e-8909-8fbab8669c53.jpg)

**Game Saves and Log Files, if possible:**

**Comment by Crazylaika** [comment]
Have this exact same issues, nothing I do seems to fix it. Other mods work fine.

**Comment by runelead00** [comment]
TNO is not compatible with the 1.11 update yet, you need to revert to 1.10.8 to play TNO
