### ISSUE TITLE
IME - Beirut Localization Missing

### ISSUE THREAD

**Issue by IndianaEnjoyer** [TNODevs/TNO-Bug-Tracker#3641]
### Operating System

Windows 10

### HOI4 version

1.14.9

### TNO version

1.6.0

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When using the Endonyms/Native Names mode in the Endonym/Exonym toggle, Beirut's name will appear as VICTORY_POINTS_792_ita if the Levant Government controls Southern Lebanon. This issue does not persist if the state of Southern Lebanon is owned by Lebanon.

### Steps to reproduce / Cause of the issue

1. Switch the Endonym/Exonym Toggle to Endonyms/Native Names
2. Ensure that the Governatoro ile Levante (i know i butchered that spelling but i don't care) owns owns the state of Southern Lebanon
3. Look over at the VP of Beirut

### Expected behaviour

For the toggle to function right, I guess.

### Screenshots

![image](https://github.com/user-attachments/assets/f3ee0445-6ecf-4f24-b94a-95e3ec9a325c)
![image](https://github.com/user-attachments/assets/24058e51-0fc3-44ce-8a3e-2cd2ba7f3de4)

**Comment by Stormeagle449** [comment]
Bug already fixed in Dev Build.
