### ISSUE TITLE
Mexico- War notification window won't close

### ISSUE THREAD

**Issue by Markman675** [TNODevs/TNO-Bug-Tracker#3642]
### Operating System

Winodws 11

### HOI4 version

Bolivar 1.14.5.0917

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT, TOA

### Describe the bug

The war declaration popup window won't go away. The one that says "xyz country has declared war on abc nation" I've tried to hit enter but it won't work. There's no close button either. Also, for some reason, the window is smaller and appears on the right side of the screen, right on the edge dead center. Github won't let me upload files so I can't show you but I can on discord if you'd like. My handle is Markku65

### Steps to reproduce / Cause of the issue

1. Just wait for any nation to declare war on any other country and the war notification will pop up when the News event does. The event goes away when you close it but the notification will not. 

### Expected behaviour

I expected the window to either close on its own or go away when I press enter.

**Comment by runelead00** [comment]
They work the same way as vanilla war notifications, they will go away on their own or you right click to close as the notification tooltip says

**Comment by Markman675** [comment]
I’ve tried right clicking and it did not work. I waited two minutes and it
wouldn’t disappear. Two more windows popped up and they also wouldn’t
close.
