### ISSUE TITLE
KOM - Ethic Cleansing

### ISSUE THREAD

**Issue by Jackopumpking** [TNODevs/TNO-Bug-Tracker#3645]
### HOI4 version

1.14

### TNO version

1.6.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/5eaeba9b-d430-4184-b3da-42c5c4ee526e)
![image](https://github.com/user-attachments/assets/7bf1e6c6-c3fe-4d3c-b441-bf901ca15ecb)
![image](https://github.com/user-attachments/assets/ea9cc3e5-1760-4ba7-902a-d617b1566034)

It says "ethic cleansing" instead of "ethnic cleansing"

**Comment by runelead00** [comment]
Fixed in Dev Build
