### ISSUE TITLE
Großafrikanischer Reichsstaat - Random Crash in mid 1966

### ISSUE THREAD

**Issue by DomKe1205** [TNODevs/TNO-Bug-Tracker#365]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: v1.2.0d “Toolbox Theory”
- Any other mods in use: (Almost) No Experience for Division Design, Precise Buffs, Radio TNO, Recall Volunteers, State Transfer Tool, Second West Russian War, TNO Nuclear War Game rule, TNO Lullabies of Europe, Twelve Support Company
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all except for No Step Back

**Longer Description of Issue:**

I was playing as Großafrikanischer Reichsstaat when the game randomly crashed mid-1966 and continues to crash on reloading the save game.

I do have found some interesting warnings in the error.log file contained in the crashes folder.

[gui.cpp:861]: Undefined GUI_TYPE: eastern_front_stations_entry - This will most likely crash the game
[gui.cpp:861]: Undefined GUI_TYPE: _stations_entry - This will most likely crash the game

**Screenshots:**
![Screenshot (57)](https://user-images.githubusercontent.com/70488023/144072856-efe8fd56-b27c-4be7-90d9-ec8fc9c535c8.png)

**Game Saves and Log Files, if possible:**
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7626758/error.log)
[hoi4_20211130_144815.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7626764/hoi4_20211130_144815.zip)

**Comment by DomKe1205** [comment]
I accidentally posted before adding a screenshot and the logfile, so I post it here.

Screenshot:
![Screenshot (57)](https://user-images.githubusercontent.com/70488023/144071267-665be1ef-adaa-4146-ba50-52e988a0a6f9.png)

Log Files:
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7626698/error.log)
[hoi4_20211130_144815.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7626701/hoi4_20211130_144815.zip)

**Comment by masterbobli** [comment]
I am pretty sure that these entry isn't the issue that crashes the game, and I am unable to find anything wrong in the files you provided. Is it possible to provide a save game before the crash or the game.log the moment it crashes?

**Comment by DomKe1205** [comment]
Here is the game.log file. There's not a lot in there, because the game crashes just seconds after pressing play.

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7641984/game.log)

Here is the save game:

[crashingsavegame.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7641995/crashingsavegame.zip)
