### ISSUE TITLE
ICE - Some national spirits used incorrect name.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3652]
### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Some Icelandic national spirits used a title "the Republic of Iceland" despite its actual name is just Iceland, not the Republic of Iceland. 
![image](https://github.com/user-attachments/assets/8c9f9792-07d1-496a-b98e-e036234e82a0)

- [x] 1. 
![image](https://github.com/user-attachments/assets/097f24d8-b57e-4c3d-9e27-1ba8a0e0d182)
- [x] 2. 
![image](https://github.com/user-attachments/assets/79cf54e2-30dd-4392-b75f-36b355e2c64c)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Marok132** [comment]
> Fixed in Dev Build.

Thank you.
