### ISSUE TITLE
DOM - "No Election" for the Democratic Dominican Republic

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3653]
### Operating System

Windows 10

### HOI4 version

1.14.9

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Dominican Republic holds elections and elect some guy, it's set no elections,

### Steps to reproduce / Cause of the issue

1. The Legion defeats fascists.
2. The communist coup is failed.
3. Wait for the 1964, 1966 and 1970 elections.

### Expected behaviour

There should not be "no electons" for the Democractic Dominican Republic.

### Screenshots

![image](https://github.com/user-attachments/assets/3b60bbb2-023b-4ee5-9b10-9d79cc1044d4)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Marok132** [comment]
> Fixed in Dev Build.

Thank you.
