### ISSUE TITLE
IBR - Portugal does not take São Tomé and Príncipe during the Iberian collapse. 

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3658]
### Operating System

Windows 10

### HOI4 version

1.14.9

### TNO version

1.6.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Iberian collapse begins and Portugal becomes independent, it won't take the São Tomé and Príncipe islands. 

### Steps to reproduce / Cause of the issue

The Iberian Wars must fire.

### Expected behaviour

the São Tomé and Príncipe islands should be part of Portugal.

### Screenshots

![image](https://github.com/user-attachments/assets/a08ec440-7a40-4f00-babc-216d5a963483)
![image](https://github.com/user-attachments/assets/f41705e5-f1ba-45c8-9572-956d7fa3afd5)

**Comment by runelead00** [comment]
Breakaway Portugal does not have power projection to take control of its former overseas territories + it declares independence almost immediately after the Iberian Wars start

**Comment by Marok132** [comment]
> Breakaway Portugal does not have power projection to take control of its former overseas territories + it declares independence almost immediately after the Iberian Wars start

OK.
