### ISSUE TITLE
Zhdanov's Komi - MPLA steel trade bug

### ISSUE THREAD

**Issue by Vityviktor** [TNODevs/TNO-Bug-Tracker#366]
**Questions**

- Operating System: Windows 11
- HOI4 Version: 1.10.08
- TNO Version: 1.2.0d
- Any other mods in use: TNO radio.
- Were you using Steam? Yes
- Which expansions do you NOT have? "No step back"

**Longer Description of Issue:**

Playing as Zhdanov's Federation of Soviet Socialist Republics I suddenly got 450 production units, 407 of them being "from trade". Turns out that the MPLA (who I was supporting with volunteers, not sure if related) was importing 4010 steel from me. It lasted for a few days, then it was gone, and then it came back again. They're not in the Comintern nor the COMECON.

**Steps to Reproduce/Cause Issue:**

1. Play as Zhdanov.

2. Wait for the Reichstaat to collapse, and a few years later for the MPLA to rise up.

3. Send them volunteers?

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/95356445/144239198-bc086919-bc70-4973-a9ed-a9b9b6091d63.png)

![image](https://user-images.githubusercontent.com/95356445/144239235-81b9f969-4bc0-46b8-ad3c-6150c3246a60.png)

**Comment by runelead00** [comment]
Should be fixed in current release
