### ISSUE TITLE
USA - Change Parameters of Americar

### ISSUE THREAD

**Issue by BigComp** [TNODevs/TNO-Bug-Tracker#3662]
### HOI4 version

1.14.10

### TNO version

1.6.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Change the parameters of the Americar so that the requirements are much easier to get the various versions of the car.

### Justifications

As far as I can tell, it is literally impossible to get the GM Century Cruiser (the best car). I even went into the files and found out that the requirements are way too much. Because of how the Americar works, you can only select decisions that improve your stats for the duration of the focus (30 or 35 days). There are multiple decisions, including one that strengthens the other decisions that you take. Even if you min max everything (take the decision buff first, and then take nothing but the best decisions) you will not be able to get close to the requirements for the GM Century Cruiser. The decisions only give ~5% increase to the various stats, whereas apathy increases from a random value between 7 and 14%.
The first screenshot is the requirements for the GM Century Cruiser (being 150% and 120% for industry disdain and energy woes respectively). The next screenshots are demonstrations of the maximum amount of stats I was able to get during the duration of the focus. As you can see, it is not even remotely close to the requirements (21.9% vs 150% and 41.7% vs 120%).
I would recommend shortening the length of the decisions, which are currently 6 days, decreasing the requirements for all of the cars, and strengthening the increase to stats in all of the decisions.

### Screenshots

![image](https://github.com/user-attachments/assets/e7649c8c-7310-4d2e-bd0d-5f5ac740ff70)
![20241029150844_1](https://github.com/user-attachments/assets/f337600f-240e-4ab9-b7ee-07e76a6fd130)
![20241029150852_1](https://github.com/user-attachments/assets/feee93a0-4a8e-43c0-a63e-f6ad7009bb3b)

**Comment by runelead00** [comment]
values are automatically increased by 1 at the end of the survey, these values are not impossible to achieve
