### ISSUE TITLE
Mexico

### ISSUE THREAD

**Issue by BreadConqueror** [TNODevs/TNO-Bug-Tracker#3666]
### Operating System

Windows 11

### HOI4 version

1.14.8

### TNO version

1.6.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

There is seemingly no content for the CDMX metro project. It does not unlock even when Uruchurtu is fired/sides with Salinas, and there is no associated event chain in the game files. The event for firing Uruchurtu as Madrazo also seems to be coded to fire itself again 54 days later. Not sure if an oversight or intentional, though disappointing as a player and infrastructure lover.

### Steps to reproduce / Cause of the issue

Reproducible in any Mexico playthrough, checkable through game files

### Expected behaviour

Unlock CDMX Metro Project

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
