### ISSUE TITLE
KMC - Add missing research

### ISSUE THREAD

**Issue by Th3Gam3Oli** [TNODevs/TNO-Bug-Tracker#3667]
### HOI4 version

1.14.10

### TNO version

1.6.0

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Add as researched the following:
Radio Detection (Engineering)
Early and Basic AA (Military Engineering)

### Justifications

Radio tech is just skipped in the tech tree.
The AA tech are used in the Orfey (Early AA) and Gnevnyy (I think there is a typo too in the design name) (Basic AA) class destroyer's designs without it being researched.

### Screenshots

![Radio](https://github.com/user-attachments/assets/fffe9ede-a72d-4776-84ce-02463c063e3d)
![AA](https://github.com/user-attachments/assets/ed480fd8-782f-4a52-bd3e-abc221594e9e)
![DD1](https://github.com/user-attachments/assets/24ab556f-1ba8-4c14-84eb-79284ee4f670)
![DD2](https://github.com/user-attachments/assets/7b6639fc-2d59-4a4c-a14d-46a3ce6c0f62)

### Additional information

I know it's a country with no content but I think a little polish won't harm :)

**Comment by Marok132** [comment]
I'm not sure it's so necessary because Kamchatka is an unplayable tag.

**Comment by Stormeagle449** [comment]
Accepted.
