### ISSUE TITLE
USA - FBI Description Missing

### ISSUE THREAD

**Issue by BigComp** [TNODevs/TNO-Bug-Tracker#3668]
### Operating System

Windows 11

### HOI4 version

1.14.10

### TNO version

1.6.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

The FBI description in the intelligence tab doesn't have any loc

### Steps to reproduce / Cause of the issue

1. Play USA
2. Open Foreign Policy GUI
3. Open Intelligence Tab
4. Click on any of the American regions
5. Hover over the info box

### Expected behaviour

There is supposed to be a little description of the FBI, like with the CIA

### Screenshots

![20241107163719_1](https://github.com/user-attachments/assets/06929787-072c-4813-a89b-59ec054f99c2)

**Comment by runelead00** [comment]
Fixed in Dev Build
