### ISSUE TITLE
Japan - Congolese Civil War Decision-GUI not disappearing, causing confusion and slowdown

### ISSUE THREAD

**Issue by agscaesar** [TNODevs/TNO-Bug-Tracker#367]
**Questions**

- Operating System: Windows 10 Pro
- HOI4 Version: 1.10.8
- TNO Version: v1.2.0d - Toolbox Theory
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
When defeating all other contenders as japan in the CCW (azandeland) the event will play but the civil war GUI doesn't go away and Azandeland never fully joins the sphere. This happened with kaya japan.

**Steps to Reproduce/Cause Issue:**

1. Play as Japan, and start CCW

2. Win the CCW with azandeland

3. hilarity ensues  (bug should be seen)

**Comment by ModdingAccount** [comment]
Fixed in dev build.
