### ISSUE TITLE
Yunnan (National Protection Army) - Game crashes after a certain point

### ISSUE THREAD

**Issue by NitrateStar** [TNODevs/TNO-Bug-Tracker#3673]
### Operating System

Windows 11

### HOI4 version

1.15.0

### TNO version

1.6.0

### Do you have other mods in use?

The Moe Order, anime music, radio_tno, tno: songs from the future

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/user-attachments/files/17787191/error.log)
It says it doesn't support the type of file for save games, so I hope the crash log is enough.

### Describe the crash

After capitulating the RoC as the NPA, the game crashes after I capitulate someone else (except Guangdong). I would also like to mention that I played as the NPA a few months ago (pre Mexico update is all I can remember), and the game also crashed then, even without capitulating anyone.
 I tried launching the save game without any submods (except anime music) and had the same problem.

### Steps to reproduce / Cause of the crash

1. Open the game
2. Select ,,Yunnan"
3. Play normally
4. Secure Sichuan
5. Take Nanjing
6. Capitulate Guangdong
7. Capitulate the North China Political Council
8. The game crashes

### Additional information

Btw the on-map decisons (both in moe and vanilla) (such as ,,take Nanjing") have the error graphic, and I have zero clue how the Sichuan minigame works lol.
I have just created a Github account specifically for this, so if I did something stupid, please politely tell me.
I also don't have Götterdämmerung, but it isn't in the choices. You also don't have Battle for the Bosporus.

**Comment by Noreaus** [comment]
Adding to this that I also experience this crash post-Far From God using the same steps as listed, when the NCPC capitulates the game crashes. I *do* have all expansions.

**Comment by runelead00** [comment]
Fixed in Dev Build
