### ISSUE TITLE
USA - 'CIA/FBI Begins Training New Operative' event uses the wrong picture again

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3674]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Same as the #3043 bug report, the event uses the German intelligence event picture because of the appearance of Adolf Hitler picture.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Recruit new operative in TNO's intelligence tab.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/2bf4620e-4922-481d-ba6c-9d3f7c5baa85)

### Additional information

The response from the #3043 bug report says "**we don't use that event anymore**" but that event is use now again.

**Comment by Stormeagle449** [comment]
Fixed in Dev Build (for real this time).
