### ISSUE TITLE
USA - Endless War Support Loss

### ISSUE THREAD

**Issue by the-magnani** [TNODevs/TNO-Bug-Tracker#3679]
### Operating System

Windows 11

### HOI4 version

1.15

### TNO version

v1.6.0a “So Far From God”

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

Playing as the United States. Won the Haiti proxy. Am still getting the -1 stability and -2.5 war support monthly. 

### Steps to reproduce / Cause of the issue

1. Go to HOI4 and open TNO.
2. Click on the US and play as them. Wait until Haiti conflict. 
3. Scroll down to click all the buttons and win the proxy (getting an event that tells you you won and increases your political party support and causes the proxy screen to vanish). 
4. See the error as your war support and stability continues to decrease as though the war has not ended. 

### Expected behaviour

Continuing to lose political party support, war support, stability

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
