### ISSUE TITLE
USA - The PPLN will rise up loc is not line break in 'The Status of the War' decision timer

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3682]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_game.zip](https://github.com/user-attachments/files/17801458/USA_game.zip)

### Describe the bug

In the decision timer effects of The Status of the War, the loc about the PPLN will rise up is not line break.   

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. The Haitian Civil War triggers.
3. The PPLN is begun to rise up that shows in The Status of the War decision timer.

### Expected behaviour

Forgot to add line break.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/03ce0d94-d503-4916-98d8-c3e1d1f6eb95)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
