### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by ruegaga** [TNODevs/TNO-Bug-Tracker#3694]
### Operating System

Windows 11

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/user-attachments/files/17873984/error.log)
[game.log](https://github.com/user-attachments/files/17873985/game.log)

### Describe the bug

Some countries do not have Focus Tree, especially the country I play, Indonesia. When opened, it only displays an empty box. Plus, when you first play as a country, the national overview column (if I'm not mistaken) also doesn't display anything. While in countries like Germany or maybe other big countries, they have it.

### Steps to reproduce / Cause of the issue

I don't get it what this mean

### Expected behaviour

I except that there is not such bug to the mod

### Screenshots

Sorry, i dont know why but i cannot capture the screenshot. Whenever i want to screenshot, the game close to window (not crash).

**Comment by Marok132** [comment]
They do not have focuses because there isn't full content yet. Wait for next updates, please.

**Comment by ruegaga** [comment]
Oh i see. Thx for the replies.

Pada Min, 24 Nov 2024 pukul 17.00 runelead00 ***@***.***>
menulis:
