### ISSUE TITLE
USA - Change the event picture for 'The Inauguration of Michael Harrington' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3695]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the event picture of 'The Inauguration of Michael Harrington' event should be changed to Harringtons election post picture.

### Justifications

The event picture for 'The Inauguration of Michael Harrington' event, however, uses the generic people picture instead of uses the Harrington's voting post or any Harrington's voting image.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/16f71f08-c86e-4141-8e19-a9742cb03696)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
