### ISSUE TITLE
Yunnan/Guizhou (YUN/GUZ) - Two Different Lu Han Portraits

### ISSUE THREAD

**Issue by runelead00** [TNODevs/TNO-Bug-Tracker#37]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?  None

**Longer Description of Issue:**
Following Lu Han's removing He Yingqin from power via the focus "A Man's Home Is His Castle", Lu Han becomes leader of Guizhou until the two nations are formally unified. During this time, the two nations use two different portraits of Lu Han with Guizhou's portrait clearly younger than Yunnan's portrait

**Steps to Reproduce/Cause Issue:**

1. As Yunnan, follow the first focus tree down the Evict He Yingqin path up until focus A Man's Home Is His Castle

2. At the completion of that focus, Guizhou will get the different Lu Han portait

**Screenshots:**
![LuHan (1)](https://user-images.githubusercontent.com/74165171/128589847-01490fbd-d7a5-483a-9761-84bf4db08130.jpg)
![LuHan (2)](https://user-images.githubusercontent.com/74165171/128589849-d6343e51-a608-4b22-aa16-25f782215120.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build.
