### ISSUE TITLE
Sverdlovsk - Error in Description of Rokossovsky

### ISSUE THREAD

**Issue by kappa1961** [TNODevs/TNO-Bug-Tracker#370]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: N/A
- Were you using Steam? Yes
- Which expansions do you NOT have?

Allied Speeches/Eastern Front Music Pack/Eastern Front Planes Pack
**Longer Description of Issue:**
In the description of Konstantin Rokossovsky, in the thirteenth line of text of the second paragraph, instead of saying Sverdlovsk, it says "[Get_RUS_Yekaterinburg_Or_Sverdlovsk]

**Steps to Reproduce/Cause Issue:**

1.  start a new game as Sverdlovsk

2. Read the description of Konstantin Rokossovsky

**Screenshots:**
![image](https://user-images.githubusercontent.com/64776622/144384651-de938376-4207-4852-a64e-717bb27ed29a.png)

**Comment by runelead00** [comment]
Fixed in Current Release
