### ISSUE TITLE
CUB - Not joining the OFN

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3700]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Cuba is supposed to join the OFN when the USA supports the Caribbean Legion during the ceasefire but it does not do it even after  the Legion victory. It worked before the 1.6.0a hotfix so I think it's a bug.

### Steps to reproduce / Cause of the issue

![image](https://github.com/user-attachments/assets/ee6dfe7e-290f-43df-93bc-d103da0f7df8)
![image](https://github.com/user-attachments/assets/ac5efc7e-a06d-4ee8-8392-d87cd4f4bd69)
![image](https://github.com/user-attachments/assets/a39026ff-e19d-4a37-bd2d-9e8203b790a0)

### Expected behaviour

Cuba should join the OFN if the USA supports the Legion.

### Screenshots

![image](https://github.com/user-attachments/assets/42c24b7e-f198-4d09-865d-98de580acb27)
![image](https://github.com/user-attachments/assets/ff88b82c-fbc1-4eef-b286-2cf26b6b8f77)

**Comment by runelead00** [comment]
Cuba only joins the OFN if the ceasefire collapses and the Legion wins

**Comment by Marok132** [comment]
> Cuba only joins the OFN if the ceasefire collapses and the Legion wins

Alright. Thank you.

**Comment by Marok132** [comment]
> Cuba only joins the OFN if the ceasefire collapses and the Legion wins

I've just tested it and it doesn't work yet. I should say that part of the Caribbean gamerules are broken for some reasons (I've reported them in my new reports).

**Comment by Marok132** [comment]
> > Cuba only joins the OFN if the ceasefire collapses and the Legion wins
> 
> I've just tested it and it doesn't work yet. I should say that part of the Caribbean gamerules are broken for some reasons (I've reported them in my new reports).

I guess the newest patch brought some new bugs with their code...
