### ISSUE TITLE
IBR - Missing icon in the decision "Invest in the Dominican Republic"

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3701]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

![image](https://github.com/user-attachments/assets/dbbd8582-5f46-4da1-9982-8a20a564a491)

### Steps to reproduce / Cause of the issue

Should Iberia be a democracy.

### Expected behaviour

It should have an icon.

**Comment by runelead00** [comment]
Fixed in Dev Build
