### ISSUE TITLE
USA - Change the event picture of 'The Acceptance Speech' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3704]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the event picture of 'The Acceptance Speech' event should be changed to a picture of 'Michael Harrington speech' or 'a president speech to the crowd'. 

### Justifications

Because 'The Acceptance Speech' event uses the picture of 'signing of something with the preventatives' and this event is about president-elect Harrington's speech. So, a picture or image of 'The Acceptance Speech' event should be changed to make it clearer. 

### Screenshots

![Image_1](https://github.com/user-attachments/assets/6074eec9-5864-461c-bf64-52195c177fd9)

**Comment by Stormeagle449** [comment]
Accepted.
