### ISSUE TITLE
ENgland/HMMLR - Fail every operation even at 90% success chance.

### ISSUE THREAD

**Issue by ClassicSwede** [TNODevs/TNO-Bug-Tracker#371]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.10.8
- TNO Version: Most recent
- Any other mods in use: Music mods. 
- Were you using Steam? Yes
- Which expansions do you NOT have? Have all.

**Longer Description of Issue:**
I have been playing the HMMLR route, I succeeded on my first operation which is operation STOCK. Moving on though I have been unable to succeed in operations even when the odds are ridicolously in my favour. Most prevalent is operation "look up" which I have been attempting to do after STOCK, I have had it (depending on the guns) at either 92% success chance or at lowest 84%, I have savescummed 6 times and let time pass, done other stuff etc and waited an extra month because frustratingly it has failed every single time despite these numbers; this can't possibly be intentional.
**Steps to Reproduce/Cause Issue:**

1. Play HMMLR till "look up" is available, having done Stock before. 

2. With a high control and low stability in lancashire, try the operation.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Works as of current dev build
