### ISSUE TITLE
USA - No add "s" for plural sentences in the 'For the American Worker' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3710]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

1.  There are no add "s" after the word "worker" in the 'For the American Worker' event because this event talks about 'for the workers and people' which is plural. So, It should be "Workers" for the event title and "workers" for the event text. 
![Image_1](https://github.com/user-attachments/assets/2ca7b7e8-83a5-45b1-b474-c7b0de13de4b)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
