### ISSUE TITLE
USA - Change the event picture from the 'Slaughterhouse-Five' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3711]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the event picture from the 'Slaughterhouse-Five' event should be changed to 'Slaughterhouse-Five Book Cover' instead of using the event picture of the 'meeting or conference of some sort'. 

### Justifications

Because this event talks about the story from the Slaughterhouse-Five Book and written by Kurt Vonnegut. So, the picture from this event should be changed. 

### Screenshots

![Image_1](https://github.com/user-attachments/assets/8f84fd8e-15fa-474c-b7c3-d4bea9e1945e)

**Comment by Stormeagle449** [comment]
Accepted.
