### ISSUE TITLE
Serov's Komi - No icon in the event "Nekro"

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3712]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the event "Nekro" is used a placeholder picture.

### Steps to reproduce / Cause of the issue

To put some picture in the event, not the placeholder one.

### Expected behaviour

The event should not use a placeholder picture.

### Screenshots

![image](https://github.com/user-attachments/assets/1f2dd1cd-ef63-46c1-9d40-8d6c98a17539)

**Comment by runelead00** [comment]
Fixed in Dev Build
