### ISSUE TITLE
Yunnan - Crash After Finishing the Vacation

### ISSUE THREAD

**Issue by jhefhfh** [TNODevs/TNO-Bug-Tracker#3714]
### Operating System

Windows 11

### HOI4 version

1.15.1.f089(c86b)

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT, TOA

### Files

[game.log](https://github.com/user-attachments/files/17893339/game.log)
[error.log](https://github.com/user-attachments/files/17893340/error.log)

### Describe the crash

After finishing Lu Han's vacation and Long Yun step up, I couldn't even finish one focus before crashing, and there were times that I couldn't even finish the vacation before crashing. I tried multiple times but it kept crashing. 

### Steps to reproduce / Cause of the crash

Wait, crash. 
The date is Jan 24. 

### Screenshots

https://github.com/user-attachments/assets/0b39c5af-f2ae-4117-941b-58e670eb3da3

**Comment by jhefhfh** [comment]
by reading the logs, it seems the problem is of Red Finland...?

**Comment by runelead00** [comment]
Fixed in Dev Build, it seems PDX changed something about template inheritance when spawning new country that caused a previous minor error to become a CTD
