### ISSUE TITLE
USA - Change the photo event of the 'Money Talks' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3715]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest the photo event of the 'Money Talks' event should be changed to 'Wall Street Journal publication papers or something Wall Street Journal newspapers' event photo. 

### Justifications

The 'Money Talks' event describes that the pro-Bennett people attacked Harrington's undo Bennett's administration through media. So, the photo event of the 'Money Talks' event should be changed instead of using the photo of 'meetings or conference of some sort'. 

### Screenshots

![Image_1](https://github.com/user-attachments/assets/4a147b81-504a-4eea-8727-f20dcdc249e7)

**Comment by Stormeagle449** [comment]
Accepted.
