### ISSUE TITLE
BLZ - Missing Leader when Belize becomes independent

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3716]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Belize becomes independent from the United Kingdom, it loses his leader and it becomes  a client state of Canada suddenly despite it's supposed to be the British one.

### Steps to reproduce / Cause of the issue

1. The HMMLR prevails in Britain.
2. The British monarchy is restored
3. The UK gets Belize.
4. To wait when Belize becomes independent.

### Expected behaviour

It should not lose its leader.

### Screenshots

![image](https://github.com/user-attachments/assets/48faf640-c0d5-481f-9b6d-3f0821d60900)

![image](https://github.com/user-attachments/assets/90397d15-0400-4a0f-a3c9-db4470737f31)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thank you so much.
