### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by jhefhfh** [TNODevs/TNO-Bug-Tracker#3718]
### Operating System

Windows 11

### HOI4 version

1.15.1.f089(c86b)

### TNO version

1.6.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA, AAT, TOA

### Files

[error.log](https://github.com/user-attachments/files/17893955/error.log)

[game.log](https://github.com/user-attachments/files/17893954/game.log)

### Describe the crash

charging into the yellow river, crashed

### Steps to reproduce / Cause of the crash

idk, i was just pushing to the north then it crashed
in error shows "Error: "Malformed token: Armored Division, near line: 8" in file: "history/units/VIN_GAW.txt" near line: 8"

### Additional information

how do i upload savefiles?

**Comment by runelead00** [comment]
Fixed in Dev Build
