### ISSUE TITLE
USA - Change the event picture from the 'Australia Objects', 'Mexico Objects' and 'Canada Objects' events

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3720]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest the picture events from the 'Australia Objects', 'Mexico Objects' and 'Canada Objects' events should be changed to 'meeting' picture, like this one.
![Image_4](https://github.com/user-attachments/assets/b24a65ec-8a34-4e9d-b403-fb8bc1b0f11e) or something like this.

### Justifications

Well, the 'meeting' event picture is quite fitting for the 'Australia Objects', 'Mexico Objects' and 'Canada Objects' events because these events talk about the objection on Trade Tariffs by three countries which means they talk. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/a77bc5f6-1335-4d88-b855-7a0ca4cc0464)

![Image_2](https://github.com/user-attachments/assets/313d95a1-d085-40f0-bbde-77560bcdf7e3)

**Comment by Stormeagle449** [comment]
Accepted.
