### ISSUE TITLE
Game crashes when capitulating Guangdong as the National Protection Army

### ISSUE THREAD

**Issue by BaveMavick64** [TNODevs/TNO-Bug-Tracker#3722]
### Operating System

windows 11

### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

Radio TNO, The New Order: Map and Cites Font

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/user-attachments/files/17910227/game.log)
[error.log](https://github.com/user-attachments/files/17910229/error.log)

### Describe the crash

When playing as the National Protection Army in china, when Guangdong loses enough victory points to capitulate, it will say calculating peace conference effects and then crash.

### Steps to reproduce / Cause of the crash

play as the National Protection Army and go through the great Asian War, when you take enough points to capitulate Guangdong the game will attempt to calculate peace conference and then crash

### Screenshots

![Screenshot (222)](https://github.com/user-attachments/assets/0003c27f-a5c5-423e-9e8b-bbd5e39e9199)
![Screenshot (223)](https://github.com/user-attachments/assets/cbadbe7d-cff6-488b-8a34-0351b9d3d756)
![Screenshot (224)](https://github.com/user-attachments/assets/f25e8861-2554-416f-8c70-b4ec2eddb5bc)

**Comment by runelead00** [comment]
Fixed in Dev Build
