### ISSUE TITLE
USA - Change the event picture of 'The Ontario Meeting Collapses!' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3726]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that 'The Ontario Meeting Collapses!' event picture should be changed to 'disappointed politicians or diplomats' picture instead of currently uses the 'normal people' picture.

### Justifications

Well, 'The Ontario Meeting Collapses!' event talks about the OFN members reject the large increase crop exports and placing the 'disappointed politicians or diplomats' picture is quite fitting, to me. 

### Screenshots

![Image_1](https://github.com/user-attachments/assets/53272398-31af-4925-a004-293a8681ca41)

**Comment by Stormeagle449** [comment]
Accepted.
