### ISSUE TITLE
USA - Massachusetts (Boston) state lore shows "Republic of Bosnia" instead of "BOS"

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#3727]
### Operating System

Windows 10

### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/user-attachments/files/17922264/error.log)
[game.log](https://github.com/user-attachments/files/17922265/game.log)
[tno.zip](https://github.com/user-attachments/files/17922271/tno.zip)

### Describe the bug

Rather than showing the regular three letter abbreviation for Boston (I'm assuming it's BOS) it shows up as "Republic of Bosnia." Assuming it's some tag-related thing due to the similarity of the two names.

### Steps to reproduce / Cause of the issue

1. Open game.
2. Click on Massachusetts state.
3. Click on the state lore button.
4. Observe issue.

### Expected behaviour

Appears as "BOS" not "Republic of Bosnia."

### Screenshots

![image](https://github.com/user-attachments/assets/f0eb1d59-04a7-4e3a-aa03-e0a4eebdb66e)

**Comment by runelead00** [comment]
Fixed in Dev Build
