### ISSUE TITLE
ITA - Still have the 'sending volunteers to Colombia' national spirit after the CCW

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3730]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[ITA.zip](https://github.com/user-attachments/files/17933318/ITA.zip)

### Describe the bug

When the Colombian Civil War ended, Italy still have the 'Military Advisors' national spirit for sending volunteers to Colombia. 

### Steps to reproduce / Cause of the issue

1. Ciano wins the power struggle against Scorza in Italy.
2. Restoration of Democracy in Italy.
3. Battle for Italy starts.
4. Japan won the Battle for Italy.
5. Italy joins the Kyōeiken.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/67b2f040-0be0-47ca-b8f4-d723a19b4a78)

![Image_2](https://github.com/user-attachments/assets/6874852f-b39a-4ed8-97d4-e6354011b117)

**Comment by runelead00** [comment]
Fixed in Dev Build
