### ISSUE TITLE
USA - Change the event pictures for the Stonewall events

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3732]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest that the event picture for 'The Stonewall Bust!', 'We Shall Overcome' and 'Kick Lines and Tear Gas' events should be changed to based on the Stonewall riots pictures instead of using generic or different pictures. 

### Justifications

The Stonewall events use different or generic pictures that they are not based on Stonewall events' texts instead of using the pictures of the Stonewall or LGBT riots. Like, 'The Stonewall Bust!' event uses a 'living normal people' picture despite the event saying that the police are arresting the LGBT activities. So, that is why I suggest this.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/196edf4a-a9aa-4c02-b1d8-6583e00f83f4)

**Comment by Stormeagle449** [comment]
Accepted.
