### ISSUE TITLE
ITA - 'A Moral Welfare' national focus uses the LBJ's The Great Society focus icon

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3733]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[ITA.zip](https://github.com/user-attachments/files/17934473/ITA.zip)

### Describe the GFX issue

The 'A Moral Welfare' national focus uses the USA LBJ's The Great Society focus icon(USA geography) instead of using a different icon about the welfare.

### Steps to reproduce / Cause of the issue

1. Ciano wins the power struggle against Scorza in Italy.
2. Restoration of Democracy in Italy.

### Expected behaviour

Forgot to check that national focus icon.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/715b6199-ad83-438f-a10b-bea9f17c3c97)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
