### ISSUE TITLE
Republic of Madagascar - Every time I attempt to get Joseph Raseta out of power in the Intelligence tab, it always fails even when I have 94% success rate

### ISSUE THREAD

**Issue by TarrySix3** [TNODevs/TNO-Bug-Tracker#3734]
### Operating System

Windows 11

### HOI4 version

1.15

### TNO version

1.2

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After winning the Malagasy uprising I am hit with the opportunity to depose Joseph Raseta of the Revolutionary Front in the Republic of Madagascar as the United States. However every time I tried deposing him I constantly keep getting an operation failed event. I tried when my success rate was 68%, 77%, 84%, and 94%. I do not know if I am scripted to lose this operation, however even when reloading the save multiple times on every success rate, I still lose it and an agent.

### Steps to reproduce / Cause of the issue

1. Play as the United States 2. Win the Malagasy Uprising with at least 99% support in the Fractured United Front 3. Wait until the Madagascar election happens in Rasetas favor 4. Attempt to depose Raseta. Either I have terrible luck or the script is constantly making me lose.

### Expected behaviour

I expected to depose Raseta after I had 94% success chance

**Comment by TarrySix3** [comment]
Correction to a mistake - TNO version is 1.6

**Comment by runelead00** [comment]
It's just bad luck and hoi4 randomness is set from game start (reloading a save will not change the outcome of event or decision)
