### ISSUE TITLE
USA - Change the event picture of 'The 1969 World Series' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3739]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest the picture of 'The 1969 World Series' event should be changed to a picture of Baseball sport or the Baseball Stadium. 

### Justifications

Well, this event talks about the Baseball sport but this event uses a picture of the Podium, which is confusing to me. That is why I suggest that the picture of this event should be changed. 

### Screenshots

![Image_1](https://github.com/user-attachments/assets/c1ab950e-9735-42b1-a77b-78bb8dabaeee)

**Comment by Stormeagle449** [comment]
Accepted.
