### ISSUE TITLE
Mex - Mexico event mentions people driving fiats despite Mexico embargoing Italy

### ISSUE THREAD

**Issue by meesplayer** [TNODevs/TNO-Bug-Tracker#3740]
### HOI4 version

1.15.1.f089

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT, TOA

### List the loc issues below

1. Event mentions union bosses driving Fiats, an Italian car brand, despite Mexico embargoing Italy.
![Schermafbeelding 2024-11-28 183106](https://github.com/user-attachments/assets/8c6b1b03-9bd6-49b5-bda8-7cf609425d96)
![Schermafbeelding 2024-11-28 184556](https://github.com/user-attachments/assets/3b75f263-28eb-4999-b03f-ff801d0c1b04)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
