### ISSUE TITLE
USA - 'Attu Islands' is mentioned in 'Battleship Diplomacy' focus description

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3741]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_npp.zip](https://github.com/user-attachments/files/17959264/USA_npp.zip)

### List the loc issues below

1.  In the 'Battleship Diplomacy' focus description, 'Attu Islands' is mentioned about the planning to repel the Japanese from US islands soil but Attu Islands is already owned but demilitarized. It should be "Two California ports to Hawaii" or "Two California ports to Honolulu" or something like this. 
![Image_1](https://github.com/user-attachments/assets/182fb65d-4615-49c3-b607-9dd4fa454c62)
![Image_2](https://github.com/user-attachments/assets/e0afd878-a9f5-487e-ac5b-fb93623b1567)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
