### ISSUE TITLE
USA - Change the event picture of the 'Unity before Similarity?' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3744]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest the 'Unity before Similarity?' event picture should be changed to a picture of 'Oval Office'(black and white color) instead of currently using a 'meeting' picture.

### Justifications

'Unity before Similarity?' event talks about President Harrington is in the Oval Office. So, a current 'meeting' picture should be replacing with an 'Oval Office'(black and white color) picture. 

### Screenshots

![Image_1](https://github.com/user-attachments/assets/ad521d4f-7eb0-40fc-ab14-b417302fbe0e)

**Comment by Stormeagle449** [comment]
Accepted.
