### ISSUE TITLE
USA - The '3 Angry Men, and a Woman' event has no effects shown

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3745]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[USA_npp.zip](https://github.com/user-attachments/files/17964149/USA_npp.zip)

### Describe the bug

When after completing the 'Pressure the Nationalists' focus and selecting the 'Unity before Similarity?' event, the '3 Angry Men, and a Woman' event has no effects while the 'Polarized' event has effects. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Michael Harrington in the 1968 election.
3. The 'Pressure the Nationalists' focus completes.

### Expected behaviour

I don't know.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/61f61e77-6460-4567-b25d-788b3d5364ed)

**Comment by runelead00** [comment]
Working as Designed, the outcome of 3 Angry Men and a Woman is the event A United NPP and the effects of that
