### ISSUE TITLE
USA - Change a picture from the 'A Foregone Conclusion' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3746]
### HOI4 version

1.15.1

### TNO version

1.6.0a

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I would like to suggest the 'A Foregone Conclusion' event's picture should be changed to a 'senators are talking' picture.

### Justifications

Well, 'A Foregone Conclusion' event tells the president is asking the RDC progressive senators to need support for his reforms. So, this event's picture should be changed to a 'senators are talking' picture instead of using a raising flag picture.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/5f053ab1-da54-4f7a-8ba7-f9e7d9ab974a)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
