### ISSUE TITLE
USA - 'Stockholm Conference Succeeds! or Fails!' events have a German intelligence picture

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3747]
### Operating System

Windows 10 Enterprise

### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The 'Stockholm Conference Succeeds!' or 'Stockholm Conference Fails!' events have a German intelligence picture. 

The 'Stockholm Conference Succeeds!' event picture should be changed to a picture of 'Nazi Germany and USA flags' and the 'Stockholm Conference Fails!' event picture should be changed to a picture of 'Empty Conference Room'. 

### Steps to reproduce / Cause of the issue

1. Bormann won the German Civil War.
2. Either Hart or Goldwater is not elected in the 1968 election.
3. The Stockholm Conference concluded.

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/5cdea1c2-e9a1-4e42-bfa7-38287212b290)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
