### ISSUE TITLE
MAG - Improperly Set Focus On WerBell Path Removes Trade Law

### ISSUE THREAD

**Issue by Kurgis** [TNODevs/TNO-Bug-Tracker#375]
**Questions**

- Operating System: Win 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0a
- Any other mods in use: Last Waltz
- Were you using Steam? Yes.
- Which expansions do you NOT have?
    Death or Dishonor
    Waking the Tiger
    Man the Guns
    La Resistance
    Battle for Bosporus

**Longer Description of Issue:**
Using the "Open For Business" focus blanks your Trade Law, it should be replacing it with Free Trade or an Export Focus. The law's effects actually seem to be unaffected by this, however, and will keep using the previous effects as Limited Exports.

**Steps to Reproduce/Cause Issue:**

1. Complete the "Open For Business" focus.

2. You will now have a blank space where your Trade Law is.

**Screenshots:**
![WerBell_issue1](https://user-images.githubusercontent.com/35203040/144585946-f4a6cdd1-9fbf-4c06-9aaf-41bac27f736f.png)
![WerBell_issue2](https://user-images.githubusercontent.com/35203040/144585961-247f13e6-bccf-47ce-9c05-508c4573bdda.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
