### ISSUE TITLE
COG - Missing Event Pictures

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3750]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Some events don't have pictures.

### Steps to reproduce / Cause of the issue

To put some pictures in these events.

### Expected behaviour

The events should have pictures

### Screenshots

![image](https://github.com/user-attachments/assets/39f30070-fcf2-476b-958a-e98488018385)
![image](https://github.com/user-attachments/assets/b4f83590-44f4-4906-8a8c-03c73ce63ca1)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Marok132** [comment]
> Fixed in Dev Build.

Thanks!
