### ISSUE TITLE
BLR - Missing Effects for the focus "Belarus is Ours" 

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3751]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The focus "Belarus is Ours" does not have any effects. Cheking its code I have found it does not have hidden effects.

### Steps to reproduce / Cause of the issue

The Ostland CW should start.

### Expected behaviour

The focus should have effects.

### Screenshots

![image](https://github.com/user-attachments/assets/f89d4144-b99f-4dab-b05e-d57bc01225c9)
![image](https://github.com/user-attachments/assets/93601c6f-8124-43ce-9b7b-f2e015477724)

**Comment by runelead00** [comment]
We are not maintaining current Ostland content
