### ISSUE TITLE
USA - Sikorsky R-4 tech icon text error

### ISSUE THREAD

**Issue by DSDHX** [TNODevs/TNO-Bug-Tracker#3752]
### Operating System

Windows 11 23H2

### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

![屏幕截图 2024-11-30 134446](https://github.com/user-attachments/assets/e3ccd99e-1b06-45c8-ad20-daf6d99ac10f)
The icon says, “Max Altitude - 2400 km.”
It should be 2400m.

### Steps to reproduce / Cause of the issue

1. Select USA or MEX
2. View Air Force Tech Tree

### Expected behaviour

Change to 2400 m

**Comment by runelead00** [comment]
Fixed in Dev Build
