### ISSUE TITLE
Guangdong - Hitachi ending tree crashing my game

### ISSUE THREAD

**Issue by Aqwa222** [TNODevs/TNO-Bug-Tracker#3753]
### Operating System

Windows 10 

### HOI4 version

1.15.1

### TNO version

1.6.0a

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/user-attachments/files/17986590/error.log)

### Describe the crash

After succesfully defeating both rioter organizations as Hitachi during the Guangdong riots, you get an event which switches the focus tree and ends the riots. if you try opening up the focus tree screen, there will be focuses but no focus icons, and after a few seconds the game will crash.
![hitachi bug](https://github.com/user-attachments/assets/3efef0b0-6ef9-4755-9de1-eb95eee83f08)

### Steps to reproduce / Cause of the crash

.1 Go down the hitachi path as Guangdong by letting the coup happen
.2 during the guangdong riots I went down the left side of the guangdong riots tree
![Screenshot 2024-12-03 135457](https://github.com/user-attachments/assets/da36e994-2573-4d71-b521-a0266cb545f0) 
.3 once both rioter organizations are defeated you will get an event to switch to the ending focus tree

![Screenshot 2024-12-03 135721](https://github.com/user-attachments/assets/cb976a16-ff76-412d-8197-f1f1512f6b74) 
.4 once the button to get the new tree is selected, if you try accessing the focus tree screen, after a few seconds the game will crash 

![hitachi bug](https://github.com/user-attachments/assets/a6f85166-d55b-47ae-a64e-9209f0edcffc)

### Screenshots

![hitachi bug](https://github.com/user-attachments/assets/18b292d5-8cb5-48af-b342-5f8de9f609d5)
![Screenshot 2024-12-03 135457](https://github.com/user-attachments/assets/46aada65-7e44-482f-b6e0-05a43013ccef)
![Screenshot 2024-12-03 135721](https://github.com/user-attachments/assets/f3a06f56-7bfe-4f1f-b9ae-b3f304b9c458)

**Comment by runelead00** [comment]
Fixed in Dev Build
