### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by i80287** [TNODevs/TNO-Bug-Tracker#376]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: idk, last update - 23 november
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown): two same answers for the event**

- [ ] 1.  https://user-images.githubusercontent.com/92759021/144708647-85b3e957-5ee4-4887-b6ae-3819bbceeef1.png

**Comment by runelead00** [comment]
Fixed in Dev Build
