### ISSUE TITLE
MAD - "Partially Decriminalized" does not have an icon.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3760]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

When I accidentally checked French Madagascar's laws, I noticed some thing that was called "Partially Decriminalized" didn't have an icon. 

### Steps to reproduce / Cause of the issue

Idk.

### Expected behaviour

It should have an icon I guess.

### Screenshots

![image](https://github.com/user-attachments/assets/e9f59609-f3a9-41df-9cb9-b3b25bd7d1b5)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Marok132** [comment]
> Fixed in Dev Build.
Thanks!

**Comment by Marok132** [comment]
> Fixed in Dev Build.

Thanks!
