### ISSUE TITLE
SER - Wrong Spelled Surname in the national spirit "Between Revolutionaries and Royalists"

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3761]
### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The title. In this national spirit Dobrica's surname is spelled as Cosic instead of Ćosić.
![image](https://github.com/user-attachments/assets/a1978001-3bff-48a5-81a5-e7a5052c1ae1)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thank you!
