### ISSUE TITLE
BFR - Missing Party names for Conservative and Fascist ones 

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3763]
### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The title.
![image](https://github.com/user-attachments/assets/f67a9e51-f220-4c83-9721-423891c0d051)
![image](https://github.com/user-attachments/assets/f996ee28-c99b-4c8d-a8e4-d926d98219e5)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thanks!
