### ISSUE TITLE
NPA - Crash upon capitulating North China Political Council

### ISSUE THREAD

**Issue by DoggosTacos** [TNODevs/TNO-Bug-Tracker#3764]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Files

[error.log](https://github.com/user-attachments/files/18031486/error.log)

### Describe the crash

Upon the daily in game tick after capitulating the NCPC, the game will display "Calculating peace conference" and promptly crash.

### Steps to reproduce / Cause of the crash

1. Play as NPA
2. Fight Great Asian War until capitulating North China Political Council

### Screenshots

State of the war an hour before the daily tick.
![394360_20241205192554_1](https://github.com/user-attachments/assets/ca22ec71-a9cd-4720-b6c4-b73613594ad8)

**Comment by runelead00** [comment]
Fixed in Dev Build
