### ISSUE TITLE
KEM - Missing Icon for KEM_ship_expansion

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3767]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title.

### Steps to reproduce / Cause of the issue

Idk.

### Expected behaviour

It should have an icon.

### Screenshots

![image](https://github.com/user-attachments/assets/eb329488-3606-46fe-b96d-ca2583c5ba31)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
