### ISSUE TITLE
GRE - Several Generals Don't have locs.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3769]
### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

These three generals don't have locs.
![image](https://github.com/user-attachments/assets/11a2c73c-fde7-4794-9901-411028792809)
![Uploading image.png…]()

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thank you!!!
