### ISSUE TITLE
Peacefully unifying with the leader of the Comintern breaks the Comintern

### ISSUE THREAD

**Issue by dym4201984** [TNODevs/TNO-Bug-Tracker#377]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?

**Longer Description of Issue:**
The PRC created the Comintern. As Irkutsk, I diplo unified with them. The Comintern is stuck voting forever on whether or not to send aid to Kyzylorda.

**Comment by YanSGod** [comment]
I also encountered this bug,if  the Comintern'Founding country had been annexed , the issue will continue forever

**Comment by YanSGod** [comment]
you can setowner the Founding country to resolve the problem as Simple method
