### ISSUE TITLE
ECU - Missing effects for The True Home of The Revolution national spirit.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3770]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title. 

### Steps to reproduce / Cause of the issue

To use these two gamerules to reproduce it.
![image](https://github.com/user-attachments/assets/869ecae0-46ae-447e-9d14-a9442b1a2b51)

### Expected behaviour

It should have some effects I guess.

### Screenshots

![image](https://github.com/user-attachments/assets/b98937e1-3579-49f1-8a02-dc954ad50a84)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thank you!
