### ISSUE TITLE
NGA - Missing Party Name for the Fascist one.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3775]
### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The title.
![image](https://github.com/user-attachments/assets/0b33365b-64dc-484b-b058-b6e47937a82d)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thank you!
