### ISSUE TITLE
GER - Missing locs for computing_tech_research.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3778]
### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

There is not a loc for the computing_tech_research thing.
![image](https://github.com/user-attachments/assets/8b6c0230-4437-4087-8cb0-4f5a8147b8de)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
