### ISSUE TITLE
Japan - An Alliance of Pragmatic Distrust missing event text

### ISSUE THREAD

**Issue by mferlandusc** [TNODevs/TNO-Bug-Tracker#378]
**Questions**

- Windows 10
- 1.10.8
- 1.2.0.d
- Radio TNO
- Yes, I was using Steam?
- I do not have the latest expansion (no step back)

For the West Africa stuff, as Japan, the initial event seemed to lack text

Steps to Reproduce/Cause Issue:

Presumably just play as Japan until mid 1964?

Screenshot:

![20211204160251_1](https://user-images.githubusercontent.com/46851797/144728507-a227c08a-5a50-4921-b82f-88a87eefafb2.jpg)

**Comment by runelead00** [comment]
Fixed in Current Release
