### ISSUE TITLE
[Bug]: Norilsk State - Province titled *very* incorrectly

### ISSUE THREAD

**Issue by Memez145** [TNODevs/TNO-Bug-Tracker#3783]
### Operating System

Ubuntu 22.04

### HOI4 version

1.15.2

### TNO version

v1.6.0a (So Far From God)

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Describe the bug

Province 12545 (north siberia, click around near the very left of Norilsk if you can't find it) is described as containing Oktyabrsky. Oktyabrsky is in Bashkortostan

### Steps to reproduce / Cause of the issue

1. Boot up the game
2. Start a new game or load a save
3. Go to Norilsk state and find Province 12545
4. check the bottom left province description thing

### Expected behaviour

province is just described as "Province" instead of Oktyabrsky, as like any other non-settlement province

### Screenshots

![image](https://github.com/user-attachments/assets/6294a952-35a6-49e3-85b2-d885f408a774)
![image](https://github.com/user-attachments/assets/a6e78b43-aa24-4827-aec0-dec6d7c3f6cb)

### Additional information

i understand this is really really small but still

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.

**Comment by Memez145** [comment]
WRONG SCREENSHOT. SORRY. CHRIST
