### ISSUE TITLE
INS - Indonesia War in the cold tab is Statemate for the USA and JAP once Supeno wins.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3791]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Supeno wins in the ICW, both Japan and the US gets Statemate in the Indonesia War despite Indonesia joins the Japanese alliance. I guess something is broken..

### Steps to reproduce / Cause of the issue

Should Supeno wins in the ICW

### Expected behaviour

Japan should get victory points while the US the defeat one.

### Screenshots

![image](https://github.com/user-attachments/assets/6f41a097-7647-49a8-9213-a8263ab86d77)
![image](https://github.com/user-attachments/assets/b0ccce28-7478-4c58-a537-0c20cc2a9544)
![image](https://github.com/user-attachments/assets/8abf28e1-48c3-4351-b393-267802cc0b5b)

**Comment by runelead00** [comment]
Working as Designed, as indicated by ending event for both tags, Indonesia is basically only nominally in the Sphere and no one is happy about it despite heavy investment on both sides

**Comment by Marok132** [comment]
> Working as Designed, as indicated by ending event for both tags, Indonesia is basically only nominally in the Sphere and no one is happy about it despite heavy investment on both sides

Hmmm, it's fine.
