### ISSUE TITLE
Mexico - Mexico City Abriviation Overflow

### ISSUE THREAD

**Issue by kylebentl** [TNODevs/TNO-Bug-Tracker#3793]
### Operating System

Windows 11

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Describe the GFX issue

![image](https://github.com/user-attachments/assets/534d9560-04c9-4bef-a71f-1d66c1c358ef)
The abriviation for Mexico City in it's state lore tab has the name of the whole country instead and it spills into the main text box (note: playing as Mexico, not sure if that has anything to do with it)

### Steps to reproduce / Cause of the issue

1-go to Mexico City
2-Click on the Federal District province
3-Click the state lore button

### Expected behaviour

The abriviation of Mexico City to not spill into the lore page

### Screenshots

![image](https://github.com/user-attachments/assets/d3fa33ca-ca93-40e2-9267-0e4d8400d57c)

**Comment by runelead00** [comment]
Fixed in Dev Build
