### ISSUE TITLE
CAF - Spelled Wrong  Country Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3794]
### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

The country uses "Beafrika" despite "Bêafrîka" is more correctly. Fix it, please.
![image](https://github.com/user-attachments/assets/4592c5ae-ecd8-4729-9d1a-4d30ff56731c)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thank you!
