### ISSUE TITLE
UKR - Missing Locs for some Ministers.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3796]
### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/f5b1d8ad-abf3-4466-91fc-819105077861)
![image](https://github.com/user-attachments/assets/b317cc19-67e7-4848-883d-6a791b352400)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thank you!
