### ISSUE TITLE
ULT - Turkestan Legion has Veli Kayum Rides Again natspirit despite he's not in power.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3797]
### Operating System

Windows 10

### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title. When Veli Kayum is overthrown by either Baymirza Hayit or Sher Muhammad Korşirmat, his own national spirit is not removed.

### Steps to reproduce / Cause of the issue

Should Baymirza Hayit or Sher Muhammad Korşirmat takes power in the Turkestan Legion.

### Expected behaviour

The national spirit should be removed once Veli Kayum is overthrown.

### Screenshots

![image](https://github.com/user-attachments/assets/f51508b8-71e0-4b93-a227-3e0bab923c5d)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thank you!
