### ISSUE TITLE
NPA (YUN) - Missing GFX on National Spirit Repair Focus

### ISSUE THREAD

**Issue by runelead00** [TNODevs/TNO-Bug-Tracker#38]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?  None

**Longer Description of Issue:**
NPA national spirit Repair Focus is missing an icon.

**Screenshots:**
![gfx2](https://user-images.githubusercontent.com/74165171/128590832-6a92c477-8cfd-466c-b022-33100bdbb736.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build.
