### ISSUE TITLE
IBR - Used a Russian map picture in the decision "Attract American Investors"

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3801]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title. It should use an American map picture, not the Russian one.

### Steps to reproduce / Cause of the issue

Should Iberia be democratized and finish this focus.
![image](https://github.com/user-attachments/assets/2ab57f93-e37d-4377-974d-87a37e0128bd)

### Expected behaviour

It should use an American map picture.

### Screenshots

![image](https://github.com/user-attachments/assets/e49b18c4-eb4e-4998-b02e-1f6bd2376c05)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
