### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Radu2512** [TNODevs/TNO-Bug-Tracker#3804]
### Operating System

Windows11

### HOI4 version

.

### TNO version

.

### Do you have other mods in use?

Player Led Peace Conferences, Reduced Cost Air, Powerful Air Doctrines, Naval and Air bases icons 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

I can't scroll on the research tab.

### Steps to reproduce / Cause of the issue

Go to the research tab
Select a slot
Go to any subcategory that's more extensive
Try going up/down or left/right 

### Expected behaviour

Normal use of the research tab

**Comment by Marok132** [comment]
Try to disable all the mods but TNO (especially Powerful Air Doctrines).

**Comment by Stormeagle449** [comment]
You don't need Player Led Peace Conferences because we don't do peace conferences, disable either Reduced Cost Air or Powerful Air Doctrines, check if both of those mods are updated.

**Comment by Radu2512** [comment]
I disabled them, everything is in order
Thank you

**Comment by Marok132** [comment]
> I disabled them, everything is in order Thank you

You're welcome.
