### ISSUE TITLE
HOL - Does not get "Reichskommissariat Niederlande" name once it rejoins.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3808]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title. When the Netherlands becomes Reichskommissariat again, it does not rename to Reichskommissariat Niederlande.

### Steps to reproduce / Cause of the issue

1. Bormann wins in the GCW.
2. Cornelis van Geelkerken takes power in the Netherlands.
3. The negotiations between Germany and the Netherlands are successful and the Netherlands are RK again.

### Expected behaviour

It should be renamed to Reichskommissariat Niederlande after rejoining Pakt.

### Screenshots

![image](https://github.com/user-attachments/assets/c286e672-47c7-4095-b5ee-b426dc0fb5e6)
![image](https://github.com/user-attachments/assets/4d9aa333-deee-4928-b1cc-c6b06c512ffa)

**Comment by runelead00** [comment]
Working as Designed as indicated via numerous events Germany gets
