### ISSUE TITLE
NNG - Missing Party Names

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3809]
### HOI4 version

1.15.0

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/9b8da8ad-ba39-4fce-8cd9-1c3cab987a3d)
![image](https://github.com/user-attachments/assets/1119e105-e0fa-494c-a64b-ffabb294a7db)
![image](https://github.com/user-attachments/assets/b06485f2-51d0-4ce5-8453-e4557a1154b5)
![image](https://github.com/user-attachments/assets/46220abb-5d9e-464a-824a-dba2ab8ad6b1)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thanks!
