### ISSUE TITLE
BRA - Operation Curtain Call affects GRO when it should affect ANG

### ISSUE THREAD

**Issue by nagisakun2** [TNODevs/TNO-Bug-Tracker#381]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.20d
- Any other mods in use: TNO Radio

- Were you using Steam?
Yes
- Which expansions do you NOT have?
No Step Back and Battle for the Bosporus

**Longer Description of Issue:**
The operation weirdly affects Ostafrika instead of Sudwestafrika even though you send boats to the Angola Basin and the Gulf of Guinea, two seas that border Sudwestafrika and Zentralafrika respectively. It makes no sense for the operation to affect a country that's on the other side of the continent.

**Steps to Reproduce/Cause Issue:**

1. Finish the Operation Deodoro focus

2. Open up the Global Conflict tab

3. Check the "Operation Curtain Call" decision

**Screenshots:**

![1](https://user-images.githubusercontent.com/94869753/145075513-051f868b-5cf2-4336-bf6e-22ed6add7bbe.png)

![2](https://user-images.githubusercontent.com/94869753/145075653-12456ac6-234e-4bc4-8a0a-eb045aaa6b3e.jpg)

![3](https://user-images.githubusercontent.com/94869753/145075726-593bbba3-a378-4be7-915b-c8dcce5992fb.png)

![fe](https://user-images.githubusercontent.com/94869753/145075831-8e79fe8e-3f4e-481f-99b2-1f3ddca1e953.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
