### ISSUE TITLE
BRA - Missing Event Pictures (There are a lot of them)

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3811]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The events with next event IDs don't have pictures: 
brazil.453 
brazil.454
brazil.488
brazil.489
brazil.490
brazil.491
brazil.493
brazil.495
brazil.496
brazil.498
brazil.499
brazil.500
brazil.501
brazil.508
BRA_quadroshundreddays.1
BRA_quadroshundreddays.2
BRA_quadroshundreddays.3
BRA_quadroshundreddays.4
BRA_quadroshundreddays.5
BRA_quadroshundreddays.6
BRA_quadroshundreddays.7
BRA_quadroshundreddays.8
BRA_quadroshundreddays.9
BRA_quadroshundreddays.100
BRA_quadroshundreddays.101
BRA_quadroshundreddays.200

### Steps to reproduce / Cause of the issue

To put pictures.

### Expected behaviour

These events should have pictures.

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thanks!
