### ISSUE TITLE
Far Eastern Soviet Republic, Sablin - Random Crash to Desktop

### ISSUE THREAD

**Issue by j-teddy** [TNODevs/TNO-Bug-Tracker#3812]
### Operating System

Windows 10

### HOI4 version

1.15.3

### TNO version

1.6.0a

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[BRY_1968_06_20_03.zip](https://github.com/user-attachments/files/18196870/BRY_1968_06_20_03.zip)
[error.log](https://github.com/user-attachments/files/18196873/error.log)
[game.log](https://github.com/user-attachments/files/18196879/game.log)

### Describe the crash

Random Crash to desktop on the 22. June 1968, no idea what might cause this.

### Steps to reproduce / Cause of the crash

1. Load File
2. Let Game run until 22.June

**Comment by j-teddy** [comment]
I turned on a bunch of custom paths in the begining, that may contribute to sth but idk

**Comment by Marok132** [comment]
> I turned on a bunch of custom paths in the begining, that may contribute to sth but idk

Did the Portuguese People's Front  spawn? I've just checked your log and I think it causes a ctd because there was a similar issue recently.

**Comment by j-teddy** [comment]
Yeah they spawned! bummer that that's the issue, anything i could do? or just start a new game?

**Comment by Marok132** [comment]
> Yeah they spawned, or at least were supposed to! bummer if that's the issue, anything i could do? or just start a new game?

Just start a new game and try to prevent the Portuguese People's Front spawn.

**Comment by j-teddy** [comment]
ok thanks ^^

**Comment by Marok132** [comment]
> ok thanks ^^

You're welcome. I think you could close this issue then.
