### ISSUE TITLE
CHT - AI doesn't select any of the A King and His Cheessboard decisions

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3814]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

AI Chita ignores decisions in the A King and His Cheessboard category.

### Steps to reproduce / Cause of the issue

Chita should unite Far East.

### Expected behaviour

AI Chita should select all the decisions until 1969 properly.

### Screenshots

![image](https://github.com/user-attachments/assets/b22f033c-3c00-4dfa-9dfd-da59eced3066)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thanks!
