### ISSUE TITLE
USA - Harrington's AI doesn't complete any focuses in the Diplomatic focus tree.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3815]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title. AI Harrington just ignores them.

### Steps to reproduce / Cause of the issue

Should Harrington be elected.

### Expected behaviour

AI Harrington should complete focuses in the diplomatic focus tree.

### Screenshots

![image](https://github.com/user-attachments/assets/32586a47-aa37-4677-8d30-4425747867dd)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
