### ISSUE TITLE
KAZ and KZR - Have Warlord Development and Raiding and Loot decisions despite they are not warlords.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3816]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title. I guess it's part of old Kazakh content when it was full of warlords.

### Steps to reproduce / Cause of the issue

Just remove these two categories for KAZ and KZR tags.

### Expected behaviour

Kazakhstan tags should not have these categories.

### Screenshots

![image](https://github.com/user-attachments/assets/d9715b2f-12f3-4954-9f87-865df14d3389)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thanks!
