### ISSUE TITLE
ONG - Missing Pictures for ONG.11 and ONG.13

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3817]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title.

### Steps to reproduce / Cause of the issue

To add pictures.

### Expected behaviour

They should have pictures.

### Screenshots

![image](https://github.com/user-attachments/assets/a5e4e84d-c0d6-4f44-a9da-1682808798e0)
![image](https://github.com/user-attachments/assets/da969d13-257d-4a31-bd50-133ef93ceba6)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
