### ISSUE TITLE
COG - Missing Event Pictures for COG_Lobster_War.2 , COG_Lobster_War.3 and COG_Lobster_War.4

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3818]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title.

### Steps to reproduce / Cause of the issue

To add pictures.

### Expected behaviour

The events should have pictures.

### Screenshots

![image](https://github.com/user-attachments/assets/f32a2ab1-ba3d-4566-b397-49eb4a4eea73)
![image](https://github.com/user-attachments/assets/c5fa7b78-b511-4bb8-aa9f-fdd742f46cd4)
![image](https://github.com/user-attachments/assets/ec3fb241-7b00-4faa-a8a7-fe0865dc18c1)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
