### ISSUE TITLE
AMR - Missing Event Pictures from AMR.smuta.1 to AMR.smuta.11 chains.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3819]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title.  All the events from AMR.smuta.1 to the AMR.smuta.11 events don't have pictures.

### Steps to reproduce / Cause of the issue

To enable Smuta focus tree for Amur.

### Expected behaviour

They should have pictures.

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thanks!
