### ISSUE TITLE
USA Negotiation options for the dream act don't appear

### ISSUE THREAD

**Issue by AbolishNasa** [TNODevs/TNO-Bug-Tracker#382]
**Questions**

- Operating System: windows 10
- HOI4 Version: 1.10.8
- TNO Version: lol current version
- Any other mods in use: various music mods and state transfer tool
- Were you using Steam? yes
- Which expansions do you NOT have?
none
**Longer Description of Issue:**
The tab on decisions that show amount of votes and negotiation options for the dream act didn't appear
**Steps to Reproduce/Cause Issue:**

1. Start the focus

**Screenshots:**
![20211207192400_1](https://user-images.githubusercontent.com/95725330/145126531-54cee53b-d9b4-42b0-af8f-82885001def2.jpg)
![20211207192353_1](https://user-images.githubusercontent.com/95725330/145126536-ab6043f6-bea2-42a4-9cd6-1c99f371b141.jpg)

**Comment by ModdingAccount** [comment]
Fixed in dev build.
