### ISSUE TITLE
BRA - Missing Event Pictures for USA_CIA_BRA.1 and USA_CIA_BRA.2

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3821]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.6.0a

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title.

### Steps to reproduce / Cause of the issue

To add pictures.

### Expected behaviour

They should have pictures.

### Screenshots

![image](https://github.com/user-attachments/assets/7241875d-598c-4a88-b648-cc2a29e0cc5d)
![image](https://github.com/user-attachments/assets/19bdc6b4-3ef2-4843-a3c9-9bfe6592b2eb)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0

**Comment by Marok132** [comment]
> Fixed for patch 1.7.0

Thanks!
