### ISSUE TITLE
Komi Republic - Minor spelling mistake in the event "A Power Play?"

### ISSUE THREAD

**Issue by LonelyAmi** [TNODevs/TNO-Bug-Tracker#3823]
### HOI4 version

1.15.3

### TNO version

v1.6.0a

### Do you have other mods in use?

Only icon, radio, and graphical mods. Nothing that should effect Komi events.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

In Komi Republic event KOM.116, "A Power Play?" the word "with" is written instead of "will".  "Those two arsonists who were paroled last month with soak the place with gasoline."
![loc error](https://github.com/user-attachments/assets/4c896d1b-5d25-4c4e-9db0-d97956773644)

**Comment by Stormeagle449** [comment]
Fixed for patch 1.7.0
