### ISSUE TITLE
WRS - Units start spawned in Onega territory

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#3824]
### Operating System

Windows 10

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[error.log](https://github.com/user-attachments/files/18223272/error.log)
[WRS_1962_01_01_01.zip](https://github.com/user-attachments/files/18223273/WRS_1962_01_01_01.zip)

### Describe the bug

Upon the game's start, three units start in Onega's territory instead of the WRRF's.

### Steps to reproduce / Cause of the issue

1. Start game as WRRF.
2. Observe issue.

### Expected behaviour

Units start in WRRF territory.

### Screenshots

![image](https://github.com/user-attachments/assets/f18cd8b9-577f-4f26-a68b-bf2c19b01059)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a
