### ISSUE TITLE
Crash before reaching main menu

### ISSUE THREAD

**Issue by larrybutcooler** [TNODevs/TNO-Bug-Tracker#3828]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/user-attachments/files/18223540/error.log)

### Describe the crash

so i have tno only active and when i started it, it had said failed to load the map

### Steps to reproduce / Cause of the crash

idk i just have tno only active and stated it and it just crashed

### Screenshots

![Screenshot 2024-12-22 144756](https://github.com/user-attachments/assets/0de23fff-ae82-4bfe-9a03-43e7312025c8)
just have tno
![Screenshot 2024-12-22 144115](https://github.com/user-attachments/assets/2b328498-77b1-4daf-b5ed-72aa3129b14e)
what happens

### Additional information

i deleted the mod files and then undeleted the files for the mod 2 months ago and i think it may be a problem even though it was running fine before the operation deep freeze update

**Comment by Stormeagle449** [comment]
I don't know why this is happening. Could be that Steam didn't download the mod correctly, in which case I suggest you to verify the game files integrity. If that doesn't work, check this page https://github.com/TNODevs/TNO-Bug-Tracker/issues/961
