### ISSUE TITLE
BRG - Food reserve won't decline.

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#383]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: none.
- Were you using Steam? Yes.
- Which expansions do you NOT have? None.

**Longer Description of Issue:**

When in famine, Burgundy's national food reserve won't decline.

**Steps to Reproduce/Cause Issue:**

1. Play Burgundy until the famine.

**Screenshots:**
![20211209175600_1](https://user-images.githubusercontent.com/65211266/145382583-07fb5cac-f18a-46c8-b2f4-ae2e75b6a0d7.jpg)

**Comment by runelead00** [comment]
Works on Dev Build
