### ISSUE TITLE
Japan - Open Chengdu State Lore

### ISSUE THREAD

**Issue by BigComp** [TNODevs/TNO-Bug-Tracker#3830]
### Operating System

Windows 11

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Files

![20241222173357_1](https://github.com/user-attachments/assets/2dd73807-c826-4f63-aeb1-ac8a9799f560)

### Describe the crash

Clicking on the Chengdu state lore freezes and then crashes the game

### Steps to reproduce / Cause of the crash

1. Click on Chengdu state
2. Open the state lore

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a

**Comment by BigComp** [comment]
Oops. Did not mean to upload that
