### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by The-True-Steward** [TNODevs/TNO-Bug-Tracker#3835]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

Whenever peacefully unifying with Guizhou Province, since new provinces have been added, you only gain a core on the state of Guiyang. I don't know if this is intentional, but I do not see a way to core the rest of the provinces through a focus or decisions, nor is Yunnan mentioned once in the changelogs, though I could have missed something.

### Steps to reproduce / Cause of the issue

1.) Turn off Ironman mode
2.) enable the cheat allowing you to instantly complete focuses
3.) complete the necessary focuses to annex/ unite with Guizhou

### Expected behaviour

Cores on all of Guizhou

### Screenshots

![Screenshot 2024-12-22 215735](https://github.com/user-attachments/assets/5c976696-8883-4b2a-995c-a78692bdaf6f)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a
