### ISSUE TITLE
BRG - Wrong tooltips

### ISSUE THREAD

**Issue by AshleyOwO** [TNODevs/TNO-Bug-Tracker#384]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: none.
- Were you using Steam? Yes.
- Which expansions do you NOT have? None.

**Longer Description of Issue:**

1. One of tooltips of the decision "BRG_destroying_schools_2“ is "BRG_Spend_50_NI" while it should be "BRG_Gain_5_NI" considering its real effect.

2. The tooltip above, "BRG_Gain_5_NI", should be renamed to "BRG_Gain_50_NI" to truthfully represent its real effect. "BRG_Gain_50_NI" is also displayed in the focus tree.

**Steps to Reproduce/Cause Issue:**

1. Play Burgundy until the education crisis.

**Screenshots:**

![Inked20211209190252_1_LI](https://user-images.githubusercontent.com/65211266/145387441-a4902478-11bb-4304-b3fa-7fab08ec3847.jpg)
--------
![20211209190323_1](https://user-images.githubusercontent.com/65211266/145387460-7828c4ee-6d84-4469-b87e-09b0bd599b86.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
