### ISSUE TITLE
BHU - Gets a military government despite it should be a reliant state.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3844]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the RoI wins in the IRW and puppets Bhutan, it gets a military government despite it should get a reliant state just like Sikkim.

### Steps to reproduce / Cause of the issue

The RoI wins in the IRW.

### Expected behaviour

Bhutan should get a client state.

### Screenshots

![image](https://github.com/user-attachments/assets/39559c38-efe2-4cba-ad9d-8ff7444efadc)
![image](https://github.com/user-attachments/assets/11ab858e-54e0-405f-ac2a-672e21cb56a0)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
