### ISSUE TITLE
GUY - The British Legacy Issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3849]
### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Despite Guyana is a republic, the national spirit The British Legacy still mentions the Queen Elizabeth II as a head of state.
![image](https://github.com/user-attachments/assets/77e4edeb-feed-4c35-b636-3276db93b37e)
![image](https://github.com/user-attachments/assets/60848817-e6d0-4aa1-8821-e3dfea877c8d)

**Comment by Stormeagle449** [comment]
"Co-operative Republic of Guyana" is Guyana's name irl, and it's also a member of the Commonwealth, which means the actual head of state is the British monarch. In TNO, Guyana recognizes Elizabeth II as its head of state.

**Comment by Marok132** [comment]
> "Co-operative Republic of Guyana" is Guyana's name irl, and it's also a member of the Commonwealth, which means the actual head of state is the British monarch. In TNO, Guyana recognizes Elizabeth II as its head of state.

Why is it called as a republic if its head of state is monarch?
