### ISSUE TITLE
Scorza's Italy - Decisions to reunify Italian East Africa don't work

### ISSUE THREAD

**Issue by user1356** [TNODevs/TNO-Bug-Tracker#386]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: Latest
- Any other mods in use: Second West Russian War
- Were you using Steam? Yes
- Which expansions do you NOT have? 

**Longer Description of Issue:**
There are decisions to reunify Italian East Africa when it collapses if playing as Scorza. There is only 1 decision that works and that is the invasion of Eritrea. The rest of the decisions simply give: "invalid id" or something, therefore making it impossible to reunify Italian East Africa.
**Steps to Reproduce/Cause Issue:**

1. Play as Scorza

2. Wait for Italian East Africa to collapse

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/95897219/145516441-d83a55d3-4e2e-4a66-9814-41bfe4f01a95.png)

**Comment by Stormeagle449** [comment]
Fixed in UB.
