### ISSUE TITLE
OMA - The OFN intervenes in the civil war directly.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3863]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Oil Crisis starts, Oman does not leave the OFN so it intervenes in the Omani Civil War directly.

### Steps to reproduce / Cause of the issue

Italy joins the OFN and the Omani civil war starts.

### Expected behaviour

The OFN should not intervenes in the civil war directly.

### Screenshots

![image](https://github.com/user-attachments/assets/e36c31a0-0dd5-483d-a822-a299562742da)

**Comment by Potablec1234** [comment]
Fixed for next hotfix

**Comment by Potablec1234** [comment]
> > Fixed for next hotfix
> 
> When you fix some issue, you should close it then. Do you know how to do it?

I’m new to this so not really sure, could you please close it?

**Comment by Marok132** [comment]
> > > Fixed for next hotfix
> > 
> > 
> > When you fix some issue, you should close it then. Do you know how to do it?
> 
> I’m new to this so not really sure, could you please close it?

I can, yes. But next time you should click there where I circled.
![image](https://github.com/user-attachments/assets/b8c6452f-28f9-4e0a-b798-8c8d66008ee3)

**Comment by Marok132** [comment]
> > > Fixed for next hotfix
> > 
> > 
> > When you fix some issue, you should close it then. Do you know how to do it?
> 
> I’m new to this so not really sure, could you please close it?

I hope it will help you.
