### ISSUE TITLE
Crash on loading games when trying to load TNO mod, issue isnt present when trying to access with other mods.

### ISSUE THREAD

**Issue by Mohamed-Ayaan358** [TNODevs/TNO-Bug-Tracker#3864]
### Operating System

Windows 11

### HOI4 version

1.14.1

### TNO version

1.7.0

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/user-attachments/files/18229328/error.log)

### Describe the crash

It loads up to 70% and then crashes out

### Steps to reproduce / Cause of the crash

1. Go to hoi4.exe and run it after setting the playset

### Screenshots

![image](https://github.com/user-attachments/assets/32bda3e1-5990-4dd4-a00d-81f127a45c58)

### Additional information

I dont have the Götterdämmerung dlc

**Comment by Marok132** [comment]
You need 1.15.3 HOI4 version to launch the mod.

**Comment by Stormeagle449** [comment]
Check the game files integrity on Steam, or follow the advice in this page https://github.com/TNODevs/TNO-Bug-Tracker/issues/961
