### ISSUE TITLE
AAN - Gets Comintern Associate

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3865]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Antarctic wastelands gets a Comintern Associate.

### Steps to reproduce / Cause of the issue

The COMECON should be established.

### Expected behaviour

Do I really need to say anything?

### Screenshots

![image](https://github.com/user-attachments/assets/8485955c-f250-4415-987d-ab669b235f36)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a

**Comment by Marok132** [comment]
> Fixed for hotfix 1.7.0a

Thanks!
