### ISSUE TITLE
AST - Has a claim on Diego Garcia for unknown reasons.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3866]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

For some reasons Australia has a claim for Diego Garcia despite it has never controlled and claimed it in OTL. I guess it's part of old TNO lore when Australlia controlled it (a very long time ago).

### Steps to reproduce / Cause of the issue

To remove this claim.

### Expected behaviour

Australia should not have a claim on Diego Garcia.

### Screenshots

![image](https://github.com/user-attachments/assets/9cc6b8d2-bfc4-4a87-a1c3-864b5e49038a)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a

**Comment by Marok132** [comment]
> Fixed for hotfix 1.7.0a

Thanks!
