### ISSUE TITLE
MAN - STATE_657 and VICTORY_POINTS_7672

### ISSUE THREAD

**Issue by AshleyTranny** [TNODevs/TNO-Bug-Tracker#387]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: none

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

The place's current name, Biluobizhan, is directly pulled from its Russian name Birobidzhan.
But there is already a name for it: Kimnin Weji, which means Kimnin Forest.

Source: 
竒穆尼窩集（城東北一千七百四十里）
https://zh.wikisource.org/zh-hans/%E6%AC%BD%E5%AE%9A%E7%9B%9B%E4%BA%AC%E9%80%9A%E5%BF%97_(%E5%9B%9B%E5%BA%AB%E5%85%A8%E6%9B%B8%E6%9C%AC)/%E5%8D%B7027#%E5%90%89%E6%9E%97%E5%90%84%E5%B1%AC
http://deepsky.com/~merovech/voynich/voynich_manchu_reference_materials/PDFs/Manchu-English+Dictionary.pdf

![20211210121237_1](https://user-images.githubusercontent.com/65211266/145516218-f6c8acfd-54bb-4630-9d8b-f954df26206d.jpg)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting.
