### ISSUE TITLE
SocDem Komi - Country gets like 60 production units after it invites foreigners to invest

### ISSUE THREAD

**Issue by Danieluis78** [TNODevs/TNO-Bug-Tracker#389]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.10.8
- TNO Version: Newest
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? Barbarosa

After I clicked the final focus of the diplomatic tree (left branch) I obtained 60 production units. 

**Steps to Reproduce/Cause Issue:**

1. Play Socdem Komi

2. Win Regional Face

Finish the "Call for Investment" Focus
 

![Screenshot (335)](https://user-images.githubusercontent.com/95912277/145557136-74605583-3d3f-4869-a47a-99c1955aa79b.png)

**Comment by thashepherd** [comment]
![image](https://user-images.githubusercontent.com/711467/145741925-5727ce63-e1cc-4bf7-8f61-0ab126c02ac8.png)
This may not be isolated to Komi; I just experienced a massive increase in PUs seemingly untied to anything as well while playin g as the SBA..

**Comment by thashepherd** [comment]
![image](https://user-images.githubusercontent.com/711467/145742609-912d98a0-fdb5-4b8b-93b6-bfcc62b3b475.png)
^ ah, _that's_ the reason.

**Comment by Scarsoftime** [comment]
Seems like it's problem solved.
