### ISSUE TITLE
Yunnan - Xinan Cores don't really apply

### ISSUE THREAD

**Issue by Interesting2752** [TNODevs/TNO-Bug-Tracker#3898]
### Operating System

Windows 10

### HOI4 version

1.15.3.551d

### TNO version

1.7.0

### Do you have other mods in use?

TNO More Tank Slots+Tank Module, Zizek's Ideology Bling, Radio TNO, Immersive Music Mod (Comintern, China, and Non-Aligned)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT, TOA

### Describe the bug

Well, when I unified with Guizhou as part of the leadup to Long Yun's wild ride, I noticed that except for the state of Guiyang, I had been granted no other cores within any states in Guizhou, and I was getting resistance and all those mechanics.

### Steps to reproduce / Cause of the issue

1. Play as Yunnan
2. Proceed to the part of the tree where you unify with Guizhou
2b. (I did the path of peaceful unification with mostly decentralizing options)
3. Finish Unification
4. See that you only have core in Guiyang if everything went to plan

### Expected behaviour

I expected that after I had unified into Xinan, I would have cores on all provinces within all of Guizhou, instead of just Guiyang

### Screenshots

![20241222203654_1](https://github.com/user-attachments/assets/9a8e5700-fbca-4af8-bd51-443880abc925)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a
