### ISSUE TITLE
NPA (YUN) - Keeping Momentum Repeating Missions

### ISSUE THREAD

**Issue by runelead00** [TNODevs/TNO-Bug-Tracker#39]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?  None

**Longer Description of Issue:**
The Keeping Momentum missions keep repeating after you've finished the mission the first (may be related to failing also causing the mission to repeat). This can create a large amount of negative devastation and gives additional equipment, stability, and war support given the decision, which is presumably not intended. Additionally all the missions in this category have missing loc on a tooltip
**Steps to Reproduce/Cause Issue:**

1. Have Long Yun take over Yunnan and go to war with China

2. Successfully invade and hold at least one of the Keeping Momentum mission targets 

**Screenshots:**
![KeepingMomentumRepeating](https://user-images.githubusercontent.com/74165171/128591121-eb620655-ff33-47ce-9612-6d8b06f035cd.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build.
