### ISSUE TITLE
BRG Volunteers to Heydrich 

### ISSUE THREAD

**Issue by Phil553** [TNODevs/TNO-Bug-Tracker#390]
**Questions**

- Operating System: Win10
- HOI4 Version: 1.10.8
- TNO Version: v1.2.0 'Toolbox Theory
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them, no Step back is disabled becouse I roled back my Version.

**Longer Description of Issue:**
When you play Burgundy and the German Civil war starts the decision "Mobilize The Burgundian-SS" will undo your ability (from the two focuses) to Send Volunteers to Heydrich. 
**Steps to Reproduce/Cause Issue:**

1. Start As Burgundy and wait for the German CW

2. Do the Focus "The Call to Arms"

3. Take the decision "Mobilize The Burgundian-SS"

4. Try to send volunteers now
Optional:

5. Do the Focus "Leading the Charge" (you are now able to send volunteers again (only 3 instead of 5)

6. Take the decision "Mobilize The Burgundian-SS" again, you are now again not able to send any volunteers.

**Comment by runelead00** [comment]
Fixed on Dev Build
