### ISSUE TITLE
Republic Of Congo breakaway state in GRO collapse still has RK Zentralafrika focus tree and can still do its focuses.

### ISSUE THREAD

**Issue by februarywhiskeys** [TNODevs/TNO-Bug-Tracker#391]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary(Old)
- TNO Version: 1.2.0d
- Any other mods in use: None
- Were you using Steam? : Yes
- Which expansions do you NOT have? : I do not have the following:

1. Eastern Front Music Pack
2. Eastern Front Planes Pack
3. Axis Armor Pack
4. Radio Pack
5. Sabaton Soundtrack(Volumes 1 and 2)
6. Allied Armor Pack
7. Allied Speeches Music Pack

**Longer Description of Issue:**
One of the breakaway states from the Level 3 Devastation collapse of Huttig's regime in GRO, is named "Republic Of Congo". It's ruling party is despotism and its government type is military junta, if that helps identify it. It has the "COG" tag.

The bug here is that this breakaway can still perform the focuses that RK Zentralafrika, which has the same tag, does. Not only that, it has all the previous ideas of RK Zentralafrika, like "Mercenary Army" and "The Call Of The Wild". However it does not have the Safari GUI. 

**Steps to Reproduce/Cause Issue:**

1.Play As Huttig until SAW, then win the SAW completely, with BOR completely annexing SAF

2.Continue Playing until you reach devastation level 3, at which point you must collapse and get the "African Devastation" Super event.

3.Open the console, then tag-switch over to COG (tag COG) to see that Republic Of Congo still has Muller's focus tree and can continue it

**Screenshots:**

![image](https://user-images.githubusercontent.com/95938523/145634113-1db31dce-0657-41aa-9985-ed77f785c350.png)

![image](https://user-images.githubusercontent.com/95938523/145634126-182b8771-dc69-4081-8e00-979f215143fb.png)

![image](https://user-images.githubusercontent.com/95938523/145634150-cfa95ab0-7f96-4997-9b43-eb591d0313a8.png)

![image](https://user-images.githubusercontent.com/95938523/145634203-7efcf7be-04f1-4ed0-b263-cc0ed3148bf0.png)

![image](https://user-images.githubusercontent.com/95938523/145634318-401032ba-f8f0-417e-9c01-cd9773f8e662.png)

![image](https://user-images.githubusercontent.com/95938523/145634337-460ec54e-7722-4a2a-b9f0-9da0071654e8.png)

![image](https://user-images.githubusercontent.com/95938523/145634350-9366a0e9-159b-4e04-97d7-5aa10c205f3c.png)

![image](https://user-images.githubusercontent.com/95938523/145634367-aae98709-775d-4480-8d28-c68868ea6273.png)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
