### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by RuSKazVG** [TNODevs/TNO-Bug-Tracker#3918]
### Operating System

Windows 10

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

Goring Expanded dev-version but that's hardly the problem

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Antarctic anarchy can join Comintern(presumably cuz anarchies are socialist)

### Steps to reproduce / Cause of the issue

1. Create Comintern
2. Enjoy

Just add AAN to an exception list of whom not to invite.

### Expected behaviour

NOT to have Antarctic anarchy in Comintern.

### Screenshots

![image](https://github.com/user-attachments/assets/2ede0b38-9c0c-4025-9864-3e58e6e583ab)

**Comment by Marok132** [comment]
It's already been fixed in #3865

**Comment by RuSKazVG** [comment]
cool
