### ISSUE TITLE
ULT - Missing Leader Name.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3923]
### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### List the loc issues below

![image](https://github.com/user-attachments/assets/65d452e5-c2e0-4dea-845c-a461e27e2edd)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a

**Comment by Marok132** [comment]
> Fixed for hotfix 1.7.0a

Thanks!
