### ISSUE TITLE
Orungus leader is missing

### ISSUE THREAD

**Issue by Codegoya** [TNODevs/TNO-Bug-Tracker#3925]
### Operating System

windows 11

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

No

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Orungus leader is randomly generated after peaceful decolonization by the us

### Steps to reproduce / Cause of the issue

1. Make The us win the saw
2. Decolonize congo
3. Look at orungu

### Expected behaviour

Orungu should have a leader

### Screenshots

![Captura de pantalla 2024-12-24 170142](https://github.com/user-attachments/assets/2dbdff24-31a9-4d71-8d2c-3f523be51bd8)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a
