### ISSUE TITLE
[Bug]: Argentina- Missing state name

### ISSUE THREAD

**Issue by Codegoya** [TNODevs/TNO-Bug-Tracker#3926]
### Operating System

windows 11

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

One of argentinas buenos aires state is missing its name

### Steps to reproduce / Cause of the issue

1.Click on argentina
2. Click on the state

### Expected behaviour

The state should have a name

### Screenshots

![Captura de pantalla 2024-12-24 170917](https://github.com/user-attachments/assets/ffbd8a4c-daa7-4e72-9ed2-57ea127f1438)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
