### ISSUE TITLE
GER - Getting Nordstern in some focuses despite it is already controls it

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3929]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title. 

### Steps to reproduce / Cause of the issue

Next focuses where Germany "gets" it:
BOR_reichs_guiding_hand
BOR_restablish_the_garrison1
BOR_successful_coup
BOR_restoring_proper_rule
BOR_resume_germanization1 (Gets a core despite Germany already has it)

### Expected behaviour

Remove getting Nordstern from these focuses because they do not make sense.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
