### ISSUE TITLE
United States - Philippine reconstruction completion button bugged

### ISSUE THREAD

**Issue by vallely1812** [TNODevs/TNO-Bug-Tracker#393]
•	Operating System: Windows 10

•	HOI4 Version: 1.10.8

•	TNO Version: 1.2.0d

•	Any other mods in use:
No.

•	Were you using Steam?
Yes.

•	Which expansions do you NOT have?
I have all major DLC.

Longer Description of Issue:
As the US I was reconstructing the Philippines post-blitz from in mid-late 1964. I reached 100% completion a few days before the deadline. However, the complete button wouldn't light up and I couldn’t select it despite big arrows pointing to it. 

Steps to Reproduce/Cause Issue:
1.	Start US game and have total control over the Philippines – after the 14th Army’s invasion.
2.	Pursue ‘Dismantle the forts’, ‘fight the banditos’, ‘enact spending controls’, ‘help in reconstruction’ in that order.
3.	Have 100% reconstruction progress and have big red arrows pointing to the button.

Screenshots:
![image](https://user-images.githubusercontent.com/95946430/145658164-90745e26-d466-45e0-8b53-c4310ea9b173.png)

**Comment by Scarsoftime** [comment]
There's an additional decision that you need to do. Apologies if this mechanic is a little bit unclear and/or too hard, it will be handled in the next patch.

**Comment by vallely1812** [comment]
Oh hi! Thank you for answering! What is the additional decision I need to do? If I know I might have a previous safe I could jump back to so I can try it out.
