### ISSUE TITLE
OFN Antarctica - Text escapes event box

### ISSUE THREAD

**Issue by turbobounce** [TNODevs/TNO-Bug-Tracker#3932]
### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

Music mods, the recall volunteer mod and the effect icon mod, TNO version.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

For the OFN Antarctica event "A Long Day", the second event option's text escapes the box it is in.
![image](https://github.com/user-attachments/assets/ed56731d-3715-47b8-87ff-05e103439382)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a
