### ISSUE TITLE
FGB - Missing Faction Status.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3933]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title.

### Steps to reproduce / Cause of the issue

Use these gamerules to reproduce:
![image](https://github.com/user-attachments/assets/60135806-8dd8-412e-9c79-77a29243abc5)

### Expected behaviour

It should have a faction status.

### Screenshots

![image](https://github.com/user-attachments/assets/4ab731c5-671c-4887-801f-96606c1fef88)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a

**Comment by Marok132** [comment]
> Fixed for hotfix 1.7.0a

Thanks!
