### ISSUE TITLE
New Zealand- Missing Leader

### ISSUE THREAD

**Issue by jonteboi0707** [TNODevs/TNO-Bug-Tracker#3935]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Bryan Tennyson does not have a portrait.

### Steps to reproduce / Cause of the issue

New Zealand elects Bryan Tennyson.

### Expected behaviour

Bryan Tennyson gets a portrait.

### Screenshots

![20241223191815_1](https://github.com/user-attachments/assets/286a1df3-d549-4f8c-9e9a-0154a4949b97)

**Comment by runelead00** [comment]
Fixed in Dev Build
