### ISSUE TITLE
YUN - Missing Decision Loc

### ISSUE THREAD

**Issue by Interesting2752** [TNODevs/TNO-Bug-Tracker#3936]
### Operating System

Windows 10

### HOI4 version

1.15.3.551d

### TNO version

1.7.0

### Do you have other mods in use?

TNO More Tank Slots+Tank Module, Zizek's Ideology Bling, Radio TNO, Immersive Music Mod (Comintern, China, and Non-Aligned)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA, AAT, TOA

### Describe the bug

Playing as Yunnan, I noticed that the title localization for some decisions relating to developing more resources and infrastructure was missing, seemingly using the debug name for these decisions.

### Steps to reproduce / Cause of the issue

1. Play as Yunnan
2. Get to Development Decisions (both for infrastructure and resources)
3. Finish prospecting decisions
4. See missing Loc

### Expected behaviour

I expected there to be a simple title relating to my development decisions, not just the debug name.

### Screenshots

![20241222210857_1](https://github.com/user-attachments/assets/c8a11445-ace1-43a0-817c-bc52d9d73a31)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a
