### ISSUE TITLE
Aryan Brotherhood- Clicking "Fiscal Crisis" alert opens Brazil election GUI

### ISSUE THREAD

**Issue by Socks2231** [TNODevs/TNO-Bug-Tracker#394]
**Questions**

- Operating System: Don't know
- HOI4 Version: 1.10.8
- TNO Version: Toolbox Theory
- Any other mods in use: 2WRW, Kamchatka, Ma Mod
- Were you using Steam?: Yes
- Which expansions do you NOT have?: All

**Longer Description of Issue:**
Clicking the fiscal crisis alert as the AB in 1963 opens the Brazil elections GUI.

**Steps to Reproduce/Cause Issue:**

1. Achieve fiscal crisis

2. Left Click alert

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/87985923/145663104-b15f64c6-84f6-42ec-874f-55116416f3d3.png)

**Comment by Scarsoftime** [comment]
2WRW is suspect, we failed to recreate this bug.
