### ISSUE TITLE
WRRF - Missing Loc

### ISSUE THREAD

**Issue by ReetheBro** [TNODevs/TNO-Bug-Tracker#396]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**
Missing localization in one of the choices in event "A Letter From the Front"

**Steps to Reproduce/Cause Issue:**

1. Start as WRRF

2. Annex Komi

3. Wait for the event "A Letter From the Front"

**Screenshots:**
![hoi4_8](https://user-images.githubusercontent.com/94774585/145683471-bda9ac2e-888b-4caa-9ba1-8901e03f45c0.png)

**Comment by Stormeagle449** [comment]
Fixed in dev build.
