### ISSUE TITLE
Yunnan - Xinan Reconstruction authority not rejoining the Sphere

### ISSUE THREAD

**Issue by PhoneythePhoneSaver** [TNODevs/TNO-Bug-Tracker#3961]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT

### Describe the bug

After defeating the NPA in the western insurrection, the Xinan Reconstruction Authority doesn't rejoin the CPS and stays in the Chinese league, also not being a puppet of China

### Steps to reproduce / Cause of the issue

1. Simply wait for when the NPA is defeated

### Expected behaviour

The Xinan Reconstruction Authority should rejoin the CPS and be a puppet of China

### Screenshots

![image (58)](https://github.com/user-attachments/assets/68c7c5c3-789e-4be9-872c-94c9066fee20)

**Comment by Marok132** [comment]
I've already reported it in #3846.

**Comment by PhoneythePhoneSaver** [comment]
My apologies, I'll close this then
