### ISSUE TITLE
Scotland - Missing Event in "Our Duties at Home' focus

### ISSUE THREAD

**Issue by PRaum1871** [TNODevs/TNO-Bug-Tracker#397]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.10.8
- TNO Version: v1.2.0d
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back

In the focus SCO_FEN_ILP_Victory_our_duties_at_home there is a missing event, the event SCO.1414 should launch upon completion of the focus but the id is invalid.

at the elections and HMMLR victory in the english civil war.

1. Have the Labour Party win the elections

2. Have the HMMLR win the civil war

3. From Right to Left, the last focus of the first branch will be the one with the issue.

(https://user-images.githubusercontent.com/96017488/145721990-334e2138-d831-4350-b03b-7dba854c6f3f.jpg)

**Comment by runelead00** [comment]
fixed in Dev Build
