### ISSUE TITLE
Kadet VYT-No reception with the ural warlords.

### ISSUE THREAD

**Issue by jonteboi0707** [TNODevs/TNO-Bug-Tracker#3977]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

1 I hade no reception with the ural warlords.
2 After i occupied the ural leauge and orenburg i got a peace treaty. But not one after i occupied the dirlewagner brigade.
3 My name got change back to Vyatka.

### Steps to reproduce / Cause of the issue

1 Play kadet Vyatka.

### Expected behaviour

None of this to happen.

### Screenshots

![20241226061900_1](https://github.com/user-attachments/assets/b8fc165a-1ded-498d-a907-8b0ebef20205)
![20241226061913_1](https://github.com/user-attachments/assets/78382734-359e-483d-a74e-16283acaee96)
![20241226061914_1](https://github.com/user-attachments/assets/c9272fa3-c8a1-464f-9ea2-5440a13a89e7)
![20241226061915_1](https://github.com/user-attachments/assets/c0e70122-f2a4-4702-bf9e-4ac393afef33)
![20241226063150_1](https://github.com/user-attachments/assets/64bedca4-592e-4ff0-9e48-1e3d3afe226a)

**Comment by runelead00** [comment]
Fixed in Dev Build
