### ISSUE TITLE
YUN - Game crushed due to possibly syntax error

### ISSUE THREAD

**Issue by Alvin0412** [TNODevs/TNO-Bug-Tracker#3978]
### Operating System

mac OS

### HOI4 version

v1.15.3.551d

### TNO version

v1.7.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[21:16:18][1966.10.08.01][persistent.cpp:68]: Error: "Unexpected token: division_template, near line: 2
Unexpected token: division_template, near line: 22
Unexpected token: division_template, near line: 40" in file: "history/units/VIN_GAW.txt" near line: 63
[21:16:18][1966.10.08.01][persistent.cpp:68]: Error: "Malformed token: Armored Division, near line: 67" in file: "history/units/VIN_GAW.txt" near line: 67

### Describe the bug

This bug will cause the game to crash whenever Longyun defeats Guangdong during the peace talk.

### Steps to reproduce / Cause of the issue

This issue is caused because the file "VIN_GAW.txt" declares "division_template" within the scope of "unit". 
It can be solved by simply declare division_template outside of that scope.

### Expected behaviour

The game is expected to continue

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
