### ISSUE TITLE
SBA - Selecting 'Fiscal Crisis' icon opens Brazil development UI

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#398]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 'Collie Anniversary'
- TNO Version: 1.2.0d
- Any other mods in use: Music mod, 2WRW (!! although likely unrelated) 
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Playing SBA, hit the more-or-less-unavoidable fiscal crisis, clicked the icon. The last nation I played was Brazil, although without the 2WRW mod enabled.

![image](https://user-images.githubusercontent.com/711467/145735663-b064ba55-d4fb-4da3-afe3-4187134df5f7.png)

**Comment by Scarsoftime** [comment]
Unable to recreate, 2WRW mod is the suspect of this bug's cause.
