### ISSUE TITLE
USA - Drops in stability and War Support, both during playthroughs and for AI. I think its to do with Haiti

### ISSUE THREAD

**Issue by USername2941** [TNODevs/TNO-Bug-Tracker#3981]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The USA gets drops in its stability and war support of around 20 % every month or so, this occurs to both the AI and the player. I think its to do with Haiti

### Steps to reproduce / Cause of the issue

I'm not sure - it just occurs for me, i think maybe war weariness in haiti but not sure

### Expected behaviour

The USA's stability remaining somewhat stable

### Screenshots

![image](https://github.com/user-attachments/assets/eaf88eb4-fe9d-427a-a54b-8d2d17afaa33)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
