### ISSUE TITLE
[Bug]: AFRSR (SPH) - OOBS still in Pangasinan despite not owning province

### ISSUE THREAD

**Issue by Vimicia** [TNODevs/TNO-Bug-Tracker#3982]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

With the new map update, Pangasinan, once part of the AFRSR, was given over to the SPR. But units for the AFRSR still remain in Pangasinan exiled, despite not owning the province. Could simply just be something that was forgotten to fix.

### Steps to reproduce / Cause of the issue

Units are spawned at the initial map loading

### Expected behaviour

OOBS in Pangasinan despite AFRSR not owning province

### Screenshots

![image](https://github.com/user-attachments/assets/ddacfd42-65b1-4193-9b99-192c7248b7d2)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
