### ISSUE TITLE
MCW - Custom Country Path Rules Triggering Opposite Event

### ISSUE THREAD

**Issue by Ighloa** [TNODevs/TNO-Bug-Tracker#3983]
### Operating System

Windows 10

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

Radio TNO, The New Order: Ideological Paradise, Updated TNO Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The current way Moskowien's country paths are implemented within the events file makes it so that the opposite of whatever path is selected happens. In the example below, the event for the civilian administration holding on is incorrectly tied to have a 0% chance of happening whenever the custom rule for the administration holding on is chosen.

### Steps to reproduce / Cause of the issue

Set Moskowien to any custom path

### Expected behaviour

Since each of Moskowien's CCP has only two outcomes, the opposite of whatever outcome was chosen will occur.

### Screenshots

![Screenshot (3427)](https://github.com/user-attachments/assets/c71501a3-2236-4c6d-94ad-c514bc208fc8)

**Comment by runelead00** [comment]
Fixed in Dev Build
