### ISSUE TITLE
ANG - in the Country Overview is said Reichskommissariat Südwestafrika  has no content.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3984]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title.

### Steps to reproduce / Cause of the issue

To start play Reichskommissariat Südwestafrika

### Expected behaviour

The Country Overview should say it has content.

### Screenshots

![image](https://github.com/user-attachments/assets/d4126585-881b-4db5-ac04-0639473f782f)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
