### ISSUE TITLE
RMB - Missing Leader

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3985]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title. After the GRO tag collapses there is not a leader for the RMB tag

### Steps to reproduce / Cause of the issue

Should GRO be collapsed at the third stage of devastation.

### Expected behaviour

The RMB tag should have a leader.

### Screenshots

![image](https://github.com/user-attachments/assets/d88aa19e-f1d2-405c-9b79-187957e32f8d)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
