### ISSUE TITLE
[Bug]: USA - Minnesota vps are off

### ISSUE THREAD

**Issue by Wolfstorm75** [TNODevs/TNO-Bug-Tracker#3988]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT, TOA

### Describe the bug

The victory points for most of the Minnesota towns are off. Mankato should be right next to the bend of the Minnesota River, Rochester should be further west, Duluth should be closer to the coast of Lake Superior, and finally St. Paul should be a little closer to Minneapolis. In addition to my screenshot, I'll include a detailed map to help for a more accurate placement.

### Steps to reproduce / Cause of the issue

1 Start Game
2 Zoom in on Minnesota

### Expected behaviour

VPs to be in the correct location

### Screenshots

![20241227084343_1](https://github.com/user-attachments/assets/4c460f62-6f52-47f6-b248-471b28bf4c64)
![minnesota-mn-political-map-with-capital-saint-paul-and-metropolitan-area-minneapolis-state-in-the-upper-midwestern-united-states-2J75KRB](https://github.com/user-attachments/assets/d4b5a94a-a5c4-462b-a10b-99f5e5c353a9)

**Comment by Stormeagle449** [comment]
Fixed for hotfix 1.7.0a
