### ISSUE TITLE
URL - in the Country Overview is said the Ural League has no content.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3989]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title.

### Steps to reproduce / Cause of the issue

To start play the Ural League

### Expected behaviour

The Country Overview should say it has content.

### Screenshots

![image](https://github.com/user-attachments/assets/d37078b3-cabc-48d2-9b53-f0f116e29cda)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
