### ISSUE TITLE
Failed to load the map

### ISSUE THREAD

**Issue by Kenny12121** [TNODevs/TNO-Bug-Tracker#399]
**Questions**

- Operating System: Window 10
- HOI4 Version: 1.11.2
- TNO Version: 1.2.0d
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I have it all

**Longer Description of Issue: I already un-install for many times and verify interigate the game but it's not working. Every time when I launch the game and I enable TNO mod and loading it always say "Failed to load the map" I already find so many solution in google but it's not working! Please help me.

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/96039859/145761501-85349c6d-9ca6-4698-8d82-4738068d8b44.png)

**Comment by runelead00** [comment]
TNO is not yet compatible with version 1.11, revert to 1.10.8 if you want to play TNO
