### ISSUE TITLE
BOR - Does not get a core on the Prince Edward Islands

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3991]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Afrika-Schild achieves a total victory in the SAF, Afrikaner Volkstaat does not get a core on the Prince Edward Islands.

### Steps to reproduce / Cause of the issue

Should Afrika-Schild achieve a total victory in the SAF.

### Expected behaviour

Afrikaner Volkstaat should get a core on the Prince Edward Islands.

### Screenshots

![image](https://github.com/user-attachments/assets/a2cfb511-e876-42de-ae4b-82a0e661189a)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
