### ISSUE TITLE
Any communist Russian tags - Can not invite any Socialist West African States in the COMECON

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3994]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

I can't invite socialist West African tags in the COMECON for unknown reasons.

### Steps to reproduce / Cause of the issue

Should the COMECON be created by any communist Russian tags. 

### Expected behaviour

The socialist West African states should be able to join the COMECON.

### Screenshots

![image](https://github.com/user-attachments/assets/82e930e0-6402-419b-90cf-4de4923a0bcc)
![image](https://github.com/user-attachments/assets/fcf3bf5f-9bfe-4b3f-874f-61e6c26f4ae6)
![image](https://github.com/user-attachments/assets/81b5eef9-ed59-40f5-8245-41cdce156cf1)

**Comment by runelead00** [comment]
Other than Chad, Working as Designed, as West Africa has its own factions + econ spheres, it's prevented from joining the current Comintern
