### ISSUE TITLE
JAP Operation Big Stick massive rise in tension

### ISSUE THREAD

**Issue by TheDon1324** [TNODevs/TNO-Bug-Tracker#3997]
### Operating System

Windows 11

### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Operation Big Stick repeats itself and causes 100% tension between USA and Japan.

### Steps to reproduce / Cause of the issue

Play as Japan and have Indian Civil War 

### Expected behaviour

Only increase tension by 15%

### Screenshots

![20241228154448_1](https://github.com/user-attachments/assets/54225fe5-16fe-45d7-a9bf-9297d9476910)

### Additional information

I used commands for my peer and public support before during and after civil war, messed with ruling party popularity later and PP but that was after the civil war

**Comment by vishwathg** [comment]
Seconded, this happens to me in every game and I don't use console commands and all

**Comment by runelead00** [comment]
Fixed in Dev Build
