### ISSUE TITLE
[Bug]: Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Samcnut** [TNODevs/TNO-Bug-Tracker#3999]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

State in Argentina is missing Localisation

### Steps to reproduce / Cause of the issue

Click on the state near Buenos Aires

### Expected behaviour

It's wrong

### Screenshots

![image](https://github.com/user-attachments/assets/94a233f4-20be-47c9-b7cc-0e7d86534b9e)

**Comment by Marok132** [comment]
TNO devs have already fixed it in #3926.
