### ISSUE TITLE
NPA (YUN) - Typos

### ISSUE THREAD

**Issue by runelead00** [TNODevs/TNO-Bug-Tracker#40]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: Radio TNO

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [x] 1. Capitalization of spirit name
![typo1](https://user-images.githubusercontent.com/74165171/128591762-d0607273-045b-43ba-914e-ba4c5b199785.jpg)
- [x] 2. Sphere not capitalized, Zaibatsus misspelt as Zaibatus
![typo2](https://user-images.githubusercontent.com/74165171/128591764-8edfb957-c17f-443b-b22c-4527dd5e8909.jpg)
- [x] 3. landlords and bite capitalized for some reason, spasm(?) misspelt as sasm
![typo3](https://user-images.githubusercontent.com/74165171/128591766-244202f6-d417-4b31-a0a8-fc6f35ef2f6c.jpg)
- [x] 4. sergeant misspelt as seargent, villages misspelt as villagees 
![typo4](https://user-images.githubusercontent.com/74165171/128591769-7cc721a3-7c09-4c8b-b0e8-a7c660c274e2.jpg)
- [x] 5. Mission title capitalization
![typo5](https://user-images.githubusercontent.com/74165171/128591770-bf655b5f-fd3f-49ec-9dc5-411c45285db4.jpg)
- [x] 6. National Liberation not capitalized, is capitalized elsewhere 
![typo6](https://user-images.githubusercontent.com/74165171/128591772-c9b2a0fc-0a3a-43e6-90db-32751321bc47.jpg)
- [x] 7. coal and iron capitalized
![typo7](https://user-images.githubusercontent.com/74165171/128591775-7d22b20f-9c5d-4810-a913-c534ec9cb35f.jpg)
- [x] 8. woman's missing ', glorious misspelt as glorius
![typo8](https://user-images.githubusercontent.com/74165171/128591778-ef3a34f1-9664-49f1-9296-711a12acef46.jpg)
- [x] 9. Mandate of Heaven not capitalized, Emblazon misspelt as Embazon
![typo9](https://user-images.githubusercontent.com/74165171/128591781-0f938c59-aa62-4e31-ac8b-e8b25c3bdc22.jpg)
- [x] 10. Sphere, Chinese not capitalized, traitor's missing '
![typo10](https://user-images.githubusercontent.com/74165171/128591782-91694b88-c26c-4012-873d-f22f12b7b817.jpg)
- [x] 11. Southwest not capitalized, is capitalized in Yunnan's first tree
![typo11](https://user-images.githubusercontent.com/74165171/128591795-7891d1b1-956b-4bf4-aca9-00ad69596b40.jpg)
- [x] 12. 200 should be 100, 100 is actual cap
![typo12](https://user-images.githubusercontent.com/74165171/128591797-b2b36c1b-15a1-4f6c-9949-4f9ff5e8a295.jpg)
- [x] 13. Focus title capitalized
![typo13](https://user-images.githubusercontent.com/74165171/128591798-e80cb74d-57fb-4229-be84-52cb94704876.jpg)
- [x] 14. Great Wall not capitalized
![typo14](https://user-images.githubusercontent.com/74165171/128591799-2618760e-a75b-457d-b904-517f184b2b46.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build.
