### ISSUE TITLE
Germany-Minor graphic error

### ISSUE THREAD

**Issue by mapu1283** [TNODevs/TNO-Bug-Tracker#400]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: v1.2.0d
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back,Armor Pack

**Longer Description of Issue:**
As a result of the game update, Brest and Kalinkovichi became Rk ukraine territory. But some system(Speer,Heydrich),
decision and focus still do not reflect it. (If you look at the screenshot, Brest and Kalinkovichi are incorrectly attached to Ostland.)

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**
![speer](https://user-images.githubusercontent.com/95910611/145829701-27168a35-32c1-4864-8f55-62748ef9a3cd.jpg)
![heydrich](https://user-images.githubusercontent.com/95910611/145829710-e3772d82-503e-4cdb-855d-65411791baba.jpg)
![speerdecision](https://user-images.githubusercontent.com/95910611/145829713-e66d39fc-a9cb-429d-9bc4-c41c49351790.jpg)
![heydrichfocus](https://user-images.githubusercontent.com/95910611/145829715-494b98f1-60cc-4d39-9241-64c452a1f0d2.jpg)

**Comment by runelead00** [comment]
Assets relating to current Germany and the RKs are not a priority going to be reworked until their respective updates
