### ISSUE TITLE
AMR - Typo in focus description

### ISSUE THREAD

**Issue by McSpain** [TNODevs/TNO-Bug-Tracker#4001]
### HOI4 version

1.15.3

### TNO version

1.7.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

in "AMR_external_pathogen_attacking_us" it must read "yet insidious in their action" instead of "yet insidious in THERI action"
![image](https://github.com/user-attachments/assets/a8ab1863-b3b1-4502-b3c2-57da36863f51)

**Comment by runelead00** [comment]
Fixed in Dev Build
