### ISSUE TITLE
NOR - A Missing Portrait for a foreign minister

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#4002]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The title.

### Steps to reproduce / Cause of the issue

To add a portrait for him.

### Expected behaviour

He should have a portrait.

### Screenshots

![image](https://github.com/user-attachments/assets/8be0b7b5-58d6-44d1-9988-40a52ecfa035)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
