### ISSUE TITLE
BHU and SIK - Don't become subjects of Reunited India

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#4003]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

Once the Lucknow Conference is successful and India is reunited, Bhutan and Sikkim don't become subjects of new India despite they are ones for Azad Hind. I think it's a bug because both tags are still dependent from India.

### Steps to reproduce / Cause of the issue

Should the Lucknow Conference be successful.

### Expected behaviour

Bhutan and Sikkim should be subjects of Reuinted India.

### Screenshots

![image](https://github.com/user-attachments/assets/13210cd1-1569-422d-96db-915bf79dc37b)
![image](https://github.com/user-attachments/assets/bdefb6a9-015a-4821-9a90-7dc2e7797101)
![image](https://github.com/user-attachments/assets/7fcbda0c-17de-43bb-9982-73f5126edf8c)

### Additional information

Also Reuinted India does not inheirt Azad Hind's generals.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
