### ISSUE TITLE
BHU and SIK - Missing Faction Ideas

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#4004]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Rajagopalachari's India joins the OFN, its subjects like Bhutan and Sikkim don't get faction ideas.

### Steps to reproduce / Cause of the issue

1. The Lucknow Conference is failure.
2. The Republic of India wins in the IRW.
3. Rajagopalachari is elected.

### Expected behaviour

Bhutan and Sikkim should get faction ideas.

### Screenshots

There are not Bhutan and Sikkim tags in this event.
![image](https://github.com/user-attachments/assets/55ba69b6-aafd-4473-a98b-d9a1f2882c60)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
