### ISSUE TITLE
Guangdong - Looking at one of Morita's end focusis crashes the game

### ISSUE THREAD

**Issue by Memelord058** [TNODevs/TNO-Bug-Tracker#4006]
### Operating System

Windows 11

### HOI4 version

1.15.3.551d (beea) (s)

### TNO version

1.7.0

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/user-attachments/files/18276766/error.log)
[game.log](https://github.com/user-attachments/files/18276768/game.log)

### Describe the crash

After I as the usa clicked on Guangdong's focus tree i saw that there were no icons so i then hoverd over one and then my game crashed

### Steps to reproduce / Cause of the crash

Go to Guangdong focustree then hover over one of them

### Screenshots

![394360_43](https://github.com/user-attachments/assets/95b4055f-b72a-49ee-8a99-191ad1281bed)

**Comment by runelead00** [comment]
Fixed in Dev Build
