### ISSUE TITLE
IRL - No Elections Issue 

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#4008]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When the Democratic Republic of Iran prevails in the civil war, the game sets No Elections for it despite it is fully funtional democracy.

### Steps to reproduce / Cause of the issue

Should the Democratic Republic of Iran wins in the civil war.

### Expected behaviour

The game should not set No Elections.

### Screenshots

![image](https://github.com/user-attachments/assets/ca972edf-3c1f-4013-aef5-7c8c46c1a3a6)

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Marok132** [comment]
> Fixed in Dev Build

Thanks!
