### ISSUE TITLE
WRRF - Becomes USSR at Superregional Unification

### ISSUE THREAD

**Issue by ReetheBro** [TNODevs/TNO-Bug-Tracker#401]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**
The West Russian Revolutionary Front becomes the Union of Soviet Socialist Republics at superregional unification. National unification not affected.

**Steps to Reproduce/Cause Issue:**

1. Be WRRF

2. Unite Western Russia and Western Siberia

**Screenshots:**
![hoi4_9](https://user-images.githubusercontent.com/94774585/145858135-28d68da1-b77a-4b3e-a4a6-5c93129e54d0.png)

**Comment by bigbadboy78** [comment]
That's normal iirc

**Comment by ReetheBro** [comment]
I don't think it is, the first focus after superregional mentions renaming themselves as the Russian Federative Soviet Socialist Republic instead of the USSR

**Comment by masterbobli** [comment]
I'm pretty sure that it's an intentional feature, but I couldn't remember why that was changed.
