### ISSUE TITLE
Russia/Antarctica - Wasteland joins COMECON/Comintern

### ISSUE THREAD

**Issue by PugAnims** [TNODevs/TNO-Bug-Tracker#4014]
### Operating System

Windows 10

### HOI4 version

1.15

### TNO version

1.15

### Do you have other mods in use?

The New Order: Last Waltz Expanded (music mod)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Files

![image](https://github.com/user-attachments/assets/3abc54fc-d924-4972-9403-7899b81ce7fb)
![image](https://github.com/user-attachments/assets/adfa7989-d5eb-4e78-aed4-fdc336836374)
![image](https://github.com/user-attachments/assets/3a65b5f9-35b1-452f-b9be-268be6beff0b)

### Describe the bug

Antarctic Wastes is able to join the comintern as a member. They can vote on policy, request economic aid, add to the fund, and everything else comintern members can do.

### Steps to reproduce / Cause of the issue

1. Play a nation that can form the Comintern
2. Form it
3. Invite the nation that displays no name
4. Antarctic Wastes has joined!

### Expected behaviour

Only governed regions of the globe being able to join an economic alliance.

**Comment by runelead00** [comment]
Fixed in Dev Build
