### ISSUE TITLE
Moskowien - Game Rules Don't Work/Oktan Only

### ISSUE THREAD

**Issue by BigComp** [TNODevs/TNO-Bug-Tracker#4016]
### Operating System

Windows 11

### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the bug

None of the game rules I used for Moskowien (Globocnik victory) have worked, and instead they just result in Oktan coming to power every time. Even without game rules, he still becomes leader.

### Steps to reproduce / Cause of the issue

1. Set any game rules for Moskowien that are not Oktan winning
2. Wait until Moskowien gets their leader

### Expected behaviour

The leader specified in the game rules is supposed to become the leader of Moskowien, not Oktan

### Screenshots

![20241230010533_1](https://github.com/user-attachments/assets/6dcec94c-ab92-47fc-8daf-7e140b66e1fa)

**Comment by runelead00** [comment]
Fixed in Dev Build
