### ISSUE TITLE
United States of Siberia - Trade Law is Blank

### ISSUE THREAD

**Issue by LateNightCK** [TNODevs/TNO-Bug-Tracker#402]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? Have all expansions

**Longer Description of Issue:**
The trade law in the political screen does not show anything and appears blank. It however appears in the intel screen. It seems to be affecting the game since not a lot of my resources have been traded and my economy has stagnated.

**Steps to Reproduce/Cause Issue:**

1.  I haven't encountered this bug, I don't know what to reproduce it. 

2.

etc...

**Screenshots:**
https://user-images.githubusercontent.com/96087949/145897248-c7774c7d-a20c-4fcf-9741-d6de01fb6e56.png
https://user-images.githubusercontent.com/96087949/145897555-ab563910-887b-4b90-9f75-298009647367.png

**Comment by Stormeagle449** [comment]
Fixed for UB.
