### ISSUE TITLE
PAK - Game Rule Text Has Wrong Color

### ISSUE THREAD

**Issue by BigComp** [TNODevs/TNO-Bug-Tracker#4021]
### HOI4 version

1.15.2

### TNO version

1.7.0

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### List the loc issues below

1. Feroz Khan Noon's Reelection Description in the Pakistan Election game rule has a bugged color for most of it
![20241231003227_1](https://github.com/user-attachments/assets/67262cee-11d8-4844-8a45-8023fbf9010f)

**Comment by runelead00** [comment]
Fixed in Dev Build
