### ISSUE TITLE
Speer Germany, not getting Remer as general

### ISSUE THREAD

**Issue by DieuMivas** [TNODevs/TNO-Bug-Tracker#404]
**Questions** 

- Operating System:
- HOI4 Version:1.10.8
- TNO Version:v1.2.0d
- Any other mods in use: No
- Were you using Steam? Yes 
- Which expansions do you NOT have?
--Battle for the Bosphorus
--No Step Back

**Longer Description of Issue:**
The event "Never a traitor" giving you, playing as Speer, Otto Ernst Remer as a general doesn't actually give him as a general

**Steps to Reproduce/Cause Issue:**
Play as Speer and wait for the event to po up or 
Execute event speer_slaverevolt.33

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Dev Build
