### ISSUE TITLE
Bennett USA - Sending more advisors to Free Indonesia does not allow me to send more volunteers.

### ISSUE THREAD

**Issue by FrozenCube420** [TNODevs/TNO-Bug-Tracker#406]
**Questions**

- Operating System: Windows 10 Hoi4
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I have no expansions.

**Longer Description of Issue:**
I took the decision to increase advisors two times, but it only let me send over one volunteer.

**Steps to Reproduce/Cause Issue:**

1. Have Bennett as president.

2. Take the decision to increase advisors to Free Indonesia.

3. Attempting to send more volunteers to Free Indonesia will be blocked.

**Screenshots:**
![image](https://user-images.githubusercontent.com/96207746/146265330-a527f627-b42c-4183-8220-f8ff3c9e3ef3.png)
![image](https://user-images.githubusercontent.com/96207746/146265376-5f70bf7c-40a5-475a-92dd-a0e972360de0.png)

**Comment by Kurgis** [comment]
> Left-click on the country's province, right click, exit the diplomatic menu, right click again, send volunteers.
If it still doesn't work keep left-clicking random provinces before right clicking your target again to open their diplomatic menu after closing it.

**Comment by runelead00** [comment]
merged into #1212 , possible solution taken from comment here
