### ISSUE TITLE
Iran - capitulating a nation during the iranian civil war prior to the break-up of the alliance causes an endless war with that nation

### ISSUE THREAD

**Issue by demanvanwezel** [TNODevs/TNO-Bug-Tracker#407]
**Questions**

- Operating System: windows 10
HOI4 Version: 1.10.8
TNO Version: 1.2.0.d
Any other mods in use: non
Were you using Steam? yes
Which expansions do you NOT have? no step back
**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1. fire the iranian civil war

2. capitulate one nation of the alliance (easiest would be the communists since they're isolated)

3. get the break-up of the alliance

4. finish of the rest of the alliance

5. iran should still be at war with the nation you capitulated who doesn't have any lands

**Screenshots:**

**Comment by FunkyDepression** [comment]
I actually got this to work with the rest of the factions in the civil war.
![image](https://user-images.githubusercontent.com/96454816/146867985-020cf212-8b0c-4f3c-bd2d-2e972a1c29cb.png)

**Comment by runelead00** [comment]
Fixed in Current Release
