### ISSUE TITLE
National Protection Army - GAW High Legitimacy Super Event music glitch

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#410]
**Questions**

- Operating System: Windows 10
- HOI4 Version:1.10.8
- TNO Version:v1.2.0d
- Any other mods in use: Second West Russian War, Terra e Liberta, Terra e Liberta Expanded, Sensible Map Font
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**
After I pressed the button of the news article saying Japan is at war with NPA, the super event window with Mao Zedong's quote appears on the screen, but the music that usually comes with the super event does not play.

**Steps to Reproduce/Cause Issue:**

1. Tag Switch to multiple nations, including NPA. (main nation playing Novosibirsk)

2. Massively use commands on NPA and other commands, including manpower, stability, war support buffs, instant construction etc.

3. Use tag switching and commands to do most of the decisions controlling other nations, including NPA.

4. Get below glitch.

https://user-images.githubusercontent.com/96382658/146681886-0c4a6bd7-973a-42db-86f1-43a053722f0c.mp4

 

**Screenshots:**

**Comment by tkgitno** [comment]
Fixed in Dev Build
