### ISSUE TITLE
Any(?) - Uranium Crisis Missing Loc

### ISSUE THREAD

**Issue by ReetheBro** [TNODevs/TNO-Bug-Tracker#411]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them.

**Longer Description of Issue:**
"The Start of the Uranium Crisis" world event has missing localizations and images.

**Steps to Reproduce/Cause Issue:**

1. Somehow get John Glenn to Presidency (It seems to be an event from him, I don't really know, I was using the Divine Mandate when this happened)

2. Wait(?)

**Screenshots:**
![hoi4_14](https://user-images.githubusercontent.com/94774585/146685852-7fa77d91-00cf-4a2b-b7e7-6af340edc3a5.png)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
