### ISSUE TITLE
Aryan Brotherhood - Missing advisor portrait

### ISSUE THREAD

**Issue by Dissatisfaction** [TNODevs/TNO-Bug-Tracker#412]
**Questions**

- HOI4 Version: Collie 10.7(?) (the pre NSB one)
- TNO Version: Current edition
- Any other mods in use: Radio TNO but probably not relevant

Tristan Schmidt portrait not showing.

![A7B76EBB-BB45-45C3-A492-CBA5C54A97D2](https://user-images.githubusercontent.com/83587467/146759974-42fbe24e-c43d-493f-aff4-d0a081580470.jpeg)

**Comment by runelead00** [comment]
Fixed in Dev Build
