### ISSUE TITLE
Iranian Civil War - Pre-Revolution Collapse Breakdown

### ISSUE THREAD

**Issue by FunkyDepression** [TNODevs/TNO-Bug-Tracker#414]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Terra è Liberta
- Were you using Steam? Yes
- Which expansions do you NOT have? All; I don't have any expansions.

**Longer Description of Issue:**
I was able to defeat the Democrats, Shahs, Islamists, and Balochis in the Iranian Civil War before the Revolutionary Alliance collapse, so the Iranian Civil War never finished. The event for Imperial Victory never fired and Iran did not join the Einheitspakt.

**Steps to Reproduce/Cause Issue:**

1. Wait for the Middle East to blow up

2. Shah gets shot, starting Iranian Civil War

3. Intervene as usual

4. Blitz any faction in the Revolutionary groups **BEFORE** Revolutionary Front (I forget what it's called) collapses
     - I got the liberals, monarchists, islamists, and balochis to capitulate as seen in the image below before the event for infighting fired, I don't know if this glitch applies to the commies but I expect it would.

5. Profit (???)

**Screenshots:**
![image](https://user-images.githubusercontent.com/96454816/146863623-49a6422e-5ec7-4801-bf87-63d2a9024b25.png)

**Comment by FunkyDepression** [comment]
suffering from success

**Comment by masterbobli** [comment]
Should have been fixed... I couldn't replicate this issue on the latest dev build
