### ISSUE TITLE
Germany (Bormann) - Extra space in bormann.1552.d

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#416]
**Questions**

- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod

Literally unplayable
![image](https://user-images.githubusercontent.com/711467/147042857-950d444d-86b1-4bef-a3e2-1f1b65c81b5e.png)
Literally unplayable

**Comment by Scarsoftime** [comment]
Fixed
