### ISSUE TITLE
Borman Germany - Wrong effect in Congolese Civil War intervention

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#417]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

'Authorize Bombing Sorties' has the wrong effect (sending equipment).

**Screenshots:**
![image](https://user-images.githubusercontent.com/711467/147043954-2d24e384-50d0-45c0-a17d-58ea7bc53bc0.png)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
