### ISSUE TITLE
Einheitspakt Credit Rating GUI - Max credit rating below minimum credit rating

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#418]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

Occurred after taking the 'A Message' focus in Bormann Germany in mid-'67. Believe it's due to my maximum credit rating being below my minimum credit rating - not sure if it's a graphical issue or a coding issue.

**Screenshots:**

![image](https://user-images.githubusercontent.com/711467/147050025-302918b7-fa8a-493e-9ff2-b62368d240b8.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
