### ISSUE TITLE
Mandate Angola - Angola decolonization doesn't work with equal strength between factions

### ISSUE THREAD

**Issue by PeaJam** [TNODevs/TNO-Bug-Tracker#420]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Collie v1.10.8
- TNO Version: Don't know how to check this but it should be the most recent version
- Any other mods in use: Radio TNO: Music of the New Order
- Were you using Steam? Yes
- Which expansions do you NOT have? Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, Battle for the Bosporus, No Step Back

**Longer Description of Issue:**
Angolan decolonization doesn't work with equal strength between factions, in the event when the new leader is chosen the option just says "Ok" and no further events fire

**Steps to Reproduce/Cause Issue:**
[Angola bug.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7760848/Angola.bug.zip)

1. If you open the file and play as Angola the event should be right there.

**Screenshots:**
![20211222204604_1](https://user-images.githubusercontent.com/67983811/147055636-b42ec94a-9d72-4261-bed9-7fda7202db73.jpg)

**Comment by runelead00** [comment]
Fixed in Current Release
