### ISSUE TITLE
Mandate Angola - Event "The Namibian Renegade" gives incorrect faction strength

### ISSUE THREAD

**Issue by PeaJam** [TNODevs/TNO-Bug-Tracker#421]
**Questions**

-Operating System: Windows 10
-HOI4 Version: Collie v1.10.8
-TNO Version: Don't know how to check this but it should be the most recent version
-Any other mods in use: Radio TNO: Music of the New Order
-Were you using Steam? Yes
-Which expansions do you NOT have? Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, Battle for the Bosporus, No Step Back

**Longer Description of Issue:**
The event "The Namibian Renegade" gives 8 strength to the selected faction, rather than the stated 10

**Steps to Reproduce/Cause Issue:**
[Nambian Renegade.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7761012/Nambian.Renegade.zip)

1.Open the attached save file

2.Select one of the options in the event and compare the before and after of the faction strengths

**Screenshots:**
![20211222205830_1](https://user-images.githubusercontent.com/67983811/147058310-79cb512d-4721-400a-8724-31e863fccc68.jpg)
![20211222205835_1](https://user-images.githubusercontent.com/67983811/147058332-0ddad830-f343-4034-a13a-4f09aeb9d7ed.jpg)
![20211222205908_1](https://user-images.githubusercontent.com/67983811/147058350-ea879623-7276-441e-895d-0087279bd37f.jpg)
![20211222205911_1](https://user-images.githubusercontent.com/67983811/147058367-9f243e8b-9e8f-43a4-b96e-f87e03e05ebb.jpg)

**Comment by runelead00** [comment]
Fixed on UB
