### ISSUE TITLE
SBA - Clicked on an annexed country on the trade screen and had the game CTD

### ISSUE THREAD

**Issue by ArneHD** [TNODevs/TNO-Bug-Tracker#422]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: Toolbox Theory / Latest as of 22/12-2021
- Any other mods in use:
-       - 12 Support Companies https://steamcommunity.com/sharedfiles/filedetails/?id=1653932883
-       - New Order: Custom Country Paths https://steamcommunity.com/sharedfiles/filedetails/?id=2191657102
-       - TNO: Second West Russian War https://steamcommunity.com/sharedfiles/filedetails/?id=2514593219
-       - Toolbox https://steamcommunity.com/sharedfiles/filedetails/?id=1417069016
- Were you using Steam? Yes
- Which expansions do you NOT have? None

Was playing as the Siberian Black Army after unifying Central Siberia. Looked at my trade screen and noticed that the flag of Tomsk (which I had annexed) was shown. Clicked the flag and CTD'd.

**Steps to Reproduce/Cause Issue:**

1. Annex nation.

2. See if Nation appears on Trade screen.

Should CTD.

**Game Saves and Log Files, if possible:**
[hoi4_20211222_182746.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7764287/hoi4_20211222_182746.zip)

**Comment by runelead00** [comment]
Fixed in Dev Build
