### ISSUE TITLE
Bormann Germany - speer.10003.t repeatedly firing

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#423]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
I'm playing as Bormann in the early 1970s. An event called `speer.10003.t` briefly appears once per day in the decisions window (this has been occurring for years). See video.

**Screenshots:**
![image](https://user-images.githubusercontent.com/711467/147302376-3af76b4c-186a-48d2-8840-d1df5df77a61.png)

https://user-images.githubusercontent.com/711467/147302538-e8aa849b-5c98-4b48-b7de-912a6a490752.mp4

**Comment by TeddyRooseveltFan12345678910** [comment]
This has also happened to me 
![image](https://user-images.githubusercontent.com/81603664/147886054-5fe38ccc-3875-4d89-89fd-5e95d1336a25.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
