### ISSUE TITLE
USA - Overwriting bills

### ISSUE THREAD

**Issue by br54** [TNODevs/TNO-Bug-Tracker#425]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d "TT"
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? I have them all

**Longer Description of Issue:**

I'm not 100% sure this one's a bug. During the Glenn Presidency in his closing the Empathy deficit there doesn't seem to be anything stopping me from introducing multiple bills into the senate. For example, the Ending Right to Work introduces the Labor Reforms Act but there's nothing stopping me from taking the Unkept Promise act which introduces the Social Security Act, this has the effect of overwriting the Labor Reforms Act. The LRA can still be passed but once it is the SSA doesn't show up to tell me which senators I need  to get support from to pass it.

**Steps to Reproduce/Cause Issue:**

1. Finish the Ending Right to Work focus in Glenn's Focus Tree

2. Immediately follow up on that by finishing the Unkept Promises focus 

3. The LRA bill becomes the SSA bill and once the LRA bill passes you can no longer see the support for the SSA bill.

**Comment by runelead00** [comment]
No longer an issue with Gleen removal, and updated triggers for requirements for focuses that start bills
