### ISSUE TITLE
Mexico - Gustavo Días Ordas' leader description has a small typo.

### ISSUE THREAD

**Issue by PedroPigeon** [TNODevs/TNO-Bug-Tracker#427]
**Questions**

- HOI4 Version:1.10.8
- TNO Version: 1.2.0.d
- Any other mods in use: Spot optimization, FPS map

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
In the third paragraph of Días Ordas description, the word "Teen" at the start of the paragraph has a missing "T" in it.
- [ 
![hoi4_7](https://user-images.githubusercontent.com/50126537/147375562-11e27a1e-da33-42ed-9510-8eb2f6935bc2.png)
] 1.

**Comment by runelead00** [comment]
Fixed on UB
