### ISSUE TITLE
Collab Britain  - Atlantic Battleground

### ISSUE THREAD

**Issue by agscaesar** [TNODevs/TNO-Bug-Tracker#429]
**Questions**

- Operating System:
- HOI4 Version: 1.10.8
- TNO Version: TT 1.12?
- Any other mods in use: Only TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Atlantic Battleground will stop giving monthly points to britain after going above 3 monthly tick, which makes it nigh impossible. Additionally after the mission 'britain stays independent' is completed britain will still join the Pakt as the mission does not cancel.
Also the economic sphere of britain is only called "No Sphere"
**Steps to Reproduce/Cause Issue:**

1. Play as Thatcher

2. Initiate Atlanticbattleground

3. Go above 3 monthly tick

**Screenshots:**
![20211225111408_1](https://user-images.githubusercontent.com/95180219/147382870-c0eeb0a0-a5a2-4507-906d-9e40fdf443df.jpg)
![20211224234354_1](https://user-images.githubusercontent.com/95180219/147382879-10d09903-6a3a-400e-95c0-893cb0c34ef1.jpg)

**Comment by agscaesar** [comment]
Edit: version is 1.20d

**Comment by runelead00** [comment]
Fixed in Current Release
