### ISSUE TITLE
Brazil- Sell Armoured personnell carriers in the South African War decisions menu actually buys them

### ISSUE THREAD

**Issue by Jaggedmallard** [TNODevs/TNO-Bug-Tracker#430]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: Latest
- Any other mods in use: The Moe Order
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back, La Resistance

**Longer Description of Issue:** The Decision for selling armoured personnel carriers to the South Africans as part of the South African War proxy war interface currently does not actually sell them and instead buys them. The buy decision also buys them. It should instead sell them like the other sell decisions

**Steps to Reproduce/Cause Issue:**

1. Play as brazil until the South African War starts

2. Intervene in the South African War
3.  Check the decisions menu, the sell APCs option will buy instead of sell

etc...

**Screenshots:** https://i.imgur.com/jkvKFBK.png

**Comment by runelead00** [comment]
Fixed on UB
