### ISSUE TITLE
Western Revolutionary Front divisions unassigned on load and CTD after unpausing

### ISSUE THREAD

**Issue by Vivaldist** [TNODevs/TNO-Bug-Tracker#431]
**Questions**

- Operating System: Win7
- HOI4 Version: 10.8
- TNO Version: 1.2.0.d
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? no step back

**Longer Description of Issue:**
Playing as western revolutionary front. Game operated as normal. Tried to load an older save to make a different decision. Upon load, all of my assigned divisions were unassigned, and the division assignment profile pictures at the bottom were missing. Crashes to desktop as soona s I unpause.
**Steps to Reproduce/Cause Issue:**

1. Load game

2. Unpause

etc...

**Screenshots:**

![image](https://user-images.githubusercontent.com/27928005/147704122-aadf6256-c334-4cd4-8e83-0158df791cfc.png)

**Game Saves and Log Files, if possible:**
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7790667/error.log)

**Comment by runelead00** [comment]
Appears to be an issue with cloud saving, turning off cloud saves should fix this issue
