### ISSUE TITLE
USA- LBJ Cape of Good Hope Resolution Volunteers

### ISSUE THREAD

**Issue by MrSparkles5017** [TNODevs/TNO-Bug-Tracker#433]
- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: TT
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? Have all expansions

Upon taking the Cape of Good Hope Resolution foci as LBJ instead of being allowed to send more divisions to the SAW instead am allowed to send 8 division to Italy instead.

Steps to Reproduce- Take Cape of Good Hope Resolution focus as LBJ

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting.
