### ISSUE TITLE
ENG - Fair Employment Act Replaces All Acts After Completing the Focus

### ISSUE THREAD

**Issue by Pieman90** [TNODevs/TNO-Bug-Tracker#434]
**Questions**

- Operating System: Win10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: music mod & larger plane gui
- Were you using Steam? yes
- Which expansions do you NOT have? using all 

**Longer Description of Issue:**
The Fair Employment Act seems to override any subsequent acts you attempt to pass all becoming said act
**Steps to Reproduce/Cause Issue:**

1. The Road Will Be Hard -> Fair Employment Act

2. After completing the act all other acts should now be FEA instead of whatever act should be loaded in
Should be noted a lot of the acts in the 2nd term also don't check if you have another act running like indirect taxation act
3. Enjoy Promoted Equality

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
