### ISSUE TITLE
Terra e Libertà - Map Bug

### ISSUE THREAD

**Issue by mapu1283** [TNODevs/TNO-Bug-Tracker#435]
**Questions**

- Operating System:Windows 10
- HOI4 Version:1.10.8
- TNO Version:v1.2.0d
- Any other mods in use:Terra e Libertà
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back,Armor Pack

**Longer Description of Issue:**

This error appears in Terra e Libertà and Terra e Libertà Expanded mod.

![bug1](https://user-images.githubusercontent.com/95910611/147849409-3e67bdeb-66a6-4cd1-b5c5-fea8e7fc2315.jpg)

1. There is a large white object near Okinawa and Iwo Jima Island.

![bug2](https://user-images.githubusercontent.com/95910611/147849412-ee98350f-5b33-49f8-8e8a-7724d1d46da1.jpg)

2. The two islands that originally existed, 'Pitcairn Island' and 'Isla de Pascua' have disappeared, and Pitokean-to is taking over.

![1](https://user-images.githubusercontent.com/95910611/147849538-d7afe72b-5e3e-4cc0-a868-d98e28d1f0df.jpg)
![2](https://user-images.githubusercontent.com/95910611/147849540-2545dafa-ec75-435b-b0a1-d48c84091dc8.jpg)

This picture is original map.

**Comment by mapu1283** [comment]
Maybe The South Pacific part has been updated in TT, but it doesn't seem to be reflected.

**Comment by runelead00** [comment]
Fixed in Dev Build
