### ISSUE TITLE
Game crashing on load

### ISSUE THREAD

**Issue by ghost** [TNODevs/TNO-Bug-Tracker#436]
**Questions**

- Operating System: both Windows 11 PRO 21H2 and Kubuntu 21.10
- HOI4 Version: both 1.10.5 and 1.10.8
- TNO Version: 1.2.0d from Steam Workshop
- Any other mods in use: No
- Were you using Steam?: Yes
- Which expansions do you NOT have?: None

**Longer Description of Issue:**
I have tried to launch HOI4 (both 1.10.5 and 1.10.8) on both Windows 11 PRO 21H2 and Kubuntu 21.10, but every time when game loads to almost 100% it crashes down. I have tried to:

1. Re-subsribe to TNO
2. Clean cache
3. purge `Paradox Interactive/Hearts of Iron IV` dir
4. Verify file integrity
5. Reinstall HOI4
6. Repeat steps (1-4) on 1.10.8
7. Repeat steps (1-6) on Kubuntu 21.10 

**Steps to Reproduce/Cause Issue:**

1. Launching HOI4 from Steam
2. Selecting playset with ONLY TNO (latest version from SW)
3. Crash

**Game Saves and Log Files, if possible:**
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7797858/error.log) -> 1.10.8
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7797861/error.log) -> 1.10.5

**Comment by Empperorthor** [comment]
Having the same issue.
