### ISSUE TITLE
BUL - Political parties of Bulgaria for its update whenever it will be

### ISSUE THREAD

**Issue by Savyto** [TNODevs/TNO-Bug-Tracker#437]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
Suggestions for the future Bulgarian update:

Authoritarian Socialism - Todor Zhivkov - „Bulgarian Communist Party" (BCP) - 5% support
 https://en.wikipedia.org/wiki/Todor_Zhivkov https://en.wikipedia.org/wiki/Bulgarian_Communist_Party
 
Libertarian Socialism - Krastyo Hadjiivanov - „Federation of Anarcho-Communists in Bulgaria" (FACB) - 0% support
https://bg.wikipedia.org/wiki/Кръстьо_Хаджииванов https://bg.wikipedia.org/wiki/Федерация_на_анархо-комунистите_в_България https://bg.wikipedia.org/wiki/Федерация_на_анархистите_в_България

Social Democracy - Kosta Lulchev - „Bulgarian Workers' Social Democratic Party" (BWSDP) - 7% support
https://bg.wikipedia.org/wiki/Коста_Лулчев https://en.wikipedia.org/wiki/Bulgarian_Workers%27_Social_Democratic_Party

Liberal Democracy - Dimitar Gichev - „Bulgarian Agrarian National Union - Vrabcha 1" (BANU - Vrabcha 1) - 0% support
https://bg.wikipedia.org/wiki/Димитър_Гичев https://bg.wikipedia.org/wiki/БЗНС_„Врабча_1“

Conservative Democracy - Nikola Petkov - „Bulgarian Agrarian National Union - Nikola Petkov" (BANU - Nikola Petkov) - 8% support
https://bg.wikipedia.org/wiki/Никола_Петков https://bg.wikipedia.org/wiki/Български_земеделски_народен_съюз_–_Никола_Петков

Authoritarian Democracy - Kimon Georgiev - „Zveno" - 5% support
https://bg.wikipedia.org/wiki/Кимон_Георгиев https://en.wikipedia.org/wiki/Zveno

Despotism - Tsar Boris III/Tsar Simeon II - „Emergency National Defense Government"  - 44% support

Fascism - Ivan Dochev - „Union of Bulgarian National Legions" - 15% support
https://en.wikipedia.org/wiki/Ivan_Dochev https://en.wikipedia.org/wiki/Union_of_Bulgarian_National_Legions

National Socialism - Aleksandar Tsankov - „National Social Movement" - 10% support
https://en.wikipedia.org/wiki/Aleksandar_Tsankov https://bg.wikipedia.org/wiki/Народно_социално_движение

Ultranationalism - Asen Kantardzhiev - Union of Ratnkis for the Advancement of the Bulgarianness (or just Ratniks) - 5% support
https://bg.wikipedia.org/wiki/Асен_Кантарджиев 
https://bg.wikipedia.org/wiki/Съюз_на_ратниците_за_напредъка_на_българщината

Burgundian System - Hristo Kunchev - National Socialist Bulgarian Workers' Party (NSBWP) - 0% support
https://nstribuna.org/nsbrp.htm https://bg.wikipedia.org/wiki/Националсоциалистическа_българска_работническа_партия https://nstribuna.org/Hristo%20Kunchev.gif

**Reasoning Behind Suggestion:**
Bulgaria is not developed country and for it's update I can give you some ideas for the parties.
**Additional Information:**

**Comment by YanSGod** [comment]
god idea

**Comment by runelead00** [comment]
Bulgaria has plans and parties decided for it in UB
