### ISSUE TITLE
All - Fiscal Crisis Warning leads to Brazil Political GUI

### ISSUE THREAD

**Issue by pentakwoi** [TNODevs/TNO-Bug-Tracker#438]
**Questions**

- Operating System: Mac
- HOI4 Version: 1.10.8
- TNO Version: TT
- Any other mods in use: 2WRW, Toolpakt, etc...
- Were you using Steam? Yes.
- Which expansions do you NOT have? All of it.

**Longer Description of Issue:**
If you click the Fiscal Crisis Warning, it displays a blank Brazil Pol-GUI, Without the parties, just the maps.
**Steps to Reproduce/Cause Issue:**

1. Crash the economy (used debug mode)

2. Get a Fiscal Crisis Warning on my upper screen, leads to the GUI getting displayed.

**Screenshots:**
![2022-01-02 08-17-52](https://user-images.githubusercontent.com/87017891/147877807-e3be7407-a3c7-4af9-9eb2-c176e3dce017.png)

**Comment by Scarsoftime** [comment]
Known issue with the 2WRW mod. Future note: etc.. is not a sufficient answer for the related question.
