### ISSUE TITLE
German Reich - Bugged Oil Crisis Statuses

### ISSUE THREAD

**Issue by TeddyRooseveltFan12345678910** [TNODevs/TNO-Bug-Tracker#439]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: v.1.2.0d
- Any other mods in use: RGFX Axis font, Blue Marble map mod, Expanded Waltz of Europe
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**
I played Bormann into the oil crisis, winning yemen's civil war and its war with arabia, and Iraq. When the UAR spawned and swallowed all the baathist nations, it forced the statuses into failure.
**Steps to Reproduce/Cause Issue:**

1. Play as Germany 

2. Play to the oil crisis 

3. Help the baathists in yemen and Iraq and win there (possibly more)  

4. Wait until they get swallowed into the UAR

**Screenshots:**
![image](https://user-images.githubusercontent.com/81603664/147885921-37523f45-4a54-463d-94ff-dc6a70f84c57.png)
![image](https://user-images.githubusercontent.com/81603664/147885937-f1762d1c-3bce-4633-bc04-e39d559c5969.png)

**Comment by ModdingAccount** [comment]
Fixed in dev build.
