### ISSUE TITLE
HMMLR England / General(?) - Inverted sign for debt interest

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#441]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8 Collie Anniversary
- TNO Version: 1.2.0d
- Any other mods in use: Music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

After winning ECW as HMMLR, and inheriting multiple fiscal crisis national ideas / having my debt rating lowered, I have a $50 billion _surplus_ due to my debt interest being -448% (should be 448%). 

This could impact other nations; I'm not sure. This was a 'normal' playthrough and I didn't use the console.

**Screenshots:**
![image](https://user-images.githubusercontent.com/711467/148450424-947945ea-e6c3-47e9-9bdb-00975a61974d.png)

![image](https://user-images.githubusercontent.com/711467/148450473-c3c02e39-a827-41b7-a713-f52235b4b47c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
