### ISSUE TITLE
USA - Glennonomics make me pay 300 Billion for Nuclear Power

### ISSUE THREAD

**Issue by SGTDaveVader** [TNODevs/TNO-Bug-Tracker#442]
USA - Glennonomics make me pay 300 Billion for Nuclear Power

- Operating System: Windows 10
- HOI4 Version: 1.10.8 (0aab)
- TNO Version: 1.2.0d
- Any other mods in use: US GUI rework, US political landscape Cheat Tool, Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? All before NSB

Longer Description of Issue:
Glorious Glennonomics Make me pay almost 300 Billion for Nuclear Expansion, seems a just a *little* high.

Steps to Reproduce/Cause Issue:
1. Took Nuclear side of the focus tree last, 
2. Seemingly came up after Focus: "Our Yield Must Grow" 
3. Maybe was due to one of the nuclear events.

Screenshots:
![grafik](https://user-images.githubusercontent.com/83709696/148569302-a45b6f2a-cfe1-43ce-baa5-fde47cf3151e.png)

![grafik](https://user-images.githubusercontent.com/83709696/148569329-40d3568e-5f16-4b9f-944e-4b1c376d8249.png)

![grafik](https://user-images.githubusercontent.com/83709696/148569377-c32c45c8-475f-46c6-a4aa-c3806523a6a9.png)

**Comment by runelead00** [comment]
Glenn is getting cut in UB, not fixing before then
