### ISSUE TITLE
[IND] Republic of India & [AZH] - Both pre-TT and TT skeleton content present in mod

### ISSUE THREAD

**Issue by orthur101** [TNODevs/TNO-Bug-Tracker#443]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: Toolbox Theory
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back

**Longer Description of Issue:**

While working on the Republic and India and Azad Hind for the Custom Countries Paths submod, I discovered that both countries have their new TT skeleton content, and their old, pre-TT skeleton content present and enabled at the same time. This results in a (presumably) unintended experience where Nehru dies two different times, there are two separate 1964 Indian elections, and Subhas Chandra Bose simultaneously retires following an assassination attempt and runs for reelection in Azad Hind. 

The new Indian and Azad Hind skeleton content, introduced in the "Toolbox Theory" update, takes place through events located in each's respective event files ("events/TNO_Republic _of_India.txt" and "events/TNO_Azad_Hind.txt"). The initial events are fired from "common/on_actions_TNO_Sphere_on_actions.txt", starting with "IND_skeleton.1" firing 31 days after startup.

However, both countries have their old, pre-TT skeleton content also present in the mod, and these old events still fire, creating the bizarre scenario I talked about above. This old content in located in "events/TNO_first_release_dummy_events.txt", and is fired from "common/on_actions/TNO_on_startup_actions.txt". From this file, "release_dummy.11" fires 792 (plus or minus 50) days after startup, beginning India's old skeleton content, and "release_dummy.26" fires 803 days after startup, beginning Azad Hind's old skeleton content. 	

Oddly, this issue (which I am presuming it is, based on the weird outcomes it results in in-game) doesn't appear to be a complete oversight. I could be wrong, but I'm pretty sure both countries had their tags changed by TT (RAJ->IND, BEN->AZH), so someone must have gone and manually changed the tags in "common/on_actions/TNO_on_startup_actions.txt" so that the old content still fired for the correct tags. The old content has also been  at least partially removed, as the India/Pakistan partition/conflicts located in "events/TNO_first_release_dummy_events.txt" has indeed been commented out and no longer occurs. I'm still pretty sure the dual-skeleton-content situation is an oversight, but the fact that at least one TNO dev went through the old content, updated the tags, and left the old events in to still fire means I could be wrong. 

Although I am not a TNO developer, and I'm not privy to all of the behind-the-scenes decision-making, I think it would be for the mod's benefit if the old content was removed from "events/TNO_first_release_dummy_events.txt" and the old content's triggers removed from "common/on_actions/TNO_on_startup_actions.txt". The subcontinent's new content introduced in TT is much simpler, includes the brand new sub-ideologies, and creates a compelling situation in India which will leave players more excited for its eventual full content. I am pretty confident that the old content's presence in the mod is an unfortunate oversight that can be corrected, but if it is not I would suggest removing it anyway for the reasons I just laid out.

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting.
