### ISSUE TITLE
SBA/WRS - Countries not using their production units

### ISSUE THREAD

**Issue by Companionh** [TNODevs/TNO-Bug-Tracker#445]
**Questions**

- Operating System: Win 10
- HOI4 Version:  1.10.8
- TNO Version:  1.2.0d
- Any other mods in use: Music mod and Kaiserreich music mod
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:** For some reason some countries refuse to use any of their production units and even keep putting their factories back to zero after I force them by tag switching to use them, In this case, WRS has 19 production units but only uses 2 and SBA has 16 production units and uses none even though they have the electricity to use them. 

I think its caused by some countries not having enough power to use them at first and the game bugging out and making them not use them even when they finally build the reactors required to use them.

**Steps to Reproduce/Cause Issue:**

1. In every game there will be countries which are bugged out like this and refuse to use any of their factories even when they have the power

2.

etc...

**Screenshots:**

what tag switching shows:
![image](https://user-images.githubusercontent.com/97452849/148778339-8efa2fc8-ea1e-4ebe-b788-d6bb3d2b5aab.png)

my attempts at forcing them to use their factories is visible at the spikes:
![image](https://user-images.githubusercontent.com/97452849/148778576-06138045-3b58-407e-af93-a67ffdead467.png)

WRS not using their factories:
![image](https://user-images.githubusercontent.com/97452849/148778764-fa0ecff8-769a-4b96-83b8-f2d55333153e.png)

**Comment by runelead00** [comment]
Fixed in Current Build
