### ISSUE TITLE
Bormann Germany - Bormann AI split ukraine into gotenland and a reichsprotekorat, neither is in the grossraum, and gotenland has the generic faction membership type.

### ISSUE THREAD

**Issue by lleo-alexis** [TNODevs/TNO-Bug-Tracker#447]
Latest tno build, hoi4 1.10.8
![20220112194631_1](https://user-images.githubusercontent.com/77152894/149094216-d479e9b0-ea8d-4c5e-ae50-08c106c2d0e3.jpg)
![20220112194547_1](https://user-images.githubusercontent.com/77152894/149094267-3c923dfc-1b8b-41a1-a4d5-a549bf2e5f1b.jpg)
.

**Comment by runelead00** [comment]
Fixed in Current Release
