### ISSUE TITLE
PRC - Bugged Focus after war with mengjiang 

### ISSUE THREAD

**Issue by dmaxwellgoodman** [TNODevs/TNO-Bug-Tracker#448]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: US GUI submod and music mods
- Were you using Steam? yes
- Which expansions do you NOT have? No Step Back

**Longer Description of Issue:**
Focus "The Road for Industrialization" increases Eastern Mongolia's GDP by 10% instead of Western Mongolia's
**Steps to Reproduce/Cause Issue:**

1. Win the war with mengjiant

2. take "the old union remnants"
3. Take "The Road for Industrialization"

**Screenshots:**
![image](https://user-images.githubusercontent.com/29666618/149443615-84013c02-2907-4ab7-8e98-e205afd5eb48.png)

**Comment by dmaxwellgoodman** [comment]
Update: Focus "Build up civilian Industry" has the same issue

**Comment by dmaxwellgoodman** [comment]
Focus "Work to do" has the same issue

**Comment by masterbobli** [comment]
Fixed all three focuses. Thanks for reporting.
