### ISSUE TITLE
England - Incorrect gun smuggling decision description

### ISSUE THREAD

**Issue by mork73** [TNODevs/TNO-Bug-Tracker#449]
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: none

The HMMLR-OFN relationship decision description states that higher state stability makes gun shipments more successful even though the exact opposite is the case.

![Localization_issue](https://user-images.githubusercontent.com/41652769/149635808-b7f6809b-03ac-449d-a33d-997833156ba0.png)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
