### ISSUE TITLE
Japan - Missing decision title

### ISSUE THREAD

**Issue by Ajeje30** [TNODevs/TNO-Bug-Tracker#45]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.1
- TNO Version: 1.1.2a
- Any other mods in use: No
- Were you using Steam? No
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Missing title of some decisions for Kaya's influence

**Steps to Reproduce/Cause Issue:**

1. Kaya at Prime Minister

2. Decision for Kaya's influence

**Screenshots:**
![Screenshot (74)](https://user-images.githubusercontent.com/82140538/128633322-88df7a35-d88c-46d5-995c-2d4195fbdfa5.png)

**Comment by Scarsoftime** [comment]
Fixed
