### ISSUE TITLE
USA - Goldwater fascist embargo

### ISSUE THREAD

**Issue by SIlvrCoconut** [TNODevs/TNO-Bug-Tracker#453]
**Questions**

- Operating System: windows 11
- HOI4 Version: 1.10.8
- TNO Version: 1.2.0d
- Any other mods in use: Cold Springs pack, Moe order, USA gui rework
- Were you using Steam? yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**
In goldwater's "Goods From Just Partners" focus, you embargo all fascist countries.  However this includes collab england, who under thatcher is in the OFN, and follows authoritarian democracy, which is not one of the ideologies that is proposed to be embargo'd "OFN nations will no longer be allowed to trade with ultranationalist, fascist, National Socialist, or esotaric Nazi nations"
I get the focus probably doesnt dynamically check all nations, but in this case collab eng is definitely not fascist, and theyre in the OFN!

**Steps to Reproduce/Cause Issue:**

1. Play USA and elect goldwater (I went wallace -> goldwater)

2. Have a collab england win and go down thatcher and join the OFN

3. Pick 'Morton's plan' (in the economic tree) and pick 'Goldwater's Way', and take the focus, England should be embargo'd

**Screenshots:**
![embargo eng](https://user-images.githubusercontent.com/54516741/150449908-16f7a396-bae7-4fb7-afed-6839aa92255a.png)
![royal party eng](https://user-images.githubusercontent.com/54516741/150449913-75233465-35c7-4372-938f-e397ad733206.png)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build

**Comment by ModdingAccount** [comment]
Fixed in dev build.
