### ISSUE TITLE
Guangdong-Minister name

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#454]
**Questions**

- HOI4 Version: pre-NSB
- TNO Version: pre-NSB
- Any other mods in use:no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [ ] 1. Guangdong Minister has a generic name
![Screenshot (2303)](https://user-images.githubusercontent.com/98137316/150455506-79d2b6c3-54ab-4d9a-981f-c117380aadcc.png)

- [ ] 2. 
(Screenshot here)

**Comment by runelead00** [comment]
Fixed in Dev Build
