### ISSUE TITLE
Japan-missing loc

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#455]
**Questions**

- HOI4 Version:pre-NSB
- TNO Version:pre-NSB
- Any other mods in use:no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [ ] 1. 
![Screenshot (2311)](https://user-images.githubusercontent.com/98137316/150455637-e0d63849-cb1d-47d9-a35d-ecba83b1a74e.png)
- [ ] 2. 
(Screenshot here)

**Comment by runelead00** [comment]
Fixed in Current Release
