### ISSUE TITLE
Dai Li investigation-misleading tooltip

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#456]
**Questions**

- HOI4 Version: pre-NSB
- TNO Version: pre-NSB
- Any other mods in use:

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [ ] 1. This event has orange text, seemingly indicating that this gives the orange clue in the Dai Li investigation. It no longer does that, however the text remains.
![Screenshot (2312)](https://user-images.githubusercontent.com/98137316/150455741-10001af1-9d08-46ba-ad5c-f4e4acd366e4.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
