### ISSUE TITLE
Brazil-typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#460]
**Questions**

- HOI4 Version: pre-NSB
- TNO Version: pre-NSB
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
During the PSP event to nominate de Barros, the first paragraph twice refers to the UDN coalition instead of the PSP
- [x] 1. 
![Screenshot (2346)](https://user-images.githubusercontent.com/98137316/150456597-3bdd44e2-058f-4b20-86e0-a5747d9f5a49.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
