### ISSUE TITLE
Brazil-Senate candidate's name goes outside the senate gui

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#461]
**Questions**

- Operating System:
- HOI4 Version: pre-nsb
- TNO Version: pre-nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? n/a

**Longer Description of Issue:**
self-explanatory, see screenshots
**Steps to Reproduce/Cause Issue:**
n/a

**Screenshots:**
![Screenshot (2347)](https://user-images.githubusercontent.com/98137316/150456740-0c94dbda-1dc5-45cb-847a-9919dc17f5d4.png)
![Screenshot (2348)](https://user-images.githubusercontent.com/98137316/150456754-1ddbcd1e-ff3d-4a4c-a0b0-2cd8ddd91472.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
