### ISSUE TITLE
Annexing of Germania causing issues with cabinet and generals

### ISSUE THREAD

**Issue by 1dohg** [TNODevs/TNO-Bug-Tracker#465]
**Questions**

- Operating System: Windows 11 Pro
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1 - Toolbox Theory NSB Patch
- Any other mods in use: Toolpakt
- Were you using Steam? Yes
- Which expansions do you NOT have? All DLC owned

**Longer Description of Issue:**

After the GCW is over and Germania is annexed, the ministers and generals from Germania are used instead of the victor's cabinet and generals

**Steps to Reproduce/Cause Issue:**

1. Play GCW

2. Win GCW

**Screenshots:**

https://cdn.discordapp.com/attachments/723235391162810420/934233060508074024/unknown.png
https://cdn.discordapp.com/attachments/723235391162810420/934235314782867496/unknown.png

**Comment by runelead00** [comment]
Fixed in Current Release
