### ISSUE TITLE
VYT - Missing General Portrait and a Similar Issue

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#466]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.4
- TNO Version: v1.2.1 “Toolbox Theory”
- Any other mods in use: No
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Since General Nikolay Rumyantsev is gained through an event, he doesn't get a portrait due to what I assume is issues with NSB's character system, with his portrait instead being the default one with a small slip of paper in the bottom left.

Field Marshal Boris Smyslovsky also has the small slip of paper in the bottom left of his portrait.

*Screenshots:**
![Hearts of Iron IV (DirectX 9) 22_01_2022 10_50_17 AM](https://user-images.githubusercontent.com/59920852/150614743-b8a7ee81-0184-4133-9f10-49f15a32175e.png)
![Hearts of Iron IV (DirectX 9) 22_01_2022 10_50_09 AM](https://user-images.githubusercontent.com/59920852/150614747-186d590d-ed36-453f-a6b5-9ca3c1bb4fa9.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
