### ISSUE TITLE
USA - George Wallace focus instantly cancels itself because "A bill is being debated in Congress"

### ISSUE THREAD

**Issue by MIILL** [TNODevs/TNO-Bug-Tracker#468]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? I do not have No Step Back

In Wallace's focus tree, the focus "Increase States' Authority" recursively cancels itself once selected. The focus triggers a decision category to spawn regarding the "American Defence Reorderment Act." When this happens, the focus will immediately cancel because one of the prerequisites for taking the focus is "No bill is being debated in Congress." Because the focus is not running, the bill will never be voted on and that entire section of the tree becomes unavailable.

Steps to Reproduce the Issue:
1. Elect George Wallace as the President of the United States
2. Go down the "This is a Union, not an Empire!" tree
3. Complete the focus "This is a Family of States"
4. Select the focus "Increase States' Authority"
5. The bug should occur; the focus will be instantly cancelled. You will be unable to select it again because you will not meet one of the prerequisites

Screenshots:
![image](https://user-images.githubusercontent.com/98198377/150622151-08aed827-637d-4bb9-a192-8143141d1de3.png)
![image](https://user-images.githubusercontent.com/98198377/150622154-903279a6-3a84-4ca8-b433-e713fe25d1e8.png)

**Comment by runelead00** [comment]
Fixed in Current Build
