### ISSUE TITLE
Reichskommissariat Balkanhalbinsel - Name for Kischenau has lost

### ISSUE THREAD

**Issue by Computer64** [TNODevs/TNO-Bug-Tracker#472]
**Questions**

- HOI4 Version: 1.11.4
- TNO Version: 1.2.1 Toolbox Theory NSB Patch
- Any other mods in use: No, only vanilla TNO

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Reichskommissaariat Balkanhalbinsel had Kischenau as dynamic name of victory point, however now localisation forgot to write for it.
- [ ] 1. 
![image](https://user-images.githubusercontent.com/92990434/150637826-cd8abf3e-6c79-47e3-b003-8742fc171578.png)

- [ ] 2. 
![image](https://user-images.githubusercontent.com/92990434/150637855-31ab250d-eeb9-49bb-ad38-9ae8a28327b6.png)

**Comment by runelead00** [comment]
Fixed on UB
