### ISSUE TITLE
Every Country - The game crashes after I boot up a country (not on startup)

### ISSUE THREAD

**Issue by santboss69** [TNODevs/TNO-Bug-Tracker#473]
**Questions**

- Operating System: W10
- HOI4 Version: 
- TNO Version: v1.2.1 “Toolbox Theory”
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? All DLC besides No Step Back

**Longer Description of Issue:**

The game literally crashes with no reason after I boot up a country

**Steps to Reproduce/Cause Issue:**

1.
I boot up the game normally

2.
I'd start a new game

3.
I'd choose a country

4.
After I chosen the country and it finished loading it, after 1 second of gameplay the game crashes.

**Screenshots:**

**Game Saves and Log Files, if possible:**

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed and cause currently unknown
