### ISSUE TITLE
Any country - crashes every time after GCW ends

### ISSUE THREAD

**Issue by Regularite** [TNODevs/TNO-Bug-Tracker#474]
**Questions**

- Operating System: Windows 7 x64
- HOI4 Version: 1.11
- TNO Version: 1.2.1
- Any other mods in use: No
- Were you using Steam? No
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Every time when GCW ends, after 4-5 days game crashes

**Steps to Reproduce/Cause Issue:**

1. I launched well

2. Choose WRRF

3. Everything was well

4. Goering wins (I tried with Speer, crashed anyway)

5. Five days come and crash 

**Screenshots:**

**Game Saves and Log Files, if possible:**
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7918559/error.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7918560/error.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7918561/error.log)

**Comment by tichbou** [comment]
I am having the same problem with the only changes being that I running on MACOS 12.1 and on steam running HOI 1.11.4.

**Comment by tkgitno** [comment]
Fixed in Dev Build
