### ISSUE TITLE
US - Various panes have overlaps

### ISSUE THREAD

**Issue by TCWebDev** [TNODevs/TNO-Bug-Tracker#475]
**Questions**

- Operating System: Win10
- HOI4 Version: Barbarossa v1.11.4.e26e
- TNO Version: 1.2.1
- Any other mods in use: NO
- Were you using Steam? Yes
- Which expansions do you NOT have?

**Longer Description of Issue:**

When selecting a naval ship type to produce the first item listed has its name hidden/covered by the ship class chooser.

**Steps to Reproduce/Cause Issue:**

1.  Open production window

2.  Select Build Ships

3.  Name of first item in chooser list is not visible, tucked under the class filter

**Screenshots:**

![image](https://user-images.githubusercontent.com/76961247/150643584-55b6f9c1-ed45-4508-ac8c-a0244cec80bc.png)

![image](https://user-images.githubusercontent.com/76961247/150644507-e40b6e50-91d5-458b-bdcd-2c606074753d.png)

![image](https://user-images.githubusercontent.com/76961247/150643625-745d960a-2cc1-4b91-9826-16e2b521981c.png)

**Comment by runelead00** [comment]
Both Fixed in Dev Build
