### ISSUE TITLE
Failed to load the map

### ISSUE THREAD

**Issue by al-Maiakovski** [TNODevs/TNO-Bug-Tracker#477]
**Questions**

- Operating System: Win10
- HOI4 Version: 1.11.4 and 1.11.5 open beta
- TNO Version: 1.2.1
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? own all of the expansions

**Longer Description of Issue:**
whenever I try to launch the mod, the game CTDs mid loading saying that it "failed to load the map", already redownloaded the mod three times, changed game version, verified files

**Steps to Reproduce/Cause Issue:**

1.start hoi4 1.11.x with TNO 1.2.1

2.CTD mid loading

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/73006446/150646213-029e8a03-b76d-4805-9f85-8966d7432ed6.png)

**Game Saves and Log Files, if possible:**

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7918696/error.log)
[pdxmp.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7918698/pdx
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7918700/
[pdxmp.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7918701/pdxmp.log)
setup.log)
mp.log)

**Comment by I4theEmperorI** [comment]
I have the same problem, have you found a way to fix it?

**Comment by Stormeagle449** [comment]
I can only recommend the solutions found on 961.
