### ISSUE TITLE
Bormann Germany - Theoderichshafen fails to core

### ISSUE THREAD

**Issue by cc4nt** [TNODevs/TNO-Bug-Tracker#478]
**Questions**

- Operating System: MacOS
- HOI4 Version: 1.11
- TNO Version: 1.2.1
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have?
I have all expansions
**Longer Description of Issue:**
Upon Dönitz reintegrating into Bormann's Germany, the main crimean state receives a core as intended but Theoderichshafen does not
**Steps to Reproduce/Cause Issue:**

1. Win civil war as Bormann

2. Dönitz reintegrates

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Dev Build
