### ISSUE TITLE
Norway - Gulbrand Lunde Norway not joining Großraum

### ISSUE THREAD

**Issue by cc4nt** [TNODevs/TNO-Bug-Tracker#479]
**Questions**

- Operating System: MacOS
- HOI4 Version: 1.11
- TNO Version: 1.2.1
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have?
I have all expansions
**Longer Description of Issue:**
When Lunde Norway rejoins the Einheitspakt they do not rejoin the German economic sphere
**Steps to Reproduce/Cause Issue:**

1. Lunde takes power

2. Germany goes down the focus for them to rejoin the Pakt

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Dev Build
