### ISSUE TITLE
Buryatia - Sablin declares war with no way to reach target.

### ISSUE THREAD

**Issue by awnman** [TNODevs/TNO-Bug-Tracker#48]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? La Resistance

**Longer Description of Issue:**

Sablin declared war on Magadan through his focus tree despite Chita not being dead yet meaning he sat there unable to complete focuses or participate in the war until one of the two won the war as he had no way of moving troops to fight Magadan.  

**Steps to Reproduce/Cause Issue:**

1. Have Chita/Amur survive against Magadan

2. Have Buryatia pick the option that declares war against the target he cannot reach.

etc...

**Screenshots:**
![Screenshot (289)](https://user-images.githubusercontent.com/88620806/128634183-7c38877e-db23-4223-891a-6786e7c333aa.png)

![Screenshot (288)](https://user-images.githubusercontent.com/88620806/128634248-a772f202-f5ba-4d2f-843f-55221803929d.png)

**Comment by Scarsoftime** [comment]
Fixed in the developer build. Thank you for your report.
