### ISSUE TITLE
Production Problem (Ships (Destroyers and Frigates) - Short Description of Issue

### ISSUE THREAD

**Issue by BartegReunificated** [TNODevs/TNO-Bug-Tracker#481]
**Questions**

- Operating System: Win10
- HOI4 Version: 1.11.4
- TNO Version: Latest
- Any other mods in use: Playerled Peace Conferences
- Were you using Steam? yes
- Which expansions do you NOT have? All DLCs

**Longer Description of Issue:**

The problem is, that when I am trying to set destroyer/frigates for production, I get message "missing component: battery". 
I am 99% sure that is Man the guns DLC issue (I do not have the dlc)

**Steps to Reproduce/Cause Issue:**
Start up the game with mod installed

**Screenshots:**
![image](https://user-images.githubusercontent.com/98238537/150656749-2e6dfd03-66a7-4965-be2f-fa8c7c115edf.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
