### ISSUE TITLE
All Countries - as soon as I click on any nation, the game closes when it finishes loading.

### ISSUE THREAD

**Issue by McArthur11** [TNODevs/TNO-Bug-Tracker#482]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.4
- TNO Version: Lastest
- Any other mods in use: No
- Were you using Steam? PC
- Which expansions do you NOT have? None

**Longer Description of Issue:**

as soon as I click on any nation, the game closes when it finishes loading.

**Steps to Reproduce/Cause Issue:**

1. Open the game

2. Click on a nation

3. Click play

4. Finishes loading and closes

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed and cause currently unknown
