### ISSUE TITLE
Yeltsin is gone

### ISSUE THREAD

**Issue by Tojoroto** [TNODevs/TNO-Bug-Tracker#483]
**Questions**

- HOI4 Version: 1.11.4
- TNO Version: 1.2.1
- Any other mods in use: Radio TNO

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
The event that makes Yeltsin the leader of the Conservative faction isn't doing it, resulting in a blank portrait.
- [ ] 1. Elect Yeltsin as Sverdolovsk.
![image](https://user-images.githubusercontent.com/98239437/150657574-eae7de39-8027-40d6-8b71-4855683c95d0.png)

**Comment by WholesomeDengist** [comment]
Honestly, probably for the best

**Comment by ltallen** [comment]
I can confirm that I have this bug as well.

**Comment by Scarsoftime** [comment]
Fixed in dev build
