### ISSUE TITLE
USA Event IRK.35 causes $150B debt

### ISSUE THREAD

**Issue by El-Lanf** [TNODevs/TNO-Bug-Tracker#485]
LBJ Run, Aug 1968, event IRK.35 occurs. Tooltip says will send IRK $30M aid. After selecting, $150B was added to debt. No other mods, non-beta patch.
![20220122212702_1](https://user-images.githubusercontent.com/32586499/150659312-266ddbb2-5f29-4f5d-90a4-9605b5e99d87.jpg)

**Comment by Scarsoftime** [comment]
Fixed in dev build.
