### ISSUE TITLE
Yunan event yun_wi.46 causes game to freeze

### ISSUE THREAD

**Issue by dissatisfieduser** [TNODevs/TNO-Bug-Tracker#486]
I am referring to this particular event:
![Screenshot 2022-01-23 at 12 22 13 AM](https://user-images.githubusercontent.com/57701135/150659861-ca4ad157-4ccc-40fe-a31a-259717925b68.png)

I have attached some logs if that helps.
[crash_logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7919526/crash_logs.zip)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7919527/error.log)

The game isn't actually crashing to desktop, it just stops and freezes so all I see until I forcequit HOI4 is the screenshot above.

**Comment by tkgitno** [comment]
Fixed in Dev Build
