### ISSUE TITLE
Amur-Food For Fuel Decision Leads To Absolutely No Fuel

### ISSUE THREAD

**Issue by JoshuaLogan1527** [TNODevs/TNO-Bug-Tracker#487]
**Questions**

- Operating System: Windows
- HOI4 Version: NSB
- TNO Version: NSB Patch
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
If the "Food for Fuel" decision is taken at Regional Stage, the player will have absolutely no fuel, even if they assign every production unit available to civilian factories, to be used for importing Oil. This makes a game of Rodzaevsky very difficult. 

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed on UB
