### ISSUE TITLE
USA - "Rosie the Radio Operator" focus automatically cancels

### ISSUE THREAD

**Issue by karkatthedalek** [TNODevs/TNO-Bug-Tracker#488]
**Questions**

- Operating System: Windows
- HOI4 Version: NSB
- TNO Version: NSB Patch
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosporus

**Longer Description of Issue:**

Was playing RFK, and attempting to do the Treaty Port Negotiations before I did the Civil Rights Act, but as I was going down the tree, the focus "Rosie the Radio Operator" cancelled itself, apparently because another bill was in progress. The Battle for Italty, the Battle for England, and the Indonesian War were all ongoing at the time, but completing the first two and letting decisions from the latter time out did nothing to change it. The issue seems to be that it's counting itself as the other bill in progress.

I seem to recall one of Goldwater's focuses, either the EPA or the Clean Water Act, having a similar issue not too long ago.

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Dev Build
