### ISSUE TITLE
Turkey (Presumably) - unfinished event about Turkes Legion fired in January 1972

### ISSUE THREAD

**Issue by jimmyjohnspizzaofficial** [TNODevs/TNO-Bug-Tracker#490]
- Operating System: Windows 11
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: N
- Were you using Steam? Y
- Which expansions do you NOT have? N/A

![20220123000039_1](https://user-images.githubusercontent.com/98248616/150665774-ae6c1c41-5de8-4193-bd07-b334a4c7cb3b.jpg)

**Comment by runelead00** [comment]
Event correctly locced in current release version
