### ISSUE TITLE
England - $167 Billion in Misc Income

### ISSUE THREAD

**Issue by SarFed** [TNODevs/TNO-Bug-Tracker#491]
**Questions**

- Operating System:
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1
- Any other mods in use: None
- Were you using Steam?: Yes
- Which expansions do you NOT have?: The armor/music packs and BFTB

**Longer Description of Issue:**
After taking the focus "The Russian Way" as Thatcher's England, instead of getting 2% of your GDP as misc income, you instead get 200% of your GDP.
**Steps to Reproduce/Cause Issue:**

1. Complete focus "The Russian Way" as Thatcher's England

2. Unpause the game and check the economy tab

**Screenshots:**
![image](https://user-images.githubusercontent.com/94810018/150666246-512fb11f-6ddf-44b3-9ad2-a7aef9ccb3af.png)

**Comment by ToastandTea** [comment]
I used to deny tno had a thatcher bias...

**Comment by runelead00** [comment]
Fixed in Current Release
