### ISSUE TITLE
Yunnan crash after winning GAW

### ISSUE THREAD

**Issue by discordine** [TNODevs/TNO-Bug-Tracker#492]
**Questions**

- Operating System:
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1
- Any other mods in use: No
- Were you using Steam?: Yes
- Which expansions do you NOT have?: NSB

**Longer Description of Issue:**
I won the GAW taking Manchu, but crashes after "The reslution" event

**Screenshots:**
![image](https://user-images.githubusercontent.com/46787431/150670197-0fb170cf-6657-421f-ba22-b276c3e4d620.png)

**Game Saves 
[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7920047/logs.zip)
and Log Files, if possible:**

**Comment by tkgitno** [comment]
Fixed in Dev Build
