### ISSUE TITLE
HMMLR England - Incorrect depiction of fox hunting

### ISSUE THREAD

**Issue by Ferd42** [TNODevs/TNO-Bug-Tracker#493]
**Questions**

- Operating System: Windows 11
- HOI4 Version: This is a lore issue.
- TNO Version:
- Any other mods in use:
- Were you using Steam? Yes
- Which expansions do you NOT have? 

**Longer Description of Issue:**

When play as HMMLR, taking the hunting with Auchinleck focus spawns an event. Unfortunatly there are some issues with this event. Firstly, it is Jellicoe shoots a fox that they have been chasing, this is not how fox hunting is done, rather the hounds kill the fox.
Moreover, Auchinleck himself did not hunt foxes. If you can get hold of the army record society papers on him, page 74 has a quote where he says that he does not hunt the fox. 
You may wish to look into game shooting instead?

**Steps to Reproduce/Cause Issue:**

1. Take the hunting with Auchinleck focus in the NDL army tree.

2. Read the event that comes up.

**Comment by Scarsoftime** [comment]
Please label your issues properly

**Comment by Stormeagle449** [comment]
Fixed in Dev Build, now he hunts a pheasant
