### ISSUE TITLE
Italy - East African Wars Events

### ISSUE THREAD

**Issue by Sharksy** [TNODevs/TNO-Bug-Tracker#494]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.4 (latest)
- TNO Version: v1.2.1 “Toolbox Theory” (latest)
- Any other mods in use: A defines mod (https://steamcommunity.com/sharedfiles/filedetails/?id=2728476887)
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
As Italy, after Italian East Africa collapsed there was a decision category to reconquer it. The decisions and event for retaking Eritrea worked just fine. However, the events associated with the decisions to invade Ethiopia, Somalia, Oromo, and Kenya all have invalid event ids. 

**Steps to Reproduce/Cause Issue:**

1. N/A (?)

2.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/56083604/150671009-5b0dd57f-dd62-4b6c-aeda-23858d5d0502.png)
![image](https://user-images.githubusercontent.com/56083604/150671013-2986c5a3-7aec-44f2-b739-eeb57aba5229.png)
![image](https://user-images.githubusercontent.com/56083604/150671017-3c361e33-6bc3-4c12-8a0a-0a32795ce805.png)
-Unable to get screenshots for Ethiopia and Somalia decisions because I already took those decisions before realizing there was a bug.

**Comment by Arikken** [comment]
I also had this issue.

**Comment by threeones111** [comment]
This is still an issue. Seems like somebody deleted impurita events 1-8 along side the outdated events 9-27.

**Comment by Stormeagle449** [comment]
Fixed in UB.
