### ISSUE TITLE
Goering's Germany after winning GCW - events spawning in commanders are crashing the game

### ISSUE THREAD

**Issue by fortasteaua** [TNODevs/TNO-Bug-Tracker#495]
**Questions**

- Operating System:
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1 updated on 1/22/2022
- Any other mods in use: no 
- Were you using Steam? yes 
- Which expansions do you NOT have? none

**Longer Description of Issue:**
I've found 2 events that crash the game while playing with goering, the first one (screenshot named crash) crashes the game, but it works fine if you are using debug mode for some reason, and the second one crashes the game with or without debug mode (screenshot named crash2, "The first promotions" event ), probably because it tries to assign a commander to goering's civil war nation that doesn't exist anymore
**Steps to Reproduce/Cause Issue:**
1. clicking on the event's option or letting it disappear crashes the game

**Screenshots:**
![crash](https://user-images.githubusercontent.com/98226017/150670789-a4488754-7283-4922-9953-4858abec6155.png)
![crash2](https://user-images.githubusercontent.com/98226017/150670795-5c6c9a42-ac12-48ed-a505-ef2e03b7e5d9.png)

**Comment by tkgitno** [comment]
Fixed in Dev Build
