### ISSUE TITLE
SAF crash after win South Africa War

### ISSUE THREAD

**Issue by Derkyster** [TNODevs/TNO-Bug-Tracker#497]
Questions

- Operating System: Windows 10
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1
- Any other mods in use: 
"Tool Pack Updated 2021"
- Were you using Steam? yes
- Which expansions do you NOT have? None

Longer Description of Issue: I play USA and help SAF win war, but when it over and American Mandat of Africa come to exist, game crash.

Steps to Reproduce/Cause Issue:

1.Take USA.

2.Let Soyth African War happend.

3. Help Union of South Africa win.

4. Profit: Game crash.

Screenshots:

Game Saves and Log Files, if possible:
[Crash.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7920363/Crash.zip)

**Comment by TCWebDev** [comment]
Confirm, this just happened to me.  Trying to reload game at an auto-save loads game, but without UI for army divisions.

**Comment by tkgitno** [comment]
Fixed in Dev Build
