### ISSUE TITLE
Tomsk - Typos and poor grammar

### ISSUE THREAD

**Issue by Somentus** [TNODevs/TNO-Bug-Tracker#498]
**Questions**

- HOI4 Version: 1.11.4
- TNO Version: 22 Jan @ 12:59am
- Any other mods in use: No

- [x] 1. 
![image](https://user-images.githubusercontent.com/15087153/150684036-3d8ff0e4-5959-495e-9d6b-8a3d834c22fe.png)
First paragraph: "a heir", which should be "an heir"

- [x] 2.
![image](https://user-images.githubusercontent.com/15087153/150684159-442abab4-6054-4b21-bd59-bd3e90f08566.png)
Not a typo, but this just looks bad: twice in the same paragraph, a sentence starts with "Through all this".

- [x] 3.
![image](https://user-images.githubusercontent.com/15087153/150684756-ac23da66-117d-460f-9bd3-ae439bb5944f.png)
In Tomsk's Duma GUI, the word "legislatures" keeps being used, when "legislators" should be used.

- [x] 4.
![image](https://user-images.githubusercontent.com/15087153/150686293-4099ab45-f811-4757-81a7-6379f1c773b3.png)
First paragraph: "as he rest in his bedroom" this is the wrong form of "rest", it should be "as he was resting" or "as he rested".

- [x] 5.
![image](https://user-images.githubusercontent.com/15087153/150693583-7ff3d264-bfab-4b1b-b065-43ffb2bb8bc6.png)
Third paragraph: "Mens of the salons": "Mens" should be "Men"

- [x] 6.
![image](https://user-images.githubusercontent.com/15087153/150694132-17f917d8-5c65-4407-aa32-76c0f28b5e23.png)
First paragpraph: "Sometimes, they would be built on", with later "Others were created on". Given the second sentence, the first sentence would sound better as: "Some were built on".

- [x] 7.
![image](https://user-images.githubusercontent.com/15087153/150694342-60028dcf-c360-4b6f-8f23-04c0312562c3.png)
Last paragraph: "Occasionally a lawyer came in to discuss." To discuss what? Should be something like "Occasionally, a lawyer came in to discuss something." or whatever. Just add something, or rewrite the sentence.

- [x] 8.
![image](https://user-images.githubusercontent.com/15087153/150695146-2a72fae9-3911-4851-9739-6bdde29d2136.png)
Second to last sentence: "But I get to complain about it if its bad". "its" should be "it is" or "it's".

- [x] 9.
![image](https://user-images.githubusercontent.com/15087153/150698118-cd2a6770-7f88-4a3b-8a70-7894b7660b86.png)
Second paragraph: "Never has an American traveled so far into Siberia for years!"
"Never" "for years"? One of those must go. Don't say never and then say it's been years. 

- [x] 10.
![image](https://user-images.githubusercontent.com/15087153/150698678-2d7b8718-91d7-466d-a937-522faf6a86c8.png)
Very first sentence: "Andrey Sakharov stood in the middle of the crowd, eager to hear from their new president." This should be rewritten, as right now, this sentence says that Andrey Sakharov is eager to hear from their new president. It should be something like "The crowd surrounded Andrey Sakharov, eager to hear from their new president".

- [x] 11.
![image](https://user-images.githubusercontent.com/15087153/150700726-bdc183a0-91cc-4346-ba38-c25b18bb19c1.png)
Second paragraph: "Their is a bright future ahead." "Their" should be "There"

- [x] 12.
![image](https://user-images.githubusercontent.com/15087153/150703573-3d929da2-ea74-4752-8d96-7723c4d6ddfd.png)
Last paragraph: "It seems not many people are not up to purchasing and reading books in Warlord Russia".
Double negative, meaning that apparently, people are up to purchasing and reading books in warlord Russia, which is not what this sentence wants to say. Remove one of the "not".

- [x] 13.
![image](https://user-images.githubusercontent.com/15087153/150791121-c13a85b6-19fc-4742-a9bc-147248abeddb.png)
"The commander of the Republic are ready to launch" This should be "The commander of the Republic is ready to launch" or "The commanders of the Republic are ready to launch". The commander is, or The commanders are, not The commander are.

- [x] 14.
I have no screenshot of this, but I did type out the text. This is for the decision in "Siberian Expansion", called "War Plan Tvyordaya Ruka":
"The Republic now stand on the cusp of beginning Operation Tvyordaya Ruka, the invasion of the Siberian Black Army held territories. The eastern Anarchists have caused much of the trouble that affected the CSR, and it is time for our army to end their insurrection once and for all."
This says "The Republic now stand on the cusp". The Republic does not match "stand". It should be "The Republic now stands".

**Comment by runelead00** [comment]
Fixed in Dev Build
