### ISSUE TITLE
America - High Military Command is bugged

### ISSUE THREAD

**Issue by Milarqui** [TNODevs/TNO-Bug-Tracker#499]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.4
- TNO Version: Toolbox Theory - NSB compatibility patch
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back, Battle for the Bosporus

**Longer Description of Issue:**
At the beginning of the game, Westmoreland and Lavelle (I think, I didn't check at first) are part of the USA High Military Command, but when the Central African OFN Mandates are set up, they leave the HMC. When the mandates are successfully decolonized, the generals return and I get a warning that I now can add the officers to the HMC, but when I click on the empty portraits I can't open the window that would allow me to do this.
**Steps to Reproduce/Cause Issue:**

1. Completely win the South African War
2. Set up the Mandates.
3. Successfully finish the decolonization process

**Comment by tkgitno** [comment]
Fixed in Dev Build (Should be automatically added after decolonization)
