### ISSUE TITLE
Jellicoe England - Focus has wrong text

### ISSUE THREAD

**Issue by awnman** [TNODevs/TNO-Bug-Tracker#50]
**Questions**

- HOI4 Version: 1.10.8
- TNO Version: 1.1.2
- Any other mods in use: No

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
The text for "Fixing the Tax System" is also used for the previous "Work Harder"
- [x] 1. 
![Screenshot (276)](https://user-images.githubusercontent.com/88620806/128634389-8aa2dfbd-3a5a-4b06-8d71-50c7e5743053.png)

- [x] 2. 
![Screenshot (277)](https://user-images.githubusercontent.com/88620806/128634393-16119927-2d08-4226-8976-2197b2bd4d5f.png)

**Comment by Scarsoftime** [comment]
It is a known issue, thank you for your report, we will work to fix this as soon as possible.
