### ISSUE TITLE
HMMLR England - Jelicoe not appeearing

### ISSUE THREAD

**Issue by RedEdd97** [TNODevs/TNO-Bug-Tracker#500]
**Questions**

- Operating System: Windows 10 64 Bit
- HOI4 Version: V1.11.4
- TNO Version:V1.2.1
- Any other mods in use: TNO Radio mod and The New Order: VT323 Map and Cities Font
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all of them

**Longer Description of Issue:**
After I win the Civil War and then get the NDL elected, Jelicoe doesn't appear and instead there is a generic leader, as well as the ministers appointed. The same goes for the leader traits and description, I get a random name for the leader each time as well as random generic traits. Not a game breaking issue obviously but just a bit weird :)

**Steps to Reproduce/Cause Issue:**

1. Win the civil war

2. Get the NDL elected

etc...

**Screenshots:*
![Screenshot 2022-01-23 153551](https://user-images.githubusercontent.com/98231810/150686611-3a624178-a1bb-43a3-80fb-213dbd34745e.jpg)
*

**Comment by Lemonater47** [comment]
I have the exact same issue. The NDL has the wrong party leader.

**Comment by runelead00** [comment]
Fixed in Current Release
