### ISSUE TITLE
Komi - Insane gdp in two states

### ISSUE THREAD

**Issue by cheapsbl** [TNODevs/TNO-Bug-Tracker#502]
**Questions**

- Operating System: windows 11
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1
- Any other mods in use: -
- Were you using Steam? Yes
- Which expansions do you NOT have? -

**Longer Description of Issue:**
Komi went Suslov and attaked the front. For a time the state of Syktyvkar had a negative gdp growth of -1000%. It's gdp rose to 1 billion which is unrealistic. I actually loaded an earlier save to see what the issue was, however in my original run i hadn't noticed the gdp until Vyatka united Western Russia, at which time Syktyvkar and Vilegodsk had respective gdps of 16 and 7 billions.

**Steps to Reproduce/Cause Issue:**

1. Take Suslov

2. ???

**Screenshots:**
![image](https://user-images.githubusercontent.com/49978033/150698327-b31e34b1-b9ad-46ca-8919-9c367518cb70.png)
![image](https://user-images.githubusercontent.com/49978033/150698465-2b8a79af-c521-47bd-9f83-5de00272055e.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build.
