### ISSUE TITLE
Chita - Post Semyonov Cabinet doesn't update properly.

### ISSUE THREAD

**Issue by ItsRevanAgain** [TNODevs/TNO-Bug-Tracker#503]
- Operating System: Windows 10
- HOI4 Version: 1.1.4
- TNO Version: v1.2.1 “Toolbox Theory” NSB
- Any other mods in use: TNO Radio, Smaller Oultines, Russian Music Mod
- Were you using Steam? Yes
- Which expansions do you NOT have?
None

After Semyonov dies, the cabinet doesn't update properly, leaving you absolutely swimming in army xp thanks to Semyonov, Shepunov x2 and Kossov being around. 

![image](https://user-images.githubusercontent.com/33811430/150701383-1bfd44a9-fc4b-46d0-a7b6-9c6863391f6a.png)
![image](https://user-images.githubusercontent.com/33811430/150701386-dbbabafc-fead-4fea-85c0-63e56a408ddb.png)
![image](https://user-images.githubusercontent.com/33811430/150701389-84fc9ce6-a296-4acd-b842-a38876884b87.png)

[TNO_Chita.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/8758339/TNO_Chita.txt)

UPDATE: After a lot of aimless running around in the files, I found the problem. 
The 'token' which removes/adds ministers, had been removed, causing Semyonov to stay, and Shepunov to remain as head of security.
File has been provided for, I hope, easy implementation.

**Comment by runelead00** [comment]
Fixed on UB
