### ISSUE TITLE
Magadan - Integrate the Tsarist Generals missing portraits

### ISSUE THREAD

**Issue by ItsRevanAgain** [TNODevs/TNO-Bug-Tracker#505]
Operating System: Windows 10
HOI4 Version: 1.1.4
TNO Version: v1.2.1 “Toolbox Theory” NSB
Any other mods in use: TNO Radio, Smaller Oultines, Russian Music Mod
Were you using Steam? Yes
Which expansions do you NOT have?
None

(Probably already reported, but I couldn't find it) 
After beating Chita, the focus which absorbs the tsarists, ends up with some portraits being absent. 

![image](https://user-images.githubusercontent.com/33811430/150702953-50c7b783-3588-4dfc-9f32-ddae384beb9d.png)

**Comment by runelead00** [comment]
Fixed on UB
