### ISSUE TITLE
Iberian Federation - PRD Focus Tree Changes To UR After Oil Crisis

### ISSUE THREAD

**Issue by Tissilelu** [TNODevs/TNO-Bug-Tracker#506]
**Questions**

- Operating System:
- HOI4 Version: Barbarossa v1.11.4.e26e (665d)
- TNO Version: v.1.2.1 - Toolbox Theory NSB Patch
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosporus

**Longer Description of Issue:**
When the oil crisis hits. The focus tree of the PRD changes to the UR. Also when the PRD was elected in the 1970 elections Torcuato Fernández-Miranda became the leader of the country.

**Steps to Reproduce/Cause Issue:**

1. Elect the PRD. You will notice Torcuato Fernández-Miranda is leading the country.

2. Wait for the Oil Crisis to emerge and the focus tree will change to the UR focus tree.

**Screenshots:**

![20220124064949_1](https://user-images.githubusercontent.com/42088463/150724137-27ee3670-743f-4ae3-8571-72467155fffb.jpg)
![20220124064938_1](https://user-images.githubusercontent.com/42088463/150724164-efe83424-dcf1-4b87-8845-eadfe6f0d91a.jpg)
Before Oil Crisis
![20220124065810_1](https://user-images.githubusercontent.com/42088463/150724616-bb8497e8-29e3-4354-a3cd-80495d8abde1.jpg)
![20220124065847_1](https://user-images.githubusercontent.com/42088463/150724736-f96484e4-4287-4b3a-bc1e-12020a499a14.jpg)
After Oil Crisis
![20220124065905_1](https://user-images.githubusercontent.com/42088463/150724754-75725e27-075b-4b83-8ed1-c09c86462d55.jpg)

**Comment by runelead00** [comment]
Fixed on Dev Build
