### ISSUE TITLE
All Countries - All map textures are missing, TNO Banner is missing

### ISSUE THREAD

**Issue by ThomasLeyk** [TNODevs/TNO-Bug-Tracker#507]
**Questions**

- Operating System: Window 10 Home, 10.0.19043 Build 19043
- HOI4 Version: Barbarossa v1.11.4.e26e (b22c)
- TNO Version: v1.2.1 “Toolbox Theory” (Latest available as im writing this)
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all expansions. Edit: Except for all the cosmetic expansions.

**Longer Description of Issue:**

See the screenshots attachted.
The examples show Germany but the problem is already present in the country picker screen.

**Steps to Reproduce/Cause Issue:**

Launch the game and click 'Singleplayer', then click 'New Game'..

**Screenshots:**
![20220124060752_1](https://user-images.githubusercontent.com/41568950/150726590-5818182d-6001-481f-b0d1-3bb7cc611e7c.jpg)
![20220124060806_1](https://user-images.githubusercontent.com/41568950/150726593-9c8178a9-a29a-4cac-a2ef-31e34f8fd3d5.jpg)
![20220124060744_1](https://user-images.githubusercontent.com/41568950/150726595-933397a0-2fe6-4f01-bca7-1b9a2eb54977.jpg)

**Comment by bzzbzzbzzbeep** [comment]
Make sure you're on Direct X9 in Renderer at Opening Window in settings.

**Comment by ThomasLeyk** [comment]
> Make sure you're on Direct X9 in Renderer at Opening Window in settings.

That fixed it. Thanks.
