### ISSUE TITLE
Irkutsk - Minister have wrong name

### ISSUE THREAD

**Issue by emil-scarlet** [TNODevs/TNO-Bug-Tracker#508]
**Questions**

- Operating System:   Windows 10
- HOI4 Version:   1.11.4
- TNO Version:   1.2.1 Toolbox Theory(NSB patch)
- Any other mods in use:   +JP The new order
- Were you using Steam?   yes
- Which expansions do you NOT have?   none

**Longer Description of Issue:**
The initial Security Minister of Irkutsk is named Jamiyangiin Lkhagvasuren, which is wrong because he is a Mongolian and is in the People's Revolutionary Council. He is named Pavel Bulanov in the localisation key.
**Steps to Reproduce/Cause Issue:**

1. Play as Irkutsk, and he is there

**Screenshots:**
![image](https://user-images.githubusercontent.com/72238679/150738656-6ee34d40-8f0b-4ebe-bcbb-7e41c262dcb8.png)
![image](https://user-images.githubusercontent.com/72238679/150739099-4f6bf497-53e7-4b34-84aa-1d28894fd02a.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
