### ISSUE TITLE
HMMLR->Commonwealth of England Crash

### ISSUE THREAD

**Issue by RolfSonOfRolf** [TNODevs/TNO-Bug-Tracker#509]
**Questions**

- Operating System:
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1 (NSB patch)
- Any other mods in use: TNO Music mod
- Were you using Steam?: Yes
- Which expansions do you NOT have? Battle for the Bosporus/La Resistance 

**Longer Description of Issue:**
I finished the ECW as HMMLR, and went down the path for reconstruction. I was campaigning for Auchinleck's NLD, but the SLP ended up winning. I saved the game shortly after becoming the Commonwealth, and when I attempted to open the save, it crashed on loading. I tried loading an earlier autosave, and this time upon an SLP victory in the elections, the game crashed instantly.  

**Steps to Reproduce/Cause Issue:**

1. Win ECW as HMMLR

2. Campaign for Auchinleck (Unsure if that's required)

3. Lose to the SLP in the Elections.

**Comment by runelead00** [comment]
Believe this has been fixed in current version
