### ISSUE TITLE
England - Event for Welsh unification missing description

### ISSUE THREAD

**Issue by awnman** [TNODevs/TNO-Bug-Tracker#51]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2
- Any other mods in use: No
- Were you using Steam?: Yes
- Which expansions do you NOT have?: La Resistance

**Longer Description of Issue:**
Text for a event regarding Welsh unification is placeholder
**Steps to Reproduce/Cause Issue:**

1. Play as England and peacefully reunify Wales

2. Have the event reducing Welsh Unrest fire.

etc...

**Screenshots:**
![Screenshot (275)](https://user-images.githubusercontent.com/88620806/128634469-903d3fa6-3ba7-4dad-b2a4-34e4b5ba3e08.png)

**Comment by Scarsoftime** [comment]
Fixed in the developer build. Thank you for your report.
