### ISSUE TITLE
Omsk - The "First batch" event triggered by completing the "Fund Omsktransmash" focus doesn't work.

### ISSUE THREAD

**Issue by rundownturner4** [TNODevs/TNO-Bug-Tracker#514]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Most recent
- TNO Version: Most recent
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? La Resistance, Battle for the Bosporus, No Step Back

**Longer Description of Issue:**
In the Omsk Focus Tree there is a focus named "Fund Omsktransmash". Completing that focus will trigger an event named "First batch" that is supposed to add 250 Main Battle Tank (MBT) and Infantry Fighting Vehicle (IFV) units to your national stockpile. For some reason however, i didn't get any new MBTs or IFVs added to my stockpile after doing the focus and getting the event.

**Steps to Reproduce/Cause Issue:**

1. Get Dmitry Yazov in power as the leader of Omsk, and deal with the Old Guard to prevent him from being assassinated.

2. Wait until the German civil war occurs and the Luftwaffe terror bombings stop. A new branch of the Omsk focus tree should soon appear. (see first screenshot)

3. Do the "Clear Skies" focus, then the "The Task Ahead" focus, and finally the "Fund Omsktransmash" focus.

4. After finishing the "Fund Omsktransmash" focus, you will get the "First batch" event where you are supposed to receive 250 MBTs and 250 IFVs (see second screenshot), but for some reason don't.

**Screenshots:**

![20220124220909_1](https://user-images.githubusercontent.com/30832634/150865530-3d3e8ec9-46a8-4018-b960-8d9148d953e9.jpg)

![20220124210628_1](https://user-images.githubusercontent.com/30832634/150862057-ffe1aa75-bc99-4aea-916a-a25185ea1452.jpg)

**Comment by runelead00** [comment]
No longer an issue on UB
