### ISSUE TITLE
All Countries - Crash during country load

### ISSUE THREAD

**Issue by wolfgang2337** [TNODevs/TNO-Bug-Tracker#515]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.5.2571
- TNO Version: 1.2.1
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

The game loads, but once I select a country and hit start, it loads for a bit before crashing while the loading bar says "Capturing Asuncion."

**Steps to Reproduce/Cause Issue:**

1. Select Country

2. Hit Start

3. Game crashes during "Capturing Asuncion"
**Screenshots:**

**Game Saves and Log Files, if possible:**

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7929290/error.log)

**Comment by El-Lanf** [comment]
Revert from beta patch back to 1.11.4
