### ISSUE TITLE
Vyatka -- Crashes on event of Anti Bolshivik Pact (1/26/1964)

### ISSUE THREAD

**Issue by kaiserm1305** [TNODevs/TNO-Bug-Tracker#517]
**Questions**

- Operating System: Windows 
- HOI4 Version: 1.11 barbarossa
- TNO Version: most recent, newest one with NSB
- Any other mods in use: Player Lead Peace
- Were you using Steam? yes
- Which expansions do you NOT have? I have all of them

**Longer Description of Issue:**
Playing as Yyatka, once Komi invites me to anti bolshivik pact, (also on 1/26/1964, could be either) any attempts to unpause game after lead to it crashing. ive tried both options and ignoring the event, tho it always crashes.
**Steps to Reproduce/Cause Issue:**

1.play as Vyatka 

2. Have Komi request Anti Bolshivik Pact

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/98362232/150883373-68c4f3ec-2d51-4817-8467-01729a9368da.png)

**Game Saves and Log Files, if possible:**
cant seem to import save

**Comment by runelead00** [comment]
Should no longer be issue on UB
