### ISSUE TITLE
All - Loading up saves crashes the game

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#518]
**Questions**

- Operating System: Windows
- HOI4 Version: Current Version
- TNO Version: Toolbox Theory NSB patch
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**

Every time I load up a save from local, the loading bar would always go midway before ultimately crashing the game.

**Steps to Reproduce/Cause Issue:**

1. Save a game

2. Load up a save

3. Wait till the loading bar goes midway

4. Crash

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**

**Comment by masterbobli** [comment]
This is a known issue. Please revert back to 1.11.4

**Comment by bzzbzzbzzbeep** [comment]
> This is a known issue. Please revert back to 1.11.4

where even is that I cant even find it

**Comment by masterbobli** [comment]
> > This is a known issue. Please revert back to 1.11.4
> 
> where even is that I cant even find it

Does 1.11.5 have this issue?

**Comment by bzzbzzbzzbeep** [comment]
> > > This is a known issue. Please revert back to 1.11.4
> > 
> > 
> > where even is that I cant even find it
> 
> Does 1.11.5 have this issue?

Turns out in every start of the month it might be the autosave that could've corrupted the saves and the rest that was made thereafter.
