### ISSUE TITLE
China - Typo in focus

### ISSUE THREAD

**Issue by awnman** [TNODevs/TNO-Bug-Tracker#52]
**Questions**

- HOI4 Version:1.10.8
- TNO Version: 1.1.2
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
The second China in this focus should read Japan as China exporting to China does not make sense
- [x] 1. 
![Screenshot (228)](https://user-images.githubusercontent.com/88620806/128634576-ef3995cf-c3f2-4a27-81ed-555b4f5b0733.png)

- [x] 2. 
(Screenshot here)

**Comment by tkgitno** [comment]
Fixed in Dev Build.
