### ISSUE TITLE
The Russian Way makes Thatcher UK get $180 Billion Yearly?!?!?!

### ISSUE THREAD

**Issue by BoneSteelTNO** [TNODevs/TNO-Bug-Tracker#520]
**Questions**

- Operating System: Windows 11 Desktop
- HOI4 Version: 1.2.1 NSB
- TNO Version: 1.2.1
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I got all of them baby.

**Longer Description of Issue:**
So you see I just finished the focus "The Russian Way" and it times your current GDP by 2, mine being 89 Billion, leaving my yearly income to be 178 Billion yearly, and a surplus of said 178 billion. 
**Steps to Reproduce/Cause Issue:**

1. Go Thatcher UK Part 2

2. Select and Complete Focus "The Russian Way"

3. Get your population drunk on state-owned alcohol

4. Profit?

**Screenshots:**
https://cdn.discordapp.com/attachments/806276324297539586/935350863139057756/unknown.png
https://cdn.discordapp.com/attachments/806276324297539586/935350960698564678/unknown.png

**Comment by masterbobli** [comment]
Fixed in the dev version. Thanks for reporting.
