### ISSUE TITLE
All countries (at least Zhukov's WRRF) - Crash corrupts all saves

### ISSUE THREAD

**Issue by StinkyIdiot** [TNODevs/TNO-Bug-Tracker#521]
**Questions**

The game crashes at some point in 1964 and 1965, and thereafter every save, regardless of how old it is in the same campaign, is corrupted.

- Operating System: Windows 11
- HOI4 Version: latest version
- TNO Version: latest version
- Any other mods in use: custom country paths, 2wrw, radio tno, vt323 map font; I also use the -opengl command, because otherwise I can't get TNO to work on my laptop without crashing during the first loading screen for the main menu.
- Were you using Steam? Yes
- Which expansions do you NOT have? None of the music packs, armor packs, etc.; Battle of the Bosporus; Man the Guns

**Longer Description of Issue:**

I was playing Zhukov's WRRF, and around Summer of 1965 the game crashed, and then corrupted the rest of my saves, so that they crash the game even when trying to load them in the loading menu that you go to from the main menu, before even clicking to load the save to actually play it. I tried to play it again tonight, and in December of 1964, the game crashed and corrupted my saves, the same as last time.

**Comment by tkgitno** [comment]
Check if Goering wins the Civil War (fixed in Dev build), otherwise will be helpful to upload the corrupted save

**Comment by StinkyIdiot** [comment]
I can't figure out how to upload hoi4 saves to show that it's corrupted, unfortunately. I will try to upload them onto some file sharing website and post the link here.

**Comment by StinkyIdiot** [comment]
https://drive.google.com/drive/folders/1fC1q2nZN7UxnJi97FButIyDjDIhQOCkX?usp=sharing
here's a google drive file with the last 3 saves

**Comment by tkgitno** [comment]
Can you change the permissions on the drive?
Or alternatively you can compress the save file and drag the zip file here directly.

**Comment by StinkyIdiot** [comment]
Changed the permissions for everyone to view, not just people with the link. If it still is broken, let me know so I can try something different

**Comment by tkgitno** [comment]
Try to disable custom country paths and restart a new game. Also turn off steam cloud saves if that's enabled

**Comment by StinkyIdiot** [comment]
I disabled the custom country paths submod and looking at some others on here I think I figured out what happened. So each time I played it the game would crash on a certain date at 21:00, and after I managed to force the game past that date, it would eventually crash later on (within a year roundabout) and from that point on, I could never pull up a save without the game crashing. I think it all has to do with the SLP winning an election. Any fix for this, or just wait for a patch?

**Comment by tkgitno** [comment]
Ah thx for finding out the culprit, in that case try to delete these parts in ENG_Government_Changes.2 of the TNO_England event file for now:

		remove_advisor_role = {
			character = FEN_Reg_Birch
			slot = economy_minister
		}
		add_advisor_role = {
			character = FEN_Reg_Birch 
			advisor = {
				slot = head_of_government
				cost = 50
				idea_token = ENG_Reg_Birch_hog
				traits = {
					hog_ambitious_union_boss
				}
				allowed = {
					original_tag = ENG
				}
			}
		}
		
		remove_all_ministers = yes
		add_ideas = {
			ENG_Reg_Birch_hog
			ENG_Alfred_Robens_eco
			ENG_Peter_Shore_for
			ENG_Bill_Alexander_sec
		}
			
Should temporaily fix this, I'll revise the code later (rarely do code errors corrupt saves so weird case)

**Comment by StinkyIdiot** [comment]
Thank you!
