### ISSUE TITLE
HMMLR England - Smuggled American tanks are all just naked chassis with NSB

### ISSUE THREAD

**Issue by d15ddd** [TNODevs/TNO-Bug-Tracker#522]
**Questions**

- Operating System: Windows 11
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1 
- Any other mods in use: TNO Radio mod
- Were you using Steam?: Yes
- Which expansions do you NOT have?: Got em all

**Longer Description of Issue:**
So apparently the americans scammed me out of getting my tanks and only sent me 180 tank chassis, no soft attack, no hard attack, just vehicular manslaughter I suppose.
**Steps to Reproduce/Cause Issue:**

1. As HMMLR England, do all 3 special deliveries with the NSB DLC

2. Wait for the ECW to fire, only to realise that your only tank division is filled with completely naked tanks

**Screenshots:**
![image](https://user-images.githubusercontent.com/98374042/150911653-29b98785-a43f-4b9e-8545-e76ee4c7bfb5.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
