### ISSUE TITLE
Ordensstaat Burgund - Crash when start scenario as following country

### ISSUE THREAD

**Issue by talonthien123** [TNODevs/TNO-Bug-Tracker#523]
**Questions**

- Operating System: Window 11
- HOI4 Version:1.11.2 "Barbarossa"
- TNO Version: 1.2.1
- Any other mods in use: None
- Were you using Steam? I've tried both and still not working
- Which expansions do you NOT have? None

**Longer Description of Issue:** 
Enter the game with 1.11.2 version with TNO mod that I just installed on steam workshop whose version is 1.2.1 which all DLC enabled and no sub mod, Get in the scenario Like a normal day with TNO and hope for a beautiful TNO gameplay day with Ordensstaat Burgund and suddenly afted I chosed scenario loaded and the game crash.

**Steps to Reproduce/Cause Issue:**

1. Enter the game with no Submod and all dlc enabled

2. Play as Ordensstaat Burgund. 

**Screenshots and Game Saves and Log Files**
https://drive.google.com/file/d/1XXaUM9YvqxwAfja5jA8sjvsUWdDZlx7a/view?usp=sharing

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed and cause currently unknown
