### ISSUE TITLE
Sverdlovsk when they turn into Ural Military District

### ISSUE THREAD

**Issue by maxlel** [TNODevs/TNO-Bug-Tracker#525]
**Questions**

- Operating System:
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use:Nope
- Were you using Steam? Yes
- Which expansions do you NOT have?
None
**Longer Description of Issue:**
As soon as I form the nation I get too much of an economy and I have too many production units. Unless you guys really love Rokossovsky, which I mean who doesn't, this is probably a bug.
**Steps to Reproduce/Cause Issue:**

1.Conquer your neighbors

2.Maybe before turning into Ural Military district or when you turn into it, you gain a bunch of production units with a GIGA economy
![image_2022-01-25_144340](https://user-images.githubusercontent.com/39634470/150988065-86a9f18e-6403-4d9a-831a-7a39e80c31fa.png)

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Can't do much to fix this without knowing the nation causing the trade PU bug, closing since that information is probably lost at this point
