### ISSUE TITLE
state lore error

### ISSUE THREAD

**Issue by mapu1283** [TNODevs/TNO-Bug-Tracker#526]
**Questions**

- Operating System:Windows 10
- HOI4 Version:1.11.4
- TNO Version:1.2.1
- Any other mods in use:no
- Were you using Steam? yes
- Which expansions do you NOT have? No step back

**Longer Description of Issue:**

1. Prag state lore has disappeared. Prag state lore exists in the TNO_state_l_English.yml file, but it does not appear in the game.
![20220125223725_1](https://user-images.githubusercontent.com/95910611/150992006-42c28125-e167-4118-8cba-5b42aba05cd7.jpg)
![20220125_224121](https://user-images.githubusercontent.com/95910611/150992510-a76f4847-8f9c-48d4-9c85-eb6474fa2c8c.png)

2.Macau's photos and Hong Kong's photos are switched.(That clock tower is in Hong Kong.)
![20220125232206_1](https://user-images.githubusercontent.com/95910611/150995850-1269a355-e9dc-4823-8c4f-340cc6f1e7d6.jpg)
![20220125232208_1](https://user-images.githubusercontent.com/95910611/150995867-c2fe738d-d8f8-4ab4-9ad3-d95c5b5d404b.jpg)

3.There are some state lore of South America that have disappeared with the update.(Quito,Cuzco,Campo de Mayo,Martín García, etc.) 

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by Stormeagle449** [comment]
Fixed in dev build.
