### ISSUE TITLE
Crash during loading after choosing a country.

### ISSUE THREAD

**Issue by Aorion06** [TNODevs/TNO-Bug-Tracker#527]
- Operating System: Windows 10
- HOI4 Version: 1.11.5.2571
- TNO Version: 1.2.1 Toolbox Theory NSB Patch
- Any other mods in use: No
- Were you using Steam?: Yes but running the local copy of the steam version of the mod (steam version only runs vanilla HoI4 for reasons unclear, redownloading a mod or reinstalling the game or even steam itself didn't fix that)
- Which expansions do you NOT have?: None

Longer Description of Issue:

The game crashes to desktop after choosing a country during loading, error log reports that it's probably because of an error related to music player GUI.
[TNO Crash Log Files.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7934638/TNO.Crash.Log.Files.zip)

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed and cause currently unknown
