### ISSUE TITLE
Speer Germany - Firm chain focus dont give any ressource right 

### ISSUE THREAD

**Issue by Starco77** [TNODevs/TNO-Bug-Tracker#528]
**Questions**

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use: Better air wing deployement 
- Were you using Steam?Yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**

The focus firm chain say that every ressource discovered in the eastern regime should be mine i got none

**Steps to Reproduce/Cause Issue:**

1.Play speer 

2.Pick the focus firm chain

3. No ressource

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
