### ISSUE TITLE
United States - Crashing After Peace Deal

### ISSUE THREAD

**Issue by GraceF4** [TNODevs/TNO-Bug-Tracker#529]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? i got all

**Longer Description of Issue:**
In April 1965 the game crashes during the South African war and I have no clue why
**Steps to Reproduce/Cause Issue:**

1. Be in South African war

2. peace deal text shows up, game crashes

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**

[TNO USA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7936735/TNO.USA.zip)

**Comment by tkgitno** [comment]
Fixed in Dev Build
