### ISSUE TITLE
USA - Both of Goldwater's environment legislation is locked

### ISSUE THREAD

**Issue by CamtheWideboi** [TNODevs/TNO-Bug-Tracker#53]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2b
- Any other mods in use: Terra e Liberta
- Were you using Steam? Yes
- Which expansions do you NOT have? N/A

**Longer Description of Issue:**
The focuses to introduce the Clean Water Act and the EPA say that there should be no major bill being debated in congress, but when I select the focus, it becomes locked. I'm able to deal with the EPA focus by just forcing it through Congress, but for the Clean Water Act, I'm not able to, so when I select it, I'm stuck and can't progress through the rest of the tree due to you not being able to cancel it.

**Steps to Reproduce/Cause Issue:**

1. Get Goldwater elected

2. Go down his environmental branch until you reach the legislation focuses, and select either one of them.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48650106/128642988-711c783a-92c0-41d7-8cb4-55caa90f5897.png)
![image](https://user-images.githubusercontent.com/48650106/128643111-b8b43654-bd9b-4a39-a7c4-d56ecc364926.png)

**Comment by CamtheWideboi** [comment]
Also, after the Oil Crisis, where I was able to unfocus on the CWA focus, it locks the rest of the tree.

**Comment by runelead00** [comment]
Fixed in Current Release
