### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by empedocles2** [TNODevs/TNO-Bug-Tracker#530]
**Questions**

- Operating System: Windows 64
- HOI4 Version:  11.4.e26e
- TNO Version: 1.21 - NSB patch
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? non

**Longer Description of Issue:** 
Hi all, first of all great mod. I'm playing as England and won the civil war as HMMLA. I elected the SNL (democrats) and just finished the focus where the queen is coronated.

However, I'm having several bugs:

-Faction Leader portrait is blank with a weird name (however in my stability I see the effects of the Democratic leader)

-The Minister of foreign affair, and the other guy, never appeared. This happened despite I finished the focus as well.

-I cannot name anybody in the Officer Corps.

Not sure if others are facing the same problem. any chance I can fix this through the console?

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Current Release
