### ISSUE TITLE
Map isn't displaying - everything is black except for the map text

### ISSUE THREAD

**Issue by nnbosko** [TNODevs/TNO-Bug-Tracker#531]
**Questions**

- Operating System: Windows 11
- HOI4 Version: Barbarossa v1.11.4.e26e
- TNO Version: Steam Version 21 January 2022 v1.2.1
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? 

**Longer Description of Issue:**

The map isn't displaying at all, save for the text.

**Screenshots:**

![image](https://user-images.githubusercontent.com/5121868/151075494-f09f375f-574e-4d36-8d44-edea89463291.png)

**Comment by tkgitno** [comment]
Fixed in Dev Build (Change settings to DX9 meanwhile)
