### ISSUE TITLE
Go4 Speer Germany - after switching to authdem, Speer is replaced with a generic leader with no portrait.

### ISSUE THREAD

**Issue by thecompanionnoob** [TNODevs/TNO-Bug-Tracker#532]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.4
- TNO Version: v1.2.1 - TT NSB update 
- Any other mods in use: none
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all expansions.

**Longer Description of Issue:**
After switching to authdem at the end of the go4 path for speer's germany, speer is replaced with "Dieter Neumann" who has no portrait. 
**Steps to Reproduce/Cause Issue:**
1. go through go4 path in speer's germany. (I did not go through an entire new playthrough to see if this is reproducible, but i did load a save from before becoming authdem and it still happened, with the same leader.)

**Screenshots:**
![20220125212441_1](https://user-images.githubusercontent.com/97998469/151094888-6a2d09ef-0bb0-49ca-9c85-866be9584e18.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
