### ISSUE TITLE
Bormann's Reich - Doesn't try to bring Moscowien or Kaukasia back into the fold

### ISSUE THREAD

**Issue by AbsoluteMonarchLWEx** [TNODevs/TNO-Bug-Tracker#533]
**Questions**

- Operating System: Windows
- HOI4 Version: 11.4.e26e
- TNO Version: 1.21 - NSB patch
- Any other mods in use: Last Waltz Expanded and a very minor localization submod that changes Japan's and Manchukuo's names and faction name. 
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all of the expansions. 

**Longer Description of Issue:**

In my recent run as Oktan's Samara, I noticed that Bormann wasn't really doing anything after winning the GCW. He was stuck on his postwar focus tree for what seemed like a long time. I tagged GER to see what was going on, and lo and behold, he was stuck because neither Moscowien nor Kaukasia were in his faction. I checked the decisions and Bormann was stockpiling political power, even though he was more than able to select the focus to attack Moscowien. I manually selected the decision for him before switching back to SAM and resuming my game. Bormann proceeded to easily conquer Moscowien, but did not puppet it, Once again, I tagged into GER and selected the option to establish a new puppet regime over Moscowien. I had to tag into GER one final time to prod Bormann into conquering Kaukasia, after which Bormann finally selected the focus that had been evading him for years, and he game proceeded normally from that point on, albeit with a severely nerfed Germany. 

This glitch had the wholesome side-effect of a tiny independent Georgian statelet existing, since Bormann waited long enough that the Kaukasia revolted started, and although he took the lion's share of the former Reichskommisariat, Georgia got to keep the province that contained its capital and was left to its own devices. 

**Steps to Reproduce/Cause Issue:**

1. Play Oktan and wait for Bormann to win the GCW I guess? No idea why this might have happened. My submods only affect the music and Japan/Manchukuo, respectively. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/98442554/151102577-f1dcf41e-8522-4423-aff8-7f6d47150137.png)
![image](https://user-images.githubusercontent.com/98442554/151102600-236f7333-f46b-4f88-99c1-581dfc8fdc04.png)

**Comment by runelead00** [comment]
Should be fixed in Current Release
