### ISSUE TITLE
Chita - Shepunov remains head of government after banishment

### ISSUE THREAD

**Issue by tichbou** [TNODevs/TNO-Bug-Tracker#534]
**Questions**

- Operating System: MACOS 12.1
- HOI4 Version: 1.11.4
- TNO Version: 1.2.1
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

After you progress through Mikhail II's path in Chita, Shepunov remains the Head of Government and Security Minister even after he is banished.

**Steps to Reproduce/Cause Issue:**

1. Play Mikhail II's path until you banish Shepunov

2. Check cabinent

**Screenshots:**
[save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7939180/save.zip)

![image](https://user-images.githubusercontent.com/98229246/151109905-2f86bdd5-c485-4d3b-b081-c31ca7e1801d.png)

**Comment by BorisFor317** [comment]
I fix it by changing file events\TNO_Chita.txt to:
```
hidden_effect = {
	remove_all_ministers = yes
	add_ideas = CHT_Anatoly_Sobchak
	add_ideas = CHT_Ivan_Mikhailov_eco
	add_ideas = CHT_Dmitry_Volkogonov_sec
	add_ideas = CHT_Nikolay_Ukhtomsky_for
}
```
I had to override all ministers to achieve right result.
There is a bug: setting ministers with add_ideas doesn't override them (checked when playing Chita). Other example: Boris Shepunov remains Security minister after death of Semyonov.

**Comment by runelead00** [comment]
All minister changes for Chita should be fixed in UB
