### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#536]
**Questions**

- Operating System:
- HOI4 Version: NSB
- TNO Version: NSB patch
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
Not sure if this is a bug, but this popped up at the start of the West African War

**Screenshots:**
![Screenshot (2375)](https://user-images.githubusercontent.com/98137316/151239996-59059ae8-a497-46c7-86f9-f3b1dcdae747.png)

**Comment by ModdingAccount** [comment]
Fixed (Revised) in dev build
