### ISSUE TITLE
USA-Mislabeled state

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#537]
**Questions**

- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
In elections, Texas is referred to as "Northern Texas".

![Screenshot (2376)](https://user-images.githubusercontent.com/98137316/151240153-908c304b-f4bd-420c-b257-90cfa125d857.png)

**Comment by ModdingAccount** [comment]
Fixed in Dev Build
