### ISSUE TITLE
USA-Sending Iberian anti-tank equipment to Free France

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#538]
**Questions**

- Operating System:
- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
Literally the title

**Screenshots:**
![Screenshot (2381)](https://user-images.githubusercontent.com/98137316/151240322-eae32d82-947c-4b9b-879f-173d4951e2be.png)

**Comment by runelead00** [comment]
Fixed on UB
