### ISSUE TITLE
USA-Cameroon Collapse gazette spawns twice

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#539]
**Questions**

- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Same as title
![Screenshot (2385)](https://user-images.githubusercontent.com/98137316/151240496-9dec8574-c322-4d56-b6fa-fc792a9dc83f.png)

**Comment by runelead00** [comment]
Can't reproduce on current builds, potentially was an issue with something scripted effect triggering an event twice, move specfic event to fire only once for good measure
