### ISSUE TITLE
Shonan-Marai Gunseibu- incomplete loc for head of government, foreign minister, and security minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#540]
**Questions**

- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Same as title
![Screenshot (2387)](https://user-images.githubusercontent.com/98137316/151240639-02b27ab2-5d98-49e1-af7b-40d1dd03ed08.png)
![Screenshot (2389)](https://user-images.githubusercontent.com/98137316/151240753-4600f273-7ca9-459c-a2c2-214a6ec9b09f.png)
![Screenshot (2388)](https://user-images.githubusercontent.com/98137316/151240794-c4e363ee-85c2-486f-b507-e16fb750e0e3.png)

**Comment by runelead00** [comment]
Fixed in current release
