### ISSUE TITLE
Iberia-No security minister if I support Speer

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#542]
**Questions**

- Operating System:
- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**
When selecting the focuses to support Speer via sending the Falangist old guard, Agustin Munoz Grandez is no longer just removed from my pool of generals, but also stops being my security minister. While he returned to the general pool once the GCW ended(with a Bormann victory) he did not become security minister again, and the position remained vacant and unfillable until I elected the Opus Dei.

**Screenshots:**
![Screenshot (2402)](https://user-images.githubusercontent.com/98137316/151241334-c39e0200-c09c-495d-b35d-7e3aadbcc22a.png)

**Comment by runelead00** [comment]
Fixed in Current Release
