### ISSUE TITLE
Iberia-negative liquid reserves

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#543]
**Questions**

- Operating System:
- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**
An event I can't remember removed money from my liquid reserves. Instead of adding this to my debt, I was given negative liquid reserves. I "paid my debt" with them, leading to nothing changing and my reserves going back to zero

**Screenshots:**
![Screenshot (2403)](https://user-images.githubusercontent.com/98137316/151241601-ea01f6cb-09ac-49f1-b54e-6eea0b1fee95.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
