### ISSUE TITLE
Free France-likely unintended annexation of territory

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#544]
**Questions**

- Operating System:
- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
Can't remember which country or countries this is, but I don't think this is how Free France's post-victory stuff is supposed to go

**Screenshots:**
![Screenshot (2404)](https://user-images.githubusercontent.com/98137316/151241808-6778a435-111b-431b-b2d4-505b4201c39d.png)

**Comment by Stormeagle449** [comment]
Should be fixed in current build, but if this happens again please let us know.
