### ISSUE TITLE
OFN Mandate East Africa/Uganda-Idi Amin released as OFN observer

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#545]
**Questions**

- Operating System:
- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have?all

**Longer Description of Issue:**
The OFN released East Africa peacefully at the end of the focus tree for the mandate. All other governments were either libdem or socialist, presumably the "good" endings, and yet Uganda was run by ultranat Idi Amin and still an OFN observer like the rest.

**Screenshots:**
![Screenshot (2405)](https://user-images.githubusercontent.com/98137316/151242037-2bfcb83c-3ac9-4bcd-b0fc-fe2334349efa.png)

**Comment by masterbobli** [comment]
This is an intended feature. There's an event that lets OFN east Africa mandate choose Idi Amin or Tito Okello as the leader.
