### ISSUE TITLE
Iberia-Finishing Gibraltar Damn event loc

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#546]
**Questions**

- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Unsure if the event is supposed to have this description
![Screenshot (2406)](https://user-images.githubusercontent.com/98137316/151242226-f402797e-1f93-4ce2-9f65-23782243b40b.png)

**Comment by Scarsoftime** [comment]
Gibraltar damn....

It's fixed
