### ISSUE TITLE
United States - Crash at exact moment of winning the African War

### ISSUE THREAD

**Issue by johnt28** [TNODevs/TNO-Bug-Tracker#548]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.4.e26e
- TNO Version: 1.2.1
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I don't have the radio dlc.

**Longer Description of Issue:**
Playing as the USA, with apocaliptic war discontent and with Robert Kennedy as president, the game crashes exactly in the moment the peace deals finish. It's april (aprox) 1966 in congressional elections period, with the battle for italy on. Don't know if it's important, but Nazi central africa was the last to capitulate. Log files and save game included.

**Steps to Reproduce/Cause Issue:**

1. Playing as the US, getting Robert Kennedy as president.

2. Winning the African war, capitulating Central Africa last.

**Screenshots:**

**Game Saves and Log Files, if possible:**
[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7945730/logs.zip)
[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7945740/logs.zip)

**Comment by tkgitno** [comment]
Fixed in Dev Build

**Comment by johnt28** [comment]
Any chance you could share the file fixed? Thanks in advance!

**Comment by tkgitno** [comment]
[Ironman TNO United States of America.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7948625/Ironman.TNO.United.States.of.America.zip)
