### ISSUE TITLE
England-David Stirling re-election event missing text

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#549]
**Questions**

- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
same as title
![Screenshot (2409)](https://user-images.githubusercontent.com/98137316/151251432-ac709a07-3814-40d4-aac9-8da354adc5fe.png)

**Comment by ModdingAccount** [comment]
Fixed in dev build.
