### ISSUE TITLE
Iberia-achieved Spartan Discipline for military

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#550]
**Questions**

- Operating System:
- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
Obtained the highest level of military development, which is supposed to be impossible
**Steps to Reproduce/Cause Issue:**
Normal reformist playthrough of Iberia
**Screenshots:**
![Screenshot (2412)](https://user-images.githubusercontent.com/98137316/151251679-a98cd20e-669b-4c76-b322-57d358463c65.png)

**Comment by runelead00** [comment]
No longer should be possible
