### ISSUE TITLE
CHI - Typo in Literacy Programs

### ISSUE THREAD

**Issue by sinopike** [TNODevs/TNO-Bug-Tracker#551]
**Questions**

- HOI4 Version:1.11.4
- TNO Version:1.2.1
- Any other mods in use:

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

- [ ] 1. In the literacy reform event, (after completing "Literacy programs" focus) for CHI, Hanzi is misspelled as Hanxi.
![image](https://user-images.githubusercontent.com/46058473/151284734-51eb73d0-8f12-4a29-be4f-fd52e48dac81.png)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
