### ISSUE TITLE
HMMLR England - Cannot use civilian or military factories post civil war.

### ISSUE THREAD

**Issue by Lemonater47** [TNODevs/TNO-Bug-Tracker#553]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.5 (Game just updated today before I started this England game).
- TNO Version: 1.2.1
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosporus

**Longer Description of Issue:**
England starts off not being able to build or use factories. However when the civil war started and I picked HMMLR I still couldn't use military factories. I won the war and completed the "For Ashes" focus which specifically mentions allowing construction again. Yet nothing. I've had the first election and still can't use any factory aside from Naval dockyards. Which I have been able to use since the beginning of the civil war. There's no National Spirit to suggest that I can't use them either.
**Steps to Reproduce/Cause Issue:**

1. Go down HMMLR tree. I can't remember what order I did the decisions in. But I started out doing the tanks (and lost the first shipment as I misremembered how it worked) and I took that single use 140 pp decision. 

2. Start the civil war

3. Can't use factories

4. Finish the civil war and For Ashes and still can't use factories.  

**Screenshots:**
Post election screenshots. You can see I have the production units assigned to factories yet nothing. It's 1965 with an NDL England. 
![20220128025819_1](https://user-images.githubusercontent.com/40253852/151374601-9911cca8-6391-423b-8eef-33fff98ddc78.jpg)
![20220128025816_1](https://user-images.githubusercontent.com/40253852/151374615-5012f9d4-fd94-4484-84ab-7f7f211beea9.jpg)

**Comment by GithubDexter** [comment]
Seems its not just England. Started a game as the USA and have the same bug happening to me.
![Image 2](https://user-images.githubusercontent.com/77835638/151383826-5300a191-ae94-4c70-8d8e-b5c6834e8642.png)

**Comment by Lemonater47** [comment]
I didn’t notice but the game actually updated to 1.11.5 today. Maybe that’s the reason. Will test an 11.4 game later if possible.

**Comment by Lemonater47** [comment]
Lol and paradox doesn't let us roll back to 11.4. So we're buggered until TNO finds a fix.

**Comment by ModdingAccount** [comment]
Unable to replicate.
