### ISSUE TITLE
Speer's Germany - CTD on 24:00:00 11/3/1966

### ISSUE THREAD

**Issue by ADudOverTheFence** [TNODevs/TNO-Bug-Tracker#555]
**Questions**

- Operating System: Windows 10 
- HOI4 Version: v1.1.4.e26e
- TNO Version: 1.2.1
- Any other mods in use: The New Order: The Last Waltz of Europe, The New Order: Radio
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Playing a run of Speer's Germany. Already dismantled the Cartels, focus being researched is 'Germania rules the Waves'. When reaching the date/time 24:00:00 11/3/1966, game freezes and sounds stop abruptly, sounds start playing again, game continues for a moment, and finally game CTD's.

**Steps to Reproduce/Cause Issue:**

1. Load save game

2. Run game to 24:00:00 /11/3/1966

3. ???

4. Game CTD's

**Screenshots:**

**Game Saves and Log Files, if possible:**
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7951736/error.log)
[ThousandDayReich.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7951745/ThousandDayReich.zip)

**Comment by tkgitno** [comment]
Fixed in Dev Build

**Comment by ADudOverTheFence** [comment]
Da linky to the dev build pls?

**Comment by masterbobli** [comment]
> Da linky to the dev build pls? Also: can I delete my current build, install the dev build and continue my playthrough or do I have to start a fresh one?

Dev builds are not available to the general public, but the fix should be included in the hotfix that is going to be released this weekend.

**Comment by ADudOverTheFence** [comment]
> > Da linky to the dev build pls? Also: can I delete my current build, install the dev build and continue my playthrough or do I have to start a fresh one?
> 
> Dev builds are not available to the general public, but the fix should be included in the hotfix that is going to be released this weekend.

Oh, thanks! Are current release saves going to be compatible with the next hotfix?

**Comment by masterbobli** [comment]
> Oh, thanks! Are current release saves going to be compatible with the next hotfix?
I'm not quite sure since I didn't fix this issue myself. If it still crashes when you load the save, you might need to start a new one.

**Comment by YanSGod** [comment]
This problem is because the focus 'Germania rules the Waves
