### ISSUE TITLE
Iberia-Rework increases in LibDem popularity

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#556]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
Increases in LibDem popularity should be nerfed, given that they now fire every time you do something that benefits both the social liberals and market liberals.
**Reasoning Behind Suggestion:**
This is my pie chart after taking every reformist decision save for one, the provision of extra ballot boxes to rural areas. Had I not done that and consequently gotten a large boost to condem and authdem, my pie chart would've been close to 95% LibDem, something that wouldn't at all reflect the stated popularities of the ConDem, AuthDem and Socialist factions.
![Screenshot (2423)](https://user-images.githubusercontent.com/98137316/151423581-5f2162cd-a7e0-4d4e-b45c-cee00eff56c7.png)

**Additional Information:**

**Comment by runelead00** [comment]
No longer an issue in UB due to return of LibCon ideology
