### ISSUE TITLE
Bormann's RK's-missing ministers

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#557]
**Questions**

- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Same as title
- [x] 1. 
![Screenshot (2424)](https://user-images.githubusercontent.com/98137316/151423695-081b4020-c7d7-48b7-8f4c-160e4480c85d.png)
- [x] 2. 
![Screenshot (2426)](https://user-images.githubusercontent.com/98137316/151423719-99410aeb-3c94-4f6a-8b11-0d5f0d897e95.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
