### ISSUE TITLE
All countries-Minister portraits replaced with SocDevs

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#558]
**Questions**

- Operating System:
- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
I don't know what triggered it, but after looking at the ministers for several of Bormann's RKs I suddenly could only view half a nation's ministers, with the latter two being replaced by their education and research socdevs. It affected every nation I looked at, but I've included multiple screenshots.

**Screenshots:**
![Screenshot (2427)](https://user-images.githubusercontent.com/98137316/151423983-adb1e9cb-0baa-40b5-86b8-2341444a6c06.png)
![Screenshot (2428)](https://user-images.githubusercontent.com/98137316/151424012-d995ed85-dafb-4db8-abe5-910d8bfef434.png)
![Screenshot (2431)](https://user-images.githubusercontent.com/98137316/151424044-d8a31a56-dff4-4195-a091-b3d482bbe6fc.png)
![Screenshot (2432)](https://user-images.githubusercontent.com/98137316/151424062-73d34425-d0cf-42b6-952c-669c0b6e9b1c.png)
![Screenshot (2433)](https://user-images.githubusercontent.com/98137316/151424078-f112eeb3-736d-474b-8e24-efdb2cce855a.png)
![Screenshot (2434)](https://user-images.githubusercontent.com/98137316/151424098-dcba62f8-d4fe-42c8-aa89-4099063e907a.png)

**Comment by Scarsoftime** [comment]
Vanilla HOI4 bug, cannot fix.
