### ISSUE TITLE
Mexico-type in Madrazo bio

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#559]
**Questions**

- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
In the second paragraph, the sentence "But Madrazo is not a simple continuance" has two spaces in between "is" and "not".
- [ ] 1. 
![Screenshot (2436)](https://user-images.githubusercontent.com/98137316/151424351-1fc3d6fb-9ad7-4149-9f3e-68e4d82c9241.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
