### ISSUE TITLE
Pan-Africanist Guinea shouldn't be in the French Community

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#561]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
Assuming this isn't a bug, it makes no sense for a Pan-Africanist leader to join the French Community after a De Gaulle victory.
**Reasoning Behind Suggestion:**

**Additional Information:**

**Comment by YanSGod** [comment]
Yes, Guinea puzzles me very much

**Comment by Stormeagle449** [comment]
Guinea can join Cameroon in certain cases, but won't join the PALF if Cameroon is too aggressive. Will eventually review the country in the near future.
