### ISSUE TITLE
Mark Lib Iberia-Focus tree glitch

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#562]
**Questions**

- Operating System:
- HOI4 Version: nsb
- TNO Version: nsb
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
After the Oil Crisis fired, my focus tree changed as if the social liberals had won the election, despite me having elected the market liberals and been doing their focuses for the past year.
**Steps to Reproduce/Cause Issue:**
Unknown, but it happened the instant the tree shifted to the oil crisis.
**Screenshots:**
![Screenshot (2440)](https://user-images.githubusercontent.com/98137316/151424928-6be74eb7-a3ad-4ccc-8325-f3224c88afd5.png)
![Screenshot (2441)](https://user-images.githubusercontent.com/98137316/151424946-7e83b2ab-a6b3-4b56-a3e0-f650f8b0f27e.png)

**Comment by runelead00** [comment]
Fixed in Current Release
