### ISSUE TITLE
Iberia - Problem with the mark-lib path

### ISSUE THREAD

**Issue by fulgurboj** [TNODevs/TNO-Bug-Tracker#563]
**Questions**

- Operating System:
- HOI4 Version: Last one
- TNO Version: Last one
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have?
No step back and death or dishonor
**Longer Description of Issue:**
Since the market liberal ideology group has been removed and it's now inside the liberal ideology group, when iberia gets the opus dei in charge after the elections, Miranda will appear as the leader of the country even though it has the opus dei focus tree. But the funniest thing is that after the petrol crisis because Iberia has Miranda as its leader, the focus tree changes to the lib-dem one
**Steps to Reproduce/Cause Issue:**

1. Get the opus dei elected in iberia

2. Have the oil crisis trigger a new part of iberias focus tree

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Current Release
