### ISSUE TITLE
Entire map - Everything is black and every bulding is on closer look not loaded

### ISSUE THREAD

**Issue by Zombiemancz** [TNODevs/TNO-Bug-Tracker#564]
**Questions**

- Operating System:Windows 10
- HOI4 Version:1.11.5
- TNO Version:1.2.1
- Any other mods in use:No
- Were you using Steam?Yes
- Which expansions do you NOT have?
- No step back, battle for bosporus

**Longer Description of Issue:**
I started up the mod and it just showed the map completely black, so i restarted it and encountered the same problem.
**Steps to Reproduce/Cause Issue:**

1. Update to newest version of launcher

2. I have no idea (maybe turn direct x11 on?)

etc...

**Screenshots:**
![Hearts of Iron IV (DirectX 11) 27 01 2022 20_36_49](https://user-images.githubusercontent.com/98554353/151432952-66743a3a-ecc9-49fb-a65b-8d342e22ab15.png)

**Comment by runelead00** [comment]
Fixed in current release
