### ISSUE TITLE
All Countries - Military and Civilian Factories not functioning

### ISSUE THREAD

**Issue by T3RR5V0N** [TNODevs/TNO-Bug-Tracker#565]
**Questions**

- Operating System: MacOS
- HOI4 Version: 1.11.5
- TNO Version: 1.2.1
- Any other mods in use: Last Waltz of Europe Expanded, TNO: The 2nd West Russian War (these mods were not the cause)
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**
When loading into a country, i noticed that the production units were not actually translating to mils and civs. reducing or increasing them doesn't change anything. This is apparent across every nation. loading and reloading don't work. uninstalling and reinstalling don't work either. 
**Steps to Reproduce/Cause Issue:**

1. Load into TNO

2. Select any country

3. Look at the production tab

![Screen Shot 2022-01-27 at 6 44 45 PM](https://user-images.githubusercontent.com/56271791/151461869-45672c8c-c657-4f19-92c0-9ab2a85cd9f0.png)

![Screen Shot 2022-01-27 at 6 44 52 PM](https://user-images.githubusercontent.com/56271791/151461871-766c42a1-3794-459a-8e55-e26d5a8c7c31.png)

![Screen Shot 2022-01-27 at 6 49 02 PM](https://user-images.githubusercontent.com/56271791/151462197-4fe9e2d6-38d0-484d-a1a0-d2de8b803acd.png)

![Screen Shot 2022-01-27 at 6 49 07 PM](https://user-images.githubusercontent.com/56271791/151462201-13d18d86-9388-48d7-818d-5b9aa8b3e0d8.png)

**Comment by Lemonater47** [comment]
This seems to be an 11.5 issue.

**Comment by BackAlleyDealer** [comment]
I have the same issue and i have all of the DLC

**Comment by Scarsoftime** [comment]
Fixed
