### ISSUE TITLE
USA - Global conflicts don't end

### ISSUE THREAD

**Issue by Milarqui** [TNODevs/TNO-Bug-Tracker#568]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.4
- TNO Version: Toolbox Theory - NSB compatibility patch
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back, Battle for the Bosporus

**Longer Description of Issue:**
I've finished propping up the Central African Mandates (managed to peacefully decolonize East Africa and Angola, the Congo entered its crisis just a couple of days away from achieving this) and the Global Conflict issue for this does not disappear. I also managed to win the Congo Civil War with victory, but the conflict remains standing. Plus, this causes the "The Scars Heal" trigger to increase domestic discontent with the war, even though it should have dropped to zero years before.

**Steps to Reproduce/Cause Issue:**

1. Win the South African War as the USA/OFN.
2. Establish the Mandates.
3. Help decolonize East Africa and Angola, while Congo suffers its crisis. A high level of investment into the Mandates may be necessary to cause the problem.
4. Win the Congo Civil War.
5. Observe as the dis

**Comment by ModdingAccount** [comment]
Fixed in dev build.
