### ISSUE TITLE
WRRF - Production Issues

### ISSUE THREAD

**Issue by OlderSport** [TNODevs/TNO-Bug-Tracker#571]
**Questions**

- Operating System: Windows
- HOI4 Version: 1.11.5
- TNO Version: 1.11.5 Hotfix (I believe)
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back

**Longer Description of Issue:**
I am unable to use production units in my game, whether it be civllian or military

**Steps to Reproduce/Cause Issue:**

1. Play WRRF

2. Gain a few production units

etc...
![20220129013905_1](https://user-images.githubusercontent.com/98641115/151656107-4528df64-786c-4ff6-b661-f920f92098c6.jpg)

**Screenshots:**

**Comment by Scarsoftime** [comment]
Fixed
