### ISSUE TITLE
Entire map is just black.

### ISSUE THREAD

**Issue by IAmEatingBread** [TNODevs/TNO-Bug-Tracker#573]
**Questions**

- Operating System: Pc
- HOI4 Version: 1.11.5
- TNO Version: 1.2.1
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? 

**Longer Description of Issue:**

The entire map is just black...exept the text and descriptions of Nations; etc.

**Screenshots:**
![20220129233626_1](https://user-images.githubusercontent.com/98671165/151680503-5f8ff392-4828-4073-9d70-668ad3411a2f.jpg)
![20220129232917_1](https://user-images.githubusercontent.com/98671165/151680508-10b07728-a3d2-417d-8974-38e5a3a98127.jpg)

**Comment by Scarsoftime** [comment]
Fixed
