### ISSUE TITLE
Battleplans, frontlines and fallback lines are not showing

### ISSUE THREAD

**Issue by Yoloseph** [TNODevs/TNO-Bug-Tracker#575]
- Operating System: Windows 11
- HOI4 Version:  1.11.5
- TNO Version: hotfix 1.2.1a
- Any other mods in use: "The New Order: Last Waltz of Europe  (Music Mod)"
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back

Longer Description of Issue:
Batleplans such as Frontlines, fallback lines, etc are not being shown on the map. The units move to the correct positions and the game shows the number of units on that frontline

Screenshots:
![20220130011845_1](https://user-images.githubusercontent.com/30907451/151683165-d5fd46bf-1e94-4d7b-9036-53881e8d676b.jpg)

**Comment by ModdingAccount** [comment]
Cannot be replicated
