### ISSUE TITLE
Jacques Rabemananjara missing from Madagascar

### ISSUE THREAD

**Issue by TimesNewLogan** [TNODevs/TNO-Bug-Tracker#577]
After winning in Madagascar and appointing Jacques Rabemananjara to lead, the event fired as usual... except he's been replaced by a blank portrait of Siegfried Vogel, an ideological crusader.  This issue only appeared after the latest update.

**Comment by TimesNewLogan** [comment]
Second playthrough, Walter Weissman instead of Vogel.

**Comment by tkgitno** [comment]
Fixed in Dev Build

**Comment by TimesNewLogan** [comment]
Excellent!  Eagerly awaiting the next patch!
