### ISSUE TITLE
GER - "Germania Rules The Waves" still causing CTD (#489 again)

### ISSUE THREAD

**Issue by jmaloy97** [TNODevs/TNO-Bug-Tracker#579]
**Questions**

- Operating System: Windows 11 Enterprise
- HOI4 Version: 1.11.5 (latest Barbarossa patch as of January 30th, 2022)
- TNO Version: NSB Hotfix A (1.2.1a)
- Any other mods in use:
"Map Modes+"
"Precise Buffs - Cheat Ideas"
"Tool Pack Updated 2021"

Were you using Steam? Yes
Which expansions do you NOT have? None

**Longer Description of Issue:**
Issue reported in #489 still happens despite being patched by devs; upon completion of "Germania Rules the Waves" by a victorious Speer, the game will crash to desktop.

**Steps to Reproduce/Cause Issue:**

1. Speer wins civil war
2. Speer completes the focus "Germania Rules the Waves"
3. Game should crash immediately afterwards

**Screenshots:**
![image](https://user-images.githubusercontent.com/50754569/151708412-4973e3bf-a6ee-4c24-b5a7-32584d6ca0c5.png)

The same section (as below) causes the CTD, when removed, the CTD does not occur.

![image](https://user-images.githubusercontent.com/50754569/151709086-d2f1f8b0-2222-4f78-8669-4bde599d1b0b.png)

**Comment by tkgitno** [comment]
Do you continue with the old save? This bug is caused by missing character flag which's only initialized at game start.

**Comment by jmaloy97** [comment]
> Do you continue with the old save? This bug is caused by missing character flag which's only initialized at game start.

This is a completely new game played as Sablin/Buryatia.

**Comment by jmaloy97** [comment]
This is probably a result of some garbage getting stuck in the pipeline with Steam updating the mod. This is a new Buryatia game but I've been having a lot of issues with HOI4 on Windows in general. I think this is probably not an issue with the game itself, now that I think about it.
