### ISSUE TITLE
SBA - Divine Mandate Trade Bug

### ISSUE THREAD

**Issue by dec1eyre** [TNODevs/TNO-Bug-Tracker#582]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.5
- TNO Version: Toolbox Theory NSB Patch A
- Any other mods in use: no
- Were you using Steam? Yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**
Playing as the SBA, I produce a small amount of tungsten. However, every so often the Divine Mandate of Siberia imports ~30,000 from me, destroying my resource stockpiles and probably production. They are doing similar things with steel. I don't know why.

**Steps to Reproduce/Cause Issue:**

1. Play SBA

2. Wait for Divine Mandate to start spawning

etc...

**Screenshots:**
![20220131131033_1](https://user-images.githubusercontent.com/98722733/151730365-22dafa3e-434b-47ac-8dba-4a24f2923f03.jpg)

**Comment by runelead00** [comment]
Should be fixed in current release
