### ISSUE TITLE
Germany - As Authdem GO4 Germany post Slave Revolt, a man with no portrait called Hermann Pfeiffer

### ISSUE THREAD

**Issue by TheWitchKing0fAngmar** [TNODevs/TNO-Bug-Tracker#583]
**Questions**

- Operating System: idk
- HOI4 Version: 1.1.5 or whatever the latest version is
- TNO Version: Latest Version
- Any other mods in use: Custom Country Paths and the Music Mod
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back and Bosporus 

Longer Description of Issue: Short description is the whole thing

Steps to Reproduce/Cause Issue: Idk 

1.

2.

etc...

**Screenshots:**
![20220131000810_1](https://user-images.githubusercontent.com/98728794/151743245-a18138ab-f892-4712-a878-1932a2127e13.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build
