### ISSUE TITLE
Iberia - Agustin Muñoz Grandes rises from the dead

### ISSUE THREAD

**Issue by ZhukovGaming** [TNODevs/TNO-Bug-Tracker#584]
**Questions**

- Operating System: Win10
- HOI4 Version: 1.11.5 "Barbarossa"
- TNO Version: 1.2.5 Toolbox Theory NSB Patch A
- Any other mods in use: N/A
- Were you using Steam? Yes
- Which expansions do you NOT have? N/A I have all of them

**Longer Description of Issue:**
If Augstin Muñoz Grandes (Iberian General) is retired due to his fascist views, upon his death in 1969, the character will rise from the dead back into active command instead of being content as a skeleton. This is likely an issue with the new Character System introduced with NSB that may have been overlooked by the development team.

**Steps to Reproduce/Cause Issue:**

1. Play Iberia

2. Retire Augstin Muñoz Grandes in order to weaken the Old Guard. Grandes will be retired (removed from command but not removed from the game)

3. Play until 1969. Upon the event where he dies, he is seemingly unretired rather than dying. I assume that if you keep him in command this event works properly.

etc...

**Comment by runelead00** [comment]
Fixed in Dev Build
