### ISSUE TITLE
Goring Germany - Event "The First Promotions" CTD

### ISSUE THREAD

**Issue by AloofGoof** [TNODevs/TNO-Bug-Tracker#588]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.5.5b4f
- TNO Version: 1.2.1a
- Any other mods in use: N/A
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle of the Bosporus

**Longer Description of Issue:**

As soon as you click the even that promotes Steinhoff and other to general in Goering's Germany, the game crashes to desktop. I have 9 volunteers in the various African colonies for the South African War. Zip file of game save attached with event. 

**Steps to Reproduce/Cause Issue:**

1. Get event "First Promotions"

2. Click "Oberst Hans Teusen, step forward."

3. Stare at your desktop background. 

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**
[GER_1965_02_14_12.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7973534/GER_1965_02_14_12.zip)

**Comment by tkgitno** [comment]
Should've been fixed in the latest patch. Do you use the old save?

**Comment by AloofGoof** [comment]
It was the latest patch. I think it was related to the tag switch from Gorings Germany to Greater German Reich. The generals that are given as part of the event are Goring's Germany original tag, so the game CTD.

**Comment by tkgitno** [comment]
Should be fixed for good in dev build this time (for some esoteric reasons Paradox refuses to transfer character nationality thus causing CTD despite being coded correctly)
