### ISSUE TITLE
All Nations - The production units don't work

### ISSUE THREAD

**Issue by BluJay07** [TNODevs/TNO-Bug-Tracker#589]
- Operating System:
- HOI4 Version: 1.11.5
- TNO Version: 1.2.1a
- Were you using Steam? Yes

**Longer Description of Issue:**
Its simple, the production units do not generate any military or civilian factories
**Steps to Reproduce/Cause Issue:**

1. Load Up Game

2. Play any nation

3. No Mils or Civs

**Screenshots:**
![20220131150739_1](https://user-images.githubusercontent.com/84937389/151865285-76dcff5f-0755-496c-88cf-d25fe00bed30.jpg)

**Comment by americanflyer530** [comment]
sometimes it takes a few in game ticks for it to do the math
