### ISSUE TITLE
Huttig-- CTD when Huttig Dies

### ISSUE THREAD

**Issue by bosco8179** [TNODevs/TNO-Bug-Tracker#590]
**Questions**

- Operating System:Win11
- HOI4 Version:1.11.5
- TNO Version:1.21A
- Any other mods in use:Nope
- Were you using Steam? Yes
- Which expansions do you NOT have? No

**Longer Description of Issue:**
Game CTD when Huttig Dies,no matter how much African Devastation he had
**Steps to Reproduce/Cause Issue:**
Don't Make SAW End with OFN Total Victory

Wait until Huttig Dies

**Comment by tkgitno** [comment]
Fixed in Dev Build.
