### ISSUE TITLE
Burgundy - Kalen and Pickardien placement in domestic situation screen

### ISSUE THREAD

**Issue by Ruokos** [TNODevs/TNO-Bug-Tracker#594]
**Questions**

- Operating System: Windows 8
- HOI4 Version: 1.11.5
- TNO Version: 30 January 2022 
- Any other mods in use: Modifier Icons (TNO VERSION)
- Were you using Steam? yES
- Which expansions do you NOT have? I have all expansions

**Longer Description of Issue:**
When playing as Burgundy and looking at the domestic situation screen, the states Kalen and Pickardien are both placed wrong (meaning that Pickardien is on the spot of Kalen in the view, and Kalen is on the spot of Pickardien.) This is a pretty minor bug and not really gamebreaking, but I thought I would mention it :).

**Steps to Reproduce/Cause Issue:**

Just play as Burgundy and look at the domestic view, you will instantly notice it.

**Comment by runelead00** [comment]
Fixed on UB Dev Build
