### ISSUE TITLE
English Transitional Government - Daily change devastation not working

### ISSUE THREAD

**Issue by Crazy9Melon8** [TNODevs/TNO-Bug-Tracker#595]
**Questions**

- Operating System: Win10 64 bit
- HOI4 Version: 1.11.5
- TNO Version: 1.2.1a
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I own all

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

When selecting the following decisions:
''Assign military units to reconstruction efforts''
''Invest into public works''

The daily change in devastation does not lower. The only change is the ''current devastation''.

**Screenshots:**

**Comment by ModdingAccount** [comment]
Fixed in dev build.
