### ISSUE TITLE
USA - Crash when loading up save.

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#597]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Current
- TNO Version: Current
- Any other mods in use: Custom Country Mod, Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**
I load up an autosave of December 1964 at the start of the game. 5 Seconds later, the game crashes me back to desktop.
**Steps to Reproduce/Cause Issue:**

1. Open up the game.

2. Singleplayer, press load up game.

3. 

**Screenshots:**

**Game Saves and Log Files, if possible:**
[hoi4_20220202_190257.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7985906/hoi4_20220202_190257.zip)

**Comment by armymooseg** [comment]
Hey man I’ve had this issue before and I think it’s just that TNO and the submods together is probably too much for HOI4 to handle since the base mod pushes the engine to its limit. I don’t think there’s anything to fix it beyond just trying again.
