### ISSUE TITLE
The name of Guangdong and China

### ISSUE THREAD

**Issue by yangjin000** [TNODevs/TNO-Bug-Tracker#599]
A Recommend: State of Guangdong can be renamed as Kwongtung Kwok(or State of Kwongtung, Romanization of Cantonese Language; Kōtō-koku or State of Kōtō in Japanese Kanji Onyomi). Republic of China can be romanized as Jonghwa Min'gwo(Gwoyeu Romatzyh, set by ROC as the official Chinese Mandarin Romanization writing system since 1920s) or Chunghwa Minkuo(Wade–Giles, was widely used even the former one was published by official government).

By the way, I also suggest all the Chinese names of cities, states, persons could be wrote in one of the two system, th Hanyupinyin you using was created and used by PRC as official after end of the Chinese civil war, ROC has not need to do it if they lives.（Chinese postal romanization is used as offical since from 1910s for some cities name, but this system doesnot include all Chinese cities, only some. So Chinese postal romanization can be prior, than one of the two system for writing the cities or states that can't be sought in Chinese postal romanization） I also know this is a huge project it will be a mess trouble if you follow, but I just mentions it for been more close to the time of 20s in rule of ROC.

**Comment by runelead00** [comment]
We aren't renaming China or Guangdong
