### ISSUE TITLE
USA - Crash on loading certain saves, or when passing certain dates.

### ISSUE THREAD

**Issue by jkopesky** [TNODevs/TNO-Bug-Tracker#600]
**Questions**

- Operating System:
   Windows 11 64-bit

- HOI4 Version:
   1.11.5

- TNO Version:
  v1.2.1a "Toolbox Theory"
  Additional non-numbered updates per changes notes from Workshop on Jan. 29 and Jan. 30.

- Any other mods in use:
   No.

- Were you using Steam?
   Yes.  

- Which expansions do you NOT have?

                  Eastern Front Planes Pack
                  Eastern Front Music Pack
                  Axis Armor Pack
                  Radio Pack
                  Sabaton Soundtrack
                  Sabaton Soundtrack Vol. 2
                  Allied Speeches Music Pack

**Longer Description of Issue:**
   When attempting to load a USA save from 1965 or 1966, or when playing an earlier save of the same game, the game will crash to desktop.
   When loading the save, the game will crash after selecting the save in the main menu, prior to actually displaying the saved map. If you use the "Continue" button in the HOI4 launcher, the game will crash after having loaded the game proper, while attempting to load the save. The save was taken at 7.7.1966.

   For the other crash, it is the same save, but taken on 12.1.1964. The game will crash at approximately 21:00 on 12.7.1964, about a day after the "Election Results are In!" event pops up.

   As stated above, these are both from the same continuous game. 

**Steps to Reproduce/Cause Issue:**
CTD ON LOADING SAVE:
1. Attempt to load 1966 save file
2. CTD

CTD ON DATE
1. Load 1964 save file.
2. Play until about 21:00 12.7.1964
3. CTD

**Screenshots:**

**Game Saves and Log Files, if possible:**
[1964 Logs and Save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7990601/1964.Logs.and.Save.zip)
[1966 Logs and Save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7990602/1966.Logs.and.Save.zip)

**Comment by tkgitno** [comment]
The 1964 one is due to SLP winning the elections. Check [here](https://github.com/TNODevs/TNO-Bug-Tracker/issues/578) for the temporaily fix before the next patch is released. 
For the 1966 one can you try to save the game at some point before crashing? Corrupted saves can't be analysed sadly.

**Comment by mrnobo1dy** [comment]
I'm having the same issue, I was completing the great society focus tree for USA. It seems 3 monthly cloud saves were corrupted and crashes every time after fully loaded. I loaded a much earlier manual save (8 in-game months before the point of crash) to circumvent the crash.

**Comment by jkopesky** [comment]
The 1964 crash was resolved using the SLP fix. As corrupted saves cannot be fixed, it doesn't look like there will be a solution for the 1966 save. As such, I'm closing the issue.
