### ISSUE TITLE
Every Country - Crashes shortly after loading country

### ISSUE THREAD

**Issue by nobelo81** [TNODevs/TNO-Bug-Tracker#602]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.5 (or current as of 2/3/2022 if different)
- TNO Version: 1.2.1a (or current as of 2/3/2022 if different)
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? Music and unit models

**Longer Description of Issue:**
The game crashes shortly after loading the introduction message for the chosen country, even when using opengl
**Steps to Reproduce/Cause Issue:**

1. Set TNO as the only mod in playset

2. Launch the game

3. Load in as any country

**Screenshots:**

**Game Saves and Log Files, if possible:**
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/7999902/error.log)

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed and cause currently unknown
