### ISSUE TITLE
USA - Chose Rabemananjara, end up with no portrait.

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#603]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Current
- TNO Version: Current
- Any other mods in use: Radio TNO, Custom Country Mod (new)
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**
After choosing Jacques Rabemananjara as president of OFN Madagascar, and after clicking the event of Rabemananjara talking on the phone, I ended up having a no portrait person named Lothar Schmidt as leader of Madagascar.
**Steps to Reproduce/Cause Issue:**

1. Win the Madagassisch Civil War as USA.

2. Choose Rabemananjara as the successor.

3. Click the event.

4. Ended up not having Rabemananjara.

**Screenshots:**
![7e5c3d8f722132d6683a807482f90661](https://user-images.githubusercontent.com/96382658/152560741-f33515c5-81d3-42d7-b5f1-a154f8a7e668.png)

**Comment by YanSGod** [comment]
I also encountered this bug

**Comment by tkgitno** [comment]
Fixed in Dev Build

**Comment by YanSGod** [comment]
> Fixed in Dev Build

This will also happen if Algeria is reunified peacefully
