### ISSUE TITLE
Chita (CHT) - Mikhail II's AutDem Trait not Removed

### ISSUE THREAD

**Issue by Honokophile** [TNODevs/TNO-Bug-Tracker#604]
**Questions**

- Operating System:
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: None
- Were you using Steam?
 Yes.
- Which expansions do you NOT have?
 I have all expansions.
**Longer Description of Issue:**
 Mikhail II's trait "The Reluctant Tsar" (code: "the_reluctant_tsar") of his Authoritarian Democracy role is not removed after event "A Quiet Dinner"(code: "CHT_regional.7" & "CHT_regional.11").

**Comment by runelead00** [comment]
Fixed on UB
