### ISSUE TITLE
HMMLR - Crash to Desktop after winning the election as SLP

### ISSUE THREAD

**Issue by johnt28** [TNODevs/TNO-Bug-Tracker#605]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.5
- TNO Version: 1.2.1.a
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I don't have the radio ones,

**Longer Description of Issue:**
The game is crashing, probably, after SLP victory playing as England after the Civil War. The crash happens a while after selecting the accepting option in the "The Decision of a Free People" event, not inmediatly.

**Steps to Reproduce/Cause Issue:**

1. Won the Civil War as HMMLR

2. Won the elections as SLP.

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**
[hoi4_20220204_140946.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8006095/hoi4_20220204_140946.zip)

**Comment by johnt28** [comment]
I saw there was already a report of this crash, but I was unnable to fix it even with the instructions, so I didn't know if this was another crash or something like that.

**Comment by runelead00** [comment]
Crash should be fixed as of Current Release
