### ISSUE TITLE
Japan - Fukuda can't become prime minister.

### ISSUE THREAD

**Issue by Tarepa** [TNODevs/TNO-Bug-Tracker#608]
**Questions**
Even if Fukuda was guaranteed to become Prime Minister and had the support of the Diet and the House of Peers, he would not become Prime Minister after completing the national focus "Retirement Of The Grand Old Man".

- Operating System: Windows 11 Pro 21H2 (22000.469)
- HOI4 Version: 1.11.5.5b4f
- TNO Version: 1.2.1a
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have?  I should have them all.

**Longer Description of Issue:**
Even if you get the national focus "Fukuda's Ascent", and the Tecnocrats faction is the largest faction in the Diet, and the Kaya government has more than 50% support in the House of Peers, completing the "Retirement Of The Grand Old Man" will trigger the event "Purgatory", indicating that Fukuda could not become the Prime Minister.

**Steps to Reproduce/Cause Issue:**

1. Complete national focus "Fukuda's Ascent". 

2. Became the largest faction in Diet and gained over 50% support in the House of Peers.

3. Complete national focus "Retirement Of The Grand Old Man". 

**Screenshots:**
![20220206113851_1](https://user-images.githubusercontent.com/26321161/152665931-246bf98c-3318-4ebb-83a9-e203409e4266.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build
