### ISSUE TITLE
YUN - AI will never  attack Tibet

### ISSUE THREAD

**Issue by Tarepa** [TNODevs/TNO-Bug-Tracker#609]
**Questions**
The AI-controlled Yunnan will never choose to attack Tibet during the Great Asian War, no matter how dominant it is.

- Operating System: Windows 11 Pro 21H2 (22000.469)
- HOI4 Version: 1.11.5.5b4f
- TNO Version: 1.2.1a
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have?  I should have them all.

**Longer Description of Issue:**
AI's Yunnan is scripted to choose a decision to attack Tibet if Manchukuo, Mengjiang or Guangdong surrenders and does not exist, but this will never be done because there is a mistake in this script.

**Steps to Reproduce/Cause Issue:**

1. The Great Asian War breaks out.

2. Xinjiang Clique, Ma Clique, and Xikang Clique enter the war as allies of Yunnan.

3. Manchukuo, Mengjiang, or Guangdong surrenders to Yunnan during the war and is annexed.

**Screenshots:**
![20220206123322_1](https://user-images.githubusercontent.com/26321161/152666834-72e67390-2832-4895-9991-f50d38072da3.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build
