### ISSUE TITLE
ILG - The leader is not correct

### ISSUE THREAD

**Issue by YanSGod** [TNODevs/TNO-Bug-Tracker#611]
**Questions**

- Operating System:Windows 10 x86_64
- HOI4 Version:1.11.5
- TNO Version:1.2.1a
- Any other mods in use:no
- Were you using Steam?yes
- Which expansions do you NOT have?Have all

**Longer Description of Issue:**
When Algeria is reunited peacefully, Tribal Rulaers will be a random leader with no picture
Event ILG.8
**Steps to Reproduce/Cause Issue:**

1.The Iberian Union chose peaceful means

2.Event ILg.8 is triggered

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/99068464/152669845-0c641250-8e08-4795-a4ff-c8785c05310b.png)
PS：To make it easier to demonstrate, I fired the event directly

**Comment by runelead00** [comment]
Fixed in Dev Build
