### ISSUE TITLE
USA - Oil Crisis Focus Issue

### ISSUE THREAD

**Issue by mrnobo1dy** [TNODevs/TNO-Bug-Tracker#612]
- Operating System: Windows 10
- HOI4 Version: v1.11.5.5b4f
- TNO Version: v1.2.1a
- Any other mods in use: Chinese localization mod (The New Order Cn.Ver); TNO nuclear war gamerule
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
In the oil Crisis, playing as USA (LBJ second term), in the support for Saudi Arabia focus tree, for focus: operation Desert Storm, instead of sending volunteer to Saudi Arabia, it sends volunteer to Italy, preventing players from assisting Saudi Arabia. 
**Steps to Reproduce/Cause Issue:**

1. Play as USA and and have LBJ as president for 1968 election (at least for me)

2. wait till oil crisis and focus to support Saudi come out

3. Progress through the direct intervention path

**Comment by runelead00** [comment]
Fixed on UB
