### ISSUE TITLE
USA - Cannot refill officer corps advisor after South African War

### ISSUE THREAD

**Issue by mrnobo1dy** [TNODevs/TNO-Bug-Tracker#613]
Operating System: Windows 10
HOI4 Version: v1.11.5.5b4f
TNO Version: v1.2.1a
Any other mods in use: Chinese localization mod (The New Order Cn.Ver); TNO nuclear war gamerule
Were you using Steam? Yes
Which expansions do you NOT have? None

**Longer Description of Issue:**
Playing as USA, after the victory of South African War, two commanders and one advisor from the USA officer corps tab disappear, presumably to head the three OFN collaboration government. During this time period, I cannot fill the vacancies in the officer corps. After the OFN collaboration governments ended, Abrams will return as an advisor, but two commander slots are still vacant and I cannot select new generals to fill the spots. 

**Steps to Reproduce/Cause Issue:**

1. Playing as USA

2. Total Victory in SAW

**Screenshots:**
![TNO bug](https://user-images.githubusercontent.com/99128314/152685071-90670588-98c3-4224-9b80-13de78c94e21.PNG)

**Comment by Scarsoftime** [comment]
Manual assignment of officer corps are disabled in TNO.
