### ISSUE TITLE
Angola - Lavelle stays leader after peaceful decolonization

### ISSUE THREAD

**Issue by kolebaby12** [TNODevs/TNO-Bug-Tracker#614]
**Questions**

- Operating System: Windows 10
- HOI4 Version: v1.11.5.5b4f
- TNO Version: v1.2.1a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
When playing as the USA, i successfully & peacefully decolonized all 3 of the mandates. East Africa, The Congo, & Angola. However, when Angola decolonized and the tag was released, the name and flag changed(& the econ type and subid) but the previous leader - Lavelle, a US general - remained unchanged. This also happened to make it so that Lavelle didn't return to my army HQ, i think.
**Steps to Reproduce/Cause Issue:**

1. Establish the mandates

2. Peacefully decolonize Angola

etc...

**Screenshots:**
![20220206154711_1](https://user-images.githubusercontent.com/94831964/152687913-9399a1c2-b7d2-446e-a126-35c2143d73b6.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build
