### ISSUE TITLE
GER - Heydrich's Germany, when in the game against Himmler, does not do anything

### ISSUE THREAD

**Issue by CardinalEugen** [TNODevs/TNO-Bug-Tracker#617]
**Questions**

- Operating System:
- HOI4 Version: up to date
- TNO Version: up to date
- Any other mods in use: none
- Were you using Steam? yes
- Which expansions do you NOT have? I have all expansions

**Longer Description of Issue:**
I play as Siberian Black Army. For fun, I deletedall units Bormann, Goring and Speer to let Heydrich win. When Heydrich is in game against Himmler, I only see Himmler's faction getting stronger and stronger. Heydrich's anti-Himmler Coalition did not expand even once. And my game suddenly ended with Thermonuclear war when Germany (Heydrich) attacked Poland, which triggered the nukes. 
**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**
Unfortunately I did not screenshot.....

**Comment by tkgitno** [comment]
Intended when it's AI Heydrich
