### ISSUE TITLE
Speer Germany - Reichsland Baltikum does not join the Pakt

### ISSUE THREAD

**Issue by Cwloftin** [TNODevs/TNO-Bug-Tracker#618]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Up to date
- TNO Version: Up to date
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for the Bosporus

**Longer Description of Issue:** In Speer phase 2 when creating the Reichslands, you split Ostland between Reichsland Baltikum and Reichsland Weisruthenien, but only Reichsland Weisruthenien is a member of the Pakt.

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Dev Build
