### ISSUE TITLE
IBR--Caudillo Superslam is broken (IBR.4023)

### ISSUE THREAD

**Issue by ltallen** [TNODevs/TNO-Bug-Tracker#619]
**Questions**

- Operating System: Ubuntu 21.10
- HOI4 Version: 1.11.5
- TNO Version: 1.2.1a
- Any other mods in use: Toolpakt
- Were you using Steam? Yes
- Which expansions do you NOT have? NSB, Bosporus, content packs

**Longer Description of Issue:**
When the focus on the diarchy debate is taken (during the consitutional reform tree after the Battle of Barcelona), there is an event chain where Salazar and Franco get into a public brawl. If you have the legislative council, and choose not to break up the fight rather than call the Guardia Civil, then nothing happens. I looked through the code and discovered why (see screenshot). As you can see, the second option is probably intended to lead to one of two events, depending on what type of council one has. Instead, it gives two events if you have an advisory council, and nothing if you have a legislative one.

**Screenshots:**
![brawlbug](https://user-images.githubusercontent.com/38485757/152908266-f031649b-00bf-468a-9163-0c21d3ae8bf7.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
