### ISSUE TITLE
Missing Loc and GFX for NSB Armor tech tree

### ISSUE THREAD

**Issue by trainvoi** [TNODevs/TNO-Bug-Tracker#621]
- Operating System: Windows 10
- HOI4 Version: 1.11.5
- TNO Version: 1.2.1a
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

- Flame Chassis (IFV and MBT) lacks any localization and only uses default IFV/MBT GFX in their equipment designers instead of Russian  IFV for Russian warlords or German IFV.
- Towed Anti-Air in Production menu use default GFX instead of Russian GFX if I play as a Russian warlord
- and a lot of missing loc in NSB Armor tree

**Comment by runelead00** [comment]
Towed Anti-Air has been fixed for UB
