### ISSUE TITLE
Gotenland - Generic leader portrait

### ISSUE THREAD

**Issue by kolebaby12** [TNODevs/TNO-Bug-Tracker#623]
**Questions**

- Operating System: Windows 10
- HOI4 Version: v1.11.5.5b4f
- TNO Version: v1.2.1a
- Any other mods in use: none
- Were you using Steam? Yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**
In Speer's megacorp tree, if he does the "a firm hand"(or something along those lines) focus it divides the pakt into several new mitsreiters. However, when 'Gotenland' was released it came out with a default leader portrait instead of whoever was supposed to be there. This default leader issue happens with several other authdem leaders, but i wasn't playing as speer at the time. 
**Steps to Reproduce/Cause Issue:**

1. Play speer

2. In the megacorp dismantlement tree, finish the reformist "a firm guide" focus

etc...

**Screenshots:**
![20220207032945_1](https://user-images.githubusercontent.com/94831964/152991461-3c9b0098-239e-4834-b3ba-e07ef744b618.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
