### ISSUE TITLE
Italy - Ciano in DemItaly

### ISSUE THREAD

**Issue by kolebaby12** [TNODevs/TNO-Bug-Tracker#624]
**Questions**

- Operating System: Windows 10
- HOI4 Version: v1.11.5.5b4f
- TNO Version: v1.2.1a
- Any other mods in use: none
- Were you using Steam? Yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**
Italy went down the democratic reformist path, making the king HoS briefly before electing the authdem pseudo-fascists. However, when the election event fired, i checked their leader and it turned out that they elected Ciano to take the reigns again, staying even after they turned fully fascist. I can only assume this is because the game didn't properly update the leader of the authdem party and it defaulted to what was there already, but it is a very amusing glitch.
**Steps to Reproduce/Cause Issue:**

1. Make Italy democratic

2. Elect the authdems

etc...

**Screenshots:**
![20220207011841_1](https://user-images.githubusercontent.com/94831964/152992194-8a7f44db-fdaa-4406-bce5-6420538ad3a4.jpg)

**Comment by tkgitno** [comment]
Fixed in Dev Build

**Comment by jakhlaghi** [comment]
Would you be willing to say where the issue was so I could fix it in my game?
