### ISSUE TITLE
Omsk - Missing Batov Insurgency and Regional Development Decisions for AI

### ISSUE THREAD

**Issue by CancerousLava** [TNODevs/TNO-Bug-Tracker#625]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.5
- TNO Version: 1.2.1a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? All

**Longer Description of Issue:**
When AI Omsk unifies West Siberia, the Batov Insurgency and Regional Development decisions do not appear, even after it has reached its regional focus tree. Insurgency decisions show up after using console to fire the event (omskbatov.1); based on this the game may not be registering Omsk as in the regional stage and hence generating neither the insurgency event nor the regional dev decisions. 

This bug is being reported as it leads to Omsk never collapsing when AI-controlled.

Issue occurred both before and after the NSB patch. Did not occur when I played Omsk myself prior to the NSB patch. 

**Steps to Reproduce/Cause Issue:**

1. Have AI Omsk unify WestSib

2. Wait until after they have reached the regional focus tree

3. Tag switch to Omsk using console

**Screenshots:**
![20220209000451_1](https://user-images.githubusercontent.com/99274223/153027086-fc428d75-5c1d-4b81-a472-c3fc5daaf325.jpg)

Insurgency decisions are there because I loaded them by firing the event manually, but as seen the regional dev decisions are missing.

![20220209000507_1](https://user-images.githubusercontent.com/99274223/153027236-2031b870-e749-4368-8035-0b99498a59a4.jpg)

They are well into their regional tree as seen.

**Comment by tkgitno** [comment]
Intended cause paradox AI just can't learn how to use GUIs properly

**Comment by masterbobli** [comment]
I actually do need to teach AI batov how to manage (or mismanage) the insurgency
