### ISSUE TITLE
Mengjiang - Demchugdongrub has the 'naval bomber' trait

### ISSUE THREAD

**Issue by Chewy598** [TNODevs/TNO-Bug-Tracker#627]
**Questions**

- Operating System: Windoes 10
- HOI4 Version: 1.11.5
- TNO Version: v1.2.1a
- Any other mods in use: No
- Were you using Steam? No
- Which expansions do you NOT have? None, have all

**Longer Description of Issue:**
Demchugdongrub seems to have the naval bomber trait that is also present in the base game.

**Screenshots:**
![Hearts of Iron IV (DirectX 9) 10_02_2022 8_45_44 PM](https://user-images.githubusercontent.com/59920852/153381652-b6f825f7-dcab-451d-a991-9ec69df5a9af.png)

**Comment by runelead00** [comment]
Removed in UB
