### ISSUE TITLE
Game crash when loading bar is full

### ISSUE THREAD

**Issue by Johnnythepro1985** [TNODevs/TNO-Bug-Tracker#628]
**Questions**

- Operating System:
- HOI4 Version: The latest
- TNO Version: The latest
- Any other mods in use: First try: Yes ; Second try: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I do not have any DLCs, I only have Poland United and Ready

**Longer Description of Issue:**
Well, I was starting TNO it showed me the loading screen and when the loading bar was full it made me crash to desktop for no reason.
**Steps to Reproduce/Cause Issue:**

1. Start the launcher.

2. Enable TNO or with compatible mods with

3. Wait loading screen to be full

4. Once loading bar full it crashes
**Screenshots:**
I don't have screenshots just a video https://www.youtube.com/watch?v=ZdUoKuNIdf0

**Game Saves and Log Files, if possible:**
Sorry I don't have any log files or saves

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed and cause currently unknown
