### ISSUE TITLE
Japan-State GDP loc error

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#629]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
The picture says it all.
![Screenshot (2450)](https://user-images.githubusercontent.com/98137316/153538296-6712bcb6-420d-4b6a-b701-b51fcb9bb7ca.png)

**Comment by runelead00** [comment]
Issue with how Paradox loads stuff, can't do anything about, will fix on its own after a bit
