### ISSUE TITLE
Tajikistan-leader glitch

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#630]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW Shukshin
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
Not knowledgeable enough about Central Asia to say what precisely is wrong here other than the missing portrait, but something about this just looks off.
**Steps to Reproduce/Cause Issue:**
I have no idea what triggered this.
**Screenshots:**
![Screenshot (2451)](https://user-images.githubusercontent.com/98137316/153538458-fa893211-1084-4ffe-9777-2bc8feb0e865.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
