### ISSUE TITLE
West African Union/Cameroon - Wonky Borders

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#631]
**Questions**

- Operating System: Windows 11
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW Shukshin
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
I'm 99% certain that this isn't how the post-victory divvying up of West Africa is supposed to go for Cameroon.
**Screenshots:**
![Screenshot (2459)](https://user-images.githubusercontent.com/98137316/153538586-9cb405d2-107f-4bc2-8309-30d2be1e7d0e.png)

**Comment by runelead00** [comment]
Fixed for UB
