### ISSUE TITLE
Takagi's Japan - Multiple, seemingly random events for other countries

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#632]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current 
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
During the prelude to the Oil Crisis I got multiple events I shouldn't have. By the time I got offered an invite to President Glenn's nuclear disarmament conference despite having just given Hawaii back to President Bennett the previous year, I gave up the game as glitched beyond ignoring and deleted the save file. Enclosed are all the events I had up until that point. Note that the Norway one actually did change my pie chart to give me 3% SocDem, but the next month that was removed and redistributed to the other ideologies.

**Screenshots:**
![Screenshot (2468)](https://user-images.githubusercontent.com/98137316/153538932-864131ab-2615-4b78-a471-b88b17c4dfd3.png)
![Screenshot (2469)](https://user-images.githubusercontent.com/98137316/153538953-cd7d9dca-7ba3-4b03-ab84-846bf33eb74f.png)
![Screenshot (2470)](https://user-images.githubusercontent.com/98137316/153538967-36e4ae95-e8de-4e9a-a20b-e16a7f8898de.png)
![Screenshot (2512)](https://user-images.githubusercontent.com/98137316/153539007-175cb85f-53a5-4629-8a99-5a85bf034a94.png)

**Comment by runelead00** [comment]
Can't Reproduce and has not show up in testing, can only assume that save file become corrupt at some point which lead to random events triggering
