### ISSUE TITLE
China-Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#634]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"Agricultural equipment" is singular, so the end of the sentence should be "use it" instead of "use them"
![Screenshot (2475)](https://user-images.githubusercontent.com/98137316/153539310-bc6d7746-2919-462c-8638-893f0aa667f7.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
