### ISSUE TITLE
China-typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#635]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: no

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"we got" should be "we've got"
![Screenshot (2477)](https://user-images.githubusercontent.com/98137316/153539376-b11bfae9-1ec5-4763-8aeb-e4c31af4df8e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
