### ISSUE TITLE
Magadan-Random event loc

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#636]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
I've played Magadan multiple times and have never seen this happen before. This didn't do anything that I could notice though.
![Screenshot (2490)](https://user-images.githubusercontent.com/98137316/153539557-7fa10d18-4518-4c04-b860-fa80197a6c54.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
