### ISSUE TITLE
WerBell-Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#637]
**Questions**

- HOI4 Version: current
- TNO Version: current 
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"locals of this lace" should be "locals of this place"
![Screenshot (2499)](https://user-images.githubusercontent.com/98137316/153539631-a853f41a-0d97-4730-a961-dccd6217cf65.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
