### ISSUE TITLE
WerBell-Poor grammar

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#638]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
I lack the vocabulary to explain precisely how, but this focus is very rambly, and the second paragraph in particular is a rather egregious run-on sentence. It could do with a touch-up if y'all get around to that sort of thing.
![Screenshot (2500)](https://user-images.githubusercontent.com/98137316/153539855-3d2f829a-7b5f-4a30-bf39-24116b92e2fb.png)

**Comment by runelead00** [comment]
Improved in Dev Build
