### ISSUE TITLE
WerBell-missing portraits

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#639]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
Upon completing the focus to work with the NKVD, I received the two ex-Yagoda generals mentioned by the focus, but without their portraits.
**Screenshots:**
![Screenshot (2502)](https://user-images.githubusercontent.com/98137316/153539962-8ed3604e-90ff-48fa-b874-379026ca1471.png)
![Screenshot (2503)](https://user-images.githubusercontent.com/98137316/153539977-9d41963b-d371-4095-847b-d772e3f9f15f.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
