### ISSUE TITLE
Brazil- Post coup elections are broken

### ISSUE THREAD

**Issue by tomas45678** [TNODevs/TNO-Bug-Tracker#64]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version:1.1.2a
- Any other mods in use: West Russian War 2, Kaiserreich music mod, red world music mod, Toolpack updated (august 2021)
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
After the coup that happens after the 100 days crisis fails the ai did the focus tree and choose to call new elections, yet nothing happened and when i tag switched to brazil to see if the AI was being a bit special, they has 
**Steps to Reproduce/Cause Issue:**

1. play brazil

2. do the coup

3. choose to call elections at the end of the tree
![imagen](https://user-images.githubusercontent.com/67890183/129119692-45ba8400-56e7-4514-a25e-a76c4de18f8d.png)
![imagen](https://user-images.githubusercontent.com/67890183/129119706-9ca66884-d352-4f76-9c83-fa8616d71787.png)
![imagen](https://user-images.githubusercontent.com/67890183/129119724-e33d7ba4-29f0-4fbd-a103-48cc6e76ad83.png)

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Current Release
