### ISSUE TITLE
Ural Military District - Unknown peace conference causes crash to desktop

### ISSUE THREAD

**Issue by a-latin-twat** [TNODevs/TNO-Bug-Tracker#641]
**Questions**

- Operating System: Windows 11
- HOI4 Version: 1.11.5.5b4f (fab9)
- TNO Version:  1.2.1a
- Any other mods in use:  Radio TNO: Music of the New Order
- Were you using Steam?  Yes
- Which expansions do you NOT have?  I don't have any of them

**Longer Description of Issue:**
I was playing as the Ural Military District, but a peace conference of a conflict (I don't know which one specifically, I THINK in the congo) crashes the game, and even the paradox pop-up asking to report the bug doesn't appear, the game just closes. Neither resetting the computer nor the game works, and it keeps crashing after the peace conference. I don't know if this is specific to the Ural military district or if it is a general bug.
**Steps to Reproduce/Cause Issue:**

1. Cause Issue: unidentified peace conference

2.

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**

**Comment by runelead00** [comment]
Not much we can do to solve the issue without the specific peace deal or files, closing since we are unlikely to get that information
