### ISSUE TITLE
Republic of Madagascar- Leader name and portrait are wrong

### ISSUE THREAD

**Issue by a-latin-twat** [TNODevs/TNO-Bug-Tracker#642]
**Questions**

- Operating System: windows 11
- HOI4 Version: 1.11.6
- TNO Version: 1.2.1a
- Any other mods in use: radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? Dont have any of them

**Longer Description of Issue:**
When you win the Malagasy civil war, you get the option to install the a native leader called Jacque something, when i picked that option I got the corresponding event, but neither his portrait and name were generic

**Steps to Reproduce/Cause Issue:**

1. Just win the Malagasy civil war as the USA and install the native leader

2.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/99560835/154121333-bc6d86e9-4924-4079-bd95-ebc70afd1d8b.png)

**Comment by runelead00** [comment]
Fixed in Current Release
