### ISSUE TITLE
Karelian Economy Broken

### ISSUE THREAD

**Issue by ChineseMissileBoat** [TNODevs/TNO-Bug-Tracker#645]
In the Karelian Economy both the Income and the Expenditures are 0
![dfgfdgdgddf](https://user-images.githubusercontent.com/91438732/154502639-4daacfd8-a0e1-4c87-b1cb-0ca2022441d5.JPG)

**Comment by runelead00** [comment]
Given how some Onega's economy, its expenses and revenues are often too small to calculate due to limitations with the system, can't really fix it
