### ISSUE TITLE
Kingdom of England - Missing Jellicoe portrait when elected

### ISSUE THREAD

**Issue by ftlb11** [TNODevs/TNO-Bug-Tracker#646]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.7 Barbarossa (no beta)
- TNO Version: 1.2.1A Toolbox Theory
- Any other mods in use: N/A
- Were you using Steam? Yes
- Which expansions do you NOT have? N/A

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Current Release
