### ISSUE TITLE
Tyumen - Khruschev coups Lazar, but doesn't take power. 

### ISSUE THREAD

**Issue by joshricatti** [TNODevs/TNO-Bug-Tracker#648]
**Questions**

- Operating System: Windows 11
- HOI4 Version: 1.11.7
- TNO Version: idk most up-to-date version
- Any other mods in use: **2WRW, Radio TNO, State Transfer Tool**
- Were you using Steam? **yes**
- Which expansions do you NOT have? **none**

**Longer Description of Issue:**
Khruschev couped Lazar in my game, but Lazar is still in power. He has Khruschev's cabinet, but he never retired even though the event said he was going to retire.

**Steps to Reproduce/Cause Issue:**

1. Play Tyumen

2. Follow the path for getting Khruschev

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/99983601/154720151-2711eb37-a3e3-427a-a067-8d77cd2ad3ff.png)

**Comment by Scarsoftime** [comment]
Fixed
