### ISSUE TITLE
Tannu Tuva Loses Its Name on Change in Ownership

### ISSUE THREAD

**Issue by runelead00** [TNODevs/TNO-Bug-Tracker#65]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.1.2a
- Any other mods in use: Radio TNO
- Were you using Steam? Yes
- Which expansions do you NOT have?  None

**Longer Description of Issue:**
Tannu Tuva loses its name to become  STATE_329_nor after it is conquered from the PRC
Edit: Appears to only affect non socialist nations, it stayed Tannu Tuva when SBA and SWF controlled it, and gave the missing loc name for Novosib.

**Steps to Reproduce/Cause Issue:**

1. Have PRC be conquered by nonsocialists and Tannu Tuva will lose its name

**Screenshots:**
![20210811170922_1](https://user-images.githubusercontent.com/74165171/129150069-9faa6248-c08c-4285-830a-2b04ae7a5232.jpg)

**Comment by SegaSaturnDude-05** [comment]
I'm having the exact same issue, only it also changes the name of the Victory Points, as well.

**Comment by tkgitno** [comment]
Fixed in Dev Build.
