### ISSUE TITLE
Congo Civil War - American generals in army

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#651]
**Questions**

- Operating System: windows 10
- HOI4 Version: current 
- TNO Version: current
- Any other mods in use: 2WRW
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
I tdebug'd to the various Congo factions to delete their armies, and found the DRC with Westmoreland as a field marshal.
**Screenshots:**
![Screenshot (2458)](https://user-images.githubusercontent.com/98137316/154745466-3f924006-e049-4052-bd22-11308eee18b9.png)

**Comment by runelead00** [comment]
Should be fixed in current release
