### ISSUE TITLE
Novosibirsk - Not properly showing equipment upgrades

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#652]
**Questions**

- Operating System: windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
I created a template for a tank division, built a few, then researched improved mbts. The manufacturing queue didn't display me as having any to replace via upgrades, despite my stockpile consisting solely of basic mbts and my units having nothing but that for equipment.
**Steps to Reproduce/Cause Issue:**
Unknown. This has happened in at least one other Russian unifier, but I can't remember whihc.
**Screenshots:**
![Screenshot (2483)](https://user-images.githubusercontent.com/98137316/154745803-008c7f8e-0768-47d3-a751-35d3dab666e9.png)
![Screenshot (2484)](https://user-images.githubusercontent.com/98137316/154745842-80e784cc-3973-48a1-a3bb-efea3e253ed9.png)
![Screenshot (2485)](https://user-images.githubusercontent.com/98137316/154745888-70d949b5-e3c3-41d8-a47d-bbc00141a9ea.png)

**Comment by runelead00** [comment]
Working as of current Dev Build
