### ISSUE TITLE
Takagi - Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#653]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
The word "lot" is unnecessarily capitalized.
- [ ] 1. 
![Screenshot (2514)](https://user-images.githubusercontent.com/98137316/154746225-889f4b9e-d3e5-40cd-9e94-69d321de50f0.png)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
