### ISSUE TITLE
Brazil - Castelo Branco doesn't become president

### ISSUE THREAD

**Issue by miki614** [TNODevs/TNO-Bug-Tracker#654]
**Questions**

- Operating System:win10
- HOI4 Version: 1.11.7
- TNO Version: 1.2.1a
- Any other mods in use: no
- Were you using Steam?  yes
- Which expansions do you NOT have? everyone

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1. Get military dictatorship in power in Brazil.

2. Do a focus inaugurating Castelo Branco as a president
3.  Mazzilli still there

etc...

**Screenshots:**
![Obraz1](https://user-images.githubusercontent.com/99992078/154746257-4dfeab73-423d-408e-8d02-52ed24174e8f.png)
![Obraz2](https://user-images.githubusercontent.com/99992078/154746269-0e598740-0908-4f06-9b0d-5260cb709383.png)

**Comment by runelead00** [comment]
Fixed on UB
