### ISSUE TITLE
Cameroon/West African Union - Isolated/unintended province post-victory

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#655]
**Questions**

- Operating System: windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW
- Were you using Steam? yes
- Which expansions do you NOT have? all

**Longer Description of Issue:**
I've reported this before, but as an isolated incident. I've now seen it happen three separate times as Japan, where I've always thrown all my pp into the war until the Pan-Africanists win. This appears to happen every time Cameroon and its allies win, regardless of which country (temporarily) conquers which other country.

**Screenshots:**
![Screenshot (2515)](https://user-images.githubusercontent.com/98137316/154746480-b065e71c-1c2e-42de-95ec-1dfe2fd420a9.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
