### ISSUE TITLE
England - Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#657]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: none

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
City of Birmingham description: "it should now be surprising" should read "it should _not_ be surprising"
- [x] 1. 
![Screenshot (2521)](https://user-images.githubusercontent.com/98137316/154747170-0365d989-2f89-4889-b021-31b8cacdd245.png)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
