### ISSUE TITLE
Collaborationist England- Halder still described as occupying Cornwall

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#658]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Despite the old Cornwall garrison being reduced to Devonport, with Cornwall simply being demilitarized(until the civil war breaks out, that is) several Collaborationist focuses still describe the pre-Toolbox Theory version where Halder owned the entire province.
- [x] 1. 
![Screenshot (2522)](https://user-images.githubusercontent.com/98137316/154747460-e668adfc-8d03-4f7c-adce-fbf33dad4a8a.png)
- [x] 2. 
![Screenshot (2523)](https://user-images.githubusercontent.com/98137316/154747510-f5bdbe2d-2d51-4d4c-8fb3-25b49b4a7220.png)

**Comment by Stormeagle449** [comment]
Fixed in Dev Build
