### ISSUE TITLE
Collab England - Confusing focus effect

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#659]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"Northern England" is used as a province name when no such province exists.
- [ ] 1. 
![Screenshot (2524)](https://user-images.githubusercontent.com/98137316/154747687-984784f3-e03b-469c-8f43-5f097b50d2f0.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
