### ISSUE TITLE
Wales annexation event - Poor grammar

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#660]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
The whole event is filled with run-on and disjointed sentences. Additionally, "they were free off" should be "they were free of".
- [x] 1. 
![Screenshot (2531)](https://user-images.githubusercontent.com/98137316/154747996-30278ebb-3999-428c-81da-a827d212b5ba.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
