### ISSUE TITLE
Kaya Japan - Missing loc in focus

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#662]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2540)](https://user-images.githubusercontent.com/98137316/154759183-2bd5f89d-4ede-418a-b6ec-b114cd6d53e6.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
