### ISSUE TITLE
Kaya - Grammatical error

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#663]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"It is of the paramount interest" should be "it is of paramount interest"
![Screenshot (2541)](https://user-images.githubusercontent.com/98137316/154759326-f852c408-2e85-44a1-8a93-3e7d9b77b591.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
