### ISSUE TITLE
Japan - Glitched Fusan city description

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#664]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2542)](https://user-images.githubusercontent.com/98137316/154759403-912e1930-b854-452d-b3a4-769ea59a1701.png)

**Comment by Scarsoftime** [comment]
Go to a city loc with a long text so that it spawns the scrollbar, scroll up, and then go back. HOI4 vanilla bug, can't do anything about it.
