### ISSUE TITLE
icon of agrarian spartanism does not appear.

### ISSUE THREAD

**Issue by mapu1283** [TNODevs/TNO-Bug-Tracker#665]
**Questions**

- Operating System:Windows 10
- HOI4 Version:1.11.7
- TNO Version:1.2.1
- Any other mods in use:no
- Were you using Steam?yes
- Which expansions do you NOT have? No step back

**Longer Description of Issue:**
An icon of agarian spartanism is displayed as an icon of esoteric Nazism.

Because in the 394360/2438003901/interface/countrypoliticsview.gfx , agrarian is incorrectly written as 'agricultural'.

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**
![1](https://user-images.githubusercontent.com/95910611/154781176-4f0d6b2e-6242-4a4d-b914-2a9b5769c5bb.jpg)

![gfx](https://user-images.githubusercontent.com/95910611/154781125-3c64a483-399e-4273-aab9-e0a9b229d6df.png)
-46cf-b7a4-aa175616997a.jpg)
![20220215_222028](https://user-images.githubusercontent.com/95910611/154781128-ba7b3213-6f8a-4c08-a49d-fbd3f4d01164.png)

**Comment by Scarsoftime** [comment]
Fixed
