### ISSUE TITLE
TNO crashing

### ISSUE THREAD

**Issue by Destroyer132** [TNODevs/TNO-Bug-Tracker#666]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.7
- TNO Version: 1.2.1a
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all of them

**Longer Description of Issue:**
When I select a country and it loads into the game it crashes and Paradox crash reporter appears

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**
![Capture](https://user-images.githubusercontent.com/100041904/154814182-0b9821a4-69a7-4317-9865-dd8db7a97688.PNG)

**Game Saves and Log Files, if possible:**
[error - Copy.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8102780/error.-.Copy.log)

**Comment by Yockieite** [comment]
dude this is the same issue i'm having

**Comment by Kommissar396** [comment]
Im also having this bug

**Comment by HOI4Gamer** [comment]
I have this bug too

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed and cause currently unknown
