### ISSUE TITLE
Komi_Communist - Ideology subtype couldn‘t change to ultravisionary_socialism

### ISSUE THREAD

**Issue by Speerofficial** [TNODevs/TNO-Bug-Tracker#669]
**Questions**
When playing zhdanov, I found that the ideology subtype keep on being Revolutionary front. So I read the file "event/komi_communist". There are codes about changing the ideology subtype to ultravisionary_socialism. So what's wrong? Why it didn't changed?

- Operating System:Windows 11
- HOI4 Version:V1.11.7.64f3(98bf)
- TNO Version:1.2.1a
- Any other mods in use: None
- Were you using Steam?: Yes
- Which expansions do you NOT have? : I have every DLC.

**Longer Description of Issue:**
It seems that the "event zhdanov.1"codes in "event/komi_communist" made some changes to the leader(changed the protrait, the color of map). But it never changes the ideology subtype. The ministers and the characters intro of zhdanov didn't changed either.
(BTW, I also noticed that the tyumen country leader can't change to Khrushchev in current TNO Version. But I haven't check the file.)

**Steps to Reproduce/Cause Issue:**

1.Play Komi and make zhdanov in power.

2.Be regional, complete the political focus tree. Then you'll find out that the ideology subtype never changes.

etc...

**Screenshots:**

<img width="345" alt="20220221025444" src="https://user-images.githubusercontent.com/100090199/154859785-02d7a9f9-520e-408e-b206-b51444487a29.png">

**Comment by runelead00** [comment]
Fixed in UB
