### ISSUE TITLE
Romania - Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#671]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
![Screenshot (2554)](https://user-images.githubusercontent.com/98137316/154863893-228ed383-55fc-42fc-b4a5-3a9347dbeaf9.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
