### ISSUE TITLE
Wallace-All focuses locked after beginning to repeal the CRA

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#672]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW
- Were you using Steam? yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**
After taking the focus "The End of the Civil Rights Act", all focuses become locked because I fail the check for America not being in crisis. This includes the focuses that I'm supposed to be taking that only unlock after I start the repeal. No event gets me out of this, so I'm softlocked. This has happened twice now.

**Screenshots:**
![Screenshot (2565)](https://user-images.githubusercontent.com/98137316/154863995-2000fe98-6d8d-4439-b4f8-78cdecff852e.png)

**Comment by runelead00** [comment]
Fixed in Current Release
