### ISSUE TITLE
US Election failing every single time

### ISSUE THREAD

**Issue by James-Carson** [TNODevs/TNO-Bug-Tracker#677]
**Questions**

- Operating System: Windowa#s
- HOI4 Version: 1.11.7 (current)
- TNO Version: TNO 1.2.1a
- Any other mods in use: TNO USA GUI Rework
- Were you using Steam?: No
- Which expansions do you NOT have?: None except Waking the Tiger, La Resistance, and Man The Guns

**Longer Description of Issue:** Been playing a US campaign and when election season rolled around, I chose NPP. Each time I consistently got several calamitous campaigns and the R-Ds won every single time up to 1968, where I quit. This COULD be exceptionally bad rng, but it feels to frequent and specific to be much else.

**Comment by Scarsoftime** [comment]
This is exceptionally bad RNG.
