### ISSUE TITLE
Any Country  - Game crashes during

### ISSUE THREAD

**Issue by Kommonwealth** [TNODevs/TNO-Bug-Tracker#678]
**Questions**

- Operating System: Linux Mint
- HOI4 Version: 1.11.16
- TNO Version: 1.2.1a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? I own all expansions 

**Longer Description of Issue:** I was playing a HRE game when the Pan African Front declared war on Libera and Mendi, which formed the Mano River Pact. When Liberia capitulated it went to a peace deal, which quickly crashed the game.

**Steps to Reproduce/Cause Issue:**

1. Have the Pan African Front win the West African War

2. Have them dec on Liberia and Mendi

3. Wait for Liberia to cap

[Game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8114072/Game.zip)

**Comment by Stormeagle449** [comment]
Should be fixed in current build.
