### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by SpasBuryatiu** [TNODevs/TNO-Bug-Tracker#680]
**Questions**

- Operating System: Windows 10
- HOI4 Version: v1.2.1 
- TNO Version: v1.11.7
- Any other mods in use: Russian translation of TNO
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all of them

**Longer Description of Issue:**
In file TNO_Russia_scripted_effects.txt superregional unification of Werbell's Magadan still refers to leaders name not the character and in that case Magadan switches to Petlin's cosmetic tag and focus tree
**Steps to Reproduce/Cause Issue:**

1. Unite Siberia as Werbell's Magadan if leaders name is not "Mitchell WerBell III"

**Screenshots:**
![2022-02-23_00-08-26](https://user-images.githubusercontent.com/75320946/155201789-e1f9e08e-5d2f-49db-ac41-3e0401fcf9eb.png)
1. Screenshot of that piece of code
![image](https://user-images.githubusercontent.com/75320946/155201731-b69f942e-f39d-44df-b240-5aa027aa1c12.png)
2. Not mine. But the how it looks at game

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
