### ISSUE TITLE
Brazil Joins the Andean Pact event- Incredibly loud softlock

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#681]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current 
- Any other mods in use: 2WRW
- Were you using Steam? yes
- Which expansions do you NOT have? none

**Longer Description of Issue:**
Playing as Magadan and got the event that Brazil joined the Andean Pact. By this, I mean both the gazette and an event box with that title, however I couldn't see anything more of the latter as the game froze, with a layered and endlessly repeating sound for a new gazette. Hitting escape brought up the menu but it'd always disappear. I could see the soldier representing some of my divisions moving very laggily, so not everything was frozen, but I couldn't actually get the boxes to go away. There weren't an infinite number of boxes, but there did seem to be a link to the repeated "new gazette" sound and the fact that i couldn't click.
**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by GeneralLemarc** [comment]
Reloaded autosave(this happened on the 20th) and it happened again. I think this kills whatever game it spawns in

**Comment by runelead00** [comment]
Likely a mod conflict, Brazil joining the Andean Pact has been disabled since TT1
