### ISSUE TITLE
KYR・TAJ・UTL - The peace process doesn't work.

### ISSUE THREAD

**Issue by Tarepa** [TNODevs/TNO-Bug-Tracker#682]
**Peace process won't work in case of Islamist victory in war over Central Asia.**

Operating System: Windows 11 Pro 21H2 (22000.527)
HOI4 Version: Barbarossa 1.11.8.89a0 (7257)
TNO Version: 1.2.1a - Toolbox Theory NSB Patch A
Any other mods in use: No
Were you using Steam? Yes
Which expansions do you NOT have? I should have them all.

**Longer Description of Issue:**
If Japan wins the Great Game over Central Asia, the final stage of which is the invasion of Turkestan by the alliance of Kyrgyzstan and Tajikistan, the peace process for this war will not function properly, and even if all of Turkestan is occupied by the alliance, it is still technically at war.

**Steps to Reproduce/Cause Issue:**

1. Islamists seize power in Kyrgyzstan.

2. Islamic fundamentalists seize power in Tajikistan.

3. The alliance between Kyrgyzstan and Tajikistan completely defeats Turkistan.

**Screenshots:**
![20220226014748_1](https://user-images.githubusercontent.com/26321161/155754532-21cb4e3f-406c-4cd0-8d8e-cd728faec031.jpg)

**Comment by bigbadboy78** [comment]
Same thing occurs if the Tajik state wins. I had terra e liberta btw.

**Comment by Tarepa** [comment]
I joined TNO team and fixed
