### ISSUE TITLE
Game crash allways when i start a country

### ISSUE THREAD

**Issue by HOI4Gamer** [TNODevs/TNO-Bug-Tracker#683]
**Questions**

- Operating System: Windows 11
- HOI4 Version: 1.11.8
- TNO Version: 1.2.1a
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? Waking the Tiger, Death or Dishonor, Together for Victory

**Longer Description of Issue:**
It crashs alwaise when i load a country.
**Steps to Reproduce/Cause Issue:**

1. Select a country

2. Load the country 

3. And then it crashs
etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**

**Comment by Kommissar396** [comment]
Im also having this bug, pls send help

**Comment by Dukksyy** [comment]
Same, need help

**Comment by Martigames** [comment]
same

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
