### ISSUE TITLE
germany/collab england - can't delete or change templates from units given by plymouth deal

### ISSUE THREAD

**Issue by demanvanwezel** [TNODevs/TNO-Bug-Tracker#684]
**Questions**

- Operating System: Windows 10 Home
- HOI4 Version: 1.11.7
- TNO Version: 1.2.1a
- Any other mods in use: none
- Were you using Steam? yes
- Which expansions do you NOT have? have them all

**Longer Description of Issue:**
if collab england wins the civil war and negotiates a settlement with germany over plymouth then germany get's 3INF-division and 1 tank-division which you can't delete or change template from, this is especially annoying as speer germany as they count towards the 50 unit limit
**Steps to Reproduce/Cause Issue:**

1. collab england wins the civil war

2. negotiate with germany over plymouth

**Comment by runelead00** [comment]
Fixed in Dev Build
