### ISSUE TITLE
usa- the CIA descriptions dont seem to be apearing

### ISSUE THREAD

**Issue by frontierplay** [TNODevs/TNO-Bug-Tracker#686]
**Questions**

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by Scarsoftime** [comment]
Closed: No issue description is provided.
