### ISSUE TITLE
All countries - CTD immediately after map loads in

### ISSUE THREAD

**Issue by PhantomBread225** [TNODevs/TNO-Bug-Tracker#687]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.8.89a0
- TNO Version: 1.2.1a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back

**Longer Description of Issue:** Upon starting a new game or loading a save file, the game will function normally until the map fully loads in after choosing a country.

**Steps to Reproduce/Cause Issue:**

1. Select "New Game" or "Load Game"

2. Choose any country or select and save file

3. Click on button labelled "START"

4. Wait for map to load in.

**Screenshots:** The nature of the issue at hand does not allow me 

**Game Saves and Log Files, if possible:**
The nature of the issue in and of itself doesn't permit saves
Log files:
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8172734/error.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8172735/system.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8172736/code_revisions.log)
Exception:
[exception.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/8172740/exception.txt)

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
