### ISSUE TITLE
speer germany/bulgaria/madagascar - bulgaria and madagascar don't properly join zolverein

### ISSUE THREAD

**Issue by demanvanwezel** [TNODevs/TNO-Bug-Tracker#688]
**Questions**

- Operating System: Windows 10 Home
- HOI4 Version: 1.11.7
- TNO Version: 1.2.1a
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? have all of them

**Longer Description of Issue:**
after winning the civil war as speer bulgaria joins the pakt but only gets the idea of the zollverein, they don't join the german economic union, madagascar after taking the decision to welcome them only joins the pakt but neither get's the zollverein idea nor joins the economic union

**Steps to Reproduce/Cause Issue:**

1. win game for bulgaria

2. win proxy war for madagascar

3. win GCW as speer

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in UB
