### ISSUE TITLE
Reichskommissariat Südwestafrika - American John D. Lavelle is general for Reichskommissariat

### ISSUE THREAD

**Issue by Polskers** [TNODevs/TNO-Bug-Tracker#689]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.8
- TNO Version: 1.2.1.a
- Any other mods in use: Music Mod
- Were you using Steam? Yes
- Which expansions do you NOT have? N/A

**Longer Description of Issue:** See title: John Lavelle is a general for Südwestafrika

**Steps to Reproduce/Cause Issue:**

1. Start up game as Südwestafrika

2. Create an army, choose a general, John D. Lavelle is there.

**Screenshots:**
![hoi4_11](https://user-images.githubusercontent.com/50228622/156686817-79fa1e70-79da-42dc-9a67-5ba9f0849f94.png)

**Comment by runelead00** [comment]
Fixed in Current Release
