### ISSUE TITLE
Oman - Missing text of event "Victory in Oman"

### ISSUE THREAD

**Issue by Ajeje30** [TNODevs/TNO-Bug-Tracker#69]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.1
- TNO Version: 1.1.2a
- Any other mods in use: No
- Were you using Steam? No
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Missing text of event "Victory in Oman" after Oman defeat The Dhofar Rebellion
**Steps to Reproduce/Cause Issue:**

1. Oman defeat The Dhofar Rebellion

**Screenshots:**
![Screenshot (78)](https://user-images.githubusercontent.com/82140538/129362249-ba992787-00b9-42ab-a813-ed160796e525.png)
![Screenshot (77)](https://user-images.githubusercontent.com/82140538/129362618-083a6222-7bad-4a9e-9aa2-32c7f23ab559.png)

**Comment by Scarsoftime** [comment]
Ah yes, the screenshot that has been circulating around in the server a lot. It has been fixed in the developer build. Thank you for your report.
