### ISSUE TITLE
Brazil South African War -- "Sell Equipment" decisions cause equipment to be added to the stockpile rather than removed

### ISSUE THREAD

**Issue by jhhillman** [TNODevs/TNO-Bug-Tracker#690]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Most Recent as of 3/4/2022
- TNO Version: "
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? The only expansion I have is No Step Back.

**Longer Description of Issue:**
When the "Sell Equipment" decisions are moused over in the South African War decision panel when playing as Brazil, the tooltip will say that the equipment will be added to the stockpile, rather than removed. When the decisions are selected, the equipment will be added to the stockpile. 

**Steps to Reproduce/Cause Issue:**

1. Play as Brazil
2. Select "Sell Equipment" decision in SAW decision panel. 

etc...

**Screenshots:**

**Comment by Scarsoftime** [comment]
fixed

**Comment by jhhillman** [comment]
Lovely
