### ISSUE TITLE
Any Russian warlord- cant research nuclear technologies

### ISSUE THREAD

**Issue by Matcher1938** [TNODevs/TNO-Bug-Tracker#693]
**Questions**

- Operating System:
- Last:
- last
- Any other mods in use: 2WRW
- Which expansions do you NOT have? NSB, walking tiger

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by Ajeje30** [comment]
Also Scotland and Ireland can't

**Comment by Scarsoftime** [comment]
Only certain nations can research those technologies, i.e. the nations that actually has access to nuclear technology such as the majors.
