### ISSUE TITLE
USA - John Birch Society Investigations Loc text not showing

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#694]
**Questions**

Operating System: Windows 10

HOI4 version
1.11.7

TNO version
1.2.1b

Any other mods in use: No
Were you using Steam? Yes 

Which expansions do you NOT have?
TFV, DOD, MTG, LAR, NSB

**Longer Description of Issue:**

RFK COINTELPRO investigations of John Birch Society doesn't show text and is missing locs.

Steps to reproduce / Cause of the issue
Code must not be inputted correctly to show the paragraph that would come post-active, after clicking these events. 

Expected behavior:

A flavor event loc describing what each of the events involves.

**Screenshots:**

![Screenshot (111)](https://user-images.githubusercontent.com/84231463/156946860-1764d406-b856-4509-9e37-e19d0c03596d.png)
![Screenshot (112)](https://user-images.githubusercontent.com/84231463/156946867-2afb28c6-359a-4030-b9bc-47581a4b40f0.png)
![Screenshot (113)](https://user-images.githubusercontent.com/84231463/156946871-eb56eaa2-72ce-46ca-9b7a-624233d45213.png)

**Comment by Stormeagle449** [comment]
Fixed in UB.
