### ISSUE TITLE
Absence of factories 

### ISSUE THREAD

**Issue by petrofuki** [TNODevs/TNO-Bug-Tracker#696]
- Operating System:
- HOI4 Version: 1.11.8
- TNO Version: Toolbox Theory
- Any other mods in use: Nope
- Were you using Steam? No
- Which expansions do you NOT have?

I have such a problem. Nothing crashes, everything is fine, but there are no military and ordinary, civilian factories.  And the AI has the same thing, when I deleted the mod, then downloaded it again and it worked. But it doesn't work now. Why?

**Comment by Scarsoftime** [comment]
Welcome to Toolbox Theory. Please read about the Production Units mechanic in the "HELP" section of the economy tab.
