### ISSUE TITLE
All Countries Crash at Jan 1 1967

### ISSUE THREAD

**Issue by Gunner6991** [TNODevs/TNO-Bug-Tracker#698]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Barbarossa v1.11.8.89a0 (bbd9)
- TNO Version: 1.2.1a
- Any other mods in use: 

1. +Easybuff
2. radio_tno
3. The New Order: Cheat Mod++
4. Last Waltz
5. USA Presidency Cheat mod
6. Its all over but the crying

- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Every country crashes at Jan 1 1967. Reloading crashes when selecting anything also affects previous autosaves.
**Steps to Reproduce/Cause Issue:**

1. Play to Jan 1 1967

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**
[Hoi4tnoSaves.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8220782/Hoi4tnoSaves.zip)

**Comment by runelead00** [comment]
likely was submod related, stale now, closing issue, rereport if reoccurs
