### ISSUE TITLE
Burgundy Collapse - SS Legions still have their Heydrich civil war leader descriptions

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#702]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US elections gui

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
As the title says. De la Maziere and Eriksson are given descriptions as if they're fighting in the SS civil war instead of the Burgundy collapse.

**Comment by runelead00** [comment]
Fixed on UB
