### ISSUE TITLE
Balance Issue - Far East Forever War

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#703]
**Questions**

- Operating System:
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW
- Were you using Steam? yes
- Which expansions do you NOT have? all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
Men took until 1970 to defeat the Pacific Fleet. The fix for this pre-TT seems to have been undone in alot of cases-this is far from the only forever war I've seen in the far east.

**Screenshots:**
![Screenshot (2558)](https://user-images.githubusercontent.com/98137316/157856797-b53c9bc5-b138-4fc5-9eae-2adbba63a136.png)

**Comment by runelead00** [comment]
Should be Fixed in Current Release, with Improvements coming in UB
