### ISSUE TITLE
Cuba - Havana typos

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#704]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US Election GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"greatest city IN the greatest island" should be "greatest city ON the greatest island", and the comma in "but now, it is the center of revolutionary fervor" should be deleted.
![Screenshot (2588)](https://user-images.githubusercontent.com/98137316/157857176-db45abff-d8c6-455c-8ff6-5e87a53182e3.png)

**Comment by runelead00** [comment]
Fixed in dev build
