### ISSUE TITLE
Mexico - Veracruz typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#706]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"or better or for worse" should be "For better or for worse"
![Screenshot (2600)](https://user-images.githubusercontent.com/98137316/157857725-5bf6d7fe-2c04-4d7d-90be-c61e8b40f825.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
