### ISSUE TITLE
Peru - Lima typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#707]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US election GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
I have no idea what "the CBD" could ever in reference to besides a meme.
![Screenshot (2601)](https://user-images.githubusercontent.com/98137316/157858013-d2fe7bcc-df16-4961-94ee-69a6ce710674.png)

**Comment by runelead00** [comment]
Made it more clear in dev build (pretty sure CBD was meant to refer to the central business district of Lima, San Isidro)
