### ISSUE TITLE
Kaya - Missing loc

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#708]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
![Screenshot (2602)](https://user-images.githubusercontent.com/98137316/157858104-42d04dc1-ce04-4e10-9248-7316f3c83d1f.png)

**Comment by Stormeagle449** [comment]
Fixed for UB
