### ISSUE TITLE
Collapse of the Triumvirate misfiring

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#709]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI
- Were you using Steam? yes 
- Which expansions do you NOT have? all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
The "collapse of the Triumvirate" event fired randomly in 1968.
**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by Scarsoftime** [comment]
Your submods are likely at fault since they do affect events. Don't run the US elections GUI unless you're playing as them.
