### ISSUE TITLE
Forever war - Western Siberia

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#714]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US elections GUI
- Were you using Steam? yes
- Which expansions do you NOT have? all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
Screenshot says it all. I've only seen this once though. If I had to guess, I'd say the bug where the unifiers send all their units to guard borders with nations that can't attack them instead of fighting the wars they're in may have come back.
**Screenshots:**
![Screenshot (2609)](https://user-images.githubusercontent.com/98137316/157859639-2ed9a718-5e3a-4052-9ad4-294c2cde1ec8.png)

**Comment by runelead00** [comment]
Should be Fixed in Current Release, with Improvements coming in UB
