### ISSUE TITLE
Kaya- Bad retirement event

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#715]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US elections GUI
- Were you using Steam? yes 
- Which expansions do you NOT have? all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
I got the event "Purgatory", detailing how Kaya's chosen successor failed. Except he didn't. I went full moderate, reduced hardliner influence to zero, strongarmed Kido into accepting my successor, and got an event indicating success because, as I said, they had zero percent influence. And yet I got the bad ending anyway.
**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Current Release
