### ISSUE TITLE
Madagascar - Missing portrait

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#716]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
![Screenshot (2616)](https://user-images.githubusercontent.com/98137316/157859989-dcd6f459-f01a-4183-afec-69166afc3541.png)

**Comment by runelead00** [comment]
Fixed in Current Release
