### ISSUE TITLE
Speer's Germany - Can't begin Fall Rollo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#722]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US Elections GUI
- Were you using Steam? yes
- Which expansions do you NOT have?  all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
After taking In The Land Of Wine And Strife, the decision to actually launch Fall Rollo never appeared. France gave me military access, but didn't declare war on Brittany, and I wasn't able to do this either.
**Screenshots:**
![Screenshot (2636)](https://user-images.githubusercontent.com/98137316/157946533-90b82f4c-7d84-43da-a86a-30ef8210e557.png)

**Comment by runelead00** [comment]
Being Changed in UB, no longer an issue
