### ISSUE TITLE
Vyatka - Missing portrait

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#723]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2642)](https://user-images.githubusercontent.com/98137316/157946916-8cfc22cc-1452-4690-8f73-5d71907e0d05.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
