### ISSUE TITLE
Ikeda- Typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#726]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"in their high horses" should be "on their high horses"
![Screenshot (2651)](https://user-images.githubusercontent.com/98137316/157949045-68601897-0490-472b-b3c4-075eeb9ebf39.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
