### ISSUE TITLE
Congo - The war dosent end even after democratic congo defated the other factions

### ISSUE THREAD

**Issue by Pozitox** [TNODevs/TNO-Bug-Tracker#728]
**Questions**

- Operating System: Windows 10
- HOI4 Version:1-11-8
- TNO Version: Latest
- Any other mods in use: Some songs and sensible map font mods
- Were you using Steam? : Yes
- Which expansions do you NOT have? : İ have them all

I was playing as the USA with Wallace , i ended the african war and stabilised the mandates , after that the congolese war begun and i supported the democratic congo , it went well but after a while i noticed that even after the war ended the event didnt show up and the "support congo" options were still on the decisions tab but they did nothing (except the send equipement ones)

**Steps to Reproduce/Cause Issue:**

1. İ asked a friend and apparently it happens when beafrika dosent declare war on congo , really i did nothing out of ordinary and the ai didnt declare war on them

Screenshot :
![Hearts of Iron IV (DirectX 9) 6 03 2022 21_31_09](https://user-images.githubusercontent.com/101464101/158021609-30a2e376-6aa3-4b2c-8cde-41851f4e008a.png)

**Comment by ModdingAccount** [comment]
Fixed in dev build.
