### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Liberty101** [TNODevs/TNO-Bug-Tracker#732]
**Questions**

- Operating System:
- HOI4 Version:
- TNO Version:
- Any other mods in use:
- Were you using Steam?
- Which expansions do you NOT have?

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1.
Not really a bug,just some error.the Italian DC economy focus’And Italy answers’ appears to let trade laws go to ‘closed economy’ which is against the description of the focus 

2.

etc...

**Screenshots:**

**Comment by runelead00** [comment]
Fixed in Dev Build
