### ISSUE TITLE
ENG - Free England not joining the OFN, softlocking their tree

### ISSUE THREAD

**Issue by LSbyju** [TNODevs/TNO-Bug-Tracker#735]
**Questions**

- Operating System: Windows 11
- HOI4 Version: 1.11
- TNO Version: can't remember but is the newest
- Any other mods in use: 2WRW
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all

**Longer Description of Issue:**
England cannot join OFN due to something, thus soft locking them

**Steps to Reproduce/Cause Issue:**
I do not know.

**Screenshots:**
https://media.discordapp.net/attachments/806276324297539586/952693603434627113/unknown.png

**Comment by Scarsoftime** [comment]
What year is this?

**Comment by Stormeagle449** [comment]
This seems to be WAD, that focus can only be taken if England joins the OFN and HMMLR England always joins, it might take a while but usually in a year or 2 they join
