### ISSUE TITLE
Don't even get to the title screen

### ISSUE THREAD

**Issue by Occasionalnewb** [TNODevs/TNO-Bug-Tracker#736]
**Questions**

- Operating System: windows
- HOI4 Version: 1.11.9
- TNO Version: latest, I just downloaded it 
- Any other mods in use: no
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
I start the game with the mod enabled and it crashes when it finishes loading
**Steps to Reproduce/Cause Issue:**

1. Start game with mod

2. Wait

3. Crash

**Screenshots:**
N/A
**Game Saves and Log Files, if possible:**
N/A

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
