### ISSUE TITLE
Pre-civil war Germany - Russian war event

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#737]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
This has happened every time I start a new Germany game
![Screenshot (2670)](https://user-images.githubusercontent.com/98137316/158688851-8edc06c7-53c4-403a-ac89-563ccb5800be.png)

**Comment by runelead00** [comment]
This is an issue with the 2WRW submod, not base TNO
