### ISSUE TITLE
Speer's Germany - Game doesn't register that I have tanks

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#739]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW, US Elections GUI
- Were you using Steam? yes 
- Which expansions do you NOT have?  all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
The decision to send tanks to Serbia in the Great Game was locked despite me having several thousand in my stockpile. Maybe this is because of the new tank designer? But I'm not sure how, since I only ever built standard tanks that I didn't customize.

**Screenshots:**
![Screenshot (2677)](https://user-images.githubusercontent.com/98137316/158690808-f6551052-9f7e-46b8-a7e6-79beb8fffd98.png)
![Screenshot (2678)](https://user-images.githubusercontent.com/98137316/158690847-3c8d5dd5-d9bc-4c90-9164-bc68308435bb.png)

**Comment by runelead00** [comment]
Fixed in Current Release
