### ISSUE TITLE
Speer's Germany - Grammatical issue

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#740]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
In the fourth sentence, "has and" should be removed in order for it to be grammatically correct.
![Screenshot (2675)](https://user-images.githubusercontent.com/98137316/158692541-80a049b2-b3c5-4703-932e-d71fa5af29ef.png)

**Comment by Scarsoftime** [comment]
Fixed
