### ISSUE TITLE
Speer's Germany -Missing decision loc

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#743]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2685)](https://user-images.githubusercontent.com/98137316/158694222-20b113ea-fa14-49bb-aee3-d233c2d96a98.png)

**Comment by Scarsoftime** [comment]
Fixed
