### ISSUE TITLE
Azawad - Missing party name

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#744]
**Questions**

- HOI4 Version: current
- TNO Version: current 
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
I'm aware that for alot of contentless countries the non-dominant ideology will be the only one with a name, but iirc the remaining ideologies should have their own names instead("communism", "conservative democracy", etc). For Azawad, and a couple other countries I'm posting issues for, these are absent and replaced with a single dash.
![Screenshot (2686)](https://user-images.githubusercontent.com/98137316/158694529-33988dee-f4ec-447b-a94a-cce21ad9198f.png)

**Comment by Scarsoftime** [comment]
Irrelevant
