### ISSUE TITLE
Air - Typo and missing party names

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#745]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
"the desert that surrounds the Air plateau IS nothing" should be "ARE nothing"
![Screenshot (2687)](https://user-images.githubusercontent.com/98137316/158694756-28e702e2-439b-4df3-95e3-3360ca3bf6e3.png)
![Screenshot (2690)](https://user-images.githubusercontent.com/98137316/158694847-160d0634-2e12-42ec-817c-7d86bc7a473d.png)
![Screenshot (2691)](https://user-images.githubusercontent.com/98137316/158694881-eab1d2fb-0090-43bf-8270-78d191876ee9.png)
![Screenshot (2692)](https://user-images.githubusercontent.com/98137316/158694912-3acaeda3-7d3b-49e1-a5c9-489729caf0ed.png)

**Comment by runelead00** [comment]
As to the typo, "the desert ... is nothing" is the correct from grammatically since desert is singular
