### ISSUE TITLE
Kanem - Missing party names

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#747]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2688)](https://user-images.githubusercontent.com/98137316/158695998-58d0eb8e-5121-4f91-aeac-6a54835e7dae.png)
![Screenshot (2689)](https://user-images.githubusercontent.com/98137316/158696044-7e743310-4cdb-487c-b681-40c80f777aa1.png)

**Comment by Scarsoftime** [comment]
Irrelevant
