### ISSUE TITLE
Mendi - Minister portrait issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#748]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
David Lansana is listed as his own head of government, but the portrait is of someone else. Additionally, the same portrait is used for economy and security minister despite the names being different.
![Screenshot (2693)](https://user-images.githubusercontent.com/98137316/158696227-6870cbef-0028-4873-9b4b-b84d0b552345.png)
![Screenshot (2694)](https://user-images.githubusercontent.com/98137316/158696266-36cd9a0a-ae6d-47c9-9cd7-0ff157283768.png)
![Screenshot (2695)](https://user-images.githubusercontent.com/98137316/158696308-c90a1f7f-8878-4f3d-867b-1fe04d26ed49.png)
![Screenshot (2696)](https://user-images.githubusercontent.com/98137316/158696343-3e549e4a-650c-48dd-a754-d1bba74394aa.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
