### ISSUE TITLE
West Russia - Forever war

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#749]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI
- Were you using Steam? yes 
- Which expansions do you NOT have? all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
Unification didn't occur until November 1967. I wasn't watching the wars, but since West Russia is usually a fast second to unify after Central Siberia it's likely something bugged out in one or more of the factions' ai.

**Screenshots:**
![Screenshot (2697)](https://user-images.githubusercontent.com/98137316/158696590-d2cc600b-c4fe-45ee-9f23-b7e04e8bf8c6.png)

**Comment by runelead00** [comment]
Should be Fixed in Current Release, with Improvements coming in UB
