### ISSUE TITLE
Socialist Republic of Turkmenistan- Possible minister issue

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#750]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
While I'm not entirely sure this is an issue, I doubt that this male security minister is supposed to be named Anna
![Screenshot (2699)](https://user-images.githubusercontent.com/98137316/158696801-e0bf09a1-99bf-44db-98c7-552299918c0c.png)

**Comment by runelead00** [comment]
Intended
