### ISSUE TITLE
Turkestan Legion - Missing economy minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#751]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2700)](https://user-images.githubusercontent.com/98137316/158696922-d2d64f65-2868-49f5-9a24-b77ebdf85f32.png)

**Comment by runelead00** [comment]
Closed as Duplicate Issue
