### ISSUE TITLE
Tajik State - Missing leader portrait

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#752]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2701)](https://user-images.githubusercontent.com/98137316/158697047-21063111-26ca-4df7-9660-c59eea3a1b3e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
