### ISSUE TITLE
Kingdom of Afghanistan - Missing economy minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#754]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
![Screenshot (2703)](https://user-images.githubusercontent.com/98137316/158697415-dbeab94f-749c-45b8-9b02-4ea56ceaee3c.png)

**Comment by runelead00** [comment]
fixed in ub, slot filled with vacant minister
