### ISSUE TITLE
Afrikaner Abwehrfront - Missing ministers

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#755]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
![Screenshot (2704)](https://user-images.githubusercontent.com/98137316/158697581-d800659d-854e-4527-9f1d-80ecad3ce206.png)

**Comment by runelead00** [comment]
Fixed in Dev Build (hopefully (Reichsstaat collapse code was a broken mess))
