### ISSUE TITLE
ZANU Zimbabwe - Minister Issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#756]
**Questions**
 
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Leopold Takawira is listed as both economy minister and head of government. Also, Robert Mugabe's portrait for security minister(which he is while also being leader) is reversed from his leader portrait
![Screenshot (2705)](https://user-images.githubusercontent.com/98137316/158698734-cc9c3d13-0aa0-46a7-89c9-8737efeb1dee.png)
![Screenshot (2706)](https://user-images.githubusercontent.com/98137316/158698771-b3981e2c-e90e-4efa-b115-e773d86820b7.png)
![Screenshot (2707)](https://user-images.githubusercontent.com/98137316/158698808-511840fa-a8ce-488e-bc15-53dcb65ce616.png)
![Screenshot (2708)](https://user-images.githubusercontent.com/98137316/158698826-0c38f952-a725-4da6-9fcd-e79fcefdced8.png)

**Comment by runelead00** [comment]
WAD
