### ISSUE TITLE
State of Uganda - Minister issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#757]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Missing security minister, and Idi Amin is his own foreign minister. Even if the latter is intentional, I don't think it makes sense given how brutal and uncaring of how he looked he was irl.
![Screenshot (2709)](https://user-images.githubusercontent.com/98137316/158699031-c4959973-aa10-4e2d-8895-3f98f4971237.png)

**Comment by runelead00** [comment]
WAD
