### ISSUE TITLE
Norway- Missing head of government

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#758]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
![Screenshot (2710)](https://user-images.githubusercontent.com/98137316/158699163-619f86c8-6429-46b4-af21-81dbbeda01b5.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
