### ISSUE TITLE
State of Turks - Missing economy minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#759]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2712)](https://user-images.githubusercontent.com/98137316/158699348-6c2f2493-bf12-4d74-8ef1-eb6000b6426e.png)

**Comment by runelead00** [comment]
Closed as Duplicate Issue
