### ISSUE TITLE
West Siberia - Forever War

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#760]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI
- Were you using Steam? yes
- Which expansions do you NOT have? all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
This has stayed this way for an unknown amount of time, possibly years, and didn't change for five months after I took this screenshot
**Screenshots:**
![Screenshot (2713)](https://user-images.githubusercontent.com/98137316/158702096-eca4fff6-e5c2-460f-8f91-0909999f4bbf.png)

**Comment by runelead00** [comment]
Should be Fixed in Current Release, with Improvements coming in UB
