### ISSUE TITLE
Bhutan-Minister Issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#761]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Kanwal Singh is listed as both leader and head of government, but the portraits are different
![Screenshot (2714)](https://user-images.githubusercontent.com/98137316/158702673-0b05c52f-1b12-4bc3-8080-e8bcb2288ba0.png)
![Screenshot (2715)](https://user-images.githubusercontent.com/98137316/158702705-7f8a4461-b082-4717-bd4b-ca6a7d03b517.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
