### ISSUE TITLE
Baltischer Bund - Minister issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#762]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
Balticscher Bund is missing economy and security ministers, and judging by the head of government the two they do have are wrong.
![Screenshot (2720)](https://user-images.githubusercontent.com/98137316/158703106-a012333d-b0c3-4e3a-9852-f8773d49dee6.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
