### ISSUE TITLE
My game Crash

### ISSUE THREAD

**Issue by Martigames** [TNODevs/TNO-Bug-Tracker#763]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.9 barbarossa
- TNO Version: 1.2.1a
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? I have all of them

**Longer Description of Issue:**
Constant crash launching the game

**Steps to Reproduce/Cause Issue:**

1. Launch hoi4

2. Play

3. Play single player or multiplayer

4. Loading all the time and then crash

etc...

**Screenshots:**

![image](https://user-images.githubusercontent.com/101831419/158882060-cc781367-14b2-4135-b004-3ce363cb3e45.png)

**Game Saves and Log Files, if possible:**

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8289947/error.log)

**Comment by TheInterrogator** [comment]
I same the same issue, if you have a fix please tell me.

**Comment by TheSudoer** [comment]
I'm encountering the same issue on Ubuntu GNU/Linux 21.10 using Xorg and the GNOME desktop environment.

**Comment by TheInterrogator** [comment]
I found a fix, I don't know if it's going to work for you.
1. Changed from borderless to full screen
2. Changed the resolution from default to lower (The lowest amount can work)
3. Changed back to borderless and changed the resolution back to default

**Comment by Martigames** [comment]
> I found a fix, I don't know if it's going to work for you.
> 
> 1. Changed from borderless to full screen
> 2. Changed the resolution from default to lower (The lowest amount can work)
> 3. Changed back to borderless and changed the resolution back to default

I will try, hope this work

**Comment by Martigames** [comment]
The issue gets fixed for me by the way that the man up here propses
