### ISSUE TITLE
WRRF/Brazil - Andean Pact Bug

### ISSUE THREAD

**Issue by bzzbzzbzzbeep** [TNODevs/TNO-Bug-Tracker#765]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: Radio TNO, Custom Country Paths
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them

**Longer Description of Issue:**

**Steps to Reproduce/Cause Issue:**

1. June 1976, playing as WRRF

2. Brazil joins Andean Pact

3. The event keeps being spammed with no way of stopping. (VIDEO BELOW IS LOUD)

https://user-images.githubusercontent.com/96382658/158930703-b2bea3de-fa3a-4a35-aadf-0fed87a328e2.mp4

etc...

**Screenshots:**

**Comment by Scarsoftime** [comment]
Custom Country Paths is at fault.
