### ISSUE TITLE
Irkutsk/Far Eastern Soviet Republic - Crashing to Desktop on March 25, 1967

### ISSUE THREAD

**Issue by XxSpicyLemonxX** [TNODevs/TNO-Bug-Tracker#766]
**Questions**

- Operating System: Windows 10 
- HOI4 Version: Most up to date version
- TNO Version: Up to date
- Any other mods in use: TNO Last Walt of Europe, Radio TNO, MoeReich (cringe), Player Led peace conferences, TNO custom paths mod, and the Toolpack mod
- Were you using Steam? Yes
- Which expansions do you NOT have? 

**Longer Description of Issue:**
My game keeps on crashing on that date, the only other big events at that time are: Free Indonesia fighting and winning against the Republic of Indonesia, Huttigs Afrika having demilitarized zones in Angola and very few others, and Pan-African Cameroon fighting against the non-Pan-African countries. Other than these i have no idea as to why my game would crash. 
**Steps to Reproduce/Cause Issue:**

1.

2.

etc...

**Screenshots:**
![image](https://user-images.githubusercontent.com/98870746/159108156-d7dcbc5c-37ba-48bb-85ed-f735189bd731.png)
![image](https://user-images.githubusercontent.com/98870746/159108164-1d4a34d8-05a3-4e48-9ce3-c3a51e9de11b.png)
![image](https://user-images.githubusercontent.com/98870746/159108260-db53b3f9-3a2f-4f26-8512-e1b318e51405.png)

**Game Saves and Log Files, if possible:** 
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8310310/error.log)

**Comment by ModdingAccount** [comment]
Unable to replicate.
