### ISSUE TITLE
Magadan - Invalid event

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#769]
**Questions**

- HOI4 Version: current
- TNO Version: current 
- Any other mods in use: 2WRW and US elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2734)](https://user-images.githubusercontent.com/98137316/159151485-cf4152d2-8969-4ef4-bbda-9228f8ad4f97.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
