### ISSUE TITLE
Kostanay - Missing head of government

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#771]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
![Screenshot (2737)](https://user-images.githubusercontent.com/98137316/159151523-776bcb58-bce6-4885-8ef2-42b15daa8b8b.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
