### ISSUE TITLE
People's Republic of Uzbekistan - Minister that seems to give no effects

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#772]
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US Elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**

![Screenshot (2738)](https://user-images.githubusercontent.com/98137316/159151546-bf362bd1-abe4-499b-8dfd-0f67ba9569e8.png)

**Comment by Stormeagle449** [comment]
Fixed for UB
