### ISSUE TITLE
Portugal - No Annexation after civil war 

### ISSUE THREAD

**Issue by T3dsch1K1** [TNODevs/TNO-Bug-Tracker#776]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: Custom Country Paths
- Were you using Steam? Yes
- Which expansions do you NOT have? /

**Longer Description of Issue:**
After the Iberian Collapse and the following Portugese civil war, when the portugese Peoples Front capitulated the Purtugese Republic and the government of National Salvation, instead of annexing it they made a whitepeace.

**Steps to Reproduce/Cause Issue:**

1.Iberia needs to follow the path to collapse 

**Screenshots:**
![Screenshot (177)](https://user-images.githubusercontent.com/94788365/159162039-93e65566-12c7-47ff-bc27-af7fd27052b4.png)
(the same as shown happened also with the portugese republic)

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting.
