### ISSUE TITLE
Komi - Wrong general(s?) at start

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#777]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW
- Were you using Steam? yes 
- Which expansions do you NOT have? all except historical portraits, rocket launcher unit pack, united and ready, waking the tiger, and wallpaper

**Longer Description of Issue:**
The guy at the top is only supposed to be there after Tabby takes over. I'm also not sure if the others in the image beyond Ivan Korolkov should be there either
**Steps to Reproduce/Cause Issue:**
It was this way when I started the game.
**Screenshots:**
![Screenshot (2752)](https://user-images.githubusercontent.com/98137316/159191919-47010dde-6e57-40e6-8c61-85c12fcf9a5d.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
