### ISSUE TITLE
The Apocalypse(started as USA) - Broken West African Crisis event popped during the apocalypse

### ISSUE THREAD

**Issue by Iamgoofball** [TNODevs/TNO-Bug-Tracker#779]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest patch of the Steam release
- TNO Version: Same but for the workshop version
- Any other mods in use: The Kaiserreich Soundtrack and Old World Blues Soundtrack mods.
- Were you using Steam? Yes
- Which expansions do you NOT have? I don't own any HOI4 expansions.

**Longer Description of Issue:**
While sitting around in the apocalyptic world to read all the post-apocalypse events for the US, I got a broken prompt for a West African Crisis event.

**Steps to Reproduce/Cause Issue:**

1. Start the game and immediately set off the nukes.

2. Wait around long enough and eventually, you'll get the picture below. I don't know what date it's at, unfortunately, due to the UI hiding the current date after the nuclear apocalypse happens.

**Screenshots:**
![hoi4_AtSJacilKn](https://user-images.githubusercontent.com/4081722/159192962-b74c51f8-e996-476f-ace8-1dbb835f417c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
