### ISSUE TITLE
My game crashed when using 1.11 No step back (No DLC) with TNO.

### ISSUE THREAD

**Issue by couldnthinkofausername** [TNODevs/TNO-Bug-Tracker#780]
**Questions**

- Operating System:
- HOI4 Version: 1.11
- TNO Version: The toolbook theory
- Any other mods in use: none
- Were you using Steam? Yes
- Which expansions do you NOT have? I have no expansions i am poor

**Longer Description of Issue:**
I do not understand the issue. But what happened is that i booted up hoi4 with 1.11, it loaded the screen where you can pick the countries but i clicked on germany and it just crashed.

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
