### ISSUE TITLE
The NPP-Far Right should be renamed to the NPP-Right

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#781]
There is no guarantee that requested suggestions will be implemented. Do not request lore changes or sweeping adjustments to gameplay or content. Suggestions may be closed at any time. If you can't explain your suggestion succinctly in under a paragraph, it likely isn't something that would be accepted.

**Description of Suggestion:**
Title says it all
**Reasoning Behind Suggestion:**
Iirc, the Left-NPP is now the Far Left NPP, with the change to communism. As such, it doesn't make sense to call Wallace's faction "far-right" when the Yockies are the farthest right faction of the party by a country mile. The paths for the current Center and Far-Right factions to work together would make alot more tonal sense if it was just the Center and the Right, too.
**Additional Information:**
By the metric of both the NPP and the in-universe American political scene, Wallace isn't an extremist unless he tries to segregate everything. A bastard, yes, but not an extremist, at least not always.

**Comment by runelead00** [comment]
Factions are being named for UB to make more sense
