### ISSUE TITLE
Fuuta Fulbe - Incorrect Annexation after West African War

### ISSUE THREAD

**Issue by T3dsch1K1** [TNODevs/TNO-Bug-Tracker#782]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: Custom Country Paths
- Were you using Steam? Yes
- Which expansions do you NOT have? /

**Longer Description of Issue:**
When the PALF wins the West African War against the FMA, Fuuta Fulbe, instead of beeing annext to the right country, is annext by Ghana. 

**Steps to Reproduce/Cause Issue:**

1.Let the PALF win the West African war against the French Military Alliance

**Screenshots:**
![Screenshot (178)](https://user-images.githubusercontent.com/94788365/160149060-2e584a38-bbf3-4577-81f2-48da6ed8e123.png)

**Comment by runelead00** [comment]
Fixed for UB
