### ISSUE TITLE
Offensive and Defensive lines are invisible

### ISSUE THREAD

**Issue by 1mokay** [TNODevs/TNO-Bug-Tracker#783]
- Operating System: Windows 10
- HOI4 Version: 1.11.9
- TNO Version: 1.2.1
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all

**Longer Description of Issue: I cant see my offensive lines, front lines and defensive lines

![unknown](https://user-images.githubusercontent.com/102377419/160161385-5410a543-6e6c-4b97-888a-05d4bca18e1f.png)
[](url)

**Comment by Stormeagle449** [comment]
Can't reproduce.
