### ISSUE TITLE
SAM - Inability to unify the super-regions through diplomacy

### ISSUE THREAD

**Issue by Tarepa** [TNODevs/TNO-Bug-Tracker#785]
**Questions**
If Samara's ideology is despotism, any unification of Western Russia and Siberia through diplomacy is impossible.

Operating System: Windows 11 Pro 21H2 (22000.556)
HOI4 Version: Barbarossa 1.11.9.e52a (bd67)
TNO Version: 1.2.1a - Toolbox Theory NSB Patch A
Any other mods in use: No
Were you using Steam? Yes
Which expansions do you NOT have? I should have them all.

**Longer Description of Issue:**
According to TNO_Russia_scripted_triggers it seems that the despotic Samara is intended to be capable of diplomatic unity with Magadan, Chita, Novosibirsk and Krasnoyarsk, but it does not work at all due to a mistake in the script in the relevant section.

**Steps to Reproduce/Cause Issue:**

1. Despotic Samara unifies Western Russia, and Magadan, Chita, Novosibirsk, or Krasnoyarsk unifies Siberia

2. Ensure that the dicision that West Russia and Siberia can be diplomatically united remains ineffective as of January 1, 1969.

**Screenshots:**
As in the case of the other countries, the countries shown in the picture should be grouped by OR = {}.
<img width="736" alt="image" src="https://user-images.githubusercontent.com/26321161/160246741-237cdfac-b9f0-4ea3-b0be-b3462200b5d9.png">

**Comment by tkgitno** [comment]
Fixed in Dev Build
