### ISSUE TITLE
GRO - No post-Congo Civil War events at all under certain conditions.

### ISSUE THREAD

**Issue by Tarepa** [TNODevs/TNO-Bug-Tracker#786]
**Questions**
Some simple mistakes in the script will prevent any subsequent African content depending on the outcome of the Congo civil war.

Operating System: Windows 11 Pro 21H2 (22000.556)
HOI4 Version: Barbarossa 1.11.9.e52a (bd67)
TNO Version: 1.2.1a - Toolbox Theory NSB Patch A
Any other mods in use: No
Were you using Steam? Yes
Which expansions do you NOT have? I should have them all.

**Longer Description of Issue:**
Since the trigger for events after the collapse of Grossafrikanischer Reichsstaat is still set to GRO, the defeat of Afrikaner-Abwehrfront in the Congo Civil War would prevent any subsequent events (even the crucial Mozambique Civil War) related to the former Grossafrikanischer Reichsstaat territory.

**Steps to Reproduce/Cause Issue:**

1. Grossafrikanischer Reichsstaat collapses (at a stage other than level 3 of devastation in Africa)

2. Afrikaner-Abwehrfront is completely defeated in the Congo Civil War and annexed by one of the countries.

3. Four Years After the Fall of the Grossafrikanischer Reichsstaat, No Mozambican Civil War

**Screenshots:**
As you can see below, the triggers for all events intended to occur after the collapse of Grossafrikanischer Reichsstaat are scripted directly into the GRO.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/26321161/160247769-573c15d3-3b23-49a4-8463-67ad857a98f7.png">

**Comment by tkgitno** [comment]
Fixed in Dev Build
