### ISSUE TITLE
Game Start Crash

### ISSUE THREAD

**Issue by CT7778** [TNODevs/TNO-Bug-Tracker#787]
**Questions**

- Operating System: Windows 10
- HOI4 Version: Latest
- TNO Version: Latest
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? I have them all

**Longer Description of Issue:**
Load up the game, wait, CTD happens as soon as the game loads
**Steps to Reproduce/Cause Issue:**

1.  load up the game

2. wait
3. CTD

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**

**Comment by runelead00** [comment]
Consolidated into single list with similar crashes
