### ISSUE TITLE
GAZ - Mozambique's civil war is broken.

### ISSUE THREAD

**Issue by Tarepa** [TNODevs/TNO-Bug-Tracker#788]
**Questions**
Many of the scripts related to the Mozambique Civil War are incorrectly specifying country tags and event IDs, so they do not function as intended in the scenario

Operating System: Windows 11 Pro 21H2 (22000.556)
HOI4 Version: Barbarossa 1.11.9.e52a (bd67)
TNO Version: 1.2.1a - Toolbox Theory NSB Patch A
Any other mods in use: No
Were you using Steam? Yes
Which expansions do you NOT have? I should have them all.

**Longer Description of Issue:**
First, if the US does not form a GZS in the event of a Mozambican civil war, they will send a volunteer force to the pro-Japanese regime of GAZ. Second, if GAZ wins the Mozambican civil war, the events originally intended to be used in the event of a GZO victory, except for World News, will occur against both the US and Japan, and GAZ will not enter the Japanese economic zone. Finally, if the GZO wins the Mozambican Civil War, the events that were originally intended to be used in the event of a GAZ victory, except for World News, will occur for both the U.S. and Japan, and the GZO will not enter the U.S. economic sphere.

**Steps to Reproduce/Cause Issue:**

1. Mozambique Civil War erupts.

2. The U.S. does not form the GZS.

3 Either GAZ or GZO will win that civil war.

**Screenshots:**
I was able to directly find the cause of the glitches after the end of the civil war.
<img width="753" alt="image" src="https://user-images.githubusercontent.com/26321161/160257262-b8651b7a-a2a0-4e9a-8c27-c2087375c83b.png">
This should be modified as follows
<img width="745" alt="image" src="https://user-images.githubusercontent.com/26321161/160257298-f2d04c60-bfea-4bb0-987d-299d29adb56a.png">

**Comment by tkgitno** [comment]
Fixed in Dev Build, thx for reporting
