### ISSUE TITLE
Goering Germany - Declares War with no way to reach target

### ISSUE THREAD

**Issue by awnman** [TNODevs/TNO-Bug-Tracker#79]
**Questions**

Operating System: Windows
HOI4 Version: 1.10.8
TNO Version: 1.1.2
Any other mods in use: No
Were you using Steam?: Yes
Which expansions do you NOT have?: La Resistance

**Longer Description of Issue:**
Goering's Germany declared war on Bulgaria as part of it's initial expansion focuses. However lacking land access to Bulgaria or access through the Mediterranean/Black it caused total collapse of Germany despite it being a very easy war. Perhaps give him a requirement to neighbour or be within a certain number of sea tiles for his focuses.
![Screenshot (368)](https://user-images.githubusercontent.com/88620806/129538834-7ae552d1-aa2d-4995-8434-238bcd2ead71.png)

**Steps to Reproduce/Cause Issue:**

1. Have Goering's Germany win

2. Wait for it to select the wrong focus.

etc...

**Screenshots:**
![Screenshot (368)](https://user-images.githubusercontent.com/88620806/129538857-49786cf1-0522-4919-afb2-d2983969ebef.png)

**Comment by runelead00** [comment]
Seems to be fixed as of current dev build
