### ISSUE TITLE
USA - Resolution Problem

### ISSUE THREAD

**Issue by ChadistChad** [TNODevs/TNO-Bug-Tracker#790]
- Operating System: Windows 11 64 bit
- HOI4 Version: v.1.11.9
- TNO Version: v1.2.1a “Toolbox Theory”
- Any other mods in use: No
- Were you using Steam? No
- Which expansions do you NOT have? Nothing

I was playing USA but because of my resolution i couldn't see the date of my country please fix this issue in the new hotfix
my resolution is 1366x768
![e6317a8a76d38047b37a8608bd3cff02](https://user-images.githubusercontent.com/78251263/160268933-4a530dbf-55b1-4539-a282-2c2305af17d5.png)

**Comment by runelead00** [comment]
Not something we can fix, only solution I can give is to change your UI scaling to work at your resolution
