### ISSUE TITLE
Game crashes when I try to start a TNO game (1.11 no DLC)

### ISSUE THREAD

**Issue by TheOriginalDoctor** [TNODevs/TNO-Bug-Tracker#791]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.9 Barbarossa
- TNO Version: 1.2.1
- Any other mods in use: none
- Were you using Steam? Yes
- Which expansions do you NOT have? Together for Victory, Death or dishonor, La Resistance, Waking the Tiger, Man the Guns, Battle for the Bosporus, No Step Back (no paying DLC at all) 

**Longer Description of Issue:** When I launch the game with (only) The New Order mod, it goes to the loading screen and when it finishes loading it immediately crashes going back to the desktop with the message from Paradox about a crash 

**Steps to Reproduce/Cause Issue:**

1. Open the game

2. Start a new game with The New Order mod

3. Wait for the loading to end, it crashes immediately after 

**Screenshots:**

![image](https://user-images.githubusercontent.com/102482944/160296301-8849f53b-f9f7-4cf7-8923-e684ea31e044.png)
The loading screen 

![image](https://user-images.githubusercontent.com/102482944/160296322-a4bfac11-38e1-4dbc-a7f6-63dc0adb3190.png)
The crash reporter

**Comment by topazand** [comment]
i hate this mod now, no one is even concerned with the crashes

**Comment by masterbobli** [comment]
It's not nobody is concerned. It's because nobody knows the cause of the crash.
