### ISSUE TITLE
Game Crash After Country Loads

### ISSUE THREAD

**Issue by Chamberlain1012** [TNODevs/TNO-Bug-Tracker#792]
**Questions**

- Operating System: Windows 11 Home

- HOI4 Version: 1.11.9 Barbarossa

- TNO Version: 1.2.1a

- Any other mods in use: none

- Were you using Steam? Yes

- Which expansions do you NOT have? I do not have any paid DLCs
- 
**Description**
The game crashed (with a Paradox crash report message) after I loaded up the country. The screen shows the country information screen (with the text about the country's backstory) for a few seconds after the game loads before the game crashes. I have done this with Germany, Japan, and the US and this has occurred with all of them. The save files for these games, which were created at country selection, are not saved.

**Comment by yungbusch17** [comment]
exact same happened to me

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
