### ISSUE TITLE
Sverdlovsk - Wrong leader and blank profile for democratic Sverdlovsk

### ISSUE THREAD

**Issue by BiplaneBully** [TNODevs/TNO-Bug-Tracker#793]
**Questions**

- Operating System: Windows 11 64-bit
- HOI4 Version: Barbarossa v1.11.9.e52a (cc45)
- TNO Version: v1.2.1a - Toolbox Theory NSB Patch A
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all the DLCs

**Longer Description of Issue:**

After you unite Western Siberia under Sverdlovsk and go democratic and have them win against the military in the elections and it says Boris Yeltsin should get into power, but he doesn't and someone else gets in power with no profile picture that I don't remember being mentioned.

**Steps to Reproduce/Cause Issue:**

1. Start the game as Sverdlovsk 

2. Unite Western Siberia

3. Choose to side with the Democracy lead by Boris Yeltsin during the election after the unification 

4. Win the election and get Boris inaugurated.

etc...

**Screenshots:**
![Hearts of Iron IV Screenshot 2022 03 29 - 14 58 22 11](https://user-images.githubusercontent.com/102611815/160685341-77e30d19-1e2e-4eb6-b285-289a2895a358.png)
![image](https://user-images.githubusercontent.com/102611815/160685762-7e44de45-85b1-4e2b-ba31-3852a17016e7.png)

**Comment by runelead00** [comment]
Fixed in Current Release
