### ISSUE TITLE
Serbia- Great game puppets wrongly 

### ISSUE THREAD

**Issue by T3dsch1K1** [TNODevs/TNO-Bug-Tracker#794]
**Questions**

- Operating System: Windows 10
- HOI4 Version: current
- TNO Version: current
- Any other mods in use: Custom country paths
- Were you using Steam? Yes
- Which expansions do you NOT have? /

**Longer Description of Issue:**
When Italy wins the great game for Serbia agains Germany, instead of becoming a dependent state it is puppeted and it's leader replaced by blank. A similar thing happens if they sway France but there the leader stays and the ideologies get mixed. 
**Steps to Reproduce/Cause Issue:**

1.Play as Italy, go democratic socialist (I havent checked if it also happens also with other ideologies)

2.Win the great game against Germany and sway Serbia (and/or France)

**Screenshots:**
![Screenshot (185)](https://user-images.githubusercontent.com/94788365/161302515-ec7ce49a-bcf6-41c9-bc67-47bf5e6b0f1f.png)
![Screenshot (186)](https://user-images.githubusercontent.com/94788365/161302578-c3cfdfd9-e7c4-441f-ab88-c4ee404571ca.png)

**Comment by runelead00** [comment]
Being changed with UB skeleton
