### ISSUE TITLE
Every country - Red arrow effect stuck on screen when playing any nation

### ISSUE THREAD

**Issue by ziksalama** [TNODevs/TNO-Bug-Tracker#796]
**Questions**

- Operating System:
Win10
- HOI4 Version:
Barbarossa v.1.11.9.e52a(6838)
- TNO Version:
TNO v.1.2.1'b' - Toolbox Theory: "Project Ferus"
- Any other mods in use:
none
- Were you using Steam?
yes
- Which expansions do you NOT have?
I have all expansions except tank packs

**Longer Description of Issue:**

When I press play on any nation, red arrows appear and its not possible to make them disappear

**Steps to Reproduce/Cause Issue:**

1. press play

2. arrows appear

**Screenshots:**
![image](https://user-images.githubusercontent.com/47155457/161377403-84fe12ee-e3e7-4392-9233-a5114570a638.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
