### ISSUE TITLE
USA - Wallace Focus Time to Save America

### ISSUE THREAD

**Issue by Blackhawk2914** [TNODevs/TNO-Bug-Tracker#798]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.9.e25a
- TNO Version: 1.2.1a
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**

USA President Wallace focus tree is soft locked due to focuses being set to (The US is **NOT** in a crisis). This was discovered on multiple focuses after completing (The end of the civil rights act) focus.

**Steps to Reproduce/Cause Issue:**

1. Elect George Wallace

2. Complete all focuses in tree up to (The end of the civil rights act)

3. After completing focus you will be soft locked and unable to complete any other focuses

![df943902d12780d1627bd8d2adeed427](https://user-images.githubusercontent.com/103009624/161657958-e840d291-b7bc-4fa3-96fe-707733af4ec6.png)

**Comment by runelead00** [comment]
Fixed on UB
