### ISSUE TITLE
Omsk - Missing events

### ISSUE THREAD

**Issue by CancerousLava** [TNODevs/TNO-Bug-Tracker#799]
**Questions**

- Operating System: Windows 11
- HOI4 Version: Latest
- TNO Version: Latest (Project Ferus)
- Any other mods in use: None
- Were you using Steam? Yes
- Which expansions do you NOT have? All

**Longer Description of Issue:**
A few events missing since TT. Screenshots of said events have been attached below. I have also attached the event file which I added the missing events to when firing them ingame (you are looking at omsksr.28 to omsksr.33). 

The following other 'issue' may be a nitpick, but the event image (GFX_report_event_gas_mask_soldier_poster) for Omsk's epilogue event (omsksr.27) had been replaced with the generic submarine image (GFX_report_event_generic_submarine). This has also been corrected in the file below.

[TNO_Omsk.txt](https://github.com/TNODevs/TNO-Bug-Tracker/files/8417902/TNO_Omsk.txt)

**Steps to Reproduce/Cause Issue:**

1. Look through Omsk event file

**Screenshots:**
- Missing events -
![20220405200033_1](https://user-images.githubusercontent.com/99274223/161750866-ae9470b4-73c9-4205-8e22-5f2f55e20ae8.jpg)
![20220405200044_1](https://user-images.githubusercontent.com/99274223/161750889-f7fe33e1-1804-4920-86ce-55bce2696144.jpg)
![20220405200053_1](https://user-images.githubusercontent.com/99274223/161750899-9680c968-8434-499f-b429-4d21ddc096cd.jpg)
![20220405200102_1](https://user-images.githubusercontent.com/99274223/161750907-a4565536-e5dd-4a34-a3b1-035bc5e302db.jpg)
![20220405200116_1](https://user-images.githubusercontent.com/99274223/161750909-91fa4549-758d-4802-87e1-02a352ffb18b.jpg)
![20220405200136_1](https://user-images.githubusercontent.com/99274223/161751001-64c34745-44fd-4466-82ae-0d1e745a4dcc.jpg)

- Correct image for epilogue event -
![20220405200146_1](https://user-images.githubusercontent.com/99274223/161751868-1269e9dd-2c6f-4829-a0d9-012161fa159f.jpg)

**Comment by runelead00** [comment]
All missing events have now been added with the events pics changed to the ones you suggested for UB
