### ISSUE TITLE
Portrait of Kei Hoashi

### ISSUE THREAD

**Issue by ghost** [TNODevs/TNO-Bug-Tracker#800]
You're using Kei Hoashi

- Operating System:win11
- HOI4 Version:1.11.9
- TNO Version:toolbox
- Any other mods in use:no
- Were you using Steam? yes
- Which expansions do you NOT have? I don't have expansions.
https://cdn.discordapp.com/attachments/928614547932217376/960909467589935214/Portrait_Manchuria_Hoashi_Kei.png
↑
He is Kan Kumagaya ( https://media.discordapp.net/attachments/928614547932217376/960912760991010877/unknown.png?width=479&height=662 )

https://media.discordapp.net/attachments/928614547932217376/960913386848260096/2022-04-05_1.png
↑
Left man is Kei Hoashi in 1962~1965.

**Comment by runelead00** [comment]
Portrait renamed, remains unused in current and future content
