### ISSUE TITLE
WRRF gets annexed by any nation it declares war on

### ISSUE THREAD

**Issue by AzzyIsNotHere** [TNODevs/TNO-Bug-Tracker#804]
### Operating System

Windows 10

### HOI4 version

1.11.10.29f3

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8454776/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8454777/error.log)
[autosave.hoi4](https://www.mediafire.com/file/bnj298euozsdx2y/autosave.hoi4/file)

### Describe the bug

Whenever the WRRF goes to war with another nation, that other nation will somehow annex them instantly. It happened with the Ural League, and it happened with me as Omsk.

### Steps to reproduce / Cause of the issue

1. Have the WRRF declare war on another nation
2. Wait a few in-game days
3. The other nation will annex the WRRF instantly

### Expected behaviour

The war carries on as normal and the WRRF does not kick the bucket

### Additional information

The savegame included is an autosave shortly before the WRRF declares war on me, Omsk. If the war does not happen, you should be able to go into decisions and manually trigger it.

**Comment by masterbobli** [comment]
Fixed in dev build. Thanks for reporting
