### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by BileGH** [TNODevs/TNO-Bug-Tracker#807]
### Operating System

Windows 10

### HOI4 version

v1.11.10.29f3 (1e33)

### TNO version

1.2.1b

### Do you have other mods in use?

N/A

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB

### Describe the bug

I declared war on Orenburg in a Sphere of Influence contest with Ural Military District (I was playing the The Sovereignty of Western Russia) as soon as war starts they win, when clicking Observe, Orenburg now controls all of my prior territories. I was told it is a bug and used the console to annex Orenburg and the Ural League. Later when declaring war on the full of the Ural Military District it happened again, without explanation.

### Steps to reproduce / Cause of the issue

1. Play Vyatka
2. Become SoWR
3. Declare war on any other Russian state/warlord

### Expected behaviour

Actual war or at least explanation to my loss

### Screenshots

https://cdn.discordapp.com/attachments/806276324297539586/962175535918747678/unknown.png

**Comment by runelead00** [comment]
Fixed in Dev Build, hopefully will be hotfixxed sometime soon.
As a bandaid fix, load a save before the war and put "set_var RUS_surrender_limit 0" and "set_flag RUS_war_start 0" into the console and should stop the instant capitulation
