### ISSUE TITLE
Komi (Bukharina) - Automatically loses wars when unified west russia and west siberia

### ISSUE THREAD

**Issue by biden-gameing** [TNODevs/TNO-Bug-Tracker#808]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.21.b

### Do you have other mods in use?

TMO, West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Describe the bug

Komi - Bukharina
automatically loses wars somehow

### Steps to reproduce / Cause of the issue

1. Unify Regionally
2. Declare war
3. you lose the war somehow

### Expected behaviour

i expected a normal war

**Comment by runelead00** [comment]
Fixed in Dev Build, hopefully will be hotfixxed sometime soon.
As a bandaid fix, load a save before the war and put "set_var RUS_surrender_limit 0" and "set_flag RUS_war_start 0" into the console and should stop the instant capitulation
