### ISSUE TITLE
Magadan - Misplaced LOC

### ISSUE THREAD

**Issue by AuH20** [TNODevs/TNO-Bug-Tracker#809]
### HOI4 version

1.11.9

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

No idea what this is or why its here
![Screenshot (7)](https://user-images.githubusercontent.com/103163541/162590539-587ba877-8581-46b8-91cf-78e57031ec7a.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
