### ISSUE TITLE
Irkutsk - can’t elect new premier

### ISSUE THREAD

**Issue by Capybarassing** [TNODevs/TNO-Bug-Tracker#810]
### Operating System

Windows 11

### HOI4 version

1.11.14

### TNO version

1.2.1c

### Do you have other mods in use?

Custom country paths mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Cannot elect new premier to get rid of Yagoda. Reform days is stuck on 0

### Steps to reproduce / Cause of the issue

Pass warlord stage - have 75+ party support - cannot select

### Expected behaviour

Replace Yagoda and free up rest of tree

**Comment by Wizard2020** [comment]
I been told this is a custom country paths issue. The submod hasn't been updated to be compatible with the latest tno update.  I think there was some changes in Irkutsk's files recently and those changes are not in the CCP files.

**Comment by runelead00** [comment]
Going off of what Wizard2020 has said and that it couldn't be replicated in base TNO, closing issue due issue with CCP
