### ISSUE TITLE
Vyatka - Instant Capitulation 

### ISSUE THREAD

**Issue by SheevPalpatine369** [TNODevs/TNO-Bug-Tracker#811]
### Operating System

Windows 11

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

Tool Pack Updated 2021

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Started out at vyatka, formed western Russia. Did the war for the Urals with a unified western Siberia, the offered me all of it and I accepted. We both started the preparations of war for each other, they hit the button to declare war in 20 days, I did not, As soon as the war starts I am instantly annexed.

(later found out same thing happend when i /annex west siberia and /allowdiplo too declare war on the other regional siberian nations)

### Steps to reproduce / Cause of the issue

1. form west russia
2. go to war with a regional (allowdiplo will have the same outcome as going down the event and descions for it)
3. 

### Expected behaviour

The war to start

### Screenshots

![20220409221309_1](https://user-images.githubusercontent.com/103292538/162598301-1aca0677-75e8-4890-8de8-996583b6b705.jpg)
![20220409221315_1](https://user-images.githubusercontent.com/103292538/162598302-51e6acd3-1657-4fb8-8ead-29bbecb21d6f.jpg)
![20220409221400_1](https://user-images.githubusercontent.com/103292538/162598304-ef3e548c-eb11-45e6-8767-a0d5b3ab5fcc.jpg)

### Additional information

Sverdlovsk formed western Siberia. The arrows in the third screenshot I believe are from observing germany, not entirely sure though.

**Comment by runelead00** [comment]
Fixed in Dev Build
