### ISSUE TITLE
Game crashes after unpausing the game after loading save

### ISSUE THREAD

**Issue by pw3n4d** [TNODevs/TNO-Bug-Tracker#813]
### Operating System

Windows 10

### HOI4 version

Barbarossa v1.11.10.29f3

### TNO version

TNO v1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8465873/error.log)
[Uploading OMS_1967_06_11_19_temp.zip…]()

### Describe the crash

The crash happened after loading a save I played days prior.

For example:

I played as Omsk, quit the game, and the next day picked up where I left. I noticed that the bar with the army / the generals was missing. I hit unpause and the game immediately crashed to my desktop. No crash while playing the game, it just runs fine.

This happens every time I start a game, play a bit and as soon as I load the save the army / generals bar is gone and unpausing the game crashes it.

I use a lot of console commands in my games, but no event commands. Used CC:

- pp
- ws
- xp
- cp
- fuel
- research all
- instantconstruction (only paused at 2400h mark)

### Steps to reproduce / Cause of the crash

1. Play a session
2. Load the save of that session
3. Notice the missing army / generals bar
4. Unpause the game
5. CTD

### Additional information

Thank you very much for your help

**Comment by Jimmy0621** [comment]
Can you solve the issue now? I am having the same problem as well.

**Comment by runelead00** [comment]
Probably a bit late, but do you use cloud saves?

**Comment by Jimmy0621** [comment]
@runelead00 Thank you for your response. I think I have solved the issue. Just like what you have mentioned, I changed to use local saves instead of cloud saves and the problem was solved. It seems that the bug was due to cloud saves.

**Comment by runelead00** [comment]
Assuming same issue as #919 and Jimmy above, turn off cloud saves and it should work
