### ISSUE TITLE
Can't Build Pony Tank

### ISSUE THREAD

**Issue by thashepherd** [TNODevs/TNO-Bug-Tracker#814]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1b (09APR hotfix)

### Do you have other mods in use?

Music mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8469081/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8469082/game.log)
[OMO_1966_09_08_16.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8469089/OMO_1966_09_08_16.zip)

### Describe the bug

I'm unable to build the LT-55A Experimental Magic Tank after researching it. It doesn't seem like there are any friendship-based options in the NSB tank designer, either. Feeling a distinct lack of harmony over here.

### Steps to reproduce / Cause of the issue

Research the pony tank tech, as well as the first few NSB tank techs. Fill your heart with the magic of friendship and press 'y' to open the production interface. 

### Expected behaviour

I expect my tanks to be pony-compatible.

**Comment by runelead00** [comment]
Finally fixed
