### ISSUE TITLE
Ordensstaat Burgund - CTD after peace conference during the West Africa crisis

### ISSUE THREAD

**Issue by heckyeahimsimon** [TNODevs/TNO-Bug-Tracker#817]
### Operating System

Windows 10

### HOI4 version

1.11.9.e52a (557a)

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8476624/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8476625/game.log)
[Ironman Ordensstaat Burgund 1.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8476640/Ironman.Ordensstaat.Burgund.1.zip)

### Describe the crash

After a peace conference on April 19, 1970, the game abruptly crashes to desktop, with the "Peace Conference In Progress" text briefly appearing on the screen. No other issues are present, and a quick look into error.log hints at the fact that the crash could be caused by a lack of a winning country in the West Africa crisis.

### Steps to reproduce / Cause of the crash

1. Play as Ordensstaat Burgund.
2. Let Heydrich's Germany fall during the German Civil War.
3. Do not interfere much (If at all.) into the West African Crisis.
4. Play until April 19, 1970 and hopefully, reproduce the crash.

**Comment by runelead00** [comment]
Fixed in Dev Build
