### ISSUE TITLE
Canada - 1967 election with generic conservative leader after liberal victory (when conservatives win in 1963)

### ISSUE THREAD

**Issue by CodemasterTH** [TNODevs/TNO-Bug-Tracker#818]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

This bug only happens if conservatives win the 1963 elections and Diefenbaker becomes leader of Canada (event OFN.20). 
When the liberals win the 1967 elections (event OFN.21), Canada stays conservative with a generic leader instead of having John Turner and the liberals in power.

### Steps to reproduce / Cause of the issue

This issue depends on random choices in the election events, 
1. Choose the conservative option in the 1963 elections (which has a 50% chance). 
2. Choose the liberal option in the 1967 elections (which has 35% chance).
3. The ruling party remains conservative instead of liberal.
4. John Diefenbaker retires and a generic leader appears.

To fix both issues, this part here in event OFN.21:
```
	35 = { #Turner Succession
		news_event = { id = WORLD.18005 days = 1 }
		retire_country_leader = yes
		add_country_leader_role = {
			character = CAN_John_Turner
			promote_leader = yes
			country_leader = {
				expire = "1967.4.8"
				ideology = liberal_democracy_market_liberalism_subtype
				id = -1
			}
		}
	}
```
Could be changed to this:
```
	35 = { #Turner Succession
		news_event = { id = WORLD.18005 days = 1 }
		retire_character = CAN_Lester_B_Pearson
		add_country_leader_role = {
			character = CAN_John_Turner
			promote_leader = yes
			country_leader = {
				expire = "1967.4.8"
				ideology = liberal_democracy_market_liberalism_subtype
				id = -1
			}
		}
		set_politics = {
			ruling_party = liberal_democracy
			last_election = "1967.4.8"
			elections_allowed = yes
		}
	}
```

### Expected behaviour

John Turner becomes country leader with the liberals as ruling party.

**Comment by masterbobli** [comment]
I've already fixed this issue yesterday with the exact same apporach. Thanks for reporting anyways.
