### ISSUE TITLE
Komi - Wargoal on Order of Saint George even when they have already capitulated

### ISSUE THREAD

**Issue by Bloopperi** [TNODevs/TNO-Bug-Tracker#819]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

TNO Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as Komi, even when the Order of Saint George have capitulated you still get a wargoal on them and can't bypass the focuses regarding them.

### Steps to reproduce / Cause of the issue

1. Play as Komi, specifically the communist focus tree.
2. Do the focuses regarding the Order of Saint George after they have already capitulated.

### Expected behaviour

These focuses are supposed to get automatically bypassed.

**Comment by runelead00** [comment]
Fixed For Unfinished Business
