### ISSUE TITLE
USA - LeMays focus tree impossible to finish

### ISSUE THREAD

**Issue by Bloopperi** [TNODevs/TNO-Bug-Tracker#820]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

TNO Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When doing the Post-Wallace LeMay tree and doing the focuses that end with a new civil rights act, the second-to-last focus called "Pull Back Economic Intervention" will cancel when you begin it, and you can't select it again, thus locking you out from signing the new CRA as him.

### Steps to reproduce / Cause of the issue

1. Have Wallace win the 1964 election in USA.
2. Get him impeached.
3. Do the focuses on the right that end up with him signing a new civil rights act.
4. Start the focus "Pull Back Economic Intervention" and the bug will happen.

### Expected behaviour

The focus isn't supposed to cancel automatically.

**Comment by runelead00** [comment]
Fixed for UB
