### ISSUE TITLE
Partisan Republic of Buryatia - Divine Mandate remnant Buryatia refuses to capitulate to Germany

### ISSUE THREAD

**Issue by White-ses-male** [TNODevs/TNO-Bug-Tracker#823]
### Operating System

Windows 8.1

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

Goering Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB

### Describe the bug

The Partisan Republic of Buryatia which spawns if the Divine Mandate of Siberia collapses that controls only the state of Taksimo refuses to capitulate at least to Germany, sorry if this is caused by the Goering submod or is an one time occurance but I guess this might have something to do with their tiny size and non-existent army.

### Steps to reproduce / Cause of the issue

1.Unite East Siberia as the Divine Mandate
2. Make the Divine Mandate collapse
3. Invade the remnants as Germany (or as anyone else?)

### Expected behaviour

They should surrender after taking Taksimo

### Screenshots

![hoi4_362](https://user-images.githubusercontent.com/36083604/163721413-858fe677-4c5b-428a-929b-5a9ec7ea82c7.png)
![hoi4_363](https://user-images.githubusercontent.com/36083604/163721516-1846fb41-1c37-43b4-8d6c-49dc069342ca.png)

**Comment by runelead00** [comment]
No longer an issue on UB
