### ISSUE TITLE
GER - Edit Speer GO4's negotiation mission in the Slave Revolt

### ISSUE THREAD

**Issue by Battletank09** [TNODevs/TNO-Bug-Tracker#825]
### HOI4 version

1.11.10.29f3

### TNO version

1.2.1c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Edit the mission about the Go4 going against Speer's wishes during the slave revolt/preparation to attack Schorner to be when selected continue the days forward before resetting.

### Justifications

As it stands right now, the Go4 going against Speer's wishes with an increasing PP cost to select, yet when selected, will start over at the 14 day mark, whether you selected it at day 13 or day 1, meaning you should wait until the final moment to select it if you wish to maintain fascist Speer. If it was to be edited to continue the timer before resetting with no effect, then it would be okay to select it whenever.

### Screenshots

![Gang Intervention Suggestion](https://user-images.githubusercontent.com/53159932/163853508-2da4a17d-cff5-4fc0-869d-429ea167dd2f.png)

### Additional information

I believe KR's system for Anqing suppressing rebels after his taking over the league of eight provinces is a similar enough.

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
