### ISSUE TITLE
GER - Paraguayan RND Operations should not be there

### ISSUE THREAD

**Issue by Battletank09** [TNODevs/TNO-Bug-Tracker#827]
### Operating System

Windows 10

### HOI4 version

1.11.10.29f3

### TNO version

1.2.1c

### Do you have other mods in use?

The Moe Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

RND operations to Paraguay are available despite the Paraguayan Bush War being over, and also the operations are really only available/viable to do well after the crisis. You are also confusingly and possibly conflicted localization in events during Speer's reign also about the potentially not yet formed RND giving intelligence on the situation. The whole system may need a rework

### Steps to reproduce / Cause of the issue

1.Win the GCW as Speer
2. Form the RND

### Expected behaviour

Remove or Rework the missions (I know not helpful)

### Screenshots

![Paraguay RND Ops Bug](https://user-images.githubusercontent.com/53159932/163854014-431997b5-e196-4fc9-86d9-c0f185e009a3.png)

**Comment by ModdingAccount** [comment]
Fixed in dev build.
