### ISSUE TITLE
All - Crash at Country Selection

### ISSUE THREAD

**Issue by Faraon123456** [TNODevs/TNO-Bug-Tracker#828]
### Operating System

Windows 10 Home

### HOI4 version

1.11.10

### TNO version

The one that was updated at 9th April

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Files

Unfortunately i don't have ones

### Describe the crash

I don't know what's happening but when i choose any country and it loads then the game automatically stops working and fires me back to the desktop

### Steps to reproduce / Cause of the crash

1. Turn the game on
2. Choose any country
3. Click start
4. It works for couple seconds then it crashes

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
