### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Sh3baSpaniel** [TNODevs/TNO-Bug-Tracker#830]
### Operating System

windows 11

### HOI4 version

1.11.10

### TNO version

v1.2.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe the bug

When Guinea wins the west african war, my takagi Japan game crashes

### Steps to reproduce / Cause of the issue

Play Japan, go Takagi, and have Guinea win against cameroon.

### Expected behaviour

just a peace to happen when guinea won and an event pop up

### Screenshots

![image](https://user-images.githubusercontent.com/104095240/164293322-e74f6f80-f663-4121-875f-768ccb867b00.png)

**Comment by runelead00** [comment]
Hopefully fixed in Dev Build
