### ISSUE TITLE
Holy Russian Empire: No Peace Conference After War

### ISSUE THREAD

**Issue by SiegleJ798** [TNODevs/TNO-Bug-Tracker#831]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8524928/game.log)

### Describe the bug

Playing as Holy Russian Empire, got the Midnight Event just before capitulating the last of the eastern russian nations.

War is sitting there with one nation left, completely erased from the map. No peace conference.

### Steps to reproduce / Cause of the issue

1) Play as Komi
2) Try to get Taboristky route
3) Replay a whole bunch to do it right
4) Finally get it, progress to climax of the plot
5) Get Midnight, then capture last city next day
6) Wait for peace conference
7) Wait for new ruler to step up after Taboristky is dead
8) Give up after 2 months, submit bug report

### Expected behaviour

Peace Conference, or Event of new ruler, or something

### Screenshots

![endlesswar](https://user-images.githubusercontent.com/83465551/164314297-b1ed9d9c-f08f-44d0-87f1-8419e58bd64f.png)

**Comment by runelead00** [comment]
No longer issue on Dev Build
