### ISSUE TITLE
All (I think) - The icon of 4 moving arrows appears on screen

### ISSUE THREAD

**Issue by BillTheKill** [TNODevs/TNO-Bug-Tracker#832]
### Operating System

Windows 10

### HOI4 version

1.11.9

### TNO version

v1.2.1

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

4 arrows appear on the center-left part of the screen when I load onto a country.
( the arrows seem to be the same arrows that appear on the German militarist icon or the American senate / state )

### Steps to reproduce / Cause of the issue

1. load a new game
2. select any country
3. load into play country
4. when loaded the 4 arrows appear

### Expected behaviour

the 4 arrows not to appear

### Screenshots

![Screenshot (4)](https://user-images.githubusercontent.com/104154203/164497701-b5567e42-6f6e-4b10-b1bd-b402bc40ac19.png)

### Additional information

not game breaking
happens wether I have DLC off or on

**Comment by runelead00** [comment]
Fixed in Dev Build
