### ISSUE TITLE
Russia - Instant Capitulation 

### ISSUE THREAD

**Issue by hoi4-gamer** [TNODevs/TNO-Bug-Tracker#833]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Bukharina's Russia instantly capitulates to Yeltsin's Russia

### Steps to reproduce / Cause of the issue

1. Play as Bukharina
2. Make Yeltsin win in the east
3. Go to war

### Expected behaviour

Bukharina's Russia will instantly capitulate one in-game hour after the war begins.

### Screenshots

![20220421191314_1](https://user-images.githubusercontent.com/104174896/164567108-de1b621c-ad83-4325-933e-6acc4a5a0e60.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
