### ISSUE TITLE
All of countries in war capitulated yet the war won't end

### ISSUE THREAD

**Issue by miguellousteau** [TNODevs/TNO-Bug-Tracker#834]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

TNO Disable Nukewar

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8549696/game.log)

(cant send save, it says "is not included in the list" even though i changed it to .log, let me know if there is another way to send it)

### Describe the bug

In the mid-late game, china colapsed and fell to many cliques that were in the same faction as Japan.
I was playing as Goering Germany, and as I capitulated Japan and his allies; I got the new puppets in the japanese territory, but some of the old japanese allies such as State of Manchuria, Central Chinese Republic, Republic of China and South China Political Council, even though they ARE capitulated and have no territories, the war won't end.

### Steps to reproduce / Cause of the issue

1. Play Goering Germany and win civil war
2. Do the usual war plans
3. China colapses in war with the Ultranationalist Clique after defeating it (?)
4. Attack Japan, capitulate the chinese cliques and Manchuria
5. Capitulate Japan trough a land invasion

### Expected behaviour

I expected the scrippted peace conference to sort out the war, but it only sorted out Japan and not the Chinese Cliques.

### Screenshots

![unknown](https://user-images.githubusercontent.com/46421347/164977227-456826a4-0f1e-46fa-9520-d54031bbf0c0.png)

(the surrendered countries are the only ones at war)

### Additional information

Although I have a submod, i believe it is not at fault, because before i put the submod mid-save (wanted to avoid nuclear war with burgundy), the same bug happened in Russia while invading it and I had to do console commands so I could annex those countries.

**Comment by runelead00** [comment]
Goering has been skeletonized, no longer an issue in current release
