### ISSUE TITLE
Novosibirsk - Focus gives an incorrect research bonus

### ISSUE THREAD

**Issue by Bloopperi** [TNODevs/TNO-Bug-Tracker#836]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

TNO Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

A focus for Novosibirsk gives you a doctrine research speed bonus, instead of an updated doctrine research cost reduction.

### Steps to reproduce / Cause of the issue

1. Play as Novosibirsk
2. When at the regional stage, choose the focus "Lessons of the Unification Wars"

### Expected behaviour

The focus is supposed to give a research cost reduction instead of a bonus to research speed.

**Comment by runelead00** [comment]
Fixed in Dev Build
