### ISSUE TITLE
Magadan- Glitched raid decision

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#838]
### HOI4 version

1.11.9

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

As Magadan, the decision to raid Amur didn't display correctly. At some point this fixed itself, but I can't remember if it was reloading the game that did it.
![Screenshot (1)](https://user-images.githubusercontent.com/98137316/165971620-d62f9078-5107-437e-b239-54d9cca3dbc0.png)

**Comment by runelead00** [comment]
already on list of known bugs #1211
