### ISSUE TITLE
Turkestan Legion - Missing Finance Minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#840]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

![Screenshot (9)](https://user-images.githubusercontent.com/98137316/165972350-8c5d1078-3c55-4402-b9a1-2f12763f3ad4.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
