### ISSUE TITLE
Ireland- Typoes and grammatical issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#841]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

1. I'm not sure what's best to replace it, but given that Google came back with nothing I assume that "TDanna" is a typo of something relating to Teachta Dala 
![Screenshot (28)](https://user-images.githubusercontent.com/98137316/165973022-4f9d790f-0aca-4a6d-93da-ae69b4e2e303.png)
2, "...de Valera's economic policy, a path of protectionism" should be "...de Valera's economic policy(insert dash or colon) a path of protectionism". "Untangling ourselves from the German web may prove difficult, if we can achieve the Irish economy stands on its own." is grammatically incorrect 
![Screenshot (33)](https://user-images.githubusercontent.com/98137316/165973412-d880b2a0-5580-401b-a260-9f71a90ae375.png)
3. "...solely with Germany from an economic perspective is viable economically." is redundant. 
![Screenshot (34)](https://user-images.githubusercontent.com/98137316/165973724-b6becc86-f42e-4b87-ab2d-245d2a2760c9.png)
4. The second sentence shifts persons from "their" to "our." 
![Screenshot (36)](https://user-images.githubusercontent.com/98137316/165973874-c115012d-9740-4d55-b929-23e23f0637a1.png)
5. Neither of the two commas in the first sentence should be present. 
![Screenshot (37)](https://user-images.githubusercontent.com/98137316/165973990-773c220a-3b77-4f0a-8ac5-1d4db7f5b861.png)
6. There shouldn't be an apostrophe in "1800's." 
![Screenshot (38)](https://user-images.githubusercontent.com/98137316/165974090-d6e358d0-74cc-4f07-933d-21f74a595be9.png)
7. The amount of commas in the third sentences makes it jarring to read. 
![Screenshot (39)](https://user-images.githubusercontent.com/98137316/165974222-ea51e00a-856b-48cb-ba6d-81043db49b21.png)
8. "Economics" shouldn't be capitalized. 
![Screenshot (41)](https://user-images.githubusercontent.com/98137316/165975370-a4599878-be2b-4fe6-92f2-4672120df747.png)
9. The first sentences of the first and third paragraph are written in a way that's confusing, if not outright grammatically incorrect. 
![Screenshot (43)](https://user-images.githubusercontent.com/98137316/165975545-b652ed9b-8c05-40ca-a926-cf634084cab1.png)
10. This is very confusing, as it implies that the credit rating gets raised twice(which it doesn't). 
![Screenshot (44)](https://user-images.githubusercontent.com/98137316/165975634-a771819b-5360-4964-b030-d40835876399.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
