### ISSUE TITLE
Ireland - Confusing text

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#843]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

The "TWEA" isn't referenced by its full name in this event or anything leading up to it, so what it stands for is unknown to the player unless they've by chance played another path where its named in full. For the record, I've got over 700 hours in TNO and have no idea what "TWEA" actually stands for. Presumably the last two letters are "Embargo Act"
![Screenshot (35)](https://user-images.githubusercontent.com/98137316/165976640-94c93957-80a7-4aeb-af49-9d9ab2be8b71.png)

**Comment by runelead00** [comment]
TWEA is mentioned by its full name, the Trading with the Enemy Act of 1917, in the sentence immediately prior to its first use in this event
