### ISSUE TITLE
Ireland- Possible text from Germany

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#844]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

It seems that the "we can now project power" message should be in Germany's event for Ireland rejoining the Pakt, yet it shows up in Ireland's version.
![Screenshot (42)](https://user-images.githubusercontent.com/98137316/165976873-a1c2dade-6906-4126-b9e6-59c39bd5653a.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
