### ISSUE TITLE
NatSoc Norway- Missing Foreign Minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#845]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

![Screenshot (45)](https://user-images.githubusercontent.com/98137316/165977040-cc70d54f-3821-42ae-9477-8e0283043219.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
