### ISSUE TITLE
Ireland - Permanently lose access to command power

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#847]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe the bug

At some point during the first half of 1962, I permanently lost the ability to gain command power due to the combined total of my officer corps(including what appeared to be placeholders for the navy and air force) costing me my max of 200 just to allow them to exist in their roles, which of course can't be altered in TNO. I can't say what made this happen, but if it helps I was able to gain enough cp to fill out the vacant promotions for both my chosen general and field marshal(either 30 or 45) before this happened. It remained until I hit the end of Ireland's content, and couldn't be fixed by using console commands to give myself more cp, as that was blocked by all 200 points being tied up already.

### Steps to reproduce / Cause of the issue

There were no steps-this happened as I played normally.

### Expected behaviour

That I would continue to gain cp at the rate described by mousing over the icon without it being capped to the point of me never gaining any

**Comment by masterbobli** [comment]
I have halved the CP allocation of an advisor. This issue should be resolved.
