### ISSUE TITLE
Bormann's Germany - Missing Ministers and Head of Government

### ISSUE THREAD

**Issue by michaeljssnsklt** [TNODevs/TNO-Bug-Tracker#848]
### Operating System

Windows 10

### HOI4 version

Barbarossa v11.10.29f3(4de7)

### TNO version

1.2.1c - Toolbox theory: project ferus

### Do you have other mods in use?

Only German March Collection and Insignia Collection - Germany and co

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Grossgermanisches Reich.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8594153/Grossgermanisches.Reich.zip)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8594164/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8594165/error.log)

### Describe the bug

Right after Slovakia capitulate to me (I played as Germany post-CW with Bormann as the winner), all of the ministers and the head of govt. of Germany are missing. The ministers are literally removed from the panel, as they don't give their positive bonus towards the country again.

I reload the save several times to 'try to fix' the bug but to no avail.

### Steps to reproduce / Cause of the issue

What I did:
1. Play as Bormann's Germany,
2. Win the civil war,
3. With the post-CW Bormann's focus tree, I go down the right path for a bit (like, half of the tree) before moving on to the left tree to help fight the South Africans
4. I won the war in South Africa
5.  I continue on the right focus tree
6. At the same time, I reintegrate the Netherlands, Denmark, and Czech into the Reich
7. Then I paid 50 PP to get the decision to reintegrate Slovakia into the Reich
8.  Slovakia refused to join the Reich, prompting the invasion of Slovakia
**9.  The Slovak capitulated and at the same time, my ministers are all gone**

I hope you can fix the bug team! Your mod is awesome, thank you so much for the amazing mod that you created!

### Expected behaviour

I lose all of my ministers, alongside their positive effect for my country. I can't repoint them as well, have wait for few years for them to come back but to no avail

### Screenshots

![Uploading Screenshot (125).png…]()

FYI: I have played like 1 year-ish in-game time since I got the bug

### Additional information

That's it, I love your mod! Keep up the good work and thank you! :D Looking forward to hearing back from you!

**Comment by michaeljssnsklt** [comment]
![Screenshot (125)](https://user-images.githubusercontent.com/104651137/166058615-6959332f-fc8d-4b38-bdb9-b240600606b7.png)

Here is the screenshot in case the upper screenshot couldn't be read. Thanks!

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by michaeljssnsklt** [comment]
Thank you runelead00!
