### ISSUE TITLE
All Countries - White Peace message appearing whenever a country capitulates

### ISSUE THREAD

**Issue by jacktomat2** [TNODevs/TNO-Bug-Tracker#849]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

When a war ends instead of just the capitulation message that would normally appear a pop up saying _x_ and _y_ have signed a white peace, x and y being the countries that were at war.

### Steps to reproduce / Cause of the issue

Have a country capitulate and the white peace message should appear.

### Expected behaviour

I expected that only the custom capitulation message would appear.

### Screenshots

![20220415235325_1](https://user-images.githubusercontent.com/104653416/166072336-73d88dd4-f8be-47b5-bcf7-506c9e21183b.jpg)
![20220415235339_1](https://user-images.githubusercontent.com/104653416/166072404-7ed6896b-de2b-4813-89a9-553e4f46d5cd.jpg)

### Additional information

I have tried changing the UI scaling, display mode and screen resolution, however the message still appears.

**Comment by ModdingAccount** [comment]
Can't replicate
