### ISSUE TITLE
All Countries - Army group color unclickable

### ISSUE THREAD

**Issue by jacktomat2** [TNODevs/TNO-Bug-Tracker#850]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

When selecting an army group it would normally be possible to click on the color bar (circled in red) to open up the army group customization menu (circled in yellow) and instead you have to click the army logo in the top right (circled in blue).

### Steps to reproduce / Cause of the issue

Select an army group and try to change the color or logo by clicking on the color bar on the left (circled in red)

### Expected behaviour

Open up the army group customization menu (circled in yellow)

### Screenshots

![Inked20220415232843_1_LI](https://user-images.githubusercontent.com/104653416/166073195-a4b0afc5-b260-4139-8662-9748f87e0475.jpg)

### Additional information

I have tried changing UI scaling, display mode, and resolution but the problem persisted.

**Comment by runelead00** [comment]
Fixed in Dev Build
