### ISSUE TITLE
Russian Warlords - Declare War Focuses only at Peace

### ISSUE THREAD

**Issue by 0-debug** [TNODevs/TNO-Bug-Tracker#851]
### HOI4 version

1.11.9

### TNO version

Apr 9 2022 Update

### Which major expansions do you NOT have?

WTT

### Describe your suggestion

Add the 'Must be at peace' requirement to every russian warlord's war focuses, rather than just a few individual ones.

### Justifications

Every single time I play Vyatka, after defeating the Aryan Brotherhood I'm always randomly hit by a one-two punch of Komi and Samara, even with the former already locked in a war with the Communists to the north. This leaves my forces attacked on a new southern front with **zero** warning and has ruined my games thus far, even when I try to split my forces as it drains my manpower way too fast. It's overall unfun to expect a front to be secure because the enemy is already at war only to suddenly be nonsensically invaded.

**Comment by runelead00** [comment]
Changed in Unfinished Business (Don't need to change anything if there are no more trees to fix :wertrell:)
