### ISSUE TITLE
Global Event - Remove Tokyo OIympics event

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#854]
### HOI4 version

1.11.9

### TNO version

Post April-Fools patch

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe your suggestion

The event for the 1964 Tokyo Olympics shouldn't be in the game anymore, as the Calgary(iirc) event now supplants it.

### Justifications

This is probably already known but seeing as it should've been removed last patch and wasn't I'm filing this just to make sure it's on file somewhere.

**Comment by runelead00** [comment]
The Tokyo is for the Summer Olympics and Calgary is for the Winter Olympics and both occurred the same year until 1992 OTL. There is no reason to remove the Tokyo event.
