### ISSUE TITLE
Bulgaria - Missing security minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#855]
### HOI4 version

1.11.9

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

![Screenshot (88)](https://user-images.githubusercontent.com/98137316/166332438-7e422ff4-b866-450f-b908-8bb834a27c4a.png)

**Comment by runelead00** [comment]
Fixed in Dev Build, filled with Vacant Minister for now
