### ISSUE TITLE
Bormann's Germany - CTD after Peace Conference

### ISSUE THREAD

**Issue by michaeljssnsklt** [TNODevs/TNO-Bug-Tracker#856]
### Operating System

Windows 10

### HOI4 version

Barbarossa v11.10.29f3(4de7)

### TNO version

1.2.1c - Toolbox theory: project ferus

### Do you have other mods in use?

(1) TNO Radio, (2) Insignia Collection - Germany and co, and (3) Helpful naval insignia

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8608894/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8608895/error.log)
[Bormann before peace conference crash.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8608908/Bormann.before.peace.conference.crash.zip)

### Describe the crash

I was playing Bormann's Germany, but then CTD happened when there is a 'calculating peace conference' event. 

I don't know if the crash was only triggered by a certain peace conference or any peace conference, as there are several wars that are going on in my save.

### Steps to reproduce / Cause of the crash

1. I played as Bormann's Germany
2. No 'peace conference issue' happens until like 1969-ish
3. Second Spanish Civil war happens
4. I send volunteers to help the falangist
5. I fought there, but there is a peace conference happening (in my case, I think it's because one of the Spanish factions was defeated) that created a CTD

Note:
1. There is one occasion where the daily autosave timed during the peace conference, in which the game didn't crash. But in my case, there is a peace conference few days after said autosave, in which the game didn't autosave and created CTD as mentioned before
2. As this is my 2nd playthrough of Bormann's Germany, FYI that this kind of crash also happened during my 1st playthrough of Bormann's Germany. The save file is already gone so I can't provide it here, but I remember that the one who triggers the peace conference is the Russian warlords that are fighting each other (the one who fights directly East of Northern Ural, in my case). 

**Seeing this kind of crash always happens during my 1968-1969-ish Bormann's Germany, I assume that the crash happens due to triggered peace conference after certain date, as there are no issues with peace conference during my early game.**

### Screenshots

I couldn't manage to capture the SS during the crash, sorry. But I hope the attached save file can help you recreate the CTD.

### Additional information

That's it, thank you for your effort! One quick question: Should you be able to fix this crash somehow, does it means that I can continue playing with my safe file? 

I love playing the mod and I hope I can continue my current safe file as almost all is going well for my Bormann's Germany haha. Thank you!

**Comment by tkgitno** [comment]
[Fix save.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8633626/Fix.save.zip)
Use this save to continue. The CTD is caused by West Africa peace deals which for some reasons are too performance heavy for the game to handle sometimes.

**Comment by michaeljssnsklt** [comment]
Hi tkgitno, woww thank you for the fix! You guys and gals are awesome :D Time for me to finish playing as Bormann's Germany
