### ISSUE TITLE
Multiple countries - Glitched production units interface

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#857]
### HOI4 version

1.11.9 and 1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

I've seen this happen across at least half the countries i've played since Toolbox Theory came out. It can be fixed simply by closing the interface and re-opening it, so I'm filing it as a loc error instead of a bug as gameplay isn't meaningfully affected.
![Screenshot (87)](https://user-images.githubusercontent.com/98137316/166731617-9d251c36-4265-4a6a-b45b-1a9c355b27c4.png)

**Comment by Scarsoftime** [comment]
Close the window and open it again.
