### ISSUE TITLE
WRRF - Typos and grammatical issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#858]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

Next to last sentence should have the word "were" deleted.
![Screenshot (93)](https://user-images.githubusercontent.com/98137316/166853936-85117aac-49e7-43a8-bd67-c5e806817af0.png)
"Payback" implies revenge-"repayment" is the better choice.
![Screenshot (94)](https://user-images.githubusercontent.com/98137316/166853992-57b757c2-8914-4509-90ec-889966d02fc6.png)
"reforming spikes of governmental inefficiency through promises of reform" is redundant, as "reform" is said twice. "Spikes" serves no purpose, and deleting it makes the sentence much clearer.
![Screenshot (95)](https://user-images.githubusercontent.com/98137316/166854107-784d4f4c-11c7-464c-9305-841af4d3b9ff.png)
A "the" is missing between "Civil War" and "Red Army"
![Screenshot (96)](https://user-images.githubusercontent.com/98137316/166854155-ee00a28c-3b09-42c0-bdda-bf73f2510a9c.png)
In the second sentence, both instances of "these" and the one instance of "it" should be unified into either a singular or plural reference to the supplies, not both.
![Screenshot (97)](https://user-images.githubusercontent.com/98137316/166854243-70ffba6b-577b-4425-bc7f-e729699cfb3a.png)
"may well have served the Soviet Union well and into prosperity" is redundant, and "served into prosperity" isn't a grammatically correct phrasing.
![Screenshot (98)](https://user-images.githubusercontent.com/98137316/166854276-2808b28b-b624-405b-b16d-9053cdf3012e.png)
"capital" shouldn't be capitalized.
![Screenshot (99)](https://user-images.githubusercontent.com/98137316/166854298-41cb3fe5-3c3f-47a3-a763-55907dd94f9f.png)
"vie" doesn't work here, and should be replaced with something like "harbor"
![Screenshot (102)](https://user-images.githubusercontent.com/98137316/166854332-5ba10c2d-660a-4a25-856d-45e5a9218696.png)
"Nevermore were the proletariat going to sit idly by" shifts tenses too quickly, and works better as "Nevermore would the proletariat sit idly by"
![Screenshot (103)](https://user-images.githubusercontent.com/98137316/166854413-1ca76983-d5d8-4e6a-be6f-7df62630dada.png)
"For itself produced" should be "produced for itself"
![Screenshot (106)](https://user-images.githubusercontent.com/98137316/166854491-a93422a5-7aa7-4c2d-8be1-fa32850f2ef5.png)
"ideologic basis" should be "ideological basis"
![Screenshot (107)](https://user-images.githubusercontent.com/98137316/166854525-0025faf0-b30a-49f5-8e9b-2a682453b69b.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
