### ISSUE TITLE
Norway - Does not join Bormann Econmic Sphere or change name

### ISSUE THREAD

**Issue by jacktomat2** [TNODevs/TNO-Bug-Tracker#859]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Bormann Wins the civil war and the hardliners take power in Norway, when they join the Pakt they don't join the German economic Sphere and do not change their name back to reichskommissariat norway.

### Steps to reproduce / Cause of the issue

Have the Hardliners take power in Norway
Have Bormann Win the civil war
Get to the point where norway rejoins the faction
See error

### Expected behaviour

When rejoing the pakt they shoul also rejoin the german sphere and change back to being named reichskommisaiat Norway

### Screenshots

![hoi4_31](https://user-images.githubusercontent.com/104653416/167233574-ae0b7901-2d5e-4da0-af6d-1378d8573157.png)

### Additional information

Thanks :)

**Comment by runelead00** [comment]
This is under Jonas Lie, correct?

**Comment by runelead00** [comment]
Disregard last comment, either way fixed under both the Radicals and Moderates in Norway in dev build
