### ISSUE TITLE
West Indies Federation - Missing Portrait

### ISSUE THREAD

**Issue by jacktomat2** [TNODevs/TNO-Bug-Tracker#860]
### Operating System

Windows 2

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

When the West Indies Federation Goes down the "America's Eleven" path the leader portrait is missing.

### Steps to reproduce / Cause of the issue

Have west indies federation go down the "America's Eleven" path
See missing portrait

### Expected behaviour

The leader should have a portrait

### Screenshots

![hoi4_33](https://user-images.githubusercontent.com/104653416/167275147-ba09940f-80ce-43b5-8f83-5ec6f9519cdb.png)

### Additional information

Thanks :)

**Comment by runelead00** [comment]
Fixed in Dev Build, Grantley Adams was suppose to remain in charge, but the puppeting switched ruling parties
