### ISSUE TITLE
All Countries - Railway Gun division icon missing

### ISSUE THREAD

**Issue by jacktomat2** [TNODevs/TNO-Bug-Tracker#861]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

When selecting a railway gun instead of the division icon it shows the error image

### Steps to reproduce / Cause of the issue

Produce a railway gun
Select the railway gun
See bug

### Expected behaviour

Should show railway gun division icon

### Screenshots

![hoi4_32](https://user-images.githubusercontent.com/104653416/167275670-5f0f3e88-e9d8-4a15-8aa9-6a3a585411e3.png)

### Additional information

Thanks :)

**Comment by runelead00** [comment]
Fixed in Dev Build finally
