### ISSUE TITLE
WRRF -Typos and grammatical issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#862]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

1. No commas are needed in the final sentence.
![Screenshot (117)](https://user-images.githubusercontent.com/98137316/167306444-5bb48005-7192-4537-818a-7b8394b58c7c.png)
2. No comma needed after "but in the end". "Whether or not it is truly useful" should be "whether or not they are truly useful" 
![Screenshot (118)](https://user-images.githubusercontent.com/98137316/167306467-b7863bb5-9ead-42e8-aec6-ab0534e63dd0.png)
3. "on unmarked graves" should be "in unmarked graves" and there doesn't need to be any commas around it. "future to be Grand Marshal" should either be "future Grand Marshal" or "Grand Marshal to be" 
![Screenshot (121)](https://user-images.githubusercontent.com/98137316/167306517-81c83585-4c1f-4017-bde7-c49a7b3cb03b.png)
4. Second to last sentence is too confusing. Should be something like "he spent the last two hours of his life lying under the metal." 
![Screenshot (124)](https://user-images.githubusercontent.com/98137316/167306562-1da355e6-bc4e-4891-b01c-0306136593ae.png)
5. First sentence should be split into two. 
![Screenshot (125)](https://user-images.githubusercontent.com/98137316/167306592-cbe058f1-9a6b-42d8-9d00-07f4cbb9881a.png)
6. "Subdued" doesn't need commas around it. 
![Screenshot (126)](https://user-images.githubusercontent.com/98137316/167306617-1a8c4207-a940-4440-b3b6-6383c418901e.png)
7. Should be "intelligence corps" 
![Screenshot (127)](https://user-images.githubusercontent.com/98137316/167306629-dd995234-b710-472d-b99b-2849e15695d2.png)
8. "With haste, and without delay" is a tautology. 
![Screenshot (128)](https://user-images.githubusercontent.com/98137316/167306650-92c8088c-2bb1-4df3-967a-1ffe3a692893.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
