### ISSUE TITLE
Uruguay - Missing minister portraits

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#864]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

![Screenshot (123)](https://user-images.githubusercontent.com/98137316/167306760-05da2bce-2314-44a8-a237-8959d6aa57c8.png)

**Comment by runelead00** [comment]
If you do not hover over the portrait to get the minister name, we have no idea which portrait is missing
