### ISSUE TITLE
Zhukov's WRRF- Tukhachevsky is a field marshal

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#865]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe the bug

After defeating Plesetsk, Tukhachevsky is now one of my field marshals. I also might have the rest of the Plesetsk generals, but I'm not sure as I don't know which ones come from which district.

### Steps to reproduce / Cause of the issue

1. Play WRRF normally while picking Zhukov as the successor
2. Fight war with Plesetsk
3. Tukhachevsky shows up in my general pool

### Expected behaviour

The man who just fought a war with me isn't working for me with no event

### Screenshots

![Screenshot (131)](https://user-images.githubusercontent.com/98137316/167306876-f55a9656-2d07-4db9-94bc-e7cb970691a8.png)

**Comment by masterbobli** [comment]
That's intentional behavior
