### ISSUE TITLE
Komi - Right Coup 

### ISSUE THREAD

**Issue by jacktomat2** [TNODevs/TNO-Bug-Tracker#866]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing Komi if you get the right to coup the republic once the timer for stabilization runs down it does not load the regional unification tree do to a missing event.

### Steps to reproduce / Cause of the issue

Play Komi
Get the right to coup after the election
stabilize the country
see bug

### Expected behaviour

The new focus tree should load after succesfully stabilizing the country.

### Additional information

Thanks :)

**Comment by ModdingAccount** [comment]
Changed in dev build.
