### ISSUE TITLE
WRRF - Grammatical errors and typos

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#869]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

1.Should be "try the government" not "trial the government"
![Screenshot (132)](https://user-images.githubusercontent.com/98137316/167508600-615cd339-3e60-42c2-8c78-59def39f7840.png)
2."bombings" shouldn't be capitalized.
![Screenshot (133)](https://user-images.githubusercontent.com/98137316/167516911-b5ebfb62-e0ca-4934-9342-d5bfd7c1a436.png)
3. "in our solar system" is redundant, and can be deleted from the sentence without negatively altering it. Additionally, Berezniki is referenced despite no longer existing.
![Screenshot (137)](https://user-images.githubusercontent.com/98137316/167516968-90380cb5-b1ee-4d1d-aaae-4e12bc9fe178.png)
4. "this simply a matter" should be "this is simply a matter" 
![Screenshot (139)](https://user-images.githubusercontent.com/98137316/167517042-ac86ac38-fba5-402f-b723-17e8e22ce7f2.png)
5. In the last sentence, "we will" should be "will we" 
![Screenshot (140)](https://user-images.githubusercontent.com/98137316/167517088-526ccfa4-ac30-4c49-8cf2-90eada6ada3e.png)
6. In the last sentence, "and are" should be "which are" 
![Screenshot (141)](https://user-images.githubusercontent.com/98137316/167517169-1214413e-ecee-4781-a010-3e596205ff18.png)
7. "minorities in the Front's" should just be "minorities in the Front" 
![Screenshot (143)](https://user-images.githubusercontent.com/98137316/167517223-fc500ae1-d3f2-4772-9301-76e221d66854.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
