### ISSUE TITLE
WRRF - Focuses do not give you cores

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#871]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe the bug

The focuses that refer to giving you cores on territories you took in the previous operation do not do that. You gain no cores on either the states you haven't started coring at all or are in the process of coring.

### Steps to reproduce / Cause of the issue

Play normally
take the focuses that say they give you cores
they don't give you cores

### Expected behaviour

That the focuses that say they give me cores give me cores

### Screenshots

![Screenshot (142)](https://user-images.githubusercontent.com/98137316/168407189-c699117e-15af-4859-bff3-b815d334f595.png)

**Comment by runelead00** [comment]
Tooltip Removed in Dev Build
