### ISSUE TITLE
Global event - Typos

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#872]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

![Screenshot (151)](https://user-images.githubusercontent.com/98137316/168407233-a36ef4f0-143e-4b78-92c6-acd93a752c4b.png)
"committed national socialist, member of the NSDAP since its founding" should be " a member of the NSDAP"
"that the grip of National Socialism" should have the "that" removed, as there is an earlier "that" in the sentence modifying that same text.
"Helldorf praised the Aryan" should be "Helldorf praised the Aryans"
"regaining the destiny of the land to the greatness" is neither grammatically correct nor a correctly-structured qoute.
"International Opinion" shouldn't be capitalized.

**Comment by runelead00** [comment]
Fixed in Dev Build
