### ISSUE TITLE
Vlaamse Nationale Staat - Capitulation typo

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#873]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

"return to it" should be "return to them"
![Screenshot (154)](https://user-images.githubusercontent.com/98137316/168407512-4ed4795a-9bf5-4b60-bd13-91cb37c4987e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
