### ISSUE TITLE
Possible Bug - Legionary Georgia and Kaukasien not at war

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#874]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe the bug

Despite breaking away along with the other rebel states, Legionary Georgia either made a peace with Kaukasien or never went to war with it to begin with.

### Steps to reproduce / Cause of the issue

Unsure

### Expected behaviour

That Kaukasien would either reconquer all its seceding territories or lose to them in a failed attempt

### Screenshots

![Screenshot (155)](https://user-images.githubusercontent.com/98137316/168407587-b202b43c-ad0c-4633-9c52-7ec1f4f3e7f4.png)

**Comment by runelead00** [comment]
Kaukasia breakaways now get all their land if they beat the RK
