### ISSUE TITLE
France - Renaming reconquered Burgundian territory

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#875]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe your suggestion

In situations where France joins Germany in invading Burgundy and regains its old territory, said territory should be renamed from its Burgundian names back to the French ones.

### Justifications

This is something any version of France, even the most collaborationist would do.

**Comment by Stormeagle449** [comment]
Added for UB.
