### ISSUE TITLE
Germany - Schörner Coup Goering 

### ISSUE THREAD

**Issue by T3dsch1K1** [TNODevs/TNO-Bug-Tracker#877]
### Operating System

Windows 10

### HOI4 version

1.11.10 

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths; Second West Russian War

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Göring gets couped by Schörner, a wrong leader is displayed as Head of the German State. 

### Steps to reproduce / Cause of the issue

1.Let the Ai play Göring/play as Göring
2.Get couped by Schörner

### Expected behaviour

Goering gets couped by Schörner but Schörner will nor become the leader. 

### Screenshots

![Screenshot (204)](https://user-images.githubusercontent.com/94788365/168464919-7a4ddf86-4f41-4202-ae45-7341196d30a6.png)

**Comment by runelead00** [comment]
Fixed for UB
