### ISSUE TITLE
WRRF - Grammatical errors and typos

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#879]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

1. Should be "so too it will be" 
![Screenshot (167)](https://user-images.githubusercontent.com/98137316/168643326-34bd5353-059c-4268-b165-a2caca2f3de2.png)
2. Should be "economic output" instead of "the economic output", and "country as a whole" instead of "country as whole" 
![Screenshot (168)](https://user-images.githubusercontent.com/98137316/168643462-6180314a-ad3f-4f66-a222-7f14f6e04c51.png)
3. "workers state" should be "workers' state". "Soviet's" doesn't need the apostrophe, and probably shouldn't be capitalized since it refers to the institutions known as soviets(ie councils) instead of the country or its people. 
![Screenshot (169)](https://user-images.githubusercontent.com/98137316/168643669-02bd1c4a-8976-4228-a4d6-73ccab000683.png)
4. "Merely" is redundant. 
![Screenshot (170)](https://user-images.githubusercontent.com/98137316/168643805-350e8baf-2123-4d49-a6fa-def471228a76.png)
5. Should be "to the east lie" 
![Screenshot (171)](https://user-images.githubusercontent.com/98137316/168643890-eb9f24c5-aeee-45e5-850a-471f08955cbd.png)
6. "Administrator" shouldn't be capitalized. 
![Screenshot (172)](https://user-images.githubusercontent.com/98137316/168644001-28cd90a7-8b7d-4c45-91cb-cdfc116a52bd.png)
7. "De-warlordization trials" shouldn't be capitalized in the description. 
![Screenshot (174)](https://user-images.githubusercontent.com/98137316/168644114-5545abcc-6125-4f8a-b7a9-a15fe1f9c7aa.png)
8. Insert "should" in-between "party" and "rule" for consistency. "The Soviet People" has "the" and "people" unnecessarily capitalized. 
![Screenshot (175)](https://user-images.githubusercontent.com/98137316/168644387-5d75e1df-a164-4e99-9f7e-acf7deaf990a.png)
9. Insert "the" in-between "great" and "Lenin." 
![Screenshot (176)](https://user-images.githubusercontent.com/98137316/168644541-e20f1ffa-1f25-49c4-b564-40b74f90f0d4.png)
10. Insert "a" in between "put" and "severe". The capital is referred to as Arkhangelsk despite my having moved to Syktyvkar. 
![Screenshot (177)](https://user-images.githubusercontent.com/98137316/168644730-42517676-ad74-4cc2-9e30-a97916e65f06.png)
11. "the World War" doesn't seem to be a term used anywhere else-should either be "World War One" or "the Great War." 
![Screenshot (178)](https://user-images.githubusercontent.com/98137316/168644860-319eb549-f986-4e2e-b12e-f7ca1d56c264.png)
12. "it" should be inserted in between "Russia" and "is an issue" 
![Screenshot (179)](https://user-images.githubusercontent.com/98137316/168644990-133aee3a-4f88-46fd-92bc-dcae29b1e891.png)
13. "They either" should be "either they." 
![Screenshot (180)](https://user-images.githubusercontent.com/98137316/168645142-41a143a9-de1f-4296-a3de-30685d923de2.png)
14. The last sentence sounds, for lack of a better phrase, less mature than the rest of the paragraph, and thus doesn't seem to fit at all. 
![Screenshot (181)](https://user-images.githubusercontent.com/98137316/168645233-05df1048-ffd2-48ba-8af5-8fefd63ae00f.png)
15. First sentence is grammatically out of order, should be "Many great deeds have been done by the [soldiers/men/men and women] of the Red Army for the people of Russia." ![Screenshot (182)](https://user-images.githubusercontent.com/98137316/168645375-33148b6b-5674-4cad-8b4d-de2b4d74d66c.png)
16. "Dissidenting" isn't a word-should be changed to either "dissident" or "dissenting" 
![Screenshot (183)](https://user-images.githubusercontent.com/98137316/168645507-9682dbf4-e741-4066-b481-3c05e631acf2.png)
17. "Many thousand distant miles" should be altered into something that makes grammatical sense. 
![Screenshot (184)](https://user-images.githubusercontent.com/98137316/168645718-cc43c6a1-78f6-4151-a104-eba0dbd054b5.png)
18. "we will be served well" should be "we will be well served." "Has" should be inserted in between "Ryzhkov" and "drowned." "fellow Soviets" should be altered to something like "fellow Soviet citizens", as its current state is grammatically unclear. 
![Screenshot (185)](https://user-images.githubusercontent.com/98137316/168646040-fd0b5e10-e076-4bd8-ab39-b3d61284195a.png)
19. "we" should be inserted in between "Front" and "will." 
![Screenshot (186)](https://user-images.githubusercontent.com/98137316/168646218-aed48bee-fe8e-4794-ac15-4648930e6b14.png)
20. "vigor enough" should be "enough vigor". "Soviet Red Army" is redundant-should be either "Soviet Army" or "Red Army." 
![Screenshot (187)](https://user-images.githubusercontent.com/98137316/168646395-051f7d79-16bc-4309-b31c-45ca9b24ccea.png)
21. "in orderly fashion" should be "in an orderly fashion".  "her beloved Red Army" should be changed to either "the Union's beloved Red Army" or "Russia's beloved Red Army", as the current sentence structure would have "her" refer to the Reich instead of Russia in the previous sentence. "America and their plenty" is confusing- either "and their plenty" should be deleted or it should be altered to make it more clear why America's wealth(what I presume is being referred to) has been brought up. 
![Screenshot (191)](https://user-images.githubusercontent.com/98137316/168646918-4db14cbb-1701-4365-b833-c91f91d8ab9d.png)
22. Vyatka should be referred to as Rykov. 
![Screenshot (192)](https://user-images.githubusercontent.com/98137316/168646988-a39cc7c4-74bd-4e46-afbc-3006118ce85e.png)

**Comment by runelead00** [comment]
Could you use [ ] in your lists, so issues can be checked off as they are done

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by GeneralLemarc** [comment]
What do you mean by that?

**Comment by runelead00** [comment]
I mean like how in the template it has - [ ] 1. which make a checkbox for each individual loc issues, makes it easier to keep track of what is fixed

**Comment by GeneralLemarc** [comment]
Got it, can do
