### ISSUE TITLE
WRRF - Incorrect policy description

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#880]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

This isn't what the change from acceptable to good pensions does. 
![Screenshot (189)](https://user-images.githubusercontent.com/98137316/168647210-f5fac394-1f48-460d-9fdf-d9bbe8032cd0.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
