### ISSUE TITLE
Kingdom of England, operation Look up spelt incorrectly.

### ISSUE THREAD

**Issue by NotTodayWillJ** [TNODevs/TNO-Bug-Tracker#882]
### HOI4 version

1.11.11

### TNO version

1.2.1c

### Do you have other mods in use?

Thermonuclear war switch, TNO Custom Country Paths, and Brave New World.

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

DOD, WTT, NSB

### List the loc issues below

![image_2022-05-17_184817459](https://user-images.githubusercontent.com/105743365/168877688-6669ae33-45bb-4ec2-aab4-6037fbe3a535.png)

**Comment by runelead00** [comment]
Fix in Dev Build
