### ISSUE TITLE
Tomsk - Typos

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#885]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### List the loc issues below

-[1] "its children" should be "their children" 
![Screenshot (200)](https://user-images.githubusercontent.com/98137316/169581524-fa018916-e1be-4b86-a7fa-688c0283fd80.png)
-[2] either change "the worker" to "the workers" or "their help" to "his help"
![Screenshot (201)](https://user-images.githubusercontent.com/98137316/169581796-cf4ec5aa-8c7e-4192-96ff-a482ff651203.png)

**Comment by runelead00** [comment]
Fixed for UB
