### ISSUE TITLE
Oman - Dhofar rebellion not spawned

### ISSUE THREAD

**Issue by PeaJam** [TNODevs/TNO-Bug-Tracker#886]
### Operating System

Windows 10

### HOI4 version

v1.11.11.2ebo(8e75)

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country paths, Radio TNO, Last waltz of Europe

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

DOD, WTT, MTG, LAR, NSB

### Files

[BRY_1970_11_04_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8747486/BRY_1970_11_04_01.zip)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8747488/game.log)

### Describe the bug

I saved after the Imamate split from Oman but before the Dhofar rebellion spawned, after coming back to the save the next day, the Dhofar rebellion never spawned

### Steps to reproduce / Cause of the issue

Load save and let it run

### Expected behaviour

For the rebellion to spawn

### Additional information

There was an update to _a_ hoi4 mod, but IDK if it's one that's active in this case.

**Comment by PeaJam** [comment]
Also I did ask the Custom Country paths devs, they said it wasn't them.

**Comment by runelead00** [comment]
Can't Reproduce, sometimes saving between certain events can break them for no clear reason, have similar happen with GCW
