### ISSUE TITLE
JAP - Investigating the Dai Li Conspiracy stucks in Chongqing

### ISSUE THREAD

**Issue by to1a** [TNODevs/TNO-Bug-Tracker#887]
### Operating System

Windows 10 x64

### HOI4 version

1.11.11.2eb0

### TNO version

1.2.1b

### Do you have other mods in use?

No except localisation mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB

### Describe the bug

Play as JAP, Investigating the Dai Li Conspiracy, after choosing investigating Chongqing twice (japdlc.100; just to get enough clue), sometimes nothing happens after event _The Investigation Begins_ (japdlc.102).

### Steps to reproduce / Cause of the issue

In TNO_Japan_DLC.txt, the normal trigger sequence is japdlc.102->chi.6669 ->japdlc.103/105; but in TNO_china.txt, chi.6669 is set {fire_only_once= yes}, means trigger chain will break in chi.6669 if fire japdlc.102 the second time, and whole Dai Li Conspiracy will be lock in this point. Simply delete fire_only_once should work, or just remove chi.6669 so that the event won't disturb CHI player (it's strange for JAP player to repeat same investigatings too, but usually can't get full clue if do only once per investigating).

### Expected behaviour

Fire relavant events after event _The Investigation Begins_ (japdlc.102.a)

**Comment by GeneralLemarc** [comment]
Speaking from experience, this run is fucked. Hope you have an earlier save.

**Comment by runelead00** [comment]
Fixed in Dev Build for UB
