### ISSUE TITLE
JAP - some possible error about percentage

### ISSUE THREAD

**Issue by to1a** [TNODevs/TNO-Bug-Tracker#888]
### Operating System

Windows 10 x64

### HOI4 version

1.11.11.2eb0

### TNO version

1.2.1b

### Do you have other mods in use?

No except localisation mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB

### Describe the bug

A possible mistake between integer and percentage

### Steps to reproduce / Cause of the issue

In events\TNO_JapanPM_Kaya.txt, line 2005;
![image](https://user-images.githubusercontent.com/25876544/169667532-31c88508-7913-4c84-a605-68c543fc13be.png)
But JAP_hardliner_influence should be a percentage variable in [0,1] ? For example, in common\scripted\TNO_JAP_scripted_effects.txt;
![image](https://user-images.githubusercontent.com/25876544/169667700-365adfcf-845d-43b5-89f3-13dbf6353275.png)
Same issue on JAP_hardliner_approval

### Expected behaviour

A clarify between integer and percentage

### Screenshots

![image](https://user-images.githubusercontent.com/25876544/169667495-6e354f72-8a88-415e-9fab-2a5a55c7aaa9.png)
It shows japkaya_tree_two.64 after japkaya_tree_two.59 , which means it succeed on check_variable = { JAP_hardliner_influence < 15 }: And in panel shows JAP hardliner influence is 22.0%

**Comment by runelead00** [comment]
Fixed for UB
