### ISSUE TITLE
Vyatka capitulating instantly fighting Siberia

### ISSUE THREAD

**Issue by Saarb97** [TNODevs/TNO-Bug-Tracker#889]
Edit:
I just saw that this issue was already reported and fixed at the dev version.

### Operating System

Windows 10

### HOI4 version

1.11.11

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[VYT_1969_04_09_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8749583/VYT_1969_04_09_01.zip)
The save above is a few days before it happens

### Describe the bug

I immediately capitulate as Sovereignty of Western Russia the second the West Siberian Republic declares war on me.

### Steps to reproduce / Cause of the issue

1.Normal start as Vladimir III, Won the wars against the communists to the north and the other guys to the west.
2.The conservatives won the election (middle of the political focus tree).
3.the siberian republic got all the Urals and annexed them.
4.I prepared for war, did all the decisions.
5.They declare war before i manage to, and i get immediately capitulated and lose the game.

### Expected behaviour

Not be capitulated for no reason

### Screenshots

![tno](https://user-images.githubusercontent.com/46871417/169699276-67f34f92-dc82-4014-835d-0b0c4b477d4c.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
