### ISSUE TITLE
Generalbezirk Lettland - Missing description of an event

### ISSUE THREAD

**Issue by Ajeje30** [TNODevs/TNO-Bug-Tracker#89]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.1
- TNO Version: 1.1.2a
- Any other mods in use: No
- Were you using Steam? No
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Missing description of event "The Waffen-SS question" for Generalbezirk Lettland

**Steps to Reproduce/Cause Issue:**

1. Play as Reichskommissariat Ostland

2. At the civil war stay with Otto-Heinrich Drechsler

3. Complete the focus "The question of the Waffen-SS"

**Screenshots:**
![Screenshot (80)](https://user-images.githubusercontent.com/82140538/130325663-fd26329a-da72-40a6-a4de-300f4acd9d37.png)
![Screenshot (79)](https://user-images.githubusercontent.com/82140538/130325685-5f439993-95e5-48f9-acf5-e946fbf720e8.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
