### ISSUE TITLE
Ust-Sysolsk - Defensive war suddenly ends with my annexation

### ISSUE THREAD

**Issue by Voker57** [TNODevs/TNO-Bug-Tracker#891]
### Operating System

linux

### HOI4 version

1.11.10.29f3 (4de7)

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

save: [case.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8772703/case.zip)

### Describe the bug

Load save, at the end of day US gets annexed. War seems to be going fine and it's defensive.

### Steps to reproduce / Cause of the issue

1. Load save
2. Wait until the end of day

### Expected behaviour

Game continues

**Comment by runelead00** [comment]
Fixed in Dev Build
