### ISSUE TITLE
Tyumen- The Third's Last Breath Typo

### ISSUE THREAD

**Issue by Jaggedmallard** [TNODevs/TNO-Bug-Tracker#892]
### HOI4 version

1.11.9

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB

### Files

![image](https://user-images.githubusercontent.com/4210279/170781459-b858eb6e-b889-465a-b8af-ce9aeb0c571b.png)

### List the loc issues below

- 
![image](https://user-images.githubusercontent.com/4210279/170781514-7360fe7b-5d74-4446-8092-913b426237f1.png)
1: The line "Those who enter canlt help" should be "those who enter can't help"

**Comment by runelead00** [comment]
Fixed for UB
