### ISSUE TITLE
Iberia - Loc Issues

### ISSUE THREAD

**Issue by Somentus** [TNODevs/TNO-Bug-Tracker#893]
### HOI4 version

1.11.11

### TNO version

Update: 9 Apr @ 7:55pm

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

- [x] 1. "once both halves of the ever-bickering Union has access to information": "has access" should be "have access" ![image](https://user-images.githubusercontent.com/15087153/170789655-040be9fd-942b-416c-8aa6-66c7ed668244.png)
- [x] 2. "we have to options" should be "we have two options". ![image](https://user-images.githubusercontent.com/15087153/170789655-040be9fd-942b-416c-8aa6-66c7ed668244.png)

**Comment by runelead00** [comment]
Fixed for UB
