### ISSUE TITLE
GUI tt update handling

### ISSUE THREAD

**Issue by CGS-CGS** [TNODevs/TNO-Bug-Tracker#894]
### HOI4 version

1.11.*

### TNO version

1.2.1.a

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe your suggestion

Currently energy grid GUI element uses TT, which is updated inside 'button_enabled' trigger. This means it is checked every tick. I suggest moving the effects for calculations inside `on_actions` daily (and specific actions which alter power if momentary update is needed).

### Justifications

This trigger has the biggest CPU usage out of all elements of mod's GUI.

### Screenshots

![image](https://user-images.githubusercontent.com/85555172/171146516-157edba5-1232-48b8-936b-58917d3698e0.png)

**Comment by Scarsoftime** [comment]
The code used in this window is a workaround to produce a list of the player's owned states and how much grid power they produce.
![image](https://user-images.githubusercontent.com/81546578/171197856-6236123c-7e85-4750-acfb-93f8307e2249.png)

I have deduced the most effective way of reducing the toll of this to performance, which is by only having it update when the amount of the country's grid power changes by attaching it as a dirty variable to the interface.

Thanks for bringing this to my attention
