### ISSUE TITLE
England Targeted decisions

### ISSUE THREAD

**Issue by CGS-CGS** [TNODevs/TNO-Bug-Tracker#895]
### HOI4 version

1.11.*

### TNO version

1.2.1.a

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe your suggestion

In `ENG_DECCAT_ENGGOOGLEMAPS` decisions add `allowed` trigger for countries, which can use this system. Currently, the decision is checked for every present nation. In addition, move state ID from `target_tirgger` to `targets `.

### Justifications

These decisions bleed a lot of CPU, as they are 20-100 times more costly than any other targeted decision.

### Screenshots

![image](https://user-images.githubusercontent.com/85555172/171178122-d5135487-6c70-4d59-81fb-e15bcdb32930.png)

**Comment by Scarsoftime** [comment]
I think I just had a stroke reading the decision code behind this, and it's not as simple as adding an `allowed = { }` check. It's so much worse.

Thanks for bringing this to my attention.
