### ISSUE TITLE
Kingdom of England (HMMLR Pre War Tree) - Generals not retiring after assasination

### ISSUE THREAD

**Issue by Brendan1121** [TNODevs/TNO-Bug-Tracker#896]
### Operating System

Windows 11

### HOI4 version

Latest

### TNO version

Latest

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Describe the bug

Playing HMMLR pre war tree, assassinated General Frank Cassels however still available as a commander.

### Steps to reproduce / Cause of the issue

I am not a scripter, but I assume just properly adding a script to retire him upon successfully assassinating him and other generals?

### Expected behaviour

Cassels to retire as a commander

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by Brendan1121** [comment]
Cheers mate
