### ISSUE TITLE
The Universe/ Psyop

### ISSUE THREAD

**Issue by TNOcrusader** [TNODevs/TNO-Bug-Tracker#898]
### HOI4 version

1.11.7

### TNO version

The Isaac Decks expansionpack

### Describe your suggestion

I suggest that the discord moderation team should grow a pair. This tomfoolery has been going on for way too long. They're all sussy bakas that should immediately be vote out. One example of their despicable behaviour is the team banning of Einstein He was a shear gigachad compared to the soyboy discord moderator team and you will all punished by god ( Pink Panzer) when the day of judgement comes. It has come to my attention that The discord moderators have a serious case of power tripping they all suckgloryhole penis in the back of their local sextoy shop.

### Justifications

Read or a discord mod

### Screenshots

![download](https://user-images.githubusercontent.com/106701682/171482893-634e1719-f68c-41a3-9628-ac866131beee.jpg)

### Additional information

#FreeEinstein
![download](https://user-images.githubusercontent.com/106701682/171483117-d5329d10-4987-4c38-bde6-998f0971c43f.jpg)
I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls

**Comment by FMGIV** [comment]
lol

**Comment by TNOcrusader** [comment]
I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur walls I'm in ur balls I'm in ur balls 

I'm in ur balls 
I'm in ur balls 
I'm in ur balls I'm in ur balls I'm in ur balls I'm in ur balls I'm in ur balls
