### ISSUE TITLE
West indies annex guyana

### ISSUE THREAD

**Issue by londegel** [TNODevs/TNO-Bug-Tracker#9]
**Questions**

- Operating System: windows
- HOI4 Version: most recent as of August 3 2021
- TNO Version: most recent as of August 3 2021
- Any other mods in use: terra e libertad, the tno radio mod, the ma mod.
- Were you using Steam? Yes
- Which expansions do you NOT have? Man the guns, battle for the bosphorus

**Longer Description of Issue:**
The west indies annexed Guyana after they rebelled
**Steps to Reproduce/Cause Issue:**

1. Wait for the Guyana war

2. Do nothing
3. if the West indies are the ones to capitulate Guyana, they will keep it. The obvious fix would be foe every ofn member to be able to release Guyana,but idk if that's possible.

etc...

**Screenshots:**
https://www.reddit.com/r/TNOmod/comments/ox1wng/whose_memories_are_these/?utm_medium=android_app&utm_source=share

**Comment by masterbobli** [comment]
Fixed in dev build.
