### ISSUE TITLE
German Reich - Liberation of Scandinavia is impossible

### ISSUE THREAD

**Issue by ikar307** [TNODevs/TNO-Bug-Tracker#904]
### Operating System

Windows 10

### HOI4 version

1.11.11.2

### TNO version

1,2,1

### Do you have other mods in use?

ONLY Russian translation (Last days of Russia)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

So i playing for reich with Goering and for the focus Liberation of Scandinavia I need Norway captured, but there is no focus for capturing a Norway, but in the same time I can continue completing focuses like Norwegian remilitarization and that focus about Norwegian divisions because in the conditions for performing these tricks there is such an thing "Reichskommissariat Scandinavia exists", although it appeared in general after the victory over Finland and has nothing to do with Norway, lol.
Also, when i finish focuses Norwegian remilitarization and Norwegian divisions nothing happens.

### Steps to reproduce / Cause of the issue

1. Playing for Goering
2. Complete plan O and capture all countries from plan A
3. Trying take focus Liberation on Scandinavia

### Expected behaviour

Capturing Norway by focus or decision, which would unlock the ability to advance further in the focus tree.

### Additional information

Save game: https://drive.google.com/file/d/1InfF4r62hrWWIhwQMEBaG6hY39QXMEas/view?usp=sharing

**Comment by runelead00** [comment]
Can't find any cause this behavior to occur, Norway should have gotten a leader if its tree progressed normally, which did not occur for some reason.
