### ISSUE TITLE
USA - Outgoing US president reaction to leaving office + interaction with incoming president

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#906]
### HOI4 version

1.11.1

### TNO version

1.2.1

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe your suggestion

There should be post-election/transition flavor events included for when a new US president has been elected.

As an example, you would have your 1964 elected president reacting to them leaving as president in either a positive mood if elected for 2 terms or in a negative mood if voted out in their first term.

In addition there should be flavor events of interactions between the leaving president with the incoming president and how friendly or hostile it would be between the two during the transition period.

E.g. Friendly: RFK welcoming and wishing Henry Jackson well as his term as president, while Jackson thanking RFK with what he has done for the country and for the NPP - C.

Hostile: Both Barry Goldwater and Francis Yockey forced to have to meet for a transition press talk (it doesn't go well), or Barry calling up all election officials, trying to see if the votes for Yockey were fraudulent only to be constantly told no they are all valid and showing him having a nervous breakdown when he finally accepts that Yockey will become president.

### Justifications

I always thought post-election, there didn't seem much of reaction events to what the leaving president was thinking/reacting while on the way out and how they would react to the incoming president who would succeed them.

I think adding these events would help to enhance the post-election period, as there would be a multitude of unique interactions between the two presidents ranging from friendly to hostile.

**Comment by runelead00** [comment]
USA team has plans to add some more flavor to transitions in Unfinished Business and I believe that will fill this need.
