### ISSUE TITLE
Ordensstaat Burgund - "Build Camps" does not do anything

### ISSUE THREAD

**Issue by C3bolla** [TNODevs/TNO-Bug-Tracker#907]
### Operating System

Windows 10

### HOI4 version

1.11.12.82b4(345a)

### TNO version

1.2.1c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the special tab the Ordensstaat Burgund you cvan manage each province and you have some options like improving infrastructure, expand cities and so on, all options seems to work just fine except "Build camps" which says that adds a "weapon factory" in the region at cost of skilled workers but when is done nothing happens and it doesn't add a factory. Since the mod system for factories works different than in vanilla and it depends on GDP, it makes it impossible to develop a strong industry with this nation because it's GDP goes down and you can't build the factories with it's special option.

### Steps to reproduce / Cause of the issue

1. Select Ordenstaaat Burgund
2. Play until decision "Build Camps" is available.

### Expected behaviour

What I expected to happen is to have a military factory added every time I clicked the button, but I only wasted workers since it didn't work

### Screenshots

![eadf90ae3a6f60ec78de39125867814b](https://user-images.githubusercontent.com/66539403/173124925-f921c478-2b05-4b09-9813-61006c61c28d.png)

**Comment by runelead00** [comment]
Fixed in Dev Build, was suppose to give a free PU but that was broken due to several factors
