### ISSUE TITLE
Ordensstaat Burgundy - End of West African War results in crash

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#908]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8884853/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8884855/game.log)

### Describe the crash

When the West African War is ending, the game crashes and returns to the home screen

### Steps to reproduce / Cause of the crash

1. Run this game in the zip file [CRASH.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8884872/CRASH.zip)
2. Letting the game run until the West African Alliance defeats the Cameroon.
3. Peace conference process should result in the game crashing

**Comment by tkgitno** [comment]
Should be fixed WAC is a nightmare to deal with
