### ISSUE TITLE
USA - Unclear of effects of losing Madagascar Civil War

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#909]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Files

[ZIP.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/8894484/ZIP.zip)

### Describe the bug

When the Madagascar Government loses you suffer an effect that is not clear what it does, just that it effects Liberia, Uruguay and Venezuela.

### Steps to reproduce / Cause of the issue

1. Have Madagascar Civil Happen
2. Let your faction lose (Madagascar Government)
3. Effects should show with no real clear effects of losing (MADAGASKAR.5)

### Expected behaviour

A negative effect of the US losing this proxy war

### Screenshots

![Screenshot (133)](https://user-images.githubusercontent.com/84231463/173445329-5c708dca-d8dd-45d6-b171-9d836af954d0.png)

**Comment by ModdingAccount** [comment]
Fixed in dev build.
