### ISSUE TITLE
Ordensstaat Burgund - Missing description of a decision

### ISSUE THREAD

**Issue by Ajeje30** [TNODevs/TNO-Bug-Tracker#91]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.1
- TNO Version: 1.1.2a
- Any other mods in use: No
- Were you using Steam? No
- Which expansions do you NOT have? None

**Longer Description of Issue:**
Missing description of a decision to cancel Globalplan Kondor

**Steps to Reproduce/Cause Issue:**

1. Start Globalplan Kondor

**Screenshots:**
![Screenshot (81)](https://user-images.githubusercontent.com/82140538/130325983-711728aa-610e-426a-81c8-752871aaf3a6.png)

**Comment by Scarsoftime** [comment]
This mechanic is entirely reworked on the Developer's build.
