### ISSUE TITLE
ENG - Free England - Enoch Powell not becoming Security Minister following NDL victory and completion of accompanying focus

### ISSUE THREAD

**Issue by Jargner** [TNODevs/TNO-Bug-Tracker#910]
### Operating System

Windows 11

### HOI4 version

1.11.12.82b4

### TNO version

1.2.1c

### Do you have other mods in use?

Zoom in Further

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Following completion of a "A Meeting with Powell" focus after NDL victory, Enoch Powell does not become Security Minister and Security Minister slot remains empty and unfillable.

### Steps to reproduce / Cause of the issue

1, Mouse over Security Minister's icon following completion of "A Meeting with Powell" focus.

### Expected behaviour

Following completion of "A Meeting with Powell" focus, Enoch Powell becomes Security Minister.

**Comment by runelead00** [comment]
Fixed for UB
