### ISSUE TITLE
Germany - Finish military assistance, generals not coming back.

### ISSUE THREAD

**Issue by Jerjudo10** [TNODevs/TNO-Bug-Tracker#911]
### Operating System

Windows 10

### HOI4 version

Barbarossa v1.11.12.82b4 

### TNO version

v1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as Germany, in my case winning the civil war with Bormann, i did all the decisions to get Europe back under German control. When negotiating to get the Fins back into the Einheitspakt, you have the option of sending them 2 generals Which are supposed to come back in 6 months as stated by Event popup. Well after waiting for over 2 years they are still not back. 

### Steps to reproduce / Cause of the issue

Play as Germany.
Win civil war as Bormann.
Do the entire dicision tree untill you can try and get Finland into the Einheitspakt.
First is the matter of the military negotiations, agree to sent 2 generals.
Wait untill you get said generals back. (after 2.5 years that still has not happened)

### Expected behaviour

I exprected the 2 generals to come back after 6 months.

**Comment by ralseigaming** [comment]
I'm not a dev but I'm pretty sure it's because there's a typo in the code of the event, supposedly it triggers event bormann.1621 but that's the Brauchitchtadt Treaty event... You could just type "event bormann.1620" in the console to trigger the right event and get ur generals back though

**Comment by runelead00** [comment]
Fixed in UB, ralseigaming was correct in that bormann.1603 was triggering the wrong event
