### ISSUE TITLE
Divine Mandate - Focuses in superregional tree don't depend on the religion you chose

### ISSUE THREAD

**Issue by Bloopperi** [TNODevs/TNO-Bug-Tracker#913]
### Operating System

Windows 10

### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

TNO Modifier Icons

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

On the superregional focus tree for the Divine Mandate, based on the focuses names and descriptions, the focuses in the center should logically only be available if you complete the focus on top of them, for example you should be able to do "A Godly Russia" only if you completed "A Kingdom Of God On Earth" and so on, but instead ingame you can just do all the focuses at the same time.

Also the focuses on the "A Kingdom Of God On Earth" and "An Ear To The Faithless" aren't connected to the focuses on top of them by lines in the tree.

### Steps to reproduce / Cause of the issue

1. Play as the Divine Mandate
2. Get to the superregional focus tree

### Expected behaviour

The other focuses should have been locked off, but you can just complete all of them at once.

**Comment by runelead00** [comment]
Changed for UB
