### ISSUE TITLE
Crash at Country Selection

### ISSUE THREAD

**Issue by notrandomman** [TNODevs/TNO-Bug-Tracker#914]
### Operating System

Windows 10

### HOI4 version

1.11.7 (i  am not sure) 

### TNO version

newwst (from 9 april)

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Files

Idk

### Describe the crash

Every time i select country game starts and after 2 secounds it crash. I tried to re install mod several times but i still can't play. I don't know what i should do.

### Steps to reproduce / Cause of the crash

Idk

### Screenshots

I dont have any

### Additional information

Please help

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
