### ISSUE TITLE
Collab England - British Sphere Not Appearing in Cold War GUI

### ISSUE THREAD

**Issue by Danieluis78** [TNODevs/TNO-Bug-Tracker#916]
### Operating System

Windows 10

### HOI4 version

Newest

### TNO version

Newest

### Do you have other mods in use?

Radio TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB

### Files

![Screenshot (400)](https://user-images.githubusercontent.com/95912277/175583657-2cdf3bb7-bdbe-4090-ac5f-b31291a54c16.png)
![Screenshot (399)](https://user-images.githubusercontent.com/95912277/175584728-7899b3fb-8436-4136-bef5-c7663048b4a7.png)

### Describe the GFX issue

The British Economic Sphere does not appear in the Cold War GIU screen.
Alright mate so I went Thatcher right' (GO MAGGIE!) and I went to see in the Cold War GIU to see who we were beating "right' ", and it the economic Sphere isn't there. Bit of Bullocks, innit. 

### Steps to reproduce / Cause of the issue

1 Play Thatcher and win the Atlantic Battleground
2 Get Economic Sphere (Fuck the Yanks and the Krauts!)
3 Click on Cold War Gui
4 See problem
5 Cry and Shit yourself

### Expected behaviour

Fix it at some point. Or don't (Who the fucks plays Thatcher?) :thatchernice:

### Screenshots

Economic Sphere not appearing in Cold War Gui Screen (The World Map up right next to the economics tab)

### Additional information

Don't mind be ruining the economy :thatchernice:

**Comment by runelead00** [comment]
Can't reproduce, possibly fixed in most recent version
