### ISSUE TITLE
Game Crashes Immediately after loading

### ISSUE THREAD

**Issue by insertcreativnamehere** [TNODevs/TNO-Bug-Tracker#917]
### Operating System

Windows 11

### HOI4 version

1.11.12.82b4 (22d5)

### TNO version

1.11.12.82b4 (345a)

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8986017/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8986018/error.log)

### Describe the crash

Well it begins and the intro to the nation you play as appears then 1 second later it freezes and crashes via automatically exiting out of hoi4

### Steps to reproduce / Cause of the crash

I simply entered in hoi4 with the TNO mod and nothing else its just that after a few seconds after starting the mod it crashes hoi4

**Comment by VictorWeikum** [comment]
Same with Windows 10 and all the expansions present

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
