### ISSUE TITLE
No peace deal in west african war

### ISSUE THREAD

**Issue by miguellousteau** [TNODevs/TNO-Bug-Tracker#918]
### Operating System

Windows 10

### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Describe the bug

West African War starts as usual around 1964, where Free France and its allies fall pretty quickly, but instead of being annex temporarly, Free France just capitulates and does not go to a peace deal, and because of that the war never ends even though france has no territory.

 
(This is not the first time I see this bug happening btw)

### Steps to reproduce / Cause of the issue

1- Play USA
2- Help Free France
3- They die
4- No peace deal

### Expected behaviour

I expected for there to be a peace deal with france but it never happened

### Screenshots

![africa](https://user-images.githubusercontent.com/46421347/175832067-bc8b23c7-6ea6-47d8-ba42-ad792e7a9bbb.png)

**Comment by Chance70000** [comment]
I have the opposite, but similar, problem. The West African War won't end for me. On my playthrough the French beat back the Cameroonian African State (CAS). The CAS, being defeated, fell into a civil war in which it is in a constant state of losing, then the game reseting the civil war from the beginning (firing the same starting event every time). The victorious African states then lose all the land they won, it is given back to the CAS, and the civil war starts anew. It is 1971 and everything is still this way. I'd like my helicopter troops back.

**Comment by runelead00** [comment]
Fixed in Dev Build by Curvinghawk
