### ISSUE TITLE
Omsk - Loading Save Causes Army View to Be Missing, Then Crash

### ISSUE THREAD

**Issue by AkumuNyaaaa** [TNODevs/TNO-Bug-Tracker#919]
### Operating System

Windows 11

### HOI4 version

Barbarossa v1.11.12

### TNO version

I don't know what version is TNO is but most likely latest

### Do you have other mods in use?

https://imgur.com/a/CZBURCG

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987498/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987499/message.log)
[pdxmp.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987500/pdxmp.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987501/posted_commands.log)
[random.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987502/random.log)
[random_1.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987503/random_1.log)
[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987504/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987505/sent_commands.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987506/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987507/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987508/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987509/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987510/time.log)
[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987511/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987512/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987513/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987514/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987515/executed_commands.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987516/game.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8987517/graphics.log)

### Describe the bug

Basically, I played the Omsk like I start it on 1 Jan 1962 to 26 Jun 1962, when I save the game because I have to go to sleeps then the next day I have to play HOI4 again and click on save game to play then suddenly It's general and field marshal disappeared then I press space, I ended up crashed, this mod could be problem when it would be bugs

### Steps to reproduce / Cause of the issue

1. Play as Omsk
2. Start on national focus tree, border wars and what so ever also I don't know how to do a economies lol
3. I save the game before I go to sleeps
4. Next day, I go in the mod and suddenly I saw general and field marshal disappears, later when I click play then I got crash.

### Expected behaviour

I told you on describe the bug, I got crash and I don't really know what did I just do with mod.

### Screenshots

![20220626214611_1](https://user-images.githubusercontent.com/47501699/175833386-a9179115-a35d-4c16-a816-6f393d9a3dc4.jpg)

### Additional information

I played TNO with 7 submods before I got crash and general and field marshal disappears.

**Comment by AkumuNyaaaa** [comment]
Also I use most submod for Brave New World and this is what general gui look like

**Comment by AkumuNyaaaa** [comment]
![image](https://user-images.githubusercontent.com/47501699/175833786-61a85012-6bf9-4b02-81b2-fc95a8fb78d0.png)

**Comment by runelead00** [comment]
Probably a bit late, but do you use cloud saves?

**Comment by AkumuNyaaaa** [comment]
Of course runelead00

**Comment by runelead00** [comment]
Cloud Saves do not work with TNO, only local saves. Turn them off and saves should work fine

**Comment by AkumuNyaaaa** [comment]
Thanks
