### ISSUE TITLE
GER - Speerist Germany unable to integrate Kaukasien

### ISSUE THREAD

**Issue by Jargner** [TNODevs/TNO-Bug-Tracker#920]
### Operating System

Windows 11

### HOI4 version

1.11.12.82b4

### TNO version

1.2.1c

### Do you have other mods in use?

Zoom in Further

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as Speerist Germany with Kingdom of Kaukasia, neither a focus path nor decision is selectable to deal with Kaukasien.

### Steps to reproduce / Cause of the issue

1. Win GCW as Speer.
2. Complete RK reintegration up until Kaukasien.
3. See that no further path is possible, stopping at Kaukasien after selecting "The Kaukasian Question" decision.

### Expected behaviour

I expect a focus path or decision that will allow reintegration of Kaukasien.

**Comment by Stormeagle449** [comment]
Should be fixed in the current version.
