### ISSUE TITLE
All Countries - Add more division template icons

### ISSUE THREAD

**Issue by sheesh187** [TNODevs/TNO-Bug-Tracker#921]
### HOI4 version

1.11.12

### TNO version

1.2.1c

### Which major expansions do you NOT have?

LAR, NSB

### Describe your suggestion

Add more icons for custom division templates, especially the icons of the brigades already in the game.

### Justifications

This would allow players to more control over their units. Especially, this would allow players to differentiate special forces divisions with air assault in them.

### Screenshots

![Armor](https://user-images.githubusercontent.com/76636566/176343665-f93a92b2-2e4c-4568-b6ed-155087a3f05d.png)
![Mountaineers](https://user-images.githubusercontent.com/76636566/176343667-4a072489-2d96-41a5-842e-95b883fd77e4.png)
![Elite Infantry](https://user-images.githubusercontent.com/76636566/176343670-3da843a3-3d52-4af7-9ecd-de211659f599.png)
![Marines](https://user-images.githubusercontent.com/76636566/176343674-aaca268e-74ed-4c07-bba6-02ffce3077f7.png)

These all look the same on the map.

**Comment by runelead00** [comment]
You can just click on the division icon to swap it will a set of icons like in vanilla
