### ISSUE TITLE
Tax Breaks for Business focus under President LeMay will lock up by getting in a loop that it can't go because a bill is being debated in Congress but the bill can't leave Congress because the focus won't go through.

### ISSUE THREAD

**Issue by Weipergur** [TNODevs/TNO-Bug-Tracker#922]
### Operating System

Windows 10 Home, 21H2

### HOI4 version

1.11.12.82b4(0126)

### TNO version

1.2.1c

### Do you have other mods in use?

Operation Deep Freeze, Custom 

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game - Copy.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9033755/game.-.Copy.log)
[error - Copy.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9033756/error.-.Copy.log)

### Describe the bug

It's like it can't tell that the focus and bill are supposed to go together.

### Steps to reproduce / Cause of the issue

1. Get to LeMay Presidency 
2. Go down the right path 
3. Attempt to do the Tax Breaks for Business focus
4. Bug appears

### Expected behaviour

I expected that sense it is the bill being brought to the senate that it would work.

### Screenshots

![20220702163836_1](https://user-images.githubusercontent.com/108594105/177017110-f918b848-687b-4d94-b391-1ccae9816d61.jpg)
![20220702163828_1](https://user-images.githubusercontent.com/108594105/177017111-660b070f-2e88-46c9-b2c0-1a477ae547bf.jpg)

**Comment by runelead00** [comment]
Fixed for UB

**Comment by Weipergur** [comment]
UB?

**Comment by runelead00** [comment]
Unfinished Business or TT3, the next planned update

**Comment by Weipergur** [comment]
Thank you
