### ISSUE TITLE
USA - Rework Margaret Chase Smith military focuses in a Zhdanov/Guangdong like mechanic way

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#923]
### HOI4 version

1.11.7

### TNO version

1.2.1

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe your suggestion

I think for MCS "Defend Our Nation" path, she should have a focus tree that's about the Skunk Works, where you specifically research and develop technologically advance aircraft, to demonstrate America's air power to counteract the Japanese and Germans. 

From there it's like Zhdanov's Experimental Weaponry projects, but you are able to develop the aircraft, like Guangdong electronic development mechanics does.
You can spend PP on researching all of the aircraft ideas to get them into a feasible scenario to develop them, but you can only select one to be constructed for the military every two years, with the level of development will result in either success and a new aircraft for you to manufacture, or failure and a loss of time and money on what you put in. 
Success would be achieved through two scales, risky launch and risk-free launch, where the level of development will go into either section depending on amount.
(D)evelopment between 60% - 85% will be risky launch where chance of (F)ailure is at 50% and goes down every 5%, 
D:60-64% → F:50%, D:65-69% → F:45%, D:70-74% → F:40%, D:75-79% → F:35%, D:80-84% → F:30%. 
If Development is 85% and above it is guaranteed to succeed but will be much more costly and development mechanics can lead to having possible delays where its not possible to get to 85% as a result.
Additional focuses can help to increase development, reduce failure and other can reduce cost, increase time of work and 

The level of scale of production depends on the unique aircraft, some can be mass produced , others can only produce them in singular units, for the military. 

Aircrafts that I would nominate are as follows: (You can find them on Found And Explained on YouTube for more information)
LTV XC-142, a V/STOL transporter 
Bell X-22, like above but has ducted fans instead of propellers.
Lockheed Cl-346, another VTOL but would have been used as a fighter jet
Convair Submersible Seaplane, a seaplane which could travel underwater for anti-submarine warfare
Convair F2Y Sea Dart, a seaplane fighter aircraft
Northrop YB-49, the pre-B-2 stealth bomber
Boeing 2707, Americas version of Concorde as a spy plane.
747 Cruise Missile Carrier
North American XB-70 Valkyrie, a supersonic nuclear strategic bomber
Lockheed YF-12, a Blackbird model Fighter Jet
North American XF-108 Rapier, a long-range interceptor aircraft
PAR-WIG, America's version of a Ekranoplan
ICARUS rocket, a DropShip to transport troops to the battlefield in 45 minutes.
Martin P6M SeaMaster, a strategic bomber flying boat, the navy's equivalent to the B-52
Lockheed Cl-1201, (THE BIG ONE, this "mother ship" would transport around 7000 troops, military equipment, or fighter aircraft. This would be the mother of all aircraft and inspire fear and awe from every nation, with Germany and Japan petrified of this aircraft.)

There would be flavor events describing the awe, amazement, wonder and fear (from enemies) when these projects are completed and being put into use as a display of power.

### Justifications

This I feel would make MCS Defend Our Nation path more interesting to pursue as I feel the current focus trees in it aren't as interesting as they're only do research or productivity of weapons. I feel this would make it interesting as it takes MCS with her being the leader of the Nationalist Party's war hawkish faction and the alliance with military-industrial complex and producing weapons against Germany and Japan and cranks it up to 11 of their theme of power projections through its military force.

**Comment by runelead00** [comment]
Any change to MCS will likely involve a full overhaul of her mechanics, story, and focuses. No suggestion on her current content will be considered or implemented until that point
