### ISSUE TITLE
All Nations - Arrows will not disappear

### ISSUE THREAD

**Issue by TheSilentKing15** [TNODevs/TNO-Bug-Tracker#924]
### Operating System

Windows 10

### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

Whenever the game starts, no matter what nation I choose, there are the 'look here' red arrows in the screen. They are always visible and do not go away. I have run the mod without submods and they remain. 

### Steps to reproduce / Cause of the issue

1. Load Mod
2. Start game
3. There it is

### Expected behaviour

I did not expect those arrows to be there

### Screenshots

![image](https://user-images.githubusercontent.com/65817460/177588168-40a6773e-143c-4636-b5a7-bf619cce0b02.png)

### Additional information

I have the game's revolution set to 3840X2160

**Comment by runelead00** [comment]
Fixed in Dev Build, push the GUI button for the Senate above the map modes in the bottom right (or respective button if playing other nations with this issue) to get arrows to disappear for now
