### ISSUE TITLE
Wales constantly tries to buy Scotland's ships and dockyards

### ISSUE THREAD

**Issue by VictorWeikum** [TNODevs/TNO-Bug-Tracker#925]
### Operating System

Windows 11

### HOI4 version

1.11.12.82b4 (345a)

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9059185/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9059186/error.log)
[Uploading Ironman Republic of Scotland TNO.zip…]()

### Describe the bug

In the begginning of the game (year 1963) Wales starts to offer Scotland to buy Scottish ships and dockyards. If I refuse, they repeat their offer again next day a few times, and then from time to time (probably need political power to do so). I haven't tried to accept it, because I play Ironman and don't want to spoil the game.

### Steps to reproduce / Cause of the issue

Play as Scotland and just wait for message to appear

### Expected behaviour

Expected the message not to appear again

**Comment by runelead00** [comment]
I've added a time to reenable on this decision so it takes 180 days to reenable if Wales gets rejected which should be a good amount
