### ISSUE TITLE
Scotland can use focuses during the English civil war that it shouldn't

### ISSUE THREAD

**Issue by VictorWeikum** [TNODevs/TNO-Bug-Tracker#926]
### Operating System

Windows 11

### HOI4 version

1.11.12.82b4 (345a)

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Ironman Republic of Scotland TNO.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9059203/Ironman.Republic.of.Scotland.TNO.zip)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9059206/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9059207/game.log)

### Describe the bug

After SNP victory, there's a number of focuses you shouldn't be able to activate or continue to been active when there's civil war in England. But you can.

### Steps to reproduce / Cause of the issue

1. Play as Scotland
2. Lead SNP to victory in 1962 elections
3. Wait for Her Majesty's Most Loyal Resistence to rise up against the Nazi puppets
4. Try to activate any political focus that says in it's terms that there shouldn't be a civil war in England

### Expected behaviour

The focuses must auto cancel and aren't able to be activated

### Screenshots

![20220707024611_1](https://user-images.githubusercontent.com/10763931/177661143-e10b635c-e3e2-4af5-a129-7267537bc8c7.jpg)
![20220707024725_1](https://user-images.githubusercontent.com/10763931/177661145-022d8993-1858-4791-ab8a-5b9bfb94c34c.jpg)

**Comment by runelead00** [comment]
Fixed in Dev Build
