### ISSUE TITLE
USA as LBJ - American malaise not changed to ray of hope after "the great society" focus 

### ISSUE THREAD

**Issue by kinggoldcatter** [TNODevs/TNO-Bug-Tracker#927]
### Operating System

windows 10

### HOI4 version

1.11.12.82b4

### TNO version

1.2.1c

### Do you have other mods in use?

TNO But Everyone has Sunglasses

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9060041/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9060042/game.log)

### Describe the bug

Despite the focus "The Great Society" saying it would replace the spirit "American malaise" with ray of hope it did not 

### Steps to reproduce / Cause of the issue

1.play as usa 
2.get lbj elected 
3.do the focus until "The great society"
4.complete the focus

### Expected behaviour

the spirit "american malaise" should be replaced with "ray of hope" 

### Screenshots

![image](https://user-images.githubusercontent.com/67169647/177682356-67a7dd4a-5219-4b8d-b7cd-7bfb5cc7d90f.png)
![image](https://user-images.githubusercontent.com/67169647/177682374-771e884b-023e-438a-979b-22ae2f0b9c0f.png)

**Comment by runelead00** [comment]
The Great Society should only improve you to American Malaise, the scripted effect just looks different after completion because it's looking at your current spirit and not the spirit you were taking the focus which isn't something we can change, everything is working properly
