### ISSUE TITLE
All Countries, Event in Goering's Germany after GCW causes crash

### ISSUE THREAD

**Issue by Kommonwealth** [TNODevs/TNO-Bug-Tracker#928]
### Operating System

Arch Linux

### HOI4 version

1.11.12 

### TNO version

1.2.1b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9080077/error.log)

### Describe the crash

The game crashes shortly after Goering wins the GCW, when the event 'pencil pushing admiral' fires and then is selected. If on maximum speed, an hour or two of in game time may pass before the crash occurs. 

### Steps to reproduce / Cause of the crash

1. Win the GCW as Goering
2. Wait for the event 'pencil pushing admiral' to appear
3. Select the option for the event, or let it time out
4. Crash will occur

### Additional information

Looking through old crash reports it seems that this issue has appeared several times, with a previous fix not seeming to work.
Inside the error log, the final errors point to line 877 in TNO_Germany_scripted_effects.txt, which deals with changing the nationality of Goering's characters back to German. These lines have been present at the end of the logs for the two games in which the crash occurred (the other being with the Goering Expanded mod) so I assume this has something to do with the crash.

**Comment by runelead00** [comment]
Pretty sure the crash has been resolved for UB, the Pencil Pusher Admiral event tries to add the wrong idea for Puttkamer's officer corps role (GER_karljesko_von_puttkamer instead of GER_KarlJesko_von_Puttkamer_navy_chief), which I believe to be the cause of your crash.
