### ISSUE TITLE
N/Y. Crash on startup, Map Definition Error

### ISSUE THREAD

**Issue by Ginnaret** [TNODevs/TNO-Bug-Tracker#929]
### Operating System

Windows 10

### HOI4 version

1.11.12.82b4 (22d5)

### TNO version

1.2.1

### Do you have other mods in use?

none

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9084092/error.log)

### Describe the crash

When I try to launch the game, near the end of loading game crashes with the message "Map Definition Error", and closes after few seconds.
I've tried reinstalling HoI4, the mod, launching in the windowed mode etc etc. nothing worked. 

### Steps to reproduce / Cause of the crash

1. Clean install HoI4 with all the dlc
2. Install the nexus mod latest version
3. Try to launch the game

**Comment by Ginnaret** [comment]
Rolling back the game versions all to way to 1.11.5 changed nothing, still the same error and crash

**Comment by Stormeagle449** [comment]
Can only recommend the fixes found here: #961
