### ISSUE TITLE
All - "The Burgundian Crisis" event typo

### ISSUE THREAD

**Issue by CaeruleumBlau** [TNODevs/TNO-Bug-Tracker#931]
### HOI4 version

v1.11.12.82b4

### TNO version

v1.2.1c

### Do you have other mods in use?

Toolpakt: Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, MTG, NSB

### List the loc issues below

On the 2nd last line of the event the word "dragging" is missing the letter "g". 
![image](https://user-images.githubusercontent.com/70009596/178989227-b476e136-4d90-4ccf-aa6e-d7effba559ea.png)

**Comment by runelead00** [comment]
Fixed for UB
