### ISSUE TITLE
Crashes after selecting a country (loading, then crash)

### ISSUE THREAD

**Issue by MisanthropeZ** [TNODevs/TNO-Bug-Tracker#932]
### Operating System

Windows 10

### HOI4 version

Barbarossa v1.11.12.82b4 (40db)

### TNO version

v.1.2.1c

### Do you have other mods in use?

russian localization (it crashes anyway even without ru localization)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9126591/error.log)

### Describe the crash

just crash

### Steps to reproduce / Cause of the crash

1. run mod
2. select a country
3. wait for load
4. 1 sec later after load - crash

### Additional information

wtf, maybe because of my pc

fx 8350; radeon hd 7850; 16 gb ddr3

**Comment by yungbusch17** [comment]
same thing happened to me

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed
