### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Rookie1654** [TNODevs/TNO-Bug-Tracker#933]
### Operating System

windows 11

### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

my TNO mod wont load in the launcher and i dont know why 

### Steps to reproduce / Cause of the issue

i dont think i can  

### Expected behaviour

when i launch the mod it just goes into vanilla hoi4

### Screenshots

![image](https://user-images.githubusercontent.com/109444097/179379585-5453552e-c435-4d0b-8100-57fb215e03b8.png)

### Additional information

and also i had an issue where the nazi germany leaders wouldn't work and had random people instead (i will try to get a screenshot of it)

**Comment by runelead00** [comment]
At a Certain Point we moved to a new steam workshop page, are you still subscribed to the old page? It looks like you might be subscribed to both the new and old pages, given that two TNOs appear in your screen shot. If so, please uninstall the old one and try again

**Comment by Rookie1654** [comment]
im sure that i only have the new steam workshop page

i think the problem might be that my launcher isn't working the way it
should be do you know how i can reset my launcher?

**Comment by Rookie1654** [comment]
im sure that i only have the new steam workshop page 

i think the problem might be that my launcher isn't working the way it should be do you know how i can reset my launcher?
