### ISSUE TITLE
Zlatoust Peace Deal Crash

### ISSUE THREAD

**Issue by Mvlysebe1992** [TNODevs/TNO-Bug-Tracker#935]
### Operating System

Windows 11

### HOI4 version

1.11.12.82b4

### TNO version

1.2.1c -> latest (Project Ferrus)

### Do you have other mods in use?

Custom country Paths, TNOMusic, Tooltip for tno, iconTNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9135353/error.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9135354/system.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9135367/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9135369/game.log)

### Describe the crash

1. start
2. at 2 october 1969 around 23PM is crashes

### Steps to reproduce / Cause of the crash

1. start
2. at 2 october 1969 around 23PM is crashes

### Additional information

if you want a link to my savegame msg me

**Comment by runelead00** [comment]
This sounds like it could be a peace deal bug, were there any wars that were near completion at the time of the crash?

**Comment by Mvlysebe1992** [comment]
Russian unification war between zatloust (as ural republic, they beat tyumen) and samara. That war was close to an end.
Rest is civil war in congo and angola, and the war in the horn of africa Ethiopia vs... but those last wars where not close to end.

**Comment by Mvlysebe1992** [comment]
ok found the solution i went manual fixing the war in siberia and there was no crash, thanks for the feedback

**Comment by Uncurlhalo** [comment]
I think I'm expeirencing this same CTD. The Ural league loses and it immediately crashes.
