### ISSUE TITLE
Provisionary Central Siberian Revolutionary Council Focus Tree Doctrine Bonus

### ISSUE THREAD

**Issue by SjobenritGaming2414** [TNODevs/TNO-Bug-Tracker#937]
### Operating System

windows 10

### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

(dont need one)

### Describe the bug

In the military tree of the PRC on regional stage, you can get a bonus for researching the ''combined operations'' or the ''strategic theorem'' doctrine. However, it is only a research bonus. With No Step Back you need to get army experience to unlock doctrines. The bonus is a research bonus and thus does not do anything

### Steps to reproduce / Cause of the issue

>Play PRC 
>go to regional stage
>second focus of the army tree, which is the second right. 

### Expected behaviour

I would get a 75% bonus on my doctrine

### Screenshots

![image](https://user-images.githubusercontent.com/80208277/180180928-d3601809-b3d8-4d5d-a917-f69d7d8e93e8.png)
![image](https://user-images.githubusercontent.com/80208277/180180960-f40e4581-7fda-41a2-aa21-8caae7a4bf66.png)

**Comment by SjobenritGaming2414** [comment]
edit: 
![image](https://user-images.githubusercontent.com/80208277/180187234-30143290-1aa8-4be9-9f99-2837395380a9.png)
last focus (fighter or bomber) has the same issue

**Comment by runelead00** [comment]
Fixed on UB
