### ISSUE TITLE
Coaliation Government of Angola - Can't complete any focus because contry is still considered "Capitulated"

### ISSUE THREAD

**Issue by ToddHoward96** [TNODevs/TNO-Bug-Tracker#939]
### Operating System

Windows 11

### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9194519/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9194520/game.log)

### Describe the bug

The Coaliation Government of Angola can't complete any of their focus because they are "Not available when your country has capitulated"

### Steps to reproduce / Cause of the issue

1: Win total OFN victory in SAW
2: Establish the 3 separate OFN Mandates
3: Open the "Coaliation Government of Angola" Focus Tree
4: Check any of the focuses

### Expected behaviour

For the AI (or me) to complete their focus tree and Decolonize

### Screenshots

![image](https://user-images.githubusercontent.com/66421825/181146591-ca0c8286-be41-44a6-9621-9324d3c823e3.png)

### Additional information

Already tried waiting for weeks, restarting the game, disabled the custom country paths mod, replaying the SAW victory and multiple console commands. This only applies to Angola and all other mandates can sucessfully complete their tree and decolonize.

**Comment by ezekielraiden** [comment]
Just wanted to boost this. I have also run into this problem. I don't have any of the expansions, just the base HOI4. If relevant,

**Comment by ModdingAccount** [comment]
Fixed in Dev Build.
