### ISSUE TITLE
[Bug]: Iberia and Cameroon - Economic Sphere Leadership Bug

### ISSUE THREAD

**Issue by Abdulmejid0Bun** [TNODevs/TNO-Bug-Tracker#940]
### Operating System

Windows 10

### HOI4 version

1.11

### TNO version

1.2

### Do you have other mods in use?

Custom Country Paths Mod, Cheat Pack++

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Well, Iberia went down their Germany path in their foreign policy tree and when they joined the Zollverein the game claims that they are the leader of this and there are no members. (Same issue can be seen with Cameroon.)

### Steps to reproduce / Cause of the issue

1. Iberia goes down their AuthDem or Despot path
2. Sides with Germany
3. Joins the Zollverein

### Expected behaviour

For their icon to disappear and just be a member like anyone else

### Screenshots

![image](https://user-images.githubusercontent.com/109768576/181344537-545bd327-7ad8-460b-be8c-22d803729022.png)
![](https://cdn.discordapp.com/attachments/806276324297539586/1001914914148978698/unknown.png)
![image](https://user-images.githubusercontent.com/109768576/181345227-82f53bfd-83fa-4ec1-b83c-35666b7f5c52.png)

**Comment by runelead00** [comment]
Both should be fixed as of current release
