### ISSUE TITLE
Siberian black army - "checks on assembly authority" reform unavailable

### ISSUE THREAD

**Issue by jossebul** [TNODevs/TNO-Bug-Tracker#941]
### Operating System

Windows 11

### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe the bug

in the libsoc path for the siberian black army, you get to choose between "we will stand shoulder to shoulder" or "freedom must be protected" national focuses ; "we will stand shoulder to shoulder" says 'reform "checks on assembly authority" will become available' after finishing the focus, the reform does appear but it is disabled (the box is grayed out, but not the name, it also doesn't say "unavailable" like other, well, unavailable resolutions)

### Steps to reproduce / Cause of the issue

1. play siberian black army
2. get to late game with the libsoc path
3. choose "we will stand shoulder to shoulder" in the national focus tree
4. check the general assembly reform

### Expected behaviour

either enable the reform or add something explaining what is needed to enable it

### Screenshots

![image](https://user-images.githubusercontent.com/50722846/182047678-0462dbd3-03de-4dac-a0d7-a3c1ef0d580e.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
