### ISSUE TITLE
Norway - Two Max-Josef Pemsels

### ISSUE THREAD

**Issue by SirJaguar** [TNODevs/TNO-Bug-Tracker#942]
### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### List the loc issues below

Two Max-Josef Pemsels
![hoi4_4BLppkCzqf](https://user-images.githubusercontent.com/51899758/182517669-88eea298-ec69-422f-aae6-e08ddda3af38.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
