### ISSUE TITLE
Russian Empire (Vyatka) - Huge debt after Focus

### ISSUE THREAD

**Issue by Max-Kreuzer** [TNODevs/TNO-Bug-Tracker#945]
### Operating System

Windows 10

### HOI4 version

1.11.12

### TNO version

1.2.1a

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Upon completing the Focus 'Adress the Uranium Problem' i receive a debt of 150 billion USD instead of 150 million USD 

### Steps to reproduce / Cause of the issue

1. Go to the focus tree 
2. complete the focus 'Adress the Uranium Problem'
3. and instead of the stated 150 million USD debt increase you receive a 150 billion USD debt increase

### Expected behaviour

Instead of getting fucked by a 150 billion USD debt i would like to only get a 150 million USD debt. As it is stated in the Focus

### Screenshots

![20220813233337_1](https://user-images.githubusercontent.com/103140591/184511532-2729bed4-787e-47ef-83c8-40ce95439b9e.jpg)
![20220813233344_1](https://user-images.githubusercontent.com/103140591/184511535-b541c039-7493-49ea-b20b-1651f7011a92.jpg)

**Comment by runelead00** [comment]
This shouldn't cause this problem in current TNO release, but it would if your files hadn't updated properly from before TT. You might want to reinstall TNO since it look like something bigger is broken as well, since those icons also shouldn't be missing
