### ISSUE TITLE
Germany - Can't create kugelpanzer divisions

### ISSUE THREAD

**Issue by MmNicecream** [TNODevs/TNO-Bug-Tracker#946]
### Operating System

Windows 10

### HOI4 version

1.11.10

### TNO version

1.2.1c

### Do you have other mods in use?

TNO Music Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as Germany, it's impossible to add kugelpanzers to division templates, even after producing kugelpanzer equipment.

### Steps to reproduce / Cause of the issue

1: Produce kugelpanzer equipment
2: Look under armor tab in the division designer
3: See that kugelpanzer battalions aren't available

### Expected behaviour

After producing kugelpanzer equipment, Germany should be able to assign kugelpanzers to divisions

### Additional information

I looked through the mod's files and it seems like this is a result of changes for NSB. Prior to the release of NSB, kugelpanzer equipment was called kugelpanzer_equipment_1. With NSB, though, the name has been changed to kugelpanzer_chassis_1. However, kugelpanzer battalions still call for kugelpanzer_equipment_1, not kugelpanzer_chassis_1. As a result, the ability to create kugelpanzer battalions never unlocks, as the battalions are looking for the wrong equipment type.

Replacing "need = { kugelpanzer_equipment_1 }" with "need = { kugelpanzer_chassis_1 }" in the kugelpanzer unit file fixed this for me.

**Comment by runelead00** [comment]
Fixed in Dev Build
