### ISSUE TITLE
All Countries / Crashing the game on load

### ISSUE THREAD

**Issue by Joaojose123** [TNODevs/TNO-Bug-Tracker#947]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384004/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384005/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384006/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384007/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384008/executed_commands.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384009/game.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384010/graphics.log)
[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384011/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384012/message.log)
[pdxmp.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384013/pdxmp.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384014/posted_commands.log)
[random.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384016/random.log)
[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384017/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384018/sent_commands.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384019/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384020/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384021/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384022/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9384023/time.log)

### Describe the crash

when you are loading in the map the game crashes and go to the desktop

### Steps to reproduce / Cause of the crash

1.Open the game
2.pick a nation
3.Crash.

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed

**Comment by Joaojose123** [comment]
its fixed?

Em qui., 1 de set. de 2022 01:03, runelead00 ***@***.***>
escreveu:
