### ISSUE TITLE
KOM - Electing Serov, the game crashed

### ISSUE THREAD

**Issue by shiki-boh** [TNODevs/TNO-Bug-Tracker#948]
### Operating System

Monterey 12.4

### HOI4 version

1.11.12

### TNO version

1.2.1c

### Do you have other mods in use?

Custom Country Paths, Radio TNO, Last Waltz Expanded, Japanese mod

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9386918/logs.zip)
[KOM_1966_01_10_01.hoi4.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9386919/KOM_1966_01_10_01.hoi4.zip)

### Describe the crash

After the event "Serov Triumphant!"(KOM.385), the game crashed.

### Steps to reproduce / Cause of the crash

1. As Komi, choose the right wing
2. Elect Komi
3. Crash

**Comment by runelead00** [comment]
Should no longer be an issue in dev build, Komi's elections have had some major changes and the broken minister looks to be fixed.
