### ISSUE TITLE
FEN - Various minor localisation issues

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#949]
### HOI4 version

1.11.7

### TNO version

1.2.1.c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### List the loc issues below

![Screenshot (1143)](https://user-images.githubusercontent.com/33550299/185796686-b23beead-2cdd-419a-aae4-453165cdb1a3.png)
![Screenshot (1141)](https://user-images.githubusercontent.com/33550299/185796694-cc9f5613-363b-4683-8534-a6f495438d44.png)
![Screenshot (1133)](https://user-images.githubusercontent.com/33550299/185796710-b7208d19-7465-4bb1-b3bf-2caa781f628c.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
