### ISSUE TITLE
SCO - Various Issues

### ISSUE THREAD

**Issue by Kennelly1** [TNODevs/TNO-Bug-Tracker#951]
### Operating System

Windows 10

### HOI4 version

1.11.7

### TNO version

1.2.1.c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB

### Describe the bug

![Screenshot (1158)](https://user-images.githubusercontent.com/33550299/186017304-d2b9ba38-6887-4ee7-92df-a7230ca93793.png)
I don't have such a national spirit

![Screenshot (1156)](https://user-images.githubusercontent.com/33550299/186017417-b0a90d71-8eb2-441e-9e1d-c80c1fbf9f08.png)
McIntyre is no longer PM (William Wolfe is), so both this and the corresponding FEN event need fixing

![Screenshot (1154)](https://user-images.githubusercontent.com/33550299/186017597-6301d9a9-e9a8-4091-bf77-57b5fcd96764.png)
Non-localized flag

![Screenshot (1157)](https://user-images.githubusercontent.com/33550299/186017692-d4b596ab-3481-47e4-8de9-9d0e8e2e01c9.png)
"Republic of Scotland asked Halliday"

![Screenshot (1153)](https://user-images.githubusercontent.com/33550299/186017838-9f355181-8cd3-4bd5-9b29-e563e33fd587.png)
I think the second and fourth "Campbell" should be "Wolfe"

![Screenshot (1152)](https://user-images.githubusercontent.com/33550299/186018042-9557336f-6c5a-49be-9c1a-116060744bd8.png)
Description sounds like it should be for FEN. Especially, since SCO has a second similar national spirit with a "Scottish" description

![Screenshot (1150)](https://user-images.githubusercontent.com/33550299/186018258-cdb1bbf5-75e7-40bf-89df-4fe9979e22e2.png)

![Screenshot (1149)](https://user-images.githubusercontent.com/33550299/186018415-578ec31a-0bfe-4d44-933c-dd57e69b77e6.png)

![Screenshot (1146)](https://user-images.githubusercontent.com/33550299/186018571-fb7d0db0-dd69-4b31-9887-9f557a6d6ed3.png)
With that cheerful description, the action text seems wrong

### Steps to reproduce / Cause of the issue

Play Scotland

### Expected behaviour

Different things

**Comment by runelead00** [comment]
All but first two issues fixed in dev build

**Comment by runelead00** [comment]
Fixed in Dev Build
