### ISSUE TITLE
Heydrich's Germany - Grammatical issues and typos

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#952]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1. ![Screenshot (458)](https://user-images.githubusercontent.com/98137316/186235716-88e6567f-4f65-45da-8d17-f8cfbf42b8e7.png)
"Our opposition nations" should be "opposing" or "enemy nations"
2. ![Screenshot (462)](https://user-images.githubusercontent.com/98137316/186235850-1b9f35f2-93ef-4e02-8bcd-7534dadf1dab.png)
"heartache" should be "headache", as "heartache" implies feelings of love.
3. ![Screenshot (465)](https://user-images.githubusercontent.com/98137316/186235954-98459130-c67a-4082-9a0d-6b9479eb1058.png)
"loathsome and degenerates of the liberal movement" should either remove "loathsome and" or become "the loathsome degenerates of the liberal movement
4. ![Screenshot (476)](https://user-images.githubusercontent.com/98137316/186236425-93541831-8df4-417a-84e5-87aa6642cb8c.png)
the dash between "death" and "it's" should be a comma
5. ![Screenshot (489)](https://user-images.githubusercontent.com/98137316/186236766-cc57011d-4ab5-4327-9125-8f140f1aab3a.png)
The first sentence of the third paragraph should be altered so as not to describe "economic policies" as "disposable", which doesn't make sense. 
6. ![Screenshot (493)](https://user-images.githubusercontent.com/98137316/186236969-7566d0e1-b60b-4a88-8091-f89f88d6fafa.png)
"Put down Daluege" should be "put Daluege down"
7. ![Screenshot (514)](https://user-images.githubusercontent.com/98137316/186237377-21adc89a-76d3-4e12-a802-ea198751cd8e.png)
"all non-Aryan" should be "all non-Aryans"

**Comment by runelead00** [comment]
Fixed in Dev Build
