### ISSUE TITLE
Heydrich's Germany - Rommel's retirement event should not happen

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#953]
### HOI4 version

1.11.10

### TNO version

Post April-Fools patch

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### Describe your suggestion

The event for Rommel's celebrated retirement should not happen under Heydrich.

### Justifications

Rommel is an ally of Spiedel, who is jailed until the start of the SS Civil War. Thus, Rommel himself would either be jailed, killed or have committed suicide after Heydrich's conquest of Germania.
![Screenshot (515)](https://user-images.githubusercontent.com/98137316/186239031-19731510-728b-42c9-a57d-b5c3dc49c163.png)

**Comment by runelead00** [comment]
Fixed in release build
