### ISSUE TITLE
WRRF- Factionalism in power struggle; rework suggestion

### ISSUE THREAD

**Issue by Acacias2001** [TNODevs/TNO-Bug-Tracker#955]
### HOI4 version

v1.11.13.886b Barbarossa

### TNO version

1.2.1c Toolbolx Theory: Project Ferus

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

I have two suggestions regarding the balance of the Zhukov-Tuckhachevsky power struggle: 
1. Change "WRS_decrease_factionalism_low = yes" to "WRS_decrease_factionalism_med = yes" in both lines 43 and 292 of the "TNO_WRS_decisions.txt" document. This change will increase the factionalism reduction from -3 to -6 in the appeasement decision, allowing for factionalism to be decreased enough to achive certain currently innaccesible outcomes described in the power struggle code.
2. Add  influence rewards to various foci in the chosen succesor focus trees  thad add up to a change of +10 influence
3. Remove or significantlly rework the 100 pp hostile action decision of the power struggle (ie operation firebird for tukh and evidence compilation for zhukov)

### Justifications

In the current version of TNO, during the Zhukov-Tukh power struggle, it is impossible for factionalism to be decreased below 55 while remaining ahead of your opponent influence. If the influence is not a concern, factionalism cannot be decreased below 31 (although this results in you losing the power struggle) . However numerous outcomes described in the power struggle code require a lower factionalism value. For example factionalism <39 is required to have a medium chance of peacefully integrating your rival, while factionalism <19 is required for a high chance. Furthermore a complete succes of the 100 pp hostile action decision requires <10 factionalism. 

As such the fact that factionalism cannot be reduced below 31 effectively removes part of the games content, and renders interaction with the factionalism system meaningless, as there is not much effective difference between having 55 factionalism and 100, meaning its best to ignore the factionalism system (and as such most of the power struggle decisions) completely.

Sugestion 1 increases the factionalism reduction from the appeasement decisions, allowing factionalism to be decreased more, allowing you to reach 16 factionalism by the end of the power struggle, increasing the chances of peacefull unification. Doing this however will still leave the chosen succesor 8 influence behind their opponent if they maximised influence gains, as such in sugestion 2 I suggest adding influence rewards throughout the focus tree to remove this deficit

Sugestion 3 deals with the 100 pp hostile action decision of the power struggle, which frankly is completely unbalanced. The rewards are comletely out of sync with both the pp cost of the decision and the needed investment in factionalism reduction: The decision if completely succesfull effectively gives +10 influence at the cost of +9 factionalism. However even with the implementation of my previous 2 sugestions. reducing factionalism by 12 costs -12 influence. And since factionalism needs to be decreased to  <10 for the decision to be fully succesfull, the "rewards" end up being a net loss. This is without taking into account the difficulties in reaching <10 factionalism, whcih ensures defeat inthe power struggle. 

### Additional information

I have made an google sheets document tracking the influence and factionalism values of the power struggle day by day and in total. I hope this helps ilustrate my point and helps in coming up with solutions. The document als includes a table at The bottom where modifier values can be changed to see how different values affect  the power struggle: https://docs.google.com/spreadsheets/d/1cMS1XIW4bWl3kayt8RVDCJ1HI1EVzUvT_IzpUnRk8FQ/edit?usp=sharing

**Comment by runelead00** [comment]
We don't plan on rework on the WRRF mechanic in the short term and plan to not devote any manpower to make it better in the meantime
