### ISSUE TITLE
All - Font Issue (VT323 related?)

### ISSUE THREAD

**Issue by JacobTheProgrammingNoob** [TNODevs/TNO-Bug-Tracker#957]
### Operating System

Windows 10

### HOI4 version

1.11.11

### TNO version

1.2.1a

### Do you have other mods in use?

TNO ECONOMIC CHEAT, FPS Map, Strategic View Adjustments (MP/A Variant), The New Order: VT323 Map and Cities Font, Player-lead Peace Conference

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe the bug

Whenever i zoom into a capital or city it just shows a white box and nothing else

### Steps to reproduce / Cause of the issue

1. Turn off the fonts mod
2. Turn it on again
3. Start up tno

### Expected behaviour

It would restart the fonts mod

### Screenshots

![tno bug](https://user-images.githubusercontent.com/75508365/187069593-5b926c5a-4987-49d3-a48a-6db8cf4ee2f5.jpeg)

**Comment by runelead00** [comment]
Likely related to font submod, hasn't seen occur to others since this was reporting
