### ISSUE TITLE
Heydrich focuses - Missing loc

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#958]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1.  
![Screenshot (871)](https://user-images.githubusercontent.com/98137316/187528288-c8ec0ed3-4d50-48e3-a2e9-e97a3c1865f2.png)
2.  
![Screenshot (872)](https://user-images.githubusercontent.com/98137316/187528364-e13f38c5-0f63-4153-b1d4-ffb6a0f9eb88.png)

**Comment by runelead00** [comment]
Fixed on Dev Build
