### ISSUE TITLE
Siberian free territories - Crash jul 1970

### ISSUE THREAD

**Issue by contlord** [TNODevs/TNO-Bug-Tracker#959]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9463138/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9463142/game.log)

### Describe the crash

The year is 1970 and i've conquered the far east siberia as the free territories of siberia. Siuda and Stepanov have just started competing for the power vacuum, and ive chosen to follow Siuda. Then the game crashes every time around the 10-12 of july at midnight.

Amazing mod, so far ive loved playing it.

### Steps to reproduce / Cause of the crash

It crashes at midnight every time around the 10-12th july 1970.

**Comment by runelead00** [comment]
Sounds like it could be a peacedeal error if it's happening at midnight, were there any wars near ending when  the crash occured?

**Comment by contlord** [comment]
I dont get any notification about any peacedeal.

**Comment by contlord** [comment]
The error log always comes up with:

[18:08:13][trigger.cpp:394]: common/scripted_triggers/TNO_Russia_scripted_triggers.txt:978: RWS: Invalid Scope, supported: State|Country|Character|Combatant|Ace|StrategicRegion|Operation, provided: None

a bunch of times with different numbers

**Comment by runelead00** [comment]
The error log is not helpful in this situation, that error is common and happens all the time without crashes, only a save is particularly useful when it comes to crashes
