### ISSUE TITLE
Siberian Free Territory - Unrelated war ending causing CTD, possibly related to Cameroon

### ISSUE THREAD

**Issue by deepfriedmax** [TNODevs/TNO-Bug-Tracker#960]
### Operating System

Windows 10

### HOI4 version

1.11.13.886b

### TNO version

1.2.1c

### Do you have other mods in use?

Colored Puppets

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

WTT, MTG, LAR, NSB

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9463591/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9463592/error.log)
[SIBERIA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9463603/SIBERIA.zip)

### Describe the crash

I'm playing the Siberian Free Territory, not at war, on March 1st, 1968. Approximately five days after save, an unspecified peace conference ends and the game crashes to desktop. The only wars going on that could end that quickly is the West African War, with Cameroon about to capitulate, Moskowiens Dissolution with Pleskau about to capitulate, and a war with Aktobe and Kostanay against a nearly capitulated Kyzylorda. Error logs seem to imply the problem is the West African Crisis not working.

### Steps to reproduce / Cause of the crash

Unsure how to reproduce, as the crash is unrelated to anything I'm doing. Logs imply the problem is an event not working properly after Cameroon capitulates and ends the war.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by runelead00** [comment]
Was related to Cameroon btw
