### ISSUE TITLE
Germany (Speer) - Zollverein Funding Broke

### ISSUE THREAD

**Issue by the-gemperor** [TNODevs/TNO-Bug-Tracker#963]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

TNO: Custom Country Paths, The Moe Order: Last Days of Anime, Toolpakt: Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[TNOTT Speer Ger 2.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9469178/TNOTT.Speer.Ger.2.zip)
[Uploading game.log…]()

### Describe the bug

Playing as Speerist Germany aiming for Go4 ending, After consolidating Europe and going through the economic tree, I noticed the Zollverein allocated budget had changed to 0.04B USD, which meant I could no longer do decisions. Ignored this for a long time as I forgot about it until the Oil Crisis, where the budget became nothing, thus preventing me from clicking any of the oil crisis Zollverein decisions that require budget.

### Steps to reproduce / Cause of the issue

1. Play as Greater German Reich
2. Go Speer
3. Win Bruderkrieg
4. Do initial post Civil War Tree and consolidate Europe
5. Do special Zollverein Missions as soon as they are able to.
6. Eventually, the money will run out and not get rejuvenated with the allocated budget decreasing
7. Get to Oil Crisis

### Expected behaviour

Zollverein Budget should be in the 1B range from previous games

### Screenshots

![20220901204305_1](https://user-images.githubusercontent.com/30204551/187897525-aa898121-7c05-40dd-af6e-75ca759ffe9f.jpg)

**Comment by runelead00** [comment]
Should be fixed in current release
