### ISSUE TITLE
English Government - "German Training" Cornwall event shouldn't give army xp

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#964]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### Describe your suggestion

As the title says

### Justifications

England is incapable of having army xp until the start of the ECW, therefore "gaining" thirty Army xp does nothing.

**Comment by runelead00** [comment]
Decision adjusted in Dev Build, xp effect removed and training PE effect increased to make up for it
