### ISSUE TITLE
Kingdom of England - Typos and loc issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#965]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1. 
![Screenshot (1031)](https://user-images.githubusercontent.com/98137316/188286261-c090279d-4a5d-4ebd-a441-a72b9403e770.png)
"defacto" should be "de facto"
2. 
![Screenshot (1032)](https://user-images.githubusercontent.com/98137316/188286270-0f295bfd-9f51-4f71-b8d2-7987e9d9372b.png)
missing text
3. 
![Screenshot (1033)](https://user-images.githubusercontent.com/98137316/188286281-35f6f868-809a-4a01-956d-a7ca0366c61d.png)
Victory event for National Front states that the Royal Party will become the governing party.

**Comment by runelead00** [comment]
Fixed in Dev Build
