### ISSUE TITLE
Chesterton's England - Typos and grammatical issues

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#966]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1. 
![Screenshot (1034)](https://user-images.githubusercontent.com/98137316/188286317-e73d779c-b8c4-46b0-9c3e-7783c85d3d46.png)
"who's single-focus" should be "whose single-minded focus". 
2. 
![Screenshot (1035)](https://user-images.githubusercontent.com/98137316/188286349-5454ba85-4348-42b1-a888-b83bb5b76a73.png)
either "Gallows grim" should be "Gallows Grim" or all words aside from the first in the first sentence shouldn't be capitalized. Additionally, "Workers" is needlessly capitalized.
3.  
![Screenshot (1036)](https://user-images.githubusercontent.com/98137316/188286366-327609b6-ad6e-454c-80b1-dabd0f89c1aa.png)
"ameatur" should be "amateur", and "premptorally" should be "preemptively" 
4.  
![Screenshot (1037)](https://user-images.githubusercontent.com/98137316/188286389-f97f302b-c666-4ad6-b460-d5d68b9077f7.png)
the dashes in the last sentence of the first paragraph should be removed, with the first replaced by nothing and the second replaced by a comma.
5. 
![Screenshot (1038)](https://user-images.githubusercontent.com/98137316/188286405-5ee86bb1-99a2-4fb1-a368-cb3f945ecaa8.png)
"plausible" makes no sense where it is. Maybe a misspelling of "pliable"?
6. 
![Screenshot (1039)](https://user-images.githubusercontent.com/98137316/188286418-02908e5b-93eb-4bac-a3ba-7963d834c0f2.png)
"Tirade" shouldn't be capitalized.

**Comment by runelead00** [comment]
Fixed in Dev Build
