### ISSUE TITLE
Union of South Africa - When Cape Town is captured by the germans its name gets changed to kapstadt but when South Africa recaptures it, its name stays as Kapstadt

### ISSUE THREAD

**Issue by MuzluKebap** [TNODevs/TNO-Bug-Tracker#967]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR

### List the loc issues below

![image](https://user-images.githubusercontent.com/112935488/188586763-f62f9043-fbcb-4460-87ce-8636fcee9672.png)

**Comment by runelead00** [comment]
Fixed in Dev Build (for every South Africa VP change as well)
