### ISSUE TITLE
Sverdlovsk - grammatical issue

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#968]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

2WRW, now called Brave New World

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1.  
![Screenshot (1040)](https://user-images.githubusercontent.com/98137316/188768086-810a3ddd-34f6-409a-8b74-bcbffa89471e.png)
""vegetable ration?" She thought." should either be "vegetable ration, she thought." or " 'vegetable ration?' she thought."

**Comment by Stormeagle449** [comment]
Fixed in UB.
