### ISSUE TITLE
USA - Replacement for Spiro Agnew resigning as Vice President

### ISSUE THREAD

**Issue by hmccabe96** [TNODevs/TNO-Bug-Tracker#970]
### HOI4 version

1.11.7

### TNO version

1.2.1b

### Which major expansions do you NOT have?

TFV, DOD, MTG, LAR, NSB

### Describe your suggestion

Spiro Agnew should go through the same scenario he suffered where he resigned due to the criminal investigation of him, where he resigns around 1973.

This would give Margaret Chase Smith (i.e. you) the opportunity to chose who to nominate who should be your vice president. 
You can choose a Dixiecrat, a Nationalist or a Progressive to be your Vice President. 

If your party has done the falling out scenario and rebuilt it by siding with one of the extremists factions (Marxist or Sovereign), this then opens them up to be a potential choice to pick for vice president.

Whichever one you pick increase the power that faction has in the NPP party.

### Justifications

This change I feel is necessary because I believe it goes with the theme of Margaret Chase Smith presidency which is of whether she should try to keep all sides happy or pick a side that she believes will benefit the party.

This scenario gives her the ability to give the minor/weaker side of the party a chance to get more of voice/power in the party, to balance both sides out so as to retain a large amount of potential voters, or give her the ability to solidify which side of the party she wants to see take control of the party and create enthusiasm among that voter base, to vote for them more.

**Comment by runelead00** [comment]
No changes or improvements are planned are will be implemented for MCS in the near future
