### ISSUE TITLE
SAF(and possible some tags) - No loc for 'econ_GDP_boost_once_flat'

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#976]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9575094/USA_play.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as any feature tag that has national focuses.
2. Saw a `econ_GDP_boost_once_flat` without added loc. 

### Expected behaviour

Forgot to added loc, I think

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190401567-0a73ec57-a593-49e0-b033-8e52ac4f1989.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Hopefully all are fixed in Dev Build
