### ISSUE TITLE
USA - The obfuscation on the any regions remains 0 despite the agency operation success 

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#978]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9580111/game.zip)

### Describe the bug

The explanation is stated in the title.

Even taking agency operation for obfuscation more than 3 times and successful operation, the obfuscation on the region remains 0 from the previous gameplay, not the current gameplay. However, the issue is still the same in this version. 

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Take the agency operation decision on the region for obfuscation with a 100% chance. 
3. The agency's operation is successful.  

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190544742-608a3044-8526-47e6-9a22-f407a0e1a8a0.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190544751-dc230b42-ad7b-4458-b5d9-a08f2a72dbd5.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Current Release
