### ISSUE TITLE
SCO - No loc for 'FEN_GF_Won_Ecw' from the 'Victorious at Last' focus

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#979]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9580731/USA_play.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. The death of Adolf Hitler and the German Civil War trigger.
2. English Civil War starts.
3. Have the English Civil War focus tree.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190557747-45ccff66-8434-4286-a8e3-5ac66ddfc3e3.png)

### Additional information

I don't have any additional information.

**Comment by Stormeagle449** [comment]
Fixed in UB.
