### ISSUE TITLE
SCO - Some political focuses are unlock due to the focuses required to have not English Civil War but the English Civil War is still ongoing

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#980]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9580838/game.zip)

Save game: [SCO.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9580840/SCO.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. English Civil War started.
2. Some political focuses are unlocked, however. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190560921-1f67b439-f007-4173-a151-d4b131f90fad.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190560927-15090a36-6c26-470f-8060-d0d485cb085e.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
