### ISSUE TITLE
NZL - AI can't able to do 'Production Units' mechanic

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#982]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9581207/USA_play.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as any tag except NZL.
2. After 1 or more than 1 year, see the NZL production factories

### Expected behaviour

Forgot to handle the Production Units mechanics for some AI tags.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190572204-852df16a-4481-4b24-b693-a033b4380d35.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190572213-aaac6133-db2a-4a94-95dd-9e3c004b67de.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/190572452-74c6eaa0-74a3-4611-9f03-baf7f3937e12.png)

### Additional information

I don't know about some non-feature tags that have the same issue with this, however.

**Comment by Stormeagle449** [comment]
In your case, NZ doesn't have PUs because it doesn't have enough power to use them. If PU>power supply, then excess PUs can't be used in production.
