### ISSUE TITLE
USA - There are no localize for economy effect in the Indian decisions' effect

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#983]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_india_decisions.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9583503/USA_india_decisions.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Complete all foreign national focuses for India.

### Expected behaviour

Forgot adding loc for economy effect, probably.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190627096-ea1399a4-0557-4f08-acba-379010698299.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190627105-8a995163-7cbf-41ef-8e96-dd074f8053ae.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
