### ISSUE TITLE
SCO - No localize for 'SCO_Paranoia_Removed' in 'An End of Paranoia' focus bypass

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#984]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [SCO.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9583787/SCO.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. HMMLR victory against English collaborators in the English Civil War.
2. Scotland completes the 'HMMLR victory' focus.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190634602-90ee3922-df37-4a37-b7d5-d25a80f42a42.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
