### ISSUE TITLE
NDL England Powell event broken

### ISSUE THREAD

**Issue by BCI1999** [TNODevs/TNO-Bug-Tracker#985]
### Operating System

Windows 10

### HOI4 version

1.11.13.886b

### TNO version

1.2.1c

### Do you have other mods in use?

Player led peace conferences, music mods

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When playing as England and having the NDL win the elections, the second or third focus (A Meeting with Powell), that should make Enoch Powell the security minister does not work.
The event fires as it should, but it only gets rid of the generic vacant seat and Powell does not become security minister.
Should be linked to event "FEN_NDL_political.3"

### Steps to reproduce / Cause of the issue

1. Play England as HMMLR and get the NDL in power
2. Complete the "A Meeting with Powell" focus

### Expected behaviour

Enoch Powell should become security minister

### Screenshots

![Screenshot1](https://user-images.githubusercontent.com/40671831/190653022-6017c143-f499-4f0e-ba45-4c975faa42f1.png)

![Screenshot2](https://user-images.githubusercontent.com/40671831/190653071-602a4401-9b31-4d08-b5f6-b89cc44123d5.png)

**Comment by BCI1999** [comment]
I looked around the files and found the possible problem.
In the event files for England, the event says to add idea "**FEN**_Enoch_Powell_sec" (line 11168 in TNO_England.txt).
Looking through the characters of England I found "**ENG**_Enoch_Powell_sec"  (line 1105 in Reich - England and Free England.txt).

**Comment by runelead00** [comment]
Fixed in Dev Build
