### ISSUE TITLE
USA - Odd effect in successful agency operation for 'Protect American Business Interest' in Central and South America

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#986]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9584065/game.zip)

### Describe the bug

The explanation is stated in the title.

The agency's operation success for 'Protect American Business Interest' in Central and South America event only effect is a tag, nothing else.

### Steps to reproduce / Cause of the issue

1. Select the 'Protect American Business Interest' decision and make chances of 100%.
2. The agency operation is successful.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190641598-0056dfab-51ed-437a-ae92-83bec410ead5.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190641611-0addeb41-0209-4e3e-a702-e54dbbbdb8b4.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
