### ISSUE TITLE
WIN - No unique icon for 'A More Perfect Union' national spirit

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#987]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9584785/USA_play.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Jamaican independence situation in WIN.
2. USA allows referendum for Jamaican independence.
3. The referendum votes to remain with the federation. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190659774-3346dcb3-3428-4abe-b8d7-a592d4558b6c.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
