### ISSUE TITLE
Paktkomission Kongo - Missing ministers

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#988]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1. 
![Screenshot (1061)](https://user-images.githubusercontent.com/98137316/190683762-de8fae00-4a1d-41da-a005-0825cc166081.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
