### ISSUE TITLE
Paktkomission Kongo - Retains RK natspirits

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#989]
### Operating System

Windows 10

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### Describe the bug

Paktkomission Kongo has at least some the natspirits of the three African RK's

### Steps to reproduce / Cause of the issue

1. Win Congo civil war for Afrikaner-Abwehrfront as Speer
2. Paktkomission Kongo created

### Expected behaviour

For the RK natspirits to not be there

### Screenshots

![Screenshot (1063)](https://user-images.githubusercontent.com/98137316/190684137-b5dbe9c2-8c7b-4b7b-bbfa-927504eeaf0f.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
