### ISSUE TITLE
Uganda under Mutesa II- Missing foreign minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#990]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1. 
![Screenshot (1064)](https://user-images.githubusercontent.com/98137316/190684348-6a4662b2-de0b-4fbf-8944-4e9d7b8a05ea.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
