### ISSUE TITLE
Republic of Rwanda - Minister issue

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#991]
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1. Gregoire Kayibanda is his own economy minister, but with a different portrait. 
![Screenshot (1065)](https://user-images.githubusercontent.com/98137316/190684633-199e4e11-41f9-4c98-a545-5da2f40ce540.png)

**Comment by runelead00** [comment]
Fixed in Dev Build
