### ISSUE TITLE
IBR - AI can't able to send volunteers to SAF despite has a available to send volunteers to SAF in 'Military Advisors' idea

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#993]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9590952/game.zip)

Save game: [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9590946/USA_play.zip)

### Describe the bug

However, AI IBR can somehow send volunteers to SAF and I think it's AI RNG or something.

### Steps to reproduce / Cause of the issue

1. South Africa War begins.
2. IBR supports SAF.

### Expected behaviour

Probably AI IBR can't send volunteers to SAF due to AI IBR's focus on Algeria War.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190841094-9a49d656-6cab-418f-b977-45efbf78ae42.png)

### Additional information

I don't have any additional information.

**Comment by LabAviator** [comment]
Was looking to create a bug report for pretty much the same issue, but of the US.
It seems like the issue isn't country specific, but lies with the military advisor spirit some countries can get.
In my case as the US I've done a decision which should allow me to send +6 volunteers, but I still can only send the base one volunteer.

![image](https://user-images.githubusercontent.com/31162832/208130137-853ebfb6-8d1d-4489-aaed-41bf9b1995fc.png)
![image](https://user-images.githubusercontent.com/31162832/208130157-6867f545-a03d-4ccd-b4a6-66ace50ed51d.png)

**Comment by Victorrah** [comment]
idk if you figured it our already but a simple fix is clicking on a province in south africa, then clicking on the flag in the province gui and then sending volunteers from there
