### ISSUE TITLE
ILG - Small flag icon in the info state uses the in-real-life Algeria flag instead of current Italian Algeria flag

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#994]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [ITA.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591029/ITA.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as any tag.
2. View the state of ILG. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190842465-c94a0fcd-ce14-4bff-9583-bb9b18211afa.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
