### ISSUE TITLE
USA - After taking the 'Pretoria', 'The Battle of Johanasburg' event triggers despite Johannesburg is controlled by the enemy

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#995]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591174/game.zip)

Save game: [autosave.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591176/autosave.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. South Africa War triggers.
3. Helping SAF.
4. Occupy the 'Pretoria-Witwatersrand-Vaal' through 'Pretoria'.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190845360-97e4af4e-8fa1-4303-aecf-1e71eebc9fc1.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Unfixable, limitation with how Paradox evaluates control, can't go down to the victory point/province  level with control. I've also seen similar issues with the Port of Magadan
