### ISSUE TITLE
KAL - No unique GFX focus icon for 'No More Deluded By Reaction' and no loc for 'kostin.20.t' and 'kostin.21.t' events

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#996]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game; [USA_play.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591223/USA_play.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. NOV forms Central Siberian Federation.
2. KAL revolts. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190846686-0c23e036-8b78-4898-ba99-af16fd94223c.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190846690-db08373c-49eb-4572-b751-19df37323943.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Icon fixed in Dev Build
