### ISSUE TITLE
USA - Some issues for SAW Humphrey's Way focuses' effect

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#997]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_NPP.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591376/USA_NPP.zip)

### Describe the bug

- No space or line break between 'Africa.' and 'Max' in the 'Africanization' focus effect.
- No line break with 'Rally american troops to garrison the cities.' in the 'Fortify the Cities' focus effect. Also, the 'american' should be 'American' because of demonym should start with the capital letter. 
- No space or line break between 'Africa.' and 'Max', and no line break with gaining political power in the 'Whip Their Commanders' focus effect. 
- No space or line break between 'Africa.' and 'Max', and no line break with gaining political power in the 'Initiate the Withdrawal' focus effect.American

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Vetoed the Civil Rights as Nixon.
3. Choosing election for NPP.
4. RFK is elected as NPP-P president. 

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190851015-88923cc3-df7f-40bf-911d-5f6a0b0673b5.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190851017-2653049d-8cee-4257-9def-3784210affe3.png)

![Untitled_3](https://user-images.githubusercontent.com/71108541/190851018-a2e21bf6-4efa-4362-817d-8be7cf2629c1.png)

![Untitled_4](https://user-images.githubusercontent.com/71108541/190851019-7b54d603-94f3-4564-88ca-388ae227728b.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
