### ISSUE TITLE
USA/SAF - No unique GFX icon for 'A Fluid War' national spirit

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#998]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Save game: [USA_a_fluid_war_idea.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591499/USA_a_fluid_war_idea.zip)

### Describe the GFX issue

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect NPP.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190853477-b416a43a-6f56-484a-b863-fdb99efe1516.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190853481-c3582696-de55-4a38-a28e-caae55e6b264.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Fixed in Dev Build
