### ISSUE TITLE
USA - There are no decisions about the 'subsidize American industry allies' after completing the 'Pump Up the War Industry' focus

### ISSUE THREAD

**Issue by Kyklosian** [TNODevs/TNO-Bug-Tracker#999]
### Operating System

Windows 10 Pro

### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

Log file: [game.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591658/game.zip)

Save game: [USA_prump_up_the_war_industry.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9591660/USA_prump_up_the_war_industry.zip)

### Describe the bug

The explanation is stated in the title.

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect NPP.
3. Completes the 'Pump Up the War Industry' focus.

### Expected behaviour

I don't know what causes this.

### Screenshots

![Untitled_1](https://user-images.githubusercontent.com/71108541/190856868-b3a9084e-3af7-41ee-b59e-cebadec4d24f.png)

![Untitled_2](https://user-images.githubusercontent.com/71108541/190861402-ae4cade1-c012-4d0f-9f43-8aedd948e886.png)

### Additional information

I don't have any additional information.

**Comment by runelead00** [comment]
Not longer an issue on UB
